### ISSUE TITLE
Server rack snapping

### ISSUE THREAD

**Issue by SavageAUS** [jgraph/drawio#1000]
I am creating a diagram of a server rack and trying to put an item at the bottom of the rack that does not take the entire width. How can i make it so it doesn't snap to the width and height?

**Comment by mararad** [comment]
My suggestion would be to remove "childLayout=rack;" from the code of the rack object you are using
i.e select rack cabinet, click Ctrl+e and remove "childLayout=rack;"
​
Note: this should help but test if everything else is working well cause this code removal can have ​some consequences.

![child](https://user-images.githubusercontent.com/44292306/85531874-70b69500-b60f-11ea-9cc9-92637dad7c44.PNG)
