### ISSUE TITLE
[IBM VPC] Icons are missing when using Firefox

### ISSUE THREAD

**Issue by jaywarfield** [jgraph/drawio#1003]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Firefox started having a problem a couple of months ago.  There should be a square icon in upper left corner of IBM / Boxes but instead the icon is now empty.  Safari and desktop draw.io work properly so the problem appears to be isolated to just Firefox.  

[FirefoxDrawioIssue.zip](https://github.com/jgraph/drawio/files/4833122/FirefoxDrawioIssue.zip)

**To Reproduce**
1. In FirefoxDrawioIssue.zip open ibm_vpc_sample.drawio in online draw.io on Firefox.
2. Note that the boxes titled IBM Cloud, Region, VPC, Zone, and Subnet are missing the square icon in upper left corner to the left of the box name.

**Expected behavior**
In FirefoxDrawioIssue.zip open IBMVPCSampleScreenshotGoodSafari.PNG.
Note that the boxes titled IBM Cloud, Region, VPC, Zone, and Subnet have a square icon in upper left corner to the left of the box name.

**Screenshots**
In FirefoxDrawIssue.zip open IBMVPCSampleScreenshotBadFirefox.PNG.
Note that the boxes titled IBM Cloud, Region, VPC, Zone, and Subnet are missing the square icon in upper left corner to the left of the box name.

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 13.3.4 in both Firefox and Safari

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Firefox 68.9.0esr, Safari 13.1.1

**Smartphone (please complete the following information):**
 - Device: N/A
 
**Additional context**

**Comment by davidjgraph** [comment]
Does it happen on latest FF?

**Comment by jaywarfield** [comment]
FF was not keeping me up-to-date like I thought, but this issue doesn't happen on FF 77.0.1.  Thanks!

**Comment by davidjgraph** [comment]
Yeah, FF 68 was quite flakely on a number of rendering issues.
