### ISSUE TITLE
Autocomplete on metadata fields

### ISSUE THREAD

**Issue by jagjordi** [jgraph/drawio#1004]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Some times the metadata fields of a shape are containing strings that are commonly used and repeated. It would be very nice that when typing text in the metadata fields some autocomplete options, based on available text in other metadata fields on the drawing, showed up to be selected.

**Describe the solution you'd like**
When typing text ona metadata field, autocomplete suggestions based on the other data fields in the drawing show up

**Describe alternatives you've considered**
Copy-Paste 😅

**Comment by jagjordi** [comment]
Is it very hard to implement?

**Comment by davidjgraph** [comment]
https://github.com/jgraph/drawio/wiki/Stale-bot-FAQ
