### ISSUE TITLE
I Can't See my partner mouse indicator (cursor). 

### ISSUE THREAD

**Issue by MEA20** [jgraph/drawio#1005]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Description of the bug**

**Hi, I found that I can't see my partner cursor when we are using the same file in Draw.io. Also, when he edits something it takes more than 10 seconds to make a change in the file.

I hope you can do something about this problem thanks.**

**Comment by mararad** [comment]
Hi, 

when it comes to a real-time collaboration, another mouse indicator can't be seen, only the editing result. 
I assume that a diagram is complex or/and contains large images. You can try editing in other browsers and Incognito mode. 
Is a diagram saved in Google Drive?

Regards,

**Comment by davidjgraph** [comment]
Has the update time improved?

**Comment by davidjgraph** [comment]
Has the update time improved?

**Comment by MEA20** [comment]
Sorry about my late replay, it still has the issue I can't see my partner cursor and there is a delay when he makes changes. I went to other flowcharts website with the same browser (google chrome) and there is no lag plus I can see my friend cursor moving around, I guess the problem isn't associated with the browser!
