### ISSUE TITLE
Page could not be loaded. Please try refreshing.

### ISSUE THREAD

**Issue by pohutukawa** [jgraph/drawio#1007]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When trying to load draw.io from an Atlassian Confluence macro, it will not load. The behaviour is the showing of a page indicating "Page could not be loaded. Please try refreshing.". It has been verified on Firefox, Chromium and Chrome browsers on the current Ubuntu focal 20.04 (64bit).

It is easiest to verify by browsing to https://confluence.draw.io

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://confluence.draw.io
2. See error "Page could not be loaded. Please try refreshing."

**Expected behaviour**
Being able to use draw.io just as I'm getting it when using https://app.diagrams.net/

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**
As it doesn't load, I cannot tell. However I have downloaded the `app.min.js` file separately and hashed it:

```
$ sha256sum app.min.js
ea7d070211d7da2de47ddd9ce31f127814490facae4e6a0e6fbf6bdbd4348219  app.min.js
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 focal LTS, 64 bit
 - Browser(s): Firefox 77.0.1+build1-0ubuntu0.20.04.1, Chromium 83.0.4103.106, Chrome 83.0.4103.116-1

**Additional context**
It seems to work on Opera (Ubuntu Linux) and Safari (a colleague's Apple, don't know the version)

**Comment by davidjgraph** [comment]
If you cannot browser confluence.draw.io there's most likely something in your network blocking that domain. I would start by asking your network IT admin if there's a deny/allow list in the network.

**Comment by pohutukawa** [comment]
Not really feasible, as (A) draw.io loads by itself (outside the scope of Confluence), and (B) it works within the same network for some people with different browsers (e.g. Safari, Opera) as explained above. It also used to work previously, and the issue has just come up. Checking with our admins, we don't have any network blocking in place here for such things.

So I'd say the network blocking hypothesis is unlikely.

**Comment by davidjgraph** [comment]
I still think it's a corrupt file cached somewhere, even if it works for some users. We flushed out the CDN is case one of the Cloudflare nodes is the root of that file. Has it improved?

**Comment by pohutukawa** [comment]
Yes, I have verified it, and it works now. Must have been a CDN problem.
