### ISSUE TITLE
Separate Scratchpad for edited file

### ISSUE THREAD

**Issue by vintprox** [jgraph/drawio#1008]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
It makes that hard to be in line with graph contributors/coworkers when everybody has to reimport Scratchpad in drawio just to have the latest templates. To have personal Scratchpad intact, while importing another, I also have to export it and reimport on demand, which is time consuming. That also impacts my colleagues.

**Describe the solution you'd like**
Separate Scratchpad embedded into file - because then we don't have to reimport personal Scratchpad or make everybody ever touch "Edit" and "Import" buttons in that section, while collaborating on several diagrams with different shapes.

**Describe alternatives you've considered**
Of course, one can export desired Scratchpad with a lots of shapes and make everybody in team to import it, but one may have personal Scratchpad that was not saved or no time for importing utility scratchpads at all (considering this pencil icon in "Scratchpad" section is very small to notice for novice, which is different story about UI/UX).

**Additional context**
There is kind of similar issue #5, but contents unlike title don't have bearing on actually embedding Scratchpad into file.

**Comment by davidjgraph** [comment]
And using libraries doesn't solve this?
