### ISSUE TITLE
Portrait/Landscape toggle is backwards for some paper sizes

### ISSUE THREAD

**Issue by element15** [jgraph/drawio#1009]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
For the paper sizes `16:9`, `16:10`, and `4:3`, the canvas appears to be in a landscape orientation when `Portrait` is selected and vice versa.

**To Reproduce**
1. Create a new blank canvas
2. Change the paper size to `16:9` in the `Diagram` menu
3. Select the `Landscape` orientation
4. Notice that the canvas now appears to be in a portrait orientation

**Expected behavior**
The canvas is expected to be wider than it is tall when in a landscape orientation, and vice versa for a portrait orientation. This behavior appears to be working properly for all paper sizes besides `16:9`, `16:10`, and `4:3`.

**Screenshots**
![Screen Shot 2020-06-29 at 09 57 09](https://user-images.githubusercontent.com/10162432/86021924-4be76680-b9ef-11ea-8b68-a33373597070.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
- 13.3.1 for macOS (installed via `brew cask install drawio`)
- 13.3.5 web

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Browser: Firefox
 - Version: 73.0.1

**Smartphone (please complete the following information):**
 Not tested.

**Additional context**
None.

**Comment by mararad** [comment]
Reproduced in Win 10 and Chrome Version 83.0.4103.116 and Chrome Incognito and in FF version 77.0.1 (64-bit)

**Comment by ezplanet** [comment]
I confirm this bug for A4 format

**Comment by alderg** [comment]
The system extends the drawing area and adds pages as needed (separated by a dashed line). However, the individual pages are of the given format and orientation. This is a feature, not a bug.
