### ISSUE TITLE
Azure cloud shape: `blog storage` typo?

### ISSUE THREAD

**Issue by thomas-riccardi** [jgraph/drawio#1012]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
In Azure cloud shape, there is a `blog storage` in the `storage service` section. I believe this is a typo for `blob storage`.
https://github.com/jgraph/drawio/blob/4b771beabbd5a3c4cbc6906a103621cc35d75c40/src/main/webapp/js/diagramly/sidebar/Sidebar-MSCAE.js#L1393-L1394

However, there is also a `blob storage` in the `databases service` section: 
https://github.com/jgraph/drawio/blob/4b771beabbd5a3c4cbc6906a103621cc35d75c40/src/main/webapp/js/diagramly/sidebar/Sidebar-MSCAE.js#L792-L793
(this last one seems to be the more standard icon)

**Expected behavior**
Maybe rename blog storage into blob storage? maybe keep both blob storages?

**draw.io version (In the Help->About menu of the draw.io editor):**

- 13.3.5

**Desktop (please complete the following information):**
 - OS: ubuntu snap

**Comment by egrimate** [comment]
Thanks for the report! This will be fixed in the next release.
