### ISSUE TITLE
Unifi sketches for server rack

### ISSUE THREAD

**Issue by SavageAUS** [jgraph/drawio#1013]
Is there anything in the works to add unifi device icons/sketches?
I am trying to design a server rack with unifi devices.

**Comment by mararad** [comment]
Hi,

at the moment no, but there is a Trello feature request card for this you can vote for and track the progress here: https://trello.com/c/rpjnipFh/181-stencils-for-mikrotick-unifi-equipment

**Comment by davidjgraph** [comment]
We can move the issue here to track it.
