### ISSUE TITLE
Group shapes in CSV import

### ISSUE THREAD

**Issue by pstefanov** [jgraph/drawio#1015]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I would like to generate containers and shapes in them e.g. a rectangle that contains a shape and other small shapes, which are grouped together and position within each other e.g. a Cisco router shape inside a rectangle with these ractangles representing various routing tables on the device. I would like to be able to connect from these routing tables to other such shapes of other Cisco routers. 

![draw-io-screenshot](https://user-images.githubusercontent.com/5366153/86443466-97f81b00-bd0f-11ea-89dd-05084827917a.JPG)

**Describe the solution you'd like**
Add a feature to group several shapes together using the CSV import function and the ability to specify how they are positioned in relation to each other.

**Describe alternatives you've considered**
No alternative exists at this point.

**Additional context**

**Comment by peter-niesel** [comment]
+1
