### ISSUE TITLE
Lucid layer import issues

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#1018]
[Support Process - nSv_ALv.vazW.json.zip](https://github.com/jgraph/drawio/files/4863530/Support.Process.-.nSv_ALv.vazW.json.zip)

**Comment by ashrafteleb** [comment]
Fixed

**Comment by alderg** [comment]
Test with page 1 in this file and that didn't work https://app.lucidchart.com/documents/edit/dad05622-5f2e-4876-9589-b9668ad014f0/0_0

**Comment by ashrafteleb** [comment]
Fixed. The copy/paste format was not covered
