### ISSUE TITLE
The option of "Autosave" is always on with diagrams saved to the local device on macOS/Chrome.

### ISSUE THREAD

**Issue by zhanbei** [jgraph/drawio#1019]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The preference of "Autosave" is not working as expected(it does work like it is ticked always):
every time I make a tiny change of my diagram, *drawio* tries to save the file to my device, and I denied the access to edit my local file(which will be synchronized once being modified). 

**To Reproduce**
1. Go to https://app.diagrams.net/
2. Create a diagram and choose ("Device") being asked "Save diagrams to...", or open a local diagram from PC file system.
3. "Finder" is called by chrome to choose a local file to edit on, ref([FileSystem](https://developer.mozilla.org/en-US/docs/Web/API/FileSystem)).
4. Edit the diagram just created and will see the "drawio" is auto-saving the diagram.
5. Choose ("Cancel") for the confirm alert 【Save changes to **Hello-World.drawio**?(app.diagrams.net will be able to edit **Hello-World.drawio** until you close all tabs for this site)】.
6. Will fall back to step 4, and the alerts in step 5 keep interrupting the normal workflow with the diagram.

**Expected behavior**
When the ("Autosave") option is disabled, "drawio" should not save the diagram automatically until I clicked the ("Unsaved changes. Click here to save.") button.

**Screenshots**
<img width="851" alt="Screen Shot 2020-07-04 at 10 41 08 PM" src="https://user-images.githubusercontent.com/17806342/86514929-18219c00-be48-11ea-8816-b8874ef3e1bb.png">
<img width="441" alt="Screen Shot 2020-07-04 at 10 41 23 PM" src="https://user-images.githubusercontent.com/17806342/86514960-48693a80-be48-11ea-9a7c-bf8f400bd63e.png">

**draw.io version:**
- draw.io version 13.3.8

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Version: 83.0.4103.116

**Comment by zhanbei** [comment]
Well, I disabled the Chrome FileSystem API( ref chrome://flags/#native-file-system-api ), and the app.diagrams.net just crashed.

**Comment by alderg** [comment]
Ignored autosave is fixed in 13.3.9. We'll see if we can do something about the crash when the Chrome FileSystem API is disabled in the next release. Thanks for the report!
