### ISSUE TITLE
Visio Stencil Import issues

### ISSUE THREAD

**Issue by siddharthsharma** [jgraph/drawio#1020]
Thanks for getting issues I reported earlier with respect to importing stencils fixed and releasing the changes. We have been doing more testing and have found some more issues with respect to importing visio stencils. Please find the file and the issues identified below: 

**[VisioStencils.zip](https://github.com/jgraph/drawio/files/4875155/VisioStencils.zip)**
The shapes in the stencils are changing alignment, text changed alignment or spacing, line jumps disappeared, some shapes became inverted, line thicknesses changed, etc. 

If I need to report these details elsewhere or open another issue for the same please let me know.

Thanks for your help.

**Comment by mararad** [comment]
Reproduced in diagrams.net online 13.3.7 and desktop 13.0.3. Win 10 and Chrome Version 83.0.4103.116 (Official Build) (64-bit) and Chrome Incognito. 

Some of the differences shown in PNGs attached below
 
![vssx](https://user-images.githubusercontent.com/44292306/86582342-c846f000-bf81-11ea-983d-d2cd9068dd77.PNG)
![vssx](https://user-images.githubusercontent.com/44292306/86582478-f75d6180-bf81-11ea-8e00-4180846781c7.PNG)

**Comment by cha0s4u** [comment]
Hi Team! We need some priority fixes done on this.  Is there some commercial product of this tool, that we can help support this open source project as well?

**Comment by davidjgraph** [comment]
No, this is an open source project, either you implement the fix yourself or wait like everyone else.
