### ISSUE TITLE
Cannot click "authorize" Google Drive in macOS Safari browser 

### ISSUE THREAD

**Issue by nitramwin** [jgraph/drawio#1021]
When I go to my Google Drive, click on an existing DrawIO project and the redirect happens, a loading screen appears. After a short while, a pop-up box appears such that I can authorize DrawIO to access my Google Drive. 

Although it was previously possible to select this blue button, it currently is not possible to click it. As such, I am relegated to using another browser when Safari used to work in the past.  

**Expected behavior**
Be able to click 'authorize' Google Drive integration in the MacOS Safari app. 

**Additional info**
I am using MacOS 10.15.5 with Safari 13.1.1 on a newer MacBook Air laptop. 
Also, Safari used to work about 2-3 days ago so something has changed.

**Comment by mararad** [comment]
Hi,

If you clear cache and temporarily disable all browser extension in Safari, does it help?

**Comment by nitramwin** [comment]
It did not.

**Comment by ashrafteleb** [comment]
Please ensure you allow pop-up windows. I tried and Safari currently blocks the pop-up window when Authorize is clicked.  Does this help?

**Comment by nitramwin** [comment]
You are right and I can confirm that this works. Since I didn’t change this setting myself, did this change occur from a software update or other? I cannot understand it… Kind regards

**Comment by davidjgraph** [comment]
Safari did change the defaults at some point.
