### ISSUE TITLE
Lost math mode due to formatting can't be reapplied 

### ISSUE THREAD

**Issue by llvs** [jgraph/drawio#1024]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
If for some reason formatting is applied to math-mode-text (or pasted), there seems to be no simple way to get math mode back. Only via workaround.

**To Reproduce**
1. Enable math typesetting in menu
2. Create normal box
3. Double-click box to change its text
4. Enter math, e.g., $$F_x$$
5. Select only the 'x' and apply a different size
6. Math mode is gone and except for typing everything anew I fail to see where to restore it, i.e., remove all the formatting of text in between the $$ delimiters.
7. Workaround: Math mode can be restored by selecting all text and apply all formatting again.

Alternative (pasting):
1. Enable math typesetting in menu
2. Create two normal boxes
3. Double-click first box to change its text
4. Enter math, e.g., $$F_x$$
5. Double-click second box to change its text
6. Enter math, e.g., $$G_x$$
7. Select one of the boxes and increase its font size
8. Copy all or parts of the math expression within the $$ delimiters
9. Paste it to other box
10. Math mode is gone.  This happens whenever the source formatting differs in whatever aspect from the destination. 
11. Workaround: Math mode can be restored by selecting all text and apply all formatting again.

**Expected behavior**
Different source and destination formatting should be irrelevant when pasting math code. Whenever there is math code, mixed formatting should be irrelevant and it should be pasted in the formatting of the destination. One usually wants to save typing and reuse complicated LaTeX math expressions with lots of braces. This effectively kills copy&paste.
It would be handy to have a button like "unify math code formatting" which resets the math in between the $$ delimiters (if automatic pasting in the destination format is not possible).

The "clear all formatting" button is only partly helpful: I have to press it more than once to remove also the formatting of pasted sections and usually I want to retain the destination formatting when I paste math code.

**Screenshots**

- draw.io version 1.3.3.9

**Desktop (please complete the following information):**
 - OS: Win 8.1
 - Browser Vivaldi 3.2.1964.3 (Chromium 84)

![mathbug1-crop](https://user-images.githubusercontent.com/26276591/86761892-9350a100-c046-11ea-93c3-f754ad87e926.png)

![mathbug2-text-crop](https://user-images.githubusercontent.com/26276591/86761933-99468200-c046-11ea-9067-b3087a3ba72f.png)

**Comment by llvs** [comment]
I don't understand why this issue is labeled as "wontfix". The issue still persists in version 1.3.9.9 and there is still no (obvious) solution how to deal with losing math mode due to formatting changes – intentional or unintentional. Please elaborate what currently a solution might be to the problem and why this is intended behaviour which should not be fixed.

**Comment by davidjgraph** [comment]
https://github.com/jgraph/drawio/wiki/Stale-bot-FAQ

**Comment by llvs** [comment]
OK thank you. That explains at least the "wontfix" tag.
However, the issue still persists in the current version.

**Comment by llvs** [comment]
I tried the current online version 14.7.7 and now there exists a checkbox saying "unformatted text". If this is activated beforehand, the pasting works and the size changes for the whole box are kept. That is a bit clumsy but it works and if one knows that, one can finally paste math formulae between boxes.
Thank you developers! Issue can then be closed as far as I am concerned.
