### ISSUE TITLE
Mathematical typesetting is off by default for new page, even when math was used before.

### ISSUE THREAD

**Issue by llvs** [jgraph/drawio#1027]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When mathematical typesetting is enabled, it should also be enabled for new pages. It is off by default.

**To Reproduce**
1. Insert stuff and enable math mode (mathematical typesetting).
2. Click on + symbol to insert a new page.
3. Mathematical typesetting is off for that new page.

**Expected behavior**
It is counter-intuitive to have this setting off when it was enabled on the previous page. Copy&paste is a common action between pages and pasting math content that does not render (at first) is confusing. I would also have expected for mathematical typesetting to be a document-wide setting. It is good that it is not, this allows for finer granularity. But please make the new page have the mathematical setting of the active page when clicking on the + sign. Or ask the user like: "You have used mathematical typesetting in this document, should it be also enabled on the new page?"

**Screenshots**
Not applicable. Should be comprehensible that way, too.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 1.3.3.9, called via [https://app.diagrams.net/?math-font=STIX-Web](https://app.diagrams.net/?math-font=STIX-Web)

**Desktop (please complete the following information):**
 - OS: Win 8.1 64bit
 - Browser: Vivaldi 3.2.1964.3 (Chromium 84)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
