### ISSUE TITLE
Checksum/GPG signature for draw.war files

### ISSUE THREAD

**Issue by ghost** [jgraph/drawio#1028]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Currenctly there's no way to verify the integrity of the downloaded draw.war files.
E.g. on https://github.com/jgraph/drawio/releases/tag/v13.4.0

**Describe the solution you'd like**
Could you please add a checksum file and or GPG sign the file (not sure it that is possible with .war files).
Many thanks.

**Comment by davidjgraph** [comment]
Out of date since we don't develop the java back-end any longer.
