### ISSUE TITLE
Connection and arrows misbehave in tight spaces

### ISSUE THREAD

**Issue by muhammad-tayyab** [jgraph/drawio#1029]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Small connections between (close) objects tend to change their shape and orientation on various zoom levels. It can also happen when an object is moved slightly on either axis, especially when constraints are applied on a connection. This is not an issue in small diagrams, but for large diagrams, it needs a lot of effort to check and correct each connection.

**To Reproduce**

1. Create two objects with relatively close distance
2. Connect them with any arrow (arrow size is set accordingly)
3. Change zoom level or try to export diagram with different zoom levels
    OR
    Slightly move any object (using arrow keys)

**Expected behavior**
Keep the shape and orientation of connections and change connection length only.

**Screenshots**
![problem](https://user-images.githubusercontent.com/11335086/86911502-05f87400-c14e-11ea-858e-56c528766d20.JPG)
![problem1](https://user-images.githubusercontent.com/11335086/86911524-0f81dc00-c14e-11ea-850f-4b790fd24acf.JPG)

**draw.io version:**
- 13.3.9

**Desktop:**
 - OS: Windows 8, Windows 10
 - Browser Chrome
 - Version Various versions

**Additional context**

**Comment by mararad** [comment]
I tried to reproduce this but I couldn't. I use:
* Chrome Version 83.0.4103.116 (Official Build) (64-bit)
* Win 10 Pro
* diagrams.net online 13.4.2

If you do the hard reload and try again, do you see the same issue? (after a reload, you should be able to see the latest online version 13.4.2)

If yes, is it possible to attach a saved diagram file so I could test it directly or create a test diagram showing described behaviour?
Also, tell me how you performed zooming - is it via mouse wheel or you just clicked Zoom in/out in Toolbar?

Thanks,
