### ISSUE TITLE
Layer Panel Keyboard Shortcut No Longer Working

### ISSUE THREAD

**Issue by baynezy** [jgraph/drawio#1030]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The keyboard shortcut Ctrl+Shift+L to open/close the Layers view does not work for me anymore. I usually use the Minimal theme which is my preference, but this heavily relies on knowing the keyboard short cuts. I have been unable to open the Layers panel via the keyboard shortcut recently, and so I have had to move back to the Kennedy Theme so I get the dropdowns again.

**To Reproduce**
1. Go to https://app.diagrams.net/
2. Create a new blank diagram
3. Attempt to open the Layers panel by using Ctrl+Shift+L
4. It will not open

**Expected behavior**
I would expect that on pressing Ctrl+Shift+L the layers panel would toggle between its two possible states open or close.

**Screenshots**
n/a

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.3.9

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional 1903
 - Browser: chrome
 - Version: 83.0.4103.116 (Official Build) (64-bit)

**Additional context**

**Comment by mararad** [comment]
Hi, 

I tested Minimal theme with the shortcut and all is working well at my place (layer panel is shown/hidden). 
I use Chrome Version 83.0.4103.116 (Official Build) (64-bit), Win 10 Pro and diagrams.net online but the latest version 13.4.1.

So my suggestions would be to:
* test if it is working in Incognito mode (if yes, clear browser cache and temporarily disable all browser extensions)
* if this doesn't help, do the hard reload, check if you have 13.4.1 under Help and try again

Does this help?

Regards,

**Comment by baynezy** [comment]
@mararad - thanks for your help. It is definitely a problem my end. I tried incognito and the issue was still there. However, if I openned it as a Guest in Chrome then it does work. I am going to disable an extension one at a time and see what has knackered it.

**Comment by baynezy** [comment]
@mararad - it turns out that it is the Bitwarden Chrome extension. It was hijacking the Ctrl+Shift+L shortcut https://bitwarden.com/help/article/auto-fill-browser/

Sorry for wasting your time.

**Comment by mararad** [comment]
@baynezy No worries :) It is great all is working well now.
