### ISSUE TITLE
Universal Process Notation (UPN) Shapes

### ISSUE THREAD

**Issue by martyychang** [jgraph/drawio#1031]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I prefer using Universal Process Notation (UPN) to draw diagrams, as it is both simple to create and simple to read. No training required. All UPN requires is [a simple box][1] that allows for one or more lines of text to be added below the box.

**Describe the solution you'd like**
I want a shape that can be added to a diagram that starts off like a normal process box. Then, I want to be able to add one or more rectangular labels below the box to hold text. When I move the box, the box and the labels should travel together. Arrows should attach to the collective boundary around both the box and its labels.

**Describe alternatives you've considered**
I've made do with creating just a process box and throwing text underneath it. While this works, it's cumbersome to move the box and the associated text, and arrow connectors at the bottom of the box look strange.

**Additional context**
See https://elements.cloud/ for an example of how UPN can look and function.

[1]: https://www.google.com/url?q=https%3A%2F%2Fsupport.elements.cloud%2Fen%2Farticles%2F982655-process-mapping-with-elements-methodology-shapes-and-hierarchy&sa=D&sntz=1&usg=AFQjCNHEjjQ7pRpiY9VK8vvhuHwCVtOY3w

**Comment by nikmanzotti** [comment]
UPN is made to be simple: while basic shapes and grouping in draw.io are enough for basic diagramming, I think that a dedicated UPN activity box supporting multiple resources, numbering and drill-down (top left corner), attachments (top right corner) should be quite easy to implement using existing assets and features (e.g. list, manual link to pages, ...) and game-changing for small businesses needing to make several diagrams (tool made specifically for UPN like Elements and Tibco Nimbus are quite costly).

Further resources on UPN:
* https://elements.cloud/2016/06/01/upn/
* https://www.salesforceben.com/introduction-to-universal-process-notation-upn-for-salesforce-processes-mapping/
* https://www.tibco.com/resources/whitepaper/universal-process-notation-simple-solution-complex-process-diagrams

**Comment by benji1304** [comment]
Was there any movement on this request? I'd love to be able to write UPN in draw.io

**Comment by davidjgraph** [comment]
Nothing has been done. If someone can point to an icon set with a suitable license that we can use, that greatly increases the chances of implmentation.

**Comment by nikmanzotti** [comment]
@davidjgraph unlike BPMN and other notations commonly used for Business Process Analysis, UPN is based on simplicity.

See the following quote from the [document considered to be the UPN "Standard"](https://www.tibco.com/sites/tibco/files/resources/wp-nimbus-universal-process-notation.pdf):
"_UPN, a simplified system of symbols and rules_"

I don't think there is a need for an icon set. The only icons I have seen in the various resources are the following:
* a paperclip, to indicate the presence of an attachment
* a down arrow, to indicate the possibility to drill down the process to the next level (this is used by Tibco, Salesforce and Elements.cloud use a different notation for this, not requiring icons)

In earlier versions of the Tibco UPN "Standard" document (05/13/2014), there were more icons, but in the current version (01/25/2016) there are only those two icons.

For both icons, interactivity may be optional or simply handled via copy-pasted links.



![image](https://user-images.githubusercontent.com/34871840/210648347-3d676d92-1b44-4003-af52-f7e3b92e0260.png)

![image](https://user-images.githubusercontent.com/34871840/210648370-0a69f781-0223-458e-9b36-eefbcb8f15e9.png)

<img width="508" alt="image" src="https://user-images.githubusercontent.com/34871840/210649275-1ce09481-1816-4602-976f-094f15b2133f.png">

<img width="508" alt="image" src="https://user-images.githubusercontent.com/34871840/210649250-c0b2c8fd-4309-4225-b588-c9c97de43ba0.png">


Can existing shapes be used for the purpose? If so, we would have both of them ready!

<img width="205" alt="image" src="https://user-images.githubusercontent.com/34871840/210649171-fbeaf7f2-26ea-47aa-93b4-5f5f34b4d8d5.png">

<img width="199" alt="image" src="https://user-images.githubusercontent.com/34871840/210649375-94287097-cd85-459b-8b63-a642dc99a8c3.png">


Let us know if there is something else we may do to increase the chances of implementation!


**P.S.** Despite being "baked" by Salesforce, UPN is still not getting huge traction. However, there are further and newer resources on UPN:
* https://elements.cloud/2021/06/26/salesforce-upn-for-business-analysts-launched/
* https://trailhead.salesforce.com/it/content/learn/modules/business-process-mapping/understand-universal-process-notation
* https://unitfly.com/what-is-universal-process-notation-upn/

**Comment by tootflap** [comment]
What community contributions might this take to get this game-changing standard implemented?

**Comment by davidjgraph** [comment]
Thanks for your suggestion. Overall, the interest in this set looks very low, so we're going to decline the request.
