### ISSUE TITLE
Add Persian Translation 

### ISSUE THREAD

**Issue by robybc** [jgraph/drawio#1032]
* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
hi 
please add Persian translation to your site

**Describe the solution you'd like**
i can type rtl and see farsi in menu
**Describe alternatives you've considered**

**Additional context**
is in translation need help I can help you

**Comment by sawfi** [comment]
_**ชุมชนบ้านยีลาปันhttps://www.facebook.com/sawfikama2531https://www.linkedin.com/in/sawfikama2531>**_ ### @[http://sawfikama2531.wordpress.comsawfikama2531https://youtu.be/tbYgc3EgGJo](`https://www.mediafire.com/folder/uot1gbhnhvrfd/Camera[URL=http://www.mediafire.com/file/c24dome3cl6x38r/MediaFire_-_Getting_Started.pdf/file]http://www.mediafire.com/file/c24dome3cl6x38r/MediaFire_-_Getting_Started.pdf/file[/URL][URL=http://www.mediafire.com/file/c24dome3cl6x38r/MediaFire_-_Getting_Started.pdf/file]http://www.mediafire.com/file/c24dome3cl6x38r/MediaFire_-_Getting_Started.pdf/file[/URL]`)
