### ISSUE TITLE
Tabloid/Landscape Page Type Prints as Letter/Portrait

### ISSUE THREAD

**Issue by mnelson10000** [jgraph/drawio#1033]
With the page type set to 11x17 (tabloid) and landscape, it prints as 8.5x11 (letter) and portrait.  I've reproduced this Firefox and the Windows desktop app.  I've also reproduced it with both a physical printer and a PDF printer.

**Comment by mararad** [comment]
Hi,

you mentioned you tried both a physical printer and a PDF printer. What exact steps you performed (where did you click), please?
Was it File > Print and Save as PDF/Print to PDF 
or File > Export as PDF > ... (add your steps please)

Thanks,

**Comment by mnelson10000** [comment]
It was File > Print.  I've tried sending to a printer (Konica Minota Biz C754) and the Microsoft Print to PDF driver. 

I just tried it in Chrome also and get the same result.  Chrome actually shows a preview in the print dialog and you can see it with the wrong paper type there.

File > Export > PDF seems to work!  The resulting file has the paper type and orientation set correctly.  Thank you for pointing that out, that's a workaround.

Thanks

**Comment by ashrafteleb** [comment]
Did you try changing the paper size in the system print dialog?

**Comment by mnelson10000** [comment]
> Did you try changing the paper size in the system print dialog?

I did and it came out with the correct paper and orientation, but I seem to remember that it didn't render correctly.  It bled off the page and spilled onto a second page.

**Comment by ashrafteleb** [comment]
Can you please provide us with a sample file and steps to reproduce the rendering issue when the system print dialog page size matches the page size in draw.io print dialog?

**Comment by mnelson10000** [comment]
I'm lost where you are going with this, because overriding the paper orientation and size through the printer driver doesn't address the bug.  :)  Rotating and stretching with the printer driver has mixed results.

Regardless, I've attached the source file and the sample PDF if I print to the Microsoft Print to PDF driver.  In this case, I used Firefox, but the problem seems cross platform.  

To reproduce, File -> Print... (which this dialog correctly shows 11x17), Print.  In the system printer dialog, change to Microsoft Print to PDF, Preferences..., Orientation: Landscape, Advanced..., Paper size: tabloid.  With this print driver, it doesn't bleed over to a second page, but it doesn't scale up to fit the full page, either (sample output file attached).  

[11x17 test.zip](https://github.com/jgraph/drawio/files/5091352/11x17.test.zip)

**Comment by ashrafteleb** [comment]
The reason I asked for changing the page size in the system print dialog is we don't have control on that dialog. We prepare the page size based on the information give in our print dialog, then the user should match those setting in the system dialog.

As in this screen shot (where I followed your steps but with clicking preview), you see the page size and orientation is correct
![Screen Shot 2020-08-18 at 12 19 04 PM](https://user-images.githubusercontent.com/24944765/90539210-8e0a6a00-e14d-11ea-8b7c-0cb1b17d6a71.png)

And this is how it prints when I matched the page size and orientation in the system dialog
[Accountability Chart no names 2020-07-20.pdf](https://github.com/jgraph/drawio/files/5091565/Accountability.Chart.no.names.2020-07-20.pdf)

**Comment by mnelson10000** [comment]
Yes, it does look correct in the preview screen.  It's just not making it to the printer with correct paper settings.  You're saying that this is a shortcoming of the development platform?  If so, I'll just continue using the PDF export functionality as a workaround.

Thanks

**Comment by ashrafteleb** [comment]
You can also try our desktop app which has more control over the printer settings and should produce correct results.
