### ISSUE TITLE
Unable to select group containing only connectors

### ISSUE THREAD

**Issue by ErikSwan** [jgraph/drawio#1036]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
After creating a group that contains only connectors, there is no way to select the group as a whole. Clicking on connectors within the group simply selects the individual connector, and there appears to be no way to manipulate the group object.

**To Reproduce**
1. Create new blank diagram
2. Add 3 basic line connectors to the diagram
3. Select all 3 connectors, then press <kbd>Ctrl</kbd>+<kbd>G</kbd> or Arrange > Group to group them.
4. Deselect the created group by clicking in a blank area of the canvas.
5. Attempt to re-select the group of connectors by clicking on one of the connectors, or clicking and dragging to select them all. The individual connectors are selected, but the group object is not, so it is impossible to (for example):
   1. Ungroup the connectors
   2. Rotate the group as a single object

**Expected behavior**
With nothing selected, clicking once on one of the connectors in the group would select the entire group object (rather than the individual connector object within the group). This is consistent with how groups of shapes behave.

**Screenshots**
Actual behavior:
![image](https://user-images.githubusercontent.com/163976/87464660-bd6b0b80-c5d0-11ea-8995-95cc90ab924d.png)
(Only a single connector selected.)

Expected behavior:
![image](https://user-images.githubusercontent.com/163976/87464702-ca87fa80-c5d0-11ea-8bf1-41ac098d6dab.png)
(Group object selected. Note the rotation icon in the top-right corner which allows rotating the group as a single object.)

**draw.io version (In the Help->About menu of the draw.io editor):**
- 13.4.3

**Desktop (please complete the following information):**
 - OS: Windows 10 1809
 - Google Chrome 83.0.4103.116

**Comment by mararad** [comment]
If you repeat all the steps in desktop app (if you have it) is it working? At my place it is working (13.0.3) but have the same problem as you in Win 10, Chrome Version 83.0.4103.116 (Official Build) (64-bit) and diagrams.net online 13.4.4

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
