### ISSUE TITLE
CTRL+SHIFT+U is not ungrouping

### ISSUE THREAD

**Issue by ppazos** [jgraph/drawio#1037]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**
1. draw a couple squares
2. select both and group
3. select the group
4. try the ungroup shortcut CTRL+SHIFT+U
5. ungroup doesn't happen

**Expected behavior**
Ungroup the items.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.4.3

**Desktop (please complete the following information):**
 - OS: Linux Mint 19
 - Browser FF 78.0.1

**Comment by mararad** [comment]
I am not able to test it in Linux (in Win 10 it is working well) but if you try in another browser and Incognito mode, is it working?
Also, if you do the hard reload (it should upgrade to 13.4.4) does it help?
