### ISSUE TITLE
command line export to non-compressed xml feature

### ISSUE THREAD

**Issue by vulkanino** [jgraph/drawio#1038]
Hello,

I usually open a draw.io design and then I export it to a non-compressed xml via the menu. When you have many files to export this is a very time consuming task. I would love to have a command line "export to xml" option, while at the moment I only see the following formats available in the command line: pdf, png, jpg, svg, vsdx.
 
Thank you.

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Comment by ashrafteleb** [comment]
Feature added to draw.io desktop app (use arguments -x xml -u)
https://github.com/jgraph/drawio-desktop/releases
