### ISSUE TITLE
MS Store Release - v13.3.9.0 - Update Loop

### ISSUE THREAD

**Issue by Saijin-Naib** [jgraph/drawio#1042]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
draw.io Microsoft Store release does not update/launch properly, and is still very back-dated compared to the website (13.4.4)

**To Reproduce**
1. Check for app Updates in the MS Store
2. Let draw.io update to 13.3.9.0
3. Launch app
4. See app upgrade prompt
5. Let app update & quit
6. Re-launch app
7. See app upgrade prompt
8. Repeat ad Infinium
9. Clear upgrade prompt, check app version to be backleveled 13.3.9.0

**Expected behavior**
App upgraded to current stable release, doesn't get stuck in upgrade cycle

**Screenshots**
https://youtu.be/5-yU0AbhW7U

**draw.io version (In the Help->About menu of the draw.io editor):**

- 13.3.9

**Desktop (please complete the following information):**
 - OS: Windows 10 2004

**Comment by davidjgraph** [comment]
13.3.9 is the lastest version in the Window store. I think the release there hasn't got the Github updater turned off.

**Comment by Saijin-Naib** [comment]
Will there be a release to make it current with the website version? There are some nice improvements in that release.

**Comment by davidjgraph** [comment]
Eventually, but it's only about 10 days behind...

**Comment by Saijin-Naib** [comment]
Thanks so much!

**Comment by Saijin-Naib** [comment]
No auto-update loop!
![image](https://user-images.githubusercontent.com/19295950/87680659-b288b600-c74b-11ea-9cca-69b802ad47c9.png)  

Rebased on 13.4.4.0!
![image](https://user-images.githubusercontent.com/19295950/87680714-c3392c00-c74b-11ea-852b-9cf8546c47b4.png)  

Many thanks! 🙏

**Comment by davidjgraph** [comment]
Thanks, but the fix is in 13.4.5. The reason it's saying no upgrade is because 13.4.4 is the latest in Github. We'll release 13.4.5 today and MS will probably take a day to approve it, so you'll likely have the problem come back for that time.

**Comment by davidjgraph** [comment]
13.4.5 is in the store.
