### ISSUE TITLE
Inconsistent behavior of containers regarding foreground / background

### ISSUE THREAD

**Issue by typex1** [jgraph/drawio#1044]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
If you put an overlay element (IBM VPC, Rectangle, Container) **over** an already added element (server icon etc.), and the overlay element has **no** color fill, then their behaivur regarding foreground / backgroud is not consistent:

- In case of an IBM VPC or a Container, the underlying icon is still clickable
- In case of a Rectangle, or an AWS element like mxgraph.aws4.group, the underlying icon is NOT clickable at once. You first need to send the Rectangle to the background

This seems like an irrelevant issue at first sight, but in case you have complex drawings which consist of several nested elements, it makes a difference if (especially during a presentation) each change in nested elements needs to first identify those elements that have to be sent to the background or not.

**To Reproduce**
1. Go to 'search elements', search for server icon, put icon on the plane
2. Search for 'IBM VPC', put this over the server icon
3. The server icon remains clickable and movable, even if it is in the background
4. Remove the VPC rectangle, move a normal rectangle over the server icon
5. The icon is not clickable unless you send the rectangle to the background before.
6. This effect can be nested, i.e. further rectangles being put over the already visible ones would lead to being all sent to the background until the server icon is clickable again.

**Expected behavior**
Transparent, not filled rectangular shapes should not hide the underlying elements, because that is not suitable for an easy work experience.

**Screenshots**
<img width="478" alt="Screenshot 2020-07-16 at 13 47 07" src="https://user-images.githubusercontent.com/8014314/87667607-f6d77e80-c76a-11ea-9c73-e9e371b11ec9.png">

<img width="404" alt="Screenshot 2020-07-16 at 13 49 11" src="https://user-images.githubusercontent.com/8014314/87667721-28504a00-c76b-11ea-81c5-56746ad82e47.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.4.4 as local app on MacOS

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 13.4.2

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alderg** [comment]
This is the intended behaviour. You can disable this behaviour by unchecking "Pointer Events" in the style pane:
![Screenshot 2020-07-20 at 09 09 37](https://user-images.githubusercontent.com/921200/87909622-deb47780-ca68-11ea-8836-0975cab88ee9.png)
