### ISSUE TITLE
Whoops! Website is down.

### ISSUE THREAD

**Issue by cooperfrench95** [jgraph/drawio#1045]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

The web application does not load when going to draw.io/app.diagrams.net.

**To Reproduce**

Navigate to `draw.io` in url bar of your favourite browser.

**Expected behavior**

Site loads.

**Actual behaviour**

User presented with infinite loading screen. Console shows error pretty clearly.

**Screenshots**

![image](https://user-images.githubusercontent.com/44951144/87877519-65d60100-ca11-11ea-8360-edba4f8e0b99.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Tried on firefox and chrome, latest versions.

**Additional context**

**Comment by alderg** [comment]
Fixed in 13.4.8.
