### ISSUE TITLE
Bring back the feature to quick add new row in Entity diagram

### ISSUE THREAD

**Issue by datsabk** [jgraph/drawio#1049]
* [Y ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [Y ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
No. It is request to bring back an old feature 

**Describe the solution you'd like**
The feature of clicking the right arrow to add a new row in the entity relationship diagram was extremely handy and that made the life easier. With the feature gone, I can't look at the site as a tool for ER diagram any more! 

**Describe alternatives you've considered**
dbdiagram.io is my go-to tool at present as it creates diagram from the code

**Additional context**

**Comment by RouhinG** [comment]
Same issue here, please bring back the feature to quick add new rows in class diagram and ER diagrams.

**Comment by davidjgraph** [comment]
Does that work again in 13.5.0?
