### ISSUE TITLE
Quick row add option for ER diagram and Class diagram is missing. Please add the feature as it was before. It is become too cumbersome to use and add new rows. 

### ISSUE THREAD

**Issue by RouhinG** [jgraph/drawio#1050]

**Comment by alderg** [comment]
You mean via blue arrow?

**Comment by RouhinG** [comment]
Yes Gaudenz...

**Comment by davidjgraph** [comment]
Fixed in 13.5.0

**Comment by RouhinG** [comment]
Hi, I use draw.io website and the current hosted version is 13.4.9..
[image: image.png]

**Comment by RouhinG** [comment]
When can we expect the same to be released for public use in the draw.io
website?

**Comment by davidjgraph** [comment]
Then current hosted version is 13.5.0, you're caching that version.

**Comment by RouhinG** [comment]
Yes David, thanks a ton, the problem is resolved now, indeed i was using a
cached version the draw.io and now the feature works just fine. Thanks a
lot!
