### ISSUE TITLE
documentation is missing images

### ISSUE THREAD

**Issue by FlorianLudwig** [jgraph/drawio#1051]
**To Reproduce**
1. Go to https://desk.draw.io/support/solutions/articles/16000067815-how-to-use-layers-
2. Images missing

**Comment by davidjgraph** [comment]
Check your ad blocker....

**Comment by FlorianLudwig** [comment]
@davidjgraph this is not an adblocker issue.

Have you even opened the link?

**Comment by FlorianLudwig** [comment]
The page tries to to render `https://github.com/jgraph/drawio/wiki/Getting-Support` as an image...

**Comment by davidjgraph** [comment]
Ah OK, I probably have a different host mapping. We'll take a look.
