### ISSUE TITLE
Allow ungrouping multiple groups at the same time

### ISSUE THREAD

**Issue by ErikSwan** [jgraph/drawio#1052]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Sometimes I want to ungroup multiple groups at the same time. It is frustrating to have to have to select each group object one at a time and ungroup it, rather than being able to ungroup multiple group objects at the same time.

**Describe the solution you'd like**
I would like to be able to ungroup multiple groups at the same time with Arrange → Ungroup or the Ungroup keyboard shortcut (currently <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>U</kbd>).

**Describe alternatives you've considered**
As mentioned above, you can ungroup groups one at a time, but this is tedious.

**Additional context**
This behavior would match how Microsoft PowerPoint handles ungrouping multiple groups at a time.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
