### ISSUE TITLE
Add WebDav option on storage selection dialog

### ISSUE THREAD

**Issue by farosha** [jgraph/drawio#1053]
Hi there,

We've recently launched **kDrive**, a collaborative cloud for storing data that respects personal data privacy and we were wondering if it would be possible to add it as a saving option on Diagrams.net, alongside with Google Drive, Dropbox and the likes?

In terms of size and volume, we have over half a million clients all over Europe, and mainly in Switzerland, France, Germany and Luxembourg, have 2 datacentres in Switzerland and about to build a third one.

Here is some more info about kDrive if you'd like : 
https://www.infomaniak.com/en/kdrive
https://news.infomaniak.com/en/kdrive-secured-cloud/

Please let me know what you think, and feel free to contact me if you have any question.

Many thanks in advance for your feedback and best regards,

Fanny Meyer

![kDrive option in Drawings net](https://user-images.githubusercontent.com/61696451/88077996-342d7900-cb7c-11ea-80cc-df8ea4af434f.png)

**Comment by davidjgraph** [comment]
Do you have a JS client that enables direct read/write without going via a server?

**Comment by farosha** [comment]
Hi David! Thank you for your quick reply. We do not provide a JS client, but we support the Webdav standard for which there are JS clients available. Would this suit you? or would you rather that we provide you with a JS API?

**Comment by davidjgraph** [comment]
We can change the ticket to be a generic WebDav option.

**Comment by farosha** [comment]
Ok so the webdav option suits you. What are the next steps then?

**Comment by davidjgraph** [comment]
Someone would have to implment the code.

**Comment by farosha** [comment]
yes sure - when would that be possible?

**Comment by davidjgraph** [comment]
This is an open source project, your question is a little strange...

**Comment by farosha** [comment]
And if we were to provide you with a JS client instead of the webdav, where can we find the specs? and what is the procedure once we have developed it to submit it? Thank you

**Comment by alderg** [comment]
Here are examples of integrating diagrams.net with a WebDAV backend: https://github.com/jgraph/drawio-integration/tree/master/webdav

**Comment by farosha** [comment]
Thanks, will have a look at it

**Comment by Rik44444** [comment]
Hi, I'd like to hereby support this feature request for Webdav support. Since this is an open-source project, it really suits the project well! Would be great if there was a sign-in for Webdav besides Dropbox and Google Drive.

**Comment by Rik44444** [comment]
this issue is not stale, webdav is really handy! I think it is also already possible, because draw.io is now available in Nextcloud as an app

**Comment by xplosionmind** [comment]
Hi, may I ask why this feature request has been closed? I believe that it would be extremely valuable.

**Comment by davidjgraph** [comment]
What the ETA on this?
