### ISSUE TITLE
Sketch function not available in draw.io for Confluence

### ISSUE THREAD

**Issue by DanielSchoeneck** [jgraph/drawio#1054]
* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I can't find the new sketch function in draw.io...I only find the Comic function

**To Reproduce**
1. Go to properties of a shape
See also https://drawio-app.com/introducing-draw-ios-new-sketch-feature/

**Expected behavior**
Sketch option can be activated

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 9.4.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 83.0.4103.116

**Comment by davidjgraph** [comment]
If this is confluence server, try updating to the latest draw.io release.
