### ISSUE TITLE
Flipping grouped items or selected items

### ISSUE THREAD

**Issue by ghominejad** [jgraph/drawio#106]
As you know flipping multiple items  or grouped items, Horizontally or Vertically is Inevitable in a complex drawing. It seems draw.io doesn't support this feature for now

Thanks

**Comment by alderg** [comment]
Works for me.

**Comment by tristanaustin** [comment]
I'm having the same problem. Can you please explain how this can be achieved?

There is no "Flip" section on the Arrange tab when I have a grouped set of objects selected. If I select a single shape, there is a Flip section with 'Horizontal' and 'Vertical' buttons that work as expected on that single shape.

If I ungroup the objects again, leave them all selected and click the "Horizontal" or "Vertical" buttons, it flips each individual selected shape in place.

I can't find any documentation explaining how to do this for grouped objects and all the examples that I have found only show [flipping a single object](https://drawio-app.com/draw-io-training-exercise-3-editing-a-diagram-change-the-shapes/).

Running on macOS 10.15.6
Draw.io version: 13.4.5

![Screen Shot 2020-07-21 at 2 06 23 pm](https://user-images.githubusercontent.com/36911621/88011714-6a0e3580-cb5b-11ea-87b1-e2becb9b7b82.png)
![Screen Shot 2020-07-21 at 2 06 29 pm](https://user-images.githubusercontent.com/36911621/88011709-667aae80-cb5b-11ea-8103-e7d348cf793c.png)
![Screen Shot 2020-07-21 at 2 13 47 pm](https://user-images.githubusercontent.com/36911621/88012116-6f1fb480-cb5c-11ea-8d33-09b6bb3320db.png)

**Comment by sachit-menon** [comment]
I have the same issue.

**Comment by gautamyadav144** [comment]
I faced same issue, i just draw three lines in zigzag way and then grouped them and then flipped horizontal.

draw.io version- 14.7.0
Chrome Browser Version 90.0.4430.212

Before snip
![image](https://user-images.githubusercontent.com/20815011/119966723-3a288d80-bfc9-11eb-9f50-eaa2a79ce1af.png)



After snip horizontal
![image](https://user-images.githubusercontent.com/20815011/119969724-8a551f00-bfcc-11eb-9732-f72a85c6755d.png)

**Comment by cha0s4u** [comment]
Hello Team,
First thanks for a great tool! We are facing difficulty without this feature and notice a related bug was closed, but it still does not work for flipping grouped stencils - horizontal or vertical.

Will be highly appreciated, if this can be pushed up in priority queue.

**Comment by davidjgraph** [comment]
If a case marked as closed doesn't work for you, you need to open a new ticket as a bug or feature request.

**Comment by Bart76** [comment]
> Works for me.

@alderg Can you please explain how it works for you? It does not work for me. I am trying to draw some filled overlapping parallelograms in order to draw a kind of a background-filled ALU-like shape, but I fail to flip one of those two parallelograms, thus failing to achieve my goal in Diagrams.NET... Should I consider switching to another drawing application instead?

**Comment by davidjgraph** [comment]
Just to clarify here, the original post is awful quality. It gives no details of environment and how to re-create the problem, it got the response it deserved. If someone wants to post a constructive issue report, we will engage with it constructively.
