### ISSUE TITLE
Error Drawing is too large when exporting as PDF

### ISSUE THREAD

**Issue by tnageleweb** [jgraph/drawio#1061]
Hi,

I was working a drawing when exporting as PDF it shows Error: Drawing is too large. But exporting as JPEG working fine. That is why I am thinking it is a bug.

Tried on Windows app, and online (https://app.diagrams.net/), both are showing the same error.

I would like to share the file so you can test it your self but cannot share it on the public since it has my Company information. Would you please let me know, how can I send you the file.

**Comment by tnageleweb** [comment]
OK, the issue resolved.

The problem is that the App is converting any loaded image into base64 which increases the file size dramatically. I think this is poor design implantation, as the image should imported by link reference and not by its content or at least let the user decide how to import it. In my case, I was re-using the same images, but since the app is already converted to base64, every copy was considered as a new image (in terms of size). 

My workaround worked for me in Windows App:
I referenced the image by file URL, for example: 
- Right-click the image,
- Edit Image...
- Edit URL: file:///absolute Path to image

However, I wanted to make the image path retrieve to App location, to do so:
- Locate the drawaio EXE file  (my case: C:\Program Files\draw.io  (<== draw.io.exe located inside this folder)
- Create folder name it i.e: 'images'
- Add all needed images inside that 'images' folder
- Now from windows app, reference images as follows: 
	file:///../images/image1.jpg
	file:///../images/imageX.jpg
	
That reduces the file size from 11 MB into less than 1MB and fixes the issue.
Hope someone finds it useful. An hope to improve the App implantation in the next releases.

**Comment by davidjgraph** [comment]
So if a user shared the diagram that referenced a localled storage image, then what?

**Comment by tnageleweb** [comment]
Valid point, it will not work. But, remember the original case (with loaded content image), also exporting is not working (what the point of sharing broken files?!)
 The workaround solved my particular case (at least) using local images, on Windows, a more practical solution is needed of course.
 I think it is still a bug and the issue needs to be addressed, what do you think?

**Comment by davidjgraph** [comment]
The image is either in the diagram or it's not. If it's not, you'll end with people sharing diagrams that don't render correct for other users.

If it is you'll end up with larger files. We resize dragged in images over a certain size limit, but other that how do you suggest this is resolved?

**Comment by tnageleweb** [comment]
I was unable to export my .drawio file to PDF (this is the original issue). In my case, I needed my images with high resolution, so resizing is not an option. Once I changed the images reference as mentioned above, I was able to export as PDF with high-resolution images, thus, solved my problem. I should not say it is resolved (sorry).

So, if you think it is not a bug, you may close the case. Thank you.

**Comment by jPPuetz** [comment]
I'm having the same issue. Export with JPEG and PNG works. But PDF fails. I think it may be an issue of the PDF implementation since SVG is workings fine too. Converting the SVG to PDF via e.g. a cloud converter works too. The PDF and SVG is large (~80MB) but usable. The only issue I'm having is that line breaks along borders of shapes aren't in the SVG therefore not a good workaround.

**Comment by ashrafteleb** [comment]
Removed size limits on PDF export for desktop app **only**
