### ISSUE TITLE
Integration with a backend

### ISSUE THREAD

**Issue by ile** [jgraph/drawio#1062]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Hi,

A suggestion for a wiki page or similar:

How to do integration with a backend, say a database, with a realtime editing.

Let's say the backend has a JS client with `submit()` function that accepts editing events and `onEvent()` listener function which is called whenever there are new editing events coming from the backend. You can add more functions here if you need something.

How would you integrate this into drawio? 

Thank you!

**Comment by ile** [comment]
I'm trying to do this myself, and I'm asking some instructions how to do it. A wiki page/documentation could help everyone. If it takes time, maybe you can start it here?

**Comment by davidjgraph** [comment]
The full answer would be very long and depend on general architecture of the system you're looking to create.

This project is, bascially, a static web app, with integration support for various existing storage APIs. It's not a back-end implementation and not really written for any specific back-end structure.

One route that a lot of people choose is to use the [postMessage protocol](https://github.com/jgraph/drawio-integration) as the persistence interface. That's been updating recently so it should technically be possible to take the collab deltas across.

In terms of the diff/sync model itself, we haven't documented that to date.

One thing that would be useful in terms of direction of an answer is what is the end result you're trying to achieve?

**Comment by ile** [comment]
Hi there, thanks for the reply!

After testing the Google Drive real time editing, it seemed that what I'm trying to do is possible and would be quite similar. It handled everything automatically (changes from client A appeared automatically client B).

I suspect the deltas (the change events) go from client A to the main server and from there they go to clients B, C and D, where they are synced into the view. 

Something, somewhere (the main server?) also probably creates the current file (the current snapshot) from those change events, that can be saved into a file/database. Right? I mean surely this has to happen, but I'm not sure where it is done and how. And is the file created from the change events, probably yes? 

So that would be the general architecture/plan.This would allow real time editing, with a normal database acting as a storage. There can be a server component too (which can do anything it needs to do).

Now, I would just need some pointers how to do this. What the clients have to do and what the server has to do. Clients probably will use some API calls to tie to drawio/mxgraph, so some instructions on that would help too.

The  "embed mode" isn't really what I'm after as I would install the app on my server with everything needed (code in clients/server)-

Thanks,

**Comment by ile** [comment]
Any help for this?

**Comment by ile** [comment]
Ok, it may not be as straightforward, but I think I can get there. I think I will need to

- Subclass `DrawioFile` like `DriveFile` does
- Create a replacement for `window.Pusher`

Or

- Rewrite `DrawioFileSync` a bit so that it doesn't need a pusher. 

Trying these...
