### ISSUE TITLE
Bug in sync?

### ISSUE THREAD

**Issue by ile** [jgraph/drawio#1063]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

Sync doesn't seem to work properly in this case (see images at the end). I'm using Dropbox file in two clients and edit/sync between them.

**To Reproduce**
1. Open the file in two clients. 
2. Create a shape in client 1. Save in client 1 and sync in client 2. 
3. Resize the shape in client 1.
4. Save the file in client 2. Don't sync, just save the original file again.
5. Sync in client 1. 
6. Sync in client 2.

**Expected behavior**
The shape in client 1 should be the same as in client 2. Client 2 should have the correct size as it was saved last.

What happens is that the size in client 1 stays the same, it won't refresh to the correct size. If I refresh the whole app and open the file again, then I see the correct size of the shape in client 1.

**Screenshots**
Client 1
![image](https://user-images.githubusercontent.com/433707/88450102-28c89f00-ce55-11ea-9f1f-9c5e5670f579.png)

Client 2
![image](https://user-images.githubusercontent.com/433707/88449973-f1a5be00-ce53-11ea-9e86-e6ad6136ae80.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.4.3 (git clone ... I should probably update this)
- mxgraph2 in use (4.2.1)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome

**Comment by davidjgraph** [comment]
Collaborative editing is only supported in back-end storage systems with if-match header support on files. That's the way we get an atomic check and write. OneDrive and Google Drive support this.
