### ISSUE TITLE
Make rotation smooth

### ISSUE THREAD

**Issue by ile** [jgraph/drawio#1065]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

A suggestion: make shape rotation smooth, regardless where the mouse is positioned.

Now, if the mouse is positioned near the edge of the shape (or inside), it rotates in (big) steps. I think it could rotate smoothly, regardless where the mouse is positioned.

Thanks.

**Comment by alderg** [comment]
This is a feature, not a bug. Hold down the Alt (Option) key while rotating the shape to rotate smoothly regardless of the mouse position.
