### ISSUE TITLE
Adding effects to a shape (like drop shadow)

### ISSUE THREAD

**Issue by ile** [jgraph/drawio#1067]
Suggestion:

Feature, where you could add *effects*, like drop shadow, to a shape. You would be able to add multiple effects to a single shape, for example multiple drop shadows.

Effects could be styled with CSS's `filter` rule:

https://stackoverflow.com/questions/6088409/svg-drop-shadow-using-css3
https://developer.mozilla.org/en-US/docs/Web/CSS/filter

This would make styling shapes very versatile.

**Comment by ddidier** [comment]
See #1671
