### ISSUE TITLE
Loading Diagrams from Browser results in error: Cannot read property 'setConsumer' of undefined

### ISSUE THREAD

**Issue by al3x-huang** [jgraph/drawio#1068]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I attempted to load diagrams by going to `File` -> `Open From` -> `Browser` but was prompted with the error message:
`Cannot read property 'setConsumer' of undefined`

**To Reproduce**
1. Click on `File`
2. Click on 'Open From'
3. Scroll down to 'Browser'

**Expected behavior**
The diagram browser for drawings stored in the browser to pop up.

**Screenshots**
![Screen Shot 2020-07-27 at 1 15 42 AM](https://user-images.githubusercontent.com/20210402/88505944-d0a1b200-cfa6-11ea-83da-1f90574b0174.png)
![Screen Shot 2020-07-27 at 1 18 26 AM](https://user-images.githubusercontent.com/20210402/88506079-25452d00-cfa7-11ea-8a3c-0c909c5d9e4d.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.4.1

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 84

**Additional context**
Could this have anything to do with the domain shift to diagrams.net?

**Comment by alderg** [comment]
Use the latest version 13.5.3.

**Comment by al3x-huang** [comment]
I can't use 13.5.3 unless I go on incognito. Reloading the page still shows 13.4.1. Any tips?

**Comment by davidjgraph** [comment]
Close all browser tabs that have app.diagrams.net open. Open [https://app.diagrams.net/?offline=0 ](https://app.diagrams.net/?offline=0) in a new tab. Once loaded, close that tab. Then try opening again.
