### ISSUE TITLE
How to deploy draw.io to github enterprise

### ISSUE THREAD

**Issue by shenghu** [jgraph/drawio#107]
If I want to use draw.io in my enterprise github, what should I do? Thanks. I want to edit documents in my enterprise github.

**Comment by davidjgraph** [comment]
We've never tried to integrate with Github Enterprise, I don't know what is required to achieve that.

**Comment by EricBalingit** [comment]
This is a missing feature and should be reopened and considered imho.

We need to make several large graphs over a project and having this support would be a benefit to my team.  Otherwise the process is very clumsy.

**Comment by davidjgraph** [comment]
OK to re-open, but it'll need someone to do this, I don't see how we can justify the effort.

**Comment by EricBalingit** [comment]
I understand, on that part I would be lost, unfortunately.

**Comment by EricBalingit** [comment]
Question if I may here.

I'm trying to link to an organization that I own and the folder comes up when I type it in, but when I click that folder draw.io jumps back to my personal folders.

Is there any possibility of making that kind of api linkage work?

I wouldn't mind having a look, but I know nothing about github api. :-(

**Comment by davidjgraph** [comment]
Please direct to https://groups.google.com/forum/#!forum/drawio

**Comment by davidjgraph** [comment]
Please file a feature request at https://draw.uservoice.com/forums/266072-feature-requests/filters/top

**Comment by davidjgraph** [comment]
Given the age of this request, the number of votes and the effort of implementing and maintaining such an integration, it's safe to say we're not going to do this.
