### ISSUE TITLE
Supprot for RTL languages (Right-To-Left)

### ISSUE THREAD

**Issue by avikla** [jgraph/drawio#1072]
Please add support for text editing in RTL languages such as Hebrew.

**Comment by alderg** [comment]
This should be detected automatically. If that does not work, try setting the writing direction in the text style panel:

![Screenshot 2020-07-30 at 09 59 09](https://user-images.githubusercontent.com/921200/88897359-6a898900-d24b-11ea-9113-97e27cf9aa27.png)
