### ISSUE TITLE
Display .drawio file in GitHub readme.md?

### ISSUE THREAD

**Issue by brightzheng100** [jgraph/drawio#1073]
* [ x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
With the VSCode plugin, I can easily create and edit my `.drawio` files, which is super cool.
However, I'm not sure how to display it in a web page, or specifically in GitHub's `README.md` file.

**Describe the solution you'd like**
I'm wondering whether I can simply display the live `.drawio` file within `README.md` with a simply image markdown like:
```
![My Architecture diagram](http://draw.io/convert?format=png&file=the_file_in_my_github.drawio)
```

**Describe alternatives you've considered**
For now I may have to convert the `.drawio` file to `.png` so that I can use the GitHub markdown.

**Comment by alderg** [comment]
Save it with an .svg extension so it can be used as an image in markdown as shown at https://github.com/jgraph/drawio-github
