### ISSUE TITLE
Copy shape is no longer working

### ISSUE THREAD

**Issue by javadba** [jgraph/drawio#1074]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

 I am a v experienced user over a few years and had created diagrams even within the past month.  

But today I could not get "copy" to work.

**To Reproduce**

* select an existing entity on the diagram
* CMD-C to copy it
Nothing happens.

I tried that a solid 20 times.  I also tried it from the Edit | copy menu. No dice.  I reloaded draw.io.  No dice. New diagram. No dice.

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

13.5.5

**Desktop (please complete the following information):**

I am on Catalina on latest chrome  Version 84.0.4147.105 (Official Build) (64-bit)

**Additional context**

I ended up using the directed green arrow to generate new boxes. But that is not my preferred way to go.

**Comment by alderg** [comment]
Checked with the same config using the online version 13.5.5 on app.diagrams.net and this works for me. Do you have any extensions installed? Does it work with other browsers/incognito mode? Are there any errors in the console? Does it work with a blank file?

**Comment by javadba** [comment]
I can reproduce this by dragging a shape from the toolbar.  For some reason re-using a shape that was already in a template does _not_ exhibit the problem: it _does_ copy correctly.  I will try to get  video for this.
