### ISSUE TITLE
[Question] is there any way to save draw.io diagram in my server to a specific location

### ISSUE THREAD

**Issue by AnubhabMondal** [jgraph/drawio#1076]
I just have a simple question. If any of you clarify these things for that would really be helpful.
 So, I just want to save whatever image I can create that would save in my server location path or my server URL path.
Now if I save any image it directly saves to  **https://viewer.diagrams.net/....** here I just want to save that image to something like **https://localhost/path..**
@diocles , @fulldecent , @mediaslav  Can you please help me with this.

**Comment by ashrafteleb** [comment]
We don't store documents on our servers. You may try to self-host draw.io and use it to view your diagrams

**Comment by gramakri** [comment]
@ashrafteleb If I understand the question correctly, @AnubhabMondal is asking whether selfhosted draw.io can save the files on their own server? Or does one always have to download / save it in browser when selfhosting diagrams.net ?

**Comment by davidjgraph** [comment]
There's no back-end storage in this project, it's just the client-side web app. It integrates with various other back-end storage options, like the cloud storage options you see in app.diagrams.net, you could also do this self-hosted.

Various other projects integrate this with other projects that provide the back-end context, like wikis, etc.
