### ISSUE TITLE
Page setup orientation error

### ISSUE THREAD

**Issue by DevT0ny** [jgraph/drawio#1077]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
In page setup option when I select 16:9 or 16:10 or 4:3 in portrait mode the page orientation is not portraited instead it uses landscape mode and when I use Landscape mode page becomes in portrait mode. 

**To Reproduce**
1. File > page setup
2. Select anyone from 16:9, 16:10, 4:3
3. Select mode as either portrait or landscape.
4. Click apply

**Expected behavior**
In portrait mode, the page should be portrait and same for the landscape.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 13.5.8]

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: chrome
 - Version: 83.0.4103.116 (Official Build) (64-bit)

**Comment by mararad** [comment]
Reproduced in Chrome Version 84.0.4147.105 (Official Build) (64-bit), win 10 Pro and diagrams.net online 13.6.0
