### ISSUE TITLE
Cannot Authorize the app for google drive

### ISSUE THREAD

**Issue by zoharar** [jgraph/drawio#1078]
there is an error 401 while trying to authorize the drawIO APP
see attached 

- [ ] [GIF](https://p66.f3.n0.cdn.getcloudapp.com/items/KourG7G2/Screen%20Recording%202020-08-03%20at%2010.12%20AM.gif?v=18d0a8c71fa541c9a118d10959857da0)

OSX 10.13.6 - chrome Version 83.0.4103.116

### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by davidjgraph** [comment]
No details provided, closing.
