### ISSUE TITLE
Unable to open svg with web version of draw.io

### ISSUE THREAD

**Issue by coupalm** [jgraph/drawio#1079]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

Save a draw IO document as svg into a OneDrive location
Open svg with Draw.IO windows client version from sync location : File open correctly
Open Draw.IO web version. Open the svg file in the OneDrive location: Error loading file (Not a diagram file (error on line 1 at column 1: Document is empty)

**Expected behavior**
Web version of draw.io should be able to open svg if client version is working.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**
draw.io web 13.3.0

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser : Edge Chromium
 - Version 13.5.7

**Comment by davidjgraph** [comment]
Could you try again on latest app.diagrams.net version?

**Comment by coupalm** [comment]
Same issue. I was using : https://app.diagrams.net/

[cid:image001.png@01D67572.B4B65CA0]

De : David Benson <notifications@github.com>
Envoyé : 3 août 2020 10:12
À : jgraph/drawio <drawio@noreply.github.com>
Cc : Martin Coupal <martin.coupal@outlook.com>; Author <author@noreply.github.com>
Objet : Re: [jgraph/drawio] Unable to open svg with web version of draw.io (#1079)


Could you try again on latest app.diagrams.net version?

**Comment by gadamiak** [comment]
Same here on 13.8.7. I'm saving and opening to/from OneDrive. While it saves correctly, the same drawing in SVG format can't be opened (File→Open from/Open recent) and returns an error:

> Error loading file
> Not a diagram file (error on line 1 at column 1: Document is empty)

When dragged and dropped into canvas it is imported correctly and can be edited.

PNG files are saved and opened correctly.

**Comment by gadamiak** [comment]
The issue is still present in 13.11.0. Still, when dragged and dropped into canvas everything works fine and the file is synced correctly.

Is there a chance to fix this?

**Comment by davidjgraph** [comment]
13.11.0 is 16 releases ago, could you check the latest?

**Comment by gadamiak** [comment]
Sorry for my ignorance, but how am I supposed to update a web app to the latest version? I'm simply going to app.diagrams.net and use it in my web browser. The `Help` menu says `About 13.11.0...`

**Comment by davidjgraph** [comment]
https://app.diagrams.net/clear.html forces an update (close all diagrams.net tabs first).

**Comment by gadamiak** [comment]
Done. This moved the web app version to `14.1.9` but didn't resolve the issue.

**Comment by phyrian** [comment]
Same happens for me using the newest web app version (`14.9.3`) and OneDrive. The .SVG diagram opens from local storage, but when I'm loading it from OneDrive I have this error:
> Error loading file
> Not a diagram file (error on line 1 at column 1: Document is empty)

The issue seems to be that the web app wants to open .SVG files as .drawio XML diagram files, eventhough both the Content-Disposition filename and the Content-Type header indicates that the fetched data from OneDrive is indeed an SVG image.

**Comment by phyrian** [comment]
Hey @davidjgraph ! I found the root cause and resolved the issue on my end. A PR was created with the fix and some details.
