### ISSUE TITLE
Bring back fast and easy text insertion

### ISSUE THREAD

**Issue by JesseAldridge** [jgraph/drawio#1080]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
<img width="156" alt="Screen Shot 2020-08-03 at 5 10 44 PM" src="https://user-images.githubusercontent.com/191903/89239185-5f1cc180-d5ad-11ea-9eb6-1c23db89a329.png">

I primarily use Draw.io create mindmaps which largely consist of text nodes connected by lines. I really liked being able to double click to insert new text nodes. When the new context menu was introduced at first I was annoyed, but then I realized I could triple click instead of double clicking and get the same behavior. Now in the lastest update the context menu appears to have moved a few pixels down and to the right so triple clicking no longer works.

These mind map diagrams are central to my work. I can easily create a hundred text nodes a day, so small changes to this UI action end up being a lot more disruptive to me than it might seem initially.

**Describe the solution you'd like**
I would appreciate it if the context menu could be moved a few pixels up and to the left so triple clicking works again. Or even better a way to get back to the initial behavior of double clicking to insert text.

**Describe alternatives you've considered**
The most obvious alternative is double clicking, moving my mouse slightly, and then clicking. A hundred times a day.

**Comment by alderg** [comment]
There was a problem with event handling on touch devices which we'll try to fix. Meanwhile, you can shift+dlb click to insert a text.

**Comment by JesseAldridge** [comment]
Oh nice, thanks.

**Comment by alderg** [comment]
We found a fix for the touch event issue. Triple click will be fixed in the next release.
