### ISSUE TITLE
Prevent accidental dragging, when on mobile

### ISSUE THREAD

**Issue by a-r-m-i-n** [jgraph/drawio#1083]
By default an item get moved instantly, when you touch it, on mobiles. An new navigation mode would be nice, which scrolls always. 

You could interrupt this behaviour and select an item with double touch/click, then. 

Also it would be nice, when pinching (two fingers) would be supported to adjust zoom factor.

Great app, thank you very much!
Armin

**Comment by davidjgraph** [comment]
what version are you using?

**Comment by a-r-m-i-n** [comment]
13.5.9

**Comment by davidjgraph** [comment]
Try with the latest.

**Comment by a-r-m-i-n** [comment]
I've just visted https://app.diagrams.net/

**Comment by a-r-m-i-n** [comment]
Now, it is 13.6.0, but I've got the same behaviour on mobile. When dragging with single finger. Double finger dragging and pinching works... But it seems to be impossible to drag (with two fingers) without zooming in/out.

**Comment by davidjgraph** [comment]
Double finger dragging and pinching works but seems impossible to drag with two fingers, I'm confused. Maybe you could re-state the current problem?

**Comment by a-r-m-i-n** [comment]
Now, when using two fingers, you can zoom (pinch). Also you can drag with this. But even when I try to not change the position of my fingers, it zooms in or out. Here a gap or something is missing to make pinching less sensitive.

Basically this works already pretty well :)
