### ISSUE TITLE
Zoom is tied to mouse cursor in published diagram after clicking links

### ISSUE THREAD

**Issue by cliffbell** [jgraph/drawio#1085]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
In a published diagram link (with lightbox active), clicking any two custom links will tie the zoom to your mouse cursor until you click again.  Happens in both Chrome and Opera browsers.  Occurs in any published diagram, including the one used by drawio as an example of how to make interactive diagrams (found [here](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=office-blueprint.html#Uhttps%3A%2F%2Fdrive.google.com%2Fa%2Fseibert-media.net%2Fuc%3Fid%3D1Cs90BgsIS4h6k2E8K6WdRqyCXPbQnHh0%26export%3Ddownload)).  Example diagram was pulled from [here](https://drawio-app.com/interactive-diagrams-with-custom-links-and-actions/), at the bottom of the article.

**To Reproduce**
1. Go to any published diagram, such as [this one from draw.io's own website](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=office-blueprint.html#Uhttps%3A%2F%2Fdrive.google.com%2Fa%2Fseibert-media.net%2Fuc%3Fid%3D1Cs90BgsIS4h6k2E8K6WdRqyCXPbQnHh0%26export%3Ddownload)
2. Click on any two custom links/"buttons".  In the example above, this behavior can be triggered by clicking on Lights twice.  You can also trigger it by clicking on "Furniture" and then on "Plumbing".  Any combination of two buttons triggers the behavior.
3. Move mouse cursor after the second click.
4. See error:  Zoom is now tied to your cursor, making the page impossible to navigate

**Expected behavior**
Custom links/Buttons should not force zoom to activate, and should not tie it to the mouse cursor

**Screenshots**
Gif of bugged behavior
![ZoomBug](https://user-images.githubusercontent.com/19594790/89335006-0a388400-d65d-11ea-97c0-c1a9c81d69e2.gif)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version:  13.5.9

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser:  Verified behavior on both Chrome and Opera
 - Chrome Version:  84.0.04147.105
 - Opera Version:  Opera 68

**Comment by mararad** [comment]
Hi,

I am not able to recreate this and our environment is almost the same (Win 10 Pro and Chrome Version 84.0.4147.105 (Official Build) (64-bit) but I tested on diagrams.net version 13.6.0 

Do you see the same behaviour in Incognito mode? If you do, could you update to 13.6.0 and tell me the result, please? 

Regards,

**Comment by cliffbell** [comment]
Hi Mararad,

Opening the diagram in Incognito mode does _not_ trigger the bug!  Tested both my own personal diagram and the one linked in the original case.  I hadn't considered the bug might be through one of my cookies, especially since I had not created nor published the example diagram on draw.io's article.

**Comment by davidjgraph** [comment]
What version does it show incognito?

**Comment by cliffbell** [comment]
Still the Official Build for Chrome (84.0.04147.105).

Went back and re-opened my diagram in the draw.io editor while in Incognito mode (after opening the published links, if that makes a difference).  Draw.io was at version 13.6.0

**Comment by davidjgraph** [comment]
There's an intended fix in 13.6.0, so if 13.6.0 works and anything before doesn't, I'd say that's fixed.

**Comment by cliffbell** [comment]
Cleared out my cache and updated to 13.6.0 on Chrome and it all works out now.  Appreciate the help!  Closing this out.
