### ISSUE TITLE
iframe edit "Save" instead of "Make a Copy" 

### ISSUE THREAD

**Issue by mlamie** [jgraph/drawio#1088]
- [X]  I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.

- [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When updating an diagram via the iframe method (see below options dialog) the updated diagram needs to be saved as a copy. This forces us to replace the iframe url every update. We would like to save the diagram maintaining the same iframe url.

**Describe the solution you'd like**
We would like to save the edits in the same file (iframe url).

**Describe alternatives you've considered**
Now we are force to update the iframe url each time an edit is made. Which is labor intensive.

**Additional context**
This is the support page https://desk.draw.io/support/solutions/articles/16000067789-how-to-embed-files-
![OS6PxV5qvu](https://user-images.githubusercontent.com/13729878/89406697-db361700-d71d-11ea-92b6-4418a4e0687a.png)

**Comment by davidjgraph** [comment]
This is for a diagram stored in Google Drive?

**Comment by mlamie** [comment]
Yes this is 

> This is for a diagram stored in Google Drive?

Yes

**Comment by ashrafteleb** [comment]
Did you try "Edit: custom" with default url (which opens the editor on the same file)

**Comment by mlamie** [comment]
> 
> 
> Did you try "Edit: custom" with default url (which opens the editor on the same file)

Thanks, that trick worked!!! Edits can be made and the iframe URL remains the same.
