### ISSUE TITLE
Why it got renamed to diagram.net

### ISSUE THREAD

**Issue by aavelyn** [jgraph/drawio#1090]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Hi there,

I'm working on a tutorial on draw.io, when I noticed that it got renamed to diagram.net. I couldn't find any official statement on why it got rename. Could you explain it shortly? Thanks!

**Comment by davidjgraph** [comment]
https://www.diagrams.net/blog/move-diagrams-net
