### ISSUE TITLE
Benable lines should fill

### ISSUE THREAD

**Issue by MuzzledLeader2** [jgraph/drawio#1093]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

I don't like the Add Shape... Freehand... options.  Shape requires code and freehand doesn't allow the poly to be edited.  Lines are amazing though.  I can bend them into any shape I want and connect the beginning with the end to make it look like a custom shape but.... I can't fill 👎   I can edit the svg code (developer tools in chrome) to make it fill so I know it's possible.  If it was possible to allow lines to fill we wouldn't need Shape... or Freehand... in most instances.
![noFill](https://user-images.githubusercontent.com/69303085/89521105-d1bcb580-d7d6-11ea-9d25-b724106bbae8.jpg)

**Comment by mararad** [comment]
Hi,

Filling bendable lines is not possible at the moment i.e it is not possible to "make" shapes out of edges. In your case polygon and polyline shapes from a library can be used.

**Comment by davidjgraph** [comment]
The freehand tool has a new brush option, https://twitter.com/drawio/status/1501886513327616003, they are filled polylines.
