### ISSUE TITLE
element under another selected with Alt+click is not editable or movable

### ISSUE THREAD

**Issue by kgignatyev** [jgraph/drawio#1095]
### Preflight Checklist

* [ X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.
similar one is https://github.com/jgraph/drawio/issues/976

**Describe the bug**

To Reproduce:

1. create new diagram
2. create a rectangle and remove fill
3. create a text 
4. place text under rectangle
5. select text with Alt+Click

===
Now the element cannot be moved with mouse (although reacts on arrow keys)
Text cannot be edited
~ Side panel shows the element, but clicking 'To Frong' on Arrange tab has no effect, the text remains under rectangle 
(on more complex diagrams, seems to work on simple one as this test )

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 13.5.7] desktop version

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] OSX 10.15.6

**Comment by mararad** [comment]
Hi, 

could you attach a saved diagram please so I can test it directly? Or click Extras > Edit diagram and copy/paste code here.
At my place editing is working so I want to be sure I repeated your steps.

Regards,
