### ISSUE TITLE
link to another page in the project is not working when exported to pdf. I want to link a shape to a different page and it works on the app itself but when exporting to pdf it isn't there and not working.

### ISSUE THREAD

**Issue by wellbeingtool** [jgraph/drawio#1099]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wellbeingtool** [comment]
Hello David,
I just checked the linking feature and it's not yet working. Plus, I'm new here so I don't really understand the reason for the closure of this ticket. Is it done? did I forget to add something?
Thank you in advance for your efforts

**Comment by davidjgraph** [comment]
Hi, you didn't fill in any of the template so it was closed.

**Comment by wellbeingtool** [comment]
got it thanks. I created a new feature request as I understand that what I'm asking for is a feature more than a bug to fix. I made sure to complete the template this time :D
