### ISSUE TITLE
Door are not showed properly after upload visio document

### ISSUE THREAD

**Issue by nksiddu** [jgraph/drawio#1100]
I uploaded visio with proper placement of door using microsoft, uploaded the same file in draw.io but didnt get proper result. Can you please suggest what I am doing wring?

Please find attachments

![](https://i.stack.imgur.com/CmR4F.png)

![](https://i.stack.imgur.com/QYldh.jpg)

Please find link to original document: https://drive.google.com/file/d/1UP71eAbE-mEiw9Z8KhYPJeryBf5pBxHt/view?usp=sharing

**Comment by davidjgraph** [comment]
[IV.02.02.PLAN.02 - Grondplan flows Antwerpen versie.vsdx.txt](https://github.com/jgraph/drawio/files/5041052/IV.02.02.PLAN.02.-.Grondplan.flows.Antwerpen.versie.vsdx.txt)

**Comment by mararad** [comment]
Issue reproduced. 

P.S Meanwhile a user was advised to use door shape from our library after file import as a workaround (https://webapps.stackexchange.com/questions/144093/door-are-not-showed-properly-after-upload-visio-document)

**Comment by ashrafteleb** [comment]
This requires group flipping which is not currently support
