### ISSUE TITLE
[Feature request] Support move single step front or back

### ISSUE THREAD

**Issue by imageslr** [jgraph/drawio#1103]
* [-] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [-] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Currently draw.io only support bring a layer/component front or back completely.  Suppose I want to move a layer A under B, but above the background layer C, it'd be nice if I can only move a layer single step back. 

Thanks.

**Comment by mararad** [comment]
Hi,

If you drag that layer and drop it where you like, does it help?

Regards,

**Comment by imageslr** [comment]
Sorry it doesn't help. For example I have two stacked layer A and B, if I want to put the layer C between A and B, I cannot do this by drag and drop, because C will alway cover A or C.

Thanks.

**Comment by imageslr** [comment]
Here is an example. I have four stacked layers:A, B, C, D. I want switch B and C.

I can't do that by only dragging and dropping.
![image](https://user-images.githubusercontent.com/17822028/91119693-69227380-e6c6-11ea-9039-8663b930d789.png)


I have to first move A, B, C to front, then separately move B, C, A to back. This is kind of like poping and pushing a stack.
![image](https://user-images.githubusercontent.com/17822028/91119758-a0912000-e6c6-11ea-83dc-3fc14e3fb994.png)

If there were two buttons "move step front" and "move step back",  I could simply switch B and C by on click.

Thank you.

**Comment by mararad** [comment]
Hi,

![layers](https://user-images.githubusercontent.com/44292306/91166637-f53a9800-e6d2-11ea-808e-e0ad7dad58fa.gif)

Does this help? Regards,

**Comment by imageslr** [comment]
Yes! That helps. Thank you so much.

**Comment by borekb** [comment]
Hi, I'm a relatively light user of draw.io and came here to say that I agree with the OP and that sending an object one step to front or back was a natural feature I was looking for.

"Workaround" via layers is interesting (I didn't know draw.io has layers!) but I think z-order should be doable step by step, similarly to all other "object-based drawing apps" that come to mind, like Excalidraw, Balsamiq, PowerPoint, Google Slides, Visio etc.

**Comment by imageslr** [comment]
@borekb  I can't agree more! I will see If I could make a PR to fix it, or fork a new version.

**Comment by hashwagon** [comment]
I see the value in layers, but I agree that having to rely on layers for simple ordering of the stack another _layer_ of work.

**Comment by michaeljfazio** [comment]
Upvote. This is probably the single most frustrating thing that is missing from drawio for me.

**Comment by Bastesque** [comment]
A single step forwards or backwards has the advantage that you can also use guides. If you are creating a layered onion-like diagram with circle shapes, you always like to make sure that all the parts of the diagram are perfectly alligned in the center. If all of these shapes are on the same layer, you can achieve that with the blue horizontal and vertical guides. You don't have this option if you are working with shapes on different layers.

**Comment by davidjgraph** [comment]
Single step back and forth added in 14.8.0.

**Comment by imageslr** [comment]
Thanks！

**Comment by iddhbaptista** [comment]
Is there possible to use To Front and To Back by action link for moving elements with some tags to front or back?
