### ISSUE TITLE
Organize sheets in folders or tree format

### ISSUE THREAD

**Issue by Raymondma-public** [jgraph/drawio#1105]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
It is not related to any bugs. But it is hard to organize for more than 10 sheets as tags.

**Describe the solution you'd like**
I hope 
1. sheets can be organized in a folder/tree format.
2. able to search sheets with sheet name
It will be much more easier to organize more sheets.

eg. 
+topic1(folder)
---Sheet 1
---Sheet 2
+topic2(folder)
---Sheet 3
---Sheet 4

**Describe alternatives you've considered**
The sheets can be not shown in tree view but show in another window as file system.

**Additional context**
![image](https://user-images.githubusercontent.com/11516250/89857108-b7ffe180-dbcd-11ea-8c4d-529421a5e78c.png)

**Comment by chris13524** [comment]
Please reopen :+1:
