### ISSUE TITLE
[jgraph/drawio] Pdf exports - only blank page appears

### ISSUE THREAD

**Issue by rlemonn** [jgraph/drawio#1106]
Describe the bug
When exporting .pdf, any page exports totally blank.

To Reproduce

Go to 'File'
Click on 'Export as'
Select 'Pdf'
Select 'Current page' unselect other options
Click 'Export'.
Select 'Download'.
Open downloaded file with any pdf reader
Expected behavior
Pdf opens with exported flowchart.

draw.io version (In the Help->About menu of the draw.io editor):

draw.io version: 13.6.2
[Organigrammes.zip](https://github.com/jgraph/drawio/files/5060016/Organigrammes.zip)

Desktop (please complete the following information):

OS: iOS
Browser: chrome
Version: 83

**Comment by rlemonn** [comment]
Here's the results when exporting one of the file attached to my last comments.
[Reseults.pdf](https://github.com/jgraph/drawio/files/5060021/Reseults.pdf)

**Comment by mararad** [comment]
Hi,

* if you repeat all the steps in Incognito mode, is it working? If yes, then clear cache and temporarily disable all browser extensions in Chrome and check the result.

* another suggestion would be to try File > Print > click "Print" > choose Print to PDF or/and Save as PDF

P.S I tested this at my place and all is working well but I use Win 10. Sometimes only first page shows as blank so check all pages down

Regards,

**Comment by rlemonn** [comment]
Hi,
I have tried that on the web version and it works perfectly fine.
When I tried it using the Desktop version of Draw.io/Diagram, it stills displays as blank file.
Can you take a look with my graph up above?
Thanks

**Comment by ashrafteleb** [comment]
Fixed, will be available in the next release
