### ISSUE TITLE
Question: is it possible to embed and pre-create diagrams?

### ISSUE THREAD

**Issue by joshxyzhimself** [jgraph/drawio#1107]
I've seen the following links

- https://github.com/jgraph/drawio-integration
- https://desk.draw.io/support/solutions/articles/16000042544

But is it is only for embedding the page..

Is it also possible to programatically create diagrams that the user will see?

Thank you very much!

**Comment by ashrafteleb** [comment]
You can use mxGraph project https://github.com/jgraph/mxgraph
