### ISSUE TITLE
Mathematically typesetting has a large min height within a table

### ISSUE THREAD

**Issue by n-gao** [jgraph/drawio#1109]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
If one adds mathematically typesetted text to a table cell, the text is cutoff if the cell does not have a certain height.

**To Reproduce**
1. Enable Mathematicall Typesetting in Extras
2. Place a "Table 1"
3. Enter $$x$$ to a cell
4. Set the cell height to 20

**Expected behavior**
The text should be correctly centered within the cell.

**Screenshots**
![image](https://user-images.githubusercontent.com/9084670/90007237-aafcf400-dc9a-11ea-9866-3a6aada09ab1.png)
The lower one is a table and the upper one is a rectangle with the same height and content.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.6.2
This also happens in the desktop version

**Desktop (please complete the following information):**
 - OS: Windows 10 2004
 - Browser Chromium Edge
 - Version 84.0.522.58

**Comment by mararad** [comment]
Hi, could you attach a file, please?

**Comment by n-gao** [comment]
Here you go:
```xml
<mxfile host="app.diagrams.net" modified="2020-08-12T10:51:43.742Z" agent="5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 Edg/84.0.522.58" etag="M3wq0Y_HzkycufZ5v-3G" version="13.6.2" type="device"><diagram id="Rj3teL5vWTeMD2Z3J5Pa" name="Page-1">7ZbbjtMwEIafJpeLcmhKuW22sEggoS0CiTtv7SZGjic40ybl6Zkkk6ZR26Vod6mQkKLW/j0e2/83OXhRktfvnCiyjyCV8UJf1l5064VhPH1Dv42w64TIjzshdVp2UjAIS/1TseizutFSlaNABDCoi7G4AmvVCkeacA6qcdgazHjVQqTqSFiuhDlWv2qJWafOYn/Q75ROs37lwOeRXPTBnKLMhISqk9qYaOFFiQPArpXXiTKNd70vXaK3Z0b3G3PK4iUTIvtJ3H2pvt/b9/W3INreSPPjJph0abbCbPjEvFvc9RbQxoumieKhkeYZ5oa6ATWrTKNaFmLVjFdUAKSVKBwySJ/6RAaFtsrxnBUYI4pSt8m6iEwb+UHsYIP9Mn1vzttTDlV99uDB3k4qQwW5QrejEJ4QTrjkuASDCSOqBqDBjLXsACYb6guuoXSferCZGuz0n7geX+46nRO1MPdU3MKmlwA4Nlg6KD4LlypkoQBtUbnFliwsWVtrYxIw0HCyYJuFEAoeNGrdz30ARMi549itfdLWqnhOF5mX+K9iL6bTJNQPhj5dTbjDBGyJjqqjyaFEiZUqL6b+SEEf18L1WE9PsKZNTrD7e1bw7TNQDOCfzBSIwdq0j61MS6ns0+DEv4Uz/atsXr/sffiP4qjHKK5GZ/afznk6QXhlPOGpm+exB5uDjZVKslmnmBwge4n3fnDsWBw/i2PUHT7k2rGDr+Fo8Qs=</diagram></mxfile>
```

**Comment by mararad** [comment]
Thanks. Reproduced in Chrome and Win 10. 

It is like 12 pt letter can't fit to 20 pt high cell. It is ok when cell height is larger or letter size is smaller.
