### ISSUE TITLE
Electrical connectors and/or pins

### ISSUE THREAD

**Issue by endolith** [jgraph/drawio#1113]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'd like to draw cable wiring diagrams and subcircuits

**Describe the solution you'd like**
There should be symbols for connectors and generic pins or terminals that connect to external circuits

**Describe alternatives you've considered**
The "test point" is similar, but that's the only option I see in the current library

![image](https://user-images.githubusercontent.com/58611/90148558-71d38b00-dd51-11ea-81c9-d62bc1997ca8.png)

**Additional context**

# Generic connector examples:

![image](https://user-images.githubusercontent.com/58611/90147970-cde9df80-dd50-11ea-9795-e3ae1341fb5e.png)

![image](https://user-images.githubusercontent.com/58611/90148027-df32ec00-dd50-11ea-8a11-2dc81492fced.png)

# Generic pin examples:

![image](https://user-images.githubusercontent.com/58611/90146687-56678080-dd4f-11ea-8a83-0c3c4c10920c.png)

![image](https://user-images.githubusercontent.com/58611/90147552-52882e00-dd50-11ea-84b2-cbd2558b70e3.png)

![image](https://user-images.githubusercontent.com/58611/90147593-5c119600-dd50-11ea-9ffb-66099968f31e.png)

![image](https://user-images.githubusercontent.com/58611/90147830-a0049b00-dd50-11ea-83b3-8399bdbee9be.png)

# Wiring diagram examples:

![image](https://user-images.githubusercontent.com/58611/90148257-215c2d80-dd51-11ea-9d5e-443f7c73b9de.png)

![image](https://user-images.githubusercontent.com/58611/90148320-36d15780-dd51-11ea-92c3-a2457ec8e34f.png)

![image](https://user-images.githubusercontent.com/58611/90148339-3c2ea200-dd51-11ea-861f-f03adef16ffd.png)

![image](https://user-images.githubusercontent.com/58611/90148371-4355b000-dd51-11ea-92d9-0b6980b9d0e7.png)

![image](https://user-images.githubusercontent.com/58611/90148603-7ef07a00-dd51-11ea-8f3f-b7defc958d2c.png)

**Comment by mararad** [comment]
Hi,

if you click "More shapes" and choose "Electrical" does it help? Are there shapes you would like to have and use?

Regards,

**Comment by endolith** [comment]
> if you click "More shapes" and choose "Electrical" does it help?

No, that's where I got the "test point" shape from

> Are there shapes you would like to have and use?

Yes, something like the ones I showed in the examples above.  Generic multi-pin connectors and/or generic single pins

**Comment by warwickchapman** [comment]
Also looking for a method of doing diagrams reflecting pinouts eg.

![image](https://user-images.githubusercontent.com/6004561/211247744-ee304c4c-07a4-47a6-b802-8b1b84f4b495.png)
