### ISSUE TITLE
Show front shapes when draging to resize back shapes

### ISSUE THREAD

**Issue by FajunChen** [jgraph/drawio#1116]
*  [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.

* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I want to resize a filled shape in back, filling is the default setting, all shapes in front of the back shape would disappear. I intent to resize the back shape according to the location of front shapes, however, I can't do it when they just disappeared. 

**Describe the solution you'd like**
When resizing a filled shape in back, the shape should be set with a proper alpha value temporally and has transparent effect, in order to keep shapes in front visible.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
