### ISSUE TITLE
Future Sandstorm platform change will impact draw.io

### ISSUE THREAD

**Issue by ocdtrekkie** [jgraph/drawio#1118]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I am filing issues to notify of future breaking changes. Specifically, client-side loading of external scripts is blocked in the following PR: sandstorm-io/sandstorm#3409

It seems in testing that draw.io loads MathJax from a CDN (at least, as of the last Sandstorm release), so rendering of mathematical formulas might be broken after this security change. We're aware the Sandstorm package is very out of date and not presently actively supported by JGraph, though I thought we should let you know.

I also thought you might want to know there is some community interest in updating this package: https://groups.google.com/forum/#!topic/sandstorm-dev/OIseYP24pBI

I actually notice that the MathJax JS file appears to have been added to this repo, so I'm guessing that an updated version of the package might alleviate this inherently.

**Comment by davidjgraph** [comment]
Yeah, we bundled a stripped down MathJax a while back, so an updated version would get around this issue.

I'll close this issue and answer on the GG thread.
