### ISSUE TITLE
Double click drawio file open empty page

### ISSUE THREAD

**Issue by wiryonolau** [jgraph/drawio#1119]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Opening .drawio file shown as empty Untitled page

**To Reproduce**
1. Double click drawio file or right click and and choose open with drawio

**Expected behavior**
Drawio should read the file and load the diagrm

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [13.6.2]

**Desktop (please complete the following information):**
 - OS: [Xubuntu 18.04.4 using **snap**]

**Additional context**
- None

**Comment by GauravMehra1996** [comment]
I have the same problem. I'm using Ubuntu 20.04lts. The diagram opens perfectly in windows but it shows empty file when opened in Ubuntu.
