### ISSUE TITLE
Set as Default Style on Directional Connector not applying.

### ISSUE THREAD

**Issue by Eddie-Hartman** [jgraph/drawio#1122]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
"Set as Default Style" button does not appear to work for the "Directional Connector"

**To Reproduce**
1. Create a new diagram on draw.io.
2. Create a "Directional Connector" located under General.
3. Change the line style from Rounded to Sharp and change the Waypoints style from straight to orthogonal.
4. Click "Set as Default Style"
5. Create another new Directional Connector, it will not have that style.

**Expected behavior**
The style is saved as default so that when you create new ones you don't have to modify the style again.

**Screenshots**
Setting the default style and applying:
![image](https://user-images.githubusercontent.com/14089997/90694849-54b62500-e247-11ea-8241-bde4caa08937.png)

After creating a new directional connector:
![image](https://user-images.githubusercontent.com/14089997/90694903-6a2b4f00-e247-11ea-9227-f00816a814c3.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.6.3

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome and Firefox
 - Version Browser and OS latest.

**Additional context**
I'd also like to save this as the default to the file so that when others modify the file, it becomes their default as well.

**Comment by mararad** [comment]
Hi,

if you add a shape, connect it with another shape, change to Orthogonal and click Set as default style, will this reflect to another shape you add? What I mean, try with creating a small diagram instead putting a separate connector into the editor.

Does it work that way?

Thanks,

**Comment by Eddie-Hartman** [comment]
It does work that way. That is good enough for me as a workaround, but I don't feel that it solves the real problem because I have to make more connections as I go. Thank you.

**Comment by Eddie-Hartman** [comment]
UGH sorry I kept seeing the reminders, but they kept coming in at inconvenient times where I couldn't comment as I was already busy.

Anyway, as far as I know this issue was never fixed or even acknowledged. Not sure if it should be closed. I just found a workaround.

@davidjgraph (just trying to ping anyone to get it to the right place)

**Comment by iamperson347** [comment]
I'm hitting this issue on the latest version. 

Latest draw.io desktop version diagrams.net 20.8.16

**Comment by hartmut27** [comment]
i can reproduce this issue in drawio version 21.8.2  (drawio-deskop-bin, Archlinux AUR, Manjaro Xfce)

**Comment by davidjgraph** [comment]
Fix in 22.1.8.

**Comment by Sc0r** [comment]
thanks David. Standard-Style now applies color, pixel size, line beginning/end, but not connector type. 

Though, if you try to change the default the connector type to = instead of →, it currently still needs a workaround.
