### ISSUE TITLE
File is not being saved in drawio

### ISSUE THREAD

**Issue by allain1203** [jgraph/drawio#1123]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**
1. Open a file in drawio
2. Edit it
3. Try to save it

**Expected behavior**
The edit is not being saved and it's taking a timeout.

**Screenshots**
![screenshot-www draw io-2020 08 20-14_34_34](https://user-images.githubusercontent.com/69955417/90725334-96e87080-e2f2-11ea-953c-1330e0004201.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.6.3

**Desktop (please complete the following information):**
 - OS: macOs 10.14.16
 - Browser Chrome
 - Version 84.0.4147.125 (Official Build) (64-bit)

**Comment by davidjgraph** [comment]
Google Drive is having an outage, you can follow https://www.google.com/appsstatus#hl=en&v=status
