### ISSUE TITLE
Cannot import SVG via URL

### ISSUE THREAD

**Issue by 0xTL** [jgraph/drawio#1124]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Importing a SVG via URL does not work. Instead of the graphic, only the text content is shown in the editor

**To Reproduce**
1. Go to [https://app.diagrams.net/](https://app.diagrams.net/)
2. Click on 'File', 'Import From', 'URL...'
3. Use URL to a SVG, for example [https://upload.wikimedia.org/wikipedia/commons/a/a0/Firefox_logo%2C_2019.svg/](https://upload.wikimedia.org/wikipedia/commons/a/a0/Firefox_logo%2C_2019.svg/)
4. Rectangle is inserted but only showing text instead of graphic

**Expected behavior**
Graphic to be shown

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 13.6.3

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 68.0.1

**Comment by ashrafteleb** [comment]
You can use Arrang -> Insert -> Image... to add SVGs to the diagram from a URL as a workaround
