### ISSUE TITLE
No custom ID numbering option

### ISSUE THREAD

**Issue by parthi2929** [jgraph/drawio#1125]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The [animation plugin example](https://www.draw.io/?lightbox=1&p=anim&edit=_blank#R7VrbkuI2EP0aHuPSxdfHHQZ2U5VUpmo2leRRgzVYO8aiZDFAvj6SLYOEMJeFmd2p4AcKteRuSX1Od0swwMPZ6rMg8%2BJ3ntNygEC%2BGuD7AUJJFKpPLVi3Aghj3EqmguVGthU8sn%2BpEQIjXbCc1s5AyXkp2dwVTnhV0Yl0ZEQIvnSHPfPStTonU%2BoJHiek9KV%2FsVwWrTRF8Vb%2BhbJpITfry9qeJzJ5mQq%2BqIy9AcLPzdN2z0inyyy0LkjOl5YIjwZ4KDiX7bc%2Fayr%2BePqm14hASZ7UPhu9zVIrpjQyXrXCulCqEAj1iklOB3q6WG0pvjM9sd%2BzJEyrjgDwh%2BPzhie9drPenrTXBAT7bEB48khwruo9u9N1Rf1dqL%2Brf%2F96ZpDskaX%2B27h5WxvuyLSFzmw1pKUi47htqi8WhJwRgO1yQtBK2ugc97xg2P1KygW14VjLdUegZcEkfZyTiW4vVZBQsy%2FkTKMXNoszsG9WKgV%2F2fAsVJJnVpZDXnLRKFOyERxHWs4raYKF8ha%2BIyWbauxP1MSpGnw3FSRnqmG9bOjXmel6Kl4pNXf%2B0s1uvFIh6coSma34TPmMSrFWQ0xvanyxdpvLbdwIO3cVVsyIEyMkJlZNN5qR7T6z%2B%2Fs9ER%2F3hHpBRU3abvpcCyclX%2BQaTdf00bh5jrjgqP%2FeykcQQsdJEPpewjDzvQSv4aXI89KYC2rSxJnc0zFi18O5yl2myYUs%2BJRXpBxtpXeNJZobX%2Fb5mFb5J507VfOp5JOXrwWrWvGYld0b36iUa%2BNDspBcibY2f%2BN83ml2AION88dkxkrtgy%2B0fKWSTcgOKtK9qDDAfS7pysxwP1J2MAlAHA%2BH7RK6mTS4U21jMApCpKlgerX5mi%2FEhD5QwZSjqdAEYdVUdf6C9sN7E558XxrPtyqNA00lJImYUjPM%2BFQ78hQ0Y4ADjFQO7p7IAXcYRkGErSfuh7Cx8cBZJS0DGDkaoxAHwHqQq9DsWKvDxu6O2hBgR20cJoE9z8hV2%2B6Qp1YhgKytYXM9oO5fTBi6ARpm6Q55W41bKm92%2FCR2w%2FTGyI%2FNSHQ5I%2BFhRkaXMjKMwA51skPUOZWROM6CFMEQpVGiP8PQsdLU529ASYjelpLYS7hfC6qzPdHwVcfG9USxcJe1qpaQO2Q8Bmkj8vihKxNFpfKT6ZixPG94v6%2Fm4mr0c9mwvFDjaLUbBiw6orRrm3nDQzzuhf8ZlVPkxmwI%2FMoJxXvq2%2FAKhVPi%2BXHIVdis6vbQi%2BJSO%2BxJuTSe6m8qOirn6vK29ry7jbjwotoXHTifHKt9jwVbFB4vipXO8D7LALDs3TOhjnftPcCS1vJKrs%2BSIDGBof10kRCDANkP9oABYxQA7GuwcZKEQWw%2F2eWwST3YPKj9YXMmDW5u0HhbaOA9x6sfhIXsYHFm4vetGrtaNZaTuthQ6aTyK%2FGrr%2FTE6kvQUjH61b20vQQtHW6t0PFrpXZNChM5hn7SEYuKd%2Fe77xRUolHa3MH8r4JKqPKNXfLi5GeJMd3l0i3IvFOQoSsm%2F9YbFkSm9c85ESf1I05H%2FFMPfCiBBw98OL3wwHehgVMPgChJg9SmjHsADBMQpNaTJa6ZnvPg99yiIP%2FMJkhVz5m4FW3Xia%2BZe6kXY%2Ff2Lfxpwql%2FfB%2B9kjm%2FAeFKQMAQBlm8cWqUfBBcRJ7vbxet75h1T8qtXSJ1kis6M7mmh29T0aW3qShzfw7E2femz0zlxzhT6RgkAMeom4qVPt%2F%2BBw61IY7VKEkOThom%2BND4y38QiW88%2FZg8xWfyNDvMU3wxT6MdZF%2Fnd0iY%2FojfITE6j6Y4uypNVXP7t7J2%2BPa%2Fe3j0Hw%3D%3D) show the shapes having numbered IDs but when any shape is created that is not the case. I searched every where online about draw io but could not find any way to get numbered IDs for the shapes. So I think this is a bug probably. 

**To Reproduce**
1. Create a shape
2. Right click and go to "Edit Data"
3. There you see random jumbled letters as ID. 
![image](https://user-images.githubusercontent.com/11896263/90729489-4a963400-e2e4-11ea-81bb-ee83fa2aa41e.png)

**Expected behavior**
1. For writing animation script in readable short format, we need numbered IDs. This is from drawio's animation example. 
![image](https://user-images.githubusercontent.com/11896263/90729548-63064e80-e2e4-11ea-8a3a-99aae0179c46.png)
2. You could then see how this ID is used for animation script as shown below. 
![image](https://user-images.githubusercontent.com/11896263/90729612-7d402c80-e2e4-11ea-94a2-cfaedec58df8.png)

**Screenshots**
They are added above for context. 

**draw.io version (In the Help->About menu of the draw.io editor):** 

- 13.6.2

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 10
 - Desktop App 

**Smartphone (please complete the following information):**
NA

**Additional context**
The ability to have custom/numbered ID is important for animations. I tried creating another shape in animation example itself which also resulted in jumbled letters for ID. I could not find any option to change them.

**Comment by ashrafteleb** [comment]
The ID must be unique for collaboration to work with no conflicts. The number after the random characters is sequential 'xyz-1', 'xyz-2', ...

**Comment by parthi2929** [comment]
Can we then have option to achieve uniqueness by simply auto numbering shape IDs. This will help a lot in handling the shapes via script like in case of animation. Thus that would be a good scalable solution as well Imho. Or, custom alias ID option to use for purposes like this.

**Comment by ashrafteleb** [comment]
You can have that only on self-hosted draw.io
You can set `graph.model.prefix` to empty string to get auto numbered ids with no prefix

**Comment by parthi2929** [comment]
Ok but the current ID form prohibits many possibilities like animation for many users, so can this be planned for the diagrams.net version?  Difficult to pursue self host option  just for this purpose.

**Comment by davidjgraph** [comment]
We can add this as a feature request, then anyone interested in implementing can do so.

**Comment by Hicsy** [comment]
as per twitter - you can now rename an ID in web-editor by CMD/CTRL+DoubleClicking it.
Not sure of the equivalent magic-combo for desktop version

**Comment by marcelobesch** [comment]
> [as per twitter](https://twitter.com/drawio/status/1391737783459405826) - you can now rename an ID in web-editor by CMD/CTRL+DoubleClicking it. Not sure of the equivalent magic-combo for desktop version

This is not working. Was the feature removed?

**Comment by alderg** [comment]
Try Shift+Double click.

**Comment by thecodewarrior** [comment]
For anyone in the future who comes across this, you have to double-click (no modifiers) on the ID in the edit data panel (at least on desktop on macOS). I initially tried shift+double click on the object itself, but that just selected the text in the object.

https://user-images.githubusercontent.com/5467669/222522228-0728978d-1aef-40dc-b609-91198b5f6978.mp4
