### ISSUE TITLE
Issue importing image is blurry and compressed

### ISSUE THREAD

**Issue by drakonkat** [jgraph/drawio#1126]
Draw.io automatically resize big image to lower resolution. How i can setup to paste image in high resolution? I have found no settings...

**Comment by daisuke-yoshimoto** [comment]
@davidjgraph @mararad @davidjgraph 
I have fixed a bug related to this issue.
https://github.com/jgraph/drawio/pull/1214

**Comment by telusomara** [comment]
ctrl-click might work;  for me it resulted in a dialog saying "image to big".  It was a screenshot from my Mac.  :(
