### ISSUE TITLE
Constant Prompt to save project after each single move of anything on the board.

### ISSUE THREAD

**Issue by dramyrez** [jgraph/drawio#1127]
### Preflight Checklist

* [ yes] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [yes ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Constant Prompt to save project after each single move of anything on the board.
**To Reproduce**
1. Go to 'draw.Io'
2. Click on 'Create new Blank project'
3. add Item and click and move anything

**Expected behavior**
I would like for this not to be prompting me every single time I move a small piece. 

**Screenshots**
![image](https://user-images.githubusercontent.com/70021902/90897268-29f1db00-e3c5-11ea-8838-8e235f717d59.png)
![image](https://user-images.githubusercontent.com/70021902/90897347-47bf4000-e3c5-11ea-9fe3-49a8e37be8bd.png)
**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.6.4

**Desktop (please complete the following information):**
 - OS: Windos OS 10 
 - Browser chrome,
 - Chrome 84.

**Additional context**

**Comment by mararad** [comment]
Hi, 

I am not able to reproduce this. 

My initial advice would be to repeat all the steps in a different browser and Incognito mode. Also, clear the cache and temporarily disable all browser extensions.

Incognito mode is great for testing cause it is cache and extension free (cache and extensions can cause some problems sometimes) and I see that you have some extensions installed. 

If nothing help, try to open it via https://app.diagrams.net/

Where did you save a file initially?

Regards,

**Comment by dramyrez** [comment]
Hi,

This only happens when my file is saved local on device and once I open it, every time I move a piece it still continues to prompt me to save.......every single time......

So to replicate, adding to the test:
- Create a file with a couple of items on it.
- Save on device
- Close draw.io 
 - Open again the draw.io and the specific document saved in your device.
Please check and advise if you managed to replicate + using these steps.

thanks,

Dragomir

**Comment by mararad** [comment]
I am still not able to reproduce this. Could you update it to the the latest version 13.6.5 and tell me the results?

If this doesn't help, could you confirm you have the same problem in Incognito mode and other browsers 
and that you tried in https://app.diagrams.net/ (not https://www.draw.io/

If nothing helps, is it possible to send a video showing all performed steps, please?

Thanks,

**Comment by greenseeker** [comment]
Dealing with this on app.diagrams.net in Chrome 103 right now.
