### ISSUE TITLE
draw.io is reaching out to `js.pusher.com` similiar to #407

### ISSUE THREAD

**Issue by MikeHofmann** [jgraph/drawio#1128]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
draw.io is reaching out to `js.pusher.com` similiar to #407

**To Reproduce**
We installed draw.io inside a dark site without internet connection. Inside this site we also have a on-premise installation of gitlab.com. Integration of draw.io and our local installation of gitlab was without issue. However accessing the local installation of draw.io (running using the docker-image) it is apparent, that draw.io tries to reach out to `js.pusher.com` but will fail eventually (because no internet).

Like in #407 we just can't set `stealth=1` as this disables the storage option for our on-premise gitlab installation as well. 

**Expected behavior**
Would like to see an option to disable each external service via the server-side configuration options (like in `PreConfig.js`). So that i can disable unwanted storage options and everything else `stealth=1` does (like disabling `js.pusher.com`) on an per-option base. 

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version `13.6.2`

**Desktop:**
 - OS: Ubuntu 20LTS
 - Browser chrome
 - Version `84.0.4147.105`

**Additional context**
Using the docker-image `jgraph/drawio:latest` with digest: `sha256:7561cd562fc1b8935faff5886c635f7614a71d57b3eae5a3d9680972e05fa0e4`

**Comment by ashrafteleb** [comment]
Do you have `DrawioFile.SYNC = 'none'; //Disable real-time sync` in PostConfig.js?
Did you use https://github.com/jgraph/docker-drawio/tree/master/self-contained?

**Comment by MikeHofmann** [comment]
Sorry, missed the mail notification.

> Do you have DrawioFile.SYNC = 'none'; //Disable real-time sync in PostConfig.js?
No, this isn't set

> Did you use https://github.com/jgraph/docker-drawio/tree/master/self-contained?
Partially. I just added `DRAWIO_SELF_CONTAINED: 1` to my docker-compose.yml and moved to a newer image. Problem went away, so closing this
