### ISSUE TITLE
Support for files larger than 4MB in OneDrive / SharePoint

### ISSUE THREAD

**Issue by DanielSmon** [jgraph/drawio#1132]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.
Yep, searched for _4mb_, _4 mb_, _onedrive,_ and more.

**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
We're storing our diagrams in SharePoint (via the OneDrive integration), and make use of screenshots for storyboarding. We'd like to be able to add more screenshots and continue to use SharePoint, but are hitting the 4MB upload limit.

**Describe alternatives you've considered**
Still exploring alternatives such as using Azure File Storage to map a "network drive" or similar. Manually uploading to SharePoint will not work for us and would lead to user confusion.

**Additional context**
The 4MB limit is because this is the limit sending a PUT using the MS Graph API as indicated in the following comment: 			https://github.com/jgraph/drawio/blob/4fe8c180696d13ee582b7ba69d4606ddf8cd269b/src/main/webapp/js/diagramly/OneDriveClient.js#L913-L920

The message shown is:
![image](https://user-images.githubusercontent.com/5592071/91175753-9d2c8180-e724-11ea-9ce1-122673877189.png)

The following StackOverflow post seems to describe using the an upload session to upload more than 4MB: https://stackoverflow.com/questions/56335586/upload-file-4mb-to-onedrive-using-graph-api

Storing files larger than 4MB would be really useful for us and we'd be really grateful for this enhancement! :)

**Comment by ashrafteleb** [comment]
Support of large files added. Will be available in the next release
