### ISSUE TITLE
FEATURE request: periodic save

### ISSUE THREAD

**Issue by HeeroYui** [jgraph/drawio#1135]
The autosave will save every change done in the diagrams, but when the diagram is too big or contain big images, the user experience is impacted.

Is is possible to add a mode of periodic saving (every 5 minutes) for example?

Thank you (for reading my English) and all your works.

**Comment by davidjgraph** [comment]
How big are diagrams when this happens? Where are you storing them? Do you have slow/high latency Internet connection?

**Comment by HeeroYui** [comment]
The diagram have image inside and the end size is nearly 6MB
I store it locally then no problem with network or bandwidth with the SSD.
I store the data compressed (seem having more problem when non-compressed)
I have the problem 6 month ago (just reported) and the experience is really better now. But it is still visible (not critical).

Method to reproduce:

  - New diagram
  - Add some images (3) @4000x4000 (fast way to show the problem)
  - add some 4 square on the top of the image
  - Test 1:
    - link square 1 with square 2
    - with no wait link square 1 with square 3
    - **here you will see the latency**
  - Test 2:
    - Disable auto-save
    - link square 1 with square 2
    - with no wait link square 1 with square 3
    - **no latency show**

**Note:** when just editing or moving square I do not show the latency. it is maybe link with adding or removing elements

**Comment by davidjgraph** [comment]
I don't understand where to store it to see the problem from your description.

**Comment by HeeroYui** [comment]
?? I store it on local HDD computer.

Note: I use the desktop plugin in chrome.

**Comment by HeeroYui** [comment]
seems to be OK
