### ISSUE TITLE
Cannot move waypoint on connector

### ISSUE THREAD

**Issue by martywesley** [jgraph/drawio#1137]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
One of the waypoints on a connector is not moveable. All other waypoints are moveable, as are the end-points, but one is not.

**To Reproduce**
1. Load the attached diagram.
2. Click on Purple connector line. Notice that four waypoints are highlighted on the connector.
3. Click and drag each waypoint to change the shape of the connector. Notice that the top most waypoint at location (240,32) is not moveable.
4. Try and fix this by right clicking on the connector and clearing waypoints. Notice that the top waypoint now at location (170,32) is still not moveable.

**Expected behavior**
Expect that waypoints on a connector would be moveable.

**Screenshots**
Load attached file to use a diagram that exhibits this problem.

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 13.6.5

**Desktop (please complete the following information):**
 - OS: Fedora 32
 - Browser Chrome 84 & Firefox 79

[stuck_waypoint.txt](https://github.com/jgraph/drawio/files/5131154/stuck_waypoint.txt)

**Comment by martywesley** [comment]
I figured out how to trigger this type of connector problem:
1. Select the purple connector and set it as the default style.
2. Pick any connection point on the shape. There are three white dots on the left, three dark gray on the right and three bumps on the bottom.
3. Hover over the connection point until you get the four directional connection arrows. (Sometimes I had to click to focus it too)
4. Select one of the directional arrows. Move over top of it, click to create a connector and begin dragging it to another connection point.
5. After connecting the end of the connector, go back and try and move the first waypoint on the connector and notice that it is not moveable.

**Comment by martywesley** [comment]
I have another document that exhibits this behavior. Please see attached. (It's listed as a TXT file, but it's really a drawio saved file.)
[Stuck_connector_waypoint.txt](https://github.com/jgraph/drawio/files/6274197/Stuck_connector_waypoint.txt)

**Comment by mararad** [comment]
Connectors are not added to "regular" shapes but if the connector in question is disconnected and reconnected, it can be moved
![moved](https://user-images.githubusercontent.com/44292306/176885305-a507bcfe-f593-4ecb-a8cc-de0efeca0030.JPG)
