### ISSUE TITLE
Create shapes from groups

### ISSUE THREAD

**Issue by Murmele** [jgraph/drawio#1138]
* [X ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When creating complex shapes with groups, I did not find an option to add connection points to a group (Do there exist one?). The idea is to create a shape from a group. So you have connection points and as second point, you cannot select an inner object of the group and moving it accidently.

**Describe the solution you'd like**
It would be nice if draw.io can create automatically shapes from created groups.

**Comment by raindropsfromsky** [comment]
This issue can be rephrased as-

Let the user define **glue points** for the combined shape (=group). He should be able to attach connectors to these **glue points**.

The idea of a glue-point can be seen in **LibreOffice Impress** or **Draw**.

https://www.youtube.com/watch?v=PI97MPRiNEo
https://www.youtube.com/watch?v=LUICmXeN10A

**Comment by Murmele** [comment]
Is it possible to implement?
