### ISSUE TITLE
Flipping groups does not work

### ISSUE THREAD

**Issue by Murmele** [jgraph/drawio#1139]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Flipping of single parts is possible with Arrange->Direction->Flip Horizontal. This works fine for simple objects, but not for Groups

**To Reproduce**
1. Create two rectangles and place them horizontal to each other
2. Color the right one red to distinguish
3. Select both and create Group "Ctrl + G"
4. Arrange->Direction->Flip Horizontal

**Expected behavior**
After flipping the left one is the red rectangle

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version "diagrams.net 13.6.2"

**Desktop (please complete the following information):**
 - OS: Windows
 - Used desktop version of draw io

**Comment by mararad** [comment]
Hi,

We don't support flipping groups at the moment.

**Comment by Murmele** [comment]
Will it be implemented?

**Comment by kstripp** [comment]
Can this please be added to the list of features to implement?

Also, why was this reply marked off-topic?  It seems completely on topic.
https://github.com/jgraph/drawio/issues/1139#issuecomment-739471182

**Comment by fishtank666** [comment]
I need to flip group of objects，could you add the feature.Many Thanks!

**Comment by davidjgraph** [comment]
Please do not "+1" or "me too" comment. It generates noise that distracts from important content.

If you wish to indicate you need the feature, thumbs up the original comment.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
