### ISSUE TITLE
Pinch zoom on iOS 10.2

### ISSUE THREAD

**Issue by blazespinnaker** [jgraph/drawio#114]
I'd like to do a pull request to fix this, as it's quite awkward on mobile safari.   When I do a pinch zoom it darts around away from the original point I was trying to zoom into.   Can you give me some insights on where to look / how to address this?  Has it been attempted before to fix it?  Are there issues on iOS or with draw.io that make it impossible / hard to fix?

**Comment by alderg** [comment]
The code is here: https://github.com/jgraph/mxgraph/blob/v3.7.2/javascript/src/js/handler/mxPanningHandler.js#L58

**Comment by joas8211** [comment]
This issue is related to https://github.com/jgraph/drawio/issues/148, that's moved to https://github.com/jgraph/mxgraph/issues/94.
