### ISSUE TITLE
Copying Elements layer changes

### ISSUE THREAD

**Issue by Murmele** [jgraph/drawio#1140]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When creating multiple layers and move one object (say "objA") to the layer "layerA" and in the layer selection dialog layer "layerD" is selected, and this object is copied and pasted, the new object ("objB") is on the selected layer ("layerD") in the layers dialog and not on the same layer than the "objA"

**To Reproduce**
1. Open Layers dialog (Ctrl+Shift+L)
2. Add new Layer and rename it to "layerA"
3. Add new Layer and rename it to "layerD"
4. Select Layer "layerD"
5. Create new object (rectangle)
6. Move object to "layerA". Select object and click on the "Move selection to" button in the layers dialog
7. Select "layerD" in Layers dialog
8. Copy and paste selected object (ctrl+c, ctrl+v)
9. Check current layer of the new object (Select object, click on "Move selection to" to se on which layer the object is

**Expected behavior**
Object is also on layer "layerA"

**Seen behavior**
Object is on layer "layerD"

- draw.io version diagrams.net 13.6.2

**Desktop (please complete the following information):**
 - OS: Windows
 - Desktop version of draw io

**Comment by mararad** [comment]
Hi,

If I followed this well, an original shape should be in layer A (because it was moved) and a copy of it should be in layer D. I tested this and it is working at my place. A shape goes to a layer which is selected.

Just to recheck - you see a shape only in layer D?

Regards,

**Comment by Murmele** [comment]
No the first object is on "layerA" the second object is on "layerD"

**Comment by ashrafteleb** [comment]
Our layers are not a property of a shape. It is like a drawing area and a grouping mechanism. Also, most other tools do the same (paste in the selected layer). It is similar to copying a shape from one page and pasting it to another (one won't expect it to be pasted in the source page). So, unfortunately, we cannot do that.
