### ISSUE TITLE
Graphical Shape Editor

### ISSUE THREAD

**Issue by Murmele** [jgraph/drawio#1142]
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.

**Is your feature request related to a problem? Please describe.**
I would like to draw a schematic with complex parts. So I tried to create groups of simple parts. The problem is that when having overlapping parts in groups, it is difficult to click on it to get the correct part. Therefore I tried to create a shape following this tutorial:
https://desk.draw.io/support/solutions/articles/16000052874-how-to-create-and-edit-shapes-
But I was not able to create a simple shape with two rectangles in it. I do not understand, why in the tutorial so many "save" operations are after each other and when deleting one, the shape changes.

**Describe the solution you'd like**
It would be nice if it is possible to create from a selection a new shape. So convert the group/parts from the selection into a single shape instead of writing the properties by text code

**Comment by Murmele** [comment]
Will it be implemented?

**Comment by davidjgraph** [comment]
This is outside the scope of the project.

**Comment by friedl-ap** [comment]
It's a mess designing shape by hand. I'd vote to include a shape editor in this project.

**Comment by notstyle** [comment]
Today txt shape editor is sad. Other svg tools have easy visualble editors and draw.io should have this also.

**Comment by Murmele** [comment]
Yes it is really anoying to draw new shapes

**Comment by friedl-priv** [comment]
Hi @davidjgraph!

Here I show you how onerous it is to modify an existing shape:

1. Hoover over the shape of interest and take not of the name displayed, for example "SPDT".
![Screenshot_20210122_235926](https://user-images.githubusercontent.com/77863148/105558523-0c77c300-5d0f-11eb-815b-5b7cc079954b.png)

2. Got to the draw.io repos at Github: [https://github.com/jgraph/drawio](url)

3. Search this repos for the beforemention string:
![Screenshot_20210123_001110](https://user-images.githubusercontent.com/77863148/105558775-aa6b8d80-5d0f-11eb-8dbd-f5f1a7e772f1.png)

4. In the search result take note of the second parameter, eg. "2-way switch" found in a file with ".js" extension:
![Screenshot_20210123_001249-1](https://user-images.githubusercontent.com/77863148/105558871-fd454500-5d0f-11eb-899c-3cc4e547da34.png)

5. Search this repos for the string found in the previous search:
![Screenshot_20210123_001513](https://user-images.githubusercontent.com/77863148/105558934-2ebe1080-5d10-11eb-9c5c-df28920f7087.png)

6. In the search result click on the line number in the ".xml" file found, where you see the "**\<shape**" tag:
![Screenshot_20210123_002119](https://user-images.githubusercontent.com/77863148/105559337-2d411800-5d11-11eb-8470-af11ec3c4cc1.png)

7. Now copy the shape data from start tag "**\<shape**" to the end tag "**\</shape\>**":
`<shape aspect="variable" h="26" name="2-Way Switch" strokewidth="inherit" w="75">
....
</shape>`

8. Go back to your drawio or drawio-desktop window and from the menu select to add a shape:
![Screenshot_20210123_003226](https://user-images.githubusercontent.com/77863148/105559862-95442e00-5d12-11eb-9285-9cd3fce45479.png)

9. In the dialog that comes up replace the shape date with the data you copied to the paste buffer in step 7. before.

10. Now try to modify the x- and y-coordinates of some element, clicking the "Preview" after each edit to see what you've change and if it really is what you want to modify.

I mastered it :triumph:. But it's definitely not fun :slightly_frowning_face:. 

Even more cumbersome if the shape is only contained in a saved ".drawio" file. Takes multiple steps decoding that one.

Please reconsider your verdict "outside the scope of the project"!

**Comment by friedl-priv** [comment]
And remember:

Before you click "Apply" in the "Edit Shape" dialog, 
**Always copy the modified shape date to a text editor of your choice!**

Because you can't continue editing your shape after hitting "Apply".

**Comment by Murmele** [comment]
@davidjgraph how some others are able create new shapes quickly?

**Comment by hwinkel** [comment]
We have exactly the same problem, Never expected that draw.io (the paid version) is not able to create shapes. Just Switched from another tool to draw.io and now the team considers going back. Creating shape libraries from existing SVG is just too much effort to justify
