### ISSUE TITLE
Google Drive Connection 401 Error

### ISSUE THREAD

**Issue by slamar18** [jgraph/drawio#1144]
The connection to Google Drive is no longer authorizing. After getting the Authorize screen, I click Allow, then this error message gets returned. I have connected with this same G user for years, so I don't believe this is a user issue. 
![image](https://user-images.githubusercontent.com/59985025/91559231-e9c6b700-e8f4-11ea-9fc2-3069e5443930.png)

**Comment by ashrafteleb** [comment]
Can you please try in incognito mode? Are you blocking 3rd party cookies or any recent changes to browser settings? Can you try another browser?

**Comment by slamar18** [comment]
THanks for the quick reply. I think the issues was going between draw.io and diagrams.net. I went back to draw.io and was able to connect from there.

**Comment by niekvb** [comment]
I'm having the same issue on Firefox 80. The Oauth process fails when calling the redirect URL.

Tracking protection is disabled, no restrictions on 3rd party cookies or anything. Trying to authorize in incognito produces the same result: 401 on https://app.diagrams.net/google...

Did not find a work around yet.

**Comment by davidjgraph** [comment]
It does need to work on diagrams.net, really. @niekvb does it work in a private window? What about a different browser?

**Comment by niekvb** [comment]
No sure what's happening here... Tried the same process on both Firefox and Chrome (85) in both regular mode and private.

In Chrome there's no problem, authorization goes as expected.

But on Firefox I'm stuck with the popup window. (both regular and private window)
When pressing "Allow draw.io" on Google's Oauth page the popup window will redirect itself to this page (if not failing with 401):
![image](https://user-images.githubusercontent.com/37668320/91660111-7da2a980-ead4-11ea-84e4-656b60ee8eff.png)
When I select a draw.io file in this popup window, the popup page stays blank (on the same url: `https://app.diagrams.net/connect/office365/drive.html`.

**Comment by niekvb** [comment]
I may have found the issue...

I suppose it is caused by blocking popup windows. It seems like some information that needs to be passed onto the popup window gets lost when the popup is blocked.

**Comment by xm4dn355x** [comment]
Same issue. Google Chrome 84.0.4147.135

![image](https://user-images.githubusercontent.com/17689941/92471663-bbe54a80-f1f1-11ea-8123-2d264f678ba6.png)

**Comment by davidjgraph** [comment]
Does it happen incognitio?

**Comment by xm4dn355x** [comment]
> Does it happen incognitio?

No. I was try to save project to my google drive, and in last stage of google oauth (after granting of all permissions to drawio) I was seeing this error.

(Sorry for my English)

**Comment by davidjgraph** [comment]
If it doesn't happen incognito it's either 1) your browser cache, 2) your browser cookies or 3) a browser extension that is causing the problem. The first 2 you can clear, the third you can find by disabling them in turn.

**Comment by teyou** [comment]
I think the issue is due to `draw.io` redirected to `https://app.diagrams.net/` ? since it is different domain, Google block the OAuth?
I'm also seeing this issue

**Comment by leonjaramillo** [comment]
I had the same issue, then I just allowed ads for all the webpages from the domain app.diagrams.net/* and it seems to be working right now. I use AdBlock to manage the ads.

**Comment by jacobbaratta** [comment]
Adding `app.diagrams.net` to the trusted sites list in uBlock Origin was insufficient to resolve the issue for me (as were the other suggestions above). It was only after I added `draw.io` to the trusted sites list that Google OAuth for https://app.diagrams.net finally started working.

**Comment by leftshift** [comment]
Strange enough, I was having a similar issue where the google auth window was redirecting me to a blank page or a blank page with a 401 error in the browser console.
Adding exceptions to uBlock Origin didn't seem to have fixed it, but allowing all popups from the page where the diagram was embedded seams to have fixed it.
Firefox 89.0.2.

**Comment by budhilaw** [comment]
> If you have any extensions such as IDM and NDM, please turn them off and try again, it worked for me, both in Chrome and edge.

Thank you so much!
