### ISSUE TITLE
Moved shape is only redrawn once before arrow keys are released

### ISSUE THREAD

**Issue by Chealer** [jgraph/drawio#1146]
* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? 
Yes
Please describe.**
A selected shape can be moved by pressing the up, right, down or left arrow keys. Achieving significant moves requires pressing several times, or keeping the key pressed for some time. Unfortunately, if one keeps an arrow key pressed for some time, the shape is only redrawn at most once initially and then when the key is released, which makes it hard to gauge when the key should be released.

**Describe the solution you'd like**
I have no specific expectation, but I suggest redrawing the shape (and possibly the whole diagram) at least each second.

**Describe alternatives you've considered**
Users who have access to a mouse/touchpad and who are able to use it can drag and drop shapes instead.

**Additional context**
This behavior is seen in Google Chrome 65 as well as Mozilla Firefox 80.

**Comment by Ezwen** [comment]
This is still a problem.

**Comment by Ezwen** [comment]
Again, I'd argue that this is still a problem.

**Comment by gitman0** [comment]
I have this issue on the desktop version as well.

**Comment by alderg** [comment]
This will be fixed in the next release.
