### ISSUE TITLE
Insert to MSWord with editable text

### ISSUE THREAD

**Issue by RuiNCosta** [jgraph/drawio#1148]
I've been using draw.io to draw diagrams, to later insert them on a MSWord file. 
For the moment, there's only one way to add them that keeps the diagram in shape as an immage file.
Ideally i'd like to be able to use the search function to locate a word written on that diagram.
I've found that by printing as PDF, there are some PDF to DOC converters that kind of work, but deform many parts of the diagram, making it unusable in fact.
It would be nice if draw.io could export to some sort of format that would allow more fluid integration into .doc files.

**Comment by mararad** [comment]
Hi,

If you use our add-in for Microsoft Office products (Word etc.) )https://desk.draw.io/support/solutions/articles/16000061408-use-diagrams-in-microsoft-word-excel-or-powerpoint does it help?

Regards,

**Comment by RuiNCosta** [comment]
Hi there!
Thank you for the quick reply!
It doesn't really help since it inserts the whole graph as a picture, and as such looses the information on what is a word and what is a drawing.
![image](https://user-images.githubusercontent.com/70520837/91730060-5bc12980-eb9d-11ea-8d92-6e00ee4b221c.png)
 If printed directly from draw.io to PDF this information goes along with it:
![image](https://user-images.githubusercontent.com/70520837/91730127-74c9da80-eb9d-11ea-90af-47f66ccf23ad.png)
But this way it's not really available for integration into a document, since one can't add the proper heading, footer, page number, caption, etc.

**Comment by ashrafteleb** [comment]
AFAIK this is currently not technically possible
