### ISSUE TITLE
GitLab.com support

### ISSUE THREAD

**Issue by ebekker** [jgraph/drawio#115]
Similar to the recently added GitHub support, it would be nice to add support for GitLab.com.

I would even be happy to submit a PR to add this support if you would provide a little guidance as to the extension points or areas where such support would need to be added.

**Comment by alderg** [comment]
Does GitLab have a REST API and oauth (client-side flow)?

**Comment by ebekker** [comment]
I believe this is what you're looking for, correct?

* OAuth support:  https://docs.gitlab.com/ee/api/#oauth-2-tokens
* REST API to push commits:  https://docs.gitlab.com/ee/api/commits.html#create-a-commit-with-multiple-files-and-actions

Note that the docs give examples in the context of `gitlab.example.com` server domain, but that's because GitLab is available as both an on-prem and a cloud-hosted version (same as GitHub), so the domain to use for the publicly hosted cloud edition is simply `gitlab.com` as in `https://gitlab.com/api/v4/projects`

**Comment by alderg** [comment]
For On-Prem, I think the problem will be the oauth callback URL. Maybe the better idea is to embed draw.io in GitLab. https://gitlab.com/gitlab-org/gitlab-ce/issues/22222

**Comment by davidjgraph** [comment]
Please file a feature request at https://draw.uservoice.com/forums/266072-feature-requests/filters/top

**Comment by ebekker** [comment]
Looks like the idea was [already there](https://draw.uservoice.com/forums/266072-feature-requests/suggestions/18421690-gitlab-connector).  Just added my votes to it.

Thanks for the great tool!

**Comment by a-komarev** [comment]
Link on exact feature request: https://draw.uservoice.com/forums/266072-feature-requests/suggestions/18421690-gitlab-connector

**Comment by agaget** [comment]
I can't access the feature in the draw.uservoice (access denied), is there any news about this feature ?
Thanks

**Comment by davidjgraph** [comment]
The issue has moved to Gitlab's issues, https://gitlab.com/gitlab-org/gitlab-ce/issues/22222. It's not something we can implement on our own, we need assistance from Gitlab.

We did assign an engineer to investigate, but we need assistance from Gitlab and they don't seem very interested.
