### ISSUE TITLE
Blurry font while editing text

### ISSUE THREAD

**Issue by JeremyMahieu** [jgraph/drawio#1150]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I see blurry text when editing said text. I've never noticed this before. Seveirty may depend on zoom level, being worse on smaller fonts but it's even happening on 100%.

- Zoom setting of the browser tab itself is 100%
- Browser: 
    - Happens on Chrome on Windows
    - Does not happen on Firefox on Windows
    - Did not try other combinations

**To Reproduce**
1. Add a rectangle, give it some text
2. While typing the text you should already see it's blurry
3. Deselect the object and see the text become clear

**Expected behavior**
Text always to be clear

**Screenshots**
![image](https://user-images.githubusercontent.com/23409814/91962758-44a14980-ed0d-11ea-84ff-9fa77c19e01e.png)
![image](https://user-images.githubusercontent.com/23409814/91962765-4834d080-ed0d-11ea-84dc-5b378c6f778a.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 13.6.6 and 13.7.9

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 85

**Comment by Rexxios** [comment]
This is still an issue in version 13.7.9

**Comment by lfdversluis** [comment]
I have the same issue on version 13.9.9, running the desktop app on Windows 10. I did not have this issue on an earlier version (I just updated) I think it was version 13.1 or something like that?
