### ISSUE TITLE
moving shapes with keyboard is extremely slow

### ISSUE THREAD

**Issue by nbelyh** [jgraph/drawio#1151]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Drop a single shape, select it, and press (and hold) DOWN arrow key for example. The shape moves unexpectedly slow. I.e. the shape does moves, but it's extremely slow, like 1 "pixel" per second, or moves a few steps and then stops, and finally "jumps" when you release the arrow key.

**Expected behavior**
I expect the shape to move in response to keypresses with a reasonable tempo (at least a few pixels per second, that is). The diagram is extremely simple - a single rectangle on the blank drawing surface.

"Lagging" this way IMHO is an awful user experience when working with keyboard... You can check out any other diagramming tool how they work when you do the same (select a shape and press and hold an arrow key), like Lucidcharts, Gliffy, PowerPoint, Visio. For an expected user experience, the move should be around 3x - 4x times faster.

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome 85

**Comment by JeremyMahieu** [comment]
Can agree about the screen not updating until releasing the key. (But don't agree about the shift thing, you should exclude this from the current issue and open another issue for that imo.)

**Comment by nbelyh** [comment]
Thank you for swift response. Removed the thing about shift, this was more of a personal preference maybe. Although following a common rules might make sense as well 😉

**Comment by JeremyMahieu** [comment]
I count 200px in 10 seconds by holding down the up button. How much do you have? My key repeat rate is 33Hz (measured [here](http://stereopsis.com/keyrepeat/)). So this is about as expected (I counted manually so not very accurate).

**Comment by nbelyh** [comment]
Not sure in numbers, I just made a video - this is the fastest I can get (maybe 4K screen?):
![move](https://user-images.githubusercontent.com/528366/91980255-3d873500-ed27-11ea-92ff-9030e5de2921.gif)

**Comment by JeremyMahieu** [comment]
When I press and hold down the button I don't see ANY updates until I let go. See video where I've let go of the button twice.
![TjB6pTCpfZ](https://user-images.githubusercontent.com/23409814/91980798-1d0baa80-ed28-11ea-99c6-a29d9ec43c24.gif)

**Comment by nbelyh** [comment]
Yes correct, if you press and hold it will "jump". I was just clicking the left arrow with the maximum rate I could 😄

**Comment by nbelyh** [comment]
Closing as duplicate to the other one (would be great if you take the speed also into account when addressing the other one)
