### ISSUE TITLE
Feature Request: Consider active page for PNG Export

### ISSUE THREAD

**Issue by hediet** [jgraph/drawio#1156]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

When exporting to png, [the first page is exported if no pageId is set on the action data](https://github.com/jgraph/drawio/blob/cfb48700e8c721bd9ee5552bb7e8ed1c8902e933/src/main/webapp/js/diagramly/EditorUi.js#L10976).
[This is different from what happens when exporting to svg - it exports the currently active page](https://github.com/hediet/vscode-drawio/issues/108).

**Describe the solution you'd like**
If no pageId is set in data, please use the currently active page rather than the first page for the png export!
It would align the png and svg export behaviour.

**Comment by hediet** [comment]
I think if [this](https://github.com/jgraph/drawio/blob/cfb48700e8c721bd9ee5552bb7e8ed1c8902e933/src/main/webapp/js/diagramly/EditorUi.js#L10976) line:
```js
var pageId = data.pageId || (this.pages != null? this.pages[0].getId() : null);
```

is replaced with this:
```js
var pageId = data.pageId || (this.pages != null? this.currentPage.getId() : null);
```

it should probably work.

**Comment by alderg** [comment]
This inconsistency between SVG and PNG export is actually a bug. However, to not break existing clients we'll add an optional currentPage parameter (boolean) for the selected page to be exported.
