### ISSUE TITLE
Clear Text From Single / Multiple Objects

### ISSUE THREAD

**Issue by bratwiz** [jgraph/drawio#1157]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the Feature You Want**

I would like to have a way to clear just the text from a selection of one or more shapes. (There is a similar feature in Visio).

**Describe the solution you'd like**

In Visio (from memory) this feature is controlled by the Backspace key but any key would be fine, or even just a context menu selection. I suppose if you create the feature, there should be a button for it on the sidebar also.

My ideal implementation would be, (1) Select one or more shapes (2) activate Clear by whatever means (3) All of the text contained in the *normally* editable area of the shape would be removed. No formatting changes, no style changes, simply removing the text is all.

**Describe alternatives you've considered**

None that I'm aware of.

**Additional context**

None.

**Comment by alderg** [comment]
We'll add Shift+Backspace and Shift+Delete for this in the next release.

**Comment by bratwiz** [comment]
Thanks!
