### ISSUE TITLE
Let users import custom shapes that are created in external software, and saved as raster/vector images. 

### ISSUE THREAD

**Issue by raindropsfromsky** [jgraph/drawio#1159]
* [v] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [v] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Drawio does not have enough P&ID shapes (=process engineering shapes), because-

1. The P&ID shapes are not standardized, so often we have to design our own shapes
2. The process engineering covers all sorts of industries, for which specialized shapes are needed. For example, wastewater treatment, petroleum refinery, etc.

This is a major limitation. But Drawio does not allow us to import images from outside.

**Describe the solution you'd like**
It is easy to create these shapes in external software, such as PowerPoint/Impress, InkScape, 
Drawio must have a facility to import new custom shapes created in such external software, as a vector or raster image (svg, png, etc).

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by davidjgraph** [comment]
Drag and drop the images into the canvas, or create a new library, File->New Library.

**Comment by raindropsfromsky** [comment]
That works, but I cannot apply a name to the shape. On the other hand, if I
give my mouse on any built-in shape, I can see its name.

How do I apply a name to imported shape?
