### ISSUE TITLE
Export to image generates a giant X instead of the object

### ISSUE THREAD

**Issue by frakman1** [jgraph/drawio#1160]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Exporting to any image format generates giant Xs over the objects

**To Reproduce**

1- Add generic server
2- Export to PNG

**Expected behavior**

I expect the exported image to look like the image in the webapp designer

**Screenshots**
![image](https://user-images.githubusercontent.com/5826484/92330521-60725b80-f03d-11ea-9cc7-a8d6d5e9a4ad.png)
![image](https://user-images.githubusercontent.com/5826484/92330447-d75b2480-f03c-11ea-9172-f6d1bf4992b5.png)
![image](https://user-images.githubusercontent.com/5826484/92330448-dc1fd880-f03c-11ea-93e7-6b589bdddc4f.png)
![image](https://user-images.githubusercontent.com/5826484/92330449-df1ac900-f03c-11ea-8ea9-1f61b177fa1c.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [diagrams.net 13.6.6]

**Desktop (please complete the following information):**
 - OS: [MacOS High Sierra 10.13.6 (17G65)]
 - Browser [Chrome: Version 84.0.4147.135 (Official Build) (64-bit)]

**Comment by mararad** [comment]
Hi, 

I couldn't reproduce this but I am a Win user. My advice would be to repeat all the steps in a different browser and Private mode. Also, clear the cache and temporarily disable all browser extensions.
Incognito mode is great for testing cause it is cache and extension free (cache and extensions can cause some problems sometimes)

Does it help?

BR,

**Comment by frakman1** [comment]
You're right. The problem went away when I tried it again later (same PC, regular chrome tab, not incognito)

**Comment by dre2004** [comment]
I get the same behaviour when using the desktop app (I've tried both Windows and Mac). It seems to only happen on some images/icons but its very random which icons it happens on.
