### ISSUE TITLE
Please allow user to enter vertically oriented text in selected cells in a table 

### ISSUE THREAD

**Issue by raindropsfromsky** [jgraph/drawio#1161]
* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Draw.io does not allow us to enter vertically oriented text, as shown below:
![image](https://user-images.githubusercontent.com/9047168/92366270-903f6300-f112-11ea-97b0-33c69c66e83a.png)

**Describe the solution you'd like**
Please allow vertically oriented text in selected cells. The rest of the table may have horizontal text.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by mararad** [comment]
Hi,

If you select a shape with text and click Vertical (Format panel on the right > Text tab) does it help?

![vertical](https://user-images.githubusercontent.com/44292306/92581569-2351d780-f290-11ea-8723-3da58b4c2296.JPG)

Regards,

**Comment by raindropsfromsky** [comment]
Yes, that works. Thank you for the tip.
