### ISSUE TITLE
Feature request: modifier+drag over part of object = selection

### ISSUE THREAD

**Issue by bjohas** [jgraph/drawio#1164]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

Would it be possible to allow selection of an object by dragging over a part of the object? E.g. with modifier + drag? 

In my experience, both "drag across whole object to select object" and "drag over part of object to select" can be useful. Is there a way of doing that? If not, could it be implemented?

**Comment by mararad** [comment]
Hi, 

partial selection is not possible at the moment, but "drag across whole object to select object" as described here: https://desk.draw.io/support/solutions/articles/16000052890-select-multiple-shapes

Does it help?

Regards,
