### ISSUE TITLE
Feature request: More options for "move object with arrow key"  

### ISSUE THREAD

**Issue by bjohas** [jgraph/drawio#1165]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

The arrow-key actions for selected options do not seem to be included in https://app.diagrams.net/shortcuts.svg - would it be possible to add them?

I wasn't able to find any more move options other than "arrow" and "shift+arrow". I would like to have an option for moving bigger distance (e.g., one large grid cell).

Many thanks!

**Comment by alderg** [comment]
<img width="353" alt="Screenshot 2020-09-08 at 13 03 50" src="https://user-images.githubusercontent.com/921200/92468636-c4c72380-f1d3-11ea-8305-066ed66490dd.png">
That?

**Comment by bjohas** [comment]
Hi @alderg - thank you - yes.

I see! 

- 'scroll / move cell' wasn't obvious to me - it might be better to call 'move selection/object' 
- 'move cell (grid size) or page' also isn't clear to me.

I would prefer

- Cursor ... Scoll page view / Move selected object (pt)
- Shift+cursor ... First/last/next/prev. page / Move selected object (grid box)

For Ctrl+cursor (without selection) the effect seems to be the same as for shift+cursor - what is the difference?

So the move by one grid box is the largest jump? I would prefer an option to be able to move objects by a 'large grid' spacing as well.
