### ISSUE TITLE
Feature request: Amend documentation for "scale selected objects"

### ISSUE THREAD

**Issue by bjohas** [jgraph/drawio#1166]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

I was unable to find a keyboard shortcut / mouse combination to scale/resize e.g. two selected objects. Could the right command be added to the shortcuts page? https://www.draw.io/?url=https%3A%2F%2Fwww.draw.io%2Fshortcuts.svg#Uhttps%3A%2F%2Fwww.draw.io%2Fshortcuts.svg

Many thanks!

**Comment by mararad** [comment]
Hi,

Thanks for the suggestion.

Meanwhile, you can select shapes, group them (Arrange > Group) and drag a blue dot (while holding Shift). If you like to constrain proportion you can tick that option in Format panel on the right > Arrange

Regards,
