### ISSUE TITLE
Pasted images no longer show on the Canvas, also impacts images that were working fine before.

### ISSUE THREAD

**Issue by bo-oz** [jgraph/drawio#1167]
### Preflight Checklist

* [ X ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ X ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I can no longer successfully copy/paste screenshots into the canvas. When I paste, I do see a blank placeholder for the image. When I try to edit the image, I see that the binary code for the PNG is there. What seems to be missing is the declaration to use base64 in the encoding bit of the PNG. The IMAGE url shows "data:image/png,binary", when I copy and paste this URL into a JSFIDDLE and add base64 to the string, it does show: "data:image/png;base64,binary"

**To Reproduce**
1. Paste any image into a blank canvas
2. You will see a placeholder without an image
3. Right click on the placeholder and click on Edit image
4. Copy paste the Data URL for the image (starts with data:image/png,)
5. Open JSFiddle.com and create a <img src=""> tag and paste what you just copied between the ""
6. Hit run and confirm that the image is not showing (https://jsfiddle.net/9wpbx75a/)
7. Replace the beginning of what you pasted in the src, so that it starts with "data:image/png;base64,"
8. Hit run again and confirm that the image is now showing correctly (https://jsfiddle.net/9wpbx75a/1/)

**Expected behavior**
Images should be shown in the canvas

**Screenshots**
See JSFIDDLE's and explanation on top.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.6.8 (in Confluence)
- draw.io version 13.6.8 (https://app.diagrams.net/)

**Desktop (please complete the following information):**
 - OS: iOS 10.14.6 
 - Browser Chrome v85, Firefox v80

**Comment by TwinkleAcuvate** [comment]
Hi, I'm facing the same issue. I'm unable to copy paste screenshots OR view screenshots added in previously saved files. Please help as it's massively impacting my project.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/70939027/92444872-1fab4b80-f1d1-11ea-8384-fb656c399b11.png)

**Comment by alderg** [comment]
Fixed in 13.6.9. Thanks for the report!

**Comment by bo-oz** [comment]
Any idea when Confluence picks up the new version? Thanks for the quick fix.

**Comment by davidjgraph** [comment]
Confluence Cloud will see it when you see 13.6.9 in the Help menu at https://confluence.draw.io
