### ISSUE TITLE
Publish URL without base64 contents

### ISSUE THREAD

**Issue by rickywu** [jgraph/drawio#1169]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Public URL of the diagram is disabled
I save my graph in private gitlab and want to export as a URL to embed in iframe in view mode

**To Reproduce**
1. Go to 'File'
2. Click on 'Export as'
2. Click on 'HTML'
4. Public URL of the diagram is disabled

**Expected behavior**
Export as a URL included private gitlab URL and without base64 contents

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version [e.g. 13.6.9]
![image](https://user-images.githubusercontent.com/442398/92454604-424e5c00-f1f3-11ea-9351-1d6f93f312d7.png)

**Comment by davidjgraph** [comment]
Closing as version not supplied

**Comment by rickywu** [comment]
> Closing as version not supplied

I updated to draw.io version [e.g. 13.6.9] still has this problem

**Comment by mararad** [comment]
Hi,

Unfortunately there is nothing we can do on our end. This isn't working because GitLab doesn't deliver a CORS header, which means we can't access the file from our HTML viewer i.e GitLab should be asked for CORS header "*" on download_url

**Comment by rickywu** [comment]
@mararad I don't think so.
Because I can build a link for preview works well, but not use drawio's export feature.
![image](https://user-images.githubusercontent.com/442398/92834779-01ca2a80-f40d-11ea-98ce-9009388f40e6.png)

The linke I build like 
`http://10.0.28.17/draw/?lightbox=1&highlight=0000ff&edit=http://10.0.28.17/draw/%23Aarch%2Fsoftdeploy%2Fmaster%2FCBS%2F%E6%A0%B8%E5%BF%83%E4%B8%9A%E5%8A%A1V1.0.drawio&layers=1&nav=1&title=%E6%A0%B8%E5%BF%83%E4%B8%9A%E5%8A%A1V1.0.drawio#Uhttp://10.0.28.17:8989/arch/softdeploy/raw/master/CBS/%E6%A0%B8%E5%BF%83%E4%B8%9A%E5%8A%A1V1.0.drawio%3Finline%3Dfalse`

**Comment by rickywu** [comment]
No plan to support?

**Comment by davidjgraph** [comment]
This is outside the scope of the project.
