### ISSUE TITLE
Unable to give a name to imported shape. How to know what it stands for? How to search for it?

### ISSUE THREAD

**Issue by raindropsfromsky** [jgraph/drawio#1170]
### Preflight Checklist

* [y ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ y] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
 When I import an external png file into Draw.IO, I cannot apply a name to the icon.
So if I hover my mouse on such an imported shape, I do not see any tooltip.
On the other hand, if I hover my mouse on any built-in shape, I can see its name as a tooltip.

So the question is, how do I apply a name to imported shape?

**To Reproduce**

Hover the mouse on an imported shape. There is no name.
We cannot name it.

**Expected behavior**
We should be able to name every shape, so that we can know its name on mouse-hover and search for it.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mararad** [comment]
Hi,

I tested this with drag&dropped PNG and JPG images and tooltips were visible on hover (select an image and click Edit > Edit tooltip) but I used diagrams.net online the latest version 13.6.9 on my computer so my suggestion would be to:

* update diagrams.net to the latest
* check tooltips are working in another browser and Private mode (also clear cache and temporarily disable all browser extensions in a preferred browser)

Does it help? Are you using only iPhone or you can work on your computer also?

Regards,

**Comment by raindropsfromsky** [comment]
I am already using the latest Desktop version (13.6.2) 
(Sorry I have not declared that detail in the form.)

Let me illustrate the problem with a few screenshots:

1. I can hover the mouse on any built-in shape, and see its thumbnail and name on the main screen.
![image](https://user-images.githubusercontent.com/9047168/92595956-ad1a9880-f2c2-11ea-8444-440578072571.png)

2. Once I am familiar with the names of my shapes, I can search for any shape by searching for their names.
For example, if I search for "Isometric edge", I get the following results:
![image](https://user-images.githubusercontent.com/9047168/92596040-cc192a80-f2c2-11ea-8081-8d4453c6ee0a.png)

But when I add an image in a personal library, there is no facility to add its name. 
When I hover the mouse on the image icon, I can see its thumbnail, but it has no name, as shown below:
![image](https://user-images.githubusercontent.com/9047168/92596529-96287600-f2c3-11ea-8c69-67e47e0866ff.png)

As a result, I cannot search for such images by name. And that's the problem.

**Comment by raindropsfromsky** [comment]
I was expecting that I can add the name using a context menu:
![image](https://user-images.githubusercontent.com/9047168/92596821-09ca8300-f2c4-11ea-80e7-05e565cf2111.png)

But none of the options allow that.

On further experimentation, I discovered that the item can be given a name by editing the XML itself.

So, step#1 is to edit the XML.
![image](https://user-images.githubusercontent.com/9047168/92596714-e0a9f280-f2c3-11ea-8880-fc7f2d27193f.png)

Step#2 is to edit the name of the item there:
![image](https://user-images.githubusercontent.com/9047168/92596969-49916a80-f2c4-11ea-92db-835628003312.png)

Although I found the way, this path is not really intuitive.
It is best if the user can edit the name of the item using its context menu.

**Comment by raindropsfromsky** [comment]
On second thought, I wonder if Draw.io treats the image on canvas as an independent copy of the image inside the library?
If that is the case, then naming the copy should not affect the original item in the library.
If that is indeed the logic, then the path is correct: I should be editing the item's name inside the library only.

**Comment by alderg** [comment]
Yes, it's an independent copy. We'll close this, the name should be edited in the library as shown.
