### ISSUE TITLE
BPMN Icons - blank for Events/Gateways

### ISSUE THREAD

**Issue by JO70** [jgraph/drawio#1172]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
BPMN icons are not visible (only Gateways/Events)

**To Reproduce**
1. Go to Sibebar - BPMN Section
2. any icon of the group BPMN Events or BPMN Gateways  --> no icon - but empty boxes

**Expected behavior**
Box should be filled with icon

**Screenshots**
**_Sidebar_** 
- doesn't show the icons on sidebar
- you can drag empty box to diagram
- you get an empty box on your diagram

![grafik](https://user-images.githubusercontent.com/66570760/92606365-214d4000-f2b3-11ea-8547-d9ede63435ad.png)
![grafik](https://user-images.githubusercontent.com/66570760/92606533-55286580-f2b3-11ea-819c-c821eadabd2f.png)
![grafik](https://user-images.githubusercontent.com/66570760/92606592-66717200-f2b3-11ea-99e6-d31c4edf09db.png)

in the [MENUE]Ansicht>>>Shapes... (opening: Box "Shapes")  ---> scroll to BPMN section - all icons for General, Events, and Gateways visible (BPMN is ticked)
![grafik](https://user-images.githubusercontent.com/66570760/92606961-d7b12500-f2b3-11ea-8142-e41705dec985.png)

_**System**_
Firefox Quantum ESR 68.5.0esr (64-Bit) on Win7
![grafik](https://user-images.githubusercontent.com/66570760/92607197-17780c80-f2b4-11ea-9f86-7b083812a129.png)
https://app.diagrams.net/  (online, version 13.6.9)

**Comment by davidjgraph** [comment]
FF 68 had some rendering bugs, can you upgrade to 78?

**Comment by MJomaa** [comment]
Looks to me like the stencil *.xml files didn't load.

**Comment by davidjgraph** [comment]
Probably. If a console can be provided we can look into it.

**Comment by REggebrecht** [comment]
Preflight Checklist
[x ] I agree to follow the Code of Conduct that this project adheres to.
[x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Hello, 

Is there a reason why you close the issue?

I have the same behaviour on cloned drawio 14.2.19 respository if I load the index.html under src\main\webapp in browser with queryparameter offline=1.

Regards, Robin

**Comment by REggebrecht** [comment]
I found out that shapes\bpmn\mxBpmnShape2.js did not get loaded because mxStencilRegistry.allowEval is set to false.

**Comment by REggebrecht** [comment]
Fixed it by loading stencils.min.js and shapes.min.js manually.

`mxscript('js/stencils.min.js', function () {
	mxscript('js/shapes.min.js', function () {
		mxscript('js/PostConfig.js');
	});
});`

**Comment by REggebrecht** [comment]
But it would be nice if we don't need to load all libraries on startup, because the file stencils.min.js is 6 mb large. :-(
