### ISSUE TITLE
Publish URL — Lightbox checkbox isn't adding the same URL parameter

### ISSUE THREAD

**Issue by rinnaz** [jgraph/drawio#1173]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

Publishing or exporting URL with lightbox mode checked should create a link with `lightbox=1` URL parameter, but it does not, and the link opens in editor mode. 

**Screenshots**
Lightbox checked:
<img src="https://user-images.githubusercontent.com/36293513/92642235-925b1a80-f2e8-11ea-95be-e5683c0a1a40.png" width="300">
`lightbox=1` URL parameter missing:
<img src="https://user-images.githubusercontent.com/36293513/92642572-13b2ad00-f2e9-11ea-9dcf-3ad889fab316.png" width="400">

**draw.io version**

- 13.6.9 self-hosted (docker)

**Comment by davidjgraph** [comment]
Works in latest build
