### ISSUE TITLE
javascript:function

### ISSUE THREAD

**Issue by cool-delete** [jgraph/drawio#1175]
* [✔] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [✔] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
when i click the Link whit URl,in fact i want to copy some text .then i tpye
```javascript
javascript:(function(e,text){ 
 e.value = text; 
 document.body.appendChild(e); 
 e.select();  document.execCommand("Copy"); 
 document.body.removeChild(e);})(document.createElement("textArea"),
"some type")
```
and i click the link it push the windows

**Describe the solution you'd like**
i can use the code run on chrome's bookmark. it work,so drawio can do this?

**Additional context**
![image](https://user-images.githubusercontent.com/13638610/92684975-52884780-f369-11ea-944e-640be77c7274.png)

**Comment by alderg** [comment]
No. We do not allow scripting in links for security reasons.
