### ISSUE TITLE
[Bug] PDF Export Doesn't Honor Transparent Background

### ISSUE THREAD

**Issue by RoyiAvital** [jgraph/drawio#118]
Hello,

When exporting a page as PDF and checking the option for Transparent Background the PDF still have white background.

Could you please allow PDF Export with transparent background?

Thank You.

**Comment by alderg** [comment]
PDF does not support transparent backgrounds.

**Comment by RoyiAvital** [comment]
What do you mean?

PDF 1.4 and above does support it:

https://helpx.adobe.com/illustrator/using/printing-saving-transparent-artwork.html

**Comment by alderg** [comment]
Yep, I just saw. Reopened.

**Comment by RoyiAvital** [comment]
Great,

It would be perfect to have it.

**Comment by alderg** [comment]
We've checked, currently our backend (PhantomJS) does not support exporting PDF with transparent backgrounds. We'll update to another backend sometime soon, but it's not a quick fix before then.

**Comment by RoyiAvital** [comment]
Any update on this one?

Could you please add "Release Notes" for your releases?

Thank You.

**Comment by alderg** [comment]
No update. Release notes are here: https://github.com/jgraph/drawio/blob/master/ChangeLog

**Comment by RoyiAvital** [comment]
@alderg , Have you switched backend?

Your service is perfect for students to create diagrams in articles.
But in order to use it in PDF's (LaTeX), transparent background is a must.

Thank You.

**Comment by RoyiAvital** [comment]
@davidjgraph , Why did you close this?

**Comment by languitar** [comment]
Has this been implemented, or why is the issue closed?

**Comment by RoyiAvital** [comment]
@davidjgraph , Could you address why was it closed?

**Comment by davidjgraph** [comment]
I think it was determined it wasn't possible with the back-end. I can re-open it, but please understand unless one of the core team look into it, it's unlikely to be solved.

**Comment by RoyiAvital** [comment]
@davidjgraph , I think support for Transparent Background is really crucial for many tasks.

I wish one of the core developers will have a look on it.

**Comment by RoyiAvital** [comment]
Any update on a new backend?

**Comment by davidjgraph** [comment]
https://github.com/jgraph/draw-image-export2

**Comment by RoyiAvital** [comment]
@davidjgraph , Does this new backend support export of PDF with transparent background?

**Comment by davidjgraph** [comment]
If it does, we don't invoke it.

**Comment by RoyiAvital** [comment]
@davidjgraph , Any chance it will be checked?

It is really important feature to use draw.io in technical (University / Research papers) writing.

**Comment by septatrix** [comment]
I briefly looked into the current backend and found out it was using puppeteer which normally always prints a opaque background. [There seems to be a workaround](https://github.com/puppeteer/puppeteer/issues/2545#issuecomment-397590569) though I have not yet been able to get it working as I am not very familiar with the backend and only tried copying the snipped from the linked issue...

**Comment by septatrix** [comment]
With adding `... && data.format != 'html'` to this line https://github.com/jgraph/drawio/blob/f9f6c97197862380c1cc11d5f4303010adca5a82/src/main/webapp/export3.html#L403

and adding the following patch to the [image export repo](https://github.com/jgraph/draw-image-export2) this can already be achieved until puppeteer/chromium handles this better (i.e. a transparent background should be the default for a html page)

```patch
diff --git a/export.js b/export.js
index 8258733..aafcc95 100644
--- a/export.js
+++ b/export.js
@@ -655,6 +655,11 @@ async function handleRequest(req, res)
                                                var info = await rederPage(i);
                                                pageId = info.pageId;
                                                to = to > info.pageCount? info.pageCount : to;
+                                               await page.emulateMedia('screen');
+                                               await page._emulationManager._client.send(
+                                                       'Emulation.setDefaultBackgroundColorOverride',
+                                                       { color: { r: 0, g: 0, b: 0, a: 0 } }
+                                               );
                                                pdfs.push(await page.pdf(info.pdfOptions));
                                        }
```

I would have submitted a PR though this code being split between two different repos I do not know how you would like to handle this

See also the entries in the chromium bug tracker:
[Printed pdf is not transparent even though background is](https://bugs.chromium.org/p/chromium/issues/detail?id=1078851)
[Printing inserts a white page background colour](https://bugs.chromium.org/p/chromium/issues/detail?id=498892)

**Comment by ashrafteleb** [comment]
@septatrix Thanks a lot for your help. The code is merged and will be available in the next release

**Comment by septatrix** [comment]
In neither of the two repos I was able to find the patches and in the online version transparent backgrounds still do not work. Is the work on some private branches and for the next major release? Multiple minor releases have been made and this does not seem like it would be considered backwards incompatible.

The only change I was able to find was here https://github.com/jgraph/drawio/blob/a5b7153955308b40ad70feb45d1b23887e9434d9/src/main/webapp/export3.html#L411 though the logic is a bit different and seems to lead to unnecessarily different results. Regardless of it there still seems to be the patch missing for the export backend...

**Comment by ashrafteleb** [comment]
The code is there in export.js (
https://github.com/jgraph/draw-image-export2/blob/master/export.js)
await page.emulateMedia('screen');
await page._emulationManager._client.send(
'Emulation.setDefaultBackgroundColorOverride',
{ color: { r: 0, g: 0, b: 0, a: 0 } }
);

**Comment by septatrix** [comment]
Sadly I was not able to find said code in the repository. Also the last
commit is from April and my comment is from June...

Even if the code is included in both places this does not explain why it
still does not work online though that could be explained by an out of date
version

**Comment by davidjgraph** [comment]
This is an issue with branches, we'll get it sorted.

**Comment by davidjgraph** [comment]
This should now be resolved.
