### ISSUE TITLE
Cannot Open Existing Diagram in Chrome / Chromium version 85

### ISSUE THREAD

**Issue by yelban** [jgraph/drawio#1182]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Cannot select a folder in Chrome and Brave Browser

**To Reproduce**
1. visit draw.io & Authorization
2. Click on 'Open Existing Diagram'
3. Got  sign in screen again, if Click Sign-in twice, got Error
There was an error!
Details:
The feature you requested is currently unavailable. Please try again later.

**Expected behavior**
List folders in Google drive

**Screenshots**
![draw io](https://user-images.githubusercontent.com/981381/93153673-61d60f00-f734-11ea-8e4f-ff207df0e555.png)

![draw io 2](https://user-images.githubusercontent.com/981381/93153749-88944580-f734-11ea-8def-243c56bb9869.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 13.7.1]

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Chrome
 - Version: 85
 also
 - Browser: Brave Browser
 - Version: 1.13 ( Chromium 85 )

`It works fine in firefox version 80`

**Additional context**
Chrome dev tools - Console 
![screenshot 2020-09-15 上午9 17 47](https://user-images.githubusercontent.com/981381/93153829-ac578b80-f734-11ea-8006-1498ad7bf521.png)

**Comment by davidjgraph** [comment]
Never tested Brave, can you try Chrome incognito?

**Comment by yelban** [comment]
Hi @davidjgraph 

Yes, I did, It's not work in Chrome incognito.

![screenshot 2020-09-15 下午5 09 16](https://user-images.githubusercontent.com/981381/93190781-599ec380-f776-11ea-9120-99086e282cf2.png)

**Comment by philipobrien** [comment]
Came here to post the same error with Brave. Works fine in Chrome

![Screenshot 2021-02-03 at 15 43 32](https://user-images.githubusercontent.com/1763813/106771411-d43d8200-6636-11eb-8844-6042c7e6ed3a.png)

![Screenshot 2021-02-03 at 15 45 34](https://user-images.githubusercontent.com/1763813/106771442-dbfd2680-6636-11eb-91bb-03d1a1070c8c.png)
