### ISSUE TITLE
wrap the whole editor in webcomponent

### ISSUE THREAD

**Issue by lbrutti** [jgraph/drawio#1185]
Hello,
I'd like to drawio as a Web Component and i'd like to know if any one has ever tried to do this.

I've been searchin' on stackoverflow but I only saw examples of how to integrate drawio or mxgraph in Angular app, which is a different task wrt what i'm trying to do.

Thanks,
Lorenzo

**Comment by ArfanMirza** [comment]
I had achieved it for Angular6 by create webpack mxgraph library and inject whole grapheditor from library to angular component.
