### ISSUE TITLE
Rulers scaling with offset

### ISSUE THREAD

**Issue by HeavensBlade** [jgraph/drawio#1187]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
With "View" -> "Page View" disabled the ruler will shift when zooming in/out.

**To Reproduce**
Create a blank diagram.
Add a shape for reference.
1. Go to "View"
2. Disable "Page View"
3. Go to "View" -> "Units"
4. Activate "Points"
5. Go to "View"
6. Activate "Ruler"

Zoom in on the shape either using the zoom buttons or CTRL + Shift

**Expected behavior**
The position of the shape should match the rulers labels at any zoom.

**Screenshots**
![Screenshots with various zoom levels](https://user-images.githubusercontent.com/3123245/93587942-f47fe380-f9aa-11ea-9130-250e1228fcd9.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.6.9

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 80.0.3987.132 64-bit

**Comment by mararad** [comment]
Hi,

when "Page View" is not disabled, this is working well. Is there a particular reason you would like to have Page view disabled? Thanks,

**Comment by HeavensBlade** [comment]
Hello everyone,

since the update to 13.7.7 I can confirm this bug also happening in Page View:

![draw io paged 145](https://user-images.githubusercontent.com/3123245/95841718-f9d01400-0d45-11eb-9819-acf372ee1e45.PNG)
![draw io paged 210](https://user-images.githubusercontent.com/3123245/95841722-fa68aa80-0d45-11eb-927e-37fcd34f9b27.PNG)

Now using Chrome Version 85.0.4183.102 64-Bit

**Comment by ashrafteleb** [comment]
Fixed. 
Thanks for the report
