### ISSUE TITLE
PDF export not working anymore

### ISSUE THREAD

**Issue by schneijan** [jgraph/drawio#1188]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
On [draw.io](https://app.diagrams.net), it is not possible anymore to export diagrams as PDF. When selecting the PDF export via _File_ --> _Export as_ --> _PDF..._ the usual configuration popup shows up. Regardless of the entered settings there , when clicking on the "export" button, a new browser page opens showing only the message "Error!".
This error seems to occur always and indepently of the drawn diagram. Even a blank diagram or a diagram with just a simple box and text result in this error.
This feature has proven to be extremly useful when writing Latex papers, so I would be very happy if this could be fixed somehow.

**To Reproduce**
1.  Create a new diagram on [draw.io](https://app.diagrams.net)
2. Select the PDF export via _File_ --> _Export as_ --> _PDF..._
3. Just click the export button in the following popup
4. A new browser page is opened, showing the error message

**Expected behavior**
PDF export of diagrams should be possible.

**Screenshots**
![image](https://user-images.githubusercontent.com/44969037/93667958-cae9b980-fa89-11ea-9068-625a79129e12.png)

![image](https://user-images.githubusercontent.com/44969037/93667968-dccb5c80-fa89-11ea-9606-7517fff4ea41.png)

**draw.io version:** 13.7.3

**Desktop:**
 - OS: Windows 10 OS Version 1909 (Build 18363.1082)
 - Browser: Vivaldi 3.3.2022.45 (Stable channel) (64-Bit)

Note: I haven't tried to reproduce this issue on the desktiop app yet, I only used the web version.

**Comment by clojia** [comment]
I have the same issue since yesterday afternoon.

**Comment by davidjgraph** [comment]
Should be fixed now, thanks for report.

**Comment by StevenLi-DS** [comment]
I'm having this issue now again.
![image](https://user-images.githubusercontent.com/33796896/133005526-1a2b5b45-fc42-4185-91a8-2035073e70a5.png)
