### ISSUE TITLE
The option 'Open Library from’ URL is not available

### ISSUE THREAD

**Issue by JamesDLD** [jgraph/drawio#1193]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The option 'Open Library from’ URL is not available.

**To Reproduce**
1. Go to the 'File' menu
2. View ‘Open Library' and that's it.

Previously we there was Click on ‘Open Library from’. Click on ‘URL…’.

**Expected behavior**
Click on the ‘File’ menu. Click on ‘Open Library from’. Click on ‘URL…’.

**Screenshots**
Before like explained [here](https://www.moderndata.ai/2020/08/working-with-azure-icons-in-draw-io-diagrams-net/?utm_source=rss&utm_medium=rss&utm_campaign=working-with-azure-icons-in-draw-io-diagrams-net).
<img width="391" alt="image" src="https://user-images.githubusercontent.com/18073917/94036106-3c947100-fdc4-11ea-9fa3-60d40bca400e.png">

Now --> 
<img width="862" alt="image" src="https://user-images.githubusercontent.com/18073917/94036084-343c3600-fdc4-11ea-87a5-e11dcc894353.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.7.3

**Desktop (please complete the following information):**
 - OS: macOS Cataline Version 10.15.6

**Comment by mararad** [comment]
Hi,

I see Open library from > URL. If you update draw.io version to the latest (13.7.5) does it help? You could do a hard reload to update it.

Regards

**Comment by JamesDLD** [comment]
Hi @mararad ,
where can I found 13.7.5 for Mac, as per the [Release change log](https://github.com/jgraph/drawio-desktop/releases; the 13.7.3 is latest release.
Regards

**Comment by mararad** [comment]
Hi, 

I thought you were using diagrams.net online since this is a place for online issues (here is the link for desktop issues https://github.com/jgraph/drawio-desktop/releases)

If you try diagrams.net online, you should be able to see File > Open library from > URL (it seems that online version was used in the article you mentioned)

BR,

**Comment by JamesDLD** [comment]
Ok done : https://github.com/jgraph/drawio-desktop/issues/385
