### ISSUE TITLE
Cross Functional Diagram Column Mess

### ISSUE THREAD

**Issue by ramiredram** [jgraph/drawio#1195]
When moving flowchart objects around when using the Cross Functional template, the diagram objects tend to get inserted into the first column... mouse moving and shift constraint movement has a tendency to give this result.
![imagen](https://user-images.githubusercontent.com/17856304/94184608-c64a4a00-fe69-11ea-9631-0f3aad5c71d1.png)

**Comment by davidjgraph** [comment]
Please provide the detail requested the template when creating an issue, deleting it just wastes our time having to ask for it all.
