### ISSUE TITLE
customize the quick pallet

### ISSUE THREAD

**Issue by clevertension** [jgraph/drawio#1197]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/346723/94248715-6c24b400-ff51-11ea-98bb-33036bafdb1d.png)

i'd like to customize this quick pallet, now it will always popup the same diagram

**Describe the solution you'd like**

maybe we can drag and drop the diagram from and to the pallet

**Comment by clevertension** [comment]
any suggestion, maybe i can contribute the code

**Comment by stephanielawaegon** [comment]
This is something that my organisation is looking to be able to do too. We use BPMN symbols, so would like to be able to customise the pop-up to show only these options.

**Comment by davidjgraph** [comment]
Please only comment when adding additional information. Me too and +1s just create comment noise. Instead, thumbs up the original request.
