### ISSUE TITLE
Text not visible in exported pdf for Google fonts

### ISSUE THREAD

**Issue by matpandemo** [jgraph/drawio#1198]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Text not visible in exported pdf for Google fonts

**To Reproduce**
0. Build a BPMN diagram
1. Select all diagram components 
2. Go to Text tab in format panel
3. Select font custom and enter "Roboto" in Google Fonts options
4. Save the changes
5.. Go to File -> Export as -> PDF
6. provide the file name and save it to local folder.  Open the generated pdf file.  only the components are visible without any texts

**Expected behavior**
Diagram should be exported as is in PDF

**draw.io version (In the Help->About menu of the draw.io editor):**
- diagrams.net 13.7.3 Desktop version

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by mararad** [comment]
Reproduced this Win 10 and desktop 13.7.3. Google font text is missing when:
File > Export as > PDF
File > Export as > Advanced > PDF
File > Print > PRint as PDF

e.g. File > Export as > PNG is working well. 

Plus: when Google Fonts are used in diagrams.net online in Chrome and Chrome Incognito,
there is error 500 (File > Export as > PDF and Advanced > PDF) but all is good with a workaround File > Print > Print as PDF

**Comment by hellt** [comment]
That fix I wait so much!

**Comment by alderg** [comment]
Fixed. Thanks for the report!

**Comment by hellt** [comment]
Hi @alderg 
is there a regression? Today I exported a PDF and Google fonts are not there...

**Comment by alderg** [comment]
This was fixed in 13.6.7 so if you have shapes with special fonts from earlier versions, the font needs to be re-applied.
