### ISSUE TITLE
Offline restricted URL version

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#1200]
a xyz.diagrams.net sub-domain where external data transfer is disabled. 

Reason is to make draw "ED Law 2D compliant because it would not require, nor even enable, the transfer of student data." http://www.nysed.gov/common/nysed/files/programs/student-data-privacy/proposed-part-121-for-pii.pdf

**Comment by fzhan** [comment]
Perhaps the feature to export 100% localized offline html with not external call is need.
