### ISSUE TITLE
Resize of grouped arrows disappear

### ISSUE THREAD

**Issue by jasonkeithscott** [jgraph/drawio#1201]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Resize of grouped arrows disappear. The objects remain and can be selected, but the arrows are not visible.

**To Reproduce**
1. Drop arrow on new drawing. Align north-south.
2. Drop another arrow. Abutt first arrow. Align north-south.
3. Select both arrows and group.
4. Resize grouped arrows.
5. Arrows become invisible but may still be selected.

**Expected behavior**
I expected the grouped arrows to resize and not become invisible. I can group and resize other objects (e.g. rectangle) without disappearance.

**Screenshots**
[Poor quality screen capture](http://jasonscott.org/resize.mp4)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 13.7.5

**Desktop (please complete the following information):**
 - OS: Windows 10, 2004
 - Browser Firefox 81.0

**Comment by mararad** [comment]
Reproduced in diagrams.net online 13.7.6, Chrome, Chrome Incognito and FF.
It seems that only north-south arrow position grouping causes the issue (arrows can have a space between or be in line)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
