### ISSUE TITLE
Able to paste into locked layer if the layer is hidden

### ISSUE THREAD

**Issue by bjohas** [jgraph/drawio#1202]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I am able to objects paste into a locked layer if the layer is hidden. (To clarify: I am not able to objects paste into a locked layer if the layer is visible.)

**To Reproduce**
1. Create document with two layers.
2. Lock and hide one layer.
3. Copy an object from visible layer.
4. Activate locked layer (keep it hidden, keep it locked)
5. Paste

Result: The object appears on the locked layer, which becomes visible (and stays locked)

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 13.7.5]

**Desktop (please complete the following information):**
 - Browser [chrome]

**Comment by mararad** [comment]
Reproduced in Chrome and Chrome Incognito (in FF couldn't reproduce)
online version 13.7.6 and Win 10

**Comment by alderg** [comment]
¨Thanks for the report. This will be fixed in the next release.
