### ISSUE TITLE
Crow Foot Digrams not showing up on firefox 68.11.0

### ISSUE THREAD

**Issue by pmaurais** [jgraph/drawio#1204]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When a line is selected, a user can change the style of the line start and line end by selecting various icons from a drop down menu in the style drop down.  The crow foot icons (one to one, one to many) do not show up on the display.  If I save the diagram and reopen it in chrome, the icons added in firefox are visible.

**To Reproduce**
1. On firefox 68.11.0esr
2. Add a line to a diagram
3. Select the line and go to the style side bar
4. Change the line start or line end to one of the crow foot icons
5. The line should now have no icon for the start/end

**Expected behavior**
Crow foot diagrams are visible

**Screenshots**
Firefox
<img width="695" alt="firefox" src="https://user-images.githubusercontent.com/20339469/94482399-37119f00-01a7-11eb-9201-a72a11793ae3.png">

Same file in chrome:
<img width="301" alt="Chrome" src="https://user-images.githubusercontent.com/20339469/94482424-409b0700-01a7-11eb-8a2c-52a6dc30de0c.png">

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 13.7.6

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 68.11.0esr

**Comment by mararad** [comment]
Hi,

I tested this with Firefox 81.0 (64-bit) and arrow start and end show well. Could you update FF and try again?

Regards,

**Comment by pmaurais** [comment]
I failed to mention before that I am using the ESR version of firefox, I just upgraded to 68.12.0esr (32-bit) and still experience the bug

**Comment by davidjgraph** [comment]
I would try on FF 78 ESR, 68 has a number of rendering bugs.

**Comment by hengtangum** [comment]
The same problem on Chrome 85.0.4183.121 (64 bit): the crow's foot does not show.
The desktop version has no problem. Thanks.

**Comment by hengtangum** [comment]
The same problem on Chrome 85.0.4183.121 (64 bit): the crow's foot does not show.
The desktop version has no problem. Thanks.
