### ISSUE TITLE
Text Wrap Not Working

### ISSUE THREAD

**Issue by eightbit** [jgraph/drawio#1205]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Word wrap not working - see attached example.

**To Reproduce**

**Expected behavior**
Expect text to wrap to boundaries of text object.

**Screenshots**
[worWrapIssue.zip](https://github.com/jgraph/drawio/files/5299962/worWrapIssue.zip)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 13.7.3]

**Desktop (please complete the following information):**
 - OS: [e.g. Win10]
 - Version [e.g. [2004]](url

)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mararad** [comment]
Hi,

would you like to add the whole link
https://lacted.org/wp-json/wc/v2/products/?consumer_key=ck_52fe8090e45dc424f094a3237771a85a9a8b4a15&consumer_secret=cs_0038bf9e811dd1e958e772e6fc081faf45e20e08 
as a label to a Text shape from a library on the left? 

P.S since it is very long line, you could add a label and then link it (double click the label > Click Insert link on the right in Format panel > add URL and click "Apply".

Regards,

**Comment by eightbit** [comment]
No. I am just documenting our code, so I want it as a text field. Curiously, it does break at the question mark, is there a reason it won't wrap through the rest of the string?
Experimenting further, I see that spaces are required to activate word wrap. I assume that is a choice by the coders.

**Comment by mararad** [comment]
Thanks. Basically spaces are required and question mark (as a possible end of a sentence) can affect word wrapping. You could select text and in Property/Values change option under Text overflow but not sure if this suits your needs fully.
![options](https://user-images.githubusercontent.com/44292306/95067087-902b8680-0703-11eb-9764-8f810f3f1e27.JPG)

**Comment by eightbit** [comment]
Not quite. I just want to wrap all of the text in the box. But it isn't a big deal...

**Comment by berkdemir** [comment]
@davidjgraph is it closed? Cannot see word warping. I think the solution is still your video from 10 years ago. Shouldn,t we see the 'text wrap' check box in the text column?
https://www.youtube.com/watch?v=dRdwUKUv2LU

**Comment by liseri** [comment]
> @davidjgraph is it closed? Cannot see word warping. I think the solution is still your video from 10 years ago. Shouldn,t we see the 'text wrap' check box in the text column? https://www.youtube.com/watch?v=dRdwUKUv2LU

No; People are not fools; Text Wrap Not Working; Are you try it?

**Comment by tanberry** [comment]
I was hoping to use draw.io to diagram a JWT... but the long text of the encoded JWT won't wrap in a box. C'est dommaage, what a pity!

I need something like this to fit into a box and word wrap (but with no breaks):

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NBT3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36OPk6yJV_adQssw5x

**Comment by alderg** [comment]
Try [this](https://app.diagrams.net/?tags=%7B%7D#RjZNNk6IwEIZ%2FDUengAgzHFf8mGChq7g6tZepSAJkBMKGKOCv3yBRpLamai%2BkefpN0t3p1oCb1QuOisRnmKSaqeNaA1PNNB3rVX5b0HTAsA2rIzGnuGN6DwJ6JUp4p2eKSalYhwRjqaDFEIYsz0koBgxxzqqhLGIpHoACxWQQRguCEKXkH9mBYpF09M16Ur8TGif3mw1deTJ0FytQJgiz6gmBmQZczpjorKx2SdoWb1iX%2BTfeR2Cc5OJ%2FNgT7pfMxfr2sbbKvJ8Hs%2FRNYI3XKBaVnlbBm2qk8b4LppQ1aNKoS9p9zG%2BmkYhyPjpygkwZ%2B3NYRkveASS%2BRVtyupPGS4yKka%2BrBX1dorCgsYb61Qhfa8FR87F3PeZGiKz5AKYK1%2F%2BXrq8kOrKenCtKKHrO5%2BB3cxBe0GMfbhZO2HB3mOvxi9Wo3M%2BUey5%2FCJtq8BFG6rKutF%2FhkuZybm904qgqfeBGw1z9PduPtPxHelGVl1fcsZbluiXYBq4d65Gxyds4xaQuot6knVJCgQGHrrWS%2FS5aITCY%2FNaQZsVyoBjbsx2kXwgWpv30z49EJcoQIy4jgjZSoDRZQ86PGZ2Q6bx2o%2BmYEutOx5LkRdbUTqQGIH4f3PSIN1Sb3374db76noQazvw%3D%3D) via HTML style="word-break:break-all;"

<img width="631" alt="Screenshot 2023-03-29 at 05 33 49" src="https://user-images.githubusercontent.com/921200/228420102-14d0aa5e-bb40-45ec-9a5c-954c2d794b63.png">

**Comment by tanberry** [comment]
Thanks so much @alderg I'll give that I try as soon as I can.

**Comment by davidjgraph** [comment]
Closing, workaround provided.

**Comment by phwoo** [comment]
The workaround provided does not properly wrap text. Is there another solution?

**Comment by davidjgraph** [comment]
@phwoo if you have a problem please open a new ticket. Otherwise, a single ticket becomes unmanageably long.
