### ISSUE TITLE
Dropbox (business) - can't create a new diagram/authorise connection

### ISSUE THREAD

**Issue by jaylapras** [jgraph/drawio#1206]
### Preflight Checklist
* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Unable to create a new diagram / authorise when logged into a Dropbox business account.
* This only happens if you are logged into a Dropbox Business/Team account. 

**To Reproduce**
1. Log into Dropbox (business/team account)
2. From app.diagrams.net, select Dropbox as the storage, click new diagram, then Create - see the Authorise dialog. 
3. Click Authorise, goes through to Dropbox, you can authorise app, then it returns to app.diagrams.net, but still shows the Authorise dialog. 
4. Clicking Authorise again gives an error. 

**Expected behaviour**
Be able to create a new diagram, stored in Dropbox.
 
Cancelling Dropbox Business to only use Dropbox Basic (Personal) - I did not need to re-authorise the connection. I could create a new diagram and save it in dropbox from the splash screen, as expected. 
I suspect the authorised connection was on the personal account, but the create new / save process tried to use the business account.

- draw.io version 13.7.6

 - macOS
 - Chrome
 - Version 85.0.4183.121

**Comment by mararad** [comment]
Authentication to Dropbox is direct, so dropbox domain cookies must be allowed.. Some browsers and browser extensions block third-party cookies, assuming they are trackers.

Initial advice would be to repeat all the steps in a different browser and Private mode. Also, clear the cache and temporarily disable all browser extensions. Incognito mode is great for testing cause it is cache and extension free (cache and extensions can cause some problems sometimes)
