### ISSUE TITLE
Store alternate text in diagrams to support i18n

### ISSUE THREAD

**Issue by gvwilson** [jgraph/drawio#1208]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

1. We are using diagrams.net to create concept maps (see https://github.com/rstudio/concept-maps/).
2. We would like these to be available in multiple languages, so we copy a diagram in language X and change the text to create one for language Y.
3. But then someone improves either the original or the translation, and now we have to copy those changes back into the other copy or copies.

**Describe the solution you'd like**

We would like to be able to store alternate strings in objects, keyed by language. For example, a box with text could store both of the strings "rouge" and "red". The first would be associated with the key 'fr' and the second with the key 'en'. If the user selected 'en' from a pulldown menu (or other affordance), _all_ of the objects would display their English text; if she selected 'fr', all of the objects would display their French text. That way, people doing translations could add text in place, while people who didn't understand the language would be able to check if their edits broke anything: for example, they could see if resizing a box would make it too small for the Japanese translation without having to understand Japanese.

**Describe alternatives you've considered**

We have tried storing the diagram as SVG and modifying the text directly, but that approach is error-prone, and storing a table of translation strings separately from the diagram itself is clumsy.

**Additional context**

Please see https://github.com/rstudio/concept-maps/ for examples.

**Comment by gvwilson** [comment]
Sorry to see this closed - this feature would help a lot internationalization efforts in open source.

**Comment by felixvd** [comment]
I agree that there are exciting possibilities for internationalization with the draw.io format (XML in SVG). I am looking at a similar problem and saw that https://github.com/jgraph/drawio/issues/1684 also raised this issue, so it seems that there is some interest. It would be great if there was a way to enable translation of diagrams without much additional development. (@davidjgraph )

@gvwilson You wrote that storing the translation strings separately is clumsy, but for projects using the [`gettext` pipeline](https://www.gnu.org/software/gettext/manual/html_node/Overview.html#Overview), it would not be much additional effort at all. I estimate that for my use case, replacing the text in the diagram's XML and regenerating the SVG would be sufficient. But I don't see a convenient way to extract the fields from XML.

Have you tried getting the translation strings from a diagram, or have any [parsing rules](https://www.gnu.org/software/gettext/manual/html_node/Preparing-ITS-Rules.html#Preparing-ITS-Rules) for this?

**Comment by alderg** [comment]
There is a URL parameter translate-diagram and diagram-language which can be used for adding i18n in the lightbox, eg. [English](https://viewer.diagrams.net/?translate-diagram=1&diagram-language=en&tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1#RdZNNc4MgEIZ%2FjcfMiObDXpuk6aE5dJxOjh0iWyFFMYhV%2B%2BsLAfyYJifZZ99ll901iLdFd5C4okdBgAdRSLog3gVRhJ5Wif4Y0luyWUcW5JIRi8IRpOwXXKSnDSNQO2aREoIrVs1hJsoSMjVjWErRzmVfgpMZqHAOszIMSDPM4Z%2FsxIiiliarifoVWE59ZhQ6T4G92IGaYiLaCYr3QbyVQih7KrotcNO8eV9eHniHwiSU6k6AOF9MP6KQ47OeyU2wL3POamojb%2FyTuHfuoFF15lxDjuNV5pfjW38qvpcf0fW9QmSBhtqHmmrV%2B35J0ZQETHwYxM8tZQrSCmfG2%2BoN0YyqwpSDzBFntJFwMHy31MCm%2FwGpoHv4zGkBBxAFKNlriQtYoI0N6f0iObsdx4fWbiZ0MrrEMew2Jh%2BuHpuqD%2B7R3nRt9uY4zpt08lPE%2Bz8%3D) and [German](https://viewer.diagrams.net/?translate-diagram=1&diagram-language=de&tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1#RdZNNc4MgEIZ%2FjcfMiObDXpuk6aE5dJxOjh0iWyFFMYhV%2B%2BsLAfyYJifZZ99ll901iLdFd5C4okdBgAdRSLog3gVRhJ5Wif4Y0luyWUcW5JIRi8IRpOwXXKSnDSNQO2aREoIrVs1hJsoSMjVjWErRzmVfgpMZqHAOszIMSDPM4Z%2FsxIiiliarifoVWE59ZhQ6T4G92IGaYiLaCYr3QbyVQih7KrotcNO8eV9eHniHwiSU6k6AOF9MP6KQ47OeyU2wL3POamojb%2FyTuHfuoFF15lxDjuNV5pfjW38qvpcf0fW9QmSBhtqHmmrV%2B35J0ZQETHwYxM8tZQrSCmfG2%2BoN0YyqwpSDzBFntJFwMHy31MCm%2FwGpoHv4zGkBBxAFKNlriQtYoI0N6f0iObsdx4fWbiZ0MrrEMew2Jh%2BuHpuqD%2B7R3nRt9uY4zpt08lPE%2Bz8%3D)

**Comment by felixvd** [comment]
@alderg Thank you very much for the pointer! Let me ask a few more questions:

1) When I set a diagram language using your third link, create a cell and edit its text, it is stored under `value` in the cell properties, not `label_XY`. The diagram from your first links does not use the `value` field. Is any other setup required?

2) I have looked into scraping the translation strings from the diagrams into `po` files (the `gettext` workflow). Is there a way to add a custom tag such as `doNotTranslate` to a cell?

I haven't seen documentation on the document format while reading the source code, so for anyone who is interested:

The `.drawio.svg` file contains the tag `<svg ... content="XXX">`, where the `content` property contains the XML of the `mxfile`, as one can download via `Save As`. Inside, each `diagram` tag contains a base64-encoded string of a compressed XML of an `mxGraphModel`, which is what you can inspect with `Extras/Edit Diagram...` in the editor. The string can be decoded with [this tool](https://jgraph.github.io/drawio-tools/tools/convert.html) and [this Python gist](https://gist.github.com/felixvd/257701b1ead4b53aaaeb2585eae970f3), which also extracts the text from the diagram, for use in a translation pipeline (possibly with [`sphinx-build gettext`](https://www.sphinx-doc.org/en/master/usage/advanced/intl.html)).

PS: Love this project and I am happy that we are supporting it through your Confluence integration.

**Comment by alderg** [comment]
Use Edit Data to edit the label_XY (Ctrl+M). For no translation, just don't add translations to the cell.

**Comment by felixvd** [comment]
Thanks, I didn't know about that command. That answers both my questions.

I updated the [gist](https://gist.github.com/felixvd/257701b1ead4b53aaaeb2585eae970f3) with Python code to read the text fields from a diagram (or SVG with an embedded diagram), overwrite them, save the changed diagram, and generate a new SVG using the `drawio` CLI. Maybe this can help someone who needs to extract translation strings from and update diagrams with the translations.

**Comment by felixvd** [comment]
@alderg I saw that [`urlParams.json` is read from the working directory](https://github.com/jgraph/drawio/blob/dev/src/main/webapp/js/grapheditor/Graph.js#L1285) when using the CLI, and succeeded in loading [a diagram](https://gist.github.com/felixvd/f1ceb3b81e912e3bffe03579512e35f9) in German and English, by setting  `translate-diagram` and `diagram-language`. However:

- When exporting via the `-x` option, the output is not in the `diagram-language`
- In the Desktop app, clicking `Extras/Diagram Language` gives this error:

![Screenshot from 2022-08-08 10-01-39](https://user-images.githubusercontent.com/4535737/183319355-dfe56b1b-2c93-4b38-b93e-28e68f84d0ea.png)

Am I missing something simple or should I post a new issue?

To reproduce (on version 19.0.3):

- Download [these files](https://gist.github.com/felixvd/f1ceb3b81e912e3bffe03579512e35f9) and navigate to the folder
   - `drawio testdiagram-de-en.xml` should display the diagram in German
   - `drawio -o testdiagram_out.svg -x -f svg testdiagram-de-en.xml` will output the diagram in English although it should be in German

**Comment by davidjgraph** [comment]
@felixvd that's a new issue in the desktop project please.
