### ISSUE TITLE
Support links in Mermaid diagrams, specifically in the viewer

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1210]
Support clickable links in Mermaid diagrams, specifically in the viewer
(asked here: https://drawio.atlassian.net/browse/DID-956)

Links are working in Mermaid live editor https://mermaid-js.github.io/mermaid-live-editor

**Comment by davidjgraph** [comment]
Now that we natively convert mermaid to draw.io, you should have links. If not, please report.
