### ISSUE TITLE
Diagram with C4 plugin throws "illegal constructor" error on copy/paste

### ISSUE THREAD

**Issue by builder7777** [jgraph/drawio#1212]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I created a diagram several months ago using draw.io. I had a c4-draw.io plugin (https://github.com/kaminzo/c4-draw.io) at the time. Today I opened the same file using draw.io (i have not made any changes to it since) and tried modifying it. As soon as I try to copy (or duplicate) a block, it throws an error "illegal constructor".

**To Reproduce**
1. Select a block
2. Right click
3. Select Copy

**Expected behavior**
The block should be copied to clipboard

**Screenshots**
<img width="1000" alt="Screen Shot 2020-10-01 at 16 15 49" src="https://user-images.githubusercontent.com/44239909/94859049-f1044780-0401-11eb-8dd9-e5079de0f688.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.7.7

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.2
 - Browser: Chrome
 - Version: 85.0.4183.121

**Additional context**
I also tried searching the existing bug reports, there's a closed bug that does not allow any comments and there's no solution provided. There is a link to another bug report but it is not clear what needs to be done to fix the problem from a user's perspective.

**Comment by davidjgraph** [comment]
The author of the plugin is responsible for this, not us.
