### ISSUE TITLE
Search doesn't take into account the embedded diagrams

### ISSUE THREAD

**Issue by CorentinHache** [jgraph/drawio#1215]
**Is your feature request related to a problem? Please describe.**
I am not able to find, using the Confluence search, a string located in an embbeded drawio. 

**Describe the solution you'd like**
I would like the string present in an embedded drawio to be taken into account by the Confluence search feature.

**Comment by davidjgraph** [comment]
Is this Confluence Server or Confluence Cloud?

**Comment by CorentinHache** [comment]
It's Confluence Cloud.

**Comment by davidjgraph** [comment]
Unfortunately, this isn't practically possible.
