### ISSUE TITLE
Bottom right cropping and/or borders are sometimes wrong  when exporting to SVG using Selection, Crop and Border settings

### ISSUE THREAD

**Issue by szcsl** [jgraph/drawio#1216]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Border and/or cropping seems to be malfunctionging **sometimes** when exporting to SVG using Selection Only + Cropping + Border Width (=20). 

Bottom right side is cropped or the borders are missing. Same export is correct after restarting the app.

**I'm happy to look into this if someone can help tracing the Export functionality in the repo.**

**To Reproduce**
Couldn't reproduce it intentionally, because I don't know what triggers the error, but will update this as soon as I have more info.

**Expected behavior**
Exported image should be properly cropped and proper borders on all four sides.

**Screenshots**

Image shows the SVG inspected in DevTools. The yellow Heap box should have the same border around it an all four sides.

![Screenshot 2020-10-05 at 23 18 30](https://user-images.githubusercontent.com/42765413/95133173-2f329b80-0761-11eb-8152-e212193c1c21.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.4.4 (macOS desktop app)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Browser N/A
 - Version N/A

**Additional context**

I have a fairly large 5 x 5 canvas with lots of small diagrams (instead of one file for each). By 5 x 5, I'm referring to when the editor automatically extends the canvas when moving a diagram to the edge.

Might be related to #866

**Comment by orangy** [comment]
I just had the same issue, but exporting the whole drawing to PNG with borders – left/top border is correct, but bottom/right part of the image is clipped seemingly exactly by the 2 border sizes. Setting border to zero doesn't cause any clipping. macOS 10.15.6, desktop app.

**Comment by rattle99** [comment]
Issue still persists

**Comment by tavurth** [comment]
Can we reopen this? Happens every time with larger drawings.

**Comment by jenn-jk** [comment]
It is July 22 2021. This issue still remains unfixed. I get around this by adding some 'dummy blocks' in the right and bottom corners and manually crop the exported image.

**Comment by tavurth** [comment]
> I get around this by

It's easier to just draw a white (disable border lines) box around the area you want to export, then export with no margin.

**Comment by alderg** [comment]
We're unable to reproduce this problem. What are the exact steps? What version of the app?

**Comment by szcsl** [comment]
@alderg I can't reproduce it intentionally, it just happens from time to time.

I haven't used the app for some time now, so I don't know if it persists in newer versions. The version I was using when I opened the issue is stated in the issue description. (13.4.4, macOS (10.15.6) app)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release. (We were able to reproduce it when the diagram was zoomed, eg. 30%.)

**Comment by tavurth** [comment]
Thank you for figuring it out @alderg! 🥳
