### ISSUE TITLE
Google Authorization not working in Safari

### ISSUE THREAD

**Issue by gusc** [jgraph/drawio#1226]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Whenever I try to authorize using my Google account either in app.diagrams.net directly or from Google Drive by opening a drawio file it gets stuck at the https://app.diagrams.net/google?state=[redacted]&code=[redacted]&scope=profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.file+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.install redirect which returns HTTP error 401.

Same happens in Private browsing mode.

This also happens in the same Safari browser but with a different Google account.

This does not happen in Google Chrome on the same machine.

**To Reproduce**
1. Go to app.diagramms.net
2. Click on "Google Drive"
3. Click on "Authorize"
4. Blank popup dialog, if you have already logged in with Google Drive, or Google auth which ends with the same blank dialog, if you are not.

**Expected behavior**
I would expect to be authorized and continue to start drawing them sweet sweet diagrams.

**Screenshots**
<img width="1496" alt="Screenshot 2020-10-08 at 15 31 41" src="https://user-images.githubusercontent.com/1258045/95458925-8dd36180-097b-11eb-95fc-478f111cc760.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- app.diagrams.net 13.7.8

**Desktop (please complete the following information):**
 - OS: macOS Mojave (10.14.6)
 - Browser: Safari
 - Version: 13.1.2

**Comment by davidjgraph** [comment]
It might be Safari is blocking third-party cookies, which Google counts as in this case. Could you check that please?

**Comment by gusc** [comment]
Checked, looks like it's not the case - Block all cookies was unchecked for me, I tried disabling the "Prevent cross-site tracking" also to no avail and finaly I tried clearing all the Google and diagrams.net related cache and cookies and still nothing.

**Comment by gusc** [comment]
Also if it helps - the only cookie delivered from my browser to app.diagrams.net is `__cfduid`

**Comment by barratt** [comment]
This is currently happening with Safari on iPad too.

**Comment by davidjgraph** [comment]
Is it possible to upgrade to Safari 14 and try again? I don't have a Safari 13.1.2 to test on.

**Comment by gusc** [comment]
I'll try Safari 14 if it's possible to run it on Mojave.

In the meantime I tried Safari 13.1 on a different mac with macOS Catalina (10.15.4) and this is what happened:

* I was already authorized with Google Drive long time ago so at first it just opened up the diagrams without even asking to authorize
* Just to be sure I logged out of all my Google accounts, but app.diagrams.net stayed logged in so I cleared all the cookies and cache for diagrams.net domain.
* After that I couldn't authorize with Google anymore, but this time it redirected me to URL https://app.diagrams.net/connect/office365/drive.html which displays this: 
<img width="637" alt="Screenshot 2020-10-09 at 08 52 46" src="https://user-images.githubusercontent.com/1258045/95547991-d850ee80-0a0c-11eb-85be-2df64dbd19d1.png">

* Then I tried to authorize for the second time and it just worked.

**Comment by davidjgraph** [comment]
10.14 does support Safari 14, https://en.wikipedia.org/wiki/Safari_version_history.

The red signin button is usually a sign of third-party cookies being blocked or a local invalid cookie being stored.

**Comment by gusc** [comment]
How did you get Safari 14? It's still in beta and no official update channel provides it yet (neither on Mojave, nor Catalina).

**Comment by gusc** [comment]
Oh, just ran the update on my Mojave mac and got Safari 14.0 and it actually works now! But still for those stuck on 13.1.x it might still be an issue.

**Comment by davidjgraph** [comment]
Yes, but it might be outside our control. I'm also not sure whether the browser version was the issue or some session cookie/localStorage/IndexedDB entry was corrupt and updating cleared something.

I'll close and other users can open tickets specific to their problem if needed.

**Comment by pedroan8** [comment]
Looks like I got same issue on my Mac using Safari 14.1

I found a little solution to make it work, usually it shows a white screen and it doesn't do anything.
<img width="1578" alt="2021-06-02_08-45-28" src="https://user-images.githubusercontent.com/66959154/120436277-03fb5d00-c37f-11eb-8d9a-d29792c6fbb4.png">

What I did is uncheck the block content that was on by default.
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/66959154/120437141-12964400-c380-11eb-9b28-5c981c841bbe.png">

Hope it can help someone.

**Comment by iwensu0313** [comment]
Thank you! @pedroan8

**Comment by edwardaux** [comment]
FWIW, after hours of trial and error, I eventually found the magic that fixed the problem for me. For me, my symptoms where that I'd get the small accounts.google.com popup and then after I'd clicked on Allow, I'd always end up with it just showing a blank white window (note that this is in Safari only... Chrome works just fine)

I'd tried a million combos of turning off Content Blockers and allowing popups along the way... the one thing that fixed it for me was to enable popups globally (see screenshot below).  This let me get past the blank popup and now it works (even if I turn that setting back to Block and Notify like it originally was).

May not solve it for everyone, but hopefully this will help someone else.

![image](https://user-images.githubusercontent.com/1574429/152077737-1c6b02cf-d4ed-4246-b5e2-158e161e1c5b.png)

**Comment by varadnarvekar** [comment]
Hey @edwardaux, the solution you stated worked for me ! kudos to you
