### ISSUE TITLE
Context menu action to replace/change/swap a shape of an existing element in the drawing

### ISSUE THREAD

**Issue by orangy** [jgraph/drawio#1227]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When polishing the diagram I often want to replace some shapes with another shape, e.g. replace rounded rectangle with ellipse, but maintain size, text, styles, etc. 

**Describe the solution you'd like**
I want a context menu action to change a shape on the existing node. 

**Describe alternatives you've considered**
Workaround I'm aware of is to place new shape, copy text and styles, and size it properly. Doesn't work on multiple selected nodes, takes way too much time.

**Comment by mararad** [comment]
Hi,

I use diagrams.net 13.7,9, Win 10 and Chrome Version 86.0.4240.75 (Official Build) (64-bit).

For a shape replace, I use shorter way: select a shape (or multiple shapes), 
hold Shift and click a shape from library on the left I am trying to replace shape(s) with.

![replace](https://user-images.githubusercontent.com/44292306/95576419-b4070900-0a30-11eb-90d7-bdee0aad3696.gif)

Does this help a bit?

**Comment by orangy** [comment]
OMG, this is exactly what I need, thank you so much! However, it is completely undiscoverable or I'm blind to find it…
