### ISSUE TITLE
Underline text with dashed line

### ISSUE THREAD

**Issue by gurjeetsingh** [jgraph/drawio#1230]
* [ y] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [y ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
In many CS courses, Entity Relationship Diagrams (ERD) are made at the beginning of database courses. 
In these ERD diagrams, weak entity sets with partial keys require the attributes that are part of the partial key to be underlined with a dashed line. As this is common across many Computer Science programs, it may be a worthy pursuit to resolve.

**Describe the solution you'd like**
An option to alter the underline of text (as if it were a line). Or a weak entity set attribute shape templet/preset.

**Describe alternatives you've considered**
Drawing and placing the dashed line underneath text, although consistency is difficult.

**Additional context**
N/A

**Comment by gurjeetsingh** [comment]
duplicate

**Comment by faid0n** [comment]
Came across the same problem. Which issue is it a duplicate of?
