### ISSUE TITLE
Error saving file to drive even the internet works fine and g drive signed in

### ISSUE THREAD

**Issue by lalith20** [jgraph/drawio#1234]
### Preflight Checklist

* [ yes ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ yes ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Error saving file to drive even the internet works fine and g drive signed in

**To Reproduce**
1. Go to 'File'
2. Click on 'Save'
3. See error
4. Says error timeout 

**Expected behavior**
All changes were saved is not showing up

**Screenshots**
![Screenshot (39)](https://user-images.githubusercontent.com/66118438/95711920-5e756b00-0c81-11eb-9f7e-7a7ba0188841.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [13.7.9]

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [86.0.4240.75]

**Smartphone (please complete the following information):**
 - Device: [Redmi note 7s]
 - OS: [Android 10]
 - Browser [Chrome]
 - Version [latest playstore version]

**Additional context**
It was working fine until yesterday night i was working on the project from morning the problem still exists now

**Comment by mararad** [comment]
Hi, 

since you mentioned that it was working fine till yesterday, my advice would be to repeat all the steps in a different browser and Incognito mode. Also, clear the cache and temporarily disable all browser extensions.

Incognito mode is great for testing cause it is cache and extension free (cache and extensions can cause some problems sometimes)

**Comment by lalith20** [comment]
Hi sir,

yes sir did that tried Microsoft edge and incognito, Reinstalled chrome, Cleared cache with ccleaner its still showing the same error and i also downloaded the drive file and tried to edit in another mail still its showing the same, i also switched to mobile data and checked its still the same

**Comment by mararad** [comment]
If there is no sensitive data, could you attach the file here so I could test it (you could click Extras > Edit diagram and copy/paste the code)? 
Are there any complex images or many of them added to the diagram?

Thanks,

**Comment by lalith20** [comment]
it says your comment is too long (maximum is 65536 characters) i am attaching a word document with the code pasted in it
[New Microsoft Office Word Document.docx](https://github.com/jgraph/drawio/files/5367133/New.Microsoft.Office.Word.Document.docx)

**Comment by brnpl89** [comment]
We have version 21.0.2 self-hosted and we are experiencing this issue with diagrams that are large or too complex. Is it possible to reopen this issue? Additionally, Is it possible to increase the timeout value, to give it a bit more time to try to save?

**Comment by davidjgraph** [comment]
Please open a new issue and submit as a proper bug report.

**Comment by brnpl89** [comment]
And do i have to open a new issue just to know if it's possible to increaste the timeout value? Can't you just answer me here?
