### ISSUE TITLE
Improved Icon Search

### ISSUE THREAD

**Issue by schabert** [jgraph/drawio#1236]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
The search for suitable ICONs is difficult. As long as you search for "standard" names like SNS, EBS, S3 you get good results.

But as soon as you leave specific services e.g. Gateway to find schematic icons. It becomes difficult.

There are 3 concrete problems for me the first one
1. the name must be complete to find results
Part name like Gatew
do not work because only the "names" are searched.  

2. the sorting of the icons always searches in "standard" libraries first. We often use custom libraries and they always appear last in the search.

3. the search is only started after "Enter" and not already while typing as it is often done in the meantime.

**Describe the solution you'd like**
My suggestion would be that the iconSearch searches for wildcards by default, i.e. "contains" text in the title or in labels.
e.g. "gatew" -> "gatwa*" will find "gateways

The sorting should prefer Custom Libraries that are integrated, i.e. the icons from Custom Libraries should be displayed first.
Because of their integration they have a higher value for the user.

The search should not be triggered by "enter" but directly when typing each letter.

Additionally it would be great to search in the labels of icons to find categories like 
Gateway has the property "component": "iot,aws,eu-central-1
And the search allows you to search for parts of it "eu-central*" also finds the gateway

**Describe alternatives you've considered**
An alternative would be to replace the search optionally by a "Plugin" which can be particularly adapted and the inquiries so to speak to the Plugin forwards and the anfrage then answeredts answers)

**Additional context**

**Comment by davidjgraph** [comment]
Thanks for your input. We've looked into this issue and it is useful, but the complexity of implementation does not justify the effort in this case.
