### ISSUE TITLE
XML export question.

### ISSUE THREAD

**Issue by matbor** [jgraph/drawio#1238]
A quick question, as I can't see it listed/asked anywhere, but when exporting a BPMN diagram from within Drawio using the XML export does it support the BPMN 2.0 XML notation. BPMN 2.0 specifications http://www.bpmn.org .

I believe it doesn't but can you confirm this?

Thx.

**Comment by davidjgraph** [comment]
It does not.

**Comment by margarida1ataide2** [comment]
Hello. Does this still apply? It is still not possible to export a BPMN diagram from within Drawio using the XML export?

**Comment by davidjgraph** [comment]
All updates to the subject are in this thread. It is not possible and we do not intend to implement it.
