### ISSUE TITLE
Improved tags dialog/panel

### ISSUE THREAD

**Issue by StianOvrevage** [jgraph/drawio#1240]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
It's very hard to use tags. There is no way to see the tags that have been used. You have to already know them. Also typing and then clicking show/hide is tedious and error-prone.

**Describe the solution you'd like**
The tags panel being similar to the layer panel. It shows the list of used tags and a checkbox for show/hide.

**Describe alternatives you've considered**
Creating a bunch of almost-identical and overlapping layers to be able to switch between views (physical, logical, per-system, etc).

**Additional context**
Layers panel:
![image](https://user-images.githubusercontent.com/6630005/95988709-928b9000-0e29-11eb-817d-987fdf9264d1.png)

Tags panel:
![image](https://user-images.githubusercontent.com/6630005/95988766-aafbaa80-0e29-11eb-892d-409799b45332.png)

**Comment by mararad** [comment]
Tag multiple objects at once 

When selecting multiple objects, and choosing Edit --> Edit Data, ideally I should be able to set a property for all selected objects.

**Comment by mararad** [comment]
Support "not" for tags
"I need the ability to hide everything not tagged "abc" while toggling the visibility of the "abc" tagged items."
https://desk.draw.io/a/tickets/12263

**Comment by ashed** [comment]
similar issue #1184 - Set properties and placeholders for multiple shapes

**Describe the solution you'd like**
Being able to select multiple shapes and adding metadata that will be added to all of them at the same time.
Add panel with all existed Tags and buttons with bool operators (tag1 AND tag2 NOT tag3).
Add command with button seems like "copy tags/paste tags" to current layer/selected layers.

Describe alternatives you've considered
Being able to select with conditions, copy and paste tags.

**Comment by davidjgraph** [comment]
Implemented

**Comment by chipbite** [comment]
Cool, I missed this. Looks really great! 
![image](https://user-images.githubusercontent.com/559199/148794324-e11deb2d-b920-4cfd-9d39-85a3e60557bd.png)

(But there is no keyboard shortcut for it?)
