### ISSUE TITLE
1 insert failed

### ISSUE THREAD

**Issue by oscarurrego** [jgraph/drawio#1241]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

When I try to insert a diagram to a google drive slide with the help of the plugin, I get the following error:
1 insert failed:
- xxxxx.drawio: No se ha encontrado el objeto de destino al llamar al método getPageWidth en el objeto con ID 38.

**To Reproduce**
1. Go to Slide and select diagrams.net for slides.
2. Click on insert diagrams
3. Select the diagram and the page.

**Expected behavior**
Insert the diagram witout problem

**Screenshots**
![image](https://user-images.githubusercontent.com/70965705/96177282-3bea8880-0ef3-11eb-8f58-37b56875b1fe.png)

**Comment by mararad** [comment]
Hi,

I tested this and it is working well at my place. I use Win 10 and Chrome Version 86.0.4240.75 (Official Build) (64-bit)

* if you repeat the steps in other browsers and Incognito mode, does it help?
* are you able to open other diagrams in Slides i.e do you have a problem only with this one?
* are you able to open the diagram in draw.io editor? does the diagram exist? If I understand this well, it says that target object isn't found?

Thanks,

**Comment by lucafabbri365** [comment]
Hello,
I'm encountering the same error (I have latest published version of Windows 10 and Chrome). In my case it happens with specific diagram/page: if I remove some images/objects from the page, it works. The diagram itself has no issue. I also tried to create new diagram, copy and paste XML but I get the same error.

Bye,
Luca
