### ISSUE TITLE
Ungroup does not work

### ISSUE THREAD

**Issue by LatinSuD** [jgraph/drawio#1247]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I cannot ungroup a certain group.

**To Reproduce**
1. Open this diagram: https://drive.google.com/file/d/1Uy1Dkj608R9NviTiqn6A30F9tZNgyOd1/view?usp=sharing
2. Ungroup the object
3. Check if it has been ungrouped, for example try to drag the bigger part. It is still grouped.

**Expected behavior**
Dragging on an ungrouped object should not carry the other objects with it.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.8.1

**Desktop (please complete the following information):**
 - OS: Debian Linux 10
 - Browser Chrome
 - Version 86.0.4240.111 (Build oficial) (64 bits)

Also tested on Firefox and Windows.

**Comment by mararad** [comment]
Hi, 

what steps you perform to share a file? Could you give edit permissions also since it is read only at the moment? 

Regards,

**Comment by LatinSuD** [comment]
> what steps did you perform to share a file? Could you give edit permissions also since it is read only at the moment?

Sorry, I was expecting you to download it (it's XML) and upload to the editor.

**Comment by LatinSuD** [comment]
Btw, there is a more simple way to reproduce the bug.

I also created a video demonstrating it:
https://www.youtube.com/watch?v=hcQXbzNsegU&feature=youtu.be

**Comment by GrumpyZhou** [comment]
The ungroup doesn't work for me as well. Just open a new diagram and try to group two random components and then they can not be ungrouped anymore.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release, scheduled for later today.
