### ISSUE TITLE
Firefox's `privacy.resistFingerprinting` setting breaks clipboard operations via keyboard

### ISSUE THREAD

**Issue by schnerring** [jgraph/drawio#1248]
### Preflight Checklist

* [ x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
If setting Firefox's `privacy.resistFingerprinting` to `true`, clipboard operations via keyboard shortcuts (`CTRL+C` etc.) stop working. Shortcuts unrelated to clipboard actions do work as expected.

**To Reproduce**
1. Install latest version of Firefox
2. Run `firefox -p` and create a test profile and run the profile
3. Go to [draw.io](https://draw.io), insert a shape and verify copy / paste with `CTRL+C` / `CTRL+V` works
4. Go to `about:config` and set `privacy.resistFingerprinting` to `true`
5. Repeat step 3 and verify that it stopped working

**Expected behavior**
Clipboard actions should function properly, regardless of the setting `privacy.resistFingerprinting`.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: 13.8.1

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Firefox
 - Version 81.0.2 / 82.0

**Additional context**
I enabled the `Event Listener Breakpoints` for `Clipboard` and `Log` in the Firefox debugger and performed the following actions:

1. Insert shape
2. `CTRL+C`
3. `CTRL+V`

Console output (`privacy.resistFingerprinting = false`):

> copy { target: div, clipboardData: DataTransfer } app.min.js:273:97
> paste { target: div , clipboardData: DataTransfer } app.min.js:273:97

Console output (`privacy.resistFingerprinting = true`):

> no output

**Comment by davidjgraph** [comment]
There's no other way to implement copy/paste. It's expected this FF function would break it.
