### ISSUE TITLE
How do i change the Grid size from 4 squares to 5 ? 

### ISSUE THREAD

**Issue by TheaterStrahl** [jgraph/drawio#1249]
I would like to change the Grid size from 4 squares to 5. 
I can't find a solution... any ideas ?

**Comment by TheaterStrahl** [comment]
in draw io.

**Comment by mararad** [comment]
"Please add the ability to customize the grid. I'd like a grid that is 5 smalls squares per 1 large square (5:1).
This site (https://incompetech.com/graphpaper/multiwidth) has an interesting interface for generating graph paper. It's a bit complicated and unintuitive, but I'm guessing that you can come up with something better. :-)"

**Comment by alderg** [comment]
A gridSteps configuration switch will be added in the next release, eg. https://app.diagrams.net#_CONFIG_UzV3UjUySi/KTAkuSS0oBrJVjR1NVM1dAA==

**Comment by KacimiBadr** [comment]
Thanks, when will that be?

**Comment by davidjgraph** [comment]
It's out in 14.3.2.

**Comment by KacimiBadr** [comment]
I can't seem to find the icon options, where should i click to change 4 squares to 5 ?
Thanks

**Comment by davidjgraph** [comment]
Are you on 14.3.2?

**Comment by mararad** [comment]
Hi,

Just click Extras > Configuration in the diagrams.net editor and you will
see the default
{
  "gridSteps": 4
}

Change the number there, click Apply and then reload a page.

Regards,

**Comment by Gentleman03** [comment]
@alderg @davidjgraph @mararad @KacimiBadr @TheaterStrahl 

> Just click Extras > Configuration in the diagrams.net editor and you will
> see the default
> {
>   "gridSteps": 4
> }


This doesn't work in desktop app. Even if I create a file using web app and then open it with desktop app.

**Comment by SteveHere** [comment]
> > Just click Extras > Configuration in the diagrams.net editor and you will
> > see the default
> > {
> > "gridSteps": 4
> > }
> 
> This doesn't work in desktop app. Even if I create a file using web app and then open it with desktop app.

Works on the web app for me.
