### ISSUE TITLE
Custom links to A0 page won't work in exported HTML

### ISSUE THREAD

**Issue by konsorg** [jgraph/drawio#1250]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
A custom link with a highlight action works nicely with A0-size diagrams inside the editor, but it doesn't work in HTML export. It renders an empty page, and the target cell is far away from the top-left area of the diagram.

**To Reproduce**
1. Go to https://drive.google.com/file/d/1jy8ZBjyUUta7V9oyTbISMM3voLv5jDP_/view?usp=sharing
2. Open 'Custom links and faulty HTML export.drawio.' This is BPMN from your app template with page canvas changed to A0, and parts of processes moved around the page to imitate a large diagram.
3. Click on the task 'Click this task', see that the editor opens Process 2 and highlights a task at the lower right end of the diagram. If you click the task 'Click this task' on Process 2, you will be redirected to process 1 the same way. Everything is cool.
4. Now open 'Custom links and faulty HTML export.html' and try to do the same things as in the editor.
5. See that it opens an empty page. 
6. Use controls at the upper border to see that they are rendered correctly if you scroll through the pages. It is the action that distorts the page.

**Expected behavior**
When I use example 2 from draw.io support page https://desk.draw.io/support/solutions/articles/16000080137 on BPMN process template over A0 canvas, it should work as specified - open the page and highlight an element.

**Screenshots**
https://share.icloud.com/photos/0HjZxMHlbLX9AU9l2rk706Nrg

**draw.io version (In the Help->About menu of the draw.io editor):**
13.8.1

**Desktop (please complete the following information):**
OS | Windows 10 OS Version 1909 (Build 18363.1139)
Google Chrome | 86.0.4240.75 (Official Build) (64-bit) (cohort: Stable)
Revision | c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}
JavaScript | V8 8.6.395.10

**Comment by mararad** [comment]
Hi,

my suggestion would be to test in Incognito mode because it is cache and extension free (I see you have a couple of browser extensions installed).
If it doesn't help. update diagrams.net version to the latest 13.8.2 (you could do a hard reload in order to get this version)

I tested at my place and I don't get a blank page. 
I use Win 10 Pro, diagrams.net version 13.8.2, Chrome Version 86.0.4240.111 (Official Build) (64-bit) and set page to A0 (File > Page setup)

Check the gif I attached.

Regards,

![html](https://user-images.githubusercontent.com/44292306/97170443-fd26bf00-178b-11eb-9811-b32054a685a8.gif)

**Comment by konsorg** [comment]
Hi mararad!

You did this with A0 on a diagram that actually fits into the default canvas (US letter something). Now if you extend the diagram down and to the right to fill the actual A0, it breaks down. I did update draw.io and chrome and tested this in incognito to no avail: https://share.icloud.com/photos/0Dqn5-xNZgHJx3K1GUt4M-KxA

See the other .drawio file made by simply moving your default elements around the canvas: https://drive.google.com/file/d/1YJoYEnitVnZpmguRFLaxbdk6iVkRiwv_/view?usp=sharing 

This is from steps 4 to reproduce the bug.

Best, 
Konstantin.
