### ISSUE TITLE
Converter for Mermaid to draw.io document

### ISSUE THREAD

**Issue by lazee** [jgraph/drawio#1251]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

I would like to be able to import a Mermaid diagram and then convert it into an actual draw.io document, where I can work
with the elements like any other document. Would that be possible?

**Comment by davidjgraph** [comment]
Sure, if you write it :).

**Comment by davidjgraph** [comment]
The is outside the scope of the project.

**Comment by davidjgraph** [comment]
This is done in 21.0.6

**Comment by lazee** [comment]
Fantastic!
