### ISSUE TITLE
Export to PowerPoint (.pptx) format

### ISSUE THREAD

**Issue by iWangJiaxiang** [jgraph/drawio#1259]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

Drawio is no doubt such a powerful solution for diagram drawing and I use it very often. However, when I need to do presentation with the diagrams from Drawio's xml file, I have to export them to `png` image first and drag it into my ppt. It's not that convenient because:

- Exported image might be not that clear due to resolution setting.
- Some slight changes (layout/size/...) would be hard/impossible.

**Describe the solution you'd like**

Add a feature that could export diagram to `.pptx` file!

**Additional context**

I have tried to export diagram to VSDX (VISIO) file first and copy shapes to ppt file. But that led to mess.

**Comment by davidjgraph** [comment]
Use https://appsource.microsoft.com/en-us/product/office/wa200000113

**Comment by zchen1997** [comment]
Does the draw.io can not export the .pptx files now?

**Comment by davidjgraph** [comment]
Export to the .pptx is not supported and will not be added in the future.
