### ISSUE TITLE
Impossible to expert to pdf

### ISSUE THREAD

**Issue by thorwens** [jgraph/drawio#1260]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When i make a diagram using draw.io, it is impossible to download it as a pdf. The window containing the different options (Crop, Grid, ...) appears but nothing happens when i click on "Export". 
The same behaviour happens with svg format, but it seems to work fine with png and jpeg.

**To Reproduce**
1. Create a new diagram 
2. Click on "File" -> "Export as" -> "pdf" 
3. Click on "Export"
4. Nothing happens

**Expected behavior**
a new window should have appeared asking me where i wanted the file to be downloaded on my PC and askin me the name of the file

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.8.6

**Desktop (please complete the following information):**
On google chrome (but the same appeared with Microsoft Edge)

**Comment by davidjgraph** [comment]
Fixed in 13.8.7. Thanks for report.
