### ISSUE TITLE
github auth too permissive

### ISSUE THREAD

**Issue by marwahaha** [jgraph/drawio#1261]
* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I feel uncomfortable that diagrams.net can edit all public and private repositories on GitHub.

**Describe the solution you'd like**
I would like to authorize GitHub for diagrams.net only to edit a specific repository.

**Describe alternatives you've considered**
For now, I will save to Google Drive, but it would be much easier to save to GitHub because I would like viewers to give feedback.

**Comment by davidjgraph** [comment]
Fully agree, but Github offers no more granular permissions for what we need.

**Comment by davidjgraph** [comment]
Also duplicate of https://github.com/jgraph/drawio/issues/1117 , please search the issues before posting.
