### ISSUE TITLE
Scale Text Font Size relative to object resize

### ISSUE THREAD

**Issue by myloginid** [jgraph/drawio#1262]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When a Object is resized the text font sizre needs to be manually increased/decreased

**Describe the solution you'd like**
Increase/Decrease Text Font Size relative to object resize

**Describe alternatives you've considered**
None. Have to do it manually each time

**Additional context**
Current - 
![image](https://user-images.githubusercontent.com/2422057/97669606-72adca80-1abf-11eb-9316-1efe1bb94697.png)

Expected
![image](https://user-images.githubusercontent.com/2422057/97669629-835e4080-1abf-11eb-8eab-d33eef58e813.png)

**Comment by mararad** [comment]
Hi,

another user already created this feature request here: https://github.com/jgraph/drawio/issues/984 
You can track it and comment if needed there. I will close this one so we have all under one roof.

Thanks,
