### ISSUE TITLE
Align Text to Container Boundaries

### ISSUE THREAD

**Issue by eightbit** [jgraph/drawio#1273]
* [X ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Text alignment does not obey the container boundaries.
To get left-aligned text to be relative to the container, the text alignment for the container must set to 'Left'. However, when that is set, centered text is centered to the extent of the body text, not the container. I've not seen this before and personally don't see the utility in it. I suggest that this be changed to align with the container.

![Draw io-textAlign](https://user-images.githubusercontent.com/5913748/97784884-b9f39400-1b6f-11eb-80af-01f9e1e23575.png)

Thanks.

**Comment by mararad** [comment]
Hi,
 I will close this thread since I replied you here: https://github.com/jgraph/drawio/issues/1274

Regards
