### ISSUE TITLE
Text Formatting Panel Not Updating

### ISSUE THREAD

**Issue by eightbit** [jgraph/drawio#1274]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

The text formatting panel does not update based on text selection (see bottom section of pic).

![Draw io-textAlign](https://user-images.githubusercontent.com/5913748/97785087-e78d0d00-1b70-11eb-9a3e-31f28c6bc61f.png)

**Comment by mararad** [comment]
Hi,

My suggestion would be to choose Text Overflow = Width for a cell in Format panel on the right > Property/Value as shown in the attachment and then align the title and text separately.

Does this solve your problem?

Regards,

![text overflow](https://user-images.githubusercontent.com/44292306/97868529-25746780-1d10-11eb-802e-9261d7eb9301.JPG)

**Comment by eightbit** [comment]
Yes, that is better. I thought I had tried that.
Note that when it is set to 'width,' the 'spacing' settings are no longer honored.
![Draw io-textAlign2](https://user-images.githubusercontent.com/5913748/98167981-8b4b2580-1eaf-11eb-8397-a3202049bbaf.png)
