### ISSUE TITLE
Google Drive connection is 401

### ISSUE THREAD

**Issue by Aescula** [jgraph/drawio#1275]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When trying to authorize to work with Google Drive, Google says you already have access, and re-confirming sends me to a 401 page.

**To Reproduce**
Attempt to open an old file from Google Drive

**Expected behavior**
I expected to see my old file, and be able to begin a new one.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.0.8

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome 86.0.4240.111

**Comment by davidjgraph** [comment]
Does it work in Chrome Incognito?

**Comment by Aescula** [comment]
It does work in Incognito. Strange.

**Comment by mararad** [comment]
Since it doesn't happen incognito it's either 1) your browser cache, 2) your browser cookies or 3) a browser extension that is causing the problem. The first 2 you can clear, the third one can be disabled.

**Comment by The3ngineer** [comment]
I am experiencing similar issues even with incognito browser windows/cleared cookies. Attempting to open an old file from Google Drive I get the authorization dialog. If I _do not_ select "Remember me" it works fine, if I _select_ "Remember me" I get a 500 error, then a 401.

The sequence of events is:

- popup window with Google account selection
- prompted for and submit Google credentials
- 500 response from request to ```https://app.diagrams.net/google``` with parameters state, code and scope

```
state: cId=blahblahblah.apps.googleusercontent.com&domain=app.diagrams.net&ver=2&token=blah
code: blahblah
scope: profile https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/drive.install https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/photos https://www.googleapis.com/auth/photos.upload
```

- pressing the reload button I get a 401.


MacOS 10.15.7
Google Drive File Stream with 2 factor authentication 43.0.8.0
Chrome (or Safari) incognito 86.0.4240.183

**Comment by PmmaGit** [comment]
I'm having a similar issue with Firefox 82.0.3, on the latest Windows 10 release.

Basically this is what happens:

1. I open a .drawio file directly from my Google Drive
2. It redirects me to app.diagrams.net
3. I'm asked to authorize Google Drive access. I leave the "Remember Me" box checked and press "Authorize"
4. Firefox blocks a pop-up, I manually authorize it to open the popup to the Google Account prompt
5. I go through the authorization process
6. At the end of it, it exhibits a mini Google Driver explorer-like tool, I select the same .drawio file again.
7. Afterwards the pop-up remains blank.

Two things to note:
- The same thing from points 2 to 7 happens, if I just open app.diagrams.net and select Google Drive as storage.
- I noticed the URL that appears on the final box, when it turns blank, mentions Office365 and not Google Drive, it could possibly be related to that.
