### ISSUE TITLE
Globally turn off the draw.io link from the Sidebar from all spaces

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1276]
"It is cluttering the UI."

https://community.atlassian.com/t5/Confluence-questions/Remove-draw-io-from-sidebar/qaq-p/1449226

![sidebar PNG](https://user-images.githubusercontent.com/44292306/98226033-c43dd580-1f55-11eb-9894-d8f6aa5092bf.png)

**Comment by davidjgraph** [comment]
Unfortunately, this isn't technically possible.

**Comment by tremours** [comment]
We use draw.io in some spaces, but not others. It's not used in our public facing space, so when the user clicks it, it always shows empty.
Also, we don't want a link to all draw.io images on the menu. They sit, in context, on each page, which suffices for us.

**Comment by tremours** [comment]
If this is Done, then how does one remove the link from the menu in a space?
