### ISSUE TITLE
add kinematic connections

### ISSUE THREAD

**Issue by karlTH** [jgraph/drawio#1277]
hello,
is it possible to add kinematic connections, i don't find it in the shapes

like on this picture :

![GitHub Logo](https://eduscol.education.fr/sti/sites/eduscol.education.fr.sti/files/u152/Exemple_de_liaisons_cinematiques_sur_Inkscape.png)

the words are in french

thanks a lot

**Comment by mararad** [comment]
Hi, unfortunately not. They are beyond the scope of drawio.

Regards,
