### ISSUE TITLE
[Feature Request] Save document title to browser history

### ISSUE THREAD

**Issue by levytal** [jgraph/drawio#128]
Currently, draw.io document webpages are all saved to the browser history with the same title: "Flowchart Maker & Online Diagram Software".
This makes it impossible to quickly access previously opened documents by typing some letters from the document title in the address bar in Chrome.
Google Docs documents, for example, do save the the title to the history, making it very convenient to quickly bring up a document by typing a few letters.
Could you please update your software so that it saves the document title to browser history?

**Comment by alderg** [comment]
We did some testing and this doesn't seem to be possible using the history API.
