### ISSUE TITLE
Colors of the Container and Component shapes of the C4 Model are swaped

### ISSUE THREAD

**Issue by akoscsiszar** [jgraph/drawio#1282]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
In the Shapes list the C4 Shapes collection can be optionally activated. This are shapes to modell SW architecture using the C4 approach - Context-Container-Component-Code. In the Context view the System shape is used. A system is composed of Containers, a Container is composed of Components. It is all hierarchical and different shades of blue are used to differentiate these. The blue shade of the container and the blue shade of the  component is swapped, the container has a lighter blue color then the component. 

**To Reproduce**
1. Go to 'More Shapes'
2. Click on 'C4'
3. Add a C4 system, container and a C4 Component to the drawing
4. Optionally ad a ConteinerDB
5. See that the Container and the ContainerDB color do not match and see that the Component has a darker blue shade then the Container. 

**Expected behavior**
The container shape should have a darker blue color then the component, like shown here: [https://c4model.com/img/abstractions.png](https://c4model.com/img/abstractions.png)

The two colors of these two shapes should be swapped.

**draw.io version (In the Help->About menu of the draw.io editor):**
diagrams.net 13.7.9

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Offline version used
 - Version diagrams.net 13.7.9

**Comment by bwlfhu** [comment]
the same opinion.
