### ISSUE TITLE
[Feature request] Access to GitHub organization's repositories

### ISSUE THREAD

**Issue by carlesaraguz** [jgraph/drawio#131]
I belong to some GitHub organizations and, for some projects where there's many people involved and teams are necessary, our repositories are owned by the organization, not our personal users. Being able to list and access these repos and to save my class diagrams there automatically would be a very nice feature.

**Comment by alderg** [comment]
This works for me. Have you tried scrolling to the end of the list? More repos are loaded when the end of the list is reached. If that doesn't work, have you tried clicking on "Enter Value" and entered the repo of the form org/repo/ref?

**Comment by carlesaraguz** [comment]
Oh... So my list is short and my screen is large (can't actually scroll). I tried the "Enter value" and typed `name-of-organization/repo-name/master` (or without the `master` part) and it didn't work. Most of my _repos_ are private, could this have something to do? Entering the repo name for public ones works.

**Comment by alderg** [comment]
We're unable to reproduce this. Could you create a private repo and give me access so I can check?

**Comment by carlesaraguz** [comment]
Done: https://github.com/nanosatlab/test4drawio

**Comment by alderg** [comment]
Thanks. The REST API does not seem to return this repo when using /user/repos  https://developer.github.com/v3/repos/#list-your-repositories with the defaults and a valid Authorization header. Strange!

**Comment by carlesaraguz** [comment]
Oh... Should I contact technical support on my side, then?

**Comment by alderg** [comment]
Yes

**Comment by carlesaraguz** [comment]
After contacting GitHub support they showed me that, since my user had requested draw.io's OAuth access before the organization was created, the organization did not have this access granted. Changing this solved the issue. My apologies for any trouble I might have caused...

https://help.github.com/articles/requesting-organization-approval-for-oauth-apps/

**Comment by alderg** [comment]
Thanks for the update!
