### ISSUE TITLE
Cisco Meraki Product icons

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1314]
https://community.meraki.com/t5/Off-the-Stack/Visio-Shapes/td-p/721

One of our users would love to see these Meraki shapes in draw.io. Can we do a work around to get them in ? Copy paste from lucidchart on these symbols did not work. Guess it is due to that they are not vectorised
Thanks
Peter

**Comment by ashrafteleb** [comment]
The shapes can be imported from the vss stencil file in the url

**Comment by davidjgraph** [comment]
The URL is no longer valid. If someone wants this, please open a new ticket.
