### ISSUE TITLE
Implement Alibaba icons

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1332]
https://www.alibabacloud.com/help/doc-detail/67830.htm

**Comment by HoiDam** [comment]
So is there any alicloud icon implemented? Thanks

**Comment by davidjgraph** [comment]
No, nobody has linked to a set.

**Comment by outan** [comment]
I love this and I am hoping to use Alibaba icons in draw.io as soon as possible.

**Comment by HoiDam** [comment]
Same

**Comment by mcsrainbow** [comment]
I collected a complete set of Alibaba Cloud vector icons and generated the draw.io icon library:
https://blog.heylinux.com/en/2024/01/alibaba-cloud-official-vector-icons-and-drawio-custom-libraries/

**Comment by HoiDam** [comment]
> > @davidjgraph why changing the status to declined?
> 
> The related in progress issue: #4086

ic thanks for the reply

**Comment by Roger0011** [comment]
> I collected a complete set of Alibaba Cloud vector icons and generated the draw.io icon library: https://blog.heylinux.com/en/2024/01/alibaba-cloud-official-vector-icons-and-draw.io-custom-libraries/

@mcsrainbow When I download the .xml file from the above link and try to open it as a stencil in Draw.io, I get a message "Error - Invalid File Data".  Are you perhaps able to advise the correct method to load your stencil into Draw.IO please?  Many thanks.

**Comment by mcsrainbow** [comment]
@Roger0011 Open draw.io - File - Open Library - Choose "alibaba-cloud-icons/2022-orange/drawio/en/Alibaba Cloud.xml"

**Comment by Roger0011** [comment]
> @Roger0011 Open draw.io - File - Open Library - Choose "alibaba-cloud-icons/2022-orange/drawio/en/Alibaba Cloud.xml"

Many thanks @mcsrainbow - that is the method I was using; I ended up re-downloading your file and it has now worked.

**Comment by mcsrainbow** [comment]
>> [@Roger0011](https://github.com/Roger0011) Open draw.io – File – Open Library – Select “alibaba-cloud-icons/2022-orange/drawio/en/Alibaba Cloud.xml”
>
> Many thanks [@mcsrainbow](https://github.com/mcsrainbow) – that’s exactly the method I was using. I ended up re-downloading your file, and now it’s working fine.

Did you click on the [url](https://github.com/mcsrainbow/alibaba-cloud-icons/blob/main/2022-orange/drawio/en/Alibaba%20Cloud.xml) and download the raw file? I tried again, and it still worked fine.

And this Alibaba icon set has already been added by the draw.io developer to the built-in category “+ More Shapes – Network – Alibaba Cloud”. So you can use it right away.
