### ISSUE TITLE
Freemind import

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1335]

**Comment by davidjgraph** [comment]
Outside the scope the of the project.

**Comment by mawid6** [comment]
Just came across this and there is a workaround whereby this can be accomplished, for the technically more savvy:

### How to import from freeplane (freemind fork) to draw.io 
Pre-requisite: Download and start freeplane, open the freemind map in freeplane.

Basically, add and use the CSV export script in freeplane, and then use the CSV text import tool in draw.io. 
So:

* Use one of the sample csv export scripts for freeplane. Here: http://www.freeplane.org/wiki/index.php/Scripts_collection#Output_A_Map_to_CSV
* Use the CSV import tool in draw.io. Its a bit technical.

Both steps are a bit technical. Using scripts in freeplane is actually quite easy once you get going.
The csv import in draw.io is a bit involved. :)

**Comment by lordmax** [comment]
Hi

> The csv import in draw.io is a bit involved. :)

Thanks for your support

I can't figure how to import csv in draw.io.
It only create a big object not a graph

Could you explain a little more?

Thanks

**Comment by lordmax** [comment]
Ok

Tried it.

The first passage is really easy. You can use a simple script and create a CSV file.

Import CSV into draw.io it's not so easy
More, it's just for table data NOT for mind map
It as to define every relation from columns but in a mind map you don't have columns just connections

It's not a practical solution

Thanks

And also mermaid it's not a solution 'cause draw.io create a single block not editable

And also svg it's not a solution 'cause draw.io import it as an image and not a editable object.

**Comment by chipbite** [comment]
Hi @lordmax ,
> The first passage is really easy. You can use a simple script and create a CSV file.

If you succeeded with this, you should be able to get the second part right... :) 

> Import CSV into draw.io it's not so easy
More, it's just for table data NOT for mind map
It as to define every relation from columns but in a mind map you don't have columns just connections

This sounds not quite right, I suspect you might be using a different solution - as the example in the drawio create an organizational chart, where the connections are indeed an important part. 

Check this page for info on how the relations are captured in the drawio import.

https://drawio-app.com/import-from-csv-to-drawio/

Looks like it should be doable, after all?

BR! /m

**Comment by lordmax** [comment]
Hi @chipbite 

Thanks

It's exactly as you say.

Connections are fundamental in CSV import for draw.io
But they have to be explicit in the setup pop-up.
You can't get a CSV and import it, you have to write down all relations and in both directions, if needed.
This is a huge waste of time.

And more, in a mind map you can't define this kind of relations, they're just connections. If I have to explicate every connection and maybe in a bidirectional way, the time I need to do so it's unacceptable.

CSV import can't be the right solution

**Comment by chipbite** [comment]
> You can't get a CSV and import it, you have to write down all relations and in both directions, if needed.

if the export does not have the relations (which it should) then I guess you would have to do it manually.

But of course, when you are getting the relations from freemind/freeplane, you need to process/transform the csv from freemind to make it into the csv that the csv import in diagrams.net expects. Might need a bit of code to do that. 

> And more, in a mind map you can't define this kind of relations, they're just connections. 

well, relations / connections - aren't they the same thing in this context? A -> B. Like graphs in graphviz or plantuml.

Anyway, sorry it did not work out for you. Take care!

**Comment by lordmax** [comment]
Hi

Not so easy
In the CSV you must have a column with the relation
AND
In the pop up for the CSV import, you have to explicitate every relations

#
# connect: {"from": "manager", "to": "name", "invert": true, "label": "manages", \
#          "style": "curved=1;endArrow=blockThin;endFill=1;fontSize=11;"}
# connect: {"from": "refs", "to": "id", "style": "curved=1;fontSize=11;"}
#

It's not sufficient they are in the CSV

So you can understand that also in case of a standard excel table you need a big amount of time to write down all relations
It's not only a matter of create CSV in the right manner.

In a mind map it's more complicated 'cause it's not an excel table with clear relations

Anyway, thanks for the support, really
