### ISSUE TITLE
Integrate in Unity3D (as Asset)?

### ISSUE THREAD

**Issue by davidlehub** [jgraph/drawio#1343]
Hi, it would be so awesome if Drawio can be integrated with Unity ( via plugin, asset?).

Btw, is there a step by step tutorial, for a total beginner of JavaScript, on how to clone the repository, modify it then make it works when publish. I Struggled to make my Github Drawio's Page to  reflect my changes - It keep showing the original unchanged draowio page. I was discourage and gave up.

Thanks in advance.
David

**Comment by davidjgraph** [comment]
Outside scope of project.
