### ISSUE TITLE
Grammarly bug 

### ISSUE THREAD

**Issue by Mennattu** [jgraph/drawio#1344]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The error appears when the user is using Grammarly 

**To Reproduce**
1. Click or hover on the Grammarly pop up that appears when you make a grammar mistake
2. The error pop up "ResizeObserver loop limit exceeded" appears
3. Dismiss the error, and it keeps reappearing when you interact with the Grammarly pop up

**Expected behavior**

**Screenshots**
<img width="895" alt="Screen Shot 2020-11-08 at 11 31 13 AM" src="https://user-images.githubusercontent.com/32979616/98464017-9a401980-21c8-11eb-9570-8392cbe3c250.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.9.1

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version Catalina

**Additional context**

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
