### ISSUE TITLE
Add 2 colors for double arrows

### ISSUE THREAD

**Issue by frederic-loui** [jgraph/drawio#1345]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
In network weathermap we are used to use 2 colors for RX/TX traffic representation.

**Describe the solution you'd like**
Is it possible to have the possibility to have 2 colors when defining the fill of a double arrow ? (or single)

**Describe alternatives you've considered**
Alternative is to use 2 unidirectional arrows and stitch them using an invisible shape.

**Additional context**
[Example of a straight double arrow (can be curved)](https://image.shutterstock.com/image-vector/double-arrowhead-horizontal-arrow-energy-260nw-96914057.jpg)

**Comment by mararad** [comment]
Hi,

you could experiment with color gradient as shown in the image below:
![gradient](https://user-images.githubusercontent.com/44292306/98540783-bd350100-228e-11eb-9304-7108ecdbb37a.JPG)

Regards,

**Comment by frederic-loui** [comment]
Thanks!
I found this possibility but I was looking at curved double arrows ...
Do you know if this is possible ?
In the network area it is common to have multiple links between 2 nodes so
curved arrow is perfect for that !

**Comment by frederic-loui** [comment]
As a side note I saw also your arrow with label which is perfect also. I was wondering if we can have this sort of double arrow and double color selection. This is an example:
<img width="273" alt="weathermap arrow example" src="https://user-images.githubusercontent.com/9639687/98652686-4c4c2280-233c-11eb-862d-ced0e7bb0fe5.png">

The idea in the end it to create a network map with draw.io and then save it as SVG or draw,io format. But put a color associated to a link load dynamically based on live data collection from the network. This would render the MAP alive. 

Back in 2004 I wrote a weathermap toolkit that gave this result:
![weathermap_france-600x622](https://user-images.githubusercontent.com/9639687/98653210-093e7f00-233d-11eb-8265-90547aba6a8b.png)

My idea is to improve this paradigm:
- By drawing diagram with draw.io
- And then couple this diagram by identifying all egde 
- Render them with a color proportional to the Network traffic load
- It would be great to have the double arrow above with 2 colors and a label (A great addition is to have a gradient)
- A great improvement is then to have the choice  of straight arrow or curved arrow. 

The current examples seems to be a bit outdated and lack of visual appealing:
https://www.renater.fr/weathermap/weathermap_metropole
https://www.renater.fr/weathermap/weathermap_idf
https://www.renater.fr/weathermap/weathermap_domtom

I'd be grateful to refresh them with diagram.io :)
Thanks !

**Comment by mararad** [comment]
Hi, we don't support 2 color curved arrows, but I created them (click Extras > Edit diagram) and copy/paste this code (you can ungroup all parts if needed):

<mxGraphModel dx="2062" dy="762" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="850" pageHeight="1100" math="0" shadow="0">
  <root>
    <mxCell id="0" />
    <mxCell id="1" parent="0" />
    <mxCell id="_xN--UQzl0-cQkWlwgzd-7" value="" style="group" parent="1" vertex="1" connectable="0">
      <mxGeometry x="425" y="480" width="180" height="20" as="geometry" />
    </mxCell>
    <mxCell id="_xN--UQzl0-cQkWlwgzd-4" value="10" style="rounded=0;whiteSpace=wrap;html=1;" parent="_xN--UQzl0-cQkWlwgzd-7" vertex="1">
      <mxGeometry x="60" width="40" height="20" as="geometry" />
    </mxCell>
    <mxCell id="_xN--UQzl0-cQkWlwgzd-5" value="" style="html=1;endArrow=none;elbow=vertical;startArrow=block;startFill=1;endFill=0;strokeColor=#006EAF;fillColor=#1ba1e2;curved=1;strokeWidth=2;" parent="_xN--UQzl0-cQkWlwgzd-7" target="_xN--UQzl0-cQkWlwgzd-4" edge="1">
      <mxGeometry width="100" relative="1" as="geometry">
        <mxPoint x="-40" y="40" as="sourcePoint" />
        <mxPoint x="130" y="60" as="targetPoint" />
        <Array as="points">
          <mxPoint y="10" />
        </Array>
      </mxGeometry>
    </mxCell>
    <mxCell id="_xN--UQzl0-cQkWlwgzd-6" value="" style="html=1;endArrow=none;elbow=vertical;startArrow=block;startFill=1;endFill=0;strokeColor=#B20000;fillColor=#e51400;curved=1;entryX=1;entryY=0.5;entryDx=0;entryDy=0;strokeWidth=2;" parent="_xN--UQzl0-cQkWlwgzd-7" edge="1">
      <mxGeometry width="100" relative="1" as="geometry">
        <mxPoint x="200" y="41" as="sourcePoint" />
        <mxPoint x="100" y="11" as="targetPoint" />
        <Array as="points">
          <mxPoint x="180" y="11" />
        </Array>
      </mxGeometry>
    </mxCell>
  </root>
</mxGraphModel>

![2color](https://user-images.githubusercontent.com/44292306/98662985-cbdfee80-2348-11eb-822a-1e76b67d2231.JPG)

**Comment by mararad** [comment]
<mxGraphModel dx="2062" dy="762" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="850" pageHeight="1100" math="0" shadow="0">
  <root>
    <mxCell id="0" />
    <mxCell id="1" parent="0" />
    <mxCell id="_xN--UQzl0-cQkWlwgzd-7" value="" style="group" parent="1" vertex="1" connectable="0">
      <mxGeometry x="425" y="480" width="180" height="20" as="geometry" />
    </mxCell>
    <mxCell id="_xN--UQzl0-cQkWlwgzd-4" value="10" style="rounded=0;whiteSpace=wrap;html=1;" parent="_xN--UQzl0-cQkWlwgzd-7" vertex="1">
      <mxGeometry x="60" width="40" height="20" as="geometry" />
    </mxCell>
    <mxCell id="_xN--UQzl0-cQkWlwgzd-5" value="" style="html=1;endArrow=none;elbow=vertical;startArrow=block;startFill=1;endFill=0;strokeColor=#006EAF;fillColor=#1ba1e2;curved=1;strokeWidth=2;" parent="_xN--UQzl0-cQkWlwgzd-7" target="_xN--UQzl0-cQkWlwgzd-4" edge="1">
      <mxGeometry width="100" relative="1" as="geometry">
        <mxPoint x="-40" y="40" as="sourcePoint" />
        <mxPoint x="130" y="60" as="targetPoint" />
        <Array as="points">
          <mxPoint y="10" />
        </Array>
      </mxGeometry>
    </mxCell>
    <mxCell id="_xN--UQzl0-cQkWlwgzd-6" value="" style="html=1;endArrow=none;elbow=vertical;startArrow=block;startFill=1;endFill=0;strokeColor=#B20000;fillColor=#e51400;curved=1;entryX=1;entryY=0.5;entryDx=0;entryDy=0;strokeWidth=2;" parent="_xN--UQzl0-cQkWlwgzd-7" edge="1">
      <mxGeometry width="100" relative="1" as="geometry">
        <mxPoint x="200" y="41" as="sourcePoint" />
        <mxPoint x="100" y="11" as="targetPoint" />
        <Array as="points">
          <mxPoint x="180" y="11" />
        </Array>
      </mxGeometry>
    </mxCell>
  </root>
</mxGraphModel>

**Comment by frederic-loui** [comment]
OK ! I'm not sure if you'll consider this feature request but this type of arrow is used a lot in network diagram. I also manage to draw them, but I had the feeling that adding this shape in the library would have been a killer addition. 

We can of course draw them but having the label automatically centered in the middle of the double arrow (straight of curved) is the key tedious action in creating this connection between 2 nodes. As I don't know how difficult it is to implement a shape that has this behavior, I suggest then as a feature request (as I saw you have already an arrow with a centered "letter" icon. 

If this FR makes sense to you and if you plan to add a shape like this It'll be for sure use ! Please let me know your thoughts otherwise you can close the issue. Thanks anyway for your swift/prompt answer !

**Comment by davidjgraph** [comment]
Outside the scope of the project.
