### ISSUE TITLE
Cannot view all layers when embedding a diagram with more than 20 layers in Confluence Cloud

### ISSUE THREAD

**Issue by eddiegroves** [jgraph/drawio#1347]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Unable to view all layers when embedding a diagram with more than 20 layers in Confluence Cloud

**To Reproduce**
1. Create a diagram with Confluence Cloud
2. Add more than 20 layers
3. Embed the diagram in a page

**Expected behavior**
I can scroll/view all layers

**Screenshots**
![image](https://user-images.githubusercontent.com/470736/98607800-fd06f180-233d-11eb-8e48-9b0431b6a76c.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.9.2

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 86

**Additional context**
Layers are awesome tool for reusing complex diagrams. Having tags available in the embedding tool would also be handy!

**Comment by eddiegroves** [comment]
Moving away from Confluence mostly now (drawio is still awesome though). Workflow is now edit diagram on desktop and copy images to where they are needed (email/teams/slack/confluence/source control/etc)

**Comment by ashrafteleb** [comment]
Fixed. Will be added to the next release

**Comment by davidjgraph** [comment]
16.0.0
