### ISSUE TITLE
Find/Replace

### ISSUE THREAD

**Issue by pensono** [jgraph/drawio#135]
Add replace to the Find functionality.

Features:
awk like regex (especially capturing groups)
Replace all/Replace First/Skip
Selects the text when found

**Comment by skleinma** [comment]
Can someone explain why this feature request was closed?  It would be very useful.
Thanks for reconsidering this.
Cc: @pensono @davidjgraph

**Comment by davidjgraph** [comment]
We can reopen, but you need someone to want to implement it.

**Comment by steveyang331** [comment]
up this feature.

**Comment by davidjgraph** [comment]
@steveyang331 convention in all issue trackers is the vote for original request (thumbs up in this case), not to pollute discussion with "me too", "+1", etc

**Comment by bjohas** [comment]
Just adding my vote to this - (search/)replace functionality would be very helpful, even if it was just for strings.
