### ISSUE TITLE
VSDX data and link import

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1351]
I created links to another page and to a shape (container) on a third page, as indicated below. I also removed all shape data fields and added a new one ("Comment"), which I modified for the two sub processes on the first page.

Loading the vsdx file to draw.io looks good, but does not contain shape data, nor the links.
![1](https://user-images.githubusercontent.com/44292306/98673296-6f380000-2357-11eb-9c7a-4f379dc666f5.png)
![2](https://user-images.githubusercontent.com/44292306/98673298-70692d00-2357-11eb-9876-850a90e86a19.png)
![3](https://user-images.githubusercontent.com/44292306/98673300-70692d00-2357-11eb-846b-8ce15c87253e.png)
![4](https://user-images.githubusercontent.com/44292306/98673302-7101c380-2357-11eb-8ea7-827d39b7e930.png)
![5](https://user-images.githubusercontent.com/44292306/98673303-7101c380-2357-11eb-9b77-9ef48877d8b5.png)

**Comment by ashrafteleb** [comment]
It will be added in the next release
