### ISSUE TITLE
Add option for showing the grid and background colour in the shared diagram as well

### ISSUE THREAD

**Issue by bergamin** [jgraph/drawio#1356]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the solution you'd like**
Add an option for the resulting shared diagram to maintain the background settings made in the editing view or not. It can be another checkbox in the group in the screenshot below

**Describe alternatives you've considered**
I searched for all settings related to background and sharing, but couldn't find anything

**Additional context**
Expectation:
![image](https://user-images.githubusercontent.com/14339291/98677080-49046700-233b-11eb-9cc1-ba9255215068.png)

Reality:
https://drive.google.com/file/d/1AM2Kp6FT31DfJyl-B8B5DLvmwg3X_7dr/view?usp=sharing

Sure, one of the reasons why I want to keep that background is my enormous laziness of not making transparencies in my shapes, but the main reason is that I want the shared diagram to actually look like a blueprint.

**Comment by bergamin** [comment]
Oh come on now... A bot is marking this as won't fix? Can't any real person at least say this isn't in their plans instead of just ignoring the issue?

**Comment by davidjgraph** [comment]
This isn't in my plans.

**Comment by bergamin** [comment]
Thanks, I'm happy now
