### ISSUE TITLE
Link placed shapes back to their library

### ISSUE THREAD

**Issue by MrTrick** [jgraph/drawio#1357]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I want to make diagrams with a consistent theme, eg using shapes from the same libraries when possible.
It is helpful that in the search results I can right-click and "Open Library".
However, once a shape is placed I cannot find any way to lookup or open the library it came from.

**Describe the solution you'd like**
Some path, perhaps a context menu item, to run "Open Library" starting from a placed shape.
Alternatively, perhaps a way to select / filter / highlight all libraries to those containing shapes used in the diagram?

**Describe alternatives you've considered**
A workaround for now is to remember to open each library before adding the shapes.

**Additional context**
This feature might be useful alongside other features to improve "two-way" visibility, eg generally making more info about a shape available once placed. (Like eg https://github.com/jgraph/drawio/issues/913 )

**Comment by MrTrick** [comment]
This is still a concern for me - is there any interest in this issue?

**Comment by davidjgraph** [comment]
Edit pulldow offers "open library" option from 24.2.7.
