### ISSUE TITLE
Placeholder for last modified date and version

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1362]

**Comment by joshualamorie** [comment]
Is this for the version of a specific page?  How hard would it to be able to add this to the `<mxfile>`?

**Comment by mararad** [comment]
Asked for online diagrams.net version also

**Comment by flybye97** [comment]
(Read)

**Comment by borisjgraph** [comment]
Instructions on how to use the placeholders are [here](https://www.diagrams.net/doc/faq/predefined-placeholders).
