### ISSUE TITLE
embed.diagrams dosnt work

### ISSUE THREAD

**Issue by efih** [jgraph/drawio#1367]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
the embed.diagrams.net not working
the page is loading but cannot do anything 

**To Reproduce**
1. open chrome v86.0.4240.193
2. open embed.diagrams.net
3. the page loading but cannot do anything (see the screenshot)

I notice this issue from the nextcloud and after that check the embed link 
**Screenshots**
![image](https://user-images.githubusercontent.com/33001397/98801078-f51c7f80-2419-11eb-8fa7-5fc1b61a5ccd.png)

**Comment by davidjgraph** [comment]
embed.diagrams.net shouldn't load stand-alone, it's the embed mode for embedding within another iFrame. The result is correct.

**Comment by efih** [comment]
I notice this issue with the nextcloud : ![image](https://user-images.githubusercontent.com/33001397/98822135-1c367980-2439-11eb-885f-f28c47bc4e48.png)

I need to open another issue ?

**Comment by davidjgraph** [comment]
I would log it on the nextcloud integration, https://github.com/pawelrojek/nextcloud-drawio/issues . With technical details of the problem there's nothing we can do.
