### ISSUE TITLE
Embed version issue

### ISSUE THREAD

**Issue by ggloveswp** [jgraph/drawio#1378]
Starting from today, I noticed that embedding using https://embed.diagrams.net/?embed=1&spin=1&ui=atlas&proto=json&saveAndExit=0&noSaveBtn=1&noExitBtn=1&modified=1 is not working anymore, while it was working fine in the past.

Any ideas?

**Comment by davidjgraph** [comment]
Can you provide full environment and reproduction steps?

**Comment by ggloveswp** [comment]
I am using the following JavaScript variable for my editor - which was working fine inside my app:
`var editor = 'https://embed.diagrams.net/?embed=1&spin=1&ui=atlas&proto=json&saveAndExit=0&noSaveBtn=1&noExitBtn=1&modified=1';`
This URL was working fine with direct access through my browser - but it stopped working today.

Steps to reproduce the issue: Visit https://embed.diagrams.net/?embed=1&spin=1&ui=atlas&proto=json&saveAndExit=0&noSaveBtn=1&noExitBtn=1&modified=1 - you will notice that loading is not being completed.

**Comment by davidjgraph** [comment]
It won't load, you cannot load this directly. Please read existing issues before posting and why suddenly are people asking the same question? https://github.com/jgraph/drawio/issues/1367

**Comment by ggloveswp** [comment]
It still cannot load properly inside an iframe - it worked until yesterday.

Here's a screenshot of the issue (stack at loading): http://prntscr.com/vhd9h3
And here's a complete PREVIEW of the XHR data: https://pastebin.com/3etbZDrp

**Comment by davidjgraph** [comment]
What's the environment, how do I reproduce this? Could a software engineer please file a report so I don't have to keep answering the same questions?

**Comment by ggloveswp** [comment]
Let me assign this to my team - they'll get back to you with a complete report so you can reproduce everything accordingly.

**Comment by ggloveswp** [comment]
**Requirements:**
- Plain HTML code environment

**Steps to reproduce the issue:**

1. Create a blank HTML file that includes the following code:
`<iframe frameborder="0" src="https://embed.diagrams.net/?embed=1&amp;spin=1&amp;ui=atlas&amp;proto=json&amp;saveAndExit=0&amp;noSaveBtn=1&amp;noExitBtn=1&amp;modified=1"></iframe>`
2. Open up the newly created HTML file and verify the non working state. UI is loaded, however, there is an infinite loading in the preloader, causing access to elements unavailable with no console errors

**Visualization of the issue:**
- Loading screen stuck: http://prntscr.com/vhdobg

**Expected behavior:**
- We expect a completely working interface, IE: http://prntscr.com/vhdo06


**Note:** The same way of usage was working fine until yesterday.

**Comment by davidjgraph** [comment]
That's still the correct behaviour. embed.diagrams.net puts the app in embed mode. It requires the message passing protocol as described in https://github.com/jgraph/drawio-integration.

At a high level, what task are you trying to achieve here?

**Comment by ggloveswp** [comment]
I'm trying to create and save diagrams inside our custom CRM - please check out this videocast: https://streamable.com/nqf6ok
It was working fine, i've been using it for days with no code altering/updates or any depedency changes.

**Comment by davidjgraph** [comment]
OK, so you do have the message passing in place. What version of the app do you see under help?

**Comment by ggloveswp** [comment]
It is 13.9.6 ( http://prntscr.com/vhfc65 )

**Comment by davidjgraph** [comment]
Could an engineer debug the message passing events to see where the process fails?

**Comment by ggloveswp** [comment]
Unfortunately no engineer is familiar with the process. I can follow a specific procedure if you give me a hint about it so I can Google around or provide remote access if needed.

What I realized - if its helpful - is that our previously saved diagrams can be edited fine: http://prntscr.com/vhgahp
Comparing console between the initial creation screen which calls the iframe and the edit view, is identical (no errors).

**Comment by alderg** [comment]
What's the value of image.getAttribute('src') on line 74 for new diagrams?

**Comment by ggloveswp** [comment]
Here it is: 
`                    if (msg.event == 'init')
                    {
                        if (draft != null)
                        {
                            iframe.contentWindow.postMessage(JSON.stringify({action: 'load',
                                autosave: 1, xml: draft.xml}), '*');
                            iframe.contentWindow.postMessage(JSON.stringify({action: 'status',
                                modified: true}), '*');

                        }
                        else
                        {
                            iframe.contentWindow.postMessage(JSON.stringify({action: 'load',
                                autosave: 1, xmlpng: image.getAttribute('src')}), '*');
                        }
                    }`

**Comment by alderg** [comment]
I mean the value of the expression image.getAttribute('src'), ie put console.log(image.getAttribute('src')) before the postMessage and send the console output.

**Comment by ggloveswp** [comment]
@alderg returns 'undefined'. An extra error is now visible.
Please check my recorded screen: https://gyazo.com/5c88cbb550382a1caf39b181b2ed0f9a

**Comment by davidjgraph** [comment]
OK, you will need one of your engineers to debug the issue properly. One of them obviously wrote the pastebin JS you sent us, ask that engineer to debug it.

**Comment by alderg** [comment]
Found the problem. We'll fix this in the next release.

**Comment by ggloveswp** [comment]
@alderg glad that you verified it wasnt a local issue or part of our code. Thank you for being cooperative.

@davidjgraph do you mind reopening this, as its now verified by your side?

**Comment by davidjgraph** [comment]
The issue was that null was being sent in the load message, that's not a valid message. It's not a bug, it's just that we added validation of the load message. Please have your engineers understand the code that they deploy to your production systems.

The release is out so the correct status is closed as the issue is changed and deployed.

**Comment by ggloveswp** [comment]
A waiting time period is supposed to occur when we talk about confirmed issues that will be fixed in the next release as @alderg pointed. 

In that case, 'Closed' would be the wrong status for this report and considering this as a false bug report, poiting me to previously created issues, for something that was working fine until yesterday. As we are using your embed function as a dependency of our work and I do assume that others do the same, we might need to internally reconsider this way for our daily use.

Hopefully @alderg invested time into the issue without ignoring it so, summing up: **Thanks for applying this super fast - I can confirm the working state again, without touching anything in our code.** 

Closed status is fine now.
