### ISSUE TITLE
Script to correct absolute link URLs after migration

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1386]
If links in diagrams point to the absolute URL of an old instance, after migration they will fail.

The simplest approach for now is to fix this at a proxy level.

Otherwise, some kind of script will have to run through each draw.io attachment and find and replace. The draw.io diagrams can be found (pseudo-code):

Perform a CQL to get the metadata for all attachments that have a matching attachment of the same name, but suffix .png

/rest/api/content/search?cql=' + encodeURIComponent('type=attachment and (title ~ "' + searchStr + '" or title ~ "' + searchStr + '.png")') + '&limit=200&expand=metadata

Then filter by mimetype from those results for:

application/vnd.jgraph.mxfile, application/drawio, application/diagramly

With the list of all attachments, you then need to open each one and locate the compress text sections between <page> elements in the XML (there can be multiple per diagram.

This compressed text is URI encoded, deflated and base64 encoded, in that order, https://jgraph.github.io/drawio-tools/tools/convert.html . So, base64 decode, inflate and URI decode to get the plain text out.

Do a text replace on the URL and put the changed pages back in (you don't have to compress them again).

**Comment by davidjgraph** [comment]
There’s an undocumented regex that can be applied to paths in the drawio viewer. https://www.diagrams.net/doc/faq/configure-diagram-editor

The key is “linkAdjustments”, for example:

`linkAdjustments=[{"re":"^/confluence/", "r":"/"}]`

This would strip out “/confluence” from the path.
