### ISSUE TITLE
VSDX export doesn't work if site is hosted in subfolder and in electron app

### ISSUE THREAD

**Issue by ayevee** [jgraph/drawio#139]
It seems that the problem is that vsdx.min.js is included using an absolute path:
```
mxscript('/js/vsdx.min.js', delayed);
```
If I change path to relative, VSDX work fine when running draw.io in subfolder:
```
mxscript('js/vsdx.min.js', delayed);
```

**Comment by alderg** [comment]
Thanks for the report, this will be fixed in the next release.
