### ISSUE TITLE
Allow link properties to be set per link

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1393]
Allow setting target per link, rather than current per diagram.

https://desk.draw.io/a/tickets/36783

**Comment by OneWorld123** [comment]
I need this, too. I use draw.io in conjunction with https://github.com/wikimedia/mediawiki-extensions-DrawioEditor/blob/master/README.md#mediawiki-drawio-editor-extension.

I need to set it to _parent. 

My use case: I want to jump from the SVG to a heading in the same wiki page. Therefore I need _parent. Auto/nothing will open it in the iframe.

**Comment by OneWorld123** [comment]
I just noticed, I indeed can edit it. After I added the link to the shape I have to right click > Edit Data.

![grafik](https://user-images.githubusercontent.com/467465/126985637-182254a8-7fb6-42f4-aaff-ce9e14092768.png)

Links within a shape can be edited using the "edit HTML" option (which I am no longer able to find :) )
