### ISSUE TITLE
Correct mixed direction cases in Hebrew translations

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1402]
Only Word manages to get these translations right. Probably will need the whole text as \uxxxx unicode escapes using LTR and RTL marks (\u200e , \u200f) to force the directions.

[Hebrew_translation_-_special_strings.docx](https://github.com/jgraph/drawio/files/5530604/Hebrew_translation_-_special_strings.docx)

**Comment by davidjgraph** [comment]
Unable to fix.
