### ISSUE TITLE
Problems setup own instance

### ISSUE THREAD

**Issue by ruben-herold** [jgraph/drawio#142]
hi,

i have tried to setup my own local drawio instance on my local server:

centos7
tomcat
nginx as reverseproxy and https

all runs fine except the onedrive, dropbox, github connection. I can't find any documentation how it works.
For example onedrive  gives me a 400 error on:

https://drawio.my.domain/onedrive3.html?oauth={%22clientId%22:%2245c10911-200f-4e27-a666-9e9fca147395%22,%22endpoint%22:1,%22scopes%22:[%22Files.Read.All%22],%22origin%22:%22https://drawio.my.domain%22,%22redirectUri%22:%22https://drawio.my.domain/onedrive3.html%22,%22state%22:%22https://drawio.my.domain_DdnLM%22}

The tomcat access log shows:

127.0.0.1 - - [11/Aug/2017:16:51:22 +0200] "GET null null" 400 -
the nginx:

XXXX:XXXX:X::XX - - [11/Aug/2017:16:51:22 +0200] "GET /onedrive3.html?oauth={%22clientId%22:%2245c10911-200f-4e27-a666-9e9fca147395%22,%22endpoint%22:1,%22scopes%22:[%22Files.Read.All%22],%22origin%22:%22https://drawio.my.domain%22,%22redirectUri%22:%22https://drawio.my.domain/onedrive3.html%22,%22state%22:%22https://drawio.my.domain_DdnLM%22} HTTP/1.1" 400 5 "https://drawio.my.domain/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.78 Safari/537.36"

If I replace the {} with %7B and %7D I get an 200 with some kind of js code.

On https://draw.io I don't see this problems.

**Comment by ruben-herold** [comment]
ok we have fixed the 400 er by changeing the nginx proxy_pass to:

proxy_pass              http://127.0.0.1:8080/$uri;

Seems that there is a problem with the uri de and encoding.

To make onedrive work we also must add our app key to:

js/diagramly/OneDriveClient.js
js/app.min.js

Is there no way to make it more confortable to add the app key's?

**Comment by alderg** [comment]
Try setting OneDriveClient.prototype.clientId after loading app.min.js (or OneDriveClient.js).

**Comment by ruben-herold** [comment]
@alderg thx I will try, but will it not much easier for deployment to have a script which read the needed keys (Onedrive,Github,Dropbox..) from one file and replace it in the js files or something like that. 

I also miss a good documentation how to install a local draw.io instance.

**Comment by alderg** [comment]
Maybe for deployment, but for development you'd have to run the build for every change. Documentation for installing a local draw.io is on our TODO.

**Comment by ruben-herold** [comment]
Thx for the info. We have installed it via ansible on centos. The playbooks  are not realy good but could be a start.

**Comment by davidjgraph** [comment]
The documentation (and lack of it) is my fault. If you can give me very specific questions, it's a lot easier to find 5 minutes to add it to docs, rather than the task of "improve them overall", which I look at and find a bug to fix ;)

**Comment by belonesox** [comment]
>We have installed it via ansible on centos. could be a start.
@ruben-herold, сan you share it? Please.

**Comment by mogsie** [comment]
Just a comment for others who end up here, I had the same problem and the resolution was not `$uri` but actually `$request_uri`.  *$uri* is a normalized version (where escaping has happened) and *$request_uri* is the original incoming version, with query string, in its raw unprocessed form.
