### ISSUE TITLE
Default style resets when diagram is re-edit

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1422]
1. Create a new diagram in a Confluence page
2. Add a new shape and change the color of the shape to blue
3. Right click on the shape and select Define as default style (Ctrl+Shift+D) or click it in Format panel
4. add a new shape: the newly created shape is blue, as expected
5. save and exit the diagram
6. re-edit the diagram
7. add a new shape to the editor: the style of the shape is not blue as expected

**Comment by LuisHenri** [comment]
This is actually something that would interesting to have. It is really annoying to re-open the Diagram to edit it and the arrows and shapes are not "by default" the ones that you "set as default"
