### ISSUE TITLE
Helpdesk webpages are missing alot of images

### ISSUE THREAD

**Issue by demux4555** [jgraph/drawio#1424]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Like title says, a lot of the pages in the documentation are missing their images.

Example webpage: [https://desk.draw.io/support/solutions/articles/16000067812-how-to-use-connectors-](https://desk.draw.io/support/solutions/articles/16000067812-how-to-use-connectors-)

The images are in fact pointing to this URL: "https://github.com/jgraph/drawio/wiki/Getting-Support"

**To Reproduce**
1. Go to https://desk.draw.io/support/solutions/articles/16000067812-how-to-use-connectors-
2. Observe as no images are loaded.

**Expected behavior**
The docs/help feature need images to be fully readable and understandable. 

**Screenshots**

![image](https://user-images.githubusercontent.com/19893658/99143038-b9242d00-265a-11eb-8260-d5f25407f2ca.png)

**Comment by mararad** [comment]
Hi, if you open these articles in other browser and Incognito mode, does it help? Also, check the URL in your address bar.
I use Chrome Version 86.0.4240.198 (Official Build) (64-bit) and Win10 and all is displayed fine.

![images](https://user-images.githubusercontent.com/44292306/99238214-c1ff3500-27f9-11eb-8ffb-3c256221eb78.JPG)

**Comment by demux4555** [comment]
I've tried Firefox, Edge, Internet Explorer, Chrome. They all have the same issue.

If I look at the source code of the webpages, I notice that the missing images all have relative paths to the files. 
Example : `/download/attachments/7962715/image2015-7-31%2015%3A45%3A10.png`

The working images all have a full path.
Example: `https://s3.amazonaws.com/cdn.freshdesk.com/data/helpdesk/attachments/production/16003339799/original/papersize.png`

If you are browsing the webpages using a different URL/domain (i.e. on an intranet solution) this could explain why you're not experiencing the same problem as external users.

**Comment by demux4555** [comment]
Hi there

Sorry, I didn't notice you've sent me a direct email instead of posting in
the github thread. (I've posted my reply there, tough.)

**Comment by davidjgraph** [comment]
We are migrating all the FAQ content, https://www.diagrams.net/doc/faq/, once that is complete it will show correctly.

Thanks for the report.
