### ISSUE TITLE
Replacement (swap) of one existing shape with another existing shape (shape, style, parameters and data)

### ISSUE THREAD

**Issue by derry43** [jgraph/drawio#1430]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

I like the feature where you can drag a shape from the shape menu to replace an existing shape in a diagram.

[https://desk.draw.io/support/solutions/articles/16000042532-replace-existing-shapes](https://desk.draw.io/support/solutions/articles/16000042532-replace-existing-shapes)

When working on large complex diagrams e.g. family trees, where new or updated information means replace existing parts of the diagram with updated details, it would be much quicker to copy and paste the new or updated shapes into the diagram and then swap them out for existing shapes already in the diagram. Preferably this could be done by dragging the new shape in to replace the existing shape. 

The ability to hold a combination of keys while dragging one existing shape over another and then to have the dragged shape (shape, style, parameters and data) replace the existing shape while maintaining the existing shapes connections would make updating a diagram in this way a quick an painless process.

**Comment by jdschwam** [comment]
Great App.

+1 for copying over the data field properties.  Maybe I am missing something, but I have looked.  After creating a shape with custom fields/properties, and then saving it to the Scratchpad. it would be nice to be able to replace existing shapes and have the custom properties copy to the newly replaced shape.   I will keep looking maybe it is there.  Tx

**Comment by derry43** [comment]
Still a really useful feature request. Would make modifying existing diagrams far more straightforward.
