### ISSUE TITLE
Properties in tooltip are not sorted

### ISSUE THREAD

**Issue by devr1** [jgraph/drawio#144]
Hi,

it seems that the properties displayed in the tooltip of a shape are not sorted.
The order corresponds to the order in which the new properties were added.
![image](https://user-images.githubusercontent.com/30261134/29313517-be76596a-81ba-11e7-8622-ae6a20baed73.png)

I think the order should be equal.

Thanks

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
