### ISSUE TITLE
Text search & Replace (all)

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1443]
When reusing a diagram would be nice to do a text search and replace. Case of a diagram for a site with multiple objects using a common naming standard. The need to rename all the object for a different diagram that was based off the previous one.

Ticket 12168

**Comment by azaz485** [comment]
Totally agree with @mararad !  SEARCH Text/  REPLACE Text functions would be great!

**Comment by CrazieIvan** [comment]
Please add this... I just had to manually change a ton of strings, one by one.  Torture.

**Comment by mawid6** [comment]
The problem/need is interesting and of course common. 
I am thinking of how we use links, and to use links more between diagrams and e g confluence pages. 
If we do so, we get the need to be able to update the links in the diagrams when we (inevitably) change things in the wiki.

Re confluence part: I can search and replace stuff on confluence pages, and conceivably in the attachments of the pages. I have some code (a node commandline utility) I have not yet published anywhere to do stuff like that, there is ofc also commercial commandline plugins/tools.  It is a chatty operation with alot of downloads, it will take time. Suitable for a tool executing on a client machine, not as a build step (ofc can be solved, but gets more complicated).

The part where I dont see a clear solution is the draw-io part. From an attached .drawio file, I need to:
* Extract the XML (from commandline essentially), 
* then do the search and replace in it, no problem. 
* Re-create the .drawio from the XML (from commandline) and
* Get drawio to do a new render of the diagram to a png export and update the page preview ( my assumption, have not checked this at all ;-) 

I know someone created a project for a headless render of drawio diagrams suitable for commandline and e  g a docker image, and a build step... and of course a tool like what I am thinking about here.

**Comment by mawid6** [comment]
(my case example is a just an example. Confluence typically handles redirects ok, so even if a document changes location, it often manages to get the request to the page anyway. Secondly, there are other solutions to the problem, but search and replace of diagrams on a wiki is a relevant need)

**Comment by borisjockov** [comment]
Text search & replace is already built into the draw.io editor so feature request is a bit unclear.
Is this meant to be used through the rest API?

**Comment by chipbite** [comment]
You're right @borisjockov  - OP is not clear - I read some into this based on my context, as I was roaming for solutions.
I assumed this was discussing a capability to do a search and replace from a central POV, somehow.

So my thoughts were on that problem, to somehow enable creation of an **_ability to update strings in diagrams programmatically_**.

**Comment by lkdmid** [comment]
It would also be extremely useful to have this feature in the "Edit Diagram..." box, so we can Find & Replace in the source. An example use-case would be replacing a hex color code which is part of a diagram's theme and therefore referenced many many times.

**Comment by deadlyBuzz** [comment]
> 

The Text Find and Replace doesnt work, and I cannot find a manual that finds it.
When I search and select "Find" - it finds the text in the page fine.  When I put something in to replace it, the "FIND" field goes RED and Won't find my search again, let alone replace.  Emptying the "Replace With" field allows me to find the text again.

**Comment by deadlyBuzz** [comment]
![image](https://user-images.githubusercontent.com/3323862/173917372-c3b73008-fde9-45ea-a673-659a96674814.png)

**Comment by palaciowagner** [comment]
This is what ended up working for me:

I have this diagram with math equations in it that I wanted to find/replace specific repeated part of the equation.
![image](https://user-images.githubusercontent.com/10745171/193431700-30670f67-7e45-4cce-bb8c-13e9fefe2813.png)

Deactivating the math composition, I'm able to see the code behind it
![image](https://user-images.githubusercontent.com/10745171/193431755-e2fa7a66-2eea-4bfb-a2fd-f07b73fb8b3a.png)

I believe draw.io diagrams all end up always generating HTML code behind it, so I went to `Extras > Edit Diagram` and I can see the HTML code with the equations text I wanted
![image](https://user-images.githubusercontent.com/10745171/193431769-9f7c5299-6a58-4da4-b44c-941599820af5.png)

So you can copy that code to any external text editor, search and replace what you want and then paste back into that box, which you have the option to either create a new diagram or replace the current one. The part I wanted to cut out was the `_{H}` from the equations:

![image](https://user-images.githubusercontent.com/10745171/193431795-cb3542ac-a37c-4fe9-b719-58be2f7e812b.png)

**Comment by kovben2004** [comment]
remember that draw.io diagrams can be downloaded (or if used in the app) as a .drawio file. that file is in .xml format, so open that in any text editor and do a find and replace.
