### ISSUE TITLE
Allow line snapping to corners of polygons

### ISSUE THREAD

**Issue by andrewda** [jgraph/drawio#146]
Currently, for squares, lines can only be snapped to 25%, 50%, or 75%. I need to attach lines to the corners of squares quite often, so it would be nice if they'd snap nicely there.

**Comment by alderg** [comment]
You can add/remove points anywhere on the shape and snap to those points. See https://desk.draw.io/support/solutions/articles/16000042498 and https://desk.draw.io/support/solutions/articles/16000054073

**Comment by andrewda** [comment]
Ah, couldn't find that, thanks!
