### ISSUE TITLE
Saving the file should not change the file version unless a change was made

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1461]
f there are no changes do not do a save operation. If there are, go through the save routine.
This would prevent getting a new file revision whenever "save and exit" is hit by the user.
A new revision would only occur with actual changes.

https://drawio.atlassian.net/jira/servicedesk/projects/DID/queues/custom/70/DID-588

**Comment by borisjgraph** [comment]
Current behaviour replicates the behaviour of the Confluence editor. Each "publish" creates a new version of the page regardless of changes made.
