### ISSUE TITLE
SVG opening errors

### ISSUE THREAD

**Issue by vagiwlak** [jgraph/drawio#1470]
Hello,

We switched from Bizagi Modeler to draw.io. Bizagi can export the BPM projects to SVG and Inkscape can open it. Unfortunately draw.io is displaying message that it cannot open the SVG because of error "This is not diagram file". Moreover, import of the same SVG file works but it is put into the draw.io map as image (non-editable). Could you please repair this functionality?

**Comment by vagiwlak** [comment]
Hello,

Any news on that?

**Comment by davidjgraph** [comment]
draw.io can import SVG as single images. It's not an SVG editor in the same way Inkscape is.
