### ISSUE TITLE
Add support for radial gradients

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1472]
https://groups.google.com/g/drawio/c/G3uCINxs7QA

**Comment by HaukeRa** [comment]
Would like to see this, too, maybe this can be re-opnened?

**Comment by alderg** [comment]
This will be added in the next release.

**Comment by yogeshg** [comment]
Is this feature available in the vscode extension?

**Comment by davidjgraph** [comment]
We're not the authors of the VSCode extension, we wouldn't know.

**Comment by gigberg** [comment]
> This will be added in the next release.
If the gradient direction could support custom angles, that would be great.
