### ISSUE TITLE
formatted draw.io macro and toc

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1475]
Create a draw.io diagram and format the line where the draw.io macro is located with heading 1. Add a 'table of content' macro to the page.

While in the edit mode of the page, everything looks fine, in view mode it seems like the definition of the diagram is shown in the table of content.

Screenshots of both the edit and view mode of the page are attached.

Most users don't get why the toc looks so strange.
<img width="300" alt="test_page_edit_mode" src="https://user-images.githubusercontent.com/44292306/99527231-c1eb6a80-299c-11eb-99a9-4c831207b51a.png">

<img width="300" alt="test_page view_mode" src="https://user-images.githubusercontent.com/44292306/99527223-bef07a00-299c-11eb-9427-5aa55c4fb979.png">

**Comment by ptrczegledi** [comment]
@mararad : I know that this is an old issue but I have encountered the same. If you check the source editor then you may find that your diagram is intended into a header tag (<h2></h2>) which causes the issue. I have replaced them with paragraph (<p></p>) tags and now the diagram is not part of the TOC.
