### ISSUE TITLE
Resizing rows in a ERD table freezes the app or does not work

### ISSUE THREAD

**Issue by jan-ekholm** [jgraph/drawio#1482]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

I have a diagram with some ERD tables. I noticed the overall diagram was getting too big and that the default row height of the tables was a bit too high. So I resized the rows of one table `colors` from 30 to 20pt. No issues. Then I tried the next table `color_types` and when I selected a few rows and resized from 30 to 20pt the app either totally froze (repaints, but doesn't react to any input) or resized the table frame instead of the selected rows. You can not select rows without the table also being selected, so I guess that's related. No idea how it worked on the first table though.

After the resizing all arrows are wonky too, their "green magic points" have disappeared and it's no longer possible to get them to connect to the correct rows. 

**To Reproduce**
1. Open attached diagram
2. Find table `color_types`
3. Try to resize one or more rows.
4. See the arrows coming to `id` of the `color_types` table. The magic connection points are gone from the entire table.

**Expected behavior**
The rows should resize to whatever I enter and the table itself should also resize to accommodate the new size(s) for the row(s). Arrows anchored to the row's green connectors should follow the resize operation and not randomly jump somewhere.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.9.9, desktop version

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: no browser, desktop version

[database.drawio.zip](https://github.com/jgraph/drawio/files/5563099/database.drawio.zip)

**Comment by davidjgraph** [comment]
Does this still happen in latest build?
