### ISSUE TITLE
Command-line export

### ISSUE THREAD

**Issue by wknapik** [jgraph/drawio#150]
It would be great if an export to html/svg/etc. was doable non-interactively and without a GUI.

I used draw.io to document some stuff and now I can put the xml file in version control, but I have no way to easily generate the html/svg versions in our CI.

This leaves only two options - both of them bad:
1. Put generated files in version control (and expect everyone to manually re-generate when changes are made to the xml file)
2. Set up a CI job that will be executed on a host with some sort of graphical environment, where the draw.io app would be launched and clicks would be simulated to produce the exports

The ideal scenario for me, would be to get a small cli tool, that can only do one thing - transform the xml into any of the export formats - and then set up a CI job that generates those files, so I can only keep the xml file in my repo.

**Comment by wknapik** [comment]
For those in need of the feature right away:

$ cat template.html
```
<!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=5,IE=9" ><![endif]-->
<!DOCTYPE html>
<html>
<head>
<title>architecture-aws</title>
<meta charset="utf-8"/>
</head>
<body><div class="mxgraph" style="max-width:100%;border:1px solid transparent;" data-mxgraph="{&quot;highlight&quot;:&quot;#0000ff&quot;,&quot;nav&quot;:true,&quot;resize&quot;:true,&quot;toolbar&quot;:&quot;zoom layers lightbox&quot;,&quot;edit&quot;:&quot;_blank&quot;,&quot;xml&quot;:&quot;&lt;mxfile userAgent=\&quot;Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36\&quot; version=\&quot;7.2.9\&quot; editor=\&quot;www.draw.io\&quot; type=\&quot;device\&quot;&gt;&lt;diagram id=\&quot;be9b821e-7279-9189-161a-15177a1780bc\&quot; name=\&quot;Page-1\&quot;&gt;__PAYLOAD__&lt;/diagram&gt;&lt;/mxfile&gt;&quot;}"></div>
<script type="text/javascript" src="https://www.draw.io/embed2.js?s=aws3;mscae/enterprise;gcp/networking;citrix&"></script>
</body>
</html>
```
$ cat drawioxml2html.sh
```
#!/usr/bin/env bash

# https://stackoverflow.com/questions/12873682/#answer-12873723
html_encode() { 
    sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&#39;/g'; 
}

generate() { 
    sed "s:__PAYLOAD__:$(sed 's,.*<diagram [^>]*>\(.*\)</diagram>.*,\1,g'|html_encode|sed -e 's/[\:&]/\\&/g'):" "$@";
}

generate "$1" <"$2"
```
$ ./drawioxml2html.sh template.html diagram.xml >diagram.html
$

Works for me.

**Comment by josefstr** [comment]
I found `drawio-batch`:
>A command line converter for draw.io documents. Converts diagrams to common image formats by wrapping the existing online conversion code into an offline tool.

https://github.com/languitar/drawio-batch

@languitar thanks! :+1:

**Comment by wknapik** [comment]
Thanks for the hint @josefstr!

**Comment by aiya000** [comment]
Now drawio-batch is to be archived :sob: 
Can I make png from xml on CLI?

**Comment by aiya000** [comment]
!?
I could get `file.png` via `$ draw.io -x -f png file.xml`.
(I found this options at #133, but I couldn't find any reference for this.)
Thanks :D
