### ISSUE TITLE
Tooltips in other formats than html

### ISSUE THREAD

**Issue by wknapik** [jgraph/drawio#151]
The tooltips (hover mouse cursor -> see properties) in html exports are very useful. So much so, that I don't want to publish in a format that doesn't support them. But html (esp. incl. <script>) is problematic, because it can't be embedded in, say, markdown (to display in README.md on GitHub/GitLab, etc.). I could use svg, or png, but then I get no tootips. Is there a way to solve that problem ? I don't know enough about svg and png to know the answer, but at least in case of html, completely static content could be generated, that would be embeddable anywhere.

**Comment by alderg** [comment]
We support HTML in tooltips, which isn't possible in SVG and PNG.

**Comment by wknapik** [comment]
There could still be an embed option with completely static html, which would resolve the problem of embedding in markdown, etc., while retaining tooltips.

Does that mean you have no interest in implementing that ?

**Comment by alderg** [comment]
Not sure what you mean by "embed option with completely static html"?

**Comment by wknapik** [comment]
At the moment, you can't embed a diagram exported as html in a lot of contexts (including GitHub/GitLab markdown), because it's not just static html, it contains <script>, which is not safe.

This could be worked around by generating plain, static html, without <script>, allowing users to embed their diagrams, with tooltips, basically anywhere.

Anyone who documents technical stuff using draw.io probably wants to publish the diagrams somewhere along with the code and they probably don't want to set up a dedicated service just for that, so embedding in another service (like GitHub/GitLab) is the likely route they'd (like to) take. Only now it's not possible.

**Comment by alderg** [comment]
Sorry, static HTML export isn't possible.

**Comment by wknapik** [comment]
I know it's impossible now. The issue was about making it possible ;]
But if you're saying this will not be implemented, then fine. Ack.

**Comment by alderg** [comment]
It's technically impossible, which means it cannot be solved or made possible.

**Comment by wknapik** [comment]
What's technically impossible ? Generating an html page that shows a diagram without using javascript ?

**Comment by alderg** [comment]
Cross-browser, yes.
