### ISSUE TITLE
Include a diagram from Confluence

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1521]
Include existing draw.io diagrams (created via Confluence-draw.io-Plugin) in the Jira tickets. The only way I found is simply putting hard hyperlinks in Jira, pointing to the Confluence pages containing draw.io charts. But would rather have the chart show up directly within the JIRA ticket:
https://desk.draw.io/a/tickets/13236

**Comment by davidjgraph** [comment]
Embedding Confluence stored diagrams in Jira cloud is supported.
