### ISSUE TITLE
Support Collapse/Expand a container via Custom Links

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1528]
Is that possible to use custom links in order to collapse/expand a particular container via its ID?
I saw toggle/show/hide but no collapse/expand/toggle container feature.

https://desk.draw.io/a/tickets/35943

**Comment by mararad** [comment]
Asked for online version also 
"I can expand or collapse a container by clicking on the '+' or '-' box on the top left corner of a container. I was wondering if I can make a Custom Link that toggles the expand/collapse function for ALL containers."

https://desk.draw.io/a/tickets/13000

**Comment by pabloarosado** [comment]
I think this would be a very useful feature.

**Comment by davidjgraph** [comment]
To vote for an issue thumbs up the original comment.
