### ISSUE TITLE
Save online

### ISSUE THREAD

**Issue by lodenrogue** [jgraph/drawio#153]
It would be wonderful to able to save diagrams online. Maybe reference them with a link or (even more work) a sign in.

**Comment by davidjgraph** [comment]
You're using the electron Desktop version?

**Comment by lodenrogue** [comment]
No, the website.

**Comment by davidjgraph** [comment]
What about saving to Google Drive?

**Comment by lodenrogue** [comment]
The purpose for the ticket was so I can share a link with someone and have them see the diagram online without having to pass xml files around. Maybe this can be a paid feature.

**Comment by alderg** [comment]
If you want a link (URL) you can create one using File, Publish or Export as, URL (this will be a copy of the diagram). If the diagram is stored on a cloud storage, the link points to the original diagram and requires a login if the diagram is not made public using the sharing options of the respective cloud provider.
