### ISSUE TITLE
Export to .dwg or .dxf format

### ISSUE THREAD

**Issue by hdavid16** [jgraph/drawio#1532]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
It's great to see process engineering stencils for process flow diagrams and piping & instrumentation diagrams typical in chemical engineering. It would be great to be able to export to .dwg (preferred) or .dxf.

**Describe the solution you'd like**
Add export to DWG option

**Describe alternatives you've considered**
Exporting to SVG and converting to DXF using Inkscape.

**Additional context**
None.

**Comment by davidjgraph** [comment]
Outside the scope of the project.

**Comment by hdavid16** [comment]
Ok

**Comment by tyllurius** [comment]
I second @hdavid16 comment..."Not having this option hinders the application of DrawIO in industry process engineering projects" exact the same for our company...

**Comment by HADJADJFelix** [comment]
I also agree with @hdavid16. Import from / export to DWG or DXF would be great

**Comment by gudh** [comment]
@hdavid16 me too

Any alternatives?

**Comment by tomholovis** [comment]
@davidjgraph has this concept been re-visited over the last 3 years? Is it still out of scope?

**Comment by davidjgraph** [comment]
It's still out of scope, yes.

**Comment by cosmii02** [comment]
That scope needs serious rework then if it's out of that scope of yours
