### ISSUE TITLE
Provide a simple class diagram with a relationship example of "Insert from text..."

### ISSUE THREAD

**Issue by nbourre** [jgraph/drawio#1536]
**Is your feature request related to a problem? Please describe.**
Lack of documentation

**Describe the solution you'd like**
Please just provide a simple example of a class diagram with a relationship between two classes. Eg : Inheritance?

**Describe alternatives you've considered**
Not much found

**Comment by mararad** [comment]
Hi,

Could you send an example, please?

Thanks,
