### ISSUE TITLE
Unable to Authorize with Google Drive on Safari/iPad

### ISSUE THREAD

**Issue by hussfelt** [jgraph/drawio#1537]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

Opening draw.io **or** Google Drive trying to open any files from draw.io (diagrams.net) you are unable to click the Authorize button. Nothing happens.

**To Reproduce**
1. Go to Google Drive on your iPad
2. Click on any of your diagrams
3. Try to click the ”Authorize” button

**Expected behavior**
I should be presented to pick an account to authorize with and open the diagram of choice.

**Screenshots**
<img width="1180" alt="diagrams net" src="https://user-images.githubusercontent.com/168864/100430844-9e5caa00-3097-11eb-96ba-54af0930ff7f.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.10.4

**Desktop (please complete the following information):**
 - OS: iOS (iPad)
 - Browser Safari
 - Version: 14.1 (18A8395)

**Comment by petercrocker** [comment]
Same problem on Safari Version 14.0.1 (16610.3.6.3) on MacOS Big Sur 11.1 Beta (20C5048l)

**Comment by yesobo** [comment]
Same on iPadOS 14.3

**Comment by alderg** [comment]
Safari: Are Pop-up Windows allowed for app.diagrams.net under Preferences, Websites, Pop-up Windows?

![macos](https://user-images.githubusercontent.com/921200/104149267-dd3f8880-53d5-11eb-9f5d-1a2626e687cf.png)

iPad: Is "Block Pop-ups" disabled in Settings under Safari, General?

![ipad](https://user-images.githubusercontent.com/921200/104149283-e597c380-53d5-11eb-9674-92e368a0f716.png)
