### ISSUE TITLE
Allow automatic export of project if saved

### ISSUE THREAD

**Issue by Stimmenhotel** [jgraph/drawio#1539]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I am using draw.io desktop version for drawing my uml charts in my thesis.
My folder sructure is:
Thesis/Images
|- drawio sources
\inkscape sources

I keep the source files (.drawio, .svg, etc) in subfolders of images, but the exported files in /Images.
It would be very convenient if the draw.io/diagrams.net app could automatically save the result (image) into a defined folder on save.
My latex document would just take the new image once compiled another time.

**Describe the solution you'd like**
Saving project dependent automatic export settings to the *.drawio project file and add a auto export feature to the app itself.
And on save automatically export the chart with the settings to a defined folder.

**Describe alternatives you've considered**
If no automatic export is possible, just the saving the export settings to a project would be very helpful to.
So if I save the project, i can click export and it uses the settings I have choosen for this project (eg. PDF + Crop) and save the result to the folder of my choice.

**Comment by davidjgraph** [comment]
Why not save as png+xml into the images folder and not bother with a source copy?

**Comment by Stimmenhotel** [comment]
I am trying to avoid png, since I am resizing the images within my latex document and png may blur out a little bit.
That is why I normally use ESP (#1540), since it seems to be natively supported by the graphics pack without needing to include others (eg. for svg).

Saving as xml sure would be possible, but it still two actions I need to perform for saving source-xml and png picture.
Or maybe I don't get the point?

I just think it could be very useful to save both, source and any export-format to a location where it gets used.

Also found a discussion on stackexchange about some the use of pdf/svg/... draw.io exports in latex: 
https://tex.stackexchange.com/questions/427622/importing-diagram-from-draw-io-into-latex

**Comment by davidjgraph** [comment]
If you use a .png or .svg suffix when saving the data XML is embedded within the PNG/SVG.

I don't see the need to add this functionality when the combined save option exists.

**Comment by Stimmenhotel** [comment]
Oh I see ... Never saw this option on creating a project.
Used .drawio since my first project.

I will try this toworrow with both formats. (Stackexchange mentioned font problems using svg and I know the problems with png and printing)
But yes, this is a much better solution. I think this can be closed then.

**Comment by Stimmenhotel** [comment]
Just tested embedded svg and png.

svg makes problems ...  Because the fonts will be provided by latex
![grafik](https://user-images.githubusercontent.com/15821524/100760865-82883980-33f2-11eb-9298-0930f9636ae1.png)

Same size as PNG (hope you can see the blurriness already)
![grafik](https://user-images.githubusercontent.com/15821524/100761064-be230380-33f2-11eb-922c-d1f9f98e3d24.png)

**Comment by davidjgraph** [comment]
ok, that would be a new issue please :)

**Comment by Stimmenhotel** [comment]
Both, the SVG and PNG problems are latex or svg related. (As far as i know)

As mentioned by Tiuri on https://tex.stackexchange.com/questions/427622/importing-diagram-from-draw-io-into-latex svg does not contain the font inflammations and/or latex/inkscape is just replacing them.

And the blurry png is because most of the time the image will be resized to fit into the theme/template.
I am using 70% of the line width. Bigger graphics will be shrunk, smaller will be enlarged.
Shrinking results in blurry pictures, while enlarging mostly works fine.
But that is why I switched to EPS for Matlab and PDF for Drawio.

The new issue would be the mentioned issue 1540 I believe.
