### ISSUE TITLE
Adding EPS to the possible export formats

### ISSUE THREAD

**Issue by Stimmenhotel** [jgraph/drawio#1540]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the solution you'd like**
Using .eps aside .pdf or .svg would be nice.

Edit: If possible with attached xml data for drawio.

**Comment by jackalcooper** [comment]
+1

**Comment by Stimmenhotel** [comment]
Changed title and request, since I wrote the wrong file format (eps = Encapsulated PostScript)

See https://github.com/jgraph/drawio/issues/1539#issuecomment-736628209 for information about why eps could be come in handy.

That be said, I don't know much about this file format, only that matlab, plantuml, umlet all are capable to export/save this format and I never had a problem using it with latex.

**Comment by YalandHong** [comment]
Vote up. It'll be nice to have this feature.

**Comment by prakashvs613** [comment]
Vote up. .svg or .pdf don't cut it many times.

**Comment by davidjgraph** [comment]
For the effort required to implement this, the complexity of the task doesn't justify the feature.

**Comment by x66ccff** [comment]
Yes please! Vote up.

**Comment by casafurix** [comment]
Yes please! Vote up.
