### ISSUE TITLE
corrupted graph

### ISSUE THREAD

**Issue by laurentopia** [jgraph/drawio#1543]
![image](https://user-images.githubusercontent.com/26075468/100701161-e90a4a80-3353-11eb-865f-5c087b1e083d.png)
this is the graph
![image](https://user-images.githubusercontent.com/26075468/100701283-2c64b900-3354-11eb-8b43-54da92367357.png)
it happened after i exidited a bunch of text to fit in the shapes

**Comment by laurentopia** [comment]
easy fix: copy paste in a new diagram

**Comment by alderg** [comment]
Is this using the online app with native files? What version do you see in Help, About?

**Comment by laurentopia** [comment]
13.10.5
it was saving as to PC that triggered that, 100% repro on latest (buggy af) chrome, using the online app on a new project so yes native file.
