### ISSUE TITLE
Archimate import support

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1545]
https://desk.draw.io/a/tickets/10138

https://www.opengroup.org/open-group-archimate-model-exchange-file-format

**Comment by davidjgraph** [comment]
Outside the scope of the project.

**Comment by Hubbitus** [comment]
@davidjgraph, why outside of scope? It looks like draw.io even support Archimate notation in figures. It will be very cool to see import such diagrams from external tools.
