### ISSUE TITLE
Add a watermark to the drawing output

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1551]
Example: when export to PDF or Print the watermark is shown. Like "Intelectual property of John Doe"

**Comment by MTVS2** [comment]
I was just looking for this feature. It would be useful to alert my distribution list that the document is a work in progress ("WIP" or "DRAFT" watermark) and not to draw (!) premature conclusions.

**Comment by nssecrier** [comment]
Any change of hart on this request? It would be a great feature for your product. Thank you.

**Comment by davidjgraph** [comment]
This can be implemented with a locked layer and/or background page. I don't see any reason to have this as an addition UI feature.

**Comment by midouwan** [comment]
@davidjgraph 
Software is designed to make tasks easier for users. Watermarks are not just limited to logos or images; they are often full-screen and in italic style. A one-click watermark feature would be highly desirable to free designers from repetitive work. For example, as a developer, I don’t typically create watermarks.
