### ISSUE TITLE
How to fill in the url in the startup parameters to open the specified content?

### ISSUE THREAD

**Issue by pengsongkun741** [jgraph/drawio#1557]
I try to start a local service and then access it through Google Chrome.Then specify the path of a local drawio file to index.html.
Like this: https://127.0.0.1:5500/src/main/webapp/index.html?url="file://C:/test.drawio".
My expectation is to access the URL to directly open the test.drwaio file.But the error message I get shows
`Error loading file.File not found`.
Is the format of the file path that I specified is wrong or I need other setting parameters?
Looking forward to your answer!

**Comment by davidjgraph** [comment]
Your browser cannot access your filesystem. This is basic browser security.

**Comment by pengsongkun741** [comment]
I added the following parameters so that Google Chrome can access local files and bypass the security policy.
`--allow-file-access-from-files --disable-web-security`
I am not sure if this way is correct.
We are integrating the tool into the editor’s Google Chrome suite, which will open when the user opens the .drawio file, but it seems that it cannot be achieved by passing the Url parameter
