### ISSUE TITLE
Add All BPMN Elements

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1558]
"I still did not found some BPMN 2.0.2 element such as on Artifact, there are missing "Group" element and text annotation. I found another missing Data Object Collection too"

"Have a more complete set of UML elements. 'Pins' are not there, neither are send and receive events (http://www.uml-diagrams.org/activity-diagrams-reference.html)."

**Comment by egrimate** [comment]
A new version of BPMN will be in the next release.
