### ISSUE TITLE
Export layers to PDF

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1561]
I've worked with autocad in the past and I remember exporting a drawing to PDF and still been able to enable and disable layers in it. This is very helpful to help visualize cluttered diagrams.

**Comment by MC-24** [comment]
I agree.
Please also consider an option to export layers to PDF (as separate files for each layer). I've been using this feature in OmniGraffle...

<img width="845" alt="Screenshot 2021-01-12 at 20 29 01" src="https://user-images.githubusercontent.com/33802131/104362987-d3706f00-5514-11eb-9d21-710b4d73a671.png">

**Comment by acsr** [comment]
It is definitely an important feature to preserve layers for roundtripping workflows. On the other hand, during import of an SVG exported eg. from Adobe Illustrator Draw.io will not keep existing layers as well. This should be possible to fix. If you need example files for testing, let me know.

**Comment by ShonaMercie** [comment]
I would really appreciate it if this was developed, as I'm really stuck how to do this :)

**Comment by JanB1** [comment]
See also Discussion jgraph/drawio#2458. I support this feature. A user currently would have to resort to Visio or some other software to get this feature.

**Comment by pierrebarroca** [comment]
It would be very nice to have this feature!

**Comment by schorsch0206** [comment]
It'd be really great if this feature could be implemented! 
Isn't there any voting functionality to show interest in feature requests raised by someone else alreay?

**Comment by terefang** [comment]
+1

**Comment by acsr** [comment]
I would like to add another aspect to the PDF Layer export feature. If you take into account, that there is a native approach to export the layered PDF in one rush, by writing the necessary structures into the PDF, you can take another approach (with some drawbacks). 

## Scripted Export Approach
Scripted export as seperate layers and merging multiple PDF into one using one PDF per layer.

1. Script draw.io to iterate through a list of all currently visible layers (omit invisible layers)
2. Export every visible layer as a single PDF with a basename and an LayerOrderID and the Layername as suffix with delimiter. Save the files in the tmp location of the OS.
3. Combine the exported PDFs into one Layered PDF using the given order by ID and the suffix als Layername using OpenSource commandline tools (my research on this has to be added later, due not reachable now from my place of writing).

### The Watermark Trick
There is one trick you can use to add layers in PDF by using the watermark / background feature first.
Watermarks are actually a simple layer at the top with adjustable transformation and tranparency with a special flag.

Watermarks can be transformed to a simple PDF layer by removing the flag.

- You add  layer by layer by repeating this process.
- You can add even the invisible layers when preserving the visibility flag in a suffix and set the visibility of the layer in the combined PDF.

This approach is similar to Python Scripts often used in Inkscape etc. to add features not possible with the default functionality but not worth a plugin or changing the general functionality.

### Remark on export preserving object structures in SVG and PDF

It is not helpful that the layers are not included even in the SVG at least as groups. This would offer another approach for scripted conversion not relying on Draw.io itselv.

Inkscape can still open the SVG only without any preservation of layer structures. The Draw.io layer names are not available in the SVG XML tree or even reflected as nested structure.

**Comment by terefang** [comment]
i dont know what is so complicated to mark resources for pdf layers.

it is as simple as wrapping the regular output in the following: 

```
/OC /L101 BDC q <content-stream> Q EDC
```
and creating a layer resource like that:
```
101 0 obj
/Type /OCG /Name (L101)
endobj
```
and adding the resource to the page "Properties" resources.
```
<<  /Type /Page  /Resources <<  /Properties <<  /L101 101 0 R>>  >>
```
--
T

**Comment by davidjgraph** [comment]
> i dont know what is so complicated to mark resources for pdf layers.

Then submit a PR if it's that easy.

**Comment by terefang** [comment]
LOL

> draw.io is also closed to contributions. We follow a development process compliant with our SOC 2 Type II process. We do not have a mechanism where we can accept contributions from non-staff members.

not allow by your own policies !

**Comment by davidjgraph** [comment]
I will make an exception for this case. Please submit the PR.

**Comment by JanB1** [comment]
@terefang Yes please. You would be my/our hero!

**Comment by terefang** [comment]
need to first ask my company if this is allowed by contract.

**Comment by terefang** [comment]
nonetheless while awaiting confirmation, i searched the codebase to to look how you generate pdf.

from the package.json files it looks like you use pdf-lib from npmjs.

i also found the PDFDocument initializer, but then i am lost.

i only found the pdfToPDF method but this is not part of the pdf-lib api.

so can you point me in the right direction (and file) where pdf-export actually starts ?

my javascript is a little bit rusty, since i wrote the last js i remember in 2010.

**Comment by alderg** [comment]
We convert HTML to PDF [on line 714](https://github.com/jgraph/draw-image-export2/blob/dev/export.js#L714)

**Comment by terefang** [comment]
> We convert HTML to PDF [on line 714](https://github.com/jgraph/draw-image-export2/blob/dev/export.js#L714)

**_that would mean it is "technically impossible" to implement layers because you are rendering thru the browser implementation._**

**Comment by acsr** [comment]
@terefang 
> that would mean it is "technically impossible" to implement layers because you are rendering thru the browser implementation and not some interfacing pdf library.
> unless you change the rendering, of course !
Yes, unfortunately there is no documentationat all mentioning layers in the used library:
- PDF-LIB · Create and modify PDF documents in any JavaScript environment.
  url:: https://Hopding.github.io/
  abstract: Create and modify PDF documents in any JavaScript environment.
  
  If you are searching for other soultions (to render), I want to mention the term Optional Content Group (OCG)used in a layer features in PDF documents to organize content.
  
For me it is unfortunately beyond my (current) scope to support this on the javascript side.

Thanks for picking this up.

**Comment by gfrodo** [comment]
For everyone else looking for this feature and ending up on this stale feature request, I created a small python script as a workaround, which exports each layer using the CLI of the drawio desktop app and compiles them into a single pdf with layers/OCGs: https://github.com/gfrodo/drawio2pdf
