### ISSUE TITLE
Isometric (3D) grid option

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1562]
Add an option to change the grid type to isometric (3D). This is the proper grid for creating 3d diagrams (like the AWS 3D shape set) and will allow for creating proper diagrams and connections between 3D shapes. An example of this from another product is http://cloudcraft.co (free trial).

A member edmoura wrote "I have been able make the grid below by leveraging the functionality in PR #340:
https://user-images.githubusercontent.com/16357187/60742904-76831880-9f6f-11e9-8296-52be20a0836e.png

**Comment by woyczek** [comment]
We really miss feature, as draw.io is the most interesting software to do isometric diagrams, especially with diagram as code.

**Comment by davidjgraph** [comment]
If you still want a feature, indicate support for the feature by "thumbs up" on the original post.

**Comment by benjisasin** [comment]
Hi, timeline says both completed and declined. Can you confirm whether this feature is available? It would be really useful thanks.

**Comment by davidjgraph** [comment]
The labels on the right are what matter, it says declined. We're not going to implement this, any requests to reopen will be deleted.
