### ISSUE TITLE
Curved text

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1563]
Write curved text, like on the example bellow:

https://gyazo.com/2d52e350d7c674d425dba57820bce640

**Comment by TobyBC** [comment]
Likewise, supporting this enhancement request. I want to use the text on a business lifecycle chart which is based on a circular object.

**Comment by davidjgraph** [comment]
Vote for issues by selecting the "thumb up" option on the original request.

**Comment by TobyBC** [comment]
> Vote for issues by selecting the "thumb up" option on the original request.

Thanks! Sorry, I'm new to github and didn't know how to vote. Done.

**Comment by davidjgraph** [comment]
Closing for lack of interest from core team.

**Comment by davidjgraph** [comment]
Duplicates #2651
