### ISSUE TITLE
Dockable layer window

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1568]
Make the layer window dockable to the format panel.

Henrik said "Having a lot of layers (eg. >30) you cannot even administer them without a big screen. Having the layer window dockable would trigger a scroll panel making all layers in the list accessible even on a smaller screen."

Mate said - "While you can drag the box on top of the "Format Panel" panel, it would be nice to simply snap the Layer box at say the bottom of the "Format Panel". Similar to the same concept in Photoshop. The Edit Data and Outline dialog windows would go along with this quite well."

**Comment by davidjgraph** [comment]
Duplicate of #687
