### ISSUE TITLE
Data Loss in Sandstorm

### ISSUE THREAD

**Issue by zeigerpuppy** [jgraph/drawio#157]
I opened a draw.io sandstorm grain that previous had quite a complicated diagram.
The diagram is showing as blank.  It previously had two layers and one page and looks to have been reset to a blank diagram.

Is there any way to recover the diagram?

**Comment by ocdtrekkie** [comment]
What version is your draw.io installed on Sandstorm? Do you have a backup of the grain? (Is it sensitive, or can you share it?)

Also, worth asking: Was there more than one user attempting to edit this diagram at one time when it was created? draw.io on Sandstorm is not collaborative.

**Comment by zeigerpuppy** [comment]
@ocdtrekkie, the version is the standard sandstorm (v6.5.4).  
Unfortunately I can't send a copy of the grain as it is sensitive data (a network map).  
Thankfully, it was pretty easy to recover the data as all our virtual machines are backed by ZFS ZVOLS (so I could rollback and get the grain from a day ago).

There would not have been any more than one user editing the grain but the grain may have been opened on more than one computer by the same user.  It'd possible this may have contributed but I'm not sure if that was the cause.  Perhaps there needs to be a more explicit locking mechanism to protect against data loss in this case?

Interestingly, the size of the grain was still about right for the data to be there (981kB) but nothing was showing up at all.  It's probably a data corruption issue I guess.

**Comment by ocdtrekkie** [comment]
Definitely curious if you can find out more. Maybe compare the contents of your backup with the corrupted one?

If effort was put in to fix multi-user quirks with draw.io on Sandstorm, my hope would be that it would be to implement proper collaborative editing like draw.io supports on Google Drive, for instance. But it's unlikely that draw.io will invest significant resources into the Sandstorm version unless it becomes a much more popular/in demand platform than it is today.
