### ISSUE TITLE
Import .odg files

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1577]
Will there be a future support to import .odg files which was commonly used and created using Libre Office Draw?

**Comment by asjones987** [comment]
I would like to add that importing and exporting .odg files from the Document Foundation / Libre Office Draw.
.... not just importing.

**Comment by davidjgraph** [comment]
We're not going to implement this. There's a limit on how many formats we can actively support. .odg is a drawing format, rather than a diagramming format, draw.io is not a drawing app.
