### ISSUE TITLE
Support Amazon S3

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1588]
Does draw.io support reading and writing files from an Amazon S3 compatible target?

https://desk.draw.io/a/tickets/10076

**Comment by davidjgraph** [comment]
Not clear what the data flow is. Closing unless an exact description is provided.

**Comment by Deiiv** [comment]
I believe this would be for storing draw.io diagrams in s3 (instead of google drive/github/etc.), that way authorization to the diagram (for embed purposes) can be done through AWS natively if you're hosting a website on it
