### ISSUE TITLE
Feature Request: Configuring parameters for png export in embed mode

### ISSUE THREAD

**Issue by hediet** [jgraph/drawio#1590]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
[Some users of the Draw.io VS Code extension would love to set parameters when exporting or saving the diagram as png image](https://github.com/hediet/vscode-drawio/issues/143). [Most importantly, this includes the zoom parameter](https://github.com/jgraph/drawio/issues/1155).

**Describe the solution you'd like**
If embedded mode consumers could specify the following parameters in the export action, I could implement that feature in the Draw.io extension:
![95143512-90189e80-0776-11eb-8457-a3d6e246a354](https://user-images.githubusercontent.com/2931520/101614363-25514100-3a0d-11eb-92bb-dcbfc832eeef.jpg)

This could look like this:
```js
{
    action: "export",
    format: "xmlpng",
    zoom: 2, // by default 1
    dark: true, // by default false
    grid: false, // by default false
    borderWidth: 0, // by default 0
}
```

**Comment by alderg** [comment]
We'll add the following optional parameters in the next release: width (px) defines the width of the image to be exported, border (px) defines the border, shadow (boolean) specifies if a shadow filter should be applied to the export, grid (boolean) specifies if a grid should be added, keepTheme (boolean) specifies if the theme should be kept (eg. for dark themes), transparent (boolean) specifies if a transparent background should be used and background (string) specifies the background color.

**Comment by hediet** [comment]
Thanks! How can I set a zoom level if I don't know the dimensions? I think having both a fixed width export and a fixed dpi export would be useful.

**Comment by alderg** [comment]
Not sure if I understand: We'll have a width (in pixels) and a scale (zoom), do you need something else?

**Comment by hediet** [comment]
So you have a scale/zoom parameter? Then I'm happy ;) You didn't mention it in you listing.

**Comment by alderg** [comment]
It was already there. But yes. We're trying to document all the options here: https://www.diagrams.net/doc/faq/embed-mode
