### ISSUE TITLE
Feature Request: Configuring parameters for svg export in embed mode

### ISSUE THREAD

**Issue by hediet** [jgraph/drawio#1591]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
[Some users of the Draw.io VS Code extension would love to be able to set a border when exporting to SVG](https://github.com/hediet/vscode-drawio/issues/179).
You can set a border when exporting a diagram as SVG on the draw.io website.

**Describe the solution you'd like**
Please support properties in the `export` action (in context of the embedded mode) to configure those parameters of the SVG export:
![image](https://user-images.githubusercontent.com/2931520/101616527-c04b1a80-3a0f-11eb-928d-36e2f58309fd.png)

With those properties, I can implement that feature for the VS Code extension.

**Additional context**

[This](https://github.com/jgraph/drawio/issues/1590) is the issue for being able to configure parameters when exporting to png.

**Comment by alderg** [comment]
In the next release, the additional optional parameters forsvg and xmlsvg are added: scale (float) to specify the zoom (default is 1), layerIds to define the array of visible layer IDs, border (px) defines the border, shadow (boolean) specifies if a shadow filter should be applied to the export, keepTheme (boolean) specifies if the theme should be kept (eg. for dark themes) and background (string) specifies the background color.
