### ISSUE TITLE
Restrict permissions on Google Docs addon

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1594]
See discussion at https://groups.google.com/forum/#!topic/drawio/L-nhB911iTU

The docs addon needs to be merged into the same app ID as the standard draw.io ID.

**Comment by tiagosimao** [comment]
Hi there

Just bumped into this trying to use draw.io in GDocs in a corporate environment (sec team denied the request)

I know you don’t accept contributions but just wanted to make myself available if that helps.

Guessing a fork/selfhost approach could work but would prefer an improved upstream :)

Cheers!

**Comment by davidjgraph** [comment]
This isn't technically possible. We tried, but the implementation caused Google performance issues, so they disabled it.

The suggested route is to publish the addons internally and use that. We open sources the addon code so you can do that, https://github.com/jgraph/drawio-google-docs.
