### ISSUE TITLE
Text to graph

### ISSUE THREAD

**Issue by akinuri** [jgraph/drawio#1601]
Is there ever going to be a text to graph converter? Text might be an indented list that represents a hierarchy. For example:

```
Matter
    Animate
        Animal
        Plant
    Inanimate
        Rock
        Water
        Wood
```
The output graph could be something as simple as this:

![Screenshot of the desired graph drawn in draw.io](https://i.imgur.com/grbgHmy.png)

While I like this app and it helps greatly, it's still a pain to manually create these hierarchies. There should be a way to seperate data (text/list) from presentation (graph). Modifying the data/list is much easier than modifying the graph. And at the most of the cases, the data has the greater priority than the graph. So spending time on the graph (add, reposition, edit, type, etc.) is a waste.

So I'd love to see a text to graph feature.

**Comment by timfrankentwf** [comment]
Something like Mermaid?
See: https://www.diagrams.net/blog/mermaid-diagrams

**Comment by akinuri** [comment]
Woa. This is much advanced than what I had in mind. I can make do with this.

There's only one downside to it. Supporting simple lists. e.g., the one I provided. If I were to draw it using this lib/syntax, I'd have to unnecessarily repeat some items. For example, compare the two:

```
Matter
    Animate
        Animal
        Plant
    Inanimate
        Rock
        Water
        Wood

graph TD;
    Matter-->Animate;
    Matter-->Inanimate;
    Animate-->Animal;
    Animate-->Plant;
    Inanimate-->Rock;
    Inanimate-->Wood;
```
Almost anyone would be able to understand/form the first list. Understanding or forming the second list requires some background knowledge.

One could write a simple parser that transforms the first/simple list into Mermaid syntax. That's one of the solutions, I guess. Having this feature out of the box would be great.

Anyway, I'm glad you brought this into my attention. It'll help me even its current form.
