### ISSUE TITLE
Highlight Connected Objects

### ISSUE THREAD

**Issue by MattAndrick** [jgraph/drawio#161]
Hi All,

As I was using drawio the other day, I thought of a feature that could be quite useful:

-When selecting an object that's connected to other objects, highlight all in-scope (connected) objects and low-light all out-of-scope objects.

A similar feature exists in a variety of graphing/visualization programs I've used, where when an item in the legend is clicked, the graph will highlight that subject in the visual. Hope this makes sense...

Thanks!

**Comment by mararad** [comment]
Highlight connected vertices when a vertex selection is made
https://trello.com/c/kkSv2IoP/301-highlight-connected-vertices-when-a-vertex-selection-is-made

**Comment by pekcheey** [comment]
Along with highlighting, it might be useful to 
perhaps with a modifier key, introduce a "select connected shapes" 
or maybe a expand selection to connected shape.

**Comment by mejl** [comment]
Highlight the text when dragging mouse over it would be good. It worked in the beginning but now when I add new stuff to the flow chart it doesn't work for some reason. I'm using it in SVG

**Comment by davidjgraph** [comment]
Closing, not enough interest from the core team.

**Comment by murphyke** [comment]
This would be so useful in diagrams with complicated connections/dependencies.

**Comment by thiagoestradiotodossantos** [comment]
This would be very useful!
