### ISSUE TITLE
Draw.io - Google add on keep throwing "Exception: Unexpected error while getting the method or property getActiveDocument on object DocumentApp." while refreshing a diagram

### ISSUE THREAD

**Issue by pravin-ms** [jgraph/drawio#1610]
Hello - while refreshing a dia. by doing "update selected" or even inserting a new dia. keep throwing 

Exception: Unexpected error while getting the method or property getActiveDocument on object DocumentApp.

The same dia. used to be working just fine 2 days back -- this has been an critical error as draw.io with in google is almost not usable at the moment. thx. any point fixing this would be greatly helpful. 

Thank you,
Pravin

**Comment by davidjgraph** [comment]
Could you show us a screenshot of what you see please?

**Comment by pravin-ms** [comment]
after selecting a pre-inserted dia for "update selected" here is what receive 
![image](https://user-images.githubusercontent.com/50378926/101933858-9e79a100-3b91-11eb-90a5-55b8fe5bd9be.png)

while clicking more details - below opens up - and nothing really refreshes 

![image](https://user-images.githubusercontent.com/50378926/101933820-94f03900-3b91-11eb-999f-c42071277682.png)

**Comment by davidjgraph** [comment]
I have no idea what software that is, but it's not ours.

**Comment by pravin-ms** [comment]
This comes from draw.io - google add on

**Comment by davidjgraph** [comment]
There is a template for bug that you deleted, if you're not going to make the basic effort to fill it in, we're not going to help you.
