### ISSUE TITLE
Support a background layer/page 

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1612]
* Add layers as includes or modules. If a add a background layer "Design" related to a separate Design.xml I can change the background design for all diagrams at once by editing the Design.xml

* Assign page background to another page: https://groups.google.com/forum/#!msg/drawio/c-DK_EoRGb4/1-Nr59QRAQAJ

* One additional feature would be to make a layer (or layers) from a background tab selectable (and also connectable). 
https://desk.draw.io/a/tickets/36165

**Comment by davidjgraph** [comment]
There are too many feature requests in one issue. If readers would like any of these please add an issue per item and link between them if needed.
