### ISSUE TITLE
Allow import/export custom library in deflated xml

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1613]
I'd like to be able to persist my library using a version control system in plain deflated xml. This will allow me to more easily see what I changed in my shapes.

**Comment by aurelien-opex** [comment]
There is another reason for this feature: we use Drawio to design models that are later compiled into code. Hence it is important that the designers uses the exact shapes and links that have been predefined, including their styles and parameters. When we make improvements in the compiler, it may happen that more parameters are needed and then, we have to manually edit the library by removing all shapes and re-adding the new version.
We would like to directly edit the XML file to add new parameters to the templates

**Comment by TeaDrinkingProgrammer** [comment]
Another problem that this would solve is collaboration on custom shape libraries. It is very cumbersome to make small changes to libararies now.

**Comment by gustaphe** [comment]
This would mean two big improvements to me: 
* Being able to compare versions in git (`` `str="mispelled"` =>`str="misspelled"` ``)
* Being able to edit libraries in external editor
