### ISSUE TITLE
(Tablet) Pen support with automatic recognition of shapes/arrows/etc

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1614]
Maybe just as a plugin:
let the user draw the diagram with the pen, and automatically recognize shapes the user draws in real time.

**Comment by xsolinsx** [comment]
Hi @davidjgraph, I know it's kind of necroposting but do you have any details on why this has been declined?
I was looking for this functionality and wanted to understand whether there is a specific reason to not implement this or whatever

**Comment by davidjgraph** [comment]
It's outside the scope of the tool we want to create. It's also relatively complex to implement.

**Comment by gajop** [comment]
Ah it's unfortunate that this got declined.
I find myself making first pass sketches in OneNote and then spending more time refining them in draw.io 

I think perfect shape detection isn't necessary - as long as it gave an option to convert things through some popup/gesture system.
