### ISSUE TITLE
files titled whatever.drawio do not open, says not valid file

### ISSUE THREAD

**Issue by rrlovelace** [jgraph/drawio#1615]
files titled whatever.drawio do not open, says not valid file.

How do I get those files to open?

**Comment by mararad** [comment]
Hi, 

where did you save these files? What steps are you performing in order to open them? How did you save them?

Thanks,

**Comment by rrlovelace** [comment]
1.	File (menu item)
2.	Save as
3.	Device (tried with dropbox, download, etc)
4.	Choose the file location
5.	Enter a file name
6.	Leave XML File as the option (default)

 

Thanks

Rob L

CXO

RepoSystems.Com Inc.

O 972.501.0375 x1006

D 469.444.6559

F 214.853.5327

**Comment by mararad** [comment]
Thanks.

I am not able to reproduce this. I followed your steps and I could open .drawio file saved to device by double click and/or right mouse click > Open > draw.io

I use diagrams.net online 14.0.3, Chrome Version 87.0.4280.88 (Official Build) (64-bit) and Win10 Pro.

If you still have the same issue, you could try the desktop app if it suits your needs.

Regards,
