### ISSUE TITLE
Edge to edge connections

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1617]
"It is useful in all kinds of circuitry diagramming."

"If you have several lines flowing into a single connection, it's pretty clunky that they all have to flow over each other. I'd really like this feature."

"Allow fixed connection points anyplace along a connector wire. In electronics, it's called a 'bus'-- a wire with multiple connections along its length."

"Very difficult to draw an electrical schematic without this. It takes hours longer to draw even a very simple schematic. Drawing anything with parallel paths is simpler with this. Conceptually, a "T" wiring point could be an object that is added by breaking a wire into two with the object dropped into the connection spot."

**Comment by hwongbaul** [comment]
I love this feature, and glad to see edge2edge is taken into consideration. #904

**Comment by ConnorNovak** [comment]
For others who find this issue before it is resolved, i've found that a tenable workaround is the "Waypoint" object in the "Misc" dropdown. Just place them at points where multiple lines intersect. It's a bit of work, but better than multiple overlapping lines.

**Comment by m-radzikowski** [comment]
Is this a "wontdo"?

**Comment by davidjgraph** [comment]
It's a wontdo. We've been discussing this one on the current model architecture for 16 years now. Without a new model each end of an edge can only connect to a vertex or nothing. This makes the best workaround connecting to a vertex that you don't realize is there. We already have that workaround.

**Comment by rahav** [comment]
Adding connection points to shapes is a new feature that diagrams.net just added. As a result of this release you can use the visual editor to actually add connection points to lines. This is a mission critical feature for all electronics, software timing diagrams, UML, ... you name it.

The new feature behaves a little bit odd and probably need some bugs fixed, but I urge the diagrams.net team to consider keeping it (and fixing the [bug](https://groups.google.com/g/drawio/c/pidyvWUShoY/m/aySJkTzrAgAJ)).

**Comment by davidjgraph** [comment]
@rahav No, I made it very clear this is not a bug. It's also not mission critical to us. Your post is simply totally overly dramatic and will be ignored.

**Comment by rahav** [comment]
@davidjgraph Your reply is rude, but it looks like [general practice](https://groups.google.com/g/drawio/c/kTcuz5r3W_c/m/wDi7pkc9EAAJ) for diagrams.net.

Thank you for extending this service, adding to the reasons to not license the product commercially.

**Comment by davidjgraph** [comment]
Likewise, your post is contary to the project code of conduct. You are banned from all communications with us and your company banned from using the product.
