### ISSUE TITLE
Feature Request For Integral Group

### ISSUE THREAD

**Issue by zhongxiang117** [jgraph/drawio#1619]
It will always come to the situation that we want to make the slightly changes on graph, like changing objects' spaces, moving to different places, or putting to different layers. And also, we want to make this type of change take effects on many different objects **in one time.**

Surely, we can use "Group" function to make those objects temporarily grouped together. However, this function is not forced, which means we can easily break it by only choosing one of them and making "relative" changes.

To better show this scenario, please have a look;

![Feature-Request-Integral](https://github.com/zhongxiang117/codeDump/blob/master/imageTrashBin/drawio-freature-request-integral.jpg)

So, please take a consideration to add this feature, many thanks!

**Comment by davidjgraph** [comment]
How is this different from selecting a number of objects and performing the action?

**Comment by zhongxiang117** [comment]
@davidjgraph In a nutshell, the `integral` is a higher level command than `group`, its subsets cannot be changed.
Here is an explanation from ChemDraw:
http://www.cambridgesoft.com/services/documentation/sdk/chemdraw/ActiveX11/ChemDrawControl10~Group~Integral.html

The reason to request this type of feature is that if we have lots of objects in Drawio and they have complex relations, e.g., in the different "layers" (front and back), or nested with each other (overlaps), using `group` cannot make subset inside them be independent, most time will occasionally select those subobjects if we want to make changes and updates. So the “integral” is the true meaning of `group`s, they are grouped as a unity.
