### ISSUE TITLE
When changing from rectangle to process, text overlaps until orange adjuster is used

### ISSUE THREAD

**Issue by t-miller** [jgraph/drawio#162]
Immediately after replace:
![image](https://user-images.githubusercontent.com/19845698/31839061-6feac2be-b5ad-11e7-9053-dc469072f72e.png)

After orange adjuster used:
![image](https://user-images.githubusercontent.com/19845698/31839098-9e95d950-b5ad-11e7-9f3d-cdd2f4fd1d20.png)

**Comment by alderg** [comment]
Thanks for the report, this will be fixed in the next release.
