### ISSUE TITLE
Container toggles not visible in export

### ISSUE THREAD

**Issue by minke-b** [jgraph/drawio#1620]
In a downloaded HTML export, container element collapse toggle icons are not visible. They are, however, still active and work if you know where to click. Also working fine whilst editing the diagram. 
First noticed when this bug when the toggle icon changed from "+" / "-" to a dropdown arrow icon. 
Using the web app 14.0.1
Please see attached screenshots of the new dropdown arrows for containers as seen visible in the app versus missing in the export:
![Schermafbeelding 2020-12-14 om 13 53 21](https://user-images.githubusercontent.com/76045123/102216958-35b95e00-3edc-11eb-94db-557af21da455.png)
![Schermafbeelding 2020-12-14 om 13 54 43](https://user-images.githubusercontent.com/76045123/102216970-38b44e80-3edc-11eb-8dcf-54db300ff505.png)

**Comment by mararad** [comment]
Reproduced at my place also. When swimlanes are exported as HTML, collapse/expand arrows are not visible anymore but they work if you click where their place is.

diagrams.net 14.0.1 Chrome and Chrome Incognito
Win 10 Pro

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
