### ISSUE TITLE
Missing button icons on the Layers, Outline & Comments panel

### ISSUE THREAD

**Issue by dreamertor** [jgraph/drawio#1622]
Hi, it has been a few days that the **Minimize**, **Close** and **Resize** icons are missing at the _Layers_, _Outline_ & _Comments_ panels.

https://app.diagrams.net/images/resize.gif
https://app.diagrams.net/images/close.gif
https://app.diagrams.net/images/normalize.gif

Thanks.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by dreamertor** [comment]
Noted. Thanks for the quick response, Gaudenz.
