### ISSUE TITLE
App.prototype.getDiagramId() and App.prototype.loadFile functions always will use location.cash as encrypted file?

### ISSUE THREAD

**Issue by Andrewbayav** [jgraph/drawio#1623]
I added keycloak javascript adapter to drawio, it redirects me to keycloak login page, after my autentification keycloak gets me back to drawio url with location.hash like #state=;,ds;aldl&session_state=akjdlkjas&code=askd;l12, it leads to exeption with alert screen which says 'Error loading file, service unavaliable or blocked' cause hash's first letter is not an R, T, S, G and else.
![photo_2020-12-15_15-55-15](https://user-images.githubusercontent.com/51492165/102364669-c5880680-3fc7-11eb-93d1-47c94c530a7f.jpg)
![photo_2020-12-15_15-56-05](https://user-images.githubusercontent.com/51492165/102364672-c6b93380-3fc7-11eb-9d06-95e73b18c1b1.jpg)

And i can solve it only:
 1. by changing original code;
 2. by redefinition of App.prototype.loadFile(..) with all it's 400 lines (not good) in my plugin
 
Maybe there is the way to let users make their own handlers/functions on location hash to make it work with OAuth or OICD and maybe other default storages?

**Comment by davidjgraph** [comment]
That's https://www.keycloak.org/ ?

What problem are you trying to solve at a high level? i.e. why would you add authenication to draw if that system doesn't offer storage?
