### ISSUE TITLE
Vertical alignment of buttons

### ISSUE THREAD

**Issue by maharjanaman** [jgraph/drawio#1624]
Minor design issue. Button isn't vertical with input.
<img width="242" alt="Screen Shot 2020-12-17 at 00 53 44" src="https://user-images.githubusercontent.com/14164484/102394929-8dea8000-4002-11eb-8378-c5fa91d66617.png">

**Comment by davidjgraph** [comment]
draw version? OS and Browser version? i.e. the details in the bug template that you deleted.

**Comment by maharjanaman** [comment]
Sorry about that, but I didn't get any template. The draw version is 14.0.4 on the web with brave browser Version 1.18.70 Chromium: 87.0.4280.101. I'm also seeing this on the macOS app versioned 13.9.9.

**Comment by davidjgraph** [comment]
OK, thanks, we'll take a look.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
