### ISSUE TITLE
[feature request] vertical page menu & readonly mode

### ISSUE THREAD

**Issue by coocooooo** [jgraph/drawio#1626]
first thank you for your excellent work , I have two feature request, wish those improve make the product better

### vertical page menu
if you have so many page, horizontal page menu shrink, and be useless(we do have popup, but can't sort in it, and it can't pin).  if we can have vertical page menu, link style pane in the right side, it would be nice

![image](https://user-images.githubusercontent.com/7315454/102435908-68856280-4052-11eb-8253-c01e29106244.png)

### readonly mode
when I review my work, accident drag the block is so frustrating

---
best regards!

**Comment by coocooooo** [comment]
For your reference I use product as a notebook, not something to generate svg or others. It help me a lot.

**Comment by mararad** [comment]
Hi,

regarding your 1st suggestion, please track this issue here: https://github.com/jgraph/drawio/issues/647 because it was already asked by users

Could you please provide me with additional details related to readonly mode? Not sure I understood what was happening at your place.

Thanks,

**Comment by coocooooo** [comment]
@mararad  I mean lock the page, so it cannot be edit anymore, so I can view my note without accident move the shape in the page

**Comment by coocooooo** [comment]
editable or not

**Comment by mararad** [comment]
Try the following: 
* select your diagram and click Edit > Lock/Unlock or
* click View > Layers and lock it/them

Does this help?

Regards,

**Comment by coocooooo** [comment]
thank's a lot, got it.
