### ISSUE TITLE
Scroll actions do not seem to work correctly

### ISSUE THREAD

**Issue by minke-b** [jgraph/drawio#1629]
I am using the web app 14.0.1. In downloaded HTML exports, scroll actions do not seem to work correctly. 
See attached screenshots. Clicking on "click here" scrolls to "link test", but then I am not able to scroll all the way to the top of the diagram anymore.
Clicking on "go back" then also does not scroll the page back to element "click here"

![Schermafbeelding 2020-12-15 om 13 54 42](https://user-images.githubusercontent.com/76045123/102479317-097a1a80-405f-11eb-84a8-05c4811f0d0d.png)
![Schermafbeelding 2020-12-15 om 13 54 26](https://user-images.githubusercontent.com/76045123/102479336-0f6ffb80-405f-11eb-958d-bee48cd3e837.png)

EDIT: scroll actions: https://drawio-app.com/interactive-diagrams-with-custom-links-and-actions/

**Comment by mararad** [comment]
Hi,

if you repeat all the steps in other browsers and Incognito mode, does it help?
If not, attach a draw.io file here so we could test it + tell us browser version and operating system you are using.
Just to confirm you clicked File > Export as > HTML?

Thanks,

**Comment by minke-b** [comment]
Hi,

Thanks for your reply.

Yes incognito gives me the same result. 
I tried in these browsers:
Chrome version 87.0.4280.88
Firefox version 84.0
Using:
MacOS Catalina version 10.15.7.

Correct, I used File > Export as > HTML
Please see attached draw.io file:
[Support-containers&links.drawio.zip](https://github.com/jgraph/drawio/files/5709860/Support-containers.links.drawio.zip)

**Comment by mararad** [comment]
Thanks.

Reproduced in Chrome Incognito Version 87.0.4280.88 (Official Build) (64-bit), diagrams.net 14.1.1 and Win10 Pro
