### ISSUE TITLE
Can't crop when exporting PDF offline

### ISSUE THREAD

**Issue by Alkaid-Benetnash** [jgraph/drawio#163]
I start a http server locally in the `war` directory. But when exporting as PDF, the menu is
![image](https://user-images.githubusercontent.com/9082286/31859775-b18ad3c0-b6d5-11e7-9510-0960ccc039d2.png)

while the draw.io's menu is
![image](https://user-images.githubusercontent.com/9082286/31859794-ce228f00-b6d5-11e7-909e-d84bf5a524ec.png)

How can I enable the crop feature?

**Comment by alderg** [comment]
The Crop option is only available when using our external PDF export service.

**Comment by Alkaid-Benetnash** [comment]
@alderg 
So that's a closed source component for now and I can't build one offline, right?

**Comment by alderg** [comment]
Correct.

**Comment by Alkaid-Benetnash** [comment]
thanks for your clarification!

**Comment by davidjgraph** [comment]
To clarify, the image/PDF generation server code is open source, https://github.com/jgraph/draw-image-export2.
