### ISSUE TITLE
Gitlab integration

### ISSUE THREAD

**Issue by Veshialle** [jgraph/drawio#1631]
I'm trying to integrate a gitlab installation on premise with a docker container of draw.io (jgraph/docker-drawio).

I state that I'm not sure if I need to open it in this repository or inside the proper container repository.
I'm also not sure which logs to check for this purpose.

The problem is that, trying to link the related user in Gitlab I always get Access Denied only via https:
![image](https://user-images.githubusercontent.com/15987201/102513643-c2564e80-408b-11eb-9faf-239c577f756d.png)

While if I navigate the draw.io istance I can do it without any issue:
![image](https://user-images.githubusercontent.com/15987201/102513770-edd93900-408b-11eb-8d5d-21ada75fe5b6.png)

Thanks

**Comment by davidjgraph** [comment]
Does this work in latest draw.io release?
