### ISSUE TITLE
Mindmap shapes are not visible in advanced tab

### ISSUE THREAD

**Issue by pawelmarkowski** [jgraph/drawio#1634]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Shapes like Sub Topic (MindMap) described on https://www.diagrams.net/blog/automated-layout-shapes are not visible. It was possible to use them few days ago. They are still visible in shapes library as you can see in the screenshots.

**To Reproduce**
1. Go to the diagram
2. Click on Shapes Advanced Tab
3. See missing shapes

**Expected behavior**
Mindmap shapes are available to use.

**Screenshots**

![image](https://user-images.githubusercontent.com/9445856/102729509-48df8a00-4331-11eb-9b99-f5f25be9ad91.png)
![image](https://user-images.githubusercontent.com/9445856/102729763-55b0ad80-4332-11eb-8a48-850c159e778f.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 14.1.1

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser chrome / firefox
 - Version latest

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
