### ISSUE TITLE
When I double click to add text, scrollbar move to the top of screen, and hide my background

### ISSUE THREAD

**Issue by HubMez** [jgraph/drawio#1635]
### Preflight Checklist

* [ X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I double click on a element to add text, scrollbar move to the top of screen, and hide my background. So I can't do anything.

**To Reproduce**
1. Create a new draw
2. Add any elements for example a rectangle
3. Double click on it to add text

**Expected behavior**
Normaly I can insert a text. Now my screen become white because of the scroll bar is on the top of sreen hidding my draw.

**Screenshots**
![Capture d’écran 2020-12-21 à 16 11 32](https://user-images.githubusercontent.com/76441530/102791457-53d50180-43a7-11eb-9895-2d9a16f67c94.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
draw.io Version 14.1.1

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version 87.0.4280.88 (Build officiel) (x86_64)

**Comment by HubMez** [comment]
It works when I am in a private navigation.

**Comment by ashrafteleb** [comment]
@HubMez Since it works correctly in private navigation, it maybe related an extension

Is there any errors in the browser console?

**Comment by HubMez** [comment]
@ashrafteleb there's no error in the browser console
👇
<img width="1280" alt="Capture d’écran 2020-12-27 à 09 34 41" src="https://user-images.githubusercontent.com/76441530/103166884-ce2dd780-4826-11eb-9008-c2e282447023.png">

**Comment by HubMez** [comment]
SOLVE !
I 've desactivated an extension (Merciappp, to correct the mistakes), and it works ! ths @ashrafteleb for your help !
