### ISSUE TITLE
Genogram stencils (and pedigree chart symbols)

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1638]
That´s a very important feature. It is a Set of Genogram Symbols and such kind of line-forms necessary for drawing good Genogram. 

Asked in https://drawio.freshdesk.com/a/tickets/35622 and https://trello.com/c/VUOWOmYl/208-genogram-stencils-and-pedigree-chart-symbols

![genogram](https://user-images.githubusercontent.com/44292306/102810274-b4723780-43c3-11eb-84dc-4460a96d48d6.png)

**Comment by fgiering** [comment]
What a pity!

**Comment by adam-ah** [comment]
I added them here as a library https://github.com/adam-ah/genogram_drawio
All the symbols from @mararad sample are covered
