### ISSUE TITLE
Privacy Issue with Sandstorm Edition - Export

### ISSUE THREAD

**Issue by zeigerpuppy** [jgraph/drawio#164]
When exporting an image from the Sandstorm version of draw.io, the output URL is https://exp.draw.io/ImageExport4/export

This presents a security issue and breach of usual Sandstorm standards, where all I/O should happen to/from the Sandstorm Server.

To reproduce:
File >> Export As >> Advanced
Export and select "Open in new window"

The export is shown originating from the exp.draw.io domain

**Comment by ocdtrekkie** [comment]
@zeigerpuppy What browser are you using?

I discussed this issue with David during app review, and I believe he said that it "shouldn't" process externally on Chrome or Firefox. (I was testing on Edge.)

**Comment by alderg** [comment]
The Advanced dialog uses the external service, while the direct export options in the menu use client-side image generation in Chrome, Firefox and Edge.

**Comment by ocdtrekkie** [comment]
I believe the *ideal* situation would be that for a self-hosted install of draw.io (whether Sandstorm or otherwise), ideally it should offer a warning dialog when exporting data to an external service. Presumably of course, with the option to skip the warning in the future.

**Comment by alderg** [comment]
@zeigerpuppy Why are you using the Advanced image export and not on of the direct export options btw?

**Comment by zeigerpuppy** [comment]
I usually use the advanced export when needing to set the resolution of a PNG export
