### ISSUE TITLE
App.prototype.loadFile does not call success(); for URL ('U') files

### ISSUE THREAD

**Issue by ga5tan** [jgraph/drawio#1640]
* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

App.prototype.loadFile does not call success(); for URL ('U') files.
Some file sources have this code:
`if (success != null)
				{
					success();
				}`
to call success parameter after file loaded.
This is unfortunately not the case for 'U' path:
`else if (id.charAt(0) == 'U')`

**To Reproduce**
call loadFile function:

`this.loadFile(fileUrl, true, null, mxUtils.bind(this, function () {
        
        console.trace(temp);
        this.actions.get('fitWindow').funct();
        this.actions.get('lockUnlock').funct();
    }));
`

**Expected behavior**
success() function is called, after file is loaded, fitting loaded file to the window

- draw.io version 14.0.4

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome, FF
 - Version latest

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
