### ISSUE TITLE
[Dropbox] Access denied on create/open diagrams

### ISSUE THREAD

**Issue by fabiofdsantos** [jgraph/drawio#1644]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I'm unable to create or open diagrams.

**Screenshots**
![image](https://user-images.githubusercontent.com/8303937/102887922-b2ee5100-444f-11eb-9031-81c774b71161.png)

![image](https://user-images.githubusercontent.com/8303937/102887893-a1a54480-444f-11eb-904b-cc2eb1b79465.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 14.1.1

**Desktop:**
 - OS: macOS 11.1
 - Browser Safari 
 - Version 14.0.2

**Additional context**
I can reproduce the issue in Google Chrome.

**Comment by davidjgraph** [comment]
Do you have third-party cookies blocked?

**Comment by fabiofdsantos** [comment]
@davidjgraph 

I'm sorry. I didn't share the console error.

```
Refused to connect to 'https://dl.dropboxusercontent.com/1/view/xxxxxxxxx/file.drawio' because
 it violates the following Content Security Policy directive: "connect-src https://*.dropboxapi.com 
https://api.trello.com 'self' https://*.draw.io https://*.diagrams.net https://*.googleapis.com 
wss://*.pusher.com https://*.pusher.com https://api.github.com 
https://raw.githubusercontent.com https://gitlab.com https://graph.microsoft.com 
https://*.sharepoint.com https://*.1drv.com https://*.google.com https://fonts.gstatic.com 
https://fonts.googleapis.com".
```

Should we just replace `https://*.dropboxapi.com` with `https://dl.dropboxusercontent.com`? (I'm not aware of the integration with Dropbox)

**Comment by fabiofdsantos** [comment]
@davidjgraph I'm sorry. I didn't share the console error.

```
Refused to connect to 'https://dl.dropboxusercontent.com/1/view/xxxxxxxxx/file.drawio' because
 it violates the following Content Security Policy directive: "connect-src https://*.dropboxapi.com 
https://api.trello.com 'self' https://*.draw.io https://*.diagrams.net https://*.googleapis.com 
wss://*.pusher.com https://*.pusher.com https://api.github.com 
https://raw.githubusercontent.com https://gitlab.com https://graph.microsoft.com 
https://*.sharepoint.com https://*.1drv.com https://*.google.com https://fonts.gstatic.com 
https://fonts.googleapis.com".
```

Should we replace `https://*.dropboxapi.com` with `https://dl.dropboxusercontent.com` or just append the second domain? (I'm not aware of the integration with Dropbox)

PS: Happy new year! 🥂

**Comment by davidjgraph** [comment]
The version is a little old. Go to https://app.diagrams.net/clear.html after closing other tabs with diagrams.net open. Once cleared try again with the latest version of the app.
