### ISSUE TITLE
 Images displayed in svg format in README.md do not display images correctly.

### ISSUE THREAD

**Issue by fs-takada** [jgraph/drawio#165]
I would like to manage a network diagrams with drow.io using Github.To save using Github you need to save it in svg format.However, when I paste an image link in readme.md, the display will be wrong in some places.(For example, text does not break, html tag is displayed.)

I hope to improve this.

**Comment by alderg** [comment]
What browser are you using?

**Comment by fs-takada** [comment]
I use Chrome.However the same phenomenon occurred even with firefox.

**Comment by alderg** [comment]
Can you share a link where this problem can be seen?

**Comment by fs-takada** [comment]
I prepared it in this repository.
https://github.com/fs-takada/test/tree/master

Please compare the picture displayed in the README with the actual file of svg.

**Comment by alderg** [comment]
Looks like GitHub is trying to be clever. Try https://cdn.rawgit.com/fs-takada/test/b8873165/sample.svg or use a gh-pages branch to deliver the SVG instead.

**Comment by fs-takada** [comment]
I'll try that way. Thank you.
