### ISSUE TITLE
Add way to configure keyboard shortcuts

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1654]

**Comment by sphakka** [comment]
Please, ensure that the **desktop** app get proper treatment ^^ I'm particularly missing menu bindings à la "Alt+...", etc.

**Comment by davidjgraph** [comment]
No need to comment to say "me too". Thumbs up on the original post is the convention to vote for it

**Comment by Screenfeed** [comment]
Hello,

This would fix an issue we have on MacOS: it uses at least 1 OS-native shortcut, Cmd+M, which is meant to minimize the current window, the kind of shortcut we use dozens of times each day.

**Comment by AlexandreBonneau** [comment]
This would also solve the issue where the well known shortcuts have been changed without giving the users a way to revert the faulty changes back (see https://github.com/jgraph/drawio/issues/3632).
