### ISSUE TITLE
Persistent zoom levels

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1661]
I have a large diagram over 50 pages. When I am working on it I like to see each page zoomed at 75%. Whenever I close and reopen the diagram I see that all 50+ pages have defaulted back to 100%, so before I begin work I need to resize each page to 75%, which is annoying and a waste of time.

Is there a way to set the page default zoom to 75% for the entire diagram and have is save that way?

**Comment by mararad** [comment]
Asked the same in https://github.com/jgraph/drawio-desktop/issues/723

**Comment by davidjgraph** [comment]
We cannot find a good solution to this. Saving the zoom level per page in the diagram falls apart when users are collaboratively editing.
