### ISSUE TITLE
Gradient and/or blur the shadow of a shape

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1671]
One feature i'd like to propose and think would highly improve many diagram looks into looking more professional out of the box is to gradient and/or blur the shadow of a shape. Right now it's a boolean attribute and one color. The added 3d effect and texture make things look more familiar esp. in diagrams w/ a lot of layers/boxes.

Proposed:
- feature one: blurred / not blurred shadow attribute.
- feature two: parametrize w/ x/y shadow offset, shadow color and blur intensity.
(I think some of those are already implemented in CSS/SVG).

https://desk.draw.io/a/tickets/10924

**Comment by ddidier** [comment]
I was looking for this sorely missing feature, so I took a look around the code and [found this](https://github.com/jgraph/drawio/blob/533720a8c7fd283c68275d81f222e617a34428f6/src/main/webapp/js/diagramly/util/mxJsCanvas.js#L604). As far as I can tell `ctx` is a [CanvasRenderingContext2D](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D) so we should use [CanvasRenderingContext2D#shadowBlur](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/shadowBlur).

**Comment by ddidier** [comment]
is there some news on this request?

**Comment by davidjgraph** [comment]
The issue is declined through lack of interest from the core team.

**Comment by rusyn66** [comment]
So is this implemented? This is the most important feature. I have to use cacoo.com just because they have shadow blurred compare to drawio which show just a second box and looks awful compare to cacoo box with shadow which looks natural.

**Comment by AymanProjects** [comment]
We still want it 🤓

**Comment by henry-js** [comment]
+1

**Comment by brsrom** [comment]
+1000000000000000000000000

**Comment by AceDicer** [comment]
+1

**Comment by karthifairhawn** [comment]
+1

**Comment by MeGilles** [comment]
+1

**Comment by bluetata** [comment]
We still want it

**Comment by PaulGBarbu** [comment]
Blurred shadows seem to already be a thing, but can only be applied globally (Have nothing selected > Diagram > Shadow). But unfortunately, it applies to everything. So the functionality seems to be there, am I maybe overlooking something?

**Comment by Ale-Naa** [comment]
+1

**Comment by ivnilv** [comment]
+1 

Why is this even marked as Closed ?

Come on now!

**Comment by josemoren** [comment]
+1

**Comment by davidjgraph** [comment]
I unsubscribed to this issue some time ago due to the amount of useless comments. So congrats, you pushed the issue back 6 months by spamming.

**Comment by davidjgraph** [comment]
The bounding box calculation is hard per shape with the blurred shadows. It's a lot easier to apply globally and just add a bit to the overall bounds.

**Comment by davidjgraph** [comment]
In 24.0.0.
