### ISSUE TITLE
Support the length of a line

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1677]
* It will be very useful if I could get the length of lines without calculating it using e.g 10pt grid and scale 1pt=1cm which works for horizontal and vertical lines but for other line orientations is hard.

* Add length to (x,y) popup when dragging a line will be helpful. http://cogito-ergo-sum.ru/line.png
https://desk.draw.io/a/tickets/11151

![line](https://user-images.githubusercontent.com/44292306/103139925-c7497c80-46e1-11eb-88d6-b35ef6eb42a3.png)

**Comment by burner-** [comment]
indeed this would be quite must have feature

**Comment by jeffatoptics** [comment]
Was this feature request dropped?  i do not see the display of line length in the latest release.

**Comment by davidjgraph** [comment]
It was rejected yes. If you prefer I can reopen the issue and nobody implement it.

**Comment by burner-** [comment]
> It was rejected yes. If you prefer I can reopen the issue and nobody implement it.

Quite grumpy way to take attitude for good and proper feature request. Is that project dead or what is reason that it wont go to implementation?

**Comment by ngarner-at-goxaas-dot-com** [comment]
Lol the last chat is comment is only 10 hours old.
 
Some questions:
1. Does anyone know how many story points this feature would require to deploy annnnnd effort to maintain?
2. Do you know how much it would be to crowd fund this feature on something like https://gitcoin.co/?
3. Do you think I it will be easier to make a tampermonkey script to fill in this gap? This was my original plan (keep all the automation abstracted (maybe add a bar to the top of the screen to show live numbers and for measurement input, the just push the change once you release the mouse drag is released)

**Comment by burner-** [comment]
Good question? Mashing head to wall almost daily with this I am quite interested to participlant for crowd fund.

**Comment by davidjgraph** [comment]
> Quite grumpy way to take attitude for good and proper feature request. Is that project dead or what is reason that it wont go to implementation?

We are fully entitled to decline a feature request. I closed the issue to reflect the fact that we don't want to implement this. Reopening it is pointless, as we don't wish to implement the feature.

Your attitude is extremely entitled. Continue and I will ban you from the project for breach of the code of conduct.

**Comment by PackElend** [comment]
to support the suggestion, that is what I did in PowerPoint, adding some auxiliary lines to draw the structure.
As I can define the length of the lines in mm at least that task is quite simple in PowerPoint
![image](https://github.com/jgraph/drawio/assets/3542031/bab0c114-23c3-4f8c-afb4-2a3b22a9eaaa)

In draw.io I have to misuse shapes 
![image](https://github.com/jgraph/drawio/assets/3542031/4761eda8-57bf-4b8f-96fa-1d5e9488b31c)

**Comment by davidjgraph** [comment]
Use %length% placeholder.

**Comment by PackElend** [comment]
> * **Enter the Placeholder**: In the label area, enter `%length%` as the text. This serves as a placeholder that will be replaced by the actual length of the line or edge in your diagram.
> *

I have just tried it but only shows the text, the placeholder is not replaced.
Does it work for anyone else?

**Comment by DmitryDemidov** [comment]
> > * **Enter the Placeholder**: In the label area, enter `%length%` as the text. This serves as a placeholder that will be replaced by the actual length of the line or edge in your diagram.
> 
> I have just tried it but only shows the text, the placeholder is not replaced. Does it work for anyone else?



It didn't work for me either, even though I'm sure I'm doing everything right.

<img width="122" alt="Screenshot 2024-04-10 at 23 48 50" src="https://github.com/jgraph/drawio/assets/12056520/ed7ccf75-a8b5-4ac7-9ac6-5503cd7271bd">

<img width="261" alt="Screenshot 2024-04-10 at 23 49 16" src="https://github.com/jgraph/drawio/assets/12056520/8af3e99f-b829-4909-9205-bbe80df6360e">

**Comment by davidjgraph** [comment]
<img width="544" alt="Capture d’écran 2024-04-11 à 18 51 41" src="https://github.com/jgraph/drawio/assets/1761087/5b57c227-fecb-4fd4-ab8f-2c3f5d3bec61">

**Comment by DmitryDemidov** [comment]
> <img alt="Capture d’écran 2024-04-11 à 18 51 41" width="544" src="https://private-user-images.githubusercontent.com/1761087/321733113-5b57c227-fecb-4fd4-ab8f-2c3f5d3bec61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MDIzNjIsIm5iZiI6MTcxMjkwMjA2MiwicGF0aCI6Ii8xNzYxMDg3LzMyMTczMzExMy01YjU3YzIyNy1mZWNiLTRmZDQtYWI4Zi0yYzNmNWQzYmVjNjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMDYwNzQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmM2MGRhN2E3NmU3ZTA1YmZjMTQ4ZTJhYmRiY2RjYzAwMTY5M2FhMGY1OTkzYWU4OTBjNjhmNGE1NzBhMmViMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Y-El_Ev3nFPn628juywEWA0kqngZxB65SMFxgYCWlu4">

Which version draw.io?

**Comment by davidjgraph** [comment]
24.2.3. If you're using desktop, you just need to wait for a new release.

**Comment by DmitryDemidov** [comment]
> 24.2.3. If you're using desktop, you just need to wait for a new release.

Thanks!

**Comment by Gudratliishere** [comment]
> 24.2.3. If you're using desktop, you just need to wait for a new release.

I am using web version v24.2.3 but It is not replacing with actual length when I use placeholder.
![image](https://github.com/jgraph/drawio/assets/72154679/342183f6-e429-4c1f-8d65-b304c9786a53)

**Comment by davidjgraph** [comment]
Is that the default label of the edge, or a new label you added to the edge?

**Comment by alderg** [comment]
Please attach a test case.

**Comment by exadmin** [comment]
No length support in desktop version 24.2.5

Test case:
1. Draw new line using "General" shapes library
2. Double click on the new line (or press F2) - to start editing line label
3. Enter "%length%" (without quotes) and clicking outside line
4. ER: %length% macro is replaced with real line length value
5. AR: plain text "%length%" exists

![image](https://github.com/jgraph/drawio/assets/23030824/7098655a-bb5a-47d5-a703-b19ceb2465f6)

**Comment by exadmin** [comment]
Thank you. Now succeed!

I was unclear that "placeholders" must be enabled.
Correct flow I've found is:
1. Draw new line
2. Press Ctrl+M and enable "placeholders" for the line
3. Use %length% macro

See gif below
![drawio-1677](https://github.com/jgraph/drawio/assets/23030824/14803f5b-24d6-4cb5-83fe-39182fa3d0fa)

**Comment by PackElend** [comment]
any chance that the length is shown in paper dimension (mm, inch etc.)?

**Comment by soph-os** [comment]
For those who struggle also like me with the placeholders. Press F2 to write the placeholder to a shape. When you use a double-click e.g. on a line, it's not converting the macro.

**Comment by ddomnik** [comment]
> any chance that the length is shown in paper dimension (mm, inch etc.)?

Thats a good idea, %unit% should be added to the predefined placeholders, which returns "mm" for example.

**Comment by alderg** [comment]
The drag hint now shows the length of the line in the diagram's current unit (View > Units: points, millimeters, meters or inches):

- **Drawing a new connection:** the hint shows the length while you drag.
- **Moving a waypoint, segment or endpoint:** the hint shows the position with the length in brackets, e.g. `50.8, 15.24 (20.32)`.
- **Endpoint snapped to a connection point:** the hint shows `[0%, 50%] (45.72)`.
- **Endpoint over a target shape:** the hint shows the length.

This will be in the next release. To show the length permanently in the label, use the `%length%` placeholder as described above.
