### ISSUE TITLE
Support re-ordering shapes when container vertical layout is used

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1680]
A user asked for the possibility to swap shape places in Container Vertical tree layout. 
The same feature request for Horizontal tree layout also

![swap_shape_place PNG](https://user-images.githubusercontent.com/44292306/103140136-4a1f0700-46e3-11eb-806f-9c408ffa11fa.png)

**Comment by davidjgraph** [comment]
It certainly can be revived, just the core team will unsubscribe from it 8-)

**Comment by Spenhouet** [comment]
@davidjgraph Thanks, so you are saying that as a feature request it is declined in the sense the community is open to implement this but the core team will not?

**Comment by davidjgraph** [comment]
The community is welcome to implement it, but in 10 years we've never had a single properly implemented PR of non-trivial complexity. It's mostly 10% tested garbage that we have to completely re-write if we want to add it.

**Comment by alderg** [comment]
As a workardound: Try right click on the incoming edge of the child and click "To Front".
