### ISSUE TITLE
Indicate "Line start" and "Line end"

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1683]
Suppose I click on an existing line on a diagram and I want to change the line ends. Let’s also say that it’s a line with no endings at the moment. How can I now which end of the line is the start and which is the end such that I can add an arrow? My current method is guess and check 😉 A circle and square would be a simple solution.

https://desk.draw.io/a/tickets/11774

![indicating_Line_start_and_Line_end_when_editing_a_connector](https://user-images.githubusercontent.com/44292306/103140215-68d1cd80-46e4-11eb-8d8d-000018018947.png)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
![photo_2021-11-16 09 14 02](https://user-images.githubusercontent.com/921200/141946524-c0e7c5c9-74ed-49bf-abcd-66c1860c9f12.jpeg)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release (bigger handle => line end).
![photo_2021-11-16 09 20 49](https://user-images.githubusercontent.com/921200/141947586-00842fdc-1c4f-45fc-bcda-4b0b20e445b5.jpeg)
