### ISSUE TITLE
Associate a comment with an object as seen in GDocs

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1694]
It would be helpful if comments were against some part of the drawing (ala Google Docs).
https://desk.draw.io/a/tickets/12977

Additionally, making it obviously visible that there is a comment associated with the object would be great. Right now, I just add a "speech bubble" object that says "hover for comment" which is awkward.

P.S we only support the tooltip plugin which shows a bubble speech showing a tooltip on hover. It can help with a tooltip visualisation but is not the replacement for comments seen in GDocs

**Comment by lqq4826** [comment]
Also looking forward to the new feature, it is really efficient
