### ISSUE TITLE
Support sharing layers as per OmniGraffle

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1695]
Is there a way of sharing layers between pages as per Omnigraffle
https://groups.google.com/forum/#!topic/drawio/eusAMrs9nZU

**Comment by iwtrf** [comment]
+1 for this request.  An example use case is to have a Background page that contains only a Background layer that is shared among all pages. A change to the single Background layer would then be reflected in all other pages. (Bonus points awarded for allowing the common background layer to be configurable per drawing page, either with an alternate background layer or none for a given page. :)  For example, all the drawing pages in a given drawing set could have the same shared layer containing project name, author, etc, but the title page would have an alternate or no background. ) This functionality is one of the Visio capabilities I miss most in diagram.net.
