### ISSUE TITLE
Add link icon in viewer on shapes that have links

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1699]

**Comment by mararad** [comment]
"ability to let diagram viewers know that a shape or object has a URL link in EDIT mode. 
In drawio when in edit mode you can’t actually tell if there are links to an object unless you hover your mouse over it. Is there any way to show an object has a link?"

Asked in DID 9573

**Comment by Bastesque** [comment]
Having the ability to link an entire shape (and making it clickable with blue highlight around the shape's perimeter) is great, but people don't see by default that there may be a subprocess etc. hidden behind the link unless they hover over the shape.  We would highly appreciate, if there was any visual hint once a shape is linked.
