### ISSUE TITLE
Support diagram scheme for SFC/Grafcet

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1701]
https://desk.draw.io/a/tickets/35788

**Comment by davidjgraph** [comment]
Closing through lack of additional interest.

**Comment by gabrielfaleiro** [comment]
Hi. I was looking for a software to support preliminary functional specifications of GRAFCETs and haven't found anything until now.

I would find that support on drawio very interesting since I already use this tool in many other drawings. 

Thanks in advance

**Comment by Indecents** [comment]
I agree this is a feature we (engineers) cannot find anywhere for free or opensource. the only software i can use is a school that made it back in 2003 (called EditSTAB). there is a real business around Grafcet/SFC diaggrams.

**Comment by ratchet11243** [comment]
This would be a good functionality. As a stop-gap I have thrown this custom library together - https://github.com/ratchet11243/DrawIO_GRAFCET/tree/main 

It is using standard draw.io symbols, so I expect it will be a bit janky in practice. If anyone has constructive feedback, that'd be welcome (especially if you know where I can find documentation that'll help with improving, for example, the transition, the action on event, or the directed link symbols)
