### ISSUE TITLE
Support partial filling

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1703]
Is it possible to fill only part of a shape (at least for a rectangle)? For instance 75% blue and 25% red as in a bargraph?
https://stackoverflow.com/questions/58174207/partially-filling-a-rectangle-with-mxgraph

![partial_filling_for_rectangle PNG](https://user-images.githubusercontent.com/44292306/103177162-440e5f00-4878-11eb-851e-6c2c097aed46.png)

**Comment by davidjgraph** [comment]
Closing through lack of additional interest.
