### ISSUE TITLE
Support sublayers

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1705]
"I have all of my classes drawn on separate layers (all students in class A on the same layer etc). I would like to perhaps have another 'sublayer' for each class that I can put this information on, use it as I move the students around and it stays with their name, but that I then 'hide' before exporting."
https://groups.google.com/forum/#!topic/drawio/rKqSAneRA3I

**Comment by idhamari** [comment]
I agree, this feature is important for large complex models!
