### ISSUE TITLE
Disallow multiple next grouping of cells

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1707]
"I never know, if I have already grouped elements. This is especially an issue, if I grouping hierarchially. I have a construct of company: Individuals, groups, Departements. Each of them has own elements. Therefore I'll group the elements for individuals, the for groups and so on. After that I'll group the individuals into a group, groups into Departements,...

later, if I want change a certain group, I have ungroup it. …."

https://desk.draw.io/a/tickets/11028

https://user-images.githubusercontent.com/44292306/103177731-46bf8300-487d-11eb-8a64-f7bc7482b293.mp4

**Comment by davidjgraph** [comment]
Closing through lack of additional interest.
