### ISSUE TITLE
vss import error

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1708]
Unknown error importing juniper visio stencils

When trying to use the visio stencils provided by Juniper Networks I get "Unknown error" when trying to import
Stencils are located here
https://www.juniper.net/us/en/products-services/icons-stencils/

I actually tried all of them. 2 of them worked but the rest do not

Additional info:
All of the stencils found at https://www.juniper.net/us/en/products-services/icons-stencils/ do not work except the juniper general icons and the juniper srx series. All other .vss files produce either an “unknown error” dialog or just say loading with the spinning icon perpetually. This error is on both desktop and web version. I have tried firefox and chrome, private and incognito and the result is always the same.

https://desk.draw.io/a/tickets/10727

**Comment by ashrafteleb** [comment]
It works now, but it takes a long time
