### ISSUE TITLE
Arrow cannot start or end at the inside portion of a shape

### ISSUE THREAD

**Issue by nsreenath** [jgraph/drawio#171]
There are some case where an arrow has to start or end at the inside portion of a shape.
Currently arrows act as connectors, so it connects the border of a shape to the border of another shape.

For example, if we need an arrow to start from the center of a circle, then it is not possible.

It would be very useful when we embed an image and try to point out something inside the image.

**Comment by alderg** [comment]
Try the exitX/Y and entryX/Y styles.
