### ISSUE TITLE
Lucidchart import fails to translate complex shape on copy/paste

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1712]
https://desk.draw.io/helpdesk/tickets/4761

What it doesn't work is to paste a draw from lucidchart. When I paste the diagrams, it only shows lines and rectangules, without any data inside.

**Comment by ashrafteleb** [comment]
The original ticket is 3 years old and lack details. Can we get the Lucidchart file or tell us which shapes are used in Lucidchart?
