### ISSUE TITLE
Label direction wrong in example vsdx export

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1715]
https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1#R7V1Zd9q%2B0%2F40OYdelGN592WSJmnetPk1SZf0vfNugzdss5hP%2F9cABmyJxCRegIb2BBBG2Jp5RjPPjOQz7tKf3cRq5HwPDdM7YxljdsZ9OWNZlhMU%2FAQt2bIFsZK4bLFj11i1bRqe3Lm5amRWrWPXMJPCgWkYeqkbFRv1MAhMPS20qXEcTouHWaFX%2FNVItU2i4UlXPbL1j2ukzrJVZqVN%2B1fTtZ38l5G4umJN1Yd2HI6D1e%2BdsZy1eCw%2F9tW8r9WFJo5qhNOtJu7qjLuMwzBdvvJnl6YHg5sP2%2Bp7E9Ubm%2FlP4P%2FXOw5H9MPxFcRmkG53uasHdkcPSZrlo2UaePBWb4MwwE8XiyEwoQsGv3NS38MvEX5pztz0GZr7wurd3%2FyTII2zrY%2Fg7d9VB0mqxuk5CBY36J6aJK6eN1%2B7Xt75wEzTbKVN6jgNcVMYp05oh4HqfQvDaHVcksbh0LwMvTBeXAHHLB74Ewt3ttVuybqpwy8trxkutDCuSTiO9VUTt9JTNbbN1cgK5GCjtZAxeszQN%2FFV4kNi01NTd1LsXV1psb0%2BbiMn%2FGIlKrrYOEJst8FoMDDPQNzX%2BO95OPbPWNHD53WhxfiVna6vc0u2RUFOHTc1nyJ1cc1TDP6icEujZyJDMCXaeCuixKni%2BvcmZpyasxL0Xh2z1RcElu%2BvBnplbrgVSKYb6KIcOM4WbEXm%2FePM7wePjTpebVrrRkt1GFRCVQXdF0jdlyrLsXbdFwiZXI%2B1caydra3uln47oa%2BNk711G5t0Vtdpum2ImijUpdt8WbcRIpVbpui2XINuix%2B6vVHkbd1WutNtiZDJfTbPJrgJjHrvwhh9esGGo7313FBN2aLquajLpmY1ZcNZip43ZsTlD0XfaPW2oudC6ELTFUIoN3c%2FQcfvRmm9Ot6SLSd1XGlRxxEZOTwlujHETd9gVH8PgtOwHJzc5qjuCrB2utA0w7BlFrYswfO2ldh8VtUwlMUhmLLB08QhsxonitVsBGIpRqJDVy8%2Fn63xx99hghBIhJEWwTMYjWg8nESgNZk%2BcULooXc5t45R4bkcyFnuIgotqjsZVr44U77GBlTV5d1TaGUtX4f49U2Y1Bmzw5gfkcHoDX6rDQwI9ZkbAMJobI5juI4AEGJ7QTa1AA1XoftpER%2BRjMCyxS03aHlD78Eb6VP85ctP%2BWf4TLXy8bjNrUAzHCruJLGIO7FV3JEh7X%2F47TwehQP8%2FIgbmF%2BeBl%2BB9jtbB5l%2BH88%2FvUmg321tAEryf3sIdA8m6VBFLAhSyZdQ2DaFvGe8XZlqPSL3ghJsow6jbUSG27fxcDzVwZ72frl2vR7EuXLJX100reZILnkQYptKvmesXVXJUUHJJaE0o%2B8XUZcGX5Oxk%2FXO7EATWrz66o%2FQxT3uFK8olcS2BNfqWyXJrU%2BjmjDJGP1upIOffUUI9RUkqEm0TORZ7gzkTIy1AP%2Bo0Fg84BthkG61Lx%2F1QEYpIUYmEdMUCbsr43fks0IT7nieKd6aPPgOJw9K8vUK3lpTFw47%2Fw3akqYD3xuYjp31fnnu29y1K9O3xhDo%2FuvuGmo19ZcD8V3cz%2Fa8tU9E3CnQeIqXxncItAqsxF72cC9qYsPh80USv89gZ2fV8MOMXXxdZrz6pYMTH9uaeyLt4K%2Fqd08qJec9z40S83UTRzgodVgwqUxe8zxpwGj2i63DfpGkwiNwQe7MNiKgFUw8NU1hYpkYNpx0NtEhXXBDDCIegbQ4WrGZuHNVWxwA2huBOBfnKlycCV9gPDGmkiW8FsPruXaAX3umBV3BsLq66p2vmlPA20WCpeMG9s8F%2BD7zCzcnxcoYwiEcJ9UjFY6UCi1RIzUlFpIGgMmc0adTOwFex1O9zMDPA0DVV%2Fw5Y2kjbQYtLsDaj3xtMjxMIfF8PTISmbIVoeCmMeCQrMD75psT8b8pdDjXwLxSWUwtUA3lLH7ZA2DFXR7A0UpU7lCiJN9wWBO6XErOSQzf2nTOkUTBT5gu%2FOnIyKDu0x3PTR0mjmQO84k5Hqhz%2FHz98zCnCo6vaT7niflcElqcz7kKJQJHSODsQ%2Bvns0DBjnQYMObnU0qUWuBQJckkArT8%2BgtXZVoGIGYSh9k4hZRp73I40Y%2BxboBV5DIKJK7fIvPP1Vw7cIw4oETenNghDsgA%2BbedjjIX5oferWm%2FV9N3a%2FSuzFcNmo5EQtOVdjWdDKxr0XRKjmvje5KqflD5r1zNC2XUHZLzHBll%2FzcYguH%2F9kwI66hzV1IZDTKioaGp%2FBVXIViufwGZSARi%2B1K65Xitvqgqj6C2oSA2MAvQ%2BVdZkPtIXD%2BkgmogBjXGxnJkOA4ZsMFAy4BdfAZ%2F69rB480yX%2Fr4zygK5wuP62EWvC0vdmGlGcxkj%2F9WXkxROi1j4qoE6Y2vGD0GeoWnJKz3EHftcyL%2FUWrwDsnxXIeSq8IxdEmMiXmCMbdIlAqapogxnoz2T0Gt9wk8ecridL7DSnWe5AIeQDlgts6seADJrGdwDqKJD2sbw8F8ptkLb%2BDed46SfpHZcrEKI7Q4K%2FN7LlQ%2FRRBQVqnzHa5d4kma4LcV%2Ba650PObsXaU5ItA6rnUpp43VET%2FIvfSZxi%2BqOwiVymOXP36QTE1PG3Be5cwIQmEZ82CIuM%2FhGSPmqgRSeQo7fE0fEPZ8mOaICjpbqHLeIyMpM%2Fx2wCKsLxsBofewemaXgzEZaKFQaDBitfeoz95gTI5anaD5DMRRyn%2BaWyCEU4zSN4HJwIl%2BhU6jH4FMvq9MebGJILaxd6v6L0BQzeOVG6Q11outanlDcXMaLeWUzJYb9Tytbez2z%2BqouWUmFnqMGMlkDHzjaNDxPz9tPwgoVhDhXiGVPymvCChSpgcGCX%2F3VATZ21MXthn5s16WWHwtgZHoAxO3vbO7BFblA3LlMZ8CSAiXUSuAkDiKz3Vl3gSyDj7D7BNP6zFqqk7bEc0n5BydzVwNUCI9JFom%2BIwDRGuQpUY%2FF8GEbFlkbCW1%2F5AKpnL9ea7DQCJjMT%2Fg72jft3%2BOC34EFwtLcIQm0JPlUD8H0YPIlbnCMo70FOhtxoRREb017Am%2BGKYTRNIdHwbz04cSrQVbo3NRCIZrD98hfFOVdiwaKjFgYGfF7vg%2BYk%2BsD3jxIdfYskVCYiG1lqGnwzMHx7x%2B%2FvIiPHTHyjzuXaDExtyovqGkuteb%2BNb%2B5CTgfv%2Fw454l9Zi6cc1DPkUh4f6iQ86NikVs061jDoZmz8aY1h98xf0fZ5NY3%2BkZp5un9iwc8VB5yihOuKaGnQyVv8DaSF7OshsmEyHbprFkEw1HeDH5%2BlkBGaHpEsOY70TJ9cjFJ4rRgSIoW1V15T7KpLRNjHeJ86Pi5Rad7HDZZMiZUU5eD0j%2FOd3vEilXj2fsRdfYO%2FAaTpzVEBRNPFtBypzezdaVPOOyy0VwnLE7vkMbS5uikQXmyp9PyIoUGrd8zxGJ1Agg%2BsHY%2Bjqptu7SqfJMSaKZIZyj4g2tbyheu89Vzt1mivKVbq4d36HKVGJDHzvrcWev7f32NI%2Fntj%2BfBJBCiFEWfPQVNZIopVfL2stDHdSGGdxNIZ7e12Ay%2Fl55TRCUYeOrxTWvuSfl2s2sOsYUDvy3MD8nF8Q9LQAukD2dA%2BMhz92hilsXjoOgxgmdw%2B2jPn5BRTDT00ziyMn0LeWxix%2Fl1gxs7isHTUkB%2BFNg0xqykZWMq9sUwG9RAb0h6dbz6BbYTaMrQRO3UnGsJGUDbp1ByVKT%2FMMSrqBiPjuhyegXhxi61Gv8sIImZFa1C3akvxD061b2Ios0B1rsLRXwWKVwBiCl1vgzn%2BGA1C2R2C2dCO1h73CPpjHqmF8TfZL5pnXFYxvSsE%2ByilezmWVtgvK18W8OwtM9FRfDkuqQvD8wzItlcggrgykNwuV7KpGqX7UbLwi1T6z9VjvAfj%2BQqiSkBsshJKq8FH%2Fsoz5Pq9sHpJUym4wDNff%2BlyR68I1k28T14DMW7nfQmk5VGE1PuqcnKEs6%2BhyX3iJJMwuh2ky8XtfEqNenr2dOzAjnsi%2BUqs8Grt9Z5UlGRu7tln5vzVwBSsHb36oKQ5sgkULDk7qJMgPxuBxud3Ja3PKZFhVk1buSCiLtT6DJpNcm7BYDGgFESH1g4jkPitMPThjxTLOBEq%2BvanErkwjoj5QViHIyzMk693E31qtWOpIkBorVJRJZujemmERWNnIwO2j2E2CwDykYsUmEKeUy%2BeEqrelrgVxJHvyZGiDcWiGU%2BDwY80JnEnmHqYQahIBYogSRonpL%2FYxEzhJ4cV8e5dWJLIf9%2FFhAzemC5WlyHF9iZTi%2Fjax3DFsb%2FhCxzXaSJIyYYGVvghhEfYhQrI%2BT0QgtljlZNqot%2BGX7MdqfGBysyN0SYSIKsJ9EUl0q7zYbY143G%2FhzIcibLZUEMsl64rU5xGPVUISOU7J77uwtyoQHSNGKvTcWJZCJkkWCc7saZidvHHmy%2FQiokqzBduskMzMfZponjXQFjerdiPbmpjT9DAlUpM85LKHgjgB9XkJ8RLDszyiJGQbc2AVWqXSh42ssuqQIaSI%2BL5CSHFvB5bSsfJSx%2FXZSIVkdCQo5Lmz9fgwEVmfjeQIyppjFcqot2Ekq9wY4wOTNPeiyDoj7LfUgEiiW%2By3toNHku%2F55hjawLMzG3A5iwI%2FGziHtIasgdmSXMmHZ8uXQ8vmpssPvuet0yXp%2BSOBRtvtP1%2BSPSsv9lwjQFvZXPS1ZPpB7RaqUHYL7XIndIVkg76N%2FEgzexdxdpTJ9XKxCKKt5mwqta4cRPnIYWk8pZyky9ucKiTTcaENQjvufbWm0VGqPHEDL1ls9QZe6%2F1IPtR%2BrfZ4%2Fib1vonbxlcXEsll3NuTOEh7f5Oa1yu3pPfEbi0ix%2FclRVFYURIkmbakrUEMkOxACxjg2QIK%2BgyzXtL81jsoNwQHyvagTdzFq7q8SBrhzyAYDrPeb3M0OkY80FY2Sx0CggzPH1wriMzhHBa6qdM4mwaDA2XOaorOJSI6F16jzRoLztfLMNuNzk%2Bg0B1xpb2lBW7tX%2B0dj5NMKi%2B2w5chhnITT8ufZqE5gi1MEsvXB1p0SFtdNcCXlRYpsDzTRzyLLaSsSBwWT5uA7KQU4xQAyXNlELG4ScQgEkQexPh2uqykH0gu6ofYHDpJ7uDcySxvatqLExw5ge%2Bnh7T7XxvVi4rAFXK%2FqE18Vtmq5QOftCpDriTEt2Z7iZv8yEpRHxqriFlvObkl%2FbtkMh56kyH4r958ZM5G2uC08YjK3ooIyQNsJQWBF%2BWqdyqrBY2ok1qMU0CjVKTEJVbuszwrywLDQ%2FrnjdVqSFTKuiHiaHOjGzkj0gQ2SbLlVtccLCIfdlSJbFsbW%2F5pz5VSOdOBw%2Fbt4W8Tmp2UZJwANGXC30EsnuCkDTrfuMMFdLy9AB%2BVfoRjtq14bUjFb%2BMQtqPZHB6rkfM9NEw44n8%3D

**Comment by ashrafteleb** [comment]
It looks OK in online Visio
<img width="1635" alt="export from visio online" src="https://user-images.githubusercontent.com/24944765/103219631-3eeaf780-48ec-11eb-9f2c-55449e17dbff.png">
