### ISSUE TITLE
Custom style on rack to scale units, rather than add them

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1716]
"We are doing drawings on large pages using A1 paper size. The rack containers seem more suited for standard Letter sized paper. I can stretch out the container, but it doesn't adjust the rack spaces in scale. Instead it just adds WAY more spaces than actually exist. Is there a way to expand the rack UNIT spacing also to scale with the overall rack container? "

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/drawio/YnNZjrxTLsk

**Comment by egrimate** [comment]
Changeable rack unit size will be in next release
