### ISSUE TITLE
URI Malformed

### ISSUE THREAD

**Issue by dawsonh2002** [jgraph/drawio#1724]
* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Tab _company_ just crashed and it can't be recovered.  Any copies made or recoveries result in URI Malformed.
Version history results in URI Malformed.
Was just moving display elements around.  Nothing profound.

**To Reproduce**
1. Go to [here](https://drive.google.com/file/d/1931joGDiv6Ok0va27PGedZrDXWmeAaPO/view?usp=sharing)

**Expected behavior**
Tab _company_ just crashed and it can't be recovered.  Any copies made or recoveries result in URI Malformed.
Version history results in URI Malformed.
Was just moving display elements around.  Nothing profound.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome
 - Version Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by ashrafteleb** [comment]
We have recovered the file for you and we are investigating why it got corrupted

[diagram_fixed.xml.zip](https://github.com/jgraph/drawio/files/5788199/diagram_fixed.xml.zip)

**Comment by alderg** [comment]
There was a bug in the compression library. This will be fixed in the next release.
