### ISSUE TITLE
Save diagram to private ftp/sftp server 

### ISSUE THREAD

**Issue by KrzysztofI** [jgraph/drawio#1726]
* [* ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ *] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [_No_]

**Describe the solution you'd like**
_As a user I want to have possibility to save diagram to my private server via ftp or sftp with folder pick like for Google Drive using credentials which I fill in dialog box. Best credentials and folder saved as cookie._ 

**Describe alternatives you've considered**
_Use native cloud in my case cloud of Synology server but honestly sftp is much more universal._

**Additional context**
_N/A_

**Comment by davidjgraph** [comment]
This would require an ftp client in JavaScript. I don't want to see that added to the project, unfortunately. If you wanted to fork and add one, that's the best route.

Webdav is possible, https://github.com/jgraph/drawio-integration/tree/master/webdav.
