### ISSUE TITLE
Renaming when saved on Trello

### ISSUE THREAD

**Issue by omarchehab98** [jgraph/drawio#173]
# Expected
When connected to Trello, renaming the project deletes the file on Trello and uploads it with the new name.

# Actual
When connected to a Trello, renaming the project causes a spinner to appear indefinitely.

Network does not make any HTTP requests after the rename is requested by the user.

**Comment by alderg** [comment]
Thanks for the report. Renaming will be disabled. (PS: We're moving to a Power Up for the Trello integration soon.)
