### ISSUE TITLE
Review keyboard shortcuts clashing with system shortcuts

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1730]
e.g. cmd+m, cmd+h on mac

**Comment by katedd** [comment]
I have the same issue, so I am requesting that this be reopened. When I use the Alt+Tab shortcut to select parent, it triggers the system shortcut instead and switches between open windows. I don't see any other way to select parents other than the shortcut, and the shortcut is not working for me.

**Comment by alderg** [comment]
We'll add Alt+Shift+P to select parent in the next release.

**Comment by Yokissa** [comment]
Encountered the same issue, found that using program specific hotkey mappings provided by certain mouse softwares a working workaround before the new release. I made a profile for drawio desktop and set the side button to Alt + Tab in Logi Options+, it's now working as expected.
