### ISSUE TITLE
Make custom library fixed in draw.io online and desktop

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1733]
* Is there any possibility to put a customized library with my own shapes to the left shape bar?
Every time I create a new diagram I have to add my customized library to the shape bar.

* Voting for this feature as well, since I am getting tired a bit from constantly loading up libraries (although it's fast) but I have to turn off my PC from time to time, or close the draw.io for desktop and reloading the libraries each and every time is becoming a burden. Especially if you have tens of custom libraries (so you don't have to search or scroll through the shapes every time to find the specific one you are looking for).

**Comment by DavidBDiligence** [comment]
I'm new to Diagrams.net.  It looks like if I open a library and refresh the browser, then the library is forgotten and has to be opened again.  Is that expected behavior?
