### ISSUE TITLE
expose Object ID in the properties pane in the Web UI

### ISSUE THREAD

**Issue by hellt** [jgraph/drawio#1741]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Hello,
It would be nice if the object ID would have been exposed in the properties pane of the selected object.
Object IDs are used in some plugins that work with diagrams.net, such as a flowchart plugin for Grafana solution. The plugin dynamically changes the attributes of the objects based on the telemetry data collected, and it uses object ID to select the right object - https://algenty.github.io/flowcharting-repository/STARTED.html#flowchart-definition

It would be way nicer, if we would have been able to access those IDs in the web ui of the drawio web interface.

**Comment by ashrafteleb** [comment]
It will be available in the next release
