### ISSUE TITLE
Adding labels to edges with transparent background color without label crossing the edge

### ISSUE THREAD

**Issue by ashrafteleb** [jgraph/drawio#1743]
Adding labels to edges with transparent background color without label crossing the edge.

Currently, this can be done approximately with using white background label color but it is not working when the edge fall on non-white background

**Comment by cvmocanu** [comment]
+1

The bug seems to be like this:
* double click and select the text of a label
* choose for background color transparent (the actual value changes to `none`)

Expected behavior: the background is transparent
Actual behavior: the background color changes to `FFFFFF` (white).

**Comment by iDoka** [comment]
Found workaroud here: https://github.com/jgraph/drawio/issues/2397

> Press escape and set the label background to transparent with the cell (not the text) selected. We're aware of the suboptimal UX with the two background colors for the cell and the selected text and are working on a fix.
