### ISSUE TITLE
Draw.io while embedding a diagram saved on google drive, now asks for access to all files in google drive

### ISSUE THREAD

**Issue by kaushr** [jgraph/drawio#1744]
### Preflight Checklist

* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**

**Expected behavior**
Draw.io should only need access to the draw.io diagram files stored on google drive and not broad access to all the files.

**Screenshots**
![image](https://user-images.githubusercontent.com/1352018/103712369-7e5db780-4f6e-11eb-92dc-8e58f35e90a8.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kaushr** [comment]
This seems to be a new behavior implemented in the last few weeks.

**Comment by davidjgraph** [comment]
This is the viewer. The viewer does require read access to all files. Where did you come from before you saw this?

**Comment by ashrafteleb** [comment]
This is the standard read-only access we need to display your diagrams. We haven't changed the required permission for a long time.

https://developers.google.com/identity/protocols/oauth2/scopes#drive
`https://www.googleapis.com/auth/drive.readonly | See and download all your Google Drive files`
