### ISSUE TITLE
embed draw.io doesn't discard the changes made.

### ISSUE THREAD

**Issue by rhalp10** [jgraph/drawio#1745]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When the user click the `Exit` button if new content/ change are made in the diagram, it prompt confirmation if you want to choose `Discard Changes` or `Cancel` to save your diagram. then if you choose `Discard Changes` the png sample still returning with the changes that you made.

**To Reproduce**
1. Go to 'https://github.com/jgraph/drawio-integration' download this.
2. Open  '[javascript.html](https://github.com/jgraph/drawio-integration/blob/master/javascript.html)' on the browser.
3. Add a new shape to the diagram to make changes.
4. Click `Exit` and `Discard Changes`.

**Expected behavior**
Discard changes of digram and it should return the PNG/SVG with the last saved the diagram.

**Screenshots**

https://user-images.githubusercontent.com/13925864/103772838-18a02700-5065-11eb-8315-970a34706a05.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 20H2 (OS Build 19042.685)
 - Browser Chrome 
 - Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by alderg** [comment]
Fixed. A related bug in diagrams.net will be fixed in the next release. Thanks for the report!
