### ISSUE TITLE
Drawio don't show font in mediaWiki

### ISSUE THREAD

**Issue by Juju-bln** [jgraph/drawio#1746]
I installed DrawIo in my MediaWiki and want to creat a drawing.

Following issue is happend:

I edit the soruce code of my wiki page with `{{#drawio:XY}}` and save the page.
Now i can open the drawio editor without issues.
I can also draw with them and editing everything i want.

But if i want to create something with font and i save it after creating, the font doesent exist in the normal user view...
If i reopen the editor I see the font...

This is what i see in the editor:
![image](https://user-images.githubusercontent.com/73852205/103796653-c8ff3280-5047-11eb-9680-b80a543d7fc2.png)

This is what I see on the website after saving:
![image](https://user-images.githubusercontent.com/73852205/103796781-ec29e200-5047-11eb-8488-fd429b9b6c12.png)

Any Idea? 

Version: 14.1.8.

**Comment by davidjgraph** [comment]
We're not the authors of that plugin, sorry.
