### ISSUE TITLE
Rectangle with 2 Rounded Corners

### ISSUE THREAD

**Issue by eightbit** [jgraph/drawio#1747]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Need additional shape for UX design

**Describe the solution you'd like**
Rounded Rectangle with top 2 corners rounded.

**Describe alternatives you've considered**
Attempted to edit XML of 3 corner rounded rectangle and reimport:
**change shape=mxgraph.basic.three_corner_round_rect** to **shape=mxgraph.basic.two_corner_round_rect**

Imported SVG not very flexible.

**Additional context**

![rect_roundedTop](https://user-images.githubusercontent.com/5913748/103822264-61d88280-5035-11eb-81c8-cdb235bb8a92.png)

**Comment by egrimate** [comment]
There is a shape called Partial Rectangle in the Basic group of shapes. In the properties window, you can set up various parts of it. In this case, you need to set Top Left Style and Top Right Style to Rounded.

**Comment by eightbit** [comment]
Thanks!

**Comment by wabiloo** [comment]
I don't see these options in the properties window...  Has something changed since 2022?
![Screenshot 2024-11-21 at 10 18 07](https://github.com/user-attachments/assets/782deb85-9d45-4231-81c1-da300672add7)

**Comment by alderg** [comment]
Check if the shape is a partial rectangle under Edit Style:

<img width="470" alt="Screenshot 2024-11-21 at 11 19 35" src="https://github.com/user-attachments/assets/dd2b9409-c2d9-4092-8451-ea29e812fa2c">

**Comment by wabiloo** [comment]
It is
![Screenshot 2024-11-21 at 10 21 16](https://github.com/user-attachments/assets/1b61a1a2-711b-4cb5-8116-a21dbd9acde7)

**Comment by alderg** [comment]
What options did you mean?

**Comment by wabiloo** [comment]
I quote a previous response, just before the ticket was closed:

> There is a shape called Partial Rectangle in the Basic group of shapes. In the properties window, you can set up various parts of it. In this case, you need to set **Top Left Style and Top Right Style to Rounded.**

**Comment by Quadrophonia** [comment]
I have looked everywhere for this and cannot find the "Rounded" corners option, even though I am using "Partial Rectangle": 

> In the properties window, you can set up various parts of it. In this case, you need to set Top Left Style and Top Right Style to Rounded.

Can anyone shed any light (sorry for tall screengrab)?

![Image](https://github.com/user-attachments/assets/35f8ee5b-6147-485d-b0d8-db55684fe213)

**Comment by dorronso** [comment]
As @egrimate mentioned, making sure I am using the Partial Rectangle worked for me:

![Image](https://github.com/user-attachments/assets/045ad15f-4282-462b-bba2-6b9e28e9ae3b)

**Comment by Alexanderhyperbeam** [comment]
> Can anyone shed any light (sorry for tall screengrab)?

For those who are still struggling, you must select the correct "partial rectangle" since there are multiple.

<img width="490" height="180" alt="Image" src="https://github.com/user-attachments/assets/60943110-0c06-4bca-8d04-59699f9bf828" />

For reference, it works with the one that appears as a full rectangle and does not work with the one that looks like an L
