### ISSUE TITLE
"There was an error!" happened while embedding a diagram saved on google drive in Google Docs

### ISSUE THREAD

**Issue by luqiuwen** [jgraph/drawio#1748]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
"There was an error!" happed while embedding a diagram in Google Docs saved on google drive.

**To Reproduce**
1. Go to 'diagram.net for Docs'
2. Click on 'Insert Diagrams'
3. See error

**Expected behavior**
No error happened.

**Screenshots**
![image](https://user-images.githubusercontent.com/1797063/104087012-c50d2380-5286-11eb-9344-0c23b2d9ea78.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 14.1.8

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 87.0.4280.141

**Comment by davidjgraph** [comment]
Should be fixed if you reload. Google just randomly changed the parent frame without notifying anywhere that we can see.
