### ISSUE TITLE
Update GCP Icons

### ISSUE THREAD

**Issue by kumanoryo** [jgraph/drawio#1749]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
The current GCP icon for draw.io is out of date.

> Please pardon our dust. We are currently in the process of updating our product icon set.

The icon set in png and svg format is provided as a zip file, although the page describes it as such.

**Describe the solution you'd like**
I want you to replace it with the new GCP icon.

**Describe alternatives you've considered**
There's no solution.

**Additional context**
[Icon Library for Architecture Diagrams - Google Cloud Platform](https://cloud.google.com/icons/)
- [Google Cloud Official Icons and Solution Architectures (Google Slides)](https://docs.google.com/presentation/d/1aGOTpNdCoO4GXZ2es38ZFO5qPGEAjTtDSVeHaDpwsas/edit?usp=sharing)
- [SVG and PNG Icons DOWNLOAD THE ICONS (ZIP)](https://cloud.google.com/icons/files/google-cloud-icons.zip)

**Comment by davidjgraph** [comment]
The latest set is in use

**Comment by kumanoryo** [comment]
I was able to confirm that it has been updated to the new icon. 
Thank you.

**Comment by KatTraxler-trust** [comment]
Hello.  The default draw.io icons are still significantly out of date.  If you notice, the binary authorization icon is in the official icon set (a service that when GA in 2019), however it is not a default icon in draw.io ?
Spot checking another service, there is no icon for asset inventory in draw.io

**Comment by KatTraxler-trust** [comment]
Hello. The default draw.io icons are still significantly out of date. If you notice, the binary authorization icon is in the official icon set (a service that when GA in 2019), however it is not a default icon in draw.io ?
Spot checking another service, there is no icon for asset inventory in draw.io

**Comment by davidjgraph** [comment]
A new issue is need per iteration, we can't open and close the same ticket over and over.

**Comment by KatTraxler-trust** [comment]
Acknowledged.  Here is a new issue for this: https://github.com/jgraph/drawio/issues/4240
