### ISSUE TITLE
Debbuging project

### ISSUE THREAD

**Issue by cubman** [jgraph/drawio#1750]
Hi. I've downloaded project. Downloaded npm and nodeJs on my computer. I'm using VSCode. To check app in Browser, I used apache-tomcat. Also I noticed, that I can start app as desktop application.

I have two problem - debugging and dynamic JS updating . Could you help me please, how you do it more effectively (without continuesly project rebuilding)? Also, I noticed, that to build application - uses Ant without webpack.

**Comment by postullat** [comment]
Hi guys, why this ticket was closed? I am also wondering how to run JS in DEV mode?
One of the option I found it to concatenate JS in build.xml instead of minifying it. But I would live to hear authors' optinion and how do you guys do JS debugging

**Comment by davidjgraph** [comment]
It's closed because it's too broad to be an issue and discussions didn't exist at the time. If you want to create a discussion on this, please feel free. But note, if the post is not of the standard of a professional software engineer, I'll just ignore it.
