### ISSUE TITLE
Previews in Google Drive picker not always showing

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1758]
Cause not yet known

**Comment by jason-wisnieski** [comment]
This may be related: On my Google Drive, some .drawio files do not show the icon. Those files, to the best of my knowledge, are the ones that are not showing the preview. Some do show a preview but one from very old revisions of the drawing.

**Comment by alizainmerchant** [comment]
I second @jason-wisnieski's comment - the two issues I would like to raise are 

1. I'm seeing some files that don't show previews
2. A few of the files that do show previews show an outdated preview from a previous revision of that document. I noticed that this gets fixed after enough time has passed.

I'd like to keep this ticket open

**Comment by davidjgraph** [comment]
We believe this to have been a quota rate limiting issue, that quota has now been lifted.

**Comment by alizainmerchant** [comment]
@davidjgraph That's great to hear, are you referring to the first issue of previews not showing up or the second issue of previews showing up outdated, or both?

**Comment by alizainmerchant** [comment]
@davidjgraph I've ran through our documents and still notice some documents don't show a preview. I don't believe this issue is resolved.
