### ISSUE TITLE
Save as PNG to OneDrive saves XML

### ISSUE THREAD

**Issue by gadamiak** [jgraph/drawio#1760]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When saving as PNG to OneDrive (in my case OD4B) the output file is an XML as produced by the 'Save As → XML' not an image.

**To Reproduce**
1. Go to 'File → Save as'
2. Choose PNG as format
3. Choose OneDrive as the destination
4. Inspect the output file

**Expected behavior**
The output file is expected to be a valid PNG with an embedded diagram.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 14.1.9

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chromium
 - Version 87.0.4280.66 (Official Build) Arch Linux (64-bit)

**Additional context**

**Comment by mararad** [comment]
Tested in Chrome Version 87.0.4280.141 (Official Build) (64-bit), Win10 Pro and diagrams.net 14.2.2

Diagrams saved as PNG (File > Save as > PNG) into GDrive are opened well but when saved to OneDrive, it reports "this is not a valid bitmap file + we don't support this file format error (when I tried to open them in some image editors)

**Comment by davidjgraph** [comment]
Does it work with 14.2.3?

**Comment by fwsGonzo** [comment]
I think I've had this same issue for a long time, except also for JPEG. I'm on Windows (and Linux sometimes). The file is corrupt but opens fine in every image viewing and editing program that I have.

The only thing that works is export to PDF.

**Comment by mararad** [comment]
I am not able to reproduce this in 14.2.4 

Could @gadamiak attach a file here, please?

**Comment by gadamiak** [comment]
Just tested in 14.2.4 on Chromium Edge on Windows 10 and it's still the same.

Attached are simple drawing originally saved in XML and then saved as PNG to OneDrive for Business (OD4B).
![test.png](https://user-images.githubusercontent.com/344082/104938754-c7226100-59af-11eb-895e-34f6e9106b29.png)
[test.drawio.txt](https://github.com/jgraph/drawio/files/5831292/test.drawio.txt)
