### ISSUE TITLE
GCP shapes are not showing

### ISSUE THREAD

**Issue by aabuniaj** [jgraph/drawio#1761]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
GCP shapes are available to select, but no content in the images itself. More like a placeholder than the images

**To Reproduce**
1. Go to GCP shapes

**Expected behavior**
Loaded my current diagram in draw.io, but the shapes are not displaying. Only placeholders. Also, in the the more shapes section, the images do not show up correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/1190449/104473246-c68e6280-558a-11eb-9c1f-92234e495bd1.png)
![image](https://user-images.githubusercontent.com/1190449/104473280-d0b06100-558a-11eb-8f04-0920797a8e1c.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 14.2.1

**Desktop (please complete the following information):**
 - Browser chrome, safari [latest versions]

**Comment by Johnboy4358** [comment]
I'm experiencing this issue also, as of a few hours ago.

All previously saved version that I could could reload show the same issue..??

**Comment by davidjgraph** [comment]
What version are you using? If not 14.2.2, close all diagrams.net tabs, go to https://app.diagrams.net/clear.html, then reload and try the app again.

**Comment by aabuniaj** [comment]
> What version are you using? If not 14.2.2, close all diagrams.net tabs, go to https://app.diagrams.net/clear.html, then reload and try the app again.

Thank you very much David. That worked!

**Comment by Johnboy4358** [comment]
> What version are you using? If not 14.2.2, close all diagrams.net tabs, go to https://app.diagrams.net/clear.html, then reload and try the app again.

Thank heavens - thought my project was smoked.

Bless you.
