### ISSUE TITLE
Uncaught TypeError: a.charCodeAt is not a function when inserting/editing a PlantUML diagram

### ISSUE THREAD

**Issue by ilya-murzinov** [jgraph/drawio#1763]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Uncaught TypeError: a.charCodeAt is not a function when inserting/editing a PlantUML diagram

**To Reproduce**
1. Go to Arrange -> Insert -> Advanced -> PlantUML...
2. Insert the following PlantUML diagram:
```
package "foo" {
    component bar [
        baz
    ]
}
```
3. See the error
```
app.min.js:10330 Uncaught TypeError: a.charCodeAt is not a function
    at k.open.pako.deflateRaw.to (app.min.js:10330)
    at App.EditorUi.generatePlantUmlImage (app.min.js:10330)
    at app.min.js:10361
    at app.min.js:3575
    at HTMLButtonElement.<anonymous> (app.min.js:292)
```

**Expected behavior**
Diagram inserted

**Screenshots**
<img width="413" alt="Screenshot 2021-01-14 at 10 15 02" src="https://user-images.githubusercontent.com/3704363/104570004-af667800-5651-11eb-8784-1f356ba0782c.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- 14.2.2

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser chrome
 - Version 87

**Comment by mararad** [comment]
Hi,

I tried to reproduce the issue with inserting template PlantUML diagram and it all went well. We are not using the same OS (at my place is Win10) but I suggest the following: 

* close all tabs
*  load https://app.diagrams.net/clear.html
* load diagrams.net again and 
* insert PlantUML

Does this help?

Regards,

**Comment by ilya-murzinov** [comment]
hi @mararad thanks for your reply
tried that, seems that the issue is with my diagram actually, not with any PlantUML..

**Comment by davidjgraph** [comment]
You need to use the method described to ensure you're running version 14.2.3 (in the help menu). That version will fix your issue.

**Comment by ilya-murzinov** [comment]
I updated the description with the diagram I'm trying to insert and the error from the console

**Comment by ilya-murzinov** [comment]
@davidjgraph I can't get 14.2.3 following these steps, I guess I'll wait a bit
