### ISSUE TITLE
Web, Office and other icons not available

### ISSUE THREAD

**Issue by jhonnisp** [jgraph/drawio#1764]
Suddenly many icons became unavailble and it shows colored blocks instead. Found this issue on Web Icons, Office Icons and other groups.
<img width="157" alt="img1" src="https://user-images.githubusercontent.com/77444752/104594912-9ad5b000-5650-11eb-8a0e-cfe10a12f471.PNG">

**Comment by davidjgraph** [comment]
-     close all diagrams.net tabs
-     load https://app.diagrams.net/clear.html
-     load diagrams.net again and test

**Comment by jhonnisp** [comment]
It worked just fine! Tks :)
