### ISSUE TITLE
Update "DC Source 3" to improve resizeability

### ISSUE THREAD

**Issue by friedl-ap** [jgraph/drawio#1765]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
"DC Source 3"does not resize nicely.

**To Reproduce**
1. From the shapes "Electrical / Sources" add the DC Source with "+" and "-".
2. Resize to smaller size
3. "+" and "-" nearly vanish when resized to 20x20.

**Current Shape Code**
```
<shape aspect="variable" h="60" name="DC Source 3" strokewidth="inherit" w="60">
    <connections>
        <constraint name="N" perimeter="0" x="0.5" y="0"/>
        <constraint name="S" perimeter="0" x="0.5" y="1"/>
    </connections>
    <background>
        <ellipse h="60" w="60" x="0" y="0"/>
    </background>
    <foreground>
        <fillstroke/>
        <path>
            <move x="27" y="55"/>
            <line x="33" y="55"/>
            <move x="30" y="2"/>
            <line x="30" y="8"/>
            <move x="27" y="5"/>
            <line x="33" y="5"/>
        </path>
        <stroke/>
    </foreground>
</shape>
```

**Suggested updated Shape Code**
```
<shape aspect="variable" h="60" name="DC Source 3" strokewidth="inherit" w="60">
    <connections>
        <constraint name="N" perimeter="0" x="0.5" y="0"/>
        <constraint name="S" perimeter="0" x="0.5" y="1"/>
    </connections>
    <background>
        <ellipse h="60" w="60" x="0" y="0"/>
    </background>
    <foreground>
        <fillstroke/>
        <path>
            <move x="22" y="55"/>
            <line x="38" y="55"/>
            <move x="30" y="2"/>
            <line x="30" y="18"/>
            <move x="22" y="10"/>
            <line x="38" y="10"/>
        </path>
        <stroke/>
    </foreground>
</shape>
```

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io desktop version 14.1.8

**Desktop (please complete the following information):**
 - OS: Win 10 Enterprise LTSC (1809)

**Additional context**

![dc-source-3](https://user-images.githubusercontent.com/77353865/104617782-26206700-568c-11eb-92b7-34b3493d1051.png)
[dc-source-3.drawio.zip](https://github.com/jgraph/drawio/files/5815602/dc-source-3.drawio.zip)

**Comment by egrimate** [comment]
A new shape will be in next release, which should address this issue
