### ISSUE TITLE
Documentation on UI elements for plugins

### ISSUE THREAD

**Issue by asha892** [jgraph/drawio#1768]
Thank you for all of your work on this awesome tool. Is there any documentation on how to use functions like ui.sidebar.addEntry() , ui.toolbar.addItem(). 

I do see there are example plugins (https://github.com/jgraph/drawio/blob/master/src/main/webapp/plugins/p1.js) that show how some of these functions are used, but i see there are lots of other functions that can be used around ui components. 

It would be great if you can point me to any documentation around this. I am trying to create input text boxes on the sidebar

**Comment by davidjgraph** [comment]
There is no documentation.
