### ISSUE TITLE
Embed mode API for checking modified and event being alerted to modifications

### ISSUE THREAD

**Issue by LucienMP** [jgraph/drawio#1769]
Currently there does not seem any clear way to be alerted to a change in settings or the diagram.
This can be useful when embedding allowing for enabling an external status of "SAVE".

I am requesting having an event sent when the modification flag changes something like as follows;
 * modifiedevent=1 : Enables modified event;  { event: 'modified', message: 'true/false' } happens on first change after a save/load
 * { action: 'modified' } can be sent at any time to return {event: 'modified', message: 'true/false' }

Existing API: https://desk.draw.io/support/solutions/articles/16000042544

**Comment by emashinnova** [comment]
For workaround I have used 'autosave' event for listening of diagram changes.
If autosave is enabled, the editor will send the current XML in an {event: 'autosave'...}.
So I can listen for the first 'autosave' event from draw.io and enable my external functions.

Particular API for cheking modified state will be very useful!
