### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by amitsindha** [jgraph/drawio#177]
Hi,

I have downloaded war file and deployed in tomcat server. It is working fine.

However, if i try to build the war file from /etc/build directory then its failed. Could you please help me to resolve it?

I got below error,

   [jscomp] 0 error(s), 1 warning(s)
   [jscomp] Compiling 1 file(s) with 65 extern(s)
   [jscomp] 0 error(s), 0 warning(s)
   [jscomp] Compiling 14 file(s) with 65 extern(s)
   [jscomp] **Graph-Resources.js:1: ERROR - Parse error. Unterminated string literal**
   [jscomp] mxResources.parse('aboutDrawio=About draw.io
   [jscomp]                   ^
   [jscomp] Graph-Stylesheet.js:1: ERROR - Parse error. Unterminated string literal
   [jscomp] Graph.prototype.defaultThemes[Graph.prototype.defaultThemeName] = mxUtils.parseXml('<mxStylesheet>
   [jscomp]                                                                                    ^
   [jscomp] 2 error(s), 0 warning(s)

**Comment by polystratus** [comment]
@alderg @davidjgraph 
Can you fix this in next release?

**Comment by amitsindha** [comment]
Thank You!!! This problem has been fixed as per "polystratus" suggestion to modify the build.xml file.

**Comment by imidimi** [comment]
We need to replace all Apostrophe's in build.xml? Can you guide bit more.
