### ISSUE TITLE
Importing Visio Stencils

### ISSUE THREAD

**Issue by sidsabharwal** [jgraph/drawio#1770]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When importing stencils from Visio the shape in the stencils are changing alignment, text changed alignment or spacing, line jumps disappeared, some shapes became inverted, line thicknesses changed, etc.
File used is attached.
[Visio.zip](https://github.com/jgraph/drawio/files/5829026/Visio.zip)

**Expected behavior**
The imported stencils should be exactly the same but this is not the case.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Additional context**

**Comment by mararad** [comment]
Reproduced in 14.2.4, Chrome Version 87.0.4280.141 (Official Build) (64-bit) and Win 10 Pro.
vssx was drag&dropped into the editor
(File > Import from > Device and File > Open from > Device didn't show them in the editor at all. It stayed blank. No browser console errors)

**Comment by AlfonsoFR2020** [comment]
Reproduced: importing simple Visio diagrams (up to 10 elements) works just fine, but an older diagram with more elements (10-100), footer, and logo, silently fails to import and only shows a blank stencil on draw.io
