### ISSUE TITLE
option in the advanced export menu to export drawing with grid

### ISSUE THREAD

**Issue by GitMoleo** [jgraph/drawio#1771]
since the old one is closed i'm opening a new issue to this specific request.

> Hi.
> It would be nice to allow exporting drawing to svg / image with grid.
> It is very useful to show specific dimensions, etc.
> Thank you.

Could you add an option for this in the advanced export menu?

_Originally posted by @GitMoleo in https://github.com/jgraph/drawio/issues/34#issuecomment-762470526_

**Comment by mararad** [comment]
Hi,

Export to png/jpeg with grid was already added in 11.1.4. The current version is 14.2.4 so just click File > Export as > png/jpeg and tick the grid option.

What specific dimensions are you referring to, please?

Regards,

**Comment by GitMoleo** [comment]
hi,

that's correct, but there's no option to export it with the grid in the _advanced export options_ menu. That means that if you want to export the diagram with a transparent background AND grid, for example, it won't work.

Regarding the dimensions, I do not know what is meant, the post was not from me.

kind regards :)

**Comment by mararad** [comment]
Hi, when you say it doesn't work, it means that you tested File > Export as > PNG, ticked both Transparent background and Grid and clicked Export, right?

When you open the exported image in some image editor, how do you see it? Is it possible to attach a print screen please?

**Comment by GitMoleo** [comment]
Hi, yeah I just saw that _transparent background_ is an option in _File > Export as > PNG_. It's a bad example, but let's assume I want to export my diagram with **100dpi**, **border width 5**, **height 100** and of course **grid enabled**

**Comment by ashrafteleb** [comment]
An option of "Grid" will be added in the next release
