### ISSUE TITLE
The positon of pasting element by Ctrl + C

### ISSUE THREAD

**Issue by Higurashi-kagome** [jgraph/drawio#1772]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to paste an element by Ctrl + C.

**Describe the solution you'd like**
My puzzling is, I expect that the element is pasted on the position of my cursor, but it's pasted in the same place every time. I think it would be really convenient if can paste an element on the position of the cursor. 

**Describe alternatives you've considered**
If it's not that easy to achieve this, it will be also helpful to make drawio easier to draw a similar element.

**Additional context**

<details>
<summary>Gif</summary>

![paste](https://user-images.githubusercontent.com/51501079/105181877-51f98c00-5b67-11eb-97de-22a52f2003d5.gif)

</details>

Thanks!

**Comment by mararad** [comment]
Hi,

you could try to paste via right mouse click > Paste here. 
If this doesn't help, select the element, hold Ctrl and drag&drop it where you want. This way a copy of the element will be created.

Hope this will help.

Regards,

**Comment by Higurashi-kagome** [comment]
It works, thanks a lot!

**Comment by happyiminjay1** [comment]
I finally found out that there was a solution after using a year. Thanks
