### ISSUE TITLE
Auto-Update Failing

### ISSUE THREAD

**Issue by merrcury** [jgraph/drawio#1774]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Auto-Updating not working. 
**To Reproduce**
1. Simply Selected Update App

**Expected behavior**
Should have updated successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/35988194/105526512-8b1d3200-5d08-11eb-84ff-035ff19e9c71.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- 13.9.9

**Desktop (please complete the following information):**
 - OS: Fedora Workstation 33 (GNOME)
 - Browser: Chromium

**Additional context**

<pre><font color="#2AA1B3">23:16:02.295</font> › Checking for update
<font color="#2AA1B3">23:16:04.939</font> › Found version 14.1.8 (url: draw.io-x86_64-14.1.8.AppImage)
<font color="#2AA1B3">23:16:04.940</font> › @update-available@
 {
  version: <font color="#26A269">&apos;14.1.8&apos;</font>,
  files: [
    {
      url: <font color="#26A269">&apos;draw.io-x86_64-14.1.8.AppImage&apos;</font>,
      sha512: <font color="#26A269">&apos;07XiOgtk/8Ei+DUGOSfG6upAKkByKZOkb4eRsny71I4KCeBx0SEe4Yqcav5VF3II0QUWnNYuu/KjycblbxogiQ==&apos;</font>,
      size: <font color="#A2734C">111778239</font>,
      blockMapSize: <font color="#A2734C">117203</font>
    }
  ],
  path: <font color="#26A269">&apos;draw.io-x86_64-14.1.8.AppImage&apos;</font>,
  sha512: <font color="#26A269">&apos;07XiOgtk/8Ei+DUGOSfG6upAKkByKZOkb4eRsny71I4KCeBx0SEe4Yqcav5VF3II0QUWnNYuu/KjycblbxogiQ==&apos;</font>,
  releaseDate: <font color="#26A269">&apos;2021-01-03T15:50:14.578Z&apos;</font>,
  releaseName: <font color="#26A269">&apos;14.1.8&apos;</font>,
  releaseNotes: <font color="#26A269">&apos;&lt;h2&gt;Releases Notes for 14.1.8&lt;/h2&gt;\n&apos;</font> +
    <font color="#26A269">&apos;&lt;p&gt;&lt;a href=&quot;https://github.com/jgraph/drawio-desktop/releases/download/v14.1.8/draw.io-14.1.8-windows-installer.exe&quot;&gt;Windows Installer&lt;/a&gt;&lt;br&gt;\n&apos;</font> +
    <font color="#26A269">&apos;&lt;a href=&quot;https://github.com/jgraph/drawio-desktop/releases/download/v14.1.8/draw.io-14.1.8-windows-no-installer.exe&quot;&gt;Windows No Installer&lt;/a&gt;&lt;br&gt;\n&apos;</font> +
    <font color="#26A269">&apos;&lt;a href=&quot;https://github.com/jgraph/drawio-desktop/releases/download/v14.1.8/draw.io-14.1.8.dmg&quot;&gt;macOS - Intel&lt;/a&gt;&lt;br&gt;\n&apos;</font> +
    <font color="#26A269">&apos;&lt;a href=&quot;https://github.com/jgraph/drawio-desktop/releases/download/v14.1.8/draw.io-arm64-14.1.8.dmg&quot;&gt;macOS - ARM&lt;/a&gt;&lt;br&gt;\n&apos;</font> +
    <font color="#26A269">&apos;Linux - &lt;a href=&quot;https://github.com/jgraph/drawio-desktop/releases/download/v14.1.8/draw.io-amd64-14.1.8.deb&quot;&gt;deb&lt;/a&gt;, &lt;a href=&quot;https://snapcraft.io/drawio&quot; rel=&quot;nofollow&quot;&gt;snap&lt;/a&gt;, &lt;a href=&quot;https://github.com/jgraph/drawio-desktop/releases/download/v14.1.8/draw.io-x86_64-14.1.8.AppImage&quot;&gt;AppImage&lt;/a&gt; or &lt;a href=&quot;https://github.com/jgraph/drawio-desktop/releases/download/v14.1.8/draw.io-x86_64-14.1.8.rpm&quot;&gt;rpm&lt;/a&gt;&lt;br&gt;\n&apos;</font> +
    <font color="#26A269">&apos;&lt;a href=&quot;https://chrome.google.com/webstore/detail/drawio-desktop/pebppomjfocnoigkeepgbmcifnnlndla/reviews&quot; rel=&quot;nofollow&quot;&gt;Google Chrome OS&lt;/a&gt;&lt;/p&gt;\n&apos;</font> +
    <font color="#26A269">&apos;&lt;p&gt;Windows intel x32 releases are marked -ia32-&lt;/p&gt;\n&apos;</font> +
    <font color="#26A269">&apos;&lt;p&gt;&lt;strong&gt;ChangeLog:&lt;/strong&gt;&lt;/p&gt;\n&apos;</font> +
    <font color="#26A269">&apos;&lt;ul&gt;\n&apos;</font> +
    <font color="#26A269">&apos;&lt;li&gt;Fixes &lt;a class=&quot;issue-link js-issue-link&quot; data-error-text=&quot;Failed to load title&quot; data-id=&quot;777636934&quot; data-permission-text=&quot;Title is private&quot; data-url=&quot;https://github.com/jgraph/drawio-desktop/issues/456&quot; data-hovercard-type=&quot;issue&quot; data-hovercard-url=&quot;/jgraph/drawio-desktop/issues/456/hovercard&quot; href=&quot;https://github.com/jgraph/drawio-desktop/issues/456&quot;&gt;#456&lt;/a&gt;&lt;/li&gt;\n&apos;</font> +
    <font color="#26A269">&apos;&lt;/ul&gt;&apos;</font>
} <b>null</b>
<font color="#2AA1B3">23:16:06.817</font> › Downloading update from draw.io-x86_64-14.1.8.AppImage
<font color="#C01C28">23:16:06.883</font> › Error: Error: ENOENT: no such file or directory, open &apos;/opt/draw.io/resources/app-update.yml&apos;
<font color="#C01C28">23:16:06.886</font> › @error@
 Error: ENOENT: no such file or directory, open &apos;/opt/draw.io/resources/app-update.yml&apos;
(node:13438) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open &apos;/opt/draw.io/resources/app-update.yml&apos;
(node:13438) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13438) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
</pre>

The directory is there in the file system.

**Comment by davidjgraph** [comment]
Manually update to the latest version at https://get.diagrams.net
