### ISSUE TITLE
Allow internal links when exporting to PDF

### ISSUE THREAD

**Issue by Bruneux** [jgraph/drawio#1776]
Hi

When we export a diagram with multiple pages (tabs), only the hyperlink are exported, not the links to other pages of the PDF document. So when we export in PDF, we cannot navigate inside the PDF by using the links.

This kind of links should be functional.

Thanks

**Comment by Bruneux** [comment]
I'm not familiar with the way you do bug management. Why is this request already closed?

**Comment by davidjgraph** [comment]
Did the template show when you created the issue with two items to agree to?

**Comment by Bruneux** [comment]
Now yes, if i would to create a new issue, but i'm not sure that these templates were shown when I create this one.

**Comment by davidjgraph** [comment]
OK, one of the requirements is to search existing issues, like https://github.com/jgraph/drawio/issues?q=pdf+link .

**Comment by Bruneux** [comment]
Ok thanks. it seems that bug #722 is similar. But this one was also marked as closed and will not be fixed.

Can we expect you to fix it?

**Comment by aj-nagrom** [comment]
This feature would be amazing. Please implement <3
