### ISSUE TITLE
Insert Shape broken

### ISSUE THREAD

**Issue by friedl-priv** [jgraph/drawio#1777]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Insert Shape is broken, it does not respect width and height.

**To Reproduce**
1. Go to [https://app.diagrams.net/](https://app.diagrams.net/)
2. Click on '**+**' -> "Shape", take note of the size, it is 100x100.
3. Click "**Apply**"
4. On the right side-bar click to show the "**Arrange**" tab
5. Take note that the inserted shape has been inserted with a size of 120x120, regardless of what has been specified in the xml code inserted. 

Can also be tested with shapes from [https://github.com/jgraph/drawio/tree/master/src/main/webapp/stencils](https://github.com/jgraph/drawio/tree/master/src/main/webapp/stencils), eg. from "**basic.xml**". Take such a shape where 'w' is more like 100 and 'h' is more like 50, eg. the "**Banner**" shape: [https://github.com/jgraph/drawio/blob/26b6e552ed4e8643e434398a1bf894c46122e570/src/main/webapp/stencils/basic.xml#L92](https://github.com/jgraph/drawio/blob/26b6e552ed4e8643e434398a1bf894c46122e570/src/main/webapp/stencils/basic.xml#L92)

**Expected behavior**
The "**Insert Shape**" dialog should honor the given size, otherwise the aspect of the shape is destroyed. 

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 14.2.7 (at time of this report)

**Desktop (please complete the following information):**
 - OS: OpenSuSE
 - Browser Firefox 
 - Version 84.0.2

**Comment by egrimate** [comment]
working as intended

**Comment by friedl-priv** [comment]
How can this be intended?

https://desk.draw.io/support/solutions/articles/16000052874-create-and-edit-complex-custom-shapes specifies:

>  The outer element is \<shape\>, that has the following attributes:
> 
>     name - string, required. This name uniquely identifies the shape. Not currently
>           used in diagrams.net.
>     w,h - optional decimal view bounds. This defines your co-ordinate system for the
>           graphics operations in the shape. The default is 100,100.
>     aspect - optional string with the value of either "variable", the default, or "fixed". 
>            Fixed always renders the shape with the aspect ratio defined by the ratio w/h.
>            Variable causes the ratio to match that of the geometry of the current vertex.
>     strokewidth - optional string containing either an integer or the string "inherit". 
>             Inherit indicates that the strokewidth of the cell will change both when you
>             scale and when you resize the shape. This numeric value defines the
>             multiplier that is applied to the width. The default is "1".

Just take any shape from your own library WITHOUT ANY MODIFICATION, eg. from https://github.com/jgraph/drawio/blob/533720a8c7fd283c68275d81f222e617a34428f6/src/main/webapp/stencils/electrical/electro-mechanical.xml and it get's changed to 120x120 not matter what.

**Comment by friedl-priv** [comment]
Does not make sense to me, really.

**Comment by friedl-priv** [comment]
Either your library or the "Insert Shape" dialog are wrong? Don't you think so?
