### ISSUE TITLE
Electrical Misc: M/F Contact needs --< line end

### ISSUE THREAD

**Issue by RWagner2021** [jgraph/drawio#1778]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I am trying to draw a connection using classic (male) arrow head but cannot find a mating (female) arrow head option. The two symbols would look like --> >--.  

**Describe the solution you'd like**
A new line end (--<) is needed to complement the existing -->.

**Describe alternatives you've considered**
I have searched other types of connectors having the appropriate ending and found nothing.

**Additional context**
This is what I am trying to achieve.
![image](https://user-images.githubusercontent.com/77171238/105864950-71a60f80-5fc0-11eb-910a-f91977913e9f.png)

**Comment by egrimate** [comment]
There will be a Plug-Socket Connector stencil in Electrical\Misc in the next release. It will have appropriate connection points for this purpose.
