### ISSUE TITLE
Box Move on its Own After editing text issue

### ISSUE THREAD

**Issue by ahsanshaokat** [jgraph/drawio#178]
Please take a look at this video:  https://drive.google.com/open?id=1Bg8CUb9HJlwODWahZLWQ9fJQsyestN5B
In this video you will see that sometimes the box moves on it's own after editing text. It doesn't always do this, but it has happened to multiple users. I am having a hard time reproducing the bug,

**Comment by alderg** [comment]
What application (webapp, desktop, confluence server etc), storage provider (google, dropbox etc) operating system, browser and version are you using?

**Comment by ahsanshaokat** [comment]
Hi, Thanks for Quick Reply, am using webapp application, storage using local, version of draw.io 6.3.1.

**Comment by alderg** [comment]
Can you attach a copy of the diagram please?

**Comment by ahsanshaokat** [comment]
Sure please have download it
https://drive.google.com/file/d/1yjTBXlIyBFXyMirFp22-OiTLVLA_roLZ/view?usp=sharing

**Comment by alderg** [comment]
Unfortunately, we, too, are unable to reproduce this (didn't happen even once). If you have the steps to reproduce it, please let us know so we can debug if further.
