### ISSUE TITLE
Hardcoded value for Gitlab url instead of using environment variable

### ISSUE THREAD

**Issue by sag1** [jgraph/drawio#1781]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I am using Gitlab on-premise instance. I configured the global environment variable **DRAWIO_GITLAB_URL="https://gitlab.mycompany"**. When I click on **Share** button under the user name, it redirects me to gitlab.com instead of my instance.

**Authorization and accesing files from my instance are working well.**

**To Reproduce**
1. Go to 'drawio instance'
2. Click on 'Share'
3. It redirects to https://gitlab.com/myuser/myproject/-/project_members instead of https://gitlab.mycompany/myuser/myproject/-/project_members

**Expected behavior**
https://gitlab.mycompany/myuser/myproject/-/project_members

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 14.2.7]

**Additional context**
I searched the file which generates sharing link. I found it here: [GitLabFile.js](https://github.com/jgraph/drawio/blob/master/src/main/webapp/js/diagramly/GitLabFile.js#L23)

This contains **hardcoded value** instead of using the variable **DRAWIO_GITLAB_URL**

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
