### ISSUE TITLE
Problem with diagrams quality in Google slides

### ISSUE THREAD

**Issue by erik0914** [jgraph/drawio#1782]
**Describe the bug**
I can't import in retina mode images in Google slides

**To Reproduce**
1. Go to 'google slides
2. Click on Addons -> diagrams.net -> Insert diagram
3. Insert diagram
4. Scroll down to see the link, modify link scale=auto to scale=2
5. Click on Apply button
6. Click on Addons -> diagrams.net -> Update selected (while selecting the diagram)
7. Diagram refreshes
8. Scroll down to see the link, the link is still scale=auto and the diagram in poor quality

**Expected behavior**
Diagram to be in good quality, scale to be at 2

**draw.io version (In the Help->About menu of the draw.io editor):**
- 14.2.7

**Desktop (please complete the following information):**
 - OS: MACOS Big Sur (11.1)
 - Browser: Chrome
 - Version: Version 88.0.4324.96 (Build officiel) (x86_64)

**Comment by mararad** [comment]
Hi,

could you attach a diagram file so I could test it, please? And attach print screens showing the diagram before and after scaling.
I use Win10 Pro but would like to check if I see the same result as yours.

Regards,

**Comment by erik0914** [comment]
Hi,
The diagram is here
[test.drawio.zip](https://github.com/jgraph/drawio/files/5886603/test.drawio.zip)

Step 1 
Imported diagram, poor quality
<img width="987" alt="Capture d’écran 2021-01-28 à 12 00 42" src="https://user-images.githubusercontent.com/41579045/106129987-1f502480-6161-11eb-9762-4dd0f5272ca3.png">

**Step 2** 
Change scale to 2 and apply
<img width="461" alt="Capture d’écran 2021-01-28 à 12 01 05" src="https://user-images.githubusercontent.com/41579045/106130144-4e669600-6161-11eb-9a0c-091585b6af14.png">

**Step 3**
Refresh diagram
<img width="449" alt="Capture d’écran 2021-01-28 à 12 01 45" src="https://user-images.githubusercontent.com/41579045/106130211-60483900-6161-11eb-90ad-29e01a9273c8.png">

**Step 4** 
Still poor quality
<img width="877" alt="Capture d’écran 2021-01-28 à 12 02 18" src="https://user-images.githubusercontent.com/41579045/106130292-748c3600-6161-11eb-8622-92c83d725b69.png">

**Step 5**
scale=2 isn't there
<img width="537" alt="Capture d’écran 2021-01-28 à 12 02 37" src="https://user-images.githubusercontent.com/41579045/106130445-a1d8e400-6161-11eb-8b55-22995017a83b.png">

Hope you can help
Erik

**Comment by alderg** [comment]
There is a size limit for images we can insert. In this case scale=auto will result in scale=2 due to the size of the image, so the output is the same and larger numbers will result in an error due to the size limit. The only workaround is to export it as a PNG in diagrams.net, then download that PNG and drop it into the slide. However, this will not auto-update when the drive file is changed.

**Comment by erik0914** [comment]
Ok, thank you. 
not exactly the answer I'd have wished but good to know, thank you for your time
