### ISSUE TITLE
Not a diagram file error for draw.io file

### ISSUE THREAD

**Issue by mohoq00** [jgraph/drawio#1783]
**Describe the bug**
I am receiving a Not a Diagram File message when I am trying to open a draw.io file that I was using for a while. Nothing was touched and it just wouldn't open anymore. All other older files have opened just fine. Desktop and browser versions give the same result.

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 14.1.8

**Desktop (please complete the following information):**
 - OS: W10
 - Browser: Chrome

**Comment by davidjgraph** [comment]
Is it possible to zip and attach it? If it's sensitive send it to support@diagrams.net.

**Comment by mohoq00** [comment]
[Hero.zip](https://github.com/jgraph/drawio/files/5888342/Hero.zip)

Here's the attached file. Thanks!

**Comment by mararad** [comment]
Hi, where did you save the diagram initially?

**Comment by mohoq00** [comment]
Thanks everyone, it turns out the file was corrupted the whole time. I was able to recover an earlier version and it opened fine.
