### ISSUE TITLE
Export PNG/SVG/PDF to Gitlab is not working

### ISSUE THREAD

**Issue by sag1** [jgraph/drawio#1784]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I integrated drawio with my company's Gitlab instance. It's working well for most of the functionalities but export is not working while choosing Gitlab as storage. It closes the dialog as it saved without any error message.

**To Reproduce**
1. Go to 'drawio' and choose the drawio file from Gitlab storage.
2. Click on 'File-->Export as --> PNG'
3. Scroll down to 'choose the branch/folder where you want to export'
4. No error as it exports well but no image is stored in Gitlab

**Expected behavior**
An image PNG is to be stored in Gitlab

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 14.2.7]
<img width="664" alt="Capture d’écran 2021-01-28 à 16 58 10" src="https://user-images.githubusercontent.com/19509906/106164546-5f77cd00-618a-11eb-8402-be133a6166ce.png">

<img width="459" alt="Capture d’écran 2021-01-28 à 16 58 19" src="https://user-images.githubusercontent.com/19509906/106164403-35bea600-618a-11eb-9162-b9fa3aa90eb3.png">
<img width="478" alt="Capture d’écran 2021-01-28 à 16 58 28" src="https://user-images.githubusercontent.com/19509906/106164418-3c4d1d80-618a-11eb-899a-cb9fddf36462.png">
<img width="506" alt="Capture d’écran 2021-01-28 à 16 58 44" src="https://user-images.githubusercontent.com/19509906/106164447-41aa6800-618a-11eb-8ac3-1b14b3c4267c.png">

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by pugetc** [comment]
hi @alderg , was this issue fixed and in which version? thanks.

**Comment by davidjgraph** [comment]
Went into 15.5.3.
