### ISSUE TITLE
Textbox's Input text preview in the side-panel or top-panel

### ISSUE THREAD

**Issue by visual901** [jgraph/drawio#1791]
* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Not a problem.

**Describe the solution you'd like**
When creating a new text box of some shape, when you double click it you can edit/enter text inside.
If you zoom out far away then the text inside the box can get pretty small but you can still edit it while zoomed out.
It will be nice to have a real-time preview in a side-panel /top-panel that shows the text inside the currently selected box, while it's selected/editing it, in a properly readable size.
Just like an Excel's cell is showing the text inside at the top of the screen while editing.
This will save the user the trouble of zooming in to the box in order to edit the text inside.

**Describe alternatives you've considered**
Current alternative is to zoom in to see the actual text inside the text box while editing it
![draw](https://user-images.githubusercontent.com/69235572/106478936-6700e400-64b2-11eb-8f27-bd090a8f4b2e.PNG)
.

**Comment by davidjgraph** [comment]
Thanks for the suggestion, unfortunately the amount of work this requires doesn't justify the effort in this case.
