### ISSUE TITLE
Mermaid results don't match those of the mermaid live editor 

### ISSUE THREAD

**Issue by noseshimself** [jgraph/drawio#1794]
### Preflight Checklist

* [X] I do not agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The results of mermaid Gantt chart rendering are not matching the expected result generated by the live editor (and plainly suck).

**To Reproduce**
Feed this to mermaid:

```
sequenceDiagram
    autonumber
    participant E as Denrique
    participant D as Damiano
    participant C as Carol
    participant B as Beast
    participant A as Architect
    C->>D: This is a rather long line needing<br>to be broken up in order to<br>avoid turning the diagram into<br>a mess
    note over E, B: This is just a small note
    C->D: This is a rather long line needing<br>to be broken up in order to<br>avoid turning the diagram into<br>a mess
    note over B, C: This is a rather long line needing<br>to be broken up in order to<br>avoid turning the diagram into<br>a mess
    D->>C: This is a rather long line needing<br>to be broken up in order to<br>avoid turning the diagram into<br>a mess
    C->>D: This is a rather long line needing<br>to be broken up in order to<br>avoid turning the diagram into<br>a mess
    D->>C: This is a rather long line needing<br>to be broken up in order to<br>avoid turning the diagram into<br>a mess
    C->>A: This is a rather long line needing<br>to be broken up in order to<br>avoid turning the diagram into<br>a mess
    A->>C: This is a rather long line needing<br>to be broken up in order to<br>avoid turning the diagram into<br>a mess
    opt nonsense is insufficient insufficient
      loop create more nonsense
        C->>D: This is a rather long line needing<br>to be broken up in order to<br>avoid turning the diagram into<br>a mess
        D->>C: (provides more nonsense)
        C->>A: This is a rather long line needing<br>to be broken up in order to<br>avoid turning the diagram into<br>a mess
        A->>C: This is a rather long line needing<br>to be broken up in order to<br>avoid turning the diagram into<br>a mess
      end
    end
    par prepare assessment schedule
      C->B: Select appropriate modules and<br>systems of interest and<br>lists required abilities
    and prepare start of project
      C->D: Agree on start of on-site assessment process
    end
```
**Expected behavior**
[The output shown here](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgYXV0b251bWJlclxuICAgIHBhcnRpY2lwYW50IEUgYXMgRGVucmlxdWVcbiAgICBwYXJ0aWNpcGFudCBEIGFzIERhbWlhbm9cbiAgICBwYXJ0aWNpcGFudCBDIGFzIENhcm9sXG4gICAgcGFydGljaXBhbnQgQiBhcyBCZWFzdFxuICAgIHBhcnRpY2lwYW50IEEgYXMgQXJjaGl0ZWN0XG4gICAgQy0-PkQ6IFRoaXMgaXMgYSByYXRoZXIgbG9uZyBsaW5lIG5lZWRpbmc8YnI-dG8gYmUgYnJva2VuIHVwIGluIG9yZGVyIHRvPGJyPmF2b2lkIHR1cm5pbmcgdGhlIGRpYWdyYW0gaW50bzxicj5hIG1lc3NcbiAgICBub3RlIG92ZXIgRSwgQjogVGhpcyBpcyBqdXN0IGEgc21hbGwgbm90ZVxuICAgIEMtPkQ6IFRoaXMgaXMgYSByYXRoZXIgbG9uZyBsaW5lIG5lZWRpbmc8YnI-dG8gYmUgYnJva2VuIHVwIGluIG9yZGVyIHRvPGJyPmF2b2lkIHR1cm5pbmcgdGhlIGRpYWdyYW0gaW50bzxicj5hIG1lc3NcbiAgICBub3RlIG92ZXIgQiwgQzogVGhpcyBpcyBhIHJhdGhlciBsb25nIGxpbmUgbmVlZGluZzxicj50byBiZSBicm9rZW4gdXAgaW4gb3JkZXIgdG88YnI-YXZvaWQgdHVybmluZyB0aGUgZGlhZ3JhbSBpbnRvPGJyPmEgbWVzc1xuICAgIEQtPj5DOiBUaGlzIGlzIGEgcmF0aGVyIGxvbmcgbGluZSBuZWVkaW5nPGJyPnRvIGJlIGJyb2tlbiB1cCBpbiBvcmRlciB0bzxicj5hdm9pZCB0dXJuaW5nIHRoZSBkaWFncmFtIGludG88YnI-YSBtZXNzXG4gICAgQy0-PkQ6IFRoaXMgaXMgYSByYXRoZXIgbG9uZyBsaW5lIG5lZWRpbmc8YnI-dG8gYmUgYnJva2VuIHVwIGluIG9yZGVyIHRvPGJyPmF2b2lkIHR1cm5pbmcgdGhlIGRpYWdyYW0gaW50bzxicj5hIG1lc3NcbiAgICBELT4-QzogVGhpcyBpcyBhIHJhdGhlciBsb25nIGxpbmUgbmVlZGluZzxicj50byBiZSBicm9rZW4gdXAgaW4gb3JkZXIgdG88YnI-YXZvaWQgdHVybmluZyB0aGUgZGlhZ3JhbSBpbnRvPGJyPmEgbWVzc1xuICAgIEMtPj5BOiBUaGlzIGlzIGEgcmF0aGVyIGxvbmcgbGluZSBuZWVkaW5nPGJyPnRvIGJlIGJyb2tlbiB1cCBpbiBvcmRlciB0bzxicj5hdm9pZCB0dXJuaW5nIHRoZSBkaWFncmFtIGludG88YnI-YSBtZXNzXG4gICAgQS0-PkM6IFRoaXMgaXMgYSByYXRoZXIgbG9uZyBsaW5lIG5lZWRpbmc8YnI-dG8gYmUgYnJva2VuIHVwIGluIG9yZGVyIHRvPGJyPmF2b2lkIHR1cm5pbmcgdGhlIGRpYWdyYW0gaW50bzxicj5hIG1lc3NcbiAgICBvcHQgbm9uc2Vuc2UgaXMgaW5zdWZmaWNpZW50IGluc3VmZmljaWVudFxuICAgICAgbG9vcCBjcmVhdGUgbW9yZSBub25zZW5zZVxuICAgICAgICBDLT4-RDogVGhpcyBpcyBhIHJhdGhlciBsb25nIGxpbmUgbmVlZGluZzxicj50byBiZSBicm9rZW4gdXAgaW4gb3JkZXIgdG88YnI-YXZvaWQgdHVybmluZyB0aGUgZGlhZ3JhbSBpbnRvPGJyPmEgbWVzc1xuICAgICAgICBELT4-QzogKHByb3ZpZGVzIG1vcmUgbm9uc2Vuc2UpXG4gICAgICAgIEMtPj5BOiBUaGlzIGlzIGEgcmF0aGVyIGxvbmcgbGluZSBuZWVkaW5nPGJyPnRvIGJlIGJyb2tlbiB1cCBpbiBvcmRlciB0bzxicj5hdm9pZCB0dXJuaW5nIHRoZSBkaWFncmFtIGludG88YnI-YSBtZXNzXG4gICAgICAgIEEtPj5DOiBUaGlzIGlzIGEgcmF0aGVyIGxvbmcgbGluZSBuZWVkaW5nPGJyPnRvIGJlIGJyb2tlbiB1cCBpbiBvcmRlciB0bzxicj5hdm9pZCB0dXJuaW5nIHRoZSBkaWFncmFtIGludG88YnI-YSBtZXNzXG4gICAgICBlbmRcbiAgICBlbmRcbiAgICBwYXIgcHJlcGFyZSBhc3Nlc3NtZW50IHNjaGVkdWxlXG4gICAgICBDLT5COiBTZWxlY3QgYXBwcm9wcmlhdGUgbW9kdWxlcyBhbmQ8YnI-c3lzdGVtcyBvZiBpbnRlcmVzdCBhbmQ8YnI-bGlzdHMgcmVxdWlyZWQgYWJpbGl0aWVzXG4gICAgYW5kIHByZXBhcmUgc3RhcnQgb2YgcHJvamVjdFxuICAgICAgQy0-RDogQWdyZWUgb24gc3RhcnQgb2Ygb24tc2l0ZSBhc3Nlc3NtZW50IHByb2Nlc3NcbiAgICBlbmQiLCJtZXJtYWlkIjp7InRoZW1lIjoibmV1dHJhbCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)

![mermaid-diagram-20210201191052](https://user-images.githubusercontent.com/6132793/106500735-7556fc00-64c2-11eb-820b-2238b2fbe7a2.png)

**Screenshots**
This is what I'm getting out of drawio:

![draw io](https://user-images.githubusercontent.com/6132793/106500910-aa634e80-64c2-11eb-94f3-2d34144d0f6a.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 14.2.9

**Desktop (please complete the following information):**
 - OS: any
 - Browser: Chrome, Safari

**Additional context**
This is looking like using some different CSS. I am getting the same result in a pure HTML page including the CDN version of mermaid.min.js without any additional CSS as by using the live editor.

**Comment by ashrafteleb** [comment]
Fixed in the next version. Mermaid updated to 8.10.1
Still color won't be the same as we use a custom style
