### ISSUE TITLE
Updating page fails with console errors

### ISSUE THREAD

**Issue by ggloveswp** [jgraph/drawio#1795]
We are using drawio library through iframe (embed) support. Everything was working fine until version 14.2.9, which once out, it produces console errors by triggering autosave part of the code:
`           else if (msg.event == 'autosave')
           {
            eventcheck=1;
            iframe.contentWindow.postMessage(JSON.stringify({action: 'export',
                                                            format: 'xmlpng', xml: msg.xml, spin: 'Updating page'}), '*');
            localStorage.setItem('.draft-' + name, JSON.stringify({lastModified: new Date(), xml: msg.xml}));
            console.log(localStorage, JSON.stringify({lastModified: new Date(), xml: msg.xml}));
            $('#diagramy_content').val(msg.data);
          }`

**To Reproduce**
1. Embed the latest version
2. Create a new diagram
3. Drag a new object on it

**Expected behavior**
No console errors should occur (autosave related) and "updating page.." message should appear only instantly (once).

**Screenshots**
Here is the perfect working state with a previous version: https://streamable.com/uh5tyd
Here is the issue that started at version 14.2.9: https://streamable.com/ji593l

**draw.io version (In the Help->About menu of the draw.io editor):** 
- draw.io version 14.2.9

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 88.0.4324.104

**Comment by ggloveswp** [comment]
@alderg @davidjgraph embed use, exactly as issue #1378, in case it helps.
Thanks in advance for taking a look at this.

**Comment by alderg** [comment]
What is the actual behaviour and what are the console errors?

**Comment by ggloveswp** [comment]
> What is the actual behaviour and what are the console errors?

Both actual behavior and console errors can be seen in the videocast of the actual behavior, here: https://streamable.com/ji593l

**Comment by alderg** [comment]
Thanks for the report, this will be fixed in the next release. Are you sending in XML that is different that the XML received for the last autosave event that triggers the export?

**Comment by ggloveswp** [comment]
We are handling autosaves using the following IF statements: https://pastebin.com/4QqiD545
