### ISSUE TITLE
Copying settings of block to default block settings should be configurable

### ISSUE THREAD

**Issue by hahyes** [jgraph/drawio#1796]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I discovered that changing for example font size of block is changing default block templates font size. Not only to one used template but to many of them. For example, changing font size of rectangle changed rectangle and diamond default font size. Kinda confusing to be honest.

**Describe the solution you'd like**
I think it's should be able to be disabled or more configurable in configuration JSON. Option to disable this behaviour and another one to limit copying settings to only one template of block.

**Comment by mararad** [comment]
Hi, 

could you attach a video showing this behaviour? Do you see the same font size change in other browsers and Incognito mode? What draw.io version do you see under Help?
