### ISSUE TITLE
Shape with shadow not added to container

### ISSUE THREAD

**Issue by JorisCleVR** [jgraph/drawio#1798]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
A shape which has shadow enabled is not added to a container when hovering over it (the blue highlight is neither depicted)

**To Reproduce**
1. Open a blank page
2. Add a container shape
3. Add a rectangle shape (outside of the container)
4. When you drag the rectangle onto the container it is highlighted in blue and parented when dropped there
5. Add another rectangle shape (outside of the container)
6. In the style of the shape enable shadow
7. 4. When you drag the rectangle onto the container it is NOT highlighted in blue and thus NOT parented when dropped there

**Expected behavior**
I expect a component with shadow as a style to react in the same way as dragging a shape without shadow onto a container

**Screenshots**
The following animated GIF depicts the issue:
![ShadowNotAddedToContainer](https://user-images.githubusercontent.com/7225673/106717853-86a62280-6600-11eb-8660-b2f6d51de70c.gif)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 14.1.8 (also tested in online version)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 88.0.4324.104

**Additional context**
-

**Comment by mararad** [comment]
Reproduced in diagrams.net online 14.2.9. in Chrome Incognito and Win 10 Pro.
The same in desktop 14.1.8 

When the shape is selected and shadow ticked in Format panel > Style, the shape is not parented.
When shadows are ticked under View > Shadows (all shapes get shadows) the rectangle is parented unless the additional shadow is ticked in Format panel > Style tab 

https://user-images.githubusercontent.com/44292306/106747048-ae5ab200-6623-11eb-826a-9d27aef02580.mp4

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
