### ISSUE TITLE
Error OneDrive System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by manuelfink** [jgraph/drawio#180]
I just tried using draw.io with my office.365 / exchange.365 / sharepoint account and get the following error:

> [OneDriveSDK Error] errorType: webRequestFailure, message: graph/me request failed, status code: '403', response text: '{ "error": { "code": "-2147024891, System.UnauthorizedAccessException", "message": "Zugriff verweigert. Sie haben keine Berechtigung, diesen Vorgang auszuführen oder auf diese Ressource zuzugreifen.", "innerError": { "request-id": "34f2dfb5-b20e-4514-bee6-bb79601a1147", "date": "2017-11-27T08:08:51" } } }'

Anyone ideas what causes this?

**Comment by davidjgraph** [comment]
We don't have support for OneDrive for Business that runs on Sharepoint, at this time. I've added a card at https://trello.com/c/HjxEcmYb/283-add-onedrive-for-business-on-sharepoint-support to track it, but I wouldn't expect anything here during, at least, the first half of 2018

**Comment by davidjgraph** [comment]
Sharepoint integration fixed in 9.2.9
