### ISSUE TITLE
Auto updating test element for versioning diagrams

### ISSUE THREAD

**Issue by helmo** [jgraph/drawio#1800]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When a diagram get's exported as png or pdf it's not clear to the viewer which version it is or when it was last modified.
The PDF had metadata for this, but who reads that ... And on paper that's lost.

**Describe the solution you'd like**
It would be nice if we could add a visual text element to the diagram that gets updated automatically.
- a diagram version number (not sure how that would increment though)
- a last modification date
- maybe a git hash if the file is in version control
- 'created with drawio version x'

Such an element could then be placed in a header or footer of the diagram.

**Describe alternatives you've considered**
Manually updating a text element is possible, but easy to forget.

**Additional context**

**Comment by mararad** [comment]
Hi,

the list of supported placeholders can be found here: https://desk.draw.io/support/solutions/articles/16000051979-how-to-work-with-placeholders- 

At the moment the last modified date and version are not supported.

**Comment by helmo** [comment]
Thanks, that helps a bit.
