### ISSUE TITLE
Can't export SVG "Allied Telesis" shapes in SVG

### ISSUE THREAD

**Issue by Nico207** [jgraph/drawio#1801]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I export a diagram to SVG with an "Allied Telesis" SVG shape, this shape is converted to PNG instead of being left in SVG.

**To Reproduce**
1. Go to "More Shapes..."
2. Check "Allied Telesis" in Networking and Apply
3. Add some shapes (Buildings, Computer and Terminals...)
4. Go to File / Export as / SVG...
5. Check "Embed Images" and "Include a copy of my diagram"
6. Export and open the file in Inkscape

**Expected behavior**
A SVG file with no PNG

**Screenshots**
I wish to have this
![image](https://user-images.githubusercontent.com/1179972/107052360-d71eab00-67cd-11eb-986f-40ed7738c63b.png)

An not this
![image](https://user-images.githubusercontent.com/1179972/107052849-6d52d100-67ce-11eb-9abb-a1ea4e58b86b.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version : try with 14.1.8 (desktop) / 13.5.4 (own web server) / 14.2.9 (draw.io website)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Firefox 
 - Version : 85.0.1

**Comment by alderg** [comment]
We're unable to reproduce this. Please attach a copy of the diagram file and the exported SVG.

**Comment by Nico207** [comment]
After some tests, it's seems I can't attribute the problem to Draw.io but to Inkscape [(#9)](https://github.com/iros/patternfills/issues/9) If I try to open the SVG file in LibreOffice or in Firefox, the rendering is good.
This happens only with shapes that are in the format "data:image/svg+xml;base64"

Here is the files
[Untitled Diagram.zip](https://github.com/jgraph/drawio/files/5939391/Untitled.Diagram.zip)
