### ISSUE TITLE
Checkbox texts of sidebar for format stacked on each other 

### ISSUE THREAD

**Issue by CaiqueTora** [jgraph/drawio#1802]
I'm using 14.2.9 drawio version on Firefox 85.0, my OS is a Ubuntu 20.04 with i3-wm

![2021-02-05-180310_299x681_scrot](https://user-images.githubusercontent.com/30985658/107093881-7480db80-67dc-11eb-9e01-038bb1271b1d.png)
![2021-02-05-180305_264x518_scrot](https://user-images.githubusercontent.com/30985658/107093884-75b20880-67dc-11eb-9162-4ff4b63cc907.png)

When I set 140% of zoom on browser the checkbox texts stop stacking

**Comment by mararad** [comment]
Hi, I tried to reproduce this one and I couldn't but I am a Win user.
Tested with:
draw.io 14.3.0 
https://www.diagrams.net/ 
Chrome Version 88.0.4324.150 (Official Build) (64-bit)

Could you update diagrams.net to the latest and test again? Close all tabs, then load https://app.diagrams.net/clear.html and then load diagrams.net again

Do you have the same problem in other browsers/incognito mode?

**Comment by CaiqueTora** [comment]
> Hi, I tried to reproduce this one and I couldn't but I am a Win user.
> Tested with:
> draw.io 14.3.0
> https://www.diagrams.net/
> Chrome Version 88.0.4324.150 (Official Build) (64-bit)
> 
> Could you update diagrams.net to the latest and test again? Close all tabs, then load https://app.diagrams.net/clear.html and then load diagrams.net again
> 
> Do you have the same problem in other browsers/incognito mode?

Oh, I found that the problem is the theme I'm using ([Pop gruvbox](https://github.com/salimundo/Pop-gruvbox)), as checkbox texts don't have their own style, it uses i3-wm theme style, that's all, sorry for not checking it out before

**Comment by mararad** [comment]
No worries, thanks for the update :) I am glad all is good again. Regards,
