### ISSUE TITLE
draw.io for windows has something about ##Memory Leak##

### ISSUE THREAD

**Issue by Su11en** [jgraph/drawio#1803]
system info: windows 7 x64

discovered the draw.io by accident. I think it's a good project.
today, i found a memory leak problem in draw.io.

description: open 3 draw.io to do my work, then close all. there is a draw.io (backgroud process in computer) opening all the way, and increasing consumption of memory.

try to repeat the bug,but fail.

introduce myself,  c++ programmer in China, also learn java now.

To record this bug, i will fix it by myself if i can do.
Of cource, hope you all can fix it as soon. because i am a totally java rookie.

there is a screenshots.
![drawio内存泄漏](https://user-images.githubusercontent.com/59603477/107114287-b9ba1180-689f-11eb-8432-a035cfa098f8.png)

**Comment by Su11en** [comment]
@Gaudenz Alder there is a bug feedback in draw.io,thanks for you watching

**Comment by mararad** [comment]
Hi, 

I would suggest to track this thread here because you might find it useful https://github.com/jgraph/drawio-desktop/issues/431

Regards,
