### ISSUE TITLE
There seems to be another (scamming?) website that is advertising this app...

### ISSUE THREAD

**Issue by derei** [jgraph/drawio#1805]
So, I'm not really sure where to check about the legitimacy of this... i hope is not disrespectful to post it here.

I found this website: https://drawio-app.com which seems to copy the logo and advertise the same app, but with a twist: it asks for money. So, i'm kinda confused of what is going on here...

**Comment by davidjgraph** [comment]
There are many implementations of draw.io to other products. This one is a paid integration to Confluence and Jira, this is completely allowed under the license.
