### ISSUE TITLE
using special characters in save dialog won't throw error

### ISSUE THREAD

**Issue by Stimmenhotel** [jgraph/drawio#1806]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Trying to save a file with special characters won't show an error message, instead is will just not work.

**To Reproduce**
1. Create file
2. Eyport PNG
3. Give it a name with "?"
4. Try to save it

**Expected behavior**
Popup saying "Can't be saved, use name without special characters" or similar.

**Screenshots**
https://user-images.githubusercontent.com/15821524/107240241-fd408700-6a29-11eb-8a7d-16cdde784ccb.mp4

- draw.io version 14.1.8

**Desktop:**
 - OS: Win10
 - Firefox 85.0.1

**Comment by alderg** [comment]
You should be getting an intermediate dialog that looks like this:

<img width="474" alt="Screenshot 2021-02-09 at 12 21 48" src="https://user-images.githubusercontent.com/921200/107356812-91195e00-6ad1-11eb-9e2a-eeac1df638b8.png">

Then the file should be directly downloaded and any special characters should be replaced with a space (Firefox) or underscore (Chrome). What URL are you using the app from?

**Comment by Stimmenhotel** [comment]
I am using the export function of the desktop client. Am 09.02.2021 12:24 schrieb Gaudenz Alder <notifications@github.com>:
You should be getting an intermediate dialog that looks like this:

Then the file should be directly downloaded and any special characters should be replaced with a space (Firefox) or underscore (Chrome). What URL are you using the app from?

**Comment by alderg** [comment]
Please open an issue here: https://github.com/jgraph/drawio-desktop/issues
