### ISSUE TITLE
grid and mm

### ISSUE THREAD

**Issue by gauchl** [jgraph/drawio#1807]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
If I select unit in mm and fix grid to 4, and if I want to draw a square snapped, I get one with 4.1mm x 4.1mm.
![drwawio-grid-mm-1](https://user-images.githubusercontent.com/59143570/107280215-50313300-6a58-11eb-876e-775c86d88ded.PNG)
![drwawio-grid-mm-2](https://user-images.githubusercontent.com/59143570/107280222-52938d00-6a58-11eb-9fe7-a2981a0ede25.PNG)

**To Reproduce**

**Expected behavior**
If I select unit mm and fix grid to 4, I should have a 4mm x 4mm square 

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 14.2.6]

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome]
 - Version [86.0.4240.75]
 - Same trouble on draw.io desktop

**Additional context**

**Comment by gauchl** [comment]
I was thinking to use drawio with my students for flowcharts and for laser draws. But I will not since the dimensions of mm grid are not respected in the drawio. Pity !

**Comment by davidjgraph** [comment]
That adds nothing to the discussion. Please limit comments to factual information.
