### ISSUE TITLE
When exporting to SVG, property and value are not output.

### ISSUE THREAD

**Issue by keizo-aoyama** [jgraph/drawio#1808]
### Preflight Checklist
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When exporting to SVG, property and value are not output.

**To Reproduce**
1. Draw a shape.
2. Select the shape and click "Edit Data".
3. Set the property name and click "Add Property".
4. Set the value for the created property and click "Apply".
5. From the "File" menu, select "Export" as and SVG to export to my local drive.
6. Please open the saved SVG file by text editor.
7. The Property and value you should have created are not included in SVG.

**Expected behavior**
I expected the property and value to be output to the SVG file.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 14.2.9

**Desktop (please complete the following information):**
 - OS: windows10
 - Browser :Chrome 
 - Version 88.0.4324.146

**Comment by alderg** [comment]
This is the expected behaviour. The shape properties are not written to the SVG output, they are stored within the mxfile data in the content attribute of the SVG element.
