### ISSUE TITLE
[Feature Request] Microsoft Office365 Teams Support / OneDrive for Business

### ISSUE THREAD

**Issue by manuelfink** [jgraph/drawio#181]
I just tried using draw.io with Microsoft Office 365 Teams, which uses sharepoint 4 business in background. It seems not to be supported? I guess it would be really helpful to integrate drawio with teams to be able ...

1. to save/open files from drawio to/from teams
2. open files from teams automatically in drawio (teams application)
3. collaborate in realtime on drawio charts on teams storage

I guess more and more companies will move to office365 in the cloud and therefore this will be an great enhancement.

**Comment by davidjgraph** [comment]
We support OneDrive for Business, just not connected to Sharepoint. That's not technically possible at this point without changes from MS.

**Comment by ronvanpol** [comment]
Are you guys reaching out to MS for the necessary changes? Is there any chance we can expect support for OneDrive for Business using team sites?

**Comment by davidjgraph** [comment]
What is "team sites"?

**Comment by ronvanpol** [comment]
Sharepoint sites (see image 1). From draw.io I can access my ODB which lists my personal files. I can also browse through the company (sharepoint) team sites. But when trying to save in that location I get the error "The resource cannot be found". The goal is to store documents in a location that is accessible for all users from our company.

![image](https://user-images.githubusercontent.com/5981708/36538970-828af44a-17d5-11e8-84d8-7f27658aea3d.png)

![image](https://user-images.githubusercontent.com/5981708/36539274-8cc16df8-17d6-11e8-9c03-b2c05f9fea16.png)

**Comment by davidjgraph** [comment]
And is that a self-hosted sharepoint, or Microsoft hosted one?

**Comment by ronvanpol** [comment]
Microsoft hosted as part of our Office 365 subscription

**Comment by davidjgraph** [comment]
Sharepoint integration fixed in 9.2.9
