### ISSUE TITLE
Why in the world, the grid has not the classical length of 10 lines?

### ISSUE THREAD

**Issue by KacimiBadr** [jgraph/drawio#1810]
* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

 I'm very frustrated with the grid size, why in the world it does have 4 squares/ thin lines? Even when you try to change the mm's.

Solution:
I would like to change the number of squares between 2 black lines.

Alternative:
Set it to 10 blocks or quares between black lines or 5 blocks. 

**Additional context**
I tried to make an x-axis, and was not able to put the numbers properly. The lines are like this 0-4-8-12....

**Comment by mararad** [comment]
Hi,

There is a discussion already opened here: https://github.com/jgraph/drawio/issues/1249 so feel to comment there.

Regards,

**Comment by mararad** [comment]
Duplicated https://github.com/jgraph/drawio/issues/1249
