### ISSUE TITLE
Make shape picker configurable based on source shape

### ISSUE THREAD

**Issue by alderg** [jgraph/drawio#1812]
Add pre-defined and custom shape picker configuration based on source shape.

<img width="268" alt="Screenshot 2021-07-22 at 12 40 53" src="https://user-images.githubusercontent.com/1761087/126633652-0e2e2645-2b3a-4e4f-b558-eb8aa1c2d812.png">

**Comment by Avlakan** [comment]
It will be wery usefuul to set scratchpad shapes into shape picker menu.

**Comment by BorjaLL** [comment]
how does this work?
I'm using the BPMN 2.0 shape library and only the default shapes are available in the shape picker

**Comment by davidjgraph** [comment]
It doesn't. Closing the issue marks it as completed, even when it's declined.
