### ISSUE TITLE
Changes when exporting to .pdf

### ISSUE THREAD

**Issue by psarumo** [jgraph/drawio#1813]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
In the web version, when I export a flowchart as PDF, the rectangles change their shape.

**To Reproduce**
1. Go to 'Flowchart' and add the 'Document' piece to the diagram
2. Go to 'File/Export as/PDF...'
2. Click on 'Export'
3. Select 'Device'
4. Open the saved document

**Expected behavior**
I would expect to obtain this diagram
![image](https://user-images.githubusercontent.com/47534769/107652599-0d9e6f00-6c81-11eb-8742-bc13b1a50b6f.png)

But the exported pdf is like this:
![image](https://user-images.githubusercontent.com/47534769/107652684-20b13f00-6c81-11eb-87bc-b8613384538f.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 14.3.1, web version

**Desktop (please complete the following information):**
 - Browser [mozilla firefox]
 - Version [81.0.2]

**Comment by alderg** [comment]
Could you attach the test file please?

**Comment by psarumo** [comment]
[Test.zip](https://github.com/jgraph/drawio/files/5967191/Test.zip)

**Comment by alderg** [comment]
When I open this .drawio file, it looks like this:

![Screenshot 2021-02-11 at 18 49 41](https://user-images.githubusercontent.com/921200/107676875-e902c100-6c99-11eb-81be-fee3759a2727.png)

Test with web version in Firefox and Chrome on macOS.

What operating system are you using? Do you have any extensions installed?

**Comment by psarumo** [comment]
I am using windows 10 and I don't have extensions. When I open the diagram in Chrome I see the same image as you, but when I reopen it in Firefox (where I don't have the last version) I still see the rectangle.

**Comment by alderg** [comment]
This seems to be a bug in older versions of Firefox. I'd recommend updating to the latest version.

**Comment by psarumo** [comment]
Ok, thank you for your help!

**Comment by alderg** [comment]
We'll add a fix for older versions of Firefox in the next release.
