### ISSUE TITLE
Gliffy import failing

### ISSUE THREAD

**Issue by lokeller** [jgraph/drawio#1814]
**Describe the bug**

When trying to import a gliffy diagram in the latest docker release (44bddc908f05) I get an error 404 on endpoint /import.

After investigating it seems that this may be releated to that commit 7f5a35aea98860d51ab39b8b480a617822de1ddc that removed some code related to Gliffy import.

**To Reproduce**

Go to File -> Import from -> Device...  or File -> Open from -> Device and select a gliffy diagram. In the first case nothing happens, in the second case the application returns an error "Invalid or missing file". In the developer console it is possible to see an error 404 on "/import".

**Expected behavior**

My understanding is that the gliffy diagram should be opened.

**draw.io version (In the Help->About menu of the draw.io editor):**

- 14.3.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 87.0.4280.66

**Additional context**

I wonder if it was decided to remove Gliffy support from the open source version of the program or it's just a bug. I tried to find information about this by looking around but the only thing I found, in the changelog, is that recently there were some improvements to the feature :)

**Comment by davidjgraph** [comment]
The gliffy import code isn't part of the project anymore. It's part of another project with a commercial vendor and they asked for it to be removed.

Gliffy import outside Atlassian is a very rare use case, mind me asking what the requirement is?

**Comment by lokeller** [comment]
Thanks for the quick answer. This clarifies the situation.

My use case is not really a common use case: the idea is to use draw.io as main diagram editor for a documentation project in sphinx and have a way to import a few gliffy diagrams that are downloaded from a confluence server (which unfortunately doesn't run draw.io and cannot be easily reconfigured). I don't really need the feature much (I can re-draw the diagrams), I wanted to be sure it was not broken by accident. On my side we can close the ticket.

**Comment by davidjgraph** [comment]
We can probably get you a free draw.io license on that Confluence to convert the Gliffys, does that work?

**Comment by lokeller** [comment]
Thank you very much for your kind offer! (and for offering such a nice editor as open source) Unfortunately the confluence server is out of my reach so I wouldn't be able to make use of the license.
