### ISSUE TITLE
Send request with mxXmlRequest with credentials

### ISSUE THREAD

**Issue by Totone** [jgraph/drawio#1820]
Hi there, 

I'm facing an issue using mxXmlRequest object to make an AJAX request with credentials to a protected API, I don't understand how to use the mxXmlRequest efficiently

Here's the code:

```js
let req = undefined;
/* condition: if "username" & "password" credentials are found */
req = new mxXmlRequest(
              url,
              null,
              "GET",
              false, // I need a synchronous request
              username,
              password
            );
            req.create();
            // req.withCredentials = true;
            // req.setRequestHeaders();
            req.send(); 
```

This doesn't work.
`req.create()` attempts to create the "inner" request object but it does not seem to work.
`withCredentials` does not seem to do anything.
I'd like to use `setRequestHeaders()` to add an Authorization header but if I give on first arg:

- `req` or `req.request` (theoretically created by `create()`): "a is null"
- `req.create()`: "XMLHttpRequest state must be OPENED."
- `req.create().open('get', url, false))`: "a is undefined" 

No matter the way I provide these methods, request does not send anything.
As well, without `setResuestHeaders()`, a simple request works but one with credentials doesn't. In this case, request is sent but blocked & "A network error occurred." error message appears in the console.

**Comment by alderg** [comment]
Might be easier to implement this with XMLHttpRequest directly.

**Comment by Totone** [comment]
Yes. I'd like to use mxXlmRequest to take advantage of the platform abstraction given with mx utils functions but while I don't understand how to make it work, I have to make my request with xhr

**Comment by alderg** [comment]
Let me know if you get it to work, it might help getting mxXmlRequest fixed.
