### ISSUE TITLE
There is a persian translation file, but not in the menus.

### ISSUE THREAD

**Issue by molaeiali** [jgraph/drawio#1823]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I can see there is a [dia_fa.txt](https://github.com/jgraph/drawio/blob/master/src/main/webapp/resources/dia_fa.txt) in the project but there is no Persian or Farsi language in the language menu of the desktop app. Why is that?

**Describe the solution you'd like**
Add Persian to the languages list.

**Additional context**
I cannot find any way to contribute to translation, I understand that you said "not open-contribution", but I think It's about code, not translation, I don't think you can have anyone who knows all languages on earth 😅

It would be great to have a translation section in documentations to readme or link to Crawdin/Transifex/Other translation platforms If exists.

**Comment by mararad** [comment]
Hi,

Could you check the following article please: https://drawio-app.com/translate-drawio/ You will find all the details related translations and how you could contribute.

Thanks,

**Comment by davidjgraph** [comment]
We only add languages as an option when a reasonable amount of the translations are translated for that language. If you are willing to help, yes, we very much welcome any help. Just email support@diagrams.net with the email address of your Google account and we'll add you to the translations spreadsheet. 

That said, a lot of the Persian translation does seem done, I'll take a look why it's not in the list.

**Comment by davidjgraph** [comment]
Added to menu in 14.4.0.
