### ISSUE TITLE
How to use DRAWIO_CONFIG variable?

### ISSUE THREAD

**Issue by sag1** [jgraph/drawio#1825]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I would like to add a custom color palette using global configuration variable **DRAWIO_CONFIG**. I searched a while to know about this configuration in source code and issues, but in vain. No documentation. I don't know what value to put there. I tried these values in PreConfig.js:

window.DRAWIO_CONFIG={"defaultColors": [
        "000000",
        "595959",
        "8F8F8F",
        "D6D6D6"]
}   **--> not working**

window.DRAWIO_CONFIG='<?xml version="1.0" encoding="UTF-8" ?><defaultColors>000000</defaultColors> <defaultColors>595959</defaultColors> <defaultColors>8F8F8F</defaultColors>' **--> Not working**

 Could you please add some details about **DRAWIO_CONFIG** and type of value expected ?

**To Reproduce**
1. Go to Style
2. Check for the added the color
3. No new colors are added

**Expected behavior**
New colors shoud be added

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 14.2.7]

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

**Additional context**
I know that we can set locally using Extras-->Configuration-->JSON. It works well. But my aim is to set globally for our SaaS instance.

**Comment by davidblaisonneau** [comment]
Same issue here using VSCode hediet.vscode-drawio integration.
The pushed config is working on the online config, and Linux app when set using the interface

**Comment by mararad** [comment]
Hi,

these articles might help you:
https://desk.draw.io/support/solutions/articles/16000058316-configure-the-diagrams-net-and-draw-io-editor
https://drawio-app.com/customise-default-colours-fonts-styles-and-the-draw-io-ui-in-confluence-cloud/

Regards,

**Comment by sag1** [comment]
Hello @mararad I know these articles, these explains on how to configure custom colors/styles via graphical interface and is applied locally to the user who configured. What I want to achieve is to apply custom colors/styles globally by using DRAWIO_CONFIG. I tried different variations json/xml to pass value in DRAWIO_CONFIG as described here https://github.com/jgraph/drawio/blob/master/src/main/webapp/js/diagramly/App.js#L1090

Could you please suggest me the format of value accepted by DRAWIO_CONFIG ?

**Comment by alderg** [comment]
The correct format JSON, eg. window.DRAWIO_CONFIG= {"gridSteps": 10}. Is PreConfig.js loaded? If yes, check if App.js line 1090 is reached.

**Comment by sag1** [comment]
Hello @alderg yes, Preconfig.js is loaded correctly
```
Init PreConfig.js
window.DRAWIO_CONFIG = {"defaultColors":["000000","595959","8F8F8F"]};
```
But no changes, the custom color is not taken into account. How to check line 1090 is reached ? I tried with console.log, no log message

**Comment by alderg** [comment]
It depends on your environmnt. If you are loading App.js put a breakpoint on that line. If you are loading app.min.js, you should put a breakpoint on Editor.configure via the developer console in your browser.

**Comment by alderg** [comment]
Just to be sure, you are expecting to see this in the color dialog?

<img width="264" alt="Screenshot 2021-02-18 at 15 07 22" src="https://user-images.githubusercontent.com/921200/108368771-1e0f9600-71fb-11eb-8b79-2c6d12955d0c.png">

**Comment by sag1** [comment]
yes that's what I expected.

I found out the error while debugging. JSON string is not well formatted even I used online formatter :( Due to this, App.js is unable to parse and apply it. After applying well formatted JSON string, it works well.

Thanks a lot @alderg 👍

**Comment by CvH** [comment]
@sag1 can you post your example ?

**Comment by sag1** [comment]
@CvH here is an example:

`window.DRAWIO_CONFIG = {"defaultColorSchemes":[[{"fill":"#000000","stroke":"none"},{"fill":"#595959","stroke":"none"},{"fill":"#8F8F8F","stroke":"none"},{"fill":"#D6D6D6","stroke":"none"},{"fill":"#C19372","stroke":"none"},{"fill":"#F4CFB2","stroke":"none"},{"fill":"#FFF6B6","stroke":"none"},{"fill":"#FFE8F7","stroke":"none"}]],"presetColors":["000000","595959","8F8F8F","D6D6D6",],"defaultColors":["000000","595959","8F8F8F","D6D6D6","FFFFFF","FF7900","4BB4E6","50BE87","FFF6B6","FFE8F7"]};`
