### ISSUE TITLE
Documentation Uencoded_url typos and unclear?

### ISSUE THREAD

**Issue by DrOteonu-Nanquanu** [jgraph/drawio#1826]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Not a bug, but unclear/typo documentation in https://desk.draw.io/support/solutions/articles/16000042546-supported-url-parameters:

`url=url:Deprecated - please use #Uencoded_url instead (opens a diagram from a URI-encoded UR,L where the URL should be encoded).`

* See the comma in "UR,L". 
* One states "url=url is Deprecated", but its successor "#Uencoded_url" does appear in the parameter list on the given page.

`Parameters for embedding HTML. Note that URL parameters that can be passed as a URL encoded JSON string via a #P... URL hash.`

I assume that the second "that" should be removed.

**Comment by TheSinding** [comment]
I also find it very unclear and have no clue how to use the new `encodedUrl` param

**Comment by DrOteonu-Nanquanu** [comment]
@TheSinding just by trial and error I found out that the following works:

`https://app.diagrams.net/#Uhttps%3A%2F%2Fwww.something.org%2Fsubdir1%2Fsubdir2`

But I they should definitely update the documentation!

**Comment by alderg** [comment]
Fixed
