### ISSUE TITLE
AWS Icons disappeared on AWS shapes

### ISSUE THREAD

**Issue by alexmelekhavets** [jgraph/drawio#1828]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
AWS Icons disappeared on AWS shapes

**To Reproduce**
1. Open any saved diagram with AWS icons or create a new one 
2. See shapes without icons on your diagram and in the search field

**Expected behavior**
AWS shapes should be visible on AWS Icons 

**Screenshots**

![image](https://user-images.githubusercontent.com/79173916/108498756-66dc5300-72be-11eb-9950-30793db68e2d.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome Version 87.0.4280.141 (Official Build) (64-bit)

**Comment by davidjgraph** [comment]
What is the version under help? i.e. could you fill in the fields we ask for in the template...

**Comment by alexmelekhavets** [comment]
I used 14.2.0, but now looking into diagrams under the 14.4.2 version in the incognito mode and everything works as exptected.

**Comment by alexmelekhavets** [comment]
I'm okay now, the workaround was to clear my browsing data and now I'm on 14.4.2. Closing this issue.
