### ISSUE TITLE
Self-call shape in sequence diagram should be improved

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1829]
"The built-in self-call in the UML shapes library is misplaced.
Attached shows the desired one and the current one. Making the desired one I have to make several clicks, draw, tweaks on the line. Any more convenient steps to create it?"

![wJbFw](https://user-images.githubusercontent.com/44292306/108499889-4953bd00-72af-11eb-8095-1198ed474578.png)

**Comment by alderg** [comment]
Fixes default alignment when dropped. As discussed, that arrow end at the start of the activation is correct.
