### ISSUE TITLE
Failing to Render Math on This 3 Matrices Code

### ISSUE THREAD

**Issue by RoyiAvital** [jgraph/drawio#1832]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When entering the text of a math as following:

```
$$ \frac{1}{2} {\left\| \underset{X}{\underbrace{\begin{bmatrix}
1 & {x}_{1}^{1} & {x}_{1}^{2} & \cdots & {x}_{1}^{P} \\
1 & {x}_{2}^{1} & {x}_{2}^{2} & \cdots & {x}_{2}^{P} \\
\vdots & \vdots & \vdots & \cdots & \vdots \\
1 & {x}_{M}^{1} & {x}_{M}^{2} & \cdots & {x}_{M}^{P}
\end{bmatrix}}} \; \underset{\boldsymbol{\theta}}{\underbrace{\begin{bmatrix} {\theta}_{1} \\ {\theta}_{2} \\ \vdots \\ {\theta}_{P + 1} \end{bmatrix}}} \; - \; \underset{\boldsymbol{y}}{\underbrace{\begin{bmatrix} {y}_{1} \\ {y}_{2} \\ \vdots \\ {y}_{M} \end{bmatrix}}} \right\|}_{2}^{2} $$
```
The math rendering fails to render (While MathJaX does render this correctly).

**To Reproduce**
1. Enable Math in `Extras`.
2. Create new text box.
3. Paste the Math Code above.
4. See the failed rendering.

**Expected behavior**
To render the equation just like MathJaX.

**Screenshots**
The failed rendering:

![image](https://user-images.githubusercontent.com/7347975/108591367-1d007500-7371-11eb-9cd9-06c3f973e526.png)

Correct output:

![image](https://user-images.githubusercontent.com/7347975/108591387-2db0eb00-7371-11eb-94c7-df75a9441635.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version `14.2.9` (The latest published on https://app.diagrams.net/).

**Desktop (please complete the following information):**
 - OS: Windows 10 (Latest updates)
 - Chrome (`88.0.4324.182`) / Edge (`88.0.705.74`)
By the way, on Firefox `85.0.2` it renders well.
But since on Chrome it renders well in MathJaX it means it is still something in the math configuration.

**Comment by alderg** [comment]
Works in Chrome 92 ([Testcase](https://app.diagrams.net/#RrVZNc5swEP01HJ0BYeL0GIOd9uBOOj60PWVkWIMagRghbNNf3xUSxvgjsdPMMEJ6etrVW1t6OH6Y754kLbOFSIA7xE12jh85hATjB2w10Fjg%2FosBUskSA3k9sGR%2FwYKuRWuWQDUgKiG4YuUQjEVRQKwGGJVSbIe0teDDrCVN4QRYxpSfoj9ZojKDPgRuj38FlmZdZs%2B1MzntyDZEldFEbA3UcvyZ44dSCGV6%2BS4ErmvX1cUEml%2BY3W9MQqGuWbCMRt%2FDH%2FNN2Hz7XZVh8Ge6nY6IibKhvLaCHTJuH9cJwrWksTOZes4kwhfRL8QnU5zisFb4ciahodZFArIChbO%2FDL0DVxgEzHgFKSuwu8LiSLZr491z3P10JbGX6p6n45F7mpc4MK1Jqukv3W6CWde7mk0usoMwToSqrg%2F1bEOhfnxul0BukkA%2BTwK5VgKCm8sB%2F2fyjX0erPxoZRc3VXbxeZVdHFX2TEGhSIb%2FffMYtV2yg3OkDwxeV1WT48uMVQaKdkuvPWHucO3LQXFsmc8wyDHj9Mc5s%2Bq5LZOW0md4X%2Fbo%2Bho0HxHfXFbd3Ca3Ofy131UnW18wl%2BTFo2xu29YgVNO5jhRam764XazKNmMKlqXW6UdbtFnEMpVzHHnYrV5BxZnlZjTOaglPmhSNESgFKxTI2QZtorKktSjUnOaMa1N%2BlLGOH7diI1rjnkFa0lLUss2aKYWGSwL%2FERu0GN1oQnWXCpFyoCWr7mKRtxNx1VLna5MCu4MkAZkepzG2T9q9Mc5DwQXORYUoQAtUUrzCEWiNC6SC3UVH9PY%2Bi98nIHJQEvfjdh8n1qqb4XDb%2B%2Fx4YrHswOOJb0Fqvy3SfeTefrFjHbgb9k7fzh18Lvmzfw%3D%3D)).
