### ISSUE TITLE
Increase circle size for negated Electrical / Logic Gates (Inverter, NAND, NOR, etc)

### ISSUE THREAD

**Issue by ftorres16** [jgraph/drawio#1833]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
In the current version, the circle at the output of negated gates like Inverter, NAND, and NOR is very small and hard to see. This can lead to confusion for the reader of the diagram, making draw.io a less than ideal tool for drawing logic.

This is especially important for integrated circuit design, where INV, NAND and NOR are the basic construction blocks.

**Describe the solution you'd like**
I would like the circle at the output of the negated logic gates Inverter, NAND, NOR, XNOR to be larger so it is more noticeable.

A good implementation is available in Circuitikz . You can see it on page 115 of [their manual](https://circuitikz.github.io/circuitikz/circuitikzmanualgit.pdf) and they discussed it in [this Github issue](https://github.com/circuitikz/circuitikz/issues/383).

> Negation indicator ("dot"/"bubble")
> 
>     IEEE 91-1973 recommends a radius R = 1/20 of the height of the symbol
>     IEEE 91-1984 recommends a radius R = 1/13 of the height of the symbol = (0.5H) / (6.5H)

With R = 1/13 of the circle diameter would be 9.32pt which I find much clearer than the standard 5pt. 

**Describe alternatives you've considered**
I considered creating new custom symbols for my personal use, but I think the standard library could benefit from it. It is harder to recommend draw.io to my colleagues as a result.

I can continue using circuitikz for my logic diagrams, but describing drawings with text is slower and less convenient. It is a very different use case.

**Additional context**

**Comment by egrimate** [comment]
Will be in next release
