### ISSUE TITLE
Use CodeMirror to make plug-ins or shapes

### ISSUE THREAD

**Issue by drawfund-founder** [jgraph/drawio#1834]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
None.

**Describe the solution you'd like**
- Annotate codemirror with charts.
- Use codemirror comment diagrams.

**Describe alternatives you've considered**
- Use CodeMirror to make plug-ins or shapes.

**Additional context**
[CodeMirror(Plugin,Shapes).drawio.zip](https://github.com/jgraph/drawio/files/6017099/CodeMirror.Plugin.Shapes.drawio.zip)

![CodeMirror(Plugin,Shapes)](https://user-images.githubusercontent.com/79265887/108614003-aecfb700-7431-11eb-957d-c11779aec17d.jpg)

**Comment by editfund-founder** [comment]
![Screenshot_20210222-192511](https://user-images.githubusercontent.com/61936162/108702156-d57e1280-7543-11eb-80d5-60f511b711c6.png)

**Comment by editfund-founder** [comment]
<span style="color:#ab4642">iframe</span>
var frame = document.createElement('iframe');
frame.setAttribute('width', '192px');
frame.setAttribute('height', '172px');
frame.setAttribute('src', 'http://www.example.com/');
frame.style.backgroundColor = 'white';

var w = document.body.clientWidth;
var h = (document.body.clientHeight || document.documentElement.clientHeight);
var wnd = new mxWindow('Title', frame, (w-200)/2, (h-200)/3, 200, 200);
wnd.setVisible(true);

**Comment by editfund-founder** [comment]
feature request:
Extras➝Edit➝[Diagram...]
![codemirror](https://user-images.githubusercontent.com/61936162/109092647-e3a17e00-7751-11eb-859f-f949aa7a12fb.jpg)

**Comment by editfund-founder** [comment]
http://hilite.me/

**Comment by editfund-founder** [comment]
![Screenshot_20210225-131657](https://user-images.githubusercontent.com/61936162/109107038-ffb21900-776b-11eb-83a9-629e28fcd88b.png)
