### ISSUE TITLE
Search allows access to disabled libraries

### ISSUE THREAD

**Issue by DaAwesomeP** [jgraph/drawio#1838]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When only certain libraries are loaded or enabled, the search still searches all libraries, even ones that the user cannot get to from the "More Shapes..." window.

**To Reproduce**
1. Create a configuration that enables only certain libraries or custom libraries or [try this one that disables everything](https://app.diagrams.net/#_CONFIG_UzV3UjUySklNSyzNKfHJTCpKLMpMLQYKqRo7gkgQckaocC4tLsnPxaMuNS8xKSc1haAKrAalJeYUp0JU5ZelFhVlpqRCJEqKSqHiQOHizPw8uLEGegZ6hnCzc9CsNXVSNXVRNXcBAA==)
2. Try searching for shapes
3. Shapes and stencils still appear from unavailable libraries. Right-clicking shapes also allow for adding those libraries

**Expected behavior**
The search should only return shapes that the user has access to.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 4.4.2

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 85.0 x64

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
