### ISSUE TITLE
Mathematical typesetting offline

### ISSUE THREAD

**Issue by USchneid** [jgraph/drawio#184]
Why is it not possible to enable mathematical typesetting in offline mode? Is it a technical problem or did you intentionally disable this option? I don't see any reason why it is hard to realize with mathjax or katex.

Best regards

**Comment by davidjgraph** [comment]
The MathJax code consists of a very large number of files, and has a large overall size. There are technical problems with including MathJax within our distro, so we take it from their CDN.

**Comment by deepmeng** [comment]
@USchneid @davidjgraph Do you mean the Draw.io-Desktop version?  I use the version of (Draw.io-desktop-v10.6.8) and it cannot convert mathematical typesetting to formulars.

**Comment by makoto-yamashita** [comment]
Mathjax can be installed locally by the users.  In Draw.io-Desktop, is it possible to point the local Mathjax installation instead of the online Mathjax?

If I used local Mathjax, I could continue using Draw.io-Desktop without internet connections.

**Comment by davidjgraph** [comment]
@makoto-yamashita If you have an issue relating to desktop please post it to https://github.com/jgraph/drawio-desktop/issues including version, environment and steps to reproduce.
