### ISSUE TITLE
Question:Is the file format .drawio an open-source file format?

### ISSUE THREAD

**Issue by jerry-yuan** [jgraph/drawio#1840]
I have using a drawio based online diagram tool named processon.com for years until I found the open-source library draw.io's desktop version.

The processon was a commercial website that only provide limited storage to free users. For this reason, I decided to transform my processon diagrams into draw.io. I found that processon don't support exporting diagarams into draw.io's file formats that contains diagram level information even the processon was built with draw.io. Fortunately, the processon provided the feature that exporting diagrams to ` .pos` file without cost. The `.pos` file (ProcessOn Schema) is the private format for itself. I have checked that the ` .pos` file was a ` json` file with meaningful keys.(contains the diagram level informations)

After that I tried to open `.drawio` file with text editor. I found that the `.drawio` file was a xml like file but there is some base64 strings like data inside the `diagram` node and I have confirmed that it was not provided by a  string with base64 encoded.

I want to know is there any documents that describe the structures of the .drawio file to be the guide for me in development of converting tools. If there is no documents, could you tell me which source file has managed the `.drawio` file generation inside desktop version of draw.io.

**Comment by editfund-founder** [comment]
File→Properties→[Compressed:Uncheck]
>

**Comment by jerry-yuan** [comment]
> File→Properties→[Compressed:Uncheck]
> 
> >

Thanks a lot.
