### ISSUE TITLE
Please share Embedded mode source code

### ISSUE THREAD

**Issue by GordonRudman** [jgraph/drawio#1842]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I am trying to build an embedded integration using the javascript/html5 postMessage pattern.
If I point my code to https://embed.diagrams.net/ things work, but if I point to my own server running the code from https://github.com/jgraph/drawio  it doesn't work (The UI loads halfway and locks up completely).
If I point to https://app.diagrams.net/ it also locks up, so I suspect there is a difference between https://app.diagrams.net/ and https://embed.diagrams.net/ but I'm not sure what it it exactly.

**Describe the solution you'd like**
Please could you share the code to https://embed.diagrams.net/ or perhaps explain what changes I need to make to enable embedded mode.

**Describe alternatives you've considered**
I've spent a lot of time trying to debug this, but to no avail.

**Additional context**
I also noticed that the minified js files in the repo are slightly different to the ones produced when running the ant build, so it looks like something is out of sync.
If I try run using the build output it fails to load properly on the stencils.min.js

**Comment by vinhchiase** [comment]
I want to embed Diagram in my Wordpress website and did it but I got the error
"Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document"

After many tries, Diagram won't let me embed it anymore, but if you open it in an incognito browser it's okay, is this a security feature?

**Comment by davidjgraph** [comment]
@vinhchiase your issue is off-topic to the original issue, please start another issue.

**Comment by vinhchiase** [comment]
@davidjgraph 
I'm sorry, I'm not good at English so there's a misunderstanding

**Comment by samcov** [comment]
This is classified as completed, however, I see no link to the source code for embed.diagrams.net.

**Comment by davidjgraph** [comment]
embed.diagrams.net runs the source in this repo, just with particular flags. Ask a decent AI tool to explain it and it will.

**Comment by samcov** [comment]
> embed.diagrams.net runs the source in this repo, just with particular flag. Ask a decent AI tool to explain it and it will.

Thanks for the info, but I already have an embedded app that works perfectly using embed.diagrams.net, however when I substutite the version I'm running locally, it fails to work.

However, your response made me debug differently and I noticed that the code gets confused when the app isn't hosted directly from the domain. 

const DRAWIO_ORIGIN = 'http://localhost/AlantusHR/zTests/webapp'; **This fails because it tests the origin against only localhost**
//const DRAWIO_ORIGIN = 'https://embed.diagrams.net'; **This Works**

My assumption is that if I hosted it on another server, say myembed.somedomain.com, it would work, which is easily something I can do and will try when I get the time!

**Thanks for the response!**

**Comment by samcov** [comment]
Better yet, I simply stopped checking if the origin was coming from the root of the domain and it just WORKED!

I forgot to mention the the checking wasn't in your code, it was in ours, someone was just double checking, but didn't do it for the general case!

And yes, all you need are the proper flags!

**Thanks so much, problem solved!!!**
