### ISSUE TITLE
Zooming in causes text to disappear 

### ISSUE THREAD

**Issue by david1oh4** [jgraph/drawio#1844]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
On large diagrams, over several A3 sized pages, any text becomes transparent when at any magnification above 30%. Text is visible while the magnification is being changed, but then once the scale of everything else shifts accordingly, the text disappears. It is still present as click on a text box to edit it produces the correct text, but it will disappear again the moment it is no longer selected.
The phenomenon is only present at the bottom half of the workspace

**To Reproduce**
1. Start a flow chart on a Windows computer using a Chrome browser
2. Make a big diagram with a lot of shapes and text, about 5 A3 pages should be more the sufficient
3. Scroll down to the bottom half of the work space
4. View the text while changing the magnification from 10% through to 100%

**Expected behavior**
The text will disappear as you go from 20% to 40% magnification

**Screenshots**
![image](https://user-images.githubusercontent.com/79650172/109171102-55d98900-7779-11eb-827f-a838d4382fb7.png)
![image](https://user-images.githubusercontent.com/79650172/109171268-84effa80-7779-11eb-8c09-15b72f4286f6.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [14.4.2]

**Desktop (please complete the following information):**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [88.0.4324.182]

**Additional context**
This problem seems to scale with the length of the workspace. The large it gets, the large the percentage of the workspace if affected by this glitch, but at smaller magnifications, e.g. the text in the lower quartile of the screen disappears at 40-50%

**Comment by mararad** [comment]
Hi,

Do you have the same issue in other browsers and Incognito mode? Could you test this in the latest 14.4.3 and tell me the result?
If still present, it would be great if you could attach the file so I could test it.

Regards,

**Comment by david1oh4** [comment]
Hi

I can confirm the bug appears in incognito mode

However, this bug is not present on ms Edge

As far as I can tell, this is on the latest version 14.4.3

Thanks

**Comment by mararad** [comment]
Hi, 

since this bug is not present on ms Edge, this is browser-related issue. My suggestion would be to disable all browser extensions and clear browser cache and test again. 

Regards,

**Comment by alderg** [comment]
Could you please attach a test case?
