### ISSUE TITLE
Make transparent regions ignore pointer events

### ISSUE THREAD

**Issue by septatrix** [jgraph/drawio#1846]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Using shapes (like rectangles) as containers to group other elements visually is a common approach.
However the usage shapes in this way has some usability problems most of which boil down to transparent regions still being considered a hit region. It is for example imposible to draw a selection around elements inside of such a container. Instead of creating a selection the background element grabs focus and you start moving it.

**Describe the solution you'd like**
Most alternative programs like Inkscape, CorelDraw, Microsoft Office etc do not consider transparent regions as clickable but instead treat them as click-though. The elements are still clickable at their edges (similar to arrows currently). I think this would also be the prefered solution as it feels natural and is widespread in most other applications.

**Describe alternatives you've considered**
I was unable to think of any alternative approach nor do I know of any application which handles this different from the aforementioned ones.

**Additional context**
1. Open diagrams.net
2. Insert a shape (e.g. rectangle)
3. Got to the style tab on the right
4. Disable fill
5. Click inside of the element (i.e. the transparent region)

**Comment by alderg** [comment]
Try using pointerEvents=0 in the cell style.

**Comment by septatrix** [comment]
That seems to be what I imagined - I assume it corresponds to `pointer-events: visiblePainted;`? Is there some place where such advanced options (which do not appear to be exposed in the UI) are documented?

What is your attitude towards making this the default? This feels a lot better from a UX standpoint. <small>This came up during a meeting yesterday where people shared this opinion which is why I am asking.</small>

**Comment by davidjgraph** [comment]
Documented, only in the code.

Can't make it the default, we have a _lot_ of users. Changing such basic stuff like that isn't an option.

You could set it globally in the default cell style in the JSON configuration. How are you consuming the project, online, confluence, other?

**Comment by septatrix** [comment]
Are they grouped in one place where one can look them up by any chance or rather scattered around?

Hm okay :/ I still think that this is more natural and what users are actually used to from basically all other programs but I understand the aspect of backwards compatibility.

Using the electron app and sometimes the vs code extension. BTW thanks very much for the option to save the file uncompressed - it is very appreciated for git :D

**Comment by septatrix** [comment]
> Can't make it the default, we have a _lot_ of users. Changing such basic stuff like that isn't an option.

I kindly disagree. This does not disable any functionality but only changes the way the user interacts with stuff. Also I would not call it basic as this only applies to shapes with a transparent fill.

While you definitely have lots of users this is not a reason not to make such a change. As I explained before this is not ideal from a user experience standpoint as it subverts a users expectation (why is this shape suddenly selected? I only clicked at an empty point in space). Additionally it prevents other basic functionality from working as expected like spanning a selection box. You can see that many similar drawing programs¹ therefore only responds to clicks on painted areas (with a bit of padding obviously).

I very much want to see this tool become better and more natural to use. Making it more intuitive is one step to achieving this goal. Furthermore this would help users switching from comparable programs.

¹ Lucidchart is the only one I know which does this like draw.io - MS Powerpoint, Libreoffice Draw, Corel Draw, Gimp do not and at least MS and Corel have multiple UX designers sitting behind those products.

**Comment by davidjgraph** [comment]
And Lucidchart is a diagramming tool, like us. The rest are not....

**Comment by septatrix** [comment]
Yes but that does not mean that they have put more thought into their UX than the other programs I listed. Also many new users will come predominantly from those non-diagramming tools. Additionally the use case for most of programs also incorporates making graphics to a large degree so their expertise should not be ignored just because they are not a pure diagramming tool
