### ISSUE TITLE
Delete shape with connectors isn't working anymore

### ISSUE THREAD

**Issue by Bastesque** [jgraph/drawio#1848]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
In the past (no matter if you used draw.io on Confluence Server or Cloud), there was the shortcut Ctrl+Shift+Delete to delete a shape and all the connectors that were coming from or going to that shape (it's also included in the keyboard shortcut list). It's not working anymore.

**To Reproduce**
1. Create a few shapes that are connected to each other.
2. Try to delete a shape that has incoming and outgoing links with the shortcut mentioned above.
3. Not working

**Expected behavior**
See above

**draw.io version (In the Help->About menu of the draw.io editor):** draw.io for Confluence Cloud

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] MacBook Pro
 - OS: [e.g. iOS8.1] macOS 10.15.5
 - Browser [e.g. stock browser, safari] Chrome
 - Version [e.g. 22] 88.0.4324.150

**Additional context**

**Comment by mararad** [comment]
Hi Bastian,

If you try Ctrl+delete (trash can) does it help? 

I tested in draw.io 14.4.3. for Confluence Cloud, Win 10 Pro and Chrome Incognito
and at my place Ctrl+delete and Ctrl+Shift +delete work well. What draw.io version are you using? (can be seen under Help in the draw.io editor)

Regards,

**Comment by Bastesque** [comment]
Hi Mohammedan,

I use 14.4.3, the latest Chrome version (tested with an without Incognito mode) on Mac OS Catalina. Holding down the Command key and click the trash can item isn't successful. I tried all possible combinations of keys, even testing it in Safari didn't work :(. Maybe it's a Mac issue?

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
