### ISSUE TITLE
CellsInserted event not raised when adding a cell from imported library

### ISSUE THREAD

**Issue by NicoSB** [jgraph/drawio#185]
Hey guys, 

**when adding a cell from an imported library in the sidebar, no cellsInserted event is fired.**

 This is due to the fact, that in [Sidebar.prototype.createDropHandler()](https://github.com/jgraph/drawio/blob/7e202a0c251182221b28dcd7e4c63a189c04baa0/war/js/mxgraph/Sidebar.js#L2069) the event is only fired when allowCellsInserted is true:

`if (allowCellsInserted) { graph.fireEvent(new mxEventObject('cellsInserted', 'cells', select));}`

The reason for this can be tracked down to diagramly's [editorUI.libraryloaded()](https://github.com/jgraph/drawio/blob/a0e1f5478643a8956c3048540ce8aa88791c1ab5/war/js/diagramly/EditorUi.js#L1670), where allowCellsInserted is set to false (last argument):

<pre>content.appendChild(this.sidebar.createVertexTemplateFromCells(cells, img.w, img.h, img.title || '', true, false, <b>false</b>));</pre>

Is this behaviour intentional?

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release. (We're moving towards firing the event for all inserted cells to support configurable defaults, which should always be used.)
