### ISSUE TITLE
mxGraph is archived/unmaintained

### ISSUE THREAD

**Issue by septatrix** [jgraph/drawio#1850]
This may not be the correct place to ask this but I was unable to find a forum or similar. As mxGraph is now archived and not actively maintained any longer what is the plan going forward as drawio uses it as a dependency?

**Comment by davidjgraph** [comment]
We maintain our own internal version for this codebase.

**Comment by septatrix** [comment]
Thanks for the quick info. That already answered my question.

May I ask why the repository was archived then (as it is also part of this organization and maintained here anyway)?

**Comment by davidjgraph** [comment]
Having it public caused me extra workload and the project very little benefit. I was short of time, so I made the project private.

**Comment by akaDJon** [comment]
> We maintain our own internal version for this codebase.

Could you publisn sources internal version mxGraph into repo drawio (by format AS IS)? No need support or any somethink. Only sources for personal read/analisys/debug/test/rework. Thanks a lot

**Comment by chezgi** [comment]
drawio seems that closed its core library and only use `open source` as branding.
a new active fork is [here](https://github.com/maxGraph/maxGraph/tree/mcyph-graph-refactor)

**Comment by davidjgraph** [comment]
https://github.com/jgraph/drawio/tree/dev/src/main/mxgraph
