### ISSUE TITLE
Export SVG includes tooltips that don't contain HTML

### ISSUE THREAD

**Issue by drewburlingame** [jgraph/drawio#1851]
* [ x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I have a tool that generates diagrams from a dependency map.  I'd like to upload the resulting diagram to Confluence.  Due to complications discussed in #1849, it's not currently possible to simply upload the diagram to Confluence because the wiki won't recognize the uploaded version.  It would be enough for me to export SVG's for each diagram and upload those except we lose the tooltips, as discussed in #151 because tooltips can contain HTML. I cannot find documentation on what HTML can be included in tooltips, does it exist.  Is it still possible and if so, is it documented anywhere?  Would it be possible to include tooltips that don't include HTML?

**Describe the solution you'd like**
Export SVG includes tooltips that don't contain HTML

**Describe alternatives you've considered**
This is an alternative to #1849.  If tooltips can no longer contain HTML, then this is simpler.

**Comment by davidjgraph** [comment]
Why not use the draw.io viewer in Confluence to render the files? That will give you full tooltip support.

**Comment by drewburlingame** [comment]
> Why not use the draw.io viewer in Confluence to render the files? That will give you full tooltip support.

@davidjgraph because we generate the diagram with a custom tool.  When we upload the diagram,  the draw.io viewer won't recognize it because the viewer requires metadata saved in the page.   That's discussed in another issue I raised.   As a work around we're generating the svg files for upload to confluence.

**Comment by davidjgraph** [comment]
If you use the embed drawio macro, rather than the standard macro, I think you should be able to reference the attachment by URL and the viewer work without the macro parameters:

<img width="645" alt="Embed drawio macro in Confluence Data Centre with the From URL tab selected" src="https://user-images.githubusercontent.com/1761087/135818569-27efef68-d683-435d-b56f-a9735d4da7f5.png">
