### ISSUE TITLE
Line Jump Suggestion

### ISSUE THREAD

**Issue by tiziano149** [jgraph/drawio#1852]
Hello drawio-github,

I'd like to propose this style of line jump style (green line jump):

![Bildschirmfoto 2021-03-01 um 13 32 19](https://user-images.githubusercontent.com/16635297/109498032-31d8b900-7a93-11eb-9a69-aab1ab4a7951.png)

I assume it could be implemented very easily.

Thank you for the great work! Keep it up.

Tiziano

**Comment by alderg** [comment]
Thanks for the report. This will be added in the next release.
