### ISSUE TITLE
User A is logged into G Docs, but 'insert' shows documents of User B  (not a bug, but counterintuitive)

### ISSUE THREAD

**Issue by bjohas** [jgraph/drawio#1853]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the "unintuitive behaviour"**

- User A is a Google Doc owned by a Google Suite (with diagrams.net plugin installed)
- I select Add-ons -> diagrams -> insert 
- I navigate to Shared Drives: The shared drives for User B are shown.

The reason for this is that it is user B who is signed in with https://app.diagrams.net/.

**Expected behavior**

I expected the diagrams visible to be ones that are accessible to User A in drive. 

In the insert dialogue, it would be good to see which user is logged in, ideally being able to change the user.

**Comment by ashrafteleb** [comment]
Which user is logged to Google Doc?

**Comment by bjohas** [comment]
There are two users "logged in". One user (A) is logged into google docs and is viewing a google doc. User B has previously logged into google drive to save a drawio to drive. So they are both logged into google drive - however, User A into the Google Doc, while for User B there's a previous log-in to google.

**Comment by ashrafteleb** [comment]
@bjohas Unfortunately, when you are logged with more than one user in Google, the method we use to get the user token returned the default one (not the current selected user). It's not related to whom is logged to diagrams.net

We user this method
ScriptApp.getOAuthToken();
https://developers.google.com/apps-script/reference/script/script-app#getoauthtoken

I'll mark this issue with Help needed label in case someone can help us

**Comment by bjohas** [comment]
Ah yeah, that makes sense (and fits my experience).

Would it be possible to display the user in the insert file dialogue? Then at least it's clear.

Björn

**Comment by ashrafteleb** [comment]
OK, we'll check that

**Comment by gezamolnar** [comment]
Yeah, the very least the actually used logged-in user should be presented (with a warning) as @bjohas wrote.

Much better when the real solution is presented :-)
