### ISSUE TITLE
Vector format export to Office 365

### ISSUE THREAD

**Issue by larsch** [jgraph/drawio#1854]
**Is your feature request related to a problem? Please describe.**

* Diagrams embedded using the Office 365 App are rasterized when shared as .docx (not in vector format)
* Imported drawing using Office 365 app are rasterized when exported as PDF and looks terrible
* Imported SVG from draw.io using Office 365 are broken due to lack of full SVG 1.1 support in Office
* Poor print quality from diagram embedded with Office 365 app

**Describe the solution you'd like**

True vector export to Office Suite, either by simplified "office compatible" SVG export with text-to-path and avoidance of CSS to style text + backgrounds (would require "polyfills" in many cases).

Alternatively WMF export.

**Describe alternatives you've considered**

Please do let me know if I'm missing something obvious here. I've been unable to find an alternative method that provides the professional print/PDF quality that is needed. 

**Additional context**

I know this is much to ask, but with draw.io being absolutely fantastic at drawing elegant and professional looking drawings, not be able to import them correctly into Word (or even Inkscape) in vector format without breaking the layout is limiting draw.io's usefulness for me and perhaps others.

Demo diagram imported via Office 365 app and exported to PDF with minimum size publishing. Terribly pixelation and JPEG artifacts:

![image](https://user-images.githubusercontent.com/15712/109678820-47c1a900-7b7b-11eb-9a2f-b20e439408f1.png)

Same diagram to PDF in Word with "standard publishing". Better, but still pixelated.

![image](https://user-images.githubusercontent.com/15712/109678984-73449380-7b7b-11eb-8062-04251a8246a6.png)

SVG exported from draw.io inserted into Word is mangled:

![image](https://user-images.githubusercontent.com/15712/109679507-ed751800-7b7b-11eb-899e-781667b26b99.png)

Original in draw.io or even SVG in browser (even Edge) looks absolutely professional, but I can't find any way to make it look good embedded in Word/PDFs.

Print quality when printed from Word with Office 365 app has fuzzy edge dithering due being scaled raster:

![drawio_office365](https://user-images.githubusercontent.com/15712/109685947-126c8980-7b82-11eb-942e-344f41460c7e.png)

Print quality when printed from draw.io is perfect:

![drawio_appprint](https://user-images.githubusercontent.com/15712/109685943-11d3f300-7b82-11eb-986c-0513af4f520f.png)

**Comment by orb71** [comment]
`Imported SVG from draw.io using Office 365 are broken due to lack of full SVG 1.1 support in Office`
The add-ins shows the same behavior, also I noticed objects from official disapears once imported.

@larsch , my current workaround is to use advanced export, png and boost to 400 DPI

Oli

**Comment by EwoutH** [comment]
Yes, I would fully support an "office compatible" SVG export! Maybe even just exporting to SVG 1.0 as an option.

How it currently looks in the latest Word and PowerPoint (Version 2102, build 13801):
<img width="642" alt="Screenshot_425" src="https://user-images.githubusercontent.com/15776622/112951182-5fb92800-913b-11eb-925c-08df8ee0fc17.png">

**Comment by muehf** [comment]
Please implement something like this. I need a vector format, that can be easily imported (drag and drop) in Microsoft Office. EMF would work great for MS Office.

**Comment by jrzwee** [comment]
@davidjgraph is there any explanation on why this issue was closed? Thank you so much in advance.

**Comment by davidjgraph** [comment]
We just don't intend to implement it.

**Comment by jrzwee** [comment]
I tried finding a workaround for this problem.

How to get a sharp image in a Microsoft Word PDF export?

1. Draw.io: Export your drawing as PDF
2. PDF24 (https://tools.pdf24.org/en/convert-from-pdf): Convert the created PDF to SVG (bulk converting possible)
3. Microsoft Word: Export (not print) the document

Before (direct svg from drawio to Word):

![Image](https://github.com/user-attachments/assets/9ece9aad-308c-4ea3-981b-691a3777a2a3)


After:

![Image](https://github.com/user-attachments/assets/78be3104-7bcc-486a-a0ee-9598534db099)
