### ISSUE TITLE
Cannot move connector endpoints on AWS shapes

### ISSUE THREAD

**Issue by coutHan** [jgraph/drawio#1856]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Cannot move connector endpoints on AWS shapes (e.g. AWS Cloud).

**To Reproduce**
1. Create an AWS shape (e.g. AWS Cloud).
2. Create a connector
3. Press "shift" while dragging one of the connector endpoints.
4. The endpoint is always attached to a fixed point on the border.

**Expected behavior**
The endpoint should be able to move freely within the AWS shape.

- draw.io version 14.4.3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Desktop version

**Comment by davidjgraph** [comment]
Alt or option on Mac, not shift.

**Comment by coutHan** [comment]
I said my OS is Windows 10 not Mac. Also, I tried Alt and Ctrl, but to no avail.

**Comment by davidjgraph** [comment]
"Alt on non-mac" or "option on mac".

Trying editing the style of the shape and remove "outlineConnect=0' if it's there.

**Comment by coutHan** [comment]
I checked the shape style, and there is no property named "outlineConnect". I want  to be able to move the connector endpoint inside the AWS shape, just like the rectangle shape below:
![Capture](https://user-images.githubusercontent.com/32535603/110030081-20d5b500-7cea-11eb-8760-e14699c7f054.PNG)

**Comment by davidjgraph** [comment]
Holding alt after starting drag and dropping the connector end while holding works for me on 14.4.3 on Windows 10. Anyone else able to repeat?

**Comment by coutHan** [comment]
This is kinda strange. My endpoints are always drawn to the same fixed points on the AWS shapes.

**Comment by alderg** [comment]
Please attach the diagram so we can check if this can be repeated with this specific diagram.
