### ISSUE TITLE
Export BPMN diagrams into Signavio

### ISSUE THREAD

**Issue by Kevan07** [jgraph/drawio#1857]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I am trying to export models from Draw.io into Signavio, however I keep getting an error when importing the draw.io XML

**Describe the solution you'd like**
I would like the export XML from Draw.io to have the relevant diagram and object information in BPMN2.0, to be able to import diagrams into Signavio without having to rebuild them manually.

**Describe alternatives you've considered**
I have been unable to identify any potential alternate methods 

**Additional context**
Error received says "Missing BPMN-DI" The diagram interchange part of the BPOMN2.0 definitions is missing. 
https://documentation.signavio.com/suite/en-us/Content/process-manager/userguide-classic/workspace-admin/import-bpmn2-xml.htm

**Comment by davidjgraph** [comment]
We don't intend to support export to BPMN 2 XML. See https://github.com/jgraph/drawio/issues/1238
