### ISSUE TITLE
Imported (Import from Device) image turns to a broken one

### ISSUE THREAD

**Issue by ggloveswp** [jgraph/drawio#1858]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Importing images from local client is not working, while at the same time, importing from remote origin (URL) works fine.

**To Reproduce**
1. Embed Draw.io library
2. Go To File -> Import From Device and upload an image
3. Check out the imported file - it will be broken

**Expected behavior**
While importing a remote URL image works, uploading a local images leads into broken image.

**Videocasts**
Failed import of local image: https://streamable.com/cwk2h2
Successful import of remote image: https://streamable.com/ne9r94

**draw.io version (In the Help->About menu of the draw.io editor):**
- 14.4.4

**Desktop (please complete the following information):**
 - All Versions/Browsers

**Comment by davidjgraph** [comment]
That is not a version that we release. You need to address your question to the author.

**Comment by ggloveswp** [comment]
14.4.4 release seems your version, out a few hours ago, according to this commit: https://github.com/jgraph/drawio/commit/cd8fb3ab6bbfc949722444b1901771332b3387d3

**Comment by davidjgraph** [comment]
No, I'm saying "diagramy" is nothing to do with us, it's the first I've ever heard of it. Where did you download this from?

**Comment by ggloveswp** [comment]
Oh, I see.
Thats the name of the CRM we use your embedded code of draw.io library.
It simply loads the embedded version of draw.io library under an iframe.

**Comment by davidjgraph** [comment]
It appears this is the vendor, https://codecanyon.net/item/diagramy-a-complete-diagram-editor-for-perfex-crm-flowcharts-process-diagrams-org-charts-more/29259040 . I would direct your question to them.
