### ISSUE TITLE
Setup defaults

### ISSUE THREAD

**Issue by kingfloyd** [jgraph/drawio#186]
How to setup the defaults for example the text align, paper size via script or app.min.js?
also is there a capability to add ruler function?

**Comment by stefanvangastel** [comment]
I am wondering the same. Would be useful to customize the defaults.

**Comment by alderg** [comment]
Ruler is in beta at https://github.com/jgraph/drawio/tree/master/src/main/webapp/js/diagramly/ruler
Setting defaults for cells can be done via Editor.configure (see https://desk.draw.io/support/solutions/articles/16000058316) or by changing https://github.com/jgraph/drawio/blob/master/src/main/webapp/styles/default.xml - depending on the requirements.
Default for paper size is at https://github.com/jgraph/mxgraph/blob/v3.9.1/javascript/examples/grapheditor/www/js/Graph.js#L26

**Comment by stefanvangastel** [comment]
@alderg Cool, thanks. And stuff like:

- Language
- Disable specific integrations (we run on-prem so no internet connection)

**Comment by alderg** [comment]
See https://desk.draw.io/support/solutions/articles/16000042546-what-url-parameters-are-supported- (lang, gapi, db, od, gh, tr)

**Comment by asl** [comment]
Note that for proper gdrive, etc. integrations one need to properly register & override various API keys, etc.

Ah, and gdrive rt API is deprecated, so some changes in the source code are necessary as well.

**Comment by stefanvangastel** [comment]
Thanks @alderg thats it! Is there a way to enforce them for all visitors?

**Comment by alderg** [comment]
Yes, you can set them in urlParams.
