### ISSUE TITLE
Installation of draw.io-amd64-14.4.3.deb yields an error

### ISSUE THREAD

**Issue by HaraldHubinger** [jgraph/drawio#1860]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
An error occurs upon installation of the .deb-package of version 14.4.3.
**To Reproduce**
Running `dpkg -i draw.io-amd64-14.4.3.deb` yields the following output:
```
(Reading database ... 634760 files and directories currently installed.)
Preparing to unpack draw.io-amd64-14.4.3.deb ...
Unpacking draw.io (14.4.3) over (13.9.9-336) ...
Setting up draw.io (14.4.3) ...
chmod: cannot access '/opt/drawio/chrome-sandbox': No such file or directory
...
```
The argument to `chmod` should be `/opt/draw.io//chrome-sandbox` I assume.

draw.io will then not launch from Gnome Applications menu. I repaired by uninstalling 14.4.3 and installing 13.9.9 again. 

A similiar error message is produced by using the built in update assistant on a Debian buster system with gnome-shell when updating from draw.io 13.9.9 to draw.io 14.4.3. In that case installation is rolled back automatically 

**Expected behavior**
Install without error messages, app can be launched from Gnome Applications menu

**draw.io version (In the Help->About menu of the draw.io editor):**

Install from 14.4.3. over 13.9.9

**Desktop (please complete the following information):**
 - OS: Debian 4.19.171-2 with gnome-shell 3.30.2

**Comment by davidjgraph** [comment]
Cannot repeat
