### ISSUE TITLE
Run actions sequentially in custom links

### ISSUE THREAD

**Issue by gbolmier** [jgraph/drawio#1861]
Hey there, thank you for the awesome work!

Custom links are a really cool feature and I was wondering if it would be possible to define multiple actions to run sequentially, i.e. one after another instead of all at the same time. Adding a `delay` parameter would also be great :)

I haven't been able to find a way to do so, is that something you may consider to implement?

**Comment by alderg** [comment]
Thanks for the report. This will be added in the next release. Please use [this tool](https://jgraph.github.io/drawio-tools/tools/link.html).
