### ISSUE TITLE
Question: Parameters for creating new diagrams

### ISSUE THREAD

**Issue by bjohas** [jgraph/drawio#1863]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Question / Describe the solution you'd like**

Is it possible to add parameters to the new diagram creation to avoid the 2-3 clicks necessary to create a new diagram?
(I've seen this: https://www.diagrams.net/doc/faq/supported-url-parameters)
```
https://app.diagrams.net/?storein=google&googledrive=new&useroot=true
```
or even better
```
https://app.diagrams.net/?storein=google&googledrive=new&folder=google_folder_id
```
Many thanks!

**Comment by davidjgraph** [comment]
Yup, makes sense. You can skip one step with https://app.diagrams.net/?mode=google

**Comment by bjohas** [comment]
Thanks!

A couple more thoughts: I would also like to circumvent the template selection - is that possible?

Also, the google dialogue offers several users.

So maybe one would even need:
```
https://app.diagrams.net/?mode=google&googledrive=new&user=somebody@google.com&folder=google_folder_id&template=none
```

Many thanks for looking at this!

**Comment by alderg** [comment]
You could try https://diagram.new, this moves all the clicks to when the diagram is saved.

**Comment by bjohas** [comment]
Yes, that's helpful - many thanks. We normally want a diagram in a collaborative situation, so having a link that can be shared...  so the idea would be to create the diagrams in a GDrive folder, that is publicly accessible!

**Comment by alderg** [comment]
When you create a new diagram in Google Drive in a specific folder, an URL of the form https://app.diagrams.net/?state=... is generated. You can append &splash=0 to that URL to bypass the template selection and create a new file in the given folder and for the given user ID in the next version. An optional &title=... parameter can be added to specify the filename.

**Comment by bjohas** [comment]
Thanks - that's very helpful. Just to double check, the splash=0 is only for a future version. That is the same for title=ABC, right? I just tried with title=ABC, and it doesn't seem to do anything [i.e., suspicion that it's for future version].
Thanks!

**Comment by davidjgraph** [comment]
Check you're running 14.4.7

**Comment by bjohas** [comment]
So when I go to help on the web-based app, it says 14.4.4. How would I upgrade that (being the web app) to 14.4.7?  Is there a configuration options somewhere? confused 😀

**Comment by davidjgraph** [comment]
It's a PWA, it will cache locally. Open https://app.diagrams.net/clear.html to flush.

**Comment by bjohas** [comment]
Fantastic - thanks!! It works!
