### ISSUE TITLE
Support alignment change in ER diagrams

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1865]
At the moment, there is no way to align in ER diagrams: tried to move each border separately (longer text might be shown incorrectly) and tried to align all at once.

Asked in https://drawio.atlassian.net/browse/DID-1840

The same issue in diagrams.net online.

![align](https://user-images.githubusercontent.com/44292306/110333400-d756d400-8021-11eb-8513-6cc01797ee2d.JPG)

**Comment by alderg** [comment]
Fixed with new ER tables.
