### ISSUE TITLE
plugin don't work in GitHub pages

### ISSUE THREAD

**Issue by flaviodonze** [jgraph/drawio#1866]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Plugins don't work in GitHub pages because of the _/plugins_ path which will lead to:
_https://jgraph.github.io/plugins/_
instead of
_https://jgraph.github.io/drawio/src/main/webapp/plugins/_

**To Reproduce**
1. open github pages: https://jgraph.github.io/drawio/src/main/webapp/index.html
2. in the menu click on: Extras -> plugins...
3. add a plugin e.g. "text", press "apply" and refresh page
4. error in console: "GET https://jgraph.github.io/plugins/text.js net::ERR_ABORTED 404 (Not Found)"

- draw.io version 14.4.4

![grafik](https://user-images.githubusercontent.com/24522870/110342487-bc895d00-802b-11eb-8a34-ee0ef56096af.png)

**Comment by jkuczek15** [comment]
Just a suggestion; but for this instance of Github pages could you try to manually create the folder structure for your repository such that you have src/main/webapp/plugins?

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
