### ISSUE TITLE
Add alternative frame to UML

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#1868]
https://softwareengineering.stackexchange.com/questions/397103/handle-alternative-frame-in-sequence-diagram

Whole block of "alt" including centre dividing line.

**Comment by egrimate** [comment]
The recent UML 2.5 update contains a shape like this:
![image](https://user-images.githubusercontent.com/2485177/113325866-3d7d0100-9319-11eb-825f-8590114da792.png)
