### ISSUE TITLE
Azure is missing some icons

### ISSUE THREAD

**Issue by JohnBloom** [jgraph/drawio#187]
I am not sure what the exhaustive list is but I know that I was looking for the following and couldnt find them:

Functions
Logic Apps
Event Grid

I think the list in draw.io is from this MS list: https://docs.microsoft.com/fi-fi/azure/architecture/resources/diagrams

That list is missing a lot of services. I am not sure what the process is to transform icons to the needed xml but I would be willing to chip in if someone had a processes to convert icons to the proper format.

**Comment by davidjgraph** [comment]
https://trello.com/c/KGHahkDS/280-add-missing-azure-icons
