### ISSUE TITLE
Connector properties not used with automatic connector creation

### ISSUE THREAD

**Issue by jikuja** [jgraph/drawio#1871]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Automatic connector creation does not create arrows with original properties. Usage of arrows with properties is really slow because of workarounds needed for this.

**To Reproduce**
1. Add C4 into a canvas
2. Select an arrow and select `Set as Default Style`
3. Add shapes with automatic connector creation using connect and clone tool of the existing shape
4. New arrow is created without label and properties and therefore is useless for e.g. C4 architecture diagrams

**Expected behavior**
The app should create an exact copy of the default connector style. Connector without label and properties is useless.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 1.4.7
- Chome

**Desktop (please complete the following information):**
 - OS: OS X
 - App Version: 14.4.3 

**Workaround**
Setup advanced connectors manually.

**Comment by jikuja** [comment]
here is activity: **ping**

**Comment by davidjgraph** [comment]
Closing. Label and properties are not part of style.

**Comment by jikuja** [comment]
I think this is something to consider as a feature for avoiding repetitive strain when adding complex arrows from plugins.
