### ISSUE TITLE
Rotation in 3D?

### ISSUE THREAD

**Issue by Syzygianinfern0** [jgraph/drawio#1873]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Is there any way I can achieve rotation in the z-axis using the cube tool? Check out the images underneath for a visual representation of my query. 

| What I can Do 	| What I Want to Do 	|
|---------------	|-------------------	|
|     ![image](https://user-images.githubusercontent.com/31875325/110973732-9f35f500-8383-11eb-9d12-c3a6c6ceb7fd.png)   | ![image](https://user-images.githubusercontent.com/31875325/110973804-ba086980-8383-11eb-8a7b-ffc3f465ed1d.png) |

**draw.io version (In the Help->About menu of the draw.io editor):**

- 14.4.8 (current website version)

**Comment by davidjgraph** [comment]
No

**Comment by leleyueyue** [comment]
Can you add this function?
