### ISSUE TITLE
Copy-paste should duplicate (and did duplicate?)

### ISSUE THREAD

**Issue by bjohas** [jgraph/drawio#1874]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

Copy-paste should duplicate (and did duplicate?)

**To Reproduce**

- Select an object
- Press ctrl-c
- Press ctrl-v

Nothing happens.

**Expected behavior**

I might be confused, but I believe that previously the above actions would have led to the object being duplicated.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 14.4.8]

**Comment by bjohas** [comment]
Hmmm... It seems that keyboard shortcuts for ctrl-x/c/v aren't working. Is anybody else seeing that?

**Comment by alderg** [comment]
Works for me. What browser and OS?

**Comment by editfund-founder** [comment]
Works for me. 
Browser:Chromium 87
OS:Win10

Works for me. 
AutoHotKey 1.1.33.04

**Comment by bjohas** [comment]
Thank you for your comments! It was due to a strange interaction with the 'locate mouse pointer' function in Ubuntu, see https://github.com/jgraph/drawio/issues/1875.

Thanks again!
