### ISSUE TITLE
Ctrl-v doesn't work after copy.

### ISSUE THREAD

**Issue by bjohas** [jgraph/drawio#1875]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**
- select object
- press ctrl-c
- deselect object
- press ctrl-v
- Nothing happens

**Expected behavior**

I expected the object to be pasted. The right-click menu with paste-here works. However, under edit, ctrl-v is not greyed out, but doesn't work.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 14.4.8]

**Additional context**

Might be related to https://github.com/jgraph/drawio/issues/1874.

**Comment by bjohas** [comment]
Hmmm... It seems that keyboard shortcuts for ctrl-x/c/v aren't working. Is anybody else seeing that?

**Comment by danielway** [comment]
I am unable to reproduce with 14.4.8 on macOS 11.2.3 Safari 14.0.3.

https://user-images.githubusercontent.com/1724257/111348754-7e54f480-864e-11eb-9196-075da91665ff.mov

**Comment by bjohas** [comment]
Thanks for looking into it - let me try to figure out what the problem might be on my side...

**Comment by bjohas** [comment]
Right - thanks again, for looking into it. The problem was to do with the accessibility setting for Ubuntu to highlight the mouse pointer: 
```
org.gnome.desktop.interface locate-pointer  true                                                                                                                           
org.gnome.mutter    locate-pointer-key      'Control_L'
```
It doesn't seem to matter for a bunch of applications (inc. chrome), but somehow for drawio it matters. In any case, with using the `locate-pointer-key` setting (in `gsettings`) the action can be moved to another key, which then fixes this.

Thanks again!
