### ISSUE TITLE
Insert image by URL

### ISSUE THREAD

**Issue by bjohas** [jgraph/drawio#1876]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

In Google Docs/Slides, the insert-diagram or new-diagram workflows are cumbersome. 

**Describe the solution you'd like**

Often I'm editing in the diagrams app already (and with this https://github.com/jgraph/drawio/issues/1863, I can also easily create new diagrams in folders in drive). However, it's then a pain to have to navigate to that diagram the add-on UI in Google Docs/Slides.

I would love to have an option to 'insert from URL'. This would mean:
- In the Google Docs/Slides plugins, have an option "Insert via APP-URL". This should allow pasting in the URL (https://app.diagrams.net/#..., together with an optional page number) or the 'tab url' (https://viewer.diagrams.net/?page-id=...#...)
- Ideally, there would be an option in app.diagrams.net, for right-click on tab called something like 'copy APP-URL'.

**Describe alternatives you've considered**

At the moment, I do this manually:
- drop random image (e.g. a tiny screenshot) into Doc/Slide
- in diagrams.net, right-click on tab -> link -> OK, then copy.
- adjust the copied 'viewer url' to be an 'app url' [which can be accellerated through a clipboard transformation script]
- back to google doc, ctrl-k to assign url, update selected diagram.

Now - that looks kinda convoluted, but it's actually faster for me to do than the insert image (which sometimes hangs).

**Comment by davidjgraph** [comment]
This isn't possible, we can only get a handle on the file via the user interaction in the picker. A straight URL often will have a permissions issue.

**Comment by jordigarcl** [comment]
This is use case is really interesting. Why not enable it only for publicly-shared diagrams stored in Google Drive? That would enable users to render public diagrams.net diagrams in places that don't admit JS (e.g. Github READMEs) while making it easier to share and edit.
