### ISSUE TITLE
Text Field Bug in Flowchart Manual Operation

### ISSUE THREAD

**Issue by Deraidos** [jgraph/drawio#1877]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When you add text to a Manual Operation shape from Flowchart, it should be shown and wrapped in the middle, but it shows right below the shape

**To Reproduce**
1. Go to Flowchart category and choose Manual Operation
3. Click 2x and type something
4. Text shows below the shape

**Expected behavior**
The text should be displayed inside the shape

**Screenshots**
![image](https://user-images.githubusercontent.com/19247488/111066057-a843d500-84ef-11eb-8cdf-971d132f0959.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 14.4.8

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2

**Additional context**
Happens in both web and Desktop version

**Comment by mararad** [comment]
Hi,

select it, click Text tab and choose "Center" under "Position". Does it help?

Regards,
![position](https://user-images.githubusercontent.com/44292306/111129953-f7811880-8576-11eb-9561-43ab044a77b2.JPG)

**Comment by Deraidos** [comment]
> Hi,
> 
> select it, click Text tab and choose "Center" under "Position". Does it help?
> 
> Regards,

Hi.
Thanks! That fixed my problem. In my opinion it should be set to "Center" by default.

**Comment by egrimate** [comment]
Will be fixed in next release
