### ISSUE TITLE
Add "bulk terminal" anchors to NMOS and PMOS devices (Electrical/Transistors)

### ISSUE THREAD

**Issue by ftorres16** [jgraph/drawio#1881]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
In the current version, the Electrical/Transistors templates include symbols for NMOS and PMOS as three terminal devices. This is useful simplification for most cases, but MOS transistors physically have a fourth terminal called "bulk" (B). 

The B is usually connected to the "source" (S) terminal, but not always.
Circuit designers sometimes need to connect B to different voltages and in its current form draw.io doesn't provide a symbol with anchor points for it.

**Describe the solution you'd like**

I would like to have two extra devices included in the templates for NMOS and PMOS with bulk terminals. They could be named "NMOS Bulk", "PMOS Bulk", or "NMOS4", "PMOS4" (because they have 4 terminals). The former is preferred to match the "MOSFET No Bulk" symbols.

The implementation can be very simple, you just need to add a horizontal line in the center of the transistor with an anchor point at the end as shown [in this drawing](https://imgur.com/c0S7wsf).

A good reference implementation is shown in the first two symbols of page 82 of [the Circuitikz manual](https://circuitikz.github.io/circuitikz/circuitikzmanualgit.pdf).

**Describe alternatives you've considered**

In the past, I have manually drawn the bulk connections on top of the symbol, but this is not convenient because you don't have anchor points and it is error prone.

I considered creating new custom symbols for my personal use, but I think the standard library could benefit from it.

I can continue using circuitikz for my circuit diagrams, but describing drawings with text is slower and less convenient. it is a very different use case.

**Additional context**

**Comment by egrimate** [comment]
Will be in next release
