### ISSUE TITLE
Default diagram view options (grid, page view)

### ISSUE THREAD

**Issue by danielway** [jgraph/drawio#1882]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When I start a diagram, the first thing I do is disable the "View > Grid" and "View > Page View" options. I prefer an open canvas to a sheet-of-paper.

**Describe the solution you'd like**
I'm interested in switching these options off by default. It appears that there is configuration functionality today in "Extras > Configuration", but I do not see either of the settings I mentioned above as [configuration options](https://www.diagrams.net/doc/faq/configure-diagram-editor).

**Describe alternatives you've considered**
I considered forking the repository and introducing these options myself, but I can imagine them being of benefit to others too.

**Comment by mararad** [comment]
Hi,

related to defaults, my suggestion would be to check this article: https://drawio.freshdesk.com/support/solutions/articles/16000042546-supported-url-parameters 
but not sure if it'll suit your needs completely.

Kind regards,

**Comment by danielway** [comment]
That's very helpful @mararad, thank you! I was able to turn off page view, but I wasn't seeing an option for disabling the grid. Do you know of an option for this?

These were my parameters to disable page view (and default to browser storage):
`https://app.diagrams.net/?pv=0&mode=browser`

**Comment by alderg** [comment]
We'll add grid=1/0 in the next release.
