### ISSUE TITLE
Enable resizing multiple objects simultaneously

### ISSUE THREAD

**Issue by danielway** [jgraph/drawio#1883]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
If I have multiple identically-sized objects, I may want to resize them simultaneously to ensure that their dimensions remain identical. I am currently unable to do this and instead must resize each individually or copy/paste the correct sized object.

**Describe the solution you'd like**
If I have multiple objects selected, I would like resize operation on them to be performed on all selected objects. The simplest scenario involves two identically sized objects having their width adjusted. If I drag the first object's size to enlarge it, the second object would mirror this change.

<img width="208" alt="image" src="https://user-images.githubusercontent.com/1724257/111347457-3bdee800-864d-11eb-88b8-35cb45c7dd8e.png">

**Describe alternatives you've considered**
Alternatively I can copy/paste my objects once resized or resize them individually. The first option is not ideal because it requires deleting and recreating the objects once I've resized one of them, and the second is not ideal because it's time-consuming and error-prone.

**Comment by mararad** [comment]
Hi, you can try the following:
1. Select a resized shape
2. Click "Copy size" (Format panel on the right)
3. Select all shapes you would like to resize
4. Click "Paste size" in Format panel

That way you don't have to resize them individually or delete them.

Does this help?

Regards,

**Comment by danielway** [comment]
Thanks for the response @mararad! That's helpful, I was unaware of that feature.
