### ISSUE TITLE
How to store to private gitlab

### ISSUE THREAD

**Issue by Hargeek** [jgraph/drawio#1884]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I want to privatize the deployment of Drawio with Docker，And configure the GitLab private storage
I have read all the other issues，The following environment variables are configured：
        - name: DRAWIO_BASE_URL
          value: "https://draw.mydraw.com"
        - name: DRAWIO_GITLAB_URL
          value: "https://gitlab.mygitlab.com"
        - name: DRAWIO_GITLAB_ID
          value: "422b89338c77a259fe5e778b852278321a630f338934bc5bd097bf8454237613"
        - name: DRAWIO_CSP_HEADER
          value: "default-src \'self\'; script-src \'self\' \'unsafe-inline\'; connect-src \'self\' https://gitlab.mygitlab.com; img-src * data:; media-src * data:; font-src * about:; style-src \'self\' \'unsafe-inline\';"

But it will eventually jump to the official Gitlab address:https://gitlab.com

The other problem is how to store to private gitlab

- draw.io version 14.4.9

**Comment by Hargeek** [comment]
I was desperate for someone to answer my questions

**Comment by Hargeek** [comment]
I want someone to communicate with me about this problem

**Comment by Hargeek** [comment]
Why delete my question？

**Comment by davidjgraph** [comment]
I didn't delete your question, your question is still there. However, your inappropriate demands for attention were deleted.

**Comment by Hargeek** [comment]
> I didn't delete your question, your question is still there. However, your inappropriate demands for attention were deleted.

So please answer my question

**Comment by davidjgraph** [comment]
No.

**Comment by Hargeek** [comment]
awesome
