### ISSUE TITLE
Backend ASP.NET integration, save file and load file from local server

### ISSUE THREAD

**Issue by epasinetti** [jgraph/drawio#1885]
Is it possible to disable all "clouds" features and add the possibility to save and load file from/to a local server where the application is hosted ?

**Comment by davidjgraph** [comment]
This project is the client only. You have to supply storage.

**Comment by epasinetti** [comment]
> This project is the client only. You have to supply storage.

Ok the storage is not a problem , but where can I attach event to send the editor output to an API that store the data on my server ?
