### ISSUE TITLE
Unexpected size when exporting to pdf with LaTeX formula

### ISSUE THREAD

**Issue by kqwyf** [jgraph/drawio#1886]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

When there is LaTeX formulas in the diagram, the exported PDF sometimes is of an extra margin (although I set the margin in export settings to be 0).

BTW, the reason of the bug seems to be that when calculating the crop size of the PDF, size of the bounding box of the raw text (rather than the rendered LaTeX formula image) is used in calculation. To verify this reason, try to add some newlines into the text box (do not break the LaTeX syntax), and the size of the exported PDF changes.

**To Reproduce**
1. Create a new file and enable math mode.
2. Create a text box and change its style to some one which has borders. This is preferred to observe the bug.
3. Write "\\(\text{abc}\pi\\)" in the text box. When the focus leaves, it should be rendered as 
![image](https://user-images.githubusercontent.com/22416169/111629047-d85ee100-882b-11eb-88e5-d8f22c46e10f.png)
4. Export the file to PDF.

**Expected behavior**
There is no blank around the box in the exported PDF.

**draw.io version (In the Help->About menu of the draw.io editor):**

- 14.4.3 (desktop version)

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser: Builtin (draw.io desktop version)
 - Version: Last updated on Mar.18

**Additional context**
Reproduce: 
[test.zip](https://github.com/jgraph/drawio/files/6164234/test.zip)

In the zip archive, test.drawio reproduce the bug (exported as test.pdf), while test2.drawio adds some newlines into the text box (exported as test2.pdf).

**Comment by mararad** [comment]
Reproduced in Chrome Incognito and diagrams.net 14.4.9 and in desktop 14.4.3

**Comment by alderg** [comment]
As a workaround, try using Hidden, Block or Width under Style, Property, Text Overflow for the cell:

<img width="233" alt="Screenshot 2021-03-30 at 13 48 01" src="https://user-images.githubusercontent.com/921200/112984238-f0edc600-915e-11eb-9e59-a891929243a1.png">

**Comment by phuntast1c** [comment]
For me, checking the „Resizable“ property and adjusting the size of the bounding box according to the symbol size has helped.
