### ISSUE TITLE
Image Too Big Inconsistencies and Improvements

### ISSUE THREAD

**Issue by nateSumi** [jgraph/drawio#1887]
A process that drawio is particularly well suited for is marking up engineering drawings, floor plans, and schematics. The grid snapping, line drawing, and shape editing is excellent for this purpose and the program is accessible from many machines.

One thing this requires, however, is importing that diagram as an image into Draw.io. There is a size limitation on importing images that is confusing and unclear; many are familiar with the "Image too Big" error message upon importing <1MB images. It's difficult to find what that size limitation actually is, and it feels completely arbitrary considering an image can be sliced into smaller pieces, imported onto a diagram at full resolution, then manually stitched together.

It would be amazing to:
1) Have a well-defined image size limit that can be adjusted and
2) Have the ability to import a single, large image instead of going through a manual stitching process.

**Comment by mararad** [comment]
Hi,

Meanwhile you could try the following as a workaround:
* Drag&drop an image and choose Resize (if that suits your needs)
* You can try to host images somewhere e.g. https://imgur.com/upload and when an image is uploaded,
right click - "Copy image address" and then link it in a diagram via URL (click "+" in the toolbar > Image)

This way file size should be smaller cause only image address is added, not the image itself.

Hopefully something will help as a workaround.

Regards,

**Comment by nateSumi** [comment]
This is a helpful workaround, however it is not effective for proprietary documents that should not be shared on the web. A fully local solution would be ideal.

**Comment by davidjgraph** [comment]
@nateSumi where do you store the diagrams?

**Comment by nateSumi** [comment]
@davidjgraph we store them in the company's Google Drive directories. Again, part of the problem is the lack of documentation and understanding where this limitation comes from. It's especially odd considering stitched together images are just fine and show no detectable performance limitation.

**Comment by iamtekson** [comment]
I got the following error when I tried to upload my draw.io file to Github. Why it has only a 1 MB size limit? How can we increase it?
![image](https://user-images.githubusercontent.com/39838116/124247309-f5ee5700-db4b-11eb-95d7-c33752617e8a.png)

**Comment by wafflook** [comment]
![Untitled Diagram](https://user-images.githubusercontent.com/98066622/154863716-ec229f1e-4384-4b0c-9402-9184bbc2ebf6.jpg)
I often use draw.io to paste screenshots of web services that I am developing.
The images I paste are long in length and large in file size. And I get the error message "Image too big". oh...no...
I solved the problem by running DRAW.IO on my own machine, not in the cloud, and changing the value of the options setting (the default is a 1MB image file size limit).

rawio\src\main\webapp\js\diagramly\EditorUi.js
``` javascript
/**
 * Maximum allowed size for images is 1 MB.
 */
EditorUi.prototype.maxImageBytes = 10000000;
```

**Comment by tbilen** [comment]
I'm using draw.io local app on my Mac.  Turns out you can add this to the Extras > Configuration screen and get past the absurdly low 520 pixel default max image size:
 
{
  "maxImageSize": "10000",
  "maxImageBytes": "30000000"
}
 
Found solution here:
https://gist.github.com/JimiSweden/329242731d07da2303826a6983f9e345

**Comment by undefine4080** [comment]
> I'm using draw.io local app on my Mac. Turns out you can add this to the Extras > Configuration screen and get past the absurdly low 520 pixel default max image size:
> 
> { "maxImageSize": "10000", "maxImageBytes": "30000000" }
> 
> Found solution here: https://gist.github.com/JimiSweden/329242731d07da2303826a6983f9e345

thanks! it works

**Comment by thibaultmol** [comment]
I guess I'll also have to use this local workaround but it's frankly ridiculous if this doesn't get pullrequested into the actual project.
I understand it might have performance impacts for some people, but that's up to the user to decide, they get the prompt asking them to resize anyway, if the user says no, that's their choice

**Comment by anton-bushuiev** [comment]
> I'm using draw.io local app on my Mac. Turns out you can add this to the Extras > Configuration screen and get past the absurdly low 520 pixel default max image size:
> 
> { "maxImageSize": "10000", "maxImageBytes": "30000000" }
> 
> Found solution here: https://gist.github.com/JimiSweden/329242731d07da2303826a6983f9e345

Thanks! It also works in a cloud 🥳!

**Comment by Sypros** [comment]
> I'm using draw.io local app on my Mac. Turns out you can add this to the Extras > Configuration screen and get past the absurdly low 520 pixel default max image size:
> 
> { "maxImageSize": "10000", "maxImageBytes": "30000000" }
> 
> Found solution here: https://gist.github.com/JimiSweden/329242731d07da2303826a6983f9e345

Thanks. This should be default.

**Comment by JordanWarne04** [comment]
it's kind of annoying that there's no way to simply set the max upload limit :/

**Comment by alderg** [comment]
Both limits can be set in Extras > Configuration (or via `DRAWIO_CONFIG` in self-hosted installs), e.g.:

```json
{"maxImageBytes": 5000000, "maxImageSize": 2000}
```

`maxImageBytes` is the maximum file size in bytes (default 2000000) and `maxImageSize` the maximum width or height in px (default 1200).
