### ISSUE TITLE
Using multiple Google accounts

### ISSUE THREAD

**Issue by aleksandrserbin** [jgraph/drawio#189]
Suppose I have 2 Google Accounts and I am logged in on both of them:

Account#1 is default Google Account
Account#2 

I log in to draw.io using Account#2 and suggested to load diagram from Account#2's drive.
Later I click to Open From -> Google Drive:

Expected:
I have file to select from Account#2's drive

Actual:
I have files to select from Account#1's drive

Setting `authuser = -1` always may be the option, but it will probably damage UX a lot.

**Comment by oscardssmith** [comment]
I've run in to this as well, a fix would be great.

**Comment by ashrafteleb** [comment]
Multiple Google accounts are supported currently
