### ISSUE TITLE
Snap to grid does not function on vertices (polyCoords) of polyline 

### ISSUE THREAD

**Issue by gordonCharles** [jgraph/drawio#1891]
When moving the vertices (polyCoords) of a polyline the coordinates do not snap to the grid as other objects do.

To reproduce

1) Set grid (most obvious is to set to a larger value)
2) Search for polyline
![image](https://user-images.githubusercontent.com/12214361/111882286-1403c300-8972-11eb-9e3a-83bc05fa08fc.png)
3) instantiate polyline
4) select vertex (PolyCoord)
5) move vertex (PolyCoord)

The vertex moves on some form of a grid; however, it is not the grid specified.

It would also be useful to have the x/y location of the vertex displayed when selected.

**Comment by mararad** [comment]
Hi, 

"It would also be useful to have the x/y location of the vertex displayed when selected."
When you select polyline, click Arrange tab on the right and check Postions. Does it help?

"The vertex moves on some form of a grid; however, it is not the grid specified."
Check if you are having other objects around. If you do, see if polyline align with them (which is default behaviour).

Regards,

**Comment by gordonCharles** [comment]
_"It would also be useful to have the x/y location of the vertex displayed when selected."
When you select polyline, click Arrange tab on the right and check Postions. Does it help?_

The Arrange tab shows the position and size of the object but not the position of the selected vertex.

![image](https://user-images.githubusercontent.com/12214361/112194468-1fe7c300-8bc6-11eb-8052-9f55480c5c08.png)

_"The vertex moves on some form of a grid; however, it is not the grid specified."
Check if you are having other objects around. If you do, see if polyline align with them (which is default behaviour) and untick Guides in Format panel on the right (when nothing is selected)_

I opened a blank document, set the grid to 10mm, instantiated a polyline and unticked the Guides in the Format panel as shown below.  The vertices still do not snap to the specified grid.

![image](https://user-images.githubusercontent.com/12214361/112194790-7bb24c00-8bc6-11eb-889b-6392255a1f7d.png)

Regards,

Gordon

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
