### ISSUE TITLE
Custom link support in tooltip

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1892]
"Tooltips support HTML with embedded links (<a href=...)
but do they support the same features as shape links (Edit|Link...)? If so, what is the link format? I've tried using the same  link format (data:page/id,.. and data:json/action,...) to no avail.
My use case requires multiple links in the tooltip popup along with explanatory text, hence the request. Ideally, this is accomplished with the right URL scheme to indicate the appropriate intra-document link/action."

https://groups.google.com/g/drawio/c/xJWPPfWSdBc/m/Msz3K_LiAwAJ

**Comment by alderg** [comment]
This will be added in the next release

**Comment by rvoyer** [comment]
This says it was completed but I don't see how to put a link in a tooltip other than the "Edit Link" which isn't quite what I need to properly document items in our diagrams and link off to further information about different subtopics.
