### ISSUE TITLE
cannot flip direction on a general curve

### ISSUE THREAD

**Issue by gordonCharles** [jgraph/drawio#1895]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Flip direction on a general curve is not supported

**To Reproduce**
1. Start with empty document
2. Instantiate a general curve and move one point to make it asymmetrical
3. Select object
4. Select <Arrange> -> <Direction> is not possible as direction is greyed out
5. Add another object, rectangle
6. Group the curved line and the rectangle
7. Select <Arrange> -> <Direction>  -> <Vertical> **There is no change in the object**
8. Select <Arrange> -> <Direction>  -> <Horizontal> **There is no change in the object**

**Expected behavior**
I would expect that any shape can be flipped in the horizontal or vertical direction.  It appears the curve is not one of them and mathematically I don't understand why this would be an issue.

**Screenshots**
Example of curve grouped with rectangle.
![image](https://user-images.githubusercontent.com/12214361/112196206-09426b80-8bc8-11eb-98b1-a38a007004db.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 14.4.9

**Desktop (please complete the following information):**
 - OS: OSX 10.13.6
 - Browser Chrome
 - Version 89.0.4389.90

**Comment by mararad** [comment]
Hi, 

Unfortunately it is not possible to flip a connector or group https://github.com/jgraph/drawio/issues/1139
Connectors can only be reversed under Arrange tab.

Kind regards,

**Comment by AP-TSP** [comment]
I just need to be able to flip a simple curve.
No group, no connectors, just plain splines.

Please consider to add this feature!

**Comment by mararad** [comment]
In addition to previous message of AP-TSP asked in DID-3785

"I draw a line like (1) and want to have a line like (2) (a mirrored version from (1) ).
With reverse, I would get the arrow like (3), which is not what I would need.
Of course, I can simply try to copy / mirror it myself, but it is 1. not handy nor fast and 2. pretty hard with curved connectors."
![curve](https://user-images.githubusercontent.com/44292306/143430693-e8a81f28-fca1-4859-b537-dfe6e7e6a96f.png)

**Comment by balaji-ch** [comment]
Please implement this feature.

**Comment by balaji-ch** [comment]
> In addition to previous message of AP-TSP asked in DID-3785
> 
> "I draw a line like (1) and want to have a line like (2) (a mirrored version from (1) ). With reverse, I would get the arrow like (3), which is not what I would need. Of course, I can simply try to copy / mirror it myself, but it is 1. not handy nor fast and 2. pretty hard with curved connectors." ![curve](https://user-images.githubusercontent.com/44292306/143430693-e8a81f28-fca1-4859-b537-dfe6e7e6a96f.png)
yeah, I too end up with a messed and twisted curves.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
