### ISSUE TITLE
Find/Replace in Minimal theme: not all buttons are visible

### ISSUE THREAD

**Issue by ImperiaGP** [jgraph/drawio#1896]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When you open the Diagrams.net application in Minimal theme and open the Find/Replace dialog, 4 buttons are displayed vertically. The 4th button (Replace All) however is not completely visible.

**To Reproduce**
1. Go to Extras -> Theme -> Minimal
2. Restart Diagrams.net
3. Go to Diagram -> Find/Replace

**Expected behavior**
All buttons visible

**Screenshots**
![image](https://user-images.githubusercontent.com/6501352/112203295-ade99b00-8c12-11eb-833c-bd720076104c.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 14.5.1]

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 86

**Comment by mararad** [comment]
Reproduced in 14.5.1 in Chrome Incognito.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
