### ISSUE TITLE
I just want to develop a plug-in to support the generation of SQL and description documents from ER diagrams.

### ISSUE THREAD

**Issue by kevin-penn** [jgraph/drawio#1897]
I just want to develop a plug-in to support the generation of SQL and description documents from ER diagrams.
Where can I get help documentation？

**Comment by HePeng11** [comment]
hi @davidjgraph , me too, i download this repository source and want to study how the lib I can use, but found nothing just a compiled(or confused) main js file named "app.min.js", it's really hard to read and understand. why you can't publish the complete source files , it's really open-source ?

**Comment by HePeng11** [comment]
![image](https://user-images.githubusercontent.com/23466980/112454844-0eecac80-8d94-11eb-8e13-7cb1c3f30d76.png)

**Comment by davidjgraph** [comment]
That's the built minified files, see https://github.com/jgraph/drawio/tree/master/src/main/webapp/js/diagramly
