### ISSUE TITLE
on-prem aspect drawio macros not correctly migrated to cloud

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#1898]
draw.io for Confluence on-premise has an aspect/filter mode where a particular page/layers combination can be set for to view an existing diagram.

On both cloud and server there are standard drawio macros and embed drawio macros. The problem is on server the standard macro provides the aspect functionality, but it's the embed drawio macros that provides it on cloud.

We need a step that either tells cloud to convert these, or to convert them on server prior to migration.

Need to be converted to embed drawio on cloud for aspect. Do we need server to add something to zip, or can cloud import handle it entirely?

**Comment by ashrafteleb** [comment]
Fixed. After import, run "draw.io re-indexing"
