### ISSUE TITLE
Do App has constraints like Figma? How change behavoir on resize parent

### ISSUE THREAD

**Issue by akaDJon** [jgraph/drawio#1899]
**Is your feature request related to a problem? Please describe.**
How change behavior sizing of children block if resize parent (or group)? Figma has constraints for it.

I do these examples:
I'am resizing container (dashed black line) and get problem with block (solid blue line)
![image](https://user-images.githubusercontent.com/19344497/112714022-7d4f7d00-8f02-11eb-9d7e-4ff0278fa09c.png)

---------------
This example in figma:
![image](https://user-images.githubusercontent.com/19344497/112714391-601bae00-8f04-11eb-8bfc-286f51539199.png)

Left Block (Solid Blue Line) has following options:
![image](https://user-images.githubusercontent.com/19344497/112714211-72e1b300-8f03-11eb-8580-ee2f4ae51189.png)

Right Block (Solid Black Line) has following options:
![image](https://user-images.githubusercontent.com/19344497/112714227-7b39ee00-8f03-11eb-9e93-1e32b8eaa8b5.png)

Container (Dashed Black Line) has following options:
![image](https://user-images.githubusercontent.com/19344497/112714237-94429f00-8f03-11eb-84f0-7a225b08e5c8.png)

---------------
article in figma https://www.figma.com/best-practices/tips-for-using-constraints-in-your-workflow/

**Comment by mararad** [comment]
Hi,

draw.io doesn't support constraints as Figma does and at the moment, there isn't a solution that suits your needs completely.

Kind regards,

**Comment by akaDJon** [comment]
Thanks for answer, Do you have any plans for develop this feature? This solution (Frame + Constraints for change sizes / Group for scale) more flexable and useful than Draw.IO's "scale or not change sizes".
Or not?

**Comment by davidjgraph** [comment]
This item is not planned.

**Comment by akaDJon** [comment]
It's a pity! But your system still the best. Thanks for your job
