### ISSUE TITLE
URI Malformed

### ISSUE THREAD

**Issue by Rafaspe** [jgraph/drawio#1901]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Tab company just crashed and it can't be recovered. Any copies made or recoveries result in URI Malformed.
Version history results in URI Malformed.

**To Reproduce**
1. Go to 'https://drive.google.com/file/d/1Q3HcoxmZlwDV0-7QKWSGS0AY9D8RTQPV/view'

**Expected behavior**
Tab company just crashed and it can't be recovered. Any copies made or recoveries result in URI Malformed.
Version history results in URI Malformed.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mararad** [comment]
Hi,

Could you re-check draw.io version you are using, please? 12.6.7 is very old (it's from 10-Feb-2020)

Also, you mentioned "Tab company just crashed and it can't be recovered. Any copies made or recoveries result in URI Malformed." How did you try to recover diagrams?
