### ISSUE TITLE
Find/Replace box in 14.5.1 don't search in metadata

### ISSUE THREAD

**Issue by goamanu** [jgraph/drawio#1902]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Until ver. 14.5.1. I could search in metadata by pressing CTRL-F (or Search box). Practically I constructed my diagrams around that concept. The fact that I cannot search metadata since 14.5.1 renders all my diagrams useless. Can you advise how can I search in metadata?
Also can you tell me if there is a posibility to display all the metadata at once (as opposed to mouse-over tooltips)?
Thank you!

**To Reproduce**
1. Go to 'Edit'
2. Click on 'Find/Replace'

**Expected behavior**
Search metadata, like the former search box.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [14.5.1] - standalone

**Desktop (please complete the following information):**
 - OS: [Windows 10]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
