### ISSUE TITLE
Google Drive authentication brings repeat 401 error

### ISSUE THREAD

**Issue by robertandrews** [jgraph/drawio#1903]
Unable to authenticate with any Google Drive account.

**Comment by davidjgraph** [comment]
Details?

**Comment by robertandrews** [comment]
> Details?

What do you need?

**Comment by davidjgraph** [comment]
Browser/version/operating system. Any browser extensions. What steps you performed, what results you saw.

Did a template not appear for this when you created the issue?

**Comment by robertandrews** [comment]
Chrome 89.0.4389.90 (Official Build) (x86_64)
Mac OS 10.14.6
Very many Chrome extensions

From both the i) start of Diagrams.net and ii) whilst in a diagram creation mode (File / Save As).
Choose Google Drive.
Use root folder? Yes.
Authorization required

<img width="410" alt="Screenshot 2021-03-31 at 12 26 16" src="https://user-images.githubusercontent.com/3158787/113137353-59e74380-921c-11eb-8c80-71be24fe1044.png">

Google Account picker appears. Many accounts for me. I pick one.
App clarifies two scopes, confirm.
Then HTTP error...

<img width="531" alt="Screenshot 2021-03-31 at 12 26 31" src="https://user-images.githubusercontent.com/3158787/113137362-5bb10700-921c-11eb-8548-b009a7666bc6.png">

Happens with multiple Google Accounts, each are GAFYD/Suite.

**Comment by davidjgraph** [comment]
Could you try incognito please?

**Comment by robertandrews** [comment]
> Could you try incognito please?

Works okay in Incognito. The only different thing was 2-step auth was sent.
