### ISSUE TITLE
Google Blocked Diagrams.net app in Authorize this app in Google Drive

### ISSUE THREAD

**Issue by VolodymyrBryskin** [jgraph/drawio#1905]
When I create a new chart in the version of diagrams.net app for the web, Google first asks me to enter the login and password to log in to the appropriate account, and then denies access with the message 

> This app is blocked
> This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.

  This state of affairs lasts longer than two weeks.

**Comment by davidjgraph** [comment]
Screenshot?

**Comment by VolodymyrBryskin** [comment]
[image: image.png]

[image: image.png]

[image: image.png]
[image: image.png]



[image: image.png]
