### ISSUE TITLE
(Electrical/Sources) Add square and triangular voltage sources

### ISSUE THREAD

**Issue by ftorres16** [jgraph/drawio#1907]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
In the current version, the Electrical/Sources library doesn't include symbols for square or triangular voltage sources. The waveform for the square wave exists in Electrical/Waveforms with the name "square_wave", and the "sawtooth" waveform is similar to the triangular waveform (though sawtooth and triangular are not exactly the same).

This sources are commonly used by circuit designers.

**Describe the solution you'd like**
I would like to have two more symbols in the Electrical/Sources templates for "Square" and "Triangular" voltage sources with the "square_wave" symbol from Electrical/Waveforms and a new triangular wave symbol.

Additionally, it would be nice to include a "sawtooth" voltage source with the "sawtooth" waveform from Electrical/Waveforms.

The difference between triangular and sawtooth is that the sawtooth has diagonal and vertical lines, whereas the triangular waveform has oblique diagonal lines.

I created [this diagram](https://imgur.com/cAiXH8W) to illustrate how the new symbols could look.

A good reference implementation is shown in the first two rows of section 3.8.6, page 56 of [the circuitikz manual](https://raw.githubusercontent.com/circuitikz/circuitikz/958798d63247f66f52c4feaf62f75a5c8dd63430/circuitikzmanualgit.pdf).

**Describe alternatives you've considered**
In the past, I have manually drawn these sources, by grouping different symbols. However, this is not convenient and is error prone. 

I considered creating new custom symbols for my personal use, but I think the standard library can benefit from it.

I can continue using circuitikz for my circuit diagrams, but describing drawings with text is slower and less convenient. It is a very different use case.

**Additional context**

**Comment by egrimate** [comment]
A shape with editable source type will be added in the next release.
