### ISSUE TITLE
Showing null for username when a diagram is saved to GitHub

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1910]
Tested in Chrome and FF in diagrams.net 14.5.7

![null](https://user-images.githubusercontent.com/44292306/113556852-5cbbad00-95fd-11eb-8577-61b72cf87e09.JPG)

**Comment by davidjgraph** [comment]
Unable to recreate, is original poster following this and can supply steps?

**Comment by mararad** [comment]
Original report sent here: https://www.reddit.com/r/ProgrammerHumor/comments/mj99z8/even_drawio_falls_prey/
I also get 404 error. All in the video. Tested in Chrome Incognito, 14.5.8 and Win 10 Pro 

https://user-images.githubusercontent.com/44292306/114012611-d904f900-9866-11eb-93b5-8bc1c0f97ae8.mp4
