### ISSUE TITLE
Not able to click 'select' while uploading a diagram add-in Word

### ISSUE THREAD

**Issue by puckhip** [jgraph/drawio#1911]
Hi there,

I am using draw.io as an add-in on Microsoft Word. I have used this application now for a few months, but I am only having this problem as of today. 
When I want to add in a diagram (connected with Google Drive) I cannot click on the 'select' button to open any diagram. I can see them all standing though, but it won't continue. Therefore I am also not able to see any diagram on the right side of the screen after selecting as I was used to before. 

More detailed explanation: 
1. I click on 'insert' within Microsoft Word
2. I click on 'Draw.io' Add-in 
3. Then I click on 'choose file on Google Drive'. All the diagrams are shown and I can click on any, but then I am not able to click on the button 'select' to insert the diagram. 

I already deleted and redownloaded the add-in on Microsoft Word. In addition, I also already logged off and signed in again with my microsoft account. I am using the MacBook Pro late 2015 with the latest edition of Microsoft 365.

I am hoping someone can help me solving this problem. 

With kind regards.

<img width="827" alt="Schermafbeelding 2021-04-06 om 15 28 51" src="https://user-images.githubusercontent.com/82030886/113718324-d088b300-96ec-11eb-987c-7327f9f39d51.png">
 
 

### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ashrafteleb** [comment]
Google added a new confirm dialog when a file is selected which doesn't work in Desktop environment, please use Online Office until we investigate this issue more

**Comment by puckhip** [comment]
@ashrafteleb Thank you for commenting this quick. Unfortunately, I also experience trouble within the Online Office. So if you have any kind of input to solve this problem within Draw.io, I would be very happy if you are able to speed things up. 
Thanks again! With kind regards.

**Comment by davidjgraph** [comment]
With office online doesn't clicking "ok" work?

**Comment by puckhip** [comment]
@davidjgraph In the online version I am able to 'select' which is not working in the offline version, but then it says there is no diagram available. Kind of weird as I have always used this exact diagram in the offline version and it is an actual diagram. In the image I have added, is shown a screen print of the online version of Microsoft Office. 


<img width="329" alt="Schermafbeelding 2021-04-06 om 16 04 26" src="https://user-images.githubusercontent.com/82030886/113723580-c74e1500-96f1-11eb-89f6-1e84763d1364.png">

**Comment by puckhip** [comment]
@davidjgraph @ashrafteleb 

I am not sure if any of you is able to help me out with this problem, but there has been an update on this case. Recently, the button for uploading a diagram with the use of Google Drive has been removed in the offline version of Microsoft Word. I have added a screenshot to elaborate. Only the buttons for uploading with the use of OneDrive and own device are visible. 
Is there a way to insert this diagram like I was used to before? Besides the online version, which is currently also not working, as I have mentioned before. 



<img width="425" alt="Schermafbeelding 2021-04-09 om 10 26 13" src="https://user-images.githubusercontent.com/82030886/114152001-052f8100-991e-11eb-9b90-86c84f4904e7.png">

**Comment by davidjgraph** [comment]
Yes, we had to remove Google Drive support for offline office. Google adding the confirm dialog broke the flow, there is no fix.

**Comment by ashrafteleb** [comment]
@puckhip Can you please give us more details on why the online version doesn't work. Is the error in the screenshot only affecting a single document or all? Can you create a new diagram and user it?

Thanks

**Comment by ashrafteleb** [comment]
Google fixed the issue and the Google Drive will be back in the next release
