### ISSUE TITLE
Add global switch to disable word wrapping and HTML labels

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#1912]

**Comment by FirbyKirby** [comment]
Is the proposed behavior of the global switch to "disable by default" or "disable unconditionally?" We'd like to prevent the existing default behavior of word wrapping and HTML labels by default, but still allow users to enable these features selectively.

**Comment by alderg** [comment]
Disbable by default.

**Comment by alderg** [comment]
Under Extras, Configuration enter ```{"simpleLabels": 1}``` or click [here](https://app.diagrams.net/#_CONFIG_UzV3UjUyKs7MLchJ9UlMSs0pBnJVjR0NVc1dAA==).
![Screenshot 2021-11-29 at 16 33 50](https://user-images.githubusercontent.com/921200/143896864-d0c4418a-64db-4240-b4cf-0d266149f64e.png)
