### ISSUE TITLE
Position of a line is not changed to mm in Format panel > Arrange

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1915]
Position of a line is not changed to mm i.e it stays in pt after View > Unites > mm is set.
Tested in Chrome Incognito and diagrams.net 14.5.8
It works for shapes.

![line positionv in mm](https://user-images.githubusercontent.com/44292306/113875716-5709c700-97b7-11eb-95b7-39f3273b2d0b.JPG)

**Comment by m-mohamedin** [comment]
Will be added in the next release
