### ISSUE TITLE
Export to vsdx with left-aligned text at incorrect location

### ISSUE THREAD

**Issue by paulkohout** [jgraph/drawio#1916]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Exporting a diagram to .vsdx with left-aligned text in a shape causes incorrect location of text.

**To Reproduce**
1. Go to [this example](https://viewer.diagrams.net/?highlight=0000ff&edit=_blank&layers=1&nav=1#RjVPJbsMgEP0aHyPZRkl6zn7poXWl5lZRMzFIYFwy3vr1BRviWFGknhjem403Q0S2qjsaWvFXzUBGacy6iOyiNE3IcmkPh%2FQjsl7HI1AYwbzTBGTiFzwY3GrB4DpzRK0limoO5rosIccZRo3R7dztouW8akULeACynMpH9FMw5CP6sown%2FASi4KFyEntG0eDsgSunTLd3ENlHZGu0xtFS3RakEy%2FoMsYdnrC3xgyU%2BJ%2BATO2%2BFcr4%2FPZ1PJP3wyJDufBZGipr%2F%2BAoXUmbb8NE4ySUoigHYvVTu043Ei443axVuPMDrhgibQtD8Mj4x2MfFDW6Lhm4pmJLt1wgZBXNHdvaHbIYRyXtLbFmqD9UDckaMAjdUxmSm7h2K0ErQNNbFx9AVn4efiFJWMh2Gm8SZsbvRhviqN%2Bo4pZ6Et0aXvdwneY7cHe%2FhOz%2FAA%3D%3D)
2. File->Export to->vsdx
3. Open the resulting vsdx in .vsdx viewer to see the text shows up out of place.

**draw.io version (In the Help->About menu of the draw.io editor):**
- 14.5.8

**Desktop**
- FF 87 Ubuntu 18.04

**Additional context**
The export seems to work successfully when `html=1` and `whiteSpace=wrap` are removed from the shape's style.

**Comment by mararad** [comment]
Hi,

I'm using Win 10 so probably not the best person to test, but I exported your example to vsdx, import it to Visio and align was correct as shown in the image. What .vsdx viewer are you using, please?

Thanks,

**Comment by paulkohout** [comment]
I exported a .vsdx with three different variants of diagrams.net:
* cloud (14.5.8): [test-cloud-14.5.8.vsdx.zip](https://github.com/jgraph/drawio/files/6278634/test-cloud-14.5.8.vsdx.zip)
* desktop (14.5.1): [test-desktop-14.5.1.vsdx.zip](https://github.com/jgraph/drawio/files/6278626/test-desktop-14.5.1.vsdx.zip)
* confluence plugin (9.5.11 on server 7.4.0): [test-confluence-server-7.4.0-plugin-9.5.11.vsdx.zip](https://github.com/jgraph/drawio/files/6278637/test-confluence-server-7.4.0-plugin-9.5.11.vsdx.zip)

I then tried opening those with:
* desktop (14.5.1)
  * all three had the text centered instead of left-aligned
    ![screenshot-desktop-14 5 1-text-centered](https://user-images.githubusercontent.com/21349865/114024773-726de400-9842-11eb-9926-612df70ef3d9.png)
* LibreOffice Draw (6.0.7.3)
  * all three had the text outside of the shape
    ![screenshot-libreoffice-draw-6 0 7 3-text-outside](https://user-images.githubusercontent.com/21349865/114024823-80236980-9842-11eb-856d-4d47902d5c8f.png)
* LucidChart plugin (4.4) for both Firefox (87.0) and Chromium (89.0)
  * .vsdx generated with desktop and confluence variants failed to open with a parse error
    ![screenshot-firefox-87 0-lucidchart-4 4-parse-error](https://user-images.githubusercontent.com/21349865/114026637-7569d400-9844-11eb-8d47-c8b4b4b101ff.png)
    ![screenshot-chromium-89 0-lucidchart-4 4-parse-error](https://user-images.githubusercontent.com/21349865/114026652-7864c480-9844-11eb-84a7-a02893911c7d.png)
  * .vsdx generated with cloud had the text outside of the shape
    ![screenshot-firefox-87 0-lucidchart-4 4-text-outside](https://user-images.githubusercontent.com/21349865/114026666-7ac71e80-9844-11eb-85df-afdc7e97da2d.png)
    ![screenshot-chromium-89 0-lucidchart-4 4-text-outside](https://user-images.githubusercontent.com/21349865/114026670-7c90e200-9844-11eb-918b-667dfe216f91.png)

**Comment by davidjgraph** [comment]
The vsdx export isn't intended to be a round-trip format to re-open with draw. Our test would be whether the output opens correctly in the native tool, which it does.

What, at a high level, are you trying to test/achieve?

**Comment by paulkohout** [comment]
Sure. Here's our use case:

We use the Confluence draw.io plugin. But we are required to produce Visio-compatible vsdx files. So I was looking for a way to export vsdx and verify it is viewable in Visio.

Clearly we could buy Visio licenses. But since we already purchased draw.io, buying licenses for Visio just seems to be a waste of the money we spent on draw.io.

So I was looking for a free tool that we could use to verify a vsdx file looks correct in Visio. How have others been solving this problem?

**Comment by ashrafteleb** [comment]
@paulkohout  You can verify vsdx files by opening them in Visio Online which is free (https://www.microsoft.com/en-ca/microsoft-365/visio/free-visio-viewer). 

![Screen Shot 2021-04-09 at 3 51 35 PM](https://user-images.githubusercontent.com/24944765/114233719-c44e6100-994b-11eb-9fdb-42ab9672c9fe.png)

**Comment by paulkohout** [comment]
Sure. Here's our use case:

We use the Confluence draw.io plugin. But we are required to produce Visio-compatible vsdx files. So I was looking for a way to export vsdx and verify it is viewable in Visio.

Clearly we could buy Visio licenses. But since we already purchased draw.io, buying licenses for Visio just seems to be a waste of the money we spent on draw.io.

So I was looking for a free tool that we could use to verify a vsdx file looks correct in Visio. How have others been solving this problem?

**Comment by ashrafteleb** [comment]
@paulkohout I don't know, maybe this one https://www.microsoft.com/en-us/download/details.aspx?id=51188 but I doubt they have something for Linux

**Comment by paulkohout** [comment]
Actually I had someone with Visio confirm that this is a real problem with the .vsdx export. They saw the same incorrect text alignment issue when opening a .vsdx file as described above.

**Comment by ashrafteleb** [comment]
@paulkohout We've tried in both Visio Desktop and Online. Both work as expected as shown above.

Please send us a screenshot of Visio with incorrect results in addition to the draw.io and vsdx file to re-test

**Comment by RealStitch** [comment]
Hi, I have this issue as well with the recent web and desktop edition of diagrams.net.
Please find attached files and screenshots
[Bugreport_drawIO.zip](https://github.com/jgraph/drawio/files/7583924/Bugreport_drawIO.zip)
![grafik](https://user-images.githubusercontent.com/94839600/142925088-10ceac02-c974-4075-bc4a-9a4256011efa.png)

**Comment by ashrafteleb** [comment]
Bug will be fixed in the next release

Thanks for the report
