### ISSUE TITLE
Custom action open to move to another tab is erased after copy/paste

### ISSUE THREAD

**Issue by chipbite** [jgraph/drawio#1919]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
For shapes with custom action in the link, of type open with page as parameter: When copy pasteing said shape (within same diagram and sheet, essentially to move), the open action is deleted. I also have a viewbox action in the list, and it is persisted. So this seems to apply only for the open action (maybe only with page target, to be tested).

**To Reproduce**
1. Create diagram with two sheets, add shape with custom action to navigate to the other sheet,  e g `data:action/json,{"actions":[{"open": "data:page/id,5QUA7mJ13ktVjbgl6bIQ"},{"viewbox":{"x": 0, "y": 0, "width": 1020, "height": 400}}]}`. Test it so it works as expected.
2. Select shape, do cut and then paste. CLick link and inspect link.

**Expected behavior**
* Clicking link takes you to the other page as expected.
* Inspecting link, it should remain as before.

**Actual result**
* Link no longer works.
* Link has been edited, the open part removed.

**Screenshots**
![image](https://user-images.githubusercontent.com/559199/114186811-96671d80-9947-11eb-8ec5-ac1041bb3905.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- web/latest (yeah, e g 14.5.9)

**Desktop (please complete the following information):**
 - OS: win10 / chrome Version 89.0.4389.114 (Official Build) (64-bit)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
