### ISSUE TITLE
Support a link indicator removal (gray box) when a shape with link is hovered 

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1925]
Support a link indicator removal when a shape is hovered in Confluence Cloud page view or make it possible to change the color of gray box. 

Asked in chat https://app.intercom.com/a/apps/fz6gxyi6/inbox/inbox/994666/conversations/55912901360978

**Comment by davidjgraph** [comment]
This request is declined, it does not fit into the scope of the functionality we're looking at for the app. Thanks for your feedback.
