### ISSUE TITLE
(Electrical / Transistors) Add support for IGBTs and improve BJTs

### ISSUE THREAD

**Issue by ftorres16** [jgraph/drawio#1926]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
In the current version, the Electrical/Transistors templates include symbols for BJT (NPN) and BJT (PNP) with a surrounding circle. Same as with MOS transistors, BJTs have a representation that is exactly the same without the circle, which is often preferred by circuit designers.

Additionally, there is no symbol for insulated gate bipolar transistors (IGBTs) which is a common device in power electronics.

**Describe the solution you'd like**
I would like to have two more symbols for BJT transistors without the surrounding circle, and two more symbols for IGBTs (NIGBT, PIGBT).

I created [this diagram](https://imgur.com/m84lbkU) to illustrate how the new symbols could look.

A good reference implementation is shown in [the circuitikz manual](https://raw.githubusercontent.com/circuitikz/circuitikz/958798d63247f66f52c4feaf62f75a5c8dd63430/circuitikzmanualgit.pdf) on the last row of page 75 (NPN), and the first (NPN), seventh (NIGBT) and eigth (PIGBT) rows of page 76.

**Describe alternatives you've considered**
I can manually draw symbols that resemble what I need for my personal use, but this is not practical and I think the standard library can benefit from it.

I can continue using circuitikz when I have to use these devices, but describing drawings with text is slower and less convenient. It is a very different use case. 

**Additional context**

**Comment by egrimate** [comment]
Will be in next release
