### ISSUE TITLE
Edit connection point values

### ISSUE THREAD

**Issue by cameron-interactive** [jgraph/drawio#1927]
Working with various line connections, using the fixed point connections work well, you get some feedback as to it's approximate position relative to the connected object, but it's not exact (just a percentage without decimal places), it's also fairly manual/finicky to get where you want it. 

It would be great if we could manually enter/modify these % values to the nth decimal place, so we can get all the lines and connections arranged consistently across a diagram.

**Comment by alderg** [comment]
Try Edit Style (Ctrl/Cmd+E) and modify entry-/exitX (relative horizontal position), entry-/exitY (relative vertical position), entry-/exitDx (absolute horizontal offset) and entry-/exitDy (absolute vertical offset).
