### ISSUE TITLE
API reference for plugin development

### ISSUE THREAD

**Issue by iceblu3710** [jgraph/drawio#1935]
I am looking to play around at implementing an asset attachment feature to objects. When trying to figure out exactly how to approach this I was unable to find an API listing or anything that describes how to interface with the drawn objects.

Is this created already, or where do I go to find exported functions?

**Comment by sktguha** [comment]
Yes actually I have a similiar requirement for the product I am working on, I have asked a question in stackoverflow as well https://stackoverflow.com/questions/67184047/does-draw-io-expose-any-js-api-for-manipulating-its-drawing-elements-programatic

Maybe we can collaborate also if required.

**Comment by sktguha** [comment]
Hi @iceblu3710 , did you end up finding any solution to this ?

**Comment by sktguha** [comment]
Hi @davidjgraph , just wondering, could you add your inputs to this if possible ? I would be really grateful to you 🙂 

If you prefer to add on stackoverflow instead, here is the question I have asked there:  https://stackoverflow.com/questions/67184047/does-draw-io-expose-any-js-api-for-manipulating-its-drawing-elements-programatic

**Comment by alderg** [comment]
Currently, the API for the archived core library is still public at http://jgraph.github.io/mxgraph/docs/js-api/files/index-txt.html

**Comment by sktguha** [comment]
@alderg this is so amazing , Thanks a lot 🙂. 
>archived core library 

By this I guess you mean that it doesn't accept any PRs for improvements as you have mentioned on the readme also. Which is fine.
