### ISSUE TITLE
There's no way to drag-select objects that are enclosed by another object (stop treating all objects as filled)

### ISSUE THREAD

**Issue by Stokestack** [jgraph/drawio#1936]
* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Yes.
Please describe.**

Drag-selecting (drawing a selection marquee) is often the only practical way of selecting numerous overlapping objects. Unfortunately, this mode is impossible in drawio if the objects are within another one (for example, a bunch of small shapes inside a rectangular frame). The initial click always selects the surrounding object instead, even if it's unfilled and you have its Editable and Movable properties disabled. This is an extremely common situation in drawings; while you can sometimes work around it by starting your drag outside the enclosing object, this often becomes impractical as the drawing gets more complicated.

I downloaded the desktop application, and found that it (unlike the browser-based version) offers an object property for "pointer events." This accomplishes exactly what I'm asking for here.... and now I find that the option also exists if I go to draw.io and create shapes. So this might have been added, rendering this issue moot. Maybe we're using an old version.

**Describe the solution you'd like**
Add the "pointer events" to the properties in the online version...
OR
If you click inside an unfilled object, that object should NOT be selected. Some drawing applications make this a user preference ("treat all objects as filled"). Alternatively (or perhaps in conjunction with that preference), add an object property that enables drag-selecting within the object.

**Describe alternatives you've considered**
As noted above, the only current workaround is to start your drag outside the enclosing object. Fortunately, drawio only selects things that are fully enclosed by the marquee (a critical mode!).

**Additional context**
Screen grab attached, of trying to select several controls in a UI mockup, but being unable to because they're within a rectangle. 

https://user-images.githubusercontent.com/196304/115470101-a655eb80-a1ea-11eb-8aaf-cdf056723006.mov

This issue is compounded by the apparent lack of any object list, which we might use to select objects if we can't click on them on the canvas.

**Comment by alderg** [comment]
The pointer events property should be visible if the object is not filled.

**Comment by Stokestack** [comment]
Unfortunately it's missing in our installation. I created a square, made sure it wasn't filled, and checked the property list. Screen shot attached. Was this setting added in a later version perhaps?

<img width="380" alt="noPointerSetting" src="https://user-images.githubusercontent.com/196304/115510223-4f750400-a234-11eb-8cd8-47ab11d69190.png">

**Comment by alderg** [comment]
What version are you using?

**Comment by Stokestack** [comment]
8.5.1

**Comment by davidjgraph** [comment]
I guess this in conf server? Try updating to the latest release.

**Comment by Stokestack** [comment]
It is. I'm not the maintainer of the server, and I have no idea what's involved in updating it. I've asked someone to look into it. Is there a built-in update utility?

**Comment by davidjgraph** [comment]
Yes, you go to manage apps, expand the draw.io section and click update.
