### ISSUE TITLE
Feature - Strikethrough styling

### ISSUE THREAD

**Issue by DavidAndrianne** [jgraph/drawio#1938]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Strikethrough styling support, same as prior closed issue:
https://github.com/jgraph/drawio/issues/197

**Describe the solution you'd like**
A button next to the bold, italic and underline symbols to apply the strikethrough effect, similar to Office or similar rich content apps. 
![image](https://user-images.githubusercontent.com/5501244/115507822-e5348180-a27c-11eb-870c-93aecae23dd6.png)

**Describe alternatives you've considered**
Copy pasting the text with mark-up from elsewhere.

**Additional context**
The reason I'd like this feature is because I'm making a before and after diagram with draw.io
It would be nice to illustrate in the new design exactly which steps are falling through with strikethrough highlighting.

**Comment by mararad** [comment]
Hi, if you double a label, you should see the strikethrough button in Text tab as shown in the image below.

![st](https://user-images.githubusercontent.com/44292306/115513006-e10b6280-a282-11eb-9468-caf01f313799.JPG)

**Comment by DavidAndrianne** [comment]
@mararad Thank you! Double clicking in the textbox area indeed appears the strikethrough! :)

**Comment by matmolni** [comment]
The proposed solution by @mararad (double clicking the text field) does not seem to apply to text in list items. Am I missing something, or would this be a new feature request?

<img width="526" alt="Screenshot 2024-08-23 at 10 22 15" src="https://github.com/user-attachments/assets/4acadcf6-9a98-4e3f-b573-e28b0dc7495c">

**Comment by alderg** [comment]
Check "Formatted Text":

<img width="526" alt="360847847-4acadcf6-9a98-4e3f-b573-e28b0dc7495c" src="https://github.com/user-attachments/assets/1b2842d0-b05d-4dd2-8497-6a0b0aea36a1">
