### ISSUE TITLE
Use the Authorization Code flow instead of Implicit grant for GitLab OAuth authentication

### ISSUE THREAD

**Issue by dee-see** [jgraph/drawio#1941]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

GitLab is going to remove support for the OAuth implicit grant in a few versions https://gitlab.com/gitlab-org/gitlab/-/issues/288516

**Describe the solution you'd like**

The application should use Authorization code flow (with PKCE ideally)

**Describe alternatives you've considered**

N/A

**Additional context**

Disclaimer: I work for GitLab. I'll try to contribute the fix myself if I get a moment but I wanted to have the issue up here if someone else wants to pick it up.

**Comment by davidjgraph** [comment]
We'll sort it. What are the rough timescales for 14.4?

**Comment by dee-see** [comment]
14.4 should be released on [October 22nd 2021](https://about.gitlab.com/community/release-managers/)

Thanks!

**Comment by davidjgraph** [comment]
Switched away from implicit grant in 14.6.9
