### ISSUE TITLE
support edit mxcell's id

### ISSUE THREAD

**Issue by Yeamy** [jgraph/drawio#1942]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When I using grafana-flowcharting, I want to show data into the graph, so I have to mapping data with the mxcell's ID, but the ID is a random string and cannot change it via UI.

**Describe the solution you'd like**
Provide an input field, and check if duplicate after modification.

**Describe alternatives you've considered**
An input field in the right sidebar and 'Edit Data' dialog.

**Additional context**
changing it via xml editor is too slow; mapping via grafana-flowcharting's UI (without change the id) is too slow and too hard to click the cell. If I can change the ID,  I can mapping via coding a script.

**Comment by alderg** [comment]
Shift+Double Click (older versions: ctrl+double click) now supported on the ID text field in the edit data dialog.
