### ISSUE TITLE
Want better control of background grid.

### ISSUE THREAD

**Issue by pj6** [jgraph/drawio#1944]
* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'm designing something where I need to be aware of an 8x8 tiling pattern throughout the layout.

**Describe the solution you'd like**
I'd like to see stable major grid lines every 8 units and have them unaffected by zoom, unless I'm zoomed out too far in which case they can disappear.

**Describe alternatives you've considered**
I've tried tiling objects in a read-only layer to get this, but at larger scales it performs poorly. I also tried setting "Paper" size to something that will tile, but that's impossible for 8 units because custom paper size is restricted to inches and 2 decimal places.

**Additional context**
I think the concern of design units and printing units should be separated.

**Comment by alderg** [comment]
Use [this](https://app.diagrams.net/#_CONFIG_UzV3UjUyyk0tSk8F0qrGjqpggfSizJTgktSCYoighaq5CxABAA==) link to configure the grid steps.
