### ISSUE TITLE
New BPMN 2.0 shapes cannot be connected with the connectables (blue crosses)

### ISSUE THREAD

**Issue by nscrd** [jgraph/drawio#1948]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The 'connectable' setting is not applied to all shapes in the BPMN 2.0 category.

**To Reproduce**
1. Click more shapes.
2. Choose business -> BPMN 2.0
3. Click apply
4. Add the shape 'generic task' (under BPMN 2.0 tasks) - (the property 'connectable' is enabled by default)
5. Hover on the shape

**Expected behavior**
Now the connectors should be displayed (small blue crosses), which can be used to connect two shapes (e.g. with an arrow).

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 14.6.6

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - Browser: Chrome
 - Version: 89.0.4389.114

**Additional context**
The problem did not occur with the "old" BPMN shapes.

**Comment by egrimate** [comment]
Anchor points to all BPMN shapes will be added in next release.
