### ISSUE TITLE
github account access denied after rename repository

### ISSUE THREAD

**Issue by Cadmus-design** [jgraph/drawio#1959]
### Preflight Checklist

* [ Y] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [Y ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I use github account for storage, but I want to change my repository to another, so I renamed it then I can't access with github account.
Thought I revoke the authority and signed with github but it doesn't work anymore.
I tried use https://app.diagrams.net/clear.html  and https://app.diagrams.net/?mode=github 
It's the same, always show the "access denied" 

**To Reproduce**
please referrer the screen shot

**Expected behavior**
please referrer the screen shot

**Screenshots**
![0001](https://user-images.githubusercontent.com/11531752/116500808-e9e2e080-a8e1-11eb-84f2-09c671ddf462.png)
![0002](https://user-images.githubusercontent.com/11531752/116500819-eea79480-a8e1-11eb-8778-e213d7ed7bd2.png)
![0003](https://user-images.githubusercontent.com/11531752/116500826-f109ee80-a8e1-11eb-99b9-862314acfbe7.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]
- online version

**Desktop (please complete the following information):**
online version

**Comment by davidjgraph** [comment]
Fixed in 14.6.9. If you need to force update the PWA go to https://app.diagrams.net/clear.html then back to the app

**Comment by Cadmus-design** [comment]
Thanks a lot.
It works now.
