### ISSUE TITLE
Shapes in draw.io for Confluence do not stick to swimlane container

### ISSUE THREAD

**Issue by Bastesque** [jgraph/drawio#1962]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Swimlane diagrams work as containers. Shapes that we drag to the swimlane remain attached to it. What we recognized is that if we create a workflows from the shape we added (either via the blue arrows and the shape picker or via the shortcut Alt+Shift+arrow keys) are not added to the container. We see that when we try to reposition the swimlane. The initial shape we added via drag and drop moves along, the others remain on their position and are not moved accordingly. When we add shapes by dragging a new shape over a blue arrow, the new shape is added to the container and it is sticky. 

**To Reproduce**
1. Add swimlane diagram
2. Drag and Drop a shape on a swimlane until container shows a purple halo. Release to attach the shape.
3. From the shape you just added, use the shape picker to create a workflow.
4. Move the swimlane to a new position to see that all the shape except the initial one aren't moved with the swimlane.
5. Check same behavior when drag and drop new shape on the blue arrow instead of using the shape picker.

**Expected behavior**
All of the shapes/connectors that I create from a shape inside the container should automatically be added to the container, too.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 9.5.14 for Confluence Server

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.5 (19F101)
 - Browser: Chrome
 - Version: 89.0.4389.114

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
