### ISSUE TITLE
Increase the size of connector start and endpoints / change color in draw.io for Confluence

### ISSUE THREAD

**Issue by Bastesque** [jgraph/drawio#1963]
* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
We just migrated from Gliffy to draw.io. In Gliffy the connector start and endpoints were displayed much bigger when we selected them. We saw that in draw.io, we have the option to have fixed or floating connectors, shown as an X or an O in the start and endpoint circle. But it's very tiny, a lot of the colleagues don't actually see the markers at all. Therefore they often don't see, where they can improve the connector behavior.

**Describe the solution you'd like**
We would love to have the connector markers (not the actual line start and end arrows) double the size when we select them. It would also be great to have different marker colors (e. g. green for fixed, blue for floating connectors).

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release (added 2 px and green/blue for fixed/floating).
