### ISSUE TITLE
Text in a box set to "top", possible to have it inside the box ? (and not just on top of it) ?

### ISSUE THREAD

**Issue by Yves759** [jgraph/drawio#1977]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Yves759** [comment]
Hello there, I'm discovering draw.io, looks great overall ? (coming from ppt ...)

Starting to draw a diagram, was a bit surprised that when you add some text in a box, and set the text position to "top", the text appears just above the box, no way to have the text at the top but inside the box ?

For instance in below, I would like "CompanyRef" to appear at the top but inside the box, right below the top line of the box :   

<img width="271" alt="Capture d’écran 2021-05-04 à 12 30 00" src="https://user-images.githubusercontent.com/83643197/116991202-7facb000-acd4-11eb-897c-2925f8098bb5.png">

**Comment by mararad** [comment]
Hi, 

choose Position Center and click Top icon as shown in the image attached. Does it help?

Regards,

![top](https://user-images.githubusercontent.com/44292306/116999422-e2f00f80-acdf-11eb-8185-01a4a2a18bee.JPG)

**Comment by Yves759** [comment]
Ok thanks ! (in fact just saw that before in a video)

But what is strange is that : 

1. If the postion is "top" in the drop down list,  and the icon "just below" is selected  : **it puts the text way above the shape**
2. if the position is "center" in the drop down list, and the icon "just below" is selected : it works (like in your msg)
3. if the position is "center" in the drop down list, and the icon "just above" is selected : it put the text just above the bottom line
5. If the position is "top" in the drop down list, and the icon "just above" is selected : it puts the text just above

1 in particular is really strange,  is this the intended behaviour ? if yes for what purpose ?

And if you start from the drop down lists instead of the icons, not very intuitive I would say, but thanks a lot for the info ! :)
