### ISSUE TITLE
Question about Asset licensing

### ISSUE THREAD

**Issue by hiringManager** [jgraph/drawio#1981]
Hello, I'm interested in transferring over some of the vector assets to another piece of software, and releasing it on github. Is there anywhere I can get the documentation for licensing these things? I'm strictly interested in just moving them over to to Affinity Designer's format ('*.afasset') and posting them here for everyone.

On top of this, since moving assets into draw.io is a bit wonky for the normal user, any chance that there is demand for including more in the initial asset library in the future? 

Thanks! Absolutely in love with this software by the way, I've lost WAY too many hours in it, and I'm only a month or so deep.

**Comment by davidjgraph** [comment]
You can re-use graphics content under https://creativecommons.org/licenses/by/4.0/ . It can be shared freely, just attribute copyright back to this project and document that the graphics are licensed under CC BY 4.0

**Comment by Matheus-Garbelini** [comment]
Hi, is there some way to automatically know where a specific asset on `shapes library` belongs so we can acknowledge?
I'm thinking of using some figures from the shape library on a research paper but I'm not sure how to correctly acknowledge this.

Attribute copyright back to this project and mentioning CC BY 4.0 is enough for all figures in shape library?

Thanks a lot.

**Comment by davidjgraph** [comment]
If you produce a diagram using this app with icons supplied as part of the app, no attribution is required. It's only if you create an app that uses the icons.

**Comment by Matheus-Garbelini** [comment]
@davidjgraph thanks for the clarification. For my use case, this app is awesome for producing research figures :+1:
