### ISSUE TITLE
Zoom in/out issue with Logitech Mx Ergo

### ISSUE THREAD

**Issue by dariomes** [jgraph/drawio#1987]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When using draw.io in edit mode in a Confluence page, I have no control over the zoom. I am using a Logitech MX Ergo mouse and I use the scroll wheel to zoom in/out. Whenever I touch it, the page zooms out or in entirely. The mouse scroll zooming works fine with other tools and web-based pages such as google maps.
I am using Google Chrome.

**To Reproduce**
N/A

**Expected behavior**
Having control over zoom of drawings. Not going to full scale with just one touch.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]
14.6.10

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chorme
 - Version latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dariomes** [comment]
The same problem happens with Mozilla and Edge.
It does not happen when using the Draw.io desktop version.

**Comment by davidjgraph** [comment]
Relates to #1611

**Comment by davidjgraph** [comment]
We don't have any mechanism to resolve this.
