### ISSUE TITLE
https://jgraph.github.io/drawio/src/main/webapp/index.html can't connect to OneDrive, Google Drive, etc.

### ISSUE THREAD

**Issue by liew312** [jgraph/drawio#1988]
Unable to connect services like OneDrive, Google Drive using the github page of diagrams.net, https://jgraph.github.io/drawio/src/main/webapp/index.html ,
When I try to connect Google Drive, 
the console shows the error
> Failed to load resource: the server responded with a status of 404 () /google?doLogout=1&userId=null&state=cId%3D671128082532-jhphbq6d0e1gnsus9mn7vf8a6fjn10mp.apps.googleusercontent.com%26domain%3Djgraph.github.io

When I try to connect OneDrive,
the console shows the error

> GET https://jgraph.github.io/microsoft?getState=1 404

How to solve this problem so I can connect to OneDrive, Google Drive and etc using the github page version?
Thank you!

**Comment by davidjgraph** [comment]
It's not supported on the GitHub pages version for security reasons.
