### ISSUE TITLE
Connector automatic routing around objects

### ISSUE THREAD

**Issue by askmydog** [jgraph/drawio#1989]
* [ X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Whenever I create anything on diagrams.net, I inevitably need manually route my connectors so they don't go over/under/through other objects (besides other connectors), and when I move anything, the connectors get out of place and I have to manually re-route them again to keep them from from going under/over/through other parts of the diagram.

**Describe the solution you'd like**
I would like an option for connectors to automatically re-route around objects (except other connectors), so that they don't over/underlap.

**Describe alternatives you've considered**
I've tried all of the connector types, none of them seem to have this feature.  The only alternative I know about is to either manually re-route the connector or move the object so they don't touch, which can be extensive for larger diagrams. 

**Additional context**
Great app!  Keep up the good work!

**Comment by mararad** [comment]
Issue re-opening
