### ISSUE TITLE
question/bug - auto-group on drag/hover

### ISSUE THREAD

**Issue by armoured-moose** [jgraph/drawio#1998]
Hi, I'm not sure if this is a desired feature or a bug - but I cannot find support pages for it.

Semi-recently I noticed that, when I drag objects over others, draw.io automatically groups those objects. This can make things difficult in projects with many closely positioned shapes.

Is there a way I can disable this, if it is a setting?

**Comment by armoured-moose** [comment]
Hi, 

I will try and make a minimum working example. In the mean time:

It's draw.io desktop: diagrams.net 14.1.8.
I tried the ALT trick and no luck.

However I do find that in my current diagram one can reproduce this by
1. creating 3 shapes.
2. grouping two of them.
3. dragging the third over the other 2 shapes, with a blue border appearing over those two original shapes as the third hovers over.
4. if I select one of the individual shapes from that original grouping and move it out of the blue box the group is destroyed. 

The problem requires at least one grouping to have been made; hovering individual shapes over each other does nothing.

I have a suspicion that this is not a bug, but I have not found the correct docs anywhere which explains this behaviour.

**Comment by gautamyadav144** [comment]
Yes I'm having same issue.

**Comment by alderg** [comment]
Select the group and uncheck "Drop Target" in the Style panel under Properties on the right:

<img width="237" alt="Screenshot 2021-05-24 at 15 07 44" src="https://user-images.githubusercontent.com/921200/119352440-fcaec200-bca1-11eb-9bb7-a5258c96c5fe.png">

**Comment by armoured-moose** [comment]
Thanks. I do notice group on hover still occurs with this setting, however; now if you hover the shape over the groups' individual elements the option to group now appears. 

Since it is only triggering on single elements its much more forgiving, since the "hit box" is smaller. However, this solution does not completely stop group-on-hover.

**Comment by alderg** [comment]
Group on hover is disabled for me on the group and its individual elements with this setting:

![6b21f062bbb2384b83b1890884f7baa4](https://user-images.githubusercontent.com/921200/119372957-325ea580-bcb8-11eb-8e7a-b692e3c32997.gif)

**Comment by armoured-moose** [comment]
OK I've just checked and you're right.I was dragging over a line connector, which then re-routes the line to connect to the shape that you are holding - which is correct functionality I think.

Thanks!
