### ISSUE TITLE
Make swimlanes selectable only from the edge

### ISSUE THREAD

**Issue by Bastesque** [jgraph/drawio#2004]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
We work with swimlanes a lot. It happens quite often that we want to select objects inside the swimlane but select the swimlane by mistake. 

**Describe the solution you'd like**
The problem would be solved, if swimlanes would only be selectable at the edges.

**Comment by alderg** [comment]
Is this with or without using a lanecolor (ie on mouse down or up)?

**Comment by alderg** [comment]
If lane colors are used, events can be disabled by unchecking Pointer Events under Properties in the Style panel.

**Comment by Bastesque** [comment]
Yes, we used lane colors in this specific example. Thanks for clarifying :D

**Comment by alderg** [comment]
We will add an additional global switch for this in the next release.
