### ISSUE TITLE
The "Open with diagrams.net" button only pops up the second time I access a Draw.io document

### ISSUE THREAD

**Issue by druatta** [jgraph/drawio#2007]
Hi there, when I open up Draw.io forms in Google Drive from Quick Access, I always need to open them, close them, and then re-open them, in order to get the "Open with diagrams.net" button to pop up.

Sincerely,
Daniel

**Comment by davidjgraph** [comment]
Browser/version/OS? Any browser extensions that might affect operation?

**Comment by druatta** [comment]
Google Chrome Version 90.0.4430.93 (Official Build) (64-bit), on Windows 10 and Google Chrome Version 90.0.4430.212. I've seen this behavior on two different computers.

Here are the extensions I'm using on one of the computers:

1. Cisco Webex
2. Explain and Send Screenshots
3. Google Docs Offline
4. Zotero Connector
5. Chromebook Recovery Utility
6. Docs
7. Sheets
8. Slides
9. VBA-M

Are you able to recreate this behavior?

**Comment by davidjgraph** [comment]
I can't recreate this. Does it happen in incognito mode?

**Comment by druatta** [comment]
Yes.

If you can't recreate this on your end, maybe it has something to do with my Chrome extensions? Or do I need to wait a while to get that button to pop up?

Let me know if you see anything odd in the code for this button, or if there are other tests that could be run to find out what's going on.

I just ran the following test:

Closed Google Drive

Opened Google Drive

Tried to access a Diagrams.net file from Quick Access

The Open with diagrams.net button is not there - I waited about 15-30 seconds to see if it would pop up.

Closed out of the file preview

Double clicked the file again (from Quick Access)

Now the button is there

If I close and re-open the preview again, the button will continue to pop up correctly.

**Comment by davidjgraph** [comment]
Does it happen in incognito mode?
