### ISSUE TITLE
Insufficient build rules in etc/build/build.xml

### ISSUE THREAD

**Issue by asl** [jgraph/drawio#201]
etc/build/build.xml contains build rules for the following files:

1. app.min.js
2. base.min.js
3. extensions.min.js
4. viewer.min.js
5. vsdx.min.js

( + shapes and stencils)

However, the drawio distribution contains some extra files:
1. atlas-viewer.min.js
2. atlas.min.js
3. embed-static.min.js
4. embed.min.js
5. reader.min.js

How one could build these files?

**Comment by petahbred** [comment]
Would also like to know this as well?

**Comment by techla** [comment]
me too :)

**Comment by alderg** [comment]
These are special files for some of our integrations, you shouldn‘t need any of those.

**Comment by PackElend** [comment]
what is meant by integrations, do you refer to [Integrations – draw.io](https://about.draw.io/category/integrations?).
Some of them are interesting for cloned repository

**Comment by PackElend** [comment]
@davidjgraph could you specify for which integration they are intented to be used for before closing it?

**Comment by davidjgraph** [comment]
Atlas is our Atlassian integrations.
Embed is the JS for embedding the viewer
Reader is another viewer, with a few extras.

**Comment by PackElend** [comment]
> Atlas is our Atlassian integrations.

definitely not gonna need it :)

>  Embed is the JS for embedding the viewer

that allows to integrate diagrams in e.g. blog, as shown on [Draw.io GitHub Integration with Bootstrap](https://jgraph.github.io/drawio-github/self-editing.html?t=1562070020200) and [How to embed files? : draw.io Helpdesk](https://desk.draw.io/support/solutions/articles/16000067789-how-to-embed-files-) doesn't it? 
I started reading here [How does Embed mode work? : draw.io Helpdesk](https://desk.draw.io/support/solutions/articles/16000042544-how-does-embed-mode-work-).
That would bring up the embed function in the draw.io file menu, wouldn't it? 

>  Reader is another viewer, with a few extras.

During my research, I found [How to embed HTML?](https://desk.draw.io/support/solutions/articles/16000042542-how-to-embed-html-), [Embed Diagrams](https://github.com/jgraph/drawio/wiki/Embed-Diagrams). 
Does this viewer allow lightbox as mentioned in the two links above or is it even something completely different? 
Would that would allow using plugins as shown on [Show Properties in Chromeless mode](https://www.draw.io/?p=props&lightbox=1#Uhttps%3A%2F%2Fjgraph.github.io%2Fdrawio-diagrams%2Fdiagrams%2Fbulb.xml). 
This would allow us to extend the functionllity of confidential diagrams, what in turn rises user acceptance signigcannlty. Currently, we cannot do that as some of the run only in the lightbox (acc. [plugins – draw.io](https://about.draw.io/tag/plugins/) and [What Plugins are available?](https://desk.draw.io/support/solutions/articles/16000056430)) what is only available on draw.io.

Does these rules cover all integration what are mentined on [The ecosystem of draw.io integrations](https://about.draw.io/integrations-ecosystem/) besides those being handled by third-party plugins/apps, which run a ported version of this respositiory.
