### ISSUE TITLE
Unsaved Changes (Timeout Error)

### ISSUE THREAD

**Issue by jonlhart88** [jgraph/drawio#2010]
My colleagues and I are collaborating on a DrawIO project. A couple of us are experiencing issues with the project automatically saving and get the following timeout errors:

<img width="898" alt="error1" src="https://user-images.githubusercontent.com/56091317/118163365-bff7e680-b3d6-11eb-886e-e800867cac1e.PNG">
<img width="396" alt="error2" src="https://user-images.githubusercontent.com/56091317/118163375-c25a4080-b3d6-11eb-87f3-a3cd3a4efc37.PNG">

Others are not experiencing any issues at all when working in the same project. Any help on resolving this issue would be great.

**Comment by davidjgraph** [comment]
So, two of you get timeout issues on that specific diagram and others don't? What are the browsers/versions/OSes involved?

What browser extensions do you have? Does it work private/incognito?

**Comment by maichomper** [comment]
Hello @davidjgraph, I'm not sure if I can reopen this issue but I am currently having the same problem where I can open all of my diagrams but one. I always use Chrome (currently Versión 97.0.4692.99) and just tried with Safari but I am getting the same message. I am using MacOS BigSur 11.5.2 After I click on "Try again" I get a second error "Access Denied". I have also tried in Incognito with the same results.

**Comment by davidjgraph** [comment]
@maichomper Please open a new issue and file as a bug report.
