### ISSUE TITLE
Unable to insert draw.io diagrams in Google Slides with "diagrams.net for Slides" Add-on

### ISSUE THREAD

**Issue by kostaschaldaios72** [jgraph/drawio#2019]
**Describe the bug**

While editing a Google Slide I try to insert one of the draw.io diagrams previously used, with "diagrams.net for Slides" Add-on . Then an error message pops up and the action is not completed. The error message is "We're sorry, a server error occurred while reading from storage. Error code PERMISSION_DENIED". If I try to insert it directly from the "Add-ons" button and after selecting the diagram and the page I wish to insert, this error message pops up: 

"1 insert failed:
- Leroy Merlin Customer Journey 2nd Draft- Scenario B May 2021.drawio: Request failed for https://convert.diagrams.net returned code 500. Truncated server response: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/... (use muteHttpExceptions option to examine full response)"

Up until yesterday I could insert the same page of the same draw.io file with no problem. No access right was changed as to explain the error described above.

**To Reproduce**
1. Press Google Slides button "Add-ons"
2. Press "diagrams.net for Slides" button
3. Press " Insert Diagrams " button
4. Select draw.io file I need and the page I need
5. Press "Insert" button

**Expected behavior**
The diagram from the page selected of the selected file should have been inserted in the slide.

![screenshot-docs google com-2021 05 16-16_56_19_2](https://user-images.githubusercontent.com/84277085/118399947-45de9080-b668-11eb-8f1b-009f55306709.png)

![screenshot-docs google com-2021 05 16-16_09_40](https://user-images.githubusercontent.com/84277085/118399876-e41e2680-b667-11eb-8619-051e2e66da56.png)

**Comment by TanZng** [comment]
Same issue on Google Docs 😢

**Comment by davidjgraph** [comment]
Is this still happening now?

**Comment by danielcrowley** [comment]
Fixed for me!
Thanks!

**Comment by davidjgraph** [comment]
This looks stable in the logs. If it happens again add a comment or start another issue.

**Comment by kmarkey-mdsol** [comment]
Just wanted to report that I was getting the same error using the add-on in Google Slides. The only difference between my use case and the OP is that I was inserting a diagram for the first time and it was `.png` instead of `.drawio`. I experienced the same behavior on 6/23 and 6/28.

I was able to get around it by copy/pasting the diagrams into a new diagram document of type `.drawio` and was then able to successfully insert them into Google Slides with the add-on.

**Comment by donlordhan** [comment]
+1
Embedding myDiagram.dawio from GoogleDrive in myGoogleDoc through addon "[diagrams.net for Docs](https://gsuite.google.com/marketplace/app/diagramsnet_for_docs/224440279306)"

Response in modalWindow:
1 insert failed:
- myDiagram.dawio: Request failed for https://convert.diagrams.net returned code 500. Truncated server response: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/... (use muteHttpExceptions option to examine full response).
 
 How can I help?

**Comment by donlordhan** [comment]
> +1
> Embedding myDiagram.dawio from GoogleDrive in myGoogleDoc through addon "[diagrams.net for Docs](https://gsuite.google.com/marketplace/app/diagramsnet_for_docs/224440279306)"
> 
> Response in modalWindow:
> 1 insert failed:
> 
>     * myDiagram.dawio: Request failed for https://convert.diagrams.net returned code 500. Truncated server response:

For me, helped recreating myDiagram.draw.io in GoogleDrive. 

Now can't embed myDiagram.draw.io in Confluence Server as HTML (before it worked for another myOldDaigram.draw.io: 
JSON.parse: end of data while reading object contents at line 1 column 2 of the JSON data
`SyntaxError: JSON.parse: end of data while reading object contents at line 1 column 2 of the JSON data
    createViewerForElement viewer-static.min.js:57594
    processElements viewer-static.min.js:57569
    forEach viewer-static.min.js:9201
    processElements viewer-static.min.js:57566
    onDrawioViewerLoad embed2.js:1
    <anonymous> viewer-static.min.js:98895
    <anonymous> viewer-static.min.js:98897
viewer-static.min.js:formatted:57572
    processElements viewer-static.min.js:57572
    forEach viewer-static.min.js:9201
    processElements viewer-static.min.js:57566
    onDrawioViewerLoad embed2.js:1
    <anonymous> viewer-static.min.js:98895
    <anonymous> viewer-static.min.js:98897`

**Comment by JENMukiri** [comment]
Insert/Update Error! 1 insert failed:
- Final_project.png: Request failed for https://convert.diagrams.net returned code 500. Truncated server response: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

**Comment by davidjgraph** [comment]
Could you attach the diagram that failed please?
