### ISSUE TITLE
Can not use system font Latin Modern Roman 

### ISSUE THREAD

**Issue by krisfans** [jgraph/drawio#2020]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
`Latin Modern  Roman`  is the default font in` LaTeX`. I Can not use system font `LM Roman 10`

**Expected behavior**
I have install `LM Roman 10` font on my computer and this font can be used by `MS Word` , `Origin Pro` and other  software successfully but not in drawio .

**Screenshots**
![Snipaste_2021-05-16_23-19-01](https://user-images.githubusercontent.com/57793534/118402609-33327e80-b69d-11eb-9c2a-a883087f1110.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 14.6.13]

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Version Windows 10 家庭中文版

**Comment by davidjgraph** [comment]
Can you attach the diagram?
