### ISSUE TITLE
Single Quotes in CSV data results in validation error on Import

### ISSUE THREAD

**Issue by exwhyz** [jgraph/drawio#2022]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**
1. Go to Arrange -> Insert -> Advanced -> CSV
2. Add data with a name column containing a 'single quote' or Apostrophe for example Tessa O'Connor
3. Here are the contents of the first row of CSV Data:
`Tessa O'Connor,CFO,emi,Office 1,,me@example.com,#dae8fc,#6c8ebf,,https://www.draw.io,https://cdn3.iconfinder.com/data/icons/user-avatars-1/512/users-3-128.png`
4. Click Import
5. Error: 
`Tessa O'Connor,CFO,emi,Office 1,,me@exam... (135): Contains validation errors`

**Expected behavior**
Expect this to be loaded without any errors unless an escape sequence for Single Quotes or Apostrophes is required.

![image](https://user-images.githubusercontent.com/28545177/118410234-0b6af880-b654-11eb-93dc-866c1f38ffdb.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 14.6.13

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 90.0.4430.93 (Official Build) (64-bit)

**Comment by alderg** [comment]
Use "...", eg. "Tessa O'Connor",CFO,emi,Office 1,,me@example.com,#dae8fc,#6c8ebf,,https://www.draw.io,https://cdn3.iconfinder.com/data/icons/user-avatars-1/512/users-3-128.png
