### ISSUE TITLE
Unable to export PDF due to "500 - Internal server error"

### ISSUE THREAD

**Issue by zhenwang9102** [jgraph/drawio#2025]
It seems to be a server error; not sure what's the scope that it can influence.

**Comment by davidjgraph** [comment]
Try print to PDF in the meantime.

**Comment by zhenwang9102** [comment]
Got it. Though it takes one more step for me to crop the pdf manually, it works. Thanks! It also helps if the original function comes back :)

**Comment by TTTsuperpyer** [comment]
It seems to be a server error; not sure what's the scope that it can influence.
