### ISSUE TITLE
Text boxes don't wrap after we migrated from draw.io to Gliffy

### ISSUE THREAD

**Issue by Bastesque** [jgraph/drawio#2026]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
We used to work with text fields in our Gliffy diagrams. We migrated to draw.io but we see that some of the text fields don't wrap anymore. We have to remove the entire formatting to be able to work with text wrapping again. 

**Expected behavior**
Text boxes we migrated from Gliffy keep the same formatting and wrapping behavior that we had in Gliffy.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version -> latest Server version

**Additional context**

**Comment by mararad** [comment]
Hi Bastian,

Did you perform manual Gliffy import or mass import? Is it possible to attach a Gliffy file showing this behaviour so we could test it? 
And just to be sure: you are using draw.io 9.6.1?

Thanks,

**Comment by dvkarlhe** [comment]
Hello Mararad, we perform here the mass import by switching from Gliffy to Draw.io
I attach you both diagramms the migrated Draw.io and the Gliffy.
[Draw.io.zip](https://github.com/jgraph/drawio/files/7379813/Draw.io.zip)

**Comment by davidjgraph** [comment]
@dvkarlhe As a paying user you can file a ticket for this at https://drawio.atlassian.net/servicedesk/customer/portal/14/group/15/create/49 . You send private information there.

**Comment by davidjgraph** [comment]
Closing, we are unable to find further improvements on this subject
