### ISSUE TITLE
See on which layer shapes are located by clicking on them (the shapes)

### ISSUE THREAD

**Issue by Bastesque** [jgraph/drawio#2027]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
We work with quite complex diagrams and therefore also regularly with the layers feature. It sometimes happens that errors occur here, e.g. shapes are accidentally attached to the wrong layer or the order of the layers is not set correctly. When reordering individual shapes, it would help us a lot if we could see which layer a shape is on just by clicking on it. Currently we can only do this by using the "Move Selection to" option in the Layers menu, but this is too complicated for our users. 

**Describe the solution you'd like**
We would like to see directly on which layer a shape is located by clicking on it.

**Comment by alderg** [comment]
The next release will contain a "dot" that shows the common layer for all selected cells (if they have a common layer):

![common-layer](https://user-images.githubusercontent.com/921200/119835647-4ea15300-bf01-11eb-82de-c3ef0f1f59ba.gif)
