### ISSUE TITLE
Add hover effect once I mouse-over a shape

### ISSUE THREAD

**Issue by Bastesque** [jgraph/drawio#2030]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the solution you'd like**
I like to be able to have a hover effect, where shapes are slightly animated when I mouse-over them. This way, I could highlight subsets of shapes so people directly see, which objects share the same entity etc. I know that there is a highlight feature embedded in the interactive shape tutorial, but this needs a button or a layer to be activated. I just like to be able to define a mouse-over effect without a linked button.

**Comment by davidjgraph** [comment]
Declined, sorry :)
