### ISSUE TITLE
Gitlab branch picker is broken when many repos are present

### ISSUE THREAD

**Issue by jamespwilliams** [jgraph/drawio#2031]
### Preflight Checklist

* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.

**Describe the bug**

When you click on a particular repository, a branch picker appears - this picker should show a list of branch names. Unfortunately, the branch picker also loads in names of repositories in subgroups (see below). The branch names will be hidden somewhere among all of them. In an organisation with many repos, this makes the branch picker unusable.

![2021-05-19-112236_473x235_scrot](https://user-images.githubusercontent.com/34778680/118797482-89b5dd80-b894-11eb-9f1e-24f50145e8a3.png)

**To Reproduce**
1. Integrate with a Gitlab instance with lots of repos
2. Observe that the branch picker within the file picker is difficult to use

**Expected behavior**

Expected a functional repo and branch picker.

**Screenshots**

(added inline in the image description for clarity)

**draw.io version (In the Help->About menu of the draw.io editor):**

14.5.6

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium and FireFox
 - Version: 84.0.4147.125 and 88 respectively

**Smartphone (please complete the following information):**

N/A

**Additional context**

If the bug is something which is straightforward to fix, I might be able to submit a PR to fix this myself, but I'd probably need some guidance on where the bug is likely to be.

**Comment by jamespwilliams** [comment]
Okay I've just had a look at this in a debugger. The issue is that each group's repos are loaded in a separate request, and they keep getting loaded even after the branch picker is selected.

So the branch picker ends up getting filled up with repository names which are coming in late.

I think this should only happen if an organisation has a lot of repos.

The fix will be either:

* stop users from selecting repos while the list of repos isn't done loading - e.g: show a spinner
* check whether repos should be added to the picker when we get a result back from the requests

I think the first is probably best. The fact that a user can interact with the picker while it's still loading in repos is not optimal, imo.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
