### ISSUE TITLE
Page tabs are too small when number of pages exceeds 15+ pages in the chart

### ISSUE THREAD

**Issue by distguitar** [jgraph/drawio#2032]
When adding multiple pages to the chart, page tabs keep reducing in size making it difficult to click on them

**Steps to reproduce the behavior:**
1. Open blank chart
2. Add 15+ pages
3. Observe how smaller and smaller tabs get

**Expected behavior:**
Tabs should remain fixed size to be still readable and clickable.
Scroll control should appear as soon as tabs reach the horizontal limit

**Screenshots:**
![image](https://user-images.githubusercontent.com/3343529/118809917-3a15e880-b879-11eb-8224-47c7c299dbb5.png)

**draw.io version**
- draw.io version 14.6.13

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**

**Comment by mararad** [comment]
Hi,

This is already asked for. Please track this issue here: https://github.com/jgraph/drawio/issues/647

Thanks,
