### ISSUE TITLE
Set Default Style does not apply to vertical text alignment inside shapes.

### ISSUE THREAD

**Issue by kryptot7** [jgraph/drawio#2036]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Set Default Style does not apply to vertical text alignment inside shapes. (Possibly related to #1122)

**To Reproduce**
1. Double-click the canvas, and create a shape.
2. In the Style tab, customize that shape by changing the fill, gradient, outline, effects, etc.
3. Go to the Text tab. Change the vertical text alignment from Center to Top or Bottom. Also, customize the font size and typeface.
4. Type some text in the shape to see the change in alignment.
4. Return to the Style tab. Click Set as Default Style.
5. Repeat Step 1
6. The new shape will reflect all of your customizations, except for the vertical text alignment.

I also tried inserting the following code into `Configuration...`. This had no effect on the bug.
```javascript
{
  "defaultVertexStyle": {
    "verticalAlign": "top"
  }
}
```

**Expected behavior**
Newly created shapes keep the vertical text alignment as specified.

**Screenshots**
![image](https://user-images.githubusercontent.com/30781325/118868337-0e632480-b8b2-11eb-914c-f25fed559de0.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
- 14.6.3

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Browser: Downloadable app
 - Version: 14.6.3

**Additional context**
This is a minor issue and can be worked around, but changing the alignment manually or duplicating existing shapes adds a small amount of tedium.
The default vertical alignment (center) works well for shapes with small amounts of text. However, when adding new lines, it pans the view downward to keep the text in place onscreen, which is slightly distracting when editing a lot of text.
Overall, though, this app is very helpful, good quality software. Thank you all so much for making it!

**Comment by mararad** [comment]
Hi,

If you click Copy style after all modifications, add a new shape and click Paste style button (instead Set as default style) does it help?

Regards,

**Comment by kryptot7** [comment]
Hi @mararad,
Yes, that does help. The vertical text alignment is pasted successfully. While this doesn't completely solve the UX issue caused by the bug, it is a useful workaround. Thanks!

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by waqarsaleem** [comment]
The issue persists to this date with text boxes.

**Comment by davidjgraph** [comment]
Please open a new issue.

**Comment by thenameisdoc1** [comment]
The issue's been fixed. The following works now:
```
{
  "defaultVertexStyle": {
    "verticalAlign": "top"
  }
}
```
