### ISSUE TITLE
Distribute Starting and endpoints of connectors along the edge of a shape with one click

### ISSUE THREAD

**Issue by Bastesque** [jgraph/drawio#2037]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
We use UML and swimlane diagrams in draw.io. Usually, we use floating connections to connect shapes, because this always keeps the ways as short as possible. But if we have multiple connections, they all start from one of the connections points in the middle. Our users find it quite hard to see, which connection starts where (because multiple lines overlay each other).

**Describe the solution you'd like**
An option that automatically distributes connector lines along the edge of a shape, so each connector has a line of its own.

**Describe alternatives you've considered**
We know that we can fix this manually, using fixed connectors. But of course, having a checkbox that does it for us makes it a lot easier.

**Comment by davidjgraph** [comment]
This issue is a sub-set of #864 . There's little point distributing the points if you can't add them, which 864 addresses as the general case. I'll close this as a duplicate, but note if you press and hold alt while dragging the connector you can connect to any position within a shape.
