### ISSUE TITLE
Support multicolor lines 

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#2038]
"Im looking for a way to represent a line with 2 colors, like an electrical lead with EU protective earth standard = yellow/green. usually this is physically lenghtwise striped but 2 color dashed or dotted would be fine as well. Cannot find a style option for adding a 2nd color to a dashed line, is this possible?"

Asked in Discord

**Comment by internetscooter** [comment]
This would be great! A sort of workaround is to connect a line from A---->B and then from B<----A. Then set the colour and hashing that looks good. It is a bit of pain when moving nodes around but it doesn't take much effort to line the two lines up again
![yello_green](https://user-images.githubusercontent.com/630867/134666350-cae66e54-a247-4fd9-b73b-0810d8593256.jpg)

**Comment by davidjgraph** [comment]
Declined

**Comment by VMT-Solutions** [comment]
is this still not considered to be implemented ?

**Comment by davidjgraph** [comment]
No, otherwise it would have been re-opened.

**Comment by FoxyHunter7** [comment]
Unfortunate that this feature request was declined, multicoloured lines are quite useful, and often I'm wasting hours fighting drawio to place 2 lines of different colours next to each other as compromise.
