### ISSUE TITLE
Support Minio storage.

### ISSUE THREAD

**Issue by rustbomber** [jgraph/drawio#2039]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

use Minio OSS as backend storage. and add config options in Docker Image.

**Describe the solution you'd like**

I selfhost a Minio server, I hope draw.io use is as storage.

Minio is a very popular object storage service.

**Describe alternatives you've considered**

**Additional context**

**Comment by davidjgraph** [comment]
Link for reference - https://min.io/

This isn't something we'd do a part of the open source project, it would be commercial only if we had a business case (which we don't).
