### ISSUE TITLE
File not found error message

### ISSUE THREAD

**Issue by dcaprani** [jgraph/drawio#204]
Hi Guys

Just tried to integrate draw.io with GitHub repo but can't access the folder containing the repo.

Working from home, when I click the link for the repo the link simply runs "javascript:void(0);" or if I copy the address of the repo into the Enter Value... link, I get the error message below.  The same occurs in both Safari and Chrome browser and I'm working on a MacBook Air running High Sierra 10.13.2.

Any help would be appreciated.

Regards
Derek
![screenshot 2018-01-15 20 26 03](https://user-images.githubusercontent.com/5470445/34960806-61be91ae-fa34-11e7-8eb5-01cc86781c44.png).

Any help would be appreciated

**Comment by alderg** [comment]
Have you tried clearing the cookies?

**Comment by enamba** [comment]
Hi,
It's happening when I try to save too. I have my personal account on github but I work with my coworks on github of our job. When I try to open my diagram on github of my job, it's opened. But when I try to save I received this same message. 

This is the repo that I want to open the diagram but I don't  save
https://github.com/claranet-br/refactor

To open the diagram on screen to "Select file" I choose "Enter value" and I wrote "claranet-br/refactor", also I select my diagram that I pushed manually to this repository (https://github.com/claranet-br/refactor/blob/master/docs/diagram.xml) 

I use chrome Versão 71.0.3578.98 64 bits, I also tried Safari Versão 12.0.1 (14606.2.104.1.1) and Firefox quantum 64.0 (64-bit). I cleaned cookies and I try to use incognito window but doesn't worked.

Regards,
Namba

**Comment by davidjgraph** [comment]
Please submit a bug report containing full re-production steps from start to finish described in enough detail that another user can follow those steps and see the error.

**Comment by enamba** [comment]
I have a simple diagram on github
![image](https://user-images.githubusercontent.com/402975/50165734-a406be00-02cc-11e9-98aa-38a6d56f5943.png)

I want to open this diagram from draw.io
![image](https://user-images.githubusercontent.com/402975/50165860-f516b200-02cc-11e9-8b69-3d944ae652f2.png)

I had authorized draw.io to access my account
![image](https://user-images.githubusercontent.com/402975/50165941-1b3c5200-02cd-11e9-803f-03269146a69d.png)

but the repo that I want to access is from my job than I click on "Enter Value..."
https://github.com/claranet-br/ - of my job
https://github.com/enamba/ - mine
![image](https://user-images.githubusercontent.com/402975/50166127-8423ca00-02cd-11e9-9a61-d71f2958dd67.png)

And selected the diagram.xml
![image](https://user-images.githubusercontent.com/402975/50166165-a0276b80-02cd-11e9-85b4-f79693a9347e.png)

I open the diagram
![image](https://user-images.githubusercontent.com/402975/50166229-c2b98480-02cd-11e9-86c1-3e2e2076d7b5.png)

but when I try to save, put something on "Commit message"
![image](https://user-images.githubusercontent.com/402975/50166317-f694aa00-02cd-11e9-8c9b-9a6cabbd6224.png)

and after I click OK I received this error message.
![image](https://user-images.githubusercontent.com/402975/50166409-25128500-02ce-11e9-9f9e-0ed4ae36f355.png)

**Comment by cznno** [comment]
Same problem.  Will this bug be fixed?

**Comment by alderg** [comment]
We're unable to reproduce this problem. Are you using any special characters in your repo, branch or filename? Any other clues that might help us to reproduce this problem?

**Comment by cznno** [comment]
I found I can save files into subfolders of my repo, but I can't save them into root folder of repos.

**Comment by alderg** [comment]
Thanks for the hint, it helped us to fix a bug, not sure if if fixes this exact problem though. Fix will go into the next release scheduled for later this week.

**Comment by ajthinking** [comment]
I still have this issue. Steps to reproduce:

* Create a drawing
* Export as->PNG
* Github org-with-dash/repo
* select branch master and location

Gives not found. No more clues unfortunately.

**Comment by alderg** [comment]
We can reproduce the problem, but the write request seems to be correct.

**Comment by alderg** [comment]
It seems to fail regardless of dashed in the org name. The problem is writing to orgs in general...

**Comment by alderg** [comment]
Found the problem. Make sure to grant access to the org at https://github.com/settings/connections/applications/89c9e4624ca416554489

**Comment by AppliNH** [comment]
Same thing happens if your initial repo is empty.
Happened to me with Gitlab, had to add a readme inside it before saving the drawio

**Comment by appsparkler** [comment]
I faced the same issue on corporate OneDrive.   Logging out and back in to the OneDrive worked for me.

Thanks :)
