### ISSUE TITLE
Google Drive SSO redirect URI 401

### ISSUE THREAD

**Issue by chasms** [jgraph/drawio#2040]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Google Drive integration's redirect URI (app.diagrams.net/google?state=[...]) returns a 401, failing to authorize.

**To Reproduce**
1. Go to 'app.diagrams.net'
2. Click on 'save' and try to use Google Drive
3. Complete SSO sign-in steps to authorize Draw.io with Google Drive
4. On final step, redirect from google domain back to app.diagrams.net/google?state=[...], which returns a 401

**Expected behavior**
Google Drive integration should complete with a successful redirect and then confirm the authentication in draw.io's UI, allowing the user to save draw.io documents to Google Drive

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.0.9

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur 11.3.1
 - Browser: Chrome Version 90.0.4430.93 (Official Build) (x86_64)

**Comment by chasms** [comment]
You know what - this worked for me on my non-work GSuite account where I'm an admin - so it may just be lack of permissions in my GSuite org. Would be very nice to improve the error messaging with the 401 - all that returns appears to be the status code from a look into the network tab

**Comment by chasms** [comment]
Got my admin to add Draw.io to our org Drive, I can open files in draw.io from in drive, but still can't save to Drive from draw.io - page tells me I need to Authorize, and then I go through the flow and continue to get the 401

**Comment by karlbrown-va** [comment]
I am seeing this same error. I am able to create and save a drawing to my root drive, while logged in with enterprise Google credentials. However, clicking on 'open existing diagram' opens a window with 'In order to select files, you must sign in to your Google account.' - clicking on 'sign-in' pops up a window that disappears; clicking it again pops up a window that disappears, and then I get 
```
400. That’s an error.

The server cannot process the request because it is malformed. It should not be retried. That’s all we know.
```

**Comment by davidjgraph** [comment]
And in incognito?

**Comment by davidjgraph** [comment]
The only draw.io version listed in this thread is 13.0.9, which is really old and I wouldn't expect to work. Any problems with recent versions?

**Comment by karlbrown-va** [comment]
I'm using from diagrams.net; it shows 14.7.6

**Comment by davidjgraph** [comment]
Do "enterprise Google credentials" vary from a Google Workspace account? I wonder if Chrome and the Google account combine to add some kind of restriction.

**Comment by karlbrown-va** [comment]
I have fixed this. I was blocking all 3rd party cookies in Chrome. I changed to allow them for app.diagrams.net, and it worked. Thanks for your help!
