### ISSUE TITLE
Make the Desktop Application Run Faster

### ISSUE THREAD

**Issue by a-samuel** [jgraph/drawio#2047]
The desktop application operates very slowly when editing pngs. It got to a point where the file would not open again in the application. 

When using the online web version it loaded instantly. I exported it to a drawio file and using this file it loads instantly in the desktop app.

Therefore a method that would instantly improve the desktop applications capability is to perform the same operation as the online web version. And that is, what I believe to be, first import the file and convert it back to a drawio file, then open that for editing, and for saving export it to a png. For file safety a recoverable backup can be maintained in a drawio temp directory however I think this isn't an existing feature. It seems like editing a png has a lot of overhead, and justifiably so, it's an amazing feature I use for posting in documentation that I can later save again and edit.

Of course this is all easier said than done and maybe is not the correct way that the web version can operate as quickly. Godspeed 👍

**Comment by alderg** [comment]
Tested a PNG file with the desktop app on macOS and it didn't slow down. What operating system are you using? Does your diagram contain large images? Could you attach the diagram file so we can check if there is something in the file that causes this?
