### ISSUE TITLE
Mathematical Typesetting Export bug

### ISSUE THREAD

**Issue by Tom-theCoder** [jgraph/drawio#2048]
I've created simple diagram with some "LaTeX notation":
"$$a^{L - 1}_0$$"
"$$\sum$$"

It worked great in browser editor, but after exporting file as JPEG / PNG / SVN i got image where "LaTeX notation" wasn't replaced with expected symbols.

I found out that the bug occures when diagram is made in "Dark" theme and export checkbox "Dark" is not checked.

drawio version:
14.7.0

To Reproduce:
1. Select Dark theme
2. Switch on Mathematical Typesetting
3. Place object containing text with "latex notation" e.g "$$\sum$$"
4. Export as.. PNG / JPEG / SVN
5. Uncheck checkbox "Dark"
6. Export
7. See error on miniature or downloaded file

My setup:
OS: Pop!_OS 20.10 (based on Ubuntu)
GNOME v3.38.3
X11
Browser: Brave 1.24.86 (official release) (64-bit)

![Dark checked](https://user-images.githubusercontent.com/82613828/119228302-ad865700-bb12-11eb-9ad8-03f214bcb9e4.png)
![Dark unchecked](https://user-images.githubusercontent.com/82613828/119228303-aeb78400-bb12-11eb-8a8f-ab8c03a96554.png)

**Comment by mararad** [comment]
Reproduced in Chrome Incognito and FF 88.0.1 (64-bit)
Win 10 Pro
diagrams.net 14.7.0

**Comment by alderg** [comment]
This will be fixed in the next release.
