### ISSUE TITLE
.5 pt thick line doesn't export same in pdf,

### ISSUE THREAD

**Issue by gautamyadav144** [jgraph/drawio#2050]
.5 pt thick line doesn't export same in pdf, there is no difference between .5pt and 1pt in exported pdf.

**Comment by mararad** [comment]
Hi,

What draw.io version are you using (can be seen under Help)?
How did you perform the export exactly?
What browser version are you using?

Thanks,

**Comment by gautamyadav144** [comment]
draw.io version- 14.7.0
i just draw two line with .5(i set this from edit style) and 1.0 thickness and just export pdf and i also tried print same issue was there too, both line were same as 1.0 pt thickness its ignored .5t

Before export in canvas-
![Thickness](https://user-images.githubusercontent.com/20815011/119968582-4b729980-bfcb-11eb-88e5-48d06c73cca3.PNG)


After export-
![image](https://user-images.githubusercontent.com/20815011/119968503-3269e880-bfcb-11eb-987b-c0835d7eb404.png)

**Comment by alderg** [comment]
Fixed
