### ISSUE TITLE
When you have a lot of links, the latests do not work (I know how to fix it)

### ISSUE THREAD

**Issue by Benjamin-Carette** [jgraph/drawio#2051]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**
1. Create a text on the working area
2. right click > edit link
3. add a link to an internet page
4. duplicate the element  (I did it 40 times)

**Expected behavior**
when exporting the diagram to svg, some links are not working. 
Trying to remove some links will not help.
Links work if the diagram is exported to html.
The reason why this is happening is because a missing pointer-events="all" 
Adding it manually using a text editor fix the problem

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10 64bits
 - Browser [e.g. chrome, safari] chrome and firefox

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, safari] chrome Version 90.0.4430.212 (Build officiel) (64 bits)  and Firefox 88.01.64 bits
![goodgood](https://user-images.githubusercontent.com/6935055/119390672-ace5f000-bccd-11eb-8a45-48b40e370593.png)
![badbad](https://user-images.githubusercontent.com/6935055/119390681-b1aaa400-bccd-11eb-9c61-c8e06a8e7dc3.png)

**Additional context**

**Comment by mararad** [comment]
Hi,

Could you attach the file so it can be tested?

Thanks,

**Comment by davidjgraph** [comment]
If you wish to send us the diagram privately, you can file an issue at https://drawio.atlassian.net/servicedesk/customer/portal/16/group/17/create/65
