### ISSUE TITLE
library import bug. (import form browser)

### ISSUE THREAD

**Issue by luokunman** [jgraph/drawio#2052]
Two problems occur when I open the LibraryDialog to import images.
Import the image for the first time and then unimport it.Open LibraryDialog a second time to import the image and you will find the problem.1. editorUi.handleError({message: mxResources.get('fileExists')}). 2. No pictures appear

/webapp/js/diagramly/Dialog.js   function addButton has problem.
I don't think the 'entries' object was deleted when it was closed the dialog.
I found the problem but I couldn't solve it.

And when you're in the edit state 'addImages' button has problem. He will replace the picture
These are two problems that I found during development.
thanks.
My English is not very good, please forgive me

**Comment by alderg** [comment]
We're unable to reproduce this problem. Could you provide the exact steps?
