### ISSUE TITLE
I'm getting an unknown error whenever i click on a shape.

### ISSUE THREAD

**Issue by Rahulisback** [jgraph/drawio#2055]
The exact description is 'Uncaught TypeError: Cannot read property 'toLowerCase' of undefined'

**Comment by davidjgraph** [comment]
What browser/version/operating system? Can you attach screenshot of browser console?

**Comment by Rahulisback** [comment]
On Wed, 26 May 2021 at 9:18 PM, David Benson ***@***.***>
wrote:

> What browser/version/operating system? Can you attach screenshot of
> browser console?
>
> I m using windows 10 pro and using google chrome
>
one sec

**Comment by Rahulisback** [comment]
[image: screenshot.30.png]

**Comment by Rahulisback** [comment]
here you go

**Comment by Rahulisback** [comment]
![screenshot 30](https://user-images.githubusercontent.com/61188285/119692199-d7b87b80-be68-11eb-841b-a4ddd3aa22e8.png)

**Comment by Rahulisback** [comment]
sorry i sent it through gmail

**Comment by davidjgraph** [comment]
Could you share the file with support@draw.io via the drive.google.com interface please?

**Comment by Rahulisback** [comment]
one sec

**Comment by Rahulisback** [comment]
yah i sent it to you btw idk how to use this app i just started using it 30 mins ago

**Comment by davidjgraph** [comment]
The file is stored in Google Drive. Please go to https://drive.google.com. Find the file in the interface (look at recent). Right click the file, select "share". Add support@draw.io to "add people or groups" and click done.

**Comment by Rahulisback** [comment]
[image: screenshot.30.png]

**Comment by Rahulisback** [comment]
Yah done

**Comment by davidjgraph** [comment]
That's a screenshot of the diagram. I need the diagram itself.

**Comment by Rahulisback** [comment]
oh im so sorry

**Comment by davidjgraph** [comment]
I don't see the error. If you open a chrome incognito window does it still happen?

**Comment by Rahulisback** [comment]
thx so much now it is not coming

**Comment by brandrsn** [comment]
@davidjgraph, I'm getting the same error I'm afraid (in incognito as well). Here's [a 30 second Loom video](https://www.loom.com/share/2071784322eb4c8e8a310af7598a1d68) and the [Google Drive file URL](https://drive.google.com/file/d/1yj6WYPE3mXJ-581sfDRo7V7BoMJz0wN-/view?usp=sharing) if that helps.

**Comment by davidjgraph** [comment]
@brandrsn that's not the same error, please open a new issue.
