### ISSUE TITLE
Exported HTML links to app.diagram.net when self-hosted

### ISSUE THREAD

**Issue by 4jag** [jgraph/drawio#2057]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When self-hosting via Tomcat deployed .WAR file, diagrams exported as HTML continue to reference resources from app.diagrams.net and viewer.diagrams.net.

**To Reproduce**
1. Edit webapp/js/Preconfig.js and set EXPORT_URL, DRAWIO_BASE_URL, and DRAWIO_VIEWER_URL to the server being deployed. In my test case I'm using localhost:8090/drawio_local (drawio_viewer_url is full base_url+path to js file)
2. Package the app into a .war file, and deploy to Tomcat.
3. Launch the drawio editor, save the diagram, and then export to HTML.
4. Load the html into a browser and observe all js, image, and css resources being fetched from diagrams.net server instead of the local.

**Expected behavior**
Html file should reference the local base_url for viewer-static.min.js as set in preconfig.js, rather than diagrams.net.  Resulting decoded SVG should also use the local base_url for additional js and image files. 

**draw.io version:**

- draw.io version 14.7.2

**Desktop:**
 - OS: Windows 10
 - Browser Firefox
 - Version 78.10.1esr

**Additional context**
A similar bug is reported on fjudith/docker-draw.io 6/3/2020: https://github.com/fjudith/docker-draw.io/issues/43

**Comment by davidjgraph** [comment]
See https://github.com/jgraph/drawio/issues/2149
