### ISSUE TITLE
It will be too wide for export edmath formulation

### ISSUE THREAD

**Issue by perryuu** [jgraph/drawio#2063]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The size of exporting math formulation will be the as the original text, which is bad for embedding in paper writing.

**To Reproduce**
1. The original text
    
<img width="590" alt="截屏2021-05-29 15 40 38" src="https://user-images.githubusercontent.com/58758269/120062382-8f7da100-c094-11eb-96b6-2b1814bb65e7.png">

2. Rendering to math formulation
<img width="592" alt="截屏2021-05-29 15 40 46" src="https://user-images.githubusercontent.com/58758269/120062393-a7552500-c094-11eb-9f89-3abbb2ec8d38.png">

3. The exported math formulation
<img width="836" alt="截屏2021-05-29 15 44 53" src="https://user-images.githubusercontent.com/58758269/120062426-e7b4a300-c094-11eb-9495-5278016caa69.png">

4. There will be a very wide white part.

**Expected behavior**
I really expect the exported math formulation can have only the part in the red box. The wide white part is bad for writing a paper because when the picture is too big, I have to control the marginal size.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version 14.6.13

**Comment by alderg** [comment]
This is a known issue. Use Hidden, Block or Width under Style, Property, Text Overflow for the cell. See Troubleshooting at https://www.diagrams.net/doc/faq/math-typesetting

**Comment by perryuu** [comment]
> This is a known issue. Use Hidden, Block or Width under Style, Property, Text Overflow for the cell. See Troubleshooting at https://www.diagrams.net/doc/faq/math-typesetting

Hi! I have tried it. However, it seems not work. The white part is still wide.

**Comment by alderg** [comment]
Could you attach the diagram where you applied the fix please? The size of the box needs to be reduced to fit the math output.

**Comment by perryuu** [comment]
> Could you attach the diagram where you applied the fix please? The size of the box needs to be reduced to fit the math output.

Sorry for the misleading. 
1. Set the text overflow to visible
<img width="783" alt="截屏2021-05-29 20 50 45" src="https://user-images.githubusercontent.com/58758269/120071024-ddf46500-c0bf-11eb-8f67-6771ec87eb49.png">

2. Set to Hidden
<img width="823" alt="截屏2021-05-29 20 51 06" src="https://user-images.githubusercontent.com/58758269/120071032-e2b91900-c0bf-11eb-89d9-e658375d1403.png">

When setting to Hidden, it disappears.

**Comment by alderg** [comment]
Try block. [Here](https://app.diagrams.net/#RrZRdT4MwFIZ%2FTRN3sQTKJvNStqk3xphdzDtTaaGNhZLSOfDX248DjOxGExOSnj7no%2FScF1CyrbpHTRr%2BrCiTCEe0Q8kOYRzj1Z1dHOmBRDEOpNSCApvAQXyzIRDoSVDWzgKNUtKIZg5zVdcsNzNGtFbneVih5PzUhpTsChxyIq%2FpUVDDA93gdOJPTJR8ODm%2BhRtXZAiGEi0nVJ0D8pdL9ijZaqVMsKpuy6Tr3tAXjE9xLzYvb2J5TF4bgus2XYa2PPwlZbyCZrX539Iwyy8iT9AvhFf%2BidB6W2iSozSjBUp3bjVutZ5kF%2FxSVNZ4t64bHoh2nfRjs%2FtoAfFjpeLGIJzxxdIai1CU%2B5hwpu%2By6YfRGdbZ62bcVNKC2JpEirK2tmSF83wxbYQd9T3gSlDqkjPNWvFNPnwhl9coURsvpHWG1jtX6WRUG8QaDwmjQKKRjNJwSNnzCukl8CFV%2FmnRLycDE3Tvy7oLUcGkHpmqmNG9DQHvCr6efr49TwqON8D4hXpTYAQ%2BmnIsPAnDGqCNYTtJ2Psu%2FgTJ%2Fgc%3D) is an example.

**Comment by perryuu** [comment]
> Try block. [Here](https://app.diagrams.net/#RrZRdT4MwFIZ%2FTRN3sQTKJvNStqk3xphdzDtTaaGNhZLSOfDX248DjOxGExOSnj7no%2FScF1CyrbpHTRr%2BrCiTCEe0Q8kOYRzj1Z1dHOmBRDEOpNSCApvAQXyzIRDoSVDWzgKNUtKIZg5zVdcsNzNGtFbneVih5PzUhpTsChxyIq%2FpUVDDA93gdOJPTJR8ODm%2BhRtXZAiGEi0nVJ0D8pdL9ijZaqVMsKpuy6Tr3tAXjE9xLzYvb2J5TF4bgus2XYa2PPwlZbyCZrX539Iwyy8iT9AvhFf%2BidB6W2iSozSjBUp3bjVutZ5kF%2FxSVNZ4t64bHoh2nfRjs%2FtoAfFjpeLGIJzxxdIai1CU%2B5hwpu%2By6YfRGdbZ62bcVNKC2JpEirK2tmSF83wxbYQd9T3gSlDqkjPNWvFNPnwhl9coURsvpHWG1jtX6WRUG8QaDwmjQKKRjNJwSNnzCukl8CFV%2FmnRLycDE3Tvy7oLUcGkHpmqmNG9DQHvCr6efr49TwqON8D4hXpTYAQ%2BmnIsPAnDGqCNYTtJ2Psu%2FgTJ%2Fgc%3D) is an example.

Wow~ Thanks for your help! And I also find the property `Resizable` needs to set True. Your project drwaio is really really really great!

**Comment by alderg** [comment]
Thanks for the hint. We'll update the docs.
