### ISSUE TITLE
Overlapping click spots make program too fiddly

### ISSUE THREAD

**Issue by oMrSmith** [jgraph/drawio#2064]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

This program is lovely and has a huge potential.
It is still extremely fiddly though, especially when working on tiny things.

One way to significantly improve this would be
to avoid overlapping click spots.

I wanna grab a handle in order to extend an element to the left: impossible.
The arrow overlaps the click spot of the handle. I think this is one of the most
annoying things of this wonderful program.

![Overlapping Clickspots](https://user-images.githubusercontent.com/78870770/120064349-fdfa3900-c06b-11eb-81de-4d570d7d81b0.png)
 
Here is another solution:
_There could simply be a switch (or key) to bypass all arrow click spots!_ 
Hallelujah!

This way you could _separate_ the task of resizing and moving 
from the task of creating connections.

**Comment by alderg** [comment]
The arrow should be moved away from those size handles in this case. How did you get this to overlap?

**Comment by oMrSmith** [comment]
I hover over the handle I want to grap.

**Comment by oMrSmith** [comment]
Now I see: Found the option to hide the connections and arrow click-spots! Makes things so much easier.
