### ISSUE TITLE
Improve locking

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#2069]
1.  When a layer is locked, nothing can be changed such as shape/label position + labels can not be changed at all (font size, colors etc.) but when Ctrl+L is used (to lock all) only shape/label position is locked. Shape color, label size, color, font etc. can still be changed.

2. When a tree container is used and layer locked, it can not be folded but when it comes to regular shapes with fold feature added they can be folded when the layer is locked.

[folded.zip](https://github.com/jgraph/drawio/files/6584156/folded.zip)

**Comment by alderg** [comment]
This will be fixed in the next release.
