### ISSUE TITLE
Initializes the infinite canvas

### ISSUE THREAD

**Issue by amitsindha** [jgraph/drawio#207]
Hi,

Is there any option to disable infinite canvas and make it fixed with specific height and width?

in the Editor.js file there is option to disable it but its not working properly

Editor.prototype.extendCanvas = true;

Is there any fix or workaround available for this functionality?

**Comment by amitsindha** [comment]
Basically, we want to use paper size defined in the format panel, 
Page layout gets change according to selected paper format. 

However, If by mistake we drag and drop the control it some where else then page size (canvas) gets extended. Is there any option that we can make it fixed? Mostly we want to fix the width.

**Comment by davidjgraph** [comment]
For programming questions please post to SO, https://stackoverflow.com/questions/tagged/draw.io.
