### ISSUE TITLE
Hatching/textures for filling shapes

### ISSUE THREAD

**Issue by gdupont1** [jgraph/drawio#2070]
Hello,

As a way to improve the graphic capabilities of the tool, I would like to have a way to define/specify some kind of texture for filling a shape (instead of just plain color and gradient).
A good example is hatching, which involve two colors woven in a pattern (to represent objects belonging to two domains for instance).

I guess in term of UX the feature kind of follows the "Fill/Gradient" UX style (checkbox + possible configuration). What I am not sure of is how to do it in the rendered view...

Best,
G. D.

**Comment by mararad** [comment]
Hi,

Check the suggestion described here: https://github.com/jgraph/drawio/issues/753. Hopefully, it'll help you.

Regards,
