### ISSUE TITLE
Some add-on shapes are distorted or incorrectly rendered when ui=sketch

### ISSUE THREAD

**Issue by manics** [jgraph/drawio#2071]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When `ui=sketch` some add-on shapes appear corrupt.

**To Reproduce**
1. Go to https://jgraph.github.io/drawio/src/main/webapp/index.html?ui=sketch
2. `Save diagrams to:`, select `Decide later`
3. Click on the `Shapes` button
4. Click on `+ More Shapes`
5. Select `AWS19`, then click `Apply`
6. Under `Shapes` scroll down to the `AWS / ...` shapes and expand, e.g. `AWS / Compute`
7. The shapes appear corrupted, screenshot:
![image](https://user-images.githubusercontent.com/1644105/120705139-5a67b900-c4af-11eb-8c61-907bacc55cf5.png)

**Expected behavior**
Shapes are rendered correctly. For example, they are shown correctly when `ui=min`, and in the default ui:
![image](https://user-images.githubusercontent.com/1644105/120705519-d7932e00-c4af-11eb-8d3b-96707b5c76ab.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version: GitHub `master` branch (14.7.4)

**Desktop (please complete the following information):**
 - OS: Fedora 33 amd64
 - Browser: Firefox
 - Version: 88.0 (64 bit)

**Additional context**
I originally discovered this problem whilst using ipydrawio, which embeds drawio in JupyterLab: https://github.com/deathbeds/ipydrawio/issues/48
It's not specific to the AWS shapes, for example it also occurs with Kubernetes.

**Comment by davidjgraph** [comment]
Need to add sketch=0 to the start of style string for shapes to be excluded.

**Comment by manics** [comment]
Thanks! Feel free to close this issue if you don't think it needs any follow-up.

**Comment by egrimate** [comment]
Will be fixed in next release
