### ISSUE TITLE
Cannot set spacing and border thickness on a shapes text directly

### ISSUE THREAD

**Issue by joel-loewenstein** [jgraph/drawio#2072]
Hello,
when using the function to specify a text an an arrow and set a border i am not able to set a spacing or border thickness nor color... would you consider enabling that? This also applies to other shapes. I just used arrows as an example.

![boder draw 3 io](https://user-images.githubusercontent.com/4130973/120788810-0d2c2b80-c531-11eb-9b81-09b1972ae16d.png)

![boder draw 4 io](https://user-images.githubusercontent.com/4130973/120788825-11f0df80-c531-11eb-959e-82e3e1e427ae.png)

![boder draw io](https://user-images.githubusercontent.com/4130973/120788741-f84f9800-c530-11eb-8386-c8604cc94607.png)

**Comment by alderg** [comment]
This is a known issue. As a workaround try [using HTML for the borders](https://app.diagrams.net/#RjZPLcoMgFIafxmVmgmaSuMy1XbTZpNclEQo0KBYxmj59D4K3yWSmG4Tvh8PhnN8g2qT1g8Y5f1aEyiCckjqItkEYxgjBaMHVgUU8dYBpQRwagKP4pQ6ilpaC0GK00Sgljcg99PETlWU0MaONWGtVjc9%2BKUlG53LM6A04Jlje0ndBDHd0GS56%2FkgF4%2F5mhOaxU1LcbvZXFxwTVQ1QtAuijVbKuFlab6i0tRvXZX9H7RLTNDP%2FOXA4ZHstPyfF7Kxevz8Wef2GJj7KBcvSPzgI5xLirYm42KTN1Vdi%2FlPaTNc5JkRkLIhWIM%2FyGkagMJ6UJlQ7zjS%2Bwgc1cqEk5NBtw8mZaVVmxG2tuDC0Dw8zZr9P%2BGSN5HKBRzXpOMmXs8ssbKJR%2B0x7RxPwmOPEqhWYEhg3qYQVgmkBCuT%2FooBvJygGdKHaCGj5SgqWATVW89dYjdZ3S466RsIPQFVKjbYPb93vW9963y%2Br3kio9TkfmGjZ%2Btd7l3WB%2B%2FbCxHe4XfZOarTB7xjt%2FgA%3D):
![fd91eae116c41566d6ba006f4d5170ab](https://user-images.githubusercontent.com/921200/120917819-94081200-c6b1-11eb-8773-e966f2a27872.gif)
