### ISSUE TITLE
Default properties for shapes

### ISSUE THREAD

**Issue by kartikshah25** [jgraph/drawio#2074]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I work on complex diagrams, that need each of the shapes to have a standard set of properties. Today I have 3 options to achieve this:
1. Manually add the properties (5 of them) to each shape individually
2. Copy an existing shape with the properties and then make changes
3. Copy the date (using the option in the arrange tab) and paste the date in the target shape instance.
All these 3 alternatives are manual and error prone.

**Describe the solution you'd like**
I would a to have an option to define the default set of properties that need to be added to any shape used in the diagram at either the file level (local and preferable) or at the global level (in the configuration). This will help teams to have consistency in the way metadata related to shapes is captured within a diagram.

**Describe alternatives you've considered**
There are 3 alternatives, all manual and error prone.
1. Manually add the properties (5 of them) to each shape individually
2. Copy an existing shape with the properties and then make changes
3. Copy the date (using the option in the arrange tab) and paste the date in the target shape instance.

**Additional context**
None

**Comment by davidjgraph** [comment]
See [https://www.diagrams.net/doc/faq/configure-diagram-editor](https://www.diagrams.net/doc/faq/configure-diagram-editor) , defaultVertexStyle, defaultEdgeStyle.
