### ISSUE TITLE
Add new connection point to shape "Resistor (Variable)"

### ISSUE THREAD

**Issue by pervoj** [jgraph/drawio#2076]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to use shape "Resistor (Variable)" and I must to add another connection point.

**Describe the solution you'd like**
You can add this connection point:
```xml
<constraint name="out2" perimeter="0" x="0.3" y="1" />
```

**Additional context**
![image](https://user-images.githubusercontent.com/71781857/121022969-20dec880-c7a3-11eb-83a0-956297684b95.png)

**Comment by egrimate** [comment]
Will be in next release
