### ISSUE TITLE
Can't save to Github

### ISSUE THREAD

**Issue by SolarDesalination** [jgraph/drawio#2077]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I sign into GitHub on Diagrams.net, it authorizes me, and it shows the folders of my repository, but it will not let me save my diagram. The "Save" Button is unclickable and shows as a lighter blue.

**Expected behavior**
Should be able to save in Github once the folder is selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/51060565/121036131-853a6180-c77c-11eb-9a36-ef367e45a6dc.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
Diagrams.net website.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 -  Version 91

**Comment by mararad** [comment]
Hi,

If you test in other browser or Incognito mode, does it help? If not, clear cache and try again.

Regards,

**Comment by jpdrsn** [comment]
You need to have a branch to save to.
