### ISSUE TITLE
connectors for OPC UA information models

### ISSUE THREAD

**Issue by ahunholz** [jgraph/drawio#2078]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

The OPC Foundation has defined special representations for nodes and connectors for the design of information models. The shapes of the nodes are easy to create. Is it possible to extend the connectors by two types?

**Describe the solution you'd like**

Extending the list of connector end point by two new types of ending. 
1: Filled double arrow heads, 
2: Outlined double arrow heads.

**Describe alternatives you've considered**

https://github.com/cpipero/OPC-UA-Draw.io-Library (Costantino Piperoy designed a library for draw.io, but the connectors don't work, when moving connectd shapes. They consist of two superimposed and grouped connectors with single arrow.)

**Additional context**

https://opcua.rocks/opc-ua-modeldesign-cheat-sheet/ shows shapes and connectors used by the OPC UA information model.
Also the two missing types of connectors with the double-arrow-heads.

**Comment by egrimate** [comment]
Will be in next release

**Comment by dmfort** [comment]
> 
Thanks for adding this.
