### ISSUE TITLE
Change objects dimensions from pt to millimeters (mm) or pixels (px)

### ISSUE THREAD

**Issue by MurzNN** [jgraph/drawio#208]
By default in draw.io documents I see 2 dimensions - page size have millimeters (A4 page shows as 210 x 297 mm), but document elements have size in pt (points), that is confusing.

How can I change default document objects dimensions in draw.io editor from points (pt) to millimeters (mm) or pixels (px)?

**Comment by mullcom** [comment]
If you find any answer to this. i hope you can share it. working with pixel is more easier.

**Comment by alderg** [comment]
Fixed. If you change the units and still see the old units int he format panel, try clearing and reselecting the cells (this will be fixed in the next release).

**Comment by zBugi** [comment]
I tried to use "mm" but there is still "in" as unit when I try to make a custom paper size.
![image](https://user-images.githubusercontent.com/64066508/152757377-a47545d6-8619-449a-89d5-2f1be0b371d6.png)

**Comment by Agedo** [comment]
2025 and custom paper size is still in inches . Only a fraction of people use imperial units. It should be a global setting that changes units universally and consistently.
