### ISSUE TITLE
A couple of Issues in Confluence page view in Confluence Cloud

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#2083]
Tested in Chrome Incognito and Firefox 89.0 (64-bit), Win 10 Pro and draw.io 14.7.7

**In Chrome and Firefox:**
* From Con page view (and from the drawio editor) "Center" works when toolbar is set to Top or EEmbed - doesn't work when Hidden. The user reported the issue with toolbar Embed also but I am not able to reproduce it. Could be due to different OS we are using - he is using macOS Big Sur
* When toolbar is embed Settings drop down is not displayed completely - the buttons on the bottom missing. All is ok with top toolbar
* When the diagram is centered the right diagram border is missing (when diagram is not centered, all borders are there)

**Only in Firefox**
* hover inconsistencies - It seems there is no pattern to follow in order to show/hide diagram borders. Looks random at the moment. In Chrome there is no hover issue, all is ok.

The user submitted all the details + video here:
https://community.atlassian.com/t5/Marketplace-Apps-Integrations/How-do-I-centre-a-draw-io-diagram-in-Confluence-Cloud/qaq-p/1336671?utm_campaign=mentions_reply&utm_content=post&utm_medium=email&utm_source=atlcomm#M87121

**Comment by ashrafteleb** [comment]
Fixed, it should be available in the next release
