### ISSUE TITLE
storage: gitlab, create new diagram file not found

### ISSUE THREAD

**Issue by uritomas** [jgraph/drawio#2084]
We have integrated a self-hosted gitlab into our diagrams.net. We have managed to authorize the application. But when we create a new diagram and select to save it in gitlab we get the error "file not found".

In the console the following appears:
![issue](https://user-images.githubusercontent.com/63196801/121558405-f2b4ef00-ca15-11eb-984c-f0fccc5a54d4.png)

Thanks!

**Comment by rickywu** [comment]
have the same problem, even I didn't updated gitlab

**Comment by rickywu** [comment]
Gitlab api v4 use this URL :GET /projects/:id/repository/tree
But drawio use this.baseUrl + '/projects/' + encodeURIComponent(org + '/' + repo) + '/repository/' +

**Comment by davidjgraph** [comment]
Is this still an active issue?

**Comment by jesayafn** [comment]
please open this issue, im facing it now
