### ISSUE TITLE
Create an interactive diagram in draw.io for Confluence Server

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#2085]
"Create an interactive diagram where you click on an object and it sets the focus to that object. Click on another object and the "graph" redraws. What I want to diagram is:

Data Object | Used in product
Object1 is used by product1, product2, product3
Object2 is used by product1, product3, product5
Object3 is used by product5, product2 and product7

I then want to click on product2 and see what data objects it uses, or click on object2, and see what products use it"

Asked in DID-2448

**Comment by gfoster00** [comment]
That's unfortunate. Thanks for logging it as a feature request though. It would be really good to have it as a differentiating feature for draw.io

I'd be willing to publish to a Google drive location (or similar) if I could demo/experiment with this capability . My question is - how do you do it again? I can't see anything in the drawio UI that enables it.

**Comment by gfoster00** [comment]
Thinking about this request, maybe the "refocus on this object" click event should be a shit-click, or cntrl-click action. This would mean the regular click events (to link to URLs etc) would continue to work as expected, and the <Modifier>+click action could be reserved for the graph recentering/refocusing.
