### ISSUE TITLE
Linking content to attachment in draw.io for Confluence Cloud doesn't work

### ISSUE THREAD

**Issue by Bastesque** [jgraph/drawio#2086]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I link a shape to na attachment in Confluence Cloud, I get a page reload but nothing happens. This applies to both, the dedicated attachment link option and when I try to link to attachments on other pages via search. I also tried Incognito mode and cleared cache multiple times, it didn't help.
 
**To Reproduce**
1. Go to random shape
2. Click on Edit Link
3. Go to > Attachments or search to link to an attachment

**Expected behavior**
Download of attachment or display of the image (if it's an image)

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version > latest version on Cloud
- Google Chrome > latest version (Version 91.0.4472.101)

**Comment by davidjgraph** [comment]
Full page preview event is triggered instead of link follow.

**Comment by ashrafteleb** [comment]
webui link returned in the API is not working. Fixed
