### ISSUE TITLE
Cannot authorize draw.io in Google Drive from the embedded diagram in Confluence - authorization link invalid

### ISSUE THREAD

**Issue by jabba-jedi** [jgraph/drawio#2087]
### Preflight Checklist

* [х] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [х] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Cannot authorize draw.io in Google Drive from the embedded diagram in Confluence - authorization link invalid.

**To Reproduce**
Prerequisites: All pop-ups in Safari enabled.

1. Go to a Confluence page with an embedded diagram.
<img width="776" alt="image" src="https://user-images.githubusercontent.com/6517649/121741050-a4334d80-cb06-11eb-987f-708820ab2019.png">
2. Click on 'Authorize...'. A Google sign-in page opens.
<img width="471" alt="image" src="https://user-images.githubusercontent.com/6517649/121741117-b8774a80-cb06-11eb-955a-a90e84fb4a07.png">
3. Select your account. A page with confirmation opens.
<img width="476" alt="image" src="https://user-images.githubusercontent.com/6517649/121741198-de9cea80-cb06-11eb-89b9-d81ce481f796.png">
4. When you click 'Allow', a blank page opens and nothing happens. I suspect a url is invalid: 

```
https://ac.draw.io/google?state=cId%3D850530949725.apps.googleusercontent.com%26domain%3Dac.draw.io%26token%3D1kmoujm28u07hpnijl91hvermm49b4jpahhti1p0gtinnsinvvdb&code=4/0AY0e-g4UTKufiaMA4L_tQzEOI7vdgx-yU9NT4f2erM61M_EWuxufA2Vb6yN7fFcyKfyAkw&scope=profile%20https://www.googleapis.com/auth/drive.readonly%20https://www.googleapis.com/auth/userinfo.profile
```

**Expected behavior**
I expected a diagram rendered on my Confluence page just as it renders in Chrome.

**draw.io version:** 14.7.7

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.4
 - Browser: Safari Version 14.1.1 (16611.2.7.1.4)

**Comment by mararad** [comment]
Hi, 

If you see the diagram in drive.google.com, could you repeat all the steps in private/incognito window?
This might be related to enabled pop-ups.

If this doesn't help, clear cache as described: close all pages with draw.io diagrams if you have any, go to https://ac.draw.io/clear.html and then re-try.

Does anything help?

Regards,

**Comment by jabba-jedi** [comment]
Hi and thanks for the swift reply,

I tried both methods and unfortunately nothing works, I still get redirected to an empty page.  
![image](https://user-images.githubusercontent.com/6517649/121872121-94398a80-cd0d-11eb-82e5-b8e32013db2b.png)

Google Drive shows draw.io Viewer as authorized, I tried removing it as well and re-authorizing again. After being redirected to an empty page, GDive shows draw.io as authorized, but Confluence still prompts me to authorize and doesn't show the diagram.

Yes, I can access the diagram both on Google Drive (Safari) and in Chrome (Confluence).

**Comment by davidjgraph** [comment]
Are you blocking third-party cookies in Safari? If yes, could you please test with that off?

**Comment by jabba-jedi** [comment]
Thank you, @davidjgraph ! Unchecking both those options and restarting Safari worked.

![image](https://user-images.githubusercontent.com/6517649/122025906-6ec28480-cdd2-11eb-92c5-922e5b15b863.png)

**Comment by huasiy** [comment]
I also encountered a similar issue and eventually resolved it by deleting the cookies saved for draw.io in the browser.
