### ISSUE TITLE
Export Dialog Not High Enough

### ISSUE THREAD

**Issue by mwaeckerlin** [jgraph/drawio#209]
All the `Export as….` dialogs have a fixed height. This height is wrong, it cuts the buttons! Anyway, you should never use a fixed number of pixels in CSS…!

**Comment by mwaeckerlin** [comment]
Here you can see the problem:
![screenshot_20180122_141116](https://user-images.githubusercontent.com/4056726/35222531-8abe34de-ff7e-11e7-966c-4012fd07c6ba.png)

When enabling the inpector, you see the limited height:
![screenshot_20180122_141156](https://user-images.githubusercontent.com/4056726/35222557-9b6dfb2a-ff7e-11e7-8190-628966ccff7f.png)

Simply setting the height to `auto` solves the problem:
![screenshot_20180122_141215](https://user-images.githubusercontent.com/4056726/35222574-ad193240-ff7e-11e7-946b-c87b1a49353d.png)

**Comment by mwaeckerlin** [comment]
Please seth the height of all dialogs to `auto`. The same problem exists in all export dialogs, not only `svg`, but also `png`, `jpeg`, etc.

**Comment by mwaeckerlin** [comment]
My browser is at 80% due to other control elements, but even in 100%, buttons are cropped. Anyway, layouts should be responsive!

**Comment by alderg** [comment]
Grüezi! Bit late to change it at this point, but we can detect clipping and add vertical scrollbars as a workaround.

**Comment by mwaeckerlin** [comment]
@alderg, don't you want too keep the issue open, until fix is done? What does «bit late» mean, on what time line? It is never too late to improve. ;)

**Comment by alderg** [comment]
Bit late means some parts of the code expect fixed size dialogs, we would have to test a lot of code to fix this. We have added it to our internal todo list though.
