### ISSUE TITLE
Can't use onedrive open existing files after authorized

### ISSUE THREAD

**Issue by Castleeee** [jgraph/drawio#2095]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I can't use onedrive open existing files after authorized,but I can open it by open recent files,perhaps there is a problem with Microsoft's auth API? 

**To Reproduce**
1. use chrome or chromium，make sure you have already sing in onedirve
2. close current tabs and choose open existing files
4. See error "Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded."

**Expected behavior**
successfuly open existing file in onedrive and edit

**Screenshots**
![Snipaste_2021-06-17_16-13-58](https://user-images.githubusercontent.com/33923279/122358569-56e03180-cf87-11eb-9b7e-26c0c0ec5577.png)
![a](https://user-images.githubusercontent.com/33923279/122361558-ef77b100-cf89-11eb-9847-8ab893789bef.gif)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [14.7.10]

**Desktop (please complete the following information):**
 - OS: [Windows10 21H1 19043.1052]
 - Browser [chrome, edgeChromium]
 - Version [edgeChromium 91.0.864.48]

**Smartphone (please complete the following information):**
 - None

**Additional context**
sorry I commit it when it not be ready~

**Comment by davidjgraph** [comment]
Could you please fill in the details of the template you deleted?

**Comment by Castleeee** [comment]
> Could you please fill in the details of the template you deleted?

sorry I commit it accidentally when it not be ready~

**Comment by davidjgraph** [comment]
Unable to repeat
