### ISSUE TITLE
There is a problem logging in.

### ISSUE THREAD

**Issue by hyungseokham** [jgraph/drawio#2101]
**Describe the bug**
when i join with google drive pop-up these problem.
![image](https://user-images.githubusercontent.com/86273258/122847661-1d227880-d343-11eb-9b0f-12ce10c0b5e8.png)

How can I solve this?

**Comment by mararad** [comment]
Hi,

Could you translate the pop-up? 

Regards,

**Comment by TheCJGCJG** [comment]
Hi,
I am having the same issue

I have attached a video of what happens in the same situation, this time in English as requested.
This issue seemingly only affects the sign in with Google button, and when you press it nothing happens. All the other integrations are fine.


https://user-images.githubusercontent.com/1349339/123332020-e3ff2980-d537-11eb-831a-7f7fe342cd6a.MP4

I’m using iPadOS 14.6 with Safari.

**Comment by davidjgraph** [comment]
Do you have third-party cookies blocked in Safari?

**Comment by TheCJGCJG** [comment]
I’ve tried both with and without third party cookies enabled, seems to not affect things very much.

I have just discovered though, that this is actually related to Safari’s default pop-up blocking. By disabling pop-up blockers it now works.
