### ISSUE TITLE
Old confluence editor only shows draw.io logo in page edit mode

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#2106]

**Comment by ashrafteleb** [comment]
Cannot reproduce
![Screen Shot 2021-06-24 at 10 25 36 PM](https://user-images.githubusercontent.com/24944765/123360082-28d88f80-d53b-11eb-86c1-1546457a0062.png)

**Comment by davidjgraph** [comment]
If you see this on your Confluence Cloud instance please raise a [support ticket](https://drawio.atlassian.net/servicedesk/customer/portal/14/group/15/create/49) including the storage format of the page.
