### ISSUE TITLE
Export as XML not downloading on Safari on Mac

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#2107]

**Comment by alderg** [comment]
Works for me after clicking "Allow" in this dialog:

<img width="442" alt="Screenshot 2021-06-23 at 11 45 01" src="https://user-images.githubusercontent.com/921200/123075544-9b9d1a00-d418-11eb-8c45-e5fb1668cdc5.png">

**Comment by davidjgraph** [comment]
This is Confluence Cloud specific.

**Comment by ashrafteleb** [comment]
Fixed
