### ISSUE TITLE
Simple viewer doesn't allow full screen

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#2108]

**Comment by davidjgraph** [comment]
Simple viewer disabling causes this, as well.

**Comment by ashrafteleb** [comment]
Added

**Comment by autoantwort** [comment]
I use the viewer within an iframe and want a full screen control:
<img width="200" alt="image" src="https://github.com/jgraph/drawio/assets/41973254/0609c9cc-8222-4221-aa97-8cd756dabf02">
but I don't find the option to add one?
