### ISSUE TITLE
Text has different position when rendering in different browsers

### ISSUE THREAD

**Issue by jsteel** [jgraph/drawio#211]
Text appears to move slightly depending on the browser you are using. I have attached a diagram that I exported as a PNG from Safari (and it includes the XML). I have also attached screenshots of that same diagram rendered in Safari, Chrome, and exported to PNG from Safari and Chrome. Every image looks slightly different. I have done the same thing with two lines and they appear to line up exactly, so I think this is limited to Text elements.
![untitled diagram-16](https://user-images.githubusercontent.com/605442/35355845-9ec462ce-011c-11e8-9108-d51a695ee582.png)
![safari in editor](https://user-images.githubusercontent.com/605442/35355868-b51518b6-011c-11e8-97e0-e52da3359781.png)
![safari as png](https://user-images.githubusercontent.com/605442/35355869-b52555dc-011c-11e8-9823-aa135ae6644c.png)
![chrome in editor](https://user-images.githubusercontent.com/605442/35355870-b5382b4e-011c-11e8-9e74-cd3964e06748.png)
![chrome as png](https://user-images.githubusercontent.com/605442/35355871-b5454054-011c-11e8-8dc4-558c0fce19d7.png)

**Comment by alderg** [comment]
Try unchecking _Word Wrap_ and _Formatted Text_ in the Text format panel.

**Comment by jsteel** [comment]
I did another test and I didn't notice the issue maybe even at all on Chrome, but Safari is very noticeable. Then I tried unchecking Word Wrap and Formatted Text and it actually made the issue arguably worse.

These are all from Safari.

![formatted text](https://user-images.githubusercontent.com/605442/35407179-17d4d45c-01d9-11e8-940d-1428eecc005a.png)
![unformatted text](https://user-images.githubusercontent.com/605442/35407180-17e13530-01d9-11e8-9ecf-9f8f4959e7dd.png)

PNG from formatted text

![png formatted](https://user-images.githubusercontent.com/605442/35407192-244bbd4a-01d9-11e8-96c4-ada8d2e6326c.png)

PNG from unformatted text

![png unformatted](https://user-images.githubusercontent.com/605442/35407195-2608e9fa-01d9-11e8-9d1c-e18f0e416fbf.png)

The server side rendering seems to make it worse in any case, that's what I'm most concerned about. I experience the same issues when using chromedriver instead of phantomjs to render the PNG.

**Comment by jsteel** [comment]
The biggest issue is the fonts rendering differently on the server rendering process. This can be solved by serving the fonts to clients from the server, and then the server can use the same fonts.

There is however still a slight misalignment. It seems to be only a couple of pixels. Notice in the picture below the gap between the first vertical line and the first barcode line.

![screen shot 2018-02-01 at 9 34 02 am](https://user-images.githubusercontent.com/605442/35683941-6c8547de-0733-11e8-9794-6f6be9ecf7a0.png)
![screen shot 2018-02-01 at 9 34 25 am](https://user-images.githubusercontent.com/605442/35683942-6c92c17a-0733-11e8-8ed0-93bd4cb0d3f6.png)

**Comment by jsteel** [comment]
I think it all comes down to the slightest of rendering differences on different operating systems for the two pixel issue above.

The only way to ensure consistent fonts is to use @font-face rules.
