### ISSUE TITLE
Onedrive Integration not working - redirect Uri /microsoft not found on server

### ISSUE THREAD

**Issue by Shubham-Isol** [jgraph/drawio#2110]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I'm trying to fork the webapp frontend code - and integrate the onedrive in it.
Created an app on azure portal and inserted the required client id and secret in environment variables.
But when I try to save file to onedrive - it returns to and URL "/microsoft" which does not exist,
HOW TO SOLVE THIS?

**Comment by Nino171** [comment]
Hey, I can only speak for my own workaround for this.

I did not have a subdomain like `drawio.example.com` but mine was like `example.com/drawio`

when redirecting, I found that it tried to redirect to `example.com/microsoft` while 
### `example.com/drawio/microsoft`
would be the correct link

So i proxy passed `example.com/microsoft` calls to the correct url with my nginx.
I hope that helps

**Comment by Shubham-Isol** [comment]
@Nino171 thanks for reply, can you please tell me what does **example.com/drawio/microsoft** url do.
Because it does not exist in repo code.

**Comment by davidjgraph** [comment]
You have to serve the /microsoft java servlet provided from a servlet engine to deliver that URL.

**Comment by Shubham-Isol** [comment]
Yes, thanks, we were not aware of service the Java servlet backend.
