### ISSUE TITLE
Support line jumps when migrated from Gliffy

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#2111]
Asked in DID-2446

When gliffy file is manually DnD directly into drawio editor or/and File > Import, line jumps are missing. 
Tested in diagrams.net online 14.8.0 and draw.io 9.6.2 

[gliffy 2446.zip](https://github.com/jgraph/drawio/files/6708875/gliffy.2446.zip)

**Comment by ashrafteleb** [comment]
Will be added to the next release
