### ISSUE TITLE
Edit colors in embedded SVG

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#2115]
Reported by a Twitter user liquid8d

I followed the instructions https://drawio.freshdesk.com/support/solutions/articles/16000079239-edit-colours-in-embedded-svg-images and tried to change colors in the example diagram but the following error shows 
"Uncaught TypeError: Cannot read property 'getSelectionState' of undefined" 
when I:
* pick another color and click Apply
* untick a color in Style tab

Tested in Chrome Incognito 
A similar error text shown in FF 

https://user-images.githubusercontent.com/44292306/123787478-28dde400-d8db-11eb-8a75-b0a6293bcbb2.mp4

https://user-images.githubusercontent.com/44292306/123787500-2f6c5b80-d8db-11eb-9a7c-86666b11886e.mp4

**Comment by alderg** [comment]
Fixed in the next release.
