### ISSUE TITLE
Allow customisation of double click menu

### ISSUE THREAD

**Issue by areon546** [jgraph/drawio#2116]
* [-] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.

* [-] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'd like the ability to change what gets shown when a user double click's the paper*. 

**Describe the solution you'd like**
I'd like the ability to change what shapes get shown when double clicking from General and to allow other things, I don't mind the shapes from 'General' being a default but simply put, I want an option to change this to anything else, or at the very least; scratchpad. 

**Extra**
I was unable to provide a screen shot so I shall leave it at this, and as I don't know a better summary for this issue, I shall keep the title as it is,. 
As I either don't know enough jargon to even understand the other feature requests or don't think they are linked, I shall leave the second checkbox marked after having had a look at the titles

\* Not sure what it's called so I'm using what I saw used in the Format Panel to describe where the user places shapes

**Comment by mararad** [comment]
Hi,

We already have this feature request here: https://github.com/jgraph/drawio/issues/1197 Feel free to vote and comment.

Regards,
