### ISSUE TITLE
Improved error message to indicate when project flavour does not support gliffy import

### ISSUE THREAD

**Issue by rechand** [jgraph/drawio#2117]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I'm able to import *.gliffy files on browser based draw.io, but unable to import *.gliffy on windows application version of draw.io. When I try to import or create from existing on windows version of draw.io. I get "Error loading file", but same file was used for browser version of draw.io which works fine.

**To Reproduce**
1. Import *.gliffy or create from existing and use *.gliffy on windows installed draw.io

**Expected behavior**
Import should succeed and I should be able to edit the diagram in draw.io.

**Screenshots**
![image](https://user-images.githubusercontent.com/56243844/123874018-4f584b00-d8ec-11eb-84ab-2b961eb8bbb8.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: 14.6.13

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version:  91.0.4472.114

**Comment by mararad** [comment]
Hi,

Gliffy import on desktop is not supported.

Regards,

**Comment by davidjgraph** [comment]
I've changed the issue to be improving the error message where Gliffy import isn't supported.

**Comment by ashrafteleb** [comment]
Will be fixed in the next release

**Comment by davidjgraph** [comment]
In 16.5.1
