### ISSUE TITLE
Cannot access google drive on Brave browser

### ISSUE THREAD

**Issue by Rem0ld** [jgraph/drawio#2118]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I'm trying to connect to my drive to retrieve a diagram, when I click on open an existing diagram, I have a window with a button sign in, when I click a popup shows up and disappear directly but nothing happens, when I click again on sign in I get an error from google.

**To Reproduce**
1. Go to draw on Brave browser
2. Click on open a diagram with drive
3. Click on sign in

**Expected behavior**
I have access to my drive and I can choose my diagram

**Screenshots**
<img width="1439" alt="Capture d’écran 2021-06-30 à 08 41 28" src="https://user-images.githubusercontent.com/60188728/123913867-043b4800-d97f-11eb-9b12-233ad6e66364.png">
<img width="1436" alt="Capture d’écran 2021-06-30 à 08 41 39" src="https://user-images.githubusercontent.com/60188728/123914013-35b41380-d97f-11eb-8c11-e94cc113315b.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 14.8.2

**Desktop (please complete the following information):**
 - OS: Mac book pro m1, Big Sur 11.2.2
 - Browser: Brave
 - Version: 1.26.67

**Additional context**
It used to work just fine, I didn't change anything on my settings.

**Comment by mararad** [comment]
Hi, 

Is it possible to test this in other browsers? You could try it in private/incognito mode and check if you are getting the same error. 
If you are able to open https://drive.google.com/ you can try opening the diagram from there.

Regards,

**Comment by shoan** [comment]
I am experiencing the same issue with Brave. Everything works fine on Chrome though.

**Comment by davidjgraph** [comment]
Brave is blocking something by default. We don't test Brave. Maybe a user could work out what is blocking and post details.
