### ISSUE TITLE
Excalidraw-like storage & sharing

### ISSUE THREAD

**Issue by borekb** [jgraph/drawio#2120]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

Excalidraw uses an interesting way to store and share diagrams that I find convenient and well-thought-out. Diagrams.net already contain several storage & sharing options, all of them nice & appreciated, but I think an additional one is worth considering as it has several nice properties and could be a great companion to the sketch theme.

**Describe the solution you'd like**

This is what happens when I click "Export a shareable link" in Excalidraw:

- The browser encrypts the data of the current diagram.
- It uploads the data to the cloud storage (S3 or similar).
- It puts the encryption key to the hash part (`excalidraw.com/#json=....`) part of the link. An example of such link is: https://excalidraw.com/#json=5645858175451136,8w-G0ZXiOfRYAn7VWpANxw.

This has several nice properties:

- It's **convenient**. I don't need to think in terms of files and folders, whether I'll use Google Drive or Dropbox, which quirks does a specific sharing mechanism of a specific cloud service has, etc. I just draw and when I want to share a link, I do it.
- Drawings are **immutable** which I greatly appreciate in practice. For example, I can share Excalidraw links in Slack or our internal docs and I know they'll look exactly the same after a month or a year.
    - For example, with Google Drive sharing, I have plethora of options but none of them does exactly that. Immutable drawings are similar in concepts to files here on GitHub, where I can either get a "mutable" version like `blob/master/README.md` or an "immutable" one like `blob/abcd1234/README.md`; in practice, I almost always choose permalinks.
- Excalidraw servers don't ever receive sensitive data – just **encrypted** blobs. This end-to-end encryption is nice both for me as a user and the service itself (less security risks to worry about).

**Describe alternatives you've considered**

Current ways to share on diagrams.net and their relative disadvantages compared to the above:

- Google Drive storage & sharing: requires Google account, makes me think about how to name the file and in which folder to store it, the drawing is not immutable (the best I can do is "Anyone with link can view" and they can then "Create a copy" to edit the diagram – still, the original diagram is mutable, it's not guaranteed that what people see today will be the same as what they'll see in the future).
- Export as URL (Link): this has many of the same properties of Excalidraw's sharing but is inherently unsafe to use as the URL can be very long and rejected by the browser. The URL is not guaranteed to render at all which I find highly problematic.

**Comment by borekb** [comment]
It's possible to get an URL to a Google Drive revision from the **File > Revision history...** history but that URL doesn't work for anyone except me, even if I shared the whole diagram publicly. Furthermore, to access file versions from diagrams.net, I have to give the "draw.io" Google app more permissions (access to all files, not just those by draw.io). One additional downside is that the revision might disappear one day (after some time / 100 newer revisions in Google Drive).

So this is not a solution for "permalinks" either.

**Comment by davidjgraph** [comment]
We don't store any data or PII of any kind across any of our integrations. Changing that would be a huge legal change in terms of GDPR and privacy policies. I don't see anyone on the team wanting to be responsible for that.

**Comment by borekb** [comment]
That's the beauty of end2end encryption – your servers wouldn't store any readable data so this doesn't introduce privacy issues. In fact, I'd argue that uploading encrypted blobs of data is safer / easier to cover by a privacy policy than granting access to cloud storages like Google Drive or Dropbox.

This article nicely explains how Excalidraw does it: https://blog.excalidraw.com/end-to-end-encryption/

**Comment by davidjgraph** [comment]
Make no difference at a commercial/legal level.

**Comment by borekb** [comment]
I understand that someone from the legal department would need to take a look. For example, this is how I imagine your privacy policy (https://www.diagrams.net/trust/) would change:

```diff
#### Diagram data storage

diagrams.net is as fully a client-side application as is technically possible –
diagrams.net does not store your diagram data.

When you choose to store your diagram on your local filesystem, localStorage in
your browser, or in Google Drive, your diagram data and your preferences do not
travel through our servers.

+ When you choose to store your diagram in our Encrypted Online Storage, your
+ diagram data is encrypted on your device before it is uploaded to our servers.
+ The decryption key never leaves your device meaning that we, or anyone else,
+ cannot read the data.

Diagram data stored in the following applications and cloud services are
covered by their respective privacy policies: [...]
```

It is a new paragraph and a new way that diagrams.net can store data so I understand the hesitancy here. I just love the convenience and safety of this sharing model – it is a brilliant idea that I'd love to see in diagrams.net as well.
