### ISSUE TITLE
Images cannot be moved in the sketch theme

### ISSUE THREAD

**Issue by borekb** [jgraph/drawio#2121]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

Moving images does not work in sketch theme.

**To Reproduce**

In the video below:

1. I start the app with `?ui=sketch`
2. I add an image.
3. I can rotate it while selected but I **cannot move** it.
4. I then switch to `?ui=minimal` and add the same image. I **can** move it.
5. I switch to `?ui=sketch` again. At this point, I **can** move the image.
6. I try to add another image in the sketch mode and it has the same problem. One of the images is movable, one isn't.

https://user-images.githubusercontent.com/101152/124101263-771bf000-da5f-11eb-8597-61f44c6da512.mov

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 14.8.0

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome 91

**Comment by mararad** [comment]
Reproduced in Chrome and FF with Win 10 Pro

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
