### ISSUE TITLE
File not found error when opening old files saved as URL

### ISSUE THREAD

**Issue by DirkMartens-Senorfy** [jgraph/drawio#2122]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Hi everyone, 
I have some old draw.io files that i want to open again. But when i try to open them i get the error "File not found". 
The files are about 2 years old and i saved them with a URL. 
The current draw.io version is 14.8.3. I don't know the version in which the files are made
This is one of the URLs that i try to open: https://www.draw.io/#Lhdb3dec.

Are my files lost for good or is there some way that i can recover them.

**Comment by davidjgraph** [comment]
Not sure if you found, but the dec=1 URL parameter stops the redirect so local storage can be accessed under www.draw.io. https://www.draw.io/?dec=1#Lhdb3dec
