### ISSUE TITLE
ungroup list

### ISSUE THREAD

**Issue by Jacob15071** [jgraph/drawio#2123]
I accidentally uncombined the list element and the list item inside it(used Ctrl+A and Ctrl + Shift + U), and then I could not insert the list item. What can I do to fix it?

**Comment by davidjgraph** [comment]
Click undo?

**Comment by Jacob15071** [comment]
> Click undo?

I can't do that because I didn't find it until I saved it and restarted it next time

**Comment by davidjgraph** [comment]
Get the last version out of your cloud storage without the upgroup and copy and paste the group from that version into the latest?

**Comment by Jacob15071** [comment]
But I'm running on a local client, is there a history version?
