### ISSUE TITLE
Navigating from the top container to the underlaying objects

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#2125]
"Stuck with navigation. When objects are stacked on each other (for example, there is an object representing a server, then a container around it representing an AWS VPC, then another container representing an AWS account), then I cannot properly navigate from the top container to the underlying objects. With Alt+click sometimes it works, sometimes not. I have this issue both with the desktop app and Confluence app" - desktop 13.9.9 and drawio 9.5.16. (Con Server) 

Tested in 9.6.2 Win 10 Pro, Chrome Version 91.0.4472.124 (Alt+click is mostly working but it is not consistent 100%)

Chat report https://app.intercom.com/a/apps/fz6gxyi6/inbox/inbox/994666/conversations/55912901513838

The user's vsdx file stripped down:
[navigating through.zip](https://github.com/jgraph/drawio/files/6769330/navigating.through.zip)

**Comment by davidjgraph** [comment]
AWS containers fixed for click navigation in draw.io for Confluence server/DC 10.0.0
