### ISSUE TITLE
Non empty file filed with zeros using diagrams.net online

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#2126]
The user reported:

* "error loading file - not a diagram file" when he tried to open it
* online version 14.8.4 used
* Chrome
* "I have been continuously saving my diagram and this morning my laptop randomly shutdown"
* diagram saved locally 
* no drafts offered when he opened diagrams.net

I tested the file: it showed all zeros and file size is 267Kb

Reported here: https://app.intercom.com/a/apps/fz6gxyi6/inbox/inbox/994666/conversations/55912901548369 with the attached file

**Comment by mararad** [comment]
Reported here: https://groups.google.com/g/drawio/c/3YWTnIoZWc8 by nemanjavacic@gmail.com

" I have the same problem since this morning. File I have been working on for a few days will not load, it keeps showing "Error loading file" I worked on it online and I tried the desktop version too and it's the same thing."

In a private message he added:
"I used it online and saved it on my drive, and it worked fine since last Monday I opened it every day, but today when I tried it showed an error loading file. I tried downloading and installing the desktop version and it shows the same error. I have it attached here so you can inspect it so I might recover it"

File is 10.8 KB and filled with zeros only.

[Story flowchart.zip](https://github.com/jgraph/drawio/files/6929744/Story.flowchart.zip)

![hexed](https://user-images.githubusercontent.com/44292306/128147912-163650f6-fd81-4f69-829c-d416d434e3e5.JPG)

**Comment by chris-cooper3** [comment]
Hello, I have the same issue. Any way to solve this?

**Comment by REZU86** [comment]
Just now it happened to me i was doing my work, suddenly my pc shutdown and everything went to oblivion (even though i was saving the file each time).
