### ISSUE TITLE
[feature] Animation for presentation slides?

### ISSUE THREAD

**Issue by ebousse** [jgraph/drawio#213]
Hi! 

I am relying on draw.io to create figures that I use in presentation slides, which works really great. However, sometimes I want to animate a figure, similarly to what MS Powerpoint or LibreOffice Impress offers (see right pane highlighted with red borders):

![image](https://user-images.githubusercontent.com/5868014/35612882-8cda1a2e-066a-11e8-9ac0-11213cce3b5e.png)

Could we imagine a feature to produce simple animations for presentation slides with draw.io? And to be able to export each frame of the animation into a separate image file?

Note that I already create such animations using draw.io layers, using each layer to add new contents, but (1) a layer cannot hide an element from the layer above (except with a white rectangle...), and (2) I need to export each layer by hand to a new figure: `myfigure_001.png` (with one layer enabled),  `myfigure_002.png` (with two layers enabled), etc.

Thanks for your work on draw.io!

**Comment by alderg** [comment]
There is the anim plugin, but it's not documented: https://www.draw.io/?lightbox=1&p=anim&edit=_blank#R7VrbkuI2EP0aHuPSxdfHHQZ2U5VUpmo2leRRgzVYO8aiZDFAvj6SLYOEMJeFmd2p4AcKteRuSX1Od0swwMPZ6rMg8%2BJ3ntNygEC%2BGuD7AUJJFKpPLVi3Aghj3EqmguVGthU8sn%2BpEQIjXbCc1s5AyXkp2dwVTnhV0Yl0ZEQIvnSHPfPStTonU%2BoJHiek9KV%2FsVwWrTRF8Vb%2BhbJpITfry9qeJzJ5mQq%2BqIy9AcLPzdN2z0inyyy0LkjOl5YIjwZ4KDiX7bc%2Fayr%2BePqm14hASZ7UPhu9zVIrpjQyXrXCulCqEAj1iklOB3q6WG0pvjM9sd%2BzJEyrjgDwh%2BPzhie9drPenrTXBAT7bEB48khwruo9u9N1Rf1dqL%2Brf%2F96ZpDskaX%2B27h5WxvuyLSFzmw1pKUi47htqi8WhJwRgO1yQtBK2ugc97xg2P1KygW14VjLdUegZcEkfZyTiW4vVZBQsy%2FkTKMXNoszsG9WKgV%2F2fAsVJJnVpZDXnLRKFOyERxHWs4raYKF8ha%2BIyWbauxP1MSpGnw3FSRnqmG9bOjXmel6Kl4pNXf%2B0s1uvFIh6coSma34TPmMSrFWQ0xvanyxdpvLbdwIO3cVVsyIEyMkJlZNN5qR7T6z%2B%2Fs9ER%2F3hHpBRU3abvpcCyclX%2BQaTdf00bh5jrjgqP%2FeykcQQsdJEPpewjDzvQSv4aXI89KYC2rSxJnc0zFi18O5yl2myYUs%2BJRXpBxtpXeNJZobX%2Fb5mFb5J507VfOp5JOXrwWrWvGYld0b36iUa%2BNDspBcibY2f%2BN83ml2AION88dkxkrtgy%2B0fKWSTcgOKtK9qDDAfS7pysxwP1J2MAlAHA%2BH7RK6mTS4U21jMApCpKlgerX5mi%2FEhD5QwZSjqdAEYdVUdf6C9sN7E558XxrPtyqNA00lJImYUjPM%2BFQ78hQ0Y4ADjFQO7p7IAXcYRkGErSfuh7Cx8cBZJS0DGDkaoxAHwHqQq9DsWKvDxu6O2hBgR20cJoE9z8hV2%2B6Qp1YhgKytYXM9oO5fTBi6ARpm6Q55W41bKm92%2FCR2w%2FTGyI%2FNSHQ5I%2BFhRkaXMjKMwA51skPUOZWROM6CFMEQpVGiP8PQsdLU529ASYjelpLYS7hfC6qzPdHwVcfG9USxcJe1qpaQO2Q8Bmkj8vihKxNFpfKT6ZixPG94v6%2Fm4mr0c9mwvFDjaLUbBiw6orRrm3nDQzzuhf8ZlVPkxmwI%2FMoJxXvq2%2FAKhVPi%2BXHIVdis6vbQi%2BJSO%2BxJuTSe6m8qOirn6vK29ry7jbjwotoXHTifHKt9jwVbFB4vipXO8D7LALDs3TOhjnftPcCS1vJKrs%2BSIDGBof10kRCDANkP9oABYxQA7GuwcZKEQWw%2F2eWwST3YPKj9YXMmDW5u0HhbaOA9x6sfhIXsYHFm4vetGrtaNZaTuthQ6aTyK%2FGrr%2FTE6kvQUjH61b20vQQtHW6t0PFrpXZNChM5hn7SEYuKd%2Fe77xRUolHa3MH8r4JKqPKNXfLi5GeJMd3l0i3IvFOQoSsm%2F9YbFkSm9c85ESf1I05H%2FFMPfCiBBw98OL3wwHehgVMPgChJg9SmjHsADBMQpNaTJa6ZnvPg99yiIP%2FMJkhVz5m4FW3Xia%2BZe6kXY%2Ff2Lfxpwql%2FfB%2B9kjm%2FAeFKQMAQBlm8cWqUfBBcRJ7vbxet75h1T8qtXSJ1kis6M7mmh29T0aW3qShzfw7E2femz0zlxzhT6RgkAMeom4qVPt%2F%2BBw61IY7VKEkOThom%2BND4y38QiW88%2FZg8xWfyNDvMU3wxT6MdZF%2Fnd0iY%2FojfITE6j6Y4uypNVXP7t7J2%2BPa%2Fe3j0Hw%3D%3D

**Comment by ebousse** [comment]
Thanks for the answer.

I already had looked at the anim plugin, unfortunately, not only it is not documented, but it does not provide any way to export the different frames of one animation into files, in order to include such files in a slideshow (in Impress, Powerpoint or LaTeX). 

Moreover, the result can only be shown in a browser, and without any way to control the animation with the mouse or the keyboard, it seems.

**Comment by jjery2243542** [comment]
Have same problem too.

**Comment by davidjgraph** [comment]
Please vote for the initial comment using the thumbs up, rather than saying "me too"

**Comment by Atcold** [comment]
So, let me outline a plan for getting this issue addressed.
A `PPTX` is a `ZIP` containing an `XML` and a few resources.

In the example below I've imported a `PDF` diagram generated with draw.io.
<img width="1392" alt="Screenshot 2020-08-26 at 18 15 29" src="https://user-images.githubusercontent.com/2119355/91362863-580e5b00-e7c9-11ea-9d39-2bb1d3aee5e0.png">
After unzipping the `PPTX` file, we get the following.

```
slides_pptx_zip/
├── [Content_Types].xml
├── _rels
├── docProps
│   ├── app.xml
│   ├── core.xml
│   └── thumbnail.jpeg
└── ppt
    ├── _rels
    ├── media
    ├── presProps.xml
    ├── presentation.xml
    ├── slideLayouts
    ├── slideMasters
    ├── slides
    ├── tableStyles.xml
    ├── theme
    └── viewProps.xml
```

We're interested in `ppt/media/` and `ppt/slides`.

```
slides_pptx_zip/ppt/media/
└── image1.emf

slides_pptx_zip/ppt/slides
├── _rels
│   └── slide1.xml.rels
└── slide1.xml
```

`ppt/media/image1.emf` is our `PDF` image converted into an `EMF`. Usually (at least on Windows), PowerPoint used to be able to edit `EMF` by simply ungrouping them. This seems not to be working on my Mac. (Can anyone try on Windows?)

<img width="479" alt="Screenshot 2020-08-26 at 18 29 21" src="https://user-images.githubusercontent.com/2119355/91363257-395c9400-e7ca-11ea-977a-5bae99b4b301.png">

Anyhow, `ppt/slides/slide1.xml` says something like:

```xml
<p:pic>
    <p:blipFill>
        <a:blip r:embed="rId2"/>
    </p:blipFill>
</p:pic>
```

And then `ppt/slides/_rels/slide1.xml.rels` has:

```xml
<Relationship Id="rId2" Target="../media/image1.emf"/>
```

All that's needed is saving as many `imageX.emf` we need (possibly one for item in draw.io) grouped together (so that relative position is preserved). In this way, the user can simply ungroup them and animate how she prefers. Therefore, the draw.io to `PPTX` conversion would simply be about populating the `ppt/media/` folder with an exploded version of the diagram, grouped together in a cohesive PowerPoint object.

Let me know what you think about this action plan.

**Comment by Atcold** [comment]
Okay, fixed it! Hahahaha!

![slides_anim](https://user-images.githubusercontent.com/2119355/91365750-e08ffa00-e7cf-11ea-95b6-e4b3806e508d.gif)

I can write a few lines about it, later, if there's interest.

**Comment by alderg** [comment]
This looks pretty cool! If you could share a few lines about it, that would be great.

**Comment by Atcold** [comment]
It's more an hack than a solution, but hey, it works. So, here it goes.

 - Export your draw.io diagram in `PDF`.
 - Create an empty PowerPoint presentation [with page size set to A3].
 - Drag and drop the `PDF` in the presentation [scale it to 200%].
 - Save as `PPT` (not `PPTX`) and quit PowerPoint.
 - Open such file with OpenOffice.
 - Right click on the diagram, select *Break*.

> **Warning 1**
> Every object is going to be split into edge and **white filling** overlayed to a copy with transparent edge and whatever filling. This means that **every filling** will turn white. (This is why the arrows in the animation above are white inside. If you make them transparent, then the black filling below will make them look completely black.)
> Workaround: select every top object and set the filling to *None*. It's time consuming.

> **Warning 2**
> Two white pages (like for every shape above, contour and filling) are generated under the diagram.
> Workaround: select them both and remove them.

 - [Select all the shapes, right click, *Group*.]
 - Save the presentation.
 - Reopen the `PPT` in PowerPoint.
 - Copy the diagram to your main presentation, [ungroup,] animate.

I wish / am wondering if we can save a dark `PDF`. Right now, regardless of the theme, a white version is saved.

**Comment by alderg** [comment]
Why not export to SVG, drag and drop the SVG in the presention, select the image, go to graphic format tab and click on convert to shape?
![328aadc92c5780b4c3c0985c3176e8bf](https://user-images.githubusercontent.com/921200/91439620-92313880-e86d-11ea-8825-3e9b0a42b22d.gif)

**Comment by Atcold** [comment]
`PDF` on the left, `SVG` on the right.

![image](https://user-images.githubusercontent.com/2119355/91654239-2c170200-ea75-11ea-811f-b6ab1c2bf455.png)

**Comment by jeremyVignelles** [comment]
@davidjgraph : I've seen you closed this as "done". Is there any link having more details as how it's been done ?

**Comment by davidjgraph** [comment]
I'm closing because this is outside the scope of the product for me.

**Comment by raintoway** [comment]
i have achieved this function in this [project](https://github.com/raintoway/drawio-desktop) fork from [drawio-desktop](https://github.com/jgraph/drawio-desktop)

**Comment by alderg** [comment]
See also: https://www.youtube.com/watch?v=p8BpZ96DoWY

**Comment by alderg** [comment]
@Atcold SVG should work now with "Convert labels to SVG" Text Settings:

<img width="401" alt="Screenshot 2023-02-09 at 09 06 53" src="https://user-images.githubusercontent.com/921200/217753450-ab7faa4d-b40d-466a-911a-26be6c177492.png">

**Comment by Atcold** [comment]
This creates *huge* issues with sizes and ungrouping.
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/2119355/222536788-79eb67ed-817f-4549-b0bc-ed726498c173.png">
On the left is Default while on the right is Convert labels to SVG.

Moreover, I used to be able to export the colours shown by DarkReader (see below)
![image](https://user-images.githubusercontent.com/2119355/222537003-531e9905-b8d4-424d-a861-5472f16ba97f.png)
while now the black is exported as black (I realise the former was probably a bug).

**Comment by Atcold** [comment]
Oh, my bad, I had to switch the theme to Extra / Appearance / Dark.
Still, stuff is broken now.

On top, you have Default SVG and converted to shape version.
On bottom, there is the Convert labels to SVG version, original and converted to shape.

<img width="891" alt="image" src="https://user-images.githubusercontent.com/2119355/222539448-aeaf632d-03f9-4e32-9d2f-ae06d643624d.png">

**Comment by alderg** [comment]
Exported SVGs with math and dark/light theme should work fine now in PPT (using an image representation of the foreignObject as a fallback where foreignObject is not supported).

**Comment by Atcold** [comment]
Currently, I'm exporting an SVG of the shapes and add the LaTeX by my own.
This seems the least painful alternative.

**Comment by alderg** [comment]
I just tried exporting [this example](https://app.diagrams.net/#R%3Cmxfile%3E%3Cdiagram%20name%3D%22Page-1%22%20id%3D%22kIisCqJz1-3iC9biXr2O%22%3E7Vvbbts4EP0aYZMHF7pYtvtYX3pDCxRNF7v7tGAk2iJWElWKsp1%2B%2FQ4p6mbTtuRAThonMGJySA0pzpnh0VA2nFm0%2FcBQEnylPg4N2%2FS3hjM3bNtyJiZ8CcmDkrjmJJesGPGVrBLckV9YCdWFq4z4OG105JSGnCRNoUfjGHu8IUOM0U2z25KGzVETtMJ7gjsPhfvSv4jPg1zqTpxK%2FhGTVaBGntjjvCFCRV%2BlIQ2QTze5SN6bszCcGaOU56VoO8OhWLxiWfIFeH%2BgtZwXwzFvc8Hc%2BvMTWs9%2B%2BOPxP867IVv97WwHSssahZm6X8MehaBvuqSgFmbNH9RKjH5mtGgYpNJO76CDNUq2VSOUVupbarkvBJ%2BihDKOpE78M0Oc0DgVs4ul7aIk4yReFZfBXdzvqgJZPqdCbDemZ8P6JqLI0b0QTb2AhP4X9EAzXkiL2hRg8YXEElam6ErDLIrrkpQjxhUYh0IQ8CiEsgXFTUA4vkuQJxo3APtcQ4iSlMihpQaGvYylZI2%2F43yxpBRvExT7qpJQEnPMFmuwYDHwkoThjIaUyZtyTNM18VJOiNH%2FcKPFmk9nyh41%2BVL%2BKU13anlSGgoYqEVbY8bx9iCMrBKc4NWYRpizB%2BiiLhi45ii%2FRnn0YFz4%2BKbyj6GjZEHNN4aFTyPlk6tSe4VbKCjodoCxrYHxLjw2JApRLJARUEZ%2BwaqhsG4IOSd3Ch%2BY5cx84xouXDeDulXV4SO6M1jxGEyCiFw0jFK%2BwSnfAc4lcdPKsodDwL65lXWHLW37ti%2FTOp1Mq3YBVK3n72cQW2%2BQmgVss6MFlLbvYmniFdxad3UohDuMEcdTmsV%2BumfXcqbnm3qoMfVQfkzDnS0Z8ozx1F8a47n45uIbWpx53h6SCAr%2FQtNNkEuYuBvJAaBu3qr%2BpablDWwm0%2BB2AIXbXGkg%2B%2BRj7oAMzMib8EEhWcVQDvFStAhTE%2BAN75Q4Ir4vNyImcKMQae1FGxFQUMapwpZVXFCyDbOUlDzjcfhyjsb3IkY%2FNKs1uFgTDVzGffm%2F%2B%2Br%2FDfuUzlp34K4R%2BUQ8aKPuAvFgdJCc%2BmR9kGm%2Bh%2BmgCMvt3TZ%2FBJgyLCIDXcK%2FGQq9LMzSE0RTo183JOt86Xsi18qkCSeRnCBQs6wgw5wKfDAK4ItE%2FRED7fJqU6AVxuUBZuJxjKQeSULBeN%2B0H6WXkLhPwDQh8XxvcjtFO3fftyyNM4z6inbjVyLbE5G1nJZMtredbHJ1O9n4PCZ7zAJnMNlddRfYud4eZbIB4oJ%2BCq4JtBVC5U0u35Iab72tc9s0i3KGS3gqGO4AaiRe8gepY1HWoLPgtdtbLKTQz4amRKglMuYVwwiWO0KRgEl8nybSyCJpp5X3Soh7jv6T49HfakR%2FWxMhbA2g7L4iRLHVvIaIrmT3ESGjjboLhAzrcCr2KNulGSOS0v1gKE6XlEVPxW0XsUCi4K2fvy0%2BlJTz6zdHUVHw%2BxSY7gsnnJZ5FNKnn69tXcxxe4s5r7nTviinLnppKac17M2615c%2Btc7Mnx41whm0c0%2FfJTYRXQpVE%2BMrLrrGIhUKBRG8UZki9XzK6x2m9WSrWSOFLzqSn8iUnmSPWlz0xx51qdLOlp7vpNVZQMUTB4491fAbPw10M6jm6Kvchi9jUF0C9KRBOYkkCSt7LOoWHRj1IxDxdAjxnchM5DQ%2FA2nI%2BLUZfbxvdGd4UaPrUoDdjf5xx41z6efCnNPDMGhGgmcMCQqqlqF8pWZNFOW4GE4sHbfTpYr7A8r15RMPUbuu2YLHUL1W%2Bi5B9XQ5xhrVMwu%2Fq17Okh54%2BlWtr2i7gQn8IeLJonpV62mSCnOceozcy%2BAWyIP8iPqwtnlKIcpiiCVigsaZp2WtlylL5RxwCLhgNEKrGHOSRmWaQ5zoeeIwrcM8WsdODwsvei4b6vGkqtuMk%2BN9l9TlN3o7USsGe01nPDad4bR9F6y3E7TyVdoXu8PV3gy%2BsiOzgr3oeK86FwvuETvEWw%2FwVHf2LSU3zcM0cfxmmx%2FzStX85Hz2Eag5%2Fsru6USFc9FjLtu5Vje%2BvmMtu2VGcoeD3nkBM2aOMR35JF5hJslo8buB58BFAZNcLLl8zwrmFfMsMmpvXL3wQy6728Oy3Y4EnnHIBdXqJzQ5aKsfIjmL%2FwE%3D%3C%2Fdiagram%3E%3C%2Fmxfile%3E) to SVG and imported into Powerpoint:

<img width="1098" alt="Screenshot 2024-06-20 at 08 03 35" src="https://github.com/jgraph/drawio/assets/921200/62e9d260-4d9e-43a6-9ee5-d9b29b408303">

**Comment by Atcold** [comment]
Oh, well, it works on my side as well now.

![image](https://github.com/jgraph/drawio/assets/2119355/6de58694-eb8c-4e1f-9f59-84730647c64a)

Do you know when and how this issue was resolved?

**Comment by alderg** [comment]
On January 23rd 2024 (v22.1.22) by adding an image as the foreignObject alt content https://twitter.com/drawio/status/1757401246917357925

**Comment by Atcold** [comment]
Is there a specific PR I can look at?
Or it's not public?

**Comment by alderg** [comment]
It's not public.

**Comment by Atcold** [comment]
Hmm… is a PNG generated here?

```
Graph.htmlToPng(html, size.width, size.height, mxUtils.bind(this, function(src) {
    replaceElt(switchElt, x, y, size, src);
    imgCache[html] = src;
    next();
}), css);
```

**Comment by alderg** [comment]
Yes

**Comment by Atcold** [comment]
Can you point out the line where the foreignObject is created?
I'm a little lost. 😵‍💫

**Comment by alderg** [comment]
The foreignObject is created [here](https://github.com/jgraph/drawio/blob/dev/src/main/webapp/mxgraph/src/util/mxSvgCanvas2D.js#L1654).

**Comment by Atcold** [comment]
Hmm… So, is 
```js
function replaceElt(switchElt, x, y, size, src)
```
creating the SVG via
```js
var node = mxUtils.createElementNs(root.ownerDocument, mxConstants.NS_SVG, 'image');
```
? Is this the line that replaces SVG data URIs in images with the actual SVG?

**Comment by alderg** [comment]
The function that replaces SVG URIs with the actual SVG is [here](https://github.com/jgraph/drawio/blob/dev/src/main/webapp/js/diagramly/EditorUi.js#L313).
