### ISSUE TITLE
Org Owner unable to commit changes to organization repo

### ISSUE THREAD

**Issue by jessb0t** [jgraph/drawio#2130]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I am able to access and save .drawio files from my personal GitHub repository.  I am also the Owner on another GitHub organization and have full administrative privileges to all repositories.  However, I am unable to commit changes to .drawio files to any repository within the organization.  I get the message below that I am not able to access the file.

**To Reproduce**
1. Open "brainBox-diagram.drawio" in github.com/NDCLab/brainBox from the GitHub account of an individual who is an Owner on the NDCLab GitHub organization.
2. Make a change.
3. Attempt to commit change.

**Expected behavior**
Given my privileges for the repositories, I would expect to be able to commit changes to all org repos just as I can commit changes to my own personal repos.

**Screenshots**
<img width="402" alt="Screen Shot 2021-07-08 at 10 21 07" src="https://user-images.githubusercontent.com/77893711/124948580-6c6cd800-dfd6-11eb-8ddf-bd26d9d53143.png">

**draw.io version:**

- draw.io version 14.8.5

**Desktop:**
 - OS: iOS
 - Browser: Chrome
 - Version 91.0.4472.114 (Official Build) (x86_64)

**Additional context**
- I asked another owner on the organization to try and they were also unable to commit changes.
- I tested removing branch protection rules, but the inability to commit was not related (that is, I cannot commit even when no branch protection rules are in place).

**Comment by davidjgraph** [comment]
Did anyone accept the app scopes on behalf of the org at any point?

**Comment by jessb0t** [comment]
@davidjgraph Excellent question and my assumption is probably not.  Could you kindly point me to documentation on how to accept app scopes for an org?

**Comment by davidjgraph** [comment]
As your personal user, not org, go to settings->applications, select "Authorized OAuth Apps' then click diagrams.net.

There should be a list of orgs you belong to. You request access to the org for the app and I think there's a section in the org admin setting to approve it. I assume you'd also get an email that an admin can click on to approve.

**Comment by jessb0t** [comment]
Thank you very much, @davidjgraph.  This worked perfectly!

Have a lovely week! 😄
