### ISSUE TITLE
Add Digitalocean shapes

### ISSUE THREAD

**Issue by EthraZa** [jgraph/drawio#2132]
I'm not sure that here is the place, if not, sorry.

You guys cold add Digitalocean shapes:

[DO icons download PNG & SVG](https://docs.google.com/presentation/d/e/2PACX-1vSI47aQrXmtAD0WmEEwdyTmMC32J-rgki5pUH1nSDw-uGNxMtcih_mysY88Cs52dsOTVyI9ym5N9zSp/pub?start=false&loop=false&delayms=3000&slide=id.p)

**Comment by mararad** [comment]
Hi,

Unfortunately, it is not possible because they do not allow their icons to be used.

Kind regards,

**Comment by EthraZa** [comment]
Well, so lets add the idea and see what happens:

[Allow your icons to be used by diagram apps](https://ideas.digitalocean.com/ideas/DO-I-3062)
