### ISSUE TITLE
Freehand is unusable

### ISSUE THREAD

**Issue by ShamanthMurali** [jgraph/drawio#2133]
See this video to understand the problem

https://youtu.be/KmGYL4wleSM

Thank you

**Comment by davidjgraph** [comment]
It's not meant for this. It's for freehand drawing, not freehand writing.

**Comment by ShamanthMurali** [comment]
Hello David, then freehand writing would be an amazing and helpful feature to have. Please consider developing it. All the best!.

**Comment by davidjgraph** [comment]
Why not insert text as normal and change to a handwritten font?

**Comment by ShamanthMurali** [comment]
Good point. I am a Commerce teacher. I am using Diagrams.net for online teaching. My teaching involves writing Complex formulas, Drawing complex tables, and accounts etc. It would be quick, simple, and convenient to do via handwritten input.
(formulas via LaTex is time consuming, and tables are basic, these have been my drawbacks so far)

Thank you for your patience.

**Comment by davidjgraph** [comment]
The freehand tool has a new brush option, https://twitter.com/drawio/status/1501886513327616003, that works better for hand writing style.

**Comment by sreramk** [comment]
But having that feature will make drawio infinitely more useful. It will open it up to an entire class of use cases that involves writing stuff.
