### ISSUE TITLE
Set Elements/Groups as repeating Header/Footer on all Pages

### ISSUE THREAD

**Issue by cduerselenBX** [jgraph/drawio#2134]
Currently there seems to be no way to set a certain element or a set of elements as a header or footer that repeats on each page within a sheet. Furthermore it would be great if you could include some markers in the text, such as `[PAGE]` or `[NUM_PAGES]` which get replaced during PDF rendering or printing with the actual page number etc. On the following pages within drawio there could be a representation of the header footer in a lower opacity so you always know that an element would be overlayed by header/footer if placed in this area.

With such a feature you would be able to have a logo repeating on each page and give the pages proper numbering. This would help a lot especially when using big drawio sheets to visualise complex matters and having meetings discussing them, as you could always refer to the page number when sharing the graphics via PDF. 

This feature request I think is somehow similar to #60 although this one is more focused on the specific header and footer elements and not having repeating elements in general. Anyhow probably those two features could be implemented with the same functionality. 

Thank you very much for consideration!

**Comment by cduerselenBX** [comment]
Could probably be merged with #2081 ?

**Comment by davidjgraph** [comment]
What about using a background page with page as a placeholder?

**Comment by cduerselenBX** [comment]
Looks great! Just realised this feature got introduced. Thank you very much !! :-) 

Is there any opportunity to define placeholders on the background page which get replaced by the page number etc. on the final pages yet?

**Comment by davidjgraph** [comment]
That should work, see https://www.diagrams.net/blog/background-pages-diagrams

**Comment by cduerselenBX** [comment]
First of all - THANK YOU VERY VERY MUCH! These features help a lot and I really appreciate your efforts and work.

Most of my use-cases are covered by this feature; the only thing missing in my opion would be that I can define a background repeating on the x/y-axes when there is more than one page within one worksheet like this:
![image](https://user-images.githubusercontent.com/64377439/144238894-3ee994e0-b163-49b9-87cf-da56438915c0.png)
Is there any way this could be easily implemented? 

Furthermore, could it be that in the scenario shown above the %pagenumber% added via placeholder always references the first page on the worksheet (as the page number stays the same although a new page has been started in the document).

**Comment by rdadbhawala** [comment]
Looking for a feature to freeze some pixels as header or footer (both row-wise and column-wise) on a diagram. This way, esp large diagrams like swim-lanes or sequence diagrams, will show some elements of the diagram at the top (or left as the case may be) though we zoom in or navigate the diagram while presenting.

**Comment by davidjgraph** [comment]
I think the initial request was implemented here. Additional requests need to be additional issues.
