### ISSUE TITLE
Hand writing / painting tool

### ISSUE THREAD

**Issue by ericschdt** [jgraph/drawio#2135]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I sometimes need to do quick annotations, paint some graphs or write complex formulas.

**Describe the solution you'd like**
I'd like to have a hand writing feature:
* click on handwriting tool, annotate, paint or write a formula, click on finish: The annotation or formula is now a single object, which could be copied, transformed or connected to other objects on the diagram sheet.

**Comment by alderg** [comment]
Try Arrange, Insert, Freehand (and grouping to create a single object).

**Comment by ericschdt** [comment]
It's just that the `Freehand tool` does not allow writing other than very slow if it shall be readable:


https://user-images.githubusercontent.com/43318127/128542406-302dc991-c301-4d1c-b2be-6338ac0fffde.mp4

(Written on a tablet.)

**Comment by davidjgraph** [comment]
It's not intended to be a handwriting tool, that's outside the scope of the project.

**Comment by ericschdt** [comment]
> It's not intended to be a handwriting tool

This was an direct answer to

> Try Arrange, Insert, Freehand (and grouping to create a single object).

Whereby about the grouping: Some auto grouping at the end of the annotation and non-autoselecting of individual symbol would make sense here.

> that's outside the scope of the project.

Too bad as I think it'd really enhance it.

**Comment by davidjgraph** [comment]
Well, he said try it, not that it was expected to work 8-).
