### ISSUE TITLE
Remove a white space shown when only the layer at the bottom of the diagram is displayed 

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#2136]
Multi layer diagrams is created. When the user choose to display only one layer on the Confluence page, if it is the layer shown at the bottom of the diagram, a large white space above it is displayed and it cannot be removed.

How it looks like when all layers are displayed:

![all layers shown](https://user-images.githubusercontent.com/44292306/125295604-aff07a80-e325-11eb-9647-eee295cda7ef.JPG)

When only the bottom layer is displayed a large white space appears (marked red)

![only the bottom layer is displayed](https://user-images.githubusercontent.com/44292306/125295694-c4347780-e325-11eb-8f77-2b4506d5065a.png)

Reported here: https://app.intercom.com/a/apps/fz6gxyi6/inbox/inbox/994666/conversations/55912901550021
Tested here: https://drawio.atlassian.net/wiki/spaces/DT2/pages/2148204545/test+chat+layers

**Comment by davidjgraph** [comment]
We've looked into this, but it's too technically complex to implement in a reasonable time. Thanks for your input.
