### ISSUE TITLE
draw.io on iPadPro

### ISSUE THREAD

**Issue by lindaonmars** [jgraph/drawio#2138]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Hi everyone,
I just got an iPadPro and it's proving very difficult to connect draw.io to my googledrive and open previous works. Do you know if there's an app release soon? Or someone has any suggestion on how to solve the issue?
Many thanks

**Comment by davidjgraph** [comment]
There won't be a native app, no.
