### ISSUE TITLE
Invalid redirect URL error when authenticating to GitLab UTC

### ISSUE THREAD

**Issue by Teva123** [jgraph/drawio#2139]
**Describe the bug**
I'm getting an 'Invalid redirect URL' error when attempting to authenticate against private gitlab instance (utc).

**To Reproduce**

1.We created a token
2.We created an application id and secret id 
3. We copy the URL (https://app.diagrams.net/?gitlab=https%3A%2F%2Fgitlab.utc.fr&gitlab-id=) and application id on search bar 
4. Attempt to authorize via a private GitLab instance
5.See error on GitLab page (The redirect URI included is not valid)

**Expected behavior**
Authentication should work

**draw.io version (In the Help->About menu of the draw.io editor):**
draw.io version 14.8.6...

**Desktop (please complete the following information):**
OS: Windows
Browser: Chrome, Firefox, Microsoft Edge, Internet explorer
Version: current

**Comment by davidjgraph** [comment]
Having your own private Gitlab instance and using our existing diagrams.net instance does not make sense from a security standpoint. You would have to send our servers your secret (which is better not to attach partial screenshots of).

Your better route is to self-host diagrams.net and set the gitlab URL, app ID and secret on that instance.

**Comment by mbricogn** [comment]
Thanks for this precision @davidjgraph. It does probably not make sense from a security stand point, but it was really helpful from an academic point of view: the students use to store their model directly on our gitlab instance, giving interesting collaborative capacities... It uses to work in march / april... 
I am not sure our IT service accept to host a diagrams.net instance. To help @Teva123, is there a possibility to restore this way of doing? Do you see any workaround?
Thanks a lot for your help !

**Comment by davidjgraph** [comment]
Gitlab deprecated implicit grant of auth tokens, which means the auth has to go via a server and therefore has to use the project secret. @ashrafteleb do we support adding the secret as a URL parameter?

**Comment by ashrafteleb** [comment]
@davidjgraph Currently we don't support secret as a URL parameter since as you mentioned, it is not secure as it should be a "secret"

Maybe we can add a mapping on our servers for private GitLab secrets and domains

**Comment by davidjgraph** [comment]
No, I'm not keen on supporting it as URL parameter, sounds totally wrong.
