### ISSUE TITLE
diagrams.net -Not a diagram file

### ISSUE THREAD

**Issue by JenyLombana** [jgraph/drawio#2145]
I have a problem I was working on the web at diagramas.net and my computer crashed when restarting the pc and trying to open my file again, I get
Error loading file
It is not a diagram file

is there any way to get it back please i need help

![image](https://user-images.githubusercontent.com/87394437/125525054-ffdfea29-99d7-4fe8-8796-fef74077bcd0.png)

**Comment by JenyLombana** [comment]
Yes, of course:
1. browser version  91.0.4472.114 (Build oficial) (32 bits)
2. drawio version 14.8.6
3.  I don't remember if  the draft diagram was offered when I reopened diagrams.net
It came out blank and asked me to open again when opening the last saved version, the error that I told you would already appear

**Comment by JenyLombana** [comment]
and operating system 64 bits

**Comment by JenyLombana** [comment]
hi, is there any way to get the file back
:(

**Comment by alderg** [comment]
Is there a file called ~${filename}.bkp or a file called {filename}.crswap in the directory where the file was originally saved (where {filename} is the name of the original file, eg. MyDrawing.drawio)?

**Comment by JenyLombana** [comment]
I do not have any file with that extension

**Comment by ashed** [comment]
Your file (https://drive.google.com/file/d/13YPkjGEkWwInhPIfs4Qjzuqcu5vizRmQ/view?usp=sharing) contain only NUL values
