### ISSUE TITLE
Invalid Publish Link URL self-hosted

### ISSUE THREAD

**Issue by tuaris** [jgraph/drawio#2149]
### Preflight Checklist
* [X ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I am using v14.9.0 and followed the suggestion in issue #750.  I am still seeing the incorrect URL

**To Reproduce**
1. Set `urlParams['sync'] = 'none';` in `preConfig.js`
2. Click on 'File' -> 'Publish' -> 'Link'
3. Click on 'Create'
4. Incorrect hostname in URL

**Expected behavior**
The correct hostname should be used in publish link

**Screenshots**
![image](https://user-images.githubusercontent.com/5660265/126054593-d08980c8-0d5d-4c5d-927d-658a752bde18.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. '14.9.0]
14.9.0

**Additional Context**
Deployed using branch/tag and pointing web server to  `webapp` directory

**Comment by davidjgraph** [comment]
You need to configure the viewer URL https://github.com/jgraph/drawio/blob/dev/src/main/webapp/js/PreConfig.js

**Comment by tuaris** [comment]
I do have that defined too, but I am still getting the same.  This is my `webapp/js/PreConfig.js`

```
window.DRAWIO_BASE_URL = 'https://draw.domain.tld';
window.DRAWIO_VIEWER_URL =  'https://draw.domain.tld/js/viewer.min.js'; 
window.DRAW_MATH_URL = 'math';
window.DRAWIO_CONFIG = null; 
urlParams['sync'] = 'none';
```

**Comment by alderg** [comment]
Try window.DRAWIO_LIGHTBOX_URL = 'https://draw.domain.tld'. We'll update the PreConfig.js.

**Comment by tuaris** [comment]
That works.
Do I need to keep both (`DRAWIO_VIEWER_URL and `DRAWIO_LIGHTBOX_URL`) or just this new one?

**Comment by alderg** [comment]
DRAWIO_VIEWER_URL references viewer.min.js (a script) and is used for HTML output.

**Comment by polski-g** [comment]
Using https://github.com/jgraph/docker-drawio with the below PreConfig.js, results in error dialog "Error loading file: No file selected" when going to http://draw.domain.com

```
Init PreConfig.js
(function() {
...
})();
window.DRAWIO_BASE_URL = 'http://draw.domain.com';
window.DRAWIO_VIEWER_URL = 'http://draw.domain.com/js/viewer.min.js';
window.DRAW_MATH_URL = 'math';
window.DRAWIO_CONFIG = null;
window.DRAWIO_LIGHTBOX_URL = 'http://draw.domain.com';
urlParams['sync'] = 'manual'; //Disable Real-Time
urlParams['db'] = '0'; //dropbox
urlParams['gh'] = '0'; //github
urlParams['tr'] = '0'; //trello
urlParams['gapi'] = '0'; //Google Drive
urlParams['od'] = '0'; //OneDrive
urlParams['gl'] = '0'; //Gitlab
Init PostConfig.js
...
```

**Comment by imshenyz** [comment]
> Using https://github.com/jgraph/docker-drawio with the below PreConfig.js, results in error dialog "Error loading file: No file selected" when going to http://draw.domain.com
> 
> ```
> Init PreConfig.js
> (function() {
> ...
> })();
> window.DRAWIO_BASE_URL = 'http://draw.domain.com';
> window.DRAWIO_VIEWER_URL = 'http://draw.domain.com/js/viewer.min.js';
> window.DRAW_MATH_URL = 'math';
> window.DRAWIO_CONFIG = null;
> window.DRAWIO_LIGHTBOX_URL = 'http://draw.domain.com';
> urlParams['sync'] = 'manual'; //Disable Real-Time
> urlParams['db'] = '0'; //dropbox
> urlParams['gh'] = '0'; //github
> urlParams['tr'] = '0'; //trello
> urlParams['gapi'] = '0'; //Google Drive
> urlParams['od'] = '0'; //OneDrive
> urlParams['gl'] = '0'; //Gitlab
> Init PostConfig.js
> ...
> ```

I have encountered the same problem. Is there any solution?

**Comment by davidjgraph** [comment]
The second issue needs a new issue opened.
