### ISSUE TITLE
[feature] Custom palette/swatch system to share same colors among elements

### ISSUE THREAD

**Issue by ebousse** [jgraph/drawio#215]
It is rather common to reuse the same color for many different objects of a diagram. When wanting to replace this color with another one in draw.io, it is necessary to select all objects using this color (without missing any), and to change their color all at the same time. However, this can become very tricky in complex diagrams with dozens of elements, especially when the color to change is used in different kinds of objects (text, shapes, arrow, etc.).

Inkscape solved this solution through the "palette/swatch" system, which enables the creation of labeled colors, which can then be applied to different objects. This is very powerful, because changing the color of a labeled color will change the color of all objects using this label.

Example, with two labeled colors `mycolor2` and `mycolor3`:
![capture d ecran de 2018-02-06 15-02-23](https://user-images.githubusercontent.com/5868014/35863660-a2d3ead2-0b4f-11e8-881c-cfdfae22f923.png)

And if we change `mycolor2`, the color of both rectangle changes automatically:
![capture d ecran de 2018-02-06 15-03-18](https://user-images.githubusercontent.com/5868014/35863689-b84e889a-0b4f-11e8-8841-6bc7782ebe0a.png)

Could we imagine something similar in draw.io in the future?

**Comment by davidmlw** [comment]
I think this feature is very useful. Will drawio support this?

**Comment by AlexandreBonneau** [comment]
I think the initial feature request is still valid.
Could you please re-open it?
