### ISSUE TITLE
Support for different color models

### ISSUE THREAD

**Issue by akinuri** [jgraph/drawio#2150]
Will there ever going to be support for different color models? While there is a swatch to pick colors from, it eventually ends up in a hex value. I don't find hex easy to work with. It'd be more practical if there was a way to switch between models (hex, rgb, hsl, etc.).

![color window](https://i.ibb.co/ZXd5RqY/Annotation-2021-07-18-193325.png)

**Comment by alderg** [comment]
We'll add a "..." button next to the input element for selecting the color in different color models:

<img width="284" alt="Screenshot 2021-08-06 at 10 55 03" src="https://user-images.githubusercontent.com/921200/128485052-c738c84f-b6f5-4b4f-83c5-96072f7af8b9.png">

**Comment by akinuri** [comment]
Just came across: https://twitter.com/drawio/status/1430123597096538120 🙂
