### ISSUE TITLE
get the corresponding DOM element of the selected 'cell'

### ISSUE THREAD

**Issue by a1371083012** [jgraph/drawio#2152]
* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.

**questions**
Hello everyone
Is there a way to get the corresponding DOM element of the selected 'cell'?
thus DOM elements can be manipulated
thx

**Comment by a1371083012** [comment]
How do I manipulate a Cell's corresponding DOM element

**Comment by DimaDushak** [comment]
Hello. I need too. I want to add a handler to add the functionality I need, but I don't know how to pass the selected diagram elements to the function.

Thx
