### ISSUE TITLE
"Unknown error" when loading juniper stencils

### ISSUE THREAD

**Issue by platinum55** [jgraph/drawio#2154]
Hello,

this is related to issue #1708 - at least the "MX Series Icons" produces an unknown error when trying to load - QFX Series works.

Output from `file` on QFX and MX series vss file:
```
Juniper QFX Series.vss: Composite Document File V2 Document, Little Endian, Os: Windows, Version 10.0, Code page: 1252, Title: Juniper QFX Series, Author: Visimation Inc. http://www.visimation.com, Comments: Revised 10/2/19Revised 3/13/19Revised 8/21/18Revised 4/11/18Revised 1/7/18First issued 1/27/11 (as QFX3500)Visio 2003-2010 format, Name of Creating Application: Microsoft Visio
```
```
Juniper MX Series.vss: Composite Document File V2 Document, Little Endian, Os: Windows, Version 10.0, Code page: 1252, Title: Juniper MX Series, Author: Visimation Inc. http://www.visimation.com, Comments: Revised 7/28/20Revised 10/24/18Revised 5/23/18Revised 4/24/18Revised 1/31/18Revised 8/14/17First issued 10/29/06 as MX960Visio 2003 and later formatRenamed MX Series with MX480 and MX240 routers added 10/26/07Revised 7/2/10, Name of Creating Application: Microsoft Visio
```

**Comment by davidjgraph** [comment]
Could you link to the exact sources for these two please?

**Comment by platinum55** [comment]
sure, sorry - forgot about that
(working) QFX Series: https://www.juniper.net/content/dam/www/assets/images/us/en/company/image-library/juniper-qfx-series-icons.zip
(not working) MX Series: https://www.juniper.net/content/dam/www/assets/images/us/en/company/image-library/juniper-mx-series-icons.zip

**Comment by mararad** [comment]
Hi,

We have 50MB file size limit. This is the reason why MX Series Icons can't be loaded.

Regards,
