### ISSUE TITLE
Allow custom connect point in XML format

### ISSUE THREAD

**Issue by TennyZhuang** [jgraph/drawio#2157]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Currently, drawio supported custom shape:

```xml
<shape h="100" w="100" aspect="variable" strokewidth="inherit">
  <connections>
    <constraint x="0" y="0" perimeter="1" />
    <constraint x="0.5" y="0" perimeter="1" />
    <constraint x="1" y="0" perimeter="1" />
    <constraint x="0" y="0.5" perimeter="1" />
    <constraint x="1" y="0.5" perimeter="1" />
    <constraint x="0" y="1" perimeter="1" />
    <constraint x="0.5" y="1" perimeter="1" />
    <constraint x="1" y="1" perimeter="1" />
  </connections>
  <background>
    <rect x="0" y="0" w="40" h="100" />
    <fillstroke />
    <rect x="40" y="0" w="20" h="100" />
    <fillstroke />
    <rect x="60" y="0" w="40" h="100" />
    <fillstroke />
  </background>
  <foreground>
  </foreground>
</shape>
```

But there is a really useful feature that cannot be customized currently: the connect point.

<img width="589" alt="图片" src="https://user-images.githubusercontent.com/9161438/126736851-66723ca1-9b68-42ef-ba18-97b9e3c8ab42.png">

Arrow can be on dragged automatically only on four fixed points, it seems that there is no solutions to add more connection points. Sometimes, we want drag arrow from center of the custom shape, or other positions easily.

**Describe the solution you'd like**
Prefer to add some new tag in `<connections>`, such as

```xml
<shape h="100" w="100" aspect="variable" strokewidth="inherit">
  <connections>
    <constraint x="0" y="0" perimeter="1" />
    <constraint x="0.5" y="0" perimeter="1" />
    <constraint x="1" y="0" perimeter="1" />
    <constraint x="0" y="0.5" perimeter="1" />
    <constraint x="1" y="0.5" perimeter="1" />
    <constraint x="0" y="1" perimeter="1" />
    <constraint x="0.5" y="1" perimeter="1" />
    <constraint x="1" y="1" perimeter="1" />

    <connect x="0.5" y="0.5" direction="UP">
  </connections>
  <background>
    <rect x="0" y="0" w="40" h="100" />
    <fillstroke />
    <rect x="40" y="0" w="20" h="100" />
    <fillstroke />
    <rect x="60" y="0" w="40" h="100" />
    <fillstroke />
  </background>
  <foreground>
  </foreground>
</shape>
```

Or some other names, and more attributes.

**Describe alternatives you've considered**

**Additional context**

**Comment by alderg** [comment]
Have you tried the points style? https://www.diagrams.net/doc/faq/shape-connection-points-customise
