### ISSUE TITLE
Gitlab wiki support

### ISSUE THREAD

**Issue by quickstar** [jgraph/drawio#2158]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Gitlab allows you to create groups which can then contain several repositories. Gitlab provides a simple wiki for sub project and also on the group level. Even though the group itself is not a git repo, the wiki is basically a dedicated repo.

For any project I was able to create an edit link in the following format: `https://app.diagrams.net/#A{group-name}%2F{project-name}%2Fmaster%2FArchitecture%2FOverview.png`

This is very handy because this allows us to embed a figure with an `Edit` button directly in a markdown file like the example below.

```html
<figure class="video_container">
  <a><img src="https://gitlab.com/{group-name}/{project-name}/-/raw/master/Architecture/Overview.png" alt="System overview"/></a>
  <figcaption>Figure 1. System overview | <a href="https://app.diagrams.net/#A{group-name}%2F{project-name}%2Fmaster%2FArchitecture%2FOverview.png">Edit</a> | <a href="https://gitlab.com/{group-name}/{project-name}/-/raw/master/Architecture/Overview.png">Full Screen</a></figcaption>
</figure>
``` 

Unfortunately this seems not possible with the wiki in general. Any ideas?

**Comment by lfvjimisola** [comment]
We would also like to be able to load/save with wiki repo and not only project repos.

**Comment by davidjgraph** [comment]
To indicate support for an issue thumbs up the original post. Please do not write "+1" or "me too".

**Comment by davidjgraph** [comment]
Declined.
