### ISSUE TITLE
Linking to cloud does not work using Firefox

### ISSUE THREAD

**Issue by oscardssmith** [jgraph/drawio#216]
I just started using draw.io, and I can't get it to link with my google account on Firefox. It works for me using Chrome. If it matters, my gmail account has 2fa. Thanks.

System info
OS: Ubuntu
Browser: Firefox 58.0.1

**Comment by davidjgraph** [comment]
Could I get you to post on https://groups.google.com/forum/#!forum/drawio please? This is for dev questions, thanks.
