### ISSUE TITLE
Words split by "/" should wrap

### ISSUE THREAD

**Issue by craigbossley** [jgraph/drawio#2160]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Keywords: word wrap, line wrap, line break, word break

**Is your feature request related to a problem? Please describe.**
I always expect words/lines to split when they are separated by a slash ("/") in the same way that they do when separated by any sort of dash or hyphen ("-/–/–"). Presently, the only way to do this is to add a space after the slash which is easily forgotten when resizing things.

**Describe the solution you'd like**
For word wrap, words separated by a slash should behave the same as those separated by a dash.

![image](https://user-images.githubusercontent.com/46577343/127426662-72b3b063-9213-41ae-853b-426cf420e1c1.png)

**Comment by mararad** [comment]
Reproduced in Chrome Version 91.0.4472.124 and diagrams.net 14.9.3

**Comment by davidjgraph** [comment]
This is built-in browser functionality, we're not going to implement an override.
