### ISSUE TITLE
Google Font Archivo doesn't contain bold font when exporting as PDF

### ISSUE THREAD

**Issue by Alvie** [jgraph/drawio#2167]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When using the Google Font "Archivo", bold texts don't become bold when exported. It seems like it only happens with Archivo as I have tried with other variable weight fonts on Google Fonts (e.g. Catamaran) and haven't come across the same issue.

**To Reproduce**
1. Add a text box
2. Use the Google Font: "Archivo"
3. Make the text in the text box bold.
4. Export as pdf

**Expected behavior**
The text in the text box should be bold

**Screenshots**
![image](https://user-images.githubusercontent.com/8447791/128041056-ba6ca978-eab6-4bdc-8b1a-9f23e1e3b8ad.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: 14.9.3

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome v92.0.4515.107

**Comment by davidjgraph** [comment]
Try print to PDF.
