### ISSUE TITLE
Shape connections constrain with 90° rotation

### ISSUE THREAD

**Issue by axydraw** [jgraph/drawio#2168]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
In a shape the \<connections\> can be defined with e.g. \<constraint x="0.15" y="0" /\>.
This does work correct as long as the shape is NOT rotated 90° or 270° with 
the menu "Arrange" and its Angle command "Rotate shape only by 90°".
However this command is required to keep the text of an item non-rotated.

**Expected behavior**
I expect, that the connections point are kept when rotating 90°, 180°, 270° and 360°.
Currently they are ok with 180° and 360° only, but not for 90° and 270°.

**draw.io version**
- draw.io version 14.6.13

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit

**Additional context**
With manual rotation of any degree xx° the connection points are ok,
but of course the text is also rotated (unwanted!).

**Comment by mararad** [comment]
This issue is closed because it is duplicated https://github.com/jgraph/drawio-desktop/issues/687
