### ISSUE TITLE
Popup names for custom colours

### ISSUE THREAD

**Issue by plumcloth** [jgraph/drawio#2169]
Hi - It would be really useful to see a name pop-up when we hover over a colour in the Default Colour Schemes part of the editor. I'm going to add a series of custom colours each of which represents a different part of our business, so it would make it easier to use for colleagues if we could add names to the custom colours, and have them pop up when hovered over.
Thanks, Pete.

**Comment by alderg** [comment]
Do you mean the preset-/defaultColors or defaultColorSchemes?

**Comment by alderg** [comment]
We'll add colorNames and title for defaultColorSchemes for tooltips in the next release. See https://www.diagrams.net/doc/faq/configure-diagram-editor
