### ISSUE TITLE
underbrace not exported to pdf

### ISSUE THREAD

**Issue by Murmele** [jgraph/drawio#217]
Hello,
when I try to export the graphic below, the underbrace will not be exported to the pdf. The text of the underbrace is shown.
Attached you find also the graphic (I had to add .txt at the end, because otherwise Github didn't let me to upload the file):
[RegelungPropeller.txt](https://github.com/jgraph/drawio/files/1702405/RegelungPropeller.txt)
[Link](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=RegelungPropeller#R7V1bb5w4FP41I3UfEmHuPDbTtKuqkaLtSts%2BVWTGM8OGwIght%2F76tcEGfGHCzNhcJhtFDRhs4Fy%2Bc%2FGxO7PmDy9fsnC7uUmXMJ6ZxvJlZn2amSYIfAv9wS2vpMWynLJlnUVL0lY3fI9%2BQ9JokNbHaAl3zI15msZ5tGUbF2mSwEXOtIVZlj6zt63SmH3qNlyTJxp1w%2FdFGEPhtn%2BiZb4pW33Tq9v%2FhNF6Q58M3KC8chcu7tdZ%2BpiQ581Ma1X8lJcfQjoWecJuEy7T58arWNcza56laV4ePbzMYYyJS8lWvu%2FnlqvVe2cwybt0sAmndvkr%2FXa4RKQgp2mWb9J1moTxdd16VXwfxCMY6GyTP8ToEKBD%2BBLlPxrHP%2FEtlw46%2Bxfm%2BSvhc%2FiYp6ipHvtbmm5JL%2FH9KaHSx2xB3tCyiUiE2RqS22yzbMNv3%2BhIvvoLTB9gnr2iGzIYh3n0xDI6JPKyru6raYYOCNnkJHTJGE9h%2FEhGvRGImsOXnKVVBnfR7%2FCuuAGTcZtGSV68hnM1cz6hljCO1glqWCBawAw1PMEsj5CQfiQXHqLlsmBIHN7B%2BKoSvXkap1nxXCp8MsJS1uNR4ctMolbk7RjRZGhJ1PuCjNSZtGSkW%2FzJjVvS1WqH%2BMnTvnpgJ3ZQ4Wiw4y%2B4jhEBeZ48b6Icft%2BGhVg9IyRjGRTutiW0rKIXLOyc2K%2FjcLcjx7s8S%2B9hg%2BxG8bNPngWqi9QlVz2HYAsFU5dg1nONTIDi2KaJSrTxFOmmwN0gp0BILHXbAwiUpAk8iDbdJZL0ck2OZr5Is0BCMl8Fxdy3KYZ6IFOGiXCoEIpEqzjUWaKoXLyypw3a2BLa2Cpo4wu0uTgCK7EF2ZXGBBwElCLIrqI45uRSKqztsq2BIxINlym4Ev0OJNJ69a550q4WuphAVWsvZCTLj9izxTTFXxotON8rQQ%2F9Qb6%2FOKm9r3a%2FrBWDGX%2BLIFrT36Jm9k1%2Fq0E%2BR0I%2B2nas70BYaVks4FsOx5bye0ivpkPMD%2BRzAxncQCURhIGO8FRsR2Ty6H1v6mczvndXWVDve4uKc3sEdvXve7eh0cGezoVxaViMxF6Yp2mUUm%2FclQDZkDK%2BDyW7yb8k9nSVy78cm4DFubWC8VEHTi6NDmvNWmynoFpU4pSolmUDc7zKZYuh7sy08a8zX2XhYuYhks9juMo%2F1C3JL%2FRPtMtn3qfi9wphKPrrzDNslP8o2%2FDpJkVDV%2F2LQzqEtKNzjZl87eDG8i0mGnADMGjE7cg8cmnErS9%2BDhx7QApQH2MfBYaRpYo3bwtTP5TyzoBS9CobAwOJxBkyOvIO%2BlE614GOjQCMxJ%2By6AtcGsgfY3yLRsMtzCL0ctjslR4IcWjo8c%2BGc8Pf205jxj%2FxRP%2BEto0lVnMYRgdHRmo%2BOwyfnlLnCjli0upI4TAE4XhLMMB7EgwuCyYgZFfJQB0vrcaP6TLjclctYOuSHNcVBUVH9LMvqlEa%2Fbuy6MfpKETqo3%2BZp0T836cw224i7OvuUtSp1ScdYwRDJxCUJAdQ1MhI%2FwU4TVfVpgf2RDAlB9HFDzjwnH%2F9A8cg%2BBZjsf3QuI6vONeI0ejLjg09hoo0rC6RhqvLe3T9c4MnRwJPXW2ccnjyZFl9AZ5IKD4ddKLekAp0Mg1OAcaFTrK5b8JArATZXYYBpUiXkNQIKFMj6IWv%2Fv7VBDF0vFim%2BBV3ZeYF8%2F42yheb5yi5h3EG1zB%2BTNaTgzAnGDJZ4nn9QFhv%2BWVX4qZ7lmoIa%2FG%2Fq1k96im72oIqQBOrgnLd%2FPo2HTSk8qcEDe2K0ydPFLA91KChLEeyHw1ZR80gvhqfWu6cmnau0XcZVZL52Ox2Cb1ZukXfh8vCjBtEBiQdCQJKuLiHk4NgrwMEm9LcmRIIlikyR7jxVYiZBlcxICsR83TlGz1xdk20YwprxCoeTaBGzJPFhGdYkXQ4T2yZWotMUKLUYhHjGRbqHcCC%2FovCfNH%2BTDs6pwDbdG195a5tZ%2FLuic7ZYO7r1BwCs8sEtq%2FLH%2FAlpmzSckuNNSO3xlByG%2FRNXiCSd4dIkXPzXUXb5wi%2FN%2BEIPyOGWhrX1UKLjEW%2BahYVXdFHha%2BNG4ilag%2Bqbc7RFJZkvdXBcg1OQMp3ODr0NtpC72SKCUmqEEpC8AAAwBB%2FVGubfFnYQGxW8bgpGSnTG9BIBVrWPdbV9szkfuMSxVFwOIrWVf81kALlQOqLQDrcDEqgJbvbLLaZoq2TsCgYbA7e71Icc3Qm4xhsagaKqjNtfsAmyC3HETALSJNGCpRBy2ztxJUhkMz4Bu5QygAMoIVHglnp2XTss2JHs6m%2FVRMu50%2Fz2qhuVivosFr6fNDQtoZDwyoN%2F78Hx6maZLHmcAv0Aq2L4cemECYYUiF6Wk66L%2B82Ov8AGJKK1SEdBC0VwdNHLSmfhtvTBxh9R55T5pM1oD7JJovP1r4YBr%2FLQZ%2F2paf4kxH7Wqibkg%2F6NiPqJVweqzjcxJ3GBd6AypJ8FmByqyYq%2BVRTmEwXfb0yA41iFgCAnkKfMWpiX7WwvCbyO4O1KOLBs4OGJ32Osrk%2BOp0lKbOdpJZT2T9dy43LwHNHpddqlwv2VrIOgCS7B9TPGrVpEOcUObR2TUfRupjfO6%2FNJR2awehl9QYAHdJD46sd5neXdCyRaLp2lwSgy1YFCkuHax5NoHYYgHexweTpPOlxh0kAZIHGGRZ0H8KV%2FsuJK8Ae6SaTFbAxXgToWtgwzDaTHs0%2FnbrNpOtwAyl0WrrsLjo%2BIyss0JFZWW0LdIAti5t0mlm7LbAZo5mV7tB1jpB%2BOFd6XKQDbLEe9By9nQOYMIBdtcXEybTXOwBbFs%2FbQUdLrH6Sx96zD8O5LdWRBeDaqqCBfW4bVFV2m5Xdwcpjgd3TBhWjnCymmMG69HoSgyevy3HIwuPO63I8sL%2BD6%2B69n83ti735CEFf1SKwZUXck10QVOncOFcE0aEtdlfCC34bQjVzClQFz3LJUL%2FGUs9e9tMogNCF2m%2FOu1JU1gF7kj3uJ10BoXTr%2B1FXQLhaYq5pVEBULm7fqliV%2B%2BuugaAPUlYE0bqR30SLIKptU8%2BxCKK3TUk1LI8So9tuKi3b9U%2BDnnd3dQ7f6%2B397Xzp8oUnOmsn0Gn9vwKXelX%2F38vW9X8%3D)

Best regards,

Martin

**Comment by arnowelzel** [comment]
JFTR: works for me, I see the underbrace in the PDF. @Murmele did you ever try that again?

**Comment by Murmele** [comment]
With the Browser it works fine. But at the moment the appimage package has some problems to show the bracket.

**Comment by davidjgraph** [comment]
Does this still happen on new export system?
