### ISSUE TITLE
An error when I create the canvas (use Device mode): `The request is not allowed by the user agent or the platform in the current`

### ISSUE THREAD

**Issue by XinRoom** [jgraph/drawio#2172]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I get an error when I create the canvas (use Device mode): `The request is not allowed by the user agent or the platform in the current`

```js
app.min.js:10394 INFO NotAllowedError undefined undefined undefined DOMException: The request is not allowed by the user agent or the platform in the current context.
```

Original error:
```js
DOMException: Failed to execute 'showSaveFilePicker' on 'Window': Must be handling a user gesture to show a file picker.
    at App.showSaveFilePicker (https://app.diagrams.net/js/app.min.js?__WB_REVISION__=634fd4673e5f2803e5a4be0e2d7e4d4c:11364:288)
    at App.createFile (https://app.diagrams.net/js/app.min.js?__WB_REVISION__=634fd4673e5f2803e5a4be0e2d7e4d4c:11393:95)
    at https://app.diagrams.net/js/app.min.js?__WB_REVISION__=634fd4673e5f2803e5a4be0e2d7e4d4c:9910:355
    at App.pickFolder (https://app.diagrams.net/js/app.min.js?__WB_REVISION__=634fd4673e5f2803e5a4be0e2d7e4d4c:10561:101)
    at App.pickFolder (https://app.diagrams.net/js/app.min.js?__WB_REVISION__=634fd4673e5f2803e5a4be0e2d7e4d4c:11434:466)
    at A (https://app.diagrams.net/js/app.min.js?__WB_REVISION__=634fd4673e5f2803e5a4be0e2d7e4d4c:9910:323)
    at https://app.diagrams.net/js/app.min.js?__WB_REVISION__=634fd4673e5f2803e5a4be0e2d7e4d4c:9930:172
    at HTMLButtonElement.<anonymous> (https://app.diagrams.net/js/app.min.js?__WB_REVISION__=634fd4673e5f2803e5a4be0e2d7e4d4c:284:62)
```

**To Reproduce**

1. Close the file modification permission of the page on the browser.
2. Go to 'https://app.diagrams.net/?src=about'
3. Click on 'Device Mode', 'Create New Diagram', 'Create'

**Expected behavior**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/32238570/128619364-6d0e3659-a0aa-422c-991e-d816a9bbc7ce.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io [14.9.5]

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [92.0.4515.131]

**Comment by XinRoom** [comment]
I found that it was caused by my default prohibition of modifying file permissions, I hope there is a clear prompt.

**Comment by XinRoom** [comment]
> @XinRoom can you tell me where to change that, im having the same problem but cant find where to change that permission. Also there could be a warning for the reason of the error and instructions to whitelist it.

Here:

![image](https://user-images.githubusercontent.com/32238570/141097070-9a2dc566-4dbf-45ed-8ed9-6da483423212.png)

**Comment by methane4** [comment]
> > @XinRoom can you tell me where to change that, im having the same problem but cant find where to change that permission. Also there could be a warning for the reason of the error and instructions to whitelist it.
> 
> Here:
> 
> ![image](https://user-images.githubusercontent.com/32238570/141097070-9a2dc566-4dbf-45ed-8ed9-6da483423212.png)

@XinRoom Thank you!
