### ISSUE TITLE
Syncronize option don't appear on Brave browser

### ISSUE THREAD

**Issue by baciucristian** [jgraph/drawio#2174]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
On Brave browser the syncronize feature don't appear. 

**To Reproduce**
1. Go to 'File' tab

**Expected behavior**
The synchronize feature should appear.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/49842769/129033463-f2dfa04b-40d1-4179-9637-c44645dee4e7.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 14.9.4

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser: Brave Version 1.27.111 Chromium 92.0.4515.131

**Comment by davidjgraph** [comment]
We don't test Brave, a user needs to debug this.
