### ISSUE TITLE
PDF Export - Hyperlink not working

### ISSUE THREAD

**Issue by Amulya-sb** [jgraph/drawio#2175]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Export as PDF in Advanced options when width and height specified , hyperlink added through Edit Link option for text in PDF not working (Link Not Clickable)

**To Reproduce**
1. Go to Export As -> Advanced
2. Select PDF From dropdown
3. Specify Width and Height
4. Export

**Expected behavior**
PDF should retain added link

**Screenshots**
![image](https://user-images.githubusercontent.com/45749186/129070713-e7579bad-7cee-47f9-b5f7-424cebb1a917.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**
 - Browser [chrome]

**Additional context**
Export As -> PDF -> Will work fine with clickable link
Problem in Export - Advanced - When width and height specified.

**Comment by mararad** [comment]
Hi,

Reproduced with 14.9.6
Chrome Version 92.0.4515.131 (Official Build) (64-bit) and Chrome Incognito and FF
Win 10 Pro

Links are not exported via File > Advanced > PDF with or without width/height specified

My suggestion would be to double click the text, click chain icon on the right, set width/height and export. 
Does it help?

Regards,

![chain icon](https://user-images.githubusercontent.com/44292306/129200264-944e6ef9-0531-4f7e-a14f-31538e9a500c.JPG)

**Comment by Amulya-sb** [comment]
Thanks for the suggestion ,
Yes that option will work fine .
But what if need to use it as Edit Link ? i.e is my query - Edit Link is not working .

**Comment by davidjgraph** [comment]
We cannot fix this. We use third party software for the PDF export.
