### ISSUE TITLE
Remove "Include a copy of my diagram" by default

### ISSUE THREAD

**Issue by itdependsnetworks** [jgraph/drawio#2177]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When exporting diagrams, the defaulting of the option `Include a copy of my diagram` results in unattended consequences to the average user. Embedding the entire diagram does not follow the Principle of Least Astonishment IMHO, as I cannot think of any other application that the exporting of images/docs that do this by default. I find the following very likely issues

* As users publish these diagrams they can easily be giving away other information, potentially confidential they did not intended
* This information is potentially searchable to see who potentially accidentally published information on the internet
* The size of the image is much larger than intended

**Describe the solution you'd like**
Remove "Include a copy of my diagram" by default

**Describe alternatives you've considered**
To at least allow "stickiness" the config option, since currently I need to remember every time to uncheck this.

**Additional context**
This IMHO should not be enable by default. 
![image](https://user-images.githubusercontent.com/9260483/129293608-956fc889-186d-497f-b93f-1bf6421ebf20.png)

**Comment by davidjgraph** [comment]
I don't agree with changing the default. We (@alderg and I) decided to set this default based on a number of support tickets where users didn't understand the difference between saving and exporting. If he doesn't agree either, it won't change again, just to set expectation on this one.

**Comment by itdependsnetworks** [comment]
Understood, feel free to close at your discretion. I can only give you my perspective as a maintainer of multiple open source projects, that I would take acting in good security faith to my users as something to be strongly considered, and I hope you agree and act in kind.

As a side note, thanks for your hard work in building a quality product free of charge. :)

**Comment by davidjgraph** [comment]
The issue of unintended data egress is certainly valid, that's a large of part of https://github.com/jgraph/drawio/discussions/2147. What I suggest is to change the issue to be a change to the JSON config to turn this off by default or/and disable the feature entirely.

**Comment by alderg** [comment]
Option "includeDiagram" to override the default (true/false) will be added in the next release.
