### ISSUE TITLE
PlantUML doesn't render the Graphviz example properly

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#2178]
* Reported in DID-3138. Only upper left corner of the diagram is shown.
* When tested here: http://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000 
whole diagram is displayed
* Reproduced in diagrams.net 14.9.6, Chrome Version 92.0.4515.131 (Official Build) (64-bit), Chrome Incognito and FF 90.0.2 (64-bit)
* Arrange > Insert > Advanced > PlantUML 
* No error in browser console

"I found it in the diagrams.net - but it doesn't render properly. Here is the Graphviz example I was playing around with to learn about clusters
However using PlantUML in diagrams.net only shows a small corner of the overall diagram, and it doesn't resize correctly."

digraph finite_state_machine {
rankdir=TB
size="8,5"

node [shape = doublecircle]; LR_0 LR_3 LR_4 LR_8;
node [shape = circle];
subgraph cluster0 {
LR_0 [label=Start URL="https://myspace.com",tooltip="this is a start"]
color=blue
}
subgraph cluster_product {
LR_1 -> LR_3 [ label = "S($end)" ];
color=green
}
subgraph cluster_rave {
color=red
LR_0 -> LR_2 [ label = "SS(B)" ];
LR_0 -> LR_1 [ label = "SS(S)" ];
LR_2 -> LR_6 [ label = "SS(b)" ];
LR_2 -> LR_5 [ label = "SS(a)" ];
LR_6 -> LR_6 [ label = "S(b)" ];
subgraph cluster_devops {
color=blue
LR_5 -> LR_7 [ label = "S(b)" ];
LR_5 -> LR_5 [ label = "S(a)" ];
}
LR_6 -> LR_5 [ label = "S(a)" ];
LR_7 -> LR_8 [ label = "S(b)" ];
LR_7 -> LR_5 [ label = "S(a)" ];
LR_8 -> LR_6 [ label = "S(b)" ];
LR_8 -> LR_5 [ label = "S(a)" ];
LR_8 [label="End",URL="https://facebook.com",tooltip="this is the end "]
}
subgraph cluster5 {
LR_2 -> LR_4 [ label = "S(A)" ];
}
}

![plantuml drawio](https://user-images.githubusercontent.com/44292306/129329950-1bc4e5d7-4080-40c6-838a-0a2b28d3d77b.JPG)

![wholeplantuml](https://user-images.githubusercontent.com/44292306/129329972-2863a942-b020-4e2e-8b00-033b2c8e564d.png)

**Comment by ashrafteleb** [comment]
Hi,
Removing `size="8,5"` fixes the issue. I believe this is PlantUML syntax issue
