### ISSUE TITLE
draw.io for Trello failing to access issue attachments on private boards

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#2179]
On private boards, when attempting to save new or edit existing diagrams attached to tickets the request is failing with a 412 at our proxy.

Behind the scene Trello has changed the URL from a AWS S3 address with a short lived authenicated embedded in the URL, to direct to trello.com using the browser authenication.

We do not pass authenication to our proxy, and so this is now failing in all cases. Apologies for this, but we were not aware this change was going to be made.

We will investigate altering the authenication flow to fix this issue. It's possible diagrams on public boards may be affected too, we haven't tested that yet.

In the meantime, you can download the diagram attachments and edit/resave them using [app.diagrams.net](https://app.diagrams.net/?splash=0), or using the [desktop app](https://get.diagrams.net).

**Comment by mararad** [comment]
Tested this in Chrome Version 92.0.4515.131 (Official Build) (64-bit) and I could add and edit drawio diagrams without any problems.
Win 10 Pro

https://user-images.githubusercontent.com/44292306/129710604-fa604310-6090-43f1-9e3b-8217bca96a9b.mp4

**Comment by ashrafteleb** [comment]
Good, the deployed fix works well then.
