### ISSUE TITLE
[Improvement] Picking Google Drive Folder

### ISSUE THREAD

**Issue by virth** [jgraph/drawio#218]
When creating a new Diagram while using Google Drive you have to pick a Google Drive Folder. While doing this you have to stay in the level **above** the folder you want to select. Which is kind of counter intuitive to me.

### Example

Let's say you have the following folder sctructure:

- root
  - my stuff
    - folder 1
    - folder 2
  - other stuff
    - folder 3
    - folder 4

To select `folder 1` I have to navigate to `root` > `my stuff` and then select `folder 1`. If I navigate **into** `folder 1` (which I somehow automatically do) I can not hit the select button anymore and have to navigate back.

### Proposal

In the example above it would be nice if I could hit the select button while I'm inside `folder 1`. In that case it would select the folder which I'm in.

**Comment by alderg** [comment]
This picker is using an API from Google, please use https://developers.google.com/picker/support
