### ISSUE TITLE
app.diagrams.net can't authenticate by Google Drive account with Firefox

### ISSUE THREAD

**Issue by rosti-il** [jgraph/drawio#2180]
If entered into the [app.diagrams.net](https://app.diagrams.net/) site with the Firefox web browser and selected "Google Drive" it can't authenticate me by my Google Drive account. When I press on the big blue "Authorize" button just nothing happens. If I do the same with other web browser, for example Microsoft Edge, it works properly.

My Firefox version is 91.0 on Windows 10.

**Comment by davidjgraph** [comment]
Does it work in a private window? Any browser extensions?

**Comment by rosti-il** [comment]
@davidjgraph No Firefox extension and in a private window it doesn't work too.

It turned out that the login window of Google is blocked because app.diagrams.net tries to open it as a pop-up window and Firefox [blocks all pop-ups by default](https://support.mozilla.org/en-US/kb/pop-blocker-settings-exceptions-troubleshooting#w_what-are-pop-ups).

On the other hand the same authentication window of Google opens and works properly with Firefox on sites like Reddit. So it looks like it's implemented wrongly in app.diagrams.net. Try to compare this implementation with https://www.reddit.com/login/?dest=https%3A%2F%2Fwww.reddit.com%2F

**Comment by rosti-il** [comment]
Also interesting that if I chose OneDrive the login window of Microsoft opens properly and probably works as well.
