### ISSUE TITLE
Pinch-zoom too sensitive

### ISSUE THREAD

**Issue by borekb** [jgraph/drawio#2182]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

Pinch-zooming on a Mac is too sensitive – moving my fingers like 1-2 cm changes zoom from 50 to 700% or similar. I have trouble achieving the right zoom / scale with the touchpad / trackpad.

**Describe the solution you'd like**

Decrease the sensitivity significantly.

**Comment by borekb** [comment]
This is probably not unique to sketch mode – I've updated the title and the description.

**Comment by denizetkar** [comment]
This issue is also relevant for Windows 10, for what its worth.

**Comment by davidjgraph** [comment]
We're unable to implement this for technical reasons, the current implement is the best effort.
