### ISSUE TITLE
Fix wrong Russian localization

### ISSUE THREAD

**Issue by ashed** [jgraph/drawio#2183]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

I translated all strings in autogenerated source file dia_ru.txt. Would you add me write permission to localization table at Google Drive ([https://docs.google.com/spreadsheets/d/1FoYdyEraEQuWofzbYCDPKN7EdKgS_2ZrsDrOA8scgwQ/edit?pli=1#gid=0](https://docs.google.com/spreadsheets/d/1FoYdyEraEQuWofzbYCDPKN7EdKgS_2ZrsDrOA8scgwQ/edit?pli=1#gid=0))?
And why you don't use TM infrastructure like Weblate or Transifex?

**To Reproduce**
1. Start drawio with Russian locale
2. Click on 'Arrange' -> show 'Bring Forward',  'Send Backward'
3. Translation string must be "Переместить вперёд", "Переместить назад"
4. And a lot of other mistranslation

**Expected behavior**
Full and correct Russian localization

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [14.9.6.]

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux]
 - Browser [Firefox, Chromium,]
 - Version [Firefox 78.13.0esr] but it does not matter

**Additional context**
Some localized strings are unable to fit to buttons and tabs, because Russian words some longer than English words in place.
Would you enlarge width of tabs and buttons in Format panel above 30%?

[dia_ru.zip](https://github.com/jgraph/drawio/files/6997674/dia_ru.zip)

**Comment by davidjgraph** [comment]
I've added you permissions to the sheet.

We don't use third-party services so we remain in control of our data, rather than being subject to their commercial interests. Our current system isn't broken, so nothing to fix :).

**Comment by ashed** [comment]
Ok. But Google already own your data in Google Sheets. This system not broken, but integrated with Google accounts and used in data gathering too. 
And by the way Google Sheets doesn't have Translation memory (it is very useful for terms unifying in translation process). :-)

**Comment by davidjgraph** [comment]
Google do not "own" our data. The data is exported to tsv on every change. They are simply hosting it for convenience and we always have an up to date copy in a standard format.

What exactly is translation memory? I'm not familiar with this.

**Comment by ashed** [comment]
Translation memory is a database that stores sentences, paragraphs or segments of text that have been translated before.
The translation memory stores the source text and its corresponding translation in language pairs called “translation units”. Individual words are handled by terminology bases and are not within the domain of TM. 
Translation memories support the localization process, dramatically improving the quality, speed, consistency and efficiency of every translation job.
