### ISSUE TITLE
Set properties (tags) for multiple shapes simultaneously

### ISSUE THREAD

**Issue by ashed** [jgraph/drawio#2184]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When working with shape properties (tags), I always have to edit the metadata in one shape in time (Ctrl+M). 
And if I try to select multiple shapes and then hit Ctrl+M, the window opens but the changes I make only affect the first shape that I selected.

I found similar issues
https://github.com/jgraph/drawio/issues/1184 - Set properties and placeholders for multiple shapes
https://github.com/jgraph/drawio/issues/1759 - Copy-paste objects in multiple layers

**Describe the solution you'd like**
Being able to select multiple shapes and adding metadata that will be added to all of them at the same time.
Or add command with button seems like "copy tags/paste tags"

**Describe alternatives you've considered**
Being able to copy and paste metadata information like you can do it with styles.

**Additional context**

**Comment by mararad** [comment]
Please track and comment this issue: 
https://github.com/jgraph/drawio/issues/1240

Thanks,
