### ISSUE TITLE
Issue with vertical pools

### ISSUE THREAD

**Issue by joejcherian** [jgraph/drawio#2185]
I had multiple vertical pools in my file. All of which were then condensed and linked with each other to make a flow chart. But since the last update I am not able to expand these vertical pools to see the swimlane chart inside. It has happened for all my draw.io files. 
they are missing the '+' sign next to the text which was used to expand the pool.
In addition to this I had multiple vertical tree layouts which are also missing the '+' sign and cannot be opened as well now.
Could someone help please?

**Comment by mararad** [comment]
Hi,

Please describe your environment (browser version, draw.io version, operating system), attach diagram file in question so we can test it and attach a print screen showing the missing + 

Thanks,

**Comment by joejcherian** [comment]
I have downloaded it so I am using the desktop mode. Version says "diagrams.net 14.9.6" inside the help menu. and I am using windows 10 OS. It has been working fine for the past 2 months and I think the '+' went missing after the last update which was a couple of days ago. 
This is the first time I am using github. Could you tell me how I can attach the diagram file. It says the format is not supported when I drag the file in from my desktop.

**Comment by davidjgraph** [comment]
Could you zip and attach an example diagram that demonstrates the problem please?

**Comment by joejcherian** [comment]
Hi, Ok Didnt think of that. Thank you.
It is attached here. Please take a look.
[Master Sheet.zip](https://github.com/jgraph/drawio/files/7008749/Master.Sheet.zip)

All the items in there ie., "influence pillar", "improve pillar", "finance" etc were tree layouts with further contents that i am not able to access now.

**Comment by ashed** [comment]
If you want to access to collapsed data just copy style from i.e. "Managing Existing Contracts" and paste this style to collapsed container and set flag "resizeable" in style.

**Comment by mararad** [comment]
Or if you find it easier, select a shape and tick Resizable in Property/Value on the right

![resizable](https://user-images.githubusercontent.com/44292306/130071013-c4631d24-bd6d-4614-a91e-9c3fcdeb65dc.JPG)
