### ISSUE TITLE
Visual marks for objects placed on different layers

### ISSUE THREAD

**Issue by ashed** [jgraph/drawio#2189]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when see all objects on all layers without any differentiation.

**Describe the solution you'd like**
Visual marks for objects placed on different layers

**Describe alternatives you've considered**
Visual marks for objects placed on different layers like in some vector editors.

**Comment by mararad** [comment]
Hi,

The only thing at the moment is the dot showing in the layer panel when a shape is selected (shown in the image below)
This way it is easier to see what layer shape(s) belong to so it could be helpful.

P.S Could you add an example of the visual marks you mentioned?

![layer dot](https://user-images.githubusercontent.com/44292306/130074021-c5f56048-44a8-4f28-b0ae-d7a564fb2e14.JPG)

**Comment by ashed** [comment]
color rectangles mark layer

[2021-08-20 14_47_27-drawio-visual-layer-marks.zip](https://github.com/jgraph/drawio/files/7020766/2021-08-20.14_47_27-drawio-visual-layer-marks.zip)

**Comment by ashed** [comment]
Is my issue been processed?
Visual marks for objects placed on different layers.
Layer has color mark and object, placed on this layer must had this color mark too.

**Comment by ashed** [comment]
Visual marks for objects placed on different layers.
Layer must had color mark and object, placed on this layer must had this color mark too.
This is visually assisted for compounding large schemes which contains a plurality of objects.
