### ISSUE TITLE
SVG export: characters are escaped twice

### ISSUE THREAD

**Issue by tao-cumplido** [jgraph/drawio#219]
[This diagram](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=test.xml#RjZNNb4MwDIZ%2FDXdKqm3XwdruslMn7ZyCC9ESjEJa6H79HHDKRzVpuRA%2FtmPzxolEZvqDlU31gQXoKImLPhJvUZJstiKmjye3kTyLlxGUVhUcNIGj%2BgGGnFdeVAHtItAhaqeaJcyxriF3CyatxW4Zdka9rNrIEh7AMZf6kX6pwlWhu3ji76DKyq0cJ5l%2FlxYvNZeLEnEe1ug2MhzF8W0lC%2BxmSOwikVlEN%2B5Mn4H20gbVxrz9H9572xZq95%2BEZEy4Sn2Z%2FpxSnqRpIpFqOiQlwGGtuwWBHPTeVzmjCWxo2zqL35ChRkukxpoi07PSeoWkVmVNZk4tAvH0CtYpkv6VHUYVhS%2BTdpVycGxk7mt2NGjEBm3Bdx%2F7mkE%2Bb%2BRoVM57LU%2Bg0%2FtlrLvC2u2lUdpP56es0EimPImbhO2QSPcYD2vQY60xy%2B5%2FBPoZYs0PgAacvVEIe8Pz4NexZbObRi2gajZlYWgkD3d5P3e6YdrwJQdzGqbBN3uwYvcL) contains this text:
```
1 < 2
```
Exporting to SVG results in this file:

```svg
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" style="background-color: rgb(255, 255, 255);" xmlns:xlink="http://www.w3.org/1999/xlink" width="41px" height="21px" version="1.1">
<defs/>
<g transform="translate(0.5,0.5)">
    <g transform="translate(4.5,1.5)">
        <switch>
            <foreignObject style="overflow:visible;" pointer-events="all" width="31" height="12" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility">
                <div xmlns="http://www.w3.org/1999/xhtml" style="display: inline-block; font-size: 12px; font-family: Tahoma; color: rgb(0, 0, 0); line-height: 1.2; vertical-align: top; width: 32px; white-space: nowrap; overflow-wrap: normal; text-align: center;">
                    <div xmlns="http://www.w3.org/1999/xhtml" style="display:inline-block;text-align:inherit;text-decoration:inherit;">
                        1 &lt; 2
                    </div>
                </div>
            </foreignObject>
            <text x="16" y="12" fill="#000000" text-anchor="middle" font-size="12px" font-family="Tahoma">
                1 &amp;lt; 2
            </text>
        </switch>
    </g>
</g>
</svg>
```
As you can see, inside the `foreignObject` node the text is escaped correctly to `1 &lt; 2` but inside the `text` node the escaped text is escaped again resulting in `1 &amp;lt; 2`.

I want to use Inkscape's LaTeX export to render images in my document with the documents font so I need to be able to write things like `$x < y$` inside my drawing and get it exported correctly.

I also get warnings from Inkscape for not recognizing the `foreignObject` nodes, maybe it would be possible to have an option on export to omit these.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
