### ISSUE TITLE
Swallowed layer window like Format Panel (Ctrl+Shift+P)

### ISSUE THREAD

**Issue by ashed** [jgraph/drawio#2190]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Free space on diagram canvas is valueable thing. Floating layers window may be swallowed by right panel

**Describe the solution you'd like**
Swallowed layer window like Format Panel (Ctrl+Shift+P)

**Comment by mararad** [comment]
Hi,

If you use Ctrl+Shift+L (on Win) does it toggle layers as listed here: https://app.diagrams.net/shortcuts.svg 

You would like to toggle them, right?

**Comment by ashed** [comment]
This keyboard shortcut also toggle layers window in Linux too. But Layers window not swallowed into right panel. This inconsistency in UI as for me.

**Comment by ashed** [comment]
Shortcut Ctrl+Shift+L toggle layers, but floating header of Layers dialog looks inconsistent.
Can you rewrite this dialog to make it´s behavior seems like Format Panel (Ctrl+Shift+P) docked or swallowed?

**Comment by ashed** [comment]
Shortcut Ctrl+Shift+L toggle layers, but floating header of Layers dialog looks inconsistent.
Can you rewrite this dialog to make it´s behavior seems like Format Panel (Ctrl+Shift+P) docked or swallowed?

**Comment by davidjgraph** [comment]
Declined.
