### ISSUE TITLE
Option to change [Enter] behavior in shapes

### ISSUE THREAD

**Issue by TilTisback** [jgraph/drawio#2196]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

-**Is your feature request related to a problem? Please describe.**
When you enter text in a shape and press [Enter], the coursor advances to the next line in that shape. To exit the shape you have to press [Ctrl]+[Enter]. Its quite annoying since most other programs i know do it the other way around.

-**Describe the solution you'd like**
Add a option to change the shape/text [Enter]-behavior.
Normal-->[Enter] advances to next line. / [Ctrl]+[Enter] exits the shape.
Flipped-->[Ctrl]+[Enter] advances to next line. / [Enter] exits the shape.

**Comment by mararad** [comment]
Hi,

There are other possibilities to exit a shape as described here: https://app.diagrams.net/shortcuts.svg 
Maybe Esc will suit your needs better.

Regards,

**Comment by Sporarum** [comment]
I think this would be very useful !

In my experience the following is almost universal:
* `[Shift] + [Enter]`: Line break
* `[Ctrl] + [Enter]`: Submit
* `[Enter]`: Depends on app and or settings

And in this case, a lot of time is spent writing short labels, so it makes sense to have enter act as submit

**Comment by davidjgraph** [comment]
We can't change the default behaviour at this point. We've 10s of millions of users, it's just not possible.

**Comment by Sporarum** [comment]
I should have been clearer,
I do not advocate for changing the default, only for there being a way to change it

**Comment by davidjgraph** [comment]
Extras->Exit on Enter, though we might move it

**Comment by davidjgraph** [comment]
Moved into configuration with other options in the extras menu.
