### ISSUE TITLE
Add connection points within imported image at exact pixel position

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#2199]
Asked here: https://groups.google.com/g/drawio/c/H8AZCgLQ2I4

At the moment, it is possible to add the third coordinate in order to be able to place connector points within a shape as described here: https://www.diagrams.net/doc/faq/shape-connection-points-customise 
but the user would like to have the possibility to add them at the exact pixel positions. 

"The network switch is just an example where I want to add custom connector points not along the border (which points=[]; will do) but rather based on pixel (or some other measurement) of the image. Like lets take the image thats 5300x550 (width x height) pixels. For that I would like to add custom connector points at pixel position (of the original image):

int1: 200x500
int2: 300x500
...
int24: 2500x500

So that when I place my line between two of these interfaces I can make it snap lets say between int1 of image1 and int16 of image2.

Currently the workaround is to place the line (with its bends) and then manually for each endpoint select the endpoint, press alt-key, move the endpoint to about where int1 of image1 is located. Repeat the process for the other endpoint of the same line that is select it, press alt-key, move the endpoint to about where int16 is located on image2. Now when you just do this once in a lifetime the above is good enough as workaround. 
But if you will do a larger network drawing the above workaround is time consuming.

If custom connector points could be setup through xml style or such then placing the lines between the interfaces of each network switch in the drawings would go so much faster. And the placement would also be exact (using the alt-key method ends up with a slight offset each time you place the line which also depends on your zoom level and how good you are to aim using the mouse).

So I guess what Im looking for is since points=[]; will only add connector points along the border of the imported image I would like to have something like (for the above case):

pixelpoints=[[200x500],[300x500],[400x500],[500x500],[600x500],[700x500],[800x500],[900x500],[1000x500],[1100x500],[1200x500],[1300x500],[1400x500],[1500x500],[1600x500],[1700x500],[1800x500],[1900x500],[2000x500],[2100x500],[2200x500],[2300x500],[2400x500]];

to be added as xml style in the properties of the imported image."

**Comment by alderg** [comment]
Absolute offsets can be defined as a fourth and fifth coordinate, eg [x,y,0/1,dx,dy]. The documentation has been updated.
