### ISSUE TITLE
Change of background color cannot be undone as an atomic event

### ISSUE THREAD

**Issue by pesho-ivanov** [jgraph/drawio#2200]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When the background color of text is changed, a checkpoint is not added to the history of events so ctrl+z (undo) skips it. 

**To Reproduce**
Create a text box with some text.
Change the background of the first letter.
Change the background of the second letter.
Press ctrl+z to undo.
See that all the text backgrounds are undone, not only the last.

**Expected behavior**
I expect to be able to undo every change of background.

- draw.io version [e.g. 12.6.5]

**Desktop (please complete the following information):**
 - OS: Manjaro

**Comment by mararad** [comment]
Hi, 
I tested this and it is working at my place with Ctrl+z and with undo arrow. I am using:
* diagrams.net 14.9.8
* Chrome Version 92.0.4515.159 (Official Build) (64-bit)
* Win 10 Pro

What version do you see under Help in the editor?
If you change browser and test in Private mode, do you still see the same issue?

Regards,

https://user-images.githubusercontent.com/44292306/130768961-baefab85-7855-4c37-8481-5229d4a49ccd.mp4

**Comment by pesho-ivanov** [comment]
Thank you for trying to reproduce, @mararad. in fact, I was using an old desktop version (12.6.5) which acts much more irregularly but the browser version seems to be just fine.

And if I understand correctly, leaving the textbox and getting back in intentionally aggregates many events as one (screen capture attached).

https://user-images.githubusercontent.com/110152/130820970-bfeabe12-a1f1-4aa3-b9b2-78f4c5776352.mp4
