### ISSUE TITLE
Add support for specifying `editableCssRules` inside a library

### ISSUE THREAD

**Issue by erdomke** [jgraph/drawio#2201]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I am creating libraries for [Clarity icons](https://clarity.design/foundation/icons/shapes/) to use in mockups. I would like to be able to change the colors inside the SVG icon within the interface. (Changing the main icon color to white, updating the badge color, etc.) The current process for this looks something like:

- Add the library icon to the current drawing
- Search for the [help document](https://www.diagrams.net/doc/faq/svg-edit-colours) on how to change SVG colors
- Edit the style with the special string `editableCssRules=.*;`
- Change the relevant colors

The flow I would like is
- Add the library icon to the current drawing
- Change the relevant colors. This would be available immediately because the notion of `editableCssRules` would be defined in the library

**Describe the solution you'd like**
It appears that you can [define the `aspect` style](https://github.com/jgraph/drawio/blob/88a470d27d40273c2d94cead9311025c98d1c079/src/main/webapp/js/grapheditor/Sidebar.js#L583) in the library and this will be honored. However, no other styles are copied from the library JSON into the style. I propose that you allow library authors to include the JSON property `editableCssRules`

```json
{
    "data": "data:image/svg+xml;base64,PHN2Z...",
    "w": 36,
    "h": 36,
    "editableCssRules": ".*",
    "title": "Analytics",
    "aspect": "fixed"
},
```

Then the `editableCssRules` will be built into the style string just like the aspect is.

**Comment by alderg** [comment]
Styles can be configured by using the xml field in the library entry. To create that, select a shape and click the + icon in the scratchpad, then export it via the edit dialog by clicking on the pen icon. Here is an example:

`<mxlibrary>[{"xml":"nVbbcqM4EP0av+zDloLwJH40F2NcCJwYj2PeuAVEwLiMMIivn5bAiTM12Zpap+wWrT46R92tiBnWq966hOec1ElazrA5w/qlrtk4qno9LcuZgmgyw8ZMURB8Z8rqm9kHOYvO4SU9sb8BKCPgGpZtOnqWZVl34AplXFyX9aWBAavhJ0ql6/RGs/aSJiO2YbycsE0ensWQVmEGVksTysKoTPWmeWnLtIGpf/8B/zW9MBqHpRNGabmtG8pofYLJqGasriCgFBNaGL9nl7o9JbpQISnwm/zcrbEsaSawrD6DN2zOaSx2/kZ7EIg1KWV586KbB8ZJyMIZXo6Pyqq5ZjNF6yvYtb5du0rANTU69G08IBquX1Bs1FcHJzjhc0z4/BpX8ZUUy47oiyGpYmqvcxZZ88E75U14mF+2u02drF86jz5dAYWdUzw41YIH/Kn3/Pe5g8c4m2pK8LoZwsOi3e7s3ilMWCs4B6+JHuFsYRfLjOhL7vpgi31nF2pl4zz3hn5I1mUT7DSUvmol8KHgNUeO4g4xt2EvG+qqR7/ZOCcXkTWrwkPfeNTNSWXyo28/vu2ORWqZj/puPiTG6jGoyiYy6sKz9mrg56WH0cjUvbcxfuapEpwjq/thK0El/woGCjbXUNnf+xYT75ODXZQe+nJLR57tWssTK8uOSp/HmCxsoUu3s8BA1PftweXqg2PYHOz8OCwbd6cOjv/cEt7NneLIvJ2Yf2/dinSOsWyI3o3WzDihan/k6MEpCPiRjHd1gYd4Kp5/Fh/x0moHUtgt2S0z4GKSyxBcEttILv8PXBZwGfvWO5CJS2prJJfQRrvvuLBTlD9s+vRZmafYWqFQ14rIWg2izyDLPfTDO9TSJQUBxL6ZkGJFwcg+mYTSvVCqiGzdM+6MDOYC4sKOPL2DftvAOnHr7RCCnT5ERsadImbEX4JNGs8QmehUWPvhZzFWIKX29T8rR2+VM+cQ3zuGOXigLdQRJ1zFEVgX+KAy+DjsW5cj6G1b6FUd/9gSmSmhYXNwfbN1D5Bp8Hu6qOIz+G1RjR7w3PFN0OmOWfWXQuuHBT5Ediq2IY8jXsyJeCI6CN3Gcr37ahbmZFcKGWBO8IvK6h2CvYA/E1oxjPm4l07uZWfsuajH/+MyM3t9HGS3ig6nkAvgdKFG4BsEl8iRxCs3vMjtzWq1a0CuFKIIfeSG8+/WkBo2tw5kE17ahKIbN5PcEofucPaUd3kqxEmatE/WyphrdRz6BLDPEP9SEzglRJG+OZwg6ZOn9kBGDsEt1+zu6iq18ru+HWsq7Otf5udD45f8Co2yH47DVB+JIUzWZxp/rc/9HleK4xOIWUH+kMgxu6vriKNjvqDfDNg7HvUQdaz7n57N6dn97fTD/0clGFRxr2FtuofhUkv7b+9y6Zouciutq5RdOIR0NGH5dJ/Px/se5SnNcvabM2xGR/aB/Xw1gMH0dnB7/HwLkXNfXlJ+AQ==","w":250,"h":250,"aspect":"fixed"}]</mxlibrary>`
