### ISSUE TITLE
Support zoom lock

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#2206]
"I’m using the “drawio sketch” macro. 
Almost every time I touch the mouse I change the zoom level. I'd like to be able to either lock the zoom level or make it so I have to hold down the option key or something to make it zoom.

I’m using a Magic Mouse with a Mac so it doesn’t have a separate mouse wheel. It scrolls like a touch pad. 
I have looked under preferences and there doesn’t seem to be anything I can change that will affect this. 
I don’t press any modifier keys" such as Ctrl or Shift.

Asked in DID-3191
https://user-images.githubusercontent.com/44292306/130919588-c2c6c13f-d89e-4b1f-b9a0-d63f5bf9d39b.mov

**Comment by alderg** [comment]
Thanks for the report, the next release will support the zoomWheel option. See https://www.diagrams.net/doc/faq/configure-diagram-editor
