### ISSUE TITLE
Add layer capabilities to container/list items

### ISSUE THREAD

**Issue by VendettaMike** [jgraph/drawio#2208]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Add ability for container/list items to be on their own layer. Currently, any container/list item is added to the layer of the encompassing container/list. Setting a specific container/list item to a layer removes it from the encompassing container/list. 

This functionality would allow for containers and lists to be filtered to display specific use cases, ideas, etc. 

No workaround seems to exist. "Hide Label" is the only option I can find that removes the text but this is not ideal.

**Comment by alderg** [comment]
Thanks for the feedback. This will be fixed in the next release.
