### ISSUE TITLE
Autosave 

### ISSUE THREAD

**Issue by cub33** [jgraph/drawio#221]
Connection dropped, webapp randomly stopped working and hours of work lost.
I guess there is a need for an autosave functionality

**Comment by davidjgraph** [comment]
Autosave is implemented everywhere that it's technical possible. If you select device it's not possible to autosave to your filesystem without a user prompt in any browser. The status area will display "unsaved changes" in red when that is the case. If you want to save locally with autosave, the desktop version is probably the better option https://download.draw.io
