### ISSUE TITLE
How to equip default package for MathJax

### ISSUE THREAD

**Issue by pilgrimlyieu** [jgraph/drawio#2211]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I wonder that if I can add default equipped package for MathJax. It's troublesome to use `\require{<packagename>}` again and again.

**Describe the solution you'd like**
Emm, I would like to get where can I edit the setting like this in the **desktop** draw.io.

**Describe alternatives you've considered**
Use `\require` again and again.

**Additional context**
I've tried to edit some files in /math but I failed. And I've gone to [MathJax](http://docs.mathjax.org/en/latest/index.html) for help, but I couldn't find the same place as it provided as [this](http://docs.mathjax.org/en/latest/web/components/input.html?#tex-extension-packages).
Additionally, [mhchem extension](http://docs.mathjax.org/en/latest/input/tex/extensions/mhchem.html) provides `\pu` and `\ce` commands but only `\ce` works.
![2021-08-27_14-03-19](https://user-images.githubusercontent.com/80107081/131080794-0e9f2da2-4e14-47d7-b3c4-512637ef49e6.png)

By the way, thanks for this charming work.

**Comment by davidjgraph** [comment]
Outside the scope of the project. I would host your own version and adapt it for your needs.
