### ISSUE TITLE
Self hosted GitLab Integration with self hosted draw.io "draw.war" file

### ISSUE THREAD

**Issue by jasonmacer** [jgraph/drawio#2215]
I might be completely on the wrong path as I did not use the docker image but instead am running the image using the instructions located [here](https://i12bretro.github.io/tutorials/0197.html).  The system is up and running and I have created my all back URLs in my gitlab instance but am running into an issue of where to enter the configuration variables on this instance. 

If i go to Extras > Configuration and enter the following in the configuration box 

window.DRAWIO_GITLAB_ID = "myGitLabAppIDHere", 
window.DRAWIO_GITLAB_URL = "http://gitlab.mydomain.com"

i get the following error: Error
Unexpected token w in JSON at position 0

I have been looking for better documentation but am striking out. Does anyone have an suggestions by any chance?

**Comment by davidjgraph** [comment]
How are you running the server part of this project, do you have the gitlab servlet running and responding correctly?
