### ISSUE TITLE
Feature Request: Color Dropper

### ISSUE THREAD

**Issue by DrLonnieJonesPFMP** [jgraph/drawio#2216]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

It would be nice to have a color dropper (like Adobe Fireworks or Photoshop) to match the color of other objects. It could save a bit of time to use the dropper than to go to the other object, pull the color, and then apply it to another object.

Here is a link to another open source project that has already developed a color dropper in JavaScript.
https://github.com/taufik-nurrohman/color-picker

**Comment by alderg** [comment]
See https://twitter.com/drawio/status/1430123597096538120 or try Shift+Click:

![color-picker](https://user-images.githubusercontent.com/921200/131253720-e50bf14b-814c-405a-882d-cd0a1f2df9de.gif)
