### ISSUE TITLE
Independent connectors for grouped shapes

### ISSUE THREAD

**Issue by ShamanthMurali** [jgraph/drawio#2217]
Watch video to understand - https://youtu.be/KkHsvHZ7vwY

It would be nice to connectors for groups

**Comment by mararad** [comment]
Hi,

What browser version and drawio version are you using? (can be seen under Help)
Basically, you would like to have blue arrows shown when a group is hovered?

And please attach the diagram file so it can be tested.

Regards,

**Comment by ShamanthMurali** [comment]
Hello,
Draw.io (Web version)
![image](https://user-images.githubusercontent.com/71114618/131341824-947ca7e8-9887-4715-ba74-7035c4d257ef.png)

Browser
![image](https://user-images.githubusercontent.com/71114618/131341923-175464e3-7ee1-44e2-a0c5-30e06ce4929f.png)

Diagram
https://drive.google.com/file/d/1gWKCaVAx8jMdNw6b8wUXWxUmQJzxrMom/view?usp=sharing

Yes I would like to have connectors for groups. And it should also work with Expand/Collapse of "Organization shape" 

Thank you.
