### ISSUE TITLE
Error: "User activation is required to request permissions".

### ISSUE THREAD

**Issue by Dileksus** [jgraph/drawio#2218]
I'm using web draw.io, and I can't save my edited diagram. The error says : "User activation is required to request permissions.". 
If I use "save as" I won't have problem until I close the webpage. I also don't have any problem with desktop version. This problem happens with web version. 

 - OS: Windows 10
 - Browser: chrome
 - Version 92.0.4515.159

**Comment by davidjgraph** [comment]
Where are you trying to save the diagram to, what storage option?

**Comment by Dileksus** [comment]
> Where are you trying to save the diagram to, what storage option?

Device.

**Comment by davidjgraph** [comment]
That means either Chrome popped up a permissions dialog that you declined, or didn't pop it up at all. If the later, that would be a bug in Chrome, but then we'd see a _lot_ of bug reports.

**Comment by Dileksus** [comment]
> That means either Chrome popped up a permissions dialog that you declined, or didn't pop it up at all. If the later, that would be a bug in Chrome, but then we'd see a _lot_ of bug reports.

Yes, I think this problem in my side. Thank you!
