### ISSUE TITLE
Container and non-container interaction with IBM Stencils

### ISSUE THREAD

**Issue by jaywarfield** [jgraph/drawio#2219]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
For the container and non-container interaction with IBM Stencils, the attached file shows some interactions I'm hoping we can look at.  If this is working as designed or a bug but can be remedied with a property or other remedy.

In IBM Stencils, Security Group is set to container=0 (to prevent ambiguity) and all other IBM Boxes/Groups are set to container=1.  There is an error in the IBM Stencils where Security Group is set to container=1, so there is a manual step to set container=0 for Security Group on the canvas when using the IBM Stencils.

draw.io has kindly added some properties in the past to help out the IBM Stencils for Boxes/Groups such as recursiveResize=0 and expand=0.

In the attached file,
[IBMSecurityGroupExample.zip](https://github.com/jgraph/drawio/files/7086782/IBMSecurityGroupExample.zip)

Scenario 1: With the Security Group in the top diagram of the attached file, nothing can be changed inside the Security Group.  The workaround is to drag the Security Group outside of other boxes/groups, edit the VSI text or move the VSI around or whatever needs to change, then drag the Security Group back into place.  

Scenario 2: With the Security Group in the bottom diagram of the attached file, the placement of the Security Group sometimes gets partially placed behind other boxes/groups, and selecting the Security Group and going to Arrange To Front doesn't bring the Security Group to the front, or selecting the surrounding boxes/groups and going to Arrange To Back doesn't bring the Security Group to the front.  The workaround is to drag the Security Group outside of other boxes/groups, then use Arrange Position to move the Security Group into place, or sometimes dragging the Security Group out and back in will eventually work until the next time something inside the Security Group needs to be updated.  

**To Reproduce**
Steps to reproduce the behavior are described in the description.

**Expected behavior**
Scenario 1 - The solution requested for consideration is to be able to update anything inside the Security Group without dragging the Security Group out.  
Scenario 2 - The solution requested for consideration is that the Security Group always ends up on top of other boxes/groups where it is placed without using Arrange.  If Arrange is optionally used the Arrange would work as expected.  

**Screenshots**
Attached file shows the 2 scenarios.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 15.0.3

**Desktop (please complete the following information):**
 - OS: Mac 11.5.2
 - Browser: Chrome
 - Version 92.0.4515.159
 - Browser: Safari
 - Version: 14.1.2

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**

**Comment by jaywarfield** [comment]
Security Group is the one box/group that can cross boundaries of other boxes/groups by definition of Security Group and setting container=0 for Security Group is also by definition of Security Group to prevent ambiguities.  If either of these is causing these 2 scenarios, is there an existing property to get the expected behaviors mentioned or how can users get the expected behaviors or rely on the workarounds mentioned.  My apologies if this is a feature request for your kind consideration.  Just hoping to make things easier for users if possible.  Thanks!

**Comment by egrimate** [comment]
If you alt-click on one of the VSI shapes, it should be selected. Also now, if you move the shape to the top of the z order it will be above the Security Group.

We hope this solution is acceptable.

**Comment by jaywarfield-developer** [comment]
I will try it out, thanks!!
