### ISSUE TITLE
Export to PDF fails with "Uncaught TypeError: Cannot read property 'value' of undefined"

### ISSUE THREAD

**Issue by novakboskov** [jgraph/drawio#2221]
Export to PDF fails with "Uncaught TypeError: Cannot read property 'value' of undefined". Seems like it fails for any diagram, even if I try to export only a simple rectangle.

1. Make a new diagram.
2. Put a simple rectangle on the canvas.
3. Export to PDF.

Here is the screenshot.
![error](https://user-images.githubusercontent.com/6290049/131750072-464b306e-690e-487c-9554-31ad96bd7830.png)

The version is 15.0.5. I work on Chrome 92.0.4515.159.

**Comment by abu-co** [comment]
The error seems to be occurring here: https://github.com/jgraph/drawio/blob/d1ba3ba35a722f78e68839b84607abde4f272408/src/main/webapp/js/diagramly/Menus.js#L522
 I don't think the variable `pagesFromInput` is initialized or even declared in this scope. This is probably why it is evaluating to `undefined` at runtime. 

This piece of code is found in a commit made just hours ago (the "15.0.5 release", https://github.com/jgraph/drawio/commit/d1ba3ba35a722f78e68839b84607abde4f272408)...

**Comment by davidjgraph** [comment]
Fix in 15.0.6 release
