### ISSUE TITLE
Page as background not working when exported to HTML, not able to change after setting it once.

### ISSUE THREAD

**Issue by jimbotrue** [jgraph/drawio#2223]
### Preflight Checklist

* [ X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Page as background not working in several instances:
1. If you set page's background to be another page, and try to change it again, there is no dropdown to select another page. 
2. Backgrounds that are set as page are not being exported in HTML export.
3. When exporting as HTML, size of background is ignored and page is trimmed to current content.

**To Reproduce**
1. Create new blank document
2. Place some objects on page-1
3. create blank page-2
4. set page-2's background to be page-1
5. Try to change page-2's background and notice how page dropdown is no longer there
6. Try to export to HTML and observe backgrounds not being present

**Expected behavior**
When you press change button next to page's background (after it was set once), there should be an option to change it's background to page
When exporting HTML, backgrounds should show

**Screenshots**
https://imgur.com/a/GyxckEa

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]
15.0.6 from diagrams.net in chrome or firefox

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome 93, firefox 91
 - Version 93,  91

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
