### ISSUE TITLE
Add Nassi-Shneiderman Diagram

### ISSUE THREAD

**Issue by nightingale-m** [jgraph/drawio#2224]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

<br>

**Nassi-Shneiderman Diagrams**

Also known as Chapin Charts, Nassi-Shneiderman (N-S) diagrams are a modern alternative to flowcharts for the following reasons:
- N-S diagrams are an alternative to simple flowchart.
- An N-S diagram can be drawn using text and lines (or completely with ASCII characters).
- N-S diagrams show processing by series, by selection, or by iteration.
- N-S diagrams are read from top to bottom.
- N-S diagrams are more structured than flow charting (one start, one end).

**Describe the solution you'd like**
Add Nassi-Shneiderman Diagram

**Additional context**

![Elements of Nassi-Shneiderman Diagrams](https://user-images.githubusercontent.com/46788763/132092367-c8a99a4a-2e3e-4abf-96a6-8e01c3f59914.png)

![Example from smartdraw.com](https://user-images.githubusercontent.com/46788763/132092368-8f1bd993-a209-4f11-a836-10c44462c30f.png)

![Example from edrawsoft](https://user-images.githubusercontent.com/46788763/132092366-885f3a1f-aa40-4fa4-ab0f-e3259f37ab67.png)

**Comment by davidjgraph** [comment]
Closing due to low interest. If future readers do want to vote for the feature, thumbs up the orginal post.

**Comment by ol-z** [comment]
If you need more references: 
https://www.structorizer.com/
https://whiledo.de/index.php?p=struktogrammeditor
(both in german)

**Comment by sanmacorz** [comment]
I have been studying these diagrams lately and I think it would be a neat addition to the project. 👍

**Comment by Joel-dev-IMP** [comment]
> Closing due to low interest. If future readers do want to vote for the feature, thumbs up the orginal post.

How many votes would it take for you to reopen the issue and add this?

**Comment by Joel-dev-IMP** [comment]
> I don't believe that vote count for a second, someone is trying to manipulate the count.

?

**Comment by Joel-dev-IMP** [comment]
Alright, i see this issue has been reopened. Is there a chance to see it implemented in the upcoming months? Will @egrimate work on this?

**Comment by davidjgraph** [comment]
No, there is no chance of this being implemented in the upcoming months.

**Comment by davidjgraph** [comment]
Thanks for the suggestion. Unfortunately, none of the team want to implement this, so it will be closed.
