### ISSUE TITLE
More unit options

### ISSUE THREAD

**Issue by dr-mccoy** [jgraph/drawio#2225]
[*] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.

[*] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

I'd love to see the possibility of more units of measurement, millimeters are too small for some of my projects.

An option such as meters, feet (although sticking to metric is fine), etc would be great.

Thanks!

**Comment by g2384** [comment]
when you export to PNG, you can set 'zoom', if you set a number greater than 100%, say 1000%, it will lossless-ly enlarge the image.
