### ISSUE TITLE
[Feature] Add guide lines like Power point

### ISSUE THREAD

**Issue by Taswen** [jgraph/drawio#2226]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

We have Grid and (smart ?)Guides<sup>[1]</sup>, but there is a lack of Guide lines<sup>[2]</sup> like Power point. It's useful in some scenes.

Are you considering adding this feature in the future?

[1]  Grid and Guides
![image](https://user-images.githubusercontent.com/30777327/132132491-0c5b1662-a233-453b-8b11-de11770451d3.png)

[2] Guide lines in Power point
![image](https://user-images.githubusercontent.com/30777327/132132475-e98d45c3-a5b2-4bbf-b659-3c5cdac8b00f.png)

**Comment by davidjgraph** [comment]
Declined
