### ISSUE TITLE
Links JSON Actions not working in HTML exported project

### ISSUE THREAD

**Issue by namonaihito** [jgraph/drawio#2228]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

After export project to HTML, my links with JSON data for "show" action is not working.
In Edit Mode all buttons with "Action" working properly, but the same actions not working after export to HTML.

Yesterday it was working fine, but today my previes exports (from 1-2 days ago) and new exports to HTML has the same bug.

**To Reproduce**
1. Open new project
2. Create 3 'TextField'
3. Add 'tags' propertie with 'testText' value to first TextField
4. Edit Link in second TextField and paste: `data:action/json,{"actions":[{"show":{"tags":["testText"]}}]}`
5. Edit Link in last TextField and paste: `data:action/json,{"actions":[{"hide":{"tags":["testText"]}}]}`
6. Try use "Action" button in Edit Mode (both actions should work)
7. Export project to HTML and open in Browser
8. Try use show and hide buttons
9. BUG: 'hide' action is working but then 'show' action do nothing, and our 'testText' field is gone

**Expected behavior**
Step 8. should has the same behavior as Step 6. in Edit Mode

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [15.0.6]

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome, firefox, edge]
 - Version [latest]

**Additional context**
I was editing the same project since last week and I have multimple HTML exports from my work. Today all those exports has the same issue. I think it's bug in one of JS files downloaded when exported HTML is open.

**Comment by namonaihito** [comment]
I've manually replaced viewer javascript file in my exported HTML from current version (from `src="https://viewer.diagrams.net/js/viewer-static.min.js"` ) to version '15.0.6 release' from github and everything is working. So I strongly feel that the last update '15.1.0 release' introduced this bug.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
