### ISSUE TITLE
Links not working in background pages

### ISSUE THREAD

**Issue by jimbotrue** [jgraph/drawio#2230]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
If you create a page to be used as a background page and place links in it (external, or to pages) the links will not work when document is exported to html. I believe this used to work few days ago. 

This is very useful feature, because you want to have a navigation that you change only in one place.

**To Reproduce**
1. Create page named BG to be used as background
2. Create other pages, PG1 and PG2
3. Place links on BG page that link to PG1 or PG2
4. Export HTML to observe that links don't work on PG1 and PG2

**Expected behavior**
Links that are placed in pages that are used as backgrounds (BG page) should be working on pages that use BG page as background

**Screenshots**
N/A

**draw.io version (In the Help->About menu of the draw.io editor):**
diagrams.net in firefox/chrome

- draw.io version [e.g. 12.6.7]
15.1.1

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser chrome/firefox
 - Version latest

**Comment by mararad** [comment]
Tested this in Chrome and FF and links are missing in HTML export.
