### ISSUE TITLE
Text background color can not be selected

### ISSUE THREAD

**Issue by kevburnsjr** [jgraph/drawio#2238]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Text Background Color cannot be enabled.

**To Reproduce**
1. Create any shape that contains text (ie. a Text element)
2. Click the Text tab in the right sidebar
3. Click the "Background Color" checkbox 

**Expected behavior**

- The "Background Color" checkbox is checked and the color selector is displayed.

**Actual behavior**

- The "Background Color" checkbox is checked for only a fraction of a second.
- The "Background Color" checkbox immediately unchecks itself and the color selector disappears.

**Screenshots**
Before clicking "Background Color" checkbox
![example](https://user-images.githubusercontent.com/20638/132778635-a6a9f734-0899-4fd3-a139-ffc413864e9a.png)
After clicking "Background Color" checkbox
![example](https://user-images.githubusercontent.com/20638/132778635-a6a9f734-0899-4fd3-a139-ffc413864e9a.png)

**draw.io version:**

- 15.1.4

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 93.0.4577.63,
 - Browser: Edge 93.0.961.38, 
 - Browser: Internet Explorer 19042.1165
 - Browser: Firefox 92.0 (64-bit)
 - Desktop App: 14.9.6

**Smartphone:**
 - Device: Android Galaxy S9
 - OS: Android Version 10 (QP1A.190711.020.G960U1UES9FUG2)
 - Browser: Chrome
 - Version: 93.0.4577.62

**Additional context**
It seems like 2 onclick event handlers are both toggling the checkbox at once.  
This defect has been present for several weeks.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by clayms** [comment]
same issue with only certain icons
