### ISSUE TITLE
disabling all external requests when self-hosted

### ISSUE THREAD

**Issue by tomryanx** [jgraph/drawio#224]
Is there a supported 'server-side' way to disable all external calls for self-hosted draw.io?

For example, I don't want/need calls to google analytics and friends.

I've seen in [another issue](https://github.com/jgraph/drawio/issues/18#issuecomment-255699541) a client-side way to do it.

**Comment by davidjgraph** [comment]
See https://desk.draw.io/support/solutions/articles/16000042546-what-url-parameters-are-supported-

analytics=0 turns that off.
stealth=0 turns everything external off.
