### ISSUE TITLE
set default style to the app is not working to any component-for ellipse,rectangle, etc., it always starts with fresh downloaded settings i guess or set as default style button is not working

### ISSUE THREAD

**Issue by vijaywavemaker** [jgraph/drawio#2240]
set default style to the app is not working to any component-for ellipse,rectangle, etc., it always starts with fresh downloaded settings i guess or set as default style button is not working.

I'm using latest windows version.. kindly please fix it.. everytime I could not set the style for each components. Thank you in advance :)

**Comment by davidjgraph** [comment]
Closing for not agreeing code of conduct.
