### ISSUE TITLE
Cannot import diagram into google docs

### ISSUE THREAD

**Issue by tleyden** [jgraph/drawio#2241]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I'm hitting the same issue as describe in https://github.com/jgraph/drawio/issues/2019.

**To Reproduce**
1. Create a diagram on www.draw.io
2. Create a new google doc
3. Go go Add-ons / Diagrams.net for Doc / Insert Diagrams 
4. Choose Page 1

**Expected behavior**

Embed document

**Screenshots**

![Screen Shot 2021-09-12 at 11 41 53 AM](https://user-images.githubusercontent.com/296876/132999065-7473885d-6e78-4d95-b08f-a91d8abacf36.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 15.1.1

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version Version 93.0.4577.63 (Official Build) (x86_64)

**Comment by Rrruli** [comment]
Same issue on my end

**Comment by davidjgraph** [comment]
Fixed, thanks for report.
