### ISSUE TITLE
Can not Export PDFs using DrawIo Online Tools in Google Drive. 

### ISSUE THREAD

**Issue by saschakruesi** [jgraph/drawio#2242]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
If you want to export your DrawIo Documents as PDFs I currently land on en error 500 on this URL https://convert.diagrams.net/node/export

This happens everytime if you want to export your documents > File > Export as > PDF and then click on Download you will be redirected to https://convert.diagrams.net/node/export with the error 500
![Bildschirmfoto 2021-09-13 um 08 05 29](https://user-images.githubusercontent.com/22472999/133031853-42ad314a-e06c-44af-91ba-bc9e4fa8e13d.png)

I tested this on a mac using chrome as browser. But it can consistently be reproduced on all other systems.

**Comment by Chibikuri** [comment]
I've been getting the same error for a day.

**Comment by davidjgraph** [comment]
Fixed, thanks for report.
