### ISSUE TITLE
URL parameter `clibs` doesn't seem to work with embed.diagrams.net

### ISSUE THREAD

**Issue by osnard** [jgraph/drawio#2243]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When using the "standalone app", one can use the URL parameter `clibs` to load custom shapes into the editor. Example: 
https://app.diagrams.net/?splash=0&clibs=Uhttps%3A%2F%2Fjgraph.github.io%2Fdrawio-libs%2Flibs%2Fun-ocha-icons-bluebox.xml;Uhttps%3A%2F%2Fjgraph.github.io%2Fdrawio-libs%2Flibs%2Fun-ocha-icons.xml

This approach does not seem to work when using embed.diagrams.net instead of app.diagrams.net

**To Reproduce**
1. Create an HTML document that uses an IFRAME to embed the diagram editor
2. Add parameter `clibs` to the URL as described on https://www.diagrams.net/doc/faq/supported-url-parameters (with properly URL escaped parameter values)
3. Load the HTML document in a webbrowser

**Expected behavior**
The custom shapes should be listed in the left column in their respective panels

**Additional context**
See also https://codepen.io/osnard/pen/rNwwmBK

**Comment by davidjgraph** [comment]
Embedding requires postMessage comms between the parent and child, https://www.diagrams.net/blog/embedding-walkthrough. The Codepen example does not have this. It won't work even without the clibs parameter.

**Comment by osnard** [comment]
Thanks! My apologies for providing a bad example. I was just re-using some code that I have available. And in there, an IFRAME is constructed with the URL. There is also postMessage communication for loading/saving diagrams, but the initial editor is just loaded via IFRAME. That's why I assumed one could just add `clibs` to that URL. I will check out your example.

**Comment by osnard** [comment]
I have updated https://codepen.io/osnard/pen/rNwwmBK to be a working example. Looks like the issue was `offline=1` parameter. Without it `clibs` seem to work.
