### ISSUE TITLE
Integration with ondrive not working

### ISSUE THREAD

**Issue by kari0ca** [jgraph/drawio#2247]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When i try to open a file that is stored on a sharepoint, i can't.
previously i could open files from onedrive/sharepoint without any problem.

**To Reproduce**
1. Open Existing Diagram
2. Login/authorize access to the account
3. Open
4. When the new window opens to select the file, select the option: Recent on the lateral menu, then the error will ocur.

**Expected behavior**
Show the folder structure of other sharepoint/onedrive

**Screenshots**
https://i.postimg.cc/DzYYfkQW/draw-error.png
![screen](https://i.postimg.cc/DzYYfkQW/draw-error.png "Error").

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 21.04, Windows 10]
 - Browser [e.g. chrome, firefox]
 - Version [e.g. chrome 91.0.4472.114, firefox 92.0]

**Comment by davidjgraph** [comment]
The image is of a sharepoint.com picker failing to find the search term "z5t". That's a problem on Microsoft's side.
