### ISSUE TITLE
OneDrive Integration Changed Behavior

### ISSUE THREAD

**Issue by Eddie-Hartman** [jgraph/drawio#2248]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.
* Similar to https://github.com/jgraph/drawio/issues/2247 but not quite the same.

**Describe the bug**
I'm unsure if this is a OneDrive change or Draw.io change, but either way it is an issue for my workflow.
Prior to a few weeks ago (unfortunately I do not know the exact time frame) when clicking Open Existing Diagram for OneDrive, I would have many more options for navigating through my files in OneDrive. Now, it only shows my personal OneDrive files, which I don't use because we share these documents with the entire team.

**To Reproduce**
1. Go to File -> Open From -> OneDrive
2. Click to proceed to where you select the file to open
3. Notice that the personal OneDrive opens and not a team one like previous functionality. There is no way that I'm aware of to open a file from a team setting in OneDrive.
![image](https://user-images.githubusercontent.com/14089997/133108725-71919971-5a52-4637-b045-e00728935721.png)

**Expected behavior**
Previously, I was able to open documents shared in Sharepoint with the entire team and have them sync.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]
- 15.2.4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 93.0.4577.63 (Official Build) (64-bit)

**Additional context**
If there is any workaround for this in the meantime please let me know. I'd like to avoid downloading and then uploading the files manually.

**Comment by ashrafteleb** [comment]
@Eddie-Hartman Can you please share a screenshot of your OneDrive for Business interface. I cannot fine sites there also.

![Screen Shot 2021-09-15 at 8 08 13 AM](https://user-images.githubusercontent.com/24944765/133430585-4b87e869-f284-4130-998f-d8520a1c392e.png)

Old (classic) OneDrive shows Sites
![Screen Shot 2021-09-15 at 8 08 48 AM](https://user-images.githubusercontent.com/24944765/133430642-a99dd6c6-c1a6-499c-98ef-73658cc761eb.png)

**Comment by ngarner-goxaas-io** [comment]
Specifically when trying to open documents. From onedrive storage. 
I can still find files and use the edit function in the word/sheets/pp insert >> draw.io app

**Comment by ashrafteleb** [comment]
@ngarner-goxaas-io In draw.io app for Office, we built our own file picker (which doesn't have all the features of OneDrive own file picker). Do you see sites in OneDrive UI?

BTW, you can have the same limited inline file picker using the following URL
https://app.diagrams.net/?inlinePicker=1

**Comment by ngarner-goxaas-io** [comment]
> @ngarner-goxaas-io In draw.io app for Office, we built our own file picker (which doesn't have all the features of OneDrive own file picker). Do you see sites in OneDrive UI?
> 
> BTW, you can have the same limited inline file picker using the following URL
> https://app.diagrams.net/?inlinePicker=1
@ashrafteleb 
OMG you saved my life. where do I donate

**Comment by davidjgraph** [comment]
We've changed this to be the default.
