### ISSUE TITLE
BPMN 2.0 shapes Tasks and Choreographies are black filled

### ISSUE THREAD

**Issue by IGZmanuelMartinVivaldi** [jgraph/drawio#2249]
BPMN 2.0 Tasks and Choreographies shapes are black filled (see image)

To reproduce just search and check BPMN 2.0 shapes

![image](https://user-images.githubusercontent.com/2234919/133120905-e7215a7e-a15c-42b8-b351-0bc13a18912d.png)
**draw.io version (In the Help->About menu of the draw.io editor):**

draw.io version 15.2.2

Desktop 
 - OS: Windows 10
 - Browser Google Chrome Version 93.0.4577.63

**Comment by davidjgraph** [comment]
Please agree to code of conduct when filing issues.

This is fixed in 15.2.4.
