### ISSUE TITLE
Wrong version number in "About"?

### ISSUE THREAD

**Issue by ebousse** [jgraph/drawio#225]
In the menu "Help" → "About", we currently get this window:
![capture d ecran de 2018-02-22 10-22-59](https://user-images.githubusercontent.com/5868014/36530105-806f9ad2-17ba-11e8-9059-10b2bd6ff79d.png)

However, the latest release seems to be 8.2.3:
![capture d ecran de 2018-02-22 10-24-20](https://user-images.githubusercontent.com/5868014/36530142-980b8412-17ba-11e8-83c5-0d7baaa48e92.png)

Shouldn't 8.2.3 be displayed in the "About" window?

**Comment by davidjgraph** [comment]
8.3.1 is the latest version, it's just that none of the changes in 8.3.0 and 8.3.1 were in the actually draw.io core codebase, so nothing on the Github project has actually changed.

**Comment by ebousse** [comment]
Ok, thanks for the explanation :). 

So neither the draw.io release used in the online version (https://www.draw.io/) nor the one used in the desktop versions (https://about.draw.io/integrations/) are using the latest version of the source code available on Github (https://github.com/jgraph/drawio)? They both rely on commits not yet made public on Github?

**Comment by davidjgraph** [comment]
No, the code you see in the public Github is exactly that deployed to both the online version and the desktop.

**Comment by davidjgraph** [comment]
Apart from the version string...
