### ISSUE TITLE
Setting default as sharp for line corners in configuration file

### ISSUE THREAD

**Issue by pabutterworth** [jgraph/drawio#2250]
Hi,
I'm creating a default configuration to get some consistency. I've used the instructions on the diagrams.net site. 

Most things are working, but I can't seem to setup connectors to have sharp corners rather than rounded. I have setup "rounded": "0", in both "defaultEdgeStyle": and "defaultVertexStyle":.

From what I had read, i think the line should inherit this style, unless I'm doing somthing wrong?

What else should I do? Is there another setting that I should use, or is this a bug.

Thanks

**Comment by alderg** [comment]
This works for me:

`{
  "defaultEdgeStyle": {
    "edgeStyle": "orthogonalEdgeStyle",
    "rounded": 1
  }
}`

**Comment by pabutterworth** [comment]
> This works for me:
> 
> `{ "defaultEdgeStyle": { "edgeStyle": "orthogonalEdgeStyle", "rounded": "0" } }`

Strange, I still get curves.

**Comment by pabutterworth** [comment]
Strangly, I get different behaviot for lines I draw or ones that are generated.
![image](https://user-images.githubusercontent.com/16760791/133442379-421694f2-e41f-4157-a946-ef064e6d15f4.png)

The one with the arrow was generated automatically, and is what I want. If I manually add a line and bend it, it's curved. I guess there is a different  setting for that?
