### ISSUE TITLE
MathJax anti-aliasing broken when exporting a diagram from the CLI

### ISSUE THREAD

**Issue by mpearson** [jgraph/drawio#2253]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When exporting a diagram in either PNG or SVG formats **using the drawio CLI**, the exported file does not have anti-aliasing on embedded math typesetting and is not just ugly, but literally unreadable in many cases. However, when exporting from the desktop app, the anti-aliasing looks fine.

I have attached a simple file illustrating the problem.

**To Reproduce**

1. Unzip this example diagram: [mathjax_antialiasing.zip](https://github.com/jgraph/drawio/files/7174484/mathjax_antialiasing.zip)

2. `cd` to the location of the file
3. Convert attached file to SVG format using the command ```drawio -x -f svg mathjax_antialiasing.drawio```
4. Open `mathjax_antialiasing.svg` in any browser

**Expected behavior**
I expect the exported SVG to look the same as when I manually export it from the GUI.

**Screenshots**
Expected MathJax appearance:
![mathjax_antialiasing_gui](https://user-images.githubusercontent.com/926478/133539309-5cad3d58-6680-41d5-bc2d-aad70f62534d.png)

Actual appearance when exporting via CLI:
![mathjax_antialiasing_cli](https://user-images.githubusercontent.com/926478/133539314-f18f3508-d6d2-48cc-93b9-68192cd1100f.png)

Note the image size is also different, but I'll let you guys file a bug for that one...

**draw.io version:**
- 15.2.7

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Opened the SVG file on Chrome 93 on Ubuntu, as well as both Chrome and Firefox on Windows. Looks perfectly hideous in all of the above.

**Additional context**
This is clearly caused by the `shape-rendering: crispEdges` styling included here: https://github.com/jgraph/drawio/blob/dev/src/main/webapp/export3.html#L8

It looks like before this was changed in version 13.4.2, this styling only applied to print media. I don't know what the use for it is there but `crispEdges` is definitely not what you want in an SVG file.

**Comment by mpearson** [comment]
Why was this issue closed? It doesn't look like any fix has been implemented.

**Comment by davidjgraph** [comment]
Nobody wanted to look, but we can leave it open and nobody look if you prefer :)

**Comment by mpearson** [comment]
Ok thanks, when I have time I will test on a few more platforms and make a PR myself. I use LaTeX extensively in my diagrams so this bug is a real bummer.

**Comment by alderg** [comment]
This will be fixed in the next release.
