### ISSUE TITLE
The Confluence draw.io does not import Microsoft Visio Professional 2019 .vsdx files correctly.

### ISSUE THREAD

**Issue by alexurakhchin** [jgraph/drawio#2255]
[The Confluence draw.io does not import Microsoft Visio Professional 2019 .vsdx files correctly.
Attached is test2.vsdx. Sorry, but that .vsdx cannot be attached. After importing that file, the "has-a" arrows disappeared.]

**Comment by davidjgraph** [comment]
If you're a paying customer you can submit a ticket directly at https://drawio.atlassian.net/servicedesk/customer/portal/14
