### ISSUE TITLE
small icon(svg format), but become very big on workspace after drag it from left pane

### ISSUE THREAD

**Issue by sharpboy2008** [jgraph/drawio#2257]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
small icon(svg format), but become very big on workspace after drag it from left pane.

**To Reproduce**
1. create a library
2. add a svg icon
3. drag it to workspace(such as page -1),sceenshot attached
 

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 15.2.7

**Desktop (please complete the following information):**

 - Browser [ chrome v93 ]

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about
![image](https://user-images.githubusercontent.com/17189077/133956305-3e05fc6e-4a28-4e34-ac35-c9e5ea0442d8.png)
 the problem here.

**Comment by mararad** [comment]
Hi,

Could you export the library in question and attach the .xml file here so I could try to test it?

Regards,

**Comment by sharpboy2008** [comment]
[Ali Cloud.zip](https://github.com/jgraph/drawio/files/7196650/Ali.Cloud.zip)
attached, including draw.io and svg files

**Comment by mararad** [comment]
Thanks.

My suggestion would be to drop .svg into the editor, make it smaller and then create a custom library or scratchpad.
I am afraid there is no easy explanation why this is happening.

Hope this will help you as a quick workaround.

Regards,

**Comment by sharpboy2008** [comment]
got it. will give a try. is this still a bug which will get fixed?

**Comment by sharpboy2008** [comment]
Hi, do you have plan when this will be fixed?
