### ISSUE TITLE
Color picker picks colors from a different place than cursor

### ISSUE THREAD

**Issue by abelmatser** [jgraph/drawio#2259]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I try to pick the color of a line I have previously colored, the color picker does not allow me to pick a color. The zoomed view does not show the color of the line, and other elements (box edges) are shifted in the zoomed view (when the cursor hovers over box edges, they are not visible in the zoomed view). The color picker is opened by clicking on a new line, shift clicking on the Style fill tool and hovering over the desired location of color picking.

BTW, I would still like to express my gratitude for this feature it really helps my diagramming workflow. (Original issue: https://github.com/jgraph/drawio/issues/1350)

**To Reproduce**
1. Draw a red line
2. Draw a new line
3. Try to set the color of the second line by color picking from the first line
4. See that this is not possible

**Expected behavior**
I would expect to be able to pick colors directly under the cursor

**Screenshots**
![color_picker_before](https://user-images.githubusercontent.com/33466359/134161434-ac2e38f2-4663-4221-8030-198be5459a6e.PNG)
![color_picker_after](https://user-images.githubusercontent.com/33466359/134161454-312414b4-881d-4e7c-bb54-f0410826df17.PNG)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 15.2.7

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Both Edge Version 93.0.961.47 (Official build) (64-bit) and Chrome Version 93.0.4577.82 (Official Build) (64-bit)
but I am using the standalone app version

**Additional context**

**Comment by mararad** [comment]
Hi,

Try using Shift+Click for color dropper https://twitter.com/drawio/status/1431986012981534721

Regards,

**Comment by abelmatser** [comment]
That is the tool I was using, but weirdly the error does not happen again today. I will mark it closed since it seems like a one-off bug.
