### ISSUE TITLE
[feature] Have more than two z-orders for the lines that support line jumps

### ISSUE THREAD

**Issue by s-sarunas** [jgraph/drawio#226]
While working with line jumps you cannot have lines in the background without creating line jumps on the primary lines.

This results in background lines overlapping everything else or unnecessary line jumps:
![illustration](https://user-images.githubusercontent.com/36805253/36637296-4e7a3546-19d1-11e8-938d-1c7c66913818.png)

**Comment by alderg** [comment]
Depending on the red line routing and layout, you could make them curved for the green line with the line jumps to ignore them if they are in the background.

**Comment by s-sarunas** [comment]
Thanks, making the red background lines curved fixed the problem. However, that only makes sense if the lines are straight or supposed to be curved. It would be nice if having lines in different layers would affect how they interact with each other.

**Comment by alderg** [comment]
We'll add a noJump=1 style for edges that should be ignored in 8.4.5 (use Edit Style).
