### ISSUE TITLE
Add columns like Table

### ISSUE THREAD

**Issue by mojusousuo** [jgraph/drawio#2260]
![image](https://user-images.githubusercontent.com/26040438/134449480-fce4e4ec-c5b7-4fbb-bc9d-670184a89bf4.png)

As shown above, add columns like Table
![image](https://user-images.githubusercontent.com/26040438/134449529-624c079e-dd29-4937-a59b-9092c47a536c.png)

**Comment by alderg** [comment]
Thanks for the report. This will be added in the next release.
