### ISSUE TITLE
PlaceHolder text doesn't disappear by typing when editing online

### ISSUE THREAD

**Issue by sunux** [jgraph/drawio#2261]
**Describe the bug**
In previous versions(about a week ago), default placeholder text in shape will disappear automatically by typing new content. But now it doesn't. Typing only append new text in front of default placeholder. It quite inconvenient for Mac doesn't have END key and Command + A can't yet select all default placeholder.

**To Reproduce**
1. add a shape with default placeholder text, for example a UML class
2. select a field area and start typing
3. new content append in front of placeholder text

**Expected behavior**
Default placeholder text disappears with only new typing content remians.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 15.3.0

**Desktop (please complete the following information):**
 - OS: [MacOS 10.15.7]
 - Browser [Chrome 93.0.4577.63]

**Comment by sunux** [comment]
Another problem is text in textarea, such as a note, can is not selectable. And insert pointer can not be moved amount text.

**Comment by sunux** [comment]
I found something. This happens each time you open draw.io the first time you open or create a document. After refreshing the page, problems solved.

**Comment by mararad** [comment]
Hi,

I couldn't reproduce this but I am a Win user. If you test this in other browsers and Private mode (without browser extensions) does it help? If browser cache is cleared, do you see the same behaviour?

Regards,

**Comment by sunux** [comment]
> Hi,
> 
> I couldn't reproduce this but I am a Win user. If you test this in other browsers and Private mode (without browser extensions) does it help? If browser cache is cleared, do you see the same behaviour?
> 
> Regards,

Hi,
I tried it in both Chrome and Firefox's Private mode. It seems to work properly with no problem. So it may have something to do with cache. Thank you for helping. 

Regards.
