### ISSUE TITLE
Dragging the graph with the mouse hopes that when the size of the current graph is changed, the whole will also change. Rather than partial changes.

### ISSUE THREAD

**Issue by mojusousuo** [jgraph/drawio#2262]
Current effect
![image](https://user-images.githubusercontent.com/26040438/134472288-e800102c-1b7b-4ed9-a603-c78c4105f429.png)
The effect i need
![image](https://user-images.githubusercontent.com/26040438/134472489-a60ab3f2-cc90-4b1e-b6ac-af809b36cd1a.png)

**Comment by alderg** [comment]
Shift+drag of the divider will handle this in the next release.
