### ISSUE TITLE
Sub-elements follow element-level zoom

### ISSUE THREAD

**Issue by xhxhxhxh** [jgraph/drawio#2263]
### Preflight Checklist

* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Drag a diagram element into canvas, scale this element, the element has been resized, but the children element does not resize.

**To Reproduce**

**Expected behavior**
Sub-elements follow element-level zoom 

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mararad** [comment]
Hi,

Could you provide us with an example screen shot, diagram file or video?

Regards,

**Comment by xhxhxhxh** [comment]
> Hi,
> 
> Could you provide us with an example screen shot, diagram file or video?
> 
> Regards,
before scale
![Dingtalk_20210923173744](https://user-images.githubusercontent.com/46396186/134487055-362d7656-6c74-4942-9bae-2f84f830291c.jpg)

after scale, child element has been scaled too
![Dingtalk_20210923173802](https://user-images.githubusercontent.com/46396186/134487069-6b8c105c-c7a0-49f7-9652-dd2eb9ef0f01.jpg)

**Comment by xhxhxhxh** [comment]
> Hi,
> 
> Could you provide us with an example screen shot, diagram file or video?
> 
> Regards,

before scale
![Dingtalk_20210923173744](https://user-images.githubusercontent.com/46396186/134487335-fedd7404-8baa-41c9-910c-333757f986b7.jpg)

after scaled, child element has been scaled too
![Dingtalk_20210923173802](https://user-images.githubusercontent.com/46396186/134487543-bfa2d6a2-aa04-4813-a1fb-6316844ffa38.jpg)

**Comment by mararad** [comment]
Thanks.

Tick "Resize Children" option under Property/Value when the parent shape is selected.
