### ISSUE TITLE
Add ability to filter and sort projects with GitLab integration

### ISSUE THREAD

**Issue by lfvjimisola** [jgraph/drawio#2264]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to find a project in GitLab with DrawIO because there are hundreds of projects available to me.

**Describe the solution you'd like**
I would like to be able to filter and sort in order for me to easier find the project that I'm looking for.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lfvjimisola** [comment]
@davidjgraph This issue was closed without a comment. Was it closed by mistake? If not, what was the reason?

**Comment by davidjgraph** [comment]
It was closed because it will not be implemented.

**Comment by lfvjimisola** [comment]
Ok. Could you please explain why that is? The lack of search makes it difficult/time-consuming to use.

**Comment by davidjgraph** [comment]
Because we don't have the time and resources to implement it.

**Comment by lfvjimisola** [comment]
Ok, that's completely understandable. But, by closing it you reduce the change of someone making a PR for it.

**Comment by davidjgraph** [comment]
We don't accept PRs, please see main README.
