### ISSUE TITLE
Containers to support full resizing of elements

### ISSUE THREAD

**Issue by agrosjea** [jgraph/drawio#2265]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
My company uses Diagrams.net to create many technical diagrams. 
We need to put these diagrams into a signature block which has to fit exactly a tabloid page. 
The issue is when your diagram starts to be bigger that the signature block... how do you resize it properly ?
Currently creating a container does scale properly the drawings but not the text, nor the line/dash sizes....

**Describe the solution you'd like**
Two options there : 
1 improve general scaling support of the containers.
2 have a viewport feature allowing to draw a rectangle around a region and reference this viewport somewhere else. 

Second option could definitely offer more. 
e.g. one could create a master diagram and then reference it on many different pages to describe it per section. A nice way to separate drawing step from page layout step. 
Could also attach more features on it such as the ability to create an embed link on a specific viewport only...

**Describe alternatives you've considered**
Currently, I need to manually scale the text or reorganize my diagram... 
I also sometime just "copy as image" my diagram and then paste the image in the signature block... but this gives an amateur looking pdf export then...

https://user-images.githubusercontent.com/1466085/134580455-9bdfb907-1467-40a8-bd59-e9fa89badacc.mp4

**Comment by mararad** [comment]
Hi,

There is the issue https://github.com/jgraph/drawio/issues/984 ("Text element that scales with its container") you can also track and comment. 

Regards,

**Comment by agrosjea** [comment]
Thank you @mararad for the the follow up.
Yes this issue is related.

**Comment by pfleer** [comment]
I'm keen to see this feature implemented as it seems at odds with the rest of the objects which scale perfectly.
