### ISSUE TITLE
Integration with OnlyOffice

### ISSUE THREAD

**Issue by Pelicans-git** [jgraph/drawio#2267]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Are there any plans to integrate with OnlyOffice? OnlyOffice is amazing, but it needs a diagramming tool such as drawio. OnlyOffice Workspace is an great versioning tool for documents, so the ability to open and edit drawio files from there would be incredible.

**Describe the solution you'd like**
The ability to open and edit drawio files from OnlyOffice.

**Describe alternatives you've considered**
Using OnlyOffice and Drawio separately.

**Additional context**

**Comment by davidjgraph** [comment]
"The ability to open and edit drawio files from OnlyOffice."

What would that look like as a process? I don't see any action on this project required for that.

**Comment by Pelicans-git** [comment]
OnlyOffice an incredible tool for versioning and editing Microsoft Office. The one thing missing from the suite is a diagramming tool like Drawio. And Drawio is by far the best diagramming tool.

The flow would need some integration work, but ideally, it would look like this:
1. drawio files are stored and version controlled in OnlyOffice (this already works)
2. When you click on a drawio file, it opens the drawio editor and you can make changes as you like.
3. When you save the drawio file, it updates the file in the OnlyOffice repository.

If you haven't looked at OnlyOffice yet, then please have a look at https://www.onlyoffice.com/ it is also open source.

**Comment by davidjgraph** [comment]
Yeah, this needs work on the OnlyOffice side of things, I don't see any action for this project.
