### ISSUE TITLE
View > Background option runs into "change…" button in Boards macro for Confluence Cloud

### ISSUE THREAD

**Issue by Bastesque** [jgraph/drawio#2268]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**
When I expand the Format panel in the draw.io Board macro, the text of the "Background" checkbox always runs into the "Change" button on the right. I can adjust the width of the panel, but once I collapse the panel and expand it again, it's the same scenario again.

**Expected behavior**
Text and Button don't overlap.

**Screenshots**
<img width="238" alt="Screenshot 2021-09-24 at 11 59 59" src="https://user-images.githubusercontent.com/68647048/134657619-be08c9bb-af08-42b4-8eee-d5d5673ab4b0.png">

**Comment by davidjgraph** [comment]
I don't see this, what browser?

**Comment by Bastesque** [comment]
Chrome, latest version.

**Comment by davidjgraph** [comment]
Looking into it. If, say, you needed a screenshot or video for now, use Firefox 8-).

**Comment by davidjgraph** [comment]
Fixed in 15.3.2
