### ISSUE TITLE
Some elements shown as black X in exported images

### ISSUE THREAD

**Issue by ViliusSutkus** [jgraph/drawio#227]
Step 1. Add some items to drawing.
Example:
`<mxfile version="8.3.2" editor="www.draw.io" type="device"><diagram id="ba240321-a644-afa4-6ab9-025c00f628fa" name="Page-1">5Vddb9sgFP01eVwU4yTtHpM06aYtUrVq22OF7RsblQ8LcGPv1+/ibzepWqnupq15CHC4cOGcewFP/I3IrzVNk72KgE/ILMon/tWEEM/zllg4pKiQ+YJUQKxZVBt1wC37BTU4q9GMRWAGhlYpblk6BEMlJYR2gFGt1XFodlB86DWlMZwAtyHlp+hPFtmkQi8Xsw7/BCxOGs/erO4JaHgfa5XJ2t+E+IfyV3UL2sxV25uERurYg/ztxN9opWxVE/kGuOO2oa0at3uit123BmlfMqCW5YHyDJoVl+uyRcMFLjF1VSZK0taJFRybHlYfQFuGrK04iyViVqU99CsNgN8owyxTrjdQ1iqBBtx1rFumNoorXfpquPLXpbOVSStxZ4jQpnFgOUSNCbYTa11UrNwmyS6M5GzKMC4OTEagpyF6JLuIWoqFww2WAeAa3WiyW87xb73dfrvbf7/+4JHLaSrjmhTcB+RPEuu1cmEagBJgdYEm+TCSi2Hz2EUT+qqwpB9JDUjrCI7bmTsVsVILeV7UxbsU9QeTFgd/YTZMQN7tV46nks/dPovHknX5F3Vd/oe6kueTlVnDwLRibrJ0xDz1yVBQ8icFvXhe0Gf1OS9rT3djtbpvrzHikDpIRB6763saUMPCqRGMQzECpWQ+TBH/8pTS5r4cUNqAr6H048tzpN1+KuS0Bs8lzGtS47w6KWiGOwNnjcvHVw3cdNBaZZYzCaUrnPezo31tChEotzTA942zGuM0u3gk1fI0+hdnlFqMIFRzcv47SulEiSAzfaUGz72YWjjSYiCgTfAxyvCk6gkowJjqdB4j2RaPLqT5aba9mYTee5BQKld08qE2lHPg18dxFHx8A72hgtjsPi3Kvt73m7/9DQ==</diagram></mxfile>`

Step 2. Export.

Step 3. Get X instead of some items
![result](https://user-images.githubusercontent.com/812793/36697899-0163a720-1b51-11e8-9efc-da94a6c68ae6.png)

**Comment by alderg** [comment]
Fixed in 8.3.4. Thanks for the report!

**Comment by ViliusSutkus** [comment]
Thanks :+1:
