### ISSUE TITLE
Lollypop connector improvement

### ISSUE THREAD

**Issue by floongle** [jgraph/drawio#2270]
When a lollypop connector is created, it is actually a small circle and a line with a "--C" connector at the end.

By default, the circle does not have any connection points, which makes aligning them in diagrams a bit hit-and-miss.

Please consider updating the default style of the circle to include connection points (as seen in most other objects). For example "points=[[0,0.5],[1,0.5],[0.5,0],[0.5,1],[0.5,0.5]]" would ensure that no matter the connection angle, the lollypop will look correct.

Example of update:
![image](https://user-images.githubusercontent.com/44733236/134932061-4b6e8849-408f-4a48-846e-021cbe894f4b.png)

I appreciate that users can add these in themselves, however it stands out as an exception to the rule that shapes have these by default.

**Comment by alderg** [comment]
We'll add outlineConnect=0 to simplify this (it will use a "blue" aka floating connection point, which snaps to all four directions).

**Comment by floongle** [comment]
Makes sense. I'd also recommend including [0.5,0.5] as a point, because without a central connection point, the "--C" connector will be too far out from the circle.

**Comment by alderg** [comment]
The --C connector has that hardcoded via the entryX/Y style. The problem with adding the point to the shape is it isis too small and it will no longer be possible to connect to the outline without zooming in.
