### ISSUE TITLE
Problem with inserting new swimlanes in a vertical/horizontal pool in draw.io for Confluence Server

### ISSUE THREAD

**Issue by Bastesque** [jgraph/drawio#2271]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I recorded a video (private Youtube link: https://youtu.be/yGI21gbiu-I) about the behavior that one of our clients noticed. It doesn't come up in draw.io for Confluence Cloud or in diagrams.net, so I guess it's a bug. You can add new swimlanes in a vertical pool via the left blue arrow of another swimlane, but the right doesn't work properly. In the horizontal pool, it's the lower blue arrow that doesn't work (all described in the video).

**To Reproduce**
See video.

- Confluence Server version 7.12.5
- draw.io version 9.5.14

**Comment by davidjgraph** [comment]
If they update to the latest version it's fixed there.
