### ISSUE TITLE
Text labels do not get properly rendered on Safari when in chromeless read-only mode

### ISSUE THREAD

**Issue by borisruf** [jgraph/drawio#2277]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
On Safari 13.1.13 or on Safari 15.0, when in chromeless read-only mode, text labels are not rendered as expected. This problem does not occur on latest versions of Chrome and Firefox.

**To Reproduce**
Try this url on Safari, and compare with Chrome or Firefox:
https://app.diagrams.net/?chrome=0#RdZNNc4IwEIZ%2FDUdnQlCkR7XW9lDbqjOeI4kkHSA0xgL99Q1mA2FsLxCeffczSxCtimajSMVfJWV5gBFtgugxwHgaJTPz6khrCU5iZEmmBLUsHMBe%2FDCATnYVlF1GQi1lrkUFEHSpLEuW6pGQKCXrse9Z5uOsFcnYHdinJL%2BnR0E1BxojNBiemcg4pDYFgaUgTg3gwgmVtYeidRCtlJTanopmxfJufG4w1u%2FpH2tfmWKl%2FsNBnj67gWCUk5O5lZsgwHFutMvKHLLu4MBZlp30TFLbd%2Fx17cpaHkRhpo%2FRltXmuZMFKQejC7I%2FLHYHF8nkt8HGCQz2kmKvj49qMa8RemGnI9%2FSh%2FfF23w5Sfr59H1fdOsuRclrSVnnj0y4mgvN9pUtvTZ7aBjXRddyCK3BXoVhn90fG0zymynNGg9B%2Fg2TBdOqNRKwTnA8S6xT6wiazS2pvTVxu8C9DZkCI7CZWR9%2BuDtzgL7dJ9ym%2Bxy25ib1%2Fr5o%2FQs%3D

Curiously, the viewer works on Safari:
https://viewer.diagrams.net/?#RdZNNc4IwEIZ%2FDUdnQlCkR7XW9lDbqjOeI4kkHSA0xgL99Q1mA2FsLxCeffczSxCtimajSMVfJWV5gBFtgugxwHgaJTPz6khrCU5iZEmmBLUsHMBe%2FDCATnYVlF1GQi1lrkUFEHSpLEuW6pGQKCXrse9Z5uOsFcnYHdinJL%2BnR0E1BxojNBiemcg4pDYFgaUgTg3gwgmVtYeidRCtlJTanopmxfJufG4w1u%2FpH2tfmWKl%2FsNBnj67gWCUk5O5lZsgwHFutMvKHLLu4MBZlp30TFLbd%2Fx17cpaHkRhpo%2FRltXmuZMFKQejC7I%2FLHYHF8nkt8HGCQz2kmKvj49qMa8RemGnI9%2FSh%2FfF23w5Sfr59H1fdOsuRclrSVnnj0y4mgvN9pUtvTZ7aBjXRddyCK3BXoVhn90fG0zymynNGg9B%2Fg2TBdOqNRKwTnA8S6xT6wiazS2pvTVxu8C9DZkCI7CZWR9%2BuDtzgL7dJ9ym%2Bxy25ib1%2Fr5o%2FQs%3D

**Expected behavior**
The text label of the box should be visible.

**Screenshots**
Safari:
<img width="728" alt="Screenshot Safari 13-1-13" src="https://user-images.githubusercontent.com/95551/135341647-62637e96-c096-44e1-ae80-bdd85ee81d75.png">

Chrome:
<img width="770" alt="Screenshot Chrome 94-0-4606-61" src="https://user-images.githubusercontent.com/95551/135341643-5d429e90-ed80-4a25-9c74-c33876760cd1.png">

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 15.3.8

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7 and macOS 11.6
 - Browser: Safari
 - Version 13.1.13 and 15.0

**Additional context**
- There no errors in the Safari console 
- It would be interesting to learn how viewer.diagrams.net is different to app.diagrams.net/?chrome=0
- I noticed that in rare cases the text label eventually appears, possibly related to switching tabs

Thanks for your great work, drawio/diagrams.net is truly awesome!

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
