### ISSUE TITLE
[feature] Remember last used folder

### ISSUE THREAD

**Issue by ebousse** [jgraph/drawio#228]
When opening/saving/exporting a drawing, draw.io always opens the file opener in the home folder of the operating system, even just after opening a file.

Could maybe draw.io remember what was the last folder that was used while opening/saving/exporting?

**Comment by davidjgraph** [comment]
It's not possible with the online version, only the OS can do this (hint, get a Mac).

**Comment by ebousse** [comment]
Indeed, I'll open an issue in the drawio-desktop bug tracker instead. Thanks!
