### ISSUE TITLE
Line-height breaks placeholders

### ISSUE THREAD

**Issue by rubenvandeven** [jgraph/drawio#2280]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

When using line-height or another style property with percentage sign, placeholders don't work anymore.

Or, percentage signs in style attributes should be ignored for placeholders.

**To Reproduce**
1. create text node with `%test%`
2. `Ctrl+m` and add property `test` with any value to your liking, make sure to check "placeholders" checkbox. Click Apply
3. Placeholder work for now.
4. Double click text box, to select. Then single click to deselect but keep cursor.
5. In text properties, adjust `line height`.
6. Placeholder now breaks (only `%test%` is shown)

Workaround:

1. Extra -> Edit Diagram ...
2. Replace the set line-height (which has a percentage value), with a value defined as `px` or `pt`.
3. `Ok`
4. Placeholder works again.

**Expected behavior**
Placeholder should have been replaced.

**draw.io version**

- draw.io version 15.1.3 on linux desktop and 15.3.4 on chromium

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chromium
 - Version 93.0.4577.82

**Comment by rubenvandeven** [comment]
Quick workaround for the GUI: change line-height from percentage to [a unitless value](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height). (Which is apparently preferred way according to MDN)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by davidjgraph** [comment]
In 15.4.1

**Comment by rubenvandeven** [comment]
That was fast, thanks!
