### ISSUE TITLE
Command palette

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#2282]
Search driven interface to find functions, https://groups.google.com/g/drawio/c/Hcsll2qifVI/m/IHAsE7FnCgAJ

**Comment by pcgeek86** [comment]
I would still love to see this feature added.

**Comment by kkweon** [comment]
I would also greatly appreciate seeing this feature enabled. What steps are necessary to revitalize this FR and advance its progress?

**Comment by alderg** [comment]
Added in v27.0.6.
