### ISSUE TITLE
Add Handwriting. 

### ISSUE THREAD

**Issue by JJger148** [jgraph/drawio#2285]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I love diagrams for many use cases, but I still have to go back to other programs I have to pay for on my Ipad for sketching. 
I would love to see drawio, to support handwriting. 

**Describe the solution you'd like**
[Concepts](https://concepts.app/de/) could be seen as a good inspiration on how to improve drawio for hand sketching. 

**Describe alternatives you've considered**

**Additional context**
<img width="201" alt="Bildschirmfoto 2021-10-04 um 10 39 10" src="https://user-images.githubusercontent.com/68868949/135820081-9e3a356f-ff4e-4a73-ae5c-9b5b3fd32aab.png">

**Comment by davidjgraph** [comment]
Declined
