### ISSUE TITLE
Add PDF support. Dropping and opening PDF in draw.io 

### ISSUE THREAD

**Issue by JJger148** [jgraph/drawio#2286]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
So I would love to see PDF support, so that I can simply drop PDF's in my draw.io and open them in my favourite PDF viewer. 

**Describe the solution you'd like**
I want to use draw.io instead of [muse](https://museapp.com/) as my thinking work desk. 
This would then become my Visual work desk for different Projects. 

**Describe alternatives you've considered**
I currently use museapp and miro as an alternative/

**Comment by gzquse** [comment]
@davidjgraph 
Hi david,
if this issue fixed? I seem still cannot drop the pdf file to the draw.io whiteboard.
