### ISSUE TITLE
Generate markdown database from Visual illustration. 

### ISSUE THREAD

**Issue by JJger148** [jgraph/drawio#2287]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When I use draw.io I want my data to be available in my knowledge base (obsidian and zettlr) 
So I would love to see visual draw.io date to be converted into a markdown repository.

**Comment by davidjgraph** [comment]
That is outside of the scope of the project.
