### ISSUE TITLE
Titel innerhalb der Swimmlane möglich

### ISSUE THREAD

**Issue by Tanja22R** [jgraph/drawio#2288]
Hi liebes Diagrams-Team, ich hätte ein Frage und zwar wollte ich wissen, ob es innerhalb einer Lane die Möglichkeit gibt, das was ganz vorne im Balken als Beschriftung der Lane eingetragen wird auch in verschiedenen Abständen wie ein Wasserzeichen nochmal aufführen zu lassen? Wenn ich einen langen Prozess male und ich weiter nach rechts scrawle, dann habe ich oft das Problem, dass ich nicht mehr weis in welcher Lane ich mich gerade befinde wenn ich mehrere davon habe. Hier wäre eine durchgängige Kennzeichnung der Lane super. Vorab danke für eure Antwort. Grüße Tanja

**Comment by davidjgraph** [comment]
Hi dear Diagrams team, I have a question and I wanted to know whether there is the possibility within a lane to have what is entered at the very front of the bar as a label for the lane, also to be listed again at different intervals like a watermark? If I paint a long process and I continue to scrawl to the right, then I often have the problem that I no longer know which lane I am in when I have several of them. Consistent marking of the lane would be great here. Thank you in advance for your answer. Greetings Tanja

**Comment by davidjgraph** [comment]
Is a screenshot of the problem possible?

**Comment by alderg** [comment]
Hallo Tanja. Zur Zeit ist das nicht möglich. Eine mögliche Lösung wäre die Markierung der Swimlane mit Farben (Lane-Color oder Linie).

**Comment by Tanja22R** [comment]
Hi David, attached a picture of a swimmlane showing the name of the lane after a few steps. In the picture, I did the marking by including a Text, unfortunately this would be very time consuming if I had to do this for each line every tim. Because of this it would be great if ther might be a function as a water sign or something. As an example, you can see this in Visio. Regards Tanja
![2288](https://user-images.githubusercontent.com/91890246/135853894-5c91ac22-d434-4fd8-892e-df789116a9cb.JPG)

**Comment by Tanja22R** [comment]
Hi aderg, 
Ok, danke für deine Nachricht. Schade, Farbe ist nicht möglich da wir unsere Prozesse mit drawio machen. Danke dennoch für die Antwort. Grüße Tanja
