### ISSUE TITLE
Add plugin through custom URL does not work

### ISSUE THREAD

**Issue by eliseyue** [jgraph/drawio#2289]
I tried to add plugin through custom URL(github raw  javascript file), but it does not response at all.  Is this a mistake, or is this done intentionally.

**Comment by davidjgraph** [comment]
Add it to where? Using what browser?

**Comment by eliseyue** [comment]
Hallo, David. thanks for answering. I tried to add a plugin in the drawio website through plugins- add- custom. But it did not work. I am using Chrome. The plugin is here to find which works if I cloned your project and added to the plugin folder: https://github.com/eliseyue/drawioCsv/blob/main/importCSV.js

**Comment by davidjgraph** [comment]
In the draw.io web site? At app.diagrams.net? That doesn't support external plugins. You'd need to host your own site for that.
