### ISSUE TITLE
[FEATURE] Context menu create new file from selected tab

### ISSUE THREAD

**Issue by Tropicalrambler** [jgraph/drawio#2295]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Sometimes I find it necessary to create an individual .drawio file from a specific tab.  Although a user can duplicate a file, and delete all pages, a faster process I have envisioned would be to add a context menu item after right clicking the selected tab that creates a  "New File from Tab".

**Describe the solution you'd like**
Add a context menu item that permits the creation of a new, separate file with all the contents from a specific drawio tab.

**Describe alternatives you've considered**
I mentioned them above (duplicating the file, and deleting all other tabs.) This is cumbersome.

**Additional context**
<img width="182" alt="Screen Shot 2021-10-05 at 1 38 47 PM" src="https://user-images.githubusercontent.com/16600935/136091349-0f0dad31-a0ab-4865-a03b-cf3b47f26373.png">

**Comment by alderg** [comment]
Which version are you using? Are you using desktop or online? If you are using online click "Open in new window" in the context menu of the page tab to create a new file from just that page:
<img width="314" alt="Screenshot 2021-10-06 at 06 01 20" src="https://user-images.githubusercontent.com/921200/136138805-725199c8-fec5-4696-9243-be620e3d233b.png">
