### ISSUE TITLE
Export multi-page file as uncompressed XML

### ISSUE THREAD

**Issue by CawawaC** [jgraph/drawio#230]
Hey!
When exporting a multi-page diagram as XML, the option for uncompressed XML is not there. Could someone please add it? :) that would be very nice of you and you'd have my eternal thanks :)

Pretty please.

**Comment by davidjgraph** [comment]
It's not an easy thing todo. You're welcome to submit a PR for the change.

**Comment by CawawaC** [comment]
I'm sure it is.
I'm making changes in a file in webapp/js/diagramly directory, but it doesn't seem to change anything when I run the index.html. Can you please tell me if I'm missing a step here?

**Comment by davidjgraph** [comment]
add the dev=1 parameter to load the raw JS. The min.js files are used by default.

**Comment by CawawaC** [comment]
So it should look like this ? file:///........./index.html?dev=1
That doesn't seem to be working, I get :
> Page could not be loaded. Please try refreshing. 
> Please ensure JavaScript is enabled.

Even without any local changes.

**Comment by davidjgraph** [comment]
you can't run it from the file system, Chrome and most other decent browsers will crap out on XHR calls. You need to server via a local web server, IIS, Apache, Nginx, other.

**Comment by CawawaC** [comment]
Ok that's completely out of my wheelhouse. So I went ahead and made a pull request that **should** work. Looks like it passed the tests without any problem \o/
Thanks for the help
