### ISSUE TITLE
Infinite canvas

### ISSUE THREAD

**Issue by SamSandq** [jgraph/drawio#2300]
When creating or editing a new diagram the size of the canvas is one of the presets. It would be nice to be able to set 'infinite' to allow it to grow in all directions as we add shapes.

Note that this also implies that e.g. PDF exports would use the real size of the diagram, like PNG export can do now.

**Comment by mararad** [comment]
Hi,

Canvas should expand in all direction as shapes are added. Also, you can untick View > Page View in order to get infinite canvas.
