### ISSUE TITLE
[Bug] Need help, Can't open .drawio file, File broken when I add too many pictures into the .drawio

### ISSUE THREAD

**Issue by A11en0** [jgraph/drawio#2302]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I add too many pictures into the .drawio file(size of 128K now), It can not open with a description like below:

![image](https://user-images.githubusercontent.com/33925232/136506131-966022a0-96ee-4535-abc9-74c6c7810672.png)

where the header Chinese means "Loading File Error". How can I restore it? **The contents are very important for me. Help Please!**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version is V12.3.2

**Desktop (please complete the following information):**
 - OS: Debian 10

**Comment by A11en0** [comment]
I don't know why you need a browser version? Because I use the client program. It's dependent on the browser. My default browser is Chrome Version 93.0.4577.82 (Official Build) (64-bit) run on Linux Debian.

**Comment by mararad** [comment]
Where did you save the file? Is there a way to find older diagram versions?

The last release is 15.5.0 (https://github.com/jgraph/drawio/blob/dev/ChangeLog) and you use 12.3.2 which is very old (from 2019). How did you get this version?

When you say "I use the client program, it's dependent on the browser." what does it exactly mean, please?
