### ISSUE TITLE
Search returns incomplete results for "SPST"

### ISSUE THREAD

**Issue by cjbarth** [jgraph/drawio#2305]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Searching for DPDT brings up the correct electrical switch, searching for SPST doesn't find any results. However, when I manually expand the panels looking for the SPST, I find it, and it is named exactly as SPST. It is under "Electrical / Switches and Relays".

**To Reproduce**
1. Make sure that Elecritcal shapes are loaded.
2. Search for DPDT, note that the correct item is shown in the search results box.
3. Search for SPST, note that no items are found in the search results box.

**Expected behavior**
The item for SPST should show in the search results box like happens when searching for DPDT.

**draw.io version (In the Help->About menu of the draw.io editor):**

- 14.4.4

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox
 - 92.0.1

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
