### ISSUE TITLE
Locked Layer no longer prevents changes to them when dragging an item from another layer

### ISSUE THREAD

**Issue by ac-arconomy** [jgraph/drawio#2316]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

From the diagrams.net documenation; (https://www.diagrams.net/doc/layers) "Locking a layer means you cannot make any changes to it - you can’t add, move, edit, stye or delete the shapes and connectors placed on that layer."

When dragging a shape X that is on Layer A and placing it on top of a locked layer B, I expect the shape to remain on Layer A and not connect to anything in the locked Layer B. The issue is that shape X is now added to Layer B and connects to lines and other shapes in Layer B. This causes havoc with my diagrams as I use layers extensively to add annotations or background shapes and then overlay with another layer detailed shapes of the diagram.

**To Reproduce**
1. Create Layer A and add a line and swimlane table to it.
2. Create Layer B and add a square shape to it
3. Lock Layer A
4. Select Layer B and drag the square shape over the line and swimlane table
5. The square shape is connected to the line and added to Layer A within the swimlane table

**Expected behavior**

The sqaure should not be connected to the line or added to the swimlane table in Layer A

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 15.5.1

**Desktop (please complete the following information):**
 - OS: MacOS BigSur 11.6
 - Browser: chrome 
 - Version: Version 94.0.4606.71 (Official Build) (x86_64)

**Additional context**
These seems to have been introduced in a recent version as this functionality worked as described in the documentation up until the last few months.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by ac-arconomy** [comment]
Great stuff - keep up the good work.
Many thanks
Ac
Alistair Cornish
Managing Director
m: 0447 407 159
