### ISSUE TITLE
Custom shape library - issue with shape scale

### ISSUE THREAD

**Issue by clare171** [jgraph/drawio#2322]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I am creating a custom library in Draw.io desktop version using SVG files that I have exported from Adobe Illustrator. The issue that I have is that Draw.io does not retain the scale of the shape once it is imported into the custom library. When I check the dimensions in the code of the library the dimensions are correct but the file scale is wrong when inserted into a new blank drawing.

**To Reproduce**

**Expected behavior**

**Screenshots**
The process I use is:
![image](https://user-images.githubusercontent.com/30987734/137475620-22801b39-7519-4a6a-b66a-ff27485a4aca.png)

Then:
 ![image](https://user-images.githubusercontent.com/30987734/137484831-4cc99db8-9a6b-4a27-b2e7-04a11a965755.png)

Then I Import the SVG file into Draw.io (desktop version):
 ![image](https://user-images.githubusercontent.com/30987734/137484892-d86ad102-123b-449e-a3d8-40f4655ecf22.png)

The dimensions of the shape should be 71.8mm x 45mm but when I add the shape to a drawing it is 51.8mm x 33.3mm.
 ![image](https://user-images.githubusercontent.com/30987734/137485045-e0003d0e-a6ad-4ca9-a367-ff50f8bb2b14.png)

Ideally, I need the shapes to be in scale to each other and I am struggling to work out why there is a discrepancy.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 15.3.5 - desktop version

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro version: 21H1

**Additional context**
When I check the dimensions in the code, the "w" and "h" are correct based on pixel size, but still present incorrectly when used in a new blank drawing.
![image](https://user-images.githubusercontent.com/30987734/137486269-45a96aab-d459-49a2-bebd-fdf076159f03.png)

**Comment by davidjgraph** [comment]
Can you attach an example SVG shape that we can re-produce this behaviour with please?
