### ISSUE TITLE
Too many permission required by draw.io viewer when authorized with Google Drive

### ISSUE THREAD

**Issue by tailaiw** [jgraph/drawio#2323]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When I use draw.io with Google Drive, it only asks for permission to files/directories created by the app. However, when I use draw.io viewer, it asks for access to all my files in the drive.

**Describe the solution you'd like**
Draw.io viewer should ask no more permission than draw.io.

**Comment by davidjgraph** [comment]
There is no other way to do this.
