### ISSUE TITLE
Possible export by selected image size bug? Export results a selected image with document/paper's size (ver. 15.5.4)

### ISSUE THREAD

**Issue by DWSuryo** [jgraph/drawio#2324]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Title. I'm trying to export the image I selected with the that image resolution. Usually, the exported image has the size of the selected image. Now, when I export, the resolution is with the document's size as well. 

**To Reproduce**
I recorded a video to reproduce the behavior

https://user-images.githubusercontent.com/72719372/137618667-7b384c4c-4f2c-481e-b4ad-42212d97c82a.mp4

1. Export selected images by dragging
2. Click File > Export as > PNG (or other formats)
3. Choose "selected image" checkbox or in selection bar
4. Click export
5. Click at the preview (opens new tab) and see if there's a problem

**Expected behavior**
The size and resolution is from the selected images

**Screenshots**

![Untitled Diagram drawio (2)](https://user-images.githubusercontent.com/72719372/137619201-fc8e5d4f-994f-4ae8-b749-dfa2ad7e2cdb.png)

![Untitled Diagram drawio](https://user-images.githubusercontent.com/72719372/137619065-e963ecc9-7287-4cf2-bfcc-ae4d7a041ccf.png)

![Untitled Diagram drawio (1)](https://user-images.githubusercontent.com/72719372/137619071-49bad038-957e-44ad-8a96-afa1bcc8b87b.png)

**draw.io version 15.5.4**

**Desktop (please complete the following information):**
 - OS: Windows 10 20H1
 - Browser: Chrome 94

**Additional context**
- Chrome plugins: mendeley web importer, zotero connector, HTTPS everywhere, UBlock origin
- The recording is in incognito mode (not logged in), However, this also applies when I logged in with Google Drive
- Have cleared cache and data from draw.io and diagrams.net
- Have tried on Firefox. Same issue as Chrome

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by DWSuryo** [comment]
tried it on 15.5.5. now it worked, thanks
