### ISSUE TITLE
Replacing rectangle with data parallelogram leaves the rectangle behind

### ISSUE THREAD

**Issue by sanketksinha** [jgraph/drawio#2325]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Replacing the rectangle with the data parallelogram leaves the rectangle behind.  The rectangle needs to be manually deleted. 

**To Reproduce**
1. Draw a rectangle
2. Replace it with a parallelogram by dragging the parallelogram from the library
3. Rectangle is left behind along with the parallelogram
4. It needs to be deleted manually. 

**Expected behavior**
Only the parallelogram should remain 

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]
- version 15.4.0

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Laptop
 - OS: Windows 11
 - Browser: NA (using desktop version)
 - Version: NA

**Additional context**

**Comment by mararad** [comment]
Hi,

Could you update diagrams.net to the latest 15.5.5? I see you are using 15.4.0 and then replace a shape following these instructions: https://www.diagrams.net/doc/faq/replace-shapes

or select rectangle and Shift+click a parallelogram in General library.

Regards,
