### ISSUE TITLE
Opening file from OneDrive->Sharepoint appears empty

### ISSUE THREAD

**Issue by tulgaadai** [jgraph/drawio#2327]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

When Opening existing file on Sharepoint Site Documents the directory shows empty.

**To Reproduce**
1. Go to 'File'
2. Click on 'Open from' ->OneDrive->Sharepoint
3. Select Site and Folder
4. Error is -> The folder appears empty

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/59754443/137678649-df727c2c-ca38-413c-a316-a61f698bd902.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version :15.4.1

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: Last

**Additional context**

**Comment by Ozzian** [comment]
Exactly the same problem here :(

**Comment by Ozzian** [comment]
Just found out that you cannot even save to the sharepoint folders :(

**Comment by NikPiermafrost** [comment]
Same problem:
DrawIo version 16.5.4
OS: windows 10
Browser: google chrome (98.0.4758.82)
It appears that clicking on refresh, this happens:

![image](https://user-images.githubusercontent.com/59047765/153424560-e2a1c3ed-84e6-4a70-9fe2-69471f328b6d.png)

It happens recursively as the refresh button is clicked. Root onedrive folder works fine
