### ISSUE TITLE
Better scaling/units support

### ISSUE THREAD

**Issue by jethrogb** [jgraph/drawio#2333]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

It would be great to have better support for drawing at scale, i.e. where the thing your drawing is not in reality the same size as the printed diagram. For example, for floorplans a 1:100 scale would be useful. The combination of units, page scale, page size, and minimum zoom out level that exists right now doesn't offer a good experience. From the [diagrams.net blog](https://www.diagrams.net/blog/floorplans):

> Each part of a floorplan is normally drawn to scale

But when looking at the diagrams in that blog it appears they are not drawn to scale at all.

I haven't thought this all the way through but I think the following things would be needed:

* Specify size and units of the drawing. This would allow defining the actual drawing area and normal zoom level in a manner appropriate to what's being drawn.
* To be able to print a drawing, you'd also need to know how to layout the drawing on pages. For this, you need to:
  * Specify a scale
  * Specify size and units of the page

**Comment by jroachgit** [comment]
> Way to go!

I just started a discussion about this.
