### ISSUE TITLE
Unable to change the color of mxgraph.aws3d.dashedArrowlessEdge

### ISSUE THREAD

**Issue by rkesters** [jgraph/drawio#2334]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The color of mxgraph.aws3d.dashedArrowlessEdge is aways blue no matter what the value of strokeColor is set to. 

**To Reproduce**
1. Using the AWS 3D shapes, added a mxgraph.aws3d.dashedArrowlessEdge
2. Using the Format Panel change the Line color to black

**Expected behavior**
Color of Line changes to black

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- diagrams.net 15.4.0

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: App
 - Version 

**Additional context**

**Comment by rkesters** [comment]
The offending code appears to be 
https://github.com/jgraph/drawio/blob/d76e39477bdf230ba6728dc488bd5896afb08425/src/main/webapp/shapes/mxAWS3D.js#L350

**Comment by egrimate** [comment]
Done. Should be in the latest release.
