### ISSUE TITLE
Re-Use Confluence content in a DrawIO image

### ISSUE THREAD

**Issue by SarahBYK** [jgraph/drawio#2335]
* [y] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [y] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Is there any kind of possibility to connect a confluence text like for e.g. a servername with a created DrawIO image?
Means can I reuse content from my conflunce page directly in a manual created image?
So that if the servername will change in the future, the name in the DrawIO Image will change in the same way (re-use content)?

**Describe the solution you'd like**
Please make possible that re-using content from confluence is also possible in a DrawIO image

**Describe alternatives you've considered**
Not aware

**Additional context**
-

**Comment by SarahBYK** [comment]
It's cloud

**Comment by davidjgraph** [comment]
We've looked into this, but it's too technically complex to implement in a reasonable time. Thanks for your input.
