### ISSUE TITLE
AWS Stencils Become Brighter Than Before

### ISSUE THREAD

**Issue by silver886** [jgraph/drawio#2336]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Before 14.9.9, which is the latest update related to AWS stencils update, the stencils was for light background.
After the update, the stencils replaced to the one for bark background.

**To Reproduce**
1. Go to 'Search Shapes'
2. Search for any AWS resource stencils
3. Click the stencil

**Expected behavior**
Maintain the original stencils set with light background.

**Screenshots**
![image](https://user-images.githubusercontent.com/11664880/138285928-5623b823-7bb4-4060-9b1c-51a2cafffd32.png)
![image](https://user-images.githubusercontent.com/11664880/138286050-b5fbada8-b84d-41e7-9613-c554e826c955.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: After (including) 14.9.9

**Desktop (please complete the following information):**
 - OS: Windows and macOS
 - Browser: Firefox and Chrome

**Additional context**
AWS provides 2 sets of stencils, one for light background and the other for dark background.
![image](https://user-images.githubusercontent.com/11664880/138287490-860bd9cc-5ded-4a92-8677-bb0e2bbc8409.png)
Having a consistency in draw.io would be great because lots of diagrams are created before 14.9.9.

> Edit (10/28): Update inline typo.

**Comment by egrimate** [comment]
Will be fixed in next release
