### ISSUE TITLE
Stuck at 'authorize' (google)

### ISSUE THREAD

**Issue by chaydgc** [jgraph/drawio#2337]
Hello,  I've authorized draw.io in my google account, but remain unable to get past the 'authorize' button in the first drawing I created on line. Nothing happens when I click it. I am using os 11.6 and firefox 92.0.1, and have also tried safari. Appreciate any guidance.

**Comment by chaydgc** [comment]
Thank you for the tip. Unfortunately it didn’t resolve the issue.

**Comment by chaydgc** [comment]
I recognize there must be ‘a number of client side reasons that can cause auth failure’. I’m trying to isolate and address the one or ones that are at play in my situation. Again, I am using the most recent version of firefox, and have tried disabling ad blockers, the firefox shield, and now privacy badger, to no avail. I am using the default setup. Thank you for any suggestions you may have.

**Comment by davidjgraph** [comment]
Does it work in a Firefox private window?

**Comment by chaydgc** [comment]
no
