### ISSUE TITLE
Fails to save into Sharepoint via OneDrive integration

### ISSUE THREAD

**Issue by fmjrey** [jgraph/drawio#234]
The OneDrive integration works well, though it fails when selecting a Sharepoint location, even if you have write access to it. Error message: `The resource could not be found`.
As a user, since I'm presented with such choice of location, I would expect this to work transparently. In other words it's a bug/issue, and I'm challenging the fact it's recorded as a new feature in trello: https://trello.com/c/jp44eYsc
Thanks

**Comment by davidjgraph** [comment]
The problem is that the OneDrive API didn't support Sharepoint last time we checked. We're not going to write a custom integration, we expect Microsoft to fix this (maybe they have since we last checked, I don't know).

There's one vote on the issue, be it a bug or feature request, there's not enough interest to be scheduled at this point.

**Comment by fmjrey** [comment]
Hi @davidjgraph 
Closing this ticket certainly makes your board cleaner, I can understand that, but how do you not forget that such integration does not work?
Even if it is for MS to fix (no it still does not work), this ticked can be used to track discussions with MS and capture links to upstream tickets.
Finally closing it prevents any further voting, so it's kind of saying this issue does not exist, it's not our problem.
However from a user point of view it does exist. The workaround suggested in [the help article|https://desk.draw.io/support/solutions/articles/16000070479-how-to-use-draw-io-with-onedrive-and-sharepoint] does not work.

**Comment by davidjgraph** [comment]
Sharepoint integration fixed in 9.2.9

**Comment by tomoveu** [comment]
Today we added drawio as add-ins to our Office365 for Business and it fails with error, when trying to access sharepoint files. Would you happen to have any hints?
