### ISSUE TITLE
c4Model container shape names are uneditable

### ISSUE THREAD

**Issue by cushyno** [jgraph/drawio#2345]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
C4 Model shapes permit editing of name, description and technology via shape data.  The source sidebar code at https://github.com/jgraph/drawio/blob/19bd7cb931a8b43796d9c545c5bf24fb510b9364/src/main/webapp/js/diagramly/sidebar/Sidebar-C4.js shows the basic container to correctly use editable c4Name, c4Description, c4Technology fields, with c4Type being non-editable.  However, other container types (data, microservice, message bus, web browser) each are lacking a c4Name field and use the c4Type field in the label in place of the name.  As c4Type is non-editable it is not possible to modify what is displayed by the label.  Each of the problematic shapes also uses a c4Container data field that is not present in the basic container.
Unless I misunderstand, I believe the specialised Containers are incorrect.
 
**To Reproduce**
1. Go to 'c4 Shapes in sidebar'
2. Click on 'data container' to add to diagram
3. Double-click to edit the display fields (and hence update the display label)
4. See error - c4Type used as display label non-editable.  Compare this to behaviour and label construction for the basic container shape.

**Expected behavior**
Data, microservice, message bus, and web browser containers should exhibit same fields and display label format as basic container.

**draw.io version (In the Help->About menu of the draw.io editor):**
- 15.5.8

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10
 - Browser: Chrome & Edge Chromium
 - Versions: Chrome 95.0.4638.54 (Official Build) (64-bit), Edge 94.0.992.50 (Official build) (64-bit)

**Comment by ndaidong** [comment]
@davidjgraph please check if my pr #2384 helps to resolve this issue. Thanks.

**Comment by cushyno** [comment]
@ndaidong I have taken a quick look at your commit.  The changes appear to meet requirements.
Looking forward to seeing the change in next release.
Thank you.

**Comment by egrimate** [comment]
Will be in next release

**Comment by Philzen** [comment]
Just bumped into this as well and was about to open an issue for it, when i found your fix @ndaidong. Now i have cloned the repo, went into `src/main/webapp`, ran `pnpm install` and `npmn run start`, only to see the issue still persists in there. Also on https://jgraph.github.io/drawio/src/main/webapp/index.html, which runs v16.5.3 (which was released three days after the fix was supposedly merged).

Can anyone advise?

**Comment by ndaidong** [comment]
@Philzen I had no chance to use drawio since that time. It seems this issue  is still happening with the current version. Not sure if my fix didn't work or something was wrong in the release process. @egrimate or other maintainer may have the answer for us.

**Comment by Philzen** [comment]
@ndaidong Although your fix commit from November was finally merged 6 days ago, it doesn't show up in the commit history, and the [file still shows as unfixed in the default branch](https://github.com/nithinprasad/drawio/blob/dev/src/main/webapp/js/diagramly/sidebar/Sidebar-C4.js). So i guess your fix is fine – but i'm rather confused where it disappeared to.
