### ISSUE TITLE
Smooth zooming? (rather than incremental)

### ISSUE THREAD

**Issue by deanfra** [jgraph/drawio#2347]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

I'm a long term user of draw.io and regard it as an excellent tool. 

The only thing that would drive me to create an Issue is the zooming. Yes I am on a Mac and it still feels very fast even on the latest version, but I noticed that zooming seems to work in large staggered increments, such as 10%,25%,40% etc. 

For example, when I pinch zoom, the display wont update until my zooming reaches a certain threshold. If I pinch zoom even the slightest I should see the display port zoom ever so slightly as well.

This might be really tricky with the framework, but a sense of acceleration and easing of the zoom would make everything feel so natural. 

I think there are a few JS libraries out there that support mouse wheel tracking and easing. You could also add a mouse wheel sensitivity setting because it looks like different operating systems have vastly different default sensitivities.

**Comment by davidjgraph** [comment]
This just isn't possible using SVG DOM.
