### ISSUE TITLE
Text is printed with wrong colors

### ISSUE THREAD

**Issue by conradoplg** [jgraph/drawio#235]
draw.io 8.4.8 installed from .deb
Ubuntu 16.04.4 LTS

* Create a blank diagram
* Add a rectangle, set background color to blue and text to white
* Type any text in the rectangle
* Print with "Print to file"

The text will be gray in the resulting PDF.

**Comment by codemonkey1337** [comment]
I have the same problem with Chrome on Windows 10. I think it is the browser that is changing the colors, but I haven't found a workaround yet. Anyone that can tell us how to get around this problem?

**Comment by alderg** [comment]
This is probably a feature, not a bug. Workaround: Tick "Background graphics" under More settings, Options in Chrome's print dialog.

**Comment by alderg** [comment]
I'm guessing they are trying to avoid white text on white background.

**Comment by conradoplg** [comment]
I understand why Chrome does this. I don't understand why draw.io does not prevent it from happening.

**Comment by alderg** [comment]
Printing is implemented in the browser, not draw.io. I'm looking at this workaround, but it doesn't seem to solve the problem.

**Comment by alderg** [comment]
Ah yes, that link helped. This will be fixed in the next release. Thanks again!

**Comment by conradoplg** [comment]
Great, thanks!
