### ISSUE TITLE
Link of the .png file as a reference next to the migrated diagram

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#2352]
"When draw.io diagram is created, there are 2 attachments created in the page. The one of draw.io format while the second one is a .png file. 
I wonder if there is an option to plant a link to the first version of the .png file under the migrated diagram (which is basically the snapshot of the diagram that we can use as a reference to Lucid diagram as it was before the migration).
It will help the system engineers to use this link as a reference to the diagram before the migration.

Do you think it is possible?"

Asked in DID-3586

**Comment by davidjgraph** [comment]
Declined. Lucidchart mass importer is now deprecated.
