### ISSUE TITLE
Improve resolution on Expand/collapse toggle icons

### ISSUE THREAD

**Issue by ShamanthMurali** [jgraph/drawio#2359]
* [ ] I agree to follow the that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**describe.**
The icon image used for expand / collapse shape toggle button on advanced shapes are of a lower resolution. It really shows up when zoomed

**Describe the solution you'd like**
Replace with higher resolution files.

**Additional context**
![image](https://user-images.githubusercontent.com/71114618/139259602-1c4c6a6c-2c66-47b4-8672-1e9c70f111c7.png)
![image](https://user-images.githubusercontent.com/71114618/139259513-e02378e3-58f6-4598-a831-cc6ddd60be3b.png)

**Comment by alderg** [comment]
This will be fixed in the next release.
