### ISSUE TITLE
crashing on save or load on google chrome from a windows 10 pc

### ISSUE THREAD

**Issue by gmwalkermtu** [jgraph/drawio#2361]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
any saving of a file to a windows 10 computer using google chrome, or opening a .drawio file on a windwos 10 computer using chrome will cause chrome to crash

**To Reproduce**
1. make a file
2. try to save as
3. save as to machine
4. input name

1. open draw.io
2. click create new diagram
3. choose a diagram type
4. input a name and location to save

**Expected behavior**
it to either load the file or save it to my computer

**Screenshots**
cant screenshot chrome crashing

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 15.6.2]

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome]
 - Version [Version 95.0.4638.54 (Official Build) (64-bit)]

**Additional context**
it seems that saving and load from google drive does not cause this issue.

downloading the file without using save to device will not cause a crash.

**Comment by richardtallent** [comment]
I'm experiencing the same issue, found this via Google.

Using Chrome 95.0.4638.69 on OS X, attempting to create a new diagram using "https://draw.io". Chrome crashes when I choose to save the new drawing from the file dialog.

**Comment by alderg** [comment]
What version of macOS?

**Comment by davidjgraph** [comment]
Does this still happen on 15.8.4? If yes, any errors in console?

**Comment by DaKeiser** [comment]
I am using 
- draw.io Version 16.5.5
- Chrome Version 95.0.4638.69
- Parrot OS 4.11 
and this issue has been happening for the past few months. Is there any workaround? However, I am able to work on Firefox on the same OS. So I guess it's some issue with Chrome.
