### ISSUE TITLE
how to create a regular hexagon?

### ISSUE THREAD

**Issue by woosley** [jgraph/drawio#2363]
I am now stuck to create a regular hexagon. 
by default, what is created is like below
 
![image](https://user-images.githubusercontent.com/61531/139384318-59f1d105-2d46-4e60-8b3e-320a8541c3d5.png)
but how can I make it as a "regular hexagon"? I can not find any way t odo this

**Comment by mararad** [comment]
Our engineer created the issue you can track https://github.com/jgraph/drawio/issues/2368

Regards,

**Comment by sehalwas** [comment]
I still don't know how to so it.

**Comment by iskanred** [comment]
+
