### ISSUE TITLE
Fit Page to Diagram Option

### ISSUE THREAD

**Issue by nplusplus** [jgraph/drawio#2366]
I would like to request implementation of a "fit page to diagram" feature in the page setup dialogue.  I believe it should likely include a specification for a modifiable default margin, and the intent would be to automatically determine a custom page size from all deployed diagram elements at the time the feature is executed such that the page size is automatically resized to fit the diagram with the configured margin between the "outer" edges of the diagram elements and the edge of the page.

Thank you,
Nathan

**Comment by mararad** [comment]
Hi,

would you like to have "fit page to diagram" option in order to export the diagram only? 
Or you would like to have this possibility so you can view only diagram in the editor (without surrounding canvas)?

Regards,

**Comment by nplusplus** [comment]
Hello,

I would like to have the "fit page to diagram" for the following two cases.

1) To export the diagram.  This seems the feature most impacted or eased by
this change.
2) To view the diagram with minimal canvas/background in the editor.  This
enhances the convenience of creating diagrams that fit the
canvas/background in the editor such that I would not have to resize my
diagram to fit on a particular page dimension.

To clarify, when I refer to the "page", I am referring to the default
background with gridlines that appears as if it is a "paper" page.
Currently, when I want this appearance, I go to the page setup dialogue,
and sort of fumble through different custom page sizes until I figure out
what it needs to be to just barely extend beyond the edges of my diagrams.

Thank you,
Nathan

**Comment by mararad** [comment]
Thanks Nathan.

1. When exporting, there is the possibility to choose to export diagram only
2. "To view the diagram with minimal canvas/background in the editor." - this is something we don't support at the moment

Regards,

**Comment by nplusplus** [comment]
Hi,

>
>    1. When exporting, there is the possibility to choose to export
>    diagram only - *I do not see this option.  When I export to PDF for
>    instance, if the diagram extends beyond the edges of the current page size,
>    I end up with multiple pages of partial diagram.  If I set the page size to
>    be larger than the diagram, then I have to do additional work to make it
>    fit "neatly" on the page.  Can you advise how I might use the feature you
>    are indicating from the web client (i.e. @ diagrams.net
>    <http://diagrams.net>)?*
>    2. "To view the diagram with minimal canvas/background in the editor."
>    - this is something we don't support at the moment - *I thought I was
>    making a request to implement a new feature.*
>
> Thank you,
Nathan

**Comment by itdependsnetworks** [comment]
For future users that stumble across this, for my use case, I was able to set the custom page height and page width to 1, 1 on the paper size:

<img width="234" alt="Image" src="https://github.com/user-attachments/assets/3047bc8e-92fc-4bc1-9f9a-7eae61ca8a0a" />

XML: 

```xml
<mxGraphModel pageScale="1" pageWidth="1" pageHeight="1">
```

This is effectively setting the page to the size of the diagram.
