### ISSUE TITLE
Google Font, Web Font missing while using the page as a background

### ISSUE THREAD

**Issue by Toliak** [jgraph/drawio#2367]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I'm trying to use the page A as a background of another one (B). 
The page A has a text :
- with Web font, 
- with Google font, 
- with System font and 
- with internal font.

If I use Page A as a background of the page B, Google font and Web Url font fails (displays another font).

**To Reproduce**
1. Create a text with a Google Font (important: the Google Font you are using should not be installed on your computer)
2. See the font is correctly applied
3. Create another page
4. Use the first page (with the text) as a background
5. See another font

**Expected behavior**
Expected correct font display of the background page text.

**Screenshots**

Page A and B side-by-side
![image](https://user-images.githubusercontent.com/25643405/139590864-6b0b3490-8017-4076-bb98-e83bd0997580.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 15.6.3

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - Browser: Google Chrome Version 94.0.4606.81 (Official Build) (64-bit)

**Additional context**

[File to reproduce the error](https://gist.githubusercontent.com/Toliak/6ee1e7775cee2e7631b0bfde8b00ba3f/raw/ff9e6e978fbe0e06218d8741e0a2205bf81f913a/issue.drawio)

**Comment by mararad** [comment]
Reproduced in:
* Chrome Version 95.0.4638.54 (Official Build) (64-bit)
* Firefox 93.0 (64-bit)
* Win 10 and diagrams.net 15.6.3

**Comment by davidjgraph** [comment]
This is a known issue.

**Comment by davidjgraph** [comment]
Fix in 24.0.3
