### ISSUE TITLE
Make existing Jira issues available within Draw.io Board

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#2372]
"Do you as well plan the functionality to make existing jira issues available within Draw.io Board?
The usecase to add a bunch of Jira-Tickets from an filter and then be able to sort / cluster / annotate them within Draw.io Board?"

Asked in DID-3625

**Comment by cr0n76** [comment]
If I understand correctly something like that is depicteted for a similiar app in the video here: https://marketplace.atlassian.com/apps/1223211/whiteboards-for-jira-team-collaboration?tab=overview&hosting=cloud (starting at about 0:48) - if you want some visual depitction.

**Comment by pmigneault** [comment]
1) Selecting a field from a particular issue in jira (with a particular ticket number or a key) and show the value with realtime update: 
 - Have the possibility to display the value with different font, font size, color or attribute (underline, bold, italic, bar).
 - Conditionnal display with a "if" : change color for value greater than a certain value or display a message
 - Hide something in draw.io (an arrow or a square for exemple) depending of value 
2) Display a table from a JQL, let the people choose the header of the colum or cell color
3) Graphical representation (pie chart, colum, dots, etc.)
4) The possibilty to freeze the diagram with the current value (so we can compare the evolution each week for exemple)
5) In all draw.io mode

**Comment by pmigneault** [comment]
- Display a particular jira comment (with the direct url from Jira)
- Basic mathematical operation (sum, divid, multi, square, etc) for a value, the sum of value of different issue or the number of issue from a jql query.

**Comment by davidjgraph** [comment]
Thanks for your interest in this issue. Having review the request we've determined that this is excessively complex to implement due to the need to connect authenication between the confluence and jira instance.

We understand this is disappointing, please understand that we did look through all possible technical implementation and none of them are possible within reasonable constraints.
