### ISSUE TITLE
Several copies of the same image in a diagram should not take more memory

### ISSUE THREAD

**Issue by laclouis5** [jgraph/drawio#2373]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I usually create diagrams which contains the same image repeated multiple times with different overlays (for instance to describe an image processing pipeline). This results in slowdown (especially during the document saving which freezes the interface) and makes the file huge (either the .drawio and the .pdf file created from it).

**Describe the solution you'd like**
This would be very efficient to avoid duplicating the image data when multiple instances of the same image are present (copying would act as a reference rather than a value).

**Describe alternatives you've considered**
I usually use PowerPoint of Keynote for such cases as they support this behavior : copying an image a lot of times does not results in a heavier file or PDF file.

**Additional context**
Simple example to highlight the issue : include an image in a blank diagram, copy-past it a dozen times. The file size should not be a multiple of the image size.

**Comment by mararad** [comment]
Hi,

as a workaround you might want to try uploading an image to e.g. Imgur, add its URL to the diagrams.net editor via "+" > Image and then copy/duplicate image (Ctrl+d) 
File size should be smaller and saving shouldn't be the issue.

Does this help?

Regards,

**Comment by laclouis5** [comment]
Thanks for this workaround, I'll try it soon.

**Comment by laclouis5** [comment]
This workaround works great, the `.drawio` file is really small since the images are not stored in the file, and it produces a PDF file size does not increase anymore with the number of duplicate images.
