### ISSUE TITLE
Text auto-adds fill and outline after drag-and-drop

### ISSUE THREAD

**Issue by stasmihailov** [jgraph/drawio#2376]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
If I drag a Rectangle and a Text, and then drag another rectangle, then the text gets same style (fill + line) as the first rectangle, but only if it has default style (white fill + white line). The workaround is to apply change style of a rectangle - e.g. change its line colour to `#010101` AND fill colour to `#FEFEFE` - that way the text doesn't change its style on drag. Also, you could set this new style as default - that way, you would not encounter this problem in current sheet, as all new shapes will use that style. But still, though, its quite annoying, esp. when there are a lot of block+text pairs which I drag around, and you would have to apply this style over all of your diagrams

**To Reproduce**
1. create a white rectangle "1"
2. create text "1"
    - at this point, text has no fill or line
3. create a white rectangle "2"
4. drag rectangle "1" and text "1" together
5. drag rectangle "2"
    - now, text "1" has fill + line

**Expected behavior**
I would've expected text to not change its style after dragging

**Screenshots**
![Nov-03-2021 3-32-21 PM](https://user-images.githubusercontent.com/13658407/140061612-c7be0f90-3d04-42ef-a622-d730cfc53482.gif)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version [e.g. 15.6.5]

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.0.1
 - Browser Safari
 - Version 15.1

**Comment by stasmihailov** [comment]
Also, if you only change e.g. fill of a Rectangle, but forget to change line colour, then the bug will reproduce, but the text will only get an outline, not the fill, since we changed it in a Rectangle before

**Comment by davidjgraph** [comment]
Try 15.6.8

**Comment by stasmihailov** [comment]
Yep, fixed in 15.6.8. Thanks!
