### ISSUE TITLE
Cell stretch on Left and top cells not working

### ISSUE THREAD

**Issue by ShamanthMurali** [jgraph/drawio#2382]
**Describe the bug**
The ability stretch cells or increase width is
Working here
![2021-11-04 21-12-36](https://user-images.githubusercontent.com/71114618/140296766-c2d7b086-28ae-4868-b730-72f77cc43731.gif)
Working here
![2021-11-04 21-12-45](https://user-images.githubusercontent.com/71114618/140296914-8cceddd4-44fd-49dc-80b7-913cdc2b1790.gif)
Working here
![2021-11-04 21-12-52](https://user-images.githubusercontent.com/71114618/140296966-67e9be08-539a-4c80-ade5-513ed51719fa.gif)
NOT WORKING HERE
![2021-11-04 21-12-58](https://user-images.githubusercontent.com/71114618/140296984-bf1a1fb9-f930-45f5-b204-21ae637f18f7.gif)
NOT WORKING HERE
![2021-11-04 21-13-12](https://user-images.githubusercontent.com/71114618/140297003-efeced4a-71d5-4dea-8982-64eec11a4a39.gif)

![image](https://user-images.githubusercontent.com/71114618/140297346-1205a560-f0fb-4f5e-8eaf-31fcfdc24ccf.png)

**Comment by mararad** [comment]
Reproduced in online 15.6.8 in Chrome 95.0.4638.69 and FF.
Also in desktop version 15.4.0
Win 10

**Comment by ShamanthMurali** [comment]
@davidjgraph This issue still seems to exist. Do you also have it or its just my computer?
