### ISSUE TITLE
Multiple selection edit of "Connectable" option is missing

### ISSUE THREAD

**Issue by floongle** [jgraph/drawio#2383]
Hi,

When selecting multiple objects that all share the same "Connectable" / "Allow Arrows" state, these settings are not presented for group editing.

# Steps to reproduce
1. Create two or more rectangles
2. Select all of them
3. Expand the Property/Value list in the right hand side toolbar

**Expected:**
 The "Connectable"  option should be present

**Actual**
The "Connectable" option are missing.

As such, if you have a large number of object that need to have this option changed, it must be done manually for each object.

# Versions, etc.
- draw.io version 15.4.0
- Desktop app
- OS Windows 10

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
