### ISSUE TITLE
it doesn't work on Opera Browser

### ISSUE THREAD

**Issue by aliafshany** [jgraph/drawio#2387]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**
when you click on the extension icon

**Expected behavior**
it does not work on Opera browser.

**Screenshots**
![image](https://user-images.githubusercontent.com/40741745/140537845-dddc6e1a-da55-40b2-9413-1e8b4b500b66.png)
**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 1.0.4

**Desktop (please complete the following information):**
 - OS: mac os
 - Browser Opera
 - Version:80.0.4170.72 (x86_64)

**Comment by alderg** [comment]
Works for me in Opera 81.0.4196.31 (arm64) on macOS 12.0.1 (21A559).

**Comment by aliafshany** [comment]
then what is wrong with my system.
my specs are the same as yours.

may be it is because of Adguard

**Comment by aliafshany** [comment]
yes
it was because of Adguard.
gotta send a bug report for them to fix it.

**Comment by alderg** [comment]
Thanks for letting us know. I'll close this.
