### ISSUE TITLE
Pan canvas using trackpad

### ISSUE THREAD

**Issue by dabure** [jgraph/drawio#2388]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When using the trackpad on my Mac, I can only navigate my way around the diagram vertically OR horizontally when using the trackpad's two-finger gesture to pan the canvas.

**Describe the solution you'd like**
I would like to be able to navigate vertically AND horizontally at the same time (i.e., navigate in whichever direction including diagonally, or just between north and northeast; not just up or down), much like I can pan around the canvas when using the shortcut "Space + drag".

**Describe alternatives you've considered**
"Space + drag" works to accomplish what I need. However, it would be more intuitive to use MacOS's "default" trackpad way of navigating.

**Additional context**
Nothing to add.

**Comment by davidjgraph** [comment]
Declined

**Comment by charleshan** [comment]
Scrolling/Panning diagonally feels broken on a trackpad. Being able to do this is a necessity in 2022. For inspiration, check out Whimsical, Figma, etc.

I'm curious, do you use a mouse @davidjgraph?

**Comment by spasm** [comment]
It's a bummer this feature doesn't receive more consideration.  It really does introduce a more polished experience to navigating around the canvas with a trackpad.

**Comment by alderg** [comment]
The is completely controlled by the browser. If there is no CSS setting to control it, then there is no way to fix this.

**Comment by davidburesund** [comment]
True. However, given that apps like Lucidchart support this (which is browser-based), then shouldn't there be a way to do this in the most popular browsers?

**Comment by spasm** [comment]
Interestingly enough, the pan behavior feels great in Firefox (v98, macOS.)  It appears to only feel off in chromium-based browsers (and thus, the desktop client is affected.)

**Comment by YGolikov** [comment]
Are there any updates on this issue?
I have the same problem. For example in miro you can scroll diagonally by default without having to clamp any keys

**Comment by davidjgraph** [comment]
We'll reopen if someone provides the technical explaination of how to implement it, or is a paying user in confluence and requests it.

**Comment by hariacharya80** [comment]
!unstale

**Comment by hariacharya80** [comment]
@davidjgraph @dabure  I think @minkyu97 has come up with a idea on issue #4538. Please have a look at it and take necessary action or we could discuss this furthermore.
