### ISSUE TITLE
Please redraw moved shape before arrow keys are released

### ISSUE THREAD

**Issue by Chealer** [jgraph/drawio#239]
A selected shape can be moved by pressing the up, right, down or left arrow keys. Achieving significant moves requires pressing several times, or keeping the key pressed for some time. Unfortunately, if one keeps an arrow key pressed for some time, the shape is only redrawn once initially and then when the key is released, which makes it hard to gauge when the key should be released.

This behavior is seen in Google Chrome 65. I suggest redrawing the shape at least each second.

**Comment by davidjgraph** [comment]
The redraw performance would be a problem if it happened straight away, a pause is needed.

**Comment by ebousse** [comment]
What about showing only a moving "ghost" version of the shape, instead of triggering a complete redraw? Or redrawing every few frames, instead of every frame? (Just being curious)

**Comment by Chealer** [comment]
I reported this issue in ticket #1146, whose title is less misleading.
