### ISSUE TITLE
On Ubuntu Shapes act as if locked i.e. cannot move or resize

### ISSUE THREAD

**Issue by SuheylZ** [jgraph/drawio#2392]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
On Ubuntu using chrome browser, the shapes don't move or resize as if they are locked. 
- checked using the incognito mode
- checked using the freshly installed browser
- checked while signed in to an account 

**To Reproduce**
1. Open draw.io in chrome
2. Click on any shape and place on canvas
3. Try to move or resize
4. Shape behaves as if locked.

**Expected behavior**
Shapes should be able to be resized or moved until locked. 

**Screenshots**
None

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [15.7.0]

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10
 - Browser: Chrome (build: 95.0.4638.69 (Official Build)  64-bit)

**Smartphone (please complete the following information):**

**Not applicable**
 - Device: 
 - OS: 
 - Browser
 - Version 

**Additional context**
None

**Comment by mararad** [comment]
Hi,

Is this working in other browsers?
Is it unlocked under Edit > Lock/Unlock
When you select a shape, is Movable ticked under Properties/Values on the right?

Regards,

**Comment by davidjgraph** [comment]
You have a native Ubuntu, i.e. not a VM?

**Comment by davidjgraph** [comment]
Is this a touch device?

**Comment by SuheylZ** [comment]
No it's not a touch device. It's a regular laptop. Dell X3 but that shouldn't matter or should it?

**Comment by SuheylZ** [comment]
> Hi,
> 
> Is this working in other browsers? Is it unlocked under Edit > Lock/Unlock When you select a shape, is Movable ticked under Properties/Values on the right?
> 
> Regards,

Yes i checked it on windows on VM and there is working just fine. I checked this behavior on other Ubuntu installations and exactly same behavior. Please note that in using chrome on all machines

**Comment by davidjgraph** [comment]
There's some very strange behaviour and it only seems to affect a very specific environment. Given the nature of the fix that would be required we suggest to use Firefox for now as a workaround.

**Comment by alderg** [comment]
This will be fixed in the next release.

**Comment by Meera-Remadevi** [comment]
Hi

**Comment by SuheylZ** [comment]
that problem seems to have been fixed now. On Mar 10, 2022 5:44 AM, Meera-Remadevi ***@***.***> wrote:
Hi

**Comment by Meera-Remadevi** [comment]
Thankyou for responding!! Do you know which release it was fixed by any chance?

**Comment by SuheylZ** [comment]
no, i just checked it a day ago and the problem is gone. since it is online and does not need any installation, I rarely check the version running. On Mar 10, 2022 5:56 AM, Meera-Remadevi ***@***.***> wrote:
Thankyou for responding!! Do you know which release it was fixed by any chance?

**Comment by Meera-Remadevi** [comment]
Ok. Thank you very much.

**Comment by alderg** [comment]
It was fixed in 15.8.0 (17-NOV-2021).

**Comment by Meera-Remadevi** [comment]
Awesome, thanks!
