### ISSUE TITLE
Add bar charts with negative values in the UI component

### ISSUE THREAD

**Issue by iamtekson** [jgraph/drawio#2393]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I was searching for a bar chart with negative values. Currently, it is unavailable in the library. I am talking about the bar chart like below,

![image](https://user-images.githubusercontent.com/39838116/140882755-4624def0-2bf6-44c3-818a-1188c8eb0be8.png)

**Describe the solution you'd like**
If added, it will be easy to build the UI.

**Comment by davidjgraph** [comment]
Charting isn't within the scope of the product functionality. You'd be better off with a tool specific to charting visualization.
