### ISSUE TITLE
Problem with specific diagram

### ISSUE THREAD

**Issue by frmariam** [jgraph/drawio#2395]
so I needed to update a diagram from 2016, and got a problem with the output png.
No idea why...
Looks good while editing but not when exported

[png_issue.zip](https://github.com/jgraph/drawio/files/7508095/png_issue.zip)
2 versions:
-draw.io exported (and importable) - doesn't look how it should
-edited with MS Paint

**Comment by mararad** [comment]
Just to check I understood you well. You uploaded the diagram in question in diagrams.net editor and exported it via File > Export as > PNG. The PNG result is different than the diagram, right?

If you test this in other browsers and Incognio mode, does it help?
After browser cache clear and browser extensions temporarily disabled, is it working better?
You could also try File > Export as > Advanced > PNG

If nothing helps:
* attach the diagram file
* tell us browser version and OS
