### ISSUE TITLE
Line/Arrow note won't keep transparent background setting

### ISSUE THREAD

**Issue by ElbPirat** [jgraph/drawio#2397]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The annotation for lines and arrows won't keep/use transparent settings.

**To Reproduce**
1. Create background color box
2. Create box and arrow
3. Create annotation with the arrow
4. Set the background while writing to transparent/none

**Expected behavior**
Being able to set the background of the annotation transparent

**Screenshots**
![grafik](https://user-images.githubusercontent.com/88144925/141092657-44046592-cc27-4168-8cb1-50fc1fdcef2d.png)
![grafik](https://user-images.githubusercontent.com/88144925/141092820-ea72d098-b4de-4d80-ab87-20b98968701b.png)
![grafik](https://user-images.githubusercontent.com/88144925/141092701-9b862f25-4cd4-4990-940a-781f814bcb4a.png)

- draw.io version 15.7.1

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Firefox
 - Version: 94.0.1

**Additional context**
Using another color will work, but keeps a white frame.
![grafik](https://user-images.githubusercontent.com/88144925/141093650-fbf0c13a-5770-4e56-a19e-79031bf6da03.png)

**Comment by alderg** [comment]
Press escape and set the label background to transparent with the cell (not the text) selected. We're aware of the suboptimal UX with the two background colors for the cell and the selected text and are working on a fix.
