### ISSUE TITLE
Autoresize not works well with diamond

### ISSUE THREAD

**Issue by imyhxy** [jgraph/drawio#2399]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Autoresize not works well with diamond, the edge of the diamond cross the text.

**To Reproduce**
1. Create a diamond shape and enter some label text
2. Stroke `Ctrl+Shift+Y` to auto resize the shape
3. See the flaw auto resize

**Expected behavior**
Auto resize the diamond shape according to the label text and prevent the edge cross the label text.

**Screenshots**

![Screenshot from 2021-11-11 13-12-52](https://user-images.githubusercontent.com/12193450/141241982-82b9f1fc-304f-4a3c-828d-a8526ad1562d.png)

![Screenshot from 2021-11-11 13-12-26](https://user-images.githubusercontent.com/12193450/141241975-6952677d-c74c-4444-8545-8fe3cc60ea4a.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- 15.7.3

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by mararad** [comment]
There is Autosize in Arrange tab (Ctrl+Shift+y) and Autosize in Property/Value section on the right.
The one in Property section works with label change (you can change label style, text etc.)

Basically you should tick Autosize in property, change label and then change Global spacing. I know it sounds confusing so I recorded a video showing all the steps

https://user-images.githubusercontent.com/44292306/141292316-c4b2a409-1a4a-4e14-87ee-41e3671c6996.mp4

**Comment by imyhxy** [comment]
@mararad Thanks for your helpful explaination.
