### ISSUE TITLE
[Desktop App] Running takes a long time after update

### ISSUE THREAD

**Issue by cocodada-lovely** [jgraph/drawio#2400]
### Preflight Checklist

* [O] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [O] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
App execution takes a long time after update and Even after launching the app, it takes a long time for the menu to appear when the button is pressed

**To Reproduce**
1. Click on 'draw.io desktop App'
2. Show only blank pages and After 5 minutes, the app is launched
3. And it takes about 1 minute for the menu to appear when the menu button is pressed.

**Expected behavior**
Desktop app must be running

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [15.7.3]

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Don't use browser, Using Desktop App]

**Additional context**
Before the update, it didn't take this much time to start up. I'm using the previous version.

**Comment by davidjgraph** [comment]
I'd suggest to uninstall and try a fresh install
