### ISSUE TITLE
Uncaught TypeError: this.addBpmnPalette is not a function

### ISSUE THREAD

**Issue by ArfanMirza** [jgraph/drawio#2401]
**addBpmnPalette** Prototype is not defined Sidebar but called, so throwing below error
Uncaught TypeError: **this.addBpmnPalette** is not a function
    init ***/js/grapheditor/Sidebar.js:109
    Sidebar ***/js/grapheditor/Sidebar.js:86
    createSidebar ***/js/grapheditor/EditorUi.js:4168
    createUi ***/js/grapheditor/EditorUi.js:4078
    EditorUi ***/js/grapheditor/EditorUi.js:339
**Sidebar.js:109:8**

![image](https://user-images.githubusercontent.com/5881606/141337274-5ad913c8-ee49-4f8f-8e50-f04eea557c84.png)

**Comment by davidjgraph** [comment]
What the context of this question?

**Comment by ArfanMirza** [comment]
When inject GraphEditor JS along with mxClient.js as script.src into html file (Same as done in mxgraph 4.2.2 grapheditor), 

https://github.com/jgraph/drawio/tree/dev/src/main/webapp/mxgraph
https://github.com/jgraph/drawio/tree/dev/src/main/webapp/js/grapheditor

Above error throw from **webapp/js/grapheditor/Siderbar.js** in console and grapheditor is not shown up, check in Sidebar.js, find out that calling function **addBpmnPalette** is not defined in Sidebar.js

Right now issue fixed by below change locally.

`if(this['addBpmnPalette'] !== undefined){
		this.addBpmnPalette(dir, false);
	}`
