### ISSUE TITLE
Authorization issue when embedding diagram into Notion app

### ISSUE THREAD

**Issue by thdoan** [jgraph/drawio#2403]
### Preflight Checklist!
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
An embedded diagram cannot be authorized properly in the Notion app, although it authorizes fine and can be displayed when viewed on [notion.so](https://www.notion.so/).

**To Reproduce**
1. Create a diagram on https://app.diagrams.net/
2. Grab embed link
3. Insert embed link in Notion app
4. Click blue Authorize button, which opens a new browser tab
5. Select Google account and click Allow
6. You get this error page:

![image](https://user-images.githubusercontent.com/4110567/141390516-1c0d9864-417c-44fc-9488-408fba4a2690.png)
URL: https://viewer.diagrams.net/google?state=cId%3D850530949725.apps.googleusercontent.com%26domain%3Dviewer.diagrams.net%26token%3D6c44kd9jcap5q03ff85shh8lapgvh9bl52brvfd60r5t6e8o3s8&code=4/0AX4XfWggOr2S14nm0FVv0dwa5IuE8qELjcLv973T_hT6dDjDrokd0X8Q8MjANd-c5R-PlA&scope=profile%20https://www.googleapis.com/auth/drive.readonly%20https://www.googleapis.com/auth/userinfo.profile

**Expected behavior**
After step 5 above, you should now be able to see the diagram embedded in the Notion app. Instead, after getting the error page you are stuck with this:

![image](https://user-images.githubusercontent.com/4110567/141390629-315dc9f3-98dd-4137-ac1d-bd8d6f32c448.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 15.7.3 ([website](https://app.diagrams.net/))

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.0.1 (21A559)
 - Browser: Chrome 95.0.4638.69 (Official Build) (x86_64)
 - Notion desktop app for macOS v2.0.19 (2.0.19)

**Comment by davidjgraph** [comment]
How did you add the Chrome extension to the Notion desktop app?

**Comment by davidjgraph** [comment]
Any better on latest with cache cleared?

**Comment by kuyazee** [comment]
This issue, unfortunately, still persists

![Screen Shot 2022-02-21 at 2 15 14 PM](https://user-images.githubusercontent.com/17846698/154899450-8f36ffe3-2366-4165-a246-89036cd7a3d9.png)
![Screen Shot 2022-02-21 at 2 15 09 PM](https://user-images.githubusercontent.com/17846698/154899457-0c387c66-0501-44b4-acb4-5fd4bd008d08.png)

**Comment by alderg** [comment]
Try using the Chrome extension instead https://chrome.google.com/webstore/detail/drawio-for-notion/plhaalebpkihaccllnkdaokdoeaokmle

**Comment by davidjgraph** [comment]
The apps are not supported.

**Comment by zoestoll** [comment]
Hi, I'm hitting this issue - is there any update here or workaround? I also tried the extension but when I try to use it I get a popup that says "Failed to insert. Please reinstall and try again".

**Comment by davidjgraph** [comment]
The app is not supported.
