### ISSUE TITLE
Unable to create child nodes in a mind map if i move the tree

### ISSUE THREAD

**Issue by amitw-vmware** [jgraph/drawio#2409]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When i use the mindmap container, it allows me to create topics and with the short cut alt + shift (on mac) + arrow lets me create sub topics.  This works fine and is nice.  The problem occurs when I try to move any of the topics or subtopics or parts of the tree.  After i do that, alt + shift (on mac) + arrow no longer creates sub topics but instead creates a leg to a new shape which isn't what i want as i'm trying to continue to build out the mind map.  

**To Reproduce**
1. Go to 'Search Shapes'
2. Click on 'Mindmap'
3. Click on the Topic shape
4. Hold Down Alt + Shift and right to create a sub topic
5. Hold Down Alt + Shift and up to create another sub topic
6. Click on the root topic shape again and use the move tree feature to move the tree somewher
7. Try to create subtopics the way you did with 4 and 5

**Expected behavior**
Sub topics that you can continue to branch from are created

**Screenshots**

https://user-images.githubusercontent.com/60367446/141659139-f4f03670-5beb-44d5-a847-67a93afdc1fb.mov

**draw.io version (In the Help->About menu of the draw.io editor):**

15.7.3

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser chrome
 - Version 95.0.4638.69

**Smartphone (please complete the following information):**
 - N/A
 
**Additional context**
- N/A

**Comment by mararad** [comment]
Reproduced on Win but with "middle" sub topic only.
As a workaround I'd suggest to make space between sub topics wider (as shown in the image) and it should work (at my place it is working this way)

Does it help?
![try](https://user-images.githubusercontent.com/44292306/141783645-23ada525-e2a5-4928-b0bb-4b160e440d4e.JPG)
