### ISSUE TITLE
work on the touch screen

### ISSUE THREAD

**Issue by essential-existence** [jgraph/drawio#2410]
Hello! I really like your project, but noticed a few inconveniences when working on a touch screen (android, google chrome browser):
- buggy double tap to edit the contents of the node text;
- pinch-to-zoom buggy, no double-tap-to-zoom;
- it is difficult to call the context menu if there are many selected elements (it would be nice to have a statically located button to call it);
- there is no way to block each selected element from accidental changes separately (or is it somehow possible?);
- most pop-up windows do not have a button to close them, and a tap outside the window cancels all element selections.
Thank you for the attention!

**Comment by davidjgraph** [comment]
Please only one subject per thread, we cannot track multiple reports in a single issue.

**Comment by essential-existence** [comment]
ok
