### ISSUE TITLE
On touch screen focus is lost after shape double tap

### ISSUE THREAD

**Issue by essential-existence** [jgraph/drawio#2414]
platform: android `10`, google chrome browser `94.0.4606.85`, draw.io `15.7.3`.

Problem: when you double-tap to edit the contents of the text of a node, the input field opens, and the focus is immediately lost (perhaps this is due to the resizing of the visible window area when the keyboard appears), or the input field is immediately closed.

Thank you for the attention!

**Comment by mararad** [comment]
You should add additional info or unfortunately the thread will be closed as incomplete

Steps to reproduce the behavior

If applicable, add screenshots or video to help explain your problem.

draw.io version (In the Help->About menu of the draw.io editor)

Browser Version

Android device

**Comment by essential-existence** [comment]
ok!

**Comment by essential-existence** [comment]
Perhaps a fixed (keyboard independent) window size will solve this problem.

**Comment by essential-existence** [comment]
Were you able to fix this problem? If so, thank you very much!
