### ISSUE TITLE
On the touch screen: issue with pinch-to-zoom and no double-tap-to-zoom

### ISSUE THREAD

**Issue by essential-existence** [jgraph/drawio#2415]
platform: android `10`, google chrome browser `94.0.4606.85`, draw.io `15.7.3`.

Problem: pinch-to-zoom bug, no double-tap-to-zoom.
The screen twitches when zooming in with a gesture.
Perhaps this is due to a change in the grid.

Thank you for the attention!

**Comment by mararad** [comment]
You should add additional info or unfortunately the thread will be closed as incomplete

Steps to reproduce the behavior

If applicable, add screenshots or video to help explain your problem.

draw.io version (In the Help->About menu of the draw.io editor)

Browser Version

Android device

**Comment by essential-existence** [comment]
did so!
