### ISSUE TITLE
On the touch screen: it is difficult to call the context menu if there are many selected elements

### ISSUE THREAD

**Issue by essential-existence** [jgraph/drawio#2416]
platform: android `10`, google chrome browser `94.0.4606.85`, draw.io `15.7.3`. 

Problem: It is very difficult to bring up the context menu on a touchscreen, especially if there are many highlighted items.
It would be nice to have a separate button to call it.

Thank you for the attention!

**Comment by mararad** [comment]
You should add additional info or unfortunately the thread will be closed as incomplete

Steps to reproduce the behavior

If applicable, add screenshots or video to help explain your problem.

draw.io version (In the Help->About menu of the draw.io editor)

Browser Version

Android device

**Comment by mararad** [comment]
Thanks. Could you add screenshot showing the issue please?
