### ISSUE TITLE
On the touch screen: most pop-up windows do not have a button to close them

### ISSUE THREAD

**Issue by essential-existence** [jgraph/drawio#2418]
platform: android `10`, google chrome browser `94.0.4606.85`, draw.io `15.7.3`.

Problem: most pop-up windows do not have a button to close them, and a tap outside the window cancels all element selections.

Thank you for the attention!

**Comment by mararad** [comment]
You should add additional info or unfortunately the thread will be closed as incomplete

Steps to reproduce the behavior

If applicable, add screenshots or video to help explain your problem.

draw.io version (In the Help->About menu of the draw.io editor)

Browser Version

Android device

**Comment by essential-existence** [comment]
ok, I have indicated everything you need to understand this problem!

**Comment by mararad** [comment]
Thanks. Could you add a screenshot showing an example, please?
