### ISSUE TITLE
How to remove page padding in draw.io

### ISSUE THREAD

**Issue by RichDevPro** [jgraph/drawio#2421]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I want to remove scrollbars when page is scaled smaller then the container size as like the photoshop. For now in draw.io the scrollbar never disappeared even the page is smaller then the container size.
I was able to be sure  it is due to the page padding.
In order to figure out this,  I already checked codes carefully and I found there was a function which gets page padding.(It was getPagePadding() function declared in EditorUi.js)
When I modify this function returns new MxPoint(0, 0), it makes the page to the left, not on the center. So I'm trying to change to center the page, but the graph's coordinates always place the vertices to the left regardless of the page grid position.
 

I am not sure It is not the proper way to modify the function like that in order to remove scrollbars(Page padddings makes the scrollbars) when page size is smaller then container.

**Describe the solution you'd like**
I want to remove the scrollbars when the page is scaled smaller then the container size like the photoshop, office, etc.

**Additional context**
![image](https://user-images.githubusercontent.com/87715252/142212292-f9a0e467-7897-49f5-8a37-0cbe61f09ce1.png)
I am expecting the way to remove page padding in the page view.
Without page padding, there would be no scrollbars when the page is smaller then container, I think.

![Screenshot_122](https://user-images.githubusercontent.com/87715252/142154460-8a3a0191-682d-4dfc-84d4-70cbd71a6055.png)

![image](https://user-images.githubusercontent.com/87715252/142160842-0ccd2d34-7516-4dc2-813a-49d731deba8f.png)

**Comment by mararad** [comment]
If you untick View > Scrollbars does it help?

**Comment by RichDevPro** [comment]
But It is not right what I  want.
The [View > Scrollbars] untick makes the container "overflow:hidden" in css so that the scrollbars are always hidden,  but what I want is to only remove the scrollbars when the page size is zoomed smaller than the container.

I am expecting the way to remove page padding in the page view.
Without page padding, there would be no scrollbars when the page is smaller then container, I think.  

Thanks.
