### ISSUE TITLE
Incorrect text kerning with some font sizes

### ISSUE THREAD

**Issue by Robyt3** [jgraph/drawio#2424]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Text kerning is not correct with some font sizes (see screenshot).

**To Reproduce**
1. Create new empty graph.
2. Add text with 12 pt Helvetica (the default font that is selected for me) and enter for example `abcwabc`.
3. Add another text with 11 pt Helvetica and enter the same text.
4. Text kerning in the second text looks incorrect, as shown in the screenshot.

**Expected behavior**
Correct text kerning with all reasonable font sizes.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/23437060/142419144-24287be7-5cdb-41a4-a0d7-f923f29eec6c.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 15.7.4 (browser version)

**Desktop:**
 - OS: Windows 10 64 bit
 - Browser: Firefox 94.0.1

**Comment by davidjgraph** [comment]
Are you sure you have Helvetica installed on the OS?

**Comment by Robyt3** [comment]
Oh, I don't. I just assumed the default font would be available on a default install of Windows 10 but it's not included.

Maybe draw.io can detect that the font is not available on the system and hide it in the list of fonts, or just detect Windows OS and use Arial as default instead instead?

**Comment by Robyt3** [comment]
It looks like it's falling back to Arial anyway, and kerning with Arial is incorrect, even though Arial is definitely installed on my OS.

![grafik](https://user-images.githubusercontent.com/23437060/142446864-f2d5b9d0-be71-4714-8740-49c34953d3f7.png)

(left is Arial, right is Helvetica but not installed on my system, top is 12 pt, bottom is 11 pt)

**Comment by mararad** [comment]
Reproduced with Arial 12pt and 11pt in FF 94.0.1 (64-bit), win 10
![text kerning](https://user-images.githubusercontent.com/44292306/142613597-10cf4632-e11e-4be6-b970-54f9de4f086a.JPG)

**Comment by davidjgraph** [comment]
I cannot recreate on FF 94.0.2, Win 10 using 15.8.7. Does the second vertex have to created a specific way?

**Comment by patricktokeeffe** [comment]
I also see problems with kerning around 'w' and offer the following observations for apps.diagrams.net v22.1.7 (yes, my computer is missing Helvetica and falls back to Arial) :

## Specific to 11 pt font? <br>Also, Lower case affected but not uppercase
![image](https://github.com/jgraph/drawio/assets/1348834/b3c767c4-334e-4222-814a-1ee3afe5210e)


## Works at 100% zoom but not other levels
![image](https://github.com/jgraph/drawio/assets/1348834/eb2bbfd6-d394-4b79-acef-10ab74a6bb86)

![image](https://github.com/jgraph/drawio/assets/1348834/7c7de70b-a30e-434f-b291-7ffb4ca60d8d)

![image](https://github.com/jgraph/drawio/assets/1348834/45152710-3984-4e9e-9754-083ceb0f7b95)

## Same behavior in Chrome (prior screenshots) and Firefox (below)
![image](https://github.com/jgraph/drawio/assets/1348834/cc931ae9-a476-46de-b139-324f31f194f1)

![image](https://github.com/jgraph/drawio/assets/1348834/78abdfd3-ab41-40f0-a616-2fa9828238c1)
