### ISSUE TITLE
Error opening diagram file - error on line 1 at column 10: error parsing attribute name

### ISSUE THREAD

**Issue by nikooiko** [jgraph/drawio#2425]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Hi guys, I've been working with the tool for some years now via draw.io (diagrams.net) and I host my files in my personal google drive. For some reason the last few days I'm unable to open a specific file and the app returns this error code: `error on line 1 at column 10: error parsing attribute name` and rejects to open the file. Is there any idea what might cause that? Do you have anything to propose to recover this file? Thanks!

**Screenshots**
![not-a-diagram-file-error](https://user-images.githubusercontent.com/9281494/142420991-f803fe82-b55d-487d-998b-32478a983660.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- 15.8.2 (diagrams.net)

**Comment by davidjgraph** [comment]
Google Drive has revisions stored for the last 100 versions. Go to drive.google.com, look at the revisions for the file and download the last but one. Open a blank editor and drop that in.

**Comment by nikooiko** [comment]
You were right, the tool can open the previous version so I can recover everything from that. Thanks!
