### ISSUE TITLE
Broken check for '.quipelements.com' domains

### ISSUE THREAD

**Issue by rene-leanix** [jgraph/drawio#2426]
Just stumbled upon the following lines of code in your index.html. The third line was probably supposed to be connected with `||`:

https://github.com/jgraph/drawio/blob/c063d9f03c0308f44c6a2d3461c7ab1f9e698654/src/main/webapp/index.html#L291-L293

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
