### ISSUE TITLE
Concept Draw Diagram crashes when opening Drawio VSDX files

### ISSUE THREAD

**Issue by gorblue** [jgraph/drawio#2427]
Hi, I've recently started using Drawio. Alongside Drawio I've been using ConceptDraw Diagrams (CDD).

Drawio files created/saved in VSDX format and opened in CDD would crash CDD every time. VSDX files natively created in Visio open without any problems.

Before I go to ConceptDraw Support, has anyone else experienced the same problem? Could this be an issue with Drawio?

OS: macOS BigSur 11.6
MBP M1 13inch
ConceptDraw Diagram: v15
Drawio: Desktop version 15.7.3

Many thanks,
GB

**Comment by davidjgraph** [comment]
It could well be an issue with drawio, but unfortunately we wouldn't address compatilbity issues with third-party tools that we don't test. I'd suggest to open it in Visio, save it again and then try that in your other tool.

**Comment by gorblue** [comment]
Thanks David

I'll give it a go and report back

**Comment by gorblue** [comment]
Opened in Viso, saved from there in Visio format and opened without any problems in ConceptDraw. 
It looks like an issue with drawio's export engine...

**Comment by davidjgraph** [comment]
Yes and no. It opens in Visio, that's the scope of the functionality we've implemented, so we won't investigate.
