### ISSUE TITLE
Double UTF-8 encoding when exporting to github

### ISSUE THREAD

**Issue by JensLincke** [jgraph/drawio#2431]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

Using https://www.diagrams.net/ I created  a drawing and saved it in github as `architecture.drawio` 

When displaying in in a website via embedding the text encoding is weired

![image](https://user-images.githubusercontent.com/1466247/142631149-08fa2767-00ee-450f-8413-afe5f67a93f5.png)

Potential BUG: double UTF-8 encoding...

```
$file architecture.drawio
architecture.drawio: UTF-8 Unicode text, with very long lines

$cat architecture.drawio | grep custom |  cut -c -120
        <mxCell id="iHkALPmoCXANNeq6opZh-39" value="+ process(code, &#xa;Â Â Â Â annotations, &#xa;Â Â Â �
        <mxCell id="iHkALPmoCXANNeq6opZh-46" value="+ onmessage(code,Â &#xa;Â  Â  annotations,Â &#xa;Â  Â  c
        <mxCell id="iHkALPmoCXANNeq6opZh-50" value="&lt;div style=&quot;font-size: 5px&quot;&gt;&lt;br&gt;&lt;/div&gt;&l
        <mxCell id="iHkALPmoCXANNeq6opZh-98" value="&lt;span class=&quot;hljs-comment&quot; style=&quot;color: rgb(150,
```

And by converting it from UTF-8 to Latin1 it will be displayed correctly in a UTF8 terminal:

```
cat architecture.drawio | iconv -f UTF-8 -t LATIN1 | grep custom |  cut -c -120
        <mxCell id="iHkALPmoCXANNeq6opZh-39" value="+ process(code, &#xa;    annotations, &#xa;    customInstanc
        <mxCell id="iHkALPmoCXANNeq6opZh-46" value="+ onmessage(code, &#xa;    annotations, &#xa;    customInstanc
        <mxCell id="iHkALPmoCXANNeq6opZh-50" value="&lt;div style=&quot;font-size: 5px&quot;&gt;&lt;br&gt;&lt;/div&gt;&l
        <mxCell id="iHkALPmoCXANNeq6opZh-98" value="&lt;span class=&quot;hljs-comment&quot; style=&quot;color: rgb(150,
```

So I assume there is a double utf-8 encoding happening somewhere?

**To Reproduce**
1. edited figugure https://app.diagrams.net/#HLivelyKernel%2Flively4-core%2Fdrawio%2Fsrc%2Fbabylonian-programming-editor%2Farchitecture.drawio

2. Visit same file on gitbub https://github.com/LivelyKernel/lively4-core/blob/gh-pages/src/babylonian-programming-editor/architecture.drawio 

3. See weired encoding on line 1000 ![image](https://user-images.githubusercontent.com/1466247/142631654-1d67ff05-17bc-43d9-a938-4b0c0febaead.png)

**Expected behavior**

I would expect to see "tabs" or other unicode there, but not encoding errors.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: 15.8.2

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 96

**Comment by alderg** [comment]
For plain text labels, we turn a tab keypress into 4 * \xa0 (non-breaking space character), which is what you see in the output. All other unicode chars (such as umlauts) are correct in the output. On the terminal in macOS, the output looks like this for me:

`$ cat architecture.drawio.xml| grep custom | cut -c -120 
        <mxCell id="iHkALPmoCXANNeq6opZh-39" value="+ process(code, &#xa;    annotations, &#xa;    customInstances, &#xa
        <mxCell id="iHkALPmoCXANNeq6opZh-46" value="+ onmessage(code, &#xa;    annotations, &#xa;    customInstances, &#
        <mxCell id="iHkALPmoCXANNeq6opZh-50" value="&lt;div style=&quot;font-size: 5px&quot;&gt;&lt;br&gt;&lt;/div&gt;&l
        <mxCell id="iHkALPmoCXANNeq6opZh-98" value="&lt;span class=&quot;hljs-comment&quot; style=&quot;color: rgb(150,`

Embedding also works for me. Could you add a link to a test case please?

**Comment by JensLincke** [comment]
maybe this is a linux issue... but I see this in a standard WSL (windows subsystem for linux) 
![image](https://user-images.githubusercontent.com/1466247/143920646-3839a798-5734-4aa7-9c6e-5255c8a44c98.png)
and in xterm... 
![image](https://user-images.githubusercontent.com/1466247/143920857-be2d59ef-c91a-48f2-9fec-208828e2aef1.png)
and I see this in chrome when viewing the raw file on github:
![image](https://user-images.githubusercontent.com/1466247/143921123-21a51019-03fb-41a2-8905-62b2af75231c.png)
@alderg , did you check the file out with git and in got automatically repaired in MacOS?

**Comment by alderg** [comment]
How did you insert those characters?

**Comment by JensLincke** [comment]
I used https://app.diagrams.net to load a file from github and save it back https://app.diagrams.net/#HLivelyKernel%2Flively4-core%2Fdrawio%2Fsrc%2Fbabylonian-programming-editor%2Farchitecture.drawio

**Comment by alderg** [comment]
What key did you press to insert those characters?

**Comment by JensLincke** [comment]
Sorry, I found the issue on my side:

using 
https://app.diagrams.net/#HJensLincke%2Fdrawio-test%2Fdrawio%2Ftest-chars.drawio

to edit
https://github.com/JensLincke/drawio-test/blob/drawio/test-chars.drawio

I used a german keyboard and pasted the unicode through the clipboard 
```
This is sample text:
this a tab...
öäüß german umlauts and sz
→and a unicode error
```
![image](https://user-images.githubusercontent.com/1466247/144460433-f6ef5314-c2f1-4705-9000-d8f98758b808.png)

and the umlauts and unicode char seems to correctly end up in the drawio branch ....
![image](https://user-images.githubusercontent.com/1466247/144461588-00600a4f-e6dc-4534-8f07-5ca664f0450b.png)

And the bad conversion happend when copying it to the main branch... 
![image](https://user-images.githubusercontent.com/1466247/144462032-931ec0f5-ffab-4a83-82bc-061e3762c816.png)
