### ISSUE TITLE
Ungrouping changes position of text (or something)

### ISSUE THREAD

**Issue by JC3** [jgraph/drawio#2433]
In this file: [camwiring.zip](https://github.com/jgraph/drawio/files/7576447/camwiring.zip) ([gist](https://gist.github.com/JC3/8821e8e152a1057361c4cd2a40147a0e))

If one of the groups is selected, right-clicked, and then ungrouped, the position of the numeric labels on all of the lines is swapped around:

![ezgif com-gif-maker (10)](https://user-images.githubusercontent.com/5651184/142767383-a28a85ef-f19f-44e5-b922-eb76f99d5529.gif)

Notes:

- There are 9 lines in that image. The crossed pairs started as 2 parallel lines and waypoints were added.
- The labels were created by clicking on each line then immediately typing text.

Environment:

- Chrome Version 96.0.4664.45 (Official Build) (64-bit)
- Windows 10 64-bit

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
