### ISSUE TITLE
Select all for texts: solution to alter font/appearance of all text in a page

### ISSUE THREAD

**Issue by mirianfonkam** [jgraph/drawio#2434]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I exported a UML class diagram and noticed that the text font (12pt) was not legible. I wanted to increase the font of all texts present in the diagram to 18 pt and was unable to find an easy method. 

I wished that `Ctrl + A` would select all text in the page so that I would be able to increase the font as a two-step method. As of now, the `Select All` command selects the parent shapes (not the strings within the shapes).

In order to achieve what I want have to manually: select the text, increase the font and repeat the process for every shape in a page.

**Describe the solution you'd like**
`Ctrl + A` or select all with mouse also selects the inner texts so that the user can alter the general text appearance. 

**Describe alternatives you've considered**
I considered increasing the Zoom % during export but it not the best solution.

**Additional context**
Current behavior during selection:
![UML Sample](https://user-images.githubusercontent.com/28691174/142784977-7f3ad124-dd34-4ba7-b5ff-6ae0db9f7dfc.png)

**Comment by mararad** [comment]
Tested in:
* diagrams.net 15.8.3
* Chrome Version 96.0.4664.45 (Official Build) (64-bit) 
* Win 10
 I clicked Ctrl+a => all were selected and font size was increased in Text tab

Did I reproduce steps you performed? Which diagrams.net version are you using? Which browser version and OS?

https://user-images.githubusercontent.com/44292306/142859617-c931f613-9f2f-4213-8cd0-6b22bd711382.mp4

**Comment by mirianfonkam** [comment]
This worked well! Thank you so much for the demo! 

It turns out I was unaware of the dialog on the right 😅
