### ISSUE TITLE
White style results in black object when exporting to Visio

### ISSUE THREAD

**Issue by RealStitch** [jgraph/drawio#2435]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When using the Style Preset "White" in the desktop version 15.7.3 the 'fillColor' gets deleted. While this does not affect the visuals in diagrams.net, this results in a black shape when exported to Visio. Results checked on desktop browser plugin and on Visio Viewer on iOS 14.8.1 (iPad)

**To Reproduce**
Create a rounded rectangle shape and open its style: 
> rounded=1;whiteSpace=wrap;html=1;labelBackgroundColor=none;strokeColor=default;fillColor=#FFFFFF;

Use any colour style from the presets e.g. orange and look at the style
> rounded=1;whiteSpace=wrap;html=1;labelBackgroundColor=none;strokeColor=#d79b00;fillColor=#ffe6cc;

Change to preset 'white' again and open style:
>rounded=1;whiteSpace=wrap;html=1;labelBackgroundColor=none;

fillColor has been deleted. 
Using the "fill" checkbox underneath the color presets with the color 'white' activated results in
> rounded=1;whiteSpace=wrap;html=1;labelBackgroundColor=none;fillColor=default;

Still exports to black in Visio.

**Expected behavior**
For white preset the fillColor should actually be set to FFFFFF.
When reactivating "fill" checkbox, the fillColor should actually be set to FFFFFF and not to "default"

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version : 15.7.3 (Desktop)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
 - Device: iPad Pro 2021
 - OS: iOS 14.8.1
 - Visio Viewer in Office 365

**Comment by RealStitch** [comment]
Btw. this worked fine with the previous version I was using in August 2021 (don't know which one though) when exporting to Visio (no fillColor needed to be set then). I just checked this in an exported Visio from then. When I export this document to Visio now, all objects are filled black (background)

Update1: With bpmn-style objects the fillColor=default seems to work fine.

**Comment by ashrafteleb** [comment]
Bug will be fixed in the next release

Thanks for the report
