### ISSUE TITLE
Preview of custom templates in draw.io for Confluence Cloud isn't working

### ISSUE THREAD

**Issue by Bastesque** [jgraph/drawio#2436]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I use the new board editor in draw.io for Confluence Cloud. I added a few custom templates which I tried to access. I recognized that for the default templates, the preview option works. For custom templates, the magnifying glass turns bright grey, but the preview doesn't work. 

**Expected behavior**
I would like to have a preview for custom templates, too.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 15.6.8
![Screenshot 2021-11-23 at 11 44 26](https://user-images.githubusercontent.com/68647048/143015115-6d28e40f-27db-4837-af4a-63385bdda794.png)
![Screenshot 2021-11-23 at 11 44 09](https://user-images.githubusercontent.com/68647048/143015116-b3d32053-8329-4b0f-af58-05536032ee5f.png)

**Comment by ashrafteleb** [comment]
Fixed
