### ISSUE TITLE
Format panel of the board editor in draw.io for Confluence Cloud refuses to show formatting options

### ISSUE THREAD

**Issue by Bastesque** [jgraph/drawio#2437]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
In our Confluence Cloud test instance, I can't access the format panel when I like to format a shape. I also have a personal Cloud instance, where everything works (see screenshots). I am using the same version (15.6.8), the same browser, I cleared the cache multiple times…unfortunately nothing works out for me. 

- draw.io version 15.6.8
- 
![Screenshot 2021-11-23 at 12 26 30](https://user-images.githubusercontent.com/68647048/143017387-2f87d232-35db-4fc1-9d10-6764250b7dcd.png)
![Screenshot 2021-11-23 at 12 26 15](https://user-images.githubusercontent.com/68647048/143017392-b911646d-7c62-4e18-8092-e900ffd65593.png)

**Comment by davidjgraph** [comment]
Try htttps://ac.draw.io/clear.html , it's a pretty old version

**Comment by Bastesque** [comment]
I found the reason…something inside the customization code keeps the format panel from being displayed. I will investigate what caused the problem. Thanks anyway.
