### ISSUE TITLE
[Feature Request] Apply edit dialog using keyboard (e.g. Ctrl+Enter)

### ISSUE THREAD

**Issue by akrpic77** [jgraph/drawio#2438]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to use mouse to click Apply on the edit dialog. Escape closes the edit dialog. There should be a way to confirm (=Apply) dialog with keyboard as well. 

**Describe the solution you'd like**
I suggest Ctrl+Enter to confirm the dialog.

**Describe alternatives you've considered**
More like a workaround, currently you have to Tab-Tab-Tab-Tab-Enter to confirm dialog.

**Additional context**
No additional context.

**Comment by alderg** [comment]
Good idea! We'll add this in the next release.

**Comment by akrpic77** [comment]
@alderg should I open new issue?

**Comment by davidjgraph** [comment]
If it works in the online version and fails in a desktop build, please open the issue on the desktop project.

**Comment by alderg** [comment]
Ctrl+Enter works for me in Chrome 100.0.4896.60 on macOS 12.3.1 (21E258).
