### ISSUE TITLE
PDF Export not working

### ISSUE THREAD

**Issue by Amulya-sb** [jgraph/drawio#2439]
PDF export not working sometimes - 500 internal server error.
Not sure when ? How big file size should be?

Environment
Online version -> Draw.io
Browser - Chrome

**Comment by mararad** [comment]
What's the file size? Which diagrams.net version are you using? Can be seen under Help in the editor
Is it working in other browsers and Incognito mode? 

If not, does the following help:
* File > Export as > Advanced > PDF
* File > Print > Print > Save as PDF/Print to PDF
* Download desktop app and export to PDF

If there are images in the diagram, you can upload them to e.g Imgur and then add image URL (not image itself) to the editor via "+" > Image. This way the file will be smaller and there should't be the export issue

**Comment by Amulya-sb** [comment]
File Size is 988kb
Version 15.8.2

**Comment by davidjgraph** [comment]
How do we reproduce the issue?
