### ISSUE TITLE
Diagrams.net cannot access private GitHub repos

### ISSUE THREAD

**Issue by pcfox-buf** [jgraph/drawio#2440]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Private repositories are no longer accessible using Diagrams.net open or save features. Only public GitHub repositories are shown when opening from or saving files to GitHub. Some repositories shown are not owned by the logged in account. On 11/10/2021, this feature showed both public and private repositories owned by the logged in account. Diagrams.net is properly authorized to pull from and push to private repositories owned by the logged in account.

**To Reproduce**
1.  Click 'File'
2.  Click 'Open From'
3.  Click 'GitHub...'
4.  Click 'Open Existing File'

**Expected behavior**
The "Select File" dialog should show repositories owned by the login account, public and private.

**Screenshot**
![image](https://user-images.githubusercontent.com/60898017/143253996-9f504fde-f38e-4ee0-81cd-2a9ae847dce6.png)
This error follows when using "Open Recent" from a private repo file (not moved).

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 15.8.5

**Desktop (please complete the following information):**
 - OS: Windows 10, Windows 11
 - Browser: Chrome, FF
 - Version: 78.15.0esr

**Additional context**
N/A

**Comment by alderg** [comment]
Try giving the app access to that repo using https://github.com/apps/draw-io-app - see https://www.diagrams.net/blog/single-repository-diagrams for details. We'll improve the error messages.

**Comment by KrzeQ** [comment]
> Try giving the app access to that repo using https://github.com/apps/draw-io-app - see https://www.diagrams.net/blog/single-repository-diagrams for details. We'll improve the error messages.

Works for my own repos, will update this comment when it's applied in org 👍
