### ISSUE TITLE
Is it possible to collaborate via the desktop app? Or only via the browser version of draw.io?

### ISSUE THREAD

**Issue by motreo** [jgraph/drawio#2441]
I tried collaborating with someone on a draw.io file saved in a shared OneDrive folder. We both opened the file locally on our laptops and started editing, but couldn't see each others changes. Selecting File > Synchronize didn't help.

Is it only possible to collaborate via the browser version of draw.io? I had a feeling this would be the case with collaboration on a tablet since draw.io doesn't have an iOS app, but I was hoping there would be an option for in-app collaboration on desktop.

**Comment by davidjgraph** [comment]
There's no external comms from the desktop app, that is by design. You could work against a sync'ed local file, but otherwise only the web app has collaboration.
