### ISSUE TITLE
Weak performance

### ISSUE THREAD

**Issue by Zagidziran** [jgraph/drawio#2443]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Extreemly low performance processing the attached picture

**To Reproduce**
1. Open the attached picture in draw.io
2. Try to chage something or even scroll

**Expected behavior**
Everything is fine.

**draw.io version (In the Help->About menu of the draw.io editor):**

- 15.8.6

**Desktop (please complete the following information):**
Checked in the
 - OS: Windows
 - Version 13.9.9

Or browser
 - Chrome

**Additional context**
![Federations alg drawio (1)](https://user-images.githubusercontent.com/38669182/143399333-2065f656-4500-4bc2-8de1-3ac149220101.png)
.

**Comment by alderg** [comment]
Looks like the dots fill pattern kills performance on Windows. We'll remove the dots fill pattern in the next release. Attached is a version of the diagram with that fill pattern removed.
![143399333-2065f656-4500-4bc2-8de1-3ac149220101-no-dots](https://user-images.githubusercontent.com/921200/143406955-4e0ddb9c-b384-4ef5-a7ee-2e8ff207afe0.png)
