### ISSUE TITLE
Keyboard/mouse shortcuts not working in draw.io

### ISSUE THREAD

**Issue by kirootsouthpark** [jgraph/drawio#2444]
Hi, 

I am using the open-source solution for diagrams.net (version 15.8.6) on a Microsoft Edge browser Version 96.0.1054.29 (Official build) (64-bit).

I am not able to use the following keyboard/mouse shortcuts within basic diagram shapes (such as boxes) and free text:

1. Ctrl+c (does not do anything) - to reproduce - first paste text from outside of diagrams.net into an open diagram. Then try to copy a chape inside the diagram using the shortcut. When you try to paste, the shape should not be copied.
2. Shift + left click to select text within the shape (does not do anything)
3. Shift + (any) arrow to select text within the shape (does not do anything)
4. Left click and drag to select text within the shape (does not do anything)

Hope we can come to a resolution to atleast some of these issues, they are really annoying :D :) 

Kind regards,
Kiril Tsankov

**Comment by mararad** [comment]
Hi,

Is the diagram maybe saved to OneDrive? Does these shortcuts work in other browsers e.g Opera or Firefox?

**Comment by kirootsouthpark** [comment]
Hi. Yes the file is saved to OneDrive. And yes, these shortcuts work on the same file in Firefox.

**Comment by Foreversun87** [comment]
Hi, where are the hotkey for paste here: ?
Default CRTL + v

![grafik](https://user-images.githubusercontent.com/44213573/143546734-e785b4b1-f01a-463e-bb6b-f13557f33582.png)

**Comment by davidjgraph** [comment]
I just tried this with the same Edge version, draw 15.8.8 and Windows 10. 

I loaded the basic flowchart example from OneDrive. None of the issues 2-4 failed. I do not understand the description for issue 1.

Does this happen with any diagrams stored in OneDrive? Are there any errors on the browser console?

**Comment by davidjgraph** [comment]
I can repeat on Edge 96 on Win 11. Non repeating case was a surface, this is desktop.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
