### ISSUE TITLE
Export to SVG 1.1 includes non-standard rgba colors

### ISSUE THREAD

**Issue by mbrannstrom** [jgraph/drawio#2445]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Export to SVG 1.1 includes non-standard rgba colors, when rgb colors would be more appropriate.

In SVG 1.1 colors are expressed as rgb values, while opacity is expressed in a separate attribute.
In the candidate SVG 2.0 version, rgba colors are allowed. Usage of rgba color values are non-standard, even though many browsers support it, but browsers are not the only applications that read SVG images.

**To Reproduce**
1. Create a draw.io diagram, containing a rectangle.
2. Export to SVG
3. SVG file contains `rgba(*, *, *, 1)` color elements (* = wildcard).

**Expected behavior**
Minimum: Color values `rgba(r, g, b, 1)` should be replaced with `rgb(r, g, b)`.

In SVG 1.1, the alpha value should be moved to the attribute `*-opacity`. 

You may want to differentiate between SVG 1.1 and (future) SVG 2.0.
In SVG 2.0 the existing behavior is fine (perhaps desired).

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 15.8.6

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 15.0

**Comment by davidjgraph** [comment]
Is there a known case of an app not rendering correctly?

**Comment by mbrannstrom** [comment]
Apache FOP uses Apache Batik which cannot handle rgba-colors. 

Example error:
```
The attribute "fill" represents an invalid CSS value ("rgba(0, 0, 0, 1)").
Original message:
The "fill" property does not support function values.
        at org.apache.batik.css.engine.CSSEngine.getCascadedStyleMap(CSSEngine.java:775)
...
        at org.apache.fop.render.pdf.PDFImageHandlerSVG.handleImage(PDFImageHandlerSVG.java:104)
```

**Comment by alderg** [comment]
We use rgba in the output to render "default" colors and add alpha=1 for CSS selectors to be able to differentiate between user input and "default" in static SVG (eg when viewed in dark mode). In other words, alpha is always 1 and could be removed in a preprocessing step. Alternatives are data-attributes or SVG 2.0 output (which probably wouldn't work with Apache FOP and Batik either).

**Comment by davidjgraph** [comment]
Does it work if you change an example to use rgba(#RRGGBBAA) hex notation?

**Comment by mbrannstrom** [comment]
> Does it work if you change an example to use rgba(#RRGGBBAA) hex notation?

No, it does not work. 

```
The attribute "fill" represents an invalid CSS value ("rgba(#000000ff)").
Original message:
Invalid RGB color: 000000ff.
```

My current workaround is to run the SVG through `sed` (BSD syntax here):

```
sed -E -i~ -e 's/rgba\(([0-9]+) *, *([0-9]+) *, *([0-9]+) *, *1 *\)/rgb(\1, \2, \3)/g' images/*.svg
```

**Comment by alderg** [comment]
The next release will use rgb() values.
