### ISSUE TITLE
New file save error in Github 

### ISSUE THREAD

**Issue by Cadmus-design** [jgraph/drawio#2447]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I want save a new file in my Github repo, it's show access denied message.
I tried  https://app.diagrams.net/?mode=github and https://app.diagrams.net/clear.html to clean my cache but doesn't work.
I also see the reference https://www.diagrams.net/blog/single-repository-diagrams and set authrize to all or single repo, and uninstall reinstall diagram app in Github.
It's not working. But I can open my recently files and modified them.

**To Reproduce**
1. Click on  'Create New diagram' 
2. Click on 'create'
3. On select folder dialogue, select any folder
4. click on  'OK'
5. See the Access denied message

**Screenshots**
1. 
![圖片](https://user-images.githubusercontent.com/11531752/143545949-64b2b5d8-8e9d-4e04-b9ac-9df097bb92ba.png)
2. 
![圖片](https://user-images.githubusercontent.com/11531752/143545990-603bdaa5-0a6f-4c08-834b-e08d73551524.png)
3. 
![圖片](https://user-images.githubusercontent.com/11531752/143546019-ef9842c8-66fd-427b-a15d-de9f226ea3fe.png)
4. 
![圖片](https://user-images.githubusercontent.com/11531752/143546070-d6c140be-b081-4b85-8809-8ce09eca184b.png)
5. 
![圖片](https://user-images.githubusercontent.com/11531752/143546107-ec79601b-b450-47e3-a9f5-f45918154def.png)

**Comment by davidjgraph** [comment]
If you click authorize, is the app installed and have you permitted access to that repo?

**Comment by Cadmus-design** [comment]
I click Authorize, but doesn't work.
But I can create a new file and save in my account properly now.
Is this the cookie issue?

**Comment by davidjgraph** [comment]
Might be caching the old cookie. If it's working now I'll close.
