### ISSUE TITLE
Custom libraries in draw.io for Confluence Cloud always have .xml ending

### ISSUE THREAD

**Issue by Bastesque** [jgraph/drawio#2448]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I created a few custom libraries for our staff. I embedded the libraries in the configuration settings. Now I experience that the custom library in the editor always gets displayed with the .xml ending.

**Expected behavior**
I would love to see the library (file) name only in my shape panel and get rid of the .xml ending.

- draw.io version 15.6.8
![Screenshot 2021-11-26 at 09 26 53](https://user-images.githubusercontent.com/68647048/143550411-2ebabf4e-388d-40cb-ac16-b47df9acc854.png)
![Screenshot 2021-11-26 at 09 23 42](https://user-images.githubusercontent.com/68647048/143550416-f357561a-9762-4f85-bea3-f0fe303cc19a.png)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by davidjgraph** [comment]
In 15.8.8
