### ISSUE TITLE
Elements move around relative to each other when zooming

### ISSUE THREAD

**Issue by rmst** [jgraph/drawio#2449]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Elements move around relative to each other when zooming. It's subtle but is problematic when precision is important. See video below (fullscreen recommended, check the eyes/pupils)

**Expected behavior**
Elements not moving around relative to each other when zooming

**Screenshots**

https://user-images.githubusercontent.com/7987756/143621744-9bbce30c-3cbf-477b-95ea-4e55d74d91ae.mp4

**draw.io version (In the Help->About menu of the draw.io editor):**

- 15.8.4 (but has been present since I started using drawio years ago)

**Desktop (please complete the following information):**
 - OS: Linux, MacOS
 - Browser: Chrome, Firefox
 - Version 96 (Chrome)

**Smartphone (please complete the following information):**
 Not tested

**Additional context**

**Comment by davidjgraph** [comment]
Please provide a diagram that recreates the problem and the steps to recreate.

**Comment by rmst** [comment]
[logo1.drawio.zip](https://github.com/jgraph/drawio/files/7611120/logo1.drawio.zip)

Attached is part of the diagram from above. Zooming in and out should look like in the video above. The effect is more pronounced when zooming further out

**Comment by mararad** [comment]
Very subtle change. Reproduced in Chrome Incognito and FF, 20.0.4 and Win 10.
At my place this behaviour can be seen when zoomed in to e.g 120% and zoomed out to e.g 100%
