### ISSUE TITLE
Inability to move small shapes

### ISSUE THREAD

**Issue by lvmm** [jgraph/drawio#2461]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
The way draw.io gives precedence to almost anything over dragging makes moving small shapes difficult. E.g. drop EIP/Message Construction/Document Message shape at the page and try dragging it at 100% magnification - impossible, you'll always end up dragging a connector out or resizing it instead of moving.

**Describe the solution you'd like**
 I'd like to be able to enter a drag-only mode by ctrl-shift-clicking perhaps, or something similar - quick and temporary.

**Describe alternatives you've considered**
After zooming to 200+% one can finally click a draggable part of the shape, but zooming in and out all the time is annoying and time-consuming.

**Additional context**
Monitor is 24" 1920*1200, if it matters

**Comment by alderg** [comment]
Try unchecking connectable under Properties:
<img width="269" alt="Screenshot 2021-12-06 at 06 19 58" src="https://user-images.githubusercontent.com/921200/144791607-0fa94fb3-b2d0-4518-b5a8-e862f41f6d41.png">

**Comment by lvmm** [comment]
@alderg I am sorry, but this is not an acceptable solution. It disables only connectors but not everything else - resizing, etc. Which could be done the same way, but I of course wouldn't want to disable this functionality permanently, and if zooming in is time consuming then constantly changing settings is obviously is even more time consuming. Finally, it just doesn't work - if you care to test your advice before you'd find out that EIP messages ignore connectable setting and still let one pull out the connectors.

Please reopen.

**Comment by alderg** [comment]
If a small shape is selected, the resize handles and blue arrows are moved away from the shape and the anchor points are hidden to make it possible to drag it:
![33ad56d448b0c784ffed05d66e0ae5d7](https://user-images.githubusercontent.com/921200/144797474-83c7a439-2402-43f4-a34b-ac31b9c081de.gif)

**Comment by lvmm** [comment]
I can only suggest again that you test _with the shape I mentioned_ - EIP/Message Construction/Document Message.
