### ISSUE TITLE
Add configuration option to adjust mousewheel/trackpad zoom sensitivity

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#2469]
Don't really have a browser config dialog, so probably goes in JSON.

**Comment by alderg** [comment]
We'll do some more work on this. Meanwhile, use zoomWheel config option https://github.com/jgraph/drawio/issues/2206

**Comment by davidjgraph** [comment]
{
  "zoomFactor": 1.05
}

**Comment by flotpg** [comment]
This works like a charm!

**Comment by flotpg** [comment]
Do you know where to start in the Nextcloud App?
The menu option is missing here:
![CleanShot 2022-02-02 at 21 37 44@2x](https://user-images.githubusercontent.com/20798074/152233493-8f5127cc-7460-4a7e-8f96-bfc7f0db1f19.png)

**Comment by davidjgraph** [comment]
@flotpg you would need to address that to the author of the integration, I don't know who that is.

**Comment by flotpg** [comment]
> @flotpg you would need to address that to the author of the integration, I don't know who that is.

On it, thanks for the fast reply.
