### ISSUE TITLE
Object metadata

### ISSUE THREAD

**Issue by jgroom33** [jgraph/drawio#247]
Add the ability to specify metadata associated with any object.

Current functionality allows 'edit data' limited to key, value pair.

This should be extended to allow structured data compliant (xml or json or yaml implementation)
The values of the data can be referenced in the object.

**Comment by Diaskhan** [comment]
this option would be very useful. Because if I need to do entterprise graph editor, u must override many thing in existing code! It would be nice if there would be template with user objects.

Its possible to include template with user objects tag ?
similar to 

    <object label="Task" sss="&quot; asdasd&quot; &quot;&quot;&quot;sad asdasd" id="3">
      <mxCell style="shape=ext;rounded=1;html=1;whiteSpace=wrap;" vertex="1" parent="1">
        <mxGeometry x="140" y="140" width="120" height="80" as="geometry"/>
      </mxCell>
    </object>

**Comment by Diaskhan** [comment]
To make similar to bpmn.io diagraming !

**Comment by Diaskhan** [comment]
@jgroom33 have U seed a demo code of user objects ?
https://jgraph.github.io/mxgraph/javascript/examples/userobject.html

U could ovveride this code 
```

var person2 = doc.createElement('Person');
person2.setAttribute('firstName', 'Bugs');
person2.setAttribute('lastName', 'Bunny');
var newLi = document.createElement('li');
newLi.innerHTML = 'Привет, мир!';
person2.appendChild(newLi);
```

**I have tested a demo Draw io dont erase custom tags in User object !**

```
<mxGraphModel>
  <root>
    <mxCell id="0"/>
    <mxCell id="1" parent="0"/>
    <Person firstName="Daffy" lastName="Duck" id="2">
      <mxCell vertex="1" parent="1">
        <mxGeometry x="40" y="40" width="80" height="30" as="geometry"/>
      </mxCell>
    </Person>
    <Person firstName="Bugs" lastName="Bunny" id="3">
      <li>
        Привет, мир!
      </li>
      <mxCell vertex="1" parent="1">
        <mxGeometry x="200" y="150" width="80" height="30" as="geometry"/>
      </mxCell>
    </Person>
    <Knows since="1985" id="4">
      <mxCell edge="1" parent="1" source="2" target="3">
        <mxGeometry relative="1" as="geometry"/>
      </mxCell>
    </Knows>
  </root>
</mxGraphModel>
```

**Comment by jgroom33** [comment]
lucidchart has a feature that allows shape data to be exposed in the view using [+template]:
https://lucidchart.zendesk.com/hc/en-us/articles/115000403726-Link-Lucidchart-Diagrams-to-Spreadsheet-Data

The implementation should consider this goal.

imo, the implementation should allow a static definition of xml under the object. This data should be editable in the view using a xml explorer view component.

**Comment by Diaskhan** [comment]
No there not )) Lucidchart is base on Draw.io ! ))

**Comment by Diaskhan** [comment]
I'am trying to say ! That the draw.io is base diagraming toolkit! Its not a dashboard toolkit like lucidchart!  If u think the developers gonna make it like lucidchart u're wrong ! Many pricing thigns based on mxgraph library! Because draw.io its on apache license!  Better is to pay to lucidchart if u wanna use it! No one from team draw.io not gonna make lucidchart because they dont needed! Better close issue! Other comments is oftopic!

**Comment by Diaskhan** [comment]
Dude is very ambigios idea like lucidchart !

**Comment by davidjgraph** [comment]
Declined. No action for 3 years, no point leaving an issue open that will not be implemented.
