### ISSUE TITLE
Inserting bold text in bold text makes the inserted text even bolder

### ISSUE THREAD

**Issue by chTom79** [jgraph/drawio#2471]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Copying and inserting bold Text in an already bold text makes the inserted text even bolder.

**To Reproduce**
1. Write some text into a shape
2. Make the text bold
3. Copy or cut a piece of the text.
4. Paste the text in the alredy bold text.
5. The inserted text is not bolder than the original text.

Looking at the HTML of the text the `<b>`-Tag is now doubled before the extra bold text:
`<b>This sample is a bold </b><b><b>sample </b>Text</b>`

**Expected behavior**
The inserted text shoulud keep it's original format.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/95519684/144701017-aeac626a-e3d1-4455-a7cc-086b29670636.png)
The word "sample" was copied and pasted. It became bolder.

**draw.io version (In the Help->About menu of the draw.io editor):**
15.9.1

**Comment by mararad** [comment]
Which browser version and OS are you using? Do you see the same behaviour in other browsers and Incognito mode?
Is it possible to attach video showing all the performed steps?

Regards,

**Comment by chTom79** [comment]
Hi @mararad 
I tested it with 3 browsers. It only happens with one.

- NOK: Firefox Version 94.0.2
   incognito mode: NOK
- OK: Microsoft Edge Version 96.0.1054.43
- OK: Google Chrome Version 96.0.4664.45

OS: Windows 10

https://user-images.githubusercontent.com/95519684/144918612-4e33b4cd-d4ed-40a5-a0af-61db3a451fb9.mp4

.

**Comment by mararad** [comment]
Thanks.

Reproduced with FF 94.0.2 (64-bit) and FF Incognito, diagrams.net 15.9.1, Win 10 Pro
