### ISSUE TITLE
Modify svg color directly

### ISSUE THREAD

**Issue by OhYee** [jgraph/drawio#2473]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I often insert svg inside the image, but most of the svg colors are set directly in the `path` using `fill`. Drawio only supports setting the color using `style`, so I need to modify the svg source code to change the color every time.

**Describe the solution you'd like**
I want drawio can directly modify each `fill` of `path`

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by alderg** [comment]
See https://www.diagrams.net/doc/faq/svg-edit-colours

**Comment by OhYee** [comment]
@alderg 
I have read and am using the features in the documentation, but it doesn't meet my needs

Maybe the issue needs to be reviewed and reopen it

**Comment by alderg** [comment]
Are are not an SVG editor.

**Comment by OhYee** [comment]
Most of the svg images I've seen don't use `style` to control color, but rather use `fill` to control color directly. 
This leads to a scenario where the editableCssRules supported by drawio are barely used, and if the edit `fill` field could be supported, it would easier when using svg.

Maybe drawio doesn't need to support complex svg editing, just show and modify all the fill fields

**Comment by alderg** [comment]
Modify the SVG and replace the fill with a style as shown in the documentation.

**Comment by OhYee** [comment]
It only support `fill` in `style` like `<style>.f1{fill: #000}</style>`. 
Doesn't support `<path d="..." fill="#000"/>`.

**Comment by alderg** [comment]
<path class="f1"...

**Comment by OhYee** [comment]
Yes, I can make drawio color editable by modifying the svg, which is what I do now. But since most svg don't use style to set colors, I need to modify almost all svg.

It would be better to have direct support for editing the `fill` inside the `path`

**Comment by SmiVan** [comment]
This is a fairly big inconvenience, it would be more user-friendly to just have a general color override option for fill and/or stroke when an SVG is dragged in by default.

It's unreasonable to expect an average user to have to manually edit every single SVG and shape style with an obscure parameter just to suit the requirements of drawio.

**Comment by davidjgraph** [comment]
No, draw.io isn't an SVG editor, this is written in the readme. Saying I use your tool therefore you need to meet every use case isn't how it works. We set the scope of the project, if you don't like it, find another tool.

**Comment by SmiVan** [comment]
This doesn't request anything that would turn draw.io into an SVG editor, changing colors of elements is already standard functionality in draw.io - it's just that here it's implemented in an inconsistent manner that requires manual tweaking to use.
