### ISSUE TITLE
Unable to authorize draw.io in gitlab on main instance app.diagrams.net

### ISSUE THREAD

**Issue by agaget** [jgraph/drawio#2474]
I globally have the same problem as here https://github.com/jgraph/drawio/issues/2348 , blank page when I'm trying to authorized the applications. 
(after that)
![image](https://user-images.githubusercontent.com/25428659/144829845-055d0204-0e87-49e6-82f8-76189ee50cbf.png)

Except that I want to use the main instance app.diagrams.net/ so I can't really change things on container or all that stuff. Is this corrected on the main instance or is there something to do?

My address is something like that
`https://app.diagrams.net/?gitlab=https://myInstance-gitlab.fr&gitlab-id=<myId>`

my application
![image](https://user-images.githubusercontent.com/25428659/144830663-d7324cd8-bf50-46b6-86b5-7ea9b1d45831.png)

removing the '.html' allow me to avoid the URI Redirection error

Thanks for your help

**Comment by davidjgraph** [comment]
drawio version? Environment setup?

**Comment by agaget** [comment]
version is the version you've deployed here : app.diagrams.net/ 15.9.1
Firefox 94.0.2
WIndows 10 enterprise V20H2

**Comment by davidjgraph** [comment]
Gitlab version?

**Comment by agaget** [comment]
oups sorry:
14.3.6

**Comment by davidjgraph** [comment]
We don't support this set up. You'd have to host draw yourself and set the URL, ID and secret on that project.

**Comment by agaget** [comment]
> We don't support this set up. You'd have to host draw yourself and set the URL, ID and secret on that project.

What is not supported ? if gitlab version were higher or lower it would work ?

**Comment by davidjgraph** [comment]
Mapping your Gitlab to our instance is not support. Thus "You'd have to host draw yourself".

**Comment by agaget** [comment]
Is not supported anymore ? It was supported 2 years ago : https://github.com/jgraph/drawio/issues/493#issuecomment-518574864

**Comment by davidjgraph** [comment]
Gitlab remove implicit grant in 14.x, this requires flow to go via the server and the secret to be kept there.

**Comment by davidjgraph** [comment]
@alexanderpetrenz Please open a new issue.
