### ISSUE TITLE
Is there any chance that drawio can have the support for the Wacom Digital plate?

### ISSUE THREAD

**Issue by Kellermaan** [jgraph/drawio#2475]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

I'm wondering is there any chance that drawio can have the support for the Wacom Digital plate.
I think it would be perfect that we can use digital plate in drawio.

Thanks.

**Comment by davidjgraph** [comment]
No, we don't have one.

**Comment by Kellermaan** [comment]
I recently found out excalidraw is supported for Digital plate (it means we can have a pen to edit it, and it can show our hand writing), do we have plan to support it? using a pen to draw something is really useful. Thanks!!!!!

**Comment by Kellermaan** [comment]
@davidjgraph Thanks !!!
