### ISSUE TITLE
Can't reduce text of a rectangle under 12 pt

### ISSUE THREAD

**Issue by bphd** [jgraph/drawio#2478]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Related to https://github.com/jgraph/drawio/issues/315 and https://github.com/jgraph/drawio/issues/25

**Comment by bphd** [comment]
Heres a workaround https://github.com/jgraph/drawio/issues/315#issuecomment-988748378, but it still needs a solution

**Comment by davidjgraph** [comment]
Please post a bug report.

**Comment by bphd** [comment]
It should be followed on #315

**Comment by davidjgraph** [comment]
Where are the reproduction steps and environment details, I don't see them.
