### ISSUE TITLE
Template with some Custom Libraries  problems

### ISSUE THREAD

**Issue by reproteq** [jgraph/drawio#248]
any way to save a custom template with several custom libraries?
i can only save template with 1 lib not more.
if I import them one by one there are no problems, but I need to make one with several and it does not leave me.

it is important for me to be able to save a file with several libraries of my own, but I do not know how and I have tried many things

**Comment by davidjgraph** [comment]
Please detail the exact steps you followed, what the result(s) that you saw were and what result(s) you expected.

**Comment by reproteq** [comment]
i make new lib and save it, after i can import lib and work without problems , but i need open new file and autoload  more 1 lib. i dont want load 1 to 1 librari because i make severals.
i tried 
http://127.0.0.1/?splash=0&clibs=pathtolib1.xml

but dont work
