### ISSUE TITLE
"Copy" in the menu "Edit" does not work for text

### ISSUE THREAD

**Issue by chTom79** [jgraph/drawio#2481]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I do not know if this is a bug or if this works as designed
When using the "Paste" function from the menu "Edit" text is not pasted. It only works shapes/lines.
(I know, "normal" people use Ctrl+C / Ctrl+V :-) )

**To Reproduce**
1. Insert shape
2. Write text to shape
3. copy text via the menu "Edit" or by pressing Ctrl+C
4. paste the text via the menu "Edit" -> "Paste"

-> No text is pasted

**Expected behavior**
One would expect that this works for text, too. Not only for shapes/lines.

**draw.io version (In the Help->About menu of the draw.io editor):**
15.9.1

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox Version 94.0.2
 - Microsoft Edge Version 96.0.1054.43
 - Google Chrome Version 96.0.4664.45

Thanks, Tom

**Comment by mararad** [comment]
In order to copy and paste text only (and not a shape with text) just double click text to select it and then use Ctrl+c/Ctrl+v 

Does this help?
