### ISSUE TITLE
Arrow End select drop-down does not show all options until Arrow Start drop-down is opened

### ISSUE THREAD

**Issue by kghamilton89** [jgraph/drawio#2482]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Arrow End select drop-down does not show all options until Arrow Start drop-down is opened.

**To Reproduce**
1. Create two shapes.
2. Connect them via arrow.
3. Open the Arrow End select option drop-down (by default, this is the arrow head shape on the right menu). Not all options are present.
4. Open the Arrow Start select option drop-down (by default, this is the arrow tail shape on the left menu). All options are present
5. Open the Arrow End select drop-down again. All options are present.

**Expected behavior**
All Arrow End options are available without opening the Arrow Start option drop-down

**Screenshots**

Step 3

![Step 3](https://i.imgur.com/tE85o5L.png)

Step 4

![Step 4](https://i.imgur.com/40iUZTW.png)

Step 5

![Step 5](https://i.imgur.com/bia4X62.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 15.9.4 (draw.io integration inside of Confluence Cloud)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by mararad** [comment]
Reproduced in FF 95.0 (64-bit) and Chrome Version 96.0.4664.93 with 15.9.4, Win 10 Pro.

To fully expand line end drop down, drop down should be clicked twice or click line start first.

https://user-images.githubusercontent.com/44292306/145387694-f1ca59a3-76f6-4ebb-9998-33921645a819.mp4

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by davidjgraph** [comment]
16.0.0
