### ISSUE TITLE
Confluence cloud integration - links are not clickable 

### ISSUE THREAD

**Issue by vukasin-nikodijevic** [jgraph/drawio#2483]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Links created on the graph objects are not clickable once rendered in confluence cloud page.

**To Reproduce**
1. Create graph and add links to the objects
2. Return to the Confluence Cloud page 
3. In rendered graph view, click on object with added link
4. It should follow the link but it doesn't

**Expected behavior**
Once object with attached link is clicked, link should be followed (in same or new page). If I inspect further, rendered preview diagram is nothing but plain SVG object.

**draw.io version:**

- draw.io version [15.9.4]

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [FireFox]
 - Version [94]

**Comment by mararad** [comment]
Are you having this issue with internal Confluence links only? Are external links working?

**Comment by vukasin-nikodijevic** [comment]
> Are you having this issue with internal Confluence links only? Are external links working?
> 

All links I've configured are internal from confluence. 

I'll check later today external links.

**Comment by ashrafteleb** [comment]
We tested the links and couldn't reproduce. Can you please share a sample link you used, the diagram file, and any errors in the console?
Thanks
