### ISSUE TITLE
SVG viewBox= width= height= are incorrectly modified by clipSvgDataUri

### ISSUE THREAD

**Issue by josedacosta** [jgraph/drawio#2484]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The SVG viewBox= width= height= are incorrectly modified by clipSvgDataUri.

**To Reproduce**
1. Please create a .svg text file with this SVG code:`<svg viewBox="0 0 45 45" xmlns="http://www.w3.org/2000/svg"><circle cx="22.5" cy="22.5" fill="#57d9a3" r="21" stroke="#0052cc" stroke-miterlimit="10" stroke-width="3"/></svg>`
2. Drag and drop the file in draw.io the editor
3. Here is the result in the data shape:
`data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjEuNSAxLjUgNDIgNDIiIHdpZHRoPSI0MiIgaGVpZ2h0PSI0MiI+PGNpcmNsZSBjeD0iMjIuNSIgY3k9IjIyLjUiIGZpbGw9IiM1N2Q5YTMiIHI9IjIxIiBzdHJva2U9IiMwMDUyY2MiIHN0cm9rZS1taXRlcmxpbWl0PSIxMCIgc3Ryb2tlLXdpZHRoPSIzIi8+PC9zdmc+`
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="1.5 1.5 42 42" width="42" height="42"><circle cx="22.5" cy="22.5" fill="#57d9a3" r="21" stroke="#0052cc" stroke-miterlimit="10" stroke-width="3"/></svg>`

**Expected behavior**
As you can see the dimensions are not correct :
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="1.5 1.5 42 42" width="42" height="42"><circle cx="22.5" cy="22.5" fill="#57d9a3" r="21" stroke="#0052cc" stroke-miterlimit="10" stroke-width="3"/></svg>`
Same thing, if I uncheck "Responsive" I am responsive in Illustrator
`<svg id="Calque_1" data-name="Calque 1" xmlns="http://www.w3.org/2000/svg" width="45" height="45" viewBox="0 0 45 45"><defs><style>.cls-1{fill:#57d9a3;stroke:#0052cc;stroke-miterlimit:10;stroke-width:3px;}</style></defs><circle class="cls-1" cx="22.5" cy="22.5" r="21"/></svg>`

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version : https://app.diagrams.net & desktop 15.8.7

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 96.0.4664.93

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
