### ISSUE TITLE
Previews for drawio files show up outdated and inaccurate

### ISSUE THREAD

**Issue by alizainmerchant** [jgraph/drawio#2486]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When viewing a drawio document via the Google Drive UI, the documents that show a preview sometimes show a preview that is outdated. When opening the same document via the diagrams.net UI the most up to date version loads; however, when comparing the document that loads on the diagram.net UI to the previews on the Google Drive UI, there are inconsistencies. This is a substantial issue as we ask users to train on diagram documents and the users may only reference the preview instead of the document on the diagrams.net UI. This could mean they're being trained on outdated processes. 

By "preview" above I mean the thumbnail of the document on the Google Drive UI AND when you double click the document and see a blown up version of that preview (but still on the Google Drive UI). When you double click and see the blown up version of that preview, at the top there is an option to open that file via another application, when clicking the "Open with diagrams.net" you're redirected to diagrams.net where you see the most accurate version. 

Another thing to note is after an arbitrary amount of time the previews for the documents get updated and match the document in the diagrams.net UI

**To Reproduce**
1. Go to Google Drive > drawio document
2. Click (once) on drawio document > Notice thumbnail on the right side of Google Drive UI inside "details" (outdated at times)
4. Click (twice) on drawio document > Notice blown up preview of document (also outdated at times, esp. if above is true)
5. Click the "Open with driagrams.net" on the top (after double clicking document)
4. Compare document from Step 5 with Step 4 and/or Step 3

**Expected behavior**
The documents should match, but sometimes do not. As mentioned above, after some time has passed the document previews are up to date.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 15.9.1

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.3.1
 - Browser chrome and safari

**Smartphone (please complete the following information):**
 - N/A

**Additional context**

**Comment by mararad** [comment]
Details related to user's question here: https://github.com/jgraph/drawio/issues/1758

**Comment by davidjgraph** [comment]
We don't have any current ideas on how to solve this issue.
