### ISSUE TITLE
Error : The Content-Range header length does not match the provided number of bytes 

### ISSUE THREAD

**Issue by tomylee78** [jgraph/drawio#2487]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I save the Draw.io project into OneDrive or Google Drive by [app.diagrams.net](https://app.diagrams.net) , and the navbar pop-out  the alert like this: [Unsaved changes](https://i.imgur.com/63710d6.png)

and I click the yellow button and Draw.io show this message [Error saving file : The Content-Range header length does not match the provided number of bytes.](https://i.imgur.com/PLlh3UY.png)

I click the "try again" button but Draw.io can't save this project loop.

**To Reproduce**
1. use a lot of UML object and screenshot in [app.diagrams.net](https://app.diagrams.net). Please [click this to see the screen](https://i.imgur.com/QYFNJlt.png)
2. [duplicate this page to 5 page ](https://i.imgur.com/A2JNOPS.png)
3. [Draw.io pop-out error message in navbar](https://i.imgur.com/63710d6.png)
4. Click this error button
5. pop-out the error message :  [Error saving file : The Content-Range header length does not match the provided number of bytes.](https://i.imgur.com/PLlh3UY.png)
6. Click "try again" button but Draw.io can't save this project and show this error message loop.

**Expected behavior**
I can save this Draw.io project.

**Screenshots**
Please see upper url.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 15.9.4

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional
 - Browser: Chrome 
 - Version 96.0.4664.93 64 bit

**Smartphone (please complete the following information):**
no use smartphone

**Additional context**

【 ***Please note this***】

When I rename page name to number, it can save [like this](https://i.imgur.com/JDjvXIj.png).

Or delete one page but no change page name, it can save [like this](https://i.imgur.com/gMHRudL.png).

**Comment by davidjgraph** [comment]
@mararad please check with file > 4MB

**Comment by mararad** [comment]
I created the 4.8 MB file. Tested in Chrome Version 96.0.4664.93 (Official Build) (64-bit), Win 10 Pro and diagrams.net 15.9.4

* Reproduced the error when I tried to save it to OneDrive in Chrome.
![error in onedrive chinese page title](https://user-images.githubusercontent.com/44292306/145817624-69b2c0f2-df9a-4ada-af38-e4dbcd39511a.JPG)

* When diagram pages were renamed to simply 1,2,3,4 and 5 there were errors in console but the file was saved to OneDrive
![saved in onedrive and simple page names](https://user-images.githubusercontent.com/44292306/145817979-64c8bae7-5357-442d-9517-3da320a5587d.JPG)

* The same file was saved to Google Drive successfully
![saved to drive](https://user-images.githubusercontent.com/44292306/145818275-bd524b09-0305-470e-812e-2a4edc2846a6.JPG)

**Comment by tomylee78** [comment]
@mararad @davidjgraph   Thank's for your reply.

Please see [this test VOD](https://youtu.be/TNEnPe9kQsQ) and use [this test project](https://1drv.ms/u/s!Aj0RxDSWKIl0jFdA6yvifXQVQb9E?e=0ZNczg). 

This draw.io project is changed screenshot photo to desktop background and replace some keywords by our original project.

I save this test project and share you test, you can refer to these reference.
