### ISSUE TITLE
Can't write into the "tab" of the package element

### ISSUE THREAD

**Issue by floriankraemer** [jgraph/drawio#2489]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

I can't write into the "tab" of the package element.

**To Reproduce**
1. Go to the search box
2. Enter "package"
3. Place the package element
4. Try to click on it everywhere to get the cursor into the tab

**Expected behavior**
My expectation is that I could write in the tab and the body of the element.

**Screenshots**
![image](https://user-images.githubusercontent.com/4996022/145905904-b677a419-3cac-4353-8d2d-e209f14fbcde.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- diagrams.net 15.8.7

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by egrimate** [comment]
In the next release, there will be a new Package shape in UML 2.5 where you will be able to edit both the header and body. Just search for Package and use the one that has "Text" in the body.
