### ISSUE TITLE
Diff-sync in embed mode over JSON protocol

### ISSUE THREAD

**Issue by jvdassen** [jgraph/drawio#2491]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The diff-sync (#644) feature of drawio works great to enable collaboration using storage providers such as Google Drive etc. It would be great if this feature could be exposed using the JSON protocol available in the [embed mode](https://www.diagrams.net/doc/faq/embed-mode). However, according to the documentation, it seems that this is not yet possible. It also appears that other applications (e.g. vscode-drawio) solve this issue by forking and modifying the editor component of drawio. In another third-party app (nextcloud-drawio), one of the maintainers [stated](https://github.com/pawelrojek/nextcloud-drawio/issues/14#issuecomment-778674225) that diff-sync can already be used in embed mode (at least what I understood of that):
> But if you're already using embed mode, that's the method by which you enable collab editing. I think we added this for th VSCode extension people, but they didn't use it. 

Thus, having a means to retrieve diffs based on specific events (e.g. autosave, explicit action) and to load/apply these diffs at another instance would be highly useful to use the collaborative feature of this tool in embed mode.

**Describe alternatives you've considered**
As of now, from the documentation it appears that the only way to use collaboration in embed mode is to use the `export` and `merge` actions on the full model.

**Additional context**

**Comment by scottxusayhi** [comment]
+1 for this feature.
