### ISSUE TITLE
Prettyprinting of the Edit Style box

### ISSUE THREAD

**Issue by floongle** [jgraph/drawio#2492]
* [ ✔] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ✔] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the solution you'd like**
As a user, I would like to see the contents of the "Edit Style" (and similar) boxes presented in a more  human-readable way.

For example, instead of:
`rounded=0;whiteSpace=wrap;html=1;fontFamily=Helvetica;fontSize=12;strokeColor=#9673a6;fillColor=#e1d5e7;fontColor=#CC0000;fontStyle=1;horizontal=0;points=[[0,0.95],[1,0.95]];`

The Edit Style data could be presented with newlines and indentation (pretty-printed):
`rounded=0;`
`whiteSpace=wrap;`
`html=1;`
`fontFamily=Helvetica;`
`fontSize=12;`
`strokeColor=#9673a6;`
`fillColor=#e1d5e7;`
`fontColor=#CC0000;`
`fontStyle=1;`
`horizontal=0;`
`points=[`
`    [0,0.95],`
`    [1,0.95]`
`    ];`

This would mean that the user wouldn't be presented with a block of wrapped text, but instead could better comprehend the JSON.

**Describe alternatives you've considered**
Expanding on this, the various style groupings (font related / stroke related / fill related / etc.) could be auto-grouped with gaps.

**Comment by davidjgraph** [comment]
This would require an additional dependency to implement and I am very anti-dependencies, so declining. But thanks for taking the time to submit.
