### ISSUE TITLE
Ruler text issue

### ISSUE THREAD

**Issue by Emanuel65** [jgraph/drawio#2494]
Except for color, any changes to the font of a ruler, are applied only to the first number, the others remain unchanged.
And changing the orientation from horizontal to vertical really messes things up.

![draw io_e1kJ2JqMAA](https://user-images.githubusercontent.com/72375458/103938723-62574300-5133-11eb-95ca-21973698fe73.png)

**Comment by davidjgraph** [comment]
Is this still valid @mararad ?

**Comment by mararad** [comment]
@davidjgraph Yes. Checked in Chrome Incognito and FF with 20.0.4 
Colour of numbers can be changed but the rest e.g font family, font size and weight can't.
