### ISSUE TITLE
Cannot insert diagram into GoogleDocs

### ISSUE THREAD

**Issue by margru** [jgraph/drawio#2497]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Inserting a diagram into a GoogleDocs document is not working.

**To Reproduce**
1. Create a new Google document in GoogleDocs
2. Click on Plugins-> diagrams.net -> Insert Diagrams
3. Select an existing diagram on Google Drive
4. See the box with the title "Select files" and progress bar and "Inserting Diagram..." forever

**Expected behavior**
I expect the diagram is inserted into the document.

**Screenshots**
![diagrams_net_error_insert_google_docs](https://user-images.githubusercontent.com/1311837/146578373-79f7ac90-a7ea-44d8-b582-01835fbed7e3.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 15.8.6]

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 64bit
 - Browser: Chrome
 - Version: 96.0.4664.45 (and 96.0.4664.110)

**Comment by davidjgraph** [comment]
Can you share the diagram that caused the issue. Does it happen for a trivial diagram, like a rectangle? All browser extensions switched off?

**Comment by margru** [comment]
@davidjgraph It happens even for a trivial diagram. I tried it in an anonymous mode and it worked. So it seems that it indeed might be a conflict with any browser extension I have installed and enabled... I didn't try to switch them off as previously it was working with them and I haven't installed any new extension recently.

**Comment by davidjgraph** [comment]
If it works incognito it's a browser state problem, either extensions, cookies or cache.

Extensions can update at any time and break things.
