### ISSUE TITLE
Text tool can resize the UI

### ISSUE THREAD

**Issue by stefnotch** [jgraph/drawio#250]
The text tool can be used to resize the UI text.

## Steps to reproduce
1. Add some text
2. Double click on it
3. Select a part of the UI's text
4. Change 8 pt to some other number

![image](https://user-images.githubusercontent.com/10220080/39578784-65b3150e-4ee5-11e8-9f17-c4c424ef2a35.png)
![image](https://user-images.githubusercontent.com/10220080/39578822-83177914-4ee5-11e8-958c-88d2c0e2b96a.png)

Browser: Firefox

**Comment by alderg** [comment]
Thanks for the report, this will be fixed in the next release.
