### ISSUE TITLE
How to set labelBackgroundColor in the configuration for Confluence Server

### ISSUE THREAD

**Issue by bandantonio** [jgraph/drawio#2502]
Hello,
I'm trying to configure default styles for shapes and I would like to remove white background for labels.

When I open shape style (Cmd + E), I see this setting: `labelBackgroundColor=#ffffff;`, after deleting background via UI, this setting changes to `labelBackgroundColor=none;`. Good. According to [this guide](https://www.diagrams.net/doc/faq/configure-diagram-editor#format) (Format section -> `defaultVertexStyle` or `defaultEdgeStyle`), the `labelBackgroundColor` should work properly in config:

> To find the key/value pairs to be used, set the style in the application and find the key and value via Edit Style (Ctrl+E) (6.5.2 and later). For example, to assign a default fontFamily of Courier New to all edges and vertices (and override all other default styles), use `{"defaultVertexStyle": {"fontFamily": "Courier New"}, "defaultEdgeStyle": {"fontFamily": "Courier New"}}`.

I was trying this:

```
"defaultVertexStyle": {
    ...
    "labelBackgroundColor": null
  },
```

and this

```
"defaultVertexStyle": {
    ...
    "labelBackgroundColor": "none"
  },
```
and even this
```
"defaultVertexStyle": {
    ...
    "labelBackgroundColor": "#f00"
  },
```

None of the above worked. It seems that this setting is simply ignored.

What am I doing wrong, and is it possible to set `labelBackgroundColor` in Confluence configuration?

* Plugin Version: 9.5.3
* draw.io Diagrams: 5023
* Confluence Server Version: 7.8.3

**Comment by ashrafteleb** [comment]
Hello,

I've tried the following configuration and it works
![Screen Shot 2021-12-21 at 8 20 27 AM](https://user-images.githubusercontent.com/24944765/146936747-136380e0-794b-4b42-8035-489c084d1006.png)

Can you please show us the exact full configuration and which shape is used to test with?

Thanks

**Comment by bandantonio** [comment]
@ashrafteleb Thanks.

Yes, moving the `labelBackgroundColor` to the top **did work**, I was able to see red background after setting the option to `#f00`.

But my problem is that I can't unset this option - `"labelBackgroundColor": "none"`, `"labelBackgroundColor": null`, or even `"labelBackgroundColor": null` **didn't work.**

The exact configuration:

Variant 1:
```
  "defaultVertexStyle": {
    "labelBackgroundColor": "none",
    "fontFamily": "Verdana",
    "fontSize": "14",
    "fillColor": "#bec5ff",
    "strokeColor": "#2f3133",
    "strokeWidth": "2",
    "rounded": 1,
    "fontColor": "#000"
  }
```
Variant 2:
```
  "defaultVertexStyle": {
    "labelBackgroundColor": null,
    "fontFamily": "Verdana",
    "fontSize": "14",
    "fillColor": "#bec5ff",
    "strokeColor": "#2f3133",
    "strokeWidth": "2",
    "rounded": 1,
    "fontColor": "#000"
  }
```

<img width="139" alt="draw io" src="https://user-images.githubusercontent.com/16765690/156365230-d2615d3d-13d5-4f6d-82da-231ef5bef81f.png">

**Comment by ashrafteleb** [comment]
The issue with BPMN shapes is they already define labelBackgroundColor in their style. The default configuration only applies to shape without that style.

I'll open a new issue as a feature request to change BPMN shape and remove labelBackgroundColor from their styles.
https://github.com/jgraph/drawio/issues/2674
