### ISSUE TITLE
Unknown error - Script error (stats.pusher.com)

### ISSUE THREAD

**Issue by Austin91TX** [jgraph/drawio#2504]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Upon opening my diagrams which contain 6 pages, I get an "Unknown error - Script error"
dev tools tell me Uncaught TypeError: Cannot read properties of undefined (reading 'receive') at stats.pusher.com/timeline/v2/jsonp/1?

**To Reproduce**
1. Go to https://app.diagrams.net/#G1vnJ6jy3Fle7L42OBC934Zte4UyRoJZ3y
2. Click on '....' (error pops up here before clicking anything)
3. Scroll down to '....' (NA)

**Expected behavior**
No error message

**Screenshots**
![Unknown error - Script error](https://user-images.githubusercontent.com/42754811/146992838-b910d4c2-f385-4e3c-98e6-85a2f6b83987.PNG)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 16.0.2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 96.0.4664.110

**Smartphone (please complete the following information):**
N/A

**Additional context**
It seems that an adblocker prevents this issue. Using Brave browser helps as well which I assume is due to it's built in adblock

**Comment by davidjgraph** [comment]
Fixed in 16.0.3
