### ISSUE TITLE
export to png/jpg with zoom 400% results in a blank picture

### ISSUE THREAD

**Issue by bellemere** [jgraph/drawio#2508]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
export to png/jpg with zoom 100% is OK, but with zoom over 100% results in a blank picture.

**Screenshots**
![image](https://user-images.githubusercontent.com/9478533/147292146-baa60778-fbfa-474e-912a-57b3d03eb5d0.png)
![image](https://user-images.githubusercontent.com/9478533/147292208-8b5641e9-8a42-4c95-9761-1f531c439400.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 
- [16.0.2]

**Desktop (please complete the following information):**
 - OS: [macOS Monterey 12.1]
 - Browser [chrome]
 - Version [Version 96.0.4664.110 (Official Build) (x86_64)]

**Comment by mararad** [comment]
If you update diagrams.net version to the latest 16.0.3 does it help?
If not, try File > Export as > Advanced > PNG

I tested this in the latest Chrome and it is working at my place, but I am a Win user so might be related to OS

**Comment by bellemere** [comment]
> If you update diagrams.net version to the latest 16.0.3 does it help? You can just do hard reload in order to get the latest versison. If not, try File > Export as > Advanced > PNG
> 
> I tested this in the latest Chrome and it is working at my place, but I am a Win user so might be related to OS

Sorry this still doesn't work. I tried exporting using the web, which didn't work either.
Maybe it's my drawio file's problem.
Can I post my drawio file to you?

**Comment by mararad** [comment]
Sure. you can add it and I'll test it.
Meanwhile you can test it again in diagrams.net 16.1.0 (just hard reload and you should see updated version)

Does export also fail in the desktop app if you use it?

Thanks,

**Comment by bellemere** [comment]
> Sure. you can add it and I'll test it. Meanwhile you can test it again in diagrams.net 16.1.0 (just hard reload and you should see updated version)
> 
> Does export also fail in the desktop app if you use it?
> 
> Thanks,

Sadlly I've tried the desktop app and the web app both, but none works as expected.
Also I've tried v16.1.0, but the problem still exists.

Here is the file link:
[https://ln5.sync.com/dl/a2bbcd760/thx3s5qb-r7cz7m68-gx2tiwwv-8enc8ktv/view/default/10789547020006](file link)

I'm not quite sure it's the file problem or the platform problem.

Thanks for your reply and your work, this app is amazing and really helps me a lot on reading the source code of some projects.

**Comment by mararad** [comment]
Thanks for the file.

We couldn't reproduce the issue with your file on macOS Monterey 12.1. Export is working.
Is it possible to test export on another machine? Sounds like there is something at your place interfering with the process.

Thanks,

**Comment by bellemere** [comment]
> Thanks for the file.
> 
> We couldn't reproduce the issue with your file on macOS Monterey 12.1. Export is working. Is it possible to test export on another machine? Sounds like there is something at your place interfering with the process.
> 
> Thanks,

I tried on my Fedora laptop, it works.
I think it's my mac's problem. I'll export it on my Fedora in the future.
Sorry bothering you.
