### ISSUE TITLE
Layout issues [Minimal theme + German language]

### ISSUE THREAD

**Issue by ImperiaGP** [jgraph/drawio#2509]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When you change the application theme to Minimal and the language to German, some of the buttons and dropdown texts are not fully visible.
The steps to reproduce below will navigate through all the affected screens, the screenshots below will show the issues themselves (marked in red)

**To Reproduce**
1. Go to 'Extras -> Theme -> Minimal'
2. Click on 'OK' and press F5
3. Go to 'Diagram -> Preferences -> Language -> Deutsch'
4. Click on 'OK' and press F5
5. Go to 'Diagramm -> Neu -> Erstellen'
6. Issue 1: Go to 'Diagramm -> Einstellungen -> Plugins...'
7. Click on 'Abbrechen'
8. Issue 2: Go to 'Diagramm -> Speichern -> Speichern unter...'
9. Click on 'Schließen'
10. Issue 3: Go to 'Diagramm -> Exportieren als -> URL...'
11. Click on 'Abbrechen'
12. Issue 4: Go to 'Diagramm -> Exportieren als -> Verknüpfung...'
13. Click on 'Abbrechen'
14. Issue 5: Go to 'Diagramm -> Exportieren als -> HTML...'
15. Click on 'Abbrechen'
16. Issue 6: Go to 'Diagramm -> Exportieren als -> Einbetten -> IFrame...'
17. Click on 'Abbrechen'
18. Issue 7: Go to 'Diagramm -> Exportieren als -> Einbetten -> Notion...'
17. Click on 'Abbrechen'

**Expected behavior**
Buttons and text should be fully visible

**Screenshots**
### Issue 1:
![image](https://user-images.githubusercontent.com/6501352/147406358-d7920754-80d5-4e58-ab27-eafe0566cea6.png)
### Issue 2:
![image](https://user-images.githubusercontent.com/6501352/147406468-245bb3d2-1eb9-48ba-afa5-55282e0da093.png)
### Issue 3:
![image](https://user-images.githubusercontent.com/6501352/147406579-77210055-5761-4e92-85fe-6d4b9ab1f12f.png)
### Issue 4:
![image](https://user-images.githubusercontent.com/6501352/147406609-4d4bf5f4-e387-4424-9b11-c6e16c0e9a56.png)
### Issue 5:
![image](https://user-images.githubusercontent.com/6501352/147406634-edbd7af3-ac78-4fa0-b0c3-d799fc5d1a55.png)
### Issue 6:
![image](https://user-images.githubusercontent.com/6501352/147406692-63175802-1964-42e0-a84c-1f26d4a9119b.png)
### Issue 7:
![image](https://user-images.githubusercontent.com/6501352/147406706-b9a2ef91-9763-40e1-b11c-39c4808832a2.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version = 16.1.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 95.0.2

**Smartphone (please complete the following information):**
N/A

**Additional context**
The dialog window from Issue 5 can also be opened via 'Diagramm -> Exportieren als -> Einbetten -> HTML...'
I suspect it is the same dialog window.

**Comment by mararad** [comment]
Thanks. 

I tested in Chrome Version 96.0.4664.110 (Official Build) (64-bit) and FF with 16.1.0 and you are right. The same "cut off" letters are also in Automatic theme in German.
All fields are displayed well in English.

P.S 'Diagramm -> Einstellungen -> Plugins...' - if you scroll down, do you see the button"Anwenden"?

**Comment by alderg** [comment]
This will be fixed in the next release.
