### ISSUE TITLE
[feature] Save to Synology NAS server

### ISSUE THREAD

**Issue by waylonwang** [jgraph/drawio#251]
I want my diagrams to be saved to my Synology NAS server and I can read diagrams from my Synology NAS server when opening files

**Comment by lsp0701** [comment]
the feature is accessible now ？

**Comment by AndreiCherniaev** [comment]
Let's ask Synology to add draw.io to Synology Drive! Vote in [community.synology.com](https://community.synology.com/enu/forum/1/post/196002)
