### ISSUE TITLE
Apple Pencil use has interrupted line detection at start of freeform stroke

### ISSUE THREAD

**Issue by bottbott** [jgraph/drawio#2510]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The Apple Pencil (2 in this case) is very helpful for sketches; however, the ability to use it in freeform mode doesn't seem to work well. When you attempt to initiate a stroke it draws a very short line and then seems to stop accepting input from the pencil. If you start your stroke very, very slow then it seems that you can continue that stroke at a regular speed. 

I've uploaded a video to Google Drive (link below) where you can see several attempted strokes that end up being very short lines, and then other strokes that were started very slowly and then are fully detected at a regular pace afterwards. 

**To Reproduce**
1. Turn on freeform drawing.
2. Try to draw with an Apple Pencil.

**Expected behavior**
Apple Pencil strokes should convert into a full stroke in draw.io. 

**Screenshots**
https://drive.google.com/file/d/1bgZdexVXN41_4a6BFLXBE8LLd_uliwde/view?usp=drivesdk 

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 16.1.0

**Desktop (please complete the following information):**
 - OS: iPad OS 15.1
 - Browser: Chrome
Google Chrome | 96.0.4664.101 (Official Build) stable (64-bit)
OS | iOS 15.1
User Agent | Mozilla/5.0 (iPad; CPU OS 15_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/96.0.4664.101 Mobile/15E148 Safari/604.1

**Comment by alderg** [comment]
This will be fixed in the next release. As a workaround, try sketch.diagrams.net for now.
