### ISSUE TITLE
document.body.appendChild replace with EditorUi.container.appendChild 

### ISSUE THREAD

**Issue by ArfanMirza** [jgraph/drawio#2511]
Feature required for Node-Webpack library Project. [https://github.com/ArfanMirza/drawio](url)

Draw.io is built as SPA using Javascript framework, this beauty is required in Angular CLI project as a component instead of the whole page application and mostly it will be used with other components in Dashboard.

Right now every div append to `document.body` and add `geEditor` class for global CSS integration.

In Angular CLI each div is appended to the component's selector-div as a child, so when draw.io is used in component few problems are created for example

On-Page navigate:

- Layer/outline box panel did not disappear on Draw.io deletion because that is appended to `document.body` not component's selector-div
- Rulers append to `document.body` instead of component's selector-div, this did not fit into draw.io page

There is a few more other problem that breaks draw.io full functionality.

```
EditorUi = function(editor, container, lightbox) 
this.container = container || document.body;
```

It will the best if the `EditorUi.container` is used to append all div instead of the `document.body`

**Comment by davidjgraph** [comment]
Declined
