### ISSUE TITLE
Column / Row Lines still shown when table is collapsed.

### ISSUE THREAD

**Issue by Peeeet** [jgraph/drawio#2512]
If you create a new table with the table button in the toolbar (with "Title" box checked) and then set the "Collapsible" property to true, collapsing said table will still show row and column lines, unlike a "List" which properly collapses.
![image](https://user-images.githubusercontent.com/5926263/147604413-23fbea0e-e274-4194-9dd6-b6537d278328.png)

Problem also appears when adding a table from a library.  Example: "Table2" item from the included "Entity Relation" library.
![image](https://user-images.githubusercontent.com/5926263/147604432-8ef1f37f-dee2-41ab-ae08-e31963952939.png)

Using Diagrams.net 16.1.0 online in Google Chrome Version 96.0.4664.110 (Official Build) (64-bit) on Windows 10 LTSC 1809 Build 17763.2366

Tested in Incognito mode to disable any plugins or settings from my regular diagrams.net cookies, etc

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
