### ISSUE TITLE
[Same as note] Add new diagram inside a Diagram box and so on(Unique idea)

### ISSUE THREAD

**Issue by I2rys** [jgraph/drawio#2514]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
It's not really a problem but this might become useful to others too as It saves a lot of space like a lot.

**Describe the solution you'd like**
Basicly It's like a note but you can add a diagram in another diagram world/template inside a diagram box and I found it so useful because when stuff get tight you can use it to make to make connections easier and save a lot of space.

**Describe alternatives you've considered**
It's the same as note but the difference is that in note you can only write stuff to it but this idea you can make another diagram inside a diagram box and can make another diagram inside a diagram box inside a diagram box and so on.

**Additional context**
None.

**Comment by davidjgraph** [comment]
Thanks for the suggestion, but it's outside the scope of the project.
