### ISSUE TITLE
Snap to grid precision errors

### ISSUE THREAD

**Issue by NexusDarkshade** [jgraph/drawio#2515]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When snapping a line to the grid, the line and endpoints do not match to the grid's actual position (screenshot 1).

Additionally, the preview when moving the endpoint shows the point being placed off the grid (screenshot 2), and additional adjustment has to be done for the point to be aligned with the grid (screenshot 3), but the endpoint will still be misaligned on placement.

**To Reproduce**
Create a line.
while the grid is enabled, move an endpoint to a grid position.
Zoom in.

**Expected behavior**
It is expected that when moving a line endpoint to snap on the grid, it should stay on the grid.

**Screenshots**
![image](https://user-images.githubusercontent.com/43826341/147698914-1646f745-754d-4659-a1d8-118ab5b3f9e4.png)
![image](https://user-images.githubusercontent.com/43826341/147699398-87d76978-f880-4393-99d8-5baee66c5cf6.png)
![image](https://user-images.githubusercontent.com/43826341/147699432-9871f9de-e714-47a2-b95b-19e232833510.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 16.0.2

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 16.0.2

**Additional context**
I am using a grid step value of 8, with units set to meters.

**Comment by NexusDarkshade** [comment]
This can also be replicated by most objects when rotated 90 or 270 degrees.

**Comment by davidjgraph** [comment]
Second part is #2385
