### ISSUE TITLE
Add a custom editable often-use color panel

### ISSUE THREAD

**Issue by 1322739583** [jgraph/drawio#2519]
the color panel is fixed and i can't edit it.I want to add some often-use colors in the area。
![image](https://user-images.githubusercontent.com/7570668/147897802-4cdaaa66-f56e-4d27-a2f2-36574be61474.png)
I can't find the function to custom the colors.And it's hard to pick the color from the color history,because colors in the history panel will miss when time pass by。

Please support that fuction,thanks!

**Comment by alderg** [comment]
See https://www.diagrams.net/doc/faq/configure-diagram-editor

**Comment by 1322739583** [comment]
> 

thank you!
