### ISSUE TITLE
Graph broken when printing from offline version of draw.io

### ISSUE THREAD

**Issue by scr4bble** [jgraph/drawio#252]
I have installed the offline version of draw.io from rpm package and everythings worked great until I tried to print the graph into pdf.
Printing worked fine for three previous graphs so this one has probably something special inside.
When I save the same graph as xml and then reopen it again in offline draw.io - it is displayed nice, but when I export it into pdf, layout and text gets broken. After opening the XML file in online version, I see the broken layout immediately in the draw.io interface (compared to offline version where it is displayed fine)
Do you know why is this happening ?

OS: Fedora 27
rpm version: draw.io-8.4.7-144.x86_64

attached: xml file, pdf file and screenshot how it looks like in the offline draw.io.
XML file has .txt extension so github allows to update it - otherwise it is xml file as it was saved by draw.io

[testos_bus_sequence_diagram.txt](https://github.com/jgraph/drawio/files/1977913/testos_bus_sequence_diagram.txt)
[testos_bus_sequence_diagram.pdf](https://github.com/jgraph/drawio/files/1977911/testos_bus_sequence_diagram.pdf)
[screenshot from 2018-05-06 20-36-45](https://user-images.githubusercontent.com/6439904/39676587-a5fa3eaa-516d-11e8-9bfb-1705185e80f6.png)

**Comment by davidjgraph** [comment]
If still an issue please file current repo details at https://github.com/jgraph/drawio-desktop/issues
