### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'nodeType')

### ISSUE THREAD

**Issue by brandrsn** [jgraph/drawio#2520]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Getting an error message whenever I attempt to add a connector within a new or pre-existing document. "Uncaught TypeError: Cannot read properties of undefined (reading 'nodeType')."

**To Reproduce**
[See 30-second Loom video here](https://www.loom.com/share/2071784322eb4c8e8a310af7598a1d68).

**Expected behavior**
For this error not to happen! :-)

**Screenshots**
<img width="1290" alt="Screenshot 2022-01-03 at 15 39 37" src="https://user-images.githubusercontent.com/3390811/147950070-516087e5-c0aa-46c6-b3fd-a1330861bfc5.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: 16.1.3

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: Version 96.0.4664.110 (Official Build) (x86_64)

**Smartphone (please complete the following information):**
N/A

**Additional context**
Occurs in a regular browsing environment, after all Chrome extensions that been disabled, and in incognito.

Edit:
Google Drive file URL is here: https://drive.google.com/file/d/1yj6WYPE3mXJ-581sfDRo7V7BoMJz0wN-/view?usp=sharing

**Comment by davidjgraph** [comment]
Please clear cache https://app.diagrams.net/clear.html and try again

**Comment by brandrsn** [comment]
That's sorted it. Thank you @davidjgraph.
(I had tried to clear the cache through Chrome, but obviously it didn't work.)
