### ISSUE TITLE
Enabled support for TAM diagrams in the web version of app.diagrams.net

### ISSUE THREAD

**Issue by stiller-leser** [jgraph/drawio#2522]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

I would like to be able to draw diagrams using the TAM notation in the web version of diagrams.net as described in #899

**Describe the solution you'd like**

In order to do so I would like to be able to enable this plug-in in the web version of app.diagrams.net: https://github.com/ariel-bentu/tam-drawio in order to draw TAM diagrams on an iPad.

**Describe alternatives you've considered**

-

**Additional context**

The CSP of app.diagrams.net prevents me from directly loading the plug-in file from GitHub: https://raw.githubusercontent.com/ariel-bentu/tam-drawio/main/tam-drawio.js . As I know what I am doing, it would be very cool to allow this. Alternatively uploading this file from my local storage would also work just fine. Considering its size it could also be stored in my browser.

**Comment by davidjgraph** [comment]
app.diagrams.net isn't exactly the same thing as this project. There we have security reviews and the CSP enforces those conclusions, this is too risky a thing to do.

You can achieve this with the project, but you have to host it yourself.

**Comment by stiller-leser** [comment]
Hey @davidjgraph,

I am very impressed. That was lightning fast feedback! I actually managed to put the TAM diagram plugin into my own draw.io instance by modifying the app.min.js and host it on my own GitHub pages. The question now would be: Am I allowed to do this?

**Comment by davidjgraph** [comment]
Sure. You could also just specify the plugin as a URL parameter without modifying the JS. https://www.diagrams.net/doc/faq/supported-url-parameters
