### ISSUE TITLE
A more smooth/scaled zoom shortcut

### ISSUE THREAD

**Issue by Rentom12** [jgraph/drawio#2528]
Preflight Checklist
[ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
[x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Hi, I recently notice that when you use the "shortcut" for zooming in or out with the  Ctrl+Mousewheel the transition is from 100% to 265% or 40% to zoom in or out respectively. 

**Expected behavior**
A month or two ago, this was much smoother, like 100% to 125% for example and it was way better to work with and less uncomfortable. At least let us choose the ranges of the zooming or something.

Is there a justification, bug or just my pc?

Thx for reading :P

**draw.io version 16.2.4**
**Desktop**
 - OS: Windows
 - Browser Brave
 - Version 1.34.80 Chromium: 97.0.4692.71 (Build oficial) (64 bits)

**Comment by alderg** [comment]
The zoomsteps should be 100%, 120%, 145%, 175%. What mouse and OS version are you using? What if you try another browser (eg. Firefox, Chrome)?

**Comment by Rentom12** [comment]
> The zoomsteps should be 100%, 120%, 145%, 175%. What mouse and OS version are you using? What if you try another browser (eg. Firefox, Chrome)?

mouse: im using a razer trinity ( for like a year, so i doubt this is the problem)
and the OS is windows 11 

I tried in chrome, and it works as you mentioned, but I dont use that browser and it would be akward to use 2 browser when I could be doing my normal works in just one. 

Do someone know if this problem could be solved in some form?

**Comment by davidjgraph** [comment]
Unfortunately, Brave isn't a browser we test. Maybe a Brave user could take a look.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
