### ISSUE TITLE
Error "a.getData is not a function" when opening a library created from scratchpad

### ISSUE THREAD

**Issue by billybarnum** [jgraph/drawio#253]
I created a library by exporting from the ScratchPad. When I try to open it (from OneDrive) I get an error dialog ""a.getData is not a function" and the library is not loaded.

Here is the xml:

<mxlibrary>[{"xml":"zVfbjtowEP2aPHYVcuHyuGSX7cNW2gpVbR8NGRJ3HSZ1zCX79R3HbghJWEGhapGQPMf22D5nfAyOH2X7J8ny9BPGIBz/0fEjiahMK9tHIITjuTx2/AfH81z6Ot7sRO+g6nVzJmGtzpngmQlbJjZgkAJ+bkDwN/gg2ML0FqoUtncLUvElE/eCJ2uCMh7Hum/KLLCkhUESgDR0JXBH2IrTmv50hWs1p8SEDDwbz1jGRUnIRxBb0KmpI1WZ0IOoKXGzjiG2UZXBbkbHhZL4Cl95rFJCfD2ClopQoKy26z8OZ7MosmekrcP+JE8VZEl6AsxAyZKG2Ameb6eUdrQXmnhnF9fYwHDtpsCT1KadWIwVJk7q1AdVqGGF6RfJ78gAcQK/iUCpUkxwzcTjAW0R12CUDizLb83gOwXuXUjhD1CqtBKxjUItY539GTE/4r3B82Ti0qejiFbZ7F1v+Ij6AjdyaaHAQIrJBNRRXZ4hkATBFN8eZ7+G7aBzJeafnx1vSMfc6+p8YIotWAEdUXYpVzDPWXWsHV3pvmtx8gJdXNuz2Y1qO/BatR24ndqe9JT28AalHXbIFkjsVMSiZEmX5SJluW7mEpdQ0NLT63gvTLm7d24wCv9Mhyi6Toea9x5PCXqID29A/LBD/LsmA2KBu6a/VAB1pCj5G1HGxIW+UPuQ2/Uh2HNVWxS1L3eoM1wnvMZ1mhK5PRLV4Nn2ZNd4QU5L13dz0H53Ri3tzYnsrOZD3040biWaBMeJDA+dRPdSsrIxLNcDinc23F4nDFplaTIeirRm9ay6Hf2Vt9CWXV2F/+4tHP9Xb+G44xJfCrLTU568ycT9UmHTb5/ZAsQLFlxx1L6rNHFTodEpW74mlTYN9lbVp8ewF6gUZsf6iVby2u079n+DZ9IbDTr27N/mWaTw8JPfXIrmP4Jf","w":511,"h":215,"aspect":"fixed"}]</mxlibrary>

(xml tag hidden)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
