### ISSUE TITLE
Improve BPMN Service shape

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#2534]
At the moment it looks like this:
![mi](https://user-images.githubusercontent.com/44292306/148774734-fbefc57f-a75e-4596-b4a4-354f5ee0bf78.JPG)

And it should be (https://camunda.com/bpmn/reference/)
![service shape](https://user-images.githubusercontent.com/44292306/148774993-06d25e46-345b-4d8d-add5-4cba522cdeae.JPG)

**Comment by egrimate** [comment]
Will be in next release
