### ISSUE TITLE
Github intergration authorising issues

### ISSUE THREAD

**Issue by onceadrog** [jgraph/drawio#254]
Does Draw.IO really need full read/write access to all elements of your entire Github?
Surely it just needs to add/edit its own files?

> Repositories
> Public and private
> This application will be able to read and write all public and private repository data. This includes the following:
> 
> Code
> Issues
> Pull requests
> Wikis
> Settings
> Webhooks and services
> Deploy keys
> Collaboration invites

Discovered when trying to pin down issue with draw.io not connecting to Github.

Also seeing issue with draw.io not validating code on re-authorisation at url: https://www.draw.io/github.html?code=xxxxx

Browser: Chrome (latest update)
OS: Win10 (latest updates)

**Comment by cleartest-dirac** [comment]
when trying to export diagrams to Github, I get a prompt asking me to authorise in Github. After clicking the button to authorise I get to a url: https://app.diagrams.net/github.html?code=xxxxxxxxx that says this page will be closed automatically. 

I am going round and round in circles. Can someone please help?

**Comment by davidjgraph** [comment]
@cleartest-dirac Your issue is not the same as the original, please create a new one.
