### ISSUE TITLE
Cannot open XML file from URL (using the parameter “url=…” )

### ISSUE THREAD

**Issue by chetanakum92** [jgraph/drawio#255]
I try to open XML file from my server (for ex., xyz.com) but I got below error : 

> The requested URL for ex., xyz.com/proxy?url="xyz.com/demo.xml" was not found on my server.
> File not found

it's give proxy error on my server but on https://draw.io/ it's working fine.

here is example url's,
- https://draw.io/?url=http://www.xyz.com/demo.xml -> Working
- https://xyz.com/?url=http://www.xyz.com/demo.xml

Note : Here xyz.com is my server and try to use xml from another server

**Comment by jandusek** [comment]
I'm having the same issue. There is a ProxyServlet that should serve the `/proxy` url-pattern, however for some reason on my server it just returns HTTP 400 and I'm not sure how to debug it.

FWIW, my JS console says:
```
20:05:28.689 app.min.js:241 GET http://xyz.com/draw/proxy?url=http%3A%2F%2Fxyz.com%3A8080%2Fdraw%2Fstencils%2Ftemplates.xml 400 ()
mxXmlRequest.send @ app.min.js:241
get @ app.min.js:158
(anonymous) @ app.min.js:7964
(anonymous) @ app.min.js:3129
(anonymous) @ app.min.js:156
```

It seems it has compiled correctly:
```
$ ls -l ./WEB-INF/classes/com/mxgraph/online/ProxyServlet.class
-rw-r----- 1 tomcat tomcat 3687 May 16 08:23 ./WEB-INF/classes/com/mxgraph/online/ProxyServlet.class
```

And it is referenced from web.xml as it should:
```
$ grep ProxyServlet ./WEB-INF/web.xml -A2 -B2
  <servlet>
    <description/>
    <display-name>ProxyServlet</display-name>
    <servlet-name>ProxyServlet</servlet-name>
    <servlet-class>com.mxgraph.online.ProxyServlet</servlet-class>
  </servlet>
  <servlet-mapping>
    <servlet-name>ProxyServlet</servlet-name>
    <url-pattern>/proxy</url-pattern>
  </servlet-mapping>
```

Any hints on what else to try would be appreciated.

**Comment by jandusek** [comment]
It worked, thank you very much @alderg ! Any plans to make this a config option?

**Comment by alderg** [comment]
Not currently.

**Comment by mkdhabale** [comment]
I am facing same issue can you please tell me exactly where and what I need to change.
Thanks in advanced
