### ISSUE TITLE
Duplication of all items in the document (unable to determine cause)

### ISSUE THREAD

**Issue by thesuavehog** [jgraph/drawio#2550]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Frequently in my draw.io documents I delete an item only to realize there is a duplicate item below it. I then check other items and virtually all other items on my page are duplicated. I cannot drag-select and delete them as that will delete all copies not just the top copy. I have no idea how they got duplicated and it happens on virtually every drawing I create so it's not a "one time, oops, select all and duplicate" user-error.

To fix I have to select EVERY item in my document one by one and delete them to determine if they are duplicated or not.

**To Reproduce**

I am unable to determine how to reproduce this. It's something I notice after the fact when I go to delete an item an realize it has happened.

**Expected behavior**

There should not be a duplication of all items in the document without identification to the user this has happened

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: **16.2.6**

**Desktop (please complete the following information):**
 - OS: Windows 10 & 11
 - Browser: Edge, Chrome
 - Version: Currently my Chrome build is 97.0.4692.71 but it's not a new issue, has been happening for the year+ I have been using draw.io

**Comment by davidjgraph** [comment]
Is this a shared diagram with other people?

**Comment by thesuavehog** [comment]
It's on Google Drive so _technically_ but it's extremely rare that anyone other than I am editing my docs. It's also uncommon for them to view them at the same time I am in the docs as typically I export to PDF to attach to Jira or Slack messages.

It definitely happens when it's only my doc that no one else has or is accessing at the same time.

**Comment by davidjgraph** [comment]
Does this happen for diagrams created within, say, the last year? Or is it for diagrams created originally some time ago?

**Comment by thesuavehog** [comment]
Happens on most documents I create - and I create new ones probably once a week or so.

**Comment by thesuavehog** [comment]
If the next one I find with this issue doesn't have sensitive content I will attach it - but the only way I know it happens is when I move or delete something and the copy shows up below and then I realize it's a bunch of objects duplicated

**Comment by thesuavehog** [comment]
No draw.io plugins installed.
Different browsers I use have different combinations of extensions installed, but my most minimal Chrome browser that I have experienced the issue on contains only a couple of extensions:
* Application Launcher for Drive (by Google)
* Google Docs Offline
* LastPass
* Sheets (Chrome App)
* Slides 9Chrome App)

**Comment by Jckf** [comment]
Could this be happening because you're using ctrl + click to select multiple items, and accidentally move the cursor while clicking? I've found that Draw.io is _incredibly_ sensitive to this, and will duplicate loads of items pretty much every time I try to use ctrl to select multiple items, unless I make _absolutely sure_ that the cursor stays in the _exact_ same place when clicking. This is makes selecting multiple items very tedious.

**Comment by GregTonoski** [comment]
The bug still occurs: Windows 11, Chromium, Diagrams.net v. 23.1.5

It was reported already in 2018: https://webcache.googleusercontent.com/search?q=cache%3Agroups.google.com%2Fg%2Fdrawio%2Fc%2Fjdth0k8GI6k&sca_esv=a03cc0aa586dcb1e&ei=RvjYZbW5I9GswPAPhJS6wAg&ved=0ahUKEwi19IuTn8KEAxVRFhAIHQSKDogQ4dUDCBE&uact=5&oq=cache%3Agroups.google.com%2Fg%2Fdrawio%2Fc%2Fjdth0k8GI6k&gs_lp=Egxnd3Mtd2l6LXNlcnAiLmNhY2hlOmdyb3Vwcy5nb29nbGUuY29tL2cvZHJhd2lvL2MvamR0aDBrOEdJNmtIuQdQvQVYvQVwAXgAkAEAmAFvoAFvqgEDMC4xuAEDyAEA-AEBiAYB&sclient=gws-wiz-serp

**Comment by davidjgraph** [comment]
Given the time difference it's very unlikely to be the same underlying cause. Re-opening isn't correct for different cause, but same result, please open a new issue.

**Comment by GregTonoski** [comment]
Ok, I've opened the new issue: Diagram elements should not be duplicated after opening file .drawio #4217.
