### ISSUE TITLE
Allow pop-ups to avoid this dialog when choose Google Drive

### ISSUE THREAD

**Issue by huabin** [jgraph/drawio#2554]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Allow pop-ups to avoid this dialog

**To Reproduce**
1. Go to 'draw.io' and choose Google Drive
2. Click on 'Authorize'
3. See error

**Expected behavior**

**Screenshots**
![bug](https://user-images.githubusercontent.com/535675/149648305-ab785193-b543-4dc6-b60f-f1959652a879.jpeg)

**draw.io version (In the Help->About menu of the draw.io editor):**
on website draw.io

- draw.io version [e.g. 12.6.7]
on website draw.io

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Safari, Chrome, Duck
 - Version: All are latest.

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 15.3
 - Browser: Safari, Chrome, Duck
 - Version All are latest.

**Additional context**
Others work fine, e.g. choose OneDrive.

**Comment by davidjgraph** [comment]
So, allow pop-up on the site to avoid the error....
