### ISSUE TITLE
Actor parsing fails in mermaid sequence diagram

### ISSUE THREAD

**Issue by ShortArrow** [jgraph/drawio#2558]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

It's error message on https://app.diagrams.net version 16.2.6.

```
Error
Parse error on line 2: ... actor user as 😊 participant sit -----------------------^ Expecting 'SOLID_OPEN_ARROW', 'DOTTED_OPEN_ARROW', 'SOLID_ARROW', 'DOTTED_ARROW', 'SOLID_CROSS', 'DOTTED_CROSS', 'SOLID_POINT', 'DOTTED_POINT', got 'NEWLINE'
```

**To Reproduce**

The phenomenon reproduction code is shown below.

```mermaid
sequenceDiagram
    actor user as 😊
    participant site as 👷
    user ->>+ site : hello
    site -->>- user : see you
``` 

**Expected behavior**

It may need to be displayed well, such as https://mermaid.live/ .

![image](https://user-images.githubusercontent.com/16986253/149857663-0a8b3d5d-e916-41e5-b7e4-1089d294b6b3.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/16986253/149857789-587ab803-cb07-49c4-a890-b217bb900dd3.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 16.2.6

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : chrome
 - Version 97.0.4692.71 64bit

**Comment by davidjgraph** [comment]
We can't update mermaid currently because we're still supporting IE 11. Once we drop support for that in April 2022, we'll do an update.

**Comment by max-ostapenko** [comment]
@davidjgraph any idea when to expect the update?

**Comment by davidjgraph** [comment]
@max-ostapenko you're welcome to submit a PR with an updated Mermaid lib that works with IE 11.

**Comment by athenor** [comment]
Just ran into this, IE just ended support...

**Comment by ashrafteleb** [comment]
Yes, we've already updated mermaid

**Comment by athenor** [comment]
Aha! Sorry if I sounded snarky, I was typing in a hurry before lunch. :) Good to hear!

**Comment by ashrafteleb** [comment]
No problem, you reminded us to close the ticket :)
