### ISSUE TITLE
[Feature request]: importing GEDCOM file format (genealogical data)

### ISSUE THREAD

**Issue by wojtech** [jgraph/drawio#2559]
This is a standard file format for exchanging genealogical/family history data.

GEDCOM Javascript parser:
https://github.com/gedcom7code/js-parser

Tools and examples:
https://gedcom.io/tools/

Format specification:
https://gedcom.io/specifications/FamilySearchGEDCOMv7.html

**Comment by davidjgraph** [comment]
Thanks for the suggestion. We reviewed the idea but decided it fell outside of the scope of the project.

**Comment by wojtech** [comment]
Thanks for the consideration and really sorry to hear that.

Would you reconsider if I tell you that
yEd (https://www.yworks.com/products/yed),
which is a similar software to draw.io, has this option?

P.S.
I switched to draw.io for some projects
as yEd searching tool is not as intuitive as yours.

**Comment by wojtech** [comment]
Thank you for your consideration.
