### ISSUE TITLE
I need your custom javascript code Un-Minified to get XML Or Json.

### ISSUE THREAD

**Issue by MunirAbbasBaloch** [jgraph/drawio#256]
I need your custom javascript code in order to get XML and Json code from mxGraph, when I create dynamic graph. Please help me.

**Comment by saeedakhtar** [comment]
@davidjgraph Is there any way we can get the js file of min files available?

**Comment by davidjgraph** [comment]
@saeedakhtar If you're looking for the non-minified sources please see https://stackoverflow.com/questions/45205746/draw-io-is-there-non-minified-source/45209458#45209458

**Comment by saeedakhtar** [comment]
@davidjgraph Thanks
