### ISSUE TITLE
The javascript viewer of Draw IO does not comply with Salesforce JavaScript Strict Mode Enforcement

### ISSUE THREAD

**Issue by KyooMario** [jgraph/drawio#2566]
* [ Y] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ Y] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
As mentioned in the title we want to integrate DrawIO viewer with Salesforce but the javascript viewer of Draw IO does not comply with Salesforce JavaScript Strict Mode Enforcement. You can test this yourself with https://developer.salesforce.com/docs/component-library/tools/locker-service-console

Can you fix this?

Kind regards,
Mario

**Comment by alderg** [comment]
Please provide a link where we can see what the actual problem is.

**Comment by davidjgraph** [comment]
"Error: assignment to undeclared variable mxForceIncludes"

that?

**Comment by KyooMario** [comment]
Yes that. And when you "fix" this the next Error: xxx is not defined will popup.

**Comment by davidjgraph** [comment]
OK. That's too much work. I would suggest to fork the project and fix the errors specifically for salesforce.
