### ISSUE TITLE
[Feature Request] Remember selected folder on Export

### ISSUE THREAD

**Issue by thesuavehog** [jgraph/drawio#2567]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Whenever I am exporting pages from my diagram, I am typically exporting to a Google Drive folder. I am never exporting to the root folder in Google Drive. Each time I export from the same file, I have to select the folder to save the export into. It's annoying, affects productivity, and is prone to error if you accidentally pick the wrong folder when doing a bunch of exports.

**Describe the solution you'd like**
After exporting from a file, remember the location selected for the export and default to that location the next time I export from the same file.

**Comment by DreamShark-Bytes** [comment]
I second this feature. 
It’s VERY annoying to have to keep navigating the extensive folders I have in my project to access the diagrams. 

I wish I could bookmark folder(s) and/or open a folder like you can in VS Code.

**Comment by davidjgraph** [comment]
Duplicate #228
