### ISSUE TITLE
Get dynamic graph XML on button click.

### ISSUE THREAD

**Issue by MunirAbbasBaloch** [jgraph/drawio#257]
When I draw graph, I need dynamic graph xml on export xml button click using javascript. I can get static graph xml as in this exaple.
[https://jgraph.github.io/mxgraph/javascript/examples/jsondata.html]
but I am unable to get xml while drawing dynamic graph.

**Comment by alderg** [comment]
What have you tried?

**Comment by MunirAbbasBaloch** [comment]
var model = new mxGraphModel();
		var graph = new mxGraph(container);	
var button = mxUtils.button('View XML', function() 
			{
				var encoder = new mxCodec();
				var node = encoder.encode(graph.getModel());
				console.log(node);
                               mxUtils.popup(mxUtils.getPrettyXml(node), true);
			});
document.body.appendChild(button);

Also I tried to update model in index page javascript.
this.editor.graph.model.addListener(mxEvent.CHANGE, mxUtils.bind(this, function(a, c) {
	for (var d = c.getProperty("edit").changes, e = 0; e < d.length; e++)
	if (d[e] instanceof SelectPage || d[e] instanceof RenamePage || d[e] instanceof MovePage || d[e] instanceof mxRootChange) {
		b();
		break
	} else {

		var diagram_id = $('body').data('diagram-id');
		var user_id = $('body').data('user-id');					
		var fake_this = this;
		this.actions.get("save").funct();
		setTimeout(function(){ 
			
			console.log(fake_2);
			
			socket.emit('diagram change', {id: diagram_id, user_id: user_id, filename: fake_this.currentFile.title, diagram: fake_this.currentFile.data, session_id: session_id});

		}, 4000);

	}
}))
