### ISSUE TITLE
License and jscolor

### ISSUE THREAD

**Issue by godric3** [jgraph/drawio#2571]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a issue that matches the one I want to file, found one: https://github.com/jgraph/drawio/issues/112.

**Describe the bug**
Project is licensed as Apache 2.0 and readme says:
> Additional minified JavaScript files and Java libraries are used in this project. All of the licenses are deemed compatible with the Apache 2.0, nothing is GPL or AGPL ,due dilgence is performed on all third-party code.

But it use jscolor which is GPL.
I see new color picker is already implemented: https://github.com/jgraph/drawio/issues/1383. But jscolor one is still there.
In linked issue #112 some other issue is mentioned but unfortunately it's not longer accessible. It would be nice to have that thing explained(or remove jscolor completely)

**Comment by davidjgraph** [comment]
We use the last version that was LGPL licensed, see https://github.com/jgraph/security-privacy-legal/tree/dev/OpenSource
