### ISSUE TITLE
Is there any way compare two images in drawio ?

### ISSUE THREAD

**Issue by anubhabmondalDirac** [jgraph/drawio#2573]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I want to compare to different drawio image and spot differences shapes, diagram movement. Is there any way we can do that.

**Comment by mararad** [comment]
Which drawio version are you using? Online or integration?

**Comment by anubhabmondalDirac** [comment]
@mararad Thanks for your reply
Online but i also checked in  conflunce ,but didn't find anything .

**Comment by mararad** [comment]
If you'd like to compare two different versions of the same diagram and you saved diagrams to Google Drive, you can use File > Revision history to track diagram changes (online version)

**Comment by anubhabmondalDirac** [comment]
Ok i understand. But i want to compare 2 images and spot the difference . Is that something possible with drawio ? @mararad

**Comment by mararad** [comment]
Unfortunately it is not possible. This compare icon is the only thing we support at the moment but wasn't sure if it'd suit your needs.

**Comment by mawid6** [comment]
For future readers that find this, this post had a useful approach: 
https://www.innoq.com/en/blog/2023/04/draw-the-diff/
