### ISSUE TITLE
[Feature Request] Ability to lock size ratio

### ISSUE THREAD

**Issue by Go-rom** [jgraph/drawio#2575]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Hello,

**Is your feature request related to a problem? Please describe.**
Sometimes I would like to lock size ratio when i'm resizing an item

**Describe the solution you'd like**
Provide an option to lock the ratio.

**Describe alternatives you've considered**
Imported pictures get automatically a locked ratio. Right now when i want the same with the embedded items, i take a screenshot with the desired item, resize the picture with Gimp then i import it as a new item.

**Additional context**
No need in that case i think.

thank you for this great tool btw

**Comment by davidjgraph** [comment]
Press and hold shift while resizing.

**Comment by Go-rom** [comment]
Thank you. 

Sorry for this useless ticket, rookie mistake...
