### ISSUE TITLE
Non Breaking Space Characters in SVG

### ISSUE THREAD

**Issue by trietsch** [jgraph/drawio#2577]
I've noticed that Draw.io / Diagrams.net includes Non Breaking Space Characters in SVG images. This breaks SVG image rendering for some tools. Is there a way to turn this off? Or is this a bug?

Obviously these tools shouldn't break, but why are Non Breaking Space Characters needed?

**Comment by alderg** [comment]
Could you attach a test case that contains non breaking spaces when exported/saved as SVG?

**Comment by trietsch** [comment]
This one has non breaking spaces, in the text `Destination Topic`.
![component-diagram](https://user-images.githubusercontent.com/22979744/151005131-5ef40a60-1ef4-4186-a75b-e94d3dd65b46.svg)

**Comment by alderg** [comment]
The TAB key added those non breaking spaces. Try replacing them with a line break and increase the right spacing in the Text tab of the format panel instead.

**Comment by trietsch** [comment]
I don't actually see these non breaking spaces in the diagrams.net interface, only when I open the SVG in a text editor (such as VS Code or IntelliJ). So how would I know that these characters are in the diagram?
