### ISSUE TITLE
Cannot move around on mobile

### ISSUE THREAD

**Issue by eakteam** [jgraph/drawio#2579]
![IMG_20220125_214520](https://user-images.githubusercontent.com/8820741/151056903-cd8ddb01-e607-454e-953a-a9206624339f.jpg)

I'm trying the latest version and cannot move up-down left-right in the diagram. 

Scrollbars also are not working when trying to drag them horizontally or vertically.

**Comment by davidjgraph** [comment]
Please state the exact version.

**Comment by eakteam** [comment]
https://jgraph.github.io/drawio/src/main/webapp/index.html


I am trying it directly.

**Comment by davidjgraph** [comment]
It can cache, what's the version under the menu help.

**Comment by eakteam** [comment]
It 16.4.5

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
