### ISSUE TITLE
Issue rendering special characters using viewer.min.js

### ISSUE THREAD

**Issue by Pectojin** [jgraph/drawio#258]
I'm generating XML and using https://draw.io/js/viewer.min.js, to display embedded drawings on my web page, but when the XML contains special characters inside the value field it will fail to render.

It fails by throwing the error `error on line 36 at column 51: Entity 'oslash' not defined`

For example I might have an mxCell with the danish letter `ø` in the value

    <mxCell id="13" parent="1" value="Leverandørnet" 
        style="shape=ext;double=0;rounded=1;whiteSpace=wrap;html=1;fillColor=#FF8000;" vertex="1">
	<mxGeometry x="750" y="280" width="120" height="60" as="geometry"/>
    </mxCell>

Removing the `ø` works, but oslash is valid XML so it seems weird that it won't render.

The special characters display as expected in the normal Web UI and in Lightbox, but specifically the embedded viewer seems to be having the issue.

**Comment by alderg** [comment]
This works for me:

```
<html>
<head></head>
<body>
<div class="mxgraph" style="max-width:100%;border:1px solid transparent;" data-mxgraph="{&quot;highlight&quot;:&quot;#0000ff&quot;,&quot;nav&quot;:true,&quot;resize&quot;:true,&quot;toolbar&quot;:&quot;zoom layers lightbox&quot;,&quot;edit&quot;:&quot;_blank&quot;,&quot;xml&quot;:&quot;&lt;mxfile userAgent=\&quot;Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36\&quot; version=\&quot;8.6.5\&quot; editor=\&quot;www.draw.io\&quot;&gt;&lt;diagram id=\&quot;8d8df455-cfe5-311a-13e6-259b44eb4504\&quot; name=\&quot;Page-1\&quot;&gt;jZM7c4MwDIB/jfdgU0rX0LQd2omhswsK9sVgzjEB+usrsM3jcrkrC9InybIeJiyrh3fDW/GlS1CEHsqBsFdCaURZir+JjJ5EcexIZWTp2Qpy+QseHjztZAnXnaPVWlnZ7mGhmwYKu2PcGN3v3c5a7bO2vII7kBdc3dNvWVrhaEqfV/4BshIhc5S8OMsPLy6V0V3j8xHKzvPnzDUPZ/lCr4KXut8gdiIsM1pbJ9VDBmpqbmibi3t7YF3ubaCx/wmgLuDGVQfhxonC0GNrAMVqEgMqcNCBfcINDMcyM0aOqWnABi9MtnXc4N2Rc/V2DB3vhbSQt7yY9B7XCp2ErRVq0eKPKS0MD0uNlgbiZoKuwZoRXULAk+95WMrY6/064SjMRWymm3jG/VJVy9FrY1HwvQ3qOsPZtnkp7PQH&lt;/diagram&gt;&lt;/mxfile&gt;&quot;}"></div>
<script type="text/javascript" src="https://www.draw.io/js/viewer.min.js"></script>
</body>
</html>
```

**Comment by Pectojin** [comment]
Hmm, interesting.

I'm starting to think it's an issue in the way I compress the XML. I decompressed my own document using the [converter](https://jgraph.github.io/drawio-tools/tools/convert.html) and it actually comes out as `Leverand&oslash` instead of `ø`, but yours comes out correctly.

Back to the drawing board.

**Comment by Pectojin** [comment]
For anyone else running into this it's a problem with PHP's gzdefalte function. We worked around it by URL encoding the data before using gzdefalte on it and passing it to DrawIO.
