### ISSUE TITLE
How to remove certain menu items or automatically open specific item after load finished ?

### ISSUE THREAD

**Issue by eakteam** [jgraph/drawio#2581]
Hello, is there any easy way to remove specific menu items like e.x : `Preferences` , `Layers`, `Tags` etc... ? (This is for the reason that i don't want users to change some preferences and forcing them to use defaults)

Also how to open specific item after the page is loaded e.x : User open the page, automatically open `Outline` without going to menu and clicking `Outline...`

**Comment by davidjgraph** [comment]
No, that isn't possible without code changes.
