### ISSUE TITLE
Text fomat loss and text misalignment in .vsdx export

### ISSUE THREAD

**Issue by RealStitch** [jgraph/drawio#2586]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Text boxes that use left or right aligned text will have their text outside the box when exported to MS Visio.

**To Reproduce**
1. Create empty diagram
2. Add a Heading Textbox.
3. Add three text boxes and space them on the diagram.
4. Add an outer line to each box for reference reasons
5. Align the text to 'left', 'middel' and 'right' for one box each by using the text alignment buttons in the formatting pane.
Note that 'Position' remains on centered and the button showing a horizontal line with two arrows pointing to it from above and below remains activated.
5. Export the diagram to .vsxd
6. Open the export in the MS Visio Viewer

**Expected behavior**
The heading textbox shall be formatted as in draw.io and not lose format and line breaks
The left or right aligned text in the boxes shall remain within the boundary line

**Screenshots**
In draw.io
![grafik](https://user-images.githubusercontent.com/94839600/151212377-29d682fb-fd95-4b9b-a2e5-403c1d8fdd30.png)

In exported vsdx
![grafik](https://user-images.githubusercontent.com/94839600/151212477-9a480efa-0fc1-4831-8827-eeca929de3be.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
Desktop Version 16.4.0

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: IE with vision viewer plugin

**Comment by bitboy85** [comment]
Please reopen.
I also noticed that line breaks are not correctly exported.
