### ISSUE TITLE
Support SVG compatible with other conversion tools (rsvg-convert and Inkscape)

### ISSUE THREAD

**Issue by fuhrmanator** [jgraph/drawio#2587]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I don't get a WYSIWYG conversion of SVG (e.g. myfile.drawio.svg) to PDF using pandoc particularly when there is wrapped text done with draw.io. This is related to https://superuser.com/questions/1604178/converting-svg-1-1-to-1-0 and #774 

**Describe the solution you'd like**
It would be nice if we could specify the version of the SVG that the .drawio.svg file is saved as (e.g., Inkscape 1.x, rsvg-convert -- I'm sorry I don't know the details of the SVG version), so we can be sure of WYSIWYG conversion with popular tools such as rsvg-convert and inkscape 1.x

**Describe alternatives you've considered**
The modern Firefox and Chrome browsers seem to display this properly, but alas I don't know how to use them in a workflow with pandoc to create PDF documents. Finally, as a workaround, I use Draw.io's **Export as...>Advanced...** and I chose a PDF (manually) that is used in my pandoc file. It's an extra step. 

**Additional context**
#774 has a lot of context (the same as mine). SVG 1.1 seems not be a useful standard outside of browsers, or is there a flexible (open source) conversion tool that handles the wrapped text properly?

**Comment by davidjgraph** [comment]
Export as has a convert html labels to SVG option. If you want it automated, you could use the CLI in the desktop version to load a diagram and output it to PDF. But it's not possible to have the SVG+XML convert labels to SVG on every save since it requires a server round-trip.
