### ISSUE TITLE
Show diagram instead download file window when Confluence server Search is used

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#2589]
Asked in DID - 4146

"We created and tested some organizational charts in Confluence. If you search for a person's name that appears in the organization chart and open the search result, you always get a preview of a document that is not displayed but has to be downloaded. This appears to be the technical file of the graphic. a) Are there ways to make diagrams searchable AND viewable via search. b) If not, there is a way to remove the unnecessary search results, which then massively load the Confluence search"

**Comment by borisjgraph** [comment]
This is not possible because Confluence doesn't provide an API to plug into the preview dialog.

**Comment by n102142** [comment]
Hey Boris, 
what is with the second solution? Is it possible to hide this technical files in the confluence search?
