### ISSUE TITLE
Microsoft Teams app fails to load teams.html

### ISSUE THREAD

**Issue by michael-kubion** [jgraph/drawio#2590]
Starting from this afternoon we where not abled to load the draw.io app in Microsoft Teams:
![drawio-teams](https://user-images.githubusercontent.com/69002079/151362406-0ed867ba-69a4-496e-9904-2667ba7fa1dc.jpg)

When opening the tab in Teams on a browser, it appears that the app loads into an iframe. The url in the src attribute of the iframe starts with: https://app.diagrams.net/teams.html

When we try to access this url directly from the browser, we also get a "Not Found" error.

Full error message:
`The requested URL /teams.html?extAuth=1&inlinePicker=1&noLogoutOD=1&openInSameWin=1&noFileMenu=1&db=0&gh=0&gl=0&tr=0&topBaseUrl=https%3A%2F%2Fteams.microsoft.com%2Fiframe-container.html&ownerEml=********&topBaseUrl=https%3A%2F%2Fteams.microsoft.com%2Fiframe-container.html&lang=nl&gapi=0 was not found on this server.`

**Comment by davidjgraph** [comment]
What version is in the help menu of app.diagrams.net?

**Comment by michael-kubion** [comment]
Goodmorning David, I can confirm that the draw.io loads the content again. Thank you!
