### ISSUE TITLE
Full PL translation done

### ISSUE THREAD

**Issue by olsza** [jgraph/drawio#2592]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I made an update in the translation for PL... now everything is translated.

**Describe the solution you'd like**
Please upload translations for PL for Dwaw.IO

**Describe alternatives you've considered**
-

**Additional context**
You can check the full translation for PL at https://docs.google.com/spreadsheets/d/1FoYdyEraEQuWofzbYCDPKN7EdKgS_2ZrsDrOA8scgwQ

**Comment by davidjgraph** [comment]
Cool, thanks very much. It will automatical import into the next build.
