### ISSUE TITLE
Missing Export>Advanced option

### ISSUE THREAD

**Issue by floongle** [jgraph/drawio#2595]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
In previous versions, it has been possible to export pngs with higher pixel densities by going to File>Export>Advanced.

This option has been removed from the list of export types. The File>Export>PNG option does not allow for such types of saves.

Please could either the Advanced option be restored, or the ability to set DPIs on PNGs added into File>Export>PNG

**Screenshots**
![image](https://user-images.githubusercontent.com/44733236/151542409-7a952b3b-4dc4-4425-b9f8-93c44c4bcf60.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 16.4.11

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Not applicable, this is seen in the app version of drawio.

**Comment by davidjgraph** [comment]
Fixed in 16.5.1. Thanks for report.
