### ISSUE TITLE
[ENH] Add toggle line button

### ISSUE THREAD

**Issue by Eseperio** [jgraph/drawio#260]
Add toggle arrow context button so in a link line, end symbols could be inverted with a click

**Comment by alderg** [comment]
Try "Reverse" in the Arrange tab of the format panel.

**Comment by Eseperio** [comment]
Yes, but it requires opening Arrange panel.If it could be in context menu  would be great.

**Comment by alderg** [comment]
Thanks for your feedback. This will be added to the context menu in the next release.
