### ISSUE TITLE
Error message from notion while trying to embed a diagram from "app.diagrams.net" containing images.

### ISSUE THREAD

**Issue by simoprine** [jgraph/drawio#2603]
**Describe the bug**
I have a problem when my diagram contains images and I embed it in notion, it shows me an error message until I remove the images from my diagram and embed it again, then I don't face a problem.

**To Reproduce**
1. Make a diagram contains images.
2. go to notion and choose **embed** feature.
3. try to embed your diagram in notion using the link generated by  app.diagram.net.
5. remove images from your diagram.
6. embed diagram in notion again
7. error disappear

**Screenshots**
![image](https://user-images.githubusercontent.com/53785817/151939451-8666f7e3-611d-404b-b689-75f36c7aaca0.png)

**draw.io version (In the Help→About menu of the draw.io editor):**
- draw.io version [16.5.2]

**Desktop (please complete the following information):**
 - Browser [Brave]
 - Version [1.34.81]

**Comment by alderg** [comment]
Probably the link is just too long. Try using the draw.io Notion Chrome extension instead: https://chrome.google.com/webstore/detail/drawio-for-notion/plhaalebpkihaccllnkdaokdoeaokmle

**Comment by simoprine** [comment]
That was helpful, thanks.

**Comment by Angel0726** [comment]
> Probably the link is just too long. Try using the draw.io Notion Chrome extension instead: https://chrome.google.com/webstore/detail/drawio-for-notion/plhaalebpkihaccllnkdaokdoeaokmle

这个插件输入中文有人问题是什么原因
