### ISSUE TITLE
draw.war / external references conflict with company privacy policy

### ISSUE THREAD

**Issue by rg-artcom** [jgraph/drawio#261]
Today I saw after installing the latest draw.war (8.6.8) in our NextCloud installation that my browser script blocker showes me two external references: cloudflare.com and jgraph.com.
This stays in conflict with our privacy policy. Please can you remove these references to external servers/services? This might be also important for others because of the new DSGVO in Germany and the GDPR in Europe. Thx.

**Comment by davidjgraph** [comment]
Cloudflare is the CDN draw.io is delivered on and jgraph.com is our company web site. We are GDPR compliance and we have a signed GDPR agreement with Cloudflare.

**Comment by davidjgraph** [comment]
What you can also try is in the NextCloud field where the draw.io server is specified, add &stealth=1 to the URL parameters

**Comment by rg-artcom** [comment]
Thank you for your comment. But when we include draw.war in our site, we need some agreement and documentation with you and have to inform our users about this. In addition our service would need external services/servers to run. Why are these external references in the code? If it's not really needed it produces huge bureaucracy.

**Comment by rg-artcom** [comment]
I will try the &stealth=1. Thx.

**Comment by davidjgraph** [comment]
jgraph.com is just the dynamic footer, it's not needed. Can you screenshot the network traffic tab showing the cloudflare calls please?

**Comment by davidjgraph** [comment]
I've added https://github.com/pawelrojek/nextcloud-drawio/issues/42 in the NextCloud integration project, hopefully the author might implement this.

**Comment by rg-artcom** [comment]
Just adding the &stealth=1 to the draw.io URL field in the NextCloud setup did not work. Draw.io did not start with this parameter.
I wanted to add the screen shot but allways see "something went really wrong .." Sorry, I'm not a github expert. So I put it on the nextcloud: https://nc.artcom.de/index.php/s/XrSZEzpkTYC6rgC

**Comment by davidjgraph** [comment]
Do you have existing URL parameters? If not, the first character has to be a question mark, the & is only for later parameters, e.g. https://www.draw.io/?stealth=1.

**Comment by rg-artcom** [comment]
If I use it in the apache reverse proxy setup (ProxyPass /draw http://localhost:8080/draw?stealth=1) it gives me:

HTTP Status 404 - /draw%3Fstealth=1
type Status report
message /draw%3Fstealth=1
description The requested resource is not available.
Apache Tomcat/8.0.32 (Ubuntu)

**Comment by arnowelzel** [comment]
The parameter can not be added in the Nextcloud app. The app itself has to deal with it to add this parameter - otherwise the URL will be malformed, since the Nextcloud app will always build in in the form

<URL as configured>?<Parameters>

If you set the URL in the configuration to https://www.draw.io/?stealth=1 the result will be something like https://www.draw.io/?stealth=1?parameter

**Comment by arnowelzel** [comment]
PS: According to https://desk.draw.io/support/solutions/articles/16000042546-what-url-parameters-are-supported- the parameter should not be `stealth=1` but a combination of `offline=1&stealth=1`.
