### ISSUE TITLE
PDF export not working

### ISSUE THREAD

**Issue by Flo222B** [jgraph/drawio#2610]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
On draw.io I am not able to export files as PDFs. When selecting the PDF export via File --> Export as --> PDF... the usual configuration popup shows up. Regardless of the entered settings there , when clicking on the "export" button, a new browser page opens showing only the message "Error!".
I have tested this with multiple diagrams and the error keeps reproducing.
I additionally tested this on the desktop app as well and it results in the wheel diagram for a save in progress spinning endlessly and showing "saving ..."

**To Reproduce**

Create a new diagram on [draw.io](https://app.diagrams.net/)
Select the PDF export via File --> Export as --> PDF...
Just click the export button in the following popup
A new browser page is opened, showing the error message

**Expected behavior**
PDF export of diagrams should be possible.

**Screenshots**
![image](https://user-images.githubusercontent.com/98973044/152389998-9f73ad31-b05f-485e-8ae0-69e15203df2b.png)

![image](https://user-images.githubusercontent.com/98973044/152390404-d1ebea75-92e9-4c27-81d4-5bdad7177125.png)

Export from desktop app
![image](https://user-images.githubusercontent.com/98973044/152390379-62679309-8fc9-474b-9676-a88878c10b57.png)

- draw.io version 16.5.3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Microsoft Edge & Google Chrome (tested on both)
 - Version 16.5.1

**Comment by mararad** [comment]
I tested exporting at my place in Chrome Version 98.0.4758.82 (Official Build) (64-bit) and it is working well.

What's the file size, please? Are there a lot of images?
Is it working in Incognito mode with all browser extensions temporarily disabled?

Meanwhile, as a workaround try:
* File > Export as > Advanced > PDF
* File > Print > Print > Save as PDF/Print to PDF

Does anything help?

**Comment by Flo222B** [comment]
Hello there,
Ah, it looks like I made a small mistake, my OS is Windows 10 and not Win 11.
The first workaround doesn't work even on Chrome in incognito mode.
The second one however works fine, so I guess its a possible solution of sorts.

**Comment by mphipps1** [comment]
I had an issue as well. Desktop version, large diagram (US Tabloid size).  
Error message: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL

Print using the Microsoft Print To PDF worked OK, so there is a workaround. 
Save to JPEG worked OK.
Same as FLO222B - the Export/Advanced/PDF did not work. but the Print to PDF did.

**Comment by Sumidu** [comment]
I have this error as well on MacOS Sonoma 14.2.1 M2 Apple Mac Book. Both in Chrome and as an installed progressive web app. The desktop-version accessible at https://github.com/jgraph/drawio-desktop/releases/tag/v23.1.5 works fine. 
I could not even export an empty new file as a PDF using the web-app. Hope this helps.
