### ISSUE TITLE
Improve default text color in dark blue Style

### ISSUE THREAD

**Issue by siddhantdixit** [jgraph/drawio#2611]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

Default text is not clearly visible in last (dark blue) style due to dark background and dark-text color overlap. It should be light in color by default.

**To Reproduce**
1. Go to style in the sidebar.
2. Select the last dark-blue style
3. Paste any text object.

**Expected behavior**
Light and clear text visibility by default (White Preferred)

**Screenshots**

![image](https://user-images.githubusercontent.com/22856752/152417303-e7511a79-605b-41c7-a285-bd49fb4c9646.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**
 - OS:  Windows Desktop
 - Browser - Chrome
 - Version 16.5.3

**Comment by mararad** [comment]
The text color is optimized when the label overlaps the cell. 
My suggestions would be to use another style or change the text color for those labels that are on the dark background.

**Comment by siddhantdixit** [comment]
@mararad Yes! The text should be white on dark background by default on this style too like other styles.
