### ISSUE TITLE
"move selection to layer" button missing

### ISSUE THREAD

**Issue by shai-tzroia** [jgraph/drawio#2616]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
seems that the "move selection to layer" button is missing (from this article: [https://drawio.freshdesk.com/support/solutions/articles/16000042490-move-shapes-and-connectors-from-one-layer-to-another]())

**To Reproduce**
Steps to reproduce the behavior (on web app and on windows desktop app):
1. Go to 'View'
2. Click on 'Layers'
3. See  the "move selection to layer" button is missing

**Expected behavior**
"move selection to layer" button to appear, and a push on it should open the list of layers to choose from.  

**Screenshots**
![move_to_layer_button_missing](https://user-images.githubusercontent.com/81351388/152675728-9127eccb-f8da-46ed-8549-94b76e9d9fc2.PNG)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version on web app 16.5.3
- draw.io version on windows desktop app 16.5.1

**Desktop (please complete the following information):**
 - OS: windows 10
 
![windows_spec](https://user-images.githubusercontent.com/81351388/152675909-9ea210d9-e2be-4d1e-a85f-0a6dc2e2e29d.PNG)

 - Browser: chrome (97.0.4692.99 (Official Build) (64-bit)), edge

**Comment by mararad** [comment]
Hi,

If you select a shape/shapes you'd like to move to another layer and click three vertical dots, does it help?

![layers](https://user-images.githubusercontent.com/44292306/152789388-0d756498-aef0-49ec-b9c8-c4e92d010af2.JPG)

**Comment by shai-tzroia** [comment]
oh, that's very embarrassing (and a little strange). i was absolutely sure I've tried that already and it did not work...
anyway, it works perfectly. thanks a lot and sorry for your trouble.
