### ISSUE TITLE
Copy/Paste Does Not Work On Ubuntu 18.04  with Chrome

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#262]
Ctrl-C and Ctrl-V does not work on Ubuntu v18.04. I tested on 2 machines. For both Online and Desktop versions of draw.io, I cannot use keyboard Ctrl-C to copy or Ctrl-V to paste on the canvas.

Copy/Paste with mouse clicks and selection from the Edit menu works as well. I have reset the Ubuntu keyboard settings to make sure there were no keyboard mapping conflicts.

[6994]

**Comment by vek0ng** [comment]
Any update for this issue?

**Comment by alderg** [comment]
Works for me with Chrome 67.0.3396.79 on Ubuntu 18.04.

**Comment by samomar** [comment]
Can confirm that copy / paste shortcuts **do not work** on Ubuntu 18.04.2 LTS (draw.io-amd64-9.3.1) 
And Chrome Version 74.0.3729.169 (Official Build) (64-bit) (draw.io online version)

There are no conflicts, the copy paste shortcut works on every other application and browser windows.

**Comment by reece** [comment]
I have the same issue on Chrome 75.0.3770.142 running on Ubuntu 19.04. 
The copy/paste shortcuts don't work at all.
Copy/paste menu selections work within a document, but not across documents.

**Comment by samomar** [comment]
Update: ctrl+c/v is working now.

The solution is simply downloading the .deb `sudo apt install` it

I've come to realize over time that apps installed through snap becomes unbelievably buggy, apps like Spotify, VLC and of course draw.io

This is a snap problem.

**Comment by davidjgraph** [comment]
Is everyone else on snap?

**Comment by reece** [comment]
I'm using draw.io Online 12.2.4 with Chrome.
Yes, ctrl-c and ctrl-v finally work. Also, verified that it works between
tabs of one document and between different documents. Hallelujah.

Thanks draw.io team!

**Comment by davidjgraph** [comment]
OK, I'll close this if it's snap specific now.
