### ISSUE TITLE
How to make the width and height of cell in a table  fixed so that avoid  the cell resized during draging the whole table?

### ISSUE THREAD

**Issue by mokeyish** [jgraph/drawio#2625]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
How to make the width and height of cell in a table  fixed so that avoid  the cell resized during draging the whole table?

**Comment by mararad** [comment]
Hi,

Please attach video showing how the table was created and cells resized when a table was dragged.
Which diagrams.net version (can be seen under Help menu) and browser are you using?

**Comment by mokeyish** [comment]
@mararad Hello, thanks for your replying. I want to draw a picture as following:
<img width="300" alt="图片" src="https://user-images.githubusercontent.com/16131917/153525948-10807003-4989-4a8b-9c26-f024deaa3886.png">

**Here is my video showing as below:**

https://user-images.githubusercontent.com/16131917/153525568-517ffb8f-a9ee-4c1e-b6f7-59b810208af6.mp4

**Comment by mokeyish** [comment]
The `resizable` dosen't seems to work.

<img width="640" alt="图片" src="https://user-images.githubusercontent.com/16131917/153526458-1ef6b8d5-be02-45a4-8e78-9cf9a3620ce2.png">

**Comment by mararad** [comment]
Thanks. If I am not wrong, it seems like you are dragging the table with cursor on or near table cell borders. Could you try to click somewhere around cell center and drag the table? Do cells still resize?

Regards,

**Comment by mokeyish** [comment]
@mararad It's hard to drag the table and not resize the cell. I want to lock the cell width and height, then I can drag the table freely.

**Comment by alderg** [comment]
Try holding down the control key when pressing the mouse button to move the table instead of resizing the cell, then drag and release the mouse button without holding down the control key.

**Comment by mokeyish** [comment]
@alderg Thanks，It worked according to your suggestion.

**Comment by siscanu** [comment]
The same problem still exist. I tried all the options without succes.

**Comment by davidjgraph** [comment]
Please open a new ticket in that case as the original poster has marked this issue as fixed.
