### ISSUE TITLE
stencil drops on different position dependent on zoom

### ISSUE THREAD

**Issue by egrimate** [jgraph/drawio#263]
Steps to reproduce:

1. set standard zoom
2. drop two rectangles on canvas, by clicking them in the sidebar.
3. they should have the same x coordinate.
4 set zoom level so that the stencil is larger than the visible canvas (> 1500% in my case)
5. drop two more rectangles in the same fashion
6. the x coordinates of the recent rectangles increased

Tested on Chrome and Firefox on Win10.

**Comment by mararad** [comment]
The issue reproduced in Incognito also and confirmed in Chrome Version 74.0.3729.131 (Official Build) (64-bit). Win10
![shapedropsondifferentpositio](https://user-images.githubusercontent.com/44292306/62697408-eb1bfd80-b9da-11e9-9b5f-9fce3fdf6242.gif)
