### ISSUE TITLE
sql plugin has some preserved keywords make some column missing

### ISSUE THREAD

**Issue by pwpvinci** [jgraph/drawio#2631]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When the SQL Server DDL has column name with "ON", the plugin will deem it as constraint and ignore to create.

**To Reproduce**
1. Go to Insert>From SQL
2. Paste DDL
`
CREATE TABLE Persons
(
PersonID int,
LastName varchar(255),
FirstName varchar(255),
Address_CONTACT varchar(255),
City varchar(255)
);
`
3. Click "Insert SQL Server"
4. found missing column

**Expected behavior**
the column Address_CONTACT should be existed

**Screenshots**
N/A

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
