### ISSUE TITLE
draw.io export pages to separate documents

### ISSUE THREAD

**Issue by ghost** [jgraph/drawio#2632]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'm using the draw io cli mode to automatically export images as pdf. If I have one file with multiple pages inside (for example page-1, page-2, ...) and I export it with
`draw.io.exe -x -f pdf --crop -o build`
then I get one pdf file with all pages as own pdf pages.

**Describe the solution you'd like**
It would be nice if it is possible to export every page as own pdf file like
file_page-1.pdf
file_page-2.pdf
...

this makes it easier to include the graphics into latex documents and makes it indipendet of the page order in the draw.io file

**Comment by felixvd** [comment]
Related: https://github.com/jgraph/drawio/issues/2920

**Comment by mbrotos** [comment]
https://gist.github.com/mbrotos/2174ffec4c5323215a4f8cbf835751e4

This script extracts all pages from a `.drawio` file, names each PDF using the tab name concatenated with the file name, and exports them individually in cropped mode using the `draw.io` CLI.
