### ISSUE TITLE
Draw.io tool APIs

### ISSUE THREAD

**Issue by suyashjoshi** [jgraph/drawio#2639]
* [ X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'd like to programmatically create diagrams using your lovely tool.

**Describe the solution you'd like**
Create publically accessible API's for Draw IO tool, Java and JavaScript languages preferred.

**Comment by davidjgraph** [comment]
For the base mxGraph library, yes, https://jgraph.github.io/mxgraph/docs/manual.html, https://jgraph.github.io/mxgraph/docs/js-api/files/index-txt.html

**Comment by msk4862** [comment]
hey @davidjgraph, I had one question: Does draw.io uses `mxGraph@4.2.2` only?  or is it some other version of mxGraph library?
