### ISSUE TITLE
<CMD-R> shortcut key not working

### ISSUE THREAD

**Issue by kevinyuan** [jgraph/drawio#2642]
**Describe the bug**
<CMD-R> is used to rotate the object 180 degree.
The function is workging with previous version of the draw.io.
However, since version 16.1.2, the shortcut key has been not working.

**To Reproduce**
1. Open a new canvas and draw any object on it (e.g. an arrow)
2. Click on the object and make sure it is selected
3. Push button <CMD-R>
4. See error (expect a rotation but nothing happen)

**Expected behavior**
Expect a rotation but nothing happen,

**draw.io version (In the Help->About menu of the draw.io editor):**
16.1.2

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser : Not relevant to the issue, since I am useing the draw.io app, not in browser.
 - Version : Big Sure 11.5.2 (20G95)

**Comment by alderg** [comment]
Works for me in v16.5.1 on macOS 12.2.1. Try updating via https://get.diagrams.net or Menu draw.io > Check for Updates.
<img width="206" alt="Screenshot 2022-02-18 at 08 38 46" src="https://user-images.githubusercontent.com/921200/154638899-1cabfd27-7c00-4da6-a13c-b1df735cee71.png">
