### ISSUE TITLE
Support integration for saving draw.io files in azure repos

### ISSUE THREAD

**Issue by SebastianSchuetze** [jgraph/drawio#2643]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
The draw.io does not have the ability to save diagrams directly in Azure Repos like for GitLab or GitHub.

**Describe the solution you'd like**
It would be great to support the same for Azure DevOps with Azure Repos. If necessary I can also provide all the information needed for this.

**Describe alternatives you've considered**
None, since there is no other implementation yet. Of course I can use Git repos with a git client. But it would be great to support this one.

**Additional context**
There was a request before (#567) but it just is on the feature roadmap to support draw.io in Azure DevOps directly. Mine can be integrated independent from Microsoft.

Example:

![image](https://user-images.githubusercontent.com/7256168/154636170-11edadf1-ad65-4500-a27e-342969115d41.png)

**Comment by morbargig** [comment]
It would be more awesome if you can support. drawio via readme.md files.

**Comment by SebastianSchuetze** [comment]
Let me see. Thought about it. I can try to start with something and hope to get quick feedback in case I get stuck!
