### ISSUE TITLE
add reference line feature

### ISSUE THREAD

**Issue by cmdares** [jgraph/drawio#2644]
* [X ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Add Reference line of drawing software such as Photoshop

**Describe alternatives you've considered**
Add Reference line of drawing software such as Photoshop

**Additional context**
![image](https://user-images.githubusercontent.com/5292190/154637351-b8fc2ad5-00b6-4fd6-b201-637c8704aada.png)

**Comment by davidjgraph** [comment]
I don't understand how the request differs from the current guide lines.

**Comment by cmdares** [comment]
The reference line and auxiliary line have their own application scenarios
Guides can prompt lines to align surrounding objects when dragging objects with the mouse.
The reference line will appear in common design graphics software, such as PS, Visio, etc.
For example, I need to design a fixed scale drawing of the project. I need to design the overall skeleton according to the specified size in advance. Some fixed boundaries will be designed in advance. I will use reference lines to divide them in advance. When designing the drawing, it is conducive to the accurate placement of elements.
![image](https://user-images.githubusercontent.com/5292190/177005532-f95bb4d0-8ca8-47d4-9ca6-e20ece989853.png)
