### ISSUE TITLE
Error loading file - d is undefined

### ISSUE THREAD

**Issue by darthoggi** [jgraph/drawio#2645]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I open the embedded editor on an SVG containing a certain shape, I get the error "Error loading file - d is undefined".

**To Reproduce**
Create an SVG containing a shape like this: 
![image](https://user-images.githubusercontent.com/69275/154676907-2d039ec6-8aa5-45e0-8c9f-9676e3fc0094.png)

Create iframe: 
var iframe = document.createElement('iframe');

Define function for event listener: 
var receive = function(evt) {...}

Add event listener: 
window.addEventListener('message',receive);

Set src to editor url ('/drawio/?embed=1&ui=min&spin=1&proto=json&configure=1&p=svgdata;tips'):
iframe.setAttribute('src',editor);

Add iframe to body:
document.body.appendChild(iframe);

Load the information within receive function with:
iframe.contentWindow.postMessage(JSON.stringify({action: 'load',autosave: 0, descriptor: {format: 'svg', data: loaded_svg.data}}), '*');

**Expected behavior**
No error.

**Workaround**
My workaround was to add
if(typeof(d) != "undefined")
{
}
to the function registered to the "mxEvent.CHANGE" listener:
(this.editor.graph.model.addListener(mxEvent.CHANGE,mxUtils.bind(this,function(b,d){for(var e=d.getProperty("edit").changes,f=0;f<e.length;f++)if(e[f]instanceof SelectPage||e[f]instanceof RenamePage||e[f]instanceof MovePage||e[f]instanceof mxRootChange){c();break}}));)

**Screenshots**
![image](https://user-images.githubusercontent.com/69275/154671619-445cccce-b16b-421a-8076-30668116814e.png)
![image](https://user-images.githubusercontent.com/69275/154671630-80fae3a1-0358-4ec8-9190-9e85baa68b28.png)
![image](https://user-images.githubusercontent.com/69275/154671642-aa4d2371-23cc-4f5b-90b5-92ed75d84661.png)

**Desktop**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 97.0 (32-bit)
 - draw.io version 16.6.1 (embedded)

**Comment by mararad** [comment]
Hi,

Is it working in other browsers and Incognito?

**Comment by robwruck** [comment]
Same here.. Test results:
- Firefox 96: "d is undefined" occurs when loading a certain image. Same in incognito mode. Does not occur for some other image.
- Seems not to be reproducible in Chrome 95
- Seems not to be reproducible in Edge 97

Using the Confluence inline editor which uses https://ac.draw.io/js/app.min.js

**Comment by davidjgraph** [comment]
Please attach a diagram file that reproduces the error.

**Comment by darthoggi** [comment]
![test drawio](https://user-images.githubusercontent.com/69275/155963964-f12e6d55-679b-49d9-8d8c-c538ade8e6f8.svg)
[test.drawio.txt](https://github.com/jgraph/drawio/files/8152469/test.drawio.txt)

Sorry for the delay.

**Comment by darthoggi** [comment]
I just tried to import the .drawio and there is no error. Also when pasting the SVG-data into an already open drawio-editor there is no error. The error only seems to occur when loading the svg data with "iframe.contentWindow.postMessage(JSON.stringify({action: 'load',autosave: 0, descriptor: {format: 'svg', data: loaded_svg.data}}), '*');" (the process is described in the initial issue description).

**Comment by davidjgraph** [comment]
When you say "loading the svg data", are you passing SVG graphics to the postMessage call?

**Comment by darthoggi** [comment]
Yes.

**Comment by davidjgraph** [comment]
Pure SVG won't work. For the SVG option it would need to be our SVG+XML format.

**Comment by darthoggi** [comment]
Thanks for the response. 
What is the difference between the SVG and SVG+XML format and why am I able to load other SVGs the same way and the SVG above in other Browsers (e.g. Chrome) without error?

**Comment by alderg** [comment]
Try 17.1.0.
