### ISSUE TITLE
[Veeam stencils] New shapes on their official site

### ISSUE THREAD

**Issue by jorgedlcruz** [jgraph/drawio#265]
Hi guys,
Veeam has a new set of stencils on their website for free: https://www.veeam.com/vmware-esx-stencils.html they are in vssx format per category, and when you import them into draw.io they work. How can this new stencils be added to the main draw.io code as you have the current ones?

**Comment by davidjgraph** [comment]
[VeeamStencils_2018.zip](https://github.com/jgraph/drawio/files/2084415/VeeamStencils_2018.zip)

**Comment by kutya** [comment]
Up to date
