### ISSUE TITLE
Allow to hide pages

### ISSUE THREAD

**Issue by mogarick** [jgraph/drawio#2650]
* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I have diagrams for projects with lots o pages as I use them for reference and evidence of the evolution of my design process but many times it happens the page tabs become cluttered so I'm not able to easily identify the page title. Currently the only option I have is to delete pages but that's not what I want.

**Describe the solution you'd like**
I'd like to be able to hide or archive pages so the app only display a few ones (usually the most recent/relevant ones) and when I need to revisit old pages for reference I can simply unhide/unarchive them.

* A First version could allow to hide page by page but for unhide/unarchive it could let to unhide/unarchive all pages.
* A 2nd version could allow to unhide/unarchive specific pages. Google Spreadsheets allows this through a menu option (View -> Hidden sheets -> List of currently hidden sheets). For the drawio such option could be added to the page bar man (the bottom-left three dots icon) 

<img width="189" alt="Captura de Pantalla 2022-02-21 a la(s) 11 00 00" src="https://user-images.githubusercontent.com/4414145/154999055-65ffc124-8f81-430d-b571-f6851284c21f.png">

**Comment by mararad** [comment]
Feel free to add he feaure reques here: https://github.com/jgraph/drawio/issues/647
