### ISSUE TITLE
Curved text in custom complex shapes

### ISSUE THREAD

**Issue by Maximvdw** [jgraph/drawio#2651]
This issue is related to https://github.com/jgraph/drawio/issues/1563 . However, a bit more detailed with additional real life use cases and current web implementations that would support this.

Curved text is often desired for many drawings and text that is located within a circle or ellipse. An example is an onion architecture
![](https://dz2cdn1.dzone.com/storage/temp/4436217-kolka.png)
where the text wraps around the circle.

While I understand that there is currently no interest for implementing a shape/UI that offers the creation of this curved text, a great help would be to add support for `textPath`  in the custom shape editor, so we have the ability to keep using draw.io for these types of drawings (https://developer.mozilla.org/en-US/docs/Web/SVG/Element/textPath).

Currently the most supported method is to link a `textPath` to a path curve. However, for parsing - the newer "path" attribute can be used similar to the SVG 2 proposal: https://www.w3.org/TR/SVG2/text.html#TextPathElementPathAttribute

Comparing this issue to other drawing software: MS Visio does not even support this (https://support.microsoft.com/en-us/office/why-can-t-i-fit-a-line-of-text-to-a-curve-1081713f-c810-4bd4-b910-c409669d1c4b) with their solution being to use WordArt.

**Comment by davidjgraph** [comment]
Declined

**Comment by Maximvdw** [comment]
What was the reason for declining? Is there a similar method to achieve a curved text which is quite common in a lot of visualisations?
