### ISSUE TITLE
Export all pages as svg with specific options

### ISSUE THREAD

**Issue by point-source** [jgraph/drawio#2653]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I often receive drawio files with many hundreds of pages/tabs and I need to export them to svg. Right now, I have to do this manually. I go one by one to each tab, open the svg export dialog, and set the following options:

- Zoom: 100%
- Border Width: 0
- Size: Diagram
- Transparent Background: Checked
- Shadow: Unchecked
- Include a copy of my diagram: Unchecked
- Embed Images: Unchecked
- Text Settings: Convert labels to SVG

I then export them all. It's very manual and tedious and takes several hours. I wish there was a better way.

**Describe the solution you'd like**
I see that there is already an option to export all pages to a pdf. Can this be extended to svg (and possibly other formats) as well? Preferably it exports as either a folder or zip file which contains all the svg files, one for each page named by the same name as the page.

**Describe alternatives you've considered**
I have tried multiple export and cli tools found around the web/github for this and I've even managed to script a bulk exporter of my own that got pretty close. Unfortunately, the options of "Include copy of my diagram" and "Text Settings" do not appear to be exposed in any of the cli tools so the output I am getting is not useable for my case.

**Comment by khaiyichin** [comment]
Any chance of this being revisited? I'm trying to export multiple pages but need the fonts to be embedded, which isn't an option with the CLI.

**Comment by davidjgraph** [comment]
Interest is determined by the number of thumbs up on the original post.
