### ISSUE TITLE
Suggestion: Allow style classes on objects (css classes)

### ISSUE THREAD

**Issue by DarkTrick** [jgraph/drawio#2655]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'd like to focus on content during diagram creation, not formatting. Currently, formatting has to be done for each individual item. This is especially a problem, when larger groups of items need to be reformatted.

**Describe the solution you'd like**
- I'd like the ability to assign one or more style classes (CSS classes) to items.
- I'd like the ability to provide style rules for these classes (simplest implementation: could be a simple large text area containing all rules, just like a CSS file.).

**Describe alternatives you've considered**
I couldn't find any workaround

**Additional context**

**Comment by WEGFan** [comment]
It'd be great if allowing placeholders in styles, so I can write `fillColor=%bg%;` if I want to change the background of a group of layers later.

**Comment by gomarcus** [comment]
Yes, the ability to add a CSS style class to any element and/or edit "default" element styles via CSS ... and an editor for editing those style classes for the hole file at ones would be so great and a huge improvement!

**Comment by lola-masson** [comment]
+1
