### ISSUE TITLE
Distribute objects in a circle with equal distance

### ISSUE THREAD

**Issue by SwissPixie** [jgraph/drawio#2656]
Is there a way to have like 5 objects distributed equally within a circle? The set templates seem to all have even numbers of objects aligned. Sometimes, I need an uneven number of objects aligned in a circle.
Might that be something to look in to? Thanks.

**Comment by mararad** [comment]
Hi,

Could you attach an example, please?

**Comment by SwissPixie** [comment]
Hi mararad,
Something like this. At the moment there are eight smalle circles around a large one. All small circles are distributed equally. If I either want to remove one, two or three of those small circles, how can I have the remaining small circles also equally distributed around the large circel?
![Diagram drawio](https://user-images.githubusercontent.com/100563284/155995018-46fb906a-9862-47c0-8917-3c14b481b21b.png)

Does this make sense? Thank you.

**Comment by davidjgraph** [comment]
No, we don't have this functionality.

**Comment by SwissPixie** [comment]
Thank you @davidjgraph for your reply.
Might this be something to consider for the future?

**Comment by davidjgraph** [comment]
Unfortunately, no, it's too narrow focused a feature to include.
