### ISSUE TITLE
Code to flow & global configuration for shape property

### ISSUE THREAD

**Issue by I2rys** [jgraph/drawio#2657]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

A feature for drawio where you can type a code like code2flow and It automatically generates a graph, It's really useful If you want to make a graph by code and It's fast and a configuration in the preference where you can configure certain shape property such as **Autosize** globally without enabling them manually over and over again in each shape.

**Comment by davidjgraph** [comment]
Declined.
