### ISSUE TITLE
Wrong label for  Managed Identities icon 🧁🧁

### ISSUE THREAD

**Issue by LuiseFreese** [jgraph/drawio#2659]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I search for `managed identity` (Azure) I find the icon, but it has the wrong label - it needs to be `Managed Identities`, not `Managed Identitties` 😂`

**To Reproduce**
1. Go to search
2. Search for "managed identities"
3. Hover over the icon
4. See error: Label shows `Managed Identitties`

**Expected behavior**
I wanted to see the correct label `Managed Identities`, not `Managed Identitties`

**Screenshots**
![image](https://user-images.githubusercontent.com/49960482/156183021-29371f90-eb07-4cea-af86-2ce82fc2487a.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 16.6.4

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by egrimate** [comment]
Will be fixed in next release
