### ISSUE TITLE
Press Enter should create a new Node in Mindmap Template

### ISSUE THREAD

**Issue by kngautham** [jgraph/drawio#266]
In the current Implementation, pressing enter takes me to the next line in the same node. It would be nice if pressing enter would create a new node in Mind Map Template

You can have Shift + Enter for moving to the next line in the same node.

Thanks

**Comment by alderg** [comment]
Try ctrl+enter to stop editing and ctrl+enter (or enter) again to create a new node.

**Comment by kngautham** [comment]
Thanks your idea works.
