### ISSUE TITLE
Paste here does not work from another editor, only paste

### ISSUE THREAD

**Issue by chipbite** [jgraph/drawio#2660]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

## Paste here does not work from another editor, only paste works
Copy stuff from another editor/browser/instance of draw.io, can only paste using paste/ctrl-v, paste here paste:s whatever was last copied in the same diagram. Two clipboards that are not aligned when pasting from another instance, maybe?

**_This may be limited to when using an drawio/diagrams.net editor in confluence <-> and a web app editor._**

**To Reproduce**

**Edit:** The issue is _not consistently appearing_, in some instances it works as expected.

1. Open diagrams in two draw.io instances, A & B (two different browsers for example).
2. Copy any object in A (ctrl-c) - call this object 1 ("local").
3. Switch over to editor B, copy any object - lets call this object 2 ("another editor").
4. Switch back to editor A.
5. Select "Paste" (or press ctrl-v). 

> **Expected behavior**
> Object 2 is pasted.
> **Actual**
> ✅  **Correct:** Object 2 is pasted.

6. Select undo to remove object 2.
7. Select "Paste Here"

> **Expected behavior**
> Object 2 is pasted.
> **Actual**
> ❌ **Incorrect:** Object 1 is pasted. Different behavior from paste / Ctrl-v.

**draw.io version (In the Help->About menu of the draw.io editor):**

- online / latest

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome
 - Version  98.0.4758.82

**Additional context**
Its been this way forever. Just haven't gotten around to reporting it. 😄 
Note again: This is inconsistent, repro not clear.

**Comment by mararad** [comment]
Hi,

Could you attach video showing all steps and the result? I couldn't reproduce with diagrams.net 16.6.5.
Tried using two diff browsers (Chrome Version 98.0.4758.102 (Official Build) (64-bit) and FF 97.0.1 (64-bit)
Also tested wih 2 editors in Chrome and in both cases Pase here pasted object 2.

If you clear browser cache does it help?

**Comment by chipbite** [comment]
Hi! Here is a simple clip showing just the issue.
![small-example](https://user-images.githubusercontent.com/559199/157647148-b0d1a48a-9dc1-48fc-b655-4d88a262ca33.gif)

It does **not** appear consistently. I do not know exactly how to setup to reproduce.
It may be an issue between instances in confluence -> web?
So far, I have not tested with different browsers, only chrome.
The issue has been around for a looong time - over different chrome versions. So, I dont think chrome browser version is a key aspect.

**Comment by chipbite** [comment]
Longer example with workaround shown:
![longer-ex-w-workaround](https://user-images.githubusercontent.com/559199/157653351-7aae0054-65c4-4404-ae3f-17bce43c097d.gif)

**Comment by mararad** [comment]
We use different “clipboards” for copy/paste via keyboard and copy/paste via menus so “paste here” only works when copy was used from menu.
Also the menu clipboard is only available in the same tab, the real (keyboard) clipboard is system-wide.

**Comment by chipbite** [comment]
No, you're wrong or inaccurate here.

> We use different “clipboards” for copy/paste via keyboard and copy/paste via menus so **“paste here” only works when copy was used from menu.**

This statement is not accurate. Easy to check/verify: 
* **(a)** In **same editor**, ctrl-c and then paste here. 
Works as expected, contrary to your statement. 
* **(b)** In **different editors**, start chrome and edge. add foo bar boxes, ctrl-c in edge, paste here in chrome.
Again, works as expected, contrary to your statement.

> Also the menu clipboard is only available in the same tab, the real (keyboard) clipboard is system-wide.

I dont quite understand this point, but since your first is not accurate, I suspect this one is also not accurate.

The issue remains, as it has for quite some time.

**Comment by alderg** [comment]
This works for me: Copy object 1 in Editor A, then copy object 2 in editor B, paste in Editor A pastes object 2, then undo and paste here in Editor A pastes object 2 (again) as expected.

**Comment by chipbite** [comment]
> This works for me: Copy object 1 in Editor A, then copy object 2 in editor B, paste in Editor A pastes object 2, then undo and paste here in Editor A pastes object 2 (again) as expected.

Yes, that is correct, I tried to get across that this issue is not consistent. I get the point, I will clarify the report a bit to say that earlier. I will also try a few things to see if I can identify some consistency for repro.

**Comment by chipbite** [comment]
### Issue is perhaps tied to Confluence editor in some way?
Maybe the issue could be exarcebated or even caused by confluence editor <-> web editor?

#### My use case
A common (perhaps primary for me, even) use case for copying between editor is this: I have some work offline that I want to copy into the diagram editor in confluence. So I will open the diagram in confluence and paste into it, content from a web editor with some local/file content opened.

# Repro: MS Edge, Confluence editor <-> web app editor
Just reproduced with edge, which I never use, and the issue is reproducible, image:
![image](https://user-images.githubusercontent.com/559199/158599054-280b4a66-c7b7-454a-9fbe-60c70168b126.png)

**Comment by chipbite** [comment]
# Repro: Firefox, confluence <-> Webapp.
Using two firefox windows. Confluence drawio editor to the left and web app to the right.
Paste here is not shown after just copying a shape from the confluence editor. 

ctrl-v works consistently, always.

![image](https://user-images.githubusercontent.com/559199/158602567-a3f04a60-73d5-4bf0-b334-2f866efd65ac.png)

After clipboard is filled locally in the right editor, paste here is shown:
![image](https://user-images.githubusercontent.com/559199/158602900-0f2a298f-01d6-42ea-a310-eb1d8fdeeba6.png)
