### ISSUE TITLE
Suggestion: introduce the possibility to disable the print icone in lightbox

### ISSUE THREAD

**Issue by zucchigiuli** [jgraph/drawio#2661]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Hi! (I'm italian, sorry for my bad english!) Please can you introduce the possibility of embedding a drawio diagram in html with the lightbox but with the possibility of disable the button "print" of the lightbox?

Thank you very much!

**Comment by borisjgraph** [comment]
![image](https://user-images.githubusercontent.com/84016578/156618754-ef1ca47c-a81d-4299-9ce4-06fe4462e3d8.png)
This is accomplished by unticking the 'lighbox' in the export dialog.

**Comment by zucchigiuli** [comment]
Sorry, there is a misunderstanding. I would like to maintain the lightbox during the export. I just want to disable the print option of the lightbox.
