### ISSUE TITLE
Incorrect or missing Fill Stroke Width for grid fill style SVG export

### ISSUE THREAD

**Issue by hberge** [jgraph/drawio#2669]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
- I am using Fill Style: Grid and Fill Stroke Width: 0.1 pt.
- Exporting to SVG changes 'Fill Stroke Width' from 0.1pt to something wider. E.g. 1pt I am guessing. Maybe it is not exported?

**To Reproduce**
1. Open sample drawing [Sample_gridline.zip](https://github.com/jgraph/drawio/files/8190456/Sample_gridline.zip)
2. I use File > Export as > SVG, Using [x] Selection only, and not 'include a copy of my diagram (a feature I don't quite understand)' 
3. Opening the SVG directly in Chrome. The resulting grid lines appear very wide. 

**Workaround**
I am able to work around this by exporting to PDF, then using the CLI tool `pdf2svg`. Results here looks as expected.

**Expected behavior**
I expected appearance of SVG to render in Chrome, like it looks inside the app (also in Chrome). 

**draw.io version : 16.6.4**

**Desktop (please complete the following information):**
 - OS: Win10 
 - Browser Chrome
 - Version 98.0.4758.102 (Official Build) (64-bit)

Kudos!

**Comment by mararad** [comment]
Reproduced in Chrome, Chrome Incognito and FF.
diagrams.net 16.6.6 
Chrome Version 98.0.4758.102 (Official Build) (64-bit)

**Comment by hberge** [comment]
This issue looks like it has been fixed. Tested in 20.2.7
