### ISSUE TITLE
Disable right-click zoom on MacOS

### ISSUE THREAD

**Issue by JesseAldridge** [jgraph/drawio#267]
Using a macOS magic mouse with draw.io results in frequently accidentally zooming in.

I use right-click drag to move around a large document.
If I accidentally slide my finger slightly while holding down the right mouse button the document zooms in or out a lot and then I have to reset the zoom.
This happens to me quite often. It's really annoying.
I can't find any way to disable the zoom trigger in the OS mouse settings, so I assume the zooming is triggered by the draw.io input handling.

**Comment by JesseAldridge** [comment]
Using macOS High Sierra 10.13.5

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
