### ISSUE TITLE
Pressing tab when editing a list does not add a nesting level

### ISSUE THREAD

**Issue by septatrix** [jgraph/drawio#2673]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**
1. Create a new text field in a diagram
2. Click on "Numbered list" or "Bulleted list"
3. Write something in the first line (optional)
4. Create a new list item by pressing <kbd>Enter</kbd> and then press <kbd>Tab</kbd> to increase the nesting level/add a sub-item.

**Expected behavior**
I would expect an increased nesting level/sub-item like which can currently only obtained by pressing "Increase Indent". This is the behaviour of virtually every writing/sketching etc. application I know of.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: `diagrams.net 16.5.1`

**Desktop (please complete the following information):**
 - OS: Linux (Fedora 35)
 - Browser: Draw.io App (from Flatpak)
 - Version: `16.5.1`

~**Smartphone (please complete the following information):**~

**Additional context**

Removing an empty indentation layer by pressing <kbd>Enter</kbd> in an empty line works as expected and the same as other applications do it.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
