### ISSUE TITLE
Add Github OAuth for Confluence app

### ISSUE THREAD

**Issue by sambeckingham-awaze** [jgraph/drawio#2677]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Problem**
Presently, at work we store our draw.io diagrams in the organisation's git repo. This works well when you're working within draw.io and its related apps.  However, if you want to embed those diagrams on a Confluence page, you are currently unable to do that with a private repo.  [I can see work was recently done to achieve basic github integration](https://github.com/jgraph/drawio/issues/1279) but unlike Google Drive and OneDrive, there's no option to authorise Github for private repos

**Describe the solution you'd like**
I would like to be able to authorise the embedded Confluence app to access private repositories, much like it does currently in the web/desktop app.

Having constantly up to date version controlled diagrams in your Confluence docs would be amazing!

**Comment by m-mohamedin** [comment]
We’ll add support for private github repositories in the next release (v20.2.5)
