### ISSUE TITLE
The "Create Custom Link" tool generates not working links when using "Set Style"

### ISSUE THREAD

**Issue by S-Dafarra** [jgraph/drawio#2679]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When selecting "Set Style" in the dropdown menu at the top of https://jgraph.github.io/drawio-tools/tools/link.html the value put inside "Key" is not appearing in the generated link. Hence, the link does not work 

**To Reproduce**
1. Go to https://jgraph.github.io/drawio-tools/tools/link.html
2. Select "Set Style" in the dropdown menu of "1. Action for Cell(s): "
3. Set a random "Key"
4. Set a random "Value"
5. Click on "Add Action"
6. The text of the resulting link does not contain anywhere what has been inserted in "Key", but you can find that the field ``key`` in the JSON is set equal to "Value"

**Expected behavior**
The output link should contain both the ``key`` and the ``value`` entries

**Screenshots**
![image](https://user-images.githubusercontent.com/18591940/157300901-2cf70057-503c-4087-acc6-df1ec6dca2db.png)

The output link is 
```
data:action/json,{
  "actions": [
    {
      "style": {
        "cells": [
          "*"
        ],
        "key": "someValue"
      }
    }
  ]
}
```
while it should be
```
data:action/json,{
  "actions": [
    {
      "style": {
        "cells": [
          "*"
        ],
        "key": "someKey",
        "value": "someValue"
      }
    }
  ]
}
```

**draw.io version (In the Help->About menu of the draw.io editor):**

- The problem is in https://jgraph.github.io/drawio-tools/tools/link.html

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome 
 - Version 99.0.4844.51

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alderg** [comment]
Fixed
