### ISSUE TITLE
Drag multiple select objects doesn't work for small objects, as they overlap with vertex handler

### ISSUE THREAD

**Issue by govardhan-srinivas** [jgraph/drawio#2680]
### Preflight Checklist

* [X ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Multiple selections drag and drop works fine for larger items, it doesn't work fine when elements are small and if vertex handlers are overlapped so the cursor doesn't show move cursor.

**To Reproduce**
1. Go to 'https://app.diagrams.net/'
2. Drag and drop on 'square' element on the page 
3. Reduce the width and height of the square element to 20px x 20px
4. Duplicate the element using Ctrl + C and Ctrl+ V around 10 times
5. Make a bulk selection of the elements at once, try moving the group

**Expected behavior**
Bulk selected elements should move [Thinking out loud, during bulk selection box to be showed similar to grouped element instead of individual element selection]

**Screenshots**
[Video link](https://youtu.be/rvxS0-J_hTY)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 17.0.0 (website)

**Comment by mararad** [comment]
Hi,

There are 2 suggestions:

* select all shapes and then untick "Resizable" under Property/Value on the right
* zoom to 200% (300%) and drag the whole selection

https://user-images.githubusercontent.com/44292306/157427425-44746a8e-489c-430e-a6be-c82d0240868e.mp4

**Comment by govardhan-srinivas** [comment]
Thanks, I used `resizable` property
