### ISSUE TITLE
Swap arrows

### ISSUE THREAD

**Issue by mphipps1** [jgraph/drawio#2682]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

It would be very convenient if there was a way to swap arrowheads on a line. I often find that I started on the destination instead of the source or that I want to reverse the direction of the flow. A button on the style format panel that swaps the arrow direction would nicely fix this.

**Comment by alderg** [comment]
Try the Reverse button in the Arrange format panel (or Cmd/Ctrl+R).
<img width="240" alt="Screenshot 2022-03-11 at 13 17 52" src="https://user-images.githubusercontent.com/921200/157865624-e996d826-4609-4ac6-892d-1b2f80c19fed.png">

**Comment by mphipps1** [comment]
It's awesome that this already exists! 
UI wise, I would put it on the style panel, and maybe label it "swap ends" to enhance discoverability.
