### ISSUE TITLE
Multiple selection of inner elements is not possible when elements are on inside of other

### ISSUE THREAD

**Issue by govardhan-srinivas** [jgraph/drawio#2683]
### Preflight Checklist

* [ x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
As shown in the below video, group selection of inner elements is not possible when elements are on inside of other

**To Reproduce**
1. Go to 'https://app.diagrams.net/'
2. Create 3 rectangles placed one inside of other
3. Try group selecting the inner rectangles
4. See error that outer rectangle is selected/moved, but inner rectangle selection didn't work

**Expected behavior**
Multi-selection of inner rectangles

**Video**
https://youtu.be/nqPM2HyS6FM

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser : chrome
 - Version  17

**Comment by mararad** [comment]
Hi,

Try the following: hold Cmd and click each shape separately. This way you should be able to select inner shapes.

Regards

**Comment by govardhan-srinivas** [comment]
Thanks, it worked. 
Is there any other solution, because I always have a base rectangle at the background & elements on top of it. So I can't make group selection anymore?

**Comment by bagheera** [comment]
Select such that your selection area spills outside the outer rectangle without containing it fully. The inner elements that get enclosed will still get selected.
