### ISSUE TITLE
Improve concurrent editing

### ISSUE THREAD

**Issue by chipbite** [jgraph/drawio#2685]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Today, in this remote work world, collaboration on shared work is key. Quite a while ago now, google docs made collaboration using concurrent editing mainstream. Today, there are many drawing apps with similarly well implemented support for users to share and edit a drawing during a web meeting, for example miro and excalidraw. Notice that diagrams.net is not one of them.

**Describe the solution you'd like**
Improve or revamp the concurrent editing implementation. Make it good (add peer to peer updates, presence, etc).

**Describe alternatives you've considered**
The open source Excalidraw implementation is excellent, but it is squarely a sketching focused app. There is also no interop.

**Additional context**
## Comparison current concurrent 
Examples below. Note how the updates lag significantly, making it in practice hard to use reliably when you are working on the same drawing or as a whiteboard during a meeting, for instance. Note also that there is no presence, which helps significantly with confidence and shared ownership during concurrent editing.
### Here is drawio concurrent editing experience:
File on google drive. Can this be improved?
![drawio-drive-collab-slowsync-smaller](https://user-images.githubusercontent.com/559199/157848132-4a7954d4-413e-4483-b4e0-8621af30ddfe.gif)
### Here is excalidraw experience:
![excalidraw-multiplayer](https://user-images.githubusercontent.com/559199/157848153-a8beca0f-ee51-4a75-b48d-0fb787e3b981.gif)

### Some references
* [Excalidraw repo](https://github.com/excalidraw/excalidraw/)
* Their blog/notes on their concurrent editing implementation: https://blog.excalidraw.com/building-excalidraw-p2p-collaboration-feature/
* [Discussion on their presence implementation](https://github.com/excalidraw/excalidraw/pull/2877)

Thanks for an awesome tool! ❤🙂👍

**Comment by davidjgraph** [comment]
What is your version under the help menu?

**Comment by chipbite** [comment]
Hi David, for Confluence help menu says: `17.1.1` & web is same; `17.1.1`

**Comment by davidjgraph** [comment]
For a google drive file that's much slower than it should be using 17.x. If you right-click do you see the show cursors option? What browser and OS is this?

**Comment by mawid6** [comment]
OK, so totally I missed the [realtime beta discussion](https://github.com/jgraph/drawio/discussions/2641). 
Tried that and it looks really great and works well in my quick test (similar to above) just to get a feel.

Looking forward to get that when using confluence to store the diagrams.
So, I asked about whether confluence users will get a similar realtime sync solution in that thread instead. 
(As confluence is a key part of my usage)

(This can be closed then, depending on how you want to track things - it seems I cant close this.)
Thanks @davidjgraph.

**Comment by mawid6** [comment]
(Duh, now I see why. Work account private acct)

**Comment by chipbite** [comment]
closed
