### ISSUE TITLE
Make changing property IDs simpler and direct

### ISSUE THREAD

**Issue by LeeMbarrett** [jgraph/drawio#2694]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I am manually changing the ID's on many objects and the process is simple enough albeit not as efficient as it could be (Edit Data on object, shift-double click on ID, change ID as needed). There are two problems with changing ID relating to efficiency:

1. Why is the process of changing object IDs not as straightforward as changing the value in any other writable property or field i.e. just click on the ID field and edit without needing to shift-double click?
2. Why can't I change the property ID simply by clicking on the ID in the properties panel and edit the value like any other writable property? after having spent a significant amount of time changing the IDs on well over 400 objects I realise the means by which the ID gets changed should be easier and more direct than it currently is.

**Describe the solution you'd like**
I want the property ID to be editable as easily and as direct as any other writable property.

**Describe alternatives you've considered**
I could just use tags and ignore the property IDs completely but then that would negate the whole point of being able to change IDs.

**Additional context**
![image](https://user-images.githubusercontent.com/55362361/158182783-724a55ab-8a89-4162-bf5c-78aebf0b5119.png)

**Comment by alderg** [comment]
Edit, Edit Data, double click the ID:

<img width="568" alt="Screenshot 2024-01-17 at 21 00 40" src="https://github.com/jgraph/drawio/assets/921200/32d3c2e5-d564-4848-a026-9efdecdb93dc">
