### ISSUE TITLE
diagrams.net GitHub Integration example broken

### ISSUE THREAD

**Issue by PackElend** [jgraph/drawio#2697]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
diagrams.net GitHub Integration example broken, it does not show the example

**To Reproduce**
1. Go to https://github.com/jgraph/drawio/wiki/Embed-Diagrams

**Expected behavior**
See an example how a diagram is embedded in GitHub Markdown

**Screenshots**
![image](https://user-images.githubusercontent.com/3542031/158456023-8bbab7f0-4de3-40b2-aa23-97a39fa2cf6f.png)

**Comment by alderg** [comment]
Fixed
