### ISSUE TITLE
Shape Issue - Flowchart -> Predefined Process

### ISSUE THREAD

**Issue by pgodwin** [jgraph/drawio#2699]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The Flowchart Predefined Process shape text location is under the shape rather than within it:
<img width="98" alt="image" src="https://user-images.githubusercontent.com/1046558/158921233-eb6a88fc-3e97-46ff-92e6-bcf760fcc55c.png">

**To Reproduce**
1. Go to 'Flowcharts' shape category
2. Drag the "Predefined Process" shape to the document
<img width="160" alt="image" src="https://user-images.githubusercontent.com/1046558/158921350-d75f03a6-eb3d-4c7f-8bb4-4e74179760b1.png">

3. Click the shape on the document and add text
4. The text appears under the shape rather than inside it.

**Expected behavior**
Text should appear inside the shape:
<img width="93" alt="image" src="https://user-images.githubusercontent.com/1046558/158921469-f3672195-ede8-41ac-9467-a5ab486888f7.png">

**Screenshots**
Inline above.

**draw.io version (In the Help->About menu of the draw.io editor):**

- diagrams.net 16.5.1

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser: Chrome 
 - Version: 99.0.4844.51 (Official Build) (64-bit)

**Comment by mararad** [comment]
Hi,

just select a shape and choose position Center under Text tab
![center text](https://user-images.githubusercontent.com/44292306/158964201-2e807833-c9d3-4581-9d5f-23e91bacf747.JPG)

**Comment by pgodwin** [comment]
That does work. Thank you!
