### ISSUE TITLE
VSSX import breaks

### ISSUE THREAD

**Issue by kutya** [jgraph/drawio#270]
[Veeam Stencils 2018 - VAS components.zip](https://github.com/jgraph/drawio/files/2106099/Veeam.Stencils.2018.-.VAS.components.zip)

**Comment by ashrafteleb** [comment]
The file imports correctly, can you please provide more details on how it breaks?

<img width="961" alt="Screen Shot 2019-06-28 at 10 32 48 AM" src="https://user-images.githubusercontent.com/24944765/60349968-8eb3d000-9990-11e9-82d8-ff94bbd9d155.png">
