### ISSUE TITLE
how to set text left align default？

### ISSUE THREAD

**Issue by ltang666** [jgraph/drawio#2702]
I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
 I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Screenshots**
<img width="555" alt="image" src="https://user-images.githubusercontent.com/3445470/159159361-628f8598-a9a1-49ee-b362-8b5155099406.png">

**draw.io version 
- draw.io version [16.1.2]

**Desktop (please complete the following information):**
 - OS: [iOS]

text default is center align, I want to change text left align default. but I didn't find a place where to do it.

**Comment by thenameisdoc1** [comment]
Inside the configuration add 
```
{
  "defaultVertexStyle": {
    "align": "left"
  }
}
```
Worked for me
