### ISSUE TITLE
UML package diagram template and UML 2.5 model shapes not styling consistently

### ISSUE THREAD

**Issue by jaylapras** [jgraph/drawio#2706]
### Preflight Checklist
* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

Style / colour issues - indicated by question marks in image below.

1. UML template > UML 2 - some of the package shapes do not apply fill colour like normal package shapes
2. UML 2.5 shape library > "model" shape - same problem

<img width="968" alt="image" src="https://user-images.githubusercontent.com/60265913/159481838-42aaf5be-7d18-4630-9401-03d3e7d17303.png">

**Expected behavior**
Fill colour and outline to be applied like the normal UML shape library > package shapes.

- diagrams.net version: 17.1.4

**Comment by mararad** [comment]
Hi,

If you click Package shape once and then again (without label mark) does it help? You'll see an small orange diamond shape. Are you able to change fill color and outline?

![uml](https://user-images.githubusercontent.com/44292306/159689363-b59ae965-e761-4737-8845-ec5442b8fb43.JPG)

**Comment by jaylapras** [comment]
Yup, that works. And makes sense, as it's a group shape. Thanks!
