### ISSUE TITLE
Version History reverts to previous saved when clicked. 

### ISSUE THREAD

**Issue by eefaye46** [jgraph/drawio#2708]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Using Draw.io as a Confluence macro. When editing the diagrams and saving on screen it updates the versions. However after a few hours it reverts back to the original version. 

When clicked on 'Revision History' to view, it returns a blank screen. I am unable to get my latest edits to load T.T

On Chrome Version 99.0.4844.82 (Official Build) (64-bit)
On draw.io macro V7.4.5
![image](https://user-images.githubusercontent.com/49186196/159655102-4804b70f-27c2-4e38-bff3-39cd50e12862.png)

**Comment by davidjgraph** [comment]
When you say draw.io macro v7.4.5, where did you get this value from?

**Comment by eefaye46** [comment]
If you go to help you can see details of the versioning: 
![image](https://user-images.githubusercontent.com/49186196/159824693-bd7ab00f-ffd8-4bb9-a8f3-dfcd7ed98675.png)

**Comment by mararad** [comment]
Thanks. You are using a very old drawio version released in 2018-05-15. 

Suggestions would be to update drawio version to the latest compatible: https://marketplace.atlassian.com/apps/1210933/draw-io-diagrams-for-confluence/version-history and also test if you see the same issue in other browsers and Incognito mode.
