### ISSUE TITLE
Dimension shape does not render correctly at larger stroke widths

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#271]
Dimension shape does not render correctly at larger stroke widths.

For example:

shape=dimension;direction=west;whiteSpace=wrap;html=1;align=center;points=[];verticalAlign=top;spacingTop=-8;labelBackgroundColor=#ffffff;strokeColor=#000000;strokeWidth=20;fillColor=none;

**Comment by mararad** [comment]
The issue reproduced in Incognito and Chrome Version 74.0.3729.131 (Official Build) (64-bit), Win10.
Strokes even larger than 5 cause a rendering issue. for dimension shapes.
![dimensionshapesdoesntrender](https://user-images.githubusercontent.com/44292306/62698624-d8ef8e80-b9dd-11e9-9142-7c2e12ef85b7.gif)

**Comment by ashrafteleb** [comment]
Fixed
