### ISSUE TITLE
Unexpected color changes in diagrams

### ISSUE THREAD

**Issue by oliversalzburg** [jgraph/drawio#2713]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

Diagrams created on a light theme have unexpected color changes when shown in an editor with dark theme (and likely vice versa).

**To Reproduce**
1. Go to app.diagrams.net
2. Ensure Atlas Theme is set
3. Create new diagram
4. Create rectangle by double-clicking the rectangle icon. A white rectangle with a black outline is created on the canvas
5. Save your diagram
6. Switch theme to dark and reload the page
7. You now have a black rectangle with a white border

**Expected behavior**

My white rectangle with black border is retained and displayed as-is. This simple case does not fully illustrate how a complex diagram will flip colors _in parts_ while retaining the author's color selection in others. I can see how this is intended as a convenience feature, but the result is anything but.

When I originally opened the diagram, which was authored on light theme, I assumed what I was seeing to be a result of the improper background color of the diagram. So in my editor, which is in dark theme, I changed the background color of the diagram to white. Only to realize that now other parts of the diagram (the parts that were auto-color-converted) are now unreadable.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 17.2.1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox Developer
 - Version 99

**Additional context**

Originally reported as https://github.com/hediet/vscode-drawio/issues/308

**Comment by mararad** [comment]
Please attach a video showing all the steps and the result. I wasn't able to reproduce this so video could help.

Thanks,

**Comment by oliversalzburg** [comment]
OK. Here it is: https://www.youtube.com/watch?v=tiapy1R5qDA I neglected to enable recording the mouse cursor. I hope you can follow along.
