### ISSUE TITLE
Table cell borders disappear when after enabling the Fill option

### ISSUE THREAD

**Issue by Xylandor** [jgraph/drawio#2714]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
By default, a table object's cells have a transparent background (Fill option disabled). Once enabled, the cells' borders disappear or are hidden. Tried disabling and re-enabling the cells' Line property in hopes that it triggers an update to show them, as well as, changing line colors, but to no avail.  

**To Reproduce**
1. Add a Table object. Doesn't matter if it's the one with or without a header.
2. Select all cells in the table and under Style, click the Fill option to enable it. Ensure the color you choose is not the same or close to the color of the cells' Fill color. Notice the borders are no longer shown. 

**Expected behavior**
When the Fill option is enabled for the cells and the fill and border colors differ, the app should still show the borders. 

**Screenshots**
<img width="789" alt="image" src="https://user-images.githubusercontent.com/24617679/159973586-c79c861c-825c-43b9-a2ab-fb798713643e.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 17.2.1

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur v. 11.4
 - Browser MS Edge and Chrome
 - Version:  MS Edge (99.0.1150.46),  Chrome (99.0.4844.83)

**Comment by alderg** [comment]
Select the table and set the LaneColor or select the cells and tick the Left, Right, Top and Bottom properties in the Property section of the style panel.

**Comment by Xylandor** [comment]
Selecting the table and setting LaneColor had no effect; however, selecting the cells and checking the properties Left, Right, Top and Bottom worked. 

I'm new to DrawIO. The properties portion, by default, is collapsed, so I missed that originally. So thank you, @alderg, for the help. I now understand how the table/cell objects work. 

One improvement that can be done is have the LRTB Line checkbox options displayed with the Line property section for easier access, instead of under the Properties section which can be easily missed; just as I did. In my opinion, if the Line checkbox is checked, the LRTB options should auto-check. It's misleading when you have one or more cells selected and it shows the Line option is check, but no lines appear.
<img width="535" alt="image" src="https://user-images.githubusercontent.com/24617679/160129544-ad18d9e2-fbbe-4d64-a8aa-49ed1ffa4b01.png">

**Comment by Erimus-Koo** [comment]
Select the cell, and try this, it works for me.
<img width="198" alt="image" src="https://user-images.githubusercontent.com/17139670/235984576-fcfdb7b6-6c89-4fa6-b85b-4169db8d6d7f.png">

**Comment by alkcbs** [comment]
> Select the cell, and try this, it works for me. <img alt="image" width="198" src="https://user-images.githubusercontent.com/17139670/235984576-fcfdb7b6-6c89-4fa6-b85b-4169db8d6d7f.png">

This worked for me, thanks. This is not intuitive and a fix would be great.
