### ISSUE TITLE
Cannot save to root folder in SharePoint library

### ISSUE THREAD

**Issue by ezuzito** [jgraph/drawio#2715]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**The bug**
I cannot save a new diagram to any root folder in any sharepoint library.
Saving to any subfolder works correctly.

**To Reproduce**
1. Create a new diagram.
2. Click on 'Select folder'.
3. Click on 'Sharepoint'.
4. Navigate to any library, but stay on root folder.
5. Click on 'Save'.

**Expected behavior**
The document should be saved to root folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/102323700/159995884-2db8fea3-b7bd-4bab-9ddd-37c43391db49.png)

**draw.io version**
- draw.io version 17.2.2

**Desktop**
 - OS: Windows 10 Pro v.21H1 19043.1586
 - Browser Microsoft Edge Chromium 64bits v.99.0.1150.46

**Comment by ashrafteleb** [comment]
Hi @ezuzito,

I believe this is the expected behavior. In OneDrive interface we cannot do anything in the root. Is it possible in your case.
![Screen Shot 2022-03-25 at 8 28 28 AM](https://user-images.githubusercontent.com/24944765/160120817-b458e0a7-39ea-43a3-8624-75f8f6ac35fb.png)
But root
![Screen Shot 2022-03-25 at 8 28 50 AM](https://user-images.githubusercontent.com/24944765/160120863-a3825cc6-4b2d-4ccc-8b48-7cb26e8d6d46.png)

Let us know how it works in your OneDrive

**Comment by ezuzito** [comment]
Hi @ashrafteleb,
I think you're misunderstanding me. I'm talking about the root directory of a document library (your first screenshot), not a site (your second screenshot). Please try saving a diagram in the "Documents" library, but not in a subfolder, and tell me if it works for you.
By the way, I'm talking about SharePoint and you mention OneDrive, but your screenshots look like SharePoint. Please confirm that we are in the same context.
Thanks in advance.

**Comment by ashrafteleb** [comment]
Hi @ezuzito,

Yes, I can save to documents under Sharepoint sites. I'm using OneDrive to access Sharepoint sites

Back to your issue, please open the browser console (press F12) and share with us any error when you try to save to Documents. Also, does this error occur if the Documents folder already have files/folders [please manually upload to it using Sharepoint/OneDrive]

Thanks

**Comment by ezuzito** [comment]
Hi @ashrafteleb,
I can save to diagrams under SharePoint sites too. The issue is related only to the root folder of a library. Following your request, I tested with the following results:

1. If I try to save to the library...
  ![image](https://user-images.githubusercontent.com/102323700/160134445-93869cf1-1cd8-4e4f-9d82-34cce83a5a9e.png)
  ...it shows an error window...
  ![image](https://user-images.githubusercontent.com/102323700/160133617-89f4d107-c565-4895-ad1d-a059edfbacc4.png)
  ...but there isn't any error on console
  ![image](https://user-images.githubusercontent.com/102323700/160133769-23df699a-66cc-41a5-844d-58e385f54676.png)
2. If I enter the library, it shows the subfolders on the root folder...
  ![image](https://user-images.githubusercontent.com/102323700/160134277-721c6338-43b7-4cc4-a9f6-2bf1d38aed80.png)
  ...and when I click on "save", the document is saved on the subfolder instead of the root folder
  ![image](https://user-images.githubusercontent.com/102323700/160134905-f815c9de-75a5-45b1-99dc-f5ec5a377c08.png)
3. If I try to save the document in a document library without subfolders on the root folder...
  ![image](https://user-images.githubusercontent.com/102323700/160135302-d8bb2c58-0a23-4982-8dd5-8b3e42facac5.png)
  ...it shows the same error window as the first case...
  ![image](https://user-images.githubusercontent.com/102323700/160135564-7af02c07-f812-470a-ba7a-97abe84074f3.png)
  ...and again there isn't any error on console
  ![image](https://user-images.githubusercontent.com/102323700/160135642-104a9677-395f-4153-9ab5-c6b81ee4e820.png)

In all cases I can save documents in the root folder of each library. It seems to be an interface error, not an API problem.
I hope I have explained myself clearly. If you need any more testing on my side please ask for them.
Thank you and greetings.

**Comment by ezuzito** [comment]
Hi @ashrafteleb,
I've done one more test. I moved a diagram to the root folder of a library and verified that I can see the document:
![image](https://user-images.githubusercontent.com/102323700/160140864-ee67153e-f496-466e-a9d7-97ec744a31e9.png)
I can open it, make changes, and save it, without errors.
It is clearly an interface issue when choosing the folder to save.

**Comment by ashrafteleb** [comment]
Will be fixed in the next version
Thanks for the report
