### ISSUE TITLE
Exporting diagram in certain formats causes Uncaught TypeError

### ISSUE THREAD

**Issue by Xylandor** [jgraph/drawio#2717]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Exporting a diagram to any of the following outlined formats produces raises an Uncaught TypeError; however, it still exports just fine.
![image](https://user-images.githubusercontent.com/24617679/160158910-d24e84aa-5877-4cba-84de-9ff98ab6b4c9.png)

![image](https://user-images.githubusercontent.com/24617679/160161093-ef273192-c7c0-4066-8297-e441f01e633b.png)

**To Reproduce**
1. Open/Create a diagram.
2. Click on File > Export As > PNG
3. On the Image dialog, leave everything as default and click Export.
4. Choose where to save the file.
5. After exporting, the error should display; however, it does save it just fine.

**Expected behavior**
After the app has exported the diagram, the error message should NOT be displayed.

**Video**
The following video will demonstrate the behavior.

https://user-images.githubusercontent.com/24617679/160160383-6c6745b7-ef55-42f2-87de-879207030af9.mov

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 17.2.3

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur v. 11.4
 - Browser MS Edge and Chrome
 - Version:  MS Edge (99.0.1150.46),  Chrome (99.0.4844.83)

**Comment by davidjgraph** [comment]
Thanks for the report, fixed in 17.2.4.
