### ISSUE TITLE
Simplify XML to output only objects and its relations

### ISSUE THREAD

**Issue by MalarvizhiK** [jgraph/drawio#2719]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Ask for a tool/feature: I am looking for a tool that can convert Exported XML from draw.io architecture and output a simplified XML with only objects and its relations. 

Do you have any such tool ?  Can you provide a tool or suggestions to implement a tool ?  Thanks.
 

**To Reproduce**
1. Go to File - Export as - XML (uncheck compressed). 

The XML has the diagrams info with mxCell, mxGeometry, mxPoint with source, target, etc. 

**Expected behavior**

1. Go to File - Export as - Simplify XML (with objects and its relations). It should give me a simplified XML without x, y, cell data with only objects, parent, source, target.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**
16.5.1
- draw.io version [e.g. 12.6.7]
16.5.1

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS Big Sur
 Desktop draw.io tool
16.5.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by davidjgraph** [comment]
This is outside the scope of this project.
