### ISSUE TITLE
Support label links for BPMN shapes

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#2720]
Make Formatted text ticked by default so shape labels can be linked. 
Reported in DID 4589

Tested with Call activity shape and wanted to link a label. It wasn't possible until Formatted text was ticked. Once ticked make other BPMN shape labels linkable. Happens in Chrome and FF (online and 10.1.4 server version) Other general shapes don't require the additional step.
![formatted](https://user-images.githubusercontent.com/44292306/160360069-0e4cb26c-ae3d-498a-9a15-2d17e8ea745a.JPG)

**Comment by egrimate** [comment]
The fix will be in the next release
