### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by TimFinkler** [jgraph/drawio#2721]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I try to link a .drawio file to another .drawio file in OneDrive I get this error message:
'_Uncaught TypeError: Cannot read properties of undefined (reading 'value')_'

**To Reproduce**
Be logged in with OneDrive.
1. Open an existing .drawio file from OneDrive, or create a new one.
2. Add a new diagram element like a rectangle, or choose an existing one.
3. Right click on that diagram element.
4. Choose 'Edit Link' in the menu.
5. Click the 'OneDrive' icon.
6. Choose a different .drawio file in the popped up OneDrive menu
7. Click 'open'
8. See error

**Expected behavior**
I expected the diagram to be linked successfully, so I can click the link to make it pop up in a new tab/window.

**Screenshots**
![image](https://user-images.githubusercontent.com/47118158/160812454-3873dd12-3b1f-4440-adae-65a8cc22849a.png)

**draw.io version:**
- draw.io version 17.2.6

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Microsoft Edge
 - Version 99.0.1150.46

**Comment by mararad** [comment]
Hi,

Try the following: open the target diagram file in diagrams.net (File > Open from > OneDrive), copy URL,
get back to the source diagram in diagrams.net > right mouse click Edit link > paste URL > Click Apply

Does this help?

Regards,

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by TimFinkler** [comment]
> 

Yes, @mararad this works. Thanks!!!
