### ISSUE TITLE
Data in edge lost on open

### ISSUE THREAD

**Issue by maarnold2** [jgraph/drawio#2722]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
After adding data to an edge and exporting document to XML, opening the document from the XML file loses the Data in the edge. Importing from XML retains the Data in the edge.

**To Reproduce**
1. Create a flowchart
2. Right-click on a vertex and click Edit Data.
3. Create a Data property name and value.
4. Click Apply
5. Right-click on an edge and click Edit Data.
6. Create a Data property name and value.
7. Click Apply
8. Click File, click Export as, click XML
9. Save to local device.
10. Exit and reenter app.diagrams.net.
11. Select Open Existing Diagram
12. Choose the saved XML file.
13. Right-click on the vertex and select Edit Data and observe the data are retained.
14. Click Cancel
15. Right-click on the edge and select Edit Data and observe the data are missing.
16. Exit and reenter app.ldiagrams.net
17. Select Create New Diagram
18. Click File, click Import from, select Device
19. Choose the save XML file.
20. Right-click on the vertex and select Edit Data and observe the data are retained.
21. Click Cancel
22. Right-click on the edge and select Edit Data and observe the data are retained.
23. Click Cancel

**Expected behavior**
I would have expected, upon opening the file from the saved XML, that the Data in the edge would have been retained.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 17.2.4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser firefox
 - Version firefox 94.0.2

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mararad** [comment]
Hi,

I tested this is Chrome Version 99.0.4844.84 (Official Build) (64-bit) with 17.3.0 and it's working well.
Is it working in other browsers and Incognito mode when all browser extensions are temporarily disabled?
Also hard reload and check if 17.3.0 version has the same problem.

If nothing helps, please attach a video showing all the steps and the result.

**Comment by maarnold2** [comment]
Hi,

Retested. It works  in the Firefox browser and in the desktop 17.2.4 for Windows. Opening an existing XML does retrain the user-defined Data in the edges. You may close this ticket.

Thanks,

Mark Arnold
