### ISSUE TITLE
Transparent background on text above lines should mask lines

### ISSUE THREAD

**Issue by tandy-1000** [jgraph/drawio#2724]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
You cannot have text overlapping a line with a transparent background.
E.g. in lucidchart you can have a transparent background for text, but there will be a mask so that if the text is over an object, the text will remain readable.

**Describe the solution you'd like**
Add some sort of transparent mask to text so that it remains readable when it overlaps an object. 

Edit: add picture example.
![image](https://user-images.githubusercontent.com/24867509/161269803-f2ed42c2-8614-4686-ba52-ff1ded4bce13.png)

**Comment by mararad** [comment]
Hi,

Please provide an example (e.g print screen) of feature you'd like to have.

Thanks,

**Comment by tandy-1000** [comment]
I added a picture, hope it helps.

**Comment by tandy-1000** [comment]
Bumping this issue :)
