### ISSUE TITLE
Remember export options

### ISSUE THREAD

**Issue by augustebaum** [jgraph/drawio#2729]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'd like to save my drawing as a PNG file, but the default resolution is too low. Hence, every time I make a change, I have to go through the export menu to increase the resolution.

**Describe the solution you'd like**
This issue would be solved by one of the following:
- A configuration option to change the default export resolution;
- A checkbox "Remember these settings" in the Advanced Export settings menu
- Once the export has been made with a given resolution, when the drawing is saved as PNG it is saved with that resolution;
- An option to specify that whenever the drawing is saved, it should be exported as PNG at a particular resolution.

The last one could then be extended to do certain things whenever the file is saved, e.g. also export as PDF (which I need as well).

**Describe alternatives you've considered**
Using a Makefile.

**Comment by JamesO2x** [comment]
I would like to second this request. Currently, when I export my diagram to `PNG` format, I have to manually do the following every single time: 

1. Change Size from "Diagram" to "Page"
2. Tick "Transparent Background"
3. Tick "Grid"
4. Untick "include a copy of my diagram"

Its very tedious if you have to make many small changes to your diagram over time.

It would be very useful if (at the very least) these export options would be saved and remembered in the `.drawio` file format.

It would be extra useful if the program would auto-export on save.

**Comment by augustebaum** [comment]
I'd like to keep this open.
