### ISSUE TITLE
I want to make a web page with question-answer workflow designer

### ISSUE THREAD

**Issue by MohammedAbdulMateen** [jgraph/drawio#273]
The question-answer workflow designer should look like as shown below,

![question](https://user-images.githubusercontent.com/17563774/41721459-8e5bca7c-7583-11e8-8735-d2b363bd8224.png)

I've searched a lot and found that jgraph/mxgraph and jgraph/drawio are close to what I'm looking for, but I don't know where to start, I see that all the code is given but no getting started guide where I can added only features I need and add them step by step by checking and learning more about them to tune it to my requirements.

I need to have a toolbox similar to drawio from where user will drag and drop the tool box item onto the screen and it will be inserted.

The diagram is made up of nodes and edges, there are 3 types of nodes i.e. User Question, Follow-up Question and Answer and there are 3 types of connections to a node i.e. Direct (one to one), Choice (one to many), If-else (two)

Please provide guidance on how to approach to create a workflow designer as shown in the above image.

Thanks in advance

**Comment by davidjgraph** [comment]
I'm afraid we don't provide high level design consulting as part of this project. I would suggest to employ a professional software engineer to advise you in this regard.

**Comment by MohammedAbdulMateen** [comment]
Can I at least filter out the features ? suppose I only want start, rectangle, stop and connectors ? please give me a starting point

**Comment by davidjgraph** [comment]
Use mxGraph, https://github.com/jgraph/mxgraph, not draw.io.

**Comment by MohammedAbdulMateen** [comment]
Okay thanks, I will go through it and if I get stuck at the same or different question can I raise a new/same issue there at https://github.com/jgraph/mxgraph ?

**Comment by davidjgraph** [comment]
Issues for mxGraph would go in the mxGraph issue tracker
