### ISSUE TITLE
Request: HTML export with table of content

### ISSUE THREAD

**Issue by AlexanderLauf** [jgraph/drawio#2731]
Dear development team,

First of all, thank you for this great tool. It is always a lot of fun to work with it, especially because it is so simple but still makes so much possible.

I would like to request the following feature. 
The export to HTML works fine, but useability would increase for larger projects with multiple tabs to have the ability to use a table of contents.
An example is a function provided by Slidy. If you press "C" a table of contents pops up. (See: https://www.w3.org/Talks/Tools/Slidy2/Overview.html#(1))

Thank you very much for considering my request.

**Comment by davidjgraph** [comment]
Thanks for your suggestion, but that is outside the scope of this project.
