### ISSUE TITLE
When diagram page is used as background image, it fails to display PNG added as Confluence page attachment

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#2733]
drawio 10.1.5 in Chrome and Chrome Incogniro Version 100.0.4896.75 (Official Build) (64-bit) and Firefox

The following works: 
Create page 1 (master page) and Drag&Drop png from desktop
Create page 2, click "Change" Background and choose Diagram content Page 1
=> Png is displayed on Page-2 (target page)

The following doesn't work:

Add png as Conf page attachment
Create page 3 (master) and add png via "+" > Image > From this page
Create page 4, change Background and choose Diagram content Page 3
=> Png is not displayed on Page 4 (target page)

P.S
Not sure why page is not displyed well in Con view and there are scroll bars (maybe just at my place)

When Background image is clicked in page 4 > Change, there is image URL and right placed field Height is cut off 
![cut off](https://user-images.githubusercontent.com/44292306/161741472-93de106d-1a1e-4bdd-866b-635d381f32b1.jpg)

Print screens in https://test4501.swift-wiki.net/display/TES/Test+logo

**Comment by davidjgraph** [comment]
Fix in 24.0.3
