### ISSUE TITLE
Microsoft Teams plugin is broken

### ISSUE THREAD

**Issue by arcane-tl** [jgraph/drawio#2735]
**Describe the bug**

The draw.io plugin in Microsoft Teams doesn't work. It gives an error message stating that the .drawio -file is "Not a diagram file".

diagrams.net version which was used to create the file: 17.2.4

![image](https://user-images.githubusercontent.com/70339038/161913666-afa59859-bcc7-42ad-9f90-1875176f41f3.png)

Also creating a diagram from scratch is not working:

![image](https://user-images.githubusercontent.com/70339038/161915092-2eb1a9b6-1c03-47a4-8fff-d0b8f1fe0ec3.png)

**To Reproduce**
----- bug with existing file -----
1. Open Teams client
2. Open a channel of your choosing which you have permission to add tabs
3. Add a new tab using draw.io plugin
4. Find a file using either Sharepoint or Onedrive
5. Behold the error message

----- bug with new file -----
1. Open Teams client
2. Open a channel of your choosing which you have permission to add tabs
3. Add a new tab using draw.io plugin
4. Choose to add New diagram
5. Behold the error message

**Comment by davidjgraph** [comment]
Working for me both with existing file from OneDrive and new file. MacOS 12.3.1. Teams 1.4.00.35562.

**Comment by arcane-tl** [comment]
That's weird, I can't get it working. I'm using Windows 10 Enterprise (19044.1586) 64 bit with Teams 1.5.00.5967 (64-bit).

**Comment by arcane-tl** [comment]
Ok something changed or it was a temporary glitch or something went wrong when the tab was added to the channel as it now started working out of the blue after I did a third reinstall of the plugin.
