### ISSUE TITLE
I can not open my existing file

### ISSUE THREAD

**Issue by jlparedese** [jgraph/drawio#2737]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![error problem DRAW IO](https://user-images.githubusercontent.com/103114653/161961041-153742a0-f2e9-4a83-91ef-8ec08d3acd0d.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**
 - OS: WINDOWS 10PRO
 - Browser: chrome
 - Version 22

**Additional context**
I was working with draw.io and then it asked me to save a copy of my file. When I did it, it showed up a message is that attached here and I cannot open any file (the original one and the copy and it shows that message). I have plenty of information there for my PhD research. Could you please help me to recover all my information. I store the file in my google drive and the name of the file is "Regression Methodoologies". Thank you for your response

**Comment by mararad** [comment]
Since the file is saved to Google Drive, check if some earlier version can be opened.

We don't have access to our users' diagrams but if possible attach drawio file so we could test it. You can also submit all the details to support@diagrams.net if you don't want file to be shared publicly here.

Regards,
