### ISSUE TITLE
OpenStack stencil pack

### ISSUE THREAD

**Issue by chateaulav** [jgraph/drawio#2738]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Missing stencil packs for OpenStack resources.  
See closed issue for initial request that had been made #952 

**Describe the solution you'd like**
I would like support for cloud resources icons leveraged within OpenStack to be added, as no other product has this implemented. I have a local draw.io file that i leverage; however would love native support.

Performing further research, they are leveraging basic font awesome icons with a circle around them.

https://github.com/openstack/heat-dashboard/tree/f9b3be622f7bbfad52487a4b44f129b926634401/heat_dashboard/static/dashboard/project/heat_dashboard/template_generator/js/resources

Also discovered some previous work, but would be great to have it natively available.

Font Awesome Licensing
https://fontawesome.com/v4/license/

**Describe alternatives you've considered**

* publish a static file with icons, but that is cumbersome and creates to many steps
* submit a pull request, but dont have enough time or am familiar enough to quickly determine how to integrate

**Additional context**
I do not mind helping, just need pointed in the right direction.

**Comment by chateaulav** [comment]
To help enable consistent inclusion see the below links for official icons

Main Project reference for icon resources in `heat-dashboard`:  

https://opendev.org/openstack/heat-dashboard/src/branch/master/heat_dashboard/static/dashboard/project/heat_dashboard/template_generator/js/resources


as reference the GitHub mirror for the main project `heat-dashboard`:  

https://github.com/openstack/heat-dashboard/tree/master/heat_dashboard/static/dashboard/project/heat_dashboard/template_generator/js/resources

**Comment by chateaulav** [comment]
@davidjgraph please let me know if anything doesn't meet standards, finally had time to sit and review past commits to determine how to integrate new packs.

**Comment by egrimate** [comment]
Will be in next release
