### ISSUE TITLE
Labels displaced, fit to window fails

### ISSUE THREAD

**Issue by chipbite** [jgraph/drawio#2739]
### Preflight Checklist

* [ x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
_After yet more testing:_ 
I have reproduced in ui=min in chrome. I am attaching an anonymized diagram where I get the issue.
**_Issue:_**
Labels are displaced, but placed correctly when scrolling up to them.
Fit to window does not work consistently.
Both issues are inconsistent.
**_See example screenshots below._**

**To Reproduce**
1. Open large drawing, probably best.
2. View lower part, pan up. 
3. View labels of shapes further up appearing in "the middle of nowhere".
4. Scroll further up so shapes with displaced labels are completely in view
5. Displaced labels are now drawn in their correct locations in the shapes where they belong.
6. Repeat 2-5 for different diagrams.

Also, press ctrl-shift-h: Expect view to be fit to window, it now often shows a part of the diagram.

**Expected behavior**
Labels stick where they have been placed. Fit to window works as expected.

**Screenshots**
I will get back with screenshots, bear with me.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 17.4.0

**Desktop (please complete the following information):**
 - OS: Win
 - Browser : chrome
 - Version:  99.0.4844.84 

**Additional context**
I have tested in a few different contexts, I have not been able to reproduce it in standard / ui=kennedy.

Started around 3 days ago. Have not had time to report it.
I have have managed to reproduce it with little trouble.
Will get back with example file, if you cannot reproduce it. But it has appeared for several diagrams for me.

BR! /marcus

Example:
![image](https://user-images.githubusercontent.com/559199/162751393-7f887a23-e72a-4c7e-9a9b-88c88b42bac9.png)

The sample file used for that example, where I get the issue:
![ANON labels displaced example Interaction Diagram drawio](https://user-images.githubusercontent.com/559199/162751754-6f1ae5ac-8785-49b7-b5fe-813f73af37a0.svg)

(running as chrome app:
![image](https://user-images.githubusercontent.com/559199/162150557-3e7e435f-5933-427b-a8b6-68ad67ae8d11.png)
)

**Comment by chipbite** [comment]
I am in training most of the day, it seems that now I know how to avoid the issue. I will get back with more info. I need to run anon plugin in "chrome app"  (what is the term) window and then I give more detailed account / screenshot/share.

**Comment by davidjgraph** [comment]
Chrome app, that's the PWA installed using Chrome?

**Comment by chipbite** [comment]
Hi! So, it turns out I get it in normal webapp as well. Not sure if it is data dependent somehow.
I could not repro with ui=kennedy. Updated the description with shots and sample data file where I get the issue.

**Comment by chipbite** [comment]
Two other examples of this, which is fairly constantly happening, seemingly only if I run ui=min:
![image](https://user-images.githubusercontent.com/559199/162949487-7d25810a-8356-4cfa-b686-df8c19dda846.png)

and
![image](https://user-images.githubusercontent.com/559199/162949367-d52fb1d0-8b00-4f95-b7ba-bdfae05add53.png)
