### ISSUE TITLE
Auto-reload page when trying to change the size of the shape in Arrange tab (Edge)

### ISSUE THREAD

**Issue by LearnedWords** [jgraph/drawio#274]
Microsoft Edge 41.16299.15.0
Microsoft EdgeHTML 16.16299
Windows 10 Update 1709
draw.io 8.8.6
ThinkPad Yoga

1. Change the size of a shape in one of width/height in the Arrange tab - don't press Enter
2. Tab or click with the mouse into the other size (width/height)
3. Webpage is forcibly reloaded dropping you to the 'create new diagram' screen. 

[drawio-bug.mp4.zip](https://github.com/jgraph/drawio/files/2128465/drawio-bug.mp4.zip)

Tested on IE on the same computer and there is no problem. 
Tested on Safari, Firefox, Chrome on a Mac and there is no problem.

**Comment by mararad** [comment]
I reproduced the steps but all works well at my place.

Win 10,
Microsoft Edge 44.18362.267.0
Microsoft EdgeHTML 18.18362
draw.io 11.1.2
![reoprtedbuginedge](https://user-images.githubusercontent.com/44292306/62699405-bc545600-b9df-11e9-9da7-f0d79e3bcd0c.gif)
