### ISSUE TITLE
`service-worker.js` requested from webroot `/` even though `DRAWIO_BASE_URL` contains path

### ISSUE THREAD

**Issue by osnard** [jgraph/drawio#2740]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
If DrawIO is hosted in a subdirectory of the webroot, the "editor" tries lo load `service-worker.js` from `/` rather than from `/<path>` and fails with status 404.

**To Reproduce**
1. Configure `DRAWIO_BASE_URL` as `https://server/drawio/`
2. Run application on `https://127.0.0.1:8080/`
3. Setup ReverseProxy (e.g. via Apacher Webserver), that forwards `https://server/drawio/` to `https://127.0.0.1:8080/`
4. Use `https://server/drawio/` in an IFRAME embedding scenario

**Expected behavior**
DarwIO application can be loaded properly in the same way as id the IFAME would embed the diagrams.net endpoint

**Screenshots**
- draw.io version 17.1.3

![image](https://user-images.githubusercontent.com/1201528/162214434-f5a9b7fc-2a96-465a-99b7-9ad37738f36b.png)
![image](https://user-images.githubusercontent.com/1201528/162214588-f4820282-6a45-4c49-a364-b70aeaef460b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 99

**Smartphone (please complete the following information):**
N/A

**Additional context**
Issue occurs when embedding a self hosted DrawIO application using an IFRAME

**Comment by MichaelGerhart** [comment]
We are also running into this issue. When trying to run Draw.io as a subpath to a gitlab installation in kubernetes, some of the static assets are being sent to webroot instead of https://gitlab.domain.com/-/draw/

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
