### ISSUE TITLE
Diagram inserted in Powerpoint via the addin doesn't show custom system font

### ISSUE THREAD

**Issue by gotson** [jgraph/drawio#2741]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When inserting a diagram in Powerpoint by using the official draw.io addin, the custom system font of the diagram is not respected, and another font is shown.

**To Reproduce**
1. Create a new diagram, use a custom system font for text
2. Insert diagram in Powerpoint by using the addin
3. The font is not correct

**Expected behavior**
The font should be the correct one.

**Screenshots**
<img width="655" alt="Screenshot 2022-04-08 at 10 09 59" src="https://user-images.githubusercontent.com/2139133/162349629-fd2d5b60-050d-4917-a44c-04f71a32c07b.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: 17.2.4

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version 99.0.4844.84 (Official Build) (arm64)

**Additional context**
I zipped the drawio, exported png, and ppt [here](https://drive.google.com/file/d/18ceLmr4hSbvPI9OcvLRQReM4vGV48vGA/view?usp=sharing).

**Comment by davidjgraph** [comment]
The image we generate is done on a server. For it to see a custom font you'd have to use a public web font URL that the server can see.
