### ISSUE TITLE
Letter Spacing/ kerning style

### ISSUE THREAD

**Issue by Joerockclimber** [jgraph/drawio#2744]
It would be awesome if the text had some sort of kerning\ letter spacing style. Letters are currently really close together.

**Comment by alderg** [comment]
As a workaround, you can use the letter-spacing CSS style by entering <span style="letter-spacing: 3pt">Hello, World</span> in the HTML view of the label:
![58e9563a63c1bf6608b0ae19ae3be8ce](https://user-images.githubusercontent.com/921200/162557948-c28d7ba8-e3ec-4999-8da5-69460c445fc7.gif)
