### ISSUE TITLE
Eye Dropper Request

### ISSUE THREAD

**Issue by kstella** [jgraph/drawio#2746]
I would be nice to have an eye-dropper tool like Photoshop has, to pick up the full style of one object, and apply it to another. 
It would save time when I paste elements from elsewhere, or simply change my mind.

I've played with editing specific elements with the existing tools, as well as editing the code under lying the object (which I find quite helpful!)

_I searched for "eye dropper", but there may be another analogous request that I missed_

**Thanks everyone for your hard work on a great tool!**

**Comment by alderg** [comment]
Shift+click on the color box and then select the eye dropper icon.
