### ISSUE TITLE
When using parameter offline=1, "File - Export as - PDF" doesn't hide

### ISSUE THREAD

**Issue by arnowelzel** [jgraph/drawio#275]
According to https://desk.draw.io/support/solutions/articles/16000042546-what-url-parameters-are-supported- you can use `offline=1` to disable features which require external servers - which also includes PDF export, as this requires a call to exp.draw.io.

However - even this parameter set, the menu item for "File - Export as - PDF" is still there, but it is in fact just calling the print dialog, but with "PDF" as title, which is quite confusing.

See as an example (in both cases I could reproduce this behaviour):

https://www.draw.io/?offline=1&demo=1
https://www.draw.io/?offline=1

It would be better, if "PDF" would be removed from the "Export as" menu when using `offline=1`.

**Comment by arnowelzel** [comment]
"Print to PDF" is not "Export to PDF" because it depends what features your browser and/or local printer setup supports. So there should not be a menu item called "Export as - PDF" if this is just invoking a print dialog.

At least in Firefox the functionality of "Export to PDF" in offline/stealth mode is exactly the same to "File - Print" - both commands behaves exactly identical. If I would like to use "Print to PDF" I would just use the "File - Print" and then choose the respective feature of my computer.

**Comment by davidjgraph** [comment]
We have a large non-technical audience, if you don't point them at print to PDF when the remote service isn't available, they won't know the feature is available.

**Comment by arnowelzel** [comment]
Hmm... but many other features are also not available in this mode:

File - Export As - Advanced
File - Embed - Google Sites
File - Embed - Google Docs
File - Open Library from - Google Drive
File - Open Library from - Github
etc...

Shouldn't these menu items not also be available then with a dialog "sorry, this feature is not available because stealth mode is active" or something similar (or shown as disabled menu items), so people know that these features generally exist, but are just disabled?

And I doubt that a non-technical audience knows how to do "Print to PDF" after pressing "Print" in that dialog - because this will just open the normal print dialog of the browser:

![image](https://user-images.githubusercontent.com/6613614/41857895-d1adc9c0-7898-11e8-8383-42aeb280431a.png)

It depends on your local setup, if there is a "PDF printer" on the computer available or not.

**Comment by davidjgraph** [comment]
Since the desktop version replaces the offline browser version and that deals with this issue correctly, I'm marking issue as resolved.
