### ISSUE TITLE
LaTeX Tikz format? any prospective?

### ISSUE THREAD

**Issue by juanfal** [jgraph/drawio#2750]
**Tikz** is the most powerful and smart system for scientists to draw intelligent figures inside LaTeX.  Today it is supported by a wide and mature community.  This amazing **drawio** app is really a great interface to draw any kind of diagram.  It could be amazing it could save those diagrams to be inserted in serious scientific papers.

Thanks

**Comment by ianclarksmith** [comment]
You'd like to generate TikZ code from a diagram drawn in draw.io, is that right? Given the export tools which already exist in the app, you could export as SVG or PDF and use Inkscape to convert to LaTeX. But if using TikZ for the power it offers, why not write it directly?

**Comment by davidjgraph** [comment]
I think SVG is enough for this, the resources for adding and maintaining another full export can be better applied elsewhere.
