### ISSUE TITLE
diagram lost all of sudden

### ISSUE THREAD

**Issue by khatriprajwol** [jgraph/drawio#2754]
I was making ERD in app.diagram.net and I have not saved it when I was working. And all of sudden my entire work is gone and it gave me an option to create or import diagram again. is there anything I can do to get it back? I had saved earlier version of my file in my device but when I was updating it, this happened to me.

**Comment by davidjgraph** [comment]
Did you try undoing the change? The whole diagram disappeared in-place or the browser crashed?

**Comment by khatriprajwol** [comment]
Actually yes! I went through the history and tried if I could restore the page but it did not work. I have no idea what happened.

**Comment by davidjgraph** [comment]
Could you fill in all the details in the bug template?
