### ISSUE TITLE
Commit Github file size limit

### ISSUE THREAD

**Issue by youyongsong** [jgraph/drawio#2755]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Can't save big diagrams to github

Similar to #816 

Seems GitLab has increased the file limit to 10MB, hope Github can also increase the file size limit to 10MB.

**To Reproduce**
1. Go to File
2. Click on Save
3. Click on Commit wirh a message

Error saving file
Drawing is too large (3.4MB / 1 MB)

**Expected behavior**

**Screenshots**
![](https://draft-1301224571.cos.ap-nanjing.myqcloud.com/2022/04/14/CleanShot%202022-04-14%20at%2017.28.48.png) 

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 17.4.4]

**Additional context**

**Comment by GloomyNAN** [comment]
You can try to re-authorize github

**Comment by GloomyNAN** [comment]
same to me

**Comment by davidjgraph** [comment]
This should be increased to 50.
