### ISSUE TITLE
Kubernetes Shapes do not show any labels correctly

### ISSUE THREAD

**Issue by lastcoolnameleft** [jgraph/drawio#2759]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When creating a Kubernetes shape, if you try adding a label to it, the text goes on top of the shape, instead of below it (like most shapes). (see attached image)

**To Reproduce**
1. Create a new page
2. Click on Kubernetes
3. Drag any Kubernetes shape to the page
4. Double click on the shape and start typing
5. Be sad because you can't read your text.  (It's hidden behind shape)

**Expected behavior**
The text should be clear to read, BELOW the shape, not on top.

**Screenshots**
![Screen Shot 2022-04-15 at 12 06 52 PM](https://user-images.githubusercontent.com/686999/163599797-63205336-3c67-46e2-8ae4-1e0c308b34cd.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version VSCode extension

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser VSCode Extension
 - Version v1.6.4

**Additional context**
I am using this from VSCode extension; however, given that it uses the mxKubernetes file, the runtime location should not matter.

**Possible Solution**
I have determined that if you add the "image" style _BEFORE_ the shape, then it renders correct.

I believe the problem exists here:
https://github.com/jgraph/drawio/blob/dev/src/main/webapp/shapes/mxKubernetes.js#L77-L101

Style which renders incorrect:
```
sketch=0;html=1;dashed=0;whitespace=wrap;fillColor=#2875E2;strokeColor=#ffffff;points=[[0.005,0.63,0],[0.1,0.2,0],[0.9,0.2,0],[0.5,0,0],[0.995,0.63,0],[0.72,0.99,0],[0.5,1,0],[0.28,0.99,0]];shape=mxgraph.kubernetes.icon;prIcon=api
```

Style which renders correct:
```
sketch=0;html=1;dashed=0;whitespace=wrap;fillColor=#2875E2;strokeColor=#ffffff;points=[[0.005,0.63,0],[0.1,0.2,0],[0.9,0.2,0],[0.5,0,0],[0.995,0.63,0],[0.72,0.99,0],[0.5,1,0],[0.28,0.99,0]];image;shape=mxgraph.kubernetes.icon;prIcon=api
```

**Comment by lastcoolnameleft** [comment]
After some additional testing, I think a better solution (instead of setting `image`) would be:

`labelPosition=center;verticalLabelPosition=bottom;align=center;verticalAlign=top;`

**Comment by egrimate** [comment]
Will be fixed in the next release.

**Comment by csakaszamok** [comment]
Unofrtunetly, this bug is still exists !

**Comment by davidjgraph** [comment]
As we believe this was previously fixed, please open a new issue.

**Comment by csakaszamok** [comment]
Sure, https://github.com/jgraph/drawio/issues/4386
