### ISSUE TITLE
Ubuntu serveur Install 

### ISSUE THREAD

**Issue by Spartacus2018** [jgraph/drawio#276]
Hello, 
i m looking for how to install drawio, on my local network, i have a ubuntu serveur at home, 

how to install drawio on it please ?

**Comment by christw92** [comment]
According to the readme, you could install docker (see ://docs.docker.com/install/linux/docker-ce/ubuntu/)

And then execute:

docker build -t draw .
docker run -d -p 8888:8080 draw

 the app will be accessible at http://localhost:8888/draw/?https=0

If this is not what you want to achieve, please describe your problem/goal more detailed.

**Comment by Spartacus2018** [comment]
i don't want use docker, because i want create a package for Yunohost server.

before i need to know how install draw whitout docker

**Comment by davidjgraph** [comment]
Take the built jar from the release and deploy to a servlet engine, like Tomcat.

**Comment by gamersalpha** [comment]
it's easy to say ...

**Comment by gamersalpha** [comment]
ok u right ...
