### ISSUE TITLE
plantuml CJK font pitch bug

### ISSUE THREAD

**Issue by ssmxgo** [jgraph/drawio#2760]
![image](https://user-images.githubusercontent.com/8423162/163669785-7c1bc4f1-0969-4b3b-8c21-8ad9d75354f7.png)

```
@startuml
class "路線図"
路線図 : "現在地の表示"
@enduml
```

**Comment by davidjgraph** [comment]
Unfortunately, if this is the diagrams.net deployment, we cannot fix this. We use AWS lambda for PlantUML export and that limits the available fonts somewhat. You'd better with your own PlantUML deployment on a non-linux machine for this case.

**Comment by ssmxgo** [comment]
I think that it can be displayed by the following implementation

`sudo apt-get install fonts-ipafont fonts-ipaexfont`

**Comment by davidjgraph** [comment]
There is no command line on AWS lambda to run this. I'm aware of the fixes when there is shell access, but none apply in this case.

**Comment by ssmxgo** [comment]
Sorry In japanese

i find easy fix
https://yongjinkim.com/chrome-aws-lambda%E6%96%87%E5%AD%97%E5%8C%96%E3%81%91%E3%81%99%E3%82%8B%E6%99%82%E3%81%AE%E7%B0%A1%E5%8D%98%E3%81%AA%E8%A7%A3%E6%B1%BA%E6%96%B9%E6%B3%95/

`const chromium = require('chrome-aws-lambda');
...
// add this
await chromium.font('https://raw.githack.com/minoryorg/Noto-Sans-CJK-JP/master/fonts/NotoSansCJKjp-Medium.ttf');
`

other
Add fonts to Lambda runtime environment
https://qiita.com/komeda-shinji/items/e049edd1389579059c53

**Comment by ashrafteleb** [comment]
Fixed. Thanks for the pointers

**Comment by ssmxgo** [comment]
![image](https://user-images.githubusercontent.com/8423162/164135096-f697304b-05e2-4871-b320-7be888baf9bf.png)
I confirmed the fix result
Thank you, everyone
