### ISSUE TITLE
[Seek Help] how can we draw connect line

### ISSUE THREAD

**Issue by heartacker** [jgraph/drawio#2762]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
how can we draw a connect line 
like this
![image](https://user-images.githubusercontent.com/1876302/163811393-7025ec9b-18b9-4672-ba06-0f52185a618a.png)

and if we change the position, they will be still connected

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 
diagrams.net 17.4.2

**Comment by mararad** [comment]
You can use 2 lines (General library), a waypoint shape (Misc library) and group them all so you can move it together.

**Comment by heartacker** [comment]
@mararad  thanks you very much, help me a lot
