### ISSUE TITLE
Some Images are broken links when exported as SVG

### ISSUE THREAD

**Issue by lastcoolnameleft** [jgraph/drawio#2763]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

When exporting a diagram to SVG and then uploading to Github, some images are broken links.

**To Reproduce**
1. Go to app.diagrams.net and create Blank Diagram
2. Click "Search Shapes" enter "Docker"
3. Drag the first shape onto canvas.  (The blue whale)
4. Export to SVG, download to computer
5. Go to gist.github.com and drag-and-drop svg to upload
6. Be sad because svg shows broken link

**Expected behavior**
It should look like this:
![docker drawio](https://user-images.githubusercontent.com/686999/163825155-8ffa6a00-dd00-4923-8200-764d1be7cd9e.png)

But instead looks like this:
https://gist.github.com/lastcoolnameleft/e1b663a2e0a0c806df2ad4155cec712e

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: 17.4.5

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: chrome
 - Version: 100.0.4896.75

**Additional context**
Here is the raw file for my example: https://gist.githubusercontent.com/lastcoolnameleft/e1b663a2e0a0c806df2ad4155cec712e/raw/4c3ab5f0a41bd2876d01a4ef0fbba115151d1e5e/docker.drawio.svg

If you open the developer console, you see the following errors:

```
Refused to load the image 'https://app.diagrams.net/img/lib/mscae/Docker.svg' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.
```

I believe this is the reason for the broken images.

**Comment by chrisweis** [comment]
Just passing by and didn't analyze this deeply, but it seems like that docker.drawio.svg image "raw file" references an underlying SVG image (https://app.diagrams.net/img/lib/mscae/Docker.svg) - which itself works OK in app.diagrams.net

**Comment by daviewales** [comment]
I'm getting this too. Would it be possible to embed the referenced SVG images directly in the saved drawio SVG, rather than having them as external references?

**Comment by alderg** [comment]
githubusercontent seems to insert a CSP that causes this error in the browser console:

`Refused to load the image 'https://app.diagrams.net/img/lib/mscae/Docker.svg' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.`

Serving it from a website without that CSP works for me.

**Comment by daviewales** [comment]
Thanks @alderg. However, 'Embed Images' is not an option for 'Save As -> Editable Vector Image'. Would it be possible to make this option available in this case?

**Comment by saulogt** [comment]
I did the same test. The file generated contains a path to the icon file inside the app itself, which obviously will not work out of my computer.
```
<image x="-0.5" y="-0.5" width="50" height="41" xlink:href="file:///Applications/draw.io.app/Contents/Resources/app.asar/drawio/src/main/webapp/img/lib/mscae/Docker.svg"/>
```

**Comment by jan-hudec** [comment]
> Just passing by and didn't analyze this deeply, but it seems like that docker.drawio.svg image "raw file" references an underlying SVG image (https://app.diagrams.net/img/lib/mscae/Docker.svg) - which itself works OK in app.diagrams.net

GitHub has a strict content security policy which prevents the external images from loading. It works in some sites, e.g. Sharepoint, which have more permissive setting.

However while for the online version this works provided the embedding site has sufficiently permissive content security policy, the desktop version (see the above mentioned issue) uses the local links, and I suppose any custom installation will use its own links, and those won't work basically anywhere. So embedding the icons would be preferable.

**Comment by TH-OC** [comment]
We use the convert to svg option for our drawio diagrams so we can embed it in our README.md file in GitHub whilst still being editable. The filename becomes filename.drawio.svg (remains editable), but some icons do not render in GitHub. I think this is the same issue. Is there a better way to maintain and editable drawio diagram in git, and have it embed in the README.md file without having to continually export a new png every time someone makes a change to the diagram?

**Comment by jan-hudec** [comment]
@TH-OC, you can have editable `.drawio.png` files too, and those will render everywhere. The downside is that it's a bitmap, so it does not scale as well.

**Comment by TH-OC** [comment]
@jan-hudec, thanks, I'll give that a try as a workaround. Some of our architecture diagrams are very large, hence why .svg is preferable. Hopefully this bug will get fixed at some point :-)

**Comment by alderg** [comment]
We've added an Embed option in the edit image dialog. Try using that for those images in your diagram.
<img width="398" alt="Screenshot 2023-09-04 at 11 38 27" src="https://github.com/jgraph/drawio/assets/921200/be382e7c-0939-47db-b4af-3f5d4d13dd9b">
<img width="382" alt="Screenshot 2023-09-04 at 11 38 56" src="https://github.com/jgraph/drawio/assets/921200/d342b481-4d33-44bc-909c-e115311a0fbf">
<img width="543" alt="Screenshot 2023-09-04 at 11 39 07" src="https://github.com/jgraph/drawio/assets/921200/e8d079aa-653d-445d-9e01-e1508a08e04a">

**Comment by pixelbits-mk** [comment]
Thanks @alderg, that worked beautifully. To summarize the issue and the solution: SVG images created from diagrams.net do not render some images that were "pasted" in.  The reason is because these images are URL references, and Github README.md files do not allow downloading of image references.  The solution is to "embed" the images into your drawio document.  Follow @alderg instructions above, and embedded images will display as intended.
