### ISSUE TITLE
I can't save .drawio files to private repo on Github

### ISSUE THREAD

**Issue by GHA193** [jgraph/drawio#2765]
### Preflight Checklist

* [√] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [√] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I can't save .drawio files to private repo on Github. 
When I click "Unsaved changes. Click here to save" and select Github, there is no private repository I set in the repository list, which was fine a week ago.

**Expected behavior**
The repository list should show the private repository I set up.

**Screenshots**
It was fine a week ago.
![image](https://user-images.githubusercontent.com/24401268/163956821-1522fba2-fbc1-4bdc-b027-70bab1e98787.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [17.4.2]

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Chrome 100.0.4896.88

**Comment by GloomyNAN** [comment]
You can try to re-authorize github

**Comment by achutharaman** [comment]
Unable to connect with Private repo.

**Comment by davidjgraph** [comment]
Closing as we don't have a reproduction case. If you have one, please open a new issue.
