### ISSUE TITLE
Doller signs ($$equation here$$) is visible not formula in full screen mode after embeding diagram into HTML file.

### ISSUE THREAD

**Issue by kuldeep-suthar** [jgraph/drawio#2771]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Let's Say I added an equation in my diagram by using mathematical typesetting like this $$\dfrac{x}{y}$$. And I embeded my diagram into an HTML file. The diagram looks great on my webpage after that however, when I click on fullscreen button on my web page the equation is no longer in math mode. It shows just as I typed the code between the double doller signs like "$$ equation code here $$".

**To Reproduce**
1. Create a Diagram with a TeX equation like $$\dfrac{x}{y}$$. Make sure you toggle "Mathematical Typesetting" from Extra > Mathemetical Typesetting
2. Now, File > Embed > HTML. This will open a dialogue box with so many options. Make Sure "Lightbox" is checked and then click on "Create".
3. A code will be generated. Copy and Paste it in "body" tag of HTML file and Save it.
4. Open the file in your browser and hover over the diagram. A lightbox will appear on the border of your diagram with options on top of diagram like Zoom Out, Zoom In, Fit and Fullscreen.
5. Click on Full Screen and a Popup window will open in your browser showing the Diagram in Full Screen.
6. But Unfortunately our Math Equation No Longer is in Math as it was without fullscreen mode. Those Double Doller Signs are visible Instead of Math Code.

**Expected behavior**
After I Opened my diagram in Full Screen Mode, the math equation should be same as that was without full screen mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/91888201/164934092-08a9906a-165d-48d7-969c-6b01daf966e0.png)
The above image is **without** full Screen mode on a web page after embeding diagram in HTML file.
![image](https://user-images.githubusercontent.com/91888201/164934105-8bf7b845-a3ab-4235-816e-1900014b979a.png)
The above image is in full Screen mode on a web page after embeding diagram in HTML file.

**draw.io version (In the Help->About menu of the draw.io editor):**
17.4.5...
- draw.io version [e.g. 12.6.7]
17.4.5
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox Developer Edition

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mararad** [comment]
Does it work in other browsers and Incognito mode, please?
I tested this in Chrome Version 100.0.4896.127 (Official Build) (64-bit) and diagrams.net 17.4.6 and it is working at my place.

If browser change doesn't help, please attach a video showing all the steps and the result so I could check if I followed your exact steps. 

Thanks,

**Comment by kuldeep-suthar** [comment]
@mararad I checked for this error just before writing this comment in Chrome, Firefox, Firefox Developer Edition, MS Edge in Widows 10. When it's not in full screen then its working fine but when i open full screen mode it's not showing equations correctly.

**Comment by kuldeep-suthar** [comment]
@mararad Here's a video from my android device. Same error is happening on PC as well

https://user-images.githubusercontent.com/91888201/165078456-5930ebec-575c-4654-8bb2-142e7e60e770.mp4

.

**Comment by alderg** [comment]
We're unable to reproduce this problem. Please attach the HTML file or a link the HTML file.
