### ISSUE TITLE
SVG document size is larger than draw.io document size

### ISSUE THREAD

**Issue by verticalegg** [jgraph/drawio#2774]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When saving/exporting a document as a SVG file, the viewBox and page size are incorrectly set with a 0.5 unit border on all sides.

**To Reproduce**
1. Create a new document 
2. Set the paper size to a preset like "4:3 (1600 x 1200)"
3. Export as SVG
4. Open SVG in a different editor and look at page size/view box

**Expected behavior**
The page size and view box should be the same as the size specified in the page size dropdown.

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 17.4.6

**Desktop**
 - OS: ChromeOS
 - Browser: Chrome
 - Version: 96.0.4664.206

**Comment by mararad** [comment]
Hi,

Which SVG editor are you using?
Please attach print screens showing page size and view box differences.

Thanks,
