### ISSUE TITLE
Horizontal Tree Layout connection edge disorder after expansion

### ISSUE THREAD

**Issue by baibhavr** [jgraph/drawio#2777]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

In the horizontal tree layout diagram, as we add more and more boxes(with tree folding settings on) and edges, the edges completely deform and move to the edge of the canvas when we collapse and expand boxes. This completely messes up the diagram after collapsing or expanding boxes.

**To Reproduce**
1. Go to Advance shapes on the left tab
2. Click on Horizontal tree layout
3. Check the _tree folding_ checkbox property of the boxes used in the tree
4. Add its children, grandchildren, and so on
5. Collapse and expand those boxes
6. The edge will get more and more disordered as we increase the number of boxes in the tree 

**Expected behavior**
The boxes should collapse and expand with the tree foldings as necessary but most importantly all diagrams and edges in the file should maintain the edge shapes.

**Screenshots**
![deformed edges](https://user-images.githubusercontent.com/4075633/165889593-43ab9ca8-a54e-47d3-bf2d-580b8a6fa89c.jpg)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 17.4.6

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - Browser Google-chrome
 - Version 100

**Comment by mararad** [comment]
Does it help if you tick "Tree folding" (instead container) for a parent shape in Property/Value?

**Comment by baibhavr** [comment]
My bad, I have updated the comment. These boxes in the tree were not containers. And their tree folding property was checked.
