### ISSUE TITLE
Export to .vsdx - connector text rotated

### ISSUE THREAD

**Issue by dawnrene** [jgraph/drawio#278]
When exporting from Draw.io to Visio (.vsdx), the text on my connectors is rotated. 
Attached are the files: original done in Draw.io
![original_drawio](https://user-images.githubusercontent.com/40668423/42042781-e763cf40-7ac2-11e8-9427-2793ce43a673.jpg)

The output in Visio
![exported_visio](https://user-images.githubusercontent.com/40668423/42042780-e7514fc8-7ac2-11e8-942a-dfba86f938da.jpg)

**Comment by kasper747** [comment]
Can confirm. Visio Pro 2016.

**Comment by davidjgraph** [comment]
Fixed in 8.9.8
