### ISSUE TITLE
3D Canvas and/or STL format export

### ISSUE THREAD

**Issue by LBoullosa** [jgraph/drawio#2792]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Mainly, I am looking for a way to export a simple diagram to a 3D model. STL is suggested because it´s supported by GitHub to be used inside README.md , so we could navigate through the model.

The farther step would be create a 3D diagram from drawio. This requirement would help moving forward [The Standard](https://github.com/hassanhabib/The-Standard) from Hassan Habib to represent Software Engineering Architecture scenarios which 2D makes complicated represent some innovative design patterns in a simple way.

**Describe the solution you'd like**
1) Have an option to export the 2D diagram (as actually works) to STL format.
2) Have a 3D Canvas which allows pulling the current 2D objects and then could be exported to STL format.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by davidjgraph** [comment]
Thanks for your suggestion, however, this feature is outside the scope of the project.
