### ISSUE TITLE
Add Salesforce diagrams icons to library

### ISSUE THREAD

**Issue by ernestovalent** [jgraph/drawio#2793]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem?**
No, I would like icons to be added

**Describe the solution you'd like**
Now Salesforce have a design guide to make diagrams using design Templates

**Additional context**
About Salesforce Templates:

- Videos: [Youtube playlist](https://www.youtube.com/playlist?list=PLn15mOuXqGJUOc-iPmMcLb0HGi4wusJpv)
- Docs: [architect](https://architect.salesforce.com/design/diagram-templates/doc-implementation-templates/)

**Comment by ashrafbaker** [comment]
Hello,
I'm interested in this issue as well, is there any news? Or workaround?
Thanks

**Comment by BocheJosue** [comment]
This point is very interesting for the organization of processes

**Comment by camilocaquimbo** [comment]
Please implement this, could be very interesting, thanks

**Comment by davidjgraph** [comment]
If you wish to vote on the issue, thumbs up the original post. "Me too" post cause noise and add nothing useful.

**Comment by egrimate** [comment]
Will be in next release

**Comment by davidjgraph** [comment]
In 22.0.1
