### ISSUE TITLE
Exported img is black when edited with dark theme

### ISSUE THREAD

**Issue by mrx23dot** [jgraph/drawio#2795]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**To Reproduce**
Set Dark theme (to be easy on eyes when editing)
draw anything
export as jpeg

**Expected behavior**
exported jpeg should be usable, ie not black, but it's black

**Screenshots**
![console](https://user-images.githubusercontent.com/4163396/167107188-9be4085b-5d83-41f1-8632-a88525b3324b.jpg)

- draw.io version 17.4.2

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] win10
 - Browser [e.g. chrome, safari] chrome, but using it offline 
 - Version [e.g. 22]  100.0

**Smartphone (please complete the following information):**

**Comment by alderg** [comment]
Untick "Dark" option in the export dialog?
