### ISSUE TITLE
Find/Replace doesn't replace multiple times

### ISSUE THREAD

**Issue by Edgeworth** [jgraph/drawio#2799]
### Preflight Checklist

* [ X ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ X ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The find/replace tool finds the text but only replaces the first occurrence. Replace all also doesn't really work. Seems unclear what the semantics for find/replace are - it's at least very unclear to me what it's meant to do.

**To Reproduce**

1. Create a text block with multiple occurrences of the same text
2. Find/replace that text
3. Replace only replaces one occurrence (even if run multiple times, or replace all is used)

**Expected behavior**
To replace every occurrence 

**draw.io version (In the Help->About menu of the draw.io editor):**

diagrams.net 18.0.1

**Desktop (please complete the following information):**
 - OS: linux
 - Browser: chrome
(both browser and desktop version are affected.

**Comment by ashrafteleb** [comment]
In order to replace all occurrences, you need to use Regular Expression (most of the cases, just activate it and use the word as is)
For more details: https://www.diagrams.net/doc/faq/find-shapes

**Comment by Edgeworth** [comment]
This happens regardless if regex is enabled or not.

**Comment by ashrafteleb** [comment]
Please send me the test diagram and string to find and replace

**Comment by ashrafteleb** [comment]
The issue will be fixed in the next release. But you still need to check "Regular Expression" to replace all occurrences

Thanks for the report

**Comment by sba923** [comment]
I'm still facing this in 20.8.16...😭
