### ISSUE TITLE
export to native PowerPoint or Office Shapes

### ISSUE THREAD

**Issue by volvox88** [jgraph/drawio#2802]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I want to share my diagrams with other team members.
But they use PowerPoint most of the times, so I need to convert into a native PowerPoint for them to edit.

I tried to export drawio files into .svg and convert to .emf/.wmf files and then insert into PowerPoint.
I also tried to export into .vsdx files and open in Visio and copy into PowerPoint.

Yes, It can be converted to Office Shapes. But broken into pieces which make our team member hard to edit.

For example, a rectangle 

![image](https://user-images.githubusercontent.com/105200627/167372375-89d376e4-7a86-45fe-9bb7-a5f5de081709.png)

may broken into

![image](https://user-images.githubusercontent.com/105200627/167372484-332df488-4d59-4d85-b2a3-ea2604a22f43.png)

So styling/text editing/resizing becomes difficult.

**Describe the solution you'd like**
Support export basic shapes to native PowerPoint files or other vector graphs which can be imported into PowerPoint.
And keep border+background+text all in one shape, just like drawing them in PowerPoint directly.

**Describe alternatives you've considered**

**Additional context**

**Comment by mararad** [comment]
Hi,

diagram exporting to ppt(x) is not supported but you can use:
https://appsource.microsoft.com/en-us/product/office/wa200000113
https://www.diagrams.net/doc/faq/microsoft-office-diagrams

Regards,

**Comment by volvox88** [comment]
> Hi,
> 
> diagram exporting to ppt(x) is not supported but you can use: https://appsource.microsoft.com/en-us/product/office/wa200000113 https://www.diagrams.net/doc/faq/microsoft-office-diagrams
> 
> Regards,

Yes, I've seen this addon. But others still need to edit the shape, so not an option for me.

**Comment by davidjgraph** [comment]
Unfortunately, this is outside the scope of the project. It's a good candidate for someone to write a parser that takes the drawio format and converts it. That way it can be developed and maintained seperately from the main project.
