### ISSUE TITLE
can't open files in this folder because it contains system files

### ISSUE THREAD

**Issue by nutmix** [jgraph/drawio#2804]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
If I chose "Device" as my storage option, I cant create or save any files, I always get "can't open files in this folder because it contains system files".  The folder in question is one I have saved to many times before, and just contains my documents (its nothing to do with system files).  The folders in question happen to be on onedrive on my Mac.

**To Reproduce**
1. select "device" as your storage
2. try to create a new file, selecting a local folder under your home dir.
3. get the error: "can't open files in this folder because it contains system files"
**Expected behavior**
document to save correctly.

Strangely, there are some dirs I can save to, e.g. downloads, but most dirs give this error for no apparent reason, and they used to work.

**Screenshots**
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/5080942/167411224-02f0b96a-dcac-488e-901f-685c831389c3.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]
18.0.1 web 
chrome Version 101.0.4951.54 (Official Build) (arm64)
MacOS 12.1

**Comment by murphyke** [comment]
> The folders in question happen to be on onedrive on my Mac.

I suspect this is the relevant factor. I have the exact same issue. At the very least, the error message could be made more informative.

**Comment by SalW0** [comment]
Hi, I have the same problem above described. Can someone tell me how resolve it? I have lots of files I cannot open anymore.

**Comment by HariKrishnaJay** [comment]
Hi, I have the same problem described as above. Can someone tell me how to resolve it?.
Diagrams.net version 20.8.18

**Comment by davidjgraph** [comment]
More the diagrams to a folder that doesn't contain system files?

**Comment by raisindetre** [comment]
This issue isn't confined to OneDrive usage. I am working on a managed Windows 10 machine with OneDrive sync confined to the default OneDrive directory. Saving a *.drawio file to a clean directory on the local filesystem (no system files) generates this dialogue box and prevents saving. This was previously possible several weeks ago when I was last working with the app (browser version only).

**Comment by nutmix** [comment]
I noticed I also can’t open new drawings.

I deleted the newly app, then downloaded and installed it again. It now works. So it’s the upgrade path which seems to have broken it.

From: raisindetre ***@***.***>
Reply to: jgraph/drawio ***@***.***>
Date: Monday, 13 February 2023 at 23:29
To: jgraph/drawio ***@***.***>
Cc: Simon Hobbs ***@***.***>, Author ***@***.***>
Subject: Re: [jgraph/drawio] can't open files in this folder because it contains system files (Issue #2804)


This issue isn't confined to OneDrive usage. I am working on a managed Windows 10 machine with OneDrive sync confined to the default OneDrive directory. Saving a *.drawio file to a clean directory on the local filesystem (no system files) generates this dialogue box and prevents saving. This was previously possible several weeks ago when I was last working with the app (browser version only).

**Comment by xyzzy11** [comment]
Hello,
I am having this issue. Is there a fix for this?

**Comment by raisindetre** [comment]
> The only workaround is to copy your files to another folder like "Documents"

Thanks, I did try saving to other folders including "Documents" and "Downloads" with the same result, however I'm on a corporate managed system with a networked home drive and don't have administrator access or permissions over files so I'm wondering if this is the limiting factor (no System files show up in target directories when hidden files are displayed). I could try clearing the cache and seeing if this forces an upgrade of the browser-based app to overcome the issue but in the meantime have used Github storage as a workaround.

**Comment by m-mohamedin** [comment]
Can you please try this sample app which use the same APIs. Does it work?
https://googlechromelabs.github.io/text-editor/

**Comment by xyzzy11** [comment]
> 

This does not work with the same error.

I too have copied my .drawio file to my documents dir and tried. No difference.


> Can you please try this sample app which use the same APIs. Does it work? https://googlechromelabs.github.io/text-editor/

**Comment by m-mohamedin** [comment]
> > 
> 
> This does not work with the same error.
> 
> I too have copied my .drawio file to my documents dir and tried. No difference.
> 
> > Can you please try this sample app which use the same APIs. Does it work? https://googlechromelabs.github.io/text-editor/

Unfortunately, if this app by Google doesn't work, we have nothing to do. It looks like a bug (or a new restriction) in the latest version of Chromium browsers

**Comment by m-mohamedin** [comment]
There is a bug in Chromium here (https://crbug.com/1408321)

And a discussion on a similar issue here (https://github.com/WICG/file-system-access/issues/401/0

**Comment by raisindetre** [comment]
Confirming that the Google app throws the same error - so it does seem to be browser based. Thanks for looking into it.

**Comment by Joshua-Swain** [comment]
I'm using Edge. I had to move the file to a non-shared folder so that I could open it

**Comment by davidjgraph** [comment]
Edge is a chromium browser.

**Comment by xyzzy11** [comment]
Moving the drawio file does not work for me, same error.  

I was able to import the drawio file and it opened successfully and my diagram displayed. 

Once I redraw it another local draw tool this will likely be the end of my using web based tools.

**Comment by zardoy** [comment]
I know this is old but for those who are here from search: just use **dragndrop**. For devs: drag n drop API doesn't have this path check, still supports opening & saving files or folders and have even better platform support (e.g. folders read on IOS).
But if you still forced to have open dialog just use symlinks (e.g. on Windows: `mklink /J %USERPROFILE%\Desktop\Folder "<any path you want>"`)

Btw seems upstream bug was closed.

**Comment by davidjgraph** [comment]
If upstream is closed, we'll close too.

**Comment by aghasemi** [comment]
Hello,

I was directed ti this page after having the same issue, but using coder/code-server. Downloads and Documents didn't work (on macOS), but Public seems to work, so far.
