### ISSUE TITLE
Mathematical typesetting not rendering in tables

### ISSUE THREAD

**Issue by rahav** [jgraph/drawio#2807]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
None of the table or entity shapes render math symbols. Tried all three versions $$a = b$$, \(a = b\), and `a = b`. To be certain I copied the raw text from the table to any other shape in the same page and it renders well.

**To Reproduce**
1. Draw any of the entities into a page, e.g. Table 1, or Entity shape
2. Add a math letter sounded by one of the approved delimiters
3. Enable Mathematical typesetting
4. The math part of the text you typed will disappear
5. If you copy the same text to a text box or any other shape it will show

**Expected behavior**
Math letters should work in entity shapes as any other regular shape.

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version [e.g. 18.0.1]

**Desktop (please complete the following information):**
 - OS: [macOS]

**Comment by auersteve** [comment]
I am using 18.0.1 on MacOS Monterey. I do not have this issue. See attached image, with a simple equation inside a table. 
Not sure this will help diagnose the issue your are having, but the "style" of the table is 
shape=table;html=1;whiteSpace=wrap;startSize=0;container=1;collapsible=0;childLayout=tableLayout;
![Table with math](https://user-images.githubusercontent.com/38922226/167546460-2c651994-e78e-4416-bd34-6456818c5cbb.png)
.

**Comment by auersteve** [comment]
Glad to help. Sounds like a bug to me!

**Comment by rahav** [comment]
@auersteve I'm new to draw.io and trying to respect the processes. Who will flag this as a bug? Is that something that I do?

**Comment by auersteve** [comment]
Rahav
Go to https://groups.google.com/g/drawio <https://groups.google.com/g/drawio> (you’ve probably done this already) and then click on New Conversation. This gives you a place to flag the issue. Most of the time a draw.io <http://draw.io/> maintainer will respond. It’s up to them to them to decide if the issue is a bug, and, if so, when/if to fix it.
Steve

**Comment by alderg** [comment]
Math typesetting requires the Formatted Text option in the Text style panel to be checked.
<img width="624" alt="Screenshot 2022-08-22 at 11 49 22" src="https://user-images.githubusercontent.com/921200/185892891-d077a373-4510-483f-aa9c-3aeda4bb422a.png">
