### ISSUE TITLE
 plugins/tooltips.js causes Unknown error TypeError:k.overlay.getBounds

### ISSUE THREAD

**Issue by keif888** [jgraph/drawio#2808]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When using the tooltips.js plugin, and having another user change the diagram to add a Tool Tip, an Unknown error dialog box appears.
The text "TypeError: k.overlay.getBounds is not a function" is within the dialog box. 

**To Reproduce**
1. Have 2 or more users on the same diagram within Microsoft Teams Browser App version
2. Have the tooltips.js plugin configured for both user's
3. Add a tool tip on the 1st users diagram in the browser
4. Error shows in 2nd users browser

**Expected behavior**
The 2nd users browser should show the ToolTip icon on the shape that has been changed by the 1st user.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 18.0.2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 101.0.1210.39
 - Browser Firefox
 - Version 100.0 
 - Browser Chrome 
 - Version 101.0.4951.54

**Additional context**

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
