### ISSUE TITLE
How to attach a list of mandatory properties for every control in draw.io ?

### ISSUE THREAD

**Issue by MalarvizhiK** [jgraph/drawio#2809]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
For every control in draw.io like IBM/VPC instance, is there a way to map it with a list of mandatory properties that a user has to fill for drawing architecture diagram ?  

**To Reproduce**
1. Open draw.io. Select IBM Cloud stencil.
2. Go to IBM/VPC
3. Click Instance. Drag and drop the instance. Now, I need to right click, edit data and add property and its value.
4. How to fill each instance control with default set of properties ? Note: The list of properties will differ for each control.  

**Expected behavior**
I want to attach every control with a list of properties. Is there any way ? Note: The list of properties will differ for each control. I want my users to fill all values for a list of properties that differs for different controls. 

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**
16.5.1
- draw.io version [e.g. 12.6.7]
16.5.1

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS Big Sur
 Desktop draw.io tool
16.5.1

**Comment by davidjgraph** [comment]
That's not possible. draw.io is more a generic diagramming tool, you need something more specialised for that.

**Comment by MalarvizhiK** [comment]
@davidjgraph Is there any tutorial for draw.io available where I should be able to explore all features of the tool ?
