### ISSUE TITLE
Changes to file are logged in revision history but the actual changes were not saved

### ISSUE THREAD

**Issue by gibsongb** [jgraph/drawio#2813]
Really frustrating issue here, I made changes to a file and saved throughout the day yesterday (5/11) but when I opened the file this morning none of the changes from that day retained i.e. none of my changes from yesterday were saved. When I look at the revision history it has timestaps for all of my saves throughout the day but they too haven't retained my changes i.e. they're all identical and show a revision from the previous day (5/10). I was able to close the file and relaunch and continue where I left off yesterday, I even have autosave enabled, but still all of yesterday's work is lost.

**Comment by schnautzr** [comment]
I'm having this issue as well. I've attempted several manual saves and it's not working. I'm stuck with my previous revision even though it shows a revision history (and every revision is identical to the last version that was successfully saved).

**Workaround (for saving):**
1) Extras > Edit Diagram...
2) Copy the syntax to a text document for later use.

**Workaround (for loading):**
1) Extras > Edit Diagram...
2) Paste the syntax from your text backup.
3) In the drop-down, make sure "Replace Existing Drawing" is selected, then press [OK].

**Comment by alderg** [comment]
What version of the app are you using? What browser, operating system and where did you store the file? Does this happen every time you open the file or are any special steps needed?

**Comment by schnautzr** [comment]
> What version of the app are you using? What browser, operating system and where did you store the file? Does this happen every time you open the file or are any special steps needed?

This happens every time I open the file. I have tried loading it from my Google Drive, using a direct link bookmark, and even clearing the cache while refreshing the page.

**Comment by schnautzr** [comment]
> > What version of the app are you using? What browser, operating system and where did you store the file? Does this happen every time you open the file or are any special steps needed?
> 
> This happens every time I open the file. I have tried loading it from my Google Drive, using a direct link bookmark, and even clearing the cache while refreshing the page.
> 
> app.diagrams.net Version 18.0.4 Google Chrome Version 101.0.4951.54 (Official Build) (64-bit)

Interesting, I just updated Chrome to 101.0.4951.67 and had a successful commit.

**Comment by schnautzr** [comment]
Seems to be working now :)
