### ISSUE TITLE
Microsoft Certification for Teams

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#2814]
Asked in DND-513

"I wanted to know if there are plans for the company to undergo Microsoft certification of the draw.io Teams add-in? 
Here is the link to the Microsoft Certification program. 
https://docs.microsoft.com/en-us/microsoft-365-app-certification/docs/enterprise-app-certification-guide

**Comment by davidjgraph** [comment]
Realisitically, this is a no.
