### ISSUE TITLE
SVG file not imported correctly

### ISSUE THREAD

**Issue by victor-yon** [jgraph/drawio#2823]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I have 2 valid and almost identical SVG files, one can be imported as expected, but the other one looks empty after import.
This is not a visual issue with the editor, the result is the same when I export the diagram as pdf.

**To Reproduce**
1. File > Import from > Device ...
2. Select svg file

**Expected behavior**
I expect both images to appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/3708059/169084686-00b39661-a540-48a6-b221-b0b4e7c89695.png)

**draw.io version:**
- 18.0.7

**Desktop:**
 - Firefox for Ubuntu
 - Version  100.0 (64-bit)

**Additional context**
Not working SVG: 
![start](https://user-images.githubusercontent.com/3708059/169085548-03ec27b0-5597-4999-876f-2ed750a213fd.svg)

Working SVG: 
![start-2](https://user-images.githubusercontent.com/3708059/169085558-4df93286-cc7f-4c72-adf6-10fedfc26896.svg)

I don't find any issue with these files, they are both working well with other applications.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
