### ISSUE TITLE
Recent list does not include device/local files

### ISSUE THREAD

**Issue by mawid6** [jgraph/drawio#2825]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I work with alot of files both locally, in git, github and confluence. 
The "Recent" files misses to include local files (save to device).
This is really annoying, since re-opening the same files takes many clicks, and is a chore when you are working with several files at the same time for a task.

**To Reproduce**
1. Start drawio (using web app, app.diagrams.net), open a local drawing (e g `test.drawio`) from your device/local drive. Do some edit, save.
2. Close drawio and open it again
3. Go to `Open Recent` in the menu

**Expected behavior**
`test.drawio` is present in recent menu.

**Actual**
`test.drawio` has not been added to recent menu

**Screenshots**
![image](https://user-images.githubusercontent.com/77722885/169263489-307c35e2-0d90-4c28-ae24-babf5314a504.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 18.0.7

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19042.1706]
 - Browser chrome
 - Version 101.0.4951.67 (Official Build) (64-bit)

**Additional context**

* Example of recent functionality in webapp populated with local / device files:
  * https://googlechromelabs.github.io/text-editor/
  * https://web.dev/file-system-access/

**Comment by mararad** [comment]
Reproduced with 18.0.8 in Chrome and FF

The same issue was fixed in desktop https://github.com/jgraph/drawio-desktop/issues/963
