### ISSUE TITLE
File extension for draw.io desktop app

### ISSUE THREAD

**Issue by rafenden** [jgraph/drawio#283]
Would be nice if draw.io used its own file extension so it would be easier to associate files on the desktop, e.g. `Diagram.dxml` or `Diagram.draw`.

**Comment by davidjgraph** [comment]
Please post in https://github.com/jgraph/drawio-desktop

**Comment by rafenden** [comment]
This should be a cross-platform functionality.

**Comment by davidjgraph** [comment]
The web app is designed to be based on MIME type, not file extension.
