### ISSUE TITLE
Confluence Cloud: Diagrams not visible in new presenter mode

### ISSUE THREAD

**Issue by mawid6** [jgraph/drawio#2831]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Atlassian just very recently rolled out `presenter mode` to confluence cloud. Great feature, allows true full screen view of a page.
However, when entering into `presenter mode`, diagrams.net diagrams are not shown.

**To Reproduce**
1. Go to a page in your confluence cloud install, view a page with diagram on it
2. Click on presenter mode

**Expected behavior**
Page shows diagram
**Actual behavior**
Page does not show diagram

**Screenshots**
Page in normal view with diagram, choosing presenter mode:
![image](https://user-images.githubusercontent.com/77722885/169497394-e4f1554e-b295-4aa4-a300-22866dd2a443.png)

Page in presenter mode:
![image](https://user-images.githubusercontent.com/77722885/169496758-5178196d-3bb9-4cdc-aab1-efa1aee6851f.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version (confluence cloud)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome
 - Version 101.0.4951.67 (Official Build) (64-bit)

**Additional context**
* Have tried: Different viewer settings (simple viewer, etc)
* Other macros seem to work (that I have tried), e g: Table, image, expand macros...

**Comment by mararad** [comment]
Tried to test but I don't see it at the moment. Found "Presenter Mode is currently rolling out so if you don’t see it yet you should within the next few weeks." https://community.atlassian.com/t5/Confluence-Cloud-articles/Presenter-Mode-for-Confluence-is-here/ba-p/2018523

Will try it when becomes visible.
