### ISSUE TITLE
Regular expressions in find/replace not working

### ISSUE THREAD

**Issue by jaylapras** [jgraph/drawio#2833]
### Preflight Checklist
* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Repeating the example at https://www.diagrams.net/doc/faq/find-shapes
Several shapes have the inventory tag, and should be found by the search. 
They are found as expected when "inventory" is used.

Problem: When a regular expression is used as per the example, it sometimes finds the first occurrence, then throws an error: ea is null
/*inv* also finds the shape with the label "In stock" (once), which has no tags, and then throws the same error.

Web app.diagrams.net ver. 18.0.8, Firefox browser

Process video:
![reg-exp-in-search-problem](https://user-images.githubusercontent.com/60265913/169520364-93bf1cf8-1151-43b5-9c6f-eaf74158ee90.gif)

Diagram file:
![reg-exp-search-problem](https://user-images.githubusercontent.com/60265913/169520785-ef7b0cac-9a69-4fc4-ae89-0afbdc603e83.png)

**Comment by mararad** [comment]
Reproduced in FF 100.0.2 (64-bit) with 18.0.8 and in Chrome incognito.
In Chrome Incognito the error is shown like this:

![in chrome](https://user-images.githubusercontent.com/44292306/169799998-5a9cf0dc-9158-4fef-843d-e9a2e6682911.JPG)

File: 
[inventory.zip](https://github.com/jgraph/drawio/files/8753768/inventory.zip)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
