### ISSUE TITLE
Click on any component, menu item not working 

### ISSUE THREAD

**Issue by alfred-donald** [jgraph/drawio#2835]
### Preflight Checklist

* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by davidjgraph** [comment]
Please don't be lazy and avoid filling out the issue template. As it stands this report is useless and wastes our time.
