### ISSUE TITLE
Line start and Line end display "None" when double arrow is selected (from bottom of list)

### ISSUE THREAD

**Issue by dmfort** [jgraph/drawio#2839]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Line start and Line end display "None" when the double arrow line endings (or beginnings) are selected.
These are the bottom two choices and were added in response to:
https://github.com/jgraph/drawio/issues/2078

**To Reproduce**
1. draw 2 boxes
2. connect them with an arrow Connection
3. click on the line to select the connection
4. Select the Style tab of properties
5. click drop down arrow on Line end control
6. pick double arrow (hollow or solid) from the bottom of the list
7. Note control displays, "None" rather than a picture of the double arrow.

**Expected behavior**
Picture of the selected Line end
(as it does for the other Line ends)

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]
18.0.6 -- desktop
17.4.5 -- browser

**Desktop (please complete the following information):**
 Windows 10
 Chrome (and desktop app)
100.0.4896.127

**Smartphone (please complete the following information):**

**Additional context**
very small issue, so if it isn't easy to fix, don't worry about it.
I am happy to have the double arrows!
![DrawIO_LineEnd](https://user-images.githubusercontent.com/106115337/169909210-9cc0e3f4-1a01-48eb-b921-990d43a14c54.JPG)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by dmfort** [comment]
> Thanks for the report. This will be fixed in the next release.

All better now. thanks!
