### ISSUE TITLE
Unable to 'ungroup' after exporting as URL

### ISSUE THREAD

**Issue by sushiljainam** [jgraph/drawio#284]
- I created an image using draw.io.
- "Group"ed all components [rectangles and arrows].
- Exported as URL, shared it to a friend.
- He viewed the image tried editing it (that makes a different copy! It's okay.)
- While editing he is unable to "Ungroup" these components.

- I can do that in my copy of the image.

Is this a bug? Please solve it.

**Comment by davidjgraph** [comment]
Please provide a minimal, exact reproduction case.
