### ISSUE TITLE
Check presentation mode functions in conf cloud

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#2842]

**Comment by ashrafteleb** [comment]
It doesn't work. They created the container BUT with the same ID, so their javascript code that initialize the macro re-initialize the original one on the page!

`<div class="ap-content " id="embedded-com.mxgraph.confluence.plugins.diagramly__drawio5355218777891297267">`

**Comment by mawid6** [comment]
My bug report for confluence presenter mode: #2831

**Comment by davidjgraph** [comment]
Duplicate https://github.com/jgraph/drawio/issues/2831
