### ISSUE TITLE
Path to Dropbox folder is incorrect

### ISSUE THREAD

**Issue by ryanpcmcquen** [jgraph/drawio#2843]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When clicking 'Open Dropbox' in the upper left corner, you are taken to a path that does not match the path that is currently used for drawio:
<img width="135" alt="Screen Shot 2022-05-24 at 11 50 09 AM" src="https://user-images.githubusercontent.com/772937/170110901-5659700c-cdb5-40a0-9887-3fda0e388253.png">

**To Reproduce**
1. Go to any diagram.
2. Click on 'Open Dropbox' in the upper left corner.
3. Observe error on dropbox.com.

**Expected behavior**
The path would match what is used for storage currently (`/Apps/drawio-diagrams` instead of `/Apps/drawio`).

**Screenshots**
<img width="966" alt="Screen Shot 2022-05-24 at 11 50 03 AM" src="https://user-images.githubusercontent.com/772937/170111059-22976afb-c175-44e5-8ca8-bb8152ad884c.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 18.1.2

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Firefox
 - Version 100

**Comment by ryanpcmcquen** [comment]
This is still valid.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by ryanpcmcquen** [comment]
Thank you!
