### ISSUE TITLE
Migrate away from the Google Drive Realtime API

### ISSUE THREAD

**Issue by subhav** [jgraph/drawio#285]
I'd like to run a personal instance of draw.io, with my own API key for Google Drive.

However, every time I create or open a Drive file, draw.io times out with the following error in console: `Drive Realtime API Error: forbidden: Access denied to file.` Manually saving times out as well, but the file seems to be written correctly in Drive.

It seems [the Google Realtime API is deprecated](https://developers.google.com/realtime/deprecation), and new applications aren't allowed to use it, while old ones are grandfathered in for this year.

What are the plans to migrate off of the Realtime API? Is there some way I can avoid the Realtime API, but still use the Google Drive integration?

**Comment by asl** [comment]
@subhav in general yes, but you'd need to patch the source code a bit.
See https://github.com/asl/scd-diagrammer/commit/edf14c953ef72769bc5b620ee12a805beb2319b2 as an example hacky non-realtime integration that somehow works.

**Comment by davidjgraph** [comment]
Our implementation will be in, hopefully, by the end of the year. It's very complex and is taking up a lot of our resources, so we're not making it public until we release it, to avoid having to support it before it's stable.

**Comment by davidjgraph** [comment]
`rt=0` URL parameter

**Comment by alderg** [comment]
Using the following override should work:

DriveClient.prototype.loadRealtime = function(resp, success, error)
{
  success();
};

**Comment by subhav** [comment]
Overriding loadRealtime works, as far as I can tell. Thank you!

I'm excited to see the replacement implementation whenever it's ready, too. :-)

@asl Good to know you were able to get around this too; thanks for sharing your commit.
