### ISSUE TITLE
Support sequential function chart

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#2851]
"Is there a shape for sfc (sequential function chart) according to IEC 61131-3? I have searched for a long time and unfortunately found nothing. I have then put something together (see attachment), but would be nicer if there was an official Shape. "
Asked in DND 553

![1](https://user-images.githubusercontent.com/44292306/171606353-6b9106d3-c0d0-406b-8e33-22c445d782e1.png)
![2](https://user-images.githubusercontent.com/44292306/171606357-91dd1397-9c76-4142-929d-f8d10d68c1aa.png)
[diagram file.zip](https://github.com/jgraph/drawio/files/8822749/diagram.file.zip)
[SAG_L50_sfc_Ofentor_en.zip](https://github.com/jgraph/drawio/files/8842737/SAG_L50_sfc_Ofentor_en.zip)

**Comment by LasseLFM** [comment]
Have they made any yet? :D
