### ISSUE TITLE
"flowAnimation=1" for shapes

### ISSUE THREAD

**Issue by tiziano149** [jgraph/drawio#2852]
Hello draw.io community,

is it possible to animate shapes the same way you would animate connectors with "flowAnimation=1;"? I'm not sure if I'm missing something but it doesnt seem possible atm and I guess it would be easy to implement. Especially for highlighting elements on an image with for instance an animated circle this would be very helpful. :)

Tiziano

**Comment by alderg** [comment]
This is currently not possible.
