### ISSUE TITLE
How can I add custom attribute in mxCell tag of mxgraph?

### ISSUE THREAD

**Issue by tuannguyenvan3795** [jgraph/drawio#2854]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by davidjgraph** [comment]
We don't support mxgraph here.
