### ISSUE TITLE
when drag a inserted url image，will request the url many times.

### ISSUE THREAD

**Issue by perseveringman** [jgraph/drawio#2859]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
when i insert a image by url, then drag it, the network will request many times.

**To Reproduce**
1. insert a image by url
2. drag it or resize the window
3. watch the network tab
4. See many times image url requests.

**Expected behavior**
I think the reason is x and y are in "image" tag, when change it ,will redraw the image.
If the x and y in the parent of "image" like  a "g" tag, and not redraw the image, maybe can fix it.

**Screenshots**
<img width="764" alt="截屏2022-06-06 下午6 50 11" src="https://user-images.githubusercontent.com/17445000/172147119-4a34e686-1782-4459-a01c-9817c366f877.png">

**Comment by davidjgraph** [comment]
I can't repeat that, at worst the cached browser version is used.
