### ISSUE TITLE
fix: drawio offline - closing application too fast whilst exporting to png results in corrupted png file

### ISSUE THREAD

**Issue by rhofer** [jgraph/drawio#286]
## Actual behavior
When exporting a drawing to png:

![image](https://user-images.githubusercontent.com/8058166/42690749-cee507e2-86a5-11e8-8e15-114d945617b8.png)

and selecting the option to 
* [x] Include a copy of my diagram

![image](https://user-images.githubusercontent.com/8058166/42690817-05717886-86a6-11e8-8bf5-b0b6fdbd7c0f.png)

then pressing button Export, and now **immediately** closing the application, leads to a corrupted export file (png).
* There is no indication that Export is still ongoing
* Export / save procedure seems to be **not** protected, what allows to close the application whilst export is still ongoing. Hence, leads to abort of export.

## Expected behavior
* Status of Export procedure is visualized and/or
* Application cannot be closed as long as export and persistance procedure is not finished

## Version info
* draw.io offline v 8.9.4
* host win10

**Comment by davidjgraph** [comment]
draw.io desktop replaces the offline setting in the majority of cases. If the problem can be reproduced there, please submit a ticket to the desktop project.
