### ISSUE TITLE
Include a copy of current page instead of diagram for security reasons

### ISSUE THREAD

**Issue by lotabout** [jgraph/drawio#2860]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Currently when we check the `Include a copy of my diagram` checkbox when exporting, the whole diagram will be embedded in the exported image. The diagram might include some pages that's under development or just privately created that's not suitable for public.

Different with https://github.com/jgraph/drawio/issues/2177, I DO like the page being exported so that others could edit the image, just not all pages.

**Describe the solution you'd like**
1. An option to export current selected page only on the export dialog.
2. And maybe a (desktop) application wide option to enable it by default globally.

Thanks!

**Comment by mararad** [comment]
Hi,

If I understood you well, there are multiple pages in a diagram. You use File > Export as > PNG + Include a copy of my diagram ticked

When you open e.g Page-1 and export it, all pages are exported as PNG, not only Page-1?

**Comment by lotabout** [comment]
@mararad correct. Here is an example exported image

![Untitled Diagram-Page-1 drawio](https://user-images.githubusercontent.com/1527040/172373542-41e2a3bd-2ad2-49d5-9678-a5b22ae1f82f.png)

**Comment by mawid6** [comment]
> Currently when we check the Include a copy of my diagram checkbox when exporting, the whole diagram will be embedded in the exported image. 

This is exactly the way I want it. Very useful to be able to have additional diagram details in additional sheets when opening it in the editor, and the first sheet is the png/svg rendered image. My use case is more "storage with rendered in image".

I guess your use case is more "export". I wonder if the cli can be used as a workaround.... (I have not checked)

**Comment by lotabout** [comment]
@mawid6 

> I guess your use case is more "export"

Yes. I need to export and send the image to someone else or post on Jira, etc.

> My use case is more "storage with rendered in image".

I understand this use case and respect it as default, but need an option for exporting current sheet/page only.
