### ISSUE TITLE
Open diagram where last worked on

### ISSUE THREAD

**Issue by rahav** [jgraph/drawio#2861]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When one opens a file with multiple tabs and drawio naively starts at the leftmost tab, the user risks editing the wrong tab.

This specifically occurs when the tabs are related to each other and contain different parts of the same algorithm, at different level of details, or different design alternatives.

**Describe the solution you'd like**
It would be very beneficial to have drawio open in the tab last edited and even better if it could open in the part of the diagram last edited or viewed.

Additional added value features that would make drawio more friendly are:
- Auto open or close the Left and right panes, depending how they were when that file was last edited.
- Remember the font and size last used, color, etc.
- Layers popup window was visible/not

**Describe alternatives you've considered**
Manually reverse order tabs so the leftmost is the one last edited. This somewhat protects against editing the incorrect tab for an hour but messes up the semantic order of tabs if the document is so organized.

**Additional context**
Thank you for considering.

**Comment by rahav** [comment]
> Not sure if that is the expected behavior in all situations.

Isn't it is safer to continue where stopped? If not in all cases, a file property then?

**Comment by mawid6** [comment]
> > Not sure if that is the expected behavior in all situations.
> 
> Isn't it is safer to continue where stopped? If not in all cases, a file property then?

I guess the tab that was open when you last saved it could be the one that is activated when you reopen. That could be saved in the diagram file. But, its a niche thing to me.
But the issue of "safety" is odd to me, it seems a bit niche use case.. Do your sheets look so similar that this happens?
The sheets in my diagram files are always quite different, this is not a use case for me, AFAICS. :-) 

I just wanted to highlight that I would love for the panel visibility to be remembered. Or atleast that I can set them to hidden by default, across sessions (in the config)... Maybe that is even possible, I must doublecheck...

**Comment by rahav** [comment]
You are correct this depends on the use and if there a better way to use the app, please share. Yes, many of my tabs are similar to each. I'm designing algorithms and I start a major revision with a DUP of the previous tab.

**Comment by rahav** [comment]
After thinking about it more I'm still of the opinion that drawio would be more user-centric if it would start in the tab + location (when the diagram have multiple pages) that was edit/viewed last. That is, even if the tabs are different from each other.

Thanks for consideration.

**Comment by jerry-bonner** [comment]
Can this request be reopened? Being able to open a diagram view in a specific location would be very helpful. With very large diagrams, the default view location and zoom level is problematic.
