### ISSUE TITLE
Notepad Function

### ISSUE THREAD

**Issue by ironlion37** [jgraph/drawio#2862]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
My problem is that I want to be able to attach a volume of information to a particle topic in the chart - without cluttering up the chart.

**Describe the solution you'd like**
I would like topics to have a corresponding side panel for notes. This expands drawio's functionality for mind mapping.

**Describe alternatives you've considered**
I don't know of any alternatives. 

**Additional context**
Here is how this works in Mindjet's Mind Manager software. Note the notepad icon added to the topic indicating it has notes attached. The side panel can be shown/hidden.
![Screen Shot 2022-06-06 at 9 46 48 AM](https://user-images.githubusercontent.com/106928525/172196721-e330cc7c-6592-4425-b338-d6506481c248.png)

**Comment by mararad** [comment]
Hi,

There is a possibility to add a tooltip on shape hover https://www.diagrams.net/doc/faq/tooltips
Also, there is the open feature request you can comment and follow: https://github.com/jgraph/drawio/issues/711

Regards,
