### ISSUE TITLE
PlantUML doesn't draw association between class and enum when a note is present

### ISSUE THREAD

**Issue by AlexTalker** [jgraph/drawio#2866]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

I met a peculiar behavior while utilizing your wonderful functionality or rendering `PlantUML` diagrams.

For some reason, when I try to create an association between a class field and `enum` related to it,
if said `enum` has a note attached to it's member, the association isn't there.

**To Reproduce**
1. Go to https://app.diagrams.net/
2. Click on `Arrange => Insert => Advanced => PlantUML`
3. Insert the following `PlantUML` diagram:
```plantuml
@startuml

enum Foo {
    Bar
}

note left of Foo::Bar
    Buggy note
end note

class Buzz {
    foo: Foo
}

Buzz::foo --> Foo

@enduml
```
5. See the error

**Expected behavior**

As displayed by plantuml.com, the association needs to be visibly rendered.

**Screenshots**

`draw.io` result:
![image](https://user-images.githubusercontent.com/3531127/172430489-fe62fceb-aae5-4beb-b30a-ab07216b8582.png)

`plantuml.com` result:
![image](https://user-images.githubusercontent.com/3531127/172430649-43006216-6768-437d-af64-946351dd3757.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- 19.0.0

**Desktop (please complete the following information):**
 - OS: `Manjaro Linux`
 - Browser `Brave`
 - Version 1.39.111 Chromium: 102.0.5005.61 (Official Build) (64-bit)](https://brave.com/latest/)

**Additional context**

I suspect some dependency update are due on your server side, since I have at the moment no means to confirm how standalone installation behaves but considering that official implementation does work okay that seems to be precisely the case.

**Comment by AlexTalker** [comment]
@mawid6 Thanks for the quick response.

In fact, when I continued to messing up with my diagram afterwards, I made some syntax errors and when the error message is rendered, it states that your PlantUML version is X days outdated(about 50 or so) which looks funny.

Also, I think my example diagram is only part of the problem since IIRC I hit the issue when I had any note whatsoever attached to a class or the `enum` but if one declares note as a separate entity and links it up later via `className -- noteName` or `enumName -- noteName`, it somehow ends well, so I stick to this hack at the moment.

Although I obviously wish it didn't happened in the first place =)

Might it be an issue with `GraphViz`? According to your screenshots, they are different too...
And I think this is how `PlantUML` gets the final picture rendered.

**Comment by mawid6** [comment]
Yeah, might be graphviz. Lets see if someone from diagrams.net get some time to look at it... :-)

**Comment by AlexTalker** [comment]
This seems to be the result of regression, according to https://github.com/plantuml/plantuml/issues/983
But still, it's odd that official PlantUML server uses GraphViz from 2014, I wanted to debug the issue by downgrading GraphViz earlier before I went to PlantUML's bug-tracker, and for distros like Arch it's such a pain to find such an ancient version for the dependency.
Also, I've checked on PlantUML release in-between:
```shell
# plantuml -version
PlantUML version 1.2022.4 (Sat Apr 09 13:29:17 GMT 2022)
(GPL source distribution)
Java Runtime: OpenJDK Runtime Environment
JVM: OpenJDK 64-Bit Server VM
Default Encoding: UTF-8
Language: en
Country: US

PLANTUML_LIMIT_SIZE: 4096

Dot version: dot - graphviz version 4.0.0 (0)
Warning : cannot determine dot version
```

The issue seems to be fixed for the following diagram:
```plantuml
@startuml BrokenSVG

class User {
  email: String
  username: String
  password: String
}

note right of User::username {
  This breaks connections
}

class Role {
  email: String
  name: String
}

User -- Role
Role -- Role

@enduml
```

PNG:
![BrokenSVG](https://user-images.githubusercontent.com/3531127/176999458-00c2dffe-1086-4435-8bb7-eee841109e5a.png)


SVG:
![BrokenSVG](https://user-images.githubusercontent.com/3531127/176999464-a0f25ec4-c653-4cc6-bcc0-f1098e3013f6.svg)
