### ISSUE TITLE
Magnifying glass

### ISSUE THREAD

**Issue by rahav** [jgraph/drawio#2868]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
The use case is viewing of very large diagrams. Large diagrams often require an overall view that forces for example zooming to 25% or smaller, but then the diagram is unreadable. Being able to magnify parts of the diagram in that birds eye view would be tremendously valuable.

**Describe the solution you'd like**
Have a magnifying glass feature that when activated the cursor changes to a magnifying glass, which enlarges a a portion of the diagram. The user can move the cursor/glass and clearly see parts of the document.

The size of the magnifying glass should also be user definable.

Is that feature possible?

**Comment by mararad** [comment]
Hi,
You might want to check View > Outline
You can expand it and have a overall view of a diagram without zooming to 25% or less.
Not exactly the thing you asked for but could be helpful meanwhile.

**Comment by rahav** [comment]
@mararad I can't stress enough how valuable your workaround is. THANK YOU!!!

**Comment by rahav** [comment]
@mararad Can you consider a related feature? Have the outline (and similar overlay windows) be able to pop out of the main editor. This way they can leave on the their own and be put on another monitor and not cover what's below them.
