### ISSUE TITLE
Teams app SharePoint list only loads 200 sites. 

### ISSUE THREAD

**Issue by Tom-Enns** [jgraph/drawio#2869]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
We have a teams environment with around 350 teams sites. We are trying to add the Draw.io teams app to all of these sites and the file the app points to on each site lives within that site. This worked well for exactly 200 of our teams. 150 of our teams do not appear in the list when selecting a SharePoint site to grab a file from. 

**To Reproduce**
- Open a teams environment with more than 200 teams sites. 
- Add the Draw.io tab to a team
- In the app settings select  the sharepoint option next to "Open Diagram" 
- Ensure that "Sharepoint" is selected in the left hand list
- Scroll through/count the teams in the right hand list.

**Expected behavior**
We expect that ALL of the SharePoint sites (teams) that the user has access to will appear. However only 200 appear in the list. 

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 19.0.0]

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 and Windows 11
 - Browser [e.g. chrome, safari] Edge and within the MS Teams App
Teams - 1.5.00.12969 (64-bit).
Edge - Version 102.0.1245.33 (Official build) (64-bit)

**Additional context**
Things we have tried:
- ensure the user adding the tab/performing the search is an owner on all teams
- ensure the user adding the tab/performing the search is a sharepoint and teams admin 
- ensure that the teams that are missing and teams that are not missing have Identical setups (both public, same channels, same tabs etc)
- Refresh the list with different users.  (note that when we do this the order of the list changes, but the contents don't)

**Comment by ashrafteleb** [comment]
Thanks for the report. This will be fixed in the next release
