### ISSUE TITLE
Export PDF in Dark theme  

### ISSUE THREAD

**Issue by hecto600** [jgraph/drawio#2871]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Exporting as pdf or advanced with dark theme applied return a file as default theme. If your export as normal png the results are as expected.

**To Reproduce**
With draw.io dark theme applied
1. Go to 'File > Export as > PDF'

**Expected behavior**
The alternatives of "export as" should apply the colors of the draw.io dark theme.

**Screenshots**
Web editor version:
![chrome_SrpH3NX9Wy](https://user-images.githubusercontent.com/10828837/172960810-43291c00-f56a-4b01-b19c-d1ef11cd1763.png)

Downloaded PDF version: (Sometimes the text maintain the white color like the leftmost square apparently empty )
![brave_OeD8RRcNzg](https://user-images.githubusercontent.com/10828837/172961001-56b356d0-8052-4c96-8256-2d046339cf5a.png)

(Png export) Expected export with dark theme option:
![image](https://user-images.githubusercontent.com/10828837/172961459-e15f0941-7910-4574-b6e6-b352a9e64745.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version [15.8.4]

**Desktop (please complete the following information):**
 - OS: First used [Linux Mint 20.3] and after I tried [Windows 10] 
 - [Mint was with desktop app latest flatpak version]
 - Browser [Windows I used Brave]
 - Version [Version 1.39.120 Chromium: 102.0.5005.99 (Official Build) (64-bit)]

**Comment by alderg** [comment]
Currently, PDF export does not support dark mode.

**Comment by hecto600** [comment]
Ty for response.
Should I re-ask as feature request now? 
and what about 'export as > advance > png'? (It returns default theme too)
![image](https://user-images.githubusercontent.com/10828837/173088377-8fe7690a-addf-437d-8ba7-0223a011a4ec.png)

**Comment by ittayd** [comment]
I would also like if the 'embed -> SVG' option would support dark mode

**Comment by ShahriarKh** [comment]
Any updates? This feature is really handy.
