### ISSUE TITLE
math font bold when diagram exported to pdf

### ISSUE THREAD

**Issue by swordfishwjy** [jgraph/drawio#2873]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I exported the diagram to pdf, the font of math symbols such as $$T_{1}$$ was bold automatically in the pdf. However, I did not set it as bold in the diagram.

**To Reproduce**
1. Enable mathematical typesetting in a diagram
2. type some latex equation
3. exported to a pdf
4. See equation font bold.

**Screenshots**
![image](https://user-images.githubusercontent.com/9381056/173202951-0c1a6dc1-dbbf-49b6-8f34-a3576e1a040b.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- I use the web-based in Chrome

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by rvinas** [comment]
I am having the same issue. Is there any workaround for the current release?

**Comment by alderg** [comment]
Fixed in 20.0.1. Go to https://app.diagrams.net/clear.html (with no other open tabs) to update.

**Comment by rvinas** [comment]
> 

I confirm that this works. Thank you very much!

**Comment by swordfishwjy** [comment]
Thanks for your quick response! It works now.
