### ISSUE TITLE
\boldsymbol not working in Mathematical Typesetting

### ISSUE THREAD

**Issue by jivatneet** [jgraph/drawio#2876]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
In Mathematica Typesetting latex formulas, \boldsymbol used to produce boldsymbols when I last worked on my drawing. When I opened the same previous drawing to edit, the latex formulas work but the \boldsymbol does not seem to work. 

![image](https://user-images.githubusercontent.com/39404029/173310519-5b94af76-ed4a-4374-83f4-3e56daf9a0ab.png)

**To Reproduce**
1. Enable Mathematical Typesetting
2. Enter formula `$$\boldsymbol{A}$$`

**Expected behavior**
I expected bold mathematical symbol like following:
$$\boldsymbol{A}$$

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 19.0.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser edge

**Comment by julianmueller** [comment]
Still not working for me in current version (21.1.2).
