### ISSUE TITLE
Mathematical typesetting in embed mode does not work

### ISSUE THREAD

**Issue by hubert5577** [jgraph/drawio#2879]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When using 'Mathematical Typesetting' in embed mode the 'Save & Exit' and 'Exit' buttons are not working.

**To Reproduce**
1. Go to 'https://jgraph.github.io/drawio-integration/helloworld.html'
2. Click on 'Start' / the image
3. After the image is loaded click on 'Format'
4. Enable the checkbox 'Mathematical Typesetting'
5. Click on 'Save & Exit'.
6. However, the content is not saved and the editor cannot be closed.
7. In the console of the developer tools there is the error message: Uncaught TypeError: Cannot read properties of undefined (reading 'Push')

**Expected behavior**
The content should be saved and then the editor should close.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.0.1, online

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 102.0.5005.115

**Comment by davidjgraph** [comment]
This isn't a production site, this is just the github pages deploy of the repo. This won't work stand-alone.

**Comment by hubert5577** [comment]
However, mathematical typesetting does not work in embed mode in general!!! The page 'https://jgraph.github.io/drawio-integration/helloworld.html' is just one example to reproduce the issue.

Furthermore, mathematical typesetting has worked in embed mode in previous versions. However, in the latest version embed mode only works when disabling mathematical typesetting.

**Comment by alderg** [comment]
What's the version in the Help menu? (Try https://embed.diagrams.net/clear.html to update.)
