### ISSUE TITLE
bug when preview and publish image

### ISSUE THREAD

**Issue by dhanyn10** [jgraph/drawio#288]
i used draw.io to make a diagram, when i've preview my diagram in small zoom, i found that the arrow is wrong but it's just fine when i preview it in previous zoom.
here i include screenshot so you can more understand:
first zoom, look smaller, the arrows become wrong
![drawio 1](https://user-images.githubusercontent.com/11478316/43060087-8ca28b12-8e79-11e8-944d-137fb2fc3f1d.png)
result from first image
![activity diagram-hapus objek wisata](https://user-images.githubusercontent.com/11478316/43060131-c52a8f66-8e79-11e8-983c-28541caee8d5.png)
second zoom, look bigger, everything become fine.
![drawio 2](https://user-images.githubusercontent.com/11478316/43060156-e78283b6-8e79-11e8-97ac-3468d0de3e27.png)
result from secound image
![activity diagram-hapus objek wisata 1](https://user-images.githubusercontent.com/11478316/43060171-f8536598-8e79-11e8-87b0-3877dcb04857.png)

**Comment by dhanyn10** [comment]
hello, how about this bug?

**Comment by Zappelphilipp** [comment]
get this exact same bug all the time. Arrows are looking fine and twisted depending on zoom levels. also preview can look fine in most zoom levels but image export is broken.

**Comment by davidjgraph** [comment]
Please vote the issue up, "me too" just creates noise that helps nobody.

**Comment by GregMillsFreesat** [comment]
I'm spotting this too. Has anyone found a workaround to this?

**Comment by GregMillsFreesat** [comment]
From further trial-and-error investigation, it seems to occur if the boxes that the line is joining are almost- **but-not-quite** in alignment.

**Comment by davidjgraph** [comment]
This should be fixed in 11.2.4, if you update.
