### ISSUE TITLE
[embed.diagrams.net / app.diagrams.net] Different behaviour in PDF export

### ISSUE THREAD

**Issue by Commifreak** [jgraph/drawio#2880]
Hi,

We use embed.diagrams.net via DrawIO Nextcloud integration. A person works with app.diagrams.net and our Nextcloud in parallel and noticed changes in the PDF export dialog.

* Is the changed PDF dialog wanted? If I check both versions, I would say, some options are missing?

`app.diagrams.net` (v20):
![app diagrams net](https://user-images.githubusercontent.com/87267/173778334-93571b82-ccda-46b0-8dae-732758d3ff22.JPG)

`embed.diagrams.net` (v20)
![embed diagrams net](https://user-images.githubusercontent.com/87267/173778479-1965a06d-e261-4fce-b852-4b1fd1111715.JPG)

**Comment by davidjgraph** [comment]
This is expected. We use a server for PDF generation, nextcloud would use the local print to PDF functionality client-side.
