### ISSUE TITLE
Saving data to public Gitlab service : invalid redirect URL

### ISSUE THREAD

**Issue by imakiro** [jgraph/drawio#2882]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

-> this issue might be related to https://github.com/jgraph/drawio/issues/1992 , but it's different as it concerns the interaction between the public draw.io service with the public Gitlab.com service.
No self hosting involved.

**Describe the bug**
It's impossible to save draw.io project data to gitlab.com.

**To Reproduce**
1. Go to ['draw.io'](https://app.diagrams.net/)
2. Click on 'Gitlab'
3. Click on create new diagram
4. Select diagram
5. Click on "Authorize" with the Gitlab logo
6. See error
![image](https://user-images.githubusercontent.com/2473976/173827261-8c286d12-17cb-4689-91a9-5fd06373dcc3.png)

**Expected behavior**
Either a modus operandi to pre-approve the connection on Gitlab's side or a functional dialog between the apps.

**Screenshots**
CF. problem description.

**draw.io version (In the Help->About menu of the draw.io editor):**

- public draw.io version 20.0.1

**Desktop (please complete the following information):**
 - OS: Linux PopOS 22.04
 - Browser : Firefox 101.0

**Comment by unmeless** [comment]
I have the same issue, and I find that "redirect_uri=https%3A%2F%2F[MY_DRAW_IO_ADDRESS]%2Fgitlab" is not end with ".html"
