### ISSUE TITLE
Latex matrix not rendering

### ISSUE THREAD

**Issue by aghriss** [jgraph/drawio#2885]
**Describe the bug**
Math typesetting does not render matrix blocks.

**To Reproduce**
1. Go to https://drive.google.com/file/d/1Lrd_Hck0OI7JEz-e9wU2aCT6p4dXIv5S/view?usp=sharing

**Expected behavior**
The pmatrix block to render

**Screenshots**
![image](https://user-images.githubusercontent.com/32200675/173919175-0a82c946-70b3-410f-9746-a40174e56fdd.png)

**draw.io version :**

- draw.io version : https://app.diagrams.net/ , 19.0.1

**Desktop (please complete the following information):**
 - OS: macOS
 - Firefox
 - Version 91.10.0esr 64-bit

**Comment by alderg** [comment]
Double click and click "Tx" (Clear Formatting) in the text style panel to remove the HTML tags:
![Screenshot 2022-06-21 at 11 13 56](https://user-images.githubusercontent.com/921200/174764337-e5279799-cb89-43ac-9652-28691ce3a22f.png)
