### ISSUE TITLE
Cannot make image filling or change the shape of image.

### ISSUE THREAD

**Issue by nico-zck** [jgraph/drawio#2888]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
 I cannot fill a parallelogram with an image or cannot resize an image shape become other shapes except for rectangle.

The expected visual effect should look like this: 
<img width="456" alt="image" src="https://user-images.githubusercontent.com/10665923/174220113-6874fc0f-f393-420b-8272-aa0475d25732.png">

**Describe the solution you'd like**
Make some shape support image filling is good.

**Describe alternatives you've considered**
I use the omnigraffle  to obtain this picture.
And I also found that Visio not support image filling but it could make the expected result by editing 3-dimensional angle of the image shape.

**Comment by davidjgraph** [comment]
Declined.
