### ISSUE TITLE
Insert (or create) From Template URL always opens a new tab/diagram in FF, fails in the desktop app

### ISSUE THREAD

**Issue by jaylapras** [jgraph/drawio#2891]
* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug/reproduce**
1. When creating a new diagram, or inserting a template (Arrange > Insert > Template), click on From Template URL.
2. Add the URL and click Create. 
The diagram is always opened in a new browser tab (Firefox), and prompts for a new filename to save the file. 

![insert-from-template-url](https://user-images.githubusercontent.com/60265913/174291433-adb0caef-b31e-48af-922c-e01b06be9e26.gif)

Following the same steps with the diagrams.net desktop app fails silently.

![insert-from-template-url-diagrams-desktop](https://user-images.githubusercontent.com/60265913/174291571-51e8d60e-cd64-4f72-9c4b-b7560ffae7b4.gif)

Also, this feature is not available in draw.io for Confluence Cloud

**Expected behavior**
This *should* simply insert the diagram from that URL in the opened tab/diagram, where *From Template URL* was clicked, like it would when inserting a template from the template library dialog.

diagrams.net version 20.0.1
Firefox version 101.0.1
diagrams.net desktop version 19.0.3
macOS 12.0.1

**Comment by chipbite** [comment]
I am just curious; reading this, it seems like a fairly minor nuisance, only. Do you agree? 
Or is this causing you frequent frustration and costing you time or incurring cognitive load?

Could you describe the situation/scenario, so that it is possible to get a feel for how it impacts your work?

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
