### ISSUE TITLE
Allow to change a Theme without requiring a restart

### ISSUE THREAD

**Issue by epomatti** [jgraph/drawio#2893]
- [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**

When I select to change a theme, it is only applied after a restart.
It would be nice to have the theme applied immediately.
In my case, I work with several projects and they use different styles.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by davidjgraph** [comment]
The modern and simple themes are the two long themes we want to support. It is possible to switch between those and light/dark without a refresh. So, the ticket is partially done, but it won't be improved beyond that. Thanks for the submission.
