### ISSUE TITLE
Notion link preview

### ISSUE THREAD

**Issue by stasmihailov** [jgraph/drawio#2894]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
No, it's not related to a problem

**Describe the solution you'd like**
Notion, which is a popular note-taking and project management app, has just introduced a new API for creating cool link previews: https://www.notion.so/releases. Here is the quote:

> **Build your own link previews with Notion’s new API**
> 
> If you’re a developer who wants to see links to your software come to life in Notion, this one’s for you. Build on Notion’s new API to enable dynamic link previews anytime your customers paste a URL to your service in a Notion doc.

They've already had previews for popular links for a while - for example, if you insert a link to a Figma project into a Notion Page, it renders like this - a full, resizable preview of the frame: _(for context, I've attached a full Notion Page at the end, so that you could see how it looks for yourself)_

<img width="798" alt="figma_now_smol" src="https://user-images.githubusercontent.com/13658407/174838418-0b1f2238-4229-43d3-9d10-b3c387ceaaed.png">

And here is what a rendered diagrams.net link looks like rn:

![diagrams_now](https://user-images.githubusercontent.com/13658407/174837491-1b1924b9-2657-4b2f-a74b-84efa01c6075.jpg)

The link preview is not very informative. Would be cool if there was a preview like the one for Figma - doesn't have to be interactive, just show the name of the diagram and its thumbnail. For example, this is what the link preview for diagrams.net could look like: (made it in MS Paint in 2 minutes)

<img width="819" alt="diagrams_proposal" src="https://user-images.githubusercontent.com/13658407/174842322-5cf5e25e-4963-4670-94c8-5b59a3b7232d.png">

This request is not related to the diagramming part of the software, so I could personally assist you in its development if this proposal goes through

**Describe alternatives you've considered**
Use the non-informative link as shown above

**Additional context**
Here is a full Notion Page with the rendered links for figma and diagrams.net as shown above: https://babochenko.notion.site/Notion-Link-Preview-4c48f405c79b4721972beff1900da984

And here is a screenshot of that page, if you don't feel like clicking the link above:

![page](https://user-images.githubusercontent.com/13658407/174838982-4b13df2c-a548-4fc7-88ad-e75e1ef304cf.jpg)

**Comment by stasmihailov** [comment]
What do you think fam? Is it worth it? Or am I the only one who even cares about this?

**Comment by ctwhome** [comment]
Please add this functionality!

**Comment by stasmihailov** [comment]
@ctwhome unfortunately, this feature might not be possible, because:

- to release it, you must own the domain app.diagrams.net, which they might not agree on, judging by that they didn't respond to this, and
- an app must support oauth for data access, which is tricky because diagrams are not self-hosted, but are rather stored in cloud providers like google drive. There is no way to coordinate that between diagrams.net and google

Which is sad because technically this feature would take just a couple hours to produce

**Comment by davidjgraph** [comment]
Tell you what, you do it in a couple of hours and send the PR over. What's your ETA?

**Comment by stasmihailov** [comment]
Sorry for a late reply. I wouldn't want to immediately jump right into development, because, right now, this feature is not of the highest importance for me. That being said, I wouldn't be able to complete it alone, because embedding an iframe  (which is already available in confluence) into a notion page would require changes in server code, which I have no access to, but then I couldn't imagine a scenario where adapting an existing iframe for notion would take more than a week, including testing. And then still, the bottleneck would be the access given by notion to their link preview api, which takes up to 2 weeks to grant per their landing page (I didn't talk to them directly)

**Comment by AAS97** [comment]
Would love that feature !
