### ISSUE TITLE
Safarai on iOS needs .xml and doesn't open .drawio

### ISSUE THREAD

**Issue by hevisko** [jgraph/drawio#2895]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
On iOS (iPadAir) I can't open via Safari a .drawio in a nextcloud shared folder. Saving files, it saves it as a filename.drawio.XML ;(

 
**To Reproduce**

1. connect  NExtCloud to iPad
2. create/save a .drawio using the NExtCloud web interface on a Mac/PC using MS-Edge
3. goto app.diagrams.net
4. open a document
5. go to the NExtCloud folder with the .drawio created in 2
6. -> it's grayed out for me, can't select it
7. cancel, close tab, open new tab
8. goto app.diagrams.net
9. select "Create file", select template
10. save file to the same directory on NExtCloud as above in 2 & 5
11. file is saved as a .xml 
12. 

**Expected behavior**
Safari on iPad to be able to open .drawio, not just .xml

**Screenshots**
![IMG_C57EC9BA75A1-1](https://user-images.githubusercontent.com/151835/175007846-4169defd-329d-4064-98bb-fc83d9a0c525.jpeg)
<img width="1180" alt="2022-06-22 12-27-15-0" src="https://user-images.githubusercontent.com/151835/175007877-15e18e58-7d2c-44e1-8654-828c1c12eae4.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- 20.0.2

**Smartphone (please complete the following information):**
 - Device: iPad Air 4th Gen
 - OS: [iOS 15.5
 - Browser: Stock Safari
 - 15.5

**Additional context**

**Comment by davidjgraph** [comment]
Why not use the nextcloud app?

**Comment by hevisko** [comment]
Screen real-estate?

But mostly that I only found now how to do it :)

That said, the main problem w.r.t. drawio vs .xml still exist when not saving on a nextcloud storage, doesn’t it?

**Comment by davidjgraph** [comment]
I'm not really clear what the exact issue is here. Please feel free to file a new ticket that explains the exact issue without using nextcloud.
