### ISSUE TITLE
Curved text 

### ISSUE THREAD

**Issue by JerryWestrick** [jgraph/drawio#2897]
This request is for a "Curved Text" feature. 

This request might be easier to implement than "Curved Text in custom complex shapes #2651" which was denied.  I assume as it would require lots of additional GUI work to support.

In this request Curved Text would be implemented by selecting a curved line and a Text object, then selecting "Place Text On Line" from the context menu.  This is the way it is done in "Ink Scape":

![image](https://user-images.githubusercontent.com/2119111/175140872-2b67c0d0-6200-445d-9928-589a77a5210d.png)

**Comment by qhungngo** [comment]
It is necessary in some cases.
