### ISSUE TITLE
Feature request: Allow boolean operations to mutate shapes

### ISSUE THREAD

**Issue by dannystaple** [jgraph/drawio#2898]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

I find Draw.io intuitive, I like much of its tools. and the sketchy style operations make a very particular feel for a diagram. However, it is frustrating when I want a shape that is not in its library. While I can make and import them from another app, this puts those items outside the style changes that DrawIO can apply.

**Describe the solution you'd like**

A set of boolean set style shape operations. Select two shapes, these can be combined, joined, subtracted, or find the intersection. Use the Z-order such that the front shape is subtracted from the rear shape for the subtraction operation.

- Combining - make a single hull - intersection parts become a single part.
- Join - maybe multiple hulls, but considered a single shape with multiple hulls.
- Subtracting - Take the intersecting parts of a front shape from the parts of a rear one. Result is what remains of the rear shape. 
- Intersecting - Keep only the overlapping parts of two shapes. Discard the rest.

**Describe alternatives you've considered**
using a different package to make images and dragging them in. This takes it outside the drawio workflow, means there are additional files to manage, and only a subset of the drawio styling options can be applied.

**Comment by davidjgraph** [comment]
We'll accept a PR for this one. Note the code must be security reviewed prior to being accepted.

**Comment by iamalonso** [comment]
Hello everyone, it would be fantastic to have the feature related to boolean operations mentioned above. Could we please add it to the backlog?

**Comment by jeeftor** [comment]
Can we vibe code it?

**Comment by davidjgraph** [comment]
We don't allow external contributions. You're welcome to vibe code it and use that as a local version.
