### ISSUE TITLE
Mathematical typesetting broken for electrical switches

### ISSUE THREAD

**Issue by bkasel** [jgraph/drawio#2899]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I try to add a label to some of the electrical switches using mathematical typesetting, the text is not rendered or is not visible
**To Reproduce**
1. Go to Electrical/ Switches and Relays
2. Add a ´Single Switch off´ ( Problm persists with some of the other Switches too)
3. Click on the newly added switch
4. type ´$$K_1$$´

**Expected behavior**
A rendered version of the formula should appear on the diagramm (as it happens for most electrical components I have tried)

**Screenshots**
before enabling mathematical typesetting
![grafik](https://user-images.githubusercontent.com/16179803/175877285-c75de946-94c4-4fe5-b1b8-aa11f9c46241.png)

after enabling mathematical typesetting

![grafik](https://user-images.githubusercontent.com/16179803/175877326-e67912a8-c919-45e9-a976-27ec9fcffb9f.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [20.0.3]

**Desktop (please complete the following information):**
 - Windows 10 (installed version and browser)
 - Firefox 101, Chrome 103
 - 20.0.03

**Comment by mararad** [comment]
Reproduced with Single Switch off in FF and Chrome Version 102.0.5005.115 (Official Build) (64-bit)
diagrams.net  20.0.3

https://user-images.githubusercontent.com/44292306/175921004-7eb0e127-c84d-464c-bb7a-93960025eb42.mp4

**Comment by alderg** [comment]
Check formatted text in the text style section:

![Screenshot 2022-06-28 at 11 53 51](https://user-images.githubusercontent.com/921200/176150542-988b923e-7ab9-4587-925a-7b34c9cfc903.png)
