### ISSUE TITLE
Enumerate feature invisible in png export

### ISSUE THREAD

**Issue by JavidPack** [jgraph/drawio#2900]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Using the enumerate feature to number shapes, I would expect the numbers in the exported png. They are missing.

**To Reproduce**
1. New diagram
2. Add a rectangle
3. Expand properties and check "Enumerate"
4. Take note of the "1" in a yellow box that appears on the rectangle, this is the Enumerate feature.
5. Export png with default options. Resulting image file does not have the 1 or the yellow box.

**Expected behavior**
I expect the png to have the enumerate feature. Testing .pdf, it properly is represented

**Screenshots**
In the editor:
![image](https://user-images.githubusercontent.com/4522492/176123435-49bdb144-83cf-4d86-85aa-1b68539671b4.png)

Resulting image:
![asd drawio (1)](https://user-images.githubusercontent.com/4522492/176123522-48f63352-b74a-4142-a39b-16cac059ee9e.png)

**draw.io version 20.0.3

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by davidjgraph** [comment]
https://github.com/jgraph/drawio-dev/commit/1cb30091ebfadd7cb959d383fa7c48e2e3320a95
