### ISSUE TITLE
Differ between visual and logical direction of edges

### ISSUE THREAD

**Issue by BonaBeavis** [jgraph/drawio#2901]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When creating subclass hierarchies, the arrow point to the super class, this makes it difficult to use the automatic layouts. The super class should be used as the root node, but drawio thinks it is a leave, because the arrow point to it.

**Describe the solution you'd like**
Make a property to edges, which inverses visual direction for layouts and collapsing tree segments.

**Describe alternatives you've considered**
A workaround is to select all edges and switch the direction before automatic layout and reverse this afterwards. But this is not a workaround for tree folding, if exported.

**Comment by davidjgraph** [comment]
You can put the arrow on either end of the connector, regardless of the real direction of the edge.

**Comment by BonaBeavis** [comment]
Doh! Thanks.
