### ISSUE TITLE
default mousewheel behavior

### ISSUE THREAD

**Issue by hiaselhans** [jgraph/drawio#2904]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

When i am navigating around a drawing i like to do so by zooming out and back in. The default for the scroll wheel is to scroll in y-direction. I feel like it would be more effective to zoom instead, because most of the time drawing are not only higher, but also wider than the screen

**Describe the solution you'd like**

I'd like the default behavior to be zoom on mouse wheel and scroll with ctrl pressed.

**Describe alternatives you've considered**

This behavior could also be hidden behind a config variable

**Comment by alderg** [comment]
zoomWheel: false

should work

**Comment by hiaselhans** [comment]
hi @alderg ,
thanks for the fast response. I tried with this configuration, but nothing changed:
```
{
  "zoomWheel": false
}
```

**Comment by hiaselhans** [comment]
ok well, got it.

```
{
  "zoomWheel": true
}
```

Thanks!
