### ISSUE TITLE
Not able to find AWS Fargate shape which is the most used one among AWS services

### ISSUE THREAD

**Issue by surajaddanki** [jgraph/drawio#2905]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by davidjgraph** [comment]
We follow the official AWS icon set, if that doesn't contain the icon then AWS is the place to file an issue.
