### ISSUE TITLE
Fail to export pdf with Source Code Pro font

### ISSUE THREAD

**Issue by yzh119** [jgraph/drawio#2906]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I tried to export a pdf file and I used `Source Code Pro` font from google in part of my diagram.
However, the exported pdf does not correctly render the part with `Source Code Pro` font.

**To Reproduce**
1. Here is a demo: https://app.diagrams.net/#G1WKe8rH_5GOzyPKvT3GZ-Lm_rE-iGVTdL
1. Go to 'File/Export As/PDF'
2. Click on 'Export'
**Expected behavior**

**Screenshots**
What does it look like in drawio
<img width="583" alt="image" src="https://user-images.githubusercontent.com/11773619/176595941-ee8d9275-9aa7-47b9-b5c3-7a5077060736.png">

Exported PDF
<img width="565" alt="image" src="https://user-images.githubusercontent.com/11773619/176596032-234ab570-693f-4fe4-9030-74fd2b979e17.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.0.4

**Desktop (please complete the following information):**
 - OS: mac os 11.4
 - Browser Chrome
 - Version 102.0.5005.61

**Additional context**
Using other fonts or exporting to other formats (e.g. PNG) do not have this issue.

**Comment by mararad** [comment]
It's read-only. Could you allow editing also?

**Comment by yzh119** [comment]
@mararad done!

**Comment by yzh119** [comment]
Okay, it turns out I need to capitalize "source code pro" to "Source Code Pro" and it works now.
