### ISSUE TITLE
Can't access draw.io on any browsers on my Mac

### ISSUE THREAD

**Issue by GratefulGIS** [jgraph/drawio#2908]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Im not sure I would call this a bug. Rather, I just cant access draw.io at all. It just keeps loading. Out of 20 attempts, it has worked like twice. Not on the same browser. Firefox, Chrome, Tor, Safari is what I have tried.

**To Reproduce**
1. Go to '.draw.io website'
2. See loading page forever

**Expected behavior**
Entering the website.

**Desktop (please complete the following information):**
 - OS: [macOS Catalina]
 - Browser [ Firefox, Chrome, Tor, Safari]
 - Version [Chrome 103.0.5060.53, newest Tor]

**Smartphone (please complete the following information):**
I have the same problem on my smartphone. Firefox, chrome.

**Comment by GratefulGIS** [comment]
Actually, it loaded on the phone after a while.

**Comment by davidjgraph** [comment]
> Go to '.draw.io website'

Specifically which URL?

**Comment by GratefulGIS** [comment]
> > Go to '.draw.io website'
> 
> Specifically which URL?

www.draw.io
or
www.diagrams.net -- www.app.diagrams.net
neither works.
