### ISSUE TITLE
Paste without formatting option

### ISSUE THREAD

**Issue by JesseAldridge** [jgraph/drawio#291]
Sometimes I copy some html from a webpage and I want to paste it into a doc as plain-text. You can do this with Google Docs. It would be nice if draw.io supported this too.

**Comment by Vitamin-B** [comment]
Try `Ctrl + Shift + V` for unformatted paste

**Comment by JesseAldridge** [comment]
Doesn't seem to work on my macbook.
Fortunately I've switched this clipboard manager: https://pasteapp.me/
It includes a feature to strip formatting and paste plain text.

**Comment by Vitamin-B** [comment]
Yes, same here, just tried now on macbook and does not work (tried also some other combinations).
`Ctrl + Shift + V` does work on linux (ubuntu) and in Confluence.

**Comment by alderg** [comment]
Unfortunately, it's not possible to read the state of the modifier keys forpaste events in JavaScript.

**Comment by Vitamin-B** [comment]
I suppose you can still add a new shortcut for non-format pasting.

**Comment by alderg** [comment]
Unfortunately not, JavaScript cannot access the system clipboard.

**Comment by Vitamin-B** [comment]
Then maybe on systems where `Ctrl + Shift + V` is not supported for unformatted pasting (Mac, idk if also Windows) the `Command + Shift + V` could make the next paste (for a short time, e.g. 1 sec) unformatted (serves as a workaround for modifier key), as now it does nothing.

User would then need to use `Command + Shift + V` followed by `Command + V` which is still pretty convenient (you just release Shift between clicks).

Just as an idea. I don't really care that much as I don't use Mac if I don't need to.

**Comment by Matt-Hill-Harness** [comment]
Pasting text copied from VScode attaches a bunch of unwanted styles to it.
It would be nice if there were a setting that would make all pasted text use a default formatting.

**Comment by davidjgraph** [comment]
Maybe pop up a dialog asking whether to clean formatted output or leave as is

**Comment by alderg** [comment]
This is the default when pasting text into the diagram (when not editing labels). When pasting into labels, select the text and click the "Tx" icon in the text format panel. We tested a dialog to remove formatting after paste but we think the usability isn't great. See https://gyazo.com/e6c6f5154e1240b460d8f1329c8bdbab

**Comment by piwaneczko** [comment]
So maybe add some property to options instead of message box

**Comment by alderg** [comment]
Try right click, Paste here.

**Comment by szetakyu** [comment]
> Try right click, Paste here.

There is no this option when right click on a cell of a table.

**Comment by CrisLi** [comment]
Still finding a solution in MacOS

**Comment by CrisLi** [comment]
> Try right click, Paste here.

MacOS desktop version, right click on text input mode , no response. only cmd+v can paste text, but can not remove formatting

**Comment by CrisLi** [comment]
> This is the default when pasting text into the diagram (when not editing labels). When pasting into labels, select the text and click the "Tx" icon in the text format panel. We tested a dialog to remove formatting after paste but we think the usability isn't great. See https://gyazo.com/e6c6f5154e1240b460d8f1329c8bdbab

I watched this video lot of times. Still can not find "Tx" icon

**Comment by alderg** [comment]
For the Tx icon to be shown, you must be editing text. To start editing, double click or press enter with a cell selected.
To paste without formatting, insert a text box, untick "Formatted Text" in the text tab of the style panel and then paste.

**Comment by barry404** [comment]
Please add  `Ctrl + Shift + V` for mac desktop version.

**Comment by pm80** [comment]
For mac use **Shift+Alt+Command+Shift+V**

**Comment by Timmmm** [comment]
Cmd+Shift+Alt+V worked on Mac but this is not very discoverable. Honestly how many users *want* formatting by default? I can't think of a single time in my life when I've wanted to paste formatted text.

Maybe it should be off by default?

**Comment by alderg** [comment]
We're restricted by browser and their APIs. Currently, with formatted text in the clipboard in Chrome:

- when editing labels, Ctrl/Cmd+V pastes with formatting while Ctrl/Cmd+Shift+V pastes without formatting
- when not editing labels, Ctrl/Cmd+V pastes with formatting while Edit, Paste (or Right click, Paste here) pastes without formatting

**Comment by alderg** [comment]
We'll add support for Ctrl/Cmd+Shift+V for paste without formatting on the Mac in the next release.

**Comment by joquijada** [comment]
Only thing that has worked for me is right click on Mac and:
![image](https://github.com/user-attachments/assets/cc86c12a-671a-440c-a42a-6f57802a8e00)

**Comment by javadba** [comment]
Command-shift-V does NOTHING on macOS. Doesn't even paste anything.

**Comment by javadba** [comment]
Since this feature is broken inside draw.io, Here are workarounds for popular programs:

For pasting from Intellij:  I added shortcut to keyboard settings:   CMD-SHIFT-P  for "Copy as plain text"
For pasting from Vscode:  Added  to settings.json    "editor.copyWithSyntaxHighlighting":false

**Comment by kamyarghajar** [comment]
Cmd + Shift + V does not work on macOS. Desktop app version: v28.1.2
