### ISSUE TITLE
[Feature request] Ability to set properites via custom links and/or data type appropriate UI elements in "Edit data" dialog

### ISSUE THREAD

**Issue by theonlynexus** [jgraph/drawio#2910]
- [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.

* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
This is unrelated to any problem.

**Describe the solution you'd like**
It would be nice if they could be used to set an element's properties (data) too.
I understand that the UI for manipulating properties is separate on purpose, but some simple manipulation would be very useful: for example a way to increment/decrement numerical values at the click of a button, or to update a certain property to contain the current date.

Reason being: give the user a quick and easy way to change document version numbers, last update dates, etc.

**Describe alternatives you've considered**
* The only viable alternative, currently, is to click "Edit data" and replace the entire value, which is rather error prone.
* A possible alternative to shapes calling custom links which, in turn, change properties would be to allow data types for properties, and display appropriate controls  in the "Edit data" UI  (e.g. date picker or increment/decrement arrows).

**Additional context**
Screencap of the document properties
![image](https://user-images.githubusercontent.com/1515004/176818544-225172d6-f5c5-446e-b20d-b4b64fa252ed.png)

Screencap of the properties being used in text labels and refresh/increment buttons (desired feature)
![image](https://user-images.githubusercontent.com/1515004/176820603-8fbe3e9a-b15e-42cf-9c70-b4f1512f0e45.png)

Mockup of possible alternative
![image](https://user-images.githubusercontent.com/1515004/176820188-d6c52b91-bce9-497f-8243-9613a19a3266.png)

**Comment by james-mariotti** [comment]
Yes Please!

Since i've not found any issues or discussions on the topic, may I piggy back on this request to also include an "IMPORT" button that provides the user a dialog box that allows data fields to be pasted in and imported in the same format it can be exported?

Thank you!

<img width="243" alt="image" src="https://user-images.githubusercontent.com/100151390/222135246-b0db9461-444c-479f-b4f0-586403cf2cfb.png">

**Comment by akrpic77** [comment]
What about embed mode protocol that would allow host app to provide custom dialog?
