### ISSUE TITLE
[Feature request] File specific properties (not page specific, not editor config)

### ISSUE THREAD

**Issue by theonlynexus** [jgraph/drawio#2911]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Not related

**Describe the solution you'd like**
The ability to set properties per file (globally) instead of just per page, or per shape, would be much appreciated.

**Describe alternatives you've considered**
Right now I create a page, set the properties, and they get carried over to any copy. But, when the moment to change their values come, I have to go through them page-by-page. So an alternative might be the ability to easily clone properties from one page to a set of others.

**Comment by theonlynexus** [comment]
Thanks for the reply. It kind of helps, but not really. 

To clarify: this would require me to setup the editor in the same way for every user, which is really not the way to go about it.

What I would really like to have, are variables that are global to one particular file. Imagine setting a variable to indicate the author, or the title of the file: by using editor-global variables those would be replaced every time someone opens the file on a different computer, which is undesired.

I hope I am making sense.

**Comment by Guillaurent** [comment]
I upvote hhis feature.

Some of my files are 25 pages long and include the document version number and last modification date.

As a workaround, I export the file as an uncompressed XML file, open it with my favourite text editor (i.e Notepad++) and replace all occurence of the properties I want to change (i.e version="3.2" by version="3.3"), save and reimport the xml file.
Not the perfect solution but it definitely beats updating (Ctrl+M) every page by hand.

**Comment by ianfinlay-aus** [comment]
It would be great if under menu Extras\Configuration you could have one JSON section for globalVars and one json section for  localDocVars , and then all pages in a doc could reference these using %localDocVar_no1% etc

**Comment by davidjgraph** [comment]
In 29.5.5
