### ISSUE TITLE
Support javascript graph/charts template

### ISSUE THREAD

**Issue by cmdares** [jgraph/drawio#2916]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Support javascript graph/charts template

**Describe the solution you'd like**
Support javascript graph/charts template

**Describe alternatives you've considered**
Can you support embedding Apache echars code fragments, which can be rendered on the canvas after insertion
It also supports editing.
**Additional context**
add plugin echarts js template 
![image](https://user-images.githubusercontent.com/5292190/177008685-faad3cab-c592-4776-9186-98689fb6fad1.png)

template script
![image](https://user-images.githubusercontent.com/5292190/177008724-e73b039d-5df0-4a31-b66a-0f283c31facb.png)

render result
![image](https://user-images.githubusercontent.com/5292190/177008816-38227d7b-084b-4d89-863d-db4de17e75e8.png)

**Comment by davidjgraph** [comment]
You are posting a number of very low quality issues today. Stop it, or you'll be banned.
