### ISSUE TITLE
Need to edit/delete menu items

### ISSUE THREAD

**Issue by howardroark2018** [jgraph/drawio#292]
How do I edit the main menu, as in which file contains the code of the menu items like 'File', 'Help' etc? 
I would like to change certain menu item names and possibly delete a couple of menu items. what do I edit in which file to do the same. please help!

Thanks a lot in advance!

**Comment by howardroark2018** [comment]
Still haven’t found it :(

**Comment by raydeo** [comment]
@howardroark2018 ...did you find your answer Howard? ...I'm new here and looking for the same.

**Comment by GordonRudman** [comment]
@howardroark2018 It's probably a bit late now, but you can find what you're looking for in the Menu.js file.

**Comment by GordonRudman** [comment]
I have a similar request, but would like to be able to easily remove unnecessary menu items [and actions] preferably before they are created (but afterwards would be ok too), without having to edit the actual drawio/mxgraph Menus.js code. I would prefer to rather have a way to overwrite the menus in my Pre/Post config.js files (or something similar) instead. That way i can leave the main drawio code alone as much as possible, which will make upgrades much easier.

I've experimented with trying to do this via a plugin, and trying to null out the menu/action using ui.menus.menus.arrange = null, or similar, but then I just end up with null reference exceptions getting thrown elsewhere in the code. I then tried to use the NullObject pattern to work around that, but JS isn't my primary language so I'm struggling a bit there. Is there an easier way to do this that I'm missing?   It would be nice to have a remove() method on menus and actions.

**Comment by bubling999** [comment]
Thanks @GordonRudman ,I'm looking into the same also - I will let you know once I get there, I have just started ...do you know where to change the app name on a global level? ...package.json /name has no effect?

**Comment by bubling999** [comment]
this is drawio-desktop ...same as drawio but in an electron app wrapper.

@GordonRudman the electron app builds ok, I'm modding drawio-desktop-12.6.5/src/main/webapp/js/mxgraph/Menus.js 

**I ditched the old:** Menus.prototype.defaultMenuItems = ['file', 'edit', 'view', 'arrange', 'extras', 'help'];
**for the new:** Menus.prototype.defaultMenuItems = ['item1', 'item2', 'item3', 'item4', 'item5', 'item6'];

rebuild.

No change seen in the menu? 

Have you been successful changing the menus in Menus.js yourself?

**Comment by GordonRudman** [comment]
I'd suggest having a look in the language resource files (resources/ "dia.txt"), and watch the browser dev tools/debugger for errors on the console.

You need to have resources defined (eg. item1, item2, etc) in the dia.txt file(s) before you can create a menu using those names, that's because the code will try lookup a language (eg. fr/French) specific translation linked to that name to show on the UI. 

I hope that helps a little.
