### ISSUE TITLE
[IBM2 Request] Can dropin images not auto-increase shape size

### ISSUE THREAD

**Issue by jaywarfield** [jgraph/drawio#2921]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
In the IBM2 shapes implementation dropping in images auto-expands the shape size and should retain the original shape size before the image was dropped in.  Also happens with the Square shape under General so appears to be a general problem.

**To Reproduce**
1. Add an IBM2 collapsed shapes to the canvas.
2. Note that collapsed shapes are restricted to 48x48 and can't be increased or decreased in size by design.
3. Go to Edit Image and dropin an image.
4. The collapsed shape is auto-increased in size to 48x52.  
5. This can then be manually decreased to the correct size to 48x48 and the shape then stays at 48x48.  
6. The Expand property is on so I also tried turning off the Expand property but the shape still expands to 48x52 with Edit Image.
7. Similar scenario for IBM2 expanded shapes.
8. Similar scenario with the drawio Square shape under General which has an initial size of 80x80, add the image=; property and go to Edit Image to dropin an image, the square size is automatically changed to 80x87.

**Expected behavior**
The shape size after an image is dropped into the shape should remain the same shape size as before the image was dropped into the shape.

**Screenshots**
<img width="473" alt="AutoExpansionProblem" src="https://user-images.githubusercontent.com/2131006/177634761-5bc9d8fc-8314-403d-b886-2b8365888a45.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io 18.1.3+

**Desktop (please complete the following information):**
 - macOS Monterey: 
 - Chrome Browser 
 - Version 103.0.5060.53

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
Medium priority for IBM2 Shapes as this auto-expansion could confuse users and if left at 48x52 will take up unnecessary
space in diagrams.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
