### ISSUE TITLE
[IBM2 Request] Can color schemes be more distinguishable

### ISSUE THREAD

**Issue by jaywarfield** [jgraph/drawio#2924]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Accessibility problem as described below.

**Describe the solution you'd like**
Color schemes will be the preferred method for using the IBM color palette in IBM2 Shape diagrams since we use a minimal set of line colors within our color palette and only have three possible fills (white fill, transparent fill, and light fill that is from the same color family as the corresponding line color in our color palette).

The first page of our color schemes is shown in the attachment for Blue and Cyan -

Top row from left to right is:
Medium Blue Line with White Filll
Medium Blue Line with Light Fill
Medium Cyan Line with White Fill
Medium Cyan Line with Light Fill

Bottom row from left to right is:
Dark Blue Line with White Fill
Dark Blue Line with Light Fill
Dark Cyan Line with White Fill
Dark Cyan Line with Light Fill

Accessibility can be difficult with our color schemes with the smaller size of each scheme.

It would be useful to identify what's in the color schemes before selecting a scheme, for example:
1. If the borders in the color schemes can be customized to be wider but not too wide since the fill still needs to be distinguishable.
2. If the color scheme had tooltips that said what line color and fill color is used in each scheme.  A tooltip on the color schemes could pull together the Fill and Line from the tooltip we already have defined for each color.

**Describe alternatives you've considered**
Users can select each scheme and look at the Fill and Line below the schemes which are easier to distinguish but which also changes the shape. And we have tooltips defined for the Fill and Line below the schemes which also helps to identify the colors.  Just not as convenient as having the tooltips defined in the color schemes directly.

**Additional context**
<img width="234" alt="ColorSchemes" src="https://user-images.githubusercontent.com/2131006/177782711-efe15351-cae1-4b1d-ade9-6e579b6bdf5c.png">

**Comment by alderg** [comment]
The title can already be specified. We'll include an additional border where the border width and type can be specified, eg. "2px solid" or "3px dashed". The documentation has been updated.
