### ISSUE TITLE
cannot get github authorization

### ISSUE THREAD

**Issue by hengeb** [jgraph/drawio#2925]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

The GitHub authorization for draw.io is broken.

**To Reproduce**

1. Go to https://app.diagrams.net/
2. Click on Save diagrams to ... `GitHub`
3. Click on `Open existing diagram`
4. Click on `Autothorize`
5. See error (404)

**Expected behavior**
I should be able to use my github account to save and load my work.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.0.4

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium
 - Version: 102

**Comment by freemedom** [comment]
I also encountered, seems to reopen once is OK.
