### ISSUE TITLE
Accidental zooming when dragging selection box on macOS

### ISSUE THREAD

**Issue by JesseAldridge** [jgraph/drawio#293]
Very similar to an issue I opened previously: https://github.com/jgraph/drawio/issues/267

When using cmd + click + drag to select many items at once it's very easy to accidentally zoom in and out. I do this multiple times a day and it's pretty annoying. Again it's because the magic mouse is a little too magical. I'm going to switch to a mouse with a normal scrollwheel. But still, it would be nice if the magic mouse worked well.

**Comment by alderg** [comment]
Try using Shift+Click+Drag instead.

**Comment by JesseAldridge** [comment]
Ok yeah that works.  Thanks.
