### ISSUE TITLE
math symbols have gray shadow when the diagram is exported to pdf

### ISSUE THREAD

**Issue by Rico1900** [jgraph/drawio#2931]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I exported the diagram to pdf, the font of math symbols such as $e_1$, had gray shadow around the symbol in the pdf, but I didn't set the shadow option.
Only specific PDF viewers can reproduce the bug such as the Overleaf pdf viewer and the Zotero pdf viewer.
When the exported pdf is opened in the macOS Preview or Chrome, it can be displayed correctly.

**To Reproduce**
1. Enable mathematical typesetting in a diagram
2. type some latex equation
3. exported to a pdf
4. open the pdf with Zotero pdf viewer or Overleaf pdf viewer

**Expected behavior**
The math symbol should not have gray shadow.

**Screenshots**

<img width="69" alt="image" src="https://user-images.githubusercontent.com/7353107/178291795-65419b6d-b271-470e-b554-1223ad5c50c7.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.0.4, Web, Chrome

**Additional context**
This bug has been reported [here](https://github.com/jgraph/drawio/issues/2873), but it seems that it does not get fixed completely.

This bug has also been discussed  [here](https://stackoverflow.com/questions/70439770/when-i-import-a-pdf-file-inside-overleaf-the-math-mode-characters-turns-bold/70441295#70441295).

**Comment by alderg** [comment]
Please attach a test case.

**Comment by Rico1900** [comment]
https://app.diagrams.net/#G1F2BlMYAJpXJ30NBibUBw7ECv7Un_U1-
[test.drawio.pdf](https://github.com/jgraph/drawio/files/9393755/test.drawio.pdf)
8

**Comment by alderg** [comment]
ie a diagram file to the ticket that shows this problem when exported as PDF

**Comment by alderg** [comment]
This PDF looks fine. There is no gray shadow. (Tried in Chrome and macOS Preview.) This looks like an error in the PDF viewers you are using.

**Comment by danielajisafe** [comment]
I still face this issue, especially when the pdf is uploaded to overleaf.

**Comment by hsinghuan** [comment]
@danielajisafe Have you resolved this problem?

**Comment by hungntt** [comment]
The problem will disappear when we download them instead of watching directly on Overleaf

**Comment by hsinghuan** [comment]
Got it! Thanks for the answer.

**Comment by danielajisafe** [comment]
Yes @hsinghuan , True @hungntt!
