### ISSUE TITLE
app.diagrams.net is not longer able to authenticate against GitLab

### ISSUE THREAD

**Issue by FlorinPeter** [jgraph/drawio#2932]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Authorize on GitLab is not working due to "The authorization server does not support this response type."

**To Reproduce**
1. Go to https://app.diagrams.net/?mode=gitlab
2. Click on 'Open Existing Diagram'
3. Click on 'Authorize'

**Expected behavior**
Authorize GitLab is working

**Screenshots**
<img width="1787" alt="Bildschirmfoto 2022-07-13 um 07 44 52" src="https://user-images.githubusercontent.com/2911849/178660166-def218eb-e303-456c-addf-2e7ce2b0bd01.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.1.1

**Comment by ashrafteleb** [comment]
I've just tried the same steps and it works. Can you please try in incognito/private mode?

**Comment by ashrafteleb** [comment]
> I don't know if this is linked but I have a similar issue with my self hosted draw (20.1.1 after upgrading from 20.0.4) connected to a self hosted gitlab. After the authorization page from gitlab, I get the following error (same error in incognito mode) : ![draw](https://user-images.githubusercontent.com/851854/178754332-17169f7c-10a1-4e33-9a1d-a399de7aee9c.png)

It's not related but we managed to reproduce and fix

Can you please try to replace this library in WEB-INF (after renaming extension to .jar) and check if it works
[gae-stub-1.0.9.zip](https://github.com/jgraph/drawio/files/9103341/gae-stub-1.0.9.zip)

**Comment by balpert89** [comment]
when opening the self-hosted diagrams instance it revealed the same error @m-mohamedin reported. We will update our image and I will report back.

![image](https://user-images.githubusercontent.com/28100685/180720445-57ba1731-390f-4811-be48-46046f70d0de.png)

**Comment by balpert89** [comment]
I can confirm updating to 20.1.4 resolves the issue successfully.

**Comment by amruthapbhat** [comment]
> I can confirm updating to 20.1.4 resolves the issue successfully.

which gilab version did you use with this verion of drawio?
