### ISSUE TITLE
Documentation on how to develop plugins

### ISSUE THREAD

**Issue by lasssim** [jgraph/drawio#2933]
Hi,

I love drawio/diagrams.net, and I'd like to develop a custom plugin. I have taken a look at the existing plugins and I can use them as a basis to develop my own, but I just can't find any official documentation. 

Am I too blind to find it, or is there none?
Is there some kind of resource where I can see what methods are available to a plugin?
I'd also like to know how I can add dropdown menus, text boxes, checkboxes and radio buttons to a dialog.

Please give me some pointers where I can find out more information on how to develop a plugin.

Thanks a lot,
Simon

**Comment by davidjgraph** [comment]
Yup, literally nothing.

**Comment by fabianoriccardi** [comment]
Will we get the docs for plugins? Or should we just reconsider the idea of developing a plugin?

**Comment by davidjgraph** [comment]
Yup, I'd use another tool.
