### ISSUE TITLE
Provide way to _only_ snap to grid and not other objects

### ISSUE THREAD

**Issue by mattklein999** [jgraph/drawio#2935]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

While trying to move items so they snap to the grid, if there is another item near the same i.e. horizontal line then that seems to take precedence over the underlying grid.

For example, when trying to aling arrow text to the grid, I frequently get the text to snap to a mid-line of another item, and that item isn't perfectly sized to the grid so the mid-line is off grid, and the text then snaps off-grid.

**Describe the solution you'd like**
Have a way (checkbox, key press) to force grid alignment, which means the alignment algorithm will ignore all other inputs and only take the grid into account.

**Describe alternatives you've considered**

**Additional context**

**Comment by alderg** [comment]
Try uncheck "Guides":
<img width="233" alt="Screenshot 2023-01-02 at 14 52 39" src="https://user-images.githubusercontent.com/921200/210240476-9182a336-ad09-4eba-a622-73fba3902d74.png">
