### ISSUE TITLE
Remove automatic text selection

### ISSUE THREAD

**Issue by manake** [jgraph/drawio#2936]
**To Reproduce**
1. Create a rectangle.
2. Write left aligned text inside (2 lines).
3. Click in the middle of 2nd line and drag cursor to the left to select text.
4. When cursor moves beyond the left edge of the rectangle it selects all previous lines of text.

**Expected behavior**
It should not select all previous lines of text.
Text editors like Visual Studio Code (VSC) don't select any previous lines of text and that's an expected and more optimal behavior for editing.

**Comment by mararad** [comment]
Couldn't reproduce the issue. Please check if you see the same problem in other browsers and Incognito mode with all browser extensions temporarily disabled.

If yes, attach a video showing all the steps, the result and add environment details.

**Comment by manake** [comment]
https://user-images.githubusercontent.com/6874031/180666775-b7eecac4-bd76-4598-b5d6-71dcea3c6366.mp4
