### ISSUE TITLE
draw.io for Notion Chrome extension:full screen button is not displayed

### ISSUE THREAD

**Issue by kimisikainai** [jgraph/drawio#2938]
Buttons such as full screen are not displayed in chrome (chrome version 103.0.5060.114  64 Bit).
![image](https://user-images.githubusercontent.com/16152606/179454174-27fb8afd-9a4f-441f-8bbb-bdd91d76cb6e.png)

The correct display should be this:
![image](https://user-images.githubusercontent.com/16152606/179454293-e0fc5b82-2a5a-4d5c-a7f3-09f5fc384d97.png)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by alderg** [comment]
Visit https://embed.diagrams.net/clear.html to force an update.

**Comment by kimisikainai** [comment]
It is worked thanks.
