### ISSUE TITLE
Rendering U+Exxx unicode block does not work

### ISSUE THREAD

**Issue by naturalmechanics** [jgraph/drawio#2942]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Rendering U+Exxx, such as U+E21C in a custom font like Symbols Nerd Font does not work.  This issue flowss over to part of U+FA30. The nerdfonts may be found here[here](https://www.nerdfonts.com/cheat-sheet) . 

**To Reproduce**

1. Copy the character U+E21C from a font viewer, libreoofice, etc.
2. Create a Rectangle in Draw.io desktop version
3. Double click to add text in the rectangle
4. Paste the copied element from clipboard. This will show a box with a cross in it, a glyph for undefined font
5. Keep this glyph selected
6. Go to "Text" tab
7. Click on "Font" of Schrift Drop down menu
8. Select "custom" or "Benutzerdefiniert" 
9. Paste the name "Symbols Nerd Font" (exactly as it appears in font viewer or libreoffice) in the textbox
10. Select ok / Anwenden
11. See error

**Expected behavior**
A font that looks like a  tree to be rendered, as per Nerdfonts website above.

**Screenshots**

![image](https://user-images.githubusercontent.com/7945932/179747739-72020d03-433c-4af6-90c9-1b903231dc94.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 19.0.3 Desktop Linux

**Desktop (please complete the following information):**
 - OS: Linux Artix 
 - uname -a output : Linux _myname_ 5.18.10-artix1-1 #1 SMP PREEMPT_DYNAMIC Fri, 08 Jul 2022 07:26:22 +0000 x86_64 GNU/Linux

I hope the error description is useful for debugging. I am not sure if this is a bug, or whether it is unsupported, and thus should fill under feature request. Let me know please.

**Comment by alderg** [comment]
Please attach a test case.

**Comment by naturalmechanics** [comment]
[test.zip](https://github.com/jgraph/drawio/files/9173751/test.zip)
U+2006 
Font name : Symbols Nerd Font (installed systemwide)
