### ISSUE TITLE
Text Label for "Predefined Process" shape appears below the shape

### ISSUE THREAD

**Issue by tesmerjg** [jgraph/drawio#2943]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The text label for the "predefined process" shape in the "flowchart" section appears _below_ the shape. I expected it to be _within_ the shape.

![image](https://user-images.githubusercontent.com/438620/179856813-7bef0f3d-70bb-46d7-8307-0f8e64306bc1.png)

The shape "fda" is from the "general" library and is labeled "process" (incorrectly - it should be "predefined process"). It correctly includes the text within the shape. The shape "rfsds" is from the "flowchart" library and is labeled "predefined process". It incorrectly shows the label of the box below the shape.

**To Reproduce**
1. Create a new flowchart.
2. Expand the "flowchart" library.
3. Drag a "predefined process" element to the drawing.
4. Enter a label on the shape.

**Expected behavior**
I expected the label to be within the box, like this:
![image](https://user-images.githubusercontent.com/438620/179857130-747f89f6-de13-4f03-b7b4-0afbe789c79b.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.1.1

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/438620/179857257-1d5724c9-b39d-490b-b813-d010cc4bd39d.png)

![image](https://user-images.githubusercontent.com/438620/179857403-3a647cdc-29f8-429b-9b3d-9752f68dd84c.png)

**Comment by mararad** [comment]
If you select the shape > Click Text tab > Choose Center under Position, does it help?

![position](https://user-images.githubusercontent.com/44292306/179954798-04e79a75-79a6-4192-8e79-892a88b75024.JPG)

**Comment by nerdoc** [comment]
Can confirm under Linux/Manjaro and Chromium 103.0.5060.134.

**Comment by davidjgraph** [comment]
Can you point us to an official specification that says the label must be within the shape?

**Comment by nerdoc** [comment]
I don't think there is an "official specification"? I think it's just natural, like the label of a STOP sign on roads is *on* the sign too, and labels of  your door bell might be as well there.
Of course it could be below, but all the other shapes in the "Flowchart" have their labels within the shape too, just "predefined process" not. It is easy to be mixed up with labels of arrows/lines, if it's outside:
![grafik](https://user-images.githubusercontent.com/2955584/181719582-7718cb52-fae0-49fd-90a4-873d1d5cbf0b.png)
So I think it's more a rule-of-common-sense than a specification.
E.g. here: https://www.zenflowchart.com/flowchart#Definition

**Comment by nerdoc** [comment]
This issue shouldn't be closed by a bot. So a small ping to keep it alive.

**Comment by davidjgraph** [comment]
First of all, we would like to express our gratitude for your time and effort in posting, your contribution to improving the project is much appreciated.

We have noticed that it has attracted very few or no votes from the community. As our development team needs to prioritize tasks that are in higher demand and directly impact the core functionality of the project, we have decided not to address this specific issue at the moment.

Please understand that this decision does not in any way devalue your suggestion. We truly appreciate your input and encourage you to continue sharing your ideas and feedback with us in the future. Our project thrives on the contributions of its users, and we will keep evaluating all issues to make sure we address the most pressing needs.

Once again, thank you for your understanding and your contribution to the project.
