### ISSUE TITLE
Reorder line and column position in table

### ISSUE THREAD

**Issue by slimhk45** [jgraph/drawio#2947]
It is not possible to switch line/column position or do transposition of a table in a text box. It should be a core feature of the core editor.

**Comment by mararad** [comment]
Does this help a bit for reordering? https://www.diagrams.net/blog/tables
"do transposition of a table in a text box." - not sure how this should look like. Please provide an example/screen shot or other

**Comment by slimhk45** [comment]
I'm using the Diagram.net with the Diagram.net for Notion extension. I don't see the feature you sent to me.

**Comment by slimhk45** [comment]
I got the problem, textbox table have almost no features compared to the standalone ones.

![image](https://user-images.githubusercontent.com/39030030/180601437-6c527bdc-f729-41b1-b6f0-881d90e3cfe4.png)

It would be useful to have the same features for both table.

**Comment by slimhk45** [comment]
Also it is not possible to reorder column in standalone table. Only rows.

**Comment by slimhk45** [comment]
**I found a workaround while waiting the feature to be fully supported!**
There is a web app called [TablesGenerator](https://www.tablesgenerator.com/) that allow you to edit HTML tables. You can copy/paste your table data from and to Draw.io to edit it in a more user-friendly way.
