### ISSUE TITLE
Minor Typo: "You application is up-to-date"

### ISSUE THREAD

**Issue by A-Franklin** [jgraph/drawio#2948]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Missing an "r" in "You application is up-to-date" 
(should be "You**r** application is up-to-date")

**To Reproduce**
1. Go to 'Help' menu
2. Click on 'Check for updates'

**draw.io version (In the Help->About menu of the draw.io editor):**
- 19.0.3

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Source: [/src/main/webapp/electron.js#L752](https://github.com/jgraph/drawio/blob/bf41618c37f9918078303e3a875961187b86f86b/src/main/webapp/electron.js#L752)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
