### ISSUE TITLE
newline in mathematical typesetting not work

### ISSUE THREAD

**Issue by a7168** [jgraph/drawio#2953]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
From 7/2 I find that the typesetting of formula is gone, the newline symbol is not work, like "\\\\" and "\newline". 
I have ask some friend and try on different PC but got the same result.
I'm not sure this is bug or I miss some environment setting, while there was no problem before 7/2.
(I noticed it on 7/2. not sure if it happened earlier)
Today I remember that drawio have desktop version, so I download and try it.
and I find that desktop does not have this problem.
My browser is chrome  103.0.5060.134

**To Reproduce**
1. enable mathematical typesetting by extras->mathematical typesetting in upper toolbar
2. type something with newline like fig, left is preview and right is text.
3. See error

**Expected behavior**
newline should work

**Screenshots**
![img](https://user-images.githubusercontent.com/27774913/180590197-7e74eb28-bd9b-460c-927b-e4703445424b.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: 20.2.0

**Desktop (please complete the following information):**
 - OS: win10 21H2
 - Browser: chrome
 - Version: 103.0.5060.134

**Comment by alderg** [comment]
See https://github.com/mathjax/MathJax/issues/2312
