### ISSUE TITLE
Textbox table are invisible on creation

### ISSUE THREAD

**Issue by slimhk45** [jgraph/drawio#2954]
When you create a textbox table with a given number of rows and column, you can't see it in your textbox until your define a border column. It would be more user friendly to set directly a default border color (black for instance).

**Comment by mararad** [comment]
Please provide a video if possible.

Thanx,

**Comment by slimhk45** [comment]
![image](https://user-images.githubusercontent.com/39030030/181069314-203b99fd-c5c2-438b-980d-470448e63a92.png)

The table I just created is invisible.

**Comment by mararad** [comment]
We improved table shapes and you don't have to use html tables any more. 
Please follow the steps described here: https://www.diagrams.net/blog/tables

**Comment by slimhk45** [comment]
I have already heard about it. Sadly there are not the features I expected. In the new table feature you can't reorder column, also you can't select a whole column/lines an paste into another empty column/lines. Also the advantage of HTML table is that it is directly embedded in the textbox (not a separate box) like a regular markdown/word doc.
