### ISSUE TITLE
"Bring Forward" and "Send Backward" should move relative to overlapping items

### ISSUE THREAD

**Issue by dtgriscom** [jgraph/drawio#2955]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
The "Bring Forward" and "Send Backward" menu items move an object one level forward or back. Problem: in a complex drawing, this will often have no visual effect since none of the affected objects overlap; you may have to choose this menu items many times to have a visual effect (and there's no point in using this without a visual effect).

**Describe the solution you'd like**
The "Bring Forward" and "Send Backward" menu items should move the selected item relative to any overlapping items, skipping all non-overlapping items.

In other words, say there are 100 items (numbered front to back), item 50 is selected, is in back of overlapping items 20 and 30, and in front of overlapping items 60 and 70, and overlaps no other items. Then:

* "Send Backward" should move the selected item 50 to layer 60, moving items 51 through 60 forward to layers 50 through 59
* "Bring Forward" should move the selected item 50 to layer 30, moving items 30 through 49 backward to layers 31 through 60

So, each selection of "Bring Forward" and "Send Backward" would (usually) have a visual affect, rearranging the other objects' layering as little as possible.

**Describe alternatives you've considered**
Adding a shortcut to "Bring Forward" and "Send Backward" would make it a little less painful to move multiple steps.

**Additional context**
(None)

**Comment by dtgriscom-ta** [comment]
This seems like a relatively simple thing to do that would make the "Bring Forward" and "Send Backward" commands useful in complex diagrams. Without this, they tease at a useful feature, but don't really provide it.
