### ISSUE TITLE
Latest GCP stencils in repo?

### ISSUE THREAD

**Issue by alexjmoore** [jgraph/drawio#2957]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
As per this blog: https://www.diagrams.net/blog/gcp-aws-shapes-network-diagrams

The stencils for AWS And Google Cloud were updated in/around March timeframe.  However I don't believe the updated Google ones made it into the repo?  at least the gcp2.xml has not been updated for 2 years.  I see reference in the ChangeLog to 17.5.0 release getting the updated icons, but I see no corresponding commit, so wondered if it didn't make it in?

Apologies if I'm looking in the wrong place.

Thanks in advance.

**Comment by egrimate** [comment]
The last update for GCP was around August 20th 2022. Please let us know if you notice some shapes missing.

**Comment by alexjmoore** [comment]
Thanks for getting back to me.

gcp2.xml seems unchanged from when I originally raised the issue, or is it another stencil set I should be using?

https://github.com/jgraph/drawio/blob/dev/src/main/webapp/stencils/gcp2.xml

Thanks,
Alex

**Comment by abdelouahabb** [comment]
Many products were added since 2020 : Workflow, AlloyDB ...

**Comment by davidjgraph** [comment]
@abdelouahabb Are these icons in the official Google icon set?

**Comment by abdelouahabb** [comment]
@davidjgraph yes, the slides are not updated yet, but the whole set is here https://googlecloudcheatsheet.withgoogle.com/

**Comment by davidjgraph** [comment]
We can't be expected to implement from there. Do the SVGs on https://cloud.google.com/icons include those?

**Comment by abdelouahabb** [comment]
@davidjgraph here is [a repo I just made](https://github.com/abdelouahabb/gcp_icons.git), I used [SVG Export Chrome Extension](https://chrome.google.com/webstore/detail/svg-export/naeaaedieihlkmdajjefioajbbdbdjgp) as on GCP, the icons are SVG, they are ordered and organized exactly how GCP console is organized
