### ISSUE TITLE
Save&Exit button is not available when this repo is cloned and used locally

### ISSUE THREAD

**Issue by mithunraj31** [jgraph/drawio#2959]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
We have integrated the drawio in ckeditor ,Since we need some customization for 
  drawio we cloned the drawio code from git https://github.com/jgraph/drawio and tried customizing 
 through diagram-editor.js

     Once the integration is done through local code we couldnt able to get the Save&Exit Button.
**(DiagramEditor.prototype.drawDomain = 'http://127.0.0.1:8001/‘;**

    But when tried to run the application through embedded link we could get the  Save&Exit button.
**(DiagramEditor.prototype.drawDomain = 'https://embed.diagrams.net/‘**

**To Reproduce**
1. Clone this repo https://github.com/jgraph/drawio
2. Run the server http-server -p 8001
3. In Diagram-editor.js change  (DiagramEditor.prototype.drawDomain = 'http://127.0.0.1:8001/‘
4. Check the drawio page on the top-right corner

**Expected behavior**
Need the Save&Exit button to be visible

**Screenshots**
Please see the attached screenshot for more information

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version latest

**Desktop (please complete the following information):**
 - OS: [ iOS]
 - Browser [ chrome]
![Screen Shot 2022-07-27 at 13 08 28](https://user-images.githubusercontent.com/13015062/181163783-f84ebd7a-2e11-4f56-8614-579bf78008b5.png)
![Screen Shot 2022-07-27 at 13 23 33](https://user-images.githubusercontent.com/13015062/181163787-12466e6b-4018-4e49-a820-c12689b1af67.png)

**Comment by davidjgraph** [comment]
Append `?embed=1` to the URL

**Comment by mithunraj31** [comment]
Hi @davidjgraph  i tried adding it but still i couldn't see the buttons.

**Comment by mithunraj31** [comment]
@davidjgraph  i have managed to get the buttons now by adding spin =0 in params h**ttp://127.0.0.1:8001/?proto=json&spin=0&embed=1&ui=min&libraries=1**\

Thnaks for your support
