### ISSUE TITLE
PDF export with transparent backgrounds

### ISSUE THREAD

**Issue by IGI-111** [jgraph/drawio#296]
I've taken to using drawio with its PDF export to draw figures for my LaTeX documents and presentations. However, the exported figures all have a white background which makes including them with darker backgrounds painful, since I have to manually remove the background element for all the figures by hand with, say, Inkscape.

It would be very nice to have a checkbox in the export dialog to not include said background at all.

**Comment by davidjgraph** [comment]
Duplicate of https://github.com/jgraph/drawio/issues/118
