### ISSUE TITLE
Mathematical typesetting disabled by zooming

### ISSUE THREAD

**Issue by qking** [jgraph/drawio#2960]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I have a figure that includes mathematical typesetting using ``. When I zoom in or out, the typesetting switches off and I see the source. If I toggle between pages (there are two), it is reactivated, so this is my workaround.

**To Reproduce**
1. Go to https://www.dropbox.com/s/zc28rm1qtzaydk9/firing_regulation_v29.drawio?dl=1 to download the file.
2. Start diagram.net in the browser. Click on File->Open from->Device and read in the downloaded file 
3. Switch to Notes page (this has more mathematical typesetting, but the Figure page also has the problem with the small number of typesetting examples)
4. Zoom in or out to see the mathematical typesetting turn off. Toggle between pages to reactivate it.

**Expected behavior**
Mathematical typesetting should not be affected by zooming.

**Screenshots**
Before zooming:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/2310411/181209064-fe1e2912-0880-4d7e-a001-49024b99af1a.png">
After zooming:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/2310411/181209253-9b2cd4e8-b17e-4d80-8376-87054781bf0a.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- 20.2.1... I have tested it on the latest Brave and Safari browsers on the latest MacOS. 

**Additional context**
I noticed this first about two weeks ago, but I hadn't worked with diagrams.net for a few months before that, so I don't know when it first appeared.

**Comment by qking** [comment]
I can add a further observation concerning this issue. If I move an object with mathematical typesetting in it, it also switches to source view for that one object.

**Comment by davidjgraph** [comment]
Is this still an issue in 24.0.6?

**Comment by qking** [comment]
Hi @davidjgraph ,

I’ve used four different versions of drawio, starting with diagrams.net, where I first experienced the issue back in 2022. This appeared to finally be fixed in late 2023. 

This is the situation this morning:

1. diagrams.net (24.0.6): No issue

2. MacOS desktop app (24.0.4): No issue

3. Confluence drawio app (no version information visible to me): No issue with zooming, but mathematical typesetting doesn’t work with the lightbox viewer, only renders equations when viewing a page if the simple viewer option is selected.

4. Unofficial drawio extension to VsCode by Henning Dieterichs (v1.6.6): Zooming issue is present. This is a recent regression. It was working until a few weeks ago and now has the zoom issue 100% of the time. The same workaround I mentioned still works – toggling between pages renders the equations until the next zooming action.

Maybe Henning needs to rebuild his extension with the latest version of drawio, to get the fix.

**Comment by qking** [comment]
I just found in the history for Henning Dieterichs' VsCode plug-in that it is using an old version: 20.8.3

**Comment by davidjgraph** [comment]
Thanks for the clarifications. We're happy we understand why this was fixed, I'll close it up.

For the confluence app, please either post version details here, in a new ticket or file a support ticket at the help desk.

This should have been dealt with faster, the issue signal to noise ratio has been a little low in this repo, I will fix that.

**Comment by qking** [comment]
Thanks a lot. 

I've reported to the Confluence support here at CERN about the drawio app issues and they have apparently reported it, but I've no news so far. It seems to be a different variation to the issue, since it doesn't affect editing, but viewing afterwards.

The VsCode extension issue is frustrating, since it is really good apart from this one point. It's even better than the desktop app in some ways, because you can set the image scaling and it's applied whenever you save. Which isn't the case with the desktop app.

**Comment by alderg** [comment]
You can set the image scaling for `.drawio.png` files in the desktop app via File, Properties:

<img width="461" alt="Screenshot 2024-03-14 at 11 38 47" src="https://github.com/jgraph/drawio/assets/921200/8ce1c109-d38d-48a1-81dd-8adf1494b6ab">

**Comment by qking** [comment]
Ah, good. I didn't see that last year, when I started using the app.

**Comment by qking** [comment]
That's strange... I'm looking at the File menu of the drawio desktop app on my Mac and there is no Properties option:

![image](https://github.com/jgraph/drawio/assets/2310411/4359d1b7-dbd2-49d3-b48f-30fb7afb0356)

It's the latest version according the "Check for updates" option: v24.0.4.

**Comment by qking** [comment]
Oh wait, it's an SVG... so no scaling is needed. I'll switch to a PNG.

**Comment by qking** [comment]
So scaling with png works correctly. :)

I got some progress on the Confluence drawio app issue. It turns out to be browser dependent. On Safari I see this:

![image](https://github.com/jgraph/drawio/assets/2310411/1c80a81a-fc5b-42bc-a8c0-f70269aa0f9a)

While on Chrome and Brave I see this:

![image](https://github.com/jgraph/drawio/assets/2310411/df5f3bb0-c3e7-41dd-9cc2-46dbd62eab66)

The first equation is show without "Simple viewer" enabled, while the second is enabled. The second has the Lightbox option enabled, but on Brave and Chrome, the equation isn't rendered in the lightbox, while it is on Safari.

**Comment by alderg** [comment]
> That's strange... I'm looking at the File menu of the drawio desktop app on my Mac and there is no Properties option:
> 
> ![image](https://private-user-images.githubusercontent.com/2310411/312853362-4359d1b7-dbd2-49d3-b48f-30fb7afb0356.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MjU3MTMsIm5iZiI6MTcxMDQyNTQxMywicGF0aCI6Ii8yMzEwNDExLzMxMjg1MzM2Mi00MzU5ZDFiNy1kYmQyLTQ5ZDMtYjQ4Zi0zMGZiN2FmYjAzNTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMTQxMDEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDkwMGYwYTFhY2E1NzhlNDk2MjM2Nzg5MjE0ZWVlYjQwZjg1YWRjODIwN2YwNjYyY2E2ZGVlMDgwNzI3MTg4ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ujldJuNyzhckJJPdMp4lR-s3yzq0oQPiRF82MKBya-0)
> 
> It's the latest version according the "Check for updates" option: v24.0.4.

What version do you see in the help menu?

<img width="353" alt="Screenshot 2024-03-14 at 15 09 17" src="https://github.com/jgraph/drawio/assets/921200/f2ffa2d7-9aeb-4fca-a605-feae819cdc9f">

I see this file menu in v24.0.4 desktop on macOS:

<img width="407" alt="Screenshot 2024-03-14 at 15 08 43" src="https://github.com/jgraph/drawio/assets/921200/ab060db2-82cc-4904-b803-87a8f6b88914">
