### ISSUE TITLE
Add release notes to releases

### ISSUE THREAD

**Issue by silopolis** [jgraph/drawio#2961]
Hi,

It would be great to have release notes, or just git commits messages history for the release, added to the releases publications.
Would better show developers work, project dynamism and help us follow evolution directly in our mail boxes

Thanks in advance

Stay well and cool
TY
J

**Comment by davidjgraph** [comment]
It's tricky. None of the changes for the latest release are relevant outside of the architecture where we host diagrams.net. It's all logging and back-end changes so when pushed to this repo the release looks kinda pointless.
