### ISSUE TITLE
Rounded Rectangle's border radius should not scale with height of Rounded Rectangle

### ISSUE THREAD

**Issue by CollinMonahanLab49** [jgraph/drawio#2965]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

I create a Rounded Rectangle and then I want it taller, I drag the bottom edge to increase height, and the border radius becomes larger also. The same doesn't happen if I increase the rectangle's width. I think that's correct, the behavior when increasing the width, and expect the same from increasing the height.

**To Reproduce**
1. Go to diagrams.net draw.io
2. Click on rounded rectangle
3. place it on screen and make taller
4. see huge border radii

**Expected behavior**
Not huge border radii

**Screenshots**

![Screen Shot 2022-07-28 at 2 46 55 PM](https://user-images.githubusercontent.com/88339423/181614588-05ed4906-9664-4a70-8a7b-cc0d16e53777.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.2.1

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 103.0.5060.134

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
N/A

**Comment by CollinMonahanLab49** [comment]
![Screen Shot 2022-07-28 at 2 53 54 PM](https://user-images.githubusercontent.com/88339423/181615762-927db21e-6df7-43d1-9744-bfe15da5fbff.png)

**Comment by alderg** [comment]
Tick "Abs. Arc Size" under Properties:
![Screenshot 2022-07-29 at 07 28 43](https://user-images.githubusercontent.com/921200/181688971-8c737bc0-56f2-4977-96be-9b95cb2ba46f.png)
