### ISSUE TITLE
Inconsitent UI when setting grStroke style to 0 on container object

### ISSUE THREAD

**Issue by EdwardBlair** [jgraph/drawio#2966]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

The purple outline when dragging a shape into a container does not work when `grStroke` to `0`.

Library shapes which are affected by this are `AWS Public subnet`, `AWS Private subnet` and the borderless `AWS Generic group`.

**To Reproduce**

1. Add `AWS Public subnet`, `AWS Private subnet` or `AWS Generic group` (borderless) to canvas
2. Observe container UI is broken when dragging a shape into the container
3. `Edit Style` set `grStroke=1;` and `Apply`
4. Observe behaviour is functional

**Expected behavior**
UI is consistent regardless of style when object is a container.

**Screenshots**
`grStroke=0`
![image](https://user-images.githubusercontent.com/239672/181908714-b6d42572-cc28-425d-a339-9db6591c2d3b.png)
`grStroke=1`
![image](https://user-images.githubusercontent.com/239672/181908842-43d903e2-eb3f-40df-9405-8fdbed0e8777.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.2.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 102.0.1

**Comment by davidjgraph** [comment]
https://github.com/jgraph/drawio-dev/commit/727d29508008505a961c2e8fb02a7a54b8a75dda

**Comment by alderg** [comment]
The container flag on the generic AWS groups isn't set for usability reasons. The subnet highlights will be fixed in the next release.
