### ISSUE TITLE
Allow adjust start U number of numbered rack

### ISSUE THREAD

**Issue by edgesite** [jgraph/drawio#2967]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When designing a cabinet, we want to split rack space into 3x15U or split it by function(power, compute, networking). The current numbered rack doesn't support adjust the start of the U number.

**Describe the solution you'd like**
Add a property to numbered rack, to specify start rack start number.

**Describe alternatives you've considered**
Don't split rack, but it mess large rack design.

**Additional context**
![demo](https://user-images.githubusercontent.com/10336620/182141125-ec8b0abf-bad6-4c37-9dee-032f6baada6c.jpg)

**Comment by egrimate** [comment]
Will be in next release

**Comment by edgesite** [comment]
any chance we can get [this PR](https://github.com/jgraph/drawio/pull/2968) merged? 😊 @davidjgraph @egrimate

**Comment by davidjgraph** [comment]
Contributions are not accepted, please read the readme, https://github.com/jgraph/drawio

We implemented the functionality ourselves, you will find it in the last mentioned.
