### ISSUE TITLE
Add cross selection

### ISSUE THREAD

**Issue by mrns** [jgraph/drawio#297]
I used Autocad in the past and although it has another purpose, their object selection tool has 2 modes, depending on the direction you create the selection box, left or right. Dragging towards right selects all objects contained by the selection (window selection), this is how draw.io works now; dragging towards left selects all objects crossed by the selection or inside it (cross selection). Here is a link to AutoDesk documentation about this feature.

https://knowledge.autodesk.com/support/autocad-lt/learn-explore/caas/CloudHelp/cloudhelp/2018/ENU/AutoCAD-LT/files/GUID-243E4DD0-8947-4905-AFE2-BE9B903A8C3F-htm.html

Cross selection makes it easier to select objects in scenarios that are difficult to achieve using window selection, like for instance selecting a container box and only some of its children. Using window selection the only way to do this is by selecting all and then deselecting some objects, with cross selection you can just cross over the container box and only the children you want.

**Comment by davidjgraph** [comment]
Use Alt+Drag to select intersection

**Comment by brandonjyee** [comment]
I just noticed the selection behavior in diagrams.net changed recently and came across this Issue. I've been using `Opt + Click` (I'm using a Mac) frequently to click within a larger container and window select items within that container. Now `Opt + Click` appears to always be doing cross selection (irregardless if I'm selecting right or left). How do I do window selection within a container now?

**Comment by alderg** [comment]
Release the alt key before releasing the mouse key.
