### ISSUE TITLE
[Feature Request] Templates add Finite State Machine Examples

### ISSUE THREAD

**Issue by andrewcrook** [jgraph/drawio#2971]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? ***
No

**Describe the solution you'd like**
Would be good to add State Machine examples to templates.
example - in the form of 

![image](https://user-images.githubusercontent.com/803618/182645088-b07543ac-4a07-465b-ab35-258d73cf8779.png)

**Comment by andrewcrook** [comment]
BUMP

**Comment by GIT-SMR** [comment]
That would be a nice to have indeed!
