### ISSUE TITLE
The draw.io app window needs a frame for the desktop app

### ISSUE THREAD

**Issue by noloader** [jgraph/drawio#2976]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I am using draw.io as a desktop app. The app was installed using a Snap on Ubuntu. The app name is 'drawio`. The drawio window is drawn without a frame line. I cannot tell where the drawio app ends and other windows begin due to lack of a frame.

I checked the various menu options. I did not see an option to turn on the window frame. Related, I did not see an option to set high contrast colors. My apologies if I missed them.

The lack of options to turn on a frame or set high contrast color is probably a UI bug. The inability to set high contrast colors is kind of egregious since visually impaired users will have problems with the app.

The drawio app works perfectly at draw.io. The browser provides a window frame, and it is easy to discern windows on the desktop.

**To Reproduce**
1. Install the drawio snap
2. Start drawio desktop app.

**Expected behavior**
I would like the frame drawn so I can discern the app's window from other windows on the desktop. Or, an option to have the frame drawn.

**Screenshots**
Please see below.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: 20.2.3 <strike>3.1.0</strike>

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
N/A
-----

![pencil-draw-io-desktop-app](https://user-images.githubusercontent.com/3538226/182927120-88007773-c3c7-41c4-9cf0-5eb0b405da53.png)

**Comment by davidjgraph** [comment]
What is pencil? draw.io 3.1.0 is very old, it has critical security holes. You need to update immediately.

**Comment by noloader** [comment]
Thanks @davidjgraph,

I _think_ this is the upstream Ubuntu bug: Snap distributes vulnerable version of draw.io, https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1987075 .

(This looks like it could be a rabbit hole. Ubuntu is telling folks to use Snap to install the software. I've got a feeling no one is officially responsible for Snap packages. It is one of those "best effort").
