### ISSUE TITLE
C4 WebBrowserContainer doesn't allow changing fillColor

### ISSUE THREAD

**Issue by JulioC** [jgraph/drawio#2977]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

When changing the colros of C4 WebBrowserContainer it doesn't apply the fillColor to the background and strokeColor for the borders as one would expect. It instead uses the fillColor to set the frame color and leaves the background always unchanged.

**To Reproduce**
1. Use default C4 shape library
2. Create a WebBrowserContainer shape
3. Set fill and stroke colors to anything (red and green maybe)
4. See the background color unchanged

**Expected behavior**

Fill should change the background color

**Screenshots**

The image below shows how this shape behaves in comparission to others from the same collection:

![image](https://user-images.githubusercontent.com/387794/183002164-58e2a286-64c0-4330-b1cb-9b05fb0f506e.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: 20.2.3

**Additional context**

The offending code appears to be in 
https://github.com/jgraph/drawio/blob/dev/src/main/webapp/shapes/mxC4.js#L185

The shape doesn't use stroke color for anything. This change might break visuals for existing diagrams with customized colors for this components (probably not many diagrams).

**Comment by davidjgraph** [comment]
Fixed in https://github.com/jgraph/drawio-dev/commit/19a5aa3321369bb9dece3fec226ad65a5bb75804
Internal release https://drawio.atlassian.net/projects/DS/versions/11213

**Comment by JulioC** [comment]
@egrimate should it be working in 20.2.8?

![GIF](https://user-images.githubusercontent.com/387794/190289201-eac5c978-d62b-4602-8387-01abe220a185.gif)
