### ISSUE TITLE
Metamask "crypto wallet" unlocked give error on diagram web

### ISSUE THREAD

**Issue by helderjnpinto** [jgraph/drawio#2979]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I can't have metamask "crypto wallet" unlocked with app.diagrams.net open give me a error

**To Reproduce**
1. Install extension wallet Metamask 
2. open a document with diagrams
3. got error

**Expected behavior**
no capture chain id of metamask inpage 

**Screenshots**
![image](https://user-images.githubusercontent.com/12281088/183246228-055f593f-6b87-41e3-b89d-e9ab9a2a835c.png)
![image](https://user-images.githubusercontent.com/12281088/183246257-c276c9e4-ecc4-4f8d-bf9b-e97bf2b894a2.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
20.2.3

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 20.0.4
 - Browser [e.g. chrome, safari] Brave 
 - Version [e.g. 22] Release Notes v1.42.86 (Aug 3rd, 2022)

**Comment by Devmenai** [comment]
> ### Preflight Checklist
> 
> 
> * [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
> * [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.
> 
> **Describe the bug**
> I can't have metamask "crypto wallet" unlocked with app.diagrams.net open give me a error
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Install extension wallet Metamask 
> 2. open a document with diagrams
> 3. got error
> 
> **Expected behavior**
> no capture chain id of metamask inpage 
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/12281088/183246228-055f593f-6b87-41e3-b89d-e9ab9a2a835c.png)
> ![image](https://user-images.githubusercontent.com/12281088/183246257-c276c9e4-ecc4-4f8d-bf9b-e97bf2b894a2.png)
> 
> **draw.io version (In the Help->About menu of the draw.io editor):**
> 20.2.3
> 
> **Desktop (please complete the following information):**
>  - OS: [e.g. iOS] Ubuntu 20.0.4
>  - Browser [e.g. chrome, safari] Brave 
>  - Version [e.g. 22] Release Notes v1.42.86 (Aug 3rd, 2022)
> 

Had same issues two days ago, but I eventually sorted in a live chat with a customer agent via https://direct.lc.chat/14390013/
