### ISSUE TITLE
Automatic Docker Build

### ISSUE THREAD

**Issue by richardbrinkman** [jgraph/drawio#298]
It would be nice if Docker Hub would be able to build a new Docker image for every push to the master branch.

I tried forking jgraph/drawio to richardbrinkman/drawio and then instructing Docker hub to automatically build an image. This unfortunately does not work since the Dockerfile resides in the /etc/docker directory. It should be copied first to the root before the build can find the various directories like `src` and `etc` that are copied to the image build process.

Is it possible to:

1. Move /etc/docker/Dockerfile to the root of the project
2. Create a Docker Hub account (jgraph) that automatically build a public image jgraph/drawio.

**Comment by talsen-team** [comment]
It should be possible to provide the relative directory location containing the Dockerfile to build.
The option is found in Builds section where you specify your tags / branches (the option is called "Dockerfile location").
![drawio-issue-298](https://user-images.githubusercontent.com/40595118/50897733-4f5aec80-140d-11e9-864e-d04470cf1ee4.png)

Or does this configuration not work with automatic build hooks?

**Comment by davidjgraph** [comment]
https://github.com/fjudith/docker-draw.io is the recommended docker image of draw.io, it's better maintained than the internal one.
