### ISSUE TITLE
"Edit connection points" entry in context menu of groups missing

### ISSUE THREAD

**Issue by Murmele** [jgraph/drawio#2984]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When an element to the drawing area it is possible to change the connection point position of that element by right click and "edit connection points".

In version 16.5.3 this was also possible for groups. In Version 20.2.3 The "edit connection points" entry in the context menu is gone

**To Reproduce**
1. Add two objects to the drawing area
2. Select both objects and create group (Ctrl + G)
3. Select object and right click

**Expected behavior**
4. "edit connection points" entry is visible

**Current**
"edit connection points" entry is not visible

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.2.3

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11
 
**Additional context**
Maybe it was removed because editing the connection points for groups has some glitches: #2606?

**Comment by alderg** [comment]
This will be fixed in the next release for connectable groups.

**Comment by Murmele** [comment]
Thank you!

**Comment by davidjgraph** [comment]
Change in 21.1.9
