### ISSUE TITLE
Self-hosted Gitlab integration hangs on blank screen on Firefox

### ISSUE THREAD

**Issue by richardmcsong** [jgraph/drawio#2985]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success. Author's note: This is the same bug as https://github.com/jgraph/drawio/issues/1961, ~but seems like it's specific to Firefox (on Mac)?~ EDIT: seems like I can't get in on Chrome either.

**Describe the bug**
When I try to auth with `https://app.diagrams.net/?gitlab=https://gitlab.example.com&gitlab-id=<app-client-id>`, it hangs on `https://app.diagrams.net/gitlab?code=<access-code>&state=<state>` with a blank screen. On Chrome, I get a 400 error

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac BigSur 11.5.2
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 102.0.1

Gitlab version: 14.10

**Comment by davidjgraph** [comment]
What are the full details of the 400 response?

**Comment by MsNatali** [comment]
I have this problem too. 

Gitlab Version v15.4.5-ee

I auth in my gitlab instance and then see 400. In browser console response of `https://app.diagrams.net/gitlab?code=<access-code>&state=<state>` is empty
![image](https://user-images.githubusercontent.com/8089373/216613389-78ff683a-41fe-4d49-86f8-35b4ac424679.png)

**Comment by MsNatali** [comment]
It's same

![image](https://user-images.githubusercontent.com/8089373/216629222-b0c154fd-2d5a-4939-b331-56510d0e9979.png)

I can show this request in postman, the response is empty

![image](https://user-images.githubusercontent.com/8089373/216631190-20ac9cf2-d171-4e25-b688-705330186483.png)

**Comment by davidjgraph** [comment]
OK, someone would have to debug, but we don't have time to do that currently.
