### ISSUE TITLE
Exporting all pages within a document

### ISSUE THREAD

**Issue by abrahamnavas** [jgraph/drawio#299]
Currently, there's only the option to export pages individually, so in case you need to export a multi-page draw.io file into a PDF, you have to export it as many times as many pages your document contains (and then merge it all into a single PDF). 

It would be great to have a feature that allows you to decide what pages you want to export or, at least, the export of all pages by default (is actually more easy to delete pages from a single PDF than merge several PDFs into a single one).

**Comment by davidjgraph** [comment]
Tracked as https://trello.com/c/TZB5LOjw/271-multiple-page-export-in-pdf
