### ISSUE TITLE
"To Front" translation to catalan 

### ISSUE THREAD

**Issue by xeanhort** [jgraph/drawio#2992]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The Catalan translation of "To Front" should be "Cap endavant" o "Mou al davant" instead of "Vés endavant", or something more clear. The same applies for "To Back".

The "Bring Forward" and "Bring Backward" is not translated.

**To Reproduce**
Secondary click over any element in the diagram to show the popup.

**Expected behavior**
A clear translation.

**Screenshots**
![image](https://user-images.githubusercontent.com/6896906/183959536-7be5b99f-ecb4-49e5-a938-3d013d76bacb.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 20.2.3

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 102

**Comment by davidjgraph** [comment]
If you have a google account you can request write permission to the spreadsheet, https://docs.google.com/spreadsheets/d/1FoYdyEraEQuWofzbYCDPKN7EdKgS_2ZrsDrOA8scgwQ

**Comment by xeanhort** [comment]
Thank you, done!

**Comment by davidjgraph** [comment]
Thank you for your work.
