### ISSUE TITLE
Math typesetting is broken in 20.2.3

### ISSUE THREAD

**Issue by rahav** [jgraph/drawio#2998]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Either type of mathematical notation, the \`x\` and \\(x\\) are not rendering correctly in the new desktop release. All existing files are partially showing and the behavior is unpredicted. Sometimes a shape with math text would render, and after editing it, it might now. New shapes added behave the same.

**To Reproduce**
1. Use \`...\` or \\(...\\) in a few shapes, or open an existing file.

- draw.io version 20.2.3

**Desktop (please complete the following information):**
 - macOS 12.4

**Comment by mararad** [comment]
It would be great if you could recreate the issue, record all the steps and the result and attach the video here.
I tried to recreate it but couldn't.

**Comment by rahav** [comment]
Thanks for looking at this. Attached are two recordings. The first shows existing math in a shape that would render only after turning the feature OFF and  back ON. In the second it wouldn't work at all.

https://user-images.githubusercontent.com/2912950/185139109-acb70e12-e459-4c3f-8ce6-081339efd151.mov



https://user-images.githubusercontent.com/2912950/185139189-b056e1ad-e7b2-4a11-a8f1-7952fb4dfaa9.mov

**Comment by rahav** [comment]
Could this occur in drawings that have a large number of shapes?

**Comment by alderg** [comment]
Please attach the diagram files. Have you also tested this on the latest version of macOS?
