### ISSUE TITLE
Can you add shapes related to Argo Project ?

### ISSUE THREAD

**Issue by iam-veeramalla** [jgraph/drawio#2999]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Firstly, I would like to thank the maintainers for this awesome project.

Can you add some shapes related to the opensource [argo-project](https://argoproj.github.io/) ? It is a CNCF project and one of the widely used in the DevOps and GitOps communities.

**Describe alternatives you've considered**
I can import the shape for sure but adding it to the default shapes might help alot of users.

**Additional context**

**Comment by mararad** [comment]
Hi,

Please provide link to shape set and license for the set.

**Comment by iam-veeramalla** [comment]
> Hi,
> 
> Please provide link to shape set and license for the set.

I will try to gather some information, Thanks @mararad
