### ISSUE TITLE
Pasting rich text removes spaces

### ISSUE THREAD

**Issue by JesseAldridge** [jgraph/drawio#300]
1. go to https://en.wikipedia.org/wiki/Foobar
2. copy the first paragraph
3. double click on a drawio document to create a new text object
4. paste in the text

The result looks like this:
![screen shot 2018-08-14 at 12 16 56 am](https://user-images.githubusercontent.com/191903/44077232-c7fd4500-9f57-11e8-9c5c-804facee2afd.png)

Note the missing spaces.

**Comment by davidjgraph** [comment]
This works correctly for me using 11.0.5 with Firefox, we probably fixed it somewhere.

**Comment by JesseAldridge** [comment]
Yep, just tested and it's working for me too.
