### ISSUE TITLE
Holacracy Org Chart

### ISSUE THREAD

**Issue by SinaStB** [jgraph/drawio#3001]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
The traditional Organizational Charts available in the diagrams.net application are not helping and I need modified org charts.

**Describe the solution you'd like**
I want to draw organizational chart using **Holacracy** concepts (not traditional hierarchal structures) and I need it to be interactive and include Holacracy key elements.

**Describe alternatives you've considered**
I am seeking a free and open-source alternative to [GlassFrog](https://www.glassfrog.com/).

**Additional context**
I am considering using Holacracy ([A reenvisioned management style](https://medium.com/@dperciv1/holacracy-a-reinvisioned-management-style-b3c785064862)) for team restructuring, and I want to draw an organizational chart using a free, open-source platform like diagrams.net application. Considering current features available in diagrams.net, I can use the simple circles inside each other to simply fulfill this purpose, but I wonder whether there is a way to make it more interactive by probably adding rules to the entities (e.g., when you click on each of the inner circles it zooms in it making its inner circles visible and also the details of each circle can be interactively shown by hovering over each circle). 
**Holacracy** concept requires the modeler to think beyond traditional hierarchal structures and design [roles and accountabilities](https://resources.holacracy.org/holacracy-glossary) according to the needs of each particular nontraditional team (c.f., [sample interactive org chart](https://app.glassfrog.com/organizations/5/orgnav/roles/9970/roles) based on Holacracy on GlassFrog). It [works great](https://www.holacracy.org/success-stories) for software development teams too. 

Thank you for your time and consideration.

**Comment by davidjgraph** [comment]
What's your question?

**Comment by SinaStB** [comment]
My Question: Is there a way in diagrams.net to implement Holacracy elements instead of the traditional elements of hierarchal organizational charts?
Interactive (with zoom feature) circular (with sub circles inside each) entities that can hold some textual properties like [roles and accountabilities](https://resources.holacracy.org/holacracy-glossary) that appear when hovered over by mouse. Something similar to [sample interactive org chart](https://app.glassfrog.com/organizations/5/orgnav/roles/9970/roles) using GlassFrog.

**Comment by davidjgraph** [comment]
At the risk of sounding sarcastic, yes, to implement it you'd change the source code until you implement Holacracy elements instead of the traditional elements of hierarchal organizational charts.

Am I missing something here?

**Comment by SinaStB** [comment]
No, you are absolutely on the point. 
Since I am new to the software development field (my background is Information Systems) and reusing open-source applications, I think the task of developing the code to fit my needs might be over my head. I guess that is why my question seems elementary. I just thought it might be wise to ensure the base code can host these changes and hope for a facilitated way to do it actually.
I appreciate your time and consideration and I will search around to learn how to implement the required changes to the source code. 
Best wishes David.

**Comment by davidjgraph** [comment]
draw.io is a complex code base as JS projects go. If you're not a developer, unfortunately, this isn't a forgiving project for the beginner.
