### ISSUE TITLE
github auth redirect URI 401

### ISSUE THREAD

**Issue by shmilyzby** [jgraph/drawio#3002]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
GIthub integration's redirect URI (https://app.diagrams.net/github2?code=[...]) returns a 401, failing to authorize.

**To Reproduce**
1. Go to 'app.diagrams.net'
2. Click on 'save' and user Github 
3. Auth draw.io App on Github
4. On final, redirect from github domain back to app.diagrams.net/github2?code)=[...], which returns a 401

**Expected behavior**

Github integration should complete with a successful redirect and then confirm the authentication in draw.io's UI, allowing the user to save draw.io documents to Github repo

**draw.io version**

- 20.2.4

Desktop (please complete the following information):

OS: Mac OS Monterey
Browser: Chrome Version 104.0.5112.79 (Official Build) (arm64)

- I tried revoke authorization on Github and re-auth draw.io app, it didn't work
- I tried delete cookies in Chrome, it didn't work
- I tried blocking third party cookies in Chrome and changing to allow them for app.diagrams.net, it did't work.

**Comment by davidjgraph** [comment]
What about using an incognito window?

**Comment by shmilyzby** [comment]
> What about using an incognito window?

It works! but how do i fix it in normal window

**Comment by shmilyzby** [comment]
It works! but how do i fix it in normal window

**Comment by shmilyzby** [comment]
> What about using an incognito window?

It works! but how do i fix it in normal window

**Comment by m-mohamedin** [comment]
> > What about using an incognito window?
> 
> It works! but how do i fix it in normal window

You'll need to clear your browser cache and cookies

**Comment by shmilyzby** [comment]
I cleaned all cookies and caches in chrome, it didnn't work :(

**Comment by shmilyzby** [comment]
I find that if i switch the storage mode to Google drive, the same thing hanppend

**Comment by m-mohamedin** [comment]
Check your browser plugins please (or another browser)
