### ISSUE TITLE
TypeError: This writable stream writer has been released

### ISSUE THREAD

**Issue by Misseva1988** [jgraph/drawio#3003]
### Preflight Checklist

* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**
1. Go to (https://app.diagrams.net/?local=1)
2. Click on 'Create'
3. Scroll down to 'Save as' window
4. See error in browser

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/34433886/185519133-57e519cc-297b-48c4-b893-a94799ce7958.png)

- draw.io version 20.2.4

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [360]

**Comment by davidjgraph** [comment]
I cannot repeat the steps as there's no 'save as' window.

**Comment by Misseva1988** [comment]
the "save as" window like this:
![image](https://user-images.githubusercontent.com/34433886/185827059-74d6afe2-df59-4c52-a88a-84e427caefc6.png)

**Comment by Misseva1988** [comment]
why I have a "save as" window?

**Comment by davidjgraph** [comment]
The reproduction steps are not clear.
