### ISSUE TITLE
GraphViewer crashes if passed a graphConfig via data-mxgraph json with a string handler

### ISSUE THREAD

**Issue by Zannick** [jgraph/drawio#3007]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

A plugin used to embed drawio diagrams from xml files fails to render with the error "Failed to execute 'addEventListener' on 'EventTarget': parameter 2 is not of type 'Object'." This was reported to the plugin in https://github.com/mikitex70/redmine_drawio/issues/105 and a workaround in the plugin was created to automatically modify the GraphViewer code.

The cause appears to be GraphViewer.js, which allows for a graph config to be defined as a JSON string in data-mxgraph, but assumes the handler in the parsed config is already a js callback, and not a string meant to be evaluated.

**Details**
The plugin populates the `data-mxgraph` attribute of a div to add an edit button to editable files, which requires a handler.[^1]

with newlines and indents added for clarity, the relevant section of the config looks like
```
"toolbar-buttons":{
  "edit":{
    "title":"Edit",
    "handler":"(function(){editDiagram($('#dg_xvtjadpq'),'filename_1.xml', false, '', 'filename_2.xml');})",
    "image":""data:image/png;base64,..."
  }
}
```

[^1]:  https://github.com/mikitex70/redmine_drawio/blob/e9c5138dc9e7ad686e40713840fbe720a40990e6/lib/redmine_drawio/macros.rb#L423-L429

data-mxgraph is parsed here and passed to GraphViewer:

https://github.com/jgraph/drawio/blob/f7158bfb0029a6456c215791b7fd005ccb5c3e76/src/main/webapp/js/diagramly/GraphViewer.js#L2141-L2152

GraphViewer.addToolbar will retrieve the handler, which is a string, and pass it to addButton:

https://github.com/jgraph/drawio/blob/f7158bfb0029a6456c215791b7fd005ccb5c3e76/src/main/webapp/js/diagramly/GraphViewer.js#L1557-L1563

addButton will attempt to register it as an event listener:

https://github.com/jgraph/drawio/blob/f7158bfb0029a6456c215791b7fd005ccb5c3e76/src/main/webapp/js/diagramly/GraphViewer.js#L1281-L1286

**To Reproduce**
Sorry I don't have an easy reproduction available. I can suggest either:

1. Manually create a data-mxgraph json string or manually call GraphViewer with an appropriate config object.
2. In a Redmine wiki with a drawio plugin version 1.3.0 or earlier, where you have edit access, upload a drawio xml file and use the macro to display the graph in-line on the wiki page. Observe that instead it says "Failed to execute 'addEventListener' on 'EventTarget': parameter 2 is not of type 'Object'." in the space the graph should be drawn.

**Expected behavior**
The diagram file is rendered correctly. I am not too concerned with whether or not the edit button works.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: 20.2.7 (as provided by https://viewer.diagrams.net/viewer-static.min.js)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 

**Additional context**
Code and reasoning behind the plugin's workaround is here: https://github.com/mikitex70/redmine_drawio/blob/50f334a2c459de7be32917ed356523805c0af304/assets/javascripts/drawioEditor.js#L555

**Comment by alderg** [comment]
We'll add a hook called createToolbarButton that can be overridden as follows in the next release:

`GraphViewer.prototype.createToolbarButton = function(fn, imgSrc, tip, enabled)
{
    if (typeof fn === 'string')
    {
        fn = eval(fn);
    }

    return graphViewercreateToolbarButton.apply(this, arguments);
};`

**Comment by Zannick** [comment]
Thanks.

To clarify, the default behavior of GraphViewer isn't changing, users of `data-mxgraph` like this plugin will be expected to override the new hook in this way? Not quite what I was hoping for, but I can understand why you would want to avoid adding `eval` in.

**Comment by davidjgraph** [comment]
Internal release link https://drawio.atlassian.net/projects/DS/versions/11213
