### ISSUE TITLE
Embed draw.io Diagram in Confluence not allow some domains because of Content Security Policy directive

### ISSUE THREAD

**Issue by ptyskju** [jgraph/drawio#3009]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I'm trying to upload CSV file from `windows.net` (Azure) or `googleusercontent.com` (Google App Script) domains, but browser console shows me that error:

```
viewer-static.min.js:253 Refused to connect to 'https://XXX.blob.core.windows.net/XXXX' because it violates the following Content Security Policy directive: "connect-src 'self' https://*.draw.io https://*.diagrams.net https://*.googleapis.com wss://*.pusher.com wss://app.diagrams.net https://*.pusher.com https://api.github.com https://raw.githubusercontent.com https://gitlab.com https://graph.microsoft.com https://*.sharepoint.com https://*.1drv.com https://api.onedrive.com https://dl.dropboxusercontent.com https://*.google.com https://fonts.gstatic.com https://fonts.googleapis.com".
```

**To Reproduce**
1. Follow that instruction: https://www.diagrams.net/doc/faq/embed-diagram-csv-confluence-server
2. Try to import file from Azure or Google App Script (I think that files from Bitbucket will not be imported as well)
3. Open browser logs

**Expected behavior**
Diagram should be rendered without any error

**draw.io version (In the Help->About menu of the draw.io editor):**

Don't know, because it is embed editor

**Desktop (please complete the following information):**
I don't think so it is related to only one environment, but here are data that you ask:
 - OS: Ubuntu 22.04
 - Browser Chrome
 - Version 104

**Comment by davidjgraph** [comment]
Fixed.
