### ISSUE TITLE
Invite for a whiteboard session in outlook with a direct link

### ISSUE THREAD

**Issue by JoernLu** [jgraph/drawio#3012]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Actually, new colleagues I need to guide through confluence to do a whiteboard session. 

**Describe the solution you'd like**
A Direct Link in outlook to the whiteboard session would be appreciated. 

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by davidjgraph** [comment]
This is for Confluence Cloud?

**Comment by JoernLu** [comment]
HI David,

yes it is confluence cloud.

Have a nice week.

Jörn Lubosch
Operation Manager
E-Mail: ***@***.******@***.***>
Tel.: +49 40 413 030 71

perview systems gmbh Lademannbogen 124, 22339, Hamburg
[Facebook]<https://protection.retarus.com/v1?u=https%3A%2F%2Ffacebook.com%2Fperview&c=3rzmP5c&r=570ZrLa47RE5hKtPckV7L3&k=7s1&s=iOMNXNeFIbV4Ssiu3ljnlswPwH5bdEKF28vFNVVIwa>
[Twitter]<https://protection.retarus.com/v1?u=https%3A%2F%2Ftwitter.com%2Fperviewhcm&c=3rzmP5c&r=50bZaUK8RebmhLYvEhmC5L&k=7s1&s=cBmbvhgvmXo5IHQjYGH3OzxkPx4NUAb6DeyBKC87H4k>
[LinkedIn]<https://protection.retarus.com/v1?u=https%3A%2F%2Flinkedin.com%2Fcompany%2F5099363&c=3rzmP5c&r=5wwaKFCB6QzqG63Ud74qYK&k=7s1&s=p74Q5M7KQWSuJkkFxz09v9EruwhMTYxnkYHluH4YsuW>
[YouTube]<https://protection.retarus.com/v1?u=https%3A%2F%2Fyoutube.com%2Fc%2FPerviewDe&c=3rzmP5c&r=75oBBO5louPzPLfUraInjQ&k=7s1&s=BpPg9nIShPKccKcuiPmf2722GMQSEPJmWG7W3LKmoP3>
[XING]<https://protection.retarus.com/v1?u=https%3A%2F%2Fwww.xing.com%2Fcompanies%2Fperviewsystemsgmbh&c=3rzmP5c&r=2Tog0dLj2wl15KAIlQzxoT&k=7s1&s=8eYkluYSIH4XVj055AbMwLbdJVkPPRdt1amekMXNMmD>
[Instagram]<https://protection.retarus.com/v1?u=https%3A%2F%2Finstagram.com%2Fperview_systems%2F&c=3rzmP5c&r=iGNLbQj3Ux1wtb1Q3yMcd&k=7s1&s=QEr9CzwK0BHUQGMgUaVNihJlWGmiVpsqUD6EOvqcTD7>
***@***.***

***@***.***<https://protection.retarus.com/v1?u=https%3A%2F%2Fperview.de%2Fonline-demo%2F&c=3rzmP5c&r=3DT2UEmseCMrbq4dXwT12E&k=7s1&s=5VcMuxXxC4Yz64MKCQ36WsEuc7XvPMhanzqBFjn6W0J>
Informationen über Ihre gespeicherten Daten finden Sie auf unserer Homepage unter folgendem Link: perview Datenschutz<https://protection.retarus.com/v1?u=https%3A%2F%2Fwordpress.perview.de%2Fdatenschutz%2F&c=3rzmP5c&r=7XUWI1EoDKg7QIJVYJxnNl&k=7s1&s=N56sSe500OLvE2rEi9n9rUyhgOrctPxYkiKhHlRkFRM>
Diese E-Mail enthält möglicherweise vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat dieser E-Mail sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie uns bitte unverzüglich und löschen Sie diese E-Mail. Das unerlaubte Vervielfältigen oder Weiterleiten dieser E-Mail ist strikt untersagt.






Von: David Benson ***@***.***>
Gesendet: Donnerstag, 1. September 2022 19:14
An: jgraph/drawio ***@***.***>
Cc: Jörn Lubosch ***@***.***>; Author ***@***.***>
Betreff: Re: [jgraph/drawio] Invite for a whiteboard session in outlook with a direct link (Issue #3012)


This is for Confluence Cloud?

**Comment by davidjgraph** [comment]
Thanks for the suggestion. Unfortunately, we cannot find a technical mechanism that allows us to implement the feature, and so have to decline it.
