### ISSUE TITLE
Additional shapes for SysML shape library

### ISSUE THREAD

**Issue by jaylapras** [jgraph/drawio#3015]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Need to be able to add ports to SysML block shapes at will for internal block diagrams. The current block shapes do not have an adequate range of port configurations.

**Describe the solution you'd like**
Three new shapes:
small filled square - blank port shape
small filled square with an arrow in it - flow port shape
small filled triangle - flow shape for placement on connectors

**Additional context**
<img width="493" alt="image" src="https://user-images.githubusercontent.com/60265913/187966386-98eea707-1237-4be6-8aef-7a1ff304f8d6.png">

**Comment by egrimate** [comment]
Will be in next release.

**Comment by davidjgraph** [comment]
Internal commit https://github.com/jgraph/drawio-dev/commit/915bfdce24c8a1599c46fea532221c9db614c6ad
