### ISSUE TITLE
Bug: Pressing CMD key on Safari 16 moves the whole diagram around 

### ISSUE THREAD

**Issue by dvaldivia** [jgraph/drawio#3017]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When using draw.io on Safari Technology Preview, if I press the CMD key, the diagram moves around, so if I want to copy (CMD+C) or tab away (CMD+TAB) the diagram will shift. For example:
![2022-09-03 19-41-24 2022-09-03 19_42_03](https://user-images.githubusercontent.com/18384552/188294750-52516ba7-fea8-4b3f-bfcc-5acff45b79a7.gif)

**Comment by filipw** [comment]
This is now happening in the main Safari release - MacOS Monterey 12.6, Safari Version 16.0 (17614.1.25.9.10, 17614).

**Comment by ima747** [comment]
> This is now happening in the main Safari release - MacOS Monterey 12.6, Safari Version 16.0 (17614.1.25.9.10, 17614).

Experiencing the same on the same MacOS and Safari versions. Window size doesn't appear to matter. Happens in fullscreen or regular window mode. Happens on existing and brand new diagrams. I'm on an M1 Max if hardware might be a factor (doubt it but details are sometimes helpful).

Does NOT happen on an iPad with magic keyboard case FWIW.

**Comment by dvaldivia** [comment]
Updated the title to reflect that it happens on release Safari 16 so more users will start experiencing this

**Comment by shz-aiworks** [comment]
I am having the same issue, any solution yet?

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release (available ASAP).

**Comment by davidjgraph** [comment]
Internal commit https://github.com/jgraph/drawio-dev/commit/c3722397b88b686199ecd3afc49c8ecfd80d47d7
