### ISSUE TITLE
Bug? Published links to publicly viewable draw.io files in Google Drive now asking for authorization 

### ISSUE THREAD

**Issue by ndinguthamsanqa** [jgraph/drawio#3018]
### Preflight Checklist
- [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched everywhere online to see if this is a known bug or if there are any workarounds, but whatever I've found is old or the authorization problems are not the ones I've experienceing.

Hi there, I hope you can help with this one! 🙏 I *love* diagrams.net so much and I rely on being able to publish my diagrams so that anybody can view them. I'm happy to provide any extra information required. Thank you! 

### Details
[Here](https://viewer.diagrams.net/?highlight=0000ff&nav=1&title=diagram-to-test-publishing.drawio#Uhttps%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D1emPfmHC6at8rH2v5AOqNtM0VE6Hr_SCj%26export%3Ddownload) is an example of a published link which is now asking for authorization to view even in Private and Ingognitio modes in Firefox and Chrome respectively. The same links on a friend's computer also asks for authorization. 

### To reproduce
Here are the steps I took to generate this test file.

1. Create a new .drawio file stored in Google Drive.
2. Share the file so that it anyone with the link can view it.
3. Go to **File > Publish > Link ...** to generate the URL to viewer.diagrams.net. 
4. Confirm that the diagram file in Google Drive is publicly shared and viewable before generating the URL. 
5. Test the URL in Private mode in Firefox or Incognito mode in Chrome.

### Desirable behaviour?
Published links created in the above way should not ask for authorization - anybody should be able to view them without needing to sign in to Google.

### Possibly useful additional information?
1. Something seems to have changed in the last month or so either on Google Drive or with diagrams.net (or both). Files I have previously published in this way without issue are now asking for authorization.
2. If I export an iframe code and embed it somewhere, I _don't_ get any authorization issues. It seems to be limited to publishing to viewer.diagrams.net.
3. A couple of weeks ago, I had a large file (~25 MB) which seemed to take a while to load in the viewer before triggering the authorization error. When I got it down to about 15 MB, the authorization issue disappeared so I guessed at the time that authorization was perhaps being triggered by loading times. But this file is now back to triggering the authorization issue, so I no longer know if this is relevant or not (or perhaps file size _can_ be an issue, but this new problem is just unrelated).

Is there a better way to share "presentation" versions of diagrams publicly?

**Comment by m-mohamedin** [comment]
Hi,

Thanks for the report, the issue will be fixed in the next release.
