### ISSUE TITLE
The value provided (3) is outside the range [-1, 2].

### ISSUE THREAD

**Issue by huornlmj** [jgraph/drawio#3019]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
In the threat modelling shapes I want to add a new column to the assets and adversaries tables but I get an error:

```
Failed to execute 'insertCell' on 'HTMLTableRowElement': The value provided (3) is outside the range [-1, 2].
```

How do I adjust the maximum number of columns that these tables will allow?

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 20.2.8]

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. chrome]

**Comment by davidjgraph** [comment]
It's one of the old HTML tables, needs to be changed to new table.

**Comment by egrimate** [comment]
Will be fixed with the next update. The library now uses the more recent table type.

**Comment by davidjgraph** [comment]
Internal commit https://github.com/jgraph/drawio-dev/commit/375c028ad4eaed3fc1009d0882a12f79077ae2d7
