### ISSUE TITLE
Electronic component issue

### ISSUE THREAD

**Issue by GR8Ko** [jgraph/drawio#3020]
Dear community,
I have been using drawio for making electronic circuit schematic but each time I struggle to align the components (mostly horizontally). For example, as shown in the attached file, I was trying to connect an inductor in series with a capacitor, they are not aligned perfectly. How can I fix it? 
PS: I tried with snap grid mode and snap point mode ON/OFF but it did not work at all.
Thanks in advance.
Best regards,
![Issue_DrawIO](https://user-images.githubusercontent.com/112927911/188564479-306bf45b-d083-4b0c-8039-2e91e5817adb.PNG)

**Comment by mararad** [comment]
When you select a e.g capacitor and click keyboard arrow down, does it help?

This is how it looks at my place.
![inductor](https://user-images.githubusercontent.com/44292306/188633705-774f9dad-f27f-4627-b2fb-681aad704359.JPG)
