### ISSUE TITLE
Cannot import the PDF I created a while back

### ISSUE THREAD

**Issue by manavsingh415** [jgraph/drawio#3026]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

I used to be able to create PDF diagrams and import them back into draw.io later to continue working on it. All the textboxes/shapes would appear the same way. Now, when I try importing the PDF, it shows me a link like this

data:application/pdf;base64,JVBERi0xLjQKJdPr6e.... 

**To Reproduce**
I'm not sure how. The PDF I want to work on was probably created using an older version of draw.io

**Expected behavior**
The textboxes and shapes to be annotated the same way as they were when I first created the PDF

Thank you!

**Comment by davidjgraph** [comment]
PDF is an export format, not a save format. To re-load a diagram you have to have saved it, rather than exported it.

**Comment by manavsingh415** [comment]
Okay, I suppose that means that I cannot load it the same way as before.
