### ISSUE TITLE
Support for Microsoft OneNote

### ISSUE THREAD

**Issue by AlexGriffith** [jgraph/drawio#3027]
Support for Word, Excel, and Powerpoint is great, but I'm often wanting to embed drawio flowcharts and such in OneNote instead. 

I'm often forced to embed screenshots of flowcharts and diagrams, or just a link to the website for a dynamic page. Adding support for installing as an add-in in OneNote would make a lot of use-cases better for myself and others.

**Comment by davidjgraph** [comment]
Declined
