### ISSUE TITLE
Guides dont work if shape is rotated

### ISSUE THREAD

**Issue by fedalal2** [jgraph/drawio#3031]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
If you set menu item View- Guides checked, you can move shapes around each other and it will snap to shape margins.
BUT it works only if shape angle is 0 or 180. If you rotate another angle (f.e. 90), it doesnt snap correctly
 

**To Reproduce**
1. Add rectangle
2. Add second rectangle
3. Set menu item  View- Guides is checked
4. Try move one rectangle arount second. Guides are showing correctly and rectangle snap to another
5. Rotate rectangle to 90 degree and try move arount another rectangle. Guides works incorrectly

**Expected behavior**
Guides should correctly work for any angle of shapes

**Screenshots**
![image](https://user-images.githubusercontent.com/49028622/189326565-a9e7682a-6610-4564-bbc4-cd39e9244596.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [20.3.0]

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [chrome]
 - Version [104.0.5112.102 ]

**Additional context**

**Comment by mararad** [comment]
Do you see the guide when vertical rectangle is places centrally as shown in the image?
![guides](https://user-images.githubusercontent.com/44292306/189625152-5ca3ad36-badb-4724-aae6-312c4afffaea.JPG)
In your image shapes are not aligned centrally.

**Comment by fedalal** [comment]
> Do you see the guide when vertical rectangle is places centrally as shown in the image? ![align](https://user-images.githubusercontent.com/44292306/189625621-bb3b97fa-0a20-47f7-8b78-de6fddd2a328.JPG)
> 
> In your image shapes are not aligned centrally.

Yes, I see  guide when vertical rectangle is places centrally,
BUT I can't snap to left/right/top/bottom of the shape if shape is rotated 90 degree.
If it has angle 0 or 180 I can snap one shape to another left/ritght/top/bottom sides
