### ISSUE TITLE
Color picker does not pick the right color

### ISSUE THREAD

**Issue by Btwoll** [jgraph/drawio#3035]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Whenever I try to use the color picker to pick a color from an existing shape on the file, the file gets greyed out and the picker selects the greyed version of the color not the actual color

**To Reproduce**
1. Go to fill
2. Click on the color panel
3. Click on the 3 dots
4. select the color pick and try to pick a color from the existing file
5. See error

**Expected behavior**
when trying to pick a color it should not be greyed out

**Screenshots**
<img width="688" alt="Screen Shot 2022-09-12 at 4 09 21 PM" src="https://user-images.githubusercontent.com/113355973/189662316-effd5097-69f3-4979-aef7-f563bf788d91.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- diagrams.net 20.2.3

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Version [12.5.1]

**Additional context**

**Comment by alderg** [comment]
Try shift+click on the original color button in the style panel.

**Comment by Btwoll** [comment]
> Try shift+click on the original color button in the style panel.

Worked thanks! but still needs to be fixed from the original style panel
