### ISSUE TITLE
Google Drive Authenticator not working

### ISSUE THREAD

**Issue by taylorwilson86** [jgraph/drawio#3036]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I want to access my Google Drive for draw.io docs. It was worked no problem for me up until today. Today when I tried accessing it took me to a blank white screen and did not progress. See my recorded video: https://www.loom.com/share/02276116238b4f0d887e969487f9fff3

I am unable to embed the draw.io to a Confluence page which is my main goal. I have the same authentication issue.

**To Reproduce**
See recorded video

**Expected behavior**
Authentication to work and access to Google Drive in draw.io and for embedding in Confluence

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io 20.3.0

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: macOC Monterey Version 12.5.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by davidjgraph** [comment]
Does it work on a chrome incognito window?

**Comment by ekkeguembel** [comment]
Same issue here, white screen / 401 after giving permissions in Google - except this is first try (not a "worked before" situation)
* 20.3.0
* MacOS 11.6.8
* same in Safari / Chrome / FF
* does not work in incognito either
* deleting cookies, local storage etc. doesn't help
* no allowing 3rd-party cookies, cross-site tracking etc. helps, no content blocking involved

**Comment by ekkeguembel** [comment]
FYI - now it works, magically.
When I experienced the issue earlier today, I asked colleagues to try the same - they had the same issue.
Now it works for them too, also for those who never tried before.


No idea what caused the hickup, but I did not change a thing.
Also no upstream cache here.

**Comment by davidjgraph** [comment]
@taylorwilson86 this isn't the same issue. You can post a new issue if you wish.
