### ISSUE TITLE
Add subMenu scrollbar

### ISSUE THREAD

**Issue by AnthonyBordet** [jgraph/drawio#304]
I created a menu with multiple submenus, and some of the submenus dont display all the element on the screen if i dont zoom out. Is it possible to add a scrollbar to my submenus ? Thanks

**Comment by davidjgraph** [comment]
Can we see your test case of it failing?

**Comment by AnthonyBordet** [comment]
I didnt really test because i couldn't find a way to do it, so i tought it would be automatic. I just have a submenu containing a huge list of elements.
