### ISSUE TITLE
Web version breaks if loaded at less than ~760px wide

### ISSUE THREAD

**Issue by tom-os** [jgraph/drawio#3048]
**To Reproduce**
1. Resize you window to less than ~760px wide
2. Load official URL (app.diagrams.net)  - or the current dev branch
3. GUI loads in broken state, unrecoverable

**Expected behavior**
Should work at this size

**Screenshots**
![image](https://user-images.githubusercontent.com/106205666/190288054-ba7ae906-b511-47ac-af55-732be6baa2a8.png)

**Comment by alderg** [comment]
This is the mobile UI which was designed for smaller screens. To disable this, select "Default" under Extras > Theme (even if it's already selected).
