### ISSUE TITLE
This is now happening in the main Safari release - MacOS Monterey 12.6, Safari Version 16.0 (17614.1.25.9.10, 17614).

### ISSUE THREAD

**Issue by Fahad1410** [jgraph/drawio#3049]
This is now happening in the main Safari release - MacOS Monterey 12.6, Safari Version 16.0 (17614.1.25.9.10, 17614).

_Originally posted by @filipw in https://github.com/jgraph/drawio/issues/3017#issuecomment-1246486359_

**Comment by davidjgraph** [comment]
This is a low quality report, please improve it or it will be closed.
