### ISSUE TITLE
Untested printing issue

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#305]
Report from user:

"If I use an object in the background to categorize items for my reference they have an issue when the print.  I am including the xml file and a pdf of what prints.  If export to pdf and then print that it works."
[example.pdf](https://github.com/jgraph/drawio/files/2301518/example.pdf)
[Example.xml.txt](https://github.com/jgraph/drawio/files/2301522/Example.xml.txt)

**Comment by ashrafteleb** [comment]
Cannot reproduce currently. Both export and print works as expected
