### ISSUE TITLE
The file was not found. It does not exist or you do not have access.

### ISSUE THREAD

**Issue by justkatha** [jgraph/drawio#3053]
I'm trying to work on a file and do some changes - I work on this file daily.
When I started my machine today and trying to access it I get following message.
I did not delete this file from my G-Drive, but it's nowhere to be found anymore.

**Describe the bug**
The file was not found. It does not exist or you do not have access. 

**Screenshots**
![image](https://user-images.githubusercontent.com/113730226/190808962-ec2bb7b5-fed0-4190-8b26-7c1b2f1c848a.png)
- draw.io version [20.3.2]

**Comment by davidjgraph** [comment]
Look in drive.google.com for the file on that account.

**Comment by justkatha** [comment]
I know - the file is gone from my Gdrive, but also not in the trash bin :( 
that's what is so confusing to me

**Comment by davidjgraph** [comment]
There is no functionality to delete Google Drive files in diagrams.net. Either there is GDrive bug or you used a different Google account.
