### ISSUE TITLE
iPad - unable to move or reorder pages / tabs

### ISSUE THREAD

**Issue by DreamShark-Bytes** [jgraph/drawio#3054]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When using the iPad and attempting to move a page around to reorder them, I am unable to. 
Not when using the trackpad on my magic keyboard, the touch screen or my apple pencil. 
I’ve also tried these actions with function keys such as CMD, Option, or Control. 
Using arrow keys with various other keys doesn’t help either, like Tab, CMD, Option or Control. 
This feature is available on Desktop version, but not iPad in any way I have tried. 

**To Reproduce**
1. use an iPad browser of Safari or Chrome, and navigate to draw.io
2. Create or open a graph with multiple pages / tabs. 
3. attempt to move the pages around and reorder them 
4. notice no change or reaction

**Expected behavior**
Being able to click-and-drag a page on a graph with multiple pages and be able to move them around and change their order. 

**Screenshots**
Since any recording applications I try don’t records button or keyboard clicks, I’m unable to properly record this action NOT taking place when I attempt it. 

**draw.io version:**
20.3.2

**Desktop (please complete the following information):**
 - OS: iOS on iPad, version 15.7
 - Browser: Chrome version 150.0.5195.129
 - Browser: Safari - version is tied to iOS version

**Comment by DreamShark-Bytes** [comment]
I'm curious where else this issue occurs.

**Comment by alderg** [comment]
Added Move submenu to page tab context menu in v20.5.0.
