### ISSUE TITLE
iPad - Double-Click & Drag causes selection to break

### ISSUE THREAD

**Issue by DreamShark-Bytes** [jgraph/drawio#3055]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When using the trackpad on the magic keyboard case for the iPad and click-and-drag for selection, but only holding the trackpad down for selection after a double-click. While dragging the selection tool (holding down the mouse) items get highlighted de-highlighted VERY fast in a strobe like-fashion. Once releasing the trackpad the selection of items gets “stuck” or “broken”. 
By “selection”, I mean that blue boxes are put around each item that is supposed to be selected, as well as weird canvas-wide blue boxes, and there are not transformation tools on the selected items. aka, no orbs on the corners of the items. 
The double-click option is normally reserved for object-creation, so a window sometimes also pops up asking if I want to insert objects, such as text, circle, square, etc.
I suspect this is also affected by mouse inputs, but I can’t test that at the moment. 
This issue is NOT the same as [issue #2758](https://github.com/jgraph/drawio/issues/2758), but it is adjacent. 

**To Reproduce**
1. use an iPad using a magic keyboard case and it’s trackpad.
2. Use a browser of Safari or Chrome, and navigate to draw.io
3. double-click on the canvas but on the 2nd-click continue to hold down the trackpad to drag the selection across multiple items. 
4. Let go of the trackpad and the items will. be pseudo-selected. Surrounded by blue-boxes without transformation tools (orbs on the corners of selected items). and a dialog box opens listing various objects I can put into the document, such as: text, circle, square, etc. 

**Expected behavior**
Should just do a normal click-and-drag selection without the rabid flashing of blue across the entire stream. 
OR
Object-creation menu. 

**Screenshots**

![iPad_DoubleClick_Selection_medium](https://user-images.githubusercontent.com/70111379/190877752-5b9cce1a-43b7-40a0-a3bd-ec0585a683cc.gif)

**draw.io version:**
20.3.2

**Desktop (please complete the following information):**
 - OS: iOS on iPad, version 15.7
 - Browser: Chrome version 150.0.5195.129
 -Browser: Safari - version is tied to iOS version

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
