### ISSUE TITLE
iPad - Double-Tap Selection (touch screen) causes selection to get stuck

### ISSUE THREAD

**Issue by DreamShark-Bytes** [jgraph/drawio#3056]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
To do object-selection using touch input on the ipad, the Option button must be held down first. 
When double-tapping the iPad screen with touch-input and hitting the Option button on the 2nd press the selection gets stuck until tapping the screen again. 
While it’s like this, there is NO way to get out of this selection when using the trackpad on the magic keyboard case for the iPad. Touch input must be used again. 
This is NOT the same as [Issue #3055](https://github.com/jgraph/drawio/issues/3055) because it’s using touch-input (not mouse/trackpad input) and the selection is getting stuck in a different way. 

**To Reproduce**
1. use an iPad and use touch-input (fingers)
2. Use a browser of Safari or Chrome, and navigate to draw.io
3. double-click quickly on the canvas but on the 2nd-click hold down the Option button (which is the way to do object-select when using touch-input)
4. Doesn’t matter if you let go of Option key first or stop touching the screen, the selection tool gets stuck until touching the screen again. If you use a trackpad from the magic keyboard case while the selection is stuck, there is no way (that I could find) to get out of the selection. 

**Expected behavior**
Should just do a normal click-and-drag selection.
OR
Object-creation menu. 

**Screenshots**
You can tell the selection is stuck because I’m able to keep moving the canvas around and the selection stays. 
![Automatic](https://user-images.githubusercontent.com/70111379/190878230-03deb26d-9c70-4afc-a9f4-c3d4ed31a7fc.gif)

**draw.io version:**
20.3.2

**Desktop (please complete the following information):**
 - OS: iOS on iPad, version 15.7
 - Browser: Chrome version 150.0.5195.129
 -Browser: Safari - version is tied to iOS version

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
