### ISSUE TITLE
Add SAP Fiori Design Stencils

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#3067]
Add [SAP Fiori Design Stencils](SAP Fiori Design Stencils). Would need to be written from scratch.

**Comment by kmschramm** [comment]
We all use draw.io very often within Confluence in the company. Our software development concepts are all written in Confluence.
What is currently missing is the ability to easily create mockups with draw.io, in particular mockups for SAP Fiori apps (not to mention the classic SAP Gui screens).
Overall, the range of templates, diagrams and icons for creating desktop mockups is a bit too limited.
