### ISSUE TITLE
Azure container apps icon is missing from compute section.

### ISSUE THREAD

**Issue by yogeshk04** [jgraph/drawio#3068]
* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Was looking for a Azure Container Apps Icon while creating a my diagram but could not find it in the Azure/compute section.
I would request could you please add it?

**Describe the solution you'd like**
Please add the Azure container apps icon in the Azure icon library.

**Describe alternatives you've considered**
Copied the icon form interner.

**Additional context**

**Comment by yogeshk04** [comment]
Please let me know if I can help to contribute in this issue? thanks

**Comment by mararad** [comment]
Could you please add an example of the missing icon so I could be sure which one exactly you are looking for?

Thanks,

**Comment by yogeshk04** [comment]
This icon is missing form Azure / Compute icon section
![image](https://user-images.githubusercontent.com/36443045/194514984-11d6e25f-6eae-4a7b-a96b-2879ffdf712c.png)

Eg.
<img width="201" alt="image" src="https://user-images.githubusercontent.com/36443045/194515096-1a5344e2-100a-4dce-8a56-23ad0b965b74.png">

Thanks

**Comment by egrimate** [comment]
An update for the Azure set will be in the next release and you will be able to find this shape in the "Other" section. The name is Worker Container App.
