### ISSUE TITLE
'Fade Out' function in the animation.js plugin throwing an error

### ISSUE THREAD

**Issue by gitown** [jgraph/drawio#3070]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When using the 'Fade Out' function in the animation.js plugin it throws an error:
_Uncaught TypeError: graph.fadeNodes is not a function_

**To Reproduce**
1. Open diagrams.net with the anim plugin: https://app.diagrams.net/?p=anim
2. Create a diagram and select any element of the diagram
3. Click on the menu Extras -> Animation
4. Click on "Fade Out" then on "Preview"
5. See the error happening!

**Expected behavior**
"Fade Out" should work without throwing an error!

**Screenshots**
![image](https://user-images.githubusercontent.com/22465690/192066836-a2ebbe16-ff8d-4120-9758-7292a3940329.png)

**diagrams.net version (In the Help->About menu of the diagrams.net editor):** 20.3.6

**Additional context**
![image](https://user-images.githubusercontent.com/22465690/192066934-e2c6efc5-0f40-4a92-b92e-6258ee9c0570.png)
The error is on the line animation.js:139:17: graph.fadeNodes(graph.getNodesForCells([cell]), false);

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by davidjgraph** [comment]
Internal commit https://github.com/jgraph/drawio-dev/commit/0c99b6306a7e5553ba309c3b79095d6c78656bed
