### ISSUE TITLE
Digital Ocean Icons

### ISSUE THREAD

**Issue by ayami123** [jgraph/drawio#3072]
* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? 
no

**Describe the solution you'd like**
Icons for Digital Ocean Services

**Describe alternatives you've considered**
add the images, so we can also search the digital ocean services in draw.io

**Additional context**
the Icons resources are here in the slides

https://docs.google.com/presentation/d/e/2PACX-1vSI47aQrXmtAD0WmEEwdyTmMC32J-rgki5pUH1nSDw-uGNxMtcih_mysY88Cs52dsOTVyI9ym5N9zSp/pub?start=false&loop=false&delayms=3000&slide=id.g5fdb962b8f_0_843

in the presentation.

**Comment by davidjgraph** [comment]
Where are the licensing terms for the icons?
