### ISSUE TITLE
Import HP aruba networking stencil from VisioCafe not working as expected

### ISSUE THREAD

**Issue by tho86** [jgraph/drawio#3076]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

When importing stencil from VisioCafe http://www.visiocafe.com/downloads/hp/HPE-Aruba-Networking.zip, broken image are display. Stencils were converted to vssx from visio.

**To Reproduce**
1. Drag and drop vssx to draw.io (web or client)

**Expected behavior**

Stencils correctly display.

**Screenshots**

![image](https://user-images.githubusercontent.com/53077283/192299025-8babddcc-e54a-495c-bec8-bedf88637d8e.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.3.0 (client) and draw.io version 20.3.6 (web)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox and Chrome
 - Version: latest

**Comment by davidjgraph** [comment]
Is this the large or small switches library?

**Comment by davidjgraph** [comment]
It's small.

**Comment by tho86** [comment]
It's the small library

**Comment by m-mohamedin** [comment]
Please use the vss file directly without conversion to vssx, it gives better results

**Comment by davidjgraph** [comment]
Fixed.

**Comment by krevoit** [comment]
I'm still running into this exact issue. Is there anything specific I need to do to get this to work?

**Comment by MrEternalrest** [comment]
I, too, have this exact issue, was anything found out since the last request of @krevoit?
