### ISSUE TITLE
[Icon]Ali Cloud

### ISSUE THREAD

**Issue by ChenpiDog** [jgraph/drawio#3077]
Hope that drawio can support Alibaba Cloud icons, such as hologres, dataworks, etc.

**Comment by davidjgraph** [comment]
Duplicate #2712

**Comment by mcsrainbow** [comment]
I collected a complete set of Alibaba Cloud vector icons and generated the draw.io icon library:
https://blog.heylinux.com/en/2024/01/alibaba-cloud-official-vector-icons-and-draw.io-custom-libraries/
