### ISSUE TITLE
Offer a new feature. Parse a comment column from a SQL query and insert it after the value of the column.

### ISSUE THREAD

**Issue by seavalley** [jgraph/drawio#308]

**Comment by seavalley** [comment]
`technologia` TINYINT(3) NOT NULL COMMENT 'comment text1',
  `kabel` INT(11) NOT NULL COMMENT 'comment text2',
  `mufty` INT(11) NOT NULL COMMENT 'comment text3'

**Comment by davidjgraph** [comment]
If this is a feature request, please re-phrase the title and we'll label it as such. Thanks.
