### ISSUE TITLE
Library preview image - .svg support

### ISSUE THREAD

**Issue by yakovlevkll** [jgraph/drawio#3080]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

When `.svg` file is used as a library preview image, it does not fit the preview container but overflows it

**To Reproduce**

1. Create custom library
2. Add a preview image in `.svg` format to library entry

```javascript
{
  "title": { "main": "Library title" },
  "entries": [
    {
      "id": "some-id",
      "title": { "main": "Library entry title" },
      "preview": "https://svgsilh.com/svg/1775543.svg",
    }
  ]
}
 ```
3. Run the app, open library preview modal window via clicking on "**+ More shapes..**." button

**Expected behavior**

Image width fits preview container width

**Screenshots**

<img width="719" alt="изображение" src="https://user-images.githubusercontent.com/24398502/193426654-d338c598-099e-4320-a8d1-a73518ea984c.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.2.3

**Desktop (please complete the following information):**
 - OS: macOS 11.5
 - Browser Chrome
 - Version 105.0.5195.125 official arm64

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by davidjgraph** [comment]
Internal commit https://github.com/jgraph/drawio-dev/commit/bc304338793ce900e6519c73fc251b87b0f1919f

**Comment by yakovlevkll** [comment]
Thank you @davidjgraph, works like a charm!
