### ISSUE TITLE
C4 - Whitespace in data container 

### ISSUE THREAD

**Issue by rowan-trade** [jgraph/drawio#3082]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Superfluous white space. White space seen before the colon after the text e.g. "[Container : ...]"
![image](https://user-images.githubusercontent.com/113126667/193555733-8db33a59-4d2e-4e12-8db7-18cbbd50a2e0.png)

# Altered

**To Reproduce**
1. Go to draw.io
2. Click on pull data container from C4 pallet

**Expected behavior**
White space should not be seen before the colon after the text e.g. "[Container: ...]"
![image](https://user-images.githubusercontent.com/113126667/193555817-3332b69b-fb71-42fd-bfbb-63bd0059eb64.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.0.4

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser chrome Version 96.0.4664.110 (Official Build) (x86_64)

**Additional context**

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by davidjgraph** [comment]
Internal commit https://github.com/jgraph/drawio-dev/commit/757280de5a160dc3f2b5e029079f8c11b4992a77
