### ISSUE TITLE
Request: Ability to disable the default edge

### ISSUE THREAD

**Issue by Yassir-Ben-BouBker** [jgraph/drawio#3089]
- [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
is it possible to disable the default edge
![image](https://user-images.githubusercontent.com/97686091/194297305-b8f80848-2a5d-4544-b8bd-581513feacdf.png)
and just use the Costum Arrows (edge)
![image](https://user-images.githubusercontent.com/97686091/194297439-e262291f-33ae-4489-976d-2e27e9e4913f.png)

**Describe the solution you'd like**

if there is no direct way to disable the default edge
i need for the edge to not show up when click and drag shape connection point
without touching the logic for Costum Edge

thanks

**Comment by mararad** [comment]
Hi,

Not sure I understood you fully. You mentioned "i need for the edge to not show up when click and drag shape connection point..." You can try with Diagram tab (when nothing is selected) > Untick Connection arrows.

Also here you can see how edge style can be configured  https://www.diagrams.net/doc/faq/configure-diagram-editor

Custom edge can be also put into a scratchpad and re-used.

**Comment by Yassir-Ben-BouBker** [comment]
thanks for your answer @mararad 
not exactly
i am working in the forked code
and what i ant is to desable the use of edge (default with small strokewidth) in the editor (and just use the added costum edge)

thanks again

**Comment by Yassir-Ben-BouBker** [comment]
i didn't found a way to disable default edge
but i tried to disable connectionPoint like you advised
so i change the code here
![image](https://user-images.githubusercontent.com/74555968/195317166-8e135400-371c-4253-99e3-fa4c499b08a5.png)
but is there a more effective way ??

thanks you a lot
