### ISSUE TITLE
Edit source code of drawio

### ISSUE THREAD

**Issue by tranlehaiquan** [jgraph/drawio#309]
Execute, how can I edit the source code of drawio. For example, I wanna edit shapes (make a new list, add, remove shape)
![image](https://user-images.githubusercontent.com/17347993/44618453-445d5080-a8a0-11e8-9d46-bf6fff467c6c.png). 
Where should I start? (Javascript source is min file?)

**Comment by davidjgraph** [comment]
See https://stackoverflow.com/questions/45205746/draw-io-is-there-non-minified-source
