### ISSUE TITLE
Did the text margin change in newer version? (20.4.0)

### ISSUE THREAD

**Issue by DWSuryo** [jgraph/drawio#3096]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
So, I used the web app again, I noticed some changes when making a new text by double click.
![image](https://user-images.githubusercontent.com/72719372/195249456-10723c29-60bd-4309-997c-77f72772518c.png)

Turns out the margin is larger than previous version (IIRC it was version 18-ish). Here's the comparison:
![previous version](https://user-images.githubusercontent.com/72719372/195249585-94dfc1f0-7d26-431f-87d7-1e2ed1a20e4c.png)

Previous style: ```text;html=1;align=left;verticalAlign=middle;resizable=0;points=[];autosize=1;strokeColor=none;fillColor=none;```

![current version](https://user-images.githubusercontent.com/72719372/195249807-5b5f6472-2ea5-461c-af81-576a40131ece.png)

Current style: ```text;html=1;align=left;verticalAlign=middle;resizable=0;points=[];autosize=1;strokeColor=none;fillColor=none;```  
Which is the same as previous one

The problem comes to editing the text created from previous version. After editing, it comes into current version, largen the margin. I think this is a problem when the text in the layout is tight enough then after editing, it's harder to move due to alignment change. My current workaround is to reduce global spacing to 0 for new version. Was there a style change for default settings during later versions? Thank you

**currently using app.diagrams.net 20.4.0 on edge/chrome/firefox (browser updated prior Oct 12 2022)**

**Comment by davidjgraph** [comment]
Please could you test against https://19-0-3-dot-drawdotio.appspot.com/

**Comment by DWSuryo** [comment]
Sorry a bit late
Yes, I think that was the case. Here's the image+style
![image](https://user-images.githubusercontent.com/72719372/196185661-d7902cc5-7cb4-4902-aaa2-5036876008d0.png)

```text;html=1;align=center;verticalAlign=middle;resizable=0;points=[];autosize=1;strokeColor=none;fillColor=none;```

**Comment by alderg** [comment]
This is due to a fix for #2732 that went into version 20.0.2.
