### ISSUE TITLE
Include background page in PDF export

### ISSUE THREAD

**Issue by vollstock** [jgraph/drawio#3101]
I just learned about using [placeholders](https://www.diagrams.net/doc/faq/predefined-placeholders) and [background pages](https://www.diagrams.net/blog/background-pages-diagrams) which should be very useful.

However, when exporting a PDF, the background page is not drawn on each page.
I does work when exporting PNGs.

**Comment by miguelhpreuss** [comment]
I have the same problem, on online drawio, the problem doesn't appear, only on the desktop one.

**Comment by hatramatra** [comment]
See also https://github.com/jgraph/drawio-desktop/issues/713, this is possibly solved now.

**Comment by vollstock** [comment]
confirm, works for me
