### ISSUE TITLE
Draw.io turn lines into a solid shape?

### ISSUE THREAD

**Issue by hoffmanshaven** [jgraph/drawio#3105]
![draw io2](https://user-images.githubusercontent.com/25552957/195724872-964199b5-2ac1-4292-b9a6-c24b27af1919.png)

I don't know if anyone can see the picture I am trying to paste into here but I am working on a floor plan. I create a curved desk type thing in a lounge area. I am trying to put the chairs underneath but that's not a solid shape. Is there a way to turn that into a solid shape where chairs can go underneath? I searched but cannot seem to find anything about this. thank you

**Comment by felixvd** [comment]
Related: https://github.com/jgraph/drawio/issues/3105
