### ISSUE TITLE
Compressed drawio file shows mxfile/compressed="false"

### ISSUE THREAD

**Issue by TXAE** [jgraph/drawio#3106]
I know this was fixed somewhen between 20.3.7 and currently online version 20.4.1 and with it the compressed attribute was removed altogether. Is the compressed attribute coming back once it works?

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Compressed drawio file shows mxfile/compressed="false"
in other words: compressed-Attribute falsely states no compression when compression is in fact active

**To Reproduce**
1. Go to File=>Export As=>XML...
2. Leave "compressed" checkbox ticked (ticked by default)
3. Click export
4. Open the exported, compressed drawio.xml file in a text editor (e.g. Notepad++)
5. Observe the bug described above

**Expected behavior**
Compressed drawio file should show mxfile/compressed="true"

**Screenshots**
![image](https://user-images.githubusercontent.com/70020564/195794222-93d8454f-0949-46e7-b120-b4a23e623499.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- diagrams.net 20.3.0

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 21H2 (OS build 19044.1466)
 - Browser: Chrome Version 106.0.5249.119 (Official Build) (64-bit)

**Comment by davidjgraph** [comment]
Literally nobody seems to want compression, so we'll default to uncompressed in the next release.
