### ISSUE TITLE
Flowchart "Data" symbol renders text below symbol

### ISSUE THREAD

**Issue by cur33** [jgraph/drawio#311]
Unlike the other symbols I've used under the Flowchart dropdown, double-clicking on a Data symbol (the rounded-corner parallelogram) renders the text below the symbol rather than inside of it. Problem found using Chrome 68.0.3440.84 on Ubuntu 16.04 and replicated using Firefox 61.0.1 on the same system.

**Comment by davidjgraph** [comment]
Label position is different for different shapes, this is intended. If you want to move it change the text position from bottom to center.

**Comment by cur33** [comment]
Ah, good to know, thanks. I saw a (slightly old) tutorial in which the Data shape behaved the same as the others, so it must have changed since then (or the creator had already changed it himself, before the tutorial).
