### ISSUE TITLE
Item where "Moveable" is unchecked in properties can still moving when selected and using arrow keys

### ISSUE THREAD

**Issue by Mozoloa** [jgraph/drawio#3110]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Item where "Movable" is unchecked in properties, can still move when selected and using arrow keys

**To Reproduce**
1. Create a drawing
2. Create any shape
3. On the right in the object "style" tab, expand the Property | value field
4. uncheck movable
5. Use the arrow keys and the object will still move

**Expected behavior**
For the item not to move

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.4.1

**Desktop (please complete the following information):**
 - OS: W11
 - Browser Brave Latest

**Comment by davidjgraph** [comment]
Can you check on chrome or FF please?

**Comment by TXAE** [comment]
Confirm on chrome, I don't think this is platform dependent

**Comment by mararad** [comment]
Reproduced in Chrome Version 106.0.5249.119 (Official Build) (64-bit), Chrome Incognito and FF 105.0.3 (64-bit)
diagrams.net 
Win 10 Pro

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
