### ISSUE TITLE
Something breaks layers at some point, happened many times

### ISSUE THREAD

**Issue by Mozoloa** [jgraph/drawio#3111]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
At some point something breaks in the layer system and I'm not sure how to reproduce it: when you move items and connections to another layer, it seems that the "view/hide" behaviour is not properly changed as hiding previous layers still hides the objects in the new layers (which are also hidden when you hide the new layer...?)

**To Reproduce**
Not sure yet but just building some graphs with some simple shapes, connections and little icons seem to provoke this randomly, it has happened several times to me (on different files) but I can't reproduce it on a new file right now

**Expected behavior**
Objects should only react to view/hide setting of the layer they're in

**Screenshots**
https://user-images.githubusercontent.com/20817233/196044942-5682a1b7-972a-4f76-91ca-a72a2997da12.mp4

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.4.1

**Desktop (please complete the following information):**
 - OS: W11
 - Browser Brave Latest Version

**Comment by mararad** [comment]
Do you see the same issue in other browsers and Incognito mode? 
Please check all the browsers diagrams.net supports https://github.com/jgraph/drawio

If browser change doesn't help, include the diagram file so we can test it.
