### ISSUE TITLE
when dragging pagination to sort, the header becomes blank

### ISSUE THREAD

**Issue by shawon1220** [jgraph/drawio#3112]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
when dragging pagination to sort, the header becomes blank.

**Expected behavior**
https://app.diagrams.net/

**Screenshots**
![image](https://user-images.githubusercontent.com/10345404/196328712-09f12a5c-d175-4c40-be15-10c4ec170901.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.4.0

**Desktop (please complete the following information):**
 - OS:  window11
 - Browser chrome
 - Version 106.0.5249.119

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release. See https://stackoverflow.com/questions/73972272/google-chrome-106-draggable-causing-elements-to-disappear

**Comment by davidjgraph** [comment]
Fixed in 20.4.2
