### ISSUE TITLE
Request: Move sub tree when tree is folded

### ISSUE THREAD

**Issue by keenfoong** [jgraph/drawio#3113]
**Is your feature request related to a problem? Please describe.**
When I fold a tree, I will sometimes move it around to another appropriate spot. However if I move it around I will lose the tree descendant positioning relative to the parent.

**Describe the solution you'd like**
- Perhaps a property that sets Tree moving as the default behaviour. Or:
- A property that allows only the folded sub tree to move.

**Describe alternatives you've considered**
- Grouping might work but it's a little janky to use.
- Always use the "Move subtree" icon. However if I forget to use it, the tree structure will be messed up. Or, 
- Using containers. Might work, but will have to change the sub-tree visual format for the other trees I'm using.

**Additional context**
A video displaying the issue.
https://user-images.githubusercontent.com/31301148/196436180-eba2e375-44fa-4b05-ae20-19bcf6ab406e.mp4

**Comment by davidjgraph** [comment]
Fixed in 24.0.6.
