### ISSUE TITLE
Customizable keyboard shortcuts

### ISSUE THREAD

**Issue by Zbigniew-Kaleta** [jgraph/drawio#3114]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Some functions I frequently use have no keyboard shortcut.

**Describe the solution you'd like**
I would love to see a window, where you can choose any option from the menu (including submenus), e.g. "Export as PDF" and assign a shortcut that is not used by other option. Removing built-in shortcuts could also be an option.

**Describe alternatives you've considered**
Another option would be a customizable toolbar with a button for every operation you frequently use.

**Comment by mararad** [comment]
In order to have all under one roof please vote/comment the feature request I have re-opened https://github.com/jgraph/drawio/issues/1654
