### ISSUE TITLE
Pressing "cmd" on macOS in Safari in drawio diagram opened from Confluence scrolls up and left

### ISSUE THREAD

**Issue by tomor** [jgraph/drawio#3116]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The canvas scrolls up and left when touching "command" key on macOS in Safari which makes usage of any shortcuts (CMD+C, CMD+V) difficult.

**To Reproduce**
1. Open a draw.io diagram via ~Jira~ Confluence plugin
2. Draw a shape on the canvas
3. Click on the canvas
4. Click on 'command' key
5. See the problem that it has scrolled up and left ( the object jumped down and right)

**Expected behavior**
Pressing "command" key alone doesn't scroll the canvas

**Screenshots**
<img width="2543" alt="Screenshot 2022-10-19 at 14 32 10" src="https://user-images.githubusercontent.com/1484739/196692556-8da31497-4702-4992-8521-7b1e60ca8e78.png">

**draw.io version:**
- draw.io version [e.g. 11.0.1]

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser: Safari
 - Version 16.0 (17614.1.25.9.10, 17614)

**Additional context**

**Comment by WolfScholle** [comment]
I have a feeling that this is related to a used iframe 🤔 We are facing a similar issue. It's really nasty when using shortcuts. Even worse when trying to make consistent screenshots 😅

**Comment by mararad** [comment]
Do you have the same issue in other browsers and Private mode with all browser extensions temporarily disabled?

**Comment by davidjgraph** [comment]
The title says Jira, the environment Confluence, which one is it? 

What other apps are installed?

**Comment by tomor** [comment]
I'm very sorry. It's confluence. I've fixed it now.

**Comment by tomor** [comment]
I'm not a confluence admin, so I don't know which other plugins are installed.

**Comment by davidjgraph** [comment]
It's probably worth submitting a ticket to support@draw.io or asking your Confluence admin to do so. We'll help you faster that way and we can ask for details that aren't suitable for posting online.

**Comment by davidjgraph** [comment]
This was fixed in draw.io for Confluence 11.0.5
