### ISSUE TITLE
Configuration option to block "pop ups" from draw.io

### ISSUE THREAD

**Issue by fariazz** [jgraph/drawio#3119]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
In our self-hosted version, our users see this popup prompting them to download something else from an external website. We don't want to send our users to an external website:

![image](https://user-images.githubusercontent.com/1313597/197115251-f882cc19-9627-4f5d-ab2c-7b61c586c933.png)

**Describe the solution you'd like**
Configuration setting to disable this popup.

**Describe alternatives you've considered**
Injecting CSS to hide them.

**Additional context**
We operate in a very regulated environment in which we cannot be sending data to other domains and cannot send users to third-party websites. We already have our instance with configuration `lockdown: true` , so it is frustrating to still see prompts to third-party sites.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
