### ISSUE TITLE
Add an export command line

### ISSUE THREAD

**Issue by olivbau** [jgraph/drawio#312]
As #196 add some command line,
Is it possible to add an export command line ?

For example something like:
draw.io --input myDiagram.xml --output myDiagram.jpg --zoom 100 --borderwidth 10
draw.io myDiagram.xml myDiagram.jpg --zoom 100 --borderwidth 10

It would be really helpful !

**Comment by AlexandreRio** [comment]
Really nice idea, what would be even better:
being able to "select" layers to export and specify the size of the image to export.

**Comment by davidjgraph** [comment]
Command line export is in the desktop build, https://github.com/jgraph/drawio-desktop/releases/tag/v10.7.5
