### ISSUE TITLE
Edit Roundness

### ISSUE THREAD

**Issue by EhudKirsh** [jgraph/drawio#3122]
Hey,

I am a big fan of diagrams.net/draw.io.

When I edit a rectangle, I can edit the roundness manually, but not on the right side by reading and writing the SVG rx and ry values. Can you please allow editing the rx and ry values directly on the right in the Style tab?

Thanks 😊

**Comment by egrimate** [comment]
Please describe in more detail what kind of rectangle are you thinking of. Is it a standard rectangle from the sidebar, a SVG rectangle or an imported one?
