### ISSUE TITLE
BUG: Confluence Cloud: Background of all drawio diagrams are now grey

### ISSUE THREAD

**Issue by mawid6** [jgraph/drawio#3123]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Starting today (Monday Oct 24th) it seems that the background of all diagrams on confluence cloud is now grey. For the previous years, it has always been white, which blends with the rest of the confluence page. I suspect this is a bug of some sort.

**To Reproduce**
1. Go to your confluence cloud install with drawio.
2. Click on a page with drawio diagrams.
3. Scroll down to a few diagrams, observe background.

**Expected behavior**
Background of diagrams (where background color has not been changed explicitly) is white.
**Actual**
Background of diagrams (where background color has not been changed explicitly) is grey.

**Screenshots**
![image](https://user-images.githubusercontent.com/77722885/197497118-76553157-c746-43be-98e4-68860ac33cee.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.5.0

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19042.2130]
 - Browser chrome Version 
 - Version 106.0.5249.119 (Official Build) (64-bit)

**Additional context**

1. I noticed that diagrams shown on page with simple viewer still has white background.
2. I tested and explicitly set the background color of a diagram to white (which I never do, normally), and it was respected - the background was indeed rendered as white. But setting all backgrounds explicitly to white would be rather time-consuming ;-)

**Comment by alderg** [comment]
Fixes in 20.5.1. Please visit https://ac.draw.io/clear.html to force an update.

**Comment by mawid6** [comment]
Yes, it looks great again - thanks alot!

**Comment by mawid6** [comment]
Hmm, @alderg - it seems that the grey background returns after a while.

The example I've found: If I go into edit mode the problem is there again, and it seems to stay, so that exiting edit, it is then back in view mode as well.

I've tried clearing cache several times, and it does alleviate the problem, but edit will bring it back.

**Comment by alderg** [comment]
What version do you see in the editor?
