### ISSUE TITLE
First text is always English

### ISSUE THREAD

**Issue by Jungeol** [jgraph/drawio#313]
When input Korean text in object, First text is always English.
![draw issue](https://user-images.githubusercontent.com/11795576/45066370-11fdef80-b0f9-11e8-8ad8-70f82286a299.PNG)
os: windows 10
browser: chrome v68.0.3440.106

**Comment by Yulight1401** [comment]
it's same in macOS, and chinese.

**Comment by davidjgraph** [comment]
What input source do I use to test this?

**Comment by mararad** [comment]
When a shape is selected and text is typed, the first letter is English but when you double click a shape, see a cursor and start typing, all letters are Korean.

Win 10, Chrome Version 74.0.3729.131 (Official Build) (64-bit) and draw.io 11.1.2
![koreantext](https://user-images.githubusercontent.com/44292306/62701478-b14ff480-b9e4-11e9-883a-ed5fb8226fb5.gif)

**Comment by yunnysunny** [comment]
https://github.com/jgraph/drawio/assets/734818/daa10a10-0698-4ae6-9d8e-c910cde77247

I met the same problem. I use Microsoft Pinyin IME to input Chinese, the first time I try to write `shi` , but it only show `hi`. Then I clean the input characters and try again, it works OK.

**Comment by davidjgraph** [comment]
Fix in 29.5.3
