### ISSUE TITLE
Ctrl + Shift + Y works only with one selected shape

### ISSUE THREAD

**Issue by vbccbz** [jgraph/drawio#3136]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The Autosize's hotkey CTRL+SHIFT+Y only works with single highlight object.

**To Reproduce**
1. Place two shape and write some text. 
2. Select both. 
3. Press CTRL+SHIFT+Y
4. See nothing.

**Expected behavior**
Doing Autosize.

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 20.3.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 
**Additional context**
If you press Autosize icon with multiple highlighted objects - this work fine.

**Comment by alderg** [comment]
Fixed in 20.3.1
