### ISSUE TITLE
From Text : Proposal for adding new functionality 

### ISSUE THREAD

**Issue by guylifshitz** [jgraph/drawio#314]
I would like to add more features to the "From Text" option since I need to use this feature for a project and the current system doesn't offer enough functionality. 

Basically I want to be able to import a diagram similar to this [https://d2slcw3kip6qmk.cloudfront.net/marketing/pages/chart/seo/ERD/discovery/erd-example.svg] 

I was thinking of going based off of PlantUML's format [ http://plantuml.com/object-diagram ] as a basis. But I will probably modify it slightly. I need to actually modify the objects afterwards so the current import of PlantUML is not sufficient.

Any thoughts or comments ?

**Comment by alderg** [comment]
Please send PR as plugin like https://github.com/jgraph/drawio/blob/master/src/main/webapp/plugins/sql.js
