### ISSUE TITLE
Small caps in text

### ISSUE THREAD

**Issue by edemaine** [jgraph/drawio#3140]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I would like to be able to write "x NOR y" where NOR is actually small-caps, like this: 
![image](https://user-images.githubusercontent.com/2218736/199128315-bf0497cf-4b35-4eec-a085-0bf0ed2f4489.png)

**Describe the solution you'd like**
There are already buttons for bold, italic, underline, strikethrough, subscript, and superscript. I'd like another button for small caps.

**Describe alternatives you've considered**
The current workaround is to write the small-caps text with capital letters, select it, and manually decrease its font size. This results in something like this (sorry, slightly different font): 
![image](https://user-images.githubusercontent.com/2218736/199128373-234ce579-2ecb-4076-9726-5eb2f756fbb8.png)

But some fonts have actual small-caps variants. [Wikipedia](https://en.wikipedia.org/wiki/Small_caps) says "Well-designed small capitals are not simply scaled-down versions of normal capitals; they normally retain the same stroke weight as other letters and have a wider [aspect ratio](https://en.wikipedia.org/wiki/Aspect_ratio_(image)) for readability."

**Additional context**
I tried manually editing an SVG file to add `<span style="font-variant: small-caps">`, but this wasn't preserved when loading with diagrams.net (perhaps unsurprisingly).

**Comment by stilobique** [comment]
Agree with this feedback. However, all typo can't support this feature, maybe it's an issue.

**Comment by davidjgraph** [comment]
Best to use math typesetting for this, it has the largest range of formatting. Can also use HTML if you're familiar with the syntax.
