### ISSUE TITLE
The working sheet goes invisible when Ctrl is pressed on active sheet in chrome browser

### ISSUE THREAD

**Issue by amitbhatia1** [jgraph/drawio#3142]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I press Ctrl key on web version of https://app.diagrams.net/ on Chrome browser, the active window shrinks, whereas the same issue is not happening on Edge browser.

**To Reproduce**
1. Go to 'https://app.diagrams.net/' 
2. Press Ctrl key on your keyboard
3. You will see the active page becomes invisible.

**Expected behavior**
Well, I expect, sheet should stay visible. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1165670/199305212-3f1797d9-5638-41a0-b195-8507d56134c7.png)

- draw.io version [20.5.1]

**Desktop (please complete the following information):**
 - OS: Windows 10 (64-bit
 - Browser : Chrome
 - Version : 107.0.5304.88 (Official Build) (64-bit)

**Additional context**
This is a blocker.

**Comment by davidjgraph** [comment]
I cannot repeat this, does it happen in an incognito window? Have you fully detailed your environment?

**Comment by amitbhatia1** [comment]
I rechecked in incognito mode. Its working fine there. Do I need to clear cache?

**Comment by amitbhatia1** [comment]
Okay, I have solved it. It is this chrome extension "TextCortex - AI writing assistant" that was causing the problem.
