### ISSUE TITLE
Page Duplication due to svg creation bug

### ISSUE THREAD

**Issue by JBRO8081** [jgraph/drawio#3143]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

Duplication of all the subpages while reimporting the SVG file generated by draw.io. The issue will not go away even if you create a new document and try to import the SVG then all the pages from the original draw.io is replicated. My findings was that the draw.io generated svg file contains information about all the pages even though the information about the single page is requested by the user. And on reimporting draw.io is not able to distinguish this information. If u edit and remove this extra data the import work fine. This issue is similar to #2550 and can be reproduced in google drive and windows versions (I didn't check other OS)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to daw.io and create a document with multiple pages.
2. Export a page as SVG.
3. Reimport the SVG file(Any page). 
4. See the duplication of the pages.

**Expected behavior**
Importing an SVG file generated by draw,io should not recreate the existing pages on importing.

- draw.io version 20.5.1

**Comment by davidjgraph** [comment]
That is the correct behaviour for the four steps in your reproduction case. If you import a diagram into an existing diagram you are adding it. There is no way we can know whether it's the same diagram or not.

**Comment by JBRO8081** [comment]
Ok got it. You can disable this by unticking "Include a copy of my diagram" while exporting.
