### ISSUE TITLE
BUG: dev mode `https://github.com/jgraph/drawio/blob/v20.5.0/src/main/webapp/js/embed.dev.js`  code last line missing '})'

### ISSUE THREAD

**Issue by fionafanfan** [jgraph/drawio#3146]
### bug  drawio dev mode 

dev mode `https://github.com/jgraph/drawio/blob/v20.5.0/src/main/webapp/js/embed.dev.js`  code last line missing '})'

**Comment by davidjgraph** [comment]
It's not a complete JS file, there's no reason to load this file.
