### ISSUE TITLE
Export SVG with CSS responsive Light and Dark themes

### ISSUE THREAD

**Issue by AdamCoulterOz** [jgraph/drawio#3147]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I use drawio for a lot of technical documentation in source control. I export to the SVG format and reference the images in markdown files. With the advent of light/dark modes, my diagrams often become unreadable in dark mode. There is no way to have an exported diagram change between light and dark.

**Describe the solution you'd like**
You've clearly put a lot of work into the light/dark editing in drawio. When I switch between light and dark in the drawio app, the colours used for my diagram invert and I can clearly see the diagram. Could these "alternate themes" be embedded in the SVG file exports with `@media (prefers-color-scheme: dark) { ... }` CSS styles so your colour invertions can come along for the ride when exported, i.e. the SVG changes to dark based on the browser it's being viewed in? It would be very cool.

**Describe alternatives you've considered**
The workaround is to export my diagrams with a solid white background.

**Additional context**
Example screenshots without changing anything about the diagram itself other than switching between light and dark mode.
<img width="1056" alt="light" src="https://user-images.githubusercontent.com/6822248/199509345-6526a5a1-a6bd-4bac-babe-428ac1ca19eb.png">
<img width="1056" alt="dark" src="https://user-images.githubusercontent.com/6822248/199509358-d966890d-8012-40e0-b916-219308af6b78.png">

**Comment by alderg** [comment]
You can manually add a style in the defs section as described [here](https://github.com/jgraph/drawio-github/blob/master/DARK-MODE.md). We're planning to add an option for this in the SVG export dialog in one of the upcoming releases.

**Comment by AdamCoulterOz** [comment]
@alderg that is awesome, I just manually inserted that `style` section in the `defs` block, and it worked perfectly. Is having this baked into the export function far away?

**Comment by alderg** [comment]
We'll update this ticket when it's added. Can't give an ETA.

**Comment by alderg** [comment]
It has been added to the export dialog:
![Screenshot 2023-09-20 at 09 19 07](https://github.com/jgraph/drawio/assets/921200/a7b2f273-79b5-463a-9ff1-28a62ea35729)

**Comment by AdamCoulterOz** [comment]
@davidjgraph - I've installed the latest version for the last few weeks, I haven't seen it released yet? What commit was it added in?

**Comment by davidjgraph** [comment]
The change in the dialog is there in the core build at version 22.0.5:

<img width="448" alt="Capture d’écran 2023-10-20 à 09 55 22" src="https://github.com/jgraph/drawio/assets/1761087/f9254b99-32da-4bf4-ba36-0cc062bf1658">

**Comment by davidjgraph** [comment]
The commit was https://github.com/jgraph/drawio/commit/ec5dcc298b979150209a3c10388f72de7bdb7eee. The 21.8.0 release.

**Comment by AdamCoulterOz** [comment]
@davidjgraph - that doesn't have the `Automatic` option shown in @alderg's previous post which is the specific feature "responsive" we are talking about. :-)

**Comment by AdamCoulterOz** [comment]
@davidjgraph, what you've referenced is different than what this issue was talking about. The screenshot from @alderg is the actual thing I was looking for.

**Comment by AdamCoulterOz** [comment]
@alderg / @davidjgraph - can I please get an answer regarding this one? because its still not implemented.

**Comment by davidjgraph** [comment]
23.0.2 shows:

<img width="442" alt="Capture d’écran 2024-01-27 à 18 01 53" src="https://github.com/jgraph/drawio/assets/1761087/9d84f071-2974-4ba3-a19e-6992312c641d">

What browser are you using?

**Comment by AdamCoulterOz** [comment]
@davidjgraph desktop on macOS

**Comment by alderg** [comment]
Check Improve Contrast under Extras, Appearance for the option to appear in the Export SVG dialog in draw.io desktop:

<img width="533" alt="Screenshot 2024-02-16 at 09 40 03" src="https://github.com/jgraph/drawio/assets/921200/964fef13-f124-4d3a-a946-eeaffef04198">

**Comment by AdamCoulterOz** [comment]
thanks @alderg, that wasn't immediately obvious, I've been checking regularly for it for ages. I've noticed that this setting isn't remembered when you re-open an exported "theme-automatic.drawio.svg", so when you save it (and it automatically syncs the exported SVG), it loses the automatic part. Can it be persisted to exported file's `mxfile` attributes and read back when reading back in an exported model, so subsequent saves keep it?
