### ISSUE TITLE
Unable to change font size smaller than 12pt

### ISSUE THREAD

**Issue by Timppe** [jgraph/drawio#315]
Title says it all

**Comment by alderg** [comment]
This works for me. What are the steps to reproduce this?

**Comment by Timppe** [comment]
It looks like it's working on my Windows machine today, but haven't tried it on the Mac where this happened. However, how it appeared to me was: I opened up an existing diagram from my Google Drive folder with draw.io, then for some reason one of the elements which had 4pt or something like that, had automatically expanded to 12pt, and I was like "ok..." then I tried to change it back, but it just wouldn't let me, not even with a new element. I have to check it out again this evening on my Mac.

**Comment by Norbert80** [comment]
I just found out that as a work around in addition I need to select the shape and set it to 6pt as well.

**Comment by antonio1475** [comment]
This continues to be an issue both on the web and the Chrome app.
On the Windows app, it's possible but then you don't have Google Drive sync...

**Comment by ofarukcaki** [comment]
On Microsoft Edge, I set my browser's minimum font size to Tiny which is 6px on my browser settings. Now I can use 6px on draw.io

**Comment by bphd** [comment]
> I just found out that as a work around I need to select the shape and set it to 6pt as well.

This is a workaround, not a fix. This don't justify case closing

**Comment by Norbert80** [comment]
I cannot reproduce this issue anymore with build "diagrams.net 14.9.6". Can you guys also confirm that it works now with recent builds?

**Comment by bphd** [comment]
15.8.6 here and it doesn't work

**Comment by Norbert80** [comment]
> I experience the issue that the line height stays at about the size of 12pt if I decrease the character size smaller than 12 pt. This leads to two problems:
> 
>     1. There are big gaps between the lines of multi-line text.
> 
>     2. The text is not aligned properly relative to it's shape.

I had to delete my last comment. This issue still exists. Build "diagrams.net 14.9.6" Linux/Ubuntu is still affected.

**Comment by Tsingv** [comment]
Hi~ I unchecked the "Word Wrap" and "Formatted Text" property and my font size could smaller than 12pt now.

**Comment by johntellsall** [comment]
Still seeing this in 2024. Unchecking `Formatted Text` worked for me... but now there's a font size at the Object and the Text layer? Confusing.

**Comment by bphd** [comment]
> Hi~ I unchecked the "Word Wrap" and "Formatted Text" property and my font size could smaller than 12pt now.

Workaround, needs to be default to be a solution. Needs to be re-opened
