### ISSUE TITLE
SVG Weblink

### ISSUE THREAD

**Issue by Gerd88** [jgraph/drawio#3151]
* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I created a svg file with a web link using draw.io.
The web link for the SVG file can be opened with a mouse click.

When I import the SVG file into Dokuwiki, the web link is recognized, but it only works with a right mouse button click and the Open link in new window command.
Is it possible that this can also be opened with a mouse click?
Thanks for the help.

**Describe the solution you'd like**
The SVG Weblink should be opened with a mouse click.

**Describe alternatives you've considered**
non
**Additional context**
non

**Comment by alderg** [comment]
Please add a link to the Dokuwiki page with the diagram.

**Comment by Gerd88** [comment]
https://dimondo.synology.me/dokuwiki/bruchawiki/doku.php/Brucha%20Wiki
BN:test
PW:test

**Comment by alderg** [comment]
<img width="1044" alt="Screenshot 2022-11-05 at 12 51 56" src="https://user-images.githubusercontent.com/921200/200118497-4c9de7da-9322-4be4-8c68-a9ec29afa159.png">

This is a file: link which is blocked by the browser for security reasons (see https://www.technewstoday.com/not-allowed-to-load-local-resource/).

**Comment by Gerd88** [comment]
Is it possible to fix this for every user who log in?

**Comment by alderg** [comment]
This is a browser limitation, you'd have to ask the browser vendor.

**Comment by Gerd88** [comment]
Outside of dokuwiki it works without problems.
