### ISSUE TITLE
Enter Chinese and display garbled characters

### ISSUE THREAD

**Issue by suzhouhu** [jgraph/drawio#3156]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Enter Chinese and display garbled characters！

**To Reproduce**
When I open the page:
http://jgraph.github.io/drawio-integration/localstorage-svg.html
Then enter an image at random, and then enter a string as shown in the figure:
![1](https://user-images.githubusercontent.com/23079693/200147988-6198804f-9c15-4835-95ae-5d42e0f6e85c.png)
Then click the save button！

![2](https://user-images.githubusercontent.com/23079693/200148031-1746c3c6-1206-405f-aca7-d6a54fe6e56d.png)
![3](https://user-images.githubusercontent.com/23079693/200148044-01d75a00-1534-4a81-9371-c86c2be3d74f.png)

**Comment by davidjgraph** [comment]
That is not a page in this project.
