### ISSUE TITLE
an abused third-party chrome extension ?

### ISSUE THREAD

**Issue by bear-shen** [jgraph/drawio#316]
sorry for my english ... 
recently i downloaded a extension from chrome webstore , [draw.io Desktop](https://chrome.google.com/webstore/detail/drawio-desktop/aeeogemjbfojkdbabkhfiddigbhibhik?utm_source=chrome-ntp-icon)
now every time i access any website, it would insert a [script](https://s3.amazonaws.com/js-static/1d1461ebcc7f16695c.js) and 3 statics to [extcoolmake.xyz](http://extcoolmake.xyz/), when i turned this extension off, it disappears ...
i'm not sure what is it ...

**Comment by davidjgraph** [comment]
This isn't ours, see the author. We don't produce any browser extensions.

**Comment by ocdtrekkie** [comment]
@bear-shen The Chrome Web Store is a cesspool of malware. I strongly advise not using any extensions in Chrome.

@davidjgraph It'd probably be good to report malicious uses of your code and brand though.

**Comment by davidjgraph** [comment]
We've tried multiple time, they won't remove anything unless we have a trademark on "draw.io".

**Comment by ocdtrekkie** [comment]
@davidjgraph You'd think the fact that it's adware that injects malicious advertising into random websites the user visits would be reason enough for Google to act, but malware makes Google a lot of money, it seems. :|

**Comment by davidjgraph** [comment]
Just way too big and they under-resource everything except search and cloud platform. Chrome Web Store has been DOA for years.
