### ISSUE TITLE
fonts.google.com is blocked following 20.5.2 release

### ISSUE THREAD

**Issue by rglennperry** [jgraph/drawio#3162]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
ERR_BLOCKED_BY_RESPONSE when trying to access fonts from drawio, configured within a confluence cloud instance.  

**To Reproduce**
1. Go to 'New Draw.io Board or Draw.io drawing within a confluence '
2. Place text and attempt to set font to Architects Daughter (missing in list) 
3. Configure custom font as Google name = Architects Daughter (apply)
4. Note font is not what was specified
5. Return to font config.  Click google font help icon. 
6. Observe ERR_BLOCKED_BY_RESPONSE

**Expected behavior**
Architects Daughter is default for draw.io board.  It should not have disappeared as an available font and it should be possible to configure google fonts

**Screenshots**
The font appears to be set to AD, (perhaps from cache?) but after click away or save, the font reverts to local system font. 
![image](https://user-images.githubusercontent.com/74622787/200271553-f76b57be-5354-4768-a1ff-7c26375c9b8f.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [20.5.3]

**Desktop (please complete the following information):**
 - OS: [windows10]
 - Browser [chrome]
- Confluence cloud

**Additional context**
<img width="453" alt="Capture" src="https://user-images.githubusercontent.com/74622787/200272018-fe2e08a3-5193-40b6-bc89-9b6b5ae9d26f.PNG">

**Comment by mararad** [comment]
I tested this in Chrome Version 107.0.5304.88 (Official Build) (64-bit), Win 10 and draw.io 20.5.3 and I see Architects Daughter listed as default.
Please open browser console (Ctrl+shift+j), open the drawio editor and click the dropdown. Take a print screen and attach it here. Then navigate to Network tab, download/export HAR file and attach it also.

If you wouldn't like to attach files publicly, feel free to submit all the details to https://drawio.atlassian.net/servicedesk/customer/portal/14/group/15/create/49
