### ISSUE TITLE
Opening a Diagram File from Google Drive Results to Getting Stuck at the Loading Screen

### ISSUE THREAD

**Issue by iron59** [jgraph/drawio#3163]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I have a diagram file that is stored under my Google Drive account and up until 2 weeks ago, I can open it just fine. However, when I try to open the file now, I'm getting stuck in the loading screen. 

**To Reproduce**
1. Go to 'Google Drive Folder where the diagram file is located'
2. Double Click on 'the diagram file'
3. Stuck in loading screen instead of loading the diagram

**Expected behavior**
The corresponding diagram should load.

**Screenshots**
![Diagrams_Net_Loading_Issue](https://user-images.githubusercontent.com/4161244/200307570-19692631-2cc7-4db6-9098-1fbc05622f45.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version  107.0.5304.88 (Official Build) (64-bit)

**Additional context**
If I clear the cache of diagrams.net, the issue is resolved. However, once I try to open the diagram file again, the issue will re-occur until I clear the cache.

I checked the error in the browser console and here's what it says:

> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src https://www.dropbox.com https://api.trello.com 'self' https://viewer.diagrams.net https://apis.google.com https://*.pusher.com 'sha256-avuoixynoo/05kdljyp0aobe+gt/ke1/vh2ps+yfqes=' 'sha256-r/ilw7kmsjxeo9eyqctzzyct0pz9ghn1blgki7vpr+a=' 'sha256-5dtsb5mj34lxcef+hfwbblef49xxjaknwgdwa/utwqa=' 'sha256-vs/mxlvd7nby7anv+0t1ap338uf7vrcs7y23kjerhkc='". Either the 'unsafe-inline' keyword, a hash ('sha256-vS/MxlVD7nbY7AnV+0t1Ap338uF7vrcs7y23KjERhKc='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by davidjgraph** [comment]
Try closing all diagrams.net tabs then opening app.diagrams.net/clear.html. Try again after that.

**Comment by iron59** [comment]
> 

Thanks for the quick response. I tried your suggestion, closing all instances of my browsers just to be sure. I was able to open the diagram file once after clearing but after that, the issue still re-occurs.

**Comment by davidjgraph** [comment]
Any errors in the browser console?

**Comment by iron59** [comment]
I forgot to add the console error in my browser. I updated my post to add this. Thank you.

**Comment by davidjgraph** [comment]
Why do you have an inline script executing, do you have a browser extension injecting it?

**Comment by iron59** [comment]
Hmm none that I know of. The only extensions I have installed recently is the playlist searcher for youtube. I doubt it will affect diagrams.net app in any way.

**Comment by iron59** [comment]
> Does it with extensions disabled?

I tried to disable all extensions but the issue still persists and the issue points out to the same lines as seen in my screenshots in my previous reply. For what it's worth, issue 1366 seems to be reporting a similar issue with the similar time of occurrence as mine though the OP did not mention any further details.

**Comment by davidjgraph** [comment]
3166 could be literally anything, there's no detail in the report at all.

Do different browsers work?

**Comment by iron59** [comment]
> 3166 could be literally anything, there's no detail in the report at all.
> 
> Do different browsers work?

Tried it in Firefox and it seems to work just fine.

**Comment by iron59** [comment]
Ok copy. Thank you. I'll try to investigate further and just post here if ever I find a solution. I just find it weird that diagrams.net will work just fine in my chrome browser as long as I clear its cache beforehand.
