### ISSUE TITLE
Rack not scalable

### ISSUE THREAD

**Issue by szwedoman** [jgraph/drawio#3164]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Rack cabinet diagram is not resizeable

**To Reproduce**
1. Select rack cabinet
2. Resize it
3. Resize is not working

**Expected behavior**
Rack can be resized

**Screenshots**
![image](https://user-images.githubusercontent.com/7964864/200340830-fa6ea3fd-9c98-43d1-ab88-1eb8f5371d66.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.5.3

**Desktop (please complete the following information):**
 - OS: WIN10
 - Browser Chrome
 - Version 107.0.5304.88

**Comment by kenm-4682** [comment]
This is still an issue; the expected behavior can be seen in the video embedded on this page at 2-3sec

**Comment by egrimate** [comment]
In the next release, there will be a rack shape where vertical size determines the number of units.

**Comment by davidjgraph** [comment]
This went into 21.0.6
