### ISSUE TITLE
Confluence Cloud: Simple viewer broken?

### ISSUE THREAD

**Issue by mawid6** [jgraph/drawio#3167]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Simple viewer seems to not work. 

**To Reproduce**
1. Go to confluence cloud install with drawio plugin
2. Edit any embed or drawio macro to use simple viewer

**Expected behavior**
Diagram is displayed.

**Actual**
Diagram gets the browser "image not found" icon (whatever it is actually called).

**Screenshots**
![drawio-confl-simple-viewer-issue](https://user-images.githubusercontent.com/77722885/200593523-efb5ffae-726f-4847-babc-c136476898f1.gif)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.x.x.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome latest

**Additional context**
Tested on both embed and diagram macro with same result.

**Comment by davidjgraph** [comment]
Any errors in the browser console?

**Comment by mawid6** [comment]
Hello!
OK, so I've checked and saved the logs. There are some errors that appear for any action on the page (refresh, etc) - but for the specific action - when I change to simple viewer and then save/publish - there is a `GET` for a `.png` that gets a `404`.

Log:
```
viewer-1-4-42.html:1 Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://ac.draw.io/') with script ('https://ac.draw.io/service-worker.js'): The user denied permission to use Service Worker.
kp-rms-workflows.drawio-d3f4ebba6011f5178306675d528282acf95b039b.png:1          GET https://i-p-e-x.atlassian.net/wiki/download/attachments/36213424287/kp-rms-workflows.drawio-d3f4ebba6011f5178306675d528282acf95b039b.png?api=v2 404
Image (async)
showDiagram @ viewer.js:447
startViewer @ viewer.js:1967
(anonymous) @ viewer.js:288
b._handleResponse @ all.js:58
f._receiveMessage @ all.js:19
stable_vendors.EPyqmQVCgN.js:2 [Violation] 'setTimeout' handler took 66ms

```

Image of that log:
![image](https://user-images.githubusercontent.com/77722885/202189371-fcf2cc5d-03c3-4fd5-8a9d-e017fb629c25.png)

**Comment by mawid6** [comment]
For your _reference_ - here are the logs for all actions, with some error messages that appear throughout, so not sure how or if they impact. The 404 above seems to be the cause in the end, but maybe something here has a relationship to it...

* [REFRESH_PAGE_i-p-e-x.atlassian.net-1668603742763.log](https://github.com/jgraph/drawio/files/10021938/REFRESH_PAGE_i-p-e-x.atlassian.net-1668603742763.log)
* [OPEN_DRAWIO_EDITOR_i-p-e-x.atlassian.net-1668603853502.log](https://github.com/jgraph/drawio/files/10021939/OPEN_DRAWIO_EDITOR_i-p-e-x.atlassian.net-1668603853502.log)
* [OPEN_DRAWIO_MACRO_PROPERTIES_DIALOGUE_i-p-e-x.atlassian.net-1668603930266.log](https://github.com/jgraph/drawio/files/10021945/OPEN_DRAWIO_MACRO_PROPERTIES_DIALOGUE_i-p-e-x.atlassian.net-1668603930266.log)
* [CHANGE_TO_SIMPLE_VIEWER_AND_SAVE_i-p-e-x.atlassian.net-1668603969590.log](https://github.com/jgraph/drawio/files/10021947/CHANGE_TO_SIMPLE_VIEWER_AND_SAVE_i-p-e-x.atlassian.net-1668603969590.log)





Image of the log for refreshing the page:
![image](https://user-images.githubusercontent.com/77722885/202189699-81db4bd2-a94a-4129-8cd8-fdfdd0212c07.png)

**Comment by davidjgraph** [comment]
See if the 20.6.0 works any better, but that sounds like the browser has the permissions set pretty tightly to refuse service workers to run. I think this means the browser has "block third-party cookies" enabled. Can you try with that off?
