### ISSUE TITLE
Enhance offline mode : Remove hard-coded reference to diagrams.net

### ISSUE THREAD

**Issue by fizard77** [jgraph/drawio#3171]
* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

Given that Draw.io is installed on an internal corporate network server that cannot join the domain diagrams.net  (Because not connected to the Internet or under a security policy that prohibits access to domains related to interactive web applications).

Then the stand-alone viewer (`viewer-static.min.js`) cannot be used because of hard-coded references to `viewer.diagrams.net`

**Describe the solution you'd like**

On setting `GraphViewer.prototype.imageBaseUrl`, replace `"https://viewer.diagrams.net/"` with `window.DRAWIO_BASE_URL` 

**Describe alternatives you've considered**
I  patched my forked version.

**Additional context**
none

**Comment by davidjgraph** [comment]
You need to change https://github.com/jgraph/drawio/blob/dev/src/main/webapp/js/PreConfig.js with your values.

**Comment by fizard77** [comment]
Thank you for your answer.
Yes, I had changed it with my values, but I also had to replace an explicit URL by the global var, for fixing some broken image links :

(in line 4071 in the minified file)
`GraphViewer.prototype.imageBaseUrl="https://viewer.diagrams.net/";`
replaced by :
`GraphViewer.prototype.imageBaseUrl=window.DRAWIO_BASE_URL+"/";`

**Comment by davidjgraph** [comment]
Fix in 21.3.4

**Comment by image72** [comment]
how to self-hosted 
  - `viewer.diagrams.net`
  -  `embed.diagrams.net`

what different from `viewer.diagrams.net` `app.diagrams.net`
