### ISSUE TITLE
embedded mode disables theme

### ISSUE THREAD

**Issue by benchonaut** [jgraph/drawio#3172]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Embedded plugins offer a theme which is requested via get param:
/?embed=1&offline=1&stealth=1&libraries=1&ui=dark&lang=de&spin=1&proto=json
but dark wasn't working , trying 
/?embed=0&offline=1&stealth=1&libraries=1&ui=dark&lang=de&spin=1&proto=json
showed the dark ui 

**To Reproduce**
1. iframe or enter the URL `/?embed=1&offline=1&stealth=1&libraries=1&ui=dark&lang=de&spin=1&proto=json`
2. iframe or enter the URL `/?embed=0&offline=1&stealth=1&libraries=1&ui=dark&lang=de&spin=1&proto=json`

**Expected behavior**
ui switch respected in embed mode

**draw.io version (20.5.x/latest):**

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by davidjgraph** [comment]
Released in 20.8.0
