### ISSUE TITLE
Add oracle icons

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#3173]
https://docs.oracle.com/en-us/iaas/Content/General/Reference/graphicsfordiagrams.htm

**Comment by jbirk-oracle** [comment]
Wanted to make a point I might not have mentioned yet: This isn’t so much a one-time ask as it is initiating an ongoing relationship. We plan to update the icon set about twice a year for the foreseeable future as we add new services.

**Comment by davidjgraph** [comment]
There's been no interest in these, apart from Oracle. For low demand icons the best route is to host the set somewhere and build a link that allows users to easily open the set.

However, with no votes in 15 months, this issue is declined.

**Comment by jbirk-oracle** [comment]
I just have to say: this was an incredibly bad experience on our side. We approached you wanting to engage and create a relationship. There was practically zero response other than creating this issue. No guidance whatsoever on how to advocate for ourselves was provided or what the basis for any decision would be, and nobody showed the slightest interest in meeting us even part way much less half way. Over a year later, it gets closed with zero discussion.  Is this how you treat AWS?
