### ISSUE TITLE
Tables can be edited after locking them

### ISSUE THREAD

**Issue by Matthew2000** [jgraph/drawio#3174]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
After locking a table the rows can still be moved and resized.

**To Reproduce**
1. Create a table.
2. Lock the table.
3. Resize and move the rows.

**Expected behavior**
You should not be able to resize or move elements in a table when locked.

**draw.io version:**
- draw.io version 20.5.3

**Desktop:**
 - OS: Windows 10
 - Browser Chrome
 - Version 107.0.5304.89

**Comment by mararad** [comment]
Reproduced in Chrome, Chrome Incognito and FF in 20.5.3, Win 10

Table is added via Table icon in the toolbar, selected whole and locked via Edit > Lock and in another test case right mouse click > Lock.
Even locked, rows and columns are still movable and text can be added.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by davidjgraph** [comment]
Internal commit https://github.com/jgraph/drawio-dev/commit/ed408c17a3c83379c37ff26c66247b726af8d2e3
Internal release https://drawio.atlassian.net/projects/DS/versions/11231/
