### ISSUE TITLE
Outside border with rectangle causes issue for editing inside

### ISSUE THREAD

**Issue by berkdemir** [jgraph/drawio#3176]
Hi,
I have tried to explain the issue below.
To create a page template like the one shown below, I need a rectangular outside of the page. When I do that, anything in the rectangle becomes "not touchable" because I always choose rectangle if I click there. The only workaround is hiding that. Any solution for this problem? Anybody else using the page template like this?
![image](https://user-images.githubusercontent.com/40423004/201352732-f1e93bae-2f64-4900-af69-7717e22a8a3a.png)

**Comment by alderg** [comment]
Uncheck pointer events under Properties in the Style panel.
