### ISSUE TITLE
Embed - HTML error: Failed to execute 'serializeToString' on 'XMLSerializer'

### ISSUE THREAD

**Issue by Inversion-des** [jgraph/drawio#3177]
### Preflight Checklist

* [x] agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I do File - Embed - HTML, and choose "Public URL of the diagram" — there is a problem the resulting snippet doesn't work. 
It always fails with an error:
`Failed to execute 'serializeToString' on 'XMLSerializer': parameter 1 is not of type 'Node'.`

**Expected behavior**
The diagram should be loaded. This export for this file worked for me some time ago.

**draw.io version:**
- 20.5.3

**Additional context**
I found that the snippet does a request:
```
https://viewer.diagrams.net/embed2.js?&fetch=https%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D1aF7xgHkYU5kZfWriDrQN1l5bzBgrDWOg%26export%3Ddownload
```
and the result from the server should contain the content of a diagram file, but instead, there is an empty string inside `decodeURIComponent` call:
```
GraphViewer.cachedUrls['https:\/\/drive.google.com\/uc?id=1aF7xgHkYU5kZfWriDrQN1l5bzBgrDWOg&export=download'] = decodeURIComponent('');
```
Later this string is parsed as an XML and fails with the mentioned error.

**Comment by mararad** [comment]
Could you attach a print screen showing the error or if possible video showing all the steps and the result?
At the moment I am not able to reproduce the issue

**Comment by Inversion-des** [comment]
Embedding settings
![image](https://user-images.githubusercontent.com/1228795/202804800-6b66c5a5-f3d7-4661-a8ec-e149ba9e7afc.png)
Then I download a result file, rename .txt to .htm and open in the browser.
Result:
![image](https://user-images.githubusercontent.com/1228795/202805052-a90bbd55-84f2-4dfe-b5b8-57a1d5e140f3.png)

**Comment by davidjgraph** [comment]
How do you open the HTML file in the browser? Directly from the file system? That won't work, needs a web server.
