### ISSUE TITLE
in mobile client 20.5.3 self-host can't display mobile view

### ISSUE THREAD

**Issue by jonesjedi** [jgraph/drawio#3179]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
i pack the new version(20.5.3) for self-host drawio. but when i use mobile devices, the drawio display not right.

**To Reproduce**
1. use mobile devices browser to view drawio service

**Screenshots**
<img width="518" alt="image" src="https://user-images.githubusercontent.com/158714/201674282-f1605038-9d46-47ac-9470-87fd6e5cef2c.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.5.3

**Comment by alderg** [comment]
We only force mobile UI on our on domains using line 299 ff in Init.js. Add your domain or your own check.
<img width="925" alt="Screenshot 2022-11-14 at 15 36 07" src="https://user-images.githubusercontent.com/921200/201687370-29c899c3-d007-4085-b1e9-0265347155a1.png">
