### ISSUE TITLE
Cannot save diagrams to GitHub

### ISSUE THREAD

**Issue by PierreLouisPAUGAM** [jgraph/drawio#3185]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Impossible to save a diagram to a github repo.

**To Reproduce**
1. Go to https://app.diagrams.net
2. Click on 'Github'
3. Follow instructions to connect to your Github account and allow access to a particular repo
4. Go back to https://app.diagrams.net
5. Create a new diagram
6. Select the desired repo on github
7. See "Ok" button grayed out

I tried on both Chrome and Edge, I also tried clearing the cache.

**Expected behavior**
The "OK" button should be clickable and save the diagram in the repo

**Screenshots**

![Capture d’écran 2022-11-17 122809](https://user-images.githubusercontent.com/58030198/202434702-cb142e10-36e9-45e0-a42a-ea3632a26c96.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [20.5.3]

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome and Edge

**Comment by davidjgraph** [comment]
Works for me, do you have the drawio app configured with access to that repo?

**Comment by louiswholoveswork** [comment]
same issue to me.

**Comment by alderg** [comment]
The repository https://github.com/PierreLouisPAUGAM/Draw.io is empty. You cannot save to an empty repository. Please initialize the repository first.
