### ISSUE TITLE
Unknown error : Uncaught TypeError: Cannot read properties of null (reading 'CodeMirror')

### ISSUE THREAD

**Issue by palangProgrammingMan** [jgraph/drawio#3187]
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/95007545/202595399-86656820-d60c-457d-86a2-2c39018db506.png">

I have this issue after edit this diagram. 17 Nov can edit with no problem but 18 Nov in the morning when i was edit some "Text" this error always pop up and cannot edit that "Text"

**Comment by LuuKhoaHoc** [comment]
Me too :<

**Comment by davidjgraph** [comment]
That isn't code in the drawio codebase, check whether you have an extension intefering.

**Comment by sueasueasuea** [comment]
After I removed Blackbox extension, it was fixed the error.

**Comment by MuhammedResulBilkil** [comment]
> After I removed Blackbox extension, it was fixed the error.

I had the same issue and this solved my problem 👍
