### ISSUE TITLE
Automatic widgets creation through .csv files

### ISSUE THREAD

**Issue by gokul1906** [jgraph/drawio#319]
can i add the link of a widget from my custom library to the csv data below.
![image](https://user-images.githubusercontent.com/43469894/45881751-c1a9b180-bdc9-11e8-9af8-e587b9a06e02.png)

**Comment by davidjgraph** [comment]
For usage questions, please submit to https://groups.google.com/forum/#!forum/drawio. Issues are for development issues only.
