### ISSUE TITLE
draw.io replicates the shape on the other side when drag an arrow line from it

### ISSUE THREAD

**Issue by varadharajaan** [jgraph/drawio#3190]
- create rectangle shape
- click on the shape and drag the arrow line out of it
- when release the arrow pointed to one side, it replicates the shape what was created on the origin side

this is very annoying that i have delete the shape everytime to use only arrow. 

attached an image in which only box and arrow to be expected but i am getting another box on the right side by default.

**Comment by varadharajaan** [comment]
<img width="1679" alt="Screenshot 2022-11-20 at 11 58 33 AM" src="https://user-images.githubusercontent.com/13198892/202889172-9f2810c0-e928-49a1-8d5a-e22867037995.png">

**Comment by alderg** [comment]
Uncheck Extras, Copy on Connect:
<img width="304" alt="Screenshot 2022-11-20 at 07 30 33" src="https://user-images.githubusercontent.com/921200/202889188-1f7bf0a4-b079-4693-87e0-9adbc33b6e58.png">
