### ISSUE TITLE
"Copy as Image" menu doesn't show up in the context menu in the Firefox browser

### ISSUE THREAD

**Issue by hojongs** [jgraph/drawio#3197]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**I can't copy the selected components as an image in the Firefox browser**
I want to copy&paste selected components as an image from the draw.io to out of the draw.io (e.g. Slack, Web browser, Notion, etc)
It can be done by the "Copy as Image" menu in the Chrome browser, but the menu doesn't show up in the Firefox browser.
I already have tried Cmd-C to copy as an iamge, but I just got the formatted text in the Clipboard, instead of the image.

**To Reproduce**
1. Open a new diagram (in the Firefox browser)
2. Draw some components e.g. jsut a rect.
3. Select the rect and right-click, you can see the context menu.
4. "Copy as Image" doesn't show up in the context menu.

**Expected behavior**

"Copy as Image" should show up in the context menu like doing it in the Chrome.

**Screenshots**

- in Chrome
    <img width="475" alt="image" src="https://user-images.githubusercontent.com/15096588/203058171-c5494e08-2b30-46ba-b6c6-226b233fd763.png">

- in Firefox
  <img width="458" alt="image" src="https://user-images.githubusercontent.com/15096588/203058749-cf94b1cf-ec77-4063-adf8-3ab512a65165.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- 20.5.3

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari]: Firefox
 - Version [e.g. 22]: 107.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alderg** [comment]
Unfortunately, Firefox does not support this function.
