### ISSUE TITLE
Shape picker shapes don't stick to swimlane in pool shape

### ISSUE THREAD

**Issue by Bastesque** [jgraph/drawio#3199]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I use one of the pool custom shapes from the _Advanced_ library. I add a shape to a lane, the purple highlight appear, telling me that this shape will be part of the swimlane container. Now I like to go on with the shape picker. I can either hover over the blue arrows to get the reduced shape options (four of them) or click on the blue arrows to get a set of 16 shapes. Both do the job, a new shape gets embedded and connected at the same time. The bug appears when I try to re-arrange swimlanes. If I used the hover-over option, the shapes don't stick to the swimlane/container. If I clicked on the blue arrows, shapes get added to the container. 

**To Reproduce**
1. Go to 'Advanced' library
2. Add pool shape of your choice
3. Add first shape from the library panel to add it to the container
4. Move on with both ways to use the shape picker (hover over or click on blue arrow)
5. Move the swimlane to another location, using the Alt-key
6. See error when you used the hover-over option

**Expected behavior**
Shapes should stick to the swimlane, no matter which option I used to use the shape picker

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.5.3 for Confluence Cloud

**Comment by davidjgraph** [comment]
Internal commit https://github.com/jgraph/drawio-dev/commit/bf75f41d6d787fef35e0e731e781e3dbb82eb4b1
Internal release https://drawio.atlassian.net/projects/DS/versions/11231

**Comment by davidjgraph** [comment]
Fixed in 20.6.0
