### ISSUE TITLE
[Feature Request] Respect shape fill properties when sketch=0

### ISSUE THREAD

**Issue by s0mbieZ** [jgraph/drawio#3201]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I often must create diagrams which will only be printed in pure black/white (no shading). Thus, I must use fill patterns like cross hatching to convey information in the diagrams. I appreciate that you added hatch filling when sketch=0 in response to issue #753. However, other properties, most importantly hachure gap, are not respected when sketch=0. This greatly restricts the ability to convey additional information using hatch patterns when the sketch style is not desired.

**Describe the solution you'd like**
Force shape fills like cross hatch, dashed, and zig-zag line to respect additional properties when sketch=0, most importantly hachure gap, so that the "density" of the fill pattern may be adjusted to convey more information.

**Describe alternatives you've considered**
Using sketch style seems to be the only alternative, but the sketch style causes overlap of the fill patterns over the boundaries of the shape, as discussed in #753. This may be undesirable in many cases.

**Additional context**
Thank you for your work on this application and for consideration of my request.

**Comment by s0mbieZ** [comment]
Do I need to do anything else to get this labeled as feature request?

**Comment by davidjgraph** [comment]
Images showing what you mean in each part would reduce the amount of time it takes to time to process the issue each time we go through all issues.
