### ISSUE TITLE
I can't open any drawio files on diagrams.net

### ISSUE THREAD

**Issue by PrzemyslawRoznowski** [jgraph/drawio#3202]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**
1. Go to 'File->Open Recent diagram'
2. Click on 'sample diagram'
Error loading file : Unknown error
**Expected behavior**
The file shoud open

**Screenshots**
![image](https://user-images.githubusercontent.com/11841827/203530153-acad94ba-f369-47a4-a862-369368eb5b08.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
20.5.3
- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Windows 11
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 107.0.5304.107

**Smartphone (please complete the following information):**

**Additional context**

**Comment by PrzemyslawRoznowski** [comment]
The diagrams worked at least week ego.

**Comment by davidjgraph** [comment]
Where is the diagram stored, can you attach it?

**Comment by PrzemyslawRoznowski** [comment]
It is on OneDrive disk. 
I found the reason - I can't copy file from OneDrive to you. I've realized that something wrong is with OneDrive. 
The files are visible but it is impossible to open them.
I can  close issue.
