### ISSUE TITLE
SVG Import and Export

### ISSUE THREAD

**Issue by ag1909** [jgraph/drawio#3205]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ag1909** [comment]
I'm new to drawio and should set up a simple process chart for a client of mine. After testing drawio I know the app tools fundamentally, but I must import additional SVG graphics, which I did in AI. The problem is, after exporting the final diagram as SVG the SVG-Graphics which were imported externally are no longer part of the new SVG file. Is there a way to get extern SVGs in a diagram in a much better way? I was expecting, that I can ungroup such imported SVGs directly in drawio to edit them. Thanks for your suggestions.

**Comment by davidjgraph** [comment]
This isn't possible, draw.io is not an SVG editor, it's a diagramming tool.
