### ISSUE TITLE
Diagram embedded in Word cannot be edited.

### ISSUE THREAD

**Issue by Neutrino-Sunset** [jgraph/drawio#3211]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Following the instrcutions here
https://desk.draw.io/support/solutions/articles/16000061408-use-diagrams-in-microsoft-word-excel-or-powerpoint

Then selecting the embedded diagram and clicking `Edit Selected`, results in the error message

`No diagrams found in the selection`

**Expected behavior**
The diagram should open in the DrawIo editor for editing.

**Screenshots**

This is Firefox

![image](https://user-images.githubusercontent.com/18445931/204160644-0d0ad624-cdd6-4788-9875-0c28f325ff2a.png)

This is in Edge

![image](https://user-images.githubusercontent.com/18445931/204160796-19249494-dd2d-49b0-bfc5-4e1fb450534c.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

Current web version.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Tested latest Firefox and Edge.

**Comment by 21PIRLO21** [comment]
I had the same problem in Drawio-desktop 21.2.8 with Windows 10 and Office 365.
When trying to modify word crashes and restarts.
The only workaround is to delete and re add the diagram.

**Comment by udif** [comment]
Same here (Office 365)/

**Comment by davidjgraph** [comment]
Duplicate #2527

**Comment by Devyanshi231** [comment]
Hello everyone,
 I am facing the same issue while editing the embedded diagram in word.
Kindly help.
![Draw ioError](https://github.com/jgraph/drawio/assets/147509343/5b130141-bfbb-44fa-ab79-202b44ef3e8e)
