### ISSUE TITLE
draw.io for Notion — missing "Pages" button

### ISSUE THREAD

**Issue by Refzlund** [jgraph/drawio#3212]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The "Pages" button does not always show up. Sometimes it does.

Missing Pages button in top-right bar
![image](https://user-images.githubusercontent.com/21252096/204167646-585f388c-cb78-479f-876e-e361e9eb71e3.png)

**To Reproduce**
1. Install Draw.io for Notion for a chromium based browser
2. Create a Notion database, and inside create a file
3. Insert draw.io via the extension button
4. Make multiple pages
4.b If you failed at it cause the button wasn't there — then you reproduced the issue
5. Navigate around a bit
6. Go back to the Notion file and see if the button is still there
7. -> .4

**Expected behavior**
The button for draw.io pages always shows up so you can create, rename and navigate pages.

**Screenshots**
I'll send a follow-up screenshot of the button next time it shows up

**Versioning**
| Name | Version
| ------- | -----
| Draw IO | 20.6.0
| Vivaldi (chromium-based browser) | 5.5.2805.44 (Stable channel) (64-bit)
| OS | Windows 11 Version 22H2 (Build 22621.819)
| JavaScript | V8 10.6.194.26
| User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
