### ISSUE TITLE
Got an error

### ISSUE THREAD

**Issue by Neha-Ali-Khan** [jgraph/drawio#3213]
![Capture](https://user-images.githubusercontent.com/119319654/204287345-f973f7cf-f810-4b8a-909c-0af7a20b002a.JPG)

I got this issue please help me how to resolve this

**Comment by davidjgraph** [comment]
Submit a bug on this issue tracker, https://github.com/jgraph/drawio/issues/new?assignees=&labels=&template=bug_report.md
