### ISSUE TITLE
Edit text in text shape using iPad does not work

### ISSUE THREAD

**Issue by jmortenk** [jgraph/drawio#3214]
### Preflight Checklist

* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**
1. open app.diagrams.net from ipad
2. start new diagram
3. add text shape
4. double click on the shape to edit text

**Expected behavior**
should be possible to edit the text using your keyboard. 

**draw.io version (In the Help->About menu of the draw.io editor): 20.6.0

**Desktop (please complete the following information):**
 - OS: iPadOS 15.7 
 - Browser chrome 107.0.5304.66, safari 

**Additional context**
Have tried several variations, using sw keyboard, fixed keyboard, pencil etc. without success.

Working fine from my iPhone iOS 16.1.1

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by davidjgraph** [comment]
Internal commit https://github.com/jgraph/drawio-dev/commit/fbc2e8fdb97220231e27d4defeb63cea5bcb577c

**Comment by davidjgraph** [comment]
Released in 20.6.1
