### ISSUE TITLE
License Update

### ISSUE THREAD

**Issue by spectejb** [jgraph/drawio#322]
Can you also update the text in v6.5.6 to be the Apache 2.0 license text? (https://github.com/jgraph/drawio/blob/v6.5.6/LICENSE)

The license title says Apache 2.0 but the text is GPL 3.0. The readme file also says GPL 3.0.

Thanks, in advance, for your help!

**Comment by davidjgraph** [comment]
We don't retrospectively alter releases, if the license is a problem update to a version with the correct file.

**Comment by davidjgraph** [comment]
The title shows the current license of the project, it doesn't changed based on which license file you're viewing.
