### ISSUE TITLE
Blurry png when imported into word

### ISSUE THREAD

**Issue by abhijeetkumarga** [jgraph/drawio#3226]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I export a draw.io diagram as a png to import into microsoft word it shows up as quite blurry. I have tried resizing the diagram, increasing dpi, and also different file formats. 

**To Reproduce**
1. Open any diagram
2. Export as png
3. Import into word

**Expected behavior**
A higher resolution image.

**Screenshots**
![image](https://user-images.githubusercontent.com/44560999/205752472-83605bde-fc74-450b-a70d-99e0d0af44c7.png)

**draw.io version (In the Help->About menu of the draw.io editor): 

- draw.io version 20.6.0

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: Version 108.0.5359.94 (Official Build) (64-bit)

**Comment by alderg** [comment]
Try exporting with 200% zoom:

![Screenshot 2022-12-06 at 07 30 57](https://user-images.githubusercontent.com/921200/205838155-fe350c5b-423b-459d-af11-9ca76c050fc5.png)

**Comment by abhijeetkumarga** [comment]
I have tried increasing zoom and have tried multiple icnrements between 200% - 900%, I think there is something more fundamentally wrong here.
