### ISSUE TITLE
New DrawIO app on Mac doesn't support multiple tabs.

### ISSUE THREAD

**Issue by starzhanganz** [jgraph/drawio#3227]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
After I upgraded to the latest DrawIO app on Mac (downloaded from https://www.diagrams.net/), lots of functions have lost.
i.e. can't create multiple tab, just few menu options are available.
<img width="955" alt="image" src="https://user-images.githubusercontent.com/84754386/205755657-54c82a40-3c10-40e5-b66a-ec1f4aed82ce.png">

**To Reproduce**
1. Create a new pape
2. You can't find a way to create a new tab like the web version.

**Expected behavior**
below is a tab function I want that is only available from the web version, but not the app.
<img width="195" alt="image" src="https://user-images.githubusercontent.com/84754386/205755874-c61cdc27-7c83-4a46-b75b-c04168b0194f.png">

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [v20.6.0]

**Desktop (please complete the following information):**
 - OS: [Mac Ventura 13.0.1]
 - Browser [ Chrome]
 - Version [107]

**Comment by davidjgraph** [comment]
Exactly where did you download 20.6.0, what was the URL?
