### ISSUE TITLE
Support file handler in PWA

### ISSUE THREAD

**Issue by povlhp** [jgraph/drawio#3230]
Some users and companies don't want to maintaint he desktop version, but would like users to use the PWA version due to the higher security of it running in a container.

One important thing to make this work seamlessly is file_handler support (i.e. extension mapping to launch the PWA when a file is double-clicked).

This is supported in Chrome and Edge.
https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/handle-files

**Comment by davidjgraph** [comment]
Duplicate #3302
