### ISSUE TITLE
Feature request: Iframe box

### ISSUE THREAD

**Issue by Inogeo** [jgraph/drawio#3232]
* [ x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I would like to add some html content fetched from remote location into drawio in a simple way.

**Describe the solution you'd like**
I would like to be able, in the same way as images, to add a feature allowing user to add an iframe referring to some html content.

**Describe alternatives you've considered**
No alternatives...

**Comment by davidjgraph** [comment]
That's not going to happen on both security and complexity grounds. Shape labels support arbitary HTML, I would look for a solution using those.
