### ISSUE TITLE
Draw io could not open an *.svg from the command line C:\Program Files\draw.io\draw.io.exe "%1"

### ISSUE THREAD

**Issue by denisbeelog** [jgraph/drawio#3235]
**Describe the bug**
Draw io could not open an *.svg from the command line C:\Program Files\draw.io\draw.io.exe "%1"

**To Reproduce**
Open Drawio with the fonction ShellAPI.ShellExecute(0,'Open',pc_selectionner,pchar('"'+strpas(Self.file_to_open_with)+'"'),pchar(ExtractFileDir(Self.file_to_open_with)),SW_NORMAL); with ab Svg file it's not open it.

**Expected behavior**
open the *.svg files by parsin the command line at setup or other extension who is available.

**Screenshots**
![image](https://user-images.githubusercontent.com/88406348/206790049-d9b611ae-c77f-4f2d-8522-4ca50a3cf81c.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
diagrams.net 20.6.1

**Desktop (please complete the following information):**
 - OS: Window 10

**Comment by denisbeelog** [comment]
Exemple of *.SVG files : 
![North America](https://user-images.githubusercontent.com/88406348/206796087-d1596b85-aa59-4e41-b837-432b54a626fb.svg)

**Comment by davidjgraph** [comment]
https://github.com/jgraph/drawio/blob/dev/README.md:

"draw.io is a diagramming or whiteboarding application.... It is not an SVG editing app..."

**Comment by denisbeelog** [comment]
Yes but the open file function display that Draw.io is able to open SVG file, so wwhy not open also an SVG file from the command line.

**Comment by alderg** [comment]
We only open .drawio.svg files which have embedded diagram data. SVG files can only be imported into existing diagrams as images.
