### ISSUE TITLE
Import through postMessage

### ISSUE THREAD

**Issue by VirtualEvan** [jgraph/drawio#324]
Is there any way to get the resultant xml of import functions by sending a postMessage?

I am trying to open importable files in a blank document directly from NextCloud.
I managed to get it by using the loadTemplate App function, but of course I am being cors-blocked when drawio is hosted in a different domain

**Comment by alderg** [comment]
Sending a postMessage to/from where?

**Comment by VirtualEvan** [comment]
From an external app (in this case Nextcloud) to the editor.
Something like
```
editor.postMessage(JSON.stringify({
         action: "import",
         file: //file or url
}), "*");
```
It would allow to import a file without using the interface.

**Comment by alderg** [comment]
Ah so this would be with an existing file open with draw.io running in embed mode in an iframe?

**Comment by VirtualEvan** [comment]
Exactly.
I have been looking through the whole code, but I wasn't able to find anything that could help me to achieve this. Is there something I missed?

**Comment by alderg** [comment]
No, we currently don't support this in the JSON protocol. But for this to be pushed from the outside, there would be an import button in the page that contains the iframe, not in the UI of draw.io?

**Comment by VirtualEvan** [comment]
The goal is to support diferent extensions in NextCloud, so, by opening an example.vsdx file automaticlly creates a example.vsdx.xml blank file, opens it with drawio in the iframe and imports the example.vsdx.

It's a bit weird, but will be easier for the user.

**Comment by alderg** [comment]
Ah, good use case. So another option would be to allow for VSDX (other supported file formats) in the load message?

**Comment by VirtualEvan** [comment]
Yes, that would be even better, it would be loaded with only one message

**Comment by alderg** [comment]
Support for all supported file formats will be added in the load action message in the next release. Please use data:application/vnd.visio;base64,... for VSD and VSDX files.
