### ISSUE TITLE
Cannot use minimal theme in embedded mode

### ISSUE THREAD

**Issue by logitick** [jgraph/drawio#3247]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Using the minimal theme in embedded mode does not work anymore. Some js code seems to be accessing a variable that hasn't been defined yet (see line 299673).
![image](https://user-images.githubusercontent.com/807325/207762981-331f7b5d-17ad-41af-87c9-b4261ac337fd.png)

This is the error I am getting:
![image](https://user-images.githubusercontent.com/807325/207763740-93029226-2970-4f57-ac19-4fe844b0a32a.png)

**To Reproduce**
1. Go to 'https://embed.diagrams.net/?embed=1&proto=json&ui=min'
3. Open the dev tools console

**Expected behavior**
The diagram tool to show up in embedded mode.

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 20.7.2

**Desktop (please complete the following information):**
 - OS:  Pop Os/Ubuntu 22.04
 - Browser: chrome 108.0.5359.71, firefox 107.0

**Additional context**
Including `libraries=1` in the query params works to avoid hitting the line causing the error

**Comment by logitick** [comment]
Apologies for posting a screenshot of the minified code in the bug report. Found the actual code after digging in the codebase:
https://github.com/jgraph/drawio/blob/31d3a5e6c9063c73b388a3e13a9bb26124c7f1b8/src/main/webapp/js/diagramly/Minimal.js#L152

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release. (As a workaround, use libraries=1 in the URL.)
