### ISSUE TITLE
Add "Move to front / to back / forwards / backwards" to the context menu for multiple objects

### ISSUE THREAD

**Issue by mbartelsm** [jgraph/drawio#3248]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Moving objects in the Z axis is a very common task when I am organizing things in the canvas. Right now, I can do it for single objects by right clicking on them, but if I want to move multiple objects, the option is not available.

**Describe the solution you'd like**
Add the options to move objects to front / to back / forwards / backwards to the context menu when multiple objects are sleected

**Describe alternatives you've considered**
Using Ctrl-X followed by Ctrl-V is an option, but that only solves the issue of bringing objects to the front and presumes the clipboard has no important data that needs to be used.

**Pictures**

Single object selection

![image](https://user-images.githubusercontent.com/5376208/207797436-b0497e26-760c-4b5f-90da-a7a015b19d4c.png)

Multi-object selection

![image](https://user-images.githubusercontent.com/5376208/207796483-1684d14d-5386-428e-b3a4-dd48c5006283.png)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by davidjgraph** [comment]
Released in 20.7.3
