### ISSUE TITLE
Add features for wire color options for electric diagrams

### ISSUE THREAD

**Issue by Zonetech123** [jgraph/drawio#3249]
* [y] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [y] I have searched the issue tracker for a feature request that matches the one I want to file, without success.
-----------------------------------------------------------------------------------------------------------------------------------------
**I waste a lot of time ajusting my colored wire in electric diagrams. It would be nice to have extra options for wire colors when building an electric diagram. For exemple:

1) To have the possibility of 2 colors for the same wire. EX: orange/black, Pink/blue. In the attached exemple, I had to superimpose two wire in order to get Rd-Bk wire.** 

![2022-12-15 10_08_14-Diagramme sans nom drawio - diagrams net](https://user-images.githubusercontent.com/120660379/207895839-77b653c1-c14d-4af9-96d0-a1c55c0321b8.png)

**Comment by alderg** [comment]
Thanks for the report. We'll add a "Dashed Wire" shape in the next release.
<img width="364" alt="Screenshot 2022-12-20 at 09 36 18" src="https://user-images.githubusercontent.com/921200/208621831-997bfa3e-d2b0-4a85-b851-65773c29bb1a.png">

**Comment by davidjgraph** [comment]
Released in 20.8.0
