### ISSUE TITLE
[feature request] can we export/publish image urls

### ISSUE THREAD

**Issue by mysterytony** [jgraph/drawio#325]
Hello!

This is a feature request. Maybe it is already a thing or is in the roadmap.

Would it be a good idea that we can export/publish an image (e.g. png) url for a page? Suppose the url is `http://draw.io/abc.png`, then we can embed this url in, say, github markdown. When we later edit the diagram, the url remain unchanged. So, we would just need to refresh the markdown to see the updated diagram, instead of re-exporting the png and update it in the markdown file.

I guess since draw.io doesn't actually host the data. It maybe difficult to implement?

**Comment by alderg** [comment]
draw.io files can be saved with a .png or .svg extension (with embedded XML). In GitHub, you can reference those images via rawgit or gh-pages.
