### ISSUE TITLE
Feature Request: Setup/switch Bottom Tabs to be Layers for Same Page

### ISSUE THREAD

**Issue by CMS009** [jgraph/drawio#3250]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when working with layers.

**Describe the solution you'd like**
Setup/switch bottom tabs of "Page 1", "Page 2", etc. to be Layers for same page.  Page 1 would be the "Background" layer.  Then, much like the layer floating window, use the tabs, instead, to control layers and visibility.  This may help users with editing the correct layer (or the layer they thought they were editing).

**Describe alternatives you've considered**
The current floating window for layer management.

**Additional context**
![draw io page-tabs](https://user-images.githubusercontent.com/48506277/207924628-25e64743-e4c6-463a-97a6-7361aa257ad8.PNG)

![draw io layers-window](https://user-images.githubusercontent.com/48506277/207925279-318d5c9f-6ecc-48e0-8bbf-ad7d1cb187bc.PNG)

![draw io layers-tabs](https://user-images.githubusercontent.com/48506277/207925450-105a36a7-17c6-4ee2-a6a7-4daedecf3a2c.PNG)

**Comment by davidjgraph** [comment]
Voting is performed by marking a thumbs up on the original post. Lots of +1 comments don't scale.

**Comment by terefang** [comment]
any updates when this feature will be available ?

**Comment by terefang** [comment]
not stale
