### ISSUE TITLE
Chromium: link labels background incorrect sized when embedded in hidden iframe

### ISSUE THREAD

**Issue by sp-schoen** [jgraph/drawio#3252]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I embed my own drawio instance into another page with an iframe. When the style of this iframe is set to "diplay: none", so that it is not visible to the user, the rendered diagram has an error at the background for link labels (Not regular labels). The svg rect used for this is sized 2px by 1px, not the size of the text. So it is effectively no visible.
This is a problem, because I export this diagram to an svg via the JS messaging API and the same error is then in the exorted svg. The problem does not occur in firefox.

**To Reproduce**
1. Embed drawio with the url parameters 'offline=1&https=0&math=0&embed=1&proto=json&spin=0&stealth=1&chrome=0&drive=0' through an iframe into another website. Use 'style="display: none"' to hide it.
2. Load a diagram with labelled links with the JS messaging API
3. Use dev tools to inspect the content of the iframe. The rectangles belonging to the link labels will have width=2 and height=1. It will also be the same in the exported svg file (Also done with the JS API)

**Expected behavior**
At least in the exported file the sizing of the link label background rectangles should be according the the text size of the label.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- 20.5.3

**Desktop (please complete the following information):**
 - OS: Linux and Windows 10
 - Browser: Windows: Edge, Chrome; Linux: Chromium
 - Version: Edge 108.0.1462.46, Chrome: 108.0.5359.125, Chromium: 108.0.5359.98

**Additional context**
A workaround for now is to hide the iframe with 'style="visibility: hidden; height: 0px; width: 0px"'

**Comment by alderg** [comment]
This is a known issue as we're using element.clientWidth to measure text. Try using visibility=hidden or width=0 instead of display=none.

**Comment by davidjgraph** [comment]
Closing, workaround provided.
