### ISSUE TITLE
The GCP templates use out-dated icons

### ISSUE THREAD

**Issue by kumar-dhanagopal** [jgraph/drawio#3254]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The GCP templates in the `/main/webapp/templates/cloud/gcp` directory use out-dated icons.

**To Reproduce**
1. In draw.io, choose File > New
2. In the Search pane, expand Cloud, and click GCP.
3. Select any of the available 12 templates.
4. Click Create.

The template shows product cards with the older icon versions.

**Expected behavior**
The GCP templates should use the current product icons.

**Screenshots**
The following screenshot shows the template with the old icons at the top, and a revised template with the correct icons at the bottom.
![gcp_template-old_icons](https://user-images.githubusercontent.com/28403513/208209395-d477c094-b5fd-4121-a072-f5d2c476f62a.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.7.3

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 108.0.5359.98

I would be happy to help update all the templates if required. Please let me know.

**Comment by egrimate** [comment]
These will be updated in the next release

**Comment by davidjgraph** [comment]
In 22.1.6 release.
