### ISSUE TITLE
Support diagram styles customization under "Style" tab

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#3255]
Support diagram styles customization under "Style" tab when nothing is selected.
Asked in DID - 6941
![image-20221212-120707](https://user-images.githubusercontent.com/44292306/208405682-1de1ea5b-bc8e-437d-a3e2-369c3c62464d.png)

**Comment by alexfoo-productions** [comment]
Hi, is this the same meaning as the question I am raising in here?

[https://github.com/jgraph/drawio-desktop/discussions/1254](https://github.com/jgraph/drawio-desktop/discussions/1254)

**Comment by davidjgraph** [comment]
It might be, but this is the right project to report editor issues.
