### ISSUE TITLE
Google drive integration not working on self hosted version v20.7.4 (get redirect to https://app.diagrams.net/<folder>/)

### ISSUE THREAD

**Issue by Pammetje** [jgraph/drawio#3260]
Hi,

I run the latest draw.io/diagrams.net (v20.7.4) war file on my own webserver (FreeBSD with Tomcat 9)
I host the draw.io webapp on a url like this https://www.ownwebserver.com/draw/
Everything works fine except the Google Drive integration.
When I click the Google Drive button, it redirects to https://app.diagrams.net/draw/ resulting in error "Error: Not Found"

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
