### ISSUE TITLE
Hi, I want to ask some question about developing plugin.

### ISSUE THREAD

**Issue by Yelixing** [jgraph/drawio#3263]
I download the drawio source code , and i don't really know it can develop plugin before. I want to develop a plugin like this guy
 https://github.com/sakazuki/step-functions-draw.io/issues

First question is :
I compile and run drawio sourcecode local . When I try to change some word like   'Edit data' and I use webstorm search global with word sensitive mode  'editData'  and though I delete those function contains 'editData' but the page still shows it . Is it running using min.js instead?  Is there a switch to turn into  developer mode instead of using min.js ?
I change into 
// Changes paths for local development environment
		if (true || urlParams['dev'] == '1')
and it doesn't work.

Second question is:
The link given upside is not able to plugin in appDiagram.com now . I tried twice. Can u try it? And if it really doesn't work . Is that any plugin instead? In fact , I want to use drawio as a frontend interface and make some backend job. And I'm in headcache about making this hard work. As I'm not so familiar with your developer eco. Is that someone did this job before?

Third question is:
I cannot judge plugin or directly change source code which is better. Is that any doc to detail show how to develop plugin ?

**Comment by Yelixing** [comment]
Will first question is not a question any more . I found the dev mode in index.html.

**Comment by Yelixing** [comment]
Will , first question i have found the suitable answer. 
```
if (location.hostname == 'localhost' || location.hostname == '127.0.0.1') {
                drawDevUrl = `http://${location.host}/draw/`;
                geBasePath = `http://${location.host}/draw/js/grapheditor`;
                mxBasePath = `http://${location.host}/draw/mxgraph`;
                mxForceIncludes = true;
            }
```

**Comment by Bhardwaj-Sahil** [comment]
How to run the source code on your local. Actually I take clone of draw.io but when i try to run index.html .But not able to load the editor
