### ISSUE TITLE
With props plugin: Text cannot be added or edited to objects

### ISSUE THREAD

**Issue by jnachtigall** [jgraph/drawio#3264]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
With the `props` plugin loaded one cannot double click on objects to add text anymore. Without the `props` plugin it works as expected.

**To Reproduce**
1. Permanently add the `props` plugin as described at https://www.diagrams.net/doc/faq/properties-plugin
2. Restart
3. Add any object, e.g. a `rectangle`
4. Double click on the object

**Expected behavior**
Without the the `props` plugin a cursor appears and one can now add a text to the object. With the `props` plugin no cursor appears and it is not possible to add text. I really like the `props` plugin but would still like to add text. 

Also happens for already existing object that already have text – one cannot edit/change this text anymore when double click. That is, on double click the existing text is highlighted but on typing nothing happens. Only if one changes the cursor position with left/right arrow key, then the text becomes editable. Very strange.

This is not restricted to diagrams.net but also occurs in the desktop app.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 
20.7.4

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Firefox
 - Version 101

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by davidjgraph** [comment]
Released in 20.8.0
