### ISSUE TITLE
Page tabs no longer movable via two finger scroll

### ISSUE THREAD

**Issue by bjohas** [jgraph/drawio#3265]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

It seems that drawio has had the UI updated. I am unsure whether this bug is related. However, in the old UI, with many page tabs open, so that there is an overflow, it was possible to scroll along the tabs bar with two fingers (eliminating the need to use the < and > buttons at the right). However, with the new UI this is no longer possible.

**To Reproduce**

1. Create a new doc
2. Create many pages, so that the 'page bar' overflows.
3. Chat that you can now move the 'page bar' left/right with the < and > buttons
4. Try to move the 'page bar' using a 2-finger swipe.

**Expected behavior**

I would expect the 'page bar' to move left/rigth, responding to a 2-finger swipe.

**draw.io version (In the Help->About menu of the draw.io editor):**

20.7.4

**Desktop (please complete the following information):**
Ubuntu 22.04 LTS

Chrome Version 108.0.5359.124 (Official Build) (64-bit)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by bjohas** [comment]
Amazing, thank you!

**Comment by davidjgraph** [comment]
Released in 20.8.0
