### ISSUE TITLE
.VSD file Import failing

### ISSUE THREAD

**Issue by VirtualEvan** [jgraph/drawio#327]
UPDATE: Looks like it is not a release problem
> After the release 9.2.2 or 9.2.3 (I am not sure) implementing the way to import files using postmessages #324 everything was working fine.
> 
> Yesterday I moved to 9.2.7 and found that .vsd files are being cors-blocked even when using the "import from device" option in the UI (same error with postmessages)

![image](https://user-images.githubusercontent.com/12986551/47083635-84daaa00-d211-11e8-8801-b146b7c06d32.png)

**Comment by VirtualEvan** [comment]
Looks like it's not a problem with versions, but with the [convert.draw.io](http://convert.draw.io) server.

**Comment by davidjgraph** [comment]
Yes, there was an issue with the vsd export servers, that should now be resolved.
