### ISSUE TITLE
Buggy window with no title bar and no way to resize

### ISSUE THREAD

**Issue by ebousse** [jgraph/drawio#3271]
**Describe the bug**

Under Fedora 37 (GNOME 43.2), the window of draw.io 20.7.4 (installed as a Flatpak) is wrongly displayed without any proper title bar, like this:

![image](https://user-images.githubusercontent.com/5868014/210799152-bcfd7ef3-76ce-4919-b553-c8b847f67b2c.png)

The consequences are that:
(1) I cannot move the windows by dragging the title bar,
(2) I don't have any top-right buttons to maximize, reduce, close,
(3) If I move my cursor in the bottom right, I cannot resize the window.

**To Reproduce**
1. Start draw.io

**Expected behavior**
The window should have a proper title bar and frame, and offer the aforementioned mouse controls (move/resize/close).

**draw.io version (In the Help->About menu of the draw.io editor):** 20.7.4
**Desktop:** Fedora 37

**Additional context**

I'm certain this was working before, but I can't define exactly "before" (previous GNOME version? previous draw.io version?)

**Comment by davidjgraph** [comment]
We're not the author of the flakpak distro, I would check with them.
