### ISSUE TITLE
Share Button for OneDrive / SharePoint Online redirects to wrong URLs

### ISSUE THREAD

**Issue by ciis0** [jgraph/drawio#3273]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.
  * There is #1859, but with less information than this Issue.

**Describe the bug**

When saving diagrams to a shared library (i.e. not personal OneDrive), the links generated by the Share Button are incorrect.

**To Reproduce**
1. Create a new diagram in a shared library (Note I use `"oneDriveInlinePicker": false` config)
2. Click on "File" &rarr; "Share"
3. A new tab opens, but SharePoint responds with "Bad Request" (if saved in library root) or `404 NOT FOUND` (when saved to a sub-folder)

**Expected behavior**

The link should "open" the file SharePoint Online / OneDrive Web.
("open" = show the "no preview available" page which you can "close" and see the folder the file is saved in.)

**Screenshots**

![image](https://user-images.githubusercontent.com/16290850/211034386-9cf51c96-17ba-498d-ab0f-a5e0c7589bf1.png)

Saved to root folder (note the `/Copy%2/` in the URL):

![image](https://user-images.githubusercontent.com/16290850/211034905-1f8591c0-648b-4d78-8e8c-b10fc0ef51eb.png)

If you remove the `Copy%2/` it works as expected:

![image](https://user-images.githubusercontent.com/16290850/211036327-8d42563b-01c4-4e7c-95f7-db8675a5aeb1.png)

Saved to `drawio` subfolder (note the `/drawi/` in the url)

![image](https://user-images.githubusercontent.com/16290850/211033669-08643c02-b692-442d-abe2-a0f6998352e6.png)

if you remove the `drawi/` it works as expected:

![image](https://user-images.githubusercontent.com/16290850/211035830-b590d78e-6d13-4ea4-9f32-2bcc53994498.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

20.8.1

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser Firefox
 - Version 108.0.1

**Additional context**

N/A

**Comment by m-mohamedin** [comment]
Will be fixed in the next release
Thanks for the report

**Comment by ciis0** [comment]
Seems to work on diagrams.net now, thank you!

**Comment by ciis0** [comment]
this seems to be broken again. :/

**Comment by ThomasIAm** [comment]
> this seems to be broken again. :/

Yes, now after removing the "0" in the following example it works.
`https://company.sharepoint.com/sites/siteName/Shared%20Documents/0/Forms/AllItems.aspx?id=/sites/siteName/Shared%20Documents/path/Untitled%20Diagram.drawio&parent=/sites/siteName/Shared%20Documents/path`

**Comment by davidjgraph** [comment]
That's fine, a new issue is better.
