### ISSUE TITLE
constrainChildren causes collapsed group resize to mess up contained cells

### ISSUE THREAD

**Issue by adamfk** [jgraph/drawio#3274]
First of all, thanks for open sourcing a wonderful project! It's amazing and I love the ability to add plugins :)

### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
if `mxGraph.constrainChildren` is enabled, resizing a collapsed group causes the contained cells to be squashed and moved around. See gif.

I realize this might not matter to you because it doesn't look like `constrainChildren` is used much in diagrams.net, but thought I would submit the issue anyway.

**To Reproduce**
See gif below with exact steps.

1. enable `constrainChildren` on mxGraph
2. collapse a group that has content inside it
3. resize the group
4. expand the group
5. notice that group contained cells have been moved and squashed

**Expected behavior**
The group's contained cells should not be moved or squashed.

**Screenshots**
![drawio-contrainChildren-bug](https://user-images.githubusercontent.com/274012/211136733-c6baf332-5cad-4aff-ad91-b8445009fdc9.gif)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.8.3

**Desktop (please complete the following information):**
 - Windows
 - Chrome
 - Version 108.0.5359.125 (Official Build) (64-bit) (cohort: Stable)

**Comment by davidjgraph** [comment]
Fix in 21.8.0.
