### ISSUE TITLE
Can't Open Files from Dropbox

### ISSUE THREAD

**Issue by dmuth** [jgraph/drawio#3282]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

Attempting to open a file from Dropbox through the web app shows an error that says "Seems like this widget is not configured properly.".

**To Reproduce**

- Go to File -> Open From -> Dropbox

**Expected behavior**

Dropbox to prompt me to connect.

**Screenshots**

![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/374060/211945682-1899cd85-71cd-4832-a78c-cc47562513dd.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- The Web-based version, 15.8.6

Thanks,

-- Doug

**Comment by mararad** [comment]
Hi,

Seeing the version and the print screen you attached, I would like to check if you are using diagrams.net
Is it possible to record a video showing all the steps and the result with diagrams.net version shown under Help menu?

Thanks,

**Comment by dmuth** [comment]
Hi, I just tried again, but this time I was unable to reproduce the issue--I was able to open a file from my DropBox folder with no issue.  So I guess that leaves us these possibilities:

1) Temporary issue with DropBox
2) Temporary issue on your end
3) Temporary issue on my end
4) Something got changed/fixed on Dropbox's end
5) Something got changed/fixed on your end
6) Something got changed/fixed on my end (I did update Chrome since...)

I can try again next week and see ifI can reproduce it again.

-- Doug
