### ISSUE TITLE
Authorizing Google Drive Connection for Diagram Embed Going to 401

### ISSUE THREAD

**Issue by ylanmuller** [jgraph/drawio#3283]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
After authenticating to a Google account through the embed link and authorizing it to access my Drive files, instead of embedding the content, it goes to a HTTP ERROR 401 page. This is specifically happening in Notion. 

**To Reproduce**
1. Open Notion
2. Enter /embed and copy and paste the Notion embed link generated in diagrams.net
3. Click the Authorize button
4. Sign in to Google account and authorize access to Google Drive scopes
5. Receive "This page isn't working" 401 error in Chrome.
6. Notion embed shows an "Error: allow poo-ups to avoid this dialog" even though I have pop-ups enabled in browser

**Expected behavior**
The expectation is that it would redirect back to Notion and proceed with embedding the content

**Screenshots**
<img width="882" alt="image" src="https://user-images.githubusercontent.com/22859458/211949344-d5a89b7f-28a5-4668-9a0d-495296b1fe55.png">

<img width="876" alt="image" src="https://user-images.githubusercontent.com/22859458/211949369-7a23404c-94ae-4644-b1a5-a4331239500f.png">

**draw.io version (In the Help->About menu of the draw.io editor):**
diagrams.net 20.7.4

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: MacOS 13.1
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22]: 108.0.5359.124

**Comment by xinatcg** [comment]
I have been confused by the 401 error long time, the easy fix is to create a new profile then connect will be successful. But it will happen after using some time until the login expired. 

I have tried to remove all data from the profile, but it doesn't work. 

I cannot always use this way to resolve the issue as I have lots of plugins. If can find some clue what the reason led to the issue will be better. 

Currently, I use a simple profile to work on diagram.net, it is not so convenient, but it is the only reasonable way for me. 

Based on my guess, the reason may be the domain name changed from draw.io to diagram.net. I believe I never encounter 401 on draw.io. but it happens frequently on diagram.net.

**Comment by Vetrarr** [comment]
I have the same problem and it only works with the chrome extension. With the google drive as the storage device in diagram.net, If i try to edit the diagram in notion i have to connect to my google drive in a new window and it doesn't change anything. But it is already connected for the viewer part of goole drive and i can see the diagram but not edit it ...

**Comment by krishna-hrytos** [comment]
I am still facing this issue and I also see that it is declined. Will there be a fix or is there a workaround?

**Comment by davidjgraph** [comment]
It's unlikely you're facing exactly the same problem as the OP (though, not impossible). You are welcome to post a new issue.

**Comment by krishna-hrytos** [comment]
No. it is the exact same problem as the OP

**Comment by TomVa-eng** [comment]
I do have the same issue, with latest macos and the macos desktop  app...
I don't have the issue when opening the page in chrome directly oÔ

**Comment by mlippens** [comment]
Same issue... how hard is this to fix? seems like it has been open for a while now, it makes draw.io unusable in notion

**Comment by alderg** [comment]
Try clearing the cookies for `viewer.diagrams.net` also check out [draw.io for Notion](https://chromewebstore.google.com/detail/drawio-for-notion/plhaalebpkihaccllnkdaokdoeaokmle)

<img width="614" alt="Image" src="https://github.com/user-attachments/assets/81f08453-cb5d-40bf-992f-b7f0bcf857b5" />

**Comment by TomVa-eng** [comment]
Cleaning cookies does not work

**Comment by dolfandringa** [comment]
Why has this been closed as "Not planned". It is a bug, not a feature request. I am having the same issue too.
