### ISSUE TITLE
Draw io Notion Chrome extension: Failed to insert

### ISSUE THREAD

**Issue by r-sniper** [jgraph/drawio#3284]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
For the first time I have installed drawio for Notion extension.
On a notion page, I click on Extension -> Insert Diagram
After a few seconds, I get an error: "Failed to Insert. Please reinstall and try again"
I have tried reinstalling, but still same error

**To Reproduce**
1. Install extension on Chrom
2. Open a notion page
3. Click on the drawio notion extension
4. Click on "Insert Diagram

**Expected behavior**
A Drawi.io diagram to be inserted

**draw.io extension version :1.1.2 **

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 108.0.5359.124

**Comment by michaelk2101** [comment]
Have also experienced this across 3 different windows laptops, a Windows server 2016 and Mac, I'd put more version but i've had this problem across multiple devices for multiple months

**Comment by alderg** [comment]
This means the operation for inserting the block and uploading the image failed. If you insert a static image, does the URL of that image in the Notion page start with "/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fc"?

**Comment by alderg** [comment]
As a workaround, you can drop any .drawio.svg file into a Notion page and click for editing. Eg.
![Flowchart drawio](https://user-images.githubusercontent.com/921200/213631081-5f530aed-de31-4505-b885-af407155a35a.svg)
