### ISSUE TITLE
Paste of style on multiple objects doesn't work any more on diagrams.net website

### ISSUE THREAD

**Issue by Jecinda** [jgraph/drawio#3287]
Sorry in advance to how novice this report is. 

**Describe the bug**
Hi there, I looked through the issues but I didn't notice this one so I thought I'd make a bug report to help out. As far as I can tell when I try to paste a style I've copied from one node to multiply it no longer gives the options. I can only paste the style on one object at a time. Whereas it used to do that previously. Maybe it was taken out, maybe it's a bug? I don't know but I thought I'd let you all know.  I have refreshed, logged out and back in, and nothing changed I'm not sure what else I should have done before sharing this. 

**To Reproduce**
1. Copy style
2. Select multiple items
3. Find that pasting style is no longer an option

**Expected behavior**
It used to show the paste style buttons on the right hand window. Same as how it shows when you have 1 item selected.

**Screenshots**
(I don't know how to attach it)
**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]
The about says "20.8.5 "

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version uh... I'm sorry >~<

**Additional context**
uh.. thank you for reading and have a great day.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by Jecinda** [comment]
> Thanks for the report. This will be fixed in the next release.

Happy to help. :)
