### ISSUE TITLE
Incomplete Bottom Fill on Entities Generated from SQL

### ISSUE THREAD

**Issue by LarsHilden** [jgraph/drawio#3288]
An issue has been identified where entities generated from SQL are not fully filled with a solid color when applying a fill color, specifically, there is a portion at the bottom that remains unfilled.

![image](https://user-images.githubusercontent.com/91375961/212560517-d5c8dd89-09ca-45e0-8727-6fe1d1b154c7.png)

**Comment by alderg** [comment]
Fixes since 20.8.0. For existing tables, click the Autosize button in the Arrange tab (or press Ctrl+Shift+Y).
<img width="238" alt="Screenshot 2023-01-16 at 06 32 00" src="https://user-images.githubusercontent.com/921200/212605400-2bcf2472-65d0-469c-9668-41c4f7662072.png">

**Comment by LarsHilden** [comment]
Any information on when the desktop version of 20.8 will be released?
