### ISSUE TITLE
Objects counter list and property add is posible? 

### ISSUE THREAD

**Issue by reproteq** [jgraph/drawio#329]
I think this drawio need counter list of objects used and add property  panel (same colours panel but for propertys).

example:

in panel dragable property array with name-property and values( same color = red, prop1= value1)

and log list , ( custom-forme1 = 3unids, custom-forme2= 9unids , etc)

**Comment by davidjgraph** [comment]
I don't understand this.

**Comment by reproteq** [comment]
please wait and i will make image for you can see idea.
basic drag property panel
and log shapes (items used)

**Comment by reproteq** [comment]
same edit data add property add new value but in new tab and dragable option.
is for fast add property and values

**Comment by reproteq** [comment]
this is photoshop mod not real, only for you think my idea.
i installed all drawio repositori in mi server and try modifi source code but uffff .... more job and not good result. 
i think you can add this in your source code

**Comment by reproteq** [comment]
I am Spanish speaking I will use Google translator to explain my idea.

my father has a fireworks and they are using freehand for years to make fireworks plans.
I thought I could use better drawio but I see that I need to improve some things to be fully functional.

I would need to count all the figures used in each sheet
I would also need to add a list of properties and values.
to do it fast you would have to be draggable and not edit figure by figure.

example :

figura1 = battery 10 guns, caliber 70, kamuro effect

figure 2 = battery 10 guns, 100 caliber, multicolor effect

Figure 3 = 3 cannons fan, 75 gauge, thunder effect



to do this I need to have a panel of dragable properties and values

**Comment by reproteq** [comment]
simple edit data panel tab for add property and values fast method drag

and log shapes sheet

you know?
