### ISSUE TITLE
Window with colour parameters is disapearing after inserting one number 

### ISSUE THREAD

**Issue by Jac00b** [jgraph/drawio#3291]
### Preflight Checklist

* [ X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When i am trying to change colour and try to insert a number window is disappearing and is puting a number i inserted it is a problem to insert more than 1 digit numbers. Screen shot below which window is a problem
![image](https://user-images.githubusercontent.com/56475908/212928843-a5bb1a68-5e0f-45fc-ae22-a16db55a776f.png)

**To Reproduce**
1. Go to colour (marker icon)
2. Click on one of the fields with colour parameter
3.Try to insert a number
4.Window will disappear after inserting first digit

**Expected behavior**
Window shouldnt disappear after inserting first digit

**Screenshots**
![image](https://user-images.githubusercontent.com/56475908/212929396-e0633c1a-4c58-46b7-8e70-2ae5f368579d.png)

- draw.io version 20.8.5

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Newest

**Comment by mararad** [comment]
Thanks for the report.
I reproduced this in Chrome Version 109.0.5414.75 (Official Build) (64-bit) and Chrome Incognito, Win 10.
diagrams.net 20.8.7

The issue appears when the color picker is clicked both in "Fill" and "Line". Numbers can't be added, but letters can. 
It is working when color square is clicked first and then color picker. 

https://user-images.githubusercontent.com/44292306/213498201-05e0dee4-c2af-4235-8a58-e637b7ea0678.mp4

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by davidjgraph** [comment]
Internal release https://drawio.atlassian.net/projects/DS/versions/11256
Internal commit https://github.com/jgraph/drawio-dev/commit/240cbf69d8f5f481b339668bfa7153d08fd223fc

**Comment by davidjgraph** [comment]
Released in 20.8.11
