### ISSUE TITLE
bug - `Exit Group` left disabled when undo action enters a group

### ISSUE THREAD

**Issue by adamfk** [jgraph/drawio#3294]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The UNDO action (CTRL+Z) is capable of entering and exiting groups. If an undo action enters a group, drawio will get confused and leave menu action `Arrange -> Navigation -> Exit Group` disabled. This can leave users stuck inside a group/container (although the keyboard short cuts still work).

**To Reproduce**
1. Enter a group `Arrange -> Navigation -> Enter Group`
2. Exit the group that was entered `Arrange -> Navigation -> Exit Group`
3. Undo action. `Edit -> Undo`. This will put you back in the group.
4. Notice that `Arrange -> Navigation -> Exit Group` is disabled even though we are in the group.

See gif below.

**Expected behavior**
When inside a group/container, `Arrange -> Navigation -> Exit Group` should be enabled.

**Screenshots**
![drawio-undo-group-exit-bug](https://user-images.githubusercontent.com/274012/212993702-b2cb7297-5ff7-40b7-a848-a0adacddaca2.gif)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.8.5

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - 108.0.5359.126 (Official Build) (64-bit)

**Additional context**
A similar thing happens when a group is exited with undo.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by davidjgraph** [comment]
Released in 20.8.8
