### ISSUE TITLE
Mindmap: Automatic arrangement of branches

### ISSUE THREAD

**Issue by lernkurve** [jgraph/drawio#3296]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.
      - Here are [all open issues with the keyword "mind map"](https://github.com/jgraph/drawio/issues?q=is%3Aissue+is%3Aopen+mind+map+)
      - Here is an issue which is similar but it's a bug: https://github.com/jgraph/drawio/issues/957

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
I am always frustrated when I want to rearrange the branches of a mindmap.

1. It's not possible to move a branch from the right to the left side of the mindmap and vice versa. One has to put a lot of manual work into rearranging all sub-branches and leaves.

    See the screenshot below or this [online diagram](https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1#R7Z1tc5s4EMc%2FjV%2FeDQgE%2BGWch%2FZuJjOdtvfQviOg2Nxh8GE5ifvpTwJhQMIxqQ2yw850pkEIMOzubxf%2BEkys6%2BXLh8xfLe7TkMQTZIQvE%2BtmgpBpOYj9x1u2osVAXtEyz6KwaDOqhi%2FRD1J2FK2bKCRr0VY00TSNabRqNgZpkpCANtr8LEufm90e0zhsNKz8OVEavgR%2BrLb%2BFYV0IVpNZ1qt%2BEii%2BUIc2kNusWLpl53FmawXfpg%2B15qs24l1naUpLf5avlyTmF%2B95nW527N298MyktAuG%2FyDv%2F9pOYsP9%2BuX8Psf6Pfbu0%2FxL2IvT368ESd8HyXh0l%2BJ30y35YVYP0fL2E%2FY0mxN%2FYwKU7GDWrNFmkU%2F0oT6MWsxWUPAF6KEZF%2B3K96LZqTYMEv%2FJddpnGasMUnzvYlfQDJKXvaemrm7YMzVSLokNNuyLmID5BRbCCezxOJz3WBIeOKiZiwXCyv6wkvmu13vjvaZeZWfzNlleMPhPE89WLlVeSw%2FpiRLfEpm6SYJ13XbsT9qp1k15RZ9g3WRYl3FrCRk7i4W2dWO6PYziX0apclttaaw%2BBUPp8puJAmlljWZLwuLmdwrgk32RELhERk%2FyXzJ2NmcH3uvxV9z13W6yQLySj9xqdmvnpPX9ue2u1WWX4Kn5o9r85GGwd5qHQus87p1PJ3WscE6r1tnqtM6GKzzunVMQ6d5HMU81%2Bz0M59v%2BFtIfNVYccwqOn6pnxcRJV9Wfn4VnllVyesLuiwrCz%2BO5gn7O2D7I6yKmPHS4o5VdVEyF114y336VDUk5Llm8puJy6zk%2FLfhhdes8pJd08S6qq3f4zlVb3RdLdS8qX13uT%2B1b7vzujdvWXpnfUNu%2F1oX4bGNHs195I73iWQR8wCScQPwC1jfoLnHwgMPbODedC3w9gfF3qoPG1OpDsNq3WcYaiVmGz25vau4%2Fdd0FQWKtx%2Fw8Yooucdngai1sdEWAPzCRuyG5UqsWEZhGFfVdnnXku9qQ9N1sS%2B%2BuBY2s25sCKQLCKTHKI7Lm6cJskKfeI%2BBclvF1jiBRx4eeww9B7uN0Gu9B2qJPNRX5HlK5M0yPwkWEHoQeicJvTShd%2F4yirnDfyTxE%2BGGFyuEj5hILJeRGJJHfxNTJUKr9npEV629Ra0jJUxPTZhuy2MS%2BcnFyaJ2CvkSgvbyCk8LWVL2M%2FRmv%2FJh%2BdHpb73w8%2Be17ALRyI%2BrZ5%2FssqcrcYsbk0cq%2FnxIKU2XZRiKM%2BUrVmmU0Pw08Yz94xY0J%2FiGGxLPzHIJy1WNuN0%2BGLPlcXnoU2b967zjN37wXzE%2Fj8RffU0%2F8R%2FRHsoQvOMN3mbpatmW3iRoqhoMPMtq7g8d%2BSxLbFrwoCqHLNzwBFvehfDuYqvTqzOmKs8AtYHaQO0Oty67WNVG7dGqdyW2DmPbfp%2FYVpXBy8E2MBoY3RejXc88M0aPViXuzminF0a7TvMmy%2FasYRmtCtCXw2gorQHbOrFdanvasK3K6IBtqeOxQ%2BPOFNunknEB24DtsWF7qvs5tqrmjgXbXkdso2MHZZ4nthHIj4BtwHYnbHvT5tgB7dguzwuwvf8S9aM%2Fem5T08AYD4tt0B8B24Dtn8O27ockaLT6Y3mih7Hdj%2F6oHduXrD8CtgHbA2LbNAxpsIB2bo9Wk3S7YrsfSdKRBm1b5cP2obCtSpIw2QEQevYIdV1pqp%2BjeaofGq082JmgfamD0rQXb2CCquogEBQIenkE1T1ZGo1WqetKUKsvoU4vQS1VqAOCAkEvjqCmq5mg1mhFsxIhhxHaj2imHaGqaAYIBYSePUK96bkhdLQCVneE9iRgeRJC0cAIVQUsQCgg9PIQautGqKolQSBBIL3D9w1aBmqEnm26v6rvLhs2%2BFQ9byz1C%2B5avxz7evX2%2BgW5dtMZ3GFfAGCd6DWvusffVC8c7GEITkaYh66ZkT8TkQEMNSFACjj7FNDPey%2FVUqGvzGHKsGh53deweUNVMSFvSB2P%2FbRAe96wTdkVBs4bJ3rdKeQNyBuQN4bOGwbSfcdhq%2BotZA7pEu0x6oVnjvJwkDkgc0DmuLDMYTmm9syhitYjyRxdXzFcZJjTTzqQP1HkdZsrpu5I%2FnSDPOlMBFhvGWi0am3XIYN2P2Kt7vEuNoi1kO4vUKxVBl0bmsVaG8RaCKRRirW45TNTw4beaKVau%2FODk56kWrvpCg4a9l0JNnyRE6B7gdWLjaS4MXUjdLSqZXeE9qNaWl7TFfB0YITCRxoBoe8AodqrUDxa%2Ba4zQnE%2F8p1uhOITyXeAUECoVoQi3QgdrY5VIuQwQq33iVBVfwKEAkLPHqHYPjeEqnoeIFTq2M9YACw%2FFrcGRigIUIDQd4BQe6oboSAnHURoP3KS9ioU5CRA6AUiVLmRx7oROlo5qeuAVPvcB6RiaXyVLb0xvecBqbjtHZZOPtT7gf0x53%2FcvqxIQPNgjgsU3O3W5cQw%2FPxAdMF4YTzkH1Ega96csG2MmPhPxWLG1y%2FTnAvMxMUm3BorcVFouttNPn1C9uUm8A9kB2kkz6MXkKB1JM%2BDh21s9MkNq91ZatgwUQs3nL644bRpKJLVrwK68eNjbb6mUd6vxcLFRJh3YmJcvga%2FTA2OqdvGHd6t2AB4DfdB7K%2FXUbCv2jKKMiXb%2Fj0p5xHli9%2Fq625eGktbsfR2kzXLM%2Bv45PLTsxhqtsQtpizbjs0tZVWxLyV0zS1YKvPt8ovQB3IL8wJ%2FW%2BsmZqntfyKDm8kQOZ7kvcUeT5q4nA4aBrj3m2oicO8zcu8TCTUwVRVu18%2F9dv28pqq%2BXueJ2K%2B%2BfmTrnpTqnGhmGZACSAGk6I0UyNNPikv%2BZl5nbaVrFez0M8LHlMpbq3xL9EDainPJqtrpjdzPbHLkSkZGpzIyW8xSTr2qO8vUi%2Fs0JLzH%2Fw%3D%3D)
![image](https://user-images.githubusercontent.com/74185/213151980-e6725b61-87cb-4e0e-b09c-ecdb542c0243.png)

2. Draw.io doesn't automatically arrange all elements of a branch once they have been created or moved.

   It looks like this with different spacings:
   ![image](https://user-images.githubusercontent.com/74185/213153112-ec5689be-26b6-400b-91ff-c973ea4aadeb.png)

   But it should look like this example from XMind where all sub-branches are constantly rearranged to have equal horizontal and vertical spacings:
   
   ![image](https://user-images.githubusercontent.com/74185/213153308-b5a14bed-4802-49dd-ac96-da8f1e173f66.png)

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
Based on the problem description above:
1. I can move the branches from right to left and all branches and leaves are automatically rearranged to point to the left.
2. I can add new elements to a branch and all existing items get automatically rearranged to have equal spacings and alignments.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._
There is a feature to move an entire branch called "tree moving". That's useful but not enough.
Example: [Reposition mind map trees in draw.io for Atlassian Confluence & Jira](https://www.youtube.com/watch?v=IR9G58KZrgA&list=PLX6xdk86h_0zX9sH2rzwmEovYGkFXFG5O&index=4)
![image](https://user-images.githubusercontent.com/74185/213150648-a3d70411-7da1-49f7-b4c5-bd070988abe0.png)

**Additional context**
It is clear that Draw.io can't have all the features a full-fledged mind mapping application like MindManager or XMind has.

But having a few basic automatic layouting features like the two described above for mindmaps would help so that people who anyway use Draw.io for everything could also draw mindmaps without having to switch to another application.

Thanks a lot for the great product! ❤️

**Comment by JeffreySu** [comment]
@davidjgraph As a mind map, automatic rearrangement is a very important feature. XMind has achieved this, allowing users to focus on content creation rather than wasting time on layout. I hope it can be improved. Automatic layout has already been implemented in some other containers, and I think it shouldn't be difficult.

**Comment by davidjgraph** [comment]
If it's not difficult, submit a PR.
