### ISSUE TITLE
CSV conversion breaks labels when importing to Lucidchart

### ISSUE THREAD

**Issue by Gby56** [jgraph/drawio#3298]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I'm currently using draw.io to convert graph data to a more standard file format, that I can re-use and import into Lucidchart.
So far no issues, I'm able to convert a CSV to a draw.io file format, (XML, no compression)

The CSV options define the `label:` with a value of a column reference, like `label: %column_name%`
The problem is that the exported draw.io file will have entries like that:
```xml
                <UserObject label="%column_name%" column_name="this_is_the_label_value" placeholders="1" id="38">
                    <mxCell style="whiteSpace=wrap;html=1;" parent="1" vertex="1">
                        <mxGeometry x="1350" y="250" width="100" height="30" as="geometry" />
                    </mxCell>
                </UserObject>
```

And it will render wrong in Lucidchart, with just "%column_name%" in place of the label.

Is there a way for me to include the value directly in the XML attribute "label", instead of a reference ?

**Expected behavior**
I'd like to have an option in the csv parser maybe, to inject values directly instead of referencing.

**Screenshots**
![image](https://user-images.githubusercontent.com/6706472/213187792-c2ae2389-2911-439f-afe6-ac5021e2470f.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.7.4

**Desktop (please complete the following information):**
 - OS: macOS ventura

**Comment by davidjgraph** [comment]
This would be an issue for Lucidchart, not us.
