### ISSUE TITLE
dynamic colors

### ISSUE THREAD

**Issue by Rico29** [jgraph/drawio#3301]
I'm using drawIO to describe my backbone architecture. I would lile drawIO to be able to retrieve information (OK / KO) based on a webservice and set-background-color of shapes based on that

**Describe the solution you'd like**
webservice : https://xxx.xxx/getstatus?ID=<SOMETHING>&return_mode=color
the call to this webservice would, for example, return "green" or "red" or "#f6f6f6"

for the item I would like to be able to set "background-color=$(https://xxx.xxx/getstatus?ID=<SOMETHING>&return_mode=color)

Is that something that is already implemented ? is that doable ?
Regards
Cédruc

**Comment by alderg** [comment]
https://github.com/jgraph/drawio-data-driven is all we have currently.
