### ISSUE TITLE
Register draw.io as a file handler with the operating system

### ISSUE THREAD

**Issue by ajoga** [jgraph/drawio#3302]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success. : I'm duplicating #3230 that was tagged with "Issue template not filled" for which the description says the ticket will be ignored as long as the template is not used.

**Is your feature request related to a problem? Please describe.**

Diagrams.net can be used as a [progressive web app](https://www.diagrams.net/doc/faq/offline) and offers and experience very close to the desktop version. In some environment, we can't install desktop applications but PWA are allowed.

This feature request suggest to have Diagrams.net register as a file handler with the operating system so drawio files can be opened with a PWA version of diagrams.net.

In the absence of this feature:

- `.drawio` files are not associated with applications on my desktop ; it means a double-click on it can't open them : 
![image](https://user-images.githubusercontent.com/37543966/213457758-c5648dd3-568c-46f4-ae7c-d10397bb2710.png)

- I must first open the diagrams.net PWA and then open the file from there

**Describe the solution you'd like**

I'd like a feature like the traditionally file association for the desktop client, but for the PWA. Relevant documentations from browser vendors seems to be:

- Edge: https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/handle-files
- Chrom(e?ium?): https://developer.chrome.com/en/articles/file-handling/

**Describe alternatives you've considered**

- Install the desktop client -> I can't in my professional IT environment
- Tried to modify the file association but it seems it's not an option I can have without being the author of the PWA
- Open diagrams.net then open the file, works but could be more efficient

**Additional context**

- This feature request is a duplicate of #3230, but following the template
- As I finish writing this ticket, I notice that as of today, an experimental flag is still needed in Edge to see that feature working which I can't enable ; I looked in the source code to see it this was maybe already implemented but it seems not, as [manifest.json](https://app.diagrams.net/images/manifest.json) does not have a `file_handlers` property.

**Comment by niktekusho** [comment]
Unless there has been updates on the matter, I think this is still relevant.

**Comment by snydergd** [comment]
Could this be re-opened?  Or is it better to create a new issue for it?

**Comment by bahuma20** [comment]
@davidjgraph Please reopen. 

It is still relevant and actionable 🙂

**Comment by Mannshoch** [comment]
Same here. I installed Draw.io as webapp but I'm not able to open it with doubleclick from a file.
