### ISSUE TITLE
Text size is changed to most recent value even when "set default style" is chosen

### ISSUE THREAD

**Issue by gal064** [jgraph/drawio#3308]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I set default style with a certain text size, I expect it not to stay and not change to the most recent value

**To Reproduce**
1. Add text and set style to 18px
2. Click on 'set defualt style'
3. Add a 2nd text and change font to 10px
4. Add 3rd text. Font size should be 18px but instead it's 10px

**Expected behavior**
Setting a font size as default style fixate the default font size to all new shapes until default style is changed by the user.

**Screenshots**

https://user-images.githubusercontent.com/50427415/213807123-f9221311-ce95-4d88-b4b7-0accb2f5c5c1.mov

**draw.io version (In the Help->About menu of the draw.io editor):**
20.08.10

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 109.0.5414.87 (Official Build) (arm64)

**Comment by alderg** [comment]
We're going to change this in the next major version: https://github.com/jgraph/drawio/discussions/3312
