### ISSUE TITLE
Set `target` for SVG links?

### ISSUE THREAD

**Issue by soywiz** [jgraph/drawio#331]
Would be nice to be able to specify `target` for SVG links.

Right now the generated links are like this:

```
<a xlink:href="link">
```

I want to set a target (`_top` or `_blank`)
```
<a target="_top" xlink:href="link">
```

The problem with not specifying a target is that when using `<embed>` the link targets the embed block instead of the container frame.

I have the issue here:
https://github.com/korlibs/korlibs.soywiz.com/blob/master/index.md
```
<embed src="korlibs-deps.svg" />
```

And I am using the script I run to fix the issue:
https://github.com/korlibs/korlibs.soywiz.com/blob/master/fix_svg_target.kt

But it is a bit annoying requiring a script for this.

**Comment by alderg** [comment]
Thanks for the report. This option will be added in the SVG export dialog in 9.3.0.

**Comment by soywiz** [comment]
I have tried and doesn't seems to work for me. I have tried the two exposed options: "Automatic" and "Open in new window". Neither option includes a `target` attribute in the `a` tag. Just a plain: `<a xlink:href="test.html">`
Also automatic would be the `_top` target?

**Comment by alderg** [comment]
Works for me. Can you share the diagram you used for testing? ("Automatic" uses no target.)

**Comment by soywiz** [comment]
**About automatic:**

If automatic doesn't uses target, would be nice an option to set it to `_top` as I described, when embedding no target makes the new page to be loaded within the embed, which is not what most people want. Lucidchart sets it `target="_top"` by default and `target="_blank"` for new pages.

The diagram using `<embed>` instead of `<img>` so links work:
<img width="816" alt="screenshot 2018-10-22 at 18 35 28" src="https://user-images.githubusercontent.com/570848/47305346-7fbe9600-d629-11e8-8545-4c4861d7e896.png">

After clicking one item, the new page is placed insitu where the `<embed>` was instead of in `_top`.
<img width="705" alt="screenshot 2018-10-22 at 18 35 38" src="https://user-images.githubusercontent.com/570848/47305347-7fbe9600-d629-11e8-88f8-9190d167f650.png">

**About the target=_blank not working for me:**

XML file:
```
<mxfile userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) draw.io/8.8.0 Chrome/61.0.3163.100 Electron/2.0.2 Safari/537.36" version="9.3.0" editor="www.draw.io" type="device"><diagram id="46ab275a-1604-dfd9-995f-36f75cb7721f" name="Page-1">dZNNc4MgEIZ/DdeOwiRtrzFpeun0kOn0jLoREhQHN1X764sCfkwaDw777Be8C4QlZXc0vBYfOgdFaJR3hO0JpXSztf8B9A6wzcaBwsjcoXgGJ/kLHkae3mQOzSoQtVYo6zXMdFVBhivGjdHtOuys1bprzQu4A6eMq3v6LXMUjr7Q55m/gyxE6BxvX50n5dm1MPpW+X6EsvP4OXfJQy1/0EbwXLcLxA6EJUZrdKuyS0AN0gbZXN7bA++0bwMV/pPw1YD5TC+DZDRSPLVTG4MQGnSpSlbXmT0JLJVzhBZ02uXUvcE+CNcKiXCqeTbYrb0bhO3GGmwf2yVvajeus+zAFty52j9gELqHR4gXLY+gS0DT25CQwLyW/q7FW2+3i8l5JBZDC4z7u1JMlWe97MKfMpgLBQOapzWGL14EO/wB</diagram></mxfile>
```

Exported SVG file:
```
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="81px" height="81px" version="1.1" content="&lt;mxfile userAgent=&quot;Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) draw.io/8.8.0 Chrome/61.0.3163.100 Electron/2.0.2 Safari/537.36&quot; version=&quot;9.3.0&quot; editor=&quot;www.draw.io&quot; type=&quot;device&quot;&gt;&lt;diagram id=&quot;46ab275a-1604-dfd9-995f-36f75cb7721f&quot; name=&quot;Page-1&quot;&gt;dZNNc4MgEIZ/DdeOwiRtrzFpeun0kOn0jLoREhQHN1X764sCfkwaDw777Be8C4QlZXc0vBYfOgdFaJR3hO0JpXSztf8B9A6wzcaBwsjcoXgGJ/kLHkae3mQOzSoQtVYo6zXMdFVBhivGjdHtOuys1bprzQu4A6eMq3v6LXMUjr7Q55m/gyxE6BxvX50n5dm1MPpW+X6EsvP4OXfJQy1/0EbwXLcLxA6EJUZrdKuyS0AN0gbZXN7bA++0bwMV/pPw1YD5TC+DZDRSPLVTG4MQGnSpSlbXmT0JLJVzhBZ02uXUvcE+CNcKiXCqeTbYrb0bhO3GGmwf2yVvajeus+zAFty52j9gELqHR4gXLY+gS0DT25CQwLyW/q7FW2+3i8l5JBZDC4z7u1JMlWe97MKfMpgLBQOapzWGL14EO/wB&lt;/diagram&gt;&lt;/mxfile&gt;" style="background-color: rgb(255, 255, 255);"><defs/><g transform="translate(0.5,0.5)"><a xlink:href="test.html"><rect x="0" y="0" width="80" height="80" fill="#ffffff" stroke="#000000"/><g transform="translate(29.5,33.5)"><switch><foreignObject style="overflow:visible;" pointer-events="all" width="20" height="12" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"><div xmlns="http://www.w3.org/1999/xhtml" style="display: inline-block; font-size: 12px; font-family: Helvetica; color: rgb(0, 0, 0); line-height: 1.2; vertical-align: top; width: 20px; white-space: nowrap; word-wrap: normal; text-align: center;"><div xmlns="http://www.w3.org/1999/xhtml" style="display:inline-block;text-align:inherit;text-decoration:inherit;">test</div></div></foreignObject><text x="10" y="12" fill="#000000" text-anchor="middle" font-size="12px" font-family="Helvetica">test</text></switch></g></a></g></svg>
```

Screenshots:

<img width="612" alt="screenshot 2018-10-22 at 18 30 32" src="https://user-images.githubusercontent.com/570848/47305146-decfdb00-d628-11e8-839a-100e48e6d870.png">
<img width="746" alt="screenshot 2018-10-22 at 18 31 18" src="https://user-images.githubusercontent.com/570848/47305148-decfdb00-d628-11e8-8fd5-174ee9624f46.png">
<img width="416" alt="screenshot 2018-10-22 at 18 31 32" src="https://user-images.githubusercontent.com/570848/47305149-decfdb00-d628-11e8-8144-8be76f77a84f.png">

**Comment by alderg** [comment]
We'll add another option for "_top" in the next release (automatic will not add a target).
