### ISSUE TITLE
Crop is not tight around the image when exporting an image including LaTeX text to svg/pdf

### ISSUE THREAD

**Issue by mattiasvillani** [jgraph/drawio#3311]
* [ x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When exporting a drawing with LaTeX text to svg or pdf, the figure is not cropped close enough to the image area. Crop should be tighter around image.

**To Reproduce**
1. Draw rectangle.
2. Insert LaTeX text `$$A$$` inside rectangle near rectangle corner. This works as it should: the crop is tight around the rectangle when exporting to svg/pdf.
3. Now, replace the LaTeX text in step 2 with `$$\boldsymbol{A}$$`, i.e. just make the letter A bold. Now the crop after export to svg/pdf is no longer tight and extends well outside the rectangle.

**Expected behavior**
I would expect the crop to be tight around the rectangle.

**Likely explanation of bug**
If I move the LaTeX text further inside the rectangle, the excess crop area becomes smaller and eventually disappears. Seems like draw.io considers the full length of the LaTeX command, \boldsymbol{A}, as raw text and there wrongly thinks that my bold A extends outside the rectangle.

**draw.io version**
- 20.6.2

**Desktop**
 - OS: Linux, Pop_os 22.04 Nvidia
 - Browser: Chrome

**Comment by savvaki** [comment]
I am also having this issue. The export to pdf is using the width of the text `$$\boldsymbol{A}$$` when it should only be using the width of the **rendered** latex equation, so just `A`. The problem gets worse the more \boldsymbols are used.

**Comment by alderg** [comment]
Please read "Blank space or extra pages" in https://www.diagrams.net/doc/faq/math-typesetting#troubleshooting
<img width="709" alt="Screenshot 2023-04-10 at 11 35 59" src="https://user-images.githubusercontent.com/921200/230876370-af2f10c7-7cd7-4deb-8a9c-905b141f05ad.png">

**Comment by savvaki** [comment]
> Please read "Blank space or extra pages" in https://www.diagrams.net/doc/faq/math-typesetting#troubleshooting <img alt="Screenshot 2023-04-10 at 11 35 59" width="709" src="https://user-images.githubusercontent.com/921200/230876370-af2f10c7-7cd7-4deb-8a9c-905b141f05ad.png">

Thanks for this!  After selecting "Block", with "Left alignment" and resizing using negative left and right spacing to remove the padding, it worked.  Although this is far from ideal.

**Comment by nhatkhangcs** [comment]
Hi, the issue seemed to be presenting in current website when I tried to do the same. Did we have an official fix (in terms of version) for this bug?

**Comment by davidjgraph** [comment]
Please file a new issue with version, environment and reproduction steps.

**Comment by nhatkhangcs** [comment]
Version: v29.7.12
Demo file: [Link](https://drive.google.com/file/d/199JUaVL5qCh7FZh1x1S7-pc_o83nPEpc/view?usp=sharing)
Reproduction steps:
1. Normal mathematical display: `$$F$$` and export to PDF (border margin set to 5) --> the crop is tight to the math text, which is what I want
2. Change to `$$\mathcal{F}$$` and export to PDF (border margin set to 5) --> the crop is not tight (extended to left and right side, depend on justification: left or right of the text display). **Expected:** The crop should also tight just like first display.

For comparison, I have put those 2 displays in the demo link.
