### ISSUE TITLE
Bring "Convert labels to SVG" export option to Desktop version + conversion issue

### ISSUE THREAD

**Issue by OverFloyd** [jgraph/drawio#3319]
* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

So, I've this big file I'm working on that has a lot (really a lot) of text labels and I'll have it to upload it to Wikimedia Commons. Since Commons doesn't like certain tags about text labels I have to convert that into vectorized text, feature that is only available on the web version. I'd really like to have it on Deskto
p so that I wouldn't have to switch working environment every time I need to export my drawings.

Second, since this file I'm working on is as I said pretty text intensive, the converter struggles to convert all the text and ends with an error. I'll upload the file for context so that you can replicate the issue.

[Carrara-Avenza rev. 3 (2023-01-23).zip](https://github.com/jgraph/drawio/files/10520874/Carrara-Avenza.rev.3.2023-01-23.zip)

Cheers!

**Comment by davidjgraph** [comment]
convert to SVG requires a back-end, it can't be ported to desktop.
