### ISSUE TITLE
Include svg's `viewBox` attribute

### ISSUE THREAD

**Issue by soywiz** [jgraph/drawio#332]
`viewBox` is required when embedding a SVG for `width` and `max-width` css properties to work properly scaling the content.

I'm patching it right now like this: https://github.com/korlibs/korlibs.soywiz.com/blob/09b38f4f369efbec66c29db99ac8a642eab3da4d/fix_svg_target.kt#L31-L43

It should be something like `<svg ... viewBox="0 0 $width $height" width="${width}px" height="${height}px" ...>`

**Comment by alderg** [comment]
Thanks for your feedback. We'll add a viewBox in the next release.
