### ISSUE TITLE
Unable to search for shapes on Android with Chromium

### ISSUE THREAD

**Issue by dj-louw** [jgraph/drawio#3321]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When running draw.io on an Android Tablet, I am unable to search for a specific shape using the upper left-hand search box, because it expects me to hit `ENTER` when done, and the mobile on-screen keyboard has no `ENTER` key.

**To Reproduce**
On an android device, using a Chromium based browser
1. Open https://app.diagrams.net/ on the MS Edge browser 
2. Press on the search box, and type in a search term
3. On the on-screen keyboard, try to find the `ENTER` key to initiate the search.

**Expected behavior**
I would expect one of 3 things to happen:
1. The on-screen keyboard would have an `ENTER` key that will allow me to initiate the search.
2. Some button would appear in the UI that I can press to initiate the search.
3. Search would automatically start based on my typed characters.

**Screenshots**

Google Chrome, with the Samsung Keyboard. No `ENTER`, only `NEXT` which moves focus to the next form field.
![chrome samsung kb](https://user-images.githubusercontent.com/1496180/215272454-6d1678c6-1871-416c-b98f-6954d1ebb673.jpg)

Google Chrome, with Gboard. Same issue.
![chrome gboard](https://user-images.githubusercontent.com/1496180/215272498-47b65f73-b22e-4ce5-9dec-0090ecd21a58.jpg)

MS Edge, with Samsung Keyboard. Same issue
![edge samsung keyboard](https://user-images.githubusercontent.com/1496180/215272514-a9ceaa41-36b1-4e3e-827c-7dfcf3095eac.jpg)

MS Edge, with GBoard. Same issue
![edge gboard](https://user-images.githubusercontent.com/1496180/215272524-adff4dc5-c1a2-4f6f-8c0f-ef1983a8b578.jpg)

Firefox, with GBoard. WORKS
![ff gboard](https://user-images.githubusercontent.com/1496180/215272542-48a0fd41-c8f7-444d-bbf1-0502856314bc.jpg)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20-8-13

**Desktop (please complete the following information):**
 - OS: Android 13 / Samsung OneUI 5.0
 - Browser: This seems to impact chromium-based browsers. The issue was replicated on both MS Edge (109) and Chrome (109)
 - I encountered this issue on a Samsung Galaxy Tab S8 Ultra, I do not have other tablets to test on.

**Smartphone (please complete the following information):**
This does not appear to be an issue on mobile devices, on my phone my keyboard has a `GO` button to initiate the search.

**Comment by davidjgraph** [comment]
Improvement in 21.8.0
