### ISSUE TITLE
Add edges specifically in CSV def

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#3324]
Change CSV to make edges specifically defined in their own section, rather than be implicit as they are at time of writing.

**Comment by EdgarSchouten** [comment]
While the styling, labelling and cardinality of edges can be defined in the `# connect`-configuration lines, the _type_ of the connector cannot be imported through CSV. This would be useful when schema's have relations with distinct semantics, for example regular relations between classes (Person drives Car) and a class hierarchy relation (Car is subclassed from Vehicle). The ability to add a property `type` with a value to a connector would make a big difference. But of course a JSON-object with arbitrary key-values would be more generic.
In the example below the value `edge` is given to the property `type` of the connector

```
# connect: { \ 
   "from": "relatedTo", \ 
   "to": "id", \ 
   "fromlabel": "relationLabel", \ 
   "Data":{"type":"edge"}, \ 
   "style": "endArrow=%cardinality%;edgeStyle=entityRelationEdgeStyle;curved=1;" \
}
```
