### ISSUE TITLE
More Shapes button color

### ISSUE THREAD

**Issue by sinups** [jgraph/drawio#3326]
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/11144268/216061878-8e694399-7c16-48aa-869d-a50a9d208214.png">

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/11144268/216062199-7df65b2d-32ef-4505-9c44-523f7129be56.png">

 `.geEditor button, .geEditor select ` overwrite button style `.gePrimaryBtn`

<img width="1773" alt="image" src="https://user-images.githubusercontent.com/11144268/216064161-c95da41d-cb25-4824-8891-33a858f3ccd4.png">

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by davidjgraph** [comment]
Released in 20.8.16
