### ISSUE TITLE
Add %width% %height% as default placeholders

### ISSUE THREAD

**Issue by mrjd19811** [jgraph/drawio#3327]
* [ x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When using dimension measurement lines from the floorplan stencil it does not automatically put the size in the label. Such as it does in several other programs. The ability to reference %width% %height% as a place holder would remedy this.

The reason this is important is that in its current form when creating a dimension line it allows the potential of human error by putting the wrong dimension in the label, or resizing the dimension line and not changing the label to reference the new size.

**Describe the solution you'd like**
be able to use %width% and %height% on any object label

**Describe alternatives you've considered**
There does not appear to be any other than manual entry, and locking. But this still can allow human error by unlocking resizing and not changing a label.

**Additional context**
![image](https://user-images.githubusercontent.com/71107353/216088858-ed311768-0e71-434a-8a50-30065e10154a.png)

**Comment by Phrogz** [comment]
This would only work for horizontal or vertical dimensions, not diagonal lines. Matching the spirit of the request, perhaps `%length%` placeholder (or alternative syntax) would be preferred?

Would this request also request a scale setup for the document, or are you content labeling dimensions all at their "print" size and not what the real-world size of such a drawing would require?

**Comment by burner-** [comment]
I think lack of this feature is biggest problem in drawio. Anyhow I agreee with Phrogz that %leght% for line objects would be better. That will allow add also diagonal measurement lines. Also that scale setup would be great because now I need scale up all drawings to spesific pixel or mm dimension and then calculate dimension again and again.

**Comment by PackElend** [comment]
I would love to see that as well, so far Visio cannot be replaced

**Comment by davidjgraph** [comment]
Please avoid "me too" comment, they cause noise and add nothing. Voting for an issue is performed by adding a thumbs up to the original post.

**Comment by davidjgraph** [comment]
21.8.0 adds width, height and length for edges.

**Comment by Shogutora** [comment]
> 21.8.0 adds width, height and length for edges.

How do you actually then add the edge label with the dynamic measurements?

**Comment by Phrogz** [comment]
@Shogutora 
> How do you actually then add the edge label with the dynamic measurements?

1. Right-click the line and choose `Edit Data…`
2. At the bottom of the dialog that opens, check the `Placeholders` checkbox
3. Add a label to the line that says "This line is %length% long"

When you stop editing the label, it will show you the current length.

**Comment by vpistis** [comment]
> @Shogutora
> 
> > How do you actually then add the edge label with the dynamic measurements?
> 
>     1. Right-click the line and choose `Edit Data…`
> 
>     2. At the bottom of the dialog that opens, check the `Placeholders` checkbox
> 
>     3. Add a label to the line that says "This line is %length% long"
> 
> 
> When you stop editing the label, it will show you the current length.

Hi,

I have found akso the faq https://www.drawio.com/doc/faq/predefined-placeholders but the `%length%` for a line is not working.
It's only my trouble?

thanx

**Comment by manuelfink** [comment]
This placeholders are great.

What I'm missing is to see them in choosen unit of measurement. Added this to another feature request on units https://github.com/jgraph/drawio/issues/713. Maybe anyone can help with this?

**Comment by jonasmhack** [comment]
> @Shogutora
> 
> > How do you actually then add the edge label with the dynamic measurements?
> 
> 1. Right-click the line and choose `Edit Data…`
> 2. At the bottom of the dialog that opens, check the `Placeholders` checkbox
> 3. Add a label to the line that says "This line is %length% long"
> 
> When you stop editing the label, it will show you the current length.

Does this work on the website or only on Desktop?

**Comment by greatvovan** [comment]
@vpistis ensure that you are adding the label by typing at the connector. If you double-click at a connector, it will create a bound text, which will move together with the connector but will be a different shape. Only main label supports %length%.

**Comment by rtfmoz2** [comment]
See https://www.drawio.com/doc/faq/predefined-placeholders
My current experience since this is available is that %width% and %height% work for shapes. Use %length% for connectors. You have to first enable placeholders in  the data settings of the object. 

1. Select shape
2. Edit Data
3. Tick box marked Placeholders
4. Apply

Now use placeholders %width% and %height%.

**Comment by alderg** [comment]
Since version 24.0.5 (13-MAR-2024), labels added by double-click also support %length%.
