### ISSUE TITLE
HTML Export without layers not working

### ISSUE THREAD

**Issue by Godehardt2003** [jgraph/drawio#3328]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
If I export my file (File -> Export as -> HTML...) and uncheck the "layers" checkbox, I get on the HTML page the following message: "E is undefined". With the layers option checked everything works. Also the other check boxes are working.
I simply wanted to remove the layers button from the HTML file...

**To Reproduce**
1. File -> Export as
2. Click on HTML...
3. Uncheck the layers option
4. Click on export
5. Open the HTML file locally and you will see the error.

**Expected behavior**
I expected that the layers button disappears and the end user is not able to see the layers.

**Screenshots**
![image](https://user-images.githubusercontent.com/78535292/216164915-13e8cdf9-e919-4181-b927-fb25824e5970.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.8.14

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 109.0 (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by davidjgraph** [comment]
I think you're caching an incorrect CSP there. Does it work in a different browser?

**Comment by Godehardt2003** [comment]
Hello @davidjgraph,
it also doesn't work in chrome but with a different error message:
![image](https://user-images.githubusercontent.com/78535292/216176079-696f4b4e-901f-415f-90c4-ea8392cd4cbf.png)

**Comment by davidjgraph** [comment]
If you're opening from the local filesystem, I wouldn't expect that to work. You need to serve it from a web server.
