### ISSUE TITLE
ui probelm about line style setting

### ISSUE THREAD

**Issue by weianweigan** [jgraph/drawio#3330]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

![image](https://user-images.githubusercontent.com/25452811/216225122-a4b5eb6e-afbc-4754-9878-69ce30a88b62.png)

**To Reproduce**
1. Add a new line
2. Select the line
3. Switch to Style tab

**draw.io version:**

- draw.io version 20.8.15

**Desktop**
 - OS: win11
 - Browser: microsoft edge
 - Version:109.0.1518.70

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
