### ISSUE TITLE
Lucid to draw.io Chrome extension does not work

### ISSUE THREAD

**Issue by nitints** [jgraph/drawio#3332]
### Discussed in https://github.com/jgraph/drawio/discussions/3285

<div type='discussions-op-text'>

<sup>Originally posted by **nitints** January 13, 2023</sup>
Hello

trying to use the chrome extension to import Lucid diagrams into draw.io but it doesn't work
 Error: Couldn't fetch documents list.

<img width="503" alt="image" src="https://user-images.githubusercontent.com/60752877/212398689-7dc918f1-4d3a-44b9-8449-d5c2d2972a5f.png">

Hoping the bug can be fixed, as we are looking forward to moving all users to diagrams.net</div>

**Comment by davidjgraph** [comment]
Lucid regularly break the extension, such is their right :).
