### ISSUE TITLE
New azure icons

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#3333]
https://learn.microsoft.com/en-gb/azure/architecture/icons/

January 2023 | Added ~106 icons for various services and components.
-- | --

**Comment by maxilampert** [comment]
There has been another update since then would be great if they could be integrated soon

March 2023 | Added 13 icons for various services and components.
-- | --

**Comment by egrimate** [comment]
Will be in next release

**Comment by davidjgraph** [comment]
In 23.1.1 release.
