### ISSUE TITLE
Include searchable metadata and keywords in compressed file formats

### ISSUE THREAD

**Issue by cushyno** [jgraph/drawio#3334]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I have a large and growing collection of solution design diagrams scattered across local folders and in SharePoint as dictated by the various projects I work on.  Organising these files so that I can easily search and find diagrams based on the content proves difficult.

**Describe the solution you'd like**
To simplify finding relevant diagrams myself and colleagues need to search embedded text of diagrams for metadata or content within the DRAWIO/XML, PNG, PDF, or SVG files.  While it is possible to search and index words in non-compressed drawio/xml files, files saved/exported to PNG's, SVG or PDF format always include a compressed mxfile diagram stream.  Therefore I am unable to search the collection of files for relevant content.

If diagrams.net would permit inclusion of "metadata" or "tags" or "keywords" to be added at file level outside of the compressed page data in all file formats, we'd be able to search documents for keywords even when in compressed format.  PDF's have such as feature by embedding XMP metadata in a document as a stream.  XML and SVG files could include an additional uncompressed keyword tag separate to the diagram/page content.

This is not about the "tags" associated with elements of diagrams that may be edit with "Edit Data" function, it relates to metadata (author, creation date, modified date, type of editor) and keywords about the file itself.

**Describe alternatives you've considered**
Options I've considered:
* Store sufficient detail in the file names.  This is unrealistic when the content of the diagrams may have many concepts and entities that would be too long to list in the file name .
* Always save files as uncompressed XML therefore enabling a full text search on its contents.  Results in very large XML files and would require saving diagrams more than once if PDF/PNG/SVG were also required.
* Maintain an external register of all diagrams and tags/metadata about the content of the diagrams.  Very inconvenient and could rapidly get out of sync with reality.

**Additional context**
Embedding XMP metadata in a PDF document:  https://docs.devexpress.com/OfficeFileAPI/403105/pdf-document-api/xmp-metadata

**Comment by cushyno** [comment]
I am still looking for a solution to this problem.  Any chance it can be considered a **feature request**?

**Comment by alderg** [comment]
We conducted additional tests on the search functions of OneDrive and Google Drive. Neither service appears to include data inside .drawio files, even when these files are uncompressed. Furthermore, only Google Drive seems to search descriptions added through its web interface, whereas OneDrive does not include file descriptions added in its web interface in search results. In summary, the best approach is to add a description to the file using the cloud storage web interface, though this may not always ensure inclusion in search results.
