### ISSUE TITLE
New AWS icons on 2023-01-31

### ISSUE THREAD

**Issue by hakanson** [jgraph/drawio#3336]
FYI, new AWS Architecture Icons were released at https://aws.amazon.com/architecture/icons/ on 2023-01-31

Asset Package Download -> https://d1.awsstatic.com/webteam/architecture-icons/q1-2023/Asset-Package_01312023.d59bb3e1bf7860fb55d4d737779e7c6fce1e35ae.zip

BTW, commit history from https://github.com/awslabs/aws-icons-for-plantuml/releases can be another source of new or changed icons.

**Comment by davidjgraph** [comment]
Thanks for the hint.

**Comment by egrimate** [comment]
Will be in next release

**Comment by hakanson** [comment]
Thanks - by "next release" do you mean `v21.1.7` ? - and will that be a desktop release as well (current desktop version is still `21.1.2` but `v21.1.6` was released yesterday)?

**Comment by davidjgraph** [comment]
Released in 21.1.8

**Comment by tetsuo-miyakuni** [comment]
I think the subnet icon is still previous icon.

**Comment by davidjgraph** [comment]
Could you show me the new subnet icon from the AWS supplied package against what we have?

**Comment by tschaffter** [comment]
This [GitHub project](https://github.com/m-radzikowski/diagrams-aws-icons) provides the latest AWS icons for Draw.io.

**Comment by tschaffter** [comment]
<img width="315" alt="image" src="https://github.com/jgraph/drawio/assets/3056480/3e95abf2-5cb4-4841-95b8-7e744d2a004c">

**Comment by davidjgraph** [comment]
Does this repo use the official AWS icon set? When you say it provides the latest set, it added 20240206 a week ago, we added that set a month ago. I'm very confused why this repo has been linked.

**Comment by tschaffter** [comment]
@davidjgraph See the README of the repo linked.

> we added that set a month ago.

From a user perspective, the most recent version visible on draw.io is "AWS19".

<img width="202" alt="image" src="https://github.com/jgraph/drawio/assets/3056480/a2dbd6d6-5824-49a0-a621-91378580b6de">

**Comment by davidjgraph** [comment]
The 2019 set is the last major version, changes to the set are made to that version if there are minor (which they have been since), our set is up to date, unless someone can show something specific. I guess we can remove the date on the 19 set if it confuses people.

In terms of their README, they are responsible for that, not us.
