### ISSUE TITLE
Feature to "upgrade" AWS Icons from old icons sets (e.g. AWS 17, AWS 18)

### ISSUE THREAD

**Issue by hakanson** [jgraph/drawio#3337]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Sometimes people use older AWS icons on diagrams, which need to be updated.  This happens when updating older diagrams, or user selects the wrong icon after a search.  Manual edits of these are frustrating.

**Describe the solution you'd like**
I would like an "easy button" to fix/update.  Maybe a built in menu item or plugin that can bulk update the icon `shape` value.

**Describe alternatives you've considered**

1. Using `Extras -> Edit Diagram...` menu and doing search/replace
2. Writing a Plugin (which wouldn't work on Desktop)
3. Writing a CLI utility to do replacements, but would want to leverage any file-format libraries (to support `.drawio`, `.svg`, and `png` formats)
4. Having an integrated or external "lint" utility to generating warnings for outdated icons.  This would require manual edits, but could also find other potential issues.

**Additional context**
Here is an PNG (with embedded diagram) or AWS 17 Lambda, AWS 18 Lambda, and current Lambda.  After the mappings, the shape replacement is the "easy" part compared to the change of dimensions between icon sets.  Even after bulk replacement, manual edits will be required.

* AWS 17 Lambda
  * shape=mxgraph.aws3.lambda
  * width="76.5" height="93"
* AWS 18 Lambda
  * shape=mxgraph.aws4.productIcon;prIcon=mxgraph.aws4.lambda
  * width="80" height="100"
* AWS Lambda
  * shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.lambda
  * width="78" height="78"

![LambdaLambdaLambda drawio](https://user-images.githubusercontent.com/414500/216784214-077ca6c3-a115-4859-a5d6-2c3846aa7e8a.png)

**Comment by kyoh86** [comment]
is there any update for this one?

**Comment by davidjgraph** [comment]
Thanks for the suggestion. Given that we've been updating the AWS19 set in place for some time now, the effort to implement and maintain this feature doesn't balance against the number of people who would benefit.
