### ISSUE TITLE
Set default scale when saving over diagram embedded in PNG

### ISSUE THREAD

**Issue by teadotjay** [jgraph/drawio#334]
I love that I can embed the XML inside the PNG and only have a single file to keep track of. However, when I reopen the PNG inside draw.io and edit it, upon saving, it reverts to 100% scale. In order to get back to the original 200% scale, I seem to have to export on top of the original PNG and set the scale manually, which significantly hampers workflow. How do I get around this? (Note that I have set the default scale in View, to no effect.)

**Comment by davidjgraph** [comment]
Could also store border settings

**Comment by alderg** [comment]
You can now save as .png file and set the default zoom and border via File, Properties.
