### ISSUE TITLE
Visio Export "Unknown Error"

### ISSUE THREAD

**Issue by hb-i** [jgraph/drawio#3340]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Opening a vsdx file and then trying to export it produces an error

**To Reproduce**
Open a vsdx file from device
Try exporting it (File > Export as > VSDX (beta)
Error "Uknown error"
**Expected behavior**
Allow saving as vsdx file

**Screenshots**
![image](https://user-images.githubusercontent.com/27036750/217350709-f1625a8f-8a05-443f-9b42-fefd06670bea.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
20.8.16

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge (Chromium)
 - Version 109.0.1518.61 (Official build) (64-bit)

**Additional context**
Looking at the Dev console I see this...

![image](https://user-images.githubusercontent.com/27036750/217351442-f6d1f8aa-c8ce-449a-8276-d6e57b83fd75.png)

**Comment by davidjgraph** [comment]
Please attach the vsdx diagram that causes this. If it's sensitive, try a non-sensitive vsdx file.

Note that the vsdx export is beta.

**Comment by hb-i** [comment]
[Visio.zip](https://github.com/jgraph/drawio/files/10679305/Visio.zip)

See attached, I removed all the sensitive info.

**Comment by SupportOutilsJiraConfluenceHQ** [comment]
Will this issue be corrected in a nearby version ?

**Comment by davidjgraph** [comment]
The example provided imports and the then re-exports correctly in 23.1.2, so the issue of the original poster is assumed fixed.
