### ISSUE TITLE
Objects in locked layers selectable

### ISSUE THREAD

**Issue by paracoon** [jgraph/drawio#3343]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Objects in locked layers are usually visible but are not "interactable" in any way. i.e. clicking on them does nothing, as it should.
Until sometime yesterday. Now when I click on an area of a diagram where there are objects in a locked layer, it selects them with a red dashed outline. I cannot DO anything to them or move them, but just being able to select them means that I cannot use a drag selection box to grab a group of objects in a non-locked layer. The only way to avoid this is to actually turn off the visibility of the locked layers as well, which is not a good workaround since I want to things to align and things I cannot see are difficult to align.

This just started yesterday, while I was editing a diagram, and for a while it did not affect other machines but it eventually got them as well. And my colleague also has experienced the problem.

I searched all the settings and options, convinced I had pressed some obscure keyboard shortcut and found nothing.

**To Reproduce**
1. Lock a layer
2. Click on an object/shape in that layer
3. Object gets selected with a red dashed outline when it should not be selected

**Expected behavior**
Clicking on an object in a locked layer should do nothing.

**Screenshots**
![Screenshot 2023-02-08 125334](https://user-images.githubusercontent.com/124816319/217625250-af812147-4e58-491d-bba4-bcf1dc0322aa.png)

In the screenshot the green box is in the "Security Zones/Area" layer

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.8.18

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 110.0.5481.78

My colleague tested it with Edge as well, and got the same behavior

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
https://github.com/jgraph/drawio-dev/commit/f766f5be6008d8ab1295d748dd73c84041e1d08b

**Comment by davidjgraph** [comment]
Released in 20.8.19

**Comment by paracoon** [comment]
Appreciate the quick response!

However there still appears to be a problem.
The red-dash outline is indeed gone, but when I attempt to click-drag a selection around items in the current unlocked layer, it does not work if the area of the screen where I initially click is occupied by an object in a locked layer. The click-drag selection does not even register.
Click-drag selection works if I click someplace outside of all objects (bare background).

**Comment by davidjgraph** [comment]
Second fix in 20.8.20.

**Comment by paracoon** [comment]
Confirmed!
Excellent support, guys, thank you so much.
