### ISSUE TITLE
Opening diagram files results in ETIMEDOUT message

### ISSUE THREAD

**Issue by widovanheemstra** [jgraph/drawio#3344]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
After updating the diagrams desktop for Mac application, it won't open files created a few weeks back with a previous version. It directly displays a popup showing the error: ETIMEDOUT: connection timed out, read.

I don't know what time is set until time out is reached, but it happens as soon as I select a file and click open.

**To Reproduce**
1. Go to 'File->Open...'
2. Select prefered diagrams file and click 'Open'
3. See error

**Expected behavior**
The file being opened and showing the diagrams created before.

**Screenshots**
![image](https://user-images.githubusercontent.com/8260162/217834359-555e8811-62cb-47bd-a90d-fb842a5416ac.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
diagrams.net 20.8.16
- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.1
 - Browser [NA]
 - Version [NA]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by davidjgraph** [comment]
Is there anything else about the folder you're opening from? Is it a cloud sync'ed drive?

**Comment by widovanheemstra** [comment]
@davidjgraph Thanks for this. Yes, my files are on a synced onedrive. However the helper function was not loaded hence the actual data was not on my disk. I started the onedrive helper and now it works!
