### ISSUE TITLE
Updating existing draw.io doc failed in Google Doc

### ISSUE THREAD

**Issue by ziler-orca** [jgraph/drawio#3345]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I try to update an existing diagram from Google doc, it is throwing the following error:

```
1 update failed:
- Request failed for https://convert.diagrams.net returned code 403. Truncated server response: <!DOCTYPE html>
<html lang="en-US">
<head>
<title>Just a moment...</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-... (use muteHttpExceptions option to examine full response)
```

**To Reproduce**
1. Create a google doc
2. Insert draw.io diagram or try updating existing one 

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/115487356/217851176-1136189a-e26b-4b17-81c8-6f4e8ef2373d.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Browser [chrome]
 - Version [109.0.5414.119 (Official Build) (arm64)]

**Additional context**
Also failing when I try to insert a diagram.

**Comment by davidjgraph** [comment]
Please try again and let us know if it's working

**Comment by ziler-orca** [comment]
Works now. Thanks.

**Comment by RapazP** [comment]
Hi,

The issue of diagram insert / update in google docs is present again. 

![image](https://user-images.githubusercontent.com/5381612/227607576-5d1d36e4-5015-4a0e-8a68-d5fc067dcaeb.png)

Best regards

**Comment by JBinAussie** [comment]
I've just run into it as well - I've checked the app is whitelisted and given all permissions in the admin console but when I try to insert a previously created diagram I get the usual error;

![image](https://user-images.githubusercontent.com/44958538/228717585-c47bb18e-571c-4709-adac-6876c6e31c6c.png)

And when I try to create a new drawing I'm taken to the Draw.io app but then there doesn't appear to be any way of inserting the finished item?

Any help would be greatly appreciated!

Thanks,

James

**Comment by davidjgraph** [comment]
If anyone else sees this please open a new issue. If you can also give us the first 2 (of 4) parts of your IP address, that helps to find it in the logs.

**Comment by RapazP** [comment]
It works again for me.

Thank you
