### ISSUE TITLE
Can't select multiple objects in a multi-layer drawing

### ISSUE THREAD

**Issue by clff-arg** [jgraph/drawio#3347]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
In a multi-layer drawing, with all layers blocked, except the top one, I'm not being able to select multiple objects by "click and drag selection" in that top layer.

The click and drag selection only works if I start the selection clicking in the background layer and where there is no object.

**To Reproduce**
1. Create multi-layer with objects overlapped objects
2. Lock every layer except the top one
3. Try to select objects in top layer by clicking and dragging, with the initial click "above" an lower layer object.

**Expected behavior**
Click and drag selection should work by clicking anywhere in the drawing and selecting only the objects in the unlocked layer

**Screenshots**
![image](https://user-images.githubusercontent.com/48154125/218143496-774802ef-92d8-4498-9201-37a88d15a3c5.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.8.19

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (Version 22H2 - OS build 19045.2486)
 - Browser: Chrome
 - Version 109.0.5414.75 (Official Build) (64-bit)

**Comment by davidjgraph** [comment]
Does it work in 20.8.20?

**Comment by clff-arg** [comment]
How do I choose to use 20.8.20?

**Comment by clff-arg** [comment]
got it
it's working with 20.8.20

thank you very much for your prompt response!
