### ISSUE TITLE
Sign in Not working

### ISSUE THREAD

**Issue by sunshinebulb394** [jgraph/drawio#3348]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When i try to authorize with my email i get a 401 error

**To Reproduce**
1. Go to https://app.diagrams.net/
2. Click on existing diagram
3. Authroization required
4. Click on authorize
5. Pop up opens,Choose account
6. Click on continue to allow access
7. Error,the page isnt working

**Expected behavior**
To be authorized and get access to my existing diagrams

**Screenshots**
![Screenshot 2023-02-11 at 8 14 58 AM](https://user-images.githubusercontent.com/111359710/218247972-43b242fd-e499-4a74-bd7c-956ff7bd7244.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**
 - OS: [ MacOS Ventura]
 - Browser [chrome]
 - Version [109.0.5414.119 (Official Build) (arm64)]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mararad** [comment]
Hi,

Where are the diagrams stored, please?
Do you have the same issue in other browsers and Incognito mode with all browser extensions temporarily disabled?

**Comment by davidjgraph** [comment]
I'm sorry to hear that you're having trouble authorizing with your email in diagrams.net. A 401 error typically indicates that there is an authentication issue, such as an incorrect username or password.

To troubleshoot this issue, you can try the following steps:

    Double-check that you are using the correct email address and password to log in to diagrams.net. If you are not sure, you can try resetting your password to see if that resolves the issue.

    Clear your browser's cache and cookies, and then try to log in to diagrams.net again.

    Try using a different browser to log in to diagrams.net to see if the issue is specific to your current browser.
