### ISSUE TITLE
is it possible to copy shapes to css classes?

### ISSUE THREAD

**Issue by AdamSEY** [jgraph/drawio#335]
This would be an amazing feature!

**Comment by alderg** [comment]
No. They are rendered using JS code.

**Comment by AdamSEY** [comment]
can we render them the same way in ReactJS application?

**Comment by davidjgraph** [comment]
We're not familiar with React, what does that involve?

**Comment by AdamSEY** [comment]
I'm looking for a way to make shapes readable in HTML pages by converting them to CSS or render them using Javascript.
