### ISSUE TITLE
Color picker crash (Fedora 37/flatpak/Wayland)

### ISSUE THREAD

**Issue by gael-api** [jgraph/drawio#3352]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Each time I click on color picker, Drawio crash.

**To Reproduce**
1. Open a new diagram
2. Click to change color
3. Click on color picker
4. Drawio crash with the following first line : 
`com.jgraph.drawio.desktop.desktop[83811]: [2:0213/185139.183093:ERROR:shared_x_display.cc(39)] Unable to open display`

**Expected behavior**
Get the color picker

**draw.io version (In the Help->About menu of the draw.io editor):**
- diagrams.net 20.7.4
[coredump.txt](https://github.com/jgraph/drawio/files/10724914/coredump.txt)

**Desktop (please complete the following information):**
 - OS: Fedora 37 
- Drawio from flatpak **com.jgraph.drawio.desktop**   **20.7.4**   

**Additional context**
Wayland without X11

I can attach multiple coredump if it's usefull.

**Comment by davidjgraph** [comment]
We're not the author of that app, the repo is at https://github.com/flathub/com.jgraph.drawio.desktop
