### ISSUE TITLE
Chart disappeared after internet disconnect

### ISSUE THREAD

**Issue by Alenagfyhf** [jgraph/drawio#3353]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
On the laptop, the Internet was gone, I rebooted the laptop several times and the diagram, which I did for 3 weeks. just faded. How is this possible? If there is "Autosave" How?

**To Reproduce**
1. Open the program in the browser, work in it for 3 weeks
2. DISCONNECT from the Internet!!! (I don't know how you reproduce it)!
3. Wait for the Internet to appear, and find that the diagram has disappeared somewhere.
**Expected behavior**
Open a browser and find that the diagram is not deleted when the Internet is disconnected.

**Screenshots**
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/125382968/218786011-c08c8f68-a72d-49e9-8e2a-911affef35d1.png">

**Desktop (please complete the following information):**
 -  iOS
 - chrome
 

**Additional context**
Help bring back the chart. There is very valuable work for 3 weeks.

Why did autosave not work?

**Comment by Alenagfyhf** [comment]
I tried and my diagram is not there. only blank pages survived.
Вт, 14 февр. 2023 г. в 23:58, Gavin Kistner ***@***.***>:

**Comment by Alenagfyhf** [comment]
I worked on this diagram for 3 weeks, and for some reason, even in the history there is no data about my visit on February 13, although it was a working day and we called colleagues and corrected the diagram! 
![image](https://user-images.githubusercontent.com/125382968/218899281-09f68a8d-088b-461c-8ded-3132072d4c54.png)

**Comment by Alenagfyhf** [comment]
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/125382968/218899460-886724ea-152d-473f-9db6-93ee8b7af724.png">
and also I renamed the diagram and gave it a different name, and disconnecting from the Internet, for some reason, affected the deletion of all data, it's terrible!

**Comment by davidjgraph** [comment]
Where did you save the diagram to?

**Comment by Alenagfyhf** [comment]
It turns out that it has not been preserved anywhere.

Because there are only empty files on google disk, and I don't understand
how it can be that the scheme has been deleted on its own.

ср, 15 февр. 2023 г. в 16:42, David Benson ***@***.***>:

**Comment by Alenagfyhf** [comment]
The day before I changed the name, after connecting the Internet, no data
was saved.

ср, 15 февр. 2023 г. в 17:20, Алена Волкова ***@***.***>:

**Comment by davidjgraph** [comment]
So, you selected Google Drive as the save location?

**Comment by Alenagfyhf** [comment]
why are you asking the same question?
I described my problem above, your questions do not help me solve it.

**Comment by davidjgraph** [comment]
I keep asking the same question because you haven't answered it. Where did you choose as your share location?

**Comment by 100rabba** [comment]
Same thing happens to me, yesterday I worked whole day on my diagram, and at last I shared with stakeholders. And suddenly today when I opened my diagram, only showing some part of my work, last saved around 15:00, but I had worked till around 19:00
