### ISSUE TITLE
Request: Adjustable padding of line labels' backgrounds

### ISSUE THREAD

**Issue by Phrogz** [jgraph/drawio#3355]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
The amount of space between text on a line and the background of that text is not adjustable. Sometimes it is visually desirable to have a larger amount of padding between the label text and the background. This is not possible without adding custom rectangles below each text label, which (of course) do not resize if the text is changed, or the line or label is moved. For example:

![A line with text label with solid color background; the background is close to the left and right edges of the text. A second line has the same text label with the solid color background extended to left and right. The image also includes the current "spacing" options for text with values of 10 specified for the "left" and "right" values.](https://user-images.githubusercontent.com/14778/218794525-b824d5b5-4019-4073-8757-45edb1afb45b.png)

**Describe the solution you'd like**
Use the "Spacing" options for text on a line as padding to define the background region. As shown in the image above, larger values for "left" and "right" would increase the distance between the bounding box of the text and the sides of the background, causing the background to draw larger.

**Describe alternatives you've considered**
The "Spacing" option for label text currently seems to be largely unused; large asymmetric values affect an offset of the label text from where the anchor point is placed. This seems to me to be neither intuitive nor useful. The same effect can be achieved by moving the anchor. However, if there's a use case for this, or if you are reticent to change the behavior because it will affect existing diagrams with non-zero spacing values, a new "Padding" section with the same UI as "Spacing" could be added to the Text options only when a one or more labels are selected.

**Comment by Phrogz** [comment]
I find your policy of having a bot close feature requests as "wontfix" due to lack of feedback troublesome. But you do you.

**Comment by tomkom** [comment]
THis is relevant and still missing, please reopen

**Comment by appspringtech** [comment]
definetely relevant..

**Comment by davidjgraph** [comment]
Voting on github issues is done by thumbs up reaction on the original post.
