### ISSUE TITLE
Switching pages creates URL variation allowing linking directly to a page

### ISSUE THREAD

**Issue by Phrogz** [jgraph/drawio#3356]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I have a diagram with multiple pages. I want to show a specific page to a colleague, by giving them a URL to click on. When they open the URL, I want the specific page to be seen. This should be easy and obvious.

**Describe the solution you'd like**
As with Google Sheets, changing between pages in a diagram should change the hash of the URL to a unique value. Opening that URL should show the corresponding page on open.

For backwards compatibility, existing hashes could be used, and appended with an additional, optional page identifier. For robustness, this page identifier should be a unique ID (seems to already exist and be shown when hovering page tabs), NOT the page number or page name.

For example, my current diagram shows the URL in the address bar:  
`https://app.diagrams.net/#G1ObcHXNSnnJfulSxYk7ez-swW8maLWk3n`

When switching to a different page, the hash in the address bar would change to:  
`https://app.diagrams.net/#G1ObcHXNSnnJfulSxYk7ez-swW8maLWk3n-Z8_XMVzUDMBFWBjzSCSS`  
...where `Z8_XMVzUDMBFWBjzSCSS` is the hash seen in the `title` attribute for that page.

**Describe alternatives you've considered**
A feature-creep to the feature would be to allow linking by page number or page title, in addition to the default behavior of link-by-hash, if desired. For example:

* Link by hash: `https://app.diagrams.net/#G1ObcHXNSnnJfulSxYk7ez-swW8maLWk3n-Z8_XMVzUDMBFWBjzSCSS`
* Link by number: `https://app.diagrams.net/#G1ObcHXNSnnJfulSxYk7ez-swW8maLWk3n-2`
* Link by title: `https://app.diagrams.net/#G1ObcHXNSnnJfulSxYk7ez-swW8maLWk3n-Camera%20FoV`

These two additional options would not be exposed by default, but could be options in the current "Link..." dialog?

**Additional context**
I understand the "Link..." feature for sharing the current state of the document via URL. I do not want this, but instead want to always share the latest version. A live link to edit the document, jumping to the correct page.

**Comment by davidjgraph** [comment]
See https://www.diagrams.net/doc/faq/supported-url-parameters, page and page-id parameters.

**Comment by alderg** [comment]
Or try "Link" in the page context menu:
<img width="342" alt="Screenshot 2023-03-01 at 08 06 51" src="https://user-images.githubusercontent.com/921200/222068292-e746849e-1c8c-41f7-8e4b-6a58adc55bf2.png">

**Comment by Phrogz** [comment]
I appreciate that there are ways (some of which I did not know) to create a page link.

The intention of this request odd to make it so that switching pages changes the URL so that copy/paste links straight to the page. Like Google Sheets does with tabs.

**Comment by davidjgraph** [comment]
The pageID is stored in the URL when the diagram is saved.
