### ISSUE TITLE
Copy and paste doesn't work anymore

### ISSUE THREAD

**Issue by dcandani** [jgraph/drawio#3359]
Hi
after upgrade to 20.8.16, copying and pasting an object doesn't work anymore.
Before I simply selected the object, ctrl-c + ctrl-v and that's all.
Now it doesn't work.
Is it normal?
I'm using the linux version of draw.io.
Hope to receive a feedback...
Thx&Bye

**Comment by digiajay** [comment]
I bumped here when I'm faced with copy paste format painter doesn't seems to work properly in v20.8.10 desktop app.  is i
