### ISSUE TITLE
Copy Paste Style doesn't format Text

### ISSUE THREAD

**Issue by digiajay** [jgraph/drawio#3361]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I tried to copy and paste styles, though the shape colors and line styles matches, it doesn't match the text formats

**Expected behavior**
When I try to copy and paste styles, it should paste all formattings between the objects

**Screenshots**
![Draw io Format Painter Not Working](https://user-images.githubusercontent.com/6551395/219014421-15595446-e8dd-4f4d-a222-b2faf5cf217a.gif)

**draw.io version: **
- draw.io version 20.8.16

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser : Chrome
 - Version 110.0.5481.78 (Official Build) (64-bit)

**Comment by liumoze** [comment]
I have the same problem

**Comment by alderg** [comment]
Select the yellow shape, then go to the Text panel on the right and click "Clear Formatting" (at the bottom, in version 21.1.4 or later).
