### ISSUE TITLE
After you export the file to the vsdx format and open it again, the file content is displayed incorrectly

### ISSUE THREAD

**Issue by Leisurelyc** [jgraph/drawio#3363]
After you export the file to the vsdx format and open it again, the file content is displayed incorrectly

before saving
![image](https://user-images.githubusercontent.com/29566221/219254053-aa31289e-7cd8-4762-b001-4d4260596c67.png)

reopen file
![image](https://user-images.githubusercontent.com/29566221/219253574-da37b48d-ed2b-463b-8af6-170e52bd7fed.png)

**Expected behavior**
Open the exported vsdx file again. The file content is displayed correctly

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [ 20.8.20]

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [110.0.5481.100]

**Comment by davidjgraph** [comment]
Yes, .vsdx export isn't suitable for round-trip operations. It is partial supported, that's why it's marked beta.

**Comment by Leisurelyc** [comment]
> Collaborator
ok, thank you
