### ISSUE TITLE
Enable standard Windows alt key menu functionality

### ISSUE THREAD

**Issue by Roy150** [jgraph/drawio#3366]
* [X] I agree to follow the [Code of Conduct]
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When working in the Windows app, there is no easy way to get to the top menus with the keyboard. Most Windows programs get you there when you click the Alt key. See attached images from Microsoft Word, and Notepad++.

**Describe the solution you'd like**
It would be nice if clicking the Alt key took you to the menu. Once there, you could use the arrow keys to move left and right to other menus, and up and down within a menu.

**Describe alternatives you've considered**
I don't know of an alternative, other than using the mouse.

**Additional context**
![Notepad_plus_plus_menu](https://user-images.githubusercontent.com/84104544/219691333-b15d2160-d7fc-4895-ae57-373047b4b866.jpg)
![Word_menu](https://user-images.githubusercontent.com/84104544/219691337-ad41b303-3f1f-4dd4-92db-01c3ebce27fa.jpg)

Thank you!

**Comment by davidjgraph** [comment]
This might make sense on the desktop app, but not in the online version.
