### ISSUE TITLE
Wrong file extension when opening PDF with embedded diagram

### ISSUE THREAD

**Issue by l-uuz** [jgraph/drawio#3368]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When you open a PDF with an embedded diagram, the file extension changes. Instead of `*.drawio.pdf` (as the suggested file extension), it opens the file as `*.drawio.drawio`. If you save the file again, the suggested filename becomes `*.drawio.drawio.pdf`

**To Reproduce**
1. Go to https://app.diagrams.net/ or use the drawio Desktop app.
2. Click on 'File -> Export as -> PDF', select "Include a copy of my diagram" and download/save the file on your local computer as `Test.drawio.pdf.`
3. Open drawio again, click on 'Open from -> Device' (or open with the Desktop app)
The opened filename now shows `Test.drawio.drawio`.

**Expected behavior**
The file extension should not be changed, in the example it should be `Test.drawio.pdf`.

**Screenshots**
Before saving:
![grafik](https://user-images.githubusercontent.com/56924246/219958927-8786aa31-de76-43d1-8420-4fe5880a6694.png)
After opening again:
![grafik](https://user-images.githubusercontent.com/56924246/219958972-22e7cb20-2b47-4145-a0eb-e8dce6dd404e.png)
Saving again:
![grafik](https://user-images.githubusercontent.com/56924246/219959148-07b0cfa3-6f29-4f70-8493-fc3e1e10cc5d.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
20.8.20

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox (also reproducable with drawio Desktop)
 - Version 110.0

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by davidjgraph** [comment]
Released in 20.8.23, https://drawio.atlassian.net/projects/DS/versions/11272

**Comment by l-uuz** [comment]
The file extension still changes in 21.0.3. "Test.drawio.pdf" is now opened as "Test.drawio".
