### ISSUE TITLE
draw.io Desktop changes not seen on draw.io Online app

### ISSUE THREAD

**Issue by bluemana** [jgraph/drawio#337]
I'm using both the online and desktop apps. It appears they can't read the diagram files in the same way. Below are the steps to reproduce. Am I missing something?

**My setup:**

- macOS 10.13.6
- Google Chrome 70.0.3538.77 (Official Build) (64-bit)
- a Google Drive folder on the macOS machine
- draw.io Desktop for macOS

**To reproduce:**

1. Create a new diagram by connecting to https://www.draw.io/ and following the Google Drive integration use case
2. Save the newly created, empty diagram somewhere in Google Drive
3. Open the diagram with draw.io Desktop and make some changes (adding text should be enough). Save the changes and close the app. Wait for the diagram to sync on Google Drive
4. Open the diagram with the online app at https://www.draw.io/, following the Google Drive integration use case. The changes cannot be seen on the online app
5. Open the diagram again with the desktop app. The changes can be seen as expected

**Expected behaviour:**

The changes made by the desktop app should be seen by the online app

**Comment by alderg** [comment]
Google Drive uses a different storage model currently. We are working on a fix for this which should be available later this year.
