### ISSUE TITLE
SmartArt | Easily create structured diagram with minimal typing

### ISSUE THREAD

**Issue by shamunhaydar** [jgraph/drawio#3371]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to create quick visual diagrams by just typing. It takes a lot of time and effort to create nice structured diagrams.

**Describe the solution you'd like**
As a user I want to easily create attractive / structured visual diagrams with minimal typing, allowing me to quickly and easily organize my thoughts.

**Describe alternatives you've considered**
- I used the "layout" features like vertical tree's
- I used "advanced" feature like mermaid

**Additional context**
Microsoft SmartArt is a feature in Microsoft Office applications that allows users to easily create professional-looking visuals. It includes hundreds of pre-made templates, or users can create their own from scratch. SmartArt allows users to quickly create diagrams and visuals from existing data or to just create an organized graphic based on their own ideas. With SmartArt, users can easily add text, shapes, colors, and other formatting to create visually appealing visuals.

First the user chooses and selects from the SmartArt categories to find the style he/she wants.
<img width="513" alt="image" src="https://user-images.githubusercontent.com/74245574/220181193-b08fc945-17bf-4da6-a141-9525369fdcb5.png">

Then the user can type the text in the text box to the left / right of the SmartArt graphic. 
![image](https://user-images.githubusercontent.com/74245574/220181357-82b091c1-310a-4827-a04a-e0bd54e26cbc.png)

Any changes will be realtime updated.
![SmartArt](https://user-images.githubusercontent.com/74245574/220183806-b8d57375-19be-493d-b96a-0f814652ce48.gif)

_The other features of SmartArt not needed, if you guys only can add this it will be more than enough._

**Comment by davidjgraph** [comment]
Thank you for sharing your feature request. We understand that creating quick, visually appealing diagrams is important for you and appreciate your feedback.

However, it's important to note that implementing a feature like Microsoft SmartArt would be a significant undertaking, as it involves a great deal of development and resources. While we strive to improve the functionality of diagrams.net, we must carefully balance the needs and requests of all our users and prioritize features that are feasible and most valuable to the majority of our users.

As an alternative, you may want to consider exploring the various layout and advanced features that are available in diagrams.net, such as vertical trees and Mermaid. These features can help you quickly create structured diagrams that meet your needs.

Thank you for using diagrams.net and for sharing your feedback. If you have any further questions or concerns, please don't hesitate to let us know.

**Comment by davidjgraph** [comment]
We've implemented https://github.com/jgraph/drawio/discussions/3414 . I will close this as it meets the requirement of "Easily create structured diagram with minimal typing"
