### ISSUE TITLE
Retain settings within the "Export As>Advanced" menu

### ISSUE THREAD

**Issue by floongle** [jgraph/drawio#3375]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When exporting images using File>Export As>Advanced, the settings are forgotten by diagrams.net. This wastes time and repetition of setting these values results in higher chance of mistakes.

**Describe the solution you'd like**
I'd like the File>Export As>Advanced dialog to remember the settings selected, both within an editing session and (preferably) when a file is reopened.

For example, the "DPI" value and "Transparent" are forgotten every time the user attempts to export. , whereas the "Border" is remembered (but only within an editing session, not when reopening the file).

**Comment by YodaEmbedding** [comment]
Same with the other settings, e.g. "Export As -> PDF".

Usually, I have to repeatedly click: crop, transparent background, download to PC.

If anyone's interested, here's some JavaScript to ease the task a bit:

```javascript
# Run this from the JavaScript Console when on the export menu.
$(".geDialog > div > div > input:nth-of-type(5)").checked = true
$(".geDialog > div > div > input:nth-of-type(6)").checked = true
$(".geDialog > div > div > input:nth-of-type(8)").checked = false
$(".geDialog > div > div > input:nth-of-type(9)").checked = true
$(".geDialog > div .geBtn:nth-of-type(2)").click()
$(".geDialog > div > div > div:nth-of-type(4) > select").value = "download"
$(".geDialog > div > div:nth-of-type(2) .gePrimaryBtn").click()
```

**Comment by yan12125** [comment]
Seems a similar issue as https://github.com/jgraph/drawio/issues/3375

**Comment by davidjgraph** [comment]
The advanced export doesn't exist any longer.
