### ISSUE TITLE
Embedding a diagram into notion leads to a white page with "undefined"

### ISSUE THREAD

**Issue by limpkin** [jgraph/drawio#3376]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When embedding (using /embed) a diagram on notion, a white diagram with "undefined" is shown.

**To Reproduce**
On draw.io
1. Files > Embed > Notion
2. Copy code and paste it into an /embed in Notion

**Expected behavior**
The diagram to show up

**Screenshots**
![image](https://user-images.githubusercontent.com/6170291/220639326-8598ede9-839d-40d5-b2e4-f14919b26c13.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 20.7.4

**Desktop (please complete the following information):**
tested on multiple browsers & OSes

**Comment by alderg** [comment]
What was the copied code?

**Comment by alderg** [comment]
And what embed link did you get from draw.io?

**Comment by limpkin** [comment]
https://viewer.diagrams.net/?border=0&tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&open=G1d1saXj9NvqDCHzjr3UTHW3ocsvJ9trLY

**Comment by alderg** [comment]
Hmm, it used to create an iframe, but now I'm getting this box instead:
![ff3b699d522a0de1a7bac1833abb054d](https://user-images.githubusercontent.com/921200/221218237-4fbbb688-7225-4239-b178-896eee98fd53.gif)

**Comment by limpkin** [comment]
could you try with https://viewer.diagrams.net/?border=0&tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram.drawio&open=Uhttps%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D1s1VPuXQoolO6TPSy2ZSMVbNtn7zzI87K%26export%3Ddownload ?
This is done with another google account with "everyone can read" permissions...

**Comment by sulkbliss** [comment]
I'm having a similar issue where the embed code given by the app itself results in Notion simply returning 

"Failed to execute 'atob' on 'Window': Tge string to be decoded is not correctly encoded."

Here's the embed

https://viewer.diagrams.net/?border=0&tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&open=RjZLJbsMgEIafhmMlY%2Bqo57hpokZVFx96RmZqkLCxCK7tPn1xGbwoitQTwzcLM%2F9AWF4PR8tb%2BWIEaJImYiDskaQpTbLEHxMZA8lSGkBllcCgBRTqB2Im0k4JuGwCnTHaqXYLS9M0ULoN49aafhv2ZfT21ZZXcAWKkutr%2BqmEk4E%2BxLEmfgJVyfgyTdBT8xiM4CK5MP0KsQNhuTXGBasectCTeFGXkPd0wzs3ZqFx%2F0l4LU%2F6nL0fn9Xb%2FvzRjnLH%2BF0aqnxz3eHA2KwbowLWdI2AqUhC2L6XykHR8nLy9n7nnklXa3%2Bj3sRyYB0MN%2Fuk8%2FT%2B24CpwdnRh8SEexQMfwxleO8X%2FWkUVa603yHjuPJqLr2o4g0UJl6XBfz5Vt%2BYHX4B

What's the deal

**Comment by alderg** [comment]
@sulkbliss Does it work when you click on [the link](https://viewer.diagrams.net/?border=0&tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&open=RjZLJbsMgEIafhmMlY%2Bqo57hpokZVFx96RmZqkLCxCK7tPn1xGbwoitQTwzcLM%2F9AWF4PR8tb%2BWIEaJImYiDskaQpTbLEHxMZA8lSGkBllcCgBRTqB2Im0k4JuGwCnTHaqXYLS9M0ULoN49aafhv2ZfT21ZZXcAWKkutr%2BqmEk4E%2BxLEmfgJVyfgyTdBT8xiM4CK5MP0KsQNhuTXGBasectCTeFGXkPd0wzs3ZqFx%2F0l4LU%2F6nL0fn9Xb%2FvzRjnLH%2BF0aqnxz3eHA2KwbowLWdI2AqUhC2L6XykHR8nLy9n7nnklXa3%2Bj3sRyYB0MN%2Fuk8%2FT%2B24CpwdnRh8SEexQMfwxleO8X%2FWkUVa603yHjuPJqLr2o4g0UJl6XBfz5Vt%2BYHX4B) directly in the browser?

**Comment by sulkbliss** [comment]
> @sulkbliss Does it work when you click on [the link](https://viewer.diagrams.net/?border=0&tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&open=RjZLJbsMgEIafhmMlY%2Bqo57hpokZVFx96RmZqkLCxCK7tPn1xGbwoitQTwzcLM%2F9AWF4PR8tb%2BWIEaJImYiDskaQpTbLEHxMZA8lSGkBllcCgBRTqB2Im0k4JuGwCnTHaqXYLS9M0ULoN49aafhv2ZfT21ZZXcAWKkutr%2BqmEk4E%2BxLEmfgJVyfgyTdBT8xiM4CK5MP0KsQNhuTXGBasectCTeFGXkPd0wzs3ZqFx%2F0l4LU%2F6nL0fn9Xb%2FvzRjnLH%2BF0aqnxz3eHA2KwbowLWdI2AqUhC2L6XykHR8nLy9n7nnklXa3%2Bj3sRyYB0MN%2Fuk8%2FT%2B24CpwdnRh8SEexQMfwxleO8X%2FWkUVa603yHjuPJqLr2o4g0UJl6XBfz5Vt%2BYHX4B) directly in the browser?

Seems to, yes

**Comment by alderg** [comment]
What browser, operating system, version, language etc?

**Comment by mksgfp** [comment]
I was getting the same issue and stumbled across a "workaround"

@limpkin your link, which is formatted per the Embed -> Notion -> Create workflow in draw.io gives you the link:

https://viewer.diagrams.net/?border=0&tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram.drawio&open=Uhttps%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D1s1VPuXQoolO6TPSy2ZSMVbNtn7zzI87K%26export%3Ddownload

If you open that link, the URL in the address bar updates to:

https://viewer.diagrams.net/?border=0&tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram.drawio&lightbox=1&chrome=0#Uhttps%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D1s1VPuXQoolO6TPSy2ZSMVbNtn7zzI87K%26export%3Ddownload

Using the second link works to embed in notion, whereas the draw.io provided link does not
[Note: the error shown `Not a diagram file` sometimes comes up as `Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.`]

<img width="884" alt="Screen Shot 2023-07-18 at 5 20 34 PM" src="https://github.com/jgraph/drawio/assets/40810531/65eec619-cdbb-4b90-a828-58ced88a2fbd">

**Comment by davidjgraph** [comment]
Please test again with 21.6.5
