### ISSUE TITLE
Win32/Zpevdo.A Windows Defender

### ISSUE THREAD

**Issue by SamuelColacchia** [jgraph/drawio#338]
When attempting to download the windows desktop version, windows defender flags it as trojan called Win32/Zpevdo.A. 

Download url

https://github.com/jgraph/drawio-desktop/releases/download/v8.8.0/draw.io-setup-signed-8.8.0.exe

**Comment by davidjgraph** [comment]
Logged as https://github.com/jgraph/drawio-desktop/issues/62
