### ISSUE TITLE
Rendering Latex Equations

### ISSUE THREAD

**Issue by AvivSham** [jgraph/drawio#3380]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I face problem when trying to render latex equations in drawio. If i try some simple equations like `$$\alpha$$` everything works as expected, but when trying `$$X\prime$$` I get the following error: `Uncaught RangeError: Maximum call stack size exceeded`. BTW after this message pops even regular commands like `$$X$$` are not rendered 
I tried to catch in which cases it happens and also for `$$\mathbb{R}$$` and `$$\mathcal{L}$$` the same error pops-up. (I didn't try every possible latex command of course).

**Expected behavior**
just to render latex equations as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/43371254/220918910-4b60644d-aa8f-460c-b8fc-491ee37bfb4d.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
- using web.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome 
 - Version: 110.0.5481.100

**Comment by davidjgraph** [comment]
What is the draw.io version?

Can you provide an example that reliable repeats this?

**Comment by davidjgraph** [comment]
Help menu shows the version.

That text does nothing for me, what do you see?

<img width="1276" alt="Capture d’écran 2023-02-23 à 13 33 48" src="https://user-images.githubusercontent.com/1761087/220921746-9256657d-430a-4f42-b19c-33653b0ff86c.png">

**Comment by AvivSham** [comment]
Make sure that `Mathematical Typesetting` is checked under `Extras` menu. 
The version is `14.4.3`
after you write for example `$$\alpha$$` you should click on the background and the formula should be rendered automatically.

**Comment by davidjgraph** [comment]
Math typesetting is ticked, it's shown in the image. Where did you get 14.4.3 from? Can you show a screenshot of the whole browser?

**Comment by AvivSham** [comment]
![image](https://user-images.githubusercontent.com/43371254/220932815-52f493d1-49f9-4986-b3b0-7bdeaf35936d.png)

**Comment by davidjgraph** [comment]
14.4.3 was deployed 2 years ago, there have been about 200 deployments since. I'm not sure how your browser is caching for so long, something is very broken here. Might one of those extension be interferring? What if you go to app.diagrams.net/clear.html with no diagrams.net tabs open and try again after?

**Comment by AvivSham** [comment]
Thanks it solved the problem!
