### ISSUE TITLE
blurry picture

### ISSUE THREAD

**Issue by Yegezw** [jgraph/drawio#3386]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The picture will have different sharpness depending on the location.
Let's say we have picture A and picture B, and picture A points to picture B, and something strange happens:
Among them, one of the images is blurry, and we can adjust the image left and right to make it clearer, but doing so will change the expected arrows of A and B.

**To Reproduce**
1. Paste picture A and picture B, they are both clear at this point
![image](https://user-images.githubusercontent.com/82441492/221502205-05f3c772-e1e6-4ccb-a642-2b7207a611e9.png)
2. Picture A points to picture B, and obviously picture B is getting blurry
![image](https://user-images.githubusercontent.com/82441492/221502763-b049d84f-af3a-442e-95a3-1ac11f6d318e.png)
![image](https://user-images.githubusercontent.com/82441492/221503333-91ec5911-a039-4f37-a3c4-969c6face3e9.png)

**Expected behavior**
The sharpness of the picture should have nothing to do with the location.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.8.16...

**Desktop (please complete the following information):**
 - OS: win 11

**Comment by alderg** [comment]
Could you attach the file.
