### ISSUE TITLE
Regression on Mermaid insertion

### ISSUE THREAD

**Issue by lilfaf** [jgraph/drawio#3389]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

Since the latest release, the insertion of Mermaid templates seems to be broken.

Inspector shows error: `ReferenceError: mxMermaidToDrawio is not defined`

**To Reproduce**
1. Go to Arrange -> Insert -> Advanced -> Mermaid...
2. Click insert
3. See error

**Expected behavior**

Diagram is inserted successfully.

**Screenshots**

<img width="730" alt="Capture d’écran 2023-02-27 à 14 10 14" src="https://user-images.githubusercontent.com/1571812/221575862-e385fa3f-5d67-487e-9e1b-dcbb9e02bf6f.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.8.20

**Desktop (please complete the following information):**
 - OS: Mac os x
 - Browser: Chrome
 - Version: 110.0.5481.177

**Comment by davidjgraph** [comment]
That's not a normal stacktrace. There's something in your environment interfering.

**Comment by lilfaf** [comment]
Hello @davidjgraph. Indeed it seems related to a Confluence integration we use. I'm closing the issue, sorry for the noise 🙏

**Comment by lilfaf** [comment]
@davidjgraph we did more testing with my colleagues and none of us can insert a `sequenceDiagram` (even the simplest example from the doc), no matter the browser used. But all other diagram types are working fine. In the end, I don't think it comes from my env.

**Comment by davidjgraph** [comment]
I followed the tests on https://app.diagrams.net/?splash=0 and the diagram inserts correctly. I'm using the same environment as the one you listed.

<img width="248" alt="Capture d’écran 2023-02-28 à 10 54 11" src="https://user-images.githubusercontent.com/1761087/221833588-ff414dc5-ee39-413f-8dc8-c6dc93039874.png">

**Comment by lilfaf** [comment]
Yes, flowcharts (and others) are working fine, only sequence diagrams are impacted.

This works:
```
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```

This fails:
```
sequenceDiagram
    participant Alice
    participant Bob
    Alice->>John: Hello John, how are you?
    John-->>Alice: Great!
```

**Comment by davidjgraph** [comment]
OK, yes, I can reproduce.

**Comment by m-mohamedin** [comment]
Will be fixed in the next release
Thanks for the report
