### ISSUE TITLE
Generic 3D shape to add any SVG image on surface

### ISSUE THREAD

**Issue by eduardomourar** [jgraph/drawio#339]
My main goal here is to draw isometric diagrams for Cloud systems (AWS, Azure, etc). A starting point would be to have a generic 3D shape (e.g. a square) in the AWS 3D library that can take a SVG as parameter. Then, hopefully, we can add that image on top of the shape.

Is this something we can do with mxGraph and Draw.io? Would it be beneficial to the community?

**Comment by eduardomourar** [comment]
I will update the feature in PR #340 to do the proper isometric projection as shown in image below:

<img width="1596" alt="isometric" src="https://user-images.githubusercontent.com/16357187/60737290-86dcc880-9f5a-11e9-9689-15da32068536.png">

**Comment by kimblew** [comment]
It would be great to have something like Junichi Yoda's shapes - (see http://www.visguy.com/2008/06/25/free-isometric-piping-shapes-for-visio/) particularly the cube, cylinder and fonts. I had made a tweak to his to allow colour (+/- a % of shade) and transparency which was useful adding additional flexibility for me.
![iso-test](https://user-images.githubusercontent.com/10983517/75126180-e582cc80-570c-11ea-8c53-f1fef2d3b012.png)

**Comment by woyczek** [comment]
We miss this issue.
