### ISSUE TITLE
Custom libraries don't persist browser page reload.

### ISSUE THREAD

**Issue by DavidBDiligence** [jgraph/drawio#3391]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Custom libraries don't persist through a browser page reload after being added to the left toolbar.

**To Reproduce**
1. Open a library using `File/Open Library from/Device...`.
2. See the library added to the left tool bar.
3. Reload the page in the browser.
4. The library is gone and has to be opened again.

**Expected behavior**
When I reload the page in the browser I expect the page to look the same as before, consistent with all other browser-based document editing applications.

**draw.io version (In the Help->About menu of the draw.io editor):**
- 20.8.23

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 110.0.5481.177

**Comment by davidjgraph** [comment]
You mention other browser-based document editing applications automatically load files from your file system at startup. Could you link one please so we can check how that's done as we do not know a technical route to achieve this. Thanks.

**Comment by DavidBDiligence** [comment]
Regardless of where the libraries are imported from I would expect the app to persist them in, e.g., `localStorage`, `indexedDB`, or within the document being edited.

**Comment by DavidBDiligence** [comment]
Because of your comment I switched to loading libraries via URL and that's a good workaround to my problem for now.
