### ISSUE TITLE
Set background of hatched shape

### ISSUE THREAD

**Issue by floongle** [jgraph/drawio#3393]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Yes. At the moment, if you want to have a hatched shape with a background, you need to make a copy of it, remove the hatching and sent a solid background colour. Then place the copied shape behind the hatched shape.

**Describe the solution you'd like**
It would be very useful to add a second fill colour option to the Hatched shape.

Here's how it could work:
![image](https://user-images.githubusercontent.com/44733236/221831452-3d781aa7-b422-4762-94eb-e8699f65ea65.png)

**Comment by jeeftor** [comment]
<img width="486" alt="image" src="https://user-images.githubusercontent.com/6491743/222268747-4fbc792b-895f-43da-8d7d-2c75d7cd7dce.png">

I just drop 1 shape on top of another and group it

**Comment by floongle** [comment]
You're right, that works, and I've shown in my original submission (see the first "I love ducks example" above)

I'm proposing in this feature request that one shape can manage both a hatch and a filled background so that if it ever needs to be changed in style the user doesn't have to ungroup, then edit and regroup.

**Comment by jeeftor** [comment]
I did realize that you had mentioned this after I posted my example but it was really pretty so I left it :)

**Comment by floongle** [comment]
IKR! Hatching is beautiful in diagrams.net.

I tell the people I work with that I use hatching just in case my diagrams get printed in black and white, so that they're still comprehensible without the colour (hatching can also be helpful for people with colour blindness I'm told too)... But deep down, I think they all know I use hatching because it's pretty.

Just few filled+hatched grouped objects in a diagram is manageable, but once you've got a whole bunch to deal with, changing things becomes no fun.

**Comment by makecent** [comment]
I am eager for such a feature.

**Comment by marcandrevigneault-abb** [comment]
+1
