### ISSUE TITLE
Confluence DC retention deleting older diagram revisions

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#3394]
Atlassian have released a new feature, [retention](https://confluence.atlassian.com/doc/set-retention-rules-to-delete-unwanted-data-1108681072.html), for Confluence DC.

`Retention rules allow you to automatically delete historical versions of pages and attachments, and purge deleted items from the trash.`

The case we looked at in detail had a number of diagrams showing as 404s. What had happened was:

There were 5 revisions of the diagram attachment. The previous page version had pointed to the latest diagram revision. Someone had reverted the page to a version where diagram revision 1 was referenced.

Revision 1 of the diagram was more than a year old and the retention system had deleted it. We assume that users see the diagram correctly when they revert the page (at least most of the time), but the attachment revision is later deleted.

There are two types of "revert" when it comes to draw.io diagrams, in the draw.io editor and page reverts.

In the draw.io editor, when a diagram is reverted we create a new version of the attachment with the diagram that was reverted. This mechanism is not effected by retention.

The other revert is a page revert. There we follow the attachment revision specified in the drawio macro.

**Comment by davidjgraph** [comment]
The solution needs to fulfill the following conditions:

- It cannot rely on users reading some documentation in order to take some action to prevent the issue. Admins will most likely never see the docs.
- It cannot rely on checking what the current retention delete period is. Retenion could be enabled at any time and suddenly delete large volumes of attachment revisions.
- It must, wherever possible, ensure the correct diagram revision is displayed.
- It cannot rely on warning users in a diagram with a message like "this diagram will be cleaned up by rentention in a month". That will cause confusion and the rentention period could decrease at any time.

**Comment by davidjgraph** [comment]
The proposed solution is to copy older diagram revisions to a new attachment with a known attachment name that includes the revision number of the diagram.

The first point we know something has happened in terms of reverting a page, is the drawio viewer is loading a version of the attachment older than the latest version.

At this point, is the attachment revision can be loaded we make this backup of the revision. That new attachment will not be deleted as it will only ever have 1 revision.

The problem comes if the page is reverted and the diagram revision is already deleted. This is probably something to address in a second phrase of this issue. Probable actions are either to 1) warn that the revision doesn't exist and suggest the user picks another version to display or 2) display the latest version of the diagram.

**Comment by m-mohamedin** [comment]
Done including second phase using (display the latest version of the diagram)

**Comment by davidjgraph** [comment]
Released in 11.1.1.

Summary of behaviour and testing:

- The issue occurs when a page is reverted and any drawio macro(s) point to an attachment version that is not the latest version of that attachment. When that happen there are one of two cases:
- The attachment revision exists. In this case make a copy of the attachment with a name indicating the diagram name and the version. Only 1 version of this attachment is ever created so rentention does not remove it. Release testing checked the version is correctly created on a page revert. Tested that version is displayed on page view. Tested that version is still displayed if the attachment revision that the macro is pointing at is deleted. Tested that editing a diagram that is using a backup revision correctly loads that backup and saves changes as the latest version of that attachment.
- The attachment revision does not exist. In this case the latest version of the diagram is shown. Tested the latest version is shown and editing the diagram edits that latest version, regardless of the revision in the macro. Tested saving saves as the latest version of the diagram.
