### ISSUE TITLE
app.diagrams.net open file from GitHub getting Repository not found error.

### ISSUE THREAD

**Issue by xundong** [jgraph/drawio#3396]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I have my draw io files saved to GitHub reposity. Today it started to stating on the "Select File" prompt with the following
"Repository not found"
I can see my relevant Reposity is private, but Draw.io has read and read write permission to the reposity.

I have cleared the browser cache several times too... but no luck
I am kinda convinced it's a authorization issue... but can't quite nail it down.

**To Reproduce**
1. Go to 'https://www.diagrams.net'
2. Click on 'File' then "Open from" then "GitHub"
3. Authenticate as require with GitHub
4. In the select file prompt, double click on my drawing repository
5. My repository opens in the Select File prompt, but with "Repository not found" 

**Expected behavior**
I expected to see all my draw io files in my selected Repository on GitHub (which they are there...)

**Screenshots**
![image](https://user-images.githubusercontent.com/33489013/222506473-9e7486ce-b9f5-4e31-b2d0-2d0694f833a6.png)
![image](https://user-images.githubusercontent.com/33489013/222506708-785ac797-8a0a-49ba-8181-a9f4849aa3a0.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.0.1

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
If I use the Open from Recent, the drawin field opens fine.
All my drawing files in the Repo main branch, and I have no other branchs in the drawings respository on GitHub.

**Comment by davidjgraph** [comment]
You haven't initialised the repo.

**Comment by terranean** [comment]
Same exact issue here. Accessed my repo's files this way last week with no issue. I unfortunately do not have any listed under "Open from Recent," so I cannot open them at all.

**Comment by gyaresu** [comment]
We just did a training session and one of my team had the same error. (all other folks on both mac and windows had no problem)

User was on macOS using both safari or chrome in private browsing mode

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by MxdGff** [comment]
I also ran into this issue and created a new graph that could not be saved to the github repository.I also ran into this issue and created a new graph that could not be saved to the github repository,

**Comment by davidjgraph** [comment]
Fixed in 21.0.2

**Comment by xundong** [comment]
Thanks! So how do I get 21.0.2 please? Cann't see any update links from within the app.diagrams.net

**Comment by davidjgraph** [comment]
Close diagrams.net tabs and load https://app.diagrams.net/clear.html

**Comment by xundong** [comment]
Thanks, done it. still 21.0.1
![image](https://user-images.githubusercontent.com/33489013/222689622-1211f8f0-4bfd-4e6b-863c-dab476217e55.png)

**Comment by xundong** [comment]
Yay! it's working for me now. Many thanks.

**Comment by Aheadboy** [comment]
> Close diagrams.net tabs and load https://app.diagrams.net/clear.html

not work for me yet

**Comment by Aheadboy** [comment]
> You haven't initialised the repo.

Yes! Finally ,after create one file in my repo it works!
