### ISSUE TITLE
Open already existing drawings No repository found

### ISSUE THREAD

**Issue by AXYZdong** [jgraph/drawio#3398]
Using Chrome browser to open already existing drawings in the repository of github. It shows that "未找到资源库"(translation: No repository found)

![image](https://user-images.githubusercontent.com/45477220/222637156-31acb383-f77d-4798-8291-2c11c22797aa.png)

**Comment by alderg** [comment]
Duplicate of https://github.com/jgraph/drawio/issues/3396
