### ISSUE TITLE
Option to export drawing with grid

### ISSUE THREAD

**Issue by peku33** [jgraph/drawio#34]
Hi.

It would be nice to allow exporting drawing to svg / image with grid.

It is very useful to show specific dimensions, etc.

Thank you.

**Comment by RoyiAvital** [comment]
Great idea!

**Comment by Bolthier** [comment]
Still no response?

This future would be really nice to have.

**Comment by peku33** [comment]
Well, any chance to increase the priority?
Opened this at Nov 28, 2016
63 thumbs up

I (we) still need it :D

**Comment by cmaggiulli** [comment]
Is this not available as a function?  I really need this.  I'd be willing to implement this.  Im not familar with the project do you accept pull requests?  If so are there any public JIRA's ?  If this requirement is written out in some story/tasks I'd like to do it.

**Comment by davidjgraph** [comment]
Is this not available as a function? No, otherwise the issue would be closed :).

do you accept pull requests? Yes

If so are there any public JIRA's ? If you mean, is there an issue tracker, yes, you posted this issue on it.

**Comment by cmaggiulli** [comment]
@davidjgraph can someone assign this issue to me?

**Comment by davidjgraph** [comment]
Added in 11.1.4

**Comment by GitMoleo** [comment]
> Hi.
> 
> It would be nice to allow exporting drawing to svg / image with grid.
> 
> It is very useful to show specific dimensions, etc.
> 
> Thank you.

Could you add an option for this in the advanced export menu?
