### ISSUE TITLE
Preset containers appear to not have their Container property set

### ISSUE THREAD

**Issue by slavistan** [jgraph/drawio#3406]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Preset containers appear to not have their `Container` property set. See the following screenshot showing a newly created vertical container and its property pane.

![image](https://user-images.githubusercontent.com/35600954/222906223-6a6581bc-4518-41e1-8c6b-891fd3497cee.png)

I've stumbled upon while this trying to use arbitrary shapes as containers, for which it's required to toggle on the `Container` property. Thus I found it odd to discover that built-in containers do not have this flag set and I though I'd let you know. Of the few I tried every built-in container seems to have this problem.

**draw.io version**
- 20.8.16 standalone electron build on Arch Linux

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
