### ISSUE TITLE
Lines in tables disappear when changing the colors of rows/columns in draw.io for Confluence Cloud

### ISSUE THREAD

**Issue by Bastesque** [jgraph/drawio#3410]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I color a table and then change the color of rows or columns again, the lines of the cells disappear (see video). If I go to Properties, I can check the single lines again, but I would rather have them visible all the time, so it matches the line color of the scheme I chose.

**To Reproduce**
1. Insert a table
2. Color in the entire table
3. Select a row or column

**Expected behavior**
See above

https://user-images.githubusercontent.com/68647048/223361776-dda6fbc4-40f9-4e51-b2d0-c615bc36e1cf.mp4

**Comment by mararad** [comment]
Reproduced in Chrome and FF with 21.0.6

Lines are shown as very thin or completly missing. It looks like line behaviour depends on 2 factors: if a row or a column is selected and if cells are selected separately or all at once by mouse hold selection.

https://user-images.githubusercontent.com/44292306/225022120-a8cb43b3-cbcd-447b-b855-853263dce228.mp4
