### ISSUE TITLE
[question]   automatic refresh

### ISSUE THREAD

**Issue by Fr-Dae** [jgraph/drawio#3412]
Hello, I have two similar questions.

context: I'm using draw.io for a game, and I'm generating a "read-only" sheet for organizing the players.

I'm not sure what the problem is with the viewer, but it is on two points.

- Is it possible to force the window to refresh regularly (e.g. every 5mn) or to have a direct update of the modifications?

- Is it possible to modify the "flowchart loading" window to have not white but a dark background, which avoids the white "flash" at each refresh 

thanks 

https://viewer.diagrams.net/?tags=%7B%7D&target=blank&highlight=0000ff&layers=1&nav=1&title=Edit-Unitystation.drawio#Uhttps%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D1-QHUdsSTg0QbBi6Ox3sjdFtMC4ed7X4R%26export%3Ddownload

**Comment by Fr-Dae** [comment]
like this , but by default 
![Capture d’écran du 2023-03-08 03-18-29](https://user-images.githubusercontent.com/23202421/223602589-450e4780-8984-4939-aa45-684d13970472.png)

**Comment by alderg** [comment]
Try adding rt=1 to the URL, eg. https://viewer.diagrams.net/?rt=1&tags=%7B%7D&target=blank&highlight=0000ff&layers=1&nav=1&title=Edit-Unitystation.drawio#Uhttps%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D1-QHUdsSTg0QbBi6Ox3sjdFtMC4ed7X4R%26export%3Ddownload

**Comment by Fr-Dae** [comment]
> Try adding rt=1 to the URL, eg. https://viewer.diagrams.net/?rt=1&tags=%7B%7D&target=blank&highlight=0000ff&layers=1&nav=1&title=Edit-Unitystation.drawio#Uhttps%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D1-QHUdsSTg0QbBi6Ox3sjdFtMC4ed7X4R%26export%3Ddownload

hello, adding "rt" change what exacly ?

**Comment by Fr-Dae** [comment]
for refresh or for black background ?

**Comment by alderg** [comment]
Refresh.

**Comment by Fr-Dae** [comment]
Interesting.
on the other hand, the document requires me to be logged in to google.
whereas before, unless I'm mistaken, it didn't ask that.

Is it possible to have the read-only view that is public without autentication?

**Comment by Fr-Dae** [comment]
@alderg

**Comment by Fr-Dae** [comment]
Or is it deliberate? @alderg

**Comment by davidjgraph** [comment]
The code of conduct says "Public or private harassment, including focusing on individual developers when a topic should be broadly addressed."

That's twice you've explicitly tagged someone. The second time is effectively "hey you, answer me". I will apply a seven day ban for this. Any further breach will lead to a permanent ban.
