### ISSUE TITLE
GitLab Sign Out link from dialog is broken

### ISSUE THREAD

**Issue by jaylapras** [jgraph/drawio#3416]
* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Click on _Sign Out_ after using GitLab as the storage location for diagrams. 
<img width="320" alt="image" src="https://user-images.githubusercontent.com/58732480/223988161-b7d44e8e-bb5d-404f-9188-cd7a668928bc.png">

-> Goes to the GitLab 404 broken link page. 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/58732480/223988211-54ecdd9f-fdb0-47c9-a5d1-ebb21277a275.png">

**Expected behaviour**
To be signed out and returned to the select storage location dialog.

- draw.io version: 21.0.4

**Desktop (please complete the following information):**
 - iOS
 - Safari
 - Version 16.2

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by davidjgraph** [comment]
Fixed in 21.0.6
