### ISSUE TITLE
segmentation fault on ubuntu 18.10

### ISSUE THREAD

**Issue by v217** [jgraph/drawio#342]
I get a seg fault with debian package and the app image on ubuntu 18.10 64bit. Thanks!

    v@v:~$ ./draw.io-x86_64-8.8.0.AppImage 
    Segmentation fault (core dumped)

**Comment by davidjgraph** [comment]
Use the [9.3.1 AppImage](https://github.com/jgraph/drawio-desktop/releases) instead. Dup of https://github.com/jgraph/drawio-desktop/issues/61
