### ISSUE TITLE
Show mermaid version in editor?

### ISSUE THREAD

**Issue by jeeftor** [jgraph/drawio#3422]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

I've seen a few issues (as well as run into them myself) by having a mismatch between the latest version of mermaid (v10.0.2) and whatever is in draw.io. 

**Describe the solution you'd like**

I wonder if it would be easy enough to add a little "Mermaid version 7.2" text blob to the mermaid input window or something?
![image](https://user-images.githubusercontent.com/6491743/224190848-f528d2d5-393a-4cf1-8139-01bd14e355ea.png)

I think this would be maybe somewhat easy ... I haven't really looked over the code so I don't know.
![Untitled](https://user-images.githubusercontent.com/6491743/224191146-3abf6889-cb7f-46f9-98f9-3220c58638db.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by Yokozuna59** [comment]
There's a workaround, mermaid have a diagram that shows the current version, simply type `info` and insert to see the version:

```mermaid-code
info
```

```mermaid
info
```

Although I'm 👍 to the idea, no need to do insert an svg to see the version then remove it.

**Comment by jeeftor** [comment]
This sounds like a HACK ... so I like it

**Comment by davidjgraph** [comment]
It's a perfectly good solution, no reason to change the interface. You can also see the version in https://github.com/jgraph/drawio/blob/dev/etc/dependencies/package.json.
