### ISSUE TITLE
Draw.io file siye is getting enormous

### ISSUE THREAD

**Issue by Postman76** [jgraph/drawio#3428]
For some reason, the file size that draw.io is cresting is getting huge and needs optimization a lot,

In my case, there is a diagram with multiple tabs (40+) and each of them has multiple embedded pictures in SVG format (file sizes between 5-15kB). And now the draw.io diagram is generating a file with a size of 300MB.

If calculating embedded picture sizes together these are still less than 1MB together, so why Draw.Io is creating such a huge file (300x times bigger than embedded pictures) from it?

**Comment by davidjgraph** [comment]
Any raster images embedded?

**Comment by Postman76** [comment]
Noup all images are very small svg images. Just wondering if the embedding somehow causes a file-increasing issue here.
Also tested exporting the whole drawing to the XML and HTML formats and both are getting as big as the original file.

**Comment by davidjgraph** [comment]
What are the reproduction steps?
