### ISSUE TITLE
Draw.io 9.3.1(Desktop, OSX, older Mac) crashed

### ISSUE THREAD

**Issue by AlbertMietus** [jgraph/drawio#343]
Hi,

I tried to run draw.io, but it constantly **crashes** when/before opening. See below for the messages that are logged. It does show noting; no window, no banner, nothing (but the log below)

I used: **draw.io-9.3.1.dmg**, on a *older* mac: MacBook Pro (15-inch, Late 2008); OSX 10.11.6 (El Capitan)

This is kind of a show-stopper ...
Hope this reports helps to make a fix, or suggest a workaround 

Thanks

Log:
> 05/11/18 11:54:30,849 draw.io Helper[54077]: <<<< VTVideoEncoderSelection >>>> VTSelectAndCreateVideoEncoderInstanceInternal: no video encoder found for 'avc1'
> 05/11/18 11:54:30,850 draw.io Helper[54077]: [11:54:30.849] VTSelectAndCreateVideoEncoderInstanceInternal signalled err=-12908 (err) (Video encoder not available) at /Library/Caches/com.apple.xbs/Sources/CoreMedia_frameworks/CoreMedia-1731.15.207/Sources/VideoToolbox/VTVideoEncoderSelection.c line 1308

**Comment by alderg** [comment]
f you are having trouble starting the application from the launcher in macOS after installation, try starting it from the Application folder the first time (it should then open from the launcher as well). See https://desk.draw.io/support/solutions/articles/16000083313
