### ISSUE TITLE
Can't change text background color only for specific icons

### ISSUE THREAD

**Issue by clayms** [jgraph/drawio#3432]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
For certain icons, like the `continuous deploy` rocket, I cannot change the text background color.  I also can't uncheck the text - background color. 

![image](https://user-images.githubusercontent.com/12793783/225458569-7e05dec8-32c3-4727-84e9-b9c0f9c2e6d8.png)

**To Reproduce**
1. search for "continuous deploy" insert the rocket icon shown above.
2. go to the "text" panel 
3. try and uncheck the "background color"
4. you can't uncheck it

**Expected behavior**
Should be able to uncheck it

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.8.10

**Desktop (please complete the following information):**
 - OS: Windows 10 and Linux
 - Browser chromium and drawio desktop app
 - Version v1.49.120 (Mar 9, 2023)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by davidjgraph** [comment]
Released in 21.0.7
