### ISSUE TITLE
Issue with Confluence and Github app connecting

### ISSUE THREAD

**Issue by marcvn-eng** [jgraph/drawio#3443]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

I have installed the draw.io app in my Github org and have a repository with a file I want to show on Confluence. The file loads perfectly fine in a repo readme and also opening the URL directly.

I then added the Confluence Plugin as a Trial to enable me to use the Github connectivity directly.

This is where it fails with 404 errors on the links. I then tried by setting my repo to public and when I did that and ticked private on the options for the confluence plugin, it suddenly loaded. Setting teh repo back to Private then breaks it. 

**To Reproduce**
1. Install Draw.io github app and Draw.io confluence plugin.
2. Create a private or internal repo on github with a draw.io diagram in it
3. Setup draw.io Github app to have access to that repo
4. Create new page on confluence and add embed macro for existing diagram
5. on the Github tab enter file name, repo owner (the org in this case), enter repo name and the branch

**Expected behavior**
Diagram loads as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/124168805/226326694-1ad0284e-e031-421c-ad7f-d294d7475f1f.png)
![image](https://user-images.githubusercontent.com/124168805/226326789-d7429fb0-2c54-494e-9c99-3f3f46a620ac.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

Latest Confluence app version

**Additional context**
I also tried by loading this from URL directly to see if that would have a different result but got a different error. Not sure if it is relevant or related, but thought I would post it.

viewer-static.min.js?__WB_REVISION__=287bcd092a0b477ba6d89669655ea34f:253 Refused to connect to 'https://github.com/cat-home-experts/Diagrams/blob/main/Incident-mgt-flow-copy.drawio.svg' because it violates the following Content Security Policy directive: "connect-src 'self'

**Comment by cathex-sam-holdaway** [comment]
Hi @m-mohamedin. I thought I'd check back in and find out if you'd had a look at this at all?

**Comment by m-mohamedin** [comment]
Hi @cathex-sam-holdaway,

Sorry for the delay.

I've tried it and it works. Can you please share with us the full file path from Github (e.g, https://github.com/jgraph/drawio/blob/dev/src/main/webapp/templates/business/accd.xml). I want to confirm that the file path is correct (in the previous example, filename/path is "src/main/webapp/templates/business/accd.xml")

**Comment by Wiegaz** [comment]
Hi, we are having the same issue.

404 from Github when trying to embed an existing Draw.io Diagram from our private Github Organization Repository in Confluence Cloud. 

Github Authorization is working fine, i can open the desired Diagram in draw.io natively, but not with the confluence app.

Any Update on this?

**Comment by m-mohamedin** [comment]
@Wiegaz  Can you please share with us the full file path from Github (e.g, https://github.com/jgraph/drawio/blob/dev/src/main/webapp/templates/business/accd.xml). I want to confirm that the file path is correct (in the previous example, filename/path is "src/main/webapp/templates/business/accd.xml")

Also, private checkbox is checked

**Comment by Wiegaz** [comment]
Hi @m-mohamedin,

Full file path: https://github.com/hpv-eG/Architecture/blob/master/model/Planned_Architecture.drawio

![image](https://github.com/jgraph/drawio/assets/97888850/4748efc5-18e6-4a90-b274-d15d55731981)

**Comment by m-mohamedin** [comment]
We use a GitHub App to access data in the repositories. Can you please make sure "draw.io for Confluence" have access to that repository

![Screenshot 2023-07-27 at 10 31 16 AM](https://github.com/jgraph/drawio/assets/24944765/95d5f784-9b1a-4db9-a724-3fb1b666b529)

**Comment by skhelishalnev** [comment]
I'm also having this issue with embedding from private repo.
Reported first here ==> https://community.atlassian.com/t5/Marketplace-Apps-Integrations/How-can-I-embed-an-existing-draw-io-diagram-into-Confluence-from/qaq-p/2073618#U2524897

**Comment by davidjgraph** [comment]
Does the OP still have this issue after checking the data access settings? For new users, please open new tickets as the underlying cause might be different.

**Comment by noeldamps** [comment]
@m-mohamedin I have the same issue now. I have installed drawio app but not the "drawio for Confluence" gh-app unfortunately i dont find the installation path. Can anybody please help me how to install the "drawio for Confluence" ?

**Comment by m-mohamedin** [comment]
> [@m-mohamedin](https://github.com/m-mohamedin) I have the same issue now. I have installed drawio app but not the "drawio for Confluence" gh-app unfortunately i dont find the installation path. Can anybody please help me how to install the "drawio for Confluence" ?

Please install from https://github.com/apps/draw-io-for-confluence
Let us know how it works

**Comment by noeldamps** [comment]
> > [@m-mohamedin](https://github.com/m-mohamedin) I have the same issue now. I have installed drawio app but not the "drawio for Confluence" gh-app unfortunately i dont find the installation path. Can anybody please help me how to install the "drawio for Confluence" ?
> 
> Please install from https://github.com/apps/draw-io-for-confluence Let us know how it works


Thanks, I already found it yesterday and it works fine 🙂 👍
