### ISSUE TITLE
Preview shows the newest version, but the app only has the older ones to edit. history did not save newer versions.

### ISSUE THREAD

**Issue by AnnyTp** [jgraph/drawio#3445]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Draw.io doesn't seem to save the newer versions of the drawing. A snapshot of the file shown as preview on the Google Drive folder has the most recent version. However when click on "Open with Diagrams.net", I get an old version of the diagram. Looking at the version history the current one is not the latest version saved. The xml files of the different versions are not reflecting such changes. 

**To Reproduce**
In my Google Drive account (a.tamez@handpoint.com) 
1. Go to Google Drive > SWP Journey
2. Select CroatiaBoard1, open it
3. Confirm lanes and structure included in the preview snapshot
4. click on "open with diagrams.net" above
5. Confirm that the lanes and structure differ from the snapshot. 

**Expected behavior**
When opening the file on Diagrams.net, I should see the diagram of the snapshot, not an older version of it. 

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io /Diagrams.net v 21.0.8

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome, although tested as well on Firefox and Safari
 - Version: 111.0.5563.64

**Additional context**
Could not include some xlm files of the older versions, no big changes on them. not reflecting the snapshot I worked on. 
<img width="1133" alt="Screenshot 2023-03-21 at 14 22 24" src="https://user-images.githubusercontent.com/75122471/226620062-59af1768-b030-44b5-a812-c90714c2014b.png">
<img width="1133" alt="Screenshot 2023-03-21 at 14 22 05" src="https://user-images.githubusercontent.com/75122471/226620064-ecb4b891-a573-4963-994f-bfb3c0216d1d.png">

**Comment by alderg** [comment]
What is the ID of the file (the part after the #G in the URL when opening the diagram with diagrams.net)?

**Comment by AnnyTp** [comment]
Thank you for looking into this! #G1YcAn4BcEhQF8hQt77A5dPVi09Ngzrfj3 that's the one I got.
