### ISSUE TITLE
draw.io Teams error "Unexpected token B in JSON at position 0"

### ISSUE THREAD

**Issue by SNHAjared** [jgraph/drawio#3446]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
draw.io files formerly working as tabs in Teams channel suddenly fail to open, with error "Unexpected token B in JSON at position 0".
These files are stored in the sharepoint associated with the Teams channel. When I download the files from sharepoint (so I'm sure its the same version of the file), they open normally in desktop and web versions of draw.io.

**To Reproduce**
I don't know. these same draw.io documents opened correctly in Teams yesterday.

**Expected behavior**
draw.io documents should open correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/92219968/226656183-18f9addc-2008-4810-ae6b-5f48e31e63de.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
21.0.8

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: MS Teams
 - Version: 1.6.00.4472 (64-bit)

**Additional context**
multiple different files, in multiple different Teams teams stopped working at the same time, and give the same error.

**Comment by davidjgraph** [comment]
Any error in the browser console?

**Comment by davidjgraph** [comment]
Not sure yet. Is it still working currently for you?
