### ISSUE TITLE
Ability to edit parent element in the properties of an object

### ISSUE THREAD

**Issue by a-magdy** [jgraph/drawio#3448]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I am using the Confluence Draw.io plugin to create an Azure Infrastructure diagram
which contains lots of elements, and I need to be able to move whole containers with their siblings quite often to reorder and add new features to the diagram
so right now, when I need to move a box with 5 elements, I have to move each one of them 5 elements with the box manually, doing that for every box is very time consuming as I'll have to select and move every single text, img and link

**Describe the solution you'd like**
I'd like to be able to correctly tell Draw.io what is the parent element of every item, so I when I move a box, Draw.io knows to move all associated children with it

**Describe alternatives you've considered**
I've currently migrated out of Confluence to the unofficial VSCode draw.io extension, which allows me to edit the XML code of the diagram, and then I can correctly set the parent id of the elements, there is a bit of manual work. but I only have to do it once

**Additional context**
I propose adding the ability to edit the (parent) element in the list of properties you show in the (Style) tab when selecting an element. updating it would reflect in the diagram
Or maybe add a button in the (Arrange) tab to (Set Parent)
In both suggestions above, the user would need to know the (id) of the parent element, which can be obtained from the (Style) tab at the top of the properties list
The expected result is when I move the parent element, all children move with it

**Comment by Tom5959** [comment]
[good]([url](www.oilpressstore.com))

**Comment by Hossy** [comment]
Any chance of getting this reopened and planned?  I'm running into the same problem and no matter how much I wiggle or move around an object, draw.io just won't get the parent right.
