### ISSUE TITLE
Firefox - InstallTrigger is deprecated and will be removed in the future

### ISSUE THREAD

**Issue by Ogglas** [jgraph/drawio#3456]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

When using [drawio-integration](https://github.com/jgraph/drawio-integration) I get the following warning from Firefox Developer Tools Console:

> InstallTrigger is deprecated and will be removed in the future. [app.min.js:150:422](https://embed.diagrams.net/js/app.min.js)

**To Reproduce**

Register on https://app.oplane.io/, open a product and edit a diagram. 

File containing the warning:

https://embed.diagrams.net/js/app.min.js

**Expected behavior**

Do not use InstallTrigger 

**Screenshots**

![image](https://user-images.githubusercontent.com/4015237/227204239-74cc4de4-b68f-4a42-b085-62753b36c4e3.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

https://github.com/jgraph/drawio-integration

https://embed.diagrams.net/

**Additional context**

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
