### ISSUE TITLE
Firefox - Partitioned cookie or storage access was provided to “https://embed.diagrams.net/?proto=json&spin=1&ui=min&libraries=1&libs=c4;threatModeling” because it is loaded in the third-party context and dynamic state partitioning is enabled.

### ISSUE THREAD

**Issue by Ogglas** [jgraph/drawio#3457]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

When using [drawio-integration](https://github.com/jgraph/drawio-integration) I get the following warning from Firefox Developer Tools Console that I have not seen before:

> Partitioned cookie or storage access was provided to “https://embed.diagrams.net/?proto=json&spin=1&ui=min&libraries=1&libs=c4;threatModeling” because it is loaded in the third-party context and dynamic state partitioning is enabled. [[Learn More]](https://developer.mozilla.org/en-US/docs/Web/Privacy/Storage_Access_Policy/Errors/CookiePartitionedForeign)

**To Reproduce**

Register on https://app.oplane.io/, open a product and edit a diagram in Firefox. 

**Describe the solution you'd like**

Does embed.diagrams.net need to access cookies or storage if editing an embedded SVG image in a HTML page? If not then I would like drawio to not demand access to these resources.

**Screenshots**

![image](https://user-images.githubusercontent.com/4015237/227204239-74cc4de4-b68f-4a42-b085-62753b36c4e3.png)

**Comment by Ogglas** [comment]
@davidjgraph Fully understandable. I could try to write a minimalistic project which reproduces this issue but the absolute fastest way would be to provide you with a test account. Is there anywhere I can send this to you in a PM?

**Comment by davidjgraph** [comment]
Please send to david@draw.io

**Comment by Ogglas** [comment]
> Please send to [david@draw.io](mailto:david@draw.io)

Fixed
