### ISSUE TITLE
Several images have suddenly disappeared

### ISSUE THREAD

**Issue by ralleman-quasarsat** [jgraph/drawio#3462]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
As of this morning, many of the images I had in one of my diagrams disappeared. These images have also disappeared from the shapes menu. Images were of spheres, planets and other similar objects that were selected from the shapes menu. The images are still present when I export to PNG. I can see that the image rectangles are still present. Examples of missing images:

<img width="125" alt="image" src="https://user-images.githubusercontent.com/93109812/227771329-c502bc69-ef9e-4552-898c-11b967ba91b0.png">
<img width="121" alt="image" src="https://user-images.githubusercontent.com/93109812/227771354-d2230f8d-29a1-4b17-8837-147962f0821c.png">

This is the shapes panel which was displaying a bunch of images:
<img width="387" alt="image" src="https://user-images.githubusercontent.com/93109812/227772368-4d802665-9d67-4654-9ad1-c19476266f6d.png">

**To Reproduce**
Uncertain how to reproduce, but I can confirm the issue is occuring in all browsers. The diagram is loaded from google drive.

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**
current on diagrams.net

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser: all

**Comment by alderg** [comment]
Are there any errors in the browser console? (See https://balsamiq.com/support/faqs/browserconsole/)

**Comment by ralleman-quasarsat** [comment]
Good thinking. Yes.
<img width="1655" alt="image" src="https://user-images.githubusercontent.com/93109812/227776353-e3fa7993-1499-4001-9f77-8abbe44b8058.png">

Some kind of cross origin issue perhaps.

**Comment by davidjgraph** [comment]
I'll close this issue. Server CORS headers are outside our control.

**Comment by davidjgraph** [comment]
Any browser extensions? Does it still happen incognito with extensions disabled?

**Comment by ralleman-quasarsat** [comment]
Hi @davidjgraph. All the images suddenly appeared again this morning. There must have been a fault on this site. This can be closed. Thanks.
