### ISSUE TITLE
Dark mode: font color of objects with custom background color should not be changed

### ISSUE THREAD

**Issue by YakovL** [jgraph/drawio#3464]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
In the dark mode, the default font color inside objects is switched to white. However, standart backgrounds (custom ones aside) are not changed, hence resulting in poorly-readable content:

![image](https://user-images.githubusercontent.com/1131924/227782532-d60a6522-2e24-4def-9e5e-3744b4b73598.png)

![image](https://user-images.githubusercontent.com/1131924/227782538-f77d3f9e-0905-466c-a1e3-84425054ee25.png)

**To Reproduce**
1. Create a box
2. Add some text to it
3. Set its background to one of the standart colors
4. Switch mode to dark

**Expected behavior**
I think due to a potential problem with custom colors, the simplest solution is not to update the font color if the background color is set. Another possible approach would be to set font color to "black" instead of "default" once a background color is set, but this may result in an inconsistent UX.

**draw.io version:**

- 21.0.2

**Desktop:**
 - OS: Windows 10
 - Browser: Vivaldi 5.7

**Comment by andrewler** [comment]
I have the same issue.
ERD are unreadable when Dark Mode is enabled.

![image](https://github.com/jgraph/drawio/assets/76549682/25af5cbe-680e-4fb5-aa05-bc9c70b89f56)

Drawio 21.3.5
Windows 11 22H2 22621.1702
Chrome Browser 114.0.5735.110 (Official Build) (64-bit)

**Comment by alderg** [comment]
Try uncheck and check the fill and lane colors:
![4f650cd88ca180461ce23b779978fbda](https://github.com/jgraph/drawio/assets/921200/3ca7de20-a6e2-4d0d-97e6-bd1a74c3a81a)
