### ISSUE TITLE
Column name cells in crossfunctional tables can't be adjusted all at once in Confluence Cloud

### ISSUE THREAD

**Issue by Bastesque** [jgraph/drawio#3468]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
A couple of months ago, it was possible to adjust the height of single column title cells by dragging the orange diamond, but also change the height of all column header cell at once by using a keyboard shortcut. This option is not around anymore, I tried all of the common draw.io shortcuts but it doesn't work. Is the shortcut broken?

**To Reproduce**
1. Embedd crossfunctional table with at least two columns
2. Try to change column title cell 1 (see screenshot)
3. Hold down Cmd, Ctrl, Alt etc. to change all column title cells

**Expected behavior**
Using a shortcut to change the height of all title cells when adjusting one cell instead of changing the height for every single cell in a crossfunctional table.

**Screenshots**

**Additional context**
![Screen Shot 2023-03-27 at 10 19 16](https://user-images.githubusercontent.com/68647048/227885068-66880c39-199a-412a-af4a-02a1b70d28bb.png)

**Comment by mararad** [comment]
Hi,

If you select cells in question and change Header size in Property/value does it help?

![header size](https://user-images.githubusercontent.com/44292306/227947573-9a3b1635-a028-4149-8e3c-8e22a49f40bd.JPG)

**Comment by mararad** [comment]
Hi,

If you select cells in question and change Header size in Property/value does it help?

![header size](https://user-images.githubusercontent.com/44292306/227947573-9a3b1635-a028-4149-8e3c-8e22a49f40bd.JPG)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by davidjgraph** [comment]
Released in 21.1.2
