### ISSUE TITLE
Domain issue with .vsd converter 

### ISSUE THREAD

**Issue by VirtualEvan** [jgraph/drawio#347]
I am trying to deploy a server with the .vsd converter, after some time receiving a 403 from my server I realized that there is [this](https://github.com/jgraph/drawio/blob/ae98ad585641179f4d819154c2979614c9e609c6/etc/vsd/VsdConverter/VsdConverter/Controllers/ConverterController.cs#L75) chunk of code which returns a 403 if the requesting domain is not one of your domains.

```
String origin = Request.GetCorsRequestContext().Origin;

if (!origin.EndsWith(".draw.io") && !origin.EndsWith(".jgraph.com") &&  origin.EndsWith(".quipelements.com"))
{
    throw new HttpResponseException(HttpStatusCode.Forbidden);
}
```

Am I missing some license which does not allow the use of this converter?
Maybe I am not in the right path to make this deployment and that is why I am getting this error, but I wanted to ask before continue into this.

**Comment by davidjgraph** [comment]
We didn't intend to release the vsd converter code, sorry, we just don't want to have to maintain stuff that runs on additional servers.
