### ISSUE TITLE
Add an option to enable editableCssRules of all elements in a library 

### ISSUE THREAD

**Issue by antoinekh** [jgraph/drawio#3471]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I am creating custom svg's and would like to be able to enable editableCssRules on all shapes at once.
Currently I have to do this by hand, by editing the style of all my objects to add editableCssRules=.*;

I tried to modify the mxlibrary xml file to add the option on each form but it is not taken into account

**Describe the solution you'd like**
Have the possibility to activate this option at once for a library or to modify it in batch in the mxlibrary xml file

**Additional context**
Similar to  Add support for specifying editableCssRules inside a library #2201

**Comment by janheussner** [comment]
style: 'editableCssRules=.*',
