### ISSUE TITLE
I think there is an issue with the hide/show functionality of the tags feature.

### ISSUE THREAD

**Issue by Guoxweii** [jgraph/drawio#3479]
**two images to illustrate my issue。**
first
![11111](https://user-images.githubusercontent.com/689550/228764551-451374a2-fdc9-4336-b28c-7acd263d2a0a.jpg)
second
![22222](https://user-images.githubusercontent.com/689550/228764574-f94a7f1a-8b87-4810-919b-e6fab6f4c097.jpg)

when i hide tags:Body, only one element is hidden.

In my opinion, in practical work, if a tag is hidden, all elements associated with that tag should also be hidden.

**Comment by Guoxweii** [comment]
Or there could be a place to configure the weight of hide and show tags.

**Comment by davidjgraph** [comment]
No, that would change existing behaviour. The next person would say that if any of the tags of a shape are displayed then the shape should be displayed. We cannot change this.

**Comment by Guoxweii** [comment]
Perhaps adding a setting would be a good solution, which won't change the existing behaviour.
