### ISSUE TITLE
PlantUML Cannot be Rendered on diagrams.net

### ISSUE THREAD

**Issue by ryewilson** [jgraph/drawio#3480]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I am unable to insert PlantUML diagrams into a draw.io diagram on diagrams.net 

**To Reproduce**
1. Open a new drawio diagram
2. Insert a plant UML diagram (Arrange -> Insert -> Advanced -> PlantUML)
3. Keep the default text (with Bob and Alice), but change the name of a request by adding an additional letter (change Request to Request1)
4. Click Apply
5. A box appears that says "Unknown error"

**Expected behavior**
The PlantUML is inserted into the diagram without error

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop:**
 - OS: Tried on both Mac OSX 13.2.1 and Windows 11
 - Browser Chrome and Safari
 - Version: 111 (Chrome), 16.4 (Safari)

**Additional context**

**Comment by davidjgraph** [comment]
This is known. There was an issue with Plant being out of date, it's been taken offline while we update it.

Note that we're not sure whether we're going to support PlantUML long term, it's a lot of work to update and not the core of what we do.

**Comment by davidjgraph** [comment]
New PlantUML version deployed.

**Comment by volnet** [comment]
https://www.drawio.com/blog/plantuml-mindmaps-from-text out of date
> Note that we're not sure whether we're going to support PlantUML long term, it's a lot of work to update and not the core of what we do.

**Comment by davidjgraph** [comment]
@volnet I don't understand your point.
