### ISSUE TITLE
OneDrive doesn't support files > 4MB

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#3481]
Version 21.1.2

Files over 4MB are returning this error:

![image](https://user-images.githubusercontent.com/1761087/229094701-e4a384e0-e2f7-4347-af61-d0145d0b1cbb.png)

From https://drawio.atlassian.net/browse/DND-950

**Comment by Nbeplate** [comment]
I have just received an error when trying to copy/paste additional images into draw.io file hosted on iCloud. Assume same issue? 
![image](https://user-images.githubusercontent.com/16955559/229687900-a1f7f946-a0df-4bff-908b-aeb6cf18bd7e.png)

**Comment by m-mohamedin** [comment]
Fixed. The fix will be available in the next release

**Comment by davidjgraph** [comment]
Released in 21.1.6
