### ISSUE TITLE
Gitlab SVG are not shown

### ISSUE THREAD

**Issue by niceborn** [jgraph/drawio#3482]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
After Release 21.0.7 svg files, that are stored directly in Gitlab over the interface are not shown as an image. Release 21.0.7 was the last Release where it worked. Opening of the files in Draw.IO afterwards works in all Releases.

![1680275398306-01](https://user-images.githubusercontent.com/19347993/229160665-26bfba84-430d-42ab-9e47-f9e0ecafdc45.jpeg)

Opening the file in a new tab shows this instead of the image:

![Screenshot_2023-03-31-17-17-32-276_com android chrome-01](https://user-images.githubusercontent.com/19347993/229162182-79c563cb-4f3e-47e6-b08a-1d6f654411db.jpeg)

**To Reproduce**
1. Add a new diagram and save as svg in Gitlab over the interface
2. Try to view the file in Gitlab
3. Image will not shown
4. Revert to 21.0.7
5. Open and save the image from and to Gitlab
6. Image is shown correctly

**Expected behavior**
The svg is shown within Gitlab.

**Screenshots**
please look above

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version after 21.0.7
- Gitlab 15.9.3 and Gitlab 15.10.0

**Desktop (please complete the following information):**
 - OS: jgraph/drawio image running on k3s
 - Browser Chrome, Edge on Windows and Android
 - Version latest

**Additional context**
-

**Comment by m-mohamedin** [comment]
Hi,

Unfortunately, I couldn't reproduce the issue on gitlab.com with draw.io 21.1.5

![Screenshot 2023-04-06 at 6 16 50 PM](https://user-images.githubusercontent.com/24944765/230503781-10203aee-af85-46fe-a688-e4fb4fc3d30b.png)

Can you please check the file mime type returned from your gitlab?

**Comment by niceborn** [comment]
Hi,

mimetype seems to be correct in all cases: content-type: image/svg+xml

But I think I found the reason: it's compression related. The old files were compressed and the newer files are stored uncompressed.

If I change the configuration setting in Browser to 
{
  "compressXml": true
}

diagrams for the newer releases from 21.1.nn are shown in GitLab again.

Is there a docker environment variable to enable this setting by default?

**Comment by niceborn** [comment]
Hi, 

I have found the setting DRAWIO_CONFIG by myself. Now it works.

**Comment by alderg** [comment]
GitLab seems to have a limit on the content attribute length of somewhere above 15 kB. (The preview is also broken for compressed filed if the content attribute is longer than that.)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/jgraph/drawio/issues/3482#issuecomment-1504980088

@alderg, if that's undocumented, might be a good idea to create a https://gitlab.com/gitlab-org/gitlab/-/issues/new with the "Documentation" preset.
