### ISSUE TITLE
Label snapping to connectors

### ISSUE THREAD

**Issue by eronlloyd** [jgraph/drawio#3485]
In drawing network diagrams, it's often helpful to have labels at the ends of a connectors, and sometimes in the middle, too.  Here is an example using draw.io to demonstrate the general idea:

![image](https://user-images.githubusercontent.com/197778/229306774-18251d67-8e05-474c-8c01-f5693d3a6514.png)

However, when the connector is moved, the labels do not remain aligned with the connector at the initial intersecting point:

![image](https://user-images.githubusercontent.com/197778/229306836-08ff8240-befa-4585-942d-1257bbf1e928.png)

This is in contrast to yEd, which allows labels to actually snap to the connectors and remain aligned when moved:

![image](https://user-images.githubusercontent.com/197778/229306901-bda0c33e-1c79-42fe-970e-009ace006f91.png)

yEd offers three default points that labels can be snapped too, even offset from the path of the connector itself:

![image](https://user-images.githubusercontent.com/197778/229307079-4b411f91-8fc6-468c-a734-f5cf745942c0.png)

It would be wonderful to have such label snapping in draw.io, as well. Thank you.

**Comment by alderg** [comment]
Try setting all values except "Left" to 0 in the Edit Geometry dialog (Ctrl/Cmd+Shift+M) and use center/middle alignment for the label. This will position the center of the label along the edge, where Left is a value from -1 to 1 (start to end).
<img width="244" alt="Screenshot 2023-04-03 at 14 13 53" src="https://user-images.githubusercontent.com/921200/229506621-492e8315-7db9-4fa8-a461-0d078e10910e.png">
<img width="236" alt="Screenshot 2023-04-03 at 14 15 30" src="https://user-images.githubusercontent.com/921200/229506635-a0e8150a-73be-45d0-b56b-ea7b5a8e2525.png">
<img width="264" alt="Screenshot 2023-04-03 at 14 14 54" src="https://user-images.githubusercontent.com/921200/229506648-5c74ff0a-a8bd-4e32-89e6-4e5d09c9315a.png">

**Comment by eronlloyd** [comment]
Thanks @alderg! It would be nice if there were some pre-existing snap points, but this is a helpful work around for now.
