### ISSUE TITLE
performance issues when working with lots of large image copied and pasted into the app and suggested solution 

### ISSUE THREAD

**Issue by HosamKsbaa** [jgraph/drawio#3486]
* [x] agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I experience performance issues when working with  lots of large image copied and pasted into the app  , i think the issue is the result of the app when u copy and past an image in it it is  storing the image data in the file itself. Currently, the solution i found is already implemented  but not efficient   is that  I have to manually save images from external sources to my local drive and then copy the path and insert it into the app, which is a time-consuming process.

**Describe the solution you'd like**
I would like the app to have an option (enabled by settings )  to automatically save any images that are copy and pasted into the app to a local folder in the same dir and reference them . This would improve performance by reducing the amount of data stored in memory and make the app much more faster , and would make it easier for me to insert images from Clip board without having to manually save them to my local drive first.

**Describe alternatives you've consideredv
As a workaround, I created a shortcut that saves images locally and pastes the link/path to the clipboard so that I can easily insert them into the app. However, this is still a multi-step process that could be streamlined by automatically saving images to a local file.

**Additional context**
I use my note-taking app frequently for taking screenshots and adding them to my notes, so this feature would greatly improve my workflow.

**Comment by davidjgraph** [comment]
How would it be ensured that the images are shared when a user shared a diagram file?

**Comment by HosamKsbaa** [comment]
This feature request is specific to a the desktop app :D

**Comment by HosamKsbaa** [comment]
but it is possible to implement a similar feature on a web-based application using the Google Drive API. The API allows you to programmatically upload images to a Google Drive folder, which can be accessed and referenced by your web application.

 It would also require the user to grant permission to the application to access their Google Drive account, which could raise privacy concerns.  but might be a good trade off

**Comment by HosamKsbaa** [comment]
> desktop


This feature request is specific to a the desktop app :D

**Comment by HosamKsbaa** [comment]
> How would it be ensured that the images are shared when a user shared a diagram file?
@davidjgraph 
but it is possible to implement a similar feature on a web-based application using the Google Drive API. The API allows you to programmatically upload images to a Google Drive folder, which can be accessed and referenced by your web application.

It would also require the user to grant permission to the application to access their Google Drive account, which could raise privacy concerns. but might be a good trade off

**Comment by davidjgraph** [comment]
> It would also require the user to grant permission to the application to access their Google Drive account

That's a non-starter, unfortunately.
