### ISSUE TITLE
"External changes" message after every single change

### ISSUE THREAD

**Issue by Rediwed** [jgraph/drawio#349]
As of a few hours there's a constant message about a external change having been introduced. I realise that due to changes at Google, collaboration has temporarily become impossible. However, this message comes up even though I'm the only one making any changes. And yes, I checked whether I had the drawing open on any other system or tab (this was not the case). Draw.IO has become impossible to be used, as every little drag, text manipulation or other edit pulls up that window.

**Comment by davidjgraph** [comment]
If you refresh you should find the dialog has been disabled.
