### ISSUE TITLE
Docker - Store files in the host

### ISSUE THREAD

**Issue by Issam2204** [jgraph/drawio#3495]
Not sure if I missed it somewhere, but is it possible to save the diagrams locally using the docker image? By locally I mean the following: provide a mounted location in my docker compose, and allow saving directly in that folder.

Currently, I can either save in the browser, or it will download the file whenever I click CTRL+S.

Thanks!

**Comment by davidjgraph** [comment]
No, we haven't implemented any backend for storage.

**Comment by cm-cot** [comment]
Hi, Thanks for posting this, I had the same question. Drawio in Docker on a Synology and was trying to figure out how to save to the Synology file system.

**Comment by davidjgraph** [comment]
Unfortunately, the same question will get the same answer, 8-). We haven't implemented any backend for storage.

**Comment by cm-cot** [comment]
Hi, sorry if it appeared I was asking the question again, I was not. Just commenting that I was searching for an answer and found it here. Thanks for the answers.

**Comment by mjkent** [comment]
@davidjgraph: I noticed you closed this as completed(found this looking where to map local storage for on docker). Has this feature been implemented? If not, do you know if there are any plans to complete it?

**Comment by davidjgraph** [comment]
Github didn't have the option to mark as not completed in the ticket, it does now, I've corrected the status.
