### ISSUE TITLE
Horizontal/Vertical DAG layout (Enhancement request)

### ISSUE THREAD

**Issue by Qazzquimby** [jgraph/drawio#350]
For items like dependency graphs, it would be very helpful to arrange as a Dag instead of a tree. This could be as lowering nodes based on their maximum depth rather than their minimum depth.

**Comment by davidjgraph** [comment]
The flow layouts under Arrange->Layout are DAG layouts.

**Comment by Qazzquimby** [comment]
@davidjgraph Thanks. 
I'd never realized because flow layouts are fairly illegible for my graphs, with children very far from their parents. [https://i.gyazo.com/0a3ee72fa881b53f3e8c0a072957868a.png](example)
Would asking for a way to keep children roughly centered on their parents be a reasonable enhancement proposal?
