### ISSUE TITLE
shape picker not working based on source shape

### ISSUE THREAD

**Issue by BorjaLL** [jgraph/drawio#3504]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When using the shape picker from a shape from the BPMN 2.0 library the options are the default ones.

**To Reproduce**
1. Create a diagram and add a shape from the BPMN 2.0 library
2. Hover over the blue arrow for the shape picker
3. Click the blue arrow for the shape picker
4. See only default shapes

**Expected behavior**
The shapes available in the shape picker should be from the library 

**Screenshots**
hover:
<img width="240" alt="Monosnap Monosnap 2023-04-12 11-28-17" src="https://user-images.githubusercontent.com/3930245/231431143-a2446505-29a0-48d6-87c9-bac4384e14b5.png">
click:
<img width="135" alt="Monosnap Monosnap 2023-04-12 11-28-37" src="https://user-images.githubusercontent.com/3930245/231431218-a9c12279-36cc-4548-a2c0-dc676a1efe8f.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [21.1.2]

**Desktop (please complete the following information):**
 - OS: MacOS
 - APP

**Additional context**
According to https://github.com/jgraph/drawio/issues/1812

**Comment by davidjgraph** [comment]
This isn't a bug, it's the expected behaviour.
