### ISSUE TITLE
shape replace not working as expected with BPMN 2.0 shape library

### ISSUE THREAD

**Issue by BorjaLL** [jgraph/drawio#3505]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**
1. create a diagram with the BPMN 2.0 shape library
2. add a shape
3. drag another shape over it

**Expected behavior**
the shape 

**Screenshots**
<img width="515" alt="Monosnap Monosnap 2023-04-12 11-41-24" src="https://user-images.githubusercontent.com/3930245/231434173-dba75e98-4a1a-4eca-801f-08402456da7b.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io desktop APP version [22.1.2]

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version [22.1.7]

**Additional context**
tested in the desktop app and the safari app

**Comment by martywesley** [comment]
I'm having the same problem with a custom library we use. We previously could drag/drop icon images from the custom library onto images on the canvas and they would replace that image. This no longer works with any of our custom library icons. 
It also doesn't work with the shapes from the BPMN 2.0 library. 
It DOES work with icons from the web icons file.

I've tested multiple browsers and multiple patterns of placing images on the canvas and then drag/drop replacement. The consistent problem is that BPMN library shapes (and our custom library images) will not update the image on the canvas.

OS: Linux
Browser: Chrome, Firefox, Edge
Drawio Version: 21.3.2

**Comment by davidjgraph** [comment]
Fix in 21.3.4

**Comment by lnclt** [comment]
Same problem with BPMN 2.0 and version 26.0.9 snap installed on xubuntu.

**Comment by davidjgraph** [comment]
If you feel the issue has recurred please open a new issue with details.
