### ISSUE TITLE
Error "Cannot read properties of null (reading 'replace') when importing a Visio VSDX file

### ISSUE THREAD

**Issue by maxsenft** [jgraph/drawio#3507]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When trying to import the attached Visio 2013 VSDX file (either using using drag-and-drop or the menu) [2080261 Blatt 1.zip](https://github.com/jgraph/drawio/files/11220197/2080261.Blatt.1.zip), after a short while I get the error "Cannot read properties of null (reading 'replace')".

**To Reproduce**
1. Open draw.io in the browser
2. Drag-and-drop the given file onto the drawing area or use the import method from the menu
3. See error

**Expected behavior**
The file is loaded and shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/37557143/231707558-a63cfe0a-11c9-4c2a-95b8-55d95e56d501.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 21.1.7

**Desktop**
 - OS: Windows 10 Pro 22H2
 - Browser: Chrome
 - Version: 111.0.5563.147 (Offizieller Build) (32-Bit)

**Comment by maxsenft** [comment]
Additional information: Just tried the same with Firefox 111.0.1 (64-Bit) and got the error message "p.Name is null".
![image](https://user-images.githubusercontent.com/37557143/231711164-d4544ef0-7392-44c7-b2c5-25d6cef7b095.png)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by davidjgraph** [comment]
Released in 21.1.8

**Comment by fatihbahceci** [comment]
The error still occurs in both the desktop and web apps when opening a VSDX file.
Sample file: 
[Sample_2025_09_10_10_19_11.zip](https://github.com/user-attachments/files/22249426/Sample_2025_09_10_10_19_11.zip)

<img width="587" height="400" alt="Image" src="https://github.com/user-attachments/assets/cf52d888-7b2e-4c15-9368-7cf4bb6fc2f1" />
