### ISSUE TITLE
App does not load on Firefox on iPad

### ISSUE THREAD

**Issue by brentco** [jgraph/drawio#3508]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Since recently the application either loads forever or shows that the app could not be loaded. In private mode it will get further but then show a JavaScript alert containing the message: "Error: Script error.".

**To Reproduce**
1. Open app.diagrams.net
2. App fails to load or keeps loading forever

**Expected behavior**
The app should load.

**draw.io version (In the Help->About menu of the draw.io editor):**

- 20.7.4

**Smartphone (please complete the following information):**
 - Device: iPad Air (5th generation)
 - OS: iPadOS 16.2
 - Browser Firefox
 - Version 111.2 (29672)

**Additional context**
I tried clearing my firefox data for:
* diagrams.net
* draw.io
* anything microsoft related as I was using onedrive as storage (perhaps an auth issue)

I had briefly played with it a few days ago and it was working then. I changed themes, drew some graphs and linked OneDrive. Today it will not load no matter what I try.

Additionally I tried clearing the cache using the /clear.html page. Didn't change anything.

**Comment by alderg** [comment]
Works for me.

**Comment by brentco** [comment]
Coindidentally, after seeing a comment on this I decided to give it another shot and it started working again. Perhaps the version bump (now 21.3.2) fixed something. I'd like to put emphasis on the fact that short of reinstalling Firefox nothing helped.
