### ISSUE TITLE
The move of the 'Movable Label' via Text-Control-Point is not correct. 

### ISSUE THREAD

**Issue by DanklR** [jgraph/drawio#3512]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The move of the 'Movable Label' via Text-Control-Point is not correct. 

**Expected behavior**
I want, that the text follows the text-control-point.

**Screenshots**
The text-setup is vertical.
![image](https://user-images.githubusercontent.com/41363611/232008035-69893c85-d106-4538-844e-ff3e4881b992.png)
If you move the text-point, that happens. The text moves in the opposite direction.
![image](https://user-images.githubusercontent.com/41363611/232008541-69436efd-8832-400c-8f3c-8777081353d3.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 21.1.5

**Desktop (please complete the following information):**
 - OS: Windows11
 - Browser Google Chrome

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by davidjgraph** [comment]
Released in 21.1.8
