### ISSUE TITLE
export fails if currently inside a group

### ISSUE THREAD

**Issue by adamfk** [jgraph/drawio#3516]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
If you are currently inside a group, and try to export an svg image, the created svg image is blank.

**To Reproduce**

1. Enter a group.
2. Click on 'File > Export as > SVG'
3. Open the created svg in a browser.
4. Notice that the svg is blank.

![export-from-within-group-fails](https://user-images.githubusercontent.com/274012/232233222-f5f9f8e9-3b41-41c8-afe9-dffb3871bd90.gif)

**Expected behavior**
Export would work like normal when not inside a group.

**Screenshots**
See above gif.

**draw.io version (In the Help->About menu of the draw.io editor):**
- diagrams.net 21.1.2 (windows app)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome Version 111.0.5563.147 (Official Build) (64-bit)
 - diagrams.net 21.1.2 (windows app)
 - Issue also occurs with online web version 21.1.7

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by davidjgraph** [comment]
Change in 21.1.9
