### ISSUE TITLE
Theme not changing in Microsoft Teams integration

### ISSUE THREAD

**Issue by autumnlewjb** [jgraph/drawio#3517]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Changing the theme did not take effect, even after reloading the Teams tab and restarting the whole Microsoft Teams desktop application. 

**To Reproduce**
1. Go to Menu > Settings.
2. Click on "Classic".
3. Click on the Teams tab again to extend the overlay menu.
4. Click on "Reload Tab".

**Expected behavior**
It should show the "Classic" UI, similar to the web version. 
![image](https://user-images.githubusercontent.com/49812781/232240580-b570911f-23ee-408d-a724-6b4a7d461d3b.png)

**Screenshots**
However, in Teams, this is what I get. 

![image](https://user-images.githubusercontent.com/49812781/232240917-67459c61-42e9-4e4f-a3d0-5975e7d37ff6.png)

**Microsoft Teams:**
 - OS: Windows 11 Home
 - Microsoft Teams Version 1.6.00.6754 (64-bit)
- draw.io version 21.1.8

**Comment by m-mohamedin** [comment]
Unfortunately, Teams app doesn't support other themes. The "Theme" menu will be removed in the next release

Thanks for the report

**Comment by davidjgraph** [comment]
Change in 21.1.9
