### ISSUE TITLE
Importing Visio VSDX: Cropping of graphics is not applied

### ISSUE THREAD

**Issue by maxsenft** [jgraph/drawio#3518]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When importing the Visio 2013 VSDX [2080261 HG1.zip](https://github.com/jgraph/drawio/files/11240450/2080261.HG1.zip) the cropping of the images is not applied.

**To Reproduce**
1. Open draw.io in the browser
2. Drag-and-drop the given file onto the drawing area or use the import method from the menu

**Expected behavior**
Cropped images as in Visio.

**Screenshots**
Visio:
Overview:
![image](https://user-images.githubusercontent.com/37557143/232249759-f1ba3450-6fd8-4bec-bda2-4efaf9d34ac7.png)

Cropping of top right image:
![image](https://user-images.githubusercontent.com/37557143/232249959-95902904-db26-462c-9e03-de7fe50a5245.png)

draw.io:
![image](https://user-images.githubusercontent.com/37557143/232249736-1788b42d-0e26-4635-8e50-79614328297b.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.1.8

**Desktop**
 - OS: Windows 10 Pro 22H2
 - Browser: Chrome
 - Version: 111.0.5563.147 (Offizieller Build) (32-Bit)

**Comment by m-mohamedin** [comment]
Will be fixed in the next release

Thanks for the report

**Comment by davidjgraph** [comment]
Change in 21.1.9
