### ISSUE TITLE
How do I extend drawio for collaborative editing?

### ISSUE THREAD

**Issue by anadon** [jgraph/drawio#352]
I'd like to add some functionality to allow for collaborative editing of flowcharts.  I'm not familiar enough with the technologies in drawio to be efficient, so where do I start?

**Comment by davidjgraph** [comment]
Honestly, if you're not familiar with a large scale JS application, and with collaboration technologies, you have no literally no chance of adding it, I wouldn't waste your time.

**Comment by anadon** [comment]
Please don't shut me down like this.  I've got all the theory, I just need a few of the tools.  Let me waste my time.

**Comment by davidjgraph** [comment]
OK, there :)

**Comment by anadon** [comment]
Thank you.  So I need to read up on electron, and mxGraph still seems to be the core of the model.  Where else should I read?
