### ISSUE TITLE
Update FAQ to clarify license of drawio syntax

### ISSUE THREAD

**Issue by twodrops** [jgraph/drawio#3520]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Large organizations need clarity on re-distruibuting open source code as well as other artifacts like drawio.

**Describe the solution you'd like**
The licensing of drawio as a tool is clear, but the license of the artifacts products by it or the syntax itself, is not really documented (or atleast I could not easily find it)

**Additional context**
A link to such a confirmation is needed by such organizations for documentation needs. For example, see [PlantUML FAQ](https://plantuml.com/de/faq). 
![image](https://user-images.githubusercontent.com/103930/232460100-177edccf-8b91-47cf-a0ce-f619791ea574.png)
![image](https://user-images.githubusercontent.com/103930/232460124-f244da5e-3d0f-4063-895c-d79239385bd4.png)
(Oops, information in the screenshots above are copyrighted by PlantUML )

I would like to have 2 FAQs in drawio FAQ/ documentation.

## What is the license of the drawio syntax?

If this makes sense, I can create a PR.

**Comment by davidjgraph** [comment]
Thanks for your feedback. Speaking about both areas in terms of licensing isn't correct in my opinion (IANAL), but this varies by location.

For licensing to apply there needs to be a copyright claim in the first place. For the first part we can add a clarification that we make no copyright claim to the content output, that's simple.

For the second part, copyright for a format is a difficult area in most geographies. Most laws, that I'm familiar with, enforce that you cannot restrict creation, usage, editing of a file format. 

I can confirm that we believe that such formats are not copyrightable and expect that we can make no such claim.

Note that it's more important that I make those statements here than in the README or similar place. Here I can be identified as someone with the authority to make these statements, as a director of JGraph I can do that. In a commonly editable file you run the risk that someone without the authority to make the statement adds it.

**Comment by davidjgraph** [comment]
Note that the statement in the PlantUML text "There are [sic] no license for the PlantUML syntax itself : this means that everyone can use it" goes against my understanding of licensing law.

If something copyrightable has no license then exactly the opposite applies, nobody can use it.
