### ISSUE TITLE
Saved files are empty

### ISSUE THREAD

**Issue by JacoduToi** [jgraph/drawio#3525]
Where did you save the diagram to?

_Originally posted by @davidjgraph in https://github.com/jgraph/drawio/issues/3353#issuecomment-1431026877_
            

Hi, I saved 4 files on my PC, and tried opening all of them this morning, all of them is empty. Blank canvass

how do I recover my work

**Comment by davidjgraph** [comment]
Please create an issue with the template filled in https://github.com/jgraph/drawio/issues/new?assignees=&labels=&template=bug_report.md
