### ISSUE TITLE
Saved drawings appear blank

### ISSUE THREAD

**Issue by JacoduToi** [jgraph/drawio#3527]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I built four models this past Friday, I exported them to PDF and saved them before closing
this morning I opened the models and they are blank

still saved under the correct name, but the models are blank

**To Reproduce**
1. Go to 'Save as...'
2. Click on 'Save....'
3. Close Diagram
4. Open Diagram
5. Diagram is blank

**Screenshots**
Please find blank files and pdf files attached.
[Operations Flow 1 (1).pdf](https://github.com/jgraph/drawio/files/11261055/Operations.Flow.1.1.pdf)
[OutboundLogisticsFlow1 (1).pdf](https://github.com/jgraph/drawio/files/11261056/OutboundLogisticsFlow1.1.pdf)

- draw.io version [e.g. 12.1.8]
file:///C:/Users/jacod/OneDrive/OneDrive%20-%20Senwes/General/Technology%20Delivery/Project%20Execution/Open/664_Hinterland%20B2C%20project/2.%20Solution%20Design/B2C%20user%20Journeys.drawio
https://app.diagrams.net/

![Draw io_OperationsFlow_Blank](https://user-images.githubusercontent.com/131147070/232762595-8b29d9d5-c5c9-49c8-8bff-f575185a86ef.JPG)
![Draw io_B2CProcessMapFlow_Blank](https://user-images.githubusercontent.com/131147070/232762605-7cffc543-64a4-4bc7-818b-1608257f5393.JPG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [edge]
 - Version [Version 112.0.1722.34 (Official build) (64-bit)]

**Comment by davidjgraph** [comment]
OneDrive has file revisioning, does the previous saved version of the file load?
