### ISSUE TITLE
I saved my file, but it cannot load.

### ISSUE THREAD

**Issue by ElMaelanthoMagnifico** [jgraph/drawio#3528]
When I try to open it within the app I receive the following error: Not a diagram file (error on line 42 at column 57: xmlParseEntityRef: no name).

File ended up saved as 2 different files (one HTML and one folder) - check attachments.

[Error files.zip](https://github.com/jgraph/drawio/files/11262039/Error.files.zip)

How can I restore my diagram ?

**Comment by davidjgraph** [comment]
Where were you storing the file? Locally, OneDrive, other?

**Comment by ElMaelanthoMagnifico** [comment]
The file is locally stored. I was working on it, and was saving it every 10-15 minutes because I was making a lot of changes. It seems that the last save broke it.

**Comment by davidjgraph** [comment]
Is this the desktop version? What version do you see under the help menu?

**Comment by davidjgraph** [comment]
You've performed a "save page", this is the HTML of the web site. You need to save within the application.

**Comment by ElMaelanthoMagnifico** [comment]
> Is this the desktop version? What version do you see under the help menu?

It is a Chrome version.

**Comment by ElMaelanthoMagnifico** [comment]
Can I somehow restore the graphic ?

**Comment by davidjgraph** [comment]
No, you haven't saved it, you've saved the web page itself. You can only recover if you have the previous save before the last one.
