### ISSUE TITLE
Add custom library to Draw.io (bpm online)

### ISSUE THREAD

**Issue by Diaskhan** [jgraph/drawio#353]
Hie gues its possible to add Bpm online nottation to Draw.io ?

Bpm online is bpm-crm system!
https://www.bpmonline.com/

If I add PR Could U accept it ?

**Comment by davidjgraph** [comment]
We don't add any libraries, only those with some volume of user demand. The process would be to create a [trello card](https://trello.com/c/YLjOl37T/430-add-bpm-online-stencils). If a card gets enough votes and interest, we might consider a PR.

If you need them quickly, your best route is to create your own library and load them from an external source, like [https://github.com/jgraph/drawio-libs](https://github.com/jgraph/drawio-libs).
