### ISSUE TITLE
Synchronize cannot be activated on Chrome, Edge & Desktop

### ISSUE THREAD

**Issue by denro67** [jgraph/drawio#3532]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I open a .drawio file from my local disk. It opens normally, I can modify it and save it.
When I try to activate Synchronize, a loading circle appears that won't go away, even after 10 minuntes. Below the circle is a dark banner stating "Updating Document. Please wait..."

**To Reproduce**
1. Go to 'File'
2. Click on 'Synchronize'
3. See circle and message

**Expected behavior**
Synchronize feature is activated and loading circle disappears.

**Screenshots**
![image](https://user-images.githubusercontent.com/108619180/233374922-5c3c82e6-0a6e-46e6-88ef-cc839772a689.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- Browser: draw.io version 21.2.0
- Desktop: draw.io-21.1.2-windows-no-installer

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise, 21H2
 - Browser Edge Version 112.0.1722.48 (Official build) (64-bit)
 - Browser Chrome Version 112.0.5615.121 (Official Build) (64-bit)

**Comment by alderg** [comment]
Is this still happening in the latest version 24.0.4?
