### ISSUE TITLE
KDE: drawio doesn't open via Kubuntu start menu (snap)

### ISSUE THREAD

**Issue by itsamemarkus** [jgraph/drawio#3536]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I install drawio on KDE (via Discover) I can't open it via start menu

**To Reproduce**
1. Install Kubuntu 23.04
2. Open Discover
3. Search draw.io
4. Install flatpack for draw.io
5. search for drawio and open it
6. nothing happens

**Expected behavior**
it should open. I think the access key in the properties might have something to do with it. If I delete `%U`, it works

**Screenshots**
![image](https://user-images.githubusercontent.com/34944988/233796724-1f176eff-03d3-4aca-9779-65c328f8e70a.png)

```
$ cat var/lib/snapd/desktop/applications/drawio_drawio.desktop
[Desktop Entry]
X-SnapInstanceName=drawio
Name=draw.io
Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/drawio_drawio.desktop /snap/bin/drawio %U
Terminal=false
Type=Application
Icon=/snap/drawio/173/meta/gui/icon.png
StartupWMClass=draw.io
Comment=draw.io desktop
MimeType=application/vnd.jgraph.mxfile;application/vnd.visio;
Categories=Graphics;
```

**draw.io version (In the Help->About menu of the draw.io editor):**

21.2.1

**Desktop (please complete the following information):**

![image](https://user-images.githubusercontent.com/34944988/233796995-22f915fc-81bb-4160-a09e-f8ad3810d41b.png)

**Comment by davidjgraph** [comment]
This would be better directed at the author of the flatpak draw.io distribution. I don't know who that is, without searching.
