### ISSUE TITLE
Tabs in shape labels converted to spaces when saving, closing, and reopening a diagram file

### ISSUE THREAD

**Issue by TechGeek01** [jgraph/drawio#3540]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When typing in labels for shapes (by double clicking on said shape), tab characters are insertable and behave as expected, and saving the diagram works perfectly fine. However, on loading the saved diagram at next program launch, the tabs are converted to spaces.

The effect here seems to be that each [tab] is converted to [space]. That is, 3 tabs converts to 3 spaces when reloading the saved diagram.

**To Reproduce**
1. Type in the label for a shape, and use tab characters
2. Save the changes to the diagram
3. Close and reopen the saved diagram
4. Tabs in labels are now converted to spaces after loading the file

**Expected behavior**
When tabs are inserted, given that tabs look and behave as expected before saving the diagram, it's expected that those tabs are preserved.

**Screenshots**
See attached screenshots. Spaces are used in the "name" column in this example to show a sort of nested hierarchy, but tabs are used to make the columns line up in a table-like format for each shape/line. In these examples, I'm emulating a table, but each line is its own shape with its own label
![Screenshot 2023-04-25 01_36_04-Home Network drawio - diagrams net](https://user-images.githubusercontent.com/3240812/234194517-8d4ee0c9-3f21-47aa-a5d0-d55291452057.png)

Upon saving the file, and closing and reopening the file again, the tabs have been converted to spaces, which makes the text "columns" no longer line up with each other.
![Screenshot 2023-04-25 01_32_41-Home Network drawio - diagrams net](https://user-images.githubusercontent.com/3240812/234194674-524e6489-fcb1-4ca2-9a57-303268d0cea5.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- Draw.io desktop 21.1.2

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2 build 22621.1555

**Comment by davidjgraph** [comment]
Thanks for report, fixed in 21.3.5.
