### ISSUE TITLE
Fillstyle:hatch - Scale fixed

### ISSUE THREAD

**Issue by Blutox** [jgraph/drawio#3542]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
A box with a fixed hatch is required. The scale currently changes depending on the zoom. That's not usable for my purpose.

![image](https://user-images.githubusercontent.com/130046415/234524464-8ebf6ef1-84ff-4f18-9138-6d1fb36a2906.png)

The first picture shows the box with a zoom 250%

![image](https://user-images.githubusercontent.com/130046415/234523472-ce1a3c91-aec5-4b52-94e6-15115126fa56.png)

The second picture shows the box with a zoom 400%

**Describe the solution you'd like**
A fix option or a custom scaled hatch would be a solution without the zoom affecting it. The scale and thickness of hatch could be set in properties.

**Additional context**
![image](https://user-images.githubusercontent.com/130046415/234529513-6f3a32eb-cce1-4536-8f1e-454ebb0b948a.png)
![image](https://user-images.githubusercontent.com/130046415/234529554-e05131b5-8a72-43e7-ac37-8b2457d2c20c.png)
I loaded this box into drawio as an SVG file. No matter which zoom, the proportions of the box and the fill remain the same.

Regards, Jay

**Comment by wagenaartje** [comment]
Same issue here. I can only see what the final hatch pattern looks like after exporting...
