### ISSUE TITLE
Problem to open draw.io diagrams saved file on owncloud

### ISSUE THREAD

**Issue by butyn13** [jgraph/drawio#3543]
### Preflight Checklist

* [ x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I'm having trouble editing drawio diagram files after April 18th. When I save any diagram, whether an existing diagram or a new one, I can no longer open it for editing, as the following error appears: "Error: This is not a Drawio file!". I'm using owncloud server 10.0.10 with drawio 0.0.9 plugin.
I don't know what else to do to safely edit and save my diagrams.

**To Reproduce**
1. Create or open an existing diagram inside the owncloud server (Web with google chrome)
2. Edit the diagram
3. Save and close the diagram
4. I try to open the saved diagram and the following error appears: "Error: This is not a Drawio file!". The diagram screen opens in white but with the loading animation and it doesn't come out of it.

**Expected behavior**
The diagram should open normally for editing.

**Screenshots**
![image](https://user-images.githubusercontent.com/35463068/234609003-479cfca2-2c76-4c76-bc51-27eb51aa33c5.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 0.0.9 (plugin)

**Desktop (please complete the following information):**
 - OS: W10
 - Browser Chrome
 - Version 112.0.5615.138

**Smartphone (please complete the following information):**
 - Device: Xiaomi 11T Pro
 - OS: Android 12
 - Browser Chrome
 - Version 112.0.5615.136

**Additional context**

**Comment by davidjgraph** [comment]
We're not the author of the owncloud plugin. If there is a listing page there might be a support page link.

**Comment by davidjgraph** [comment]
https://marketplace.owncloud.com/apps/drawio
