### ISSUE TITLE
file in OneDrive not found, due to format filtering

### ISSUE THREAD

**Issue by ionymikler** [jgraph/drawio#3547]
### Preflight Checklist

- [ x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [ x ]  I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When trying top open a file from OneDrive,it wont show up in the select file window. This is because OD automatically hides (or deletes) the .drawio format string in the name and then drawio wont display it for selection.

**To Reproduce**
1. Go to 'Open Existing Diagram' for OneDrive
2. Click 'Files'
3. Navigate to the folder containig the drawio file named <anything>.drawio
4. See the file not displayed

**Expected behavior**
4. find the file for selection

**Workaround**
name the file <anything>.drawio.drawio, so that the OD automation would only delete one of the suffixes and leave the second one

**Screenshots**

- draw.io version: webapp - firefox - ubuntu 22

**Additional context**
None

**Comment by mararad** [comment]
I can see it at my place but I am a Win user. 
![displayed](https://user-images.githubusercontent.com/44292306/235433306-bcee6dc1-3ad7-498d-a470-d3627c691423.JPG)

 I'll check if someone can test in Ubuntu. Could you attach a print screen showing the file is not displayed?
