### ISSUE TITLE
Add the "stage" dimension to the swimlane diagram.

### ISSUE THREAD

**Issue by PuckRadish** [jgraph/drawio#3551]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
While using swimlane diagrams to illustrate a process, I'd like to represent activities from two dimensions: "departmental division of labor" and "stages." This is the basic functionality of swimlane diagrams, but I haven't found a way to add the "stages" dimension in draw.io. I've consulted blog posts and YouTube tutorial videos (https://youtu.be/ITZeeN_PeWE) and tried various layout approaches, but I haven't found a straightforward and effective implementation. If this is an issue on my end, please provide instructions on how to achieve this. Thank you.

**Describe the solution you'd like**
This GIF demonstrates the implementation approach used in another application that I've tried.
![动画](https://user-images.githubusercontent.com/112269959/235125037-25555724-e9ad-4dcb-a699-839a4c774b72.gif)

**Describe alternatives you've considered**
Currently, I'm maintaining this functionality by manually adding components, but the results are not satisfactory. When resizing the swimlane diagram, I have to adjust many components to accommodate the changes.

**Comment by bajarobster** [comment]
Too bad this is closed; I would love this feature or a clear workaround.
