### ISSUE TITLE
Local file name doesn't have a same defualt name as disgram name

### ISSUE THREAD

**Issue by LovesAsuna** [jgraph/drawio#3555]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When I start a new disgram, I have finished specificing a file name, but then create a local storage, it does't have a same default name.

**Describe the solution you'd like**
the local file name should have a same file name as draw name

**Describe alternatives you've considered**
none

**Additional context**
![TX T6PVZV4_8S)18T4BXAU7](https://user-images.githubusercontent.com/32810896/235332747-e653b709-16de-4e8f-9af8-471105eb1635.png)
![QRSJ1UO4H`B8CSSFR%ZUXPT](https://user-images.githubusercontent.com/32810896/235332782-406bbf69-8f38-4f08-8392-7dbc1c9944f5.png)

**Comment by davidjgraph** [comment]
Fixed in 24.0.6. Thanks for report.
