### ISSUE TITLE
Import google drawings from google drive does not work

### ISSUE THREAD

**Issue by ragedblp** [jgraph/drawio#3556]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When importing Google Drawings from Google Drive into draw.io, I get an "Error loading file" popup saying "The owner has disabled options to download, print or copy for commenters and viewers on this file".
I'm using a Google Workspace with the same account as draw.io.
And I have already set all permission from draw.io to google drive and third-party cookies are allowed as it is recommended [here](https://www.diagrams.net/doc/faq/google-drive-diagrams) and [there](https://www.diagrams.net/doc/faq/enable-third-party-cookies).

**To Reproduce**
1. Go to 'File->Import from->Google Drive'
2. Double-click on a Google Drawings file
3. See error

**Expected behavior**
The Google Drawings file should be opened in draw.io without errors.

**Screenshots**
![Screenshot from 2023-04-27 16-57-44](https://user-images.githubusercontent.com/74249347/235604198-b3f31d9b-d1ab-43fa-88d6-30386370b771.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]
21.2.4

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: chrome
 - Version: 112.0.5615.165

**Comment by davidjgraph** [comment]
draw.io doesn't support importing Google drawings.
