### ISSUE TITLE
drawio-integration with embed.diagrams.net 21.2.8 causes malformed editor when scrollbar is present and UI is not on bottom of page

### ISSUE THREAD

**Issue by Ogglas** [jgraph/drawio#3563]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
This issue can be seen in your own examples. This works fine http://jgraph.github.io/drawio-integration/helloworld.html. However when using http://jgraph.github.io/drawio-integration/javascript.html with the scrollbar on top it will look like this when clicking to edit:

![image](https://user-images.githubusercontent.com/4015237/236270324-4580562b-91e6-4bda-8760-9b059387dbd3.png)

If you scroll to bottom it works fine:

![image](https://user-images.githubusercontent.com/4015237/236271321-4ab6a8f2-249e-4e9f-b4da-e0fef1c8b0e1.png)

Is there anyway to pin https://embed.diagrams.net/ version to avoid bugs like this in our production environment?

**Expected behavior**
A working diagram editor even when a scrollbar is present 

**draw.io version (In the Help->About menu of the draw.io editor):**

I can not see version but https://embed.diagrams.net/ says 21.2.8.

- draw.io version 21.2.8 

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser Chrome
 - Version 113.0.5672.64 (Official Build) (64-bit)

**Comment by davidjgraph** [comment]
Thanks for the report, this is fixed in 21.2.9. If you can't get it to update try embed.diagrams.net/clear.html

We don't currently have pinning. It could be possible, but we've no idea how many are using are using embed, maybe worth a feature request and see whether it gets votes.

**Comment by Ogglas** [comment]
@davidjgraph Thank you for the fast response and fix! I wrote a feature request for version pinning here: https://github.com/jgraph/drawio/issues/3566
