### ISSUE TITLE
Custom diagram libraries cannot be edited or saved after expanding them

### ISSUE THREAD

**Issue by pjmavcom** [jgraph/drawio#3565]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Custom diagram libraries cannot be edited or saved after they have been expanded. Only one of these can consistently be edited. Clicking the +, pencil or x button only expands or collapses the other custom libraries.

This was referenced in topic #3323 -  Can not save customized library anymore, but it doesn't fix this issue. It kind of sounds like it might be the same thing, but the first sign I noticed was the buttons just expand and collapse that section instead of allowing it to be edited or saved.

**To Reproduce**
I have three custom libraries I am using, but this works on opening a fourth one too.
On opening the app, only one of those libraries is expanded, but they can all be edited.
Expanding a library causes all of its buttons (the +, pencil and x) to all expand or collapse that library. It cannot be edited or saved now.
After expanding all libraries, only the original one that was open can be edited.

**Expected behavior**
The buttons to work as intended, edit, add or close the library.

**Screenshots**

- diagrams.net desktop version 21.2.1
- OS: Windows 10 21H2
- Firefox 112.0.2

**Comment by pjmavcom** [comment]
I just tried something new. I closed and reopened the app, then removed all libraries with their respective x button (since these buttons work before expanding the library).
I then added the libraries back with the File | Open Library menu command. They are all able to be consistently edited and saved now.
But just for that session. Closing and reopening the app produces the same results as before.

**Comment by axefrog** [comment]
I am also experiencing the same issue and came here to report this bug.

**Comment by TechGeek01** [comment]
This is the exact same issue I'm experiencing as well, with the same symptoms. WIn11 Pro 22H2 build 22621.1702, Draw.io version 21.2.1, but I can't even open the app, either via start menu or by opening a diagram file at the moment.

**Comment by TechGeek01** [comment]
This is the exact same issue I'm experiencing as well, with the same symptoms. WIn11 Pro 22H2 build 22621.1702, Draw.io version 21.1.2, but I can't even open the app, either via start menu or by opening a diagram file at the moment.

**Comment by axefrog** [comment]
@davidjgraph I think people are just reporting based on what they're using. The bug is in the web interface too.

**Comment by pjmavcom** [comment]
Sorry David, I didn't realize there were two separate forums for each one. Should I re-post this there, or can it be moved?

**Comment by TechGeek01** [comment]
Yep, can confirm. Was following a thread about a similar instance of this that may or may not be the same issue on desktop, and saw that issue was mentioned in this one, so I jumped here. More than happy to either open an issue, or chime in if someone else opens a new issue there!

**Comment by alderg** [comment]
> @davidjgraph I think people are just reporting based on what they're using. The bug is in the web interface too.

Which version of the web interface?
