### ISSUE TITLE
[FEATURE] GPT to create diagrams

### ISSUE THREAD

**Issue by luketych** [jgraph/drawio#3568]
Since diagrams are represented in xml I thought it would be feasible to train a gpt system to create a basic diagram which I could build off of.

**Comment by davidjgraph** [comment]
Like https://www.diagrams.net/blog/smart-diagram-generation?

**Comment by davidjgraph** [comment]
@magedhelmy1 your request seems to be different to the original. Please open a new ticket with a specific request. Please be brief but explain the request precisely.
