### ISSUE TITLE
Text snapping/positioning problem when dragging

### ISSUE THREAD

**Issue by JesseAldridge** [jgraph/drawio#357]
![screen shot 2018-11-26 at 1 39 45 pm](https://user-images.githubusercontent.com/191903/49043834-ff87d500-f180-11e8-941b-ec2be5b40d30.png)

<hr>

![screen shot 2018-11-26 at 1 49 11 pm](https://user-images.githubusercontent.com/191903/49044265-12e77000-f182-11e8-9389-030663721bfb.png)

In the screenshots above I drag the "test 3" label to be slightly below and to the right of "test 2". But when I get too close to "test 2" those "I-beam" symbols appear and the cursor snaps to be right on top of "test 2". I don't understand the purpose of this feature, since it results in the moved label being dropped directly on top of the other one rendering both illegible.

I think this is a new feature? I don't recall this happening before. Does the Draw.io desktop app automatically update itself?

I realize I can hold the option key to prevent this snapping from occuring, but I move text around a whole lot and having to hit option every time is annoying and slows me down considerably.

**Comment by alderg** [comment]
Fixed in 9.5.0.
