### ISSUE TITLE
Save and close diagram then i lose all data

### ISSUE THREAD

**Issue by Silence-7** [jgraph/drawio#3572]
i open a created diagram, just edit it. Then i save and close. But i find the file turn to 0kb.i lose all the data.
How can i get it back? It's a 50+kb diagram, i used 2 week to draw it.

**Comment by SoundaryaKoutharapu** [comment]
where did you saved the data.?
(google drive / device...etc)

**Comment by Silence-7** [comment]
> @Silence-7 where did you saved the data.? (google drive / device...etc)

On local disk D，the same place， i used SAVE not SAVE AS.
Maybe the file is too large, i close the diagram before saving is complete.
