### ISSUE TITLE
Sharepoint Add-in?

### ISSUE THREAD

**Issue by mrdeadlocked** [jgraph/drawio#3574]
* [X ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I would love to see this as a SharePoint Add-in so that the files can be hosted on a SharePoint site and directly edited inside of that one workspace.

**Describe the solution you'd like**
QOL improvement to allow better SharePoint functionality

**Describe alternatives you've considered**
Individually application installation on every machines across org.

**Comment by davidjgraph** [comment]
We wrote an add-in, but the dependencies for a sharepoint add-in are too insecure for us to publish it. Unless the security position of the dependencies massively improve, we will never be able to publish it.

**Comment by mrdeadlocked** [comment]
Good to know. Thank you!
