### ISSUE TITLE
Collapse not working on grouped elements.

### ISSUE THREAD

**Issue by YouRQ** [jgraph/drawio#3576]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Collapse not working on grouped elements. Clicking minus sign and nothing happens.
It was working on version 18 what i used before.
Bug is in desktop version, on browser it's working.

**To Reproduce**
1. Open or add any grouped element
2. Click on minus sign
3. Nothing happens

**Expected behavior**
Collapsing elements like in v18

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [21.2.8]

**Comment by mararad** [comment]
How did you group elements exactly, please? It would be great if you could attach a printscreen/video showing the steps and the result.

You mentioned the issue is in the desktop version. Which Os are you using?
