### ISSUE TITLE
Draw.io desktop installer fails with Win32

### ISSUE THREAD

**Issue by StinkerB06** [jgraph/drawio#358]
If you try to run the installer on Win32, it doesn't work, on Win64 it does. When I uploaded the file to VirusTotal, it said it was a "Win32 EXE".

I've used the web version of draw.io in the past without issues, until today when I discovered the desktop binaries. Since web applications require more resources on the computer, the speeds of the desktop versions should be more comfortable to work with.

Do you have anything to do with the installer not working?

**Comment by davidjgraph** [comment]
https://desk.draw.io/support/solutions/articles/16000078648-is-there-or-will-there-ever-be-a-32bit-windows-version-of-draw-io-desktop
