### ISSUE TITLE
Some fields of C4 diagrams are mixed up

### ISSUE THREAD

**Issue by Igorgro** [jgraph/drawio#3581]
Some fields of C4 diagram elements are mixed up. For example, web browser container (mixed type and name):
![image](https://github.com/jgraph/drawio/assets/22894169/3d9b4696-5815-48d8-bf73-1874aef4de06)

The same for database container and probably other elements (I did not checked them all)

**Comment by rowan-trade** [comment]
This creates a bit of confusion. It doesn't make sense that it is inconsistant:

![image](https://github.com/jgraph/drawio/assets/113126667/0f123117-9605-4c6d-bb7d-4736d993270a)

**Comment by davidjgraph** [comment]
I don't understand the issue from this description.

**Comment by Igorgro** [comment]
@davidjgraph when I'm creating 'Software system' element, then all fields are mapped correctly:
![image](https://github.com/jgraph/drawio/assets/22894169/cc895c78-a150-47de-9060-45278719a8ae)
![image](https://github.com/jgraph/drawio/assets/22894169/13103f04-056c-4910-bba2-860b1bda889c)

But when I'm filling 'Database' or 'Microservice container' elements, then the fields are mixed up:
![image](https://github.com/jgraph/drawio/assets/22894169/b822e6ce-cd42-4861-9e7d-8049275e1289)
![image](https://github.com/jgraph/drawio/assets/22894169/11ddf9d2-f885-4f12-b398-f51fd300cac2)

There is a field 'c4Container' which is actually must be a 'c4Type' and a `c4Type` which actually must be 'c4Type', the same for the 'Microservice container' and some other elements

**Comment by jhdowney** [comment]
It looks like this commit https://github.com/jgraph/drawio/commit/ac77e295d4dfcdf65252a0dd634d3efc75b40973 looks like it should have addressed the problem described in this issue. 
However, it doesn't look to me like the changes then made it into the 15.7.1 release (https://github.com/jgraph/drawio/commit/de8b542fe2cab9ba4fae8be69110f70ae2dbed8e) or any subsequent releases: 
There is some discussion about the missing changes in https://github.com/jgraph/drawio/issues/2345

**Comment by davidjgraph** [comment]
Is this still incorrect? If yes, still the same problem?

**Comment by Igorgro** [comment]
Yes, just checked now in app.diagrams.net, nothing is changed

**Comment by davidjgraph** [comment]
Yeah, none of these PRs are going to fix the issue because this isn't the development repo, it's a mirror.

**Comment by davidjgraph** [comment]
Fixed in 24.2.0.

**Comment by Igorgro** [comment]
@davidjgraph After this fix there are some strange `%` appars:

![image](https://github.com/jgraph/drawio/assets/22894169/acaa27c0-428f-4f7a-b61b-bdccc56e4ccb)
![image](https://github.com/jgraph/drawio/assets/22894169/ec27ee9a-967a-4d41-8e84-731b51ba2b04)

**Comment by davidjgraph** [comment]
New issue please.

**Comment by davidjgraph** [comment]
The fix for caused https://github.com/jgraph/drawio/issues/4300. The fix for that caused https://github.com/jgraph/drawio/issues/4312.

I have no idea what C4 is or what it's supposed to show. A user needs to take charge of this, otherwise we'll just remove the C4 set.
