### ISSUE TITLE
Import .VSDX via drag and drop only creates 1st tab

### ISSUE THREAD

**Issue by mitch1927** [jgraph/drawio#3587]
### Preflight Checklist

* [Y ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [Y ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When importing a .VSDX file with multiple tabs in the online version. A new blank diagram is created and the .VSDX file is dragged onto the blank page. Once the mouse button is released the diagrams.net page shows the drawing that was on the first tab of the .VSDX file. Other tabs that are in the VSDX file are not imported or displayed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Browser, type draw.IO in the URL, 
2. click create new diagram, 
3. select blank diagram and create, 
4. select the folder to store the file. 
5. Drag a Visio (VSDX file having multiple tabs onto the blank page.
6. The diagram contained on the first page of the VSDX file is displayed.
7. No other tabs are created.

**Expected behavior**
All tabs within the .VSDX file are expected to be recreated in the Draw.IO diagram

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):** = 21.2.9...

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 113.0.5672.92 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by davidjgraph** [comment]
And file->open?
