### ISSUE TITLE
Regression with regards to copy/paste and image metadata

### ISSUE THREAD

**Issue by allokera** [jgraph/drawio#3588]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
For a long time it was possible to collaborate using "copy as image" and for the recipient to paste the image into drawio. Drawio would auotmatically extract the metadata from the pasted image and recreate the diagram from that rather than dumping the static bitmap onto the canvas. This procedure no longer works and is disruptive to established collaborative workflows.

**To Reproduce**
1. Sender selects the portions of a diagram in drawio
2. Sender goes to the 'Edit' menu or right-clicks on the selection
3. Sender clicks on 'Copy as image' in the menu
4. Sender pastes the image into communication tool of choice (Microsoft Teams, Outlook, SharePoint, Confluence, etc.)
5. Sender transmits the image to recipient
6. Recipient receives the message
7. Recipient opens message
8. Recipient copys the image
9. Recipient pastes the image into drawio using ctrl+v
10. Recipient gets a static bitmap rather than a editable diagram

**Expected behavior**
I expect the editable diagram to be recreated in the recipients drawio rather than a static bitmap like it used to work.

**Screenshots**
N/A

**draw.io version (In the Help->About menu of the draw.io editor):**

- diagrams.net 21.2.8

**Desktop (please complete the following information):**
 - OS: Microsoft Windows Enterprise 10.0.19045
 - Browser: Edge
 - Version 112.0.1722.64 64-bit

**Additional context**
Same problem occurs in the desktop app.

**Comment by davidjgraph** [comment]
Step 4, what communication tool? Are you certain that tool resampling the image?

Step 9 paste following what steps?

**Comment by davidjgraph** [comment]
I can't repeat this. A number of host tools are stripping the data out of the PNG, most likely by accident, but that's an issue for the tool where the image is stored, we cannot have any control over that.
