### ISSUE TITLE
Unable to authenticate to Google using Firefox

### ISSUE THREAD

**Issue by borisvu** [jgraph/drawio#3590]
**Describe the bug**
A regression of older issue https://github.com/jgraph/drawio/issues/2180.
When opening the  113.0 using Firefox, it's impossible to login to Google Drive.
When choosing an existing diagram (or a saving new one), I'm presented with Log In screen modal.
Clicking on SIGN IN link opens a pop-up window for a moment that it almost instantly closes.
User is back to Login modal.
Clicking on SIGN IN link opens a pop-up repeats the process, but now I'm presented with an error from Google:
```
400. That’s an error.
The server cannot process the request because it is malformed. It should not be retried. That’s all we know.
```

- draw.io version 21.2.1

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Browser Firefox 113.0

Google Workspace account (as opposed to gmail.com)
Pop-up windows are enabled for the website `app.diagrams.net`.
No exceptions were present in the console.

**Comment by davidjgraph** [comment]
Browser extensions? Does it work in private window?

**Comment by borisvu** [comment]
Tried in private window found this odd issue.
Popup got stuck on URL:
```
https://app.diagrams.net/google?state=cId<reducted>mp.apps.googleusercontent.com%26domain%3Dapp.diagrams.net%26token<reducted>&code=<reducted>&scope=profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.file+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.install+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile
```
Not closed automatically afterwards.
Closed the popup and reloaded the window - was able to use the app.

Privacy badger and AddblockPlus were disabled before opening the ticket.
Cleared cache didn't help.

Played disabling and enabling  some unrelated plugins somehow got logged in and able to save.
I'll try pinpointing the reason later on.

**Comment by davidjgraph** [comment]
It's a browser extension.

**Comment by clushie** [comment]
Issue for me was because of https://github.com/ClearURLs/Addon/issues/329
