### ISSUE TITLE
A lane in cross-functional flowchart is malfunctioning

### ISSUE THREAD

**Issue by MartinFix** [jgraph/drawio#3592]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
We have created a cross-functional flowchart and worked on it for a while using both the web interface and the desktop apps for Windows and Mac. File is stored in a Google Drive folder.

After many interactions, changes and edits, suddenly for two specific lanes the rightmost containers started to misbehave.

Original file includes about 8 tabs/sheets, but the problem appears only in one specific flow chart in a single sheet.

We have been able to remove this problem by deleting the specific rows and then recreate them from scratch.
This issue is informative in case there might be a bug. Nothing blocks us from keep moving forward as needed.

Attached is the file in the state before any new columns are added. Lane is marked by a box right next to it and the information above is included as well.

Happy to answer any specific questions or to provide more details if needed.

**To Reproduce**
Not possible to describe how to reproduce. However, a sample file is attached where the existing defective behaviour can be observed.
1. add a column to the very right
2. draw.io shows an error message "Cannot set properties of null (setting 'value')" but still adds the column
3. you will see that the new column does not have the purple sepearation lines

1. click any container
2. container will not be selected

**Expected behavior**
Purple separator lines should be drawn all along to the right end of the flow chart.
Clicking into a container should select the container.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.2.1 (desktop under Windows)
- draw.io version 21.2.9 (browser version under Chrome (both windows and Mac)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version  112.0.5615.140

**Additional context**
[_DEBUG_ONLY.zip](https://github.com/jgraph/drawio/files/11459920/_DEBUG_ONLY.zip)

**Comment by davidjgraph** [comment]
What's the difference between this report and #3582 ?

**Comment by MartinFix** [comment]
Content is identical. I just realized that #3592 was not captured as bug with the standard info requested.
I thought I had closed #3582 to avoid confusion.
Sorry if that actually caused a confusion...

Martin

12 May 2023 17:37:12 David Benson ***@***.***>:

**Comment by davidjgraph** [comment]
Fixed in 21.3.1, thanks for the report.
