### ISSUE TITLE
Settings for Appearance Mode and Grid Color not Saved Individually for Diagram Files

### ISSUE THREAD

**Issue by tedo135** [jgraph/drawio#3595]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

I've noticed that the software currently applies the appearance mode (light/dark) and grid color settings globally across all my projects, rather than saving them for each individual diagram file. This has been causing some inconvenience.

Often, I work on multiple projects at the same time, each requiring its own unique set of visual settings for optimal productivity. For example, I might want to use a dark mode with a specific grid color for one project, but prefer a light mode with a different grid color for another. The current global setting forces me to manually reset the appearance and grid color every time I switch between projects.

It would significantly improve my user experience and productivity if I could customize and save the light/dark mode and grid color settings for each individual diagram file. This way, every time I open a diagram file, it would automatically display with my preferred visual settings, eliminating the need for manual adjustments.

I hope this feature, allowing individual customization of appearance settings per diagram file, can be considered for inclusion in future software updates. This would not only enhance my personal workflow but I believe it would also be appreciated by many other users facing similar challenges.

**Comment by davidjgraph** [comment]
What happens if two users are collaborating in real time and one changes from light to dark mode? The other user changes too? That's not right.
