### ISSUE TITLE
export to PDF is creating a blank page

### ISSUE THREAD

**Issue by scholvin** [jgraph/drawio#3596]
Per the subject - I have a drawio diagram that is saved on my Google Drive. I made some changes today, and when I try to export to PDF, I get a blank page. Export to PNG still works.

**Comment by MichaelLogutov** [comment]
Same here. Thought that I've broke something but reverting to old revision now produces blank page pdf.

**Comment by miathetaiwanese** [comment]
Same here :/, tried with different files and settings.

**Comment by davidjgraph** [comment]
Fixed in 21.3.1, thanks for the report.
