### ISSUE TITLE
--page-index CLI parameter is not working properly 

### ISSUE THREAD

**Issue by anselmobattisti** [jgraph/drawio#3597]
### Preflight Checklist

* [ x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

When exporting a diagram via terminal CLI the --page-index parameter is not working according to the description in the help text.

**Expected behavior**

executing 

`$ drawio --export --page-index 0 --output 0.pdf file.drawio `

It should export the first page of the diagram but, instead, it exports all the pages.

The page index is defining the first page
`$ drawio --export --page-index 1 --output 0.pdf file.drawio`

Should export only the first page but it exporting all the pages greater than 1

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.2.8

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04

**Comment by m-mohamedin** [comment]
Will be fixed in the next release
Thanks for the report

**Comment by davidjgraph** [comment]
Core release 21.3.3
