### ISSUE TITLE
onedrive integration shows blank page while authentication 

### ISSUE THREAD

**Issue by neotea** [jgraph/drawio#360]
I tried to use draw.io with onedrive (business account) and after I submit my onedrive email adress I get routed to a blank page: https://www.draw.io/onedrive3.html
I am using Safari / FF on an Mac
![step1](https://user-images.githubusercontent.com/7034722/49659473-a05d7680-fa44-11e8-8c7d-817511e122d8.png)
![step2](https://user-images.githubusercontent.com/7034722/49659472-a05d7680-fa44-11e8-9af6-250cdb287841.png)
![step3 error](https://user-images.githubusercontent.com/7034722/49659470-9fc4e000-fa44-11e8-86d5-a1db5930d20f.png)

**Comment by alderg** [comment]
Are there any errors in the browser console?
