### ISSUE TITLE
Make link created in background sheet clickable

### ISSUE THREAD

**Issue by SimoneR2** [jgraph/drawio#3604]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Feature request (i think): I'm trying to create a page template for our diagrams. This template should have a working link that once pressed would redirect user to another page. 

This is working when creating the link in every pages, but when applied as background it is not longer working

Maybe this is impossibile as background pages is threated as image when referenced to other pages but this would prevent us lots of heachache

**Describe alternatives you've considered**
Creating a template but not using it as background. The problem is when changing something we'll have to change it for every pages created starting from the template.

**Comment by davidjgraph** [comment]
Yeah, the background isn't active. Changing that at this stage is too much work, unfortunately.
