### ISSUE TITLE
Cannot export merged tables to vsdx

### ISSUE THREAD

**Issue by Dethrone110** [jgraph/drawio#3608]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Cannot export merged  cells/tables to vsdx format.  
The pop-up window showing unknown error when I click Export as-- VSDX（beta）
It can be reproduced for a blank merged table.

**Screenshot**
<img width="556" alt="image" src="https://github.com/jgraph/drawio/assets/83146216/51d8a127-c64e-483e-9b12-cd90c49c4e40">
<img width="1506" alt="image" src="https://github.com/jgraph/drawio/assets/83146216/4de65d1a-7f7d-4b06-82bc-02a11f2f1f23">

**Desktop (please complete the following information):**
reproduced on 3 different devices :
Mac Safari  21.3.2 & Window 11 desktop version 21.2.8 & Windows 10  21.2.8

**Comment by davidjgraph** [comment]
Fix in 21.3.3
