### ISSUE TITLE
Mermaid Timeline Diagram cannot be inserted

### ISSUE THREAD

**Issue by cavernBuilderZYX** [jgraph/drawio#3613]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Cannot add timeline diagram of mermaid (introduced in mermaid.js 9.4.0). After pasting the following code in the input box and clicking 'Insert'，'inserting' text and a large waiting circle icon always remains on the screen. This happens both on the web version and the desktop version.

The code (from the mermaid website):
```mermaid
timeline
    title History of Social Media Platform
    2002 : LinkedIn
    2004 : Facebook
         : Google
    2005 : Youtube
    2006 : Twitter
```

**To Reproduce**

1. Go to 'Arranged'->'Insert'->Advanced
2. Click on '.Mermaid..'
3. Enter the text shown above
4. No diagram generated.

**Expected behavior**
As shown in https://mermaid.js.org/syntax/timeline.html.

**Screenshots**
![图片](https://github.com/jgraph/drawio/assets/72795311/dfcd3a0b-36a6-460f-973f-f79fa258037a)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io 21.29

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser [firefox, edge]

**Additional context**

**Comment by davidjgraph** [comment]
Fix in 21.3.4
