### ISSUE TITLE
Diagrams embedded via the Publish link option are in dark mode

### ISSUE THREAD

**Issue by jabba-jedi** [jgraph/drawio#3614]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

We are embedding the draw.io diagrams to coda.io using the link generated by the Publish option. A week ago, all our embedded diagrams became dark mode by default. When you open a diagram in a separate window, it is possible to switch to light mode, but the embed doesn't change.

**To Reproduce**

1. Create a diagram. Example: https://drive.google.com/file/d/1AtveEZyv-2iKOjJ9U7A77ekopmbLHcnB/view?usp=sharing
2. Embed it in coda.io using the embed formula. Example: https://coda.io/d/_de57CX26vwd/Diagram-embed_su5Ul
There are no settings in Coda that suggest dark mode. The embed formula is as follows:
```
Embed("https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1#G1AtveEZyv-2iKOjJ9U7A77ekopmbLHcnB", 600,800,force: True())
```

**Expected behavior**
The diagram appears on the white background, as usual.

**Screenshots**

<img width="744" alt="image" src="https://github.com/jgraph/drawio/assets/6517649/eefa3e4c-10cf-432c-8b39-053660a87125">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.3.2

**Desktop (please complete the following information):**
 - OS: 13.1 (22C65)
 - Browser Safari
 - Version 16.2 (18614.3.7.1.5)

The problem appears for all of my colleagues across different platforms and browsers.
**Additional context**
coda.io support is of an opinion that draw.io is the cause of the problem.

**Comment by alderg** [comment]
Is the operating system in dark mode?

**Comment by jabba-jedi** [comment]
Yes it is. Is it the behavior change of draw.io? Because up until a week ago my system was in dark mode too, but the diagrams embedded normally.

**Comment by sdandois** [comment]
Same issue here. It looks like a recent change. I'm using Publish->Link option.

The diagram shows in dark mode without any option to change it to light mode. 

If the diagram was made for a light mode, if you want it to look properly, your only option is to change system settings and restart chrome.

**Comment by sdandois** [comment]
I think one option is to respect the theme declared in the editor. 

In the editor I've clicked Extras->Appearance->Light

**Comment by alderg** [comment]
This will be fixed in the next release.

**Comment by sdandois** [comment]
Thanks for the support!

**Comment by jabba-jedi** [comment]
Thank you!

**Comment by davidjgraph** [comment]
Change in 21.3.3
