### ISSUE TITLE
Wrong unit description used in font-size

### ISSUE THREAD

**Issue by cosing** [jgraph/drawio#3615]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

Wrong unit description used in font-size

![image](https://github.com/jgraph/drawio/assets/63569926/c7c866ff-78cf-4743-b823-773d27506be4)

**To Reproduce**

The unit displayed on the right side of the screen is in pt, but if we use the development tools to check, we can clearly see that this unit should actually be px, and in my understanding pt is short for point, which is the number that should be displayed at the top of the screen. (Here I cover it with another semi-transparent page)

![image](https://github.com/jgraph/drawio/assets/63569926/2021650f-78d5-4b95-a7bd-61b2b500626e)

**Expected behavior**

Show px here

**Screenshots**

If we really use pt as unit here, it should be bigger

![image](https://github.com/jgraph/drawio/assets/63569926/53ef07fb-1ac5-4eaf-834c-25967d158b4b)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: vivaldi
 - Version: 6.0.2979.22 (Stable channel)

**Comment by cosing** [comment]
I think a similar error is mentioned in this page #3455

**Comment by mykappa** [comment]
Related: https://github.com/jgraph/drawio-desktop/issues/1448#issuecomment-2034609398

**Comment by davidjgraph** [comment]
Fix in 24.2.7.
