### ISSUE TITLE
Find and Replace stops working when used once

### ISSUE THREAD

**Issue by accmltr** [jgraph/drawio#3616]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I use Find and Replace in my diagram, it only replaces one or two instances of my query and then stops "finding" the rest, even though I can manually see many more instances that should be found.

**To Reproduce**
Unfortunately I was not able to reproduce it, but I'll add screenshots of how it happens in my project. Hopefully someone smarter can figure out why it happens.

**Expected behavior**
The Find and Replace feature should always find all instances of the user's query and replace them with the desired text.

**Screenshots**
I open find and replace and type in my query:

![2023-05-23](https://github.com/jgraph/drawio/assets/19354678/a2f6b2c7-1980-4d85-aeb3-3656a398a195)

I then click Replace All and get the following result, where only some replaces happened:

![2023-05-23 (1) markup](https://github.com/jgraph/drawio/assets/19354678/aa5d715b-5caa-43f8-9ad9-fe5fd0006b17)

Then, when I click Find it does not find the remaining instances:

![2023-05-23 (2) markup](https://github.com/jgraph/drawio/assets/19354678/96fb5cae-6551-4532-a968-1dd78bea60c2)

When I remove the string in the Replace field, it finds my query again:

![2023-05-23 (3)](https://github.com/jgraph/drawio/assets/19354678/6865e7e9-2e2f-4685-afea-b3c3cae91b4a)

**draw.io version (In the Help->About menu of the draw.io editor):**

- diagrams.net 21.2.8

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 22H2

**Comment by m-mohamedin** [comment]
The issue will be fixed in the next release.
Thanks for the report

**Comment by davidjgraph** [comment]
Released in 21.5.1
