### ISSUE TITLE
Draw.io doesn't respect browser's language preference

### ISSUE THREAD

**Issue by jeanlucaslima** [jgraph/drawio#3622]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When accessing draw.io from a device with a language chosen, draw.io's interface choose language based on location. And on top of that it is not easy to 

**To Reproduce**
1. With a machine setup for English as language
2. With a browser setup for English as language
3. Access from a Brazilian IP 
4. Observe the interface in Portuguese from Portugal

**Expected behavior**
It should respect the users' preference for language. Even if they are in a place that speaks another language. 

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.3.2

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Browser Chrome (v113.0)

**Additional context**
It really took me some minutes to find the option to change the language since it was in Portuguese and in a non-intuitive place like on the `File->Preferences` menu that is a standard for most apps. If you are navigating on a different language and the menus are not in the usual places users can get lost quickly.

**Comment by davidjgraph** [comment]
It is not based on location.

**Comment by jeanlucaslima** [comment]
@davidjgraph OK, how can I rewrite it? Because I have video evidence it is loading in Portuguese on my laptop that uses Chrome in English, and MacOS in English. Only other factor may be my location.

**Comment by davidjgraph** [comment]
I'd know if we selected based on location. We don't. This would require a server call that returns the location of the IP request. Disconnect your network cable and the language won't change.

**Comment by jeanlucaslima** [comment]
Perfect, created a new issue describing it the way it happened.

**Comment by jeanlucaslima** [comment]
@davidjgraph do you need a video to believe me that it is loading the incorrect language?

**Comment by davidjgraph** [comment]
No, I believe you. But you are saying it's looking up the IP when I know it's not.

**Comment by jeanlucaslima** [comment]
OK, i will remove the IP part. Do I need to create a new issue?

**Comment by davidjgraph** [comment]
did you install the br-pt version of chrome when you installed it?

**Comment by jeanlucaslima** [comment]
Nope, it is not the pt-br version of Chrome. And MacOS is a UK model, with pre-installed OS.

**Comment by davidjgraph** [comment]
so you go to app.diagrams.net and the interface is in br-pt? If you look at local storage in the debugger, what is the value of the .drawio-config string?

**Comment by jeanlucaslima** [comment]
I think I found the issue. Not draw.io related. 

This is my language configuration on Chrome, somehow it is not respecting English on the top. 
Deleting and adding English again on top seems to have solved it for now. 

You can change it on chrome://settings/?search=lang 

<img width="737" alt="image" src="https://github.com/jgraph/drawio/assets/1311402/7496d889-cd58-44a7-b01c-43c5146a194c">

**Comment by davidjgraph** [comment]
Thanks for the clarification.
