### ISSUE TITLE
Exported SVG missing cell-id elements

### ISSUE THREAD

**Issue by rlaci999** [jgraph/drawio#3624]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The structure of the exported SVG file has changed in [v21.3.4](https://github.com/jgraph/drawio/releases/tag/v21.3.4) or [v21.3.5](https://github.com/jgraph/drawio/releases/tag/v21.3.5), earlier, for example, **an arrow with a text on it** was like:
```html
<g id="cell-xPgHAoHCg6b0oo1jKT46-55">
   <path ... >
   <path ... >
   <g transform="translate(-0.5 -0.5)"><switch> ... 
</g>
``` 

but now the `g#cell-...` wrapper is missing and the element order is not the same:

```html
<g transform="translate(-0.5 -0.5)"><switch> ...   
<path ... >  
<path ... >
```

I noticed that the first line of the exported file has changed from "diagrams.net" to "draw.io" and it happened in [v21.3.4](https://github.com/jgraph/drawio/releases/tag/v21.3.4), but this is just FYI:
`<!-- Do not edit this file with editors other than diagrams.net -->`

**To Reproduce**
1. Have an existing diagram saved earlier, containing an arrow with a text on it, and have an earlier exported SVG from it
2. Export the same SVG again
3. Compare the results, for example in Chrome DevTools

**Expected behavior**

Is it a bug or a feature?
I am reusing the SVG and I expect the old format. 

**draw.io version (In the Help->About menu of the draw.io editor):**

- 21.3.3 (stange. Are you sure this is correct version number?)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 113

**Comment by alderg** [comment]
The `g#cell-...` wrapper is only created with the `svgdata` plugin. The element order for SVG export did not change. The change of the first line is intended.

**Comment by rlaci999** [comment]
Indeed, thank you. So the `svgdata` plugin somehow disappeared for me. Re-adding again solved the issue.
