### ISSUE TITLE
Container Reposition Header

### ISSUE THREAD

**Issue by emendir** [jgraph/drawio#3625]
_Feature Request:_
Currently a container's header is always positioned at the top of the container.
It would be great if we had the ability to change the postion of a container's header to above, below, to the left or to the right of the container's body.

**Comment by davidjgraph** [comment]
Rotate the shape?

**Comment by emendir** [comment]
Thanks for the hint. I think I now have a set of solutions for all cases:
In the _Arrange_ tab, clicking the _Rotate shape only by 90°_ button changes the position of container's header.
If one wishes to change the container header's orientation accordingly, one sets _Angle_ instead.
![image](https://github.com/jgraph/drawio/assets/91378069/ad7a5788-02ac-41bb-a15f-69e036a8d408)

**Comment by emendir** [comment]
As the feature I asked about already exists, I close this issue, and hope that others may find it useful in finding the above presented solution.
