### ISSUE TITLE
Cannot modify an existing file

### ISSUE THREAD

**Issue by AvitalSHBR** [jgraph/drawio#3628]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Error saving file
An operation that depends on state cached in an interface object was made but the state had changed since it was read from disk.

The only thing I can do is to save the file as new file with different name

**To Reproduce**
It started in my computer lately and now I see it consistent just by open saved file and modify it, than try save it

**Expected behavior**
When modify existing file it should save the changes on the same file

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 21.3.5]

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 113.0.5672.93

**Additional context**

**Comment by alderg** [comment]
Is this in a synchronized local folder (Google Drive, iCloud etc)?

**Comment by davidjgraph** [comment]
What is the path of the folder you're writing to?

**Comment by AvitalSHBR** [comment]
C:\Users\ashiebe\Documents\MyFiles\TaProj

**Comment by davidjgraph** [comment]
Unfortunately, without being able to recreate, there isn't anything we can do.
