### ISSUE TITLE
Confusing download location/security risk? 

### ISSUE THREAD

**Issue by ddebree** [jgraph/drawio#3629]
* [ x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When I want to download a local executable to run the draw io software, it is really difficult to know what is the right download URL. I google "draw.io download" and there is a number of download locations that look questionable. I am not sure if these locations are just copying the executable on this github repo, or if they are maliciously altered. 

**Describe the solution you'd like**
It would be nice if there was a link from the online version of the application to the download or this repo.

**Describe alternatives you've considered**
Not sure how to create more clarity on the downloads.

**Comment by ddebree** [comment]
I see the help->support menu does link to this github repo, but again not terribly clear that the downloads are hosted here

**Comment by davidjgraph** [comment]
download.draw.io.
