### ISSUE TITLE
Revert the copy/paste style keyboard shortcut to `ctrl+shift+c` and `ctrl+shift+v`

### ISSUE THREAD

**Issue by AlexandreBonneau** [jgraph/drawio#3632]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
For many years in Draw.io, and in other editors, ctrl+shift+c and ctrl+shift+v has been used to copy and paste the style (or to 'paste special'). This is the norm.

Changing the shortcut to `Alt+Shift+Q` and `Alt+Shift+W` is really bad:
- Because of muscle memory developed during years of use
- Because it breaks Jakob's law and the principle of least surprise
- Because of non-logical keys placement when considering non-qwerty keyboards
*(for instance I'm using Dvorak and this is now hell to use. Do note that I have a mechanical C/V/X shortcut on that Dvorak keyboard.)*

It would be semi-ok if the user could easy switch back to the previous keyboard shortcut, however there is no such easy way (if any).

**To Reproduce**
1. Try to copy and paste an element style using `ctrl+shift+c` then `ctrl+shift+v`
2. It fails

**Expected behavior**
Revert this [faulty commit](https://github.com/jgraph/drawio/commit/f3162652bde7d452452cc21a9f281d4658b8522d#diff-b7dc174a7197248546ca1f70257cebd5313829cb7ef531e36b6d6fd241333ce4L811) so that `ctrl+shift+c` then `ctrl+shift+v` can be used as before.

Alternative solution: allow the users to modify the keyboard shortcuts.

**draw.io version:**
- draw.io version 21.2.8

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
This issue has first been raised [here](https://github.com/jgraph/drawio/issues/3589), and as you can see this is not a logical shortcut.

**Comment by alderg** [comment]
See https://github.com/jgraph/drawio/issues/291

**Comment by AlexandreBonneau** [comment]
Thanks for pointing to the cause of the change.

I understand the need to be able to paste without style (although as [one commenter said](https://github.com/jgraph/drawio/issues/291#issuecomment-1310037140), I fail to record *once* where I used pasting with formatting, since I *always* paste without formatting). Maybe the real improvement here would have been to make "paste without formatting" the default, then display a temporary very small icons on the bottom right of the pasted item to add the formatting to the pasted text. That icon would be short-lived and disappear when focus is shifted elsewhere.

Anyway, I'm digressing; about the `ctrl+shift+v` shortcut, I still stand by my initial issue where this shortcut has been in use for many, many years and changing it without giving the possibility to users to change it back is very annoying.

This is especially true for user not using a QWERTY keyboard.

One other alternative would be to change the `ctrl+shift+v` behavior so that it still paste the style *like before*, but only if a `ctrl+shift+c` has been done before, and the clipboard content has not been changed.
That could go like this:
1/ So when doing `ctrl+shift+c` you save an md5 hash of the clipboard content.
2/ When you do `ctrl+shift+v` you md5 hash the clipboard content again and check if it has changed since 1/
3/ If it hasn't changed, it means the users wants to paste the style, and `ctrl+shift+v` do paste the style as before
4/ If the clipboard content has changed, then default to the  'Paste without formatting' behavior

**Comment by etinlucem** [comment]
After six years of using Draw.io this one change breaks my workflow completely, to the point that I am ready to revert back to an earlier version and lose functionality or drop the program completely. Allowing users to program their own keyboard shortcuts would bring the tool in line with other modern editors.

**Comment by davidjgraph** [comment]
https://github.com/jgraph/drawio-dev/commit/90f7514a6b9cee30d26a63aa90ca7b7ad4be6e22

**Comment by AlexandreBonneau** [comment]
> https://github.com/jgraph/drawio-dev/commit/90f7514a6b9cee30d26a63aa90ca7b7ad4be6e22

Sorry but it seems this link is dead

**Comment by davidjgraph** [comment]
It's an internal link.

**Comment by bjoernbusch** [comment]
I would be thrilled to get the initial shortcuts back, since it's currently very difficult to figure out which keys should be used:

- Muscle memory says: `CTRL+SHIFT+C` / `CTRL+SHIFT+V`
- Also the current help still shows this: https://www.drawio.com/blog/shortcut-styles
- The shortcut cheatsheet says it should be `ALT+C` / `ALT+V` https://app.diagrams.net/shortcuts.svg
- Only here in the issue I could find the current state of `Alt+Shift+Q `and `Alt+Shift+W`

**Comment by davidjgraph** [comment]
The new shortcuts for Copy/Paste style are Alt+C / Alt+V. The blog post will be fixed.

The previous shortcuts Alt+Shift+Q/W are still working, but only for backwards compatibilty.

Ctrl+Shift+V is now paste text without formatting.

We won't revert the commit, the current setup is about the best solution we can find for all the possible variations.

**Comment by AlexandreBonneau** [comment]
This does not fix the problem for non-standard keyboards, although Alt+C/V is undoubtedly a better shortcut than Alt+Shift+Q/W.
I still think the underlaying problem here is not giving a way for the user to either edit their own keyboard shortcuts (which would be the best solution), or at least give them a way to load predefined shortcut profiles (so that they could use drawio like there other drawing apps).

Anyway, thanks for changing it to a more sane shortcut!

**Comment by davidjgraph** [comment]
Yes, custom shortcut is another issue with a ticket open (somewhere).
