### ISSUE TITLE
Can't select items when starting to drag on top of a blocked one in the background

### ISSUE THREAD

**Issue by AlexandreBonneau** [jgraph/drawio#3633]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
We have an awesome feature that allows to 'block' some elements so that you cannot inadvertently move them while clicking and dragging the mouse across the viewport.
This is really useful for instance if you do not want to modify the headers / footers / legend of your documents.

On my end, I'm using multiple 'blocked' elements to create a specific A3 background that I reuse in my work documents.
(Do note here that I'm not using multiple layers)

However, when you want to select multiple objects placed on top of those blocked elements, you _must_ start dragging the rectangular selection from _outside_ any elements, even if those are blocked.
If you start dragging the rectangular selection from _inside_ a blocked element, then it will just select that element (and display a dashed red line around it) and stop the rectangular selection.

**To Reproduce**
1. Create a rectangle the size of the viewport, then set it as 'blocked'
2. Create a few small circles on top of that big rectangle
3. Deselect everything, the try to do a rectangular selection of those circles, starting to click inside the big rectangle
4. The 'blocked' big rectangle is selected

**Expected behavior**
Since those elements are blocked, then starting a drag on top of those should be allowed without selecting those first.
In order to select a blocked element, then a simple 'click' (no drag) could be used.
In order to select multiple blocked elements, then dragging a rectangular selection around those should select them.

Alternative solution ; have a switch in the diagram panel named "Allow selecting blocked elements" (off by default), which would allow the user to select blocked elements when 'on'. When 'off', then all the blocked elements would be unselectable (by rectangular selection nor simple click).

**draw.io version:**

- draw.io version 21.2.8

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
This issue is loosely related to [this one](https://github.com/jgraph/drawio/issues/3347)

**Comment by alderg** [comment]
Try this:

```
mxRubberband.prototype.isForceRubberbandEvent = function(me)
{
	return mxEvent.isAltDown(me.getEvent()) || me.getState() == null ||
		mxUtils.getValue(me.getState().style, 'forceRubberband', '0') == '1';
};
```

**Comment by AlexandreBonneau** [comment]
Sorry I'm not sure to follow; I added this function definition in the console on https://app.diagrams.net/, but that does not fix the behavior I'm describing.

**Comment by AlexandreBonneau** [comment]
Was this fixed? I do not see a reference to a commit here ':)

**Comment by davidjgraph** [comment]
Yes, it was fixed.
