### ISSUE TITLE
Importing mermaid for ELK rendering is not supported

### ISSUE THREAD

**Issue by davis-liu** [jgraph/drawio#3634]
### Preflight Checklist

* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

%%{init: {"flowchart": {"defaultRenderer": "elk"}} }%%
    flowchart LR
       subgraph 1659390261651824765
       direction LR
       A
       B
       C
       end

 When I import graphics from drawio using the above information, I have been in a waiting state

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [21.2.1]

**Comment by m-mohamedin** [comment]
Hi,

Can you please explain more. I inserted this mermaid diagram (Arrange->Insert->Advanced->Mermaid) and it works

Thanks

**Comment by m-mohamedin** [comment]
Thanks for the details, I can reproduce now
We'll try to get it fixed

**Comment by bodritto** [comment]
Hi @m-mohamedin ! Any update on this? This is link to mermaid docs on this: https://mermaid.js.org/syntax/flowchart.html#renderer

**Comment by davidjgraph** [comment]
Please test 24.4.11.

**Comment by davidjgraph** [comment]
Added in 24.4.14.

**Comment by Igzak** [comment]
Looks like right now ELK not supported or something broken
