### ISSUE TITLE
Shape Bounding rect not aligned with grid

### ISSUE THREAD

**Issue by Murmele** [jgraph/drawio#3635]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I created my own shapes which shall be aligned with the grid. For this the bounding rectangle is sometimes a little bit greater than the content (See example below). When adding the shape from my library to the drawing area, the bounding rect is not aligned with the grid and therefore the connection points are also not on the grid.
I designed the shapes, so that the bounding rect is aligned with the grid, but it seems that this will not be done

Diagram.drawio:
```xml
<mxfile host="Electron" modified="2023-05-31T07:25:36.594Z" agent="5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) draw.io/20.8.16 Chrome/106.0.5249.199 Electron/21.4.0 Safari/537.36" etag="J_CVxuE9MucYDT354cNX" compressed="false" version="20.8.16" type="device">
  <diagram name="Page-1" id="2mBxP0mlJQwRutrJ-KL2">
    <mxGraphModel dx="2528" dy="1178" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="472" pageHeight="472" math="0" shadow="0">
      <root>
        <mxCell id="0" />
        <mxCell id="1" parent="0" />
        <mxCell id="aETKFiIY0m40jLAyEIl4-1" value="" style="shape=stencil(pZRRcoMgEIbP0od9TAchOUCHtvcgBisTAg6SpL19FxZnYow2TXxQ91/8+NndEYTsW9Vp4KwF8Q6cc4Y3DM8Urkuo+k7XkbSTCkZtraZMH4Pf67PZxUIwrtXBxJQVH8DeICEZCFl75xBivOtHmYs8wpRx+C37JljZ/qdErxuKO9zhoKMOpFekAv+8G1w9AxYSlbnjCLlV9f4r+KPb3bTzslrRS0glnTvqzTZcNan44gyJE38zLoRsfNAL9hpjLTV1oaRpUe2tDxjSMxsDLpp8LTekU2lYJokhffAnPVeXii2hB4I17oJQPYIYmxDPu1g/gvijEcOy8SRdnXczGqWhnu1/bNw1E6hPGpvVycBllX48WfgF);whiteSpace=wrap;html=1;rotation=90;fillColor=#97D077;resizable=0;" parent="1" vertex="1">
          <mxGeometry x="-370" y="50" width="50" height="20" as="geometry" />
        </mxCell>
      </root>
    </mxGraphModel>
  </diagram>
</mxfile>
````

````
<shape h="20" w="40" aspect="variable" strokewidth="inherit">
  <connections>
    <constraint x="0" y="0.5" perimeter="1" />
    <constraint x="1" y="0.5" perimeter="1" />
  </connections>
  <background>
    <!-- <rect x="0" y="0" w="40" h="20" /> -->
  </background>
  <foreground>
    <fillstroke />
    <fillcolor color="#ffffff" />
    <path>
      <move x="0" y="10" />
      <line x="10" y="10" />
      <move x="30" y="10" />
      <line x="40" y="10" />
      <stroke />
      <rect x="10" y="5" w="20" h="10" />
      <fillstroke />
    </path>
  </foreground>
</shape>
````

**To Reproduce**
1. Create the above shape
2. Save the shape in a library
3. Drag the new shape on a new drawing area

**Expected behavior**
The Shape Bounding rect is aligned with the grid 

**Screenshots**
![grafik](https://github.com/jgraph/drawio/assets/10099533/e576ff92-29a9-4530-bb5c-09a5575b1f86)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.8.16

**Desktop (please complete the following information):**
 - OS: Windows
 - Desktop version

**Comment by alderg** [comment]
This is the intended behavior. Try using a single click on the rotation handle to rotate the shape 90 degrees and keep it aligned with the grid.
