### ISSUE TITLE
Transparent background doesn't seem to work with arrow labels

### ISSUE THREAD

**Issue by YakovL** [jgraph/drawio#3637]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Arrow labels have a background picker. While it has an option to set background color to "none", it is, in fact, set to white.

**To Reproduce**
1. Create an arrow between two elements, add a text label to it (enter, type something, click elsewere to save);
2. Open the label for editing again, open bg color picker;
3. Select transparent (none), apply;
4. Close the label editing mode.

**Expected behavior**
The label should have no background color.

**Screenshots**
![vivaldi_C2Apo7CBSM](https://github.com/jgraph/drawio/assets/1131924/e20ef920-90a5-42ac-9c33-dae4450a1b43)

**Environment:**
 - draw.io version: 21.3.6
 - OS: Windows 10 x64
 - Browser: Vivaldi 6.0.2979.15 (stable channel, 64 bit); also reproduced in Firefox 111.0.1 (64 bit)

**Comment by alderg** [comment]
Works for me. Please attach a test case.

**Comment by YakovL** [comment]
Well, here it is, but it seems the background change isn't applied at all

![mcve](https://github.com/jgraph/drawio/assets/1131924/f237e643-79c4-4510-b19c-e964deebd955)

Could you attach a diagram where you've successfully applied transparent background to a label? I'll test at least whether it's displayed correctly for me.

Just in case, I've also saved it as .drawio and .xml, and the result is the same, but GitHub supports attaching neither of these.

**Comment by alderg** [comment]
[Here](https://app.diagrams.net/?tags=%7B%7D#RpVRdb5swFP01PCYCE5LwuNBme2inSp20vU0OvgF3houMSUN%2F%2FUy4fLhppFWTkPA9vj7369hemBTnr5pX%2BSMKUB7zxdkL7zzGgnW8sr8OaQlZsbhHMi1Fj%2FkT8CzfgBwHtJECasJ6yCAqIysXTLEsITUOxrXGV9ftiEo4QMUzcNLogOeUK7hy%2BymFyXt0G828v4HM8iFy4NPOgad%2FMo1NSfE8Fu73SRJT%2BQUfuMi%2FzrnA1xkU3nthohFNvyrOCaiuuW7b9jd2x7w1lOZfDqzT3zp%2FeVz%2F%2Bu4LtnjiQeq3C0a5mXboBwjbHjJLLO1vlzb6BB1LYI1LxRfLtxZqk2OGJVcPiBW5vIAxLU2aNwYtlJtC0e4RS0ObgW3CrjZcD8DW2lCKmdXn1yV1s%2BxgbKZVKWABRrfWRYPiRp7cc5zUko1%2B49EnlJaR%2BYO0N9QbEvaCsWXkktjEMzB0bt75d1SLFVtuYjZ%2B28hlDqLYJa6x0SlcEdvFrMIJugz6E0MP%2B2gnrhrqzg%2BozYdKeOAHe%2BGd%2BXEls9KuUzsA0BY4gTbSXqgvtFFIITqOnYZavvHDha8TS9UVdCkx2nnR3TstrK2tunC78WIlqFBPOqS0bTg4ex%2B8DRRqftUnldyW%2F7V0hrn5y3Cz2fZc%2FymnMHRmPmQ4EODxWMMnh23N6fXo3ac3Orz%2FCw%3D%3D) is an example. Uncheck background color in the text section:

<img width="242" alt="Screenshot 2023-06-12 at 07 00 31" src="https://github.com/jgraph/drawio/assets/921200/a762d903-5de5-4316-a9e9-d1700bb9e8a7">

**Comment by YakovL** [comment]
Right, what you've created is a separate text element. I'm talking about an arrow label

**Comment by alderg** [comment]
Please attach a test case. (Use Export as URL and attach the link.)

**Comment by YakovL** [comment]
[Here](https://app.diagrams.net/?tags=%7B%7D#RzVVNk5NAEP01HLUCk5DkuJvNrlbpqpWD63GW6YXRgaaGZiH%2BeofQfImb0jJWeaHmvf5g%2BnU3eGKX1ndW5sl7VGC8YKFqT9x4QbD1F%2B7ZEMeWWK7XLRFbrVrKH4iD%2Fg5MclxcagXFxJEQDel8SkaYZRDRhJPWYjV1e0IzfWsuY5gRh0iaOftZK0padhOsB%2F4N6Djp3uyH29aSys6ZKykSqbAaUWLviZ1FpPaU1jswjXadLm3c7QvW%2FmIWMvqtgPRxf3sP5aerIlt9DO4%2FvL2qX3GWZ2lKLpgvS8dOAYtlpqBJsvDEdZVogkMuo8ZauZY7LqHUOOS745M2ZocG7SlWqBVs1NLxBVn8BiPLJngUYegs8zK6O4ElqEcUl3UHmALZo3Nha7BgiXnGNgyroWE9l4ya1cdJHpK4Tz3o6A4s5R%2FIupzJ6kqhmbSg3KwxREsJxphJsx%2FY66n4g887xJwl%2FwpER14cWRJOGwK1pofR%2BUuT6vWK0U3NmU%2Fg2IHMafAwBqOoBg5hJ9TFvdjKAksbwRm9eOpI2hjojJ9o%2FRrdzg6GBSNJP093%2BOJdDmZdxgz%2Bbn8usQ3%2BdBu2820If7EM4b%2FaBfFfqrT8SaVetcvL5ODwlT%2FZRr9Ksf8B)

**Comment by alderg** [comment]
[There](https://app.diagrams.net/?tags=%7B%7D#RzVVNc9MwEP01PsLEUmLcY5OmhRkoMDnQHhVra4vKXo%2B8rm1%2BPXIsf2HIwBBmOFnv7Ye1b3dHHt%2Bl9Z0RefIBJWiPrWTt8RuPMZ8Fvv20TOOYFQs7JjZKOm4kDuob9I6OLZWEYuZIiJpUPicjzDKIaMYJY7Cauz2hnv81FzEsiEMk9JL9oiQlHRuyNyP%2FFlSc9H%2F2g6vOkore2VVSJEJiNaH43uM7g0jdKa13oFv1el26uNtfWIeLGcjotwLS4%2F72HsrP10W2%2BcTuP767rl%2B5LC9Cl65gd1lqegUMlpmENsnK49sqUQSHXESttbJNt1xCqbbIt8cnpfUONZpTLJcbCOXa8gUZfIaJJWRHHgTWsiyjvxMYgnpCubLuAFMg01gXZ2UrJ7EbstDBamzYwCWTZg1xwg1JPKQedbQHJ%2BUfyLpeyGpLoYW0IO2sOYiGEowxE3o%2Fstu5%2BKPPe8TcSf4ViBq3OKIknDcEakUPk%2FNjm%2Br1xqGb2mU%2BgaYHmdXgYQomUS0cw06oj9PiCHorouf4dO2%2B2xlmcK7RBZYmgjNqupkkYWKgM36882tVPTs2BrQg9TLf8IvPAFvMQKvDX23XJXbFn%2B%2FK1XJXgp%2BsSvCvNoX%2Flyqtf1BpUO3yMlk4vgEn2%2BQp5fvv) (Select the edge, go the Text tab, uncheck Background Color.)

**Comment by YakovL** [comment]
Right, thanks! But closing this is not a good idea: I've described the expected behavior, and the actual one which definitely is a bug (the color picker has the transparent option, but applying it doesn't provide what's expected). It's great that I now know the workaround, but for UX it's definitely better to either make transparent option to work as expected, or remove it from there.

**Comment by alderg** [comment]
Happy to reopen this, but again, it works for me, and without the reproduction steps or a test case we can't fix this.
![1d526f40c260b83bfb3469c3f543c89f](https://github.com/jgraph/drawio/assets/921200/7f261bbc-3a3d-46aa-8fd4-742c8aeadb91)

**Comment by YakovL** [comment]
Ah, that's because you don't follow the steps to reproduce like I've described them. I've checked: indeed, if I don't enter the _edit label mode_, like you do in the gif, the picking works. But if you follow

> 2. Open the label for editing again, open bg color picker;

you'll find that (unlike for other colors!) picking transparent in this mode doesn't work.

**Comment by alderg** [comment]
In editing mode, the background color is changed for the current text selection.

**Comment by YakovL** [comment]
Oh, I see, that's not trivial. Thaks for the explanation!
