### ISSUE TITLE
The first character is letter when I use  Microsoft Pinyin IME

### ISSUE THREAD

**Issue by yunnysunny** [jgraph/drawio#3642]
https://github.com/jgraph/drawio/assets/734818/daa10a10-0698-4ae6-9d8e-c910cde77247

I met the same problem which has asked in https://github.com/jgraph/drawio/issues/313 (But it has been closed). I use Microsoft Pinyin IME to input Chinese, the first time I try to write `shi` , but it only show `hi`. Then I clear the input characters and try again, it works OK.

_Originally posted by @yunnysunny in https://github.com/jgraph/drawio/issues/313#issuecomment-1569492915_

**Comment by davidjgraph** [comment]
Is this still happening in the latest release?

**Comment by yunnysunny** [comment]
It seems fixed in latest version(24.5.3)

**Comment by alderg** [comment]
> It seems fixed in latest version(24.5.3)

What operating system did you use? And this is with the initial key pressed while not yet editing the label?

**Comment by yunnysunny** [comment]
> > It seems fixed in latest version(24.5.3)
> 
> What operating system did you use? And this is with the initial key pressed while not yet editing the label?

I use Win 10. It used to come up when I edit on the lable.

**Comment by davidjgraph** [comment]
Duplicate #4802

**Comment by davidjgraph** [comment]
Fix in 29.5.3
