### ISSUE TITLE
Fit Window zoom option no longer working as expected

### ISSUE THREAD

**Issue by sebastia01** [jgraph/drawio#3647]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I just upgraded and the Fit Window option used to zoom to either the selected objects or, if no selection, a magnification that would include all objects on the canvas.  Now, it always zooms to the full set of pages including empty spaces.

**To Reproduce**
1. Create a new diagram
2. Drop a few shapes
3. Select a shape and click 'Fit Window' on zoom menu dropdown or use the CMD+SHIFT+H shortcut
4. Unselect all artifacts and repeat step 3.

**Expected behavior**
Step 3: the zoom magnifies to show all selected shapes
Step 4: the zoom magnifies to show all shapes

**Screenshots**
After Step 3 actual:
<img width="2007" alt="image" src="https://github.com/jgraph/drawio/assets/26609209/870489ea-4adb-4fad-bcfa-62d28f08eb74">

After Step 3 expected:
<img width="2831" alt="image" src="https://github.com/jgraph/drawio/assets/26609209/32690c7a-a61f-46ee-8a50-d98752265405">

After step 4 actual:
<img width="2002" alt="image" src="https://github.com/jgraph/drawio/assets/26609209/a80ee330-4067-439e-832e-b40285d3b453">

After step 4 expected:
<img width="3268" alt="image" src="https://github.com/jgraph/drawio/assets/26609209/1ea3bd61-3aee-4e7c-83f1-082950bc9698">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.2.8

**Desktop (please complete the following information):**
 - OS: macOS 
 - Browser : Chrome (114.0.5735.90 (Official Build) )
 - Version: Ventura 13.4

**Smartphone (please complete the following information):**

**Additional context**

**Comment by davidjgraph** [comment]
Fix in 21.3.8

**Comment by sebastia01** [comment]
Thank you @davidjgraph
