### ISSUE TITLE
Multiple signals fired for single event

### ISSUE THREAD

**Issue by anadon** [jgraph/drawio#365]
In https://github.com/MTU-CS5441/drawio/blob/TestingPeer/src/main/webapp/js/mxgraph/Dialogs.js we have had to work around the "END_EDIT" event firing twice for a single edit.

**Comment by alderg** [comment]
What are the steps to reproduce this problem?

**Comment by anadon** [comment]
Over in https://github.com/MTU-CS5441/drawio/tree/TestingPeer, our listener for the event just always gets called twice.  We found work arounds to ignore them.

**Comment by anadon** [comment]
Guys, why do you keep closing out each of these tickets?  There are clear problems in your code.

**Comment by alderg** [comment]
No reproduction case provided.

**Comment by anadon** [comment]
Just run it.  Look at some of the changes.  There are no unit tests, so this is how debugging works,

**Comment by davidjgraph** [comment]
"Run my repo" isn't a reproduction case. https://stackoverflow.com/help/mcve is a typical process for providing reproduction cases. We're busy people, if you make no effort, nor will we.

**Comment by anadon** [comment]
Every time I have attempted to engage, I get dismissed or belittled.

**Comment by alderg** [comment]
That said, if you are talking about loading a file, we first reset the graph (one END_EDIT) then set the root (second END_EDIT), so that's not a bug.
