### ISSUE TITLE
Not a diagram file Microsoft Word error

### ISSUE THREAD

**Issue by mbellandi** [jgraph/drawio#3650]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
We have an existing Word document with embedded Visio objects, upon exporting them out to a Visio file and re-importing them using the Draw.io add-in for Microsoft Word I get an error message saying "Not a diagram file". However if I open the file using the stand alone Draw.io application, they open no problem.  Also, if I convert the Visio file to a drawio file type and then insert into Word via the add-in it works fine. 

**To Reproduce**
1. Open a Word document with embedded Visio objects
2. Alt + double click on the diagram to open it Visio, then click Save to save it as a .vsdx file on your local computer
3. Click on the draw.io add-in and select Pick Device File  and select the recently saved file. [embedded_drawing.zip](https://github.com/jgraph/drawio/files/11672483/embedded_drawing.zip)
4. See error in screenshot

**Expected behavior**
I expect the drawing to be imported and I shouldn't have to open it first in the app and convert it.

**Screenshots**
<img width="277" alt="Screenshot 2023-06-06 205501" src="https://github.com/jgraph/drawio/assets/104934514/f1a3bf1d-46ec-4611-a8fd-db29166293fd">

**draw.io version (In the Help->About menu of the draw.io editor):**
21.2.8.0 (desktop version)
1.0.0.0 (Office add-in version)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser: Mozilla Firefox
 - Version: 113.0.2 

**Additional context**
Using Microsoft Word for Microsoft 365 MSO (Version 2304 Build 16.0.16327.20200) 64-bit

**Comment by alderg** [comment]
The Draw.io add-in for Microsoft Word only supports draw.io files, while the standalone app automatically imports Visio files.
