### ISSUE TITLE
Add spider diagram template

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#3652]
"In Excel I’m able to create a spider diagram, which is based on table values from 1 to 5. The values determine what the spider diagram will look like, see screenshot."

![spider](https://github.com/jgraph/drawio/assets/44292306/ce5e243a-4d85-4727-b945-890eee45281f)

Asked in DID 8472 (Confluence Cloud)

**Comment by davidjgraph** [comment]
This is outside the scope of this product.
