### ISSUE TITLE
Shapes from custom libraries don't show when copying from lucidchart

### ISSUE THREAD

**Issue by aseques** [jgraph/drawio#3653]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

I am using the free stencils from [here](https://vmtoday.com/2013/05/updated-vmware-horizon-view-visio-shapes-stencil/) in some lucidcharts drawings
When I copy the drawing into a blank page in diagrams.net instead of the icons I see ony some empty boxes.

**To Reproduce**
1. Login into lucidchart
2. Import a stencil pack
3. Draw anything with those stencils
4. Copy to diagrams.net net diagram
7. The white squares will show

**Expected behavior**
The images from the original drawing should be copied

**Screenshots**
![ksnip_tmp_vYDrIc](https://github.com/jgraph/drawio/assets/555542/6550f850-5b98-4bbb-89dc-a46dc7b53732)

![ksnip_tmp_voRqGI](https://github.com/jgraph/drawio/assets/555542/23dc92c7-6ebd-4a42-a3f0-676fee4fffdc)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version:  21.3.7

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome / Firefox
 - Version 113

**Additional context**

See  attached the file 

[importedFiles.zip](https://github.com/jgraph/drawio/files/11677917/importedFiles.zip)

**Comment by davidjgraph** [comment]
We can't fix this. Lucid store the images on their servers, we have no access to them.

**Comment by aseques** [comment]
Just to know @davidjgraph, would it be possible for me to create a template gallery as specified [here](https://drawio-app.com/blog/draw-io-training-exercise-9-create-your-own-custom-library/) and somehow fix the xml to point the shapes on my library?  (even if it means doing it locally for me)

**Comment by davidjgraph** [comment]
You can just drag the stencils into the editor and they should work.
