### ISSUE TITLE
Cannot edit or remove links added on text

### ISSUE THREAD

**Issue by oanalavinia** [jgraph/drawio#3654]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When adding a link to a specific word from a text shape, that link cannot be deleted or edited afterwards.

**To Reproduce**
1. Add a Textbox shape
2. Select one of the words, e.g. _Lorem_
3. Go to the `Format` panel and click on `Insert -> Link...`
4. Add any type of link (e.g. add the URL `https://www.drawio.com/`) and click on `Apply`
5. Click outside the Textbox and then back on it
6. Observe the displayed tooltip

**Expected behavior**
An `Edit link` option, along with the `Remove link`, should be displayed besides the link in the tooltip, as you can see when the link is added to a shape.

Or maybe to be able to use, even if it's not an intuitive UI,  the right click -> `Edit link...` when the word is selected.
The only option right now is to delete the shape and add it again correctly.

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/22794181/542ba66c-3b92-45cc-b023-e62e729c0222)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.3.7

**Desktop :**
 - OS: Fedora Linux 36 (Workstation Edition)
 - Browser Firefox 105.0.1

**Comment by davidjgraph** [comment]
Fix in 21.3.8

**Comment by oanalavinia** [comment]
Thanks a lot!
