### ISSUE TITLE
Expand event documentation

### ISSUE THREAD

**Issue by anadon** [jgraph/drawio#366]
When my group was working on collaborative editing, we found that the properties variable in events was insufficiently documented.  We were looking for a way to capture and disseminate individual changes, but there dosn't seem to be any documentation about how changes are created and applied to the underlying graph model.

**Comment by alderg** [comment]
We replaced log replay with diff-sync for collaborative editing. See
https://github.com/jgraph/drawio/blob/master/src/main/webapp/js/diagramly/DiffSync.js and 
https://github.com/jgraph/drawio/blob/master/src/main/webapp/js/diagramly/DrawioFileSync.js

**Comment by anadon** [comment]
Where is the documentation for this?

**Comment by alderg** [comment]
https://neil.fraser.name/writing/sync/

**Comment by anadon** [comment]
I've run into too many gotchyas on documentation here.  Where are all the locations of documentation, and can they be centralized?

**Comment by RingyRing** [comment]
Sorry for bumping a fairly old thread, but may I ask you, what was your rationale behind changing operational transform with differential syncing?

**Comment by davidjgraph** [comment]
Doesn't need a server.

**Comment by RingyRing** [comment]
Does it mean that the current implementation of diagrams.net runs completely on the user's machine, even when he or she shares files with others?

**Comment by davidjgraph** [comment]
Depends whether you want delta changes to reduce bandwidth. In the current app.diagrams.net deployment a server is used to pass on encrypted deltas. But you could sync against the full file and avoid the use of a server.

Diff sync is also better are merging two files with an arbitary history distance between them.

**Comment by RingyRing** [comment]
Could operational transform be implemented as a secondary option for the users of app.diagrams.net? Perhaps as a toggle inside File -> ... or Extras -> ... ?

**Comment by RingyRing** [comment]
The rationale behind my suggestion is that OT is better suited for real-time collaboration on a single file.

**Comment by davidjgraph** [comment]
Anything _could_ be implemented. I'd suggest to open another issue with a detailed explaination of why OT is better, including example cases of problems in the current implementation.
