### ISSUE TITLE
Is there any possible to add the feature of saving to the gitee?

### ISSUE THREAD

**Issue by BorenZhang** [jgraph/drawio#3660]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I am a developer from China and I'm very like your work here, but for some reason, in China, it's hard to access github, Google drive and some other website. So it's impossible to save my work to github or Google Drive. 

**Describe the solution you'd like**
https://gitee.com/ is one of Online software source code hosting service platform in China, You could think of it as the github of China. Not like github, it's very easy for Chinese to access gitee. So if you could add a feature of saving files to the gitee, I think it could be a wonderful thing for Chinese.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Thanks.
A Loyal Chinese User

**Comment by davidjgraph** [comment]
Thanks for the suggestion. However, having considered the effort of implementation and maintenance vs the number of people who would benefit, this doesn't meet our level for a feature request.
