### ISSUE TITLE
Pasting html-formatted text doesn't apply the formatting anymore

### ISSUE THREAD

**Issue by mikarieta** [jgraph/drawio#3666]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When pasting an html-formatted text Drawio doesn't apply the formatting anymore, instead it "outputs" the raw html.

**To Reproduce**
1. Copy some text from e.g. VS Code, or even the simple default `text` inside a text element from Drawio with `ctrl + c`
2. Paste with `ctrl + v`

**Expected behavior**
Expected behavior is like V21.2.8, see screenshots

**Screenshots**
V21.2.8 - as intended:
![paste 2128](https://github.com/jgraph/drawio/assets/81352526/0f16e26a-cdda-459a-99bc-a8bd16e5644c)

V21.3.7 - bug or as intended?
![paste 2137](https://github.com/jgraph/drawio/assets/81352526/23b31a20-b7a9-4ac7-8550-463ccb15b517)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.3.7

**Desktop (please complete the following information):**
 - OS: Ubuntu - both Snap package and Chrome

**Comment by davidjgraph** [comment]
Fixed in 21.4.0
