### ISSUE TITLE
Misalignment of arrow labels on horizontal flow layout

### ISSUE THREAD

**Issue by GitSparTV** [jgraph/drawio#3668]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When applying horizontal flow on somewhat complex graph (any layout that makes multiple waypoints on arrows) labels on arrows have different offset from the arrow itself.

**To Reproduce**
1. Go to `Arrange` -> `Insert` -> `Advanced` -> `From Text`
2. Select `Horizontal Flow`
3. Paste this:
<details>
  <summary>Open me</summary>
  ```
67412943987606680->94%->67412943211911568
67412943213937232->92%->67412943214775224
67412943209139952->37%->67412943270003920
67412943209139952->37%->67412943987819120
67412943209139952->40%->67412943268307824
67412943209139952->36%->67412944072782096
67412943209139952->40%->67412944101229616
67412943209139952->38%->67412944101354424
67412943209139952->37%->67412944042096312
67412944042096312->38%->67412943270003920
67412944042096312->71%->67412943268307824
67412944042096312->87%->67412944072782096
67412944042096312->90%->67412944018982152
67412944042096312->36%->67412943215695888
67412944018982152->42%->67412943187034000
67412944018982152->36%->67412943215695888
67412944018982152->36%->67412944101176760
67412944072781072->89%->67412943984927224
67412943897133240->70%->67412943212836760
67412943987697848->36%->67412943209139952
67412943987697848->85%->67412943987819120
67412944072782096->64%->67412943268307824
67412944072782096->37%->67412943270003920
67412944101229616->36%->67412944101354424
67412943273725968->81%->67412943984927224
67412943273725968->47%->67412943268334728
67412943273725968->84%->67412944072781072
67412943899160952->82%->67412943271878648
67412943268307824->39%->67412943212893520
67412944101176760->36%->67412943210926544
67412943271968984->36%->67412944101176760
67412943210926544->37%->67412944101354424
67412944101354424->36%->67412944071858320
67412943215695888->46%->67412943270003920
67412943215695888->39%->67412943212893520
67412943215695888->58%->67412943268307824
67412943215695888->55%->67412944072782096
67412943215695888->36%->67412943209139952
67412943215695888->59%->67412944042096312
67412943215695888->39%->67412944070788760
67412943215695888->38%->67412943267444872
67412943990524304->59%->67412943270003920
67412943990524304->41%->67412943215695888
67412943270003920->37%->67412943187034000
67412943270003920->42%->67412943268307824
67412943270003920->37%->67412943267444872
67412943241524592->51%->67412943270003920
67412943241524592->41%->67412943268307824
67412943241524592->41%->67412943215695888
67412943241524592->57%->67412943990524304
67412943268334728->49%->67412943984927224
67412943268334728->51%->67412944072781072
67412943216619408->45%->67412943215695888
67412943187034000->36%->67412943210926544
67412943955520688->94%->67412943987606680
67412943955520688->95%->67412943187064728
67412943955520688->94%->67412943211911568
67412943187064728->94%->67412943987606680
67412943187064728->94%->67412943211911568
  ```
</details>
4. Look at labels' positions and to which arrows their belong

**Expected behavior**
Labels should be positioned on the arrow by default.

**Screenshots**
Here is a chart
<img width="970" alt="image" src="https://github.com/jgraph/drawio/assets/5685050/8b89b8de-6356-41b7-94a3-5e3a226afcbf">

If I select the top arrow, the yellow dot appears at the bottom indicating the label position.
<img width="1071" alt="image" src="https://github.com/jgraph/drawio/assets/5685050/4584dceb-5cbb-482f-9399-849cc4a471c2">

These labels are intersecting each other
<img width="676" alt="image" src="https://github.com/jgraph/drawio/assets/5685050/cfe4141a-8e52-43bc-b9e9-c387366280d7">

**draw.io version (In the Help->About menu of the draw.io editor):**

**Desktop:**
 - OS: MacOS
 - Browser: Safari
 - Version: 21.3.8

**Desktop:**
 - OS: MacOS
 - Browser: Desktop app
 - Version: 21.3.7

**Comment by davidjgraph** [comment]
Arrow label alignment change in 21.5.0

**Comment by GitSparTV** [comment]
Perfect! Thank you very much.
<img width="1139" alt="image" src="https://github.com/jgraph/drawio/assets/5685050/95a0c4e8-657f-449c-acd3-6c5567a99627">
