### ISSUE TITLE
Flow diagram is missing in Edit mode Draw.io in confluence

### ISSUE THREAD

**Issue by Jay1989** [jgraph/drawio#3670]
### Preflight Checklist

* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by davidjgraph** [comment]
Please submit to https://drawio.atlassian.net/servicedesk/customer/portal/14
