### ISSUE TITLE
What version of mxGraph library does draw.io use?

### ISSUE THREAD

**Issue by msk4862** [jgraph/drawio#3673]
I have one query to ask:
Does `draw.io` uses mxGraph@4.2.2 only as base library which is the [latest version available](https://www.npmjs.com/package/mxgraph)? or does it some other modified version of mxGraph library?

As far as I understood this is the mxGraph file: https://github.com/jgraph/drawio/blob/dev/src/main/webapp/mxgraph/mxClient.js which is getting used for draw.io, and I see its different from the [mxGraph 4.2.2 version file].(https://github.com/jgraph/mxgraph/blob/master/javascript/mxClient.min.js).

So I just wanted to confirm if draw.io does uses some modified version of mxGraph? and if yes, are there any breaking changes that [this version](https://github.com/jgraph/drawio/blob/dev/src/main/webapp/mxgraph/mxClient.js) has compared to 4.2.2 version of mxGraph?

**Comment by davidjgraph** [comment]
It's not versioned, https://github.com/jgraph/drawio/tree/dev/src/main/mxgraph

**Comment by hxmwr** [comment]
How is the `mxclient.js` built? I didn't see any build script for `mxclient.js` just concatened with other scripts and packaged into the final `app.min.js`
