### ISSUE TITLE
how to integration with gitlab on ubuntu 22.04

### ISSUE THREAD

**Issue by goldli** [jgraph/drawio#3674]
hey, guys. i want to know how to integration with gitlab on ubuntu 22.04.

my environment is

host: 

      windows 11 pro x64 22H2

hyper-v client: 
                        
      ubuntu 22.04 lts ,   ip: 192.168.0.135
            gitlab version 16.0 ,  http://192.168.0.135
            tomcat version 10.1.10   http://192.168.0.135:7890
            draw.war version 21.40   http://192.168.0.135:7890/draw

i have searched around from the web finding  integration with gitlab. but , i am not lucky. one import thing is , gitlab and draw are not in docker. they are in a OS.
i have recorded a video for my environment and my trouble , and i need a clear solution.

some urls:

      gitlab project

            http://192.168.0.135/drawioGroup/drawio.git

      gitlab group

            名称(name): [drawio](http://192.168.0.135/drawioGroup)
            路径(path): drawioGroup

      user

            名称(name): drawio
            用户名(user name)： drawio
            电子邮件(email)： [drawio@draw.io](mailto:drawio@draw.io) 已验证

      gitlab application

            Application: drawio
            appId  bb837cf5430cd2e7ae8af087af640dac674afe88601dba3b7b053816ff8864d0
            回调 URL (callback url) http://192.168.0.135:7890/draw/gitlab

the video link

[mega link](https://mega.nz/file/xtM31A6b#7LiCQU7h7mlYFfhXUL2F-Q7sLjvDm9zN9RAfG7iVQUQ)
or
[terabox link](https://terabox.com/s/1XHwUkT_cPXuR-RfFE26Yfw)

**Comment by goldli** [comment]
2 days, no one knows how to solve it?

**Comment by davidjgraph** [comment]
2 days over the weekend and you don't have a solution, no. Read https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md and stop being so entitled.

**Comment by goldli** [comment]
long time no answer,  closed.

**Comment by davidjgraph** [comment]
Banning for breach of code of conduct.
