### ISSUE TITLE
line jumps over layered connectors

### ISSUE THREAD

**Issue by emily-drawio** [jgraph/drawio#3675]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
when two connectors lie directly on top of one another, and you put one over them perpendicular, there is no line jump. I could bypass this by clicking that third connector, and clicking "To Front". this was brought to me by a comment on one of our youtube videos: https://youtu.be/Wm9JgevPrIU

**To Reproduce**
drag shape to canvas, drag two shapes stacked on top of on another to the right of it, connect left shape to right top shape, and again connect left shape to right bottom shape (making sure connectors directly overlap). then drag shape above connectors, and drag from top shape down below connectors. turn on line jump for that third connector. I only achieved a proper line jump once I brought that third connector "To Front". _but_, when I did this exact process again in the same canvas 60 seconds later, i *was* able to get the line jump. so, it seems like sometimes it works, and sometimes it doesn't.

**Expected behavior**
line jump over layered connectors

**Screenshots**
<img width="483" alt="image" src="https://github.com/jgraph/drawio/assets/136879717/82ea0b2d-21d8-4541-9214-cf1e1ab8b028">
**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 21.4.0

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6
 - Browser: chrome
 - Version 114.0.5735.133

**Smartphone (please complete the following information):**
n/a

**Additional context**
hi sorry if this isn't done correctly, this is my first time using this website. hiii 👋🏼

**Comment by davidjgraph** [comment]
Hi Emily and welcome,

I can't repeat this, maybe you could show one of us over a video call? Either get a slack invite from Mike or arrange something via email, david@draw.io.

**Comment by emily-drawio** [comment]
Hi David!

it happened the ONE time I did it. I've done it many times over now on many different pre-existing diagram editors, and I've not been able to replicate it. I am unsure of the reason... but, I suppose this is a good thing? 😅 what shall we do now?

**Comment by davidjgraph** [comment]
I'm happy to pretend it never happened if you are, tree that falls in a forest and nobody hears it style...

**Comment by emily-drawio** [comment]
sure thing 😅 I just hope the user that brought this to my attention never runs into this again as well 🤦🏼‍♀️

**Comment by davidjgraph** [comment]
Could well have been https://github.com/jgraph/drawio/issues/2664 and it was an old version caching. If you came back later to the app if could have pulled the latest in.

**Comment by MartinX3** [comment]
In 24.6.4 it is still an issue.

![image](https://github.com/jgraph/drawio/assets/4518092/a3f5bc1f-cc65-48f6-a225-fc8101b47c11)
![image](https://github.com/jgraph/drawio/assets/4518092/22126941-441d-4547-a2bb-545bf2576af0)

It sometimes only works if they are not layered.
