### ISSUE TITLE
Newline in the table heading can't be removed

### ISSUE THREAD

**Issue by olfek** [jgraph/drawio#368]
There is a bug with `ER Table 1` in `Entity Relation` set where a newline in the table heading can't be removed. **This may affect other objects.**

Steps to reproduce:

1. Create new diagram.
1. Select `ER Table 1` in `Entity Relation` set and drag and drop it on to the page.
1. In the table heading text field, write something short and enter newline and immediately remove it by pressing backspace.
1. Click in an empty space on the page to un-focus the table heading text field.

Observe that that the newline is still there. It takes some trial and error to remove it.

**Comment by olfek** [comment]
Still a bug

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
