### ISSUE TITLE
Zoom function in 'Edit connection points' feature doesn't work

### ISSUE THREAD

**Issue by Bastesque** [jgraph/drawio#3684]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I wanted to add a few connection points to a shape. The shape is quite big, so I wanted to zoom in a little so it is easier to add it. Unfortunately, the zoom in and out function doesn't seem to work.

**To Reproduce**
1. Go to 'Edit Connection points'
2. Click on 'Magnifying glas icons' (see screenshot)
3. See error

**Expected behavior**
I can zoom in and out just like with the zoom function on the draw.io canvas.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io for Confluence Cloud
![Screen Shot 2023-06-21 at 21 09 12](https://github.com/jgraph/drawio/assets/68647048/55bc4800-1004-413b-b72c-bfcdf9e70689)

**Comment by davidjgraph** [comment]
Initial change in 21.5.1
