### ISSUE TITLE
Add grid to 'Edit Connection Points' function

### ISSUE THREAD

**Issue by Bastesque** [jgraph/drawio#3685]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Sometime it's hard for me to position the connection points the way I want them to be. I know that I can position them using the X and Y axis, but especially when I position a connection point inside a shape, a grid would be much more intuitive (just like the way you are offering it on the draw.io canvas.

**Describe the solution you'd like**
Adding a grid to the connection points editor

**Comment by davidjgraph** [comment]
Initial change in 21.5.1
