### ISSUE TITLE
Formatting of custom shapes and scratchpad doesn't get adapted when replacing shapes

### ISSUE THREAD

**Issue by Bastesque** [jgraph/drawio#3686]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When you take a custom shape (e. g. rectangle with custom color, line thickness and font) from your scratchpad or a custom library to replace an existing shape on your canvas, only the shape itself and the line-thickness get adapted. The shape color or the font (and font size) don't get adapted.

**To Reproduce**
1. Create a rectangle shape and color it in, change line thickness and font type/font size
2. Add the shape to the Scratchpad or a custom library
3. Add another shape to the canvas and select it
4. Try replacing the shape with the object from the Scratchpad/custom library

**Expected behavior**
Replacing a shape also adapts the color and font type/size of the target object

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io for Confluence Cloud

**Comment by davidjgraph** [comment]
Fix in 21.5.2
