### ISSUE TITLE
Vector path editing

### ISSUE THREAD

**Issue by jacobus** [jgraph/drawio#3690]
* [* ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [* ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the solution you'd like**
It would be great if DrawIO could allow path editing where practical in some shapes. Something similar to Figma's Pen tool. Just a quick and simple way to edit the vector path of an object.

**Comment by davidjgraph** [comment]
Thanks for your suggestion. It certainly makes sense in the context of vector graphics tools, but draw.io is scoped specifically as being a diagramming tool. Vector graphics is another domain of software tool (in which figma belongs). We don't want to extend the scope of the product.
