### ISSUE TITLE
Contrast in right sidebar to low for WCGA (AA)

### ISSUE THREAD

**Issue by wginolas** [jgraph/drawio#3691]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The contrast in the right sidebar does not meet the [WCAG (AA) guidelines](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast?utm_source=devtools&utm_medium=a11y-panel-checks-color-contrast). Especially in dark mode.

**To Reproduce**
1. Check the contrast with developer tools.

**Expected behavior**
Contrast is 4.5:1 or above.

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/1014026/e1504a61-5370-4c50-aad8-c5cdea1197bb)

**Comment by wginolas** [comment]
Yes, in this version the contrast is high enough. Sorry for the noise.

**Comment by davidjgraph** [comment]
That's ok, it's a valid report, I could hardly read the old version myself.
