### ISSUE TITLE
Update Kubernetes icons

### ISSUE THREAD

**Issue by nnlkcncff** [jgraph/drawio#3699]
There are cool icons in this project, how about replacing some existing icons with them and adding some missing icons too?
https://github.com/kubernetes/community/blob/master/icons/README.md

There some difference, for example, in drawio etcd icon slightly differs from the others and from the official diagram icon too:
https://kubernetes.io/docs/concepts/overview/components/

**Comment by egrimate** [comment]
Will be in next release

**Comment by davidjgraph** [comment]
In 22.1.12
