### ISSUE TITLE
Try to import CSV file, get Cannot read property 'length' of null error

### ISSUE THREAD

**Issue by gde-odoo** [jgraph/drawio#370]
When I try to import the following CSV file ([here](https://pastebin.com/qppxY7Pb)) I get the following error message: Cannot read property 'length' of null

In the past, I successfully import the CSV to generate my graph but now, impossible. I tried to find a reason for this message online but can't find anything. 
I tried many changes in the popup where I have to paste the CSV content without any luck. 
Even when I only import one column "name", it fails.

Hope you will be able to help me.

Thanks in advance.

**Comment by alderg** [comment]
The quote on line 126 (and maybe others) must be escaped. We'll add an error message for this case.
