### ISSUE TITLE
[Diagrams for Jira] Save image as SVG/PNG

### ISSUE THREAD

**Issue by kpalatzky** [jgraph/drawio#3704]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I want to use the Jira draw.io app, but currently using the draw.io app is completely pointless, because I work a lot on the SmartPhone and here it is not even possible to view the images.

**Describe the solution you'd like**
A simple and elegant solution here would be to include the "save format" in the configuration. 

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. The user then has the option to select "DrawIO", "SVG", "PNG".

If the user selects DrawIO, then the document will still be saved normally (mxfile). If he chooses one of the other two options this will be saved as an image with the embedded content.

This gives the additional possibility that the images can be included in the content and also the "draw.io" panel does not have to be used any further. 

**Additional context**

**Comment by davidjgraph** [comment]
Unfortunately, the Jira app doesn't support third party apps yet.

> A simple and elegant solution here would be to include the "save format" in the configuration.

Fix the default save format in the JSON configuration or just change the default?

At the moment Confluence Connect has a bug that mangles the PNG+XML format when we try to upload it. If that were fixed we could combine the two.

If you removed the draw.io panel there'd be no way to edit the diagram from within an issue. You'd have to download the file, edit and save it, then upload it again.
