### ISSUE TITLE
Page used as Background is missing elements on applied page

### ISSUE THREAD

**Issue by bigbird023** [jgraph/drawio#3712]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I have developed a diagram on page "bg", and then on "gn" page I have applied the background "bg".  The "gn" page is getting majority of the background but some "images" are not appearing on the "gn" page as a background

**To Reproduce**
1. create page bg, and add image from external resource
2. create page gn, and select bg as background
3. See error (missing image)

**Expected behavior**
Everything on the original background page should appear on any pages that have the background applied

**Screenshots**
bg screenshot
![image](https://github.com/jgraph/drawio/assets/617900/1fd3095a-8c7d-4c22-b288-64c79f4fc3cb)

gn screenshot
![image](https://github.com/jgraph/drawio/assets/617900/992b0c82-84d8-4b15-a948-326f1dd904e8)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version [e.g. 12.6.7]
- 21.5.2 - web version

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by davidjgraph** [comment]
Fix in 24.0.3.
