### ISSUE TITLE
clicking a connector in "Explore from here" lightbox makes the whole thing disappear

### ISSUE THREAD

**Issue by poopsmith-asf** [jgraph/drawio#3716]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I create a diagram with a few shapes that are connected.  I use the explore plugin (right-click -> Explore from here) on one of the shapes.  If I click on a connector, the whole diagram disappears and the lightbox is empty.

**To Reproduce**
I haven't been able to narrow this down fully.  I've seen the behaviour when I've created the connections:
- from the blue arrows on the 4 axes of a shape (blue arrow appears when hovering)
- from the various predefined connection points of a shape (blue x's on shape edge when hovering)
- manually using a connector shape from the library

It doesn't seem to matter what kind of shape I use.  I've proven this behaviour with:
- Organization rectangle from Advanced library
- Rounded Rectangle from General library

The one commonality is that there has to be a label on the connector, and it seems like more than 2 shapes are needed to reproduce the bug.  Sometimes the connectors are not clickable, but most of the time they are.  When you click them in this explore mode, the whole diagram goes bye-bye.

I've been trying to narrow this down to a base case, but I'm not finding this to be 100% reproducible :(

**Expected behavior**
I wouldn't expect the diagram to disappear.  In fact, I wouldn't expect the connectors to be clickable at all.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- 21.3.7

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 114.0.5735.134 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by davidjgraph** [comment]
Fix in 21.6.2
