### ISSUE TITLE
"Error loading file", "Not a diagram file (error on line 1 at column 1: Document is empty)", using integration-master

### ISSUE THREAD

**Issue by orionseye** [jgraph/drawio#3720]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Info ahead: The .png files i use are exported from Confluence "Export as > png > Include a copy of my diagram

I am getting **"Error loading file", "Not a diagram file (error on line 1 at column 1: Document is empty)"** when trying to load any editable png into the app.
I am using the **drawio-integration-master -> diagram-editor.js** for editable png's, inmplemented in tinyMCE editor v.5+
First i thought that it might be an editor issue, but then i tried using the "drawio-integration-master" files for testing,  with same bug.
**IMPORTANT!** Instead, when dragging the (e.g. file.drawio.png) into the app, everything works fine.
Not sure if it is related to https://github.com/jgraph/drawio-desktop/issues/965

**To Reproduce**
1. From Confluence page, Export a diagram as test.drawio.png
2. Use "drawio-integration-master" / javascript.html
3. Define img style="cursor:pointer;" title="Click to edit image" onclick="DiagramEditor.editElement(this);" src="test.drawio.png"/
4. Click the editable .png
5. See error

**draw.io version (In the Help->About menu of the draw.io editor):**
Latest https://github.com/jgraph/drawio-integration

**Comment by orionseye** [comment]
Short update:
I've tested the same differently and the issue persists by:
1. Visit diagrams.net and open the editor
2. create any diagram
3. export as name.drawio.png
4. use "drawio-integration-master" / javascript.html to open the file
5. issue same as above

**Comment by alderg** [comment]
Only data URIs are supported in this example.
