### ISSUE TITLE
Drawio file won't save. "Unsaved changes. Click here to save (Timeout)"

### ISSUE THREAD

**Issue by ogems** [jgraph/drawio#3722]
My drawio wont save after editing. It would say "unsaved changes. click here to save (timeout)

![Screen Shot 2023-07-11 at 5 23 25 PM](https://github.com/jgraph/drawio/assets/139221336/a72af9b2-b095-406a-9362-0dff49dcafc1)

I have noticed this right after updating my mac OS to Catalina. I have tried using it on both Safari and Google chrome both with the same result.

There were other people who had the same issue with me and I was not able to find the solution. Please help

**Comment by jprtf** [comment]
@ogems are you saving the file in the cloud (Google Drive, OneDrive, etc)?
Check if you have have compression active on your file.
I had this issue too, and I figured out that disabling the compression on `File > Properties` helps.
Once I disabled compression on my diagrams the files are saved without issues.
