### ISSUE TITLE
Can't group shapes with a table - context menu & menu

### ISSUE THREAD

**Issue by jaylapras** [jgraph/drawio#3725]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Select a table and some shapes. 
Right click and there is no "Group" in the context menu. 
Arrange > Group / Ungroup / Remove from Group is disabled

Should be able to group tables with shapes/connectors/text so they will move together.

<img width="1042" alt="image" src="https://github.com/jgraph/drawio/assets/60265913/b23513fc-b2b2-4b8e-a236-bf305542aab6">

<img width="1716" alt="image" src="https://github.com/jgraph/drawio/assets/60265913/d66086d4-d54c-43bf-8f4d-ea4161449360">

- draw.io version 21.6.1

**Comment by davidjgraph** [comment]
Fixed in 21.6.3
