### ISSUE TITLE
Shift + Alt + drag should always move a selected shape

### ISSUE THREAD

**Issue by jaylapras** [jgraph/drawio#3726]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

The selected shape is moved when holding shift + alt + drag when the mouse cursor is over a table cell, or other shapes on the canvas. 

The selected shape doesn't move if shift + alt + drag is done on a blank area of the drawing canvas (which draws a selection box instead). 

https://github.com/jgraph/drawio/assets/60265913/97ddab15-ea54-40e8-90a5-0a3bf854f5bb

Ideally, always move the selected shape with shift + alt + drag. 

- draw.io version 21.6.1

**Comment by davidjgraph** [comment]
Fixed in 21.6.3
