### ISSUE TITLE
Export diagram to csv

### ISSUE THREAD

**Issue by Amidamaru** [jgraph/drawio#3729]
* [ x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the solution you'd like**
Like importing from csv (according to that howto: https://drawio-app.com/blog/automatically-create-draw-io-diagrams-from-csv-files/) I would like to also export to csv. So both, import from and export to CSV should be possible in my opinion. The big advantage would be that you could further process the csv in automations and with little adjustments bring it back to the diagram.

**Describe alternatives you've considered**
An alternative I have considered was to export the diagram to XML, parse it and create an CSV with javascript. But this is not a convenient solution.

Any ideas or tips and tricks how to achieve what I want to achieve?

**Comment by tempest-1973** [comment]
I would like to see this too.  It would really help create a template that I can use for importing other diagrams without having to build out all the formatting code by hand

**Comment by tomcollis** [comment]
This is already discussed in #3161 

https://github.com/jgraph/drawio/discussions/3161

**Comment by davidjgraph** [comment]
This one is newer, but it's a feature request and so an issue, rather than a discussion.

**Comment by Amidamaru** [comment]
Hi @davidjgraph thanks for the clarification! Appreciate it.
Can you give us a hint If you May Work on this Feature request?

**Comment by davidjgraph** [comment]
I have no interest in implementing the feature, personally. I can't speak for the rest of the team.
