### ISSUE TITLE
Support IBIS Argument Mapping Diagrams

### ISSUE THREAD

**Issue by netname** [jgraph/drawio#3730]
**Suppot IBIS Diagram**
IBIS (issue-based information system) is an argumentation-based approach to clarifying problems.

It just needs 3 shapes: Question (Issue), Proposition (Idea), Argument.  Although it is common to add 2 more: Evidence (a reference to supporting documentation) and Decision (indicating which final proposition was chosen)

**Comment by davidjgraph** [comment]
Please link to the shape set.

**Comment by netname** [comment]
As I mentioned, it only needs 3 icons. But, I would argue, that you need 2 more: 
- Decision Made. Linked to a Position (idea), to indicate which was the conclusion
- Evidence. Linked to any other icon, to provide comments or indicate which is the external link to the evidence (documentation)
- 
[Wikipedia Article](https://en.wikipedia.org/wiki/Issue-based_information_system)

[eight2late Blog](https://eight2late.wordpress.com/2009/07/08/the-what-and-whence-of-issue-based-information-systems/)
![ibiselements](https://github.com/jgraph/drawio/assets/1933049/4772a7c8-419a-4efc-8d34-c3e92f763de4)

[CleverWorkArounds](https://www.cleverworkarounds.com/2009/09/16/the-practice-of-dialogue-mapping-part-2/)
![ibis-cleverworkarounds](https://github.com/jgraph/drawio/assets/1933049/75139cf9-cb58-494e-a5ec-81c3de73484c)
