### ISSUE TITLE
Copy Text from Viewer

### ISSUE THREAD

**Issue by ciis0** [jgraph/drawio#3732]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

-->  I check the org for a dedicated viewer repo, but there does not seem to be one, I hope this is the correct repo to file this bug.

**Describe the bug**

It currently does not seem to be possible to copy text when using viewer.diagrams.net

**To Reproduce**
1. Go to app.diagrams.net
2. Create a box with text in it
3. open the diagram in viewer
    1. file --> embed --> iframe...
    2. copy src link and paste to address bar (of a new tab/window)
5. try to copy the text
    1. double click does not mark text
        1. neither with alt, shift, ctrl or any combination
    3. drag does not mark text, shows "move" cursor
        2. also with shift, ctrl, or a combination of them.
        4. also alt shift
        3. alt (also in combiantion ctrl) draws "select objects" area

trivial example: https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram.drawio#RjZLBboMwDIafhuMkIAzWa1lXLpU2MWnniHgkWkJQGgrs6ReGU0Bo0k6xPzu28zsBydVwNrTlF81ABnHIhoA8B3EcJSRxx0TGmWQpgtoIhkkLKMU3IAyRdoLBdZNotZZWtFtY6aaBym4YNUb327RPLbddW1rDDpQVlXv6IZjlM32Ks4UXIGruO0fpYY4o6pPxJVdOme5XiJwCkhut7WypIQc5ied1me%2B9%2FBG9D2agsf%2B5UCRH9dXc3g8dKV8vWZ3nb8UDVrlR2eGDLQwWB7ajV8HormEwFQoDcuy5sFC2tJqivdu7Y9wq6bzImfvBfBcwrvoK4aBn0AqsGV0KRkmGouGviR%2FR75cdRF5YvtI%2FRUZx7fW99KKMM1Ac7y5L%2BI2tvjI5%2FQA%3D

**Expected behavior**

I can copy the text from viewer by marking or double-clicking it, possibly hidden behind ctrl/alt/shift.

**Screenshots**

I considered attaching a video, but I do not have a recorder at hand that records clicks and/or keyboard, so it would only be a recording of a wiggling mouse...

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.6.2

**Desktop (please complete the following information):**

||||
|--|--|--|
|OS|Windows|Windows
|Browser|Firefox|Edge
|Version|115|114.0.1823.82

**Additional context**

**Comment by davidjgraph** [comment]
As a workaround click the pen icon at the bottom and copy from the editor.

**Comment by davidjgraph** [comment]
Added in 21.7.3.

**Comment by ciis0** [comment]
I can confirm it works now, thank you!
