### ISSUE TITLE
Hotkey for "Redo" on "Ctrl+Shift+Z"

### ISSUE THREAD

**Issue by friendRU** [jgraph/drawio#3733]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
It is VERY inconvenient to press Ctrl+Y when most of modern apps have "Ctrl+Shift+Z" alternative.

**Describe the solution you'd like**
Just add a one more tracked hotkey variant for this action.

**Describe alternatives you've considered**
The best (but also hard) way to implement it is to allow users to customize the hotkey map.

**Comment by davidjgraph** [comment]
Added in 21.6.3
