### ISSUE TITLE
Use remote content (excerpts) in diagrams

### ISSUE THREAD

**Issue by defycgn** [jgraph/drawio#3735]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I use draw.io to illustrate data models and dependencies between them. These models are documented in detail (tables) outside the diagram on confluences pages. I currently miss a feature to not only link to these external pages in the diagram but to use excerpts from them for my diagram elements. Especially table contents. 

**Describe the solution you'd like**
Changes to these remote tables should be updated dynamically in the diagram, so that I do not have to maintain two areas redundantly.

**Describe alternatives you've considered**
Not using detail information in the diagrams but only the global names which doesn't change to often. But to shrink the quality and informative value of my diagrams is actually not what I really want.

**Comment by davidjgraph** [comment]
We've looked into this, unfortunately, the implementation is too complex to justify the effort. It breaks a lot of updating functionality in way we cannot see fixes for.
