### ISSUE TITLE
Exporting to png from browser throws URI malformed error

### ISSUE THREAD

**Issue by skilljar2022** [jgraph/drawio#3737]
X I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
X  have searched the issue tracker for a feature request that matches the one I want to file, without success.

When exporting to png from the browser version of draw.io an error message is thrown "URI malformed"

**To Reproduce**
1. Go to file > export > png
2. Click on export
3. See error

**Expected behavior**
Exporting to png should download a file to the machine

**Screenshots**
(Screen shot attached)

**draw.io version (In the Help->About menu of the draw.io editor):**
v21.6.5

**Desktop (please complete the following information):**
 - OS: Apple M1 Pro
 - Browser Chrome
 - Version Ventura 13.4.1

![Screenshot 2023-07-20 at 4 14 17 PM](https://github.com/jgraph/drawio/assets/114512772/2d9e53eb-5d6a-432f-9e0e-e95a5d451819)

**Comment by alderg** [comment]
Works for me. Please add the diagram you are tryint to export.

**Comment by davidjgraph** [comment]
Also, try in incognito with all extensions disabled.

**Comment by skilljar2022** [comment]
Hello,You can close out this ticket. I was using a background image url that doesn’t work and that fixed the problem. Appreciate the help!Sent from my iPhoneOn Jul 22, 2023, at 4:20 AM, David Benson ***@***.***> wrote:﻿
Also, try in incognito with all extensions disabled.
