### ISSUE TITLE
Support SVG as attachment in Confluence next to PNG

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#3738]
Provide flag, when true, that generates the SVG of the diagram as a page attachment when the diagram is saved, along side the data and PNG attachments.

**Comment by davidjgraph** [comment]
Added in 21.6.6, config is `generateSVGs: true`

**Comment by davidjgraph** [comment]
Added in conf cloud, actually, leaving open for DC.

**Comment by m-mohamedin** [comment]
Will be added to the next release [generateSVGs=1]

**Comment by davidjgraph** [comment]
In 12.2.0 release.
