### ISSUE TITLE
Opening Google Drive files directly in the editor for the first time does not work

### ISSUE THREAD

**Issue by inukiwi** [jgraph/drawio#3742]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Opening a link to a Google Drive file in the editor like https://app.diagrams.net/#G`fileid` does not work when the file hasn't been previously opened through Google Drive by the user. (https://drive.google.com/file/d/`fileid`/view)
It returns this error message: The file was not found. It does not exist or you do not have access. (`User`, `user@domain.ext`)
This has been tested on shared files on Google Workspace, both shared drives and personal drives. It appears to work correctly on viewer.diagrams.net.

**To Reproduce**
1. Share a diagram on Google Drive from one account
2. Don't open the diagram on the other account yet, but get the file ID
3. Open the file with the editor link: https://app.diagrams.net/#G`fileid`
4. **The error is shown**
5. Open the file with the Drive link: https://drive.google.com/file/d/`fileid`/view
6. The file loads correctly
7. Open the file with the editor link: https://app.diagrams.net/#G`fileid`
8. The file loads correctly

**Expected behavior**
Sharing a link directly to the editor should open the file correctly as well I think, just like sharing a link directly to the viewer does.

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/21198638/d79bed0f-4d17-4362-8a36-0d237d2e2feb)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: v21.6.5

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 115

**Additional context**
-

**Comment by davidjgraph** [comment]
This is a google enforced security rule. Third-party apps must only open Google Drive files via drive.google.com. The situtation they want to avoid is a user is sent a link to an app with the Google file ID to open and the user agrees to open it without realising it's a malicious app.

**Comment by davidjgraph** [comment]
It works on viewer.diagrams.net because the app there requests access to read all Google Drive files. app.diagrams.net is a different app with a much more restrictive permission.

We could change app.diagrams.net to read all your files, but the current permission massively restricts any possible attack surface.

**Comment by inukiwi** [comment]
Okay, thanks for the quick reply! We'll make sure to work around this then :)
