### ISSUE TITLE
Curved lines turn into straight lines after importing a VSDX file

### ISSUE THREAD

**Issue by m3y54m** [jgraph/drawio#3748]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

I have a diagram designed using Microsoft Visio 2019 and I imported it to draw.io app. Everything is almost OK except curved lines which turn into straight lines. 

**To Reproduce**
1. Go to 'File > Import from > GitHub'
2. Choose the repository: [m3y54m/Embedded-Engineering-Roadmap](https://github.com/m3y54m/Embedded-Engineering-Roadmap)
3. Select the file: `Embedded-Engineering-Roadmap.vsdx`

**Expected behavior**
I expect curved lined be imported exactly the same shape that they had in original Visio VSDX file.

**Screenshots**

Original VSDX diagram:
![image](https://github.com/jgraph/drawio/assets/1549028/36a7a098-e825-4b1e-88da-534bbcf47cd9)

After importing to Draw.io:
![image](https://github.com/jgraph/drawio/assets/1549028/610979f2-9cd5-40ae-aa58-a78592975f38)

**draw.io version (In the Help->About menu of the draw.io editor):**

- **21.1.1**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 115.0.2

**Comment by davidjgraph** [comment]
Duplicate #2104
