### ISSUE TITLE
Keyboard shortcut for Copy as image

### ISSUE THREAD

**Issue by rfbonte** [jgraph/drawio#3754]
I use Copy as Image a lot to paste models into different programs, mainly MS Word. I use the Desktop app on Windows and It takes a couple of mouse clicks that I would like to reduce/ move to keyboard.

**Describe the solution you'd like**
The ideal solution is descripbed in issue https://github.com/jgraph/drawio/issues/1845. Just use [CTRL]+[C] and depending of the target editor either paste as model, or paste as image.

Here I request an alternative: Keyboard shortcut for Copy As Image. Preferred:  [CTRL]+[ALT]+[C]

**Describe alternatives you've considered**
Using right-click and context menu instead of Edit menu already works a bit faster.

**Comment by davidjgraph** [comment]
Change in 21.7.3 release. Ctrl+Alt+X for copy as image.

**Comment by rfbonte** [comment]
Great @davidjgraph thanks. 
When will this version be available for Windows via MS Store? There I see 21.6.5.
