### ISSUE TITLE
Show page name in iframe embed

### ISSUE THREAD

**Issue by Arian-D** [jgraph/drawio#3763]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When embedding viewer.diagrams.net diagrams with iframe, there is a `< 1/n >` view at the bottom to show which page I'm on, which is great. The problem is that these pages have particular titles and I'm not able to view them unless I actually open the diagram in a separate tab.

**Describe the solution you'd like**
I was thinking it would be nice to show the page title somewhere in the bottom bar. It would also be nice to show the page title when hovering over the arrows instead of `(Next|Previous) Page`.

**Describe alternatives you've considered**
Opening the document externally :sweat_smile:  

**Additional context**
That was all. I'd understand if it's not feasible or needed, but it would just be nice to have.

Thank you

**Comment by davidjgraph** [comment]
Added in 21.7.0.
