### ISSUE TITLE
Pre-import image to Scratchpad

### ISSUE THREAD

**Issue by maxkaoppp** [jgraph/drawio#3765]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Can I pre-import image to Scratchpad in drawio when diagram onload?

**Describe the solution you'd like**
Defined pre-import image in JS function - because then we don't have to continuously import image to Scratchpad.

**Describe alternatives you've considered**
Not Yet.

**Additional context**
There is kind of similar issue https://github.com/jgraph/drawio/issues/5, but contents unlike title don't have bearing on actually embedding Scratchpad into file.

**Comment by davidjgraph** [comment]
Thanks for the suggestion. Unfortunately, the request didn't gain enough interest over the open it was open to justify the effort of implementation and maintenance.
