### ISSUE TITLE
Connector for link aggregation in networks

### ISSUE THREAD

**Issue by bitboy85** [jgraph/drawio#3766]
* [+ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ +] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Currently there is no connector for visualizing a link aggregation in networks.
It looks like this:
![grafik](https://github.com/jgraph/drawio/assets/6197580/449b7168-06bc-48a9-9810-d29d6f111a2d)

Basic version: just the two lines with a circle
Advanced version: with 4 text labels, two at each end to name the ports

**Comment by alderg** [comment]
Use the connector with symbol in the general tab, change the symbol to an ellipse and the the connector to a double line will [get you this](https://app.diagrams.net/?tags=%7B%7D#R7ZdNc5swEIZ%2FDcd0%2BPDnMXaSdjrpTCY%2BNFcFrUFTgRghjO1f3xWID0E8SRvHJ5%2BMXu2%2BSPtoZdsJ1sn%2BuyRZ%2FEtQ4I7v0r0T3Dm%2B782WHn5o5WCUSTCplUgyWmtuJ2zYEUxgoxaMQm60WlJCcMUyWwxFmkKoLI1IKUo7bCs4tYSMRGAtQwubkHAYhf1mVMW1upj2on8Ai%2BLmzZ5rZhLSBBshjwkVZU8K7p1gLYVQ9VOyXwPX1bPr8nBitl2YhFR9JGFaPicP4aOInudHUiyLny%2BzlxvjsiO8MBs2i1WHpgKQ0ltdSByFnOQ5C51gFauEo%2BDhoxRFSkG%2FxMXRVqTKUPRwi6uwkLtqUodiCTI9w1n6B4f1q4BGw1p3W%2FLaQuERA5GAkgcMkcCJYjs7jxjUURvXpj4Jho6%2Ba87ljTcL6pxDI8wHJrkoZAgmr1%2FVodW7TorICNTICR96W%2Bqkito%2FEPTfJ9iUHd2wbcDGJwqFOGDd9s%2BQ4gzHGUiGCwXZuTx10qqMmYJNRkKdUOJNoC0Y52vBhU5JRQot7x1IBfuTxE8f0%2FExKLuOxGVWVnGvGf1FrX32tCwGhCe2g9huc%2FgStsGI7Rvtie3zSF7x3rWwEs6iVLcsFrZipMvO8F67NRMJo1R7rCTk7EheKz%2FNPtO7r7Y2XTnTuzdOw0mO5hI2Zv079f%2F4NgDcb3PfZhCch%2BzScvX8S4GdjMB6V7DnBDts2cWlyE5HZIMr2TOSXXjDr9tLkZ2NyE6uZL%2BOrOd9HiwOu9%2FXdXj3NyW4%2Fws%3D):

<img width="122" alt="Screenshot 2023-08-25 at 08 11 50" src="https://github.com/jgraph/drawio/assets/921200/9979599b-d983-436c-adff-91583aacf7da">

**Comment by bitboy85** [comment]
Can you tell me how excactly you changed the symbol and added the labels?

And do you think its possible to have the text labels correctly positioned when the connector is moved or resized?

**Comment by alderg** [comment]
Change symbol: Drag and drop new symbol on old symbol
Adding labels: Double click

The labels should stick to the connector ([try this link](https://app.diagrams.net/?tags=%7B%7D#R7ZdNc5swEIZ%2FDcd0%2BPDnMXaSdjrpTCY%2BNFcFrUFTgRghjO1f3xWID0E8SRvHJ5%2BMXu2%2BSPtoZdsJ1sn%2BuyRZ%2FEtQ4I7v0r0T3Dm%2B782WHn5o5WCUSTCplUgyWmtuJ2zYEUxgoxaMQm60WlJCcMUyWwxFmkKoLI1IKUo7bCs4tYSMRGAtQwubkHAYhf1mVMW1upj2on8Ai%2BLmzZ5rZhLSBBshjwkVZU8K7p1gLYVQ9VOyXwPX1bPr8nBitl2YhFR9JGFaPicP4aOInudHUiyLny%2BzlxvjsiO8MBs2i1WHpgKQ0ltdSByFnOQ5C51gFauEo%2BDhoxRFSkG%2FxMXRVqTKUPRwi6uwkLtqUodiCTI9w1n6B4f1q4BGw1p3W%2FLaQuERA5GAkgcMkcCJYjs7jxjUURvXpj4Jho6%2Ba87ljTcL6pxDI8wHJrkoZAgmr1%2FVodW7TorICNTICR96W%2Bqkito%2FEPTfJ9iUHd2wbcDGJwqFOGDd9s%2BQ4gzHGUiGCwXZuTx10qqMmYJNRkKdUOJNoC0Y52vBhU5JRQot7x1IBfuTxE8f0%2FExKLuOxGVWVnGvGf1FrX32tCwGhCe2g9huc%2FgStsGI7Rvtie3zSF7x3rWwEs6iVLcsFrZipMvO8F67NRMJo1R7rCTk7EheKz%2FNPtO7r7Y2XTnTuzdOw0mO5hI2Zv079f%2F4NgDcb3PfZhCch%2BzScvX8S4GdjMB6V7DnBDts2cWlyE5HZIMr2TOSXXjDr9tLkZ2NyE6uZL%2BOrOd9HiwOu9%2FXdXj3NyW4%2Fws%3D)).

**Comment by alderg** [comment]
[This link works better](https://app.diagrams.net/#R7ZZLb6MwEMc%2FDcdKPAJNjiV9rFZdqWoO26uLJ2CtwciYkOTT7xjMwyHbh7qPw%2FYE%2Fntm7Jmfx%2BAE63x%2FJ0mZfRMUuOO7dO8E147ve5EX4EMrh05ZrfxOSCWjneSOwoYdwXj2as0oVEbrJCUEV6y0xUQUBSTK0oiUorHNtoJTSyhJCtY2tLBJCIeZ2XdGVdapy3Bi%2FQVYmvUre66ZyUlvbIQqI1Q0Eym4cYK1FEJ1b%2Fl%2BDVwXz67L7S9mh41JKNRbHMLmMb9N7kX6eHkk9ar%2B%2BhQ9XZgoO8Jrk7DZrDr0FYCCXulC4ijhpKpY4gRxpnKOgoevUtQFBb2Ii6OtKJSh6GGKcVLLXTupTbEEpZ7hrPiBw3kGZjtA02n5TT53IHJQ8oAGEjhRbGczIgZ1OtgNrg%2BC4RK%2Ba47lhReZY3nohcuTIJWoZQLGb1rV01CvRlJEpqBmkfBlktIotdTeQdB%2FnWBfdoyGbQM2PlErxAHroX9OKUY4LkEy3CjIMcrDKMVNxhRsSpJohwYvAh2Ccb4WXGiXQhRwlveLZxKkgv2Lx6AZOxK32Xplk2b0l5320dOyPCG8sCOI7baCP8I2mLE9057YK%2FfkGa9dCyvhLC10y2KtW0a6nAzvtSszkTNKdYxYQsWO5LmNp9mXOvs2tTB2wuszp%2BGDHIfL2ixq3YcW36FdLQD9p%2BHNWC0s72WwmDHwPhng8K9CCGcQgv8Rwr%2Fsg2iGYPGJ4Le1AQ7HP8Hu8zH%2BTwc3PwE%3D) for automatic label positions. Make sure you are using x=[-1...1] y=[-10..10] in the geometry of those labels:
<img width="692" alt="Screenshot 2023-08-29 at 11 52 52" src="https://github.com/jgraph/drawio/assets/921200/3eac3090-ceac-4bb7-a175-442eef2a40a3">

**Comment by bitboy85** [comment]
Thanks for your time!

With drag and drop to change the symbol i end up with this.
![grafik](https://github.com/jgraph/drawio/assets/6197580/992f82cd-4e72-4656-bcf6-8578e9439469)
