### ISSUE TITLE
Embedding exported SVG with 'enableCssDarkMode' enabled is affecting other SVGs

### ISSUE THREAD

**Issue by NivruthaB** [jgraph/drawio#3768]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I export an SVG in dark theme with the new colour adaption technique enabled(i.e when "enableCssDarkMode" is true) and use it in our application where there are other SVGs present, we see that the colour adaption affects the other SVGs we have as well.  

**To Reproduce**
1. In dark mode, add a shape. 
2. Export the diagram as SVG with 'Appearance' setting as 'Dark'.
<img width="437" alt="Screenshot 2023-08-08 at 14 52 05" src="https://github.com/jgraph/drawio/assets/86827455/aa60868a-b737-4af6-8302-c950714a17a0">

3. If we now embed the exported SVG in another application where there are other SVGs, we see that the colour of the other SVGs is also affected.  

**Expected behavior**
I see that this is because **filter: invert(100%) hue-rotate(180deg)** property is added to svg in general. Is there any way to target it just at just SVGs from drawio? 

**Screenshots**
I have attached a simple example by placing the exported SVG in w3schools where there is another SVG. 

**Original colours:**
<img width="856"  alt="without-drawio-svg" src="https://github.com/jgraph/drawio/assets/86827455/fc9afb8a-b737-4df9-aa34-f63865e9901f">

**After adding drawio SVG:**
<img width="836" alt="with-drawio-svg" src="https://github.com/jgraph/drawio/assets/86827455/cada1ba2-1525-45f5-b292-97b5055162b7">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: 21.6.6

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: macOS Ventura 13.2.1

**Comment by davidjgraph** [comment]
Fix in 21.6.9
