### ISSUE TITLE
Keyboard shortcut for inserting rows in UML Classes, tables, and DB entities

### ISSUE THREAD

**Issue by maxgraybremner** [jgraph/drawio#3773]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
There does not appear to be a keyboard shortcut for inserting rows into Database entity tables or UML classes.
The closest thing i have been able to find is using ctrl + d and duplicating rows, but this adds a row to the end of the table.
This is obviously a nice to have but i have come across a number of forum posts with users asking if this feature exists. 

**Describe the solution you'd like**
It would be nice to have a keyboard shortcut for inserting rows into these tables, say "ctrl + i" for inserting rows beneath the current selected row. 

**Describe alternatives you've considered**
-

**Additional context**
if this is already a feature please let me know.

**Comment by alderg** [comment]
Try Ctrl+Enter (Cmd+Enter on macOS).

**Comment by maxgraybremner** [comment]
Thanks @alderg that is perfect
