### ISSUE TITLE
Preview diagram in Google Drive

### ISSUE THREAD

**Issue by DrHeinzDoofenshmirtz** [jgraph/drawio#3775]
* [ x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

I would really like if it was possible to preview a draw.io file when browsing the file in Google Drive.

When double-clicking a draw.io file it opens the browser version of draw.io for editing. But there is no Preview option, which is what I want.

Currently it looks like a thumbnail is generated, that I can see in Google Drive, so it kind of communicates that Google Drive is able to render the draw.io file. But I believe it is just a thumbnail.

**Comment by davidjgraph** [comment]
Thanks for the suggestion. Unfortunately, there is technical mechanism to implement such functionality.
