### ISSUE TITLE
Errors with autosave and collaboration

### ISSUE THREAD

**Issue by 8floorltd** [jgraph/drawio#3777]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When working on a document online from google drive, changes are not always saved. When working together, changes are not always synchronized and often one person's work is overwritten by an older version of another person's document/tab. As a result, work becomes a constant tracking of relevance and data recovery. The cookie settings are correct. Autosave is enabled.

**Expected behavior**
One or more people are working with the document and edits are saved in addition to each other.

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 21.6.7

**Comment by 8floorltd** [comment]
> any errors in the browser console when this happens?

over 1,000 such messages
- Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

and a dozen of these
- Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

and isolated messages like this
- DevTools failed to load source map: Could not load content for chrome-extension://cofdbpoegempjloogbagkncekinflcnj/build/content.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
-[2023-08-11 15:34:46][EventHandler][constructor] not enable app.diagrams.net  content.js:49

**Comment by davidjgraph** [comment]
Could you disable your browser extensions you have enabled and check again please?

**Comment by 8floorltd** [comment]
> Could you disable your browser extensions you have enabled and check again please?

After disabling all extensions, the console became empty. I found extensions that generated errors:

**DeepL**
- DevTools failed to load source map: Could not load content for chrome-extension://cofdbpoegempjloogbagkncekinflcnj/build/content.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
- Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
- app.min.js?__WB_REVISION__=7bbe15fda9109f88254d773211c22514:288     GET https://www.googleapis.com/drive/v2/files/1lwmhZXzf8JApjW9wodCgfuNuDRxnrPUR?supportsAllDrives=true&fields=etag,headRevisionId,modifiedDate,properties(key,value) net::ERR_CONNECTION_CLOSED

**Flappypedia**
- [2023-08-11 15:34:46][EventHandler][constructor] not enable app.diagrams.net content.js:49

PS Also noticed that there are still posts that are always shown, regardless of extensions. I am attaching their screenshots just in case: https://prnt.sc/j-JilTlyRrBd

**Comment by 8floorltd** [comment]
> OK, but it works with the extensions off?

It takes a while to test it in operation. I will test it within an hour and post it here.

**Comment by 8floorltd** [comment]
> OK, but it works with the extensions off?

Everything works great now, thanks!
As for conflicts with extensions - should I write to the developers of these extensions or whose side is the error here?

**Comment by davidjgraph** [comment]
Unfortunately, it's up to the end user to deal with this. There are hundreds of thousands of web applications and a similar number of chrome extensions. There's no possible way for any party to apply significant effort to address such issues.

You just have to understand that when you add an extension you're changing the browser to behave differently and debug when there are issue.

**Comment by 8floorltd** [comment]
> Unfortunately, it's up to the end user to deal with this. There are hundreds of thousands of web applications and a similar number of chrome extensions. There's no possible way for any party to apply significant effort to address such issues.
> 
> You just have to understand that when you add an extension you're changing the browser to behave differently and debug when there are issue.

Thank you, this is a valuable comment and experience!
