### ISSUE TITLE
Trying to load the mermaid code in embed mode. Like load csv descriptor

### ISSUE THREAD

**Issue by BoovendanM** [jgraph/drawio#3783]
Since the mermaid to drawio non minified version is not available for general public. as per the issue - https://github.com/jgraph/drawio/issues/3782

Any other approach to auto create the drawio diagrams from mermaid code in the drawio embed mode ?? through any existing actions using the integration ?

**Comment by BoovendanM** [comment]
Any possibility that I can pass the mermaid code from outside and generate a diagram in drawio on embed mode message pass through api ? or otherwise ?

**Comment by tianxiuali** [comment]
I have the same question

**Comment by alderg** [comment]
This is currently not supported.

**Comment by tianxiuali** [comment]
Oh no☹Is it easy to support? I really need that feature😥

**Comment by alderg** [comment]
This is now supported. You can pass Mermaid code to the embedded editor via the JSON protocol (`proto=json`) using the `descriptor` field in the `load` action:

```json
{
  "action": "load",
  "descriptor": {
    "format": "mermaid",
    "data": "graph TD\n  A[Start] --> B[End]"
  }
}
```

The editor will parse the Mermaid code and convert it into a draw.io diagram. Note that `isMermaidEnabled` must be `true` in the editor environment (it is by default on embed.diagrams.net).

You can also preserve the original Mermaid source in the diagram model using `sourceMetadata`:

```json
{
  "action": "load",
  "descriptor": {"format": "mermaid", "data": "graph TD\n  A-->B"},
  "sourceMetadata": {"key": "mermaidSource", "value": "graph TD\n  A-->B"}
}
```
