### ISSUE TITLE
Emojis on dark mode look wrong.

### ISSUE THREAD

**Issue by SrGeneroso** [jgraph/drawio#3784]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Emojis looks weird in dark mode.

**To Reproduce**
1. Add an emoji of the type on the canvas
2. Go to 'appearance'
3. Click on 'dark'

**Expected behavior**
I would think that the emojis would be the same as I selected or copied but it shows incorrect colors.
**Screenshots**
<img width="294" alt="image" src="https://github.com/jgraph/drawio/assets/5541794/6edc9b54-cbd3-4c28-9f6c-7f35c0c9f1e0">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [21.6.7]

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Brave]

**Additional context**
They look ok in light mode, but I guess emojis should not change despite style mode selected.

**Comment by SrGeneroso** [comment]
Also, saving the file breaks the emoji. when you reload or open a file (I've tried XML as .drawio in github and desktop), it doesn't shows anymore. Both in web and desktop app.
<img width="668" alt="image" src="https://github.com/jgraph/drawio/assets/5541794/a4407431-2b60-49b2-bdac-6e579ba126a6">

**Comment by davidjgraph** [comment]
Where does this emoji window come from in the first post?

**Comment by SrGeneroso** [comment]
> Where does this emoji window come from in the first post?

From windows, "Win + . " launchs the emoji keyboard, but it's not really important, you can copy the emoji from another place and the results are the same. I just used like that to make it fit in a smaller screenshot.

**Comment by SrGeneroso** [comment]
#3701 I think is related to this. I'll close this issue and follow that discussion.
