### ISSUE TITLE
In the paper size customization, the unit is still in inches

### ISSUE THREAD

**Issue by Power-onoff** [jgraph/drawio#3788]
Changed from View > Unit to Millimeter
There are still parts that are displayed in inches

There was talk about this a long time ago, but I think it's still the same
Is there any update plan for this fix?

![image](https://github.com/jgraph/drawio/assets/114426350/57a4c693-ca03-4651-8e2d-4433dac998e0)

![image](https://github.com/jgraph/drawio/assets/114426350/d9f13fa2-a6da-4ebf-81ee-688940ae3267)

**Comment by patrickbard** [comment]
Yes, this is very annoying

**Comment by davidjgraph** [comment]
See 24.4.6.
