### ISSUE TITLE
www.draw.io reference inside generated files

### ISSUE THREAD

**Issue by VirtualEvan** [jgraph/drawio#379]
We have been testing some file exports/embed and they look to point to www.draw.io inside
Would be possible to change this for the name of the server where it was created?

**Options tested:**
* embed html
* embed image
* embed svg
* export svg
* Save as > Device

#### An example of what I mean inside an embed
```
https://www.draw.io/?client=1&amp;lightbox=1&amp;edit=_blank
```
I think is [this one](https://github.com/jgraph/drawio/blob/336e02cecf60bff46e35d532d9d6ecd6e2fff00e/src/main/webapp/js/diagramly/EditorUi.js#L5563) 

Also saw that "editor" is specified as www.draw.io, to reference the application and not the website maybe "drawio" could be enough

```
<mxfile userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" version="9.3.1" editor="www.draw.io" type="device">
```

**Comment by alderg** [comment]
We can add EditorUi.embedHost to configure this but we can't use location.host since some of our integrations would break. The editor attribute in mxfile was changed to host quite some time ago.
