### ISSUE TITLE
Link for customized Libraries

### ISSUE THREAD

**Issue by Brisika** [jgraph/drawio#3793]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.

* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. [No]

**Describe the solution you'd like**
I am looking for a feature for inserting the link for customized library. We use Draw IO for our QMS and in the procedure we would like to guide our colleagues to use the specific customized libraries. Instead of inserting a whole diagram using all the legends in the library. The customized libraries are not always visible; you need to find it by clicking on the more (+) button. Thus it would be nice to have a link for customized libraries.

**Describe alternatives you've considered**
For now, I will have a diagram with all the legends from the customized library and insert the link for that diagram but this can be misleading and messy. 

**Additional context**
I do not have screenshots but appreciate if you can give me the reason for not going ahead with this feature.

**Comment by davidjgraph** [comment]
https://github.com/jgraph/drawio-libs readme explains the process for creating URLs with custom libraries.
