### ISSUE TITLE
"Delete Waypoint" option when drawing arrow.

### ISSUE THREAD

**Issue by codemaivanngu** [jgraph/drawio#3794]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Sometimes I don't really want to clear all waypoints when drawing arrow.

**Describe the solution you'd like**
 A choice to choose a waypoint or a set of way points and delete it only will be very helpful for me.

**Comment by alderg** [comment]
Try right click, remove waypoint:
<img width="367" alt="Screenshot 2023-08-24 at 16 22 17" src="https://github.com/jgraph/drawio/assets/921200/2ee92870-2f25-4583-836e-829b5a061a76">

**Comment by codemaivanngu** [comment]
> Try right click, remove waypoint: <img alt="Screenshot 2023-08-24 at 16 22 17" width="367" src="https://user-images.githubusercontent.com/921200/263003730-2ee92870-2f25-4583-836e-829b5a061a76.png">

But some of them don't have this function.
![image](https://github.com/jgraph/drawio/assets/90603532/5ae0fc4f-6dde-4f21-b830-91fb2af550bd)

**Comment by alderg** [comment]
Can you share a test case and let us know which of the waypoints doesn't have that function so we can check why that is?
