### ISSUE TITLE
Error loading file, not a diagram file 

### ISSUE THREAD

**Issue by TinhAnhGitHub** [jgraph/drawio#3797]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I used draw.io to draw some diagrams for my project, and I saved it in GitHub. This morning, everything worked properly, saving the files, drawing,... But when I opened the project just then, it didn't load up the file. 
I checked the file in GitHub, the whole code is there but draw.io could load the file up. 

**To Reproduce**
1. Go to draw.io
2. Open existing file
3. Direct to GitHub
![image](https://github.com/jgraph/drawio/assets/120301674/22de389a-bea2-4006-8f62-cb2fb0c2278a)

5. And see this error:
![image](https://github.com/jgraph/drawio/assets/120301674/e1ffac2e-3f1d-4a4a-bf49-d40671d462cc)

**Expected behavior**
Well it should have popped up the project. 

**draw.io version: **

- draw.io version:  [v21.6.8] 

**Desktop (please complete the following information):**
 - OS: Window 11
 - Browser chrome

**Smartphone (please complete the following information):**

**Comment by alderg** [comment]
If the repo is public, please include the URL of the file, else, please attach a copy of the file.

**Comment by DarkDonnerGunther** [comment]
I have the same problem. Here is the repo. I can not open any file from here.

https://github.com/DarkDonnerGunther/rivercookery/tree/main/vegeterian%20Pizza

When I download the files I can open it from my device inside of draw.io-webpage and draw.io-app on Windows 10.

**Comment by DarkDonnerGunther** [comment]
Thanks, this helped me a lot. But, now the other way works, too. So, maybe there was a bugfix.

**Comment by DarkDonnerGunther** [comment]
Thanks, this helped me. But only for a diagram in the main root of the repository.

So, for this diagram it works:
https://github.com/DarkDonnerGunther/rivercookery/blob/main/legend_graphic.drawio

But for this, it does not work:
https://github.com/DarkDonnerGunther/rivercookery/blob/main/vegetarian_pizza/de_vegetarische_Pizza.drawio

When I save the diagram at the first time and let it open in draw.io, everything works fine. But if I want to open it again from GitHub it does not open.

**Comment by DarkDonnerGunther** [comment]
Ok, this works for me, too. And I can save and export the diagram. Thanks. So, maybe there is a problem with the interaction between my github-account and draw.io. But is there a simple way to create the link, you sent me?

**Comment by davidjgraph** [comment]
When providing the URL of a diagram you have to provide the raw URL of that file. Pointing the HTML page displaying a UI for the file isn't going to work.
