### ISSUE TITLE
Autosave problems, losing work using diagrams.net online

### ISSUE THREAD

**Issue by Roche-Tactile** [jgraph/drawio#3800]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Sometimes the autosave is not working, so a lot of valuable work gets lost. It is also irrecoverable via revision history.

**To Reproduce**
1. No exact steps to reproduce sadly, but usually being on the same document (so having the tab open and active) both typing and not typing for a long time (over 30 minutes maybe? Hard to tell) would cause it to stop autosaving/making save feature do nothing.
2. Sometimes there are connection drops so we'd be working offline without knowing it and then it would not save
3. Sometimes we work on a diagram, then open it the next day and it's no longer there.

**Expected behavior**
Expected the autosave to always work no matter how long we work on a document.

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/135694705/b8949386-c071-4b67-89b1-e2fceebc5d0f)

**draw.io version (In the Help->About menu of the draw.io editor):**
- We are currently on v21.6.8 but we've been having issues since more than 13 days ago.

Thanks for the help.

**Comment by davidjgraph** [comment]
Do you have any browser extensions installed?

Please attach a screenshot of the result you get for https://speed.cloudflare.com/ . It would be good to get that when you have the save issue.

What is the diagram size shown in Google Drive?

**Comment by Roche-Tactile** [comment]
What also happened a couple of times was that in a folder with multiple tabs, someone else going into one tab and looking at things (sometimes not even changing/saving) would cause work in another tab which they hadn't touched, to disappear.

**Comment by alderg** [comment]
What version of the app, browser and OS and versions are you using?

**Comment by alderg** [comment]
At the bottom of the help menu in the browser version of the app, what version number do you see?

**Comment by Roche-Tactile** [comment]
v21.6.8

**Comment by Roche-Tactile** [comment]
The last time was around last week. We are using both Windows and Mac and the problems have occurred in both.

**Comment by Roche-Tactile** [comment]
Hello,

Update:
We just had this real-time collaboration error this morning and it might be related to the save issues that we are having.

![image](https://github.com/jgraph/drawio/assets/135694705/4389b15c-e9d7-47c0-a606-a4965cda2167)

**Comment by Roche-Tactile** [comment]
![image](https://github.com/jgraph/drawio/assets/135694705/c42dccd8-bafa-4ae1-9fb9-5d72f344b543)![image](https://github.com/jgraph/drawio/assets/135694705/957bd357-ea4a-411a-a3d5-4b71b6e52d77)

Other images that might help. This happened yesterday morning.

**Comment by Roche-Tactile** [comment]
They are being saved into google drive.

**Comment by davidjgraph** [comment]
OK, then I cannot explain why the app is trying to write to your local machine. That message only makes sense if you had selected "device" as your storage option.

**Comment by Roche-Tactile** [comment]
Hi again, just checking in to ask about the progress on this issue. I have seen someone post about a similar issue [here](https://github.com/jgraph/drawio/issues/3828).

**Comment by davidjgraph** [comment]
#3828 is using the desktop tool, they have posted in the wrong place.

We're not able to recreate the problem, particularly the part where it writes to the file system. Using the web app and saving from the browser to google drive never accesses the file system. The most likely cause is a browser extension, but we don't investigate issues caused by those.

**Comment by davidjgraph** [comment]
Unfortunately, we cannot reproduce how a google drive save would invoke the file system. There's something we don't understand on this system, but we're not going to investigate any further.

**Comment by brianivander** [comment]
Hey! I'm having the same problem, this drives me crazy. I've worked all night on diagrams.net only to figure out that in the morning all my changes are gone. I'm sorry I can't put my stuff here because it's confidential, but you need to do something about this.

**Comment by davidjgraph** [comment]
Although this thread is older, there is another thread open at https://github.com/jgraph/drawio/issues/3983.
