### ISSUE TITLE
File size in app.diagrams.net

### ISSUE THREAD

**Issue by Mexxicanec** [jgraph/drawio#3801]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Big file size in app.diagrams.net

**To Reproduce**
1. Go to 'https://app.diagrams.net/'
2. Click on 'File-Open from-Device'
3. Open file (its size is 807 kb)
4. Making some changes (minor)
5. Click on 'File-Save As' (File type: "XML File (*.drawio;..")
6. The size of the newly saved file is larger than 10 times the size of the original file (10353 kB vs 807 kB) 

**Expected behavior**
How can I influence the size of saved files? 
With the PNG extension, the story is similar.

**Screenshots**

**https://app.diagrams.net/**

-  OS: [Windows 10 Pro ]
 - Browser [chrome 116.0.5845.96]
 - Version [21.6.8]

**Comment by davidjgraph** [comment]
We'd need the before and after diagram files please.

**Comment by Mexxicanec** [comment]
[Before-after.zip](https://github.com/jgraph/drawio/files/12406043/Before-after.zip)

**Comment by alderg** [comment]
Are you sure these are the correct files? Before has 1 page, after has 10 pages.

**Comment by Mexxicanec** [comment]
Oh!
I understand the reason...
Thank you. Didn't even look at it...
Please delete these files

**Comment by Mexxicanec** [comment]
Issue resolved.
Thank you!
