### ISSUE TITLE
Draw.io diagrams are all now blank

### ISSUE THREAD

**Issue by Emruc** [jgraph/drawio#3803]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I created a number of Draw.io diagrams that i saved to my one drive, all such created diagrams are now blank when opened in the web page with no way to roll back or view them another way.

**To Reproduce**
1. Go to 'Draw.io'
2. Click on 'File open/ one drive diagram'
3. Scroll down to '.the diagram in question open it'

**Expected behavior**
The diagram should open to the flow chart i have created for each diagram, this has happened every other time but they are all now blank

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Emruc** [comment]
Hi David, no that doesn't help it still appears as blank. Seems another user had this issue possibly due to One Drive?

**Comment by davidjgraph** [comment]
No, there's never been a case where all diagrams were affected in this way. Could you fill in the details of the bug template please?

**Comment by Emruc** [comment]
Ok will do that now thanks
