### ISSUE TITLE
Drawio sometime freezes when text is copied into the shape

### ISSUE THREAD

**Issue by Zoellick** [jgraph/drawio#3811]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When copying a text into the shape it sometimes freezes for a considarable amount of time or forever.
I haven't found an exact conditions under which the problem happens. Typicaly it happens after a significant amount of shapes with text is already present on a digram.

**To Reproduce**
create rectangular shape, 
press Ctrl+V to paste text from buffer into the shape

**Expected behavior**
No freeze

**Screenshots**
![drawio freeze threads](https://github.com/jgraph/drawio/assets/7482078/50f4796b-d22d-4d67-85ca-b29b4008e1ca)
![drawio freeze stack](https://github.com/jgraph/drawio/assets/7482078/ddd8cd65-f583-4214-b27a-0ee7f117dfe4)
Minidump: [draw-mini-dmp.zip](https://github.com/jgraph/drawio/files/12427771/draw-mini-dmp.zip)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.6.8, standalone

**Desktop (please complete the following information):**
 - OS: 10.0.19045 Build 19045

**Additional context**
I created a full dump of a process memory and ready to upload it onto FTP or send you by any other means.

**Comment by thanhpk** [comment]
I have the similar issue, the app just hang after I paste this text `71435390-f63b3a2-2ba5499-7f23d900e4d0-c001cac-1445-75` (just a random id tooked from my server)

**Steps to reproduce:**
1. Open draw.io (v22.0.3) on Ubuntu 20.04 (xfce 4.16)
2. Create a new diagram
3. Paste this text 71435390-f63b3a2-2ba5499-7f23d900e4d0-c001cac-1445-75
4. draw.io hang

**Comment by alderg** [comment]
Should be fixed.
