### ISSUE TITLE
Error when loading diagram, not a diagram file

### ISSUE THREAD

**Issue by Haryto** [jgraph/drawio#3813]
Hello!

I have few "DrawIO" diagrams exported from the **Confluence**.
These diagrams are exported as separate ".drawio" and ".drawio.png" files.
In case with specific diagram ".drawio" contains diagram data, and ".drawio.png" contains diagram image.

I have a need to produce from that one ".drawio.png" file which will contain diagram image with diagram data located in `tEXt` PNG meta data chunk.

I succeeded with placing necessary diagram data in `tEXt` chunk, so image is correctly processed by any image viewer (so PNG structure is not corrupted). But when I try to open that PNG file in DrawIO editor - I receive such an error:
`Not a diagram file (error on line 1 at column 8: error parsing attribute name)`
After that I tried to open in DrawIO editor:
1. Original ".drawio" file from export data, to make sure that file is correct. It was opened without any issues.
2. Extracted from `tEXt` chunk diagram data (which I saved as separate file), to make sure that diagram data was not corrupted when placed into `tEXt` chunk. It was opened without any issues as well.

Also I created random DrawIO diagram in online editor, exported it as PNG and compared with my PNG file (mostly I looked on `tEXt` meta data chunk). They look pretty similar, so I don't have any idea what is wrong...

I would appreciate any help or hints how to proceed. Also I can attach both files (file with diagram data and PNG file) if needed.

Thank you in advance!

**Comment by alderg** [comment]
Yes, please attach the files.

**Comment by Haryto** [comment]
Thank you for a quick response!
Attached [drawio_issue.zip](https://github.com/jgraph/drawio/files/12463828/drawio_issue.zip) with such files:

- `diagram_after_export.drawio` and `diagram_image_after_export.drawio.png` - files got from **Confluence** export. First one gets correctly opened in DrawIO editor without errors, second one is just diagram PNG image without diagram data.
- `diagram_image_with_metadata.drawio.png` - image file with diagram meta data inserted into `tEXt` chunk. That's exactly the file which causes error `Not a diagram file (error ...)` I mentioned above.
- `diagram_extracted_after_changes.drawio` - diagram data extracted from `diagram_image_with_metadata.drawio.png`, just to make sure that data was not corrupted. Gets opened in DrawIO editor without errors.

Please let me know if you'll need some additional information.

**Comment by Haryto** [comment]
Eventually I solved my issue, thank you for your attention.
Problem was that I used PHP function `urlencode()` to encode diagram XML, and this function encoded spaces as `"+"` symbol (instead of `"%20"` as DrawIO expects). I changed encoding function to `rawurlencode()` and issue disappeared.
