### ISSUE TITLE
Timeout error when saving large file to Google Drive

### ISSUE THREAD

**Issue by brnpl89** [jgraph/drawio#3815]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
We are running version 21.0.2 self-hosted and we are experiencing this issue with diagrams that are large in byte size (more than 1.5MB) or too complex. When we want to save changes to a diagram, we get a timeout error (as evidenced by the screenshots attached to this issue). We would like to know if it’s possible to change the value of the timeout and where we can do that.

**To Reproduce**
1. Open a large file from Google Drive
2. Click on “Save” or make a change in the diagram and let it save automatically
3. Error appears

**Expected behavior**
It should save the file without any issues.

**Screenshots**
 
![image](https://github.com/jgraph/drawio/assets/143200688/05e55889-fe24-4fcd-bd24-804224726c2f)

![image](https://github.com/jgraph/drawio/assets/143200688/1c70601d-468f-482d-9921-0583ba2f93a4)

![image](https://github.com/jgraph/drawio/assets/143200688/85ffa1ba-eee2-429d-89d5-0fd933bf1378)
   
**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.0.2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Edge
 - Version: (latest Windows 10 version)

**Comment by davidjgraph** [comment]
Duplicated by https://github.com/jgraph/drawio/discussions/3821. Please don't double post.
