### ISSUE TITLE
Is there a way to integrate mxgraph with asciidoctor

### ISSUE THREAD

**Issue by carun** [jgraph/drawio#382]
Asciidoctor can integrate with various graph generation apps like plantuml, etc. See https://asciidoctor.org/docs/asciidoctor-diagram/#creating-a-diagram

Is there a way to add draw.io to this list?

**Comment by carun** [comment]
Related question on Asciidoctor diagram: https://github.com/asciidoctor/asciidoctor-diagram/issues/213

**Comment by rdmueller** [comment]
depends on the kind of integration you need.
I create draw.io diagrams as `.png` files. Draw.io will store the source of the diagram as meta-data within the `.png`. This way, you can reference the diagram from my AsciiDoc files and you will still be able to edit it with draw.io.

To recognize that the `.png` contains meta-data, I use the extension `.dio.png`

**Comment by davidjgraph** [comment]
Leave take the conversation to https://github.com/asciidoctor/asciidoctor-diagram/issues/213 rather than have two threads.
