### ISSUE TITLE
According to the custom horizontal or vertical spacing size, realize equal spacing horizontal distribution or vertical distribution

### ISSUE THREAD

**Issue by luomgf** [jgraph/drawio#3820]
According to the custom horizontal or vertical spacing size, realize equal spacing horizontal distribution or vertical distribution

**Comment by luomgf** [comment]
Hi,davidjgraph!

Has this function been implemented?

I want to express such a function

![演示](https://github.com/jgraph/drawio/assets/18029400/e8dada33-ed39-40c2-a6ee-41a931ed32c0)

Now the positions of A1 and B1 are not equal, but I want to set them to the specified size distance

Then I input 20pt at the position of C, and click the d horizontal distribution button


The distance between them becomes A1 and B1, which becomes a custom 20pt

Is this function already implemented?

Thanks for the reply Thanks！

**Comment by davidjgraph** [comment]
The issue was closed for the reason written in the feature request template.
