### ISSUE TITLE
value of the shape parameter under Style property of "Or" and "Summing Junction" shapes under flowchart should be swapped

### ISSUE THREAD

**Issue by mk7exe** [jgraph/drawio#3822]
You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

The value of the shape parameter of a Style property for OR shape under flowchart is mxgraph.flowchart.summing_function. The corresponding value for the Summing Junction is mxgraph.flowchart.or. They need to be swapped.

1. Insert Or shape by double-clicking on it under the flowchart section
2. Right-click on the shape
3. Select Edit Style
4. See the value of the shape parameter

The value of the shape parameter in the Style property for Or and Summing Junction flowchart shapes should be swapped.

![image](https://github.com/jgraph/drawio/assets/62263580/199dd691-9f55-4f13-87a3-4b13b42fc38a)

- draw.io version v21.6.5
- OS: macOS Ventur 13.4.1

**Comment by davidjgraph** [comment]
They cannot be swapped at this stage, it would change too many diagrams.

**Comment by mk7exe** [comment]
Thanks for your response. I believe it will only swap the shape of the "Or" and "Summing Junction" in the current flowchart. This should be a low-risk change. Right now, if you want to make use of XML objects (like my use case), you have to use the wrong shape. It would be great if this gets fixed someday.

**Comment by davidjgraph** [comment]
It will swap them in all diagrams, this is intolerable risk.
