### ISSUE TITLE
Less clicking for exporting diagrams

### ISSUE THREAD

**Issue by cty44** [jgraph/drawio#3825]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated each time I want to export my diagrams to JPEG (or anything else) into my computer with my mouse (and there's no other ways available that I know of to do such task).
I must click on File > Export as > JPEG... Then a modal with more selections and clicks. In short, it's a lot of clicks to export and download a file, since a long time ago.
As of August 31st, 2023, I noticed you modified the UX for exporting files (e.g. download JPEG into our computer) and I have to make 3 more clicks to accomplish the same task since then, such as click on a drop-down menu then select "Download" then "OK" in order to get it downloaded into my computer as JPEG file.

**Describe the solution you'd like**
May you undo the changes on that exportation modals, like removing the drop-down menu, and putting back the one-click icons instead?

**Describe alternatives you've considered**
Or maybe provide us with at least one of the following options to bypass all (or most of) the modals and clicks, so we can get to the point of downloading our exports in the format we want:
  * a Javascript call that we could use locally in our browser with userscripts (e.g. Greasemonkey, Tampermonkey, Violentmonkey) or
  * some keyboard shortcuts.

**Additional context**
The new modal I dislike because I have to make more clicks to download my export as JPEG:
![clip 23-09-01_00 11 32](https://github.com/jgraph/drawio/assets/13182506/0068087d-8a0b-429c-9c44-ad1d4a3f3ac6)

**Comment by davidjgraph** [comment]
The old dialog is not coming back, it was non-standard and confused users.

I count 2 extra clicks, not 3.
