### ISSUE TITLE
Feature Request- Blocks, quick-popup, Auto-Image resizing

### ISSUE THREAD

**Issue by rajq123** [jgraph/drawio#3829]
1. Blocks are similar to groups containing several objects but the beauty of block is that if we make changes in one block then all other same block will be updated as well like color, size, text objects inside the block. we use them in CAD program very much. there can be additional options like DeBlock, Nested Block (so that only certain parts can be changed only), add/remove objects from block. currently in groups, it is very annoying that we make a group and when we click on it some object of group gets selected and if we want to move group together then the object under cursor start resizing.
2. Option to toggle popup menu so that when we select the block the menu appear just right to the object allowing user to change the parameters.
3. Sometimes the simple diagrams are not enough and we make them in inkscape and import them by svg but that looses the ability to edit them. by implementing blocks we can import inkscape file as blocks and when we finish edit in inkscape then there can be function to update the block. I think today we as a freelancer work in various programs and need to switch multiple softwares hence it is very helpful feature.
4.  i noticed that when we import the image even after checking resize option, the file gets laggy after pasting the image couple of times. so i suggest to Resize the image to 200x200 pixel automatically and when it is used in large size then at the time of export bring it back to original.

**Comment by davidjgraph** [comment]
Thanks for taking the time to submit your idea. Unfortunately, having reviewed the request, this isn't a feature request we feel has mainstream appeal and will decline it.
