### ISSUE TITLE
Coloured tabs

### ISSUE THREAD

**Issue by aleonccc** [jgraph/drawio#3830]
* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to apply colour to created tabs

**Describe alternatives you've considered**
DrawIO automatically colours tabs just created

**Comment by davidjgraph** [comment]
Thanks for taking the time to submit your idea. Unfortunately, having reviewed the request, this isn't a feature request we feel has mainstream appeal and will decline it.
