### ISSUE TITLE
Infinite canvas style editing (Artboards)

### ISSUE THREAD

**Issue by raphajp** [jgraph/drawio#3831]
### **Feature**
Ability to organize pages by moving them around in a infinity canvas like in adobe illustrator, figma, affinity design.. etc
Basically the concept of an artboard.

### **Current implementation**
New pages are created as content overflows the current page. 
The arrangement of the new pages are fixed in a rigid layout.

### **Implementation ideas**
- Introduce the page shape (Promote a page to a normal Draw.io shape allowing for example arrows, text, etc. )
- Have the ability to create shapes outside of pages
- Pages have properties (style, text, arrange), or some new page property
- Allow for pages inside pages
- Have a way to select what pages go on to  export or print
- Have a way to export the whole canvas by fitting it to a given page size on export or print.

### **Comments**
I know that this probably not the main design objective of Draw.io. However moving
stuff around to illustrator, for example, really breaks the flow for me. Specially when I am  loosely sketching or prototyping ideas.

**Comment by olfek** [comment]
~@davidjgraph -- Infinite canvas would be so cool like in: https://concepts.app~

My bad, apparently you can already do this 🤦‍♂️, https://github.com/jgraph/drawio/issues/2300#issuecomment-938534716
