### ISSUE TITLE
Open by URL

### ISSUE THREAD

**Issue by BoyceData** [jgraph/drawio#3834]
Hello,
I downloaded the code and I'm trying to open a file by URL and it always returns file not found. When I do the same test in the production version: https://app.diagrams.net?url=https://boycedata.net/BoycePrivacy/MapaProcessos/diagrama1.xml the diagram opens normally.
Searching the net there is a lot of confusion and no clear answer what to do. They talk about configuring a proxy and many other things that I couldn't understand.
Could you please provide a brief description of what to do to open a file by URL, I believe it will be very useful for all users.
I apologize if the answer is obvious and I wasn't smart enough to figure it out.
Thank you all and congratulations on the product, it is sensational.
Walter

**Comment by davidjgraph** [comment]
What exactly are you deploying? What have you deployed that upon?

**Comment by BoyceData** [comment]
Hello, I just downloaded the application, loaded it in the browser and want to open the file from the above URL.
In the production module it works, but in my application with the downloaded sources, /proxy appears in the URL and responds with file not found.
If you can help me, thank you.

**Comment by BoyceData** [comment]
I'm using IIS, I put the code in an asp.net framework project.

**Comment by davidjgraph** [comment]
How do the java servlets run in asp.net?

**Comment by davidjgraph** [comment]
And again, what exactly are you deploying, the docker image, the war? At what version?

**Comment by BoyceData** [comment]
Using version 21.7.2, on IIS with dot.net application. It's not docker. Should I use apache?

**Comment by davidjgraph** [comment]
You require a servlet engine to run java servlets. Neither dot.net or apache are that. Good luck.
