### ISSUE TITLE
Sharepoint/Teams/Onedrive app terms of service and privacy links are broken

### ISSUE THREAD

**Issue by Arunass** [jgraph/drawio#3835]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
I try to add a draw.io diagram through Microsoft Teams.   In the process, I am prompted to authenticate and indicate that I accept that draw.io can access my name, email address, and profile picture.  I am assured that the use of this information is governed by the privacy agreement.   The link provided results in a Server not found (not just a 404).  Inspection shows that the URL is https://www.diagrams.net.trust/, which is clearly a typo.  Does anybody ever read these things?

**To Reproduce**
1.  try to add a draw.io diagram through Microsoft Teams
2. Authenticate as required
3. When asked to permit access to profile data, click on the "terms of service" or "privacy" links

**Expected behavior**
The correct privacy or terms of service documents should appear in my browser.

**Screenshots**
n/a

**draw.io version (In the Help->About menu of the draw.io editor):**
unsure - I never got to this point

**Desktop (please complete the following information):**
 - OS: mac os
 - Browser: any
 - Browser Version: any

**Smartphone (please complete the following information):**
 n/a

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
yes

**Additional context**

**Comment by Arunass** [comment]
Later in the process, there is an actually accessible privacy statement which is missing the typographical errors that I find when I edited the above URL to https://diagrams.net/trust, and it's quite a different document, which spells out clearly that draw.io never sees any data from the user (neither personal nor diagram data).

**Comment by Arunass** [comment]
The statement here: https://www.drawio.com/trust/privacy-microsoft-teams

is fare more comforting than the permissions requested would indicate:
![image](https://github.com/jgraph/drawio/assets/1088686/bbd9e037-8b43-4f85-a7bd-a0e108bc001d)

**Comment by davidjgraph** [comment]
Ignoring the tone of your original post, where in the trust document does it state "clearly that draw.io never sees any data from the user".

**Comment by Arunass** [comment]
Sorry if there was an implied tone somewhere, nothing was intended.  

In reading the document here https://www.drawio.com/trust/privacy-microsoft-teams I see:
![image](https://github.com/jgraph/drawio/assets/1088686/0bd69983-412d-40c2-8f88-71a83619599c)

![image](https://github.com/jgraph/drawio/assets/1088686/0b365d0c-4a46-4e33-a66f-456a220715ac)

OK, there is the element of PDF generation, where it does say that data is transmitted to draw.io, but that it is never stored.  But these look quite clearly like many efforts are made to avoid seeing any customer data except when required.

The document at https://diagrams.net/trust is quite different in tone and editing.

**Comment by Arunass** [comment]
There seem to be many different places describing the privacy and service agreements.   After trying to add Draw.io, and accepting things, there's a new line in the teams chat saying that I added draw.io.  If I hover over 'draw.io' here, I see this:

![image](https://github.com/jgraph/drawio/assets/1088686/6000c77a-5a0a-4406-8875-87d891d559eb)

and the links on this popup are to the two documents previously linked above - this time the link to https://diagrams.net/trust is correct.  That image seems to strongly disagree with the privacy-microsoft-teams document

**Comment by davidjgraph** [comment]
The image above is the permissions screen displayed by Microsoft. In order to integrate with any third-party particular scopes are requested. The image details what the scope of the permissions are in the widest possible sense.

For example "access my profile infromation such as...". That means the app can access that information if it wishes to. Microsoft doesn't know whether any specific app uses the scope full, it just has to warn you that's it's possible.

It details what the app can do in theory, we detail what the app does in practice. Can you point to specific conflicts?

**Comment by Arunass** [comment]
Ok, so you're saying "We can, but we don't".   It's a side conversation anyway - the bug report is that somewhere in the integration, the links are both to diagrams.net.trust, which doesn't bring up meaningful documents.   That nobody else seems to have reported this makes me suspect that most people don't bother to try to read them.

**Comment by davidjgraph** [comment]
I've looked through all of the links in the manifest, we don't deliver, or have delivered, any links malformed in this way.

Looking at the listing for the app prior to install:

<img width="1875" alt="Capture d’écran 2023-09-08 à 12 20 14" src="https://github.com/jgraph/drawio/assets/1761087/08f31413-15c5-4024-8ffa-d65e045fb24d">

The links are all correctly formed and clicking on them takes me to the correct locations.

That nobody has reported this for 2 years and given the volume of users installing, I would say users are seeing the correct URL as I do and some small minority are not.

It is difficult to debug without a reproduction case. However, https://www.diagrams.net/trust/privacy-microsoft-teams is the correct privacy policy specific to the app and https://www.diagrams.net/trust/ is the correct privacy policy for the company as a whole.

**Comment by Arunass** [comment]
I will try to reproduce - it's tough to get the initial screen with the broken links now that I accepted.

**Comment by Arunass** [comment]
I have found another way to get the bad link.   As I am trying to reverse the act of giving draw.io access, I've logged into office 365.
Under 'Apps', I have a long list of 'other apps', included is diagrams.net:
![image](https://github.com/jgraph/drawio/assets/1088686/cf3b723c-6a46-48b3-9eed-1860e0e3e53e)

I select 'Manage my apps':
![image](https://github.com/jgraph/drawio/assets/1088686/54f1be25-3b00-44df-bfd3-236b1c49d367)

I get here:
![image](https://github.com/jgraph/drawio/assets/1088686/ae640a86-8131-4fc5-b5dc-950847701fcf)

The Terms and Conditions link is incorrect:
![image](https://github.com/jgraph/drawio/assets/1088686/e98e599d-6df4-4ffe-8dae-b49ec57ea153)

**Comment by Arunass** [comment]
OK, in teams, I go to a chat with colleagues, and I click on the + to add a tab:
![image](https://github.com/jgraph/drawio/assets/1088686/1a2d12f2-b39c-4ae8-85ee-88425d45f74c)

I select draw.io:
![image](https://github.com/jgraph/drawio/assets/1088686/4f699ef3-cf9c-4d32-8c70-326123f00e02)

I get prompted by this window:
![image](https://github.com/jgraph/drawio/assets/1088686/4f0747df-1b7e-486d-a167-46cee1f9cdc8)
the links in here are all correct

I select 'Add'.
I am presented with this window:
![image](https://github.com/jgraph/drawio/assets/1088686/05b78233-6f09-47bf-a61d-0348aba1d09e)

I enter 'test' as the diagram name and select Sharepoint
I get prompted with:
![image](https://github.com/jgraph/drawio/assets/1088686/84a9b83a-3b96-4ca6-b82f-0b4c04edba4c)

I select continue

I'm prompted with the microsoft authentication window:
![image](https://github.com/jgraph/drawio/assets/1088686/cd460ff0-809f-4341-bbbc-ffb82f51f597)

I enter my password and continue
The same panel is now fille with:
![image](https://github.com/jgraph/drawio/assets/1088686/fcf87563-46c5-44d8-9dea-d341ffc544e5)

The link to terms of service and privacy statement both lead to 
![image](https://github.com/jgraph/drawio/assets/1088686/f0213b70-7b63-49ef-bce9-c94627538985)

**Comment by Arunass** [comment]
Not sure whether it's relevant or helpful, but clicking on the 'app.diagrams.net' link opens a drop-down with:

> Name
> diagrams.net
> Publisher
> app.diagrams.net
> Date created
> 3/11/2020
> Reply URLs
> https://app.diagrams.net/connect/teams/auth/odAuth-end.html
> https://app.diagrams.net/onedrive3.html
> https://app.diagrams.net/microsoft

**Comment by davidjgraph** [comment]
Still not been able to repeat. Not sure if this is unique to one instance, but we're not going to spend any longer looking.

**Comment by ixil** [comment]
I could repeat url issue - specific problem is with 'one-drive' integration terms of service + privacy policy url. Instead of forward-slash '/' a dot '.' is present.  (See mouse hover url text below.)
Not sure if relevant but I have ability to agree on behalf of my organization - perhaps that is in a different location.
![image](https://github.com/jgraph/drawio/assets/2058587/c3781f3d-a662-44ab-93ed-1a0057bf6fb6)
