### ISSUE TITLE
Latex array environment not working when exported to png.

### ISSUE THREAD

**Issue by Arkonaire** [jgraph/drawio#3839]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
I need a matrix with horizontal and vertical lines written inside a text box with latex (mathematical typesetting enabled). I am using the array environment in latex. It works fine in the app but the horizontal and vertical lines do not appear when I export the image in a png format. It works when  export as pdf. Does not work in svg format.

**To Reproduce**
1. Enable Mathematical Typesetting from the Extras menu.
2. Create a text box and type in the following latex code inside it.
```
\(\begin{array}{c|c}
    1 & 0 \\
    \hline
    0 & 1 \\
\end{array}\)
```
4. Go to File > Export as > PNG
5. Download the exported PNG to disk.

**Expected behavior**
Refer to the screenshots below. Screenshot 1 shows the textbox as it appears in the draw.io app (both web and desktop versions). This is expected. Screenshot 2 shows the exported PNG. The horizontal and vertical lines have disappeared. Expected behavior is that all lines should be retained in the exported PNG.

**Screenshots**

Screenshot 1
![screenshot_drawio](https://github.com/jgraph/drawio/assets/24692376/36eaab10-bd65-4b5b-86a6-a57a93d4c56b)

Screenshot 2
![exported_image](https://github.com/jgraph/drawio/assets/24692376/9c8af8fd-848b-4fcc-b850-471a0794d585)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 21.7.4

**Desktop (please complete the following information):**
 - Windows 10
 - Brave
 - 1.57.62

**Smartphone (please complete the following information):**
 - Not tested.

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- Yes

**Additional context**
N/A

**Comment by davidjgraph** [comment]
Fix in 21.7.5.
