### ISSUE TITLE
Command-line SVG export functionality.

### ISSUE THREAD

**Issue by NicolasRouquette** [jgraph/drawio#384]
There was a related issue, https://github.com/jgraph/drawio/issues/150, that was closed based on the `drawio-batch` tool. Unfortunately, the batch tool does not work properly, see: https://github.com/languitar/drawio-batch/issues/9

Launching a headless chromium browser to run draw.io like drawio-batch would be a cute trick if it worked; alas, it doesn't.

**Comment by davidjgraph** [comment]
Command line export is in the desktop version, https://github.com/jgraph/drawio-desktop/releases/tag/v10.7.5

**Comment by psychemedia** [comment]
I found I had to pass an explicit path to call the app on command line in a mac:

`/Applications/draw.io.app/Contents/MacOS/draw.io drawing.drawio`

I also couldn't find a way to export to anything other than PDF (I wanted to convert all the `.drawio` files in a particular directory to `.xml` ?)

**Comment by jmini** [comment]
@psychemedia The drawio CLI also works with folders and the `-f` flag can be used to specify the format. To convert all the files in the `files/` folder to png: 

```
$ mkdir out
$ draw.io -x -f png -o out/ files/
```

See [Draw.io from the command line](https://j2r2b.github.io/2019/08/06/drawio-cli.html) (In particular the "Convert multiple files" section at the end of the page)
