### ISSUE TITLE
Can't add "Flow" plugin to web app (https://app.diagrams.net/)

### ISSUE THREAD

**Issue by devr24** [jgraph/drawio#3840]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I'm attempting to use the 'Flow' plugin for animated diagraming.

When I try to include the 'Flow' plugin from the plugins screen (Extras > Plugins > Add > Flow) it acts like it's worked but then an "Undefined" item is added to the plugin list. Shown here:

When I close the dialog and go back in, its stated as "null" (shown in screen shot above as well - all the previous attempts to add 'Flow').

This is happening on the web app but I also cannot add 'Flow' plugin to the desktop app.  

**To Reproduce**
1. Go to 'Extras' menu
2. Click on 'Plugins'
3. Click on 'Add'
4. Select 'Flow' from the dropdown list and press Ok
6. See error

**Expected behavior**
I expect 'Flow' to be added and available for me to use.

**Screenshots**
![Plugin_error1](https://github.com/jgraph/drawio/assets/6367545/d2083118-54f2-45ea-a10b-4ae4f557fee9)
![image](https://github.com/jgraph/drawio/assets/6367545/55c5173c-199f-47ee-b088-e96808eb9490)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.7.2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Browser Version 116.0.5845.111

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- YES

**Additional context**
I tried this on the desktop version of Drawio also and have problems there too:
![Plugin_error_desktop](https://github.com/jgraph/drawio/assets/6367545/a9b379b0-856d-4b1e-98a6-a9b81dfcd01d)

**Comment by alderg** [comment]
The flow plugin is no longer needed (and will be removed from that list). You can enable the animation from here:
<img width="241" alt="Screenshot 2023-09-09 at 06 53 42" src="https://github.com/jgraph/drawio/assets/921200/c2a17ef8-2757-43ae-93d0-e0faa0be48be">
