### ISSUE TITLE
When switching pages, the view moves automatically.

### ISSUE THREAD

**Issue by oobbppoo** [jgraph/drawio#3844]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
There is a container on page 1 that contains an arrow. The target point of the arrow is outside the container, and the arrow is pointing upwards. When switching from page 1 to page 2 and then back to page 1, the view automatically moves upward.

**To Reproduce**
1. Create a rectangle in page 1.
2. Modify the properties of the rectangle to make it a container.
3. Create an arrow and place it inside the rectangle.
4. Adjust the direction of the arrow to point upwards, with the target point outside the rectangle.
5. Switch from page 1 to page 2, and then back from page 2 to page 1.
6. Bug encountered: The view automatically moves upward.

**Expected behavior**
The view should remain unchanged after page transition.

**Screenshots**
![动画](https://github.com/jgraph/drawio/assets/25734631/5910fcea-9769-4f54-8950-0784748ca3ff)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.7.4

**Desktop (please complete the following information):**
 - OS: [Win11]
 - Browser [Edge]
 - Browser Version [116.0.1938.62]

**Smartphone (please complete the following information):**
 - Not tested.

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**
diagram file：
[test.zip](https://github.com/jgraph/drawio/files/12567570/test.zip)

**Comment by alderg** [comment]
Please attach the diagram file.

**Comment by oobbppoo** [comment]
diagram file：
[test.zip](https://github.com/jgraph/drawio/files/12567572/test.zip)
diagram link：
https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=test.drawio#R%3Cmxfile%20pages%3D%222%22%3E%3Cdiagram%20name%3D%22Page-1%22%20id%3D%22kcOqMC6cRUO9vtxvvubz%22%3EjZRvb4IwEMY%2FDS9NQPz7UpmyLTExc8u2V0tDT%2BhSqClVcJ9%2BZVyFCjO%2Bsvf0er3%2BnhPHD9IylOSQbAQF7gxdWjr%2BgzMcet7I1z%2BVckbFdae1EktGUWuEHfsBk4jqkVHIrUQlBFfsYIuRyDKIlKURKUVhp%2B0Ft289kBg6wi4ivKu%2BM6qSWp0Np43%2BCCxOzM3eZF7vpMQk40vyhFBRtCR%2F5fiBFELVq7QMgFf0DJf63Pqf3UtjEjJ1z4Gxuy2WpZgH%2B%2F3u82UZbySZDbDKifAjPhibVWdDQIpjRqEq4jr%2BskiYgt2BRNVuoU3XWqJSriNPL7UNirAMJMbdJs2NIBWULQmbDkGkoORZp%2BCuP0aAOEKjEcZF44dnICctLyaoERyB%2BFK6oaQXCKofWliyD%2Ffj7StcP4WL19XpefO9uAcaZHRRTZ%2BOIk7ynEU2Jxtql9Its4BaI9sF1wIz7uFiNAmcKHayB70PFt6wFUy31%2Fhi2zK%2Bop2Lo4wAz7TH8naZwfSqjiIyBtWp82fc5c19Xuqw%2BXPV6c03yl%2F9Ag%3D%3D%3C%2Fdiagram%3E%3Cdiagram%20id%3D%229EHw1-nygLJyNX-ennIQ%22%20name%3D%22Page-2%22%3EddHNEoIgEADgp%2BGu0GSdzfLSyUNnRjZhBl0HabSePh0gY6wTy7cLyw9heTtdDO%2FlFQVoQhMxEXYilKbpjs3DIk8vSZI5aYwS3lao1AtCodeHEjBEhRZRW9XHWGPXQW0j48bgGJfdUcdde97ABqqa663elLDS6YFmq5egGhk6p%2Fujy7Q8FPubDJILHL%2BIFYTlBtG6qJ1y0MvrhXdx685%2Fsp%2BDGejsjwVzsO49T6IvYsUb%3C%2Fdiagram%3E%3C%2Fmxfile%3E

**Comment by davidjgraph** [comment]
Fix in 21.7.5
