### ISSUE TITLE
How to get floating Shapes and formatting panels

### ISSUE THREAD

**Issue by offdesk** [jgraph/drawio#3845]
Sorry I cannot find any info on this.. I noticed my test setup has windowed shapes and format panels (inside an mxWindow), rather than the usual anchored panels. Is there a configuration option that determines if the panels are anchored versus windowed? 

Thanks

**Comment by alderg** [comment]
Maybe try Settings, Theme, Classic.

**Comment by offdesk** [comment]
Yep. I found themes. Thanks
