### ISSUE TITLE
In Notion drawio plugin, I save file failed

### ISSUE THREAD

**Issue by Foolisher** [jgraph/drawio#3846]
when I save my notion plugin svg-xml file , I got this error, please help us to solve this problem，very thanks

the file save request and resp as follow：

url: https://www.notion.so/api/v3/getUploadFileUrl
req:
  {"bucket":"secure","name":"notion-template.drawio.svg","contentType":"image/svg+xml"}

resp:
{
    "errorId": "2c6d1bdc-8eb4-41cb-b054-daf56ebeb6ce",
    "name": "UserValidationError",
    "clientData": {
        "type": "file_upload_generic_error"
    },
    "debugMessage": "File upload is not allowed.",
    "message": "Something went wrong. (400)"
}

**Comment by alderg** [comment]
We have fixed this in the plugin. You can force an update by clicking on Details for the plugin under Extensions, Manage Extensions:
<img width="411" alt="Screenshot 2023-09-11 at 17 45 43" src="https://github.com/jgraph/drawio/assets/921200/3d93652a-3122-4f46-a9c5-07550bcf10cd">

Then enable Developer mode and click on Update. You should see version 1.2.4:
<img width="943" alt="Screenshot 2023-09-11 at 17 47 53" src="https://github.com/jgraph/drawio/assets/921200/3aed6858-dbf8-40d4-95de-9789415b3ea4">
