### ISSUE TITLE
add the drag and drop function of tab

### ISSUE THREAD

**Issue by Now-Sprouting** [jgraph/drawio#3852]
* [✅ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [✅ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
At present, the default export function is the content of the first page. Can I add a pr to select a tab in the export mode or add the drag and drop function of tab?
![image](https://github.com/jgraph/drawio/assets/64894484/7e8c44bb-70b9-45ff-a145-6a0a351ca7bf)
![image](https://github.com/jgraph/drawio/assets/64894484/4743992b-2da6-4325-8dbd-d002cf0cef5d)

**Describe the solution you'd like**
none

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by davidjgraph** [comment]
Unfortunately, we don't accept PRs, please see the main README.
