### ISSUE TITLE
Connector to fixed point inside the shape is always in the back (Confluence Cloud)

### ISSUE THREAD

**Issue by Bastesque** [jgraph/drawio#3853]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
When I hold down the Shift key to connect to a fixed point inside a shape, the connector will appear in the back of the connected shape once I release the mouse (see screenshot).

**To Reproduce**
1. Connect to target shape, holding down Shift
2. Release the mouse
3. Shape enters shape but then is located in the back

**Expected behavior**
Connector appears on top of the target shape.
![Screenshot 2023-09-14 at 10 44 35](https://github.com/jgraph/drawio/assets/68647048/28eab9ee-3a6c-4415-bd54-b01420248450)

**Comment by davidjgraph** [comment]
Changed in 21.8.0.
