### ISSUE TITLE
Reverse the order of selected linked shapes

### ISSUE THREAD

**Issue by growupanand** [jgraph/drawio#3856]
* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I would like to have a feature to sort linked shapes in reverse order. like you can in below screenshot
<img width="770" alt="image" src="https://github.com/jgraph/drawio/assets/29487686/d7e27cbc-01ff-4248-97ee-90836f4a6f27">

**Describe the solution you'd like**
So there could be a button by pressing we can achieve this. After pressing button the shapes will look like in below screenshot.
<img width="779" alt="image" src="https://github.com/jgraph/drawio/assets/29487686/c5512324-af17-4664-b607-f6fa8d60829c">

**Describe alternatives you've considered**

**Additional context**

**Comment by davidjgraph** [comment]
Thanks for your suggestion. We'll decline to implement it on this occassion, it's a very specific case to add complexity to the UI for.
