### ISSUE TITLE
how to get the unminified app.js 

### ISSUE THREAD

**Issue by usernamedd** [jgraph/drawio#386]
- 
 have look up the issue "developping and debugging shape files". But when I use dev=1 as the parameter , the page can not be loaded. 

-
 locally open the index.html file in the chrome or firefox,it did not work like visiting www.draw.io, the bad result is that i can not get the workspace.

**Comment by davidjgraph** [comment]
You need to serve web applications from a server, not the filesystem.

App.js is in the main JS folder, https://github.com/jgraph/drawio/tree/master/src/main/webapp/js/diagramly

**Comment by usernamedd** [comment]
> 
> 
> You need to serve web applications from a server, not the filesystem.
> 
> App.js is in the main JS folder, https://github.com/jgraph/drawio/tree/master/src/main/webapp/js/diagramly

thank you . I mean ,the min version of app.js file is more larger than the un-minied one.

**Comment by YauHsien** [comment]
@usernamedd It's bigger because it's [a big collection](https://github.com/jgraph/drawio/blob/dev/etc/build/build.xml#L441).
