### ISSUE TITLE
Update Archimate elements in Draw.io

### ISSUE THREAD

**Issue by marceloancelmo** [jgraph/drawio#3863]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Archimate notation is currently on version 3.2, which contains some additional elements (Value Stream) and updates on relatioships between elements. It would be helpful to update the notation support on draw.io from version 3.0 to version 3.2

Details about differences between versions can be found at [Appendix E: Changes from Version 2.1 to Version 3.2](https://pubs.opengroup.org/architecture/archimate3-doc/ch-Changes-from-previous-versions.html). sections E.2 and E.3 are relevant for the changes added on versions 3.1 and 3.2 respectively 

**Describe the solution you'd like**
Update the notation support for Archimate from version 3.0 to version 3.2

**Describe alternatives you've considered**
Currently I have the use use the element "Step" available in the "General" shapes to represent a Value Stream in Archimate diagrams 

**Additional context**

**Comment by egrimate** [comment]
Will be in next release

**Comment by davidjgraph** [comment]
In 22.1.3.
