### ISSUE TITLE
Inverted image color in Google Drive permissions modal while using Dark Mode

### ISSUE THREAD

**Issue by jeanlucaslima** [jgraph/drawio#3869]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
While trying to connect to Google Drive I was surprised by the profile photo on the share modal, because the photo had inverted colors.

**To Reproduce**
1. Go to draw.io
2. Click on Share
3. Connect with Google Drive
4. Choose a folder, go to next step
5. See error in the user profile photo

**Expected behavior**
The user photo should show properly. 

**Screenshots**
<img width="1393" alt="Screenshot 2023-09-19 at 11 28 51" src="https://github.com/jgraph/drawio/assets/1311402/27280144-cb12-4647-a0e5-649e7873a596">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.7.5

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.5.2
 - Google Chrome Version 117.0.5938.62 (Official Build) (arm64)

**Smartphone (please complete the following information):**

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
N/A

**Additional context**

**Comment by jeanlucaslima** [comment]
Btw, this is the photo it is trying to show for the profile, the image is loading properly, it just has the effect of inverting colors. 
![Uploading image.png…]()

**Comment by davidjgraph** [comment]
Set to light mode in 21.8.0
