### ISSUE TITLE
Various issues with AWS19 shapes

### ISSUE THREAD

**Issue by mattburgess** [jgraph/drawio#387]
I noticed the following when trying to draw diagrams that comply with the latest guidelines from AWS (see slide 18 of https://d1.awsstatic.com/webteam/architecture-icons/AWS-Architecture-Icons-Deck_For-Light-BG_20190207.pptx.ddf95639227091debc86208b805841cb5bba68c0.zip):

* No shape for Availability Zone under AWS/Groups
* Security Group under AWS/Groups shouldn't have an icon in the top-left corner
* Auto-scaling group's icon should be in the top-centre of the box, not in the top-left corner
* Missing groups for 'Private Subnet' and 'Public Subnet', and the catch-all 'VPC Subnet' should be removed
* The two Generic groups are missing

If these are maintained/updated manually, then I can give changing them a try.  However, I suspect these may be generated automatically from the SVGs Amazon provide by running them through something like https://github.com/jgraph/svg2xml? If that's the case I could take a look at whatever does the conversion to see if it can be tweaked to produce shapes that match AWS' PowerPoint slides.

**Comment by mattburgess** [comment]
I've raised a PR at https://github.com/jgraph/drawio/pull/388 which I think addresses all the discrepancies I've found with a couple of exceptions:
* I couldn't find a way of moving the Auto Scaling Group's icon to the top-centre of the box
* The Private subnet and Public subnet fill color should be the same as their respective icons, but with opacity set to 10.  However, when I did this, the opacity was applied to the icon as well meaning it just disappeared.  I couldn't see a way of setting opacity only on the fill, and not to the icon, so I fudged things by choosing a colour as close as I could to what the opacity-fill would look like.  I'm not overly happy with that approach though.

**Comment by davidjgraph** [comment]
Thanks for the report and PR. It looks like AWS are updating the documentation constantly and we missed that bit. We'll take a look.

**Comment by kutya** [comment]
Done. Will be in next release.

**Comment by mattburgess** [comment]
@kutya those improvements look super.  Thanks very much for updating so quickly.
