### ISSUE TITLE
Mermaid integrate new version?

### ISSUE THREAD

**Issue by romerod** [jgraph/drawio#3870]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Inserting a mermaid diagram with a C4Context doesn't result in a diagram. 
https://mermaid.js.org/syntax/c4.html

**Describe the solution you'd like**
Latest mermaids features supported in draw.io

**Describe alternatives you've considered**
Workaround: Export mermaid to svg and then insert as image

**Comment by davidjgraph** [comment]
I appreciate the idea, but this could effectively be a permanent issue open since we'll spend most of the time out of date. We update Mermaid for security issues, otherwise every 6-12 months. But, it's not a critical part of the app, so we won't update on every release.
