### ISSUE TITLE
How to prevent adding images in a UX-friendly way

### ISSUE THREAD

**Issue by JoepKockelkorn** [jgraph/drawio#3876]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When using embed mode together with [a custom configuration](https://www.drawio.com/doc/faq/configure-diagram-editor), we want to prevent (non-svg) images from being added. We now set the `maxImageBytes` to `0` to prevent that. But this still shows the popup asking whether to resize or use the original size. After making any choice a popup is shown: 'Image is too large' (see below).

**Describe the solution you'd like**
When setting `maxImageBytes` to 0 (or the alternative `maxImageSize`) then the user should not have to make a choice whether to use the original or resize. A simple 'Images are not allowed' message or similar would be sufficient.

**Describe alternatives you've considered**
Setting `maxImageSize` to 0 has the same effect. We could self-host drawio and make the changes, but this requires too much effort for now as we then need to implement our own custom proxy endpoint in ASP.net ([see this issue](https://github.com/jgraph/drawio/issues/3834)).

**Additional context**
A screenshot of the message shown (in Dutch):
<img width="534" alt="image" src="https://github.com/jgraph/drawio/assets/12891645/3249dd6a-5eb3-4947-a09b-a2fd5325b84d">

**Comment by davidjgraph** [comment]
Thanks for your suggestion. Having reviewed it we've decide it is too narrow scope to justify implementing and maintenance.
