### ISSUE TITLE
Allow disable auto add to groups

### ISSUE THREAD

**Issue by burner-** [jgraph/drawio#3877]
Not sure is this bug or feature but it is frustrating and renders groups almost useless:
Current behavior:
- I do group of  objects
- I drag new object over that group
- it will show group borders as blue and when I release object it will add it to group. 

When I do group whole point of that is that it act as one object and wont get meshed with another object accidentaly.  If this is feature it would be much better that user need hold some key down to enable it. It is is not possible to hook it to key then that current feature do just more harm than good and it is better to just remove it.

**Comment by alderg** [comment]
Try uncheck Drop Target:
<img width="243" alt="Screenshot 2023-09-22 at 08 11 31" src="https://github.com/jgraph/drawio/assets/921200/b2468dcb-9723-4a45-82ea-532fa79f7045">
