### ISSUE TITLE
Show ask confirm dialog when keyup "ESC" in Insert Layout

### ISSUE THREAD

**Issue by RelicOfTesla** [jgraph/drawio#3880]
Pressing the ESC key to exit editing while editing text can easily cause the edited content to be lost. You can add an exit inquiry confirmation dialog box to prevent operational errors.

**Comment by davidjgraph** [comment]
That's the intended behaviour of the escape key, it's a common paradigm to cancel the current action in software. I don't agree with a confirmation dialog in this case.

**Comment by RelicOfTesla** [comment]
Im lost something data when editing....or you can record some draft !

**Comment by davidjgraph** [comment]
OK, I misread, we'll add a confirm in the next release.
