### ISSUE TITLE
brush tool feature additions

### ISSUE THREAD

**Issue by emily-drawio** [jgraph/drawio#3882]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I guess just simple customizability and intuitivity. would make the brush tool much more appealing

**Describe the solution you'd like**
I would like if you were able to change the brush color and pattern/design _before_ you begin drawing. I also would like if you could fill in the shapes you draw so long as the lines overlap to create a closed shape. and maybe even add the freehand option to the upper toolbar for even quicker access.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by alderg** [comment]
Brush color added:

<img width="191" alt="289065163-58f8f74a-d952-406a-a890-0c39d7b425d6" src="https://github.com/jgraph/drawio/assets/921200/891c76b0-96f6-43db-923c-2c117510ff5a">
