### ISSUE TITLE
Broken dialog - unable to "decide later" when selecting storage

### ISSUE THREAD

**Issue by cushyno** [jgraph/drawio#3883]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
When selecting storage for a new diagram, clicking "Decide later" does not close the modal dialog.  Still able to click storage options, but unable to close dialog, therefore unable to use the application without having first selected storage.  This means I can't save data to internal browser storage either.

**To Reproduce**
1. Open diagrams.net in new browser window, the "Select a draft to continue editing" dialog is shown.
2. Click on 'Cancel'
3. The dialog "Save diagrams to" is shown
4. Click on 'Decide later'

**Expected behavior**
Expect the dialog to close and present a blank canvas

**Screenshots**
Diagram shows the "Drafts dialog" and "Decide later" link clicked and dialog that has remained on screen afterwards.

<img width="948" alt="Diagrams_net issue - decide later 0" src="https://github.com/jgraph/drawio/assets/8866837/338d18d0-4af5-4d48-9a17-0ef32606bec8">

<img width="917" alt="Diagrams_net issue - decide later 1" src="https://github.com/jgraph/drawio/assets/8866837/aaaea9dd-687a-4b05-b518-52d6bb060a83">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: 21.8.2

**Desktop (please complete the following information):**
 - OS: Windows 10

 - Browser: Microsoft Edge for Business
 - Browser Version: 117.0.2045.41

 - Browser: Chrome
 - Browser Version: 117.0.5938.92

**Smartphone (please complete the following information): Not applicable**

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes.
Problem does not reproduce as there are no draft diagrams stored in private mode.

**Additional context**
This workflow I have followed for previous 2 years.  I use Diagrams.net daily and encourage my colleagues to do so too.  This is a serious usability bug for me.

A colleague with same browsers who had v21.7.2 of Diagrams.net was not affected.  After clearing cookies and updating to v21.8.2 the same problem is exhibited in his browser too, but only after he has created more than one draft diagram, which is when the initial dialogs show up.  Therefore the issue is with closing the dialogs, rather than the underlying application.

**Comment by cushyno** [comment]
Further info:

Adding URL parameter  splash=0 circumvents the dialog closure problem.  The drafts dialog still shows, but there is no prompt for which storage to use.  No dialog displayed means no issue with "Decide later" link not closing it.

**Comment by davidjgraph** [comment]
Fix in 22.0.0

**Comment by cushyno** [comment]
Unfortunately this still seems to be an issue.  Testing with same browser versions.  Updated to v22.0.0.
Ctrl+F5 to refresh page, no dialog issue encountered.  F5 (refresh) on its own still exhibits the same symptoms as before, even after performing the Ctrl+F5.

Issue should be re-opened.

**Comment by davidjgraph** [comment]
OK, but we can no longer repeat it, without being able to recreate on 22.0.0 there's little we can do.

**Comment by cushyno** [comment]
@davidjgraph, thank you. I'll update if there are any changes to status as a result of browser upgrades or similar at my end.

**Comment by cushyno** [comment]
My apologies, issue is resolved.  I can no longer recreate the issue either. 👍
