### ISSUE TITLE
Styles not rendered from Mermaid

### ISSUE THREAD

**Issue by finalspy** [jgraph/drawio#3884]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

If I take simple examples from Mermaid documentation, and try to import them into drawIO they should be rendered with style.

For instance from [Mermaid documentation](https://mermaid.js.org/syntax/flowchart.html#styling-a-node) :

```text
flowchart LR
    id1(Start)-->id2(Stop)
    style id1 fill:#f9f,stroke:#333,stroke-width:4px
    style id2 fill:#bbf,stroke:#f66,stroke-width:2px,color:#fff,stroke-dasharray: 5 5
``` 

```mermaid
flowchart LR
    id1(Start)-->id2(Stop)
    style id1 fill:#f9f,stroke:#333,stroke-width:4px
    style id2 fill:#bbf,stroke:#f66,stroke-width:2px,color:#fff,stroke-dasharray: 5 5
``` 
Is not properly rendered in DrawIO, all style is lost ...

**To Reproduce**
1. Go to 'Arrange > Insert > Advanced > Mermaid'
2. Copy past the mermaid code with colors, classes definition etc.
3. Click 'Insert' button
4. See diagram is rendered but style is lost.

**Expected behavior**

I expect to see the diagram with the styles applied properly if present in the import.

**Screenshots**
This screenshots shows the mermaid documentation for nodes styling.
![mermaid_styles](https://github.com/jgraph/drawio/assets/413502/b214f5db-c85b-46f1-b7a8-427457c6f269)

This other screenshot shows the rendering inside draw.io
![drawio_result](https://github.com/jgraph/drawio/assets/413502/6c38c221-bfde-4767-b4ca-9b0f12d6e864)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.8.0

**Desktop (please complete the following information):**
 - OS: Ubuntu 1804
 - Browser Chrome
 - Browser Version 116.0.5845.140 (Official Build) (64-bit)

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Comment by mandreato** [comment]
Hi there, I've just created a new empty diagram on https://app.diagrams.net (today it's 24.5.5).

Arrange > Insert > Advanced > Mermaid

Then pasted the sample from [Mermaid documentation](https://mermaid.js.org/syntax/flowchart.html#styling-a-node):
`flowchart LR
    id1(Start)-->id2(Stop)
    style id1 fill:#f9f,stroke:#333,stroke-width:4px
    style id2 fill:#bbf,stroke:#f66,stroke-width:2px,color:#fff,stroke-dasharray: 5 5`

Formatting is visible only when I insert as image but not when I insert as diagram. Would it be possible to have formatting in the diagram as well?

**Comment by asdkant** [comment]
Can confirm this is still happening in 24.6.4 and in the website, I inserted a mermaidJS diagram with this init line (note the mention of a theme) and it's rendered in shades of gray (it works fine in GitLab and the vscode extension `bierner.markdown-mermaid`, so I'm assuming it's correct)
```
%%{init: { 'logLevel': 'debug', 'theme': 'default', 'gitGraph': {'showBranches': true,'showCommitLabel': false}} }%%
```

**Comment by PedroLuizPBR** [comment]
Hi,
        I used the lasted version web V24.7.7  and doesn`t work  properly ....

        Exist two issues  --  if would like to use colors into the nodes  . . 
                                       if would like like format the text into the nodes


 
##################################### draw.io not accept Styles

![image](https://github.com/user-attachments/assets/451f7469-a9f5-4b24-b218-c2b0680d7fda)



################################### draw.io not format text into nodes .... example
![image](https://github.com/user-attachments/assets/9a32ae86-3cf3-47bc-81a2-2a7596dd3c7f)


 
Thanks !

**Comment by ifly-leonard** [comment]
Hi, experiencing the same. The charts when loaded on draw.io don't have colors. Is there a workaround for this? Thanks!

**Comment by arciandreswork** [comment]
Same here. Are style-less diagrams an expected behavior?

**Comment by styk-tv** [comment]
As part of the software evolution, you should seriously re-think support for mermaid and upgrade the spec to support simple feature like colors. I hope DrawIO will forever stay best of the best but you cannot pause in time. Tons of tools out there generate or maintain diagrams as code so this is required functionality I would argue.  Proper editor for mermaid source would be great similar to https://mermaid.live with proper undo. As a main citizen not burried inside several menu options. Looking forward to evolution. Cheers.
