### ISSUE TITLE
Recuperar archivo web por borrado de cookies

### ISSUE THREAD

**Issue by Ricardo2e** [jgraph/drawio#3886]
Buenos dias 
Estabe trabajando diagramas importantes y lo guarde en mi navegador la URL como marcador, pero hace poco borre historial y cookies para otra cosa y ya no me abre el archivo.
![image](https://github.com/jgraph/drawio/assets/146134331/c758e209-653e-4fcf-91aa-887d0e58a12d)

Solicito su apoyo si lo puedo recuperar es muy importante, si esta en su base de datos o algo por el estilo

la url a recuperar son 3:
https://app.diagrams.net/#LDiagrama%20disponibilidad.drawio#%7B%22pageId%22%3A%22k4bv-V6Oib1x1KGIiG4g%22%7D
https://app.diagrams.net/#LCyberArk-Prod
https://app.diagrams.net/#LCyberark%20-%20Test.drawio

**Comment by davidjgraph** [comment]
The #L part means it's stored in your browser. When you cleared everything out you deleted it from the storage in your browser. Can I ask why you selected "browser" as the storage?

**Comment by Ricardo2e** [comment]
Fue por la urgencia por la cual elegi ese metodo para cambiarlo en un futuro, pero sucedio esta incidencia, hay forma re recuperarlos?
