### ISSUE TITLE
Error Loading File - Not a diagram file (error on line 3541 at column 2598: AttValue: " expected

### ISSUE THREAD

**Issue by neurath2** [jgraph/drawio#3888]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
I tried opening a .dawio file I worked on yesterday just fine.  When opening today and I get the error window "Error loading File.  Not a diagram file (error on line 3541 at column 2598: AttValue: " expected)".  

**To Reproduce**

**Expected behavior**
I expect to be able to open my file again.

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/25961801/45e5235c-60de-46e6-a234-d731124d45af)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version x.y.z  Desktop draw.io version v21.8.2

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Win10
 - Browser [e.g. chrome, safari]  Desktop draw.io, but same error occurs when using the online version via Chrome 117.0.5938.63
 - Browser Version [e.g. 22]  n/a

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]  n/a
 - OS: [e.g. iOS8.1]  n/a
 - Browser [e.g. stock browser, safari]  n/a
 - Version [e.g. 22]  n/a

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- No clue what this is.

**Additional context**

**Comment by alderg** [comment]
Please attach the diagram file.

**Comment by neurath2** [comment]
Unfortunately, due to project constraints I am unable to release the drawings offsite.

**Comment by davidjgraph** [comment]
Then we can't investigate.
