### ISSUE TITLE
Feasibility of creating a code syntax highlighting plugin?

### ISSUE THREAD

**Issue by MostHated** [jgraph/drawio#389]
Hey there all,
    I am using draw.io as a way to map out the flow of my application and to keep notes and what not. I have been putting code snippets and such in it and I was wondering if it would be at all possible to have a code syntax highlighting plugin somehow? Are there any tutorials or anything on writing plugins? Perhaps I could find an open source solution and integrate it.

Thanks,
-MH

**Comment by Fanna1119** [comment]
this is definitely a must.
often times i want some syntax highlighted code/json data in a graph or diagram. No way to do so. :(

**Comment by jjco790923** [comment]
Im looking for the same a plugin for code syntax highlight
