### ISSUE TITLE
Unable to collaborate on files shared via onedrive

### ISSUE THREAD

**Issue by Sylvester-D** [jgraph/drawio#3891]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Background information: My organization has a shared onedrive folder in which we house client project related information. each client gets a folder, and each folder has many artifacts in it. in total there are a few hundred unique client folders.

Issue: we are attempting to use draw's live collaboration functionality via the web application through chrome. we have tested several methods of doing so and have run into roadblocks with each of them. Sharing this as a single issue as ultimately any solution in which we can easily collaborate on draw files shared via onedrive would meet our needs.

**To Reproduce**
**Attempted Method 1: via one drive folder**
Steps taken:
1. I create a draw file using webapp and store at \CompanyOnedrive\Clients\ABC_Company\file.drawio
2. Coworker also opens webapp for draw.io and attempts to browse to the above file using File Menu > Open From > One Drive and selecting **Files** from the browsing window.
**Failure 1:** Coworker is only able to browse their personal onedrive using this method using the webapp.

**Attempted Method 2: via sharing file**
Steps taken:
1. I create a draw file using webapp and store at \CompanyOnedrive\Clients\ABC_Company\file.drawio
2. Browse to \CompanyOnedrive\Clients\ABC_Company\ via explorer and select and share file.drawio to coworker
3. Coworker opens webapp for draw.io and attempts to browse to the above file using File Menu > Open From > One Drive and selecting **Shared** from the browsing window.
**Failure 2:** If file is located, we can both open the file, HOWEVER live collaboration is NOT available to us. One person's changes are saved and the other person receives a notification that they need to resynchronize the file. Neither of us can see each others cursors. Furthermore the list of shared files is extensive and not sorted in any meaningful manner. 

**Attempted Method 3: via sharepoint file browser**
Steps taken:
1. I create a draw file using webapp and store at \CompanyOnedrive\Clients\ABC_Company\file.drawio
2. Coworker opens webapp for draw.io and attempts to browse to the above file using File Menu > Open From > One Drive and selecting **Sharepoint** from the browsing window.
3. Coworker is unable to effectively navigate this list, they have hundreds of unsorted folders located within \CompanyOnedrive\Clients\ listed with no means of effectively finding \ABC_Company\
4. I attempted to share \ABC_Company\ directly with them via explorer share function, which is successful as it seems to 'boost' this folder to near the top of the list within the sharepoint browser
5. Coworker can now find \ABC_Company\ and select file.drawio
**Semi-successful:** We are now able to live collaborate on the file, HOWEVER we are not able to easily replicate this experience as the difficulty of navigation to a given file via the onedrive sharepoint file listing is highly abrasive. 

**Expected behavior**
Noted above

**Screenshots**
available upon request but didnt seem relevant

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version x.y.z

**Desktop (please complete the following information):**
 - Browser Version [e.g. 22]

**Smartphone (please complete the following information):**

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**
- the webapp version we are both using is 21.7.5
- no error messages are experienced at any point throughout this process (except the notification to resynchronize the file given in method 2)
- if an alternative method of browsing to a file on which we plan to collabrate is not listed above you should assume we are unaware of that method
- I did not mention any steps above which involve leveraging the desktop application as it is our understanding that live collaboration via the desktop app for a file on onedrive is not currently supported, let me know if that is incorrect. 

Any assistance would be greatly appreciated, this is a great tool we plan to leverage further going forward assuming we are able to not collide with eachothers changes.

**Comment by bryanh-csat** [comment]
Sounds like this isn't going to happen.

From the README:

> Note, in particular, we don't have support for collaborative editing in this project. If this is important, one of the projects above is likely a better choice.

**Comment by davidjgraph** [comment]
The README refers to the source in this project, rather than the version we run.

**Comment by Sylvester-D** [comment]
the collaboration function itself seems to work, just in limited circumstances. At a minimum, if the open from onedrive / sharepoint list was alphabetized that would function as a suitable workaround
