### ISSUE TITLE
Adding mhchem (chemical formulae/equations) in the Extras ?

### ISSUE THREAD

**Issue by cadoitrouler** [jgraph/drawio#3894]
* [yes] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [yes] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

As there is the possibility to activate mathematical equations in latex in the menu Extras (Suppléments), would there be in the same way the possibility to activate [mhchem](https://docs.moodle.org/401/en/Chemistry_notation_using_mhchem) for being able to enter chemical formulae/equations in latex ? As a chemical physicist, this would be extremely useful.
With best regards.

**Comment by alderg** [comment]
Works for me. [Example](https://app.diagrams.net/?tags=%7B%7D#RjVRNb%2BIwEP01ltoDUj4IsMcm0LIrrdAuh5W4VN54SKw6HmQMCfz6HScOkG1Re4gyfvNm5jmZGRZnVfNi%2BK78iQIUiwLRsHjOoigMkxm9HHLySDxJOqQwUnRYcAXW8gye2KMHKWDvsQ6yiMrK3RDMUWvI7QDjxmA9pG1RiQGw4wUMZDhgnXMF72h%2FpLBlh86SG%2FYSZFH2lcPAeyrek32KfckF1je14gWLM4NoO6tqMlDu6w2%2Fy%2FMd70WYAW2%2FEvCbG5Ec1q8v%2BbdfP1abp%2Fj7rB5FXZYjVwd%2FYZZkD%2FTkwKYpeTaaJQuiOJtFE17tWJwqKpi2dA8ULZCk10DHj1bLEZvOWeKIbcxfQ9Yd8tK9PXtMvoMWYPZgHSPJLDTOonIlWjAyp5DyJAw21B8ubPpRkemlyEY%2FrJaP7V179viT%2B2ROY5S2tyBRSfqx1ndF76u3YA3vVONZ6pzbr0inyp36cStjEY1ubhC0MrJH32P21DeuQSfB%2FfuA0tWltLDe8dx5a5pVwkpbKTqFZF5603G3qO0zr6RyM7sEdQQrc%2B4dfkJDat%2BUK1loOuTUgWAIwCOYrWoT1d2wpIS4aPXkuZUUwklMSzTyTAl5r6HN7vU7GXtr8A0yVEip5xq1i9pKpf6DfAdTHWjujkZ4GThaVYAV%2FYgTUfoAv5P8khqFk0kH1NeRHwd%2BVsqbcZ9M%2FabxW6a4pL4OIhl%2BFvvjdeZb383qjBf%2FAA%3D%3D)
