### ISSUE TITLE
Authorization with Google Drive fails on Firefox

### ISSUE THREAD

**Issue by munael** [jgraph/drawio#3896]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Authorization with Google Drive fails on Firefox with no specific failure code.

Screenshot:
![image](https://github.com/jgraph/drawio/assets/5769148/51c22ed2-edc5-43c5-93ee-d31f2758f684)

**To Reproduce**
1. Open Firefox.
2. Login to a Google account. I'm logged in to multiple but tried on a profile with only 1 and it didn't help.
3. Open diagrams.net and select Drive.
4. Click Authorize and select your Google account on the Google login popup.
5. Select both permissions requested (for access to Drive files created by the app).
6. You'll see the page above.

**Expected behavior**
Authorization succeeds and draw.io has access to my Google Drive storage.

**Screenshots**
See above.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.0.0

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Browser: Firefox
 - Browser Version: 116.0.3

**Smartphone (please complete the following information):**

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- Yes.
- I've also tried disabling (third-party) cookies blocking protection in Firefox.

**Additional context**

**Comment by davidjgraph** [comment]
Tried with all browser extensions disabled?
