### ISSUE TITLE
Want to be able to add criss-cross swimlane graphs

### ISSUE THREAD

**Issue by dyxcrazy** [jgraph/drawio#3897]
# Code of Conduct and Regulations

*   [x] I agree to follow the [[Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md)](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.

*   [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

# **Is your feature request related to a problem? Please describe.** 

I find that the current cross-functional flowcharts and the use of container adjustments are not suitable for accurately representing the process flow of each stage in swimlane diagrams. As a result, I am experiencing difficulties in effectively communicating the process flow of our software development team.

# **Describe the solution you'd like** 

I would like to request the addition of criss-cross swimlane graphs to Draw.io. This type of swimlane diagram will allow me to clearly represent the process flow of each stage in a more intuitive manner, without the need for complex container adjustments.

# **Describe alternatives you've considered**

 I have considered using other diagramming tools, but they do not provide the flexibility and ease of use that Draw.io offers.

# **Additional context** 

Please refer to the following image to understand the format of the criss-cross swimlane graph that I am requesting:

 ![20230228 软件开发流程图](https://user-images.githubusercontent.com/36730384/222456657-a32a7829-7619-4435-a7c1-78682ad15842.png)

**Comment by davidjgraph** [comment]
Duplicate #822
