### ISSUE TITLE
Feature Request: Marble Diagrams

### ISSUE THREAD

**Issue by sirinath** [jgraph/drawio#3898]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I want to have *marble diagrams*

**Describe the solution you'd like**
I want to draw *marble diagrams*

**Describe alternatives you've considered**
None

**Comment by davidjgraph** [comment]
If you submit such a low quality issue again you will be banned.
