### ISSUE TITLE
Mermaid insertion won't render diagrams with multi-word names even though this syntax is valid

### ISSUE THREAD

**Issue by baynezy** [jgraph/drawio#3899]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**

**To Reproduce**
1. Create blank diagram at https://app.diagrams.net/
2. Select Arrange > Insert > Advanced > Mermaid...
3. Paste in a mermaid ERD diagram that has multi-word entities
4. It will show the inserting spinner forever and do nothing else

Example
```mermaid
erDiagram
"EMPLOYEE SALES SUMMARY" }o--|| "PRICE REGION" : via
```

**Expected behavior**
1. Create blank diagram at https://app.diagrams.net/
2. Select Arrange > Insert > Advanced > Mermaid...
3. Paste in a mermaid ERD diagram that has multi-word entities
4. Render mermaid diagram correctly

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.0.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Browser Version 117.0.5938.132 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**

**Comment by Lockszmith-GH** [comment]
This is still happening

**Comment by davidjgraph** [comment]
Yes, it's a dup of #4307
