### ISSUE TITLE
Keyboard cut-copy-paste are broken

### ISSUE THREAD

**Issue by gricey432** [jgraph/drawio#3903]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Cut, copy, and paste using Ctrl+x,c,v aren't working

**To Reproduce**
1. Create an object, I made a rectangle
2. Ctrl+c
3. Ctrl+v

**Expected behavior**
A new box should appear, but nothing happens.

Other keyboard shortcuts seem to work fine, I tried a few out from https://app.diagrams.net/shortcuts.svg

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version v22.0.01

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Browser Version: Version 117.0.2045.47 (Official build) (64-bit)

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- No, but tested and reproduced on the Drawio Desktop 22.0.1 as well

**Additional context**

There is a ticket for this issue from another user on the Desktop repo https://github.com/jgraph/drawio-desktop/issues/1479

**Comment by davidjgraph** [comment]
Working correctly for me using Edge, MacOS 13.5.2.

**Comment by volnet** [comment]
I'm sorry, I didn't find them in different GitHub repositories. I will try searching on a broader scale in the future.
But it's not work in Windows.

**Comment by gricey432** [comment]
Interestingly, I'm finding with the web version that if I copy-paste a bunch nothing happens but then if I refresh the page all the pastes appear.

I also tried reloading with "disable cache" and it seems to have fixed it in the browser but not in the desktop app. Unsure if this is better off here or in the desktop repo now that I can only repro it in desktop.

**Comment by gricey432** [comment]
Spent a bit more time on this and can reliably reproduce it on a different browser with no extensions; Same windows 11 PC with Firefox 118.0.1

I can reliably use the following steps to reproduce this:

1. Clear all application storage, f5, click "Decide Later" in the popup
2. Make an object
3. Test copy+paste doesn't work
4. Refresh page (f5, nothing special about cache clear)
5. Assert it now works
6. File -> Close, Discard. Click "Decide later" to get a new blank diagram
7. Make an object
8. Assert it's now broken again

Let me know if a recording would help, but most of the action is on my keyboard.

Also right-click copy -> right click paste-here works just fine

**Comment by joseph-zhong** [comment]
+1, I've just upgraded to Sonoma and this issue seems to have come back, keyboard shortcuts for copy/cut/paste all don't work :(

One additional datapoint is that this is consistent with the Mac Universal app (which I assume is treated the same 

For what it's worth, this is reproduced on Safari as well -- the weird thing is that this seems isolated to cut/copy/paste since I was able to do a "CMD+L" to lock/unlock an item

**Comment by joseph-zhong** [comment]
Seems similar to https://github.com/jgraph/drawio/issues/949

**Comment by stanislav-tiurikov-tangany** [comment]
Copy/Paste doesn't work for me either after updating to 22.0.1
Linux, same behavior for both Chrome and Desktop versions.

**Comment by volnet** [comment]
I open the Help->DevTools, It's from Edge.
So I check my Edge version : Microsoft Edge version 117.0.2045.47

**Comment by davidjgraph** [comment]
Fix in 22.0.2. Thanks for report and debugging. If the service worker doesn't refresh the code, try clear.diagrams.net with any app.diagrams.net tabs closed.
