### ISSUE TITLE
Groups will not drag

### ISSUE THREAD

**Issue by bittybruv** [jgraph/drawio#3906]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Have been working with drawio for years. I assume this is a current bug but could not find. Group objects, try to drag the group. unable. Only drags individual objects. Checking in properties the object is grouped, but the group will only select, not drag.

**To Reproduce**
1. group objects
2. try to drag object
4. notice how the group will never, ever drag only individual elements

**Expected behavior**
the selected group object will drag all group members

**Screenshots**
N/A

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version x.y.z
web 

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser edge
 - Browser Version current

**Smartphone (please complete the following information):**

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
YES

**Additional context**

**Comment by bittybruv** [comment]
If any object in a group had pointer events disabled this is the behavior.  Hello Visio.

**Comment by alderg** [comment]
This works for me. Can you add a testcase with the exact steps please?

**Comment by bittybruv** [comment]
should have closed this with the prior comment, this behavior occurs when any object in the group is set to disable pointer events. if this is not intended behavior someone can reopen

**Comment by cyberjj999** [comment]
I'm facing the same issue. When I try to group a few objects, i.e. a textbox and an image, when I try to drag and hold to reposition the grouped object, it'll end up moving elements individually. I need to be super precise in clicking a corner of the grouped element in order to drag as a group.

Any advice? @alderg
