### ISSUE TITLE
Save diagrams to MEGA

### ISSUE THREAD

**Issue by dandeancook** [jgraph/drawio#3908]
This issue https://github.com/jgraph/drawio/issues/79 says the feature to save to MEGA is completed but no such option on Save Dialogue.

**Is your feature request related to a problem? Please describe.**
Draw.io is focusing on privacy-first, MEGA is one of the most popular E2EE cloud storage.
Is it possible to save diagrams to MEGA too?

**Describe the solution you'd like**
The save dialogue may add another option to save to MEGA.

**Describe alternatives you've considered**
Alternative: Save to MEGA folder locally.

**Additional context**
None

**Comment by davidjgraph** [comment]
I assume that is https://mega.io/. I've never heard of it, nor has any of the team, so I don't think it's _that_ popular.

We're not going to add it to the splash dialog, so if that's the request it's declined.
