### ISSUE TITLE
Dark Mode - Tags dialog uses dark icons for "Show/Hide" and "Select" buttons

### ISSUE THREAD

**Issue by Peeeet** [jgraph/drawio#3910]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When using dark mode, the Tags dialog (similar to Layers, opened by Ctrl+K) still shows the same black icons for "Show / Hide" and "Select" to the left of the tag name.  Should be updated to use properly contrasting icons when in dark mode, similar to how the Layers dialog appears and behaves.

**To Reproduce**
1. Go to 'https://app.diagrams.net'
2. Click 'decide later' if asked for storage location
3. Open the Tags dialog (under View menu or press Ctrl-K)
4. Add a new tag
5. Note color of icons next to tag name.  If in dark mode they are barely visible.
6. If not in dark mode, use icon in upper-right corner of app to switch (either a sun or a moon depending on theme)

**Expected behavior**
Icons expected to update based on view mode (dark vs light), similar to what happens with the icons in the Layers dialog.

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/5926263/0a372d09-6972-4a0e-8e6b-a713513d95e1)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version:  22.0.2

**Desktop (please complete the following information):**
 - OS:  Windows 10 Pro 22H2
 - Browser:  Google Chrome
 - Browser Version:  117.0.5938.132 (Official Build) (64-bit)

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Comment by davidjgraph** [comment]
Fix in 22.0.3
