### ISSUE TITLE
Variable referencing within a Drawio diagram.

### ISSUE THREAD

**Issue by tolleif** [jgraph/drawio#3911]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Variable referencing within a Drawio diagram.

On the diagram it is possible to add Properties and values which is useful for export.

Let's say we create a Property called "CompanyName" and the value is "Contoso"

I'd like to see extended use of such data properties.
If I create a bunch of text symbols where I want to show "Contoso" I do not want to hard code that all over Changing would be a nightmare and some will be forgotten. Instead I'd like to enter some special reserved character and the data variable i.e. "$$$Data:CompanyName$$$" knowing that when the drawing is presented my  "$$$Data:CompanyName$$$" is replaced with "Contoso". Maybe also built-in variables like file date, filename, etc.

Thank you for your time.

Tolleif

**Comment by davidjgraph** [comment]
https://www.drawio.com/blog/placeholders
https://www.drawio.com/doc/faq/predefined-placeholders
?
