### ISSUE TITLE
Revamped IBM Stencils with only five static simple shapes and new icons for IBM Cloud.

### ISSUE THREAD

**Issue by jaywarfield** [jgraph/drawio#3914]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
The existing IBM stencils that drawio implemented have been excellent but we are no longer submitting updates.  

**Describe the solution you'd like**
We would like to request drawio's help to implement the revamped new shapes and icons described here with five static simple shapes using existing drawio features as described in the attached IBMShapes.pdf.  This will help to 1) ensure that users can create diagrams for our growing product offerings, and 2) grow our user base on drawio for simple and complex architecture diagrams.  The first slide of IBMShapes.pdf describes how the new shapes relate to the old shapes with the new shapes also being simple and static but in code only and using only icons from svg2xml.

The refreshed and validated icons are in the attached IBMIcons directory which includes icons for our latest product offerings including AI.  All icons are from our design center with quality processes, and we have recently added additional processes for our icons to work flawlessly with svg2xml.  

We are planning on only two sidebars and request that More Shapes contain selections for "IBM Cloud" and "IBM Shapes" sidebars with content as described in the attached IBMSidebars.xlsx, and both sidebars will use the same set of icons.  The IBM Shapes sidebar is intended more for non-cloud use cases eventually to grow our user base across multiple use cases in drawio, but most important are the shapes described here for cloud so we can grow our use base on cloud in drawio before looking at other use cases.  Let us know if there is another method for providing the details of the sidebars.  

Contents of the attached [IBMStencils.zip](https://github.com/user-attachments/files/17267846/IBMStencils.zip) :

1. IBMShapes.pdf – Details for the five new static simple shapes.
2. IBMSidebars.xlsx – Spreadsheet describing contents of IBM Cloud and IBM Shapes sidebars.
3. IBMColors.json – Contains the IBM Color Palette.
4. IBMFonts.json – Contains the IBM Plex Fonts on Google Fonts.
5. IBMIcons – Directory of icon svg files ready for input to svg2xml.

Our shapes will only be static simple shapes using existing drawio features.  For other features/complexities we are looking at handling on our side with diagram-as-code as appropriate.  We look forward to the drawio team's implementation of this revamped proposal and refining to meet drawio's recommendations and standards.  Let us know if you need anything else or have any questions.

**Describe alternatives you've considered**
No alternatives, drawio is the best tool.

**Additional context**
Refer to IBMShapes.pdf for screenshots and details.

**Comment by jaywarfield** [comment]
Before assigned, the IBMStencils.zip has been kept updated.

When IBM Cloud and IBM Shapes sidebars are available in More Shapes the old sidebar named "IBM" can be removed from More Shapes.

The old nine templates under Cloud / IBM can be removed and we will submit new templates when IBM Cloud and IBM Shapes sidebars are available. 

Let me know if you have any questions.

Thanks!

**Comment by egrimate** [comment]
Just a couple questions:
1. Can you please describe in more detail what dropin images are? 
2. Is defining icons ok via style (there is an entry in the style string that defines what icon will be used) or does it explicitly has to be dropping on a shape/container?
3. What is the difference between IBM icons and dropin images?
4. If you want to use IBM Plex Sans, you have to host is somewhere and the link must not change over time. Otherwise the app will regress to a default font.

**Comment by egrimate** [comment]
Is the updated IBMStencils.zip attached?

Also, adding new icons is fine, but please keep the changes to existing ones to a minimum, since we have to keep all the old variants too.

**Comment by jaywarfield** [comment]
For questions 1-3,
the style for the VPC Virtual Server under IBM Cloud / Compute might include the following depending on your naming:
shape=mxgraph.ibmshapes.pnode;icon=ibm-cloud--virtual-server-vpc;image=;

The IBM Icon refers to that "icon=ibm-cloud--virtual-serer-vpc;" where that icon name is in the xml you create with svg2xml.  The IBM Icon is used but if an image is dropped onto the shape then that image is used and the "image=;" is set to the image.  May be useful if another icon is needed that is not available in the sidebar, but not used very often if you don't think the "image=;" is needed.

**Comment by jaywarfield** [comment]
For question 4,
the IBMFonts.json included in the IBMStencils.zip defines the fontCss from Google Fonts and customFonts names.
The fontCss will eventually need to include IBM Plex for Chinese which is not available yet. 

We have been using semibold (weight 600) for shape labels by using the following along with "html=1;" specified in the style:
<b style='font-weight:600>label</b>

I didn't mention using semibold for shape labels in the ppt/pdf in IBMStencils.zip because semibold is not available in the Format Panel which has bold (weight 700), but if shapes labels can start out with semibold that would be a consideration, connectors labels always start out with regular font.  I understand too if using semibold would be confusing with the bold in the Format Panel.

**Comment by jaywarfield** [comment]
For the IBM Shapes (non-cloud) sidebar, "icon=undefined;" would be set in the style on each shape.  

It would be useful if there is an existing way for users to select from a list of icon names available in ibmicons.xml (or whatever name you use for the output of svg2xml) which then changes the "icon=undefined;" to another icon name , but alright if not.  The icon name can also be specified in our diagram-as-code that I mentioned in the original description which helps create drawio files.

**Comment by davidjgraph** [comment]
With the fonts the issue is where will the fonts be hosted? We don't host fonts. There needs to be a fixed, permanent, URL where the font files can referenced from.

Or, each user needs to install the fonts locally (which they'd have to do on the desktop version, anyway).

**Comment by jaywarfield** [comment]
Sure, defaulting to a regular font is alright too and we mention another font (Arial if I recall) as being similar to Plex.  

Plex would be desired if possible.  
Users can install the Plex fonts locally.
And is Google Fonts considered a permanent location? 

The IBMFonts.json was created from Google Fonts:
{
"fontCss":
        "@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@400;600;700&family=IBM+Plex+Sans+Devanagari:wght@400;600;700&family=IBM+Plex+Sans+Hebrew:wght@400;600;700&family=IBM+Plex+Sans+JP:wght@400;600;700&family=IBM+Plex+Sans+KR:wght@400;600;700&family=IBM+Plex+Sans+Thai:wght@400;600;700&family=IBM+Plex+Sans:ital,wght@0,400;0,600;0,700;1,400;1,600;1,700&display=swap');",
"customFonts":
       ["IBM Plex Sans",
        "IBM Plex Sans Arabic",
        "IBM Plex Sans Devanagari",
        "IBM Plex Sans Hebrew",
        "IBM Plex Sans JP",
        "IBM Plex Sans KR",
        "IBM Plex Sans Thai"]
}

This was created following this [blog](https://drawio-app.com/blog/customise-default-colours-fonts-styles-and-the-draw-io-ui-in-confluence-cloud/).  I was impressed with how Google Fonts puts everything together nicely into a single import statement.  

The blog is for Confluence which may not apply generally.
We have a permanent location for Plex also which I will need to look into.  

Thanks!

**Comment by jaywarfield** [comment]
fontFamily of IBM Plex Sans is the default.

With customFonts in IBMFont.json the complete list in the Format Panel is
IBM Plex Sans
IBM Plex Sans Arabic
IBM Plex Sans Devanagari
IBM Plex Sans Hebrew
IBM Plex Sans JP
IBM Plex Sans KR
IBM Plex Sans Thai

And Chinese will come later.

If that is too much to implement initially, the IBM Plex Sans is primary use case to start with.

If Arabic, for example, is intended for an entire diagram, setting fontFamily to Arabic is done for each shape unless there's a way to have Arabic be used for an entire diagram.

**Comment by jaywarfield** [comment]
Let me know if you have any questions about IBMColors.json and IBMFonts.json in IBMStencils.zip.

Before our mtg we were specifying the font source in the styles and manually selecting stroke and fill colors that correspond to the IBM Color Palette.

Then we moved to the drawio customization:
- For IBMColors.json, using the drawio customization for the IBM Color Palette is excellent, and customizing the color schemes is perfect for us since we recommend using a light fill color from the same color family as the border color or a fill color of white, all combinations are included in our color schemes, and IBMColors.json enables users to know what colors are in the IBM Color Palette.
- For IBMFonts.json, using the drawio customization to include the import url from Google Fonts is also excellent, and we can easily give you an updated import url when Chinese is added to Plex.  Google Fonts also makes it easy to create a single import url of all the Plex fonts we select.  If you include this import url we would verify all of the languages.

The IBMColors.json (won't change) and IBMFonts.json (easy change when Plex Chinese is available which is the last Plex language) are examples for your consideration, depending on your direction and how customization is intended.

Thanks!

**Comment by jaywarfield** [comment]
For the IBM Cloud sidebar sheet in IBMSidebars.xlsx with IBMShapes.pdf included in IBMStencils.zip:
- Categories are Groups, Actors, AI, Compute, Containers, Data, DevOps, Network, Observability, Security, Storage, and Connectors (Connectors have labels with end types in parens if any).
- Zone group shape types are set to container=0 and strokeWidth=2 with dashed border.
- All other group shape types are set to container=1 and strokeWidth=1 (one case of strokeWidth=2) with solid border.

For Zone groups with container=0, the excellent feature you implemented for our previous sidebar still applies where selecting shapes inside of container=0 groups may require using alt-click or option-click or change the Z order by moving shapes backward.

The container=0 versus container=1 can be easily missed with the groups, so just emphasizing the container=0 for Zone groups only.

Thanks!

**Comment by egrimate** [comment]
Please check out our implementation and let us know if it matches your expectations.

https://ea8f1c63.drawio-dev.pages.dev/

**Comment by jaywarfield** [comment]
Everything looks excellent and works perfectly!

Depending on your direction, is it alright for shape labels to default to 14px and connector labels 12px (although connector labels are added by user), and will changing strokeColor of group border also change sidebar color and icon color.

Only a few minor corrections for your consideration:
1. In Groups category, typo in spreadsheet if you can please change label “Generic Core” to “Generic Group”.
2. In Containers category, if you can please change label for OpenShift, and add Kubernetes Service icon from spreadsheet.
3. In Data category, if you can please change labels for MongoDB and MySQL to mixed case.
4. In Network category, typo in spreadsheet if you can please change Classic Load Balancer to use internal icon name “load-balancer—classic”.

Thanks!

**Comment by egrimate** [comment]
The minor corrections and shape label sizes are done, but connector labels and color changing needs additional code on project level and there are no short or medium term plans to implement

**Comment by jaywarfield** [comment]
I understand, we are continuing to exercise and really like the implementation, thanks!

**Comment by jaywarfield** [comment]
If still possible, could you please check the container=0 behavior of the Zone shapes in the Groups category:

- Shapes placed inside the Generic Zone shape don't move when the Generic Zone is moved which is working as expected.
- However, shapes placed inside the other Zone shapes (such as Security Group) are moving with the Security Group as if container=1 is set but container=0 is set.   

Thanks!

**Comment by jaywarfield** [comment]
Sounds good, all of the Zone shapes correctly have container=0 set, and we'll look forward to the fix in a follow-on release so shapes placed inside the Zone shapes don't move when the Zone shape is moved, which applies to all of the Zone shapes (Access Group, Account Group, Resource Group, Security Group, Instance Group, Placement Group, and Availability Zone).  Thanks!
