### ISSUE TITLE
Table with Title 1, crashes when first row is deleted

### ISSUE THREAD

**Issue by Zockaholika** [jgraph/drawio#3915]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**

**To Reproduce**
1. Go to forms
2. Click on Table with Title 1
3. mark the first two rows
4. merge the first two rows
5. delete this rows
6. browser or program is crashing

**Expected behavior**
It only need to delete this rows and dont crash the program/browser

**Screenshots**
<img width="316" alt="image" src="https://github.com/jgraph/drawio/assets/113764832/7c3a94b2-ccd2-43ab-874b-4cd141c183ee">
<img width="240" alt="image" src="https://github.com/jgraph/drawio/assets/113764832/a92639f5-d7ef-4a68-be03-bc806e9bc7a4">
<img width="187" alt="image" src="https://github.com/jgraph/drawio/assets/113764832/63a83afb-8a52-43d5-8224-f06c04f459de">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.0.2

**Desktop (please complete the following information):**
 - OS: [Windows 11 Pro 22H2]
 - Browser [Google Chrome and Desktop App]
 - Browser Version [117.0.5938.134]

**Smartphone (please complete the following information):**
 - Device: [i used only my PC]
 - OS: [i used only my PC]
 - Browser [i used only my PCi]
 - Version [i used only my PC]

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-"yes"

**Additional context**
Loog at the Screenshots there i highlited my steps

**Comment by davidjgraph** [comment]
Cannot repeat.
