### ISSUE TITLE
Enhance Freehand Drawing Tool with On-the-Fly Color Selection and Keyboard Shortcuts

### ISSUE THREAD

**Issue by misharigot** [jgraph/drawio#3916]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
While diagrams.net's freehand drawing tool (activated via the x keyboard shortcut) is incredibly useful for quick sketching, it lacks the option to change the pen color on-the-fly. This limitation can make it cumbersome when trying to create color-coded or multi-colored sketches.

**Describe the solution you'd like**
I propose that diagrams.net introduce a color palette in the freehand tool's floating window that appears after activating it with the x keyboard shortcut. This palette could feature a set of 10 preset colors for quick selection. Alongside these presets, it would be highly beneficial to include a color picker for more granular control over the color selection. To streamline the drawing process further, these preset colors could be mapped to the 1-0 keyboard keys, allowing users to effortlessly switch between colors while sketching.

**Describe alternatives you've considered**
Currently, the only workaround is to finish drawing the shape and then manually select it to change its line color via the formatting window on the right side. This method, however, interrupts the flow of sketching and adds unnecessary steps to the drawing process.

**Additional context**

Desired solution:
![image](https://github.com/jgraph/drawio/assets/15928604/666654bc-9055-48a8-8373-051a31de9f17)

Only way to currently change colors, as far as I know of:
![image](https://github.com/jgraph/drawio/assets/15928604/92b36abc-e929-4d57-b8e2-e49abed6c1ed)

**Comment by tbui-isgn** [comment]
Having this would be a HUGE improvement!

**Comment by ljburtz** [comment]
yes please the lack of this feature is a dealbreaker for this tool -> two people can't collaborate with the freehand tool since the only color is black it becomes very messy very quickly.

**Comment by FolkertRA** [comment]
I like the idea, but would alter the short keys for colors to match "resistor color coding", which I think is a more universal color to number coding scheme
![image](https://github.com/jgraph/drawio/assets/20575061/f86fe2e1-a600-4d09-a2a5-e1d4497bf161)
