### ISSUE TITLE
[Feature Request] Include data and object id in svg output

### ISSUE THREAD

**Issue by null-saad** [jgraph/drawio#392]
Problem : Need a way to reference the SVG elements after exporting, something like a custom attribute/property that reflects in the <svg> tags.

**Similar Issue :** As the following issue is closed https://github.com/jgraph/drawio/issues/77#issue-210952489 is there a solution provided because the given URL for the SVG Plugin https://github.com/jgraph/drawio/blob/master/war/plugins/svgdata.js does not work ?

**Comment by alderg** [comment]
The plugin is here: https://github.com/jgraph/drawio/blob/master/src/main/webapp/plugins/svgdata.js
Load it via https://www.draw.io/?p=svgdata

**Comment by null-saad** [comment]
> The plugin is here: https://github.com/jgraph/drawio/blob/master/src/main/webapp/plugins/svgdata.js
> Load it via https://www.draw.io/?p=svgdata

Hey, thanks for support but this does not work when exporting as HTML, and for some weird reasons the export as SVG and as HTML generates different kinds of output. Is this normal behavior ?
