### ISSUE TITLE
With google Slides plugin, and draw.io/diagrams in dark theme, the diagram is white-on-black in app, but not in slides.

### ISSUE THREAD

**Issue by IliasBergstrom** [jgraph/drawio#3923]
### Preflight Checklist

* [X ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**

With google Slides plugin, and draw.io/diagrams.net in dark theme, the diagram is white-on-black in app, but not in slides.
See the picture below.

**To Reproduce**
1. Install diagrams plugin for Slides.
2. Create a diagram in diagrams.net
3. Set diagrams to dark theme - the diagram will auto-switch its colours to white-on-black.
4. Create a slide with a black background
5. Insert the created diagram with the slides plugin.
6. The slide will fail to reverse the colours as it does in the app.

**Expected behavior**

I would expect the diagram in draw.io/diagrams.net (I've tried both), to look the same in google Slides when embedded with the plugin, as it does in the app.

Or at the very least, that there's an option in the plugin, which allows me to select an appropriate "theme" setting: light/dark/(auto/match app).

**Screenshots**

![Screen Shot 2023-10-11 at 09 17 29 AM  1](https://github.com/jgraph/drawio/assets/54887066/6b926f07-ab07-4710-90f2-f124062db770)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.0.2

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS 13.3.1
 - Browser Chrome
 - Browser Version 117.0.5938.149 (Official Build) (arm64)

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
Yes

**Additional context**

**Comment by davidjgraph** [comment]
Note to self, slides doesn't have a dark mode so we probably could detect where the request is coming from and also export in light.

**Comment by davidjgraph** [comment]
Google Slides only has a light mode, diagrams need to be designed in light mode to match. If Google Slides ever has a dark mode and allows us to indicate that during the image creation, we'll use that.
