### ISSUE TITLE
With google Slides plugin, and draw.io/diagrams.net, when I try to insert any diagram, into any set of slides, I get an error pop-up: w return code 530, server response error code: 1033

### ISSUE THREAD

**Issue by IliasBergstrom** [jgraph/drawio#3925]
### Preflight Checklist

* [X ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**

With google Slides plugin, and draw.io/diagrams.net, when I try to insert any diagram, into any set of slides, I get an error pop-up:

1 insert failed:
- TWO Class Diagrams.drawio: Request failed for https://convert.diagrams.net returned code 530. Truncated server response: error code: 1033 (use muteHttpExceptions option to examine full response).

**To Reproduce**

I honestly don't know - it seems permanent for my account? I've tried making a new diagram, and inserting it into a new slide. I still get it.

**Expected behavior**

I would expect the diagram in draw.io/diagrams.net (I've tried both), to look the same in google Slides when embedded with the plugin, as it does in the app.

Or at the very least, that there's an option in the plugin, which allows me to select an appropriate "theme" setting: light/dark/(auto/match app).

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.0.2

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS 13.3.1
 - Browser Chrome
 - Browser Version 117.0.5938.149 (Official Build) (arm64)

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
Yes

**Additional context**

**Comment by davidjgraph** [comment]
Still happening now?

**Comment by IliasBergstrom** [comment]
Nope, just tested, now it's fine!
