### ISSUE TITLE
understand docker-compose yaml files for component draws in drawio

### ISSUE THREAD

**Issue by miksch27** [jgraph/drawio#3927]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by miksch27** [comment]
I redraw my docker server landscape...  This is defined in a yml file.
My sample: https://github.com/miksch27/mongoDBDocker/blob/main/docker-compose.yml.  Indentions and keys are describe a cluster of boxes.   I think there are quite more docker-compose.yml files that might need to explain to other nerds..
Could you offer a method that put "named" boxes into drawio. which might allow to produce a system component diagram.   
... Thank you!!

**Comment by davidjgraph** [comment]
Thanks for the suggestion. Unfortunately, the request didn't gain enough interest over the open it was open to justify the effort of implementation and maintenance.
