### ISSUE TITLE
Select Current Layer based on Element selection

### ISSUE THREAD

**Issue by AntoniusGolly** [jgraph/drawio#3928]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Is your feature request related to a problem?
**Yes**
As much as I like Drawio and Diagrams.net and as heavily rely on it in our daily work documenting and planning a large application in cross-functional teams, there are two things that greatly hinder our work. One of them is this:

* Layer A is active layer
* Work on Layer A, arrange items in Layer A, etc
* Now I work on elements of layer B
* ie. arrange items in Layer B, 
* If I copy/paste an element of layer B, it becomes a member of layer A! (because active Layer doesn't change upon Element selection)

### Describe the solution you'd like
* When I am in active Layer A, and select an element of Layer B -> **Layer B should become the active Layer**
* That's how it is done in many other graphic programs
* At least, make this a setting the customer can choose from

### Describe alternatives you've considered
There are no alternatives. People forget what the active Layer was and our diagrams constantly get messed up and inconsistent as Elements of one layer are spread across multiple layers due to copy paste and wrong active layer was chosen.

### Context
* copy paste is done by either drag + CTRL or CTRL+C, CTRL+V

That would change my world. Thanks.

**Comment by davidjgraph** [comment]
selectParentLayer config switch added in 22.1.4.
