### ISSUE TITLE
Spacing between <li> elements

### ISSUE THREAD

**Issue by palexdev** [jgraph/drawio#3930]
I have a bunch of rectangles in which reside numbered lists as text. The issue I'm having is that elements are way too close to each other, and there seems to be no feasible way to specify a certain spacing between them.

It would be good in the properties tab on the left to have a field for this.
Or, at the very least, document a way of achieving it. In HTLM `<li>` elements can be spaced out by setting something like this in CSS:
```css
li {
  margin: 10px 0;
}
```

Currently, the only way to do something similar is to:
1) Change the line height property, BUT if the element is on multiple lines than the effect is ugly to say the least
2) Add a blank line at the end of the text with Shift+Enter

**Comment by alderg** [comment]
You can add CSS to the `<li>` elements by clicking the HTML button while editing. The CSS of the first element will be used in new elements:
![66b0ac55f97f6038106163a3941c9480](https://github.com/jgraph/drawio/assets/921200/82e313f3-9629-45df-9468-afeb6c8dbc2b)
