### ISSUE TITLE
Racks don't snap to rack units by default

### ISSUE THREAD

**Issue by JohnstonJ** [jgraph/drawio#3935]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
The Numbered Rack Cabinet and Rack Cabinets by default do not snap equipment to rack units.

**To Reproduce**
1. Create a new diagram using the Blank Diagram template.
2. Click "More Shapes" and add Networking: Rack shapes.
3. Add the "Numbered Rack Cabinet" shape from Rack / General to the diagram.
4. Add the "Cover Plate" shape from Rack / General by dragging and dropping it somewhere into the center of the rack cabinet.
5. Observe that the cover plate is snapping to the global grid, not to the rack units in the cabinet.
6. Try moving the cover plate to a different rack position and notice how it never quite aligns right with the rack units, instead snapping to the grid.  Resizing the cover plate vertically will also not snap it to rack units, instead ending up with odd equipment heights.

Workaround:

The problem appears to be that the `rackUnitSize` style is missing.  Right-click the rack cabinet and click "Edit Style", and then add `rackUnitSize=14.8;` to the styles.  Then the expected behavior will occur.  This can also be accomplished by going to the Style tab, and editing the "Unit height" property, which shows a default of 14.8: change the value to a different value like 15.0, and then back to 14.8 or other desired value.

**Expected behavior**
The rack equipment should snap to rack units by default, such as seen in the demo video on the blog post at https://www.drawio.com/blog/rack-diagrams

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/13113915/0e917b37-53cd-4e1c-96bf-287ba3afb71f)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.0.4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Browser Version: 118.0.2088.46

Also reproduced with Draw.io desktop application for Windows.

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Comment by pdjohntony** [comment]
I'm also having this problem. Thanks for the `rackUnitSize=14.8;` workaround!
