### ISSUE TITLE
Page unresponding error after pasting an image

### ISSUE THREAD

**Issue by hinfien** [jgraph/drawio#3939]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
When I try to insert an image of a smoking toilet the drawio page stops responding

**To Reproduce**
1. Go to https://www.deviantart.com/gothnebula/art/Toilet-Smoking-prank-again-884168537
2. Copy this image
3. Paste this image in drawio
4. See *page unresponding* error

**Expected behavior**
I thought I'd insert a picture of a smoking toilet

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io 22.0.4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Brave: 1.59.117 Chromium: 118.0.5993.70

**Smartphone (please complete the following information):**

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-yes

**Additional context**
This bug also exists in incognito mode and in microsoft edge

**Comment by davidjgraph** [comment]
What is the exact URL of the image you are copying?

**Comment by hinfien** [comment]
> What is the exact URL of the image you are copying?

https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/75b358c7-c23b-433b-9002-4d875e2e1fc5/demest5-911f5342-53b7-43d5-a372-9ed9ae87556d.jpg/v1/fit/w_828,h_1104,q_70,strp/toilet_smoking_prank_again_by_gothnebula_demest5-414w-2x.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzc1YjM1OGM3LWMyM2ItNDMzYi05MDAyLTRkODc1ZTJlMWZjNVwvZGVtZXN0NS05MTFmNTM0Mi01M2I3LTQzZDUtYTM3Mi05ZWQ5YWU4NzU1NmQuanBnIiwiaGVpZ2h0IjoiPD0xMzY2Iiwid2lkdGgiOiI8PTEwMjQifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uud2F0ZXJtYXJrIl0sIndtayI6eyJwYXRoIjoiXC93bVwvNzViMzU4YzctYzIzYi00MzNiLTkwMDItNGQ4NzVlMmUxZmM1XC9nb3RobmVidWxhLTQucG5nIiwib3BhY2l0eSI6OTUsInByb3BvcnRpb25zIjowLjQ1LCJncmF2aXR5IjoiY2VudGVyIn19.JSSJr67e1a8NZ7uz79y0uvMIjyU_9r6XDzG4hDCRLkI

**Comment by davidjgraph** [comment]
Kinda shitty example to pick.

**Comment by davidjgraph** [comment]
Fix in 24.0.7.
