### ISSUE TITLE
Getting messy navigating complex diagrams

### ISSUE THREAD

**Issue by quantic-dream** [jgraph/drawio#3948]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**The problem:**
When using diagrams on touchscreen devices I always get frustrated trying to navigate and edit complex diagrams with many shapes (hundreds) and very little or none empty space. When doing this I accidentally move the shapes constantly. Locking the layer is not an option due to lack of empty space (needed to displace) in many cases.

**3 solutions I propose: (edited from 2 to 3)**
1. In lock layer option, make shapes to be able to work like empty space for displacement.
2. Preferred one: accesible button to switch between "normal mode, aka mouse mode" and "only move pre-selected shapes, aka touch screen mode" (tap, finger up, drag), and double tap for edit.
3. coolest if well implemented: 2 fingers to navigate through the canvas.

**Grateful for your work**
For me, it's the best diagrams app for mouse devices, with some workaround for this behavior would also be the best for touch screen devices for me. Thank you.

**Comment by alderg** [comment]
As a workaround, try press and hold two fingers to the screen, and move them vertically and horizontally.

**Comment by alderg** [comment]
What touchscreen device, what browser and what version of draw.io are you using?
