### ISSUE TITLE
copy content/output of variables to clipboard

### ISSUE THREAD

**Issue by dlewando** [jgraph/drawio#3949]
* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Using global variables which are shown in placeholders cannot be copied to clipboard (the content/text you see).

**Describe the solution you'd like**
It would be nice to have an option by right-clicking onto that text-field (which includes the placehoder for the variables) to copy the output (not the variables)

**Describe alternatives you've considered**
The alternative is to write down the text you see with good old style (pencil and notepad on your desk)

**Additional context**
currently, it's not possible to copy a textfield by just right-click. You need to double-click onto that text-field
 that the text is all marked and then copy it. if you do this with text where variables are used, you will copy the variable name and not the output/content of the variable.
 It would be nice to add this "copy text as seen" feature in a future release :)

**Comment by davidjgraph** [comment]
22.1.6 adds resolved placeholders in output for Export button in edit data dialog.

<img width="512" alt="287501841-65cd6063-ff66-4691-8953-4a9b760276ae" src="https://github.com/jgraph/drawio/assets/1761087/95c3a061-d232-4dd2-9129-59b151a70bf4">
