### ISSUE TITLE
Error loading file: Google Drive

### ISSUE THREAD

**Issue by Oh4sh0** [jgraph/drawio#3952]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I save a file in Google Drive and re-open it at our co from within draw.io, I am almost always met with "Error loading file. The file does not exist or you do not have access."

**To Reproduce**
1. Select GDrive as save location.
2. Add a few elements to the blank doc
3. Let it save
4. Try and open it from Google Drive
5. Error dialog appears

**Expected behavior**
File opens without error

**Screenshots**
https://imgur.com/Rq9D4a7

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 22.0.6

**Desktop (please complete the following information):**
 - OS: macOS 
 - Browser: Google Chrome
 - Browser Version: Has been an issue for many versions, current V is 118.0.5993.88 

**Smartphone (please complete the following information):**
 - Device: NA
 - OS: NA
 - Browser NA
 - Version NA

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes, issue appears there as well.

**Additional context**
I see the following in the console, which may be helpful:
Failed to load resource: the server responded with a status of 403 (Forbidden)
/drive/v2/files/15XAjZVxSXldNf0f9g_Vlm1a9A1N6DxFY?alt=media&source=downloadUrl:1 
        
Failed to load resource: the server responded with a status of 404 ()
app.min.js:13041 error in loadFile: 15XAjZVxSXldNf0f9g_Vlm1a9A1N6DxFY Object

**Comment by mararad** [comment]
Hi,

I am not able to reproduce the issue in Chrome Version 118.0.5993.89 (Official Build) (64-bit) but on Win. Do you maybe have a possibility to test on another machine using Win?

**Comment by Oh4sh0** [comment]
I had another user test on Windows, and they were not able to replicate the UX.

**Comment by Oh4sh0** [comment]
I had another that indicated they could, so it's possible, probable this is a proxy or dlp ruleset issue that is causing the problem.

**Comment by Oh4sh0** [comment]
We were able to adequately confirm this was an "our network" issue rather than a product issue.
