### ISSUE TITLE
Bad visual glitch in toolbar when scrolling

### ISSUE THREAD

**Issue by JesseAldridge** [jgraph/drawio#396]
https://www.dropbox.com/s/tl8f86weekat9qt/glitch.mov?dl=0

See the linked video. It only happens if my canvas has multiple pages.

**Comment by alderg** [comment]
What version of macOS and what version of draw.io? Can you share the file for testing?

**Comment by JesseAldridge** [comment]
![screen shot 2019-03-07 at 7 26 19 pm](https://user-images.githubusercontent.com/191903/54005623-fd81ca80-410e-11e9-999c-53a5557382ea.png)

https://www.dropbox.com/s/npo1m1rq6mzuhdl/amazon_selling.xml?dl=1

**Comment by alderg** [comment]
What version of draw.io are you using?

**Comment by JesseAldridge** [comment]
v10.3.6

**Comment by alderg** [comment]
And this is the desktop version, correct?

**Comment by JesseAldridge** [comment]
Yes, it's the desktop version.
I haven't used the app in a couple of months, but never saw this glitch
before.
So I guess the bug was introduced between then and now?

**Comment by alderg** [comment]
Just checked using macOS 10.14.3 with draw.io desktop 10.3.6 and it works for me (see https://gyazo.com/6e10c9e611f07fa0384baa13c3bc5271). What are the steps to reproduce this problem?

**Comment by JesseAldridge** [comment]
1. Create a new file.
2. Add a bunch of random text across multiple pages.
3. Scroll around.

That's it.
It's pretty clearly a memory corruption issue right? So if I reboot I think
the problem will go away temporarily at least.
But none of the other applications I'm running are having this problem.

**Comment by alderg** [comment]
I tried those steps but I'm not seeing this problem and there were no other reports of this so far. Have you tried another machine or upgrading macOS to the latest version? Are you also getting this problem when loading the file with the online version at www.draw.io?

**Comment by alderg** [comment]
We've deployed 10.3.8 with more defensive CSS. Can you check if this fixes it?

**Comment by JesseAldridge** [comment]
Yeah, that seems to have fixed it. Thanks.
