### ISSUE TITLE
Groups not preserved in svg export

### ISSUE THREAD

**Issue by wryun** [jgraph/drawio#3960]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Groups defined in the application are not exported to an SVG.

**To Reproduce**
1. Create three lines.
2. Select two of them, and group them (right click -> group)
3. Export as SVG
4. Examine resulting SVG file

It will look something like:

```
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="background-color: rgb(255, 255, 255);" version="1.1" width="222px" height="222px" viewBox="-0.5 -0.5 222 222">
  <defs/>
  <g>
    <path d="M 170 220 L 220 170" fill="none" stroke="rgb(0, 0, 0)" stroke-miterlimit="10" pointer-events="stroke"/>
    <path d="M 60 90 L 110 40" fill="none" stroke="rgb(0, 0, 0)" stroke-miterlimit="10" pointer-events="stroke"/>
    <path d="M 0 50 L 50 0" fill="none" stroke="rgb(0, 0, 0)" stroke-miterlimit="10" pointer-events="stroke"/>
  </g>
</svg>
```

**Expected behavior**
```
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="background-color: rgb(255, 255, 255);" version="1.1" width="222px" height="222px" viewBox="-0.5 -0.5 222 222">
  <defs/>
  <path d="M 170 220 L 220 170" fill="none" stroke="rgb(0, 0, 0)" stroke-miterlimit="10" pointer-events="stroke"/>
  <g>
    <path d="M 60 90 L 110 40" fill="none" stroke="rgb(0, 0, 0)" stroke-miterlimit="10" pointer-events="stroke"/>
    <path d="M 0 50 L 50 0" fill="none" stroke="rgb(0, 0, 0)" stroke-miterlimit="10" pointer-events="stroke"/>
  </g>
</svg>
```
(or nested groups, if the top level group is necessary)

**draw.io version (In the Help->About menu of the draw.io editor):**

- 22.08

**Desktop (please complete the following information):**
 - OS: Linux
 - Firefox
 - 118.0.2

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- no (not relevant)

**Additional context**

I'm hoping to programmatically hide various groups in an SVG. Unfortunately, because the groups are lost in the export, the only way around I can see it to add them in post-processing, but I don't know of an easy way to identify them since element data is also not preserved in the export (I think?).

**Comment by wryun** [comment]
Found svgdata in https://www.drawio.com/doc/faq/plugins which may provide a workaround.

**Comment by wryun** [comment]
I am still active and vaguely frustrated :)

**Comment by davidjgraph** [comment]
You understand this is a free, open source project? We don't remotely have the resources to deal with every issue.

**Comment by wryun** [comment]
No worries, not expecting you to change this; I shouldn't have mentioned my frustration. Bumping since that was what the bot seemed to suggest I do. If you'd like to close this as wontfix, that's fine.

**Comment by davidjgraph** [comment]
Groups preserved in 24.6.0.

**Comment by wryun** [comment]
Thanks! This will be really useful :) Appreciate it.
