### ISSUE TITLE
Can't save, export, import projects in Linux Mint 21.2 MATE with Draw.io Standalone

### ISSUE THREAD

**Issue by cxbignekoc** [jgraph/drawio#3964]
installed via flatpak
- draw.io             com.jgraph.drawio.desktop 22.0.3

```
linux mint 21.2 MATE
kernel 5.15.0-88-generic
AMD ATI Radeon R9
Intel i7 479
```

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You already have a way around the issue but not have a solution presented:
https://www.drawio.com/doc/faq/diagram-source-save

**Describe the bug**

Try to use links for save, export, import projects inside the app result in "No Action".
Export shows me a Dialog for Settings but "export" results in a short loading animation and stops and hides

Further **i can not** 
- open websites from inside the app, (but it works also not in synaptic paket manager)
- use the button "saved change - click here for saving"
- choose an export Folder, because no dialog
- keyboard shortcuts
- quich start video

i can use:
- undo redo
- all drag and drop from sidebar features
- write text and text options
- using darktheme and style options (was not working first time, but after reboot)
- copy as picture and import it to gimp (thankfully)
- edit diagram exporting, 
- File New
- Open Dev Tools
- 

**To Reproduce**
1. open draw.io from start menu, window open that say java is enabled
2. draw some sweet geometric cats, can use all thing it feeld
3. Go to File 'SAVE' nothing happens
4. 'Save as' nothing happens
5. click here to save - button, nothing happens
6. export as PNG, Dialog pop, click export nothing happens, but a short Loading Icon flickering
7. then trying ALL export functions, but nothing works
8. i try other Options, i can create a new Library and add Pictures to it and **here Caja opens**
9. Then after trying a lot in Files, the Pictures turns parts into black outlined objects from white and some objects are filled white with also black outlines...this can not be a missclick

**Expected behavior**

- draw.io opens Caja to select a Path, Folder, giving a Filename and save the project in a regular way

**Screenshots**

https://github.com/jgraph/drawio/assets/31941245/f0c76a5d-c06a-404c-b166-2425acf17e45

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.0.3

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.2 MATE
 - Browser Firefox

**Smartphone (please complete the following information):**

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
i test it not in Browser

**Additional context**
-none

**Comment by davidjgraph** [comment]
We are not the author of the flatpak distro.

**Comment by cxbignekoc** [comment]
Hi, i dont understand your comment.

can you shortly explain what that means?
draw.io is from you isn't it?
