### ISSUE TITLE
Lines jump at the branching point of branching lines

### ISSUE THREAD

**Issue by iwasakin** [jgraph/drawio#3965]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Lines jump at the branching point of branching lines like as the attached image.
This issue does not occure befor draw.io-20.8.16.

**To Reproduce**
1. Draw two lines which seems branching
2. Change jump property of the upper line to enable

**Expected behavior**
The lines jumps at the branching point of branching lines.

**Screenshots**
See the screenshot
![ss](https://github.com/jgraph/drawio/assets/56847361/c97543c4-e985-4db4-a63a-bda8cc57df3a)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.0.3

**Desktop (please complete the following information):**
 - OS: Windows 10 pro

**Additional context**
- I think #2664 changeing affects this behavior.
- We can avoid this issue to change z-order of lines.

**Comment by davidjgraph** [comment]
Fixed in 22.1.19, thanks for report.
