### ISSUE TITLE
Grouping seems to be broken on MacOS

### ISSUE THREAD

**Issue by rcdrifter900** [jgraph/drawio#3967]
When creating a blank document, I create a square and some circles that's filled in black. I group the one square and three circles via right click and group. I click on the square to drag around the circles do not come with it. I have to highlight everything, which seems that group is broken. Running version 22.0.2, on MacOS Sonoma 14.0.

**Comment by mrndev** [comment]
Im using 22.0.8 and the grouping seems to be still broken. I create two rectangles and group them. I if move the group once (click and drag) the group moves. if I move it the second time, just the rectangle under the cursor moves and it breaks the group. Can you fix this or explain why the behavior is what it is?
