### ISSUE TITLE
Save to Egnyte

### ISSUE THREAD

**Issue by pklapperich** [jgraph/drawio#3968]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

I would like to see Egnyte.com added as a storage back end. [Developer documentation is here](https://developers.egnyte.com/docs).

**Comment by davidjgraph** [comment]
We don't want to add any integrations, unless they are clearly in mass use, which this isn't.
