### ISSUE TITLE
Ability to hide/unhide layers at a user define zoom range

### ISSUE THREAD

**Issue by kwtj43** [jgraph/drawio#3972]
* [ X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I would like to be able to define a "zoom range" in which Layers are visible/not visible.  In that way, smaller details in my diagram would disappear when zooming out.

**Describe the solution you'd like**
- Add an option to each layer in the Layers panel that allows the user to define a visible range (defaults to 0% to "max").
- When the zoom of the diagram is outside of the layer's range it is hidden.

**Describe alternatives you've considered**
NA

**Additional context**
I love draw.io -- I use it for stakeholder engagement, low level design, documentation, etc.  I think I could get 90% of my work done in draw.io alone which is nice because everything is one place.  However, the diagrams eventually get complicated and it would be nice to use the zoom feature to quickly change from a high level discussion to the lower level implementation details.

**Comment by tomer-ben-david** [comment]
This is super important I'm surprised no votes!!
