### ISSUE TITLE
Cannot change the radius of the corners of a rounded rectangle

### ISSUE THREAD

**Issue by yoflippo** [jgraph/drawio#398]
It is not possible the change the radius of the corners of a rounded rectangle to a specific value via the text editor (the yellow diamond is still operational). Any change from the default value (1) results in a normal rectangle.

**Comment by ashrafteleb** [comment]
You can do that by changing the "Arc Size" from the properties or "arcSize=##;" in the style

**Comment by bjtucker** [comment]
It seems that arcsize is still to the size of the shape. Is there any way to specify a specific arc radius that doesn't change as the shape is resized?

**Comment by saman** [comment]
@bjtucker , just check the `Abs. Arc Size` checkbox.

**Comment by hwinkel** [comment]
does it work for all shapes, seems the build in hexagon is not working this way, no Abs. Arc size, and is badly broken anyway for scaling

**Comment by anscarlett** [comment]
I know this is  an old topic but its the only thing that came up in my google search. 
I do not have a checkbox called Abs. arcSize in the Interface, or if i do, its not in an obvious place.

To manually add this, right click on a shape, Select Edit->Edit Style
Add the following to the style information.
```
absoluteArcSize=1;
```

**Comment by alderg** [comment]
<img width="229" alt="Screenshot 2024-04-26 at 09 37 21" src="https://github.com/jgraph/drawio/assets/921200/367493a9-f1c4-4f89-9c8d-f58efd8a1567">
