### ISSUE TITLE
Webapp doesn't display correctly

### ISSUE THREAD

**Issue by emmanboika** [jgraph/drawio#3982]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
The web application does not display my diagram correctly. I've updated the page several times but nothing changes.

**To Reproduce**

**Expected behavior**

**Screenshots**
![Capture d’écran de 2023-11-14 17-09-54](https://github.com/jgraph/drawio/assets/114389458/c96fece7-1498-42ae-8867-b09c9600b6b9)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.0

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux Elementary OS
 - Browser [e.g. chrome, safari] Google Chrome
 - Browser Version [e.g. 22] 119.0.6045.123

**Smartphone (please complete the following information):**

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-

**Additional context**

**Comment by davidjgraph** [comment]
This is a boundary case, we don't have the resources to investigate every rare issue, unfortunately.
