### ISSUE TITLE
History revisions lost

### ISSUE THREAD

**Issue by albcitibox** [jgraph/drawio#3983]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version x.y.z

**Desktop (please complete the following information):**
 - Browser Version [e.g. 22]

**Smartphone (please complete the following information):**

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-

**Additional context**

**Comment by albcitibox** [comment]
Hi , i have been working in a process flow during last two days and this morning the application gave me a sync error and when i have refreshed the flow all the updates i have done since Friday have disappeared and no revisions from friday. 
Something happened but no idea what can be done to recover the information
<img width="1518" alt="Captura de Pantalla 2023-11-15 a las 17 44 10" src="https://github.com/jgraph/drawio/assets/150945524/b5dc490d-3a33-4cc5-b4d4-d6893bed6448">
<img width="1518" alt="Captura de Pantalla 2023-11-15 a las 17 44 10" src="https://github.com/jgraph/drawio/assets/150945524/8cc07c05-b6a0-45c7-809d-b9f06eb30b4a">

**Comment by albcitibox** [comment]
what can i do to recover the information?

**Comment by AlexandrBezrukWRK** [comment]
v22.1.5

**Comment by davidjgraph** [comment]
We have pretty extensive debugging relating to this, there have been many reports. We have mechanisms in place to check whether a save has worked, we don't allow users to carry on endlessly writing into the ether.

Goggle has now admitted that there might be data loss (read as, there has) when using the desktop sync version, https://www.theverge.com/2023/11/27/23978591/google-drive-desktop-data-loss-bug-files-missing-investigation.

There are several threads with hundreds of users complaining about this:

https://support.google.com/drive/thread/245861992/drive-for-desktop-v84-0-0-0-84-0-4-0-sync-issue
https://support.google.com/drive/thread/245055606/google-drive-files-suddenly-disappeared-the-drive-literally-went-back-to-condition-in-may-2023?hl=en

I'm not saying it's definitely this, we need to collect your exact environment details, OS, browser and version, browser extensions, are you using the sync client. The original report in this thread contains nothing that is requested, it no use to us.

https://marker.io/blog/how-to-write-bug-report describes how to write a bug report.

**Comment by AlexandrBezrukWRK** [comment]
@alderg 
1. Browser: Google Chrome Version 119.0.6045.200 (Official build), (64 bit)
2. Addons for Google Chrome:
1) "Adblock Plus", ver. 3.21.1 (https://chromewebstore.google.com/detail/adblock-plus-%D0%B1%D0%B5%D1%81%D0%BF%D0%BB%D0%B0%D1%82%D0%BD%D1%8B%D0%B9-%D0%B1/cfhdojbkjhnklbpkdaibdccddilifddb)
2) "Google Документы офлайн" (Online documents), ver. 1.69.0 (https://chromewebstore.google.com/detail/google-%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B-%D0%BE%D1%84%D0%BB%D0%B0%D0%B9%D0%BD/ghbmnnjooekpmoecnnnilnnbdlolhkhi)
3) "Google Переводчик" (Translater), ver. 2.0.13 (https://chromewebstore.google.com/detail/google-%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4%D1%87%D0%B8%D0%BA/aapbdbdomjkkjkaonfhkkikfgjllcleb?pli=1)

3. Drawio online, ver. 22.1.5 from https://app.diagrams.net/
4. Save work files on Google Drive, online
5. File size (which lost data): 153.2 kB
6. OS: MS Windows 10 Pro, ver. 22H2 (build OS 19045.3693)

**Comment by alderg** [comment]
@AlexandrBezrukWRK ie. you are not running a sync client?

**Comment by AlexandrBezrukWRK** [comment]
> ie. you are not running a sync client?
@alderg no

**Comment by AlexandrBezrukWRK** [comment]
my wrk process like this:

1. login in to Google account in Chrome browser
2. open https://app.diagrams.net/
3. if it need, give access diagrams.net (if it ask)
4. do wrk online on https://app.diagrams.net/ (open, create, wrk, etc.)
5. if create new file in drawio: save it in only on Google Drive (in my, or shaired directory) 
6. see autosave results in UI https://app.diagrams.net/ by the all time of wrk
7. see result file on Google Drive if need to copy file or finde it fore sending
8. repit ...

**Comment by davidjgraph** [comment]
I would suggest to try working in a different chrome window with all the of the extensions disabled for some time and see if that makes any difference.
