### ISSUE TITLE
Incorrect horizontal timeline example

### ISSUE THREAD

**Issue by ginkel** [jgraph/drawio#3988]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Hi there,

the horizontal timeline example found at https://github.com/jgraph/drawio-diagrams/blob/dev/examples/timeline-infographic-shapes-horizontal.drawio unfortunately just contains what looks identical to the vertical timeline example.

Regards,
Thilo

**Comment by davidjgraph** [comment]
Thanks for the pointer. We use that link in blog posts, so we can't change its name.

**Comment by ginkel** [comment]
Hello @davidjgraph,

well, that's right as I discovered the file via the blog post. The text, however, is misleading as the blog post's text references a horizontal layout, but you end up at the vertical example.

Regards,
Thilo
