### ISSUE TITLE
Insert a new row in the list group

### ISSUE THREAD

**Issue by arulkumar4** [jgraph/drawio#3993]
Typically, when working with a "List," I would employ the "Insert Row Below" function found under the "Arrange" -> "Table" properties to add a new row.

However, I've noticed that this option is absent in the List group when attempting to insert a new row. 
Can we have a "Table" property for the "List group" too?

[Screenshot for reference](https://i.stack.imgur.com/wEqeF.png)

Web Applications Stack Exchange post: [How to insert a new row in the list group in draw.io](https://webapps.stackexchange.com/q/172911/124928)

**Comment by alderg** [comment]
Try [this](https://app.diagrams.net/#R7ZZNb9swDIZ%2FTY4b%2FJG06XF22%2B3QAkUzbLuqFm2zlUVDluekv36ULSdxjA7doRgKFAli8RUpkdQjI4s4rbZfjajLW5KgFlEgt4v4chFFYbQ844dTdl4JgvWgFAbloAUHYYPPMDp6tUUJjdcGyRIpi%2FVUzEhryOxEE8ZQN3XLScmJUIsCJmk4YZMJBTO3nyhtOajr1ZH3N8CiHHfmAoeZSozOXmhKIak7kuKrRZwaIjuMqm0KynVv2pfrF2b3iRnQ9jUB3x8hD55gh7%2Baq%2BQuTM5rWH%2Fyq%2FwWqvUFX4OwrQHpk7a7sRNNh5USmq0kJ203fiZgOytRyRuxo9Zl0liRPY1WUpLBZ%2FYXiqdCFnjaWH%2FQsYvOUamUFJl%2Bnzg%2Fd59J5Mat6Pcy0HDs3Vh2eCLdiu3E8UY0dsySlBJ1gw%2F7vCthCtQJWUuVl0pbjYn2VQ55hmd94oae4ChTmbuP24paLUH6OGEyH3bhLIWF5rGC3LWjqUWGurjprcs1K%2F4EwFjYvni04R4YvmpAFVizYxcfsPSI7aZmdwA2Cv1FLI9hHdEU%2FpIU%2B5UPHPHAo%2FQPWEUzrFLDm0TBY9tY4idJpDlhpajdkAu3KNQ932ehCzd70nvUJRi0J%2Bxo6uE8abhrLPJ9%2FuLlCqUclpydhFfufYeWLBGH56q%2FtiUHgu5P2worDhTVhNr2HVwl%2FOWepsHn1WLFJaVshwebv87d2JQ0VySwP15gRDtwmCZdiRY2nIZbu%2BNX6t%2BJND5Tl8VQbj98OAb6VXi9%2FG6YM%2Bchi18JWfxWjMUzxi5FjQ%2Btw0xk7l3Pp6mwQSeg%2FqDtPdN29r9pW85o%2B8FNZNxUW7n9LP%2BAoeYDs%2FeM2cXbYcbm4b9eP3f0lzm%2B%2BgM%3D) implementation.

**Comment by arulkumar4** [comment]
@alderg Certainly! I have the capability to add a new row to the provided URL. 
Is the "List group" located in the left sidebar? or is it slated for addition in an upcoming release?

**Comment by egrimate** [comment]
Done
