### ISSUE TITLE
Font size should be able to be set once for a diagram

### ISSUE THREAD

**Issue by JLCarveth** [jgraph/drawio#4000]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I am always frustrated when editing text on an arrow connection, within a shape, or directly on the grid. Tee app always defaults to 12pt font, which is tiny (but I'm not here to complain about the default font size). What I think should be the standard behaviour is if I change the font size, any subsequent text added to the diagram should be the same font size that I initially selected. That way I won't have to constantly change the font sizes when labeling my diagrams. 

**Describe the solution you'd like**
Persist the font size I select, and use it for all new text elements in a diagram.

**Describe alternatives you've considered**
The alternative is everything continuously defaults to 12pt, which is not ideal.

**Comment by alderg** [comment]
Try https://github.com/jgraph/drawio/discussions/3312

**Comment by JLCarveth** [comment]
Perfect, thank you!
