### ISSUE TITLE
As gradually decreasing the font size of a latex formula, the subscript and superscript size does not change.

### ISSUE THREAD

**Issue by douseful** [jgraph/drawio#4009]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.
**Screenshots**

<img width="708" alt="image" src="https://github.com/jgraph/drawio/assets/52767905/f7d58a50-7eec-4e1e-b9e4-8f3e28eeca60">

- draw.io version 22.1.2

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [Desktop]
 - Version [22.1.2]

**Comment by douseful** [comment]
it's 03/20/2024 now. This issue has not yet been resolved

**Comment by davidjgraph** [comment]
A few things:

1) It's 20.03.2024.
2) Don't be a dickhead.
