### ISSUE TITLE
Name of shapes

### ISSUE THREAD

**Issue by Bruneux** [jgraph/drawio#401]
Hi
Say you have received a diagram and want to know the name of certain shapes. Is there a way to know the name of the shapes in the diagram?
Thanks

**Comment by davidjgraph** [comment]
Duplicate of https://groups.google.com/forum/#!topic/drawio/oPOMSQD5TPM

**Comment by Bruneux** [comment]
Oh sorry, I thought the group was for questions / answers while github was for submitting a bug.

**Comment by davidjgraph** [comment]
Github is for submitting bugs, but I don't see a bug report here.
