### ISSUE TITLE
SVG Export in browser is not working, Ssite can’t be reached.

### ISSUE THREAD

**Issue by zboras37** [jgraph/drawio#4017]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
SVG Export does not work on  browser version. Page says: This site can’t be reached (ERR_HTTP2_PROTOCOL_ERROR)

**To Reproduce**

1. Open the diagram to be exported as svg
2. Click File
3. Click Export as
4. Choose SVG...
5. Make Text Settings: Convert labels to SVG
6. Click Save

**Expected behavior**
The exported SVG File should be downloaded.

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/64359071/a459daaa-7c61-40b1-ac69-c7c58eff640e)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.5 (On Browser)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Browser Version 119.0.6045.200 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: NA
 - OS: NA
 - Browser NA
 - Version NA

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-yes

**Additional context**
NA

**Comment by davidjgraph** [comment]
Closing as network issue, we can't debug every single such case.
