### ISSUE TITLE
Support for crossing wires conventions to make explicit that there is no join

### ISSUE THREAD

**Issue by masumshaikh** [jgraph/drawio#4019]
Could you please introduce an option whereby, whenever we have two lines crossing in a diagram, one of them behaves as either B or C, shown below?

![image](https://github.com/jgraph/drawio/assets/6390012/c1a8636c-25c8-4c4e-98e3-ae903f2e9415)

Thank you.

**Comment by davidjgraph** [comment]
Search first before posting.
