### ISSUE TITLE
IBM Blockchian Icons Update

### ISSUE THREAD

**Issue by ggdaly** [jgraph/drawio#402]
Can you please add all these Icons in the Zip file attached and do the following:
 
Replace Current Ledger with new file
Replace Current Membership with new file
Replace Current Smart Contract with new file
 
Attached in the zip file also is BLOCKCHAIN TEMPLATE can we add this to the NETWORKS section in Draw.io???
[Blockchain-Draw.io.zip](https://github.com/jgraph/drawio/files/2992456/Blockchain-Draw.io.zip)

**Comment by ggdaly** [comment]
@davidjgraph David is it possible to add the Blockchian architecture to the "NETWORK" section as a fully baked architecture? 
[Blockchain Architecture.zip](https://github.com/jgraph/drawio/files/3094736/Blockchain.Architecture.zip)

**Comment by kutya** [comment]
Ok, it is currently in progress.

**Comment by kutya** [comment]
@ggdaly IoT Devices in the template is non-existent. To which group should I put it?

**Comment by kutya** [comment]
Completed

**Comment by ggdaly** [comment]
@kutya Mate here are the icons thanks
[Blockchain Architecture 2.zip](https://github.com/jgraph/drawio/files/3098263/Blockchain.Architecture.2.zip)
