### ISSUE TITLE
Font Mismatch Inserting Diagram into Google Slides 

### ISSUE THREAD

**Issue by Phrogz** [jgraph/drawio#4020]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Inserting a diagram into Google Slides where the diagram uses a custom Google Font results in an image with an incorrect font displayed. If it matters, the Google Slides presentation is also using the same custom Google Font.

**To Reproduce**
1. Create a diagram with a shape with text inside.
2. Set the font to "Bebas Neue Regular" (a Google font)
4. Save the diagram to Google Drive
5. Create a Google Slides deck, with the Diagrams.net add-on installed.
6. Choose "Insert Diagram..." for the add-on, and insert your previously-saved diagram.

**Expected behavior**
The image shown in the Google slide should match the font shown in diagrams.net  
![diagram as shown during editing](https://github.com/jgraph/drawio/assets/14778/6a38c114-fafe-417c-a97a-150a11d1a302)

**Actual behavior**
The image in Slides is using a different font. I'm unsure if this is a Theme font for the Slide, or a default font:  
![actual result](https://github.com/jgraph/drawio/assets/14778/b2e00f18-89cd-426d-bf12-96219475afd0)

- draw.io version v22.1.5

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome v119

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- no; need to be logged into Google

**Comment by moscii** [comment]
Same problem. The font of the kanji in the generated diagram is a Chinese font instead of a Japanese font.

**app.diagrams.net**
<img width="477" alt="Screenshot 2024-01-12 at 10 37 05" src="https://github.com/jgraph/drawio/assets/10438213/a8b440f0-a2eb-4c9f-8388-9c696977bc99">

**diagrams for Docs**
<img width="406" alt="Screenshot 2024-01-12 at 10 36 42" src="https://github.com/jgraph/drawio/assets/10438213/41121699-8027-4b26-ac73-809018812f17">

**Comment by davidjgraph** [comment]
Please attach the example diagram to test with.

**Comment by moscii** [comment]
Hi David,
I'll share a sample diagram to you.
![plantuml version drawio](https://github.com/jgraph/drawio/assets/10438213/6196e102-c202-45f5-b917-afd3041f30d4)

The following code is embedded in the diagram.
```puml
@startuml
listfonts 新
@enduml
```

Thanks!

**Comment by davidjgraph** [comment]
This relates to PlantUML?

**Comment by moscii** [comment]
I am embedding plantuml into a diagram on app.diagrams.net.
Arrange > Insert > Advanced > PlantUML
<img width="686" alt="Screenshot 2024-03-15 at 2 25 59" src="https://github.com/jgraph/drawio/assets/10438213/0e762a08-72c3-43c8-8255-ad665c1b2bcf">

**Comment by davidjgraph** [comment]
OK, that has nothing to do with the original posting. Please don't hijacking issues, create a new one.

**Comment by moscii** [comment]
OK, I understand.
