### ISSUE TITLE
Insert page as object in another page

### ISSUE THREAD

**Issue by sahil48** [jgraph/drawio#4023]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I reuse the same process in several diagrams. I would like to show it in several other pages. When someone is following a procedure, it is difficult to switch between multiple pages, compared to having everything in one page that can be read through and followed from start to finish.

**Describe the solution you'd like**
I would like to be able to insert a page in the diagram with a subprocess as an object in another page. The object would render with all the shapes in the page, accept connection points, but not be editable. When the subprocess diagram is updated, the rendered diagram is also updated to be current. The page object will have a link to quickly navigate to the other page.

Could also consider allowing the page object to be collapsible, but not required for my use case. Could consider inserting a page from another diagram in a different diagram in similar fashion, but not required for my use case.

**Describe alternatives you've considered**
Subpages - It is difficult to relate subprocesses or parts of a to other objects in a diagram if they are in a separate page.
Copy-Paste, or make the subprocess a library object - It is difficult to ensure that if a subprocess changes, then it stays up to date.

**Additional context**
I think the above has enough detail and I do not have any additional context.

**Comment by qu1rk3y** [comment]
+1

**Comment by davidjgraph** [comment]
+1

**Comment by davidjgraph** [comment]
+1

**Comment by davidjgraph** [comment]
+1

**Comment by davidjgraph** [comment]
+1

**Comment by sahil48** [comment]
I don't really get what all the +1's are about. Did I do something wrong in making this request?

**Comment by davidjgraph** [comment]
No, but background pages already exist and they sound very like the thing you're looking for. https://www.drawio.com/doc/faq/background-diagram

**Comment by sahil48** [comment]
Thanks for the link. It's very close, except must be applied to the entire page of the diagram. I'm looking to have be able to be able set a rectangle shape's background image to a page of the diagram. This way, the diagrams in multiple pages can be pieced together on same page and related.

**Comment by davidjgraph** [comment]
OK, I follow you. But, unfortunately, we cannot technically implement that with the data model we use.
