### ISSUE TITLE
Features for version control

### ISSUE THREAD

**Issue by Bambofy** [jgraph/drawio#4024]
* [X ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the solution you'd like**
Libreoffice provides a version control system (https://help.libreoffice.org/latest/en-US/text/shared/guide/redlining_versions.html) which is really helpful to keep track of changes and new versions of diagrams and documents made with their tools.

**Comment by davidjgraph** [comment]
This is an issue tracker for feature requests and bugs. You have simply made a statement about Libreoffice.
