### ISSUE TITLE
Make default drawio libraries appear at the top before custom libraries

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#4027]
"Currently, default drawio libraries appear at the bottom after the custom libraries. Is it possible to make them appear at the top?"

Asked in DID 10198

**Comment by davidjgraph** [comment]
`"appendCustomLibraries": true`

**Comment by ktalapaneninvda** [comment]
Hi @davidjgraph ,
Is this available in drawio Version: 11.3.5 ?
Our confluence is currently on 7.19.17 LTS.

**Comment by davidjgraph** [comment]
No, it goes into the core release first and will go into the next 11.x sequence release, probably numbered 11.3.6.

**Comment by ktalapaneninvda** [comment]
Got it. Thank you. Please let me know once 11.3.6 is released.

**Comment by davidjgraph** [comment]
In core 22.1.8 release.
