### ISSUE TITLE
Apache cann't proxy pass because of '?' in URL

### ISSUE THREAD

**Issue by longnguyen2306** [jgraph/drawio#403]
I used your Dockerfile to deploy drawio on my server and try to use Apache2 as Reverse Proxy. Following is my config:

```
<VirtualHost *:443>
		...
        ProxyPass /draw/ http://localhost:8888/draw/
        ProxyPassReverse /draw/ http://localhost:8888/draw/

        ProxyPass / http://localhost:8888/draw/?local=1/
        ProxyPassReverse / http://localhost:8888/draw/?local=1/
		...

</VirtualHost>
```

Basicly I can only reach the site with https://drawio.example.com/draw/?local=1/

Trying to reach the site with https://drawio.example.com will result a 404 with /draw/%253Flocal=1/ not found. I think there's a problem with the encoding of the '?' character and I don't know how to fix it

**Comment by davidjgraph** [comment]
The docker functionality was community submitted, we don't maintain it. https://hub.docker.com/r/fjudith/draw.io/ is rather better maintained, could you try if that works please?

**Comment by longnguyen2306** [comment]
Thank you, that works like a charm.
