### ISSUE TITLE
Support adding custom templates via Arrange > Insert > Templates in the editor

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#4033]
"We have a few custom templates that are available under the Custom Templates section when creating a new diagram in a page. Now, we have users who would like to add those custom templates to existing diagrams. When editing a diagram, there is the option Arrenge → Insert → Templates… however, we are only offered with generic templates, we can’t see the same custom templates that we have as when creating a new diagram.
Is there a way we can add our custom templates to an existing diagram?"

Asked in DID 10271

**Comment by m-mohamedin** [comment]
Will be added to the next release

**Comment by davidjgraph** [comment]
In 11.3.7 (conf 7.x) and 12.1.6 (conf 8.x)
