### ISSUE TITLE
Deleted scratchpad items are still searchable

### ISSUE THREAD

**Issue by diomidov** [jgraph/drawio#404]
1. Place a rectangle.
2. Drag it to scratchpad.
3. Edit the scratchpad.
4. Rename the rectangle to "Foo".
5. Save.
6. Edit the scratchpad again.
7. Delete Foo.
8. Save.
9. Type "Foo" in the searchbar.

What I expected to happen: no search results.

What actually happened: it found my deleted rectangle.

![image](https://user-images.githubusercontent.com/22151995/54870958-98bba680-4d83-11e9-886d-33f4cefb82e0.png)

**Comment by alderg** [comment]
This is a known issue. It will disappear when you reload the page.
