### ISSUE TITLE
 Be able to switch back to last recently viewed Page via either Shortcut, Hotkey, or "Back button" on the GUI

### ISSUE THREAD

**Issue by jatrindo** [jgraph/drawio#4043]
* [ X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I create diagrams (using the offline version of drawio) with plenty of nodes that link to other pages in the diagram, as a sort of "navigate to page X, navigate to page Y" functionality. It would be extremely convenient for me if there were some shortcut or button on the GUI that would let me visit the page I viewed last.

**Describe the solution you'd like**
Being able to just go back a the most recently viewed page would be extremely convenient to eliminate the searching process. Keeping track of the most recently viewed page would be plenty enough for me (although having a history of pages to navigate back through would be awesome!)

**Describe alternatives you've considered**
Currently I have to re-find the page that I want by remembering the name of the page I was on and manually searching the scrollable bar at the bottom of the application. However, this doesn't scale all that well when pages start numbering around 20 or so for me and I've forgotten the names of the pages I was on. A number of the pages I have are also a bit heavy to load, which slows down this manual search process even further.

I am also aware that `cmd/ctrl + shift + page up/down` exists. However, this by itself does not quite solve my issue because of the heavy-to-load pages mentioned before, which prevents me from flitting around page-to-page quickly enough to my liking.

**Additional context**
![Screenshot 2023-12-15 061539](https://github.com/jgraph/drawio/assets/67666868/4a9519c8-70d3-4311-b3f0-6e8aa99e091d)
![Screenshot 2023-12-15 061041](https://github.com/jgraph/drawio/assets/67666868/93d2fcaf-0c29-4efd-b1d3-dc40d39b2f0d)

**Comment by jatrindo** [comment]
Also, if such a feature doesn't exist, I would be willing to create a PR for it!

**Comment by alderg** [comment]
Try undo.

**Comment by jatrindo** [comment]
So, that works in the case where I don't make edits to sheets as I navigate around, which I failed to mention that in my use case I do.

I use drawio for note taking (I find it better to have some concepts laid out in a diagram), so a common workflow for me is to:
- Hop to some page A and make some changes
- Hop to to a page B and make more changes
- Then return to page A to make some changes (b/c, for example. I found a better way to lay things out while I was working on B)

In order to visit page A again via undo, I would first have to undo the current work on page B, which wouldn't work for me.

It would be much more convenient if there were a keyboard shortcut or GUI button I could use to specifically go back to the last page I visited, while also preserving the edits I've made to the current page thus far. It would be even more convenient if I could also do so beyond just the last page I've visited, up to some _n_ visited pages back (so a means of navigating a history of visited pages).

**Comment by Peeeet** [comment]
If you are already navigating to these pages by clicking a node that you created that has a link in it, why not have that link also hide a group of buttons on the target page you are going to and show only a button that links back to the page the link was on?

That might even work though multiple traversals of pages until you pass through the same page from two different directions...
