### ISSUE TITLE
Error opening .drawio from Github in app.diagrams.net - Error loading file Not a diagram file

### ISSUE THREAD

**Issue by Brandon-Valley** [jgraph/drawio#4045]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
I have some .drawio files that when opening from github through the app.diagrams.net UI, result in `Error loading file
Not a diagram file`, but some other .drawio files work as expected in the same Github Repo. All .drawio files were created by saving from app.diagrams.net to Github

However, I am able to open the problematic files by using the "Raw" Github view and opening from URL through the app.diagrams.net UI.

**To Reproduce**

Example .drawio file that throws `Error loading file Not a diagram file` from app.diagrams.net > File > Open from > Github... > Select File > REPO_NAME > hotel_booking.drawio
- https://github.com/Brandon-Valley/draw_io_diagrams/blob/master/hotel_booking.drawio

However, the same file **CAN** be opened in app.diagrams.net by: File > Open From > URL... > https://raw.githubusercontent.com/Brandon-Valley/draw_io_diagrams/master/hotel_booking.drawio

**Expected behavior**

Example .drawio file that opens as expected from app.diagrams.net > File > Open from > Github... > Select File > REPO_NAME > Spotify_Top_K.drawio
- https://github.com/Brandon-Valley/draw_io_diagrams/blob/master/Spotify_Top_K.drawio

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.8 - app.diagrams.net - Windows 10 - Firefox

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**

I love this tool and I am grateful for all the work that has gone into it, any and all assistance is greatly appreciated!

**Comment by alderg** [comment]
Works for me: https://app.diagrams.net/#Uhttps://raw.githubusercontent.com/Brandon-Valley/draw_io_diagrams/master/hotel_booking.drawio

**Comment by Brandon-Valley** [comment]
Yes, opening from the raw URL works, but opening from app.diagrams.net > File > Open from > Github... > Select File > REPO_NAME > hotel_booking.drawio does not work, my goal is to avoid the "raw" github work-around

Thanks!

**Comment by davidjgraph** [comment]
Fix in 22.1.12.

**Comment by Brandon-Valley** [comment]
Just tested on my end with v22.1.16 and it works! @davidjgraph @alderg Thank you so much!
