### ISSUE TITLE
[FR] Paste where mouse was last clicked (or is pointing)

### ISSUE THREAD

**Issue by Peeeet** [jgraph/drawio#4053]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Currently when you copy-paste an object, it just appears next to the copied one.

**Describe the solution you'd like**
It would be very useful for the pasted object to either appear where the mouse last clicked - or (whichever is easier to implement) where the mouse cursor is currently hovering.

**Describe alternatives you've considered**
Currently implemented: It is handy to be able to hold control and drag an object somewhere to create a copy, but sometimes the click grabs a different object under or nearby the intended object and you end up dragging a copy of one or many other unintended items.  It would be a great time-saver to be able to just click and press CTRL-V to quickly place a bunch of objects instead of having to grab the object each time - especially very small objects over a larger area (AKA lots of zooming in and out or lot's of misclicks due to tiny target)

**Comment by anugoyal998** [comment]
I would like to work on it.
Please assign it to me.

**Comment by alderg** [comment]
Try Right Click, Paste Here:
<img width="237" alt="Screenshot 2023-12-22 at 09 30 15" src="https://github.com/jgraph/drawio/assets/921200/e63fe3fd-7ada-4eb2-b75f-beffaf3790f5">

**Comment by Peeeet** [comment]
Okay cool, can we get a keyboard shortcut for that?  Like `Control (Command) + Shift + V` for example...
