### ISSUE TITLE
How to add the custom css to the editor of the drawio 

### ISSUE THREAD

**Issue by chandaniKhanesha59** [jgraph/drawio#4054]
**-Below is my code that I'm trying to implement drawio in my react application but I've to change the css but I'm not able to do ir**
  
  <DrawIoEmbed
        ref={drawioRef}
        urlParameters={{
          spin: false,
          libraries: true,
          saveAndExit: true,
        }}
        onExport={(data) => {
          console.log(data, 'onExport');
          if (drawioRef.current) {
            drawioRef.current.draft({
              xml: data.xml,
              name: 'Helllllo',
              editKey: '',
              discardKey: '',
              ignore: false,
            });
 console.log(img, 'img');
          }
          setxml(data.xml);
          setimg(data.data);
        }}
        // onExport={(data) => console.log(data, 'onExport')}
        onLoad={(data) => {
          console.log(data, 'data');
        }}
        onSave={(data) => {
          console.log(data, 'onSave');
        }}
      />

**Comment by Peeeet** [comment]
You can add custom CSS to the editor UI in the "Configuration" dialog under the "Extras" menu in the DrawIO UI:
![image](https://github.com/jgraph/drawio/assets/5926263/82eeb4c9-4517-41ae-a342-3c4e1ea57a1a)

**Comment by davidjgraph** [comment]
This is an exceptionally low quality issue. As a software developer, you should understand this is completely unacceptable. If you repeat this you will be banned.
