### ISSUE TITLE
Shape picker interferes with drawing on iPad

### ISSUE THREAD

**Issue by BradAF** [jgraph/drawio#4057]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
When using Freehand to draw on the iPad with an Apple Pencil, inputs like dotting i's or crossing t's are interpreted as double clicks and the shape picker menu appears interrupting text or causing unexpected lines to appear.

**To Reproduce**
1. Create a new page in either Simple or Sketch modes (other modes not tested).
2. Click on Freehand tool
3. Attempt to write a a sentence like 'This is a test'.
4. New shape picker appears, interrupting writing.

**Expected behavior**
I would expect in Freehand mode that the shape picker does not appear at all.

**Screenshots**
<img width="1590" alt="image" src="https://github.com/jgraph/drawio/assets/11336928/f83fe6a8-0ac7-4f8c-ae96-f24d947dbcae">
<img width="1590" alt="image" src="https://github.com/jgraph/drawio/assets/11336928/02bf9def-3934-411b-8991-9ded806300c7">

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version v22.1.11

**Tablet (please complete the following information):**
 - Device: iPad Pro M1
 - OS: v17.1.2
 - Browser: stock browser, safari
 - Version stock browser

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- No

**Additional context**
Added app to home screen per instructions at https://drawio-app.com/blog/use-draw-io-on-a-tablet/

**Comment by alderg** [comment]
Fixed in v24.4.5.
