### ISSUE TITLE
Inconsistent "read only" status div appearance

### ISSUE THREAD

**Issue by FarSeeing** [jgraph/drawio#4058]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
The "read only" `div` in the status container has at least 3 different vaiants, one of which has a malformed `title`

**To Reproduce**
- [`src/main/webapp/js/diagramly/EditorUi.js`](https://github.com/jgraph/drawio/blob/dev/src/main/webapp/js/diagramly/EditorUi.js#L2950) - malformed `title` because of the `span` instead of `div` (see screenshot below)
```javascript
this.editor.setStatus('<span class="geStatusAlert">' +
	mxUtils.htmlEntities(mxResources.get('readOnly')) + '</span>');
```
- [`src/main/webapp/js/diagramly/ElectronApp.js`](https://github.com/jgraph/drawio/blob/dev/src/main/webapp/js/diagramly/ElectronApp.js#L1221) - no `title`
```javascript
this.editor.setStatus('<div class="geStatusAlert">' + mxResources.get('readOnly') + '</div>');
```
- [src/main/webapp/js/diagramly/DrawioFileSync.js](https://github.com/jgraph/drawio/blob/dev/src/main/webapp/js/diagramly/DrawioFileSync.js#L592) - `title` set
```javascript
(!this.file.isEditable() ? '<div class="geStatusBox" title="' +
	mxUtils.htmlEntities(mxResources.get('readOnly')) + '">' +
	mxUtils.htmlEntities(mxResources.get('readOnly')) + '</div>' : '') +
```

**Expected behavior**

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/559569/a80de132-ae7c-4e46-a2bd-0de82d29e765)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.11

**Desktop (please complete the following information):**
 - OS: any
 - Browser any
 - Browser Version any

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Browser any
 - Version any

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**

**Comment by davidjgraph** [comment]
Fix 24.5.1
