### ISSUE TITLE
Add support for custom fonts in exported SVG images

### ISSUE THREAD

**Issue by m-mohamedin** [jgraph/drawio#4059]
When a diagram with custom fonts is exported to SVG, only the font name is exported but the font URL/css is not included. The result is the font is different in the exported SVG.

Related to https://drawio.atlassian.net/browse/DID-10349

**Comment by woodwm** [comment]
The same applies exporting to PDF. I custon fonts as Google Font. When I export to PDF, the font reverts to Time New Roman.

**Comment by m-mohamedin** [comment]
> The same applies exporting to PDF. I custon font as a Google Font. When I export to PDF, the font reverts to Time New Roman. The Google font shows correctly on the web, but not in the exported PDF.

This shouldn't happen in PDF unless the font is hosted in a private URL. I just tested Google Fonts and it works.
Please share the steps or the diagram with the issue

**Comment by woodwm** [comment]
Hi, I think it is my bad. I guess it is because my browser blocks the google font. 

Is it possible to support different weight in google font, such as Lato:wght@300? The regular is Lato:wght@400? https://fonts.google.com/specimen/Lato

**Comment by alderg** [comment]
To support different font weights, enter the Google Font name and the following Font URL under Web Fonts in the Custom Font dialog:

`https://fonts.googleapis.com/css2?family=Lato:wght@300`

<img width="461" alt="Screenshot 2024-01-03 at 08 05 19" src="https://github.com/jgraph/drawio/assets/921200/05ee237f-3f65-4506-899a-6e7baf42eb73">

**Comment by woodwm** [comment]
@alderg Thanks a lot. That is smart.
