### ISSUE TITLE
Any change is not saving.

### ISSUE THREAD

**Issue by KgBrother** [jgraph/drawio#4064]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Everytime i do a change it never saves the changes to file. It even says "Unsaved changes. Click here to save. (Timeout)"

I tried Chrome, Chrome icognito, and Microsoft edge

**To Reproduce**
1. Open a file and make any change. 
2. wait for it to auto save
3. It wont.

**Expected behavior**

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/154865718/aae8d4af-b233-452c-94a2-128d5d443dee)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.11

 - OS: Windows 11
 - Browser Chrome & Microsoft Edge
 - Browser Version [e.g. 22]

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-yes

**Additional context**
Ive also had a friend try it and its not working for him either. The file is trying to save toa  google drive file.

**Comment by davidjgraph** [comment]
Any browser extensions? Any errors in the browser console?

**Comment by iamamanprajapati** [comment]
Same issue with me

**Comment by davidjgraph** [comment]
The same question will be met with the same answer....

**Comment by iamamanprajapati** [comment]
I have used incognito mode but still not working
