### ISSUE TITLE
Feature request : Vertical arrangement of CJK characters

### ISSUE THREAD

**Issue by lbcmiao** [jgraph/drawio#4068]
version: diagrams.net 20.6.2 ,
os: windows 10 1809 x86_64.

In my view, the "vertical button" should be divided into two button : "CJK vertical" and "English vertical".
Because Chinese/Japanese/Korean have different vertical typesetting habits. And vertical in draw.io cannot make a corrent effect in Chinese/Japanese/Korean.

This is the effect in draw.io
All characters follow the English vertical typesetting habit.
[![zXYxsJ.png](https://s1.ax1x.com/2022/12/22/zXYxsJ.png)](https://imgse.com/i/zXYxsJ)

And this is the corrent vertical effect in Chinese/Japanese/Korean. 
In Chinese/Japanese/Korean articles, English characters should also follow the Chinese/Japanese/Korean typesetting habit.
[![zXYvM4.png](https://s1.ax1x.com/2022/12/22/zXYvM4.png)](https://imgse.com/i/zXYvM4)
 
Can you get it?

**Comment by GeorgeHu6** [comment]
neew this feature

**Comment by davidjgraph** [comment]
Test code in 22.1.18

**Comment by davidjgraph** [comment]
In 24.0.0, thanks for the report.
