### ISSUE TITLE
even with offline=1&stealth=1 draw.io is trying to reach out to Internet

### ISSUE THREAD

**Issue by whatleyjt** [jgraph/drawio#407]
I have downloaded, built, and deployed the latest as draw.war in Tomcat on a system that is not connected to the Internet and am trying to use the app from other systems that are not on the Internet, but the app fails to work properly because even with ?offline=1&stealth=1&local=1 the app tried to reach out to fonts.googleapis.com , js.pusher.com, and rt.draw.io

I am trying to get draw.io to work where the server hosting the app and the client workstation using the app(firefox) are both not connected to the Internet.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
