### ISSUE TITLE
Ability to select objects that are under the top one

### ISSUE THREAD

**Issue by rezanid** [jgraph/drawio#4070]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When a diagram has several items that are put on top of each other (very common in software diagrams e.g. UML and ArchiMate) it is frustrating to to try to select an object that is not the top one. One has to reshuffle the objects, or move them temporarily just to be able to select and change another one that is under. 

**Describe the solution you'd like**
One technique that I have seen some vector drawing software use is switching between objects if the user continues clicking without changing the mouse position.
Imagine there are three object on top of each other. Object 1 is on top of 2 and object 2 is on top of 3. When user click on object 1 on a position that is also relevant to object 2 and 3, by default the object 1 is selected. If user clicks another time without moving the mouse pointer, then object 2 is selected and then object 3.

**Describe alternatives you've considered**
Another alternative (though I haven't seen it in another app) is to let user select among different objects, if the user clicks and hold for a few seconds. In other words, in above scenario, when user clicks on object 1 and continues holding the button for a few seconds a context menu could display a list of all the relevant objects for selection. When user hovers the mouse over an object name, it can be highlighted. If user then clicks on the object name, the object will be selected and context menu would disappear.

**Additional context**
I think that the first solution would be easier to implement and having personally worked with it (I wish I remember which app, I guess Microsoft Expression Design) I think it's pretty natural and easy from user perspective.

**Comment by alderg** [comment]
Try Alt+Click?

**Comment by alderg** [comment]
Try Alt+Shift+Drag with the object selected.

**Comment by nemomode7** [comment]
I'd suggest double click as default instead of Alt+Click. Also this workaround doesn't allow to edit content of selected shape. So, for now its: (Alt+Click to) select, then (Alt+Shift+Mouse to) drag it out, then edit it, then drag it back. Many actions for something simple.

**Comment by alderg** [comment]
@nemomode7 Alt+Click and start typing?

**Comment by nemomode7** [comment]
> @nemomode7 Alt+Click and start typing?
Yes, that works for an empty shape. If the shape already had some text in it, it will be lost.

**Comment by alderg** [comment]
Alt+Click and Enter?

**Comment by ThomasOsinga** [comment]
All quite tedious, but it seems to work!

**Comment by TobywL1** [comment]
I thought I was going crazy, as I was facing the same problem. Alt + Click does indeed work and allows you to select the object. There must be a better way round this?
