### ISSUE TITLE
Can't open VSDX files with desktop version 22.1.11

### ISSUE THREAD

**Issue by 007me** [jgraph/drawio#4072]
Hi, 
When trying to open VSDX files on desktop version 22.1.11 the opening GIF is displayed forever and the file can't be open.
I tried with double click on VSDX file and choosing to open with  Draw.io.
I also tried importing it from within Draw.io.
Same response.
![image](https://github.com/jgraph/drawio/assets/4060022/9e5ef631-be2c-46c5-9339-aebe536998e1)

**Comment by alderg** [comment]
This seems to be specific to your VSDX file. Please attach the file so we can check.

**Comment by 007me** [comment]
This is happening with every VSDX file. Attaching one.
[amisragas-sw-map-22apr2018.zip](https://github.com/jgraph/drawio/files/13776795/amisragas-sw-map-22apr2018.zip)

**Comment by davidjgraph** [comment]
Try desktop 22.1.15

**Comment by 007me** [comment]
That worked! Thanks!
