### ISSUE TITLE
Release 22.1.12 broke viewer.min.js and viewer-static.min.js full screen mode

### ISSUE THREAD

**Issue by pvlasov** [jgraph/drawio#4075]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Release 22.1.12 broke viewer.min.js and viewer-static.min.js full screen mode - it shows an alert "mxSettings is not defined" and then only the background grey is shown. Everything worked fine yesterday.

**To Reproduce**
1. Go to https://architecture.models.nasdanika.org/demo/internet-banking-system/index.html
2. Click on "Fullscreen" button on the diagram

**Expected behavior**
As it was before - https://docs.nasdanika.org/demo-drawio-map/ - this site points to an old version of viewer-static.js

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.12 in Chrome

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Comment by davidjgraph** [comment]
Thanks, yes, we're aware.

**Comment by davidjgraph** [comment]
Fix in 22.1.14
