### ISSUE TITLE
Integrate with gitea

### ISSUE THREAD

**Issue by rickywu** [jgraph/drawio#408]
Since integrate with gitlab is difficult but how about support gitea https://github.com/go-gitea/gitea
It make sense because someone use private git repository service.

And gitea support OAuth2 API and also support push with API
https://try.gitea.io/api/swagger#/repository

**Comment by davidjgraph** [comment]
Happy to review PR that adds the functionality.

**Comment by rickywu** [comment]
@davidjgraph Any way to run server-side code seperately and hot-loading the client-side source 
so that I can implement much more easy

**Comment by davidjgraph** [comment]
You don't need the server-side code when integrating draw. https://github.com/jgraph/drawio-html5

**Comment by jearton** [comment]
Is there any solution?
