### ISSUE TITLE
Kubernetes Icons are all blue squares

### ISSUE THREAD

**Issue by SimonTheLeg** [jgraph/drawio#4082]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
For me all Kubernetes Icons are now the same blue square, both in the library on the left as well as when dragging them onto the canvas. Issue occurs both on Firefox as well as Chrome. Other shapes work just fine.

![grafik](https://github.com/jgraph/drawio/assets/20774623/c4788cc7-e8e3-46bf-868e-f88f58315d94)

**To Reproduce**
1. Under `+ More Shapes` activate Kubernetes (Note: in the pop up the shapes seem to look fine)
2. Expand the Kubernetes section => all shapes are blue squares
3. Drag any of the shapes onto the canvas => shape is a blue square as well

**Expected behavior**
Normal Icons should be displayed

**Screenshots**
see above.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version v22.1.16

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox 121.0
 - Browser Chrome 116.0

**Additional context**
The icons have been updated 2 weeks ago in https://github.com/jgraph/drawio/issues/3699, maybe this has something to do with it.

**Comment by davidjgraph** [comment]
I cannot repeat this. Any errors in the browser console?

**Comment by SimonTheLeg** [comment]
Browser console does not contain any errors. After system reboot, I am no longer able to reproduce this. Everything works now correctly again in both browser.

Maybe it was just a strange cacheing error. Thanks for the swift response :)
