### ISSUE TITLE
Overlays not being drawn on image/PDF exports.

### ISSUE THREAD

**Issue by gitgitwhat** [jgraph/drawio#4083]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Cell overlays (`mxCellOverlay`), such as tooltips, added via `addCellOverlay` do not get exported onto PNG/JPG/PDF/etc.

**To Reproduce**
-Enable tooltip plugin.
-Add tooltip to an object.
-Export diagram to PNG.
-Observe that tooltip icon is not shown on image.

**Expected behavior**
All drawing elements should be exported onto static formats.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.16

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome/Vivaldi/Firefox
 - Browser Version: latest

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
yes

**Additional context**

**Comment by davidjgraph** [comment]
That is the correct behaviour.

**Comment by gitgitwhat** [comment]
Can you make it an optional behavior?

**Comment by davidjgraph** [comment]
No, that's a lot of work to change and maintain it.
