### ISSUE TITLE
When editing the text of any shape and NOT clicking inside the canvas auto-save is not triggered.

### ISSUE THREAD

**Issue by YaninaLeanIX** [jgraph/drawio#4084]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**

When editing the text of any shape and clicking NOT inside the canvas, but e.g. on a menu in the top, auto-save is not triggered.
https://github.com/jgraph/drawio/assets/87121494/032b51c2-8736-48f6-b65d-21551161016e

**To Reproduce**
1. Add a Shape with a Text
2. Click Save (do not Click somewhere on the Canvas)
3. The Text is not Saved
4. If you click somewhere on the Canvas - then the Text is Saved

A video of the behavior is attached.

**Expected behavior**
It should be possible to save the text without clicking on the Canvas.

**Screenshots**
Attached a video

**draw.io version (In the Help->About menu of the draw.io editor):**
v22.1.16

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: iOS
 - Browser [e.g. chrome, safari]: Chrome
 - Browser Version [e.g. 22]: Version 120.0.6099.129

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- Yes

**Comment by alderg** [comment]
Some of the clicks outside of the canvas are required to change font properties, eg. click on bold, and should not stop editing. A generic function to determine which click should not stop editing isn't trivial.

**Comment by davidjgraph** [comment]
Thanks for the suggestion, but we are declining due the complexity of implementation.
