### ISSUE TITLE
Making showing overlays on exported images optional.

### ISSUE THREAD

**Issue by gitgitwhat** [jgraph/drawio#4085]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Please see #4083 

It doesn't make sense that objects shown during drawing wouldn't also be shown when exported.  Even though that is the currently expected behavior, it shouldn't be or at the very least an option.

**Describe the solution you'd like**
Show overlays on exported images.

**Describe alternatives you've considered**
You'd have to create regular objects to act like overlays but the behaviors (such as when moving the parent object) don't work the same.

**Additional context**

**Comment by davidjgraph** [comment]
Thanks for the suggestion, but overlays are a temporary part of the diagram, that is how they are defined. This will not change.

**Comment by gitgitwhat** [comment]
@davidjgraph It's unfortunate you won't support it.

For anyone else that may need this functionality:

In `mxClient.js` under `mxImageExport` simply change `mxImageExport.prototype.includeOverlays` to `1`.  

If you need overlays included in the exported XML, remove `"overlays`" from the excluded list for `mxObjectCodec`.  Then add `'mxCellOverlay', 'mxImage'` to the `mxCodec.allowlist` found in `js/grapheditor/Graph.js` file.

Obviously if you want it toggable, you'll have to add your own connective tissue.
