### ISSUE TITLE
Alibaba Cloud icon set

### ISSUE THREAD

**Issue by si7eka** [jgraph/drawio#4086]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
希望可以在图形形状中添加华为云和阿里云图标，感谢项目组

**Describe the solution you'd like**
原生支持他们的图标，请考虑一下中国公有云平台。

**Describe alternatives you've considered**
目前我只能到他们的网站下载PPT图标并复制到draw.io中使用。
下面是两家cloud的图标下载地址。
https://help.aliyun.com/document_detail/67830.html?spm=a2c4g.11174283.6.541.6187307bfWLA1r
https://www.huaweicloud.com/service/dsource.html

**Additional context**

**Comment by hwy1782** [comment]
How is this issue going? Is there any progress?

**Comment by westzhao** [comment]
I collected a complete set of Tencent Cloud official vector icons and generated the draw.io icon library:
https://github.com/8710925/tencent-cloud-icons

Icons are sourced from the official Tencent Cloud Design Center: https://cloud.tencent.com/act/event/icons

**Comment by westzhao** [comment]
Hi, I'm the author of the Tencent Cloud icon library mentioned in https://github.com/jgraph/drawio/issues/2712.

I've been maintaining this library for a while and it now includes:

450+ official Tencent Cloud icons (latest version from [Tencent Cloud Design Center](https://cloud.tencent.com/act/event/icons))
18 categories organized similar to Alibaba Cloud's structure
Both Chinese and English versions
Ready-to-use draw.io XML library files
📦 Repository: https://github.com/8710925/tencent-cloud-icons

I noticed that draw.io already has built-in support for Alibaba Cloud icons (as mentioned in https://github.com/jgraph/drawio/issues/4086). It would be great if Tencent Cloud icons could also be included as a built-in library, considering:

Tencent Cloud is one of the major cloud providers in Asia
The icon set is complete and well-organized
The library follows the same structure as existing cloud provider icons in draw.io
I'm happy to help with integration if needed. Let me know if there's anything I can do to assist!
