### ISSUE TITLE
Dismissing intro dialog with ESC leaves the UI largely empty

### ISSUE THREAD

**Issue by thecodewarrior** [jgraph/drawio#4089]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
If you dismiss the intro dialog using the escape key, the UI is left mostly uninitialized. If you dismiss it by clicking the background however it *does* initialize the UI.

**To Reproduce**
1. Launch the desktop app
2. Press the escape key

**Expected behavior**
I would expect the two methods of closing the dialog to behave identically. 

**Screenshots**
<img width="885" alt="empty_drawio_window" src="https://github.com/jgraph/drawio/assets/5467669/897f5f43-d622-49c9-a92b-abf1167899fd">

**draw.io version (In the Help->About menu of the draw.io editor):** 

- draw.io version v22.1.11 (desktop)

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.1.1 
 - Browser: N/A
 - Browser Version: N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- N/A

**Additional context**
I use the draw.io desktop app and it appears the dialog in question doesn't even exist on the web version, so it's likely only relevant for the desktop version.

**Comment by davidjgraph** [comment]
Fix in 22.1.22
