### ISSUE TITLE
div in SVG Export

### ISSUE THREAD

**Issue by madflow** [jgraph/drawio#409]
Hi there!

I have created a "Map". After exporting it to SVG there are some objects with `<div>Text</div>` in the text field. This seems to only affect the SVG Export. 

**Source File, with just one of the affected objects**: 

[DivInSvg.zip](https://github.com/jgraph/drawio/files/3037432/DivInSvg.zip)

**Example**:

![DivInSvg](https://user-images.githubusercontent.com/183248/55461511-e0002d80-55f4-11e9-8dc7-4f04b80e7722.png)

**Comment by alderg** [comment]
See https://desk.draw.io/a/solutions/articles/16000042487 What did you use to view the SVG file?

**Comment by madflow** [comment]
eog (Gnome Image Viewer) and Gimp show the `div`. Firefox does not. Everything on Arch Linux.
