### ISSUE TITLE
Text wrapping and auto-sizing doesn't work with flowchart diamonds

### ISSUE THREAD

**Issue by JCBerger** [jgraph/drawio#4097]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
I'm not sure if this is an issue with text wrapping or padding or the autosize, the text overflow settings, or something else, but the text wrapping in diamonds does not seem to work. Text either spills out of a diamond, or it adds in what appears to be a lot of padding to fit the text in the diamond.

**To Reproduce**
1. Create a diamond in the flowchart template.
2. Type or copy & paste text into a diamond.
3. See problematic behavior.

**Expected behavior**
That the auto-size would make better use of the space in the diamond to create line breaks or wrap text.

**Screenshots**
<img width="241" alt="Screenshot 2024-01-10 at 11 58 55" src="https://github.com/jgraph/drawio/assets/3228462/4935a95a-1420-4a4b-bef1-e7f15712952f">
<img width="512" alt="Screenshot 2024-01-10 at 12 00 44" src="https://github.com/jgraph/drawio/assets/3228462/674becd0-1e68-4bf7-9f8a-d92de3673f7e">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.18

**Desktop (please complete the following information):**
 - OS: macOS 14.2.1 (23C71)
 - Browser [Safari]
 - Browser Version [Version 17.2.1 (19617.1.17.11.12)]

**Smartphone (please complete the following information):**
 - Device: [n/a]
 - OS: [n/a]
 - Browser [n/a]
 - Version [n/a]

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
(Not applicable)-

**Additional context**

**Comment by error9900** [comment]
I'm curious why this is "not planned". I can understand why it wouldn't be a high priority, but auto-sizing for diamonds is currently bad UX, so I'm not sure why it was completely dismissed unless there's some technical reason for why it can't be done.

**Comment by mcaay** [comment]
I just figured out that you can:
- add an element you want, e.g. diamond
- add a text field and move it and size it inside the diamond
- group those 2 together
- add to custom palette for reusability

Then you get an element that will not be styled in this ugly overflowy way.
