### ISSUE TITLE
RTL Text Direction Resets When Outside of Editing Mode 

### ISSUE THREAD

**Issue by SaeedZeroOne** [jgraph/drawio#4104]
# Bug Description
When I write in a right-to-left language, while I'm writing, the direction of the text is correct (if text direction is set to right to left), but as soon as I click outside the text box, the appearance will revert to the LTR mode.

# To Reproduce
1. Make any shape, set text direction to right to left, and double click to write text inside
2. Write a text in a right-to-left language like Persian
3. Click outside of the shape and see the orientation change (if there are punctuations, it will be shown better)

# Screen Recording

https://github.com/jgraph/drawio/assets/11497700/51359903-1041-4c0a-84c4-031a4a3cfe23

# Version Details
- draw.io version 22.1.18
- Windows 11
- Microsoft Edge version 120.0.2210.133

**Comment by davidjgraph** [comment]
Fixed in 22.1.19, thanks for report.
