### ISSUE TITLE
By removing a Swimlane Container with Text inside, the whole diagram is deleted.

### ISSUE THREAD

**Issue by YaninaLeanIX** [jgraph/drawio#4109]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
When you remove the Swimlane container including "Text", the whole diagram is erased except for the "Text" included in the erased Swimlane container.

**To Reproduce**
1. Add several Swimlane Containers with and without Text inside
2. First remove the Swimlane container without "Text"- the Container is removed and nothing is broken
3. Then remove the Swimlane container with "Text" - the whole diagram is removed as well except for the "Text" included in the erased Swimlane container.

**Expected behavior**
When you remove the Swimlane container with "Text" - just Swimlane Container is removed, not the whole diagram.

**Screenshots**
The video recording of the screen is attached.

https://github.com/jgraph/drawio/assets/87121494/71219966-ad17-4a17-a20c-2a4c605ac1a8

- draw.io version: v22.1.18

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.2.1
 - Browser: Chrome
 - Browser Version:  120.0.6099.216

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-Yes

**Additional context**

**Comment by davidjgraph** [comment]
Please attach the full XML of the diagram to this ticket.

**Comment by YaninaLeanIX** [comment]
Full XML of the diagram 
[bug.log](https://github.com/jgraph/drawio/files/13953203/bug.log)

**Comment by davidjgraph** [comment]
This XML is not generated by draw.io.
