### ISSUE TITLE
Set Page Size by Pixels

### ISSUE THREAD

**Issue by RoyiAvital** [jgraph/drawio#411]
Hello,

Could you please add option to define page size with Pixels?

Thank You.

**Comment by RoyiAvital** [comment]
@davidjgraph , Any update on this?
I guess the underlying framework uses pixels hence it should be doable, right?

**Comment by ConnorJamesLow** [comment]
Would be nice if "Pixels" was available under _View > Units_. Physical measurements are not very useful for digital mockups. `em` and `rem` would be a nice bonus.

**Comment by RoyiAvital** [comment]
Any update on this? Any reasoning behind the `wontfix` label?

**Comment by davidjgraph** [comment]
What is the ETA on this?

**Comment by Dr-KerbalMD** [comment]
As a workaround, documents seem to export at 100 DPI so you can just set a custom size at the desired pixel dimensions / 100. For example, if you wanted a 1920 x 1080 export, just make the doc 19.2 x 10.8 inches.

**Comment by skycommand** [comment]
The app currently supports pixels. You must open the `.drawio` file in an XML editor, such as Visual Studio Code, and modify the value there.

The unit of pixels is critical because sometimes, I am forced to create something that has a strict dimension requirement in pixels.
