### ISSUE TITLE
Missing Azure Video Indexer Icon

### ISSUE THREAD

**Issue by tshaiman** [jgraph/drawio#4110]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
No , Just want to point to missing icons

**Describe the solution you'd like**
- The Icons of Several services in Azure is missing 
- You can get the latest Icon sets here : https://learn.microsoft.com/en-us/azure/architecture/icons/
- Please onbaord Azure Video Indexer Icon if Possible ( attached SVG)
![01800-icon-service-Azure-Video-Indexer](https://github.com/jgraph/drawio/assets/512709/1225113e-b53f-4031-abde-6c583c498228)

**Describe alternatives you've considered**

**Additional context**

**Comment by tshaiman** [comment]
any updates on this issue ?

**Comment by davidjgraph** [comment]
No, otherwise there would be a comment in the issue stating what the update is.
