### ISSUE TITLE
OneDrive authentication failure

### ISSUE THREAD

**Issue by rlarno** [jgraph/drawio#4116]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Attempting to open a drawing stored on Microsoft OneDrive, the authorization fails.

**To Reproduce**
1. Go to draw.io
2. In the 'Save diagrams to:' dialog, select **OneDrive**
3. In the 'Authorization required' dialog, select the **Authorize** button
4. A new popup windows opens to login.microsoft.com asking me to Sign In to my Microsoft account and authorize draw.io access to my account. select to allow.
5. The popup window now redirects back to https://app.diagrams.net/microsoft?code=_code_&state=_state_
6. The popup window shows HTTP ERROR 401
7. I am unable to load the drawing from my OneDrive account

**Expected behavior**
Authorization for OneDrive succeeds and I can use draw.io to work on my diagram

**Screenshots**
<img width="394" alt="image" src="https://github.com/jgraph/drawio/assets/1152839/cebd8778-d46b-4d05-a10d-53ef50badc2f">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.21

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: MS Edge
 - Browser Version:  120.0.2210.133

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
Yes
And with different MS Accounts

**Additional context**
Loading a file stored locally does work. Work-around is to use the local file.

**Comment by grayfrost90** [comment]
I'm getting this issue too - thought it was just my machine so I've tried the following:

- restarted browser
- restarted machine
- tried incognito
- enterprise and personal MS accounts

and still getting access denied

**Comment by technic** [comment]
I can confirm. Few days ago it was working

**Comment by duanemck** [comment]
Can confirm I'm seeing the same behaviour, have also tried the things mentioned above.

**Comment by davidjgraph** [comment]
Please stop with the "me too"s, only report if you have technical information to add.

**Comment by creatcatsby** [comment]
![image](https://github.com/jgraph/drawio/assets/157111507/8764729a-9ac9-4920-ba31-93de154fd6cc)

seeing this error in the Azure Logs

**Comment by davidjgraph** [comment]
This should now be fixed, thanks for the report. We've implemented steps to avoid this happening again.

**Comment by creatcatsby** [comment]
can confirm that it's working!

**Comment by rlarno** [comment]
Thank you for the swift resolution. Awesome 🎉
