### ISSUE TITLE
Reposition multiple shapes - all shapes squash together, Align feature does not work

### ISSUE THREAD

**Issue by YaninaLeanIX** [jgraph/drawio#4118]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
If you add, for example, 20 shapes on the canvas, then “Select all” – click “Arrange” – “Align” – “Middle”, all objects squash together (from 20 objects just 7 are visible on the canvas). I also tried other “Align” options but they resulted in the same. 

**To Reproduce**
1. Add 20 shapes on the canvas
2. “Select all” – click “Arrange” – “Align” – “Middle”
3. All shapes squash together 

**Expected behavior**
The shapes should be aligned to "Middle" or another option with respect to each other without squashing them together. If it is expected behaviour, what is the logic behind it?

**Screenshots**

https://github.com/jgraph/drawio/assets/87121494/b34efca7-bd40-41ac-bf51-4ce1585e3e0b

**draw.io version (In the Help->About menu of the draw.io editor):**

v22.1.21

**Desktop (please complete the following information):**
- OS: macOS Sonoma 14.2.1
- Browser: Chrome
- Browser Version: 120.0.6099.234

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-Yes

**Additional context**

**Comment by YaninaLeanIX** [comment]
If it is expected behavior, what is the logic behind it?

**Comment by davidjgraph** [comment]
The logic is that the function aligns all the selected shapes to their middles and that's what it does.

**Comment by YaninaLeanIX** [comment]
Thank you for the reply. My last question is, what about "Horizontal/Vertical Discribute"? It should redistribute the shapes with an alternative spacing but it does not work this way..Could you explain how this feature should work?

**Comment by alderg** [comment]
Distribute uses the left-/rightmost shape.
