### ISSUE TITLE
Mobile Browser Pinch Zoom not working probebly ( too fast )

### ISSUE THREAD

**Issue by salehawal** [jgraph/drawio#4120]
### Preflight Checklist

[* ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
[* ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Mobile Browser Pinch Zoom not working probebly ( too fast )

**To Reproduce**
1. Go to draw.io from mobile browser
2. create a new diagram and draw anything
3. pinch zoom with 2 fingers

**Expected behavior**
zooming should be smooth like pc experience

**Comment by pedroarthur** [comment]
Hi! I need to fix this bug. Any pointers to where I could start?

**Comment by alderg** [comment]
> Hi! I need to fix this "bug." Any pointers to where I could start? Thank you!

Have you tried configuring [zoomFactor](https://www.drawio.com/doc/faq/configure-diagram-editor)?

**Comment by salehawal** [comment]
> > Hi! I need to fix this "bug." Any pointers to where I could start? Thank you!
> 
> Have you tried configuring [zoomFactor](https://www.drawio.com/doc/faq/configure-diagram-editor)?

no, but will try it now

**Comment by salehawal** [comment]
> > Hi! I need to fix this "bug." Any pointers to where I could start? Thank you!
> 
> Have you tried configuring [zoomFactor](https://www.drawio.com/doc/faq/configure-diagram-editor)?

ok it works now, the problem was the setting of the zoomFactor was set to "1.2", which is ok for Desktop but vert fast for mobile screen space, after adjusting it to "0.4", now it is working fine, by adding the following setting code:
"
[
  {
    "zoomFactor": "0.4"
  }
]
"

to : Settings >> Configuration

just add the above code and restart the app and it should work ... :+1:

**Comment by salehawal** [comment]
> > > Hi! I need to fix this "bug." Any pointers to where I could start? Thank you!
> > 
> > Have you tried configuring [zoomFactor](https://www.drawio.com/doc/faq/configure-diagram-editor)?
> 
> ok it works now, the problem was the setting of the zoomFactor was set to "1.2", which is ok for Desktop but vert fast for mobile screen space, after adjusting it to "0.4", now it is working fine, by adding the following setting code:
> "
> [
>   {
>     "zoomFactor": "0.4"
>   }
> ]
> "
> 
> to : Settings >> Configuration
> 
> just add the above code and restart the app and it should work ... :+1: 

It did work for a day, but now not working at all, even when changing the browser all the same result, and now there is a new issue you can drag elements touch or s pen

Kindly check and resolve all these issues because for now it is not usable as a mobile pwa app, but we wish to see it work
