### ISSUE TITLE
CSV import with parents needs two imports to work correctly

### ISSUE THREAD

**Issue by GordianDziwis** [jgraph/drawio#4121]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
CSV import with parents needs two imports to work correctly.

**To Reproduce**

1. Import
```csv
# label: %subject%
# stylename: type
# styles: { \
#   "Node": "whiteSpace=wrap;fontSize=14;", \
#   "AnonContainer": "\
#     swimlane;\
#     fontStyle=0;\
#     childLayout=stackLayout;\
#     horizontal=1;\
#     startSize=0;\
#     horizontalStack=0;\
#     resizeParent=1;\
#     resizeParentMax=0;\
#     resizeLast=0;\
#     collapsible=1;\
#     marginBottom=10;\
#     marginTop=10;\
#     marginRight=10;\
#     marginLeft=10;\
#     whiteSpace=wrap;\
#     fillColor=default;\
#     swimlaneFillColor=default;\
#     rounded=0;\
#     spacing=4;\
#     arcSize=12;\
#     html=0;\
#     fillOpacity=100;"}
# identity: identity
# parent: parent
# namespace: csvimport-
# connect: { "from": "object", "to": "identity", "sourcelabel": "%predicate%", "style": "fontSize=14;"}
##
identity,type,subject,predicate,object,parent
1,AnonContainer,,,,
2,Node,<s>,<p>,3,
3,Node,<o>,,,1
```
2. -> There is no container
3. Repeat step two
5. There is a container

**Expected behavior**
Import should work

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.6.9 and 22.1.21

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [Firefox]
 - Browser Version [121]

**Smartphone (please complete the following information):**

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**

**Comment by GordianDziwis** [comment]
What is also broken, is that when a Container uses the `styles` attribute its style will get overwritten by the `parentstyle` attribute (even when `parentstyle` is not set).

**Comment by mmaura** [comment]
I confirm, also if we use the cli to generate the files it is impossible to obtain the good result.
