### ISSUE TITLE
Missing toolbar in Notion Embed

### ISSUE THREAD

**Issue by jumale** [jgraph/drawio#4123]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
When exporting a drawing and embedding it into Notion, the Toolbar is missing in the Notion preview (see the first screenshot).
However when clicking on "View original" in context menu in notion - it opens the view in a browser window where the toolbar is displayed as expected.
**Sometimes** (but not always) when exporting multiple pages - the toolbar is displayed as expected (see the second screenshot). I could not find the exact pattern here, but in general it looks like if **some of my pages contain copy-pasted content from my older drawings** - then the multi-page export is most likely to have the toolbar.
Also the toolbar is displayed as expected in those my drawings which I exported and embedded around 6 months ago. So it looks like it's happening only for recently created/embedded drawings.
This bug prevents me from arranging the imported view to fit the resized Embed-box.

**To Reproduce**
1. Create a drawing in Draw.io desktop app (macOS)
2. Click in menu > Export as > Embed > Notion
3. Click "Create" and then "Copy"
4. Open Notion
5. Add an Embed block
6. Paste the copied URL
7. Hover the block - no toolbar is displayed (see the first screenshot)

**Expected behavior**
The toolbox is displayed on hover in Notion.

**Screenshots**
![Screenshot 2024-01-22 at 13 02 58](https://github.com/jgraph/drawio/assets/5584627/64be6e0d-3d9a-4dc6-a856-891f5763730c)
![Screenshot 2024-01-22 at 13 03 26](https://github.com/jgraph/drawio/assets/5584627/18ad6a6f-8c0e-48c9-9113-8727bd819743)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io desktop version 22.1.21

**Notion version:**
- Notion desktop version 3.1.0 

**Desktop (please complete the following information):**
 - OS: macOS 14.2.1
 - Browser not applicable
 - Browser Version not applicable

**Smartphone (please complete the following information):**
 - not applicable

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- not applicable

**Additional context**

**Comment by alderg** [comment]
Notion adds an indirection `https://embed.notion.co/api/iframe?app=1&url=...` that disabled our toolbar.
