### ISSUE TITLE
Reopened diagrams in PNG don't remember zoom value used during export

### ISSUE THREAD

**Issue by pktiuk** [jgraph/drawio#4125]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

In case of editing existing `.png` files (with embedded diagram metadata) overwriting it causes overwriting earlier selected value of `Zoom`

**To Reproduce**

1. Create diagram
2. Export it to PNG (`File->Export as...-> PNG...`) with value Zoom changed (for example 300%) and with metadata
![obraz](https://github.com/jgraph/drawio/assets/45544416/dcdd14f2-3434-4c20-af55-bd5c6826c61d)
3.  Close app
4. Check size of the image
5. Open app
6. Open file (`File->Open`)
7. Change something
8. Save (Ctrl+S)
9. Check image size

Now image is smaller than previously.

**Expected behavior**

Image should have the same resolution as before saving

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):** v22.1.21 (Flatpak package)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux Pop!_OS 22.04
 - Browser Version [e.g. 22]

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-

**Additional context**

In case of exporting the same image again the `Zoom` value is still remembered.

**Comment by davidjgraph** [comment]
In 23.0.0

**Comment by pktiuk** [comment]
@davidjgraph 

Retested with 3.0.2

Size is remembered now, but background setting is forgotten after editing:

![obraz](https://github.com/jgraph/drawio/assets/45544416/11c6ceed-8776-48db-96da-7537888d4480)

**Comment by davidjgraph** [comment]
OK, but we'd need a new issue for that please.

**Comment by pktiuk** [comment]
Done
