### ISSUE TITLE
Draw.io: integration with Gitea

### ISSUE THREAD

**Issue by AKopytenko** [jgraph/drawio#4128]
* [+] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [+] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
[EN] The user attaches the .drawio file to the messages in the issues. When clicking on the attached file, the user is redirected to the draw.io, at the same time, the contents of the file [XML in base64 or the like] are sent to the payload of the POST request. Draw.io receiving the file content and expands it into a schema. Apparently, the issue is complex and requires collaboration with the guys from Gitea. Let's try?

[RU] Пользователь прикрепляет файл .drawio к сообщениям в задачах. При клике на прикреплённый файл пользователь перенаправляется на ресурс draw.io, при этом в payload POST-запроса отправляется содержимое файла [XML в base64 или т.п.]. Draw.io, получая файл, разворачивает его в схему. Видимо, задача комплексная и требует совместной работы с ребятами из Gitea. Давайте попробуем?

**Describe alternatives you've considered**
No. 

**Additional context**
I was upset that https://github.com/jgraph/drawio/issues/408 it was rejected.

P.S.: Here is link to issue in Gitea repo :) 
https://github.com/go-gitea/gitea/issues/28903

**Comment by davidjgraph** [comment]
Even though it's closed, this issue is still a duplicate. The FR was rejected and that's still the case currently.
