### ISSUE TITLE
Inserting a digram into google slides creates a 503 and 1033 error code

### ISSUE THREAD

**Issue by skilljar2022** [jgraph/drawio#4133]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**

**To Reproduce**
1. Go to google slides
2. Click on extensions
3. Scroll down to digagram.net for slides
4. Find file and insert
5. See error

**Expected behavior**
The diagram should embed

**Screenshots**
See loom recoding here:

https://www.loom.com/share/b68a418dde674080b74375eef2349ded?sid=fccff05e-8d3d-4f7f-abd3-938b0de084d0

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 23.0.1

**Desktop (please complete the following information):**
 - MAC OS
 - Browser CHROME
 - Browser Version 120.0.6099.199

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- YES

**Additional context**

**Comment by skilljar2022** [comment]
Currently I have to copy the image and paste into a google slide. This is a workaround and an extra step.

**Comment by davidjgraph** [comment]
Thanks for the report (especially the video). Is this still happening?

**Comment by Bartel-C8** [comment]
Same here in Google Docs, but a 500 response:

Request failed for https://convert.diagrams.net returned code 500. Truncated server response: Error! (use muteHttpExceptions option to examine full response).

**Comment by FlorentCLMichel** [comment]
I'm facing the same issue since today. (I have not used this function in the past two weeks so I'm not sure when the problem started.) 
Interestingly, on my side the problem seems to be intermittent. When trying to insert a new diagram, insertion fails about 75% of the times but trying repeatedly generally succeeds after a few attempts. Updating an existing diagram seems to fail with the same error message more frequently, based on my small number of attempts (20 attempts, 100% failure rate).

**Comment by davidjgraph** [comment]
Fixed, thanks for report.

**Comment by skilljar2022** [comment]
@davidjgraph - Confirmed this is fixed on my end. Thank you for the help.
