### ISSUE TITLE
Issue between diagrams.net and Google Slides

### ISSUE THREAD

**Issue by anonymous-consultant** [jgraph/drawio#4134]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
The diagrams.net extension is not working on Google products. I am trying to update a diagram from draw.io that is already present in a Google Slides presentation, and whenever I attempt to update the visual in the slideshow, an error pops up. I also tried deleting the diagram from the presentation and re-inserting it, but this also was unsuccessful. I have cleared browser history, cleared cache, used an incognito window, however none of these solved the issue. Any help would be greatly appreciated!

1. Go to 'Google Slides'
2. Click on 'Extension > diagrams.net > update selected diagrams OR update all'
3. Scroll down to 'no need to scroll'

**Expected behavior**
The diagram was supposed to be updated to reflect new adjustments in the draw.io visual within our Google Slides presentation. 

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/157621840/ed7c8160-3f85-4703-8a34-f24ab698c180)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 23.0.1

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Browser Version 120.0.6099.225

**Smartphone (please complete the following information):**
 - Device: [iPhone 13]
 - OS: [e.g. iOS17.2]
 - Browser [safari]
 - Version [e.g. 17.2]

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-yes

**Additional context**
Please help :(

**Comment by davidjgraph** [comment]
Cannot repeat.
