### ISSUE TITLE
Freehand drawing unexpected behavior - cannot draw circles

### ISSUE THREAD

**Issue by dgan11** [jgraph/drawio#4140]
### Preflight Checklist
* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Unexpected behavior when drawing curves (i.e. circle, lowercase letter "e") when using the freehand tool. Expecting to be able to draw a circle but instead looks like a coiled shoestring.

Was working a couple days ago. Started for me yesterday (1/23/24)

**To Reproduce**
1. open the freehand tool
2. try to draw a circle
3. See error

**Expected behavior**
I can draw a circle without a little coil happening

**Screenshots**

https://github.com/jgraph/drawio/assets/37032548/8e3d553d-bf22-4c80-83e6-314be9e79041

clicked the gear icon in the freehand tool and these are the settings. I don't know if they have changed or not. 

<img width="549" alt="Screenshot 2024-01-24 at 3 19 19 PM" src="https://github.com/jgraph/drawio/assets/37032548/f3a33be0-20f8-4413-b878-09aa4d7a0b1e">

- draw.io version 23.0.0

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome 
 - Browser Version: 120.0.6099.199

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**

**Comment by davidjgraph** [comment]
Fix in 23.0.2, thanks for report.

**Comment by dgan11** [comment]
Working as expected again, thanks!
