### ISSUE TITLE
White line when changing background color of text

### ISSUE THREAD

**Issue by poesjeskoning** [jgraph/drawio#4142]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When changing the background color of a text there is still a white line visible.

**To Reproduce**
1. put down a line
2. type a text on the line
3. change the background color of that text
4. See white line under the wanted background color

**Expected behavior**
I expect the background color to be fully the color i select

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/157711996/ab9b5d1f-a98d-4e67-86c7-85caf746cc84)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.7.3

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome 120.0.6099.225

**Smartphone (please complete the following information):**
 - Device: No phone

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
 the issue is in the application, i do not care about browser.

**Comment by davidjgraph** [comment]
draw.io version 13.7.3? Seriously?

**Comment by poesjeskoning** [comment]
> 

Just updated to 22.1.21, still the same problem.

**Comment by alderg** [comment]
Try select the label (not the text) and set the text background color again.

**Comment by poesjeskoning** [comment]
> Try select the label (not the text) and set the text background color again.

ah just figured it out, it is still weird. if i double click on the text, then it goes wrong. if i select the line then press text. then it does work as intended. Still think this is a bug. but i can get color combi like this.

![image](https://github.com/jgraph/drawio/assets/157711996/072f58d3-cdbe-49d3-a5d9-e180a19cda1d)

*but if you*
 1. place line with text
 2. double click and select text
 3. change background color
 4. select line
 5. click on text
 6. error: it thinks the whole background changed.
 7. then select other color to create my image
