### ISSUE TITLE
Editable SVGs exported by v23.0.2 are not rendering in Gitlab/Github

### ISSUE THREAD

**Issue by ssarraju** [jgraph/drawio#4154]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
When we export an editable svg from drawio with latest version 23.0.2, the svgs aren't rendering in gitlab/github. Issue isn't seen in previous versions.
**To Reproduce**
1. Draw a diagram
2. Save as editable svg
3. Refer to the svg in markdown of GitHub/gitlab
4. Render the page in gitlab/github

**Expected behavior**
SVG should render properly

**Screenshots**
![Screenshot 2024-01-29 at 7 03 18 PM](https://github.com/jgraph/drawio/assets/391986/f4062805-ca59-4eac-8d7a-181e65679d9e)
**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version x.y.z

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [v23.0.2]

**Smartphone (please complete the following information):**

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-

**Additional context**

**Comment by davidjgraph** [comment]
Can you point to a public example?
