### ISSUE TITLE
Issue trying to create new file

### ISSUE THREAD

**Issue by ego93** [jgraph/drawio#4156]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
When I open app.diagrams.net in Firefox it opens on my previous diagram, I go to create a new diagram and get the following error:
`o.url is not a function` 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open existing diagram
2. Go to 'File' -> 'New...'
3. Click on 'Blank Diagram' then click the 'Create' button
4. See error `o.url is not a function` 

**Expected behaviour**
I expected a fresh blank diagram

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/32328035/2d86b8a1-b36d-4406-80fb-d2b350c25c02)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.18

**Desktop (please complete the following information):**
 - OS: MacOS 14.2.1 
 - Browser Firefox
 - Browser Version 122.0

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- Yes and its not an issue

**Comment by davidjgraph** [comment]
Close the app, use clear.diagrams.net to clear you cache and re-load the app.
