### ISSUE TITLE
Stencil Import broken images in Desktop app

### ISSUE THREAD

**Issue by neilyo51** [jgraph/drawio#4165]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
About a fourth of imported vssx Splunk stencils in Desktop are broken. Web app works as intended. 

**To Reproduce**
1. Go to 'Open Library'
2. Click on 'Show Option' > 'Open'.'
3. See error
<img width="493" alt="image" src="https://github.com/jgraph/drawio/assets/32020991/793ef453-bf22-451b-83e9-12a3c528d3f0">

**Expected behavior**
Web app works appropriately as shown
<img width="493" alt="image" src="https://github.com/jgraph/drawio/assets/32020991/e2a65bfc-c313-4265-85c3-c99edaf6b667">

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version v23.0.2

**Desktop (please complete the following information):**
 - OS: [MacOS Sonoma 14.2.1]

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- N/A

**Additional context**

**Comment by neilyo51** [comment]
Stencils from
https://docs.splunk.com/Documentation/Community/current/community/Resources

**Comment by davidjgraph** [comment]
They contain EMF images. Importing those requires a server, the desktop app is designed to be isolated.
