### ISSUE TITLE
When inserting non-image files the spinner stays on page forever

### ISSUE THREAD

**Issue by FarSeeing** [jgraph/drawio#4166]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**

When inserting non-image files the spinner stays on page forever

**To Reproduce**
1. Go to https://app.diagrams.net/
2. Create a diagram
3. Click on `Arrange - Insert - Image...' menu item
4. Click on `Open` button
5. Select any non-image file
6. Verify that the spinner stays on page

**Expected behavior**

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/559569/db5f8f26-463b-40e9-9a91-3048c86bac17)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 23.1.0

**Desktop (please complete the following information):**
 - OS: any
 - Browser any
 - Browser Version any

**Smartphone (please complete the following information):**

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**

**Comment by davidjgraph** [comment]
Fix in 23.1.2
