### ISSUE TITLE
more than 1000 graphics,become very slow!

### ISSUE THREAD

**Issue by lijunay** [jgraph/drawio#417]
After loading more than 1000 graphics, scaling and other operations become very slow, how to solve?

**Comment by davidjgraph** [comment]
Load less than 1000 graphics?

**Comment by lijunay** [comment]
more than 1000 shape.

**Comment by davidjgraph** [comment]
Github issues is more for developers with bug reports. For end user questions, please use https://groups.google.com/forum/#!forum/drawio
