### ISSUE TITLE
Export to PDF issue

### ISSUE THREAD

**Issue by FS-ISCG** [jgraph/drawio#4177]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
The Export to PDF option seems to be encountering some error, the only message the end user are getting is a simple "Error!" when looking at https://convert.diagrams.net/node/export

**To Reproduce**
Tested the export option from within the normal chrome browser and the draw.io desktop app and both are returning the same behaviour when trying to perform a Export to pdf.

**Expected behavior**
PDF to be created but it doesnt.

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/159123291/5c4b4bf8-562e-4273-966c-b75f1da48fac)

**draw.io version (In the Help->About menu of the draw.io editor):**

- v23.1.1

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Chrome
 - Browser Version 121.0.6167.140 (Official Build) (64-bit)

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**
None

**Comment by davidjgraph** [comment]
Fixed, thanks for report.

The desktop app cannot be doing this, though, what version are you using?

**Comment by FS-ISCG** [comment]
![image](https://github.com/jgraph/drawio/assets/159123291/0ea3e945-08d4-4ecf-9bce-e0ec4d7eb0b6)
And Thank you issue seems resolved.

**Comment by davidjgraph** [comment]
OK, I think that's the chrome app. I thought Google discontinued support for those?
