### ISSUE TITLE
Impossible to save

### ISSUE THREAD

**Issue by piiskop** [jgraph/drawio#4183]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Impossible to save**
Automatic nor manual save does not work. It ends with:

> Viga faili salvestamisel
> Failed to execute 'createWritable' on 'FileSystemFileHandle': Failed to create swap file.
> 

**To Reproduce**
1. Open a file from another device that does not contain the browser!
2. Go to 'File' -> 'Salvesta'!
3. See the error message!

**Expected behavior**
It is possible to save.

**draw.io version (In the Help->About menu of the draw.io editor):**

- v23.1.1

**Desktop (please complete the following information):**
 - OS: 'Ubuntu 23.10'
 - Browser chrome
 - Browser Version 121.0.6167.139 (Official Build) (64-bit)

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**
Saving works if the file is on the same drive as the browser.

**Comment by davidjgraph** [comment]
I don't understand the environment and reproduction steps.

**Comment by piiskop** [comment]
What do you mean by the environment? The web app cannot save if the file is on a different drive than the browser. It did save before. I discovered this anomaly this afternoon.

**Comment by davidjgraph** [comment]
Are you sure the device isn't simply read-only?

**Comment by davidjgraph** [comment]
Might be https://bugs.chromium.org/p/chromium/issues/detail?id=1523851

**Comment by piiskop** [comment]
I am sure that the device is not simply read-only. I used the very same device and file so far without problems.

The file _füüsika_ is was the folder _füüsika_. I moved the file into another folder and changed the name, too. Now, I can save changes. So, have we localized the issue?

**Comment by davidjgraph** [comment]
Yes, it's a chrome bug.
