### ISSUE TITLE
Google Drive: HTTP ERROR 401

### ISSUE THREAD

**Issue by ajmeese7** [jgraph/drawio#4187]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Authenticating to Google Drive is currently giving a 401 error on your site, I'm not sure if the error is localized or for everyone. It was working for me as of yesterday, I'm not sure what might have changed.

Whenever I hit "Reload" in the popup window, there is a long load time before getting the message "Internal Server Error".

Sometimes I get this HTML in plaintext returned in the popup window:

```html
<!DOCTYPE html><html><head><script src="/connect/office365/js/driveLoader.js" type="text/javascript"></script><script type="text/javascript">(function() { var authInfo = {"access_token":"OBFUSCATED_FOR_SECURITY_REASONS","expires_in":3599};if (window.opener != null && window.opener.onGoogleDriveCallback != null){	window.opener.onGoogleDriveCallback(authInfo, window);} else {	onGDriveCallback(authInfo);}})();</script></head><body></body></html>
```

**To Reproduce**
1. Go to 'https://app.diagrams.net/'
2. Click on 'Open Existing Diagram'
3. Click 'Authorize'

**Expected behavior**
The normal functionality that allows me to select an existing graph in the website.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 23.1.2

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave
 - Browser Version: v1.62.162

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Comment by davidjgraph** [comment]
This should have recovered now.

**Comment by ajmeese7** [comment]
Full functionality has been restored, thanks!
