### ISSUE TITLE
SharePoint sites missing in Save as

### ISSUE THREAD

**Issue by FlorianFey** [jgraph/drawio#4188]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
I login with my MS 365 account abut I do not see all my SharePoint sites in the selction, when I want to save on SharePoint.

**To Reproduce**
1. Go to 'File'
2. Click on 'Save as'
3. Click on 'One Drive - Choose folder'
4. Click on 'SharePoint'
5. Click on 'Refresh icon'
6. I only see 1 site, but I have a lot of SharePoint sites.

**Expected behavior**
I wnat to see all my sites to select the one I want to save my file.

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/76658861/b24e3115-cba2-40d7-89a1-2eae4f85c101)

![image](https://github.com/jgraph/drawio/assets/76658861/a27afbd2-16c5-4c96-b7d8-402c27899acd)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version web

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Browser Version  121.0.2277.106 

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**

**Comment by davidjgraph** [comment]
Not sure if this is us or not. The picker is Microsoft supplied on their domain, but it's possible that we haven't authorized correctly in some way.

That said, we don't have the resources to investigate this in the short term, just to set expectations.

**Comment by FlorianFey** [comment]
Honestly this is a bad answer because you make announcements, that we can use Drawio with SharePoint, connect it, save files there. And the you just say "Oh sorry, we do not have time to fix what we offer you.!

**Comment by davidjgraph** [comment]
OK, and you pay for draw.io?

**Comment by FlorianFey** [comment]
Yes, I would pay for it

**Comment by davidjgraph** [comment]
I'd suggest a commercial tool in that case, https://www.lucidchart.com/pages/ has a Microsoft integration.
