### ISSUE TITLE
Technology Function Stencil missing from ArchiMate 3.2/Technology

### ISSUE THREAD

**Issue by danfossjhc** [jgraph/drawio#4193]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
The ArchiMate stencil is not complete and are missing at least one stencil.

**To Reproduce**
1. Go to '+ More Shapes'
2. Click on 'Tick mark "ArchiMate 3.2 and press Apply'
3. Scroll down to 'ArchiMate 3.2 / Technology'
4. "Technology Function" is missing from the stencils

**Expected behavior**
Technology Function should be there according to OpenGroup documentation on ArchiMate 3.2 
(https://pubs.opengroup.org/architecture/archimate32-doc/ch-Technology-Layer.html)
**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 23.0.2

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser [Edge]
 - Browser Version [121.0.2277.112]

**Smartphone (please complete the following information):**
 - Device: [N/A]
 - OS: [N/A]
 - Browser [N/A]
 - Version [N/A]

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**

**Comment by sirex** [comment]
Yes, found the same issue. And a more precise link to the missing stencil:

https://pubs.opengroup.org/architecture/archimate32-doc/ch-Technology-Layer.html#sec-Technology-Function

![](https://pubs.opengroup.org/architecture/archimate32-doc/images/fig-Technology-Function-Notation.png)

**Comment by davidjgraph** [comment]
https://pubs.opengroup.org/architecture/archimate3-doc/ch-Summary-of-Language-Notation.html

**Comment by egrimate** [comment]
Will be in next release
