### ISSUE TITLE
Feature request:

### ISSUE THREAD

**Issue by JinHansson** [jgraph/drawio#4198]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.
** (Similar to https://github.com/jgraph/drawio/issues/3090)

**Is your feature request related to a problem? Please describe.**
Bullet point and numbered list indentation is awfully large by default and there seems to be no way to modify it.

**Describe the solution you'd like**
Having an option for that would make drawing neat diagrams much easier without having to hassle with additional overlaid textboxes to achieve the desired outlook.

**Describe alternatives you've considered**
So far I've created new textboxes I have overlaid with the existing ones. It's clumsy and feels silly.

**Comment by alderg** [comment]
Currently, the only workaround that doesn't affect existing diagrams is clicking the HTML button and adding style="padding-left:20px;" after the UL tag:

<img width="435" alt="Screenshot 2024-03-05 at 09 38 47" src="https://github.com/jgraph/drawio/assets/921200/5be6ae81-4a16-42ac-bd6b-43cdbda729ee">
