### ISSUE TITLE
Add SAP Business Technology Platform Stencils (SAP Icons, BTP Service Icons & Shapes)

### ISSUE THREAD

**Issue by fabianleh** [jgraph/drawio#4199]
* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Include SAP Business Technology Platform Stencils as part of the standard integration in draw.io. 
As the SAP ecossyteme ([community](https://community.sap.com/t5/forums/searchpage/tab/message?advanced=false&allow_punctuation=false&q=SAP%20BTP%20Solution%20Diagrams)/partner) make use to create SAP BTP Solution Diagrams with draw.io it would be great to get this integration.

Official link with more details will be shared soon !

**Comment by fabianleh** [comment]
Happy to share now also the link to the GitHub [repo](https://github.com/SAP/btp-solution-diagrams/tree/main)/[page](https://sap.github.io/btp-solution-diagrams/) and announcement [blog](https://community.sap.com/t5/technology-blogs-by-sap/announcement-new-release-of-content-and-central-entry-point-for-sap-btp/ba-p/13615582) at SAP Community

**Comment by fabianleh** [comment]
@egrimate can you share already (if available) a estimated timeline to integrate the SAP BTP Icons / Examples etc. ?

**Comment by davidjgraph** [comment]
Sorry, that isn't how we work. We don't provide ETAs.

**Comment by fabianleh** [comment]
@davidjgraph ok, got it. But can you pls. explain what it means as the "stencil" tag is added now ? 
In case you need support from our side we're happy to collaborate/discuss.

**Comment by davidjgraph** [comment]
It just means that it's a stencil request. There's nothing needed from your team. One of our team needs to decide that they want to implement the stencils.

**Comment by davidjgraph** [comment]
Just to update on this, we're stuck due to never having accepted a contribution to the core. The entire project is copyrighted to us and we have downstream contracts that state this must be the case.

**Comment by davidjgraph** [comment]
In 24.7.0. Any issues, please open new issue or discussion.

**Comment by fabianleh** [comment]
@davidjgraph great new's !
