### ISSUE TITLE
Any plans for 2019 javascript classes refactor?

### ISSUE THREAD

**Issue by robertdumitrescu** [jgraph/drawio#420]
Are there any plans to refactor the classes here: "https://github.com/jgraph/drawio/tree/master/src/main/webapp/js/mxgraph" into 2019 classes? (without prototype)

I am trying to embed the project into a React app and currently, web pack can't import them due to static properties or prototype properties.

**Comment by davidjgraph** [comment]
Not in this project, someone would have to fork it. It just makes work for us for something that provides us no benefit.

My view is if the tool cannot manage standards compliant JavaScript, the tool is at fault.

**Comment by robertdumitrescu** [comment]
Fair enough :)

**Comment by DanielYu8899** [comment]
> Fair enough :)

Hi Robert, do you resolve this issue?
