### ISSUE TITLE
Cropped images break on duplicated / new pages (no way to recover)

### ISSUE THREAD

**Issue by JonLevin25** [jgraph/drawio#4202]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Cropping an image works fine for the current page. Once the page is duplicated, the new page displays the entire (uncropped) image outside the bounds of the crop. It seems the selection rect is still correct to the crop.

ADDITIONAL NOTES:
 * Copying and pasting the correctly cropped image from the original page to the new one will still be broken
 * In the new page - if creating an image from scratch and cropping it again - it will also be broken
 * If creating a new page after this - it will be broken like the duplicated page.

**To Reproduce**
1. Create a new diagram
2. Copy an image to the clipboard, i.e. go [here](https://cdn.vox-cdn.com/thumbor/wfbQ3XccV6SxGMt1l6zBPL3Xg7o=/0x0:1192x795/1400x1050/filters:focal(596x398:597x399)/cdn.vox-cdn.com/uploads/chorus_asset/file/22312759/rickroll_4k.jpg) and right click -> Copy image
3. Paste the image in your diagram
4. Crop the image
5. Duplicate the page containing the image
6. Go to your duplicated page
7. All images in the new page are broken, showing all uncropped areas. It is impossible to fix any images in that or any new pages.

**Expected behavior**
Images should not show anything outside their cropped bounds.

**Screenshots**
Original (properly cropped):
![image](https://github.com/jgraph/drawio/assets/57547561/e2a403b3-7d23-43ba-999d-3ad5eff45f04)

Broken (notice the rect shows the actual crop)
![image](https://github.com/jgraph/drawio/assets/57547561/ec35e1ce-aac1-4d9d-8a50-6154fa317fed)

- draw.io version 21.7.5

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome - 121.0.6167.162 (Official Build) (64-bit)

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes. Once it also repro'd when cropping immediately for me (before duplicating)

**Additional context**
It's pretty severe in that it seems to mess up all new pages (except the original one that you already cropped)

**Comment by ArthurOuaknine** [comment]
+1 on this issue, it's a really severe break on all crop features.
On my side, even creating a new drawio page, copy / past an image and trying to crop it does not work anymore.

Here is a test of just a squared crop:
![try to crop](https://github.com/jgraph/drawio/assets/22349402/b70ca61c-e9dd-46be-9cf2-3f572bd33881)

Result of the crop:
![results crop](https://github.com/jgraph/drawio/assets/22349402/20cb9106-fcd8-4cf6-983c-5523494bed0f)

Note that both the rounded and ellipse crop methods are not working anymore as well:
![rounded crop](https://github.com/jgraph/drawio/assets/22349402/553e7157-b87c-4ea9-8b24-f7b0e9159b54)

![ellipse crop](https://github.com/jgraph/drawio/assets/22349402/953bd630-32ec-4240-bb81-298977d86558)

How to reproduce: just copy past a random image on a new drawio page and try to crop it.

**Comment by davidjgraph** [comment]
Fix in 23.1.6, thanks for report.

**Comment by ArthurOuaknine** [comment]
Thanks for taking care of this, do you know when this version will be in production online?
