### ISSUE TITLE
When pasting from VS Code, indentation is lost on MACOSX

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [jgraph/drawio#4209]
**Describe the bug**
When pasting from VS Code, indentation is lost on MACOSX app

**To Reproduce**
1. Open a diagram
2. create a json document in VSCode
3. Copy from VSCode
4. Paste on draw.io

**Expected behavior**
indentation to be maintened

**draw.io version (In the Help->About menu of the draw.io editor):**

- About draw.io is redirecting to the website, but there are no available updates as of today deb 20th

**Desktop (please complete the following information):**
 - OS: MACOSX 14.3.1 (23D60) SONOMA
 - Native App

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-

**Additional context**

**Comment by alderg** [comment]
Fixed in 24.0.0.
