### ISSUE TITLE
When using gitlab, Share opens wrong link to members page

### ISSUE THREAD

**Issue by noREAVER** [jgraph/drawio#4213]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When opening a file from a GitLab repository I own, the "Share" button opens a new tab with the link to the project members page, but the URL is partially escaped and of course Page not Found. Some / are /  but some in the middle are escaped %2F
I am not sure if this has something to do with the subgroup name being of format "abc-def" and not "abc_def".
What i get is:
https://gitlab.com/myteam%2Fabc-def%2Fpublic/someproject/-/project_members
and should be
https://gitlab.com/myteam/abc-def/public/someproject/-/project_members

**Expected behavior**

- draw.io version 23.0.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Browser Version: 121.0.6167.185

**Comment by davidjgraph** [comment]
Fix in 24.5.4.
