### ISSUE TITLE
Gitlab api 404 when listing branches using Create New or Open Existing

### ISSUE THREAD

**Issue by frangigu** [jgraph/drawio#4221]
Hi, 

It seems like there is an issue when using Drawio and GitLab integration to fetch the list of branches from a project.

When trying to create or open from a Git Repo, we get a dialog showing the project listing but when we select the project, we receive an error in the UI and a 404 from the API that is visible in the network & console of the browser.

From what I can see, Drawio is using the project name as a Path Parameter instead of the project numeral ID which is expected by the GitLab API
![image](https://github.com/jgraph/drawio/assets/95890417/db73765d-53cb-4ea2-8706-9ed53714ba15)
![image](https://github.com/jgraph/drawio/assets/95890417/e24fa9ff-b613-4603-bc27-c6e0a0e7895c)
GitLab API branches specs : https://docs.gitlab.com/ee/api/branches.html

To reproduce, simply try to create a new file to a GitLab repo, find the URL giving the 404 from the browser console or network tab, if you replace the project name with the proper ID and the API will respond with the branches listing for the project.

GitLab version on my end : v16.9.1

**Comment by alderg** [comment]
According to that spec, "ID or **URL-encoded path of the project**" is allowed.
