### ISSUE TITLE
Unable to open .drawio files from OneDrive web app.

### ISSUE THREAD

**Issue by Naroleptic** [jgraph/drawio#4228]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Can't open .drawio files from my OneDrive web app (onedrive.live.com).   

**To Reproduce**
1. From 'onedrive.live.com', try to open any .drawio file.
2. Only gives the option to Download, not open the file, see screenshot.

**Expected behavior**
I am in the process of switching from Google One to Microsoft 365 Personal.

Opening a .drawio file in Google drive gives a preview and the option to open it in diaggrams.net in a new browser tab (both Chrome and Edge).

It seems that .drawio is not among the file types that can be previewed in [OneDrive](https://support.microsoft.com/en-us/office/file-types-supported-for-previewing-files-in-onedrive-sharepoint-and-teams-e054cd0f-8ef2-4ccb-937e-26e37419c5e4), so a preview is out and that's ok, if not ideal.

But is there any way to at least open the file in diagrams.net, like from Google Drive? 

If not, this gets quite problematic. Downloading a separate file locally, editing it in the draw io win app, then having to manually replace the original file in OneDrive is not a reasonable solution.

Using only the draw io Win app to open files in my local OneDrive folder is not really a solution either, since I want to be able to link to/share/integrate with docs etc. I also prefer working in my browser, because of the auto-save, ability to Bookmark and group with other tabs by projects etc. 

Is there any way to make this work? I really love the app and would hate to have to look for alternatives for this reason alone.
 

**Screenshots**

![No DL drawio](https://github.com/jgraph/drawio/assets/104962704/c5fc53a1-2c08-43e9-97e2-6adeb95523a6)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 23.1.5 Win app, but this is really about diagrams.net 2.4.0.1 (?)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome 122.0.6261.95 or Edge 122.0.2365.66 - no difference
 

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
Yes

**Additional context**
If I try sharing a diagram, similar to issue [#3758](https://github.com/jgraph/drawio/issues/3758) I also only get the "Download" option after being redirected to OneDrive, not "open" as the OP of that issue.

**Comment by davidjgraph** [comment]
OneDrive doesn't support opening third-party apps in the way Google Drive does. The only option is to open within app.diagrams.net.

**Comment by Floriszz** [comment]
The workaround I found for this is:
1) open the draw.io stored in Onedrive/SharePoint in app.diagram.net from app.diagrams.net
2) right click on the page tab on the bottom and choose Link....
3) Create a view and/or Edit link.
4) Click new/create link in Onedrive/SharePoint in the same folder or other folder where you saved your draw.io file and paste the the created link from step 3.
5) now you can single click from OneDrive/Sharepoint to open a draw.io file in the browser(app.diagram.net) and also share this link.

**Comment by Naroleptic** [comment]
Thanks! Ended up going back to gdrive for various reasons, but appreciate
you taking the time to get back to me on this!

All the best!

**Comment by callumgare** [comment]
@Floriszz  I'm trying to follow your steps but I can't see a "Link" option in the menu for the page tab at the bottom of window:

![Image](https://github.com/user-attachments/assets/c6598695-f402-4423-9782-86d4eb3632b1)

Should I be seeing "Link..." here?

**Comment by Floriszz** [comment]
@callumgare , could it be you did not go through step 1. It is essential you open the drawio file, that is saved in onedrive/sharepoint from app.diagrams.net.
I see that I missed the 's' in diagrams.
I will try to correct it.

**Comment by callumgare** [comment]
Yep, I did that by opening though here:
![Image](https://github.com/user-attachments/assets/a2033ea9-1e37-4a8e-9b1f-a65645e1adcd)

I think I've just worked out the issue though. Looks like it's moved into the file menu:
![Image](https://github.com/user-attachments/assets/6725667f-49e0-436a-8430-b654eb7f7124)

I can't see a view option to create a "view and/or Edit link" anywhere but under the edit option you can select custom and that looks like it'll create a link that will attempt to open the file from the onedrive location if someone attempt to edit the document. (I'm waiting on approval from our IT department to approve the required onedrive oauth request in order to confirm that's how it works but seems like it's meant to work that way. The wording in the UI could definitely be improved to make it clearer though)

![Image](https://github.com/user-attachments/assets/e1cc149e-9228-4403-944f-2c505904911c)

**Comment by Floriszz** [comment]
@callumgare , I think you are right! Although I can't test it anymore, while my current environment does not allow the DrawIO authentication for SharePoint. When I test it with personal Onedrive and/or Github, I don't see the 'Link...' menu option by right click on the page tab either. So it is moved to the main menu for all, or it just works for Onedrive for Business/SharePoint(after the allow by System Admin is done for DrawIO integration).
After the System Admin has allowed DrawIO take note that the integration can be tricky with asking you to Allow Access multiple times. And even after aknowledging multiple times, you have to go back some steps sometimes to do it again to finally be able to browse you SharePoint libraries.
Success! I still think DrawIO is far more user friendly than the MsVisio I'm now fed up with for work.
