### ISSUE TITLE
Misleading translation of 'reverse' in Dutch

### ISSUE THREAD

**Issue by anneb** [jgraph/drawio#4232]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
The translation of "reverse" to Dutch is currently "Ongedaan maken" which has the very misleading meaning of "Undo". In the context of drawio "reverse" is used as "turn around in opposite direction" which in Dutch should be translated to "Omdraaien"

**To Reproduce**
1. Go to 'https://draw.io' in a Browser set to Dutch language
2. Click on 'Nieuw diagram aanmaken', create "Blanco Diagram"
3. Add a single direction arrow, click tab "Ordenen"
4. A button "Ongedaan maken" (meaning "Undo") appears

**Expected behavior**
A button "Omdraaien" should appear

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version x.y.z
23.0.1

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Browser Version 122.0.6261.95

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
