### ISSUE TITLE
PDF export returns error (502 Bad Gateway, 1033 Argo Tunnel error)

### ISSUE THREAD

**Issue by nmook** [jgraph/drawio#4233]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
PDF export returns either
"Error!" 
or
"502 Bad Gateway
An error occurred while opening a stream to the origin."
or
"Error 1033
Argo Tunnel error"

**To Reproduce**
1. Create any diagram, can be empty
2. Click on 'File' > 'Export as' > 'PDF...'
3. Make any export configuration and click 'Export'
4. Leave 'Where' to 'Device' and click 'OK'
5. See error

**Expected behavior**
A PDF download of the diagram being started.

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/28782867/eafb1bf3-9619-4547-a003-212f899f15e0)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 24.0.1

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Browser Version 122.0.2365.66 (Official build) (64-bit)

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-yes

**Additional context**
Monday 2024-03-04 10:00 GMT PDF export still worked, several hours later it stopped working. One day later, it's still broken.

**Comment by davidjgraph** [comment]
This is now resolved, thanks for report.
