### ISSUE TITLE
Drawio page as background in other page fails to show shapes (+ More shapes graphics)

### ISSUE THREAD

**Issue by tolleif** [jgraph/drawio#4239]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**
1. Create a new blank Drawio diagram. 
2. In Page-1 insert Shape by clicking in lower left blue button "+ More Shapes"
3. Select random library i.e. "Active Directory" and set check box
![OpenShapes](https://github.com/jgraph/drawio/assets/17848561/bb277fdf-b743-4986-9d90-7692b3c5e4c6)
4. In shape pane to the left find the new Active Directory and insert the first symbol in the Page-1
![insert shapes](https://github.com/jgraph/drawio/assets/17848561/c16ef620-a430-4ad3-9e00-70d680200cf1)
For comparison insert a rectangle and and image by just dragging and dropping a PNG file into the Page-1

5. Create a new page "Page-2"
6. In the right pane click on Background Change button
![background change](https://github.com/jgraph/drawio/assets/17848561/a5c6847d-e6b1-41f3-85a5-aaa22bd4a5ec)

7. Select Page-1 as background page
![background page](https://github.com/jgraph/drawio/assets/17848561/422a6673-d397-4da3-aff1-74a4b4fea94e)

8. The Page-1 is shown. The rectangle and the PNG image looks fine. But the Shape is not shown properly.
![shape not ok](https://github.com/jgraph/drawio/assets/17848561/5843e613-ee70-42d0-8dcf-d1eeec51754c)

9. One Page 1 the properties in a shape is a path
![broken image properties](https://github.com/jgraph/drawio/assets/17848561/816dd269-e6ce-49b3-a371-6d1967306bc3)
![image path](https://github.com/jgraph/drawio/assets/17848561/372d3c87-4598-41e6-8ca1-1a68616d8b38)

10. The PNG image that works fine does not have a reference but the whole image b64 encoded
![PNG image property](https://github.com/jgraph/drawio/assets/17848561/13424086-28de-4353-b837-48bcb425b869)

**Expected behavior**
I was expecting to see everything I can see in Page-1 identically in Page-2

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version v23.1.5

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2

**Comment by davidjgraph** [comment]
Fix in 24.0.3.
