### ISSUE TITLE
Math typesetting rendering problem related to scrollbars

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#424]
Issue reproduced in Chrome Version 73.0.3683.103 (Official Build) (64-bit)  and Incognito mode.
Tick/untick Scrollbars (View > Scrollbars) affects math typesetting rendering.

Performed steps:
1. Open draw.io online
2. Tick Math typesetting
3. Drag&drop a file - all render well on both pages (after a few seconds)
4. Page1 - View > Scrollbars unticked
nothing changes but when switched to page2 and back to page1 -  everything revers back to plain text on page1

The used file and video are in ticket 12446.

**Comment by alderg** [comment]
Thanks for the report, this will be fixed in the next release.
