### ISSUE TITLE
Update GCP Icons

### ISSUE THREAD

**Issue by KatTraxler-trust** [jgraph/drawio#4240]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The current GCP icon for draw.io is out of date.

**Expected behavior**
Please include with draw.io the latest set of GCP icons

**Additional context**
The latest PNG and SVG Icons can be found [here](https://cloud.google.com/icons/?hl=en)
Many services, such as binary authorizations and assets inventory are in the official icon pack but not available in draw.io

**Comment by nprime496** [comment]
+1

**Comment by egrimate** [comment]
Implemented.
