### ISSUE TITLE
Mathematical Typesetting stops working after Zoom

### ISSUE THREAD

**Issue by david-gottschalk** [jgraph/drawio#4242]
### Preflight Checklist
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Huge fan of your software here, started writing a lot of LaTeX mathy stuff in drawio due to the excelent interactivity and flexibility unoptainable from static compilation but I recently (beginning of this week) noticed that:
After zooming, the Mathematical rendering temporarily turns of and stays of until a new event other than zooming or panning occures.

**To Reproduce**
1. Open an new draw.io tab
2. Create a new file (save to device)
3. Enable `Mathematical Typesetting`
4. Type some `\(\LaTeX\)` equations
5. Zoom by any means
6.  "Updating" the view by any interaction other than zooming or panning (i.e., dragging the misbehaving element or creating a new element) temporarily fixes the rendering until the next zoom event.

**Expected behavior**
Previously, the Mathematical rendering would stay on consistently.

**Screenshots**
https://github.com/jgraph/drawio/assets/62221909/42821f64-f1c9-40b1-b5ba-36e534b05bcc

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 24.0.2

**Desktop (please complete the following information):**
 - OS: Arch 
 - Browser: Chromium
 - Browser Version: 120.0.6099.109

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

Thanks and have a great day!

**Comment by davidjgraph** [comment]
Fix in 24.0.3.
