### ISSUE TITLE
PLUGIN EXPLORE - "Explore from here" view mode does not behave consistently with layer and tag filtering

### ISSUE THREAD

**Issue by toblockornot** [jgraph/drawio#4243]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When using "explore from here" shapes and edges which were previously filtered / hidden will reappear instead of staying as per the set filtering mode.

**To Reproduce**
1. Open [this link](https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&p=ex&layers=1&nav=1&title=explore_layer_tags.drawio#R7Vpbk5s2FP41fswOQtz82L00bSedpON2kn0UIAOJbLmyfKG%2FvgLERdxhvY43E%2B%2FsGB0d3fjO%2BfQhvIAPm%2FN7hnbhn9THZKFr%2FnkBHxe6DizDFl%2BJJc4sjmNlhoBFvnQqDavoPyyNmrQeIh%2FvFUdOKeHRTjV6dLvFHldsiDF6Ut3WlKij7lCAG4aVh0jT%2BjnyeSitwFqWFb%2FhKAjl0I4uF7xBubNcyT5EPj1VTPBpAR8YpTy72pwfMEluXn5fsna%2FdtQWE2N4y8c08P4wvPeM%2F7vCNPr7dL8if%2F3%2B9E72ckTkIBe80C0i%2Brv3o6O4DJLL3OQ2DKxuEcM3vIStrzN83hHKcAIOoxvxFeKk1N1fpTMXed8CRg9bv38wxQS3NErCCAVdjVK4eJzHgLiPItxE4f4URhyvdshLak4i4oUt5BsiSkBcriNCHqhYTdoOrs3kL7HTLa%2FYs4%2Bw7zmj33Clxko%2FxRyOmHF87sQbFFEk0g%2FTDeYsFi6ygbGUgSczDziyfKrEcR6cYTWEpQ3J1AmKrsvoEhcywCYEm9EINuwHCfBgFrR1lERfK1mkjIc0oFtEnkrrfdobTmaoiVLp84HSnUTwK%2BY8liyEDpyq%2BGZ45TygF7NIl9GLkpgpPTAP99wdXbIbYgHmQynbRJ1hgnh0VOfRBqFs%2BolGYoalC12v92LcOsbFCPNh1xuwCyrczce9PaUnZbQaCW8pq4Fdy%2BrlyKy2pmf1P3vMPrpfk21V1whyMVGyFqL5WIjqfb7f6EMBtKzcERlwP1DeO1fK%2Bw6QRbGC8yjc3XbcBaZgHOaZ5yDuQPvewAswWfxFtk8Lz9Wax3O16jHOS%2BeIf6lcJ220O1OWykZJodrmE2aRgAszaasRj29ixzfaCMbRXZgSjBqo8G0Gatr0F8ZQXHHYJdvVvmX%2FytWOo%2FKiAU1VDQ%2F4C0MtSbIZjNwJJ2RRvvlB8d%2Fc7F45pZzejMqmBh%2B9mEQicRgc3hzdLMU%2BuIWhWNLHAxfd4JxDsxwD5qzAvsDOaWoq4rBND2stOycA07fOlngY%2BUDWfCKTtKu30e4tquSCNIvCs0KTA6RZEOVzpaadNL0DO6YzffVN2rpl7nP0miaEtZOAmr8NXui%2F1F%2FClSMTAXYlgtGmO91OuXmBx4W3LjHBtZ4t5z1IGK3MNgnQy2tP4za152ganaA9b0xnXi1a5wlNsyY0%2B7mz7g70fl1qak6f%2FwV06Uj67T61MX6e2kzVno2z2Nc7tBkHr9lAl6AYs8u8VLA7JWzbzp0OXD0M%2FP6bcS12MBCUaLfFyNKyIZpNiH3I3IwifVGYWZ0k0vaeaTASLsEhId24h%2F1k%2FhgRA6N4ohvzTvKwrRp5WCPZozBeHFfQBDbXcl4XsK%2BJ6lXl2J1tKIrsTltaQ6osKQ0c712fZToj7p1YkwYljc99sST7skCrXip6yIhONuoTRvZSzQLHUTvKmLDR0VR9ZxmT9F3dfVDf1ZfRp%2B8u85ZOFMtfGWTu5W814NP%2F) to load the test diagram in viewer mode or edit mode (diagram is embedded in link url)
2. The Test diagramm should open: 
![explore01](https://github.com/jgraph/drawio/assets/162711464/21df85c7-369c-4163-91f1-a16880c3e5eb)

3. Click on 'shape 1' to test explore mode to see 4 shapes around it (as expected)
4. Press "Esc" to go back to normal view mode
5. Set layer: Hide layer 1
6. Shape 2 and all edges on layer1 are hidden in "normal viewer mode": 
![explore02a](https://github.com/jgraph/drawio/assets/162711464/982d1c46-b068-4e94-a685-a7296f3fd377)

7. Click on shape "explore from here"
8. All 4 surrounding shapes (including shape 2) and all edges on layer1 are displayed again --> Consistently I would expect those elements to be hidden in explore view as well --> bug 1, layer filter does not work in explore mode for shapes and edges 
![explore02b](https://github.com/jgraph/drawio/assets/162711464/9ef3f0f2-403a-4e78-9ade-39bd09fcda55)

9. Click "Esc" to go back to normal view
10. Click on tags and hide tag 1
11. shap 2 and shap 3 including all edges are hidden in "normal viewer mode"
![explore03a](https://github.com/jgraph/drawio/assets/162711464/de7b8777-338c-4b7f-ba62-deb5c329f1cc)

12. Click on shape "explore from here"
13. Shap 3 (tag1) remains hidden but edge 4b (tag#1) is still displayed and shown over the other edges to shape 4 --> bug 2: Filtering of tags does not work for edges in explore mode.
![explore03b](https://github.com/jgraph/drawio/assets/162711464/b651eb50-1316-4e18-a20c-5869822a6be3)

**Expected behavior**
I expect the filtering of shapes and edges to behave consistently between "explore from here" mode and normal viewer mode.

**Screenshots**
see above

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.0.2

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Browser Version [e.g. 22] 122.0.6261.112

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**
I have inspeceted chrome browser for developer console but did not see any logged error when trying to reproduce.
I expect the explore from here plugin was not developed considering above feature combinations.

**Comment by davidjgraph** [comment]
Fix in 24.0.5.
