### ISSUE TITLE
Embedded Images Not Included Upon Exporting to PNG (or JPEG, or SVG)

### ISSUE THREAD

**Issue by lexperiments** [jgraph/drawio#4244]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I have a particular diagram that will not export correctly as a PNG. While most of the diagram successfully exports, certain images within the diagram are not actually included in the PNG. This leads to an exported PNG that looks particularly empty (see screenshots). I have also tried exporting as JPEG and SVG; none of these exports correctly export the images within the diagram. The export to HTML and URL did work correctly, but I need this to be a PNG. 

**To Reproduce**
1. Go to https://app.diagrams.net/?title=Proposal%3A%20Asraport%20Missions.drawio#G1NK1gMqgZ4PDCDa_CgnzlgnvmxIfmIGwN#%7B%22pageId%22%3A%22Gn9G_yjAVDiZtvJYlJvF%22%7D 
2. Export as PNG, JPEG, or SVG
3. See that the embedded images are not included in the exported PNG

**Expected behavior**
I expected the embedded images to be included in the PNG export.

**Screenshots**
What the chart looks like when editing:
![image](https://github.com/jgraph/drawio/assets/44708360/df69a98c-3acd-48d0-8ccd-b789d983603c)

The exported PNG:
![Proposal_ Asraport Missions drawio](https://github.com/jgraph/drawio/assets/44708360/db10bb8d-57c0-468e-b397-7b8d24a9d2c0)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.0.1

**Desktop (please complete the following information):**
 - OS: macOS Monterey Version 12.5.1
 - Browser: Chrome
 - Browser Version: 122.0.6261.112 (Official Build) (arm64)

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- Yes

**Additional context**
None

**Comment by davidjgraph** [comment]
How do we access the diagram?

**Comment by lexperiments** [comment]
Also, augh! So sorry. I just experimented a little more with this, and solved the problem.

Fix: I had dragged the embedded images onto the diagram from a URL. These images showed up in the diagram, but not in the exported PNG. Importing the images from my device, on the other hand, makes it so that they show up in the exported PNGs. 

Closing now!
