### ISSUE TITLE
Vectorized Images

### ISSUE THREAD

**Issue by alithorpe** [jgraph/drawio#4246]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I would like to upload an image of another diagram and convert the objects in the picture to vector graphics/shapes that I could further edit. 

**Describe the solution you'd like**
I'd like to turn images into editable shapes, as if I were working on the original file I uploaded. 

**Describe alternatives you've considered**
I've tried converting images to .svg and .AI using online conversion websites. Nothing free has worked.

**Additional context**

**Comment by davidjgraph** [comment]
That is PhD for someone, but a little complex for this project...
