### ISSUE TITLE
Distribute and snap-to-grid no longer work

### ISSUE THREAD

**Issue by bennyschmidt** [jgraph/drawio#4249]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
> Among many other issues, "Distribute Horizontal/Vertical" and "Snap-to-Grid" Arrange functions no longer work. It seems like every day a new feature is breaking in draw.io when about ~1 year ago this thing was awesome. I don't know what happened, this app is falling apart. Very slow, few things work anymore.

**To Reproduce**
Steps to reproduce the behavior (distribute):
> 1. Select a shape
> 2. Make 3 of them
> 3. Try to distribute them
> 4. See that they are not evenly spaced

**To Reproduce**
Steps to reproduce the behavior (snap-to-grid)
> 1. Select any group
> 2. Click "Snap-to-grid"
> 3. Watch it snap off the grid by a few pixels 

**Expected behavior**
The shapes should acknowledge the grid and Arrange tools should work like they did ~6 months (or 1 year) ago. The app is incredibly slow and clunky now, just falling apart day-by-day.

**Screenshots**

**Desktop - Web (please complete the following information):**
 - OS: Ubuntu 22
 - Browser: Chrome 
 - Version: 122.0.6261.94 (Official Build) snap (64-bit)
 
**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- Yes

**Additional context**

**Comment by davidjgraph** [comment]
What's the version?

**Comment by bennyschmidt** [comment]
> What's the version?

It's the web version as I indicated in the report. Are there multiple web versions? Should be v24.0.4.

**Comment by davidjgraph** [comment]
You deleted the version field and there's nothing to indicate it's web in your report. Please don't delete parts of the template.

Any errors in the browser console? Any browser extensions?

For clarify, I don't have to help you, if you carry on this tone I won't.

**Comment by bennyschmidt** [comment]
> there's nothing to indicate it's web in your report

![image](https://github.com/jgraph/drawio/assets/45407493/c1c06d16-4c7e-45b6-b73f-227237281159)

I removed the entire "mobile" section because I'm not on a mobile device, how is this not a clearer indication that I'm no **Desktop - Web** ??

In any case, do you have a solution or focusing only on peripherals? What a joke

**Comment by davidjgraph** [comment]
And that is how you get banned from this project for future readers.
