### ISSUE TITLE
Disable Auto-Save

### ISSUE THREAD

**Issue by bennyschmidt** [jgraph/drawio#4250]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
> When choosing the "Device" storage option, draw.io will save to device after every single action performed, rather than allowing the user to click "Save" / "Save as" like they would with any other application, including browser-based applications (e.g. Photopea). This slows down my OS while I'm working on the diagram, causing excess disk writes, network activity, CPU cycles, and increased memory usage.

**Describe the solution you'd like**
> Like any other application, the file should not save until the user clicks "Save". If some users want an "Auto-Save" option, that option should be exposed in a menu or setting, not be the default as no other app works that way so it's unexpected.

**Describe alternatives you've considered**
> What I do now as a workaround is I choose "Decide Later" for storage. But this isn't ideal for me because I have to build the entire diagram in "unsaved" mode potentially losing changes, and only when I'm ready to export the final do I use the "Save" feature. It's the only way I know how to both save my changes and not have my browser constantly downloading files.

**Additional context**

**Comment by alderg** [comment]
Try disable autosave:
<img width="242" alt="Screenshot 2024-03-11 at 17 08 54" src="https://github.com/jgraph/drawio/assets/921200/64a09e50-00bc-4abe-839b-5942d7e70e83">

**Comment by bennyschmidt** [comment]
> Try disable autosave: <img alt="Screenshot 2024-03-11 at 17 08 54" width="242" src="https://private-user-images.githubusercontent.com/921200/311776264-64a09e50-00bc-4abe-839b-5942d7e70e83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNzM2ODAsIm5iZiI6MTcxMDE3MzM4MCwicGF0aCI6Ii85MjEyMDAvMzExNzc2MjY0LTY0YTA5ZTUwLTAwYmMtNGFiZS04MzliLTU5NDJkN2U3MGU4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQxNjA5NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2ZmNTYzYzA5ODYxOTA0YTc5ZmIyMjdlNTA4YzVkZjNiMWZjMjRiNTEwOTYxMjUzNDA3NGJiNjI4ZTE5NWE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ynzv9rvCBjeYNcJ0sle6nEHCqgjPt6oPaIrKU9GcvjI">

I don't have this tab, and can't seem to locate a toggle for enabling it.

![Screenshot from 2024-03-11 09-10-01](https://github.com/jgraph/drawio/assets/45407493/0ea198cd-bf60-48eb-810c-52bd3c68286e)

Here's my `View` menu:

![Screenshot from 2024-03-11 09-10-51](https://github.com/jgraph/drawio/assets/45407493/177ab9fd-43d5-477a-91a3-dbed0b6033b1)

And my `Extras`:

![Screenshot from 2024-03-11 09-11-04](https://github.com/jgraph/drawio/assets/45407493/547141c0-3534-43a8-973d-b74412139a6c)

(Note: Clicking `Edit Diagram` opens a text editor)
