### ISSUE TITLE
Length Placeholder does not work

### ISSUE THREAD

**Issue by JingleheimerSE** [jgraph/drawio#4254]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Attempting to use %length% Placeholders does not work. Tested primarily with the Floor Plan template.

NOTE: %height%, %width%, and %length% appear to have been added with 21.8.0 according to #3327 but %length% still does not work in 

**To Reproduce**
1. Create a new floor plan
2. Drag a wall onto the plan
3. Right click the wall, and select Edit Data..., then check the Placeholders box and hit Apply
4. Edit the label of the wall and enter "Height: %height%, Width: %width%, Length: %length%, Date:%date%"

**Expected behavior**
All documented placeholders (https://www.drawio.com/doc/faq/predefined-placeholders) should populate

**Screenshots**
Using online 16.6.4 version (which may be expected to not function due to feature being added in 21.8.0)
![image](https://github.com/jgraph/drawio/assets/15690523/2928e06c-9955-4f96-98e5-0246b6bab81b)

Using Desktop version 24.0.4 (which should function)
![image](https://github.com/jgraph/drawio/assets/15690523/91226bbd-7dc8-45b7-abb7-479fcf9a719c)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 16.6.4
- draw.io Desktop version 24.0.4

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Browser Version 122.0.6261.112

**Smartphone (please complete the following information):**

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**

**Comment by davidjgraph** [comment]
Length is only for edges, not shapes.
