### ISSUE TITLE
Error saving to Google Drive or OneDrive

### ISSUE THREAD

**Issue by GuttoSP** [jgraph/drawio#426]
Hello.

I downloaded the files at https://github.com/jgraph/drawio and uploaded it to my CPanel hosting. I then accessed the URL https://www.concurseiros.club/mapa-mental/, but I can not choose the save option in Google Drive or Onedrive. Only works when I choose to save the files in "Locally on device". When I click on the Google Drive icon, the page is redirected to https://www.draw.io/mapa-mental/, which displays the message "Error: Not Found". When I click on the OneDrive icon the message "invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application." 

How do I set up Google Drive and OneDrive to use draw.io in my hosting? 

Thank you.

**Comment by ashrafteleb** [comment]
draw.io is not entirely static, it has some dynamic components (including Google and OneDrive integration)

So, please refer to https://github.com/jgraph/docker-drawio/tree/master/self-contained
