### ISSUE TITLE
Font mismatch when inserting diagrams into Google Docs by Google Workspace add-on

### ISSUE THREAD

**Issue by moscii** [jgraph/drawio#4265]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I insert a diagram into Google Docs using the Workspace add-on, the image is displayed in a different font than drawio. If you use "Copy as Image" on app.diagrams.net and paste the diagram into Google Doc, the font will be the same as drawio.
Also, it occurs both in drawio's shape with text and in the PlantUML diagram embedded in drawio.

**To Reproduce**
1. Create a diagram with shapes containing text ("新" in Japanese) on app.diagrams.net.
<img width="320" alt="Screenshot 2024-03-16 at 2 29 25" src="https://github.com/jgraph/drawio/assets/10438213/b2a865c8-5e6d-47ef-a6d8-bb7d2e1c9d51">

2. Insert the PlantUML diagram into the drawio diagram using the following steps. "Arrange > Insert > Advanced > PlantUML..." The source code of PlantUML is as follows.

```puml
@startuml
listfonts 新
@enduml
```

<img width="886" alt="Screenshot 2024-03-16 at 2 31 44" src="https://github.com/jgraph/drawio/assets/10438213/f7c866fa-0106-436d-89eb-995fd048e764">

3. Save the diagram to Google Drive
4. Create a Google Docs deck, with the Diagrams.net add-on installed.
5. Choose "Insert Diagram..." for the add-on, and insert saved diagram.

**Expected behavior**
The image shown in the Google Doc should match the font shown in app.diagrams.net
<img width="712" alt="Screenshot 2024-03-16 at 2 47 35" src="https://github.com/jgraph/drawio/assets/10438213/cd58e492-3e18-42da-9b00-94c440e77bec">

**Screenshots**
The image in Docs is using a different font. I'm unsure if this is a Theme font for the Doc, or a default font.
<img width="573" alt="Screenshot 2024-03-16 at 2 49 40" src="https://github.com/jgraph/drawio/assets/10438213/868e8198-dcde-43be-9fdb-633e04cc5710">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version v24.0.6

**Desktop:**
 - OS: Mac/Windows
 - Browser Chrome
 - Browser Version 122.0.6261.129 (Official Build) (x86_64)

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- no; need to be logged into Google.

**Comment by davidjgraph** [comment]
What format is the PlantUML output in?

**Comment by moscii** [comment]
The output format is .drawio or .drawio.svg.

**Comment by davidjgraph** [comment]
What is the font family name of the correctly rendered text please?

**Comment by moscii** [comment]
The font that can correctly render the text of shapes on drawio is "Sawarabi Gothic" from Google Fonts. However, the drawio font does not seem to have any effect on the embedded PlantUML diagram.

**Comment by davidjgraph** [comment]
This is expected. We host PlantUML on AWS lambda which provides limited scope for custom fonts.
