### ISSUE TITLE
[Bug] Misaligned text and wrong cropping when exporting PDF

### ISSUE THREAD

**Issue by tjadevries** [jgraph/drawio#427]
I have a diagram with centered LaTex mathematical typesetting (attached). When exporting the diagram to pdf with the crop option ticked, some text elements (x-hat, script O and y) are shifted downward in the pdf and a second "page" appears. When exporting the diagrom without the crop option ticked, all text elements seem to be placed correctly; there is an extra page, though. The extra pages are not so much of a problem, but the misalignment is a pain.
This might be related to the (closed) issue #80 
[Blockdiagram2.zip](https://github.com/jgraph/drawio/files/3162854/Blockdiagram2.zip)
[Blockdiagram2-withcrop.pdf](https://github.com/jgraph/drawio/files/3162857/Blockdiagram2-withcrop.pdf)
[Blockdiagram2-nocrop.pdf](https://github.com/jgraph/drawio/files/3162858/Blockdiagram2-nocrop.pdf)

**Comment by HemersonTacon** [comment]
This started to happen to my diagrams too. I noticed that it happens by just having the mathematical typesetting active, there is no need to really add some text that uses this setting. The extra page thing is a huge problem for me since I am creating those diagrams to embed into my dissertation, which is in latex.

**Comment by carstenhag** [comment]
I'm getting the same issue :(

**Comment by davidjgraph** [comment]
What about print to PDF locally as a workaround, does that avoid the extra pages?

**Comment by carstenhag** [comment]
@davidjgraph Hey, when printing via the Print menu, there is no crop option. I get a big A4 pdf with a small diagram, which I want to avoid.

**Comment by davidjgraph** [comment]
OK, we'll get round to the issue, eventually, it's just not burning enough of a hole, just yet (plus, it's too hot to work). For people with low volume and an urgent need, export without cropping and use an online cropping tool for now, https://www.google.com/search?q=crop+pdf+online

**Comment by carstenhag** [comment]
Agreed on the too hot for work. Thanks!

**Comment by tjadevries** [comment]
For some reason, I cannot print using the offline draw.io.
In the online version, for the Blockdiagram2 example I can get a correct full-page pdf.
I then created a "full page" drawing, see attachment. If I print that page to pdf, something interesting occurs. In the print dialog, I can set the scale in 'more settings'. Scale 112 is still ok; scale 113 results in a changing position for x^hat..
[Blockdiagram2a.zip](https://github.com/jgraph/drawio/files/3432300/Blockdiagram2a.zip)

**Comment by fjnn** [comment]
I have the same issue with png and jpeg options as well. Any updates?

**Comment by dougsouza** [comment]
I got around this by resizing the canvas and exporting without crop. When setting the canvas to a custom size, a light dashed line appears, it represents the boundary between pages, so just set the canvas size to be one page long.

**Comment by alderg** [comment]
This is a known issue. Apparently, a component in the PDF rendering engine tries to be clever and avoid page borders for text boxes. Keeping text boxes away from page borders and/or using textOverflow=fill/width for math elements (as shown in the image) might help.
![nnFKMbFv7Rnoc8cp35PDRNkRq5GujBGvvg](https://user-images.githubusercontent.com/921200/67952682-f3589300-fbed-11e9-9a3a-25256407513a.png)

**Comment by alderg** [comment]
Misaligned text fixed for PDF export in 12.5.0.

**Comment by spacetime-labs** [comment]
Hi, this is happening to me on desktop version 29.0.3 for MacOS.
Mainly for Latex text inside circles, it is being shifted to the left.

**Comment by davidjgraph** [comment]
Please file a new issue, the original issus was fixed.
