### ISSUE TITLE
When drawing with the mouse the press on the mouse wheel does not let you finish drawing

### ISSUE THREAD

**Issue by cuakinya** [jgraph/drawio#4278]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
When using the feature of drowing shapes with the mouse if you click on the mouse wheel then you can't stop drawing even if you click the wheel|right|left button another time or click on the "stop drawing" button.

**To Reproduce**
1. Go to 'Drowing'
2. Click on 'mouse wheel'
3. Move your mouse
4. See drawing follow you mouse
5. Click any (do not know which) button to stop drawing
6. See that you don't stop

**Expected behavior**
You click on the mouse and stop drawing?.

**Screenshots**
Does not show problem

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.0.6

**Desktop (please complete the following information):**
 - OS:Windows
 - Browser Chrome
 - Browser Version 122.0.6261.129

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
yes

**Additional context**
Some times the shape appears you drow this way appears on the screen but you can't delete it. It moves not by rules of scaling and can disappear for some time. Guess it is a cache problem.

**Comment by davidjgraph** [comment]
Fix in 24.0.8.
