### ISSUE TITLE
Add "Edit Shape" to Right-Click menu of Custom Shapes

### ISSUE THREAD

**Issue by Peeeet** [jgraph/drawio#4284]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Currently it can take up to five clicks and a modal change (switching to the Style tab) to get to the "Edit Shape" dialog of a pre-existing Custom (aka `stencil()`?) Shape.

**Describe the solution you'd like**
When right clicking on an object that was created with the "Shape..." option in the create object tool (plus sign on the toolbar) there could be an option for "Edit Shape" to bring up the same dialog that appears when you have the object selected and choose "Edit Shape" from the Edit dropdown menu in the Style tab of the right side panel (in classic theme)

**Describe alternatives you've considered**
As far as I can tell, the only way to edit a custom shape in this way is through the dropdown in the Style tab.  I thought I remember it being in one of the other menus but I keep accidentally opening "Edit Geometry" and "Edit Diagram".

**Comment by alderg** [comment]
Added in the Simple theme.
<img width="242" alt="Screenshot 2024-04-23 at 07 27 22" src="https://github.com/jgraph/drawio/assets/921200/12e0c7ca-0071-4cbf-949e-8eb7ccc0853b">
<img width="539" alt="Screenshot 2024-04-23 at 07 27 04" src="https://github.com/jgraph/drawio/assets/921200/704ff67d-4615-4035-bf78-f851a08fd0bd">
