### ISSUE TITLE
Autosize property set on the "Configuration" template is being ignored

### ISSUE THREAD

**Issue by euu2021** [jgraph/drawio#4285]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Autosize property set on the "Configuration" template is being ignored.

**To Reproduce**
1. Go to 'Configuration'
2. Set this Config:
```
{
  "defaultFonts": ["Times New Roman"],  
	
  "defaultVertexStyle": {
    "fontFamily": "Times New Roman",
	"fontSize": "50",
	"autosize": "1",
	"strokeWidth": "10",
	"strokeColor": "#f2a60f"
  },
  "defaultEdgeStyle": {
    "fontFamily": "Times New Roman",
    "strokeColor": "#09e6cf",
	"curved": "1",
	"fontSize": "50",
    "strokeWidth": "10"
  }
}
```
3. restart the app
4. create a rectangle
5. Every property is correct, but Autosize is disabled

**Expected behavior**
Autosize be enabled.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version v24.0.7

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Browser Version  122.0.6261.129

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Comment by davidjgraph** [comment]
Try 24.2.9.

**Comment by euu2021** [comment]
> Try 24.2.9.

It's working fine. Thanks!
