### ISSUE TITLE
The background of the artboard becomes black. 

### ISSUE THREAD

**Issue by tuvalusoftware** [jgraph/drawio#4293]
When I create a new diagram the background of the artboard turns black. 
Also in files I start working on when the background is white suddenly the artboard turns black. 
The background of the exported image is always white. 

see image below. 

![Screenshot 2024-03-24 at 1 00 00 PM](https://github.com/jgraph/drawio/assets/593984/f5e1e9a7-1898-4c43-ae9a-2678e6cd035f)

### Preflight Checklist

* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version x.y.z

**Desktop (please complete the following information):**
 - Browser Version [e.g. 22]

**Smartphone (please complete the following information):**

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-

**Additional context**

**Comment by tuvalusoftware** [comment]
why closed. This is not a feature request but a but report. I was hoping to get instructions on how to fix the problem

**Comment by davidjgraph** [comment]
Read the template text

**Comment by tuvalusoftware** [comment]
I don't find relevant template text. Besides that, new diagrams are created
with  black or white randomly randomly. That can't be me not reading
documentation

**Comment by davidjgraph** [comment]
In your original post "You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.".
