### ISSUE TITLE
Random uneditable paw icons appear and cover the diagram in browser

### ISSUE THREAD

**Issue by elb-bme** [jgraph/drawio#4294]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**

While editing a simple graph diagram in browser - first only the exported image, then the online editor's rendering as well - had various sized paw icons appeared on them ó, covering the diagram and making it impossible to read. 
I had a browser extension long ago, that I forgot the name of, with such a paw icon that was for collecting images, I couldn't even find it in the list anymore and I disabled a few others. So I don't know in what way could it still remain in the system to appear or cause problem. Before this operation, the diagram appeared in the editor at least without paws, it was only exported as an image full of them - after fiddling with the extensions, they appeared in the editor as well. It looks like this in another browser and private windows, moreover, the icons do not react to anything, the editor does not see them. When hovering over them with the mouse, it causes a shadow effect on their edges, but they are not clickable. It has been loading and exporting the chart this way ever since.

**To Reproduce**
1. Go to '...' https://drive.google.com/file/d/1CM5jfNEah-aGdSBUH_ftMBJZ47-EVldZ/view
2. Click on '....' open with draw.io
3. Scroll down to '....' diagram
4. See error: the paw icons cover the drawing and they are not removable

**Expected behavior**
The diagram is covered in paw icons.

**Screenshots**
Editable shared diagram in question: https://drive.google.com/file/d/1CM5jfNEah-aGdSBUH_ftMBJZ47-EVldZ/view
**draw.io version (In the Help->About menu of the draw.io editor):**  24.1.0

![vc_graph_contract](https://github.com/jgraph/drawio/assets/79838492/521c9820-7d52-4e0e-ace3-e94b082a1a1f)

- draw.io version 24.1.0

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari]: Chrome
 - Browser Version [e.g. 22]: Version 122.0.6261.131 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] realme 8i
 - Browser [e.g. stock browser, safari] chrome
 - Version [e.g. 22] 122.0.6261.120

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-yes

**Additional context**

**Comment by davidjgraph** [comment]
Totally cool and normal.

But, this is clearly the extension has messed up some images in your diagram. I'm afraid we can't be expected to clean up someone else's mess.
