### ISSUE TITLE
VsdConverter fails to import .vsd

### ISSUE THREAD

**Issue by ElijahShadbolt** [jgraph/drawio#4295]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Importing visio does not work.

**To Reproduce**
Open app.diagrams.net in Chrome web browser.
Create default untitled diagram.
Drag and drop a .vsd (Microsoft Visio) file onto the canvas.
An error popup box appears. "Error". "Unknown error".
JavaScript console says "Access to XMLHttpRequest at 'https://convert.diagrams.net/VsdConverter/api/converter' from origin 'https://app.diagrams.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."
net::ERR_FAILED

**Expected behavior**
it would import the visio file and display the diagrams.

- draw.io version 24.0.1

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Browser Version: 123.0.6312.59 (64-bit)

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**
I was trying to see the contents of the visio file without using Microsoft Visio, so I'm not sure if the file is corrpted or not.

**Comment by davidjgraph** [comment]
Worked OK for me just now with:

[architecture.vsd.zip](https://github.com/jgraph/drawio/files/14749879/architecture.vsd.zip)
