### ISSUE TITLE
Add support for OS high contrast

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#4296]
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/forced-colors

Windows has a high constrast mode. Window 10 has an on/off high constrast switch. Windows 11 has 4 themes to apply high constrast.

We don't have a windows 10 machine to test with, but we assume it's using forced-colors the same way the win 11 themes are.

The suggested solution is to ignore the OS attempts to change colours (as it messes up the UI) and to increase the constrast in the app when the media prop is detected.

The user can then switch light/dark within the app as required. [DID-11145]

[DID-11145]: https://drawio.atlassian.net/browse/DID-11145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by alderg** [comment]
<img width="1178" alt="Screenshot 2024-03-26 at 12 58 06" src="https://github.com/jgraph/drawio/assets/921200/68be2fdd-3bf9-4f36-a440-c84b975ebd7e">
<img width="1176" alt="Screenshot 2024-03-26 at 12 54 58" src="https://github.com/jgraph/drawio/assets/921200/026a136a-dcbc-46a0-879a-278bde6c9bd7">
<img width="1178" alt="Screenshot 2024-03-26 at 12 58 52" src="https://github.com/jgraph/drawio/assets/921200/d43bff3d-52d1-4657-bd82-61ac1860257b">
<img width="1178" alt="Screenshot 2024-03-26 at 12 57 04" src="https://github.com/jgraph/drawio/assets/921200/98044dc2-5179-4a9c-8f7f-acc1160de8db">
<img width="1178" alt="Screenshot 2024-03-26 at 12 57 49" src="https://github.com/jgraph/drawio/assets/921200/4adbcfe9-4b3e-4311-b493-06031f1d92ef">
<img width="1177" alt="Screenshot 2024-03-26 at 12 58 21" src="https://github.com/jgraph/drawio/assets/921200/a3b27865-fdcf-4f6a-8ce5-20ea55e300b9">
<img width="1178" alt="Screenshot 2024-03-26 at 12 58 38" src="https://github.com/jgraph/drawio/assets/921200/1ae8a5cf-0e96-43ab-aea0-28e461ad2c24">
<img width="1178" alt="Screenshot 2024-03-26 at 12 54 45" src="https://github.com/jgraph/drawio/assets/921200/689df136-abae-4091-bf53-8bb0b60210e5">
<img width="1177" alt="Screenshot 2024-03-26 at 12 52 35" src="https://github.com/jgraph/drawio/assets/921200/84072db6-139e-482a-bf80-466f778a7b4b">
<img width="1178" alt="Screenshot 2024-03-26 at 12 53 05" src="https://github.com/jgraph/drawio/assets/921200/3ff04c52-7898-44b9-8116-f7d75b80e85c">
<img width="1177" alt="Screenshot 2024-03-26 at 12 59 58" src="https://github.com/jgraph/drawio/assets/921200/c838c986-1f22-4eb6-aee6-df0164da2aac">
<img width="1177" alt="Screenshot 2024-03-26 at 13 00 07" src="https://github.com/jgraph/drawio/assets/921200/399a7199-2dd4-4d06-ba2d-2296dac299e2">
<img width="1179" alt="Screenshot 2024-03-26 at 12 51 38" src="https://github.com/jgraph/drawio/assets/921200/eeb23f94-19b5-4061-b729-ba8590bafe36">
<img width="1177" alt="Screenshot 2024-03-26 at 12 51 49" src="https://github.com/jgraph/drawio/assets/921200/1bc3f502-3f14-4c8a-a9ce-cb48e9af3c0a">
<img width="1178" alt="Screenshot 2024-03-26 at 12 59 35" src="https://github.com/jgraph/drawio/assets/921200/5098c6a3-1d1b-43d2-a2c3-d32e9842d1ce">
<img width="1179" alt="Screenshot 2024-03-26 at 12 59 44" src="https://github.com/jgraph/drawio/assets/921200/2da86c98-7324-4d13-b914-93e2e10e4dab">
<img width="1178" alt="Screenshot 2024-03-26 at 12 51 59" src="https://github.com/jgraph/drawio/assets/921200/d3e5ef23-f810-45cb-bc4d-8cba18d771ee">
<img width="1179" alt="Screenshot 2024-03-26 at 12 51 22" src="https://github.com/jgraph/drawio/assets/921200/a1d42d98-2442-4dfb-9132-7a58d77b09f2">
