### ISSUE TITLE
importing vsdx custom attributes cannot be displayed correctly

### ISSUE THREAD

**Issue by qizhq** [jgraph/drawio#4299]
Added custom attributes to the shape data in visio. import into draw selecting the shape edit data. The custom attribute values can be displayed, but the name display is incorrect
![1](https://github.com/jgraph/drawio/assets/80200776/33a35244-ab7b-4a17-bcbe-efe330b41646)
![2](https://github.com/jgraph/drawio/assets/80200776/445e37f1-b27d-4493-a892-df65c77e462c)

**Comment by davidjgraph** [comment]
Please provide an example vsdx file that demonstrates this issue.

**Comment by qizhq** [comment]
***@***.***
 
From: David Benson
Date: 2024-03-28 14:57
To: jgraph/drawio
CC: qizhq; Author
Subject: Re: [jgraph/drawio] importing vsdx custom attributes cannot be displayed correctly (Issue #4299)
Please provide an example vsdx file that demonstrates this issue.

**Comment by m-mohamedin** [comment]
Will be fixed in the next release
Thanks for the report
