### ISSUE TITLE
VSDX import failing in some cases

### ISSUE THREAD

**Issue by VirtualEvan** [jgraph/drawio#430]
We are getting blank pages when importing some .vsd/.vsdx files.
They are properly opening in Visio 365 and 2016.
We tried converting them manually with both of the applications and the result was the same.

Is there any known limitation about the content of the files in order to be imported?

A sample of the failing files:
[Plan 272-R-002.vsd.txt](https://github.com/jgraph/drawio/files/3177872/Plan.272-R-002.vsd.txt)
[Plan 272-R-002_conv365.vsdx.txt](https://github.com/jgraph/drawio/files/3177873/Plan.272-R-002_conv365.vsdx.txt)
[Plan 272-R-002_conv2016.vsdx.txt](https://github.com/jgraph/drawio/files/3177874/Plan.272-R-002_conv2016.vsdx.txt)

**Comment by VirtualEvan** [comment]
A coworker investigated a bit more about this issue.
He made some tests in Visio with the pages being used as background by other pages
It looks like removing these dependency between them allows the file to be imported by Drawio, but I have seen files where it works with the dependencies.

---

This is a case created by me where it worked with some particularities:
* Page1 is declared as background in the Page Setup -> Page Properties
* Page2 uses Page1 as background, contains more figures and is also declared as background
* Page3 uses Page2 as background and add figures
* Page4 uses Page1 as background and add figures

When imported in Drawio:
* Page1 doesn't exist
* Page2 doesn't exist
* Page3 is ok (contains both of the backgrounds and it's own content)
* Page4 is ok (contains it's background and own content)
* Additionally Page3 is renamed to Page1 in Drawio

So, it looks like the names are a bit messed up, and the "background pages" are not imported, but their content is imported in the pages where they were "referenced". Not sure if that's the intended behavior.

[multiplepages.vsdx.txt](https://github.com/jgraph/drawio/files/3191595/multiplepages.vsdx.txt)

**Comment by ashrafteleb** [comment]
Yes, your conclusion is correct, ("background pages" are not imported, but their content is imported in the pages where they were "referenced".)

In the next release, we will allow all pages to be imported

**Comment by bitking** [comment]
How do i import vsd or vsdx files?
In both cases when selecting an "open existing drawing" it will fail with the message.
"error on line 1 at column 1: Document is empty" or with "unknown error"

**Comment by VirtualEvan** [comment]
Are you using the online version?
We used to have that problem too, there is have an option "Import/Import from" in the "File" menu, it should work if you create a blank diagram and then import your vsdx/vsd

In any case, the "Open" option started working for Visio files some release ago, are you using the latest version?

**Comment by bitking** [comment]
I am using the latest self hosted version, as far as i could discover the following is true.

1. On the self hosted version you can only import .vsdx files, this is probably due to the fact that vsdx files are XML based and easy-er for 3rd party's to implement.
2. importing vsd files is only possible on the online environment of draw.io on www.draw.io using an converting api. (Due note that the files are then being processed by this organisation)

**Comment by davidjgraph** [comment]
We use a third-party library to convert vsd files. It's not open source, so we can't share it, plus the cost per server is USD10ks (per year).

If you want to convert from vsd to vsdx your best route is to use a powershell script on a windows machine that loads up the vsd and saves as vsdx.
