### ISSUE TITLE
C4 Shapes have superfluous characters in the technology field

### ISSUE THREAD

**Issue by rowan-trade** [jgraph/drawio#4300]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Some C4 shapes have erroneous charters in the technology section. This includes but not limited to the database shape.

**To Reproduce**
1. draw.io
2. click on shapes
3. select c4
4. drag database shape onto the page.

**Expected behavior**
Doesn't have the additional characters.

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/113126667/646b8fe1-bcbc-494f-8675-b2843c838326)
![image](https://github.com/jgraph/drawio/assets/113126667/12573954-1bdd-467a-9abb-0bffb2ae6f5f)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.2.0

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Browser Version: 123.0.6312.59

**Smartphone (please complete the following information):**

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- Yes

**Additional context**

**Comment by davidjgraph** [comment]
Fix in 24.2.1.
