### ISSUE TITLE
Exporting a large diagram: high zoom values not respected when exported image would have large dimensions

### ISSUE THREAD

**Issue by axefrog** [jgraph/drawio#4304]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

I'm using the latest version of the Windows 10 desktop version of the app.  Here's a zoomed out screenshot of the diagram I'm trying to export:

![image](https://github.com/jgraph/drawio/assets/298883/c20dd19f-e089-4ff7-a01f-6ac74810a6e3)

This is what it looks like at 300% zoom in the app:

![image](https://github.com/jgraph/drawio/assets/298883/b693e74a-e9d9-4044-9191-2ab10c6d9ea4)

Here I am about to export the diagram as a PNG file:

![image](https://github.com/jgraph/drawio/assets/298883/51d2aa30-5aa6-4944-a253-ec2372e3be03)

And this is what the same section in the 300% zoomed image above looks like at 1:1 scaling in the exported PNG. I've annotated the screenshot with comparison to what was expected:

![image](https://github.com/jgraph/drawio/assets/298883/129ea3bc-9634-4f8d-88dd-48e38b30da11)

Eyeballing things, it looks like the actual exported zoom value used is about 170%, which incidentally is a zoom setting I frequently default to while editing. Not sure if there is some correlation there that I've missed, but I suspect it's a coincidence.

I have also tested at zoom values lower than 170% and the exported scale of the image seems about right, so it seems like something in the app is capping the export zoom value for some reason.

**UPDATE:**

I tried the "Advanced" export dialog and noticed that the dimension inputs are highlighted in red if the width of the exported image will be >= 24056. This limitation seems to be set by the app, as it is not a limitation of PNG or JPG files. Why is the limitation there? Does it need to be? I can see that maybe it might be required on the server side for the browser app, but the desktop app shouldn't have this limitation. If my intuition about the limitation being to save server-side resources in the diagrams.net app, can the limitation be disabled for the desktop release? If so, I'm happy to open an issue for the desktop repo to request this.

**UPDATE:**

The red highlighting of the input box doesn't seem to correlate with the refusal to export larger image sizes, as I've now tried exporting at lower (but still high) zoom values (e.g. 240%, which puts the exported width in the range of 22000-24000 pixels), and the exported image still seems to have a zoom value of about 170%.

**draw.io version:**

- draw.io version 24.1.0

**Desktop:**
 - OS: Windows 10 Professional
 - ~~Browser: Chrome~~
 - ~~Browser Version: 123.0.6312.86 (Official Build) (64-bit)~~
 - ^^ Using the desktop version, not the browser version

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- Not applicable (we're talking about is the desktop release)

**Comment by alderg** [comment]
Could you attach the diagram file and the exported PNG image please?
