### ISSUE TITLE
Update Mermaid version used in Draw.io

### ISSUE THREAD

**Issue by pktiuk** [jgraph/drawio#4307]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success. Only found an issue which may be related: https://github.com/jgraph/drawio/issues/4107

**Is your feature request related to a problem? Please describe.**

Currently used version od Mermaid in the Drawio does not support some of the features it provides.
For example aliases for names in ER diagrams: https://mermaid.js.org/syntax/entityRelationshipDiagram.html#entity-name-aliases-v10-5-0

**Describe the solution you'd like**
Update mermaid version to the latest one. (Current one is pretty old).

**Describe alternatives you've considered**
--

**Additional context**

 **Reproduction:**

Paste mermaid diagram:

```
erDiagram

%%ENTITIES

loc[LOCATION] {
float lat
float lon
float alt
}
```

and it does not work:

```
Parse error on line 4:
erDiagramloc[LOCATION] {float t
------------^
Expecting 'EOF', 'SPACE', 'NEWLINE', ':', 'BLOCK_START', 'title', 'acc_title', 'acc_descr', 'acc_descr_multiline_value', 'ALPHANUM', 'ENTITY_NAME', 'ZERO_OR_ONE', 'ZERO_OR_MORE', 'ONE_OR_MORE', 'ONLY_ONE', 'MD_PARENT', 'open_directive', got '['
```

When this diagram is simplified everything works:

```
erDiagram

%%ENTITIES

LOCATION {
float lat
float lon
float alt
}
```

**Comment by davidjgraph** [comment]
At the moment we’re running an older version of mermaid because more recent versions don’t support all the browser versions that we support. We are actively looking at ways to solve the issue.

**Comment by ooskapenaar** [comment]
There are a bunch of other issues that would be addressed by this, I think: #4107, #3884, ...
https://github.com/jgraph/drawio/issues?q=is%3Aopen++mermaid

**Comment by SebGonzalez98** [comment]
Hi! which version is being used? I am trying to integrate ChatGPT+Mermaid+drawio and I want to update the prompt to evade version-related errors

**Comment by davidjgraph** [comment]
10.0.2

**Comment by davidjgraph** [comment]
10.9.1 added in 24.4.11.

**Comment by pktiuk** [comment]
Thank you for dealing with this issue so quickly :rocket:

**Comment by jeffzhangc** [comment]
> 10.9.1 added in 24.4.11.

how can i get real verison of mermaid in drawio?

I found that the mermaid's version in [etc/dependencies/package.json](https://github.com/jgraph/drawio/blob/dev/etc/dependencies/package.json) is still 10.0.2

![image](https://github.com/user-attachments/assets/100e5868-4cf3-4a9b-9761-86ffd6e6ba57)
