### ISSUE TITLE
Exporting file with many pages to PDF is broken

### ISSUE THREAD

**Issue by vladd12** [jgraph/drawio#4308]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I have file with many diagrams and text notes in separate pages:
![image](https://github.com/jgraph/drawio/assets/15172665/e1598e8a-a112-45cd-bc7a-d5febcfe4a70)
There are a total of 17 pages with A4 size and landscape orientation. I'm using web version of the application. After selecting "File -> Export as -> PDF..." a new tab with https://convert.diagrams.net/node/export address is created in the browser. After some loading time, the new tab content contains only "Error!" text:
![image](https://github.com/jgraph/drawio/assets/15172665/0ef37858-c3cf-4220-b36c-c691cc1ebf72)

**Expected behavior**
Well, I just want my converted PDF file 😅 

**draw.io version**
- draw.io version: 24.2.1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Browser Version: 123.0.6312.86

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Comment by krishna-ship-it** [comment]
It's working fine..........

**Comment by vladd12** [comment]
@krishna-ship-it, well, I spent some time to editing a file from my project. So, you can try to convert this to pdf (firstly change the file type to drawio instead txt, githud doesn't allow uploading *.drawio files)
[temp2.txt](https://github.com/jgraph/drawio/files/14850405/temp2.txt)

**Comment by m-mohamedin** [comment]
I've tested the file and it works fine, maybe it was an issue with our export server that is fixed now.
I'll close but if you're still having the issue, please reply and we'll open it again
Thanks

**Comment by vladd12** [comment]
@m-mohamedin, well this issue has been fixed. Now export working perfectly, thanks dev team!
