### ISSUE TITLE
SVG Export: Text is cropped at text field borders

### ISSUE THREAD

**Issue by BOW-el** [jgraph/drawio#4313]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
First, Many thanks for this great and helpful project!

Upon Exporting a graph via sgv, text is cropped at text field borders. This behavior differs from jpg export

**To Reproduce**
1. Open new graph
2. Insert text field and enter text that exceeds the field borders
3. Export as png/jpg
4. Export as svg

**Expected behavior**
WISIWYG, text should be displayed as in the interface. Possibly the text field could be extended in the export?

**Screenshots**
Interface Screenshot:
![grafik](https://github.com/jgraph/drawio/assets/51232641/15aaf5eb-6e57-4d74-b892-d093a955c825)
Rendered output from jpg export (desired state):
![grafik](https://github.com/jgraph/drawio/assets/51232641/589e670e-79ab-4ec6-9176-374f0fb198a7)
Rendered output from svg export (undesired)
![grafik](https://github.com/jgraph/drawio/assets/51232641/f8e770bd-381d-44de-ad22-484c8da706e7)

**draw.io version (In the Help->About menu of the draw.io editor):**

 draw.io version 24.1.0

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Windows 11

**Additional context**

**Comment by BOW-el** [comment]
Text Output is rendered correctly by Edge for instance actually, but not by Inkscape (where I took the screenshot above from). Might therefore actually be an issue with the rendering software. Artificially increasing the text field size might still help.

**Comment by lpdx** [comment]
I'm using the version 24.4.8 on Windows and I have the textbox not showing completely in Inkscape nor in LaTeX using svg package. In the web browser it is rendered corrected.

From drawio:
![image](https://github.com/jgraph/drawio/assets/13546280/9d2e484e-9079-4c0b-93e5-ab44ab75c6b8)

Openning in Inkscape I have:
![image](https://github.com/jgraph/drawio/assets/13546280/bfdb49de-4322-429a-b5c5-7efae3cbece1)

**Comment by alderg** [comment]
Did you export the SVG? What were the export settings?
