### ISSUE TITLE
pdf export breaks Thai text

### ISSUE THREAD

**Issue by Co9ski** [jgraph/drawio#4316]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
A text in Thai language gets corrupted when exported into PDF format, particularly when dealing with glyph(s) above or below a consonant glyph.

**To Reproduce**
1. have some Thai text present in the file.
2. Go to 'file > export as > PDF'
3. tick 'crop', click 'Export'
4. Use any pdf reader to check the text embedded in the print.

**Expected behavior**
Thai text gets partially corrupted. Space added and characters repeated a few times around the affected combination of glyphs.

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/166302213/e8f4074f-41ba-482e-b4cf-08c9e5fb35cf)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.2.2

**Desktop (please complete the following information):**
 - OS: Ultramarine Linux (Fedora-based)
 - Browser Firefox for Fedora (tested on google chrome: same issue)
 - Browser Version 121.04

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**
Some emoji failed to display, but the embedded works.

**Comment by davidjgraph** [comment]
Please attach a diagram that recreates the issue.

**Comment by Co9ski** [comment]
github won't let me paste xml files. i hope this will do
https://drive.google.com/file/d/1_N83rP1nIpQLJpuf3Ygq1m8JDSWqKp9N/view?usp=sharing

**Comment by davidjgraph** [comment]
I would try print to PDF instead instead. I assume you're using a specific font family that the export server doesn't have installed.
