### ISSUE TITLE
Issues With Sketch Mode and Arrow Labels

### ISSUE THREAD

**Issue by nevdelap** [jgraph/drawio#4323]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**

1. When turning on Sketch using the checkbox in the Style tab...

![image](https://github.com/jgraph/drawio/assets/583807/9d558fac-b37f-454b-9c73-495ef692dc3f)

it draws the sketch version over the top of the normal version (the main problem)...

![image](https://github.com/jgraph/drawio/assets/583807/8f250296-c131-4cc5-a41a-1d6784d305e2)

See how the sketch version is drawn over the original? It is most obvious with the arrows.

and turns it on in the Diagram tab (good), 

![image](https://github.com/jgraph/drawio/assets/583807/fe989f4e-b46f-4deb-b6a4-d80fdf93aea2)

but...

2. When it is off in the Style tab, turning it on and off in the Diagram tab doesn't do anything (secondary, minor problem).

and...

3. When I was drawing the diagram the labels were drawn on top of the arrows - they had a white background rectangle under the label text, but when I turned on Sketch the first time they started drawing behind the arrows, (or the white background rectangle isn't being drawn?), and have stayed that way. If I add a new label it behaves like all the others did before.

![image](https://github.com/jgraph/drawio/assets/583807/a0ee3512-8e7b-4c73-9bbc-3397368fad68)

**To Reproduce**

As above.

**Expected behavior**

The Sketch buttons in the two tabs should both turn on Sketch mode, I guess, and when it is on, the sketch version of the diagram should be drawn without drawing the regular version at the same time, and the labels should display like the Good One example above.

**Screenshots**

Above.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.2.3

**Desktop (please complete the following information):**

 - OS: Linux
 - Browser: Chrome
 - Browser Version: 123.0.6312.105 

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**

- Yes

**Additional context**

I'm using it on https://app.diagrams.net/

It's a very nice tool! Thank you.

**Comment by nevdelap** [comment]
I figured out how I could turn the arrow text backgrounds back on. So the bug is just that they'd all turned off.

**Comment by alderg** [comment]
I get a white label background with and without sketch mode in the Style tab:

<img width="416" alt="Screenshot 2024-04-16 at 09 49 30" src="https://github.com/jgraph/drawio/assets/921200/fbaaf97b-2c11-4a16-bcc5-05670b93d0bb">

**Comment by nevdelap** [comment]
The label background thing was a once off. They all just turned off at one point. I've not seen it again, so probably that should be ignored.

Your sketch mode looks to be working properly though, unlike mine.

**Comment by nevdelap** [comment]
Actually, I zoomed the diagram, and what I thought were straight lines - I thought it was the non-sketch version being drawn at the same time as the sketch version - are actually curved lines.

![image](https://github.com/jgraph/drawio/assets/583807/32840eba-8ac2-4201-8867-839a0b10b194)

vs

![image](https://github.com/jgraph/drawio/assets/583807/a43f0aa1-bd76-4c88-b076-2d72a5c32f65)

I think the sketch mode just has lines that look very straight when the diagram is small, and I thought it was doing something it isn't. I'll close this.

The different behaviour of the checkboxes on the two tabs is wonky I think, but that was a minor part of what I thought I was reporting.

**Comment by nevdelap** [comment]
I discovered that if I don't like how the arrow is being drawn I can delete it and replace it with a new one until I get one I like. :+1:
