### ISSUE TITLE
This seems to be a typo?

### ISSUE THREAD

**Issue by snowfoxzx** [jgraph/drawio#4324]
This seems to be a typo?

https://github.com/jgraph/drawio/blob/1211f818099a6c3cffb78cb3cd1666a46a99a58d/src/main/webapp/js/grapheditor/Dialogs.js#L1920-L1921

**Comment by davidjgraph** [comment]
Looks ok, what specifically are you saying is wrong here?

**Comment by snowfoxzx** [comment]
My personal understanding is that when a node has the "placeholders" attribute and its value is "1", the "label" attribute should be removed. In the code, the attribute name being checked is "placeholder", missing an "s". Or perhaps I misunderstood?

> Looks ok, what specifically are you saying is wrong here?

**Comment by alderg** [comment]
placeholder (with no s) is used to define the placeholder used as the label. [Here is an example.](https://app.diagrams.net/#RdZNRT4MwEMc%2FDY9LKOiGr24TY7KYuAcfTaUnrSmUlGOAn96ytkCje%2BLu1397vf%2BVKN1XQ65pw0%2BKgYySmA1ReoiShCRxZj4TGS15yHYWlFowi%2BIFnMUPuJ2edoJB65hFqJRE0YSwUHUNBQaMaq36UPalJAtAQ0sIrjGBc0El%2FJG9C4bc0ux%2BpX4GUXJfmcRupaJe7EDLKVP9CqXHKN1rpdBG1bAHOZkX%2BvJ0Y3W%2BmIYa%2F9mgPr8nP4xC0gK46Ru0lSG06Jycoiu7UNmBO3HRh975yofmI98OHXkdBNu0bxqa08uGzB3NN21x9C5q1dUMpv1xlD72XCCcG1PGgN68G8M4VtJkxIS22gU0wnCz13W9HFQFqEcj8RvunOnu1ZGdy%2FtlhsQPhq%2Fmt3WMutbL%2BejFWRO4Hn3qvPbpMtOrdPVnpMdf#%7B%22pageId%22%3A%22aO-uAPksOmj-8bHFsAnL%22%7D)

**Comment by snowfoxzx** [comment]
Understood, thanks for your explanation.
