### ISSUE TITLE
Hover Over Bar with Comments button doesn't appear as described in documentation

### ISSUE THREAD

**Issue by rwlaschin** [jgraph/drawio#4327]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Hi, I was following the instructions here https://drawio-app.com/blog/comment-diagrams-confluence-cloud/#:~:text=Add%20comments%20to%20a%20draw.io%20diagram&text=Hover%20over%20the%20diagram%2C%20and,the%20side%20of%20your%20diagram for adding a comment.

It doesn't seem to work for me/anymore?  I have some rectangles and some images, when I hover over them I don't get the bar on the bottom and I'm unable to add comments.

**To Reproduce**
1. Create a new diagram
2. Add a box or an image
3. Hover over the box/image

**Expected behavior**
This is what should happen https://drawio-app.com/blog/comment-diagrams-confluence-cloud/#:~:text=Add%20comments%20to%20a%20draw.io%20diagram&text=Hover%20over%20the%20diagram%2C%20and,the%20side%20of%20your%20diagram.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version v24.2.2

**Desktop (please complete the following information):**
 - OS: Mac Big Sur, 11.7.10
 - Browser: Chrome
 - Browser Version: 123.0.6312.107 (OB) (x86_64)

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**
N/A

**Comment by davidjgraph** [comment]
This is in Confluence Cloud?
