### ISSUE TITLE
how to edit shapes

### ISSUE THREAD

**Issue by lhpitn** [jgraph/drawio#433]
hi there,

i would like to create a new shape, the half cloud, to get a two coloured cloud for a diagram. So how to do that, rtfm i guessed, so i read https://desk.draw.io/support/solutions/articles/16000052874 but there a button is mentioned that i can not see:

https://imgur.com/a/0lxFHFf

only edit stile not edit shape.

sou please help me out on it. thanks a lot

**Comment by davidjgraph** [comment]
What exactly steps did you follow, what result were you expecting and what result do you get?
