### ISSUE TITLE
web version - Doesn't save changes

### ISSUE THREAD

**Issue by arhesaim** [jgraph/drawio#4330]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Document didn't save contents after explicitly pressing "save" 2 times.

**To Reproduce**
I've created separate pages for each diagram by clicking "+" at the bottom of the page. 
When the diagrams were done, i've saved changes 2 times by pressing "file" -> "save " before closing the tab. 
When I opened the document later - only empty pages were saved. 
I've tried going to "file" -> "revision history", and there it was showing the same empty pages for each timestamp - so when I was pressing "save" it weren't saving changes.

**Expected behavior**
I've expected it to save the changes made 😄

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.2.5

**Desktop (please complete the following information):**
 - OS: [macOS 14.4.1]
 - Browser [Opera]
 - Browser Version [108.0.5067.29]

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-yes

**Additional context**

**Comment by davidjgraph** [comment]
Where are you saving to?

**Comment by davidjgraph** [comment]
Apologies, but we currently lack the resources to investigate such cases.
