### ISSUE TITLE
Add ability to disable Export to - URL via configuration

### ISSUE THREAD

**Issue by Xandrr** [jgraph/drawio#4336]
**Is your feature request related to a problem? Please describe.**
We need to disable "export URL" function in our local instance of draw.io due security reasons.

**Describe the solution you'd like**
Add startup parameter to override Editor.enableExportUrl value without code editing.

**Describe alternatives you've considered**
I should manual edit file in my local repository:
src/main/webapp/js/diagramly/Editor.js
@@ -174,7 +174,7 @@
    /**
     * Disables the export URL function.
     */
    Editor.enableExportUrl = true;
    Editor.enableExportUrl = false;

**Additional context**

**Comment by davidjgraph** [comment]
Why do you specifically want that disabled and not save as XML, extra->edit diagram, etc?
