### ISSUE TITLE
I can export a file to .pdf but OneDrive browser does not show .pdf files

### ISSUE THREAD

**Issue by Dziurkacz420** [jgraph/drawio#4339]
* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I can export to .pdf, but I cannot try to open a .pdf file from OneDrive.

**To Reproduce**
1. Open from > One Drive.
2. Find a .pdf file.

**Expected behavior**
I can see all files, the usual system browser is being used.

**Actual behavior**
File browser shows only some file extenstions:
![image](https://github.com/jgraph/drawio/assets/148913685/b29e3a3f-3e7c-40bb-976a-127b58e2d111)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.2.7

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser chrome
 - Browser Version 123.0.6312.123

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- Yes.

**Additional context**
The usecase is that I do not have an ability to download files from sharepoint, but drawio has access to them.

**Comment by davidjgraph** [comment]
Try using 24.2.9.

**Comment by Dziurkacz420** [comment]
It seems to be working, but notice what happens to breadcrumbs when you
click "refresh", it multiplicates the last entry in the path. Thank you!
[image: image.png]

śr., 24 kwi 2024 o 12:40 David Benson ***@***.***> napisał(a):
