### ISSUE TITLE
Support iframe sandbox attribute ...

### ISSUE THREAD

**Issue by DeepDiver1975** [jgraph/drawio#4340]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
From a security perspective a iframes should use sandbox attributes to limit attack vectors and jail an application inside an iframe.
It should be enough to load drawio in an iframe with sandbox="allow-scripts" but drawio tries to access the parent document.

### Access to document.cookie
![image](https://github.com/jgraph/drawio/assets/1005065/416f640d-bb4b-4ce4-8a64-01811caa07ba)
This can be worked around by specifying the urlParam `mode=foo`

### Access to Navigator.serviceWorker
![image](https://github.com/jgraph/drawio/assets/1005065/ecb5db08-c34e-4f04-89a3-103f63772e8c)
I could not find a workaround to this - no idea if it is even possible to run without the service worker

**Describe the solution you'd like**
drawio should not try to break out of the iframe - at least workarounds should be documented.

**Describe alternatives you've considered**
See above

**Comment by davidjgraph** [comment]
Are you asking how to set a CSP on your own deployment?

**Comment by DeepDiver1975** [comment]
> Are you asking how to set a CSP on your own deployment?

no. When embedding drawio in an iframe I want to use a minimal set of sandbox attributes. I mainly don't want to grant `allow-same-origin` -  only granting `allow-scripts` should be sufficient.
https://www.w3schools.com/tags/att_iframe_sandbox.asp

THX

**Comment by davidjgraph** [comment]
We have reasons for how we configure our own deployment. If you need something different simply create your own deployment.

**Comment by DeepDiver1975** [comment]
It is not about the deployment. Even if I run my own deployment of drawio I can still not iframe it with the desired iframe sandbox.

Unless I miss anything. THX a lot

**Comment by davidjgraph** [comment]
Should work in 24.3.1

**Comment by DeepDiver1975** [comment]
Thx a lot. I will test this asap!

**Comment by DeepDiver1975** [comment]
I am sorry to say - but this is not fixed ...

let me know if you need any further support - thx

![image](https://github.com/jgraph/drawio/assets/1005065/2f15be05-bc4e-45b3-97d9-92eb80e58794)

**Comment by DeepDiver1975** [comment]
@davidjgraph can you please reopen this issue?

**Comment by DeepDiver1975** [comment]
@davidjgraph is there any fix? Shall I retest anything?

**Comment by alderg** [comment]
Should work now.

**Comment by DeepDiver1975** [comment]
Looks like it is working now - THX @davidjgraph @alderg
