### ISSUE TITLE
When export the diagram as PNG, the WEB fonts are not applied, the font applied is standard

### ISSUE THREAD

**Issue by YaninaLeanIX** [jgraph/drawio#4341]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
When I used a web font stored externally, it was applied correctly on the Canvas. Once I exported the diagram as PNG, the web font was reverted to a standard font. 

**To Reproduce**
1. Add a shape with the text on the Canvas
2. Select the Text tab in the format panel, click on the drop-down arrow next to the font name, then click on Custom.
3. Click on the Web Fonts radio button, enter a name in the Font Name field, and then enter the URL where your .woff font file is stored. Then click Apply.
4. Then go back to the diagram - the custom font is applied. 
5. Export the diagram as "PNG"
6. The custom font is not applied anymore.

**Expected behavior**
When you export the diagram, the custom font is still applied. 

**Screenshots**
Attached the screenshots
Export without custom font: (https://github.com/jgraph/drawio/assets/87121494/ef907057-058b-4d06-864e-6d4989ba6aa6)
Screenshot from Canvas with a custom font(https://github.com/jgraph/drawio/assets/87121494/2d9db9a7-e1d7-40f9-a230-a6c21d7c7b32)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: v24.2.3

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : iOS
 - Browser [e.g. chrome, safari]: Chrome
 - Browser Version [e.g. 22]: Version 124.0.6367.61

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- Yes

**Additional context**

**Comment by davidjgraph** [comment]
Which version of iOS are you using?

**Comment by YaninaLeanIX** [comment]
macOS Sonoma 14.4.1

**Comment by davidjgraph** [comment]
Any error in the console?

**Comment by YaninaLeanIX** [comment]
This is the error, tried with different fonts from the GitHub 
https://github.com/hakimel/reveal.js/tree/master/dist/theme/fonts/source-sans-pro
<img width="913" alt="Screenshot 2024-04-26 at 12 05 01" src="https://github.com/jgraph/drawio/assets/87121494/32ffc866-bb3c-4356-93a9-19895d857d2a">

**Comment by davidjgraph** [comment]
OK, the error explains itself.
