### ISSUE TITLE
PWA for Mobile doesn’t work: “Error Not Found”

### ISSUE THREAD

**Issue by Compg** [jgraph/drawio#4342]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**

PWA does not work on iOS. Shortcut added to Home Screen and opens page with “Error Not Found”

**To Reproduce**
1. Go to apps.diagrams.net
2. Click on Share Button
3. Add to Home Screen
4. Click icon
5. See error

**Expected behavior**

Apps.diagrams.net opens in PWA

**Screenshots**

![IMG_0620](https://github.com/jgraph/drawio/assets/134229312/f3fc4a26-1510-4665-b517-0c829c8eb4ce)

- draw.io version 24.2.7

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] IPad Pro M2
 - OS: [e.g. iOS8.1] iOS 17.4
 - Browser [e.g. stock browser, safari] Safari

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- Yes

**Additional context**

**Comment by davidjgraph** [comment]
Try using 24.2.9.

**Comment by Compg** [comment]
I'm seeing version 24.2.18 as latest on mobile and it's showing same error.

**Comment by alderg** [comment]
Visit https://clear.diagrams.net and try again please.

**Comment by Compg** [comment]
Works perfectly now. Thank you both!
![IMG_0624](https://github.com/jgraph/drawio/assets/134229312/6277b510-09e3-47a9-a233-b27426ac896d)

**Comment by Compg** [comment]
Works perfectly now. Thank you both!
![IMG_0624](https://github.com/jgraph/drawio/assets/134229312/6277b510-09e3-47a9-a233-b27426ac896d)
