### ISSUE TITLE
Make "Publish" for files stored on Gitlab the same as for files stored on Google Drive

### ISSUE THREAD

**Issue by natefitzgeraldmse** [jgraph/drawio#4346]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

I'd like to share non-editable views of diagrams that are stored in GitLab with my company colleagues in a manner similar to the functionality for files stored on Google Drive.  But the current process for "publish"-ing a non-Drive diagram does not allow it.

**Describe the solution you'd like**

Right now, one can generate a non-editable view of a diagram using the File->Publish->Link menu option.  For files stored on Google drive, the URL that is generated from that process containing "https://viewer.diagrams.net/" essentially links back to the version of the document stored on Google Drive.  In other words, if changes are made to the diagram after the "publish" URL is generated, the changes will still appear when a user loads the URL at a later date.  Also, if a person who does not have the correct Google Drive permissions to access the document manages to get access to the URL, they are prevented from accessing the view of the diagram.

For every other file storage option, the "Publish" option has different behavior.  It generates a URL that encodes the entire diagram, so that it is a self contained expression of the content.  It does not refer back to the file at its original storage location, so updates to the file will not be reflected by users of the URL.  And the users of the URL do not need to have the credentials from the original file location; anyone with the URL can view the diagram.

Especially for files stored in Gitlab, I would like have the "File->Publish->Link" behavior mimic the current behavior for files based out of Google Drive... that the "https://viewer.diagrams.net/" reference the current version in the repository and require the right credentials to access.  I'm sure this same feature would be useful for files stored in other version controlled and access restricted repositories as well.

**Describe alternatives you've considered**

I've tried messing around with writing my own viewer of SVG files stored in Gitlab, but to no avail.

**Additional context**
N/A

**Comment by alderg** [comment]
Try adding the hash property of the URL (ie. `#A...`) after https://viewer.diagrams.net/

**Comment by natefitzgeraldmse** [comment]
I tried that, but get the following error after authorizing the app in Gitlab 

![image](https://github.com/jgraph/drawio/assets/167917678/ea280a35-e893-4e91-8d4e-f37adc0a7f4b)

**Comment by alderg** [comment]
Try `https://app.diagrams.net/?lightbox=1#A...`

**Comment by natefitzgeraldmse** [comment]
That did about 95% of what I needed! After inspecting the URL from a "publish" of my diagram, I tried

`https://app.diagrams.net/?lightbox=1&highlight=0000ff#A...`  and that got me the other 5% of what I needed!

Looking through the elements of the "publish" URL some more, is there any documentation on what some of the other fields do.  I can guess some of them from playing around, but others aren't immediately clear.

- ?tags=%7B%7D
  - ???
- &highlight=0000ff
  - This looks like it generated the highlights around the links
- &edit=_blank
  - this looks like it adds the menu option to open a new copy of the diagram... from playing around, I think I see how to reference the original diagram as well 
- &layers=1
  - ???
- &nav=1
  - ???
- &title=MyDiagram.svg
  - This looks it just sets the title for the tab in the browser.

Are there any others that would be useful to know about?

**Comment by alderg** [comment]
Nav enables collapse/expand icons for containers.
Tags and layers enables the respective buttons if tags/layers are used in the diagram, eg.
<img width="509" alt="Screenshot 2024-04-25 at 19 28 18" src="https://github.com/jgraph/drawio/assets/921200/6dbcd890-4cde-4e78-9171-61a4ef92b41c">

**Comment by natefitzgeraldmse** [comment]
Ah... so that's what's documented [here](https://www.drawio.com/doc/faq/supported-url-parameters).   Thanks!
