### ISSUE TITLE
PDF export functionality not respecting "Crop" setting

### ISSUE THREAD

**Issue by NapaHali** [jgraph/drawio#4348]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
As of today, when I attempt to export a diagram to PDF using the "Crop" setting, the setting seems to be ignored. The exported PDF still appears as a full A4 page, rather than being cropped as specified.

**To Reproduce**
1. Create a simple diagram
2. Select the option to export as... PDF.
3. In the export settings, check "Selection only" and "Crop" options
4. See error => The resulting PDF was formatted as a full A4 page

**Expected behavior**
Expect the output to be trimmed to the diagram's boundaries (selection).

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.2.8

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Browser Version: 124.0.6367.61

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- weirdly, it works in incognito

**Additional context**
This issue has been consistent across multiple attempts on different diagrams today. Tested on two computers with different accounts, settings, etc.

**Comment by TobiasFrahm** [comment]
Same here: 
EndevourOS + Firefox
Win11+ Firefox

**Comment by davidjgraph** [comment]
I cannot repeat with 24.3.0.

**Comment by TobiasFrahm** [comment]
> I cannot repeat with 24.3.0.

I wonder how I do get different Versions of draw.io when using it direct in the browser? 
Firefox normal mode shows me v24.2.3, in incognito mode however it shows v24.3.0. 
And you are right I can crop and export with v24.3.0

**Comment by davidjgraph** [comment]
Try clear.diagrams.net. Sometimes the caching can be aggressive.

**Comment by NapaHali** [comment]
> I cannot repeat with 24.3.0.
After further troubleshooting, I cleared the cookies and cache in my browser, which successfully resolved the issue with the "Crop" setting in the PDF export function. Interestingly, I was able to replicate the same issue on another device that had not been using draw.io recently.
