### ISSUE TITLE
Google doc add on: Imported diagrams are all grey

### ISSUE THREAD

**Issue by AleeeKoi** [jgraph/drawio#4349]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
I was working on a google doc, I have already added some diagrams from the same .drawio file.

From about 30 minutes ago, inserting new diagrams they all appear grey without content.
By updating the previously inserted diagrams (which were visible) they become grey.

I tried creating a new google doc file and a new .drawio file but the situation doesn't change, now all the imported diagrams are grey.

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/46484371/fdb2f341-4119-4570-b54a-39400ef9de93)

**draw.io version (In the Help->About menu of the draw.io editor):**

- online version

**Desktop (please complete the following information):**
 - OS: osx 14
 - Browser chrome 
 - Browser Version 124

**Comment by davidjgraph** [comment]
That's now fixed, thanks for the report.

**Comment by AleeeKoi** [comment]
Hi @davidjgraph , thanks for your quick response.
Ok, now the diagram can be imported but it's not cropped, look at the following screenshot:

![image](https://github.com/jgraph/drawio/assets/46484371/bc9ac95a-5107-4ac5-bf35-fe61a26202fa)

Could you please restore the prev functionality?

Thanks

**Comment by davidjgraph** [comment]
Please add another ticket for that.
