### ISSUE TITLE
edit shape  text fontsize dont work

### ISSUE THREAD

**Issue by reproteq** [jgraph/drawio#435]
https://desk.draw.io/support/solutions/articles/16000070744-how-to-create-custom-stencils-in-draw-io-using-the-text-editor-step-by-step-

How to create custom stencils in draw.io using the text editor, step by step?
<shape name="stencilName" h="100" w="50" aspect="variable" strokewidth="inherit">
</shape>

<text str="someText" x="50.0" y="50.0" align="left" valign="top" vertical="0" rotation="0.0" align-shape="1"/>

DONT WORK 
The styles related to text are:

fontsize - attribute is size and is a decimal value. Defines font size.
fontstyle - attribute is style and is an ORed bit pattern of bold (1), italic (2) and underline (4), i.e bold underline is "5"
fontfamily - attribute is family and is a string defining the typeface to be used

i cant change size and color

<shape name="Bat60" h="120" w="12" aspect="variable" strokewidth="inherit">
  <background>
    <rect x="0" y="0" w="12" h="120"/>
  </background>
  <foreground>
    <fillstroke/>
    <text fontsize="6" str="60" x="0.4" y="0.4" align="left" valign="top" vertical="0" rotation="0.0" align-shape="1"/>
    <ellipse x="0" y="0" w="12" h="12"/>
    <stroke/>
    <ellipse x="0" y="12" w="12" h="12"/>
    <stroke/>
    <ellipse x="0" y="24" w="12" h="12"/>
    <stroke/>
    <ellipse x="0" y="36" w="12" h="12"/>
    <stroke/>
    <ellipse x="0" y="48" w="12" h="12"/>
    <stroke/>
    <ellipse x="0" y="60" w="12" h="12"/>
    <stroke/>
    <ellipse x="0" y="72" w="12" h="12"/>
    <stroke/>
    <ellipse x="0" y="84" w="12" h="12"/>
    <stroke/>
    <ellipse x="0" y="96" w="12" h="12"/>
    <stroke/>
    <ellipse x="0" y="108" w="12" h="12"/>
    <stroke/>
  </foreground>
</shape>

**Comment by ashrafteleb** [comment]
It should be used as the following example in order to work:
(e.g, Styles before the text)

<fontsize size="20"/>
<fontfamily family="Arial"/>
<fontstyle style="5"/>
<fontcolor color="#FF0000"/>
<text str="someText" x="50.0" y="50.0" align="left" valign="top" vertical="0" rotation="0.0" align-shape="1" />
