### ISSUE TITLE
Google Doc integration adds too much space around embedded image

### ISSUE THREAD

**Issue by thaDude** [jgraph/drawio#4351]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Starting 2024-04-24 draw.io images embedded into a Google Doc document are extended to the bottom-right with empty space. I have not observed this behavior before this date.

**To Reproduce**
1. Open a Google Doc document
2. Click on Extensions -> Draw.io -> Insert Diagrams
3. Select an existing diagram
4. See box around image being too large with extra space on bottom-right, see screenshots below.

**Expected behavior**
The space surrounding the diagram content should be even on all sides and not excessive.

**Screenshots**
![Screenshot 2024-04-24 at 19 14 43](https://github.com/jgraph/drawio/assets/578631/5cfd84c7-cd3a-4762-9985-72ba10d199b1)
![Screenshot 2024-04-24 at 19 14 17](https://github.com/jgraph/drawio/assets/578631/7461b3e8-a2b4-4424-bcf3-032aa8fcb12b)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 24.3.0

**Desktop (please complete the following information):**
 - OS: macOS 14.2.1
 - Browser Safari 
 - Browser Version 17.2.1

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- "yes"

**Additional context**
Tested in Chrome as well, same issue. Very useful product overall.

Regards, David

**Comment by DanielArndt** [comment]
I'm experiencing the same thing.

**Comment by DanielArndt** [comment]
I should add, mine are not only cropped incorrectly, but the background is now grey for some reason.

**Comment by alderg** [comment]
Fixed.
