### ISSUE TITLE
Extra Padding around diagram when exporting to PDF

### ISSUE THREAD

**Issue by FelixPSch** [jgraph/drawio#4353]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When exporting to PDF and selecting 'Crop', there's extra padding around the diagram when exported. This extra padding does not appear when exporting to PNG, and selecting 'Diagram' for size.

**To Reproduce**
1. Open diagram
2. Go to 'File' -> 'Export as' -> 'PDF'
2. Select 'Crop' and unselect everything else
3. Click on 'Export'
4. Choose a file name and where to save the PDF, I reproduced the issue with 'GitHub', 'Download', and 'Open in New Window'
5. Click on 'OK'
6. See extra padding in exported PDF

**Expected behavior**
There should be no extra padding around the PDF, and it should be cropped to fit the content, similarly to the PNG export with size 'Diagram'.

**Screenshots**
PDF with extra padding (white backround is from PDF, gray border is from PDF viewer):
![PDF with extra padding](https://github.com/jgraph/drawio/assets/64274747/b8c56075-8273-4ff6-9b64-29642ae6a3e0)
PNG without extra padding:
![PNG without extra padding](https://github.com/jgraph/drawio/assets/64274747/4cc35b4b-a062-4ed7-8bfc-dd546719eb30)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 24.3.0

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Comment by alderg** [comment]
Try now.

**Comment by FelixPSch** [comment]
It works correctly now, thanks!

**Comment by jakobjung10** [comment]
@alderg , the problem is still (or again) present.
version: v29.6.1

<img width="417" height="874" alt="Image" src="https://github.com/user-attachments/assets/ca762802-5d3d-4c45-959d-0ad3cb762c50" />

In contrast, the graphic is correctly cropped with the svg or png export options...

BR,
Jakob

**Comment by davidjgraph** [comment]
The OP marked the original issue as fixed, so you'll likely hitting a different issue, even if the result looks very similar. Please open a new issue.
