### ISSUE TITLE
Allow https://app.diagrams.net/#U to access private gitlab pages

### ISSUE THREAD

**Issue by natefitzgeraldmse** [jgraph/drawio#4356]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

In the FAQ page for ["Supported location hash properties"](https://www.drawio.com/doc/faq/supported-location-hash-properties) there's an example referencing a diagram located at a specific URL from a public GitHub pages site.
```
https://app.diagrams.net/#Uhttps%3A%2F%2Fjgraph.github.io%2Fdrawio-diagrams%2Fdiagrams%2Fbulb.xml
``` 

However, "Error loading file: File not found" occurs when trying to access a private GitLab-pages domain with the same syntax (i.e. https://app.diagrams.net/#Uhttps%3A%2F%2Fmydomain.gitlab.io%2Fmyrepo%2Fmyfile.svg).  I've verified that https://mydomain.gitlab.io/myrepo/myfile.svg is accessible if typed directly into my browser. 

**Describe the solution you'd like**

Assuming this error is related to redirection behavior for authentication to the private domain, the feature request to resolve access to private gitlab pages so that the example URL above does not result in a "File Not Found" error.

**Describe alternatives you've considered**

One potential alternative is to reference a specific gitlab branch or commit with the #A directive.  That requires pointing to a particular branch, which is ok.  I have a particular workflow that relies on information posted to gitlab pages being the "official" documentation, so I wanted the diagram access to be consistent with that.

**Additional context**
N/A

**Comment by davidjgraph** [comment]
The #U concept doesn't support authenication, that is by design. You have the use the specific gitlab provided functionality.
