### ISSUE TITLE
Export single page plot as PDF but get multiple pages output

### ISSUE THREAD

**Issue by PatrickYanZ** [jgraph/drawio#4357]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Export a single page pdf with a wide plot but get the image with seperate page. I expect to have a single page.
Each page contains part of plot.
It only happens on export PDF, working fine in export to PNG JPEG, also working fine in draw.io Desktop with Mac.

**To Reproduce**
1. Go to 'File', 'Export as' 'pdf' 

**Expected behavior**
expect to have a single page.

**Screenshots**
<img width="395" alt="image" src="https://github.com/jgraph/drawio/assets/37357319/cdcb6f09-2ea9-4f6d-afb3-0914e5a66026">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.1.0

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome/ Safari 125.0.1

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**

**Comment by alderg** [comment]
Try v24.3.0 via https://clear.diagrams.net

**Comment by PatrickYanZ** [comment]
Thanks @alderg
