### ISSUE TITLE
Not a diagram file (error on line 180 at column 75128: AttValue: ' expected)

### ISSUE THREAD

**Issue by ayberguleryunus** [jgraph/drawio#4358]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
The file I have been working on for a week now cannot be opened. I get the error "Not a diagram file (error on line 180 at column 75128: AttValue: ' expected)".

**To Reproduce**
1. Go to dekstrop
2. Click on PATROL.drawio

**Expected behavior**
Open the file without any problems

**Screenshots**
![Screen](https://github.com/jgraph/drawio/assets/76584189/d0409066-cc53-4d9b-a3cd-6dc6ddc974fa)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.21

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Browser Version:124.0.6367.62

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-yes

**Additional context**
Even though I save regularly, the file size seems smaller than I expected.

**Comment by davidjgraph** [comment]
"Click on PATROL.drawio"

How does clicking on a file open draw.io in chrome?

**Comment by ayberguleryunus** [comment]
Actually, I use the desktop application. I would open the PATROL.drawio
file with the application. I can't open it anymore and I get error 75128. I
also tried it in Chrome but I encounter the same error.

David Benson ***@***.***>, 26 Nis 2024 Cum, 14:30 tarihinde
şunu yazdı:

**Comment by davidjgraph** [comment]
This is saved to a folder sync'ed to OneDrive?

**Comment by yingyingqiqi** [comment]
I saved the file yesterday and am experiencing the same problem today

**Comment by yingyingqiqi** [comment]
Solution: There will be a hidden file named xxx.drawio.bkp in the same directory, copy it and rename it to xxx.drawio.
