### ISSUE TITLE
export PDF with extra background part

### ISSUE THREAD

**Issue by Absoler** [jgraph/drawio#4361]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The crop option seems useless, I have tried export a PDF from pathes of "export as -> PDF" and "export as -> advanced" and both fail.
The exported PDF contains a whole page anyway.
**To Reproduce**
1. Go to 'File'
2. Click on 'Export as'
3. Select 'crop'
4. Click on 'Export'

**Expected behavior**
a PDF file only contains the diagram is exported

**Screenshots**

the currenet exported 
![image](https://github.com/jgraph/drawio/assets/35028379/300e4141-d826-44f2-a477-83f8482cc3a3)

**draw.io version (In the Help->About menu of the draw.io editor):**
v24.2.7

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Browser Version  124.0.6367.60

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
yes

**Additional context**
similar with https://github.com/jgraph/drawio/issues/4353 https://github.com/jgraph/drawio/issues/4348

**Comment by davidjgraph** [comment]
Close all diagrams.net tabs, use clear.draw.io to push an update and test with 24.3.1.

**Comment by Absoler** [comment]
And if I export PDF through "File -> print", it seems correct

**Comment by Absoler** [comment]
> Close all diagrams.net tabs, use clear.draw.io to push an update and test with 24.3.1.

Thanks, it works for the path "File -> Export as -> PDF". But still fail for "File -> Export as -> Advanced -> PDF", which I remember could work some days ago.

**Comment by davidjgraph** [comment]
What does it show for the version under the help menu?

**Comment by mayone23** [comment]
> > Close all diagrams.net tabs, use clear.draw.io to push an update and test with 24.3.1.
> 
> Thanks, it works for the path "File -> Export as -> PDF". But still fail for "File -> Export as -> Advanced -> PDF", which I remember could work some days ago.

Yes, it is not working now. The generated pdf are coming in multiple pages with blank background.

**Comment by Absoler** [comment]
> What does it show for the version under the help menu?

24.3.1

**Comment by daviddavo** [comment]
Working here too

**Comment by mayone23** [comment]
![image](https://github.com/jgraph/drawio/assets/26814667/45870e96-0cbf-4413-b764-248b7f7e648e)

**Comment by mayone23** [comment]
> ![image](https://private-user-images.githubusercontent.com/26814667/326393184-45870e96-0cbf-4413-b764-248b7f7e648e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzODM4ODYsIm5iZiI6MTcxNDM4MzU4NiwicGF0aCI6Ii8yNjgxNDY2Ny8zMjYzOTMxODQtNDU4NzBlOTYtMGNiZi00NDEzLWI3NjQtMjQ4YjdmN2U2NDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA5Mzk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmZjJjNzM4ZDYyYjA1OTFkODY1ZDY5MjE2ZTMxMDAwODZjMDE3NjNiNjU3OGVmMDQwNzM3NzFhNDNjYTA4N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YVz0oWfa55Zs87pSAZ_Hm10rmYqeUaVEseJG2KM9NPM)

Here, you can see, I am getting this one as the generated pdf. When I click on version 24.3.1 it's showing nothing.

**Comment by davidjgraph** [comment]
We're going to add the zoom to the standard dialog and remove the advanced export to PDF option.

**Comment by Augur1989** [comment]
can we get an option to set a pdf background color?
in the older versions, the background in exported pdf's was the selected diagram background color, but atm its always white

**Comment by shi-ang** [comment]
I'm still facing this issue. I tried "File -> Export as -> PDF" and "File -> Export as -> Advanced -> PDF". They both failed.

I also experience the issue that the generated PDF will crop my large diagrams into multiple pages (all with large margins). 

I tested on a desktop with Ubuntu 22.04 LTS, drawio v24.3.1, and a laptop with Windows 11, drawio v24.2.3. Anyone knows how to solve this?

**Comment by IridiumXOR** [comment]
I have the same problem...

**Comment by shi-ang** [comment]
> I'm still facing this issue. I tried "File -> Export as -> PDF" and "File -> Export as -> Advanced -> PDF". They both failed.
> 
> I also experience the issue that the generated PDF will crop my large diagrams into multiple pages (all with large margins).
> 
> I tested on a desktop with Ubuntu 22.04 LTS, drawio v24.3.1, and a laptop with Windows 11, drawio v24.2.3. Anyone knows how to solve this?

I got a temporary solution for now. 

First press "Ctrl + A" to select all the elements. Then "File -> Export as -> PDF". Then select both "Selection Only" and "Crop". This retains the previous "File -> Export as -> Advanced -> PDF" behavior.

**Comment by IridiumXOR** [comment]
> > I'm still facing this issue. I tried "File -> Export as -> PDF" and "File -> Export as -> Advanced -> PDF". They both failed.
> > I also experience the issue that the generated PDF will crop my large diagrams into multiple pages (all with large margins).
> > I tested on a desktop with Ubuntu 22.04 LTS, drawio v24.3.1, and a laptop with Windows 11, drawio v24.2.3. Anyone knows how to solve this?
> 
> I got a temporary solution for now.
> 
> First press "Ctrl + A" to select all the elements. Then "File -> Export as -> PDF". Then select both "Selection Only" and "Crop". This retains the previous "File -> Export as -> Advanced -> PDF" behavior.

It is the way I use usually but in my case does not work...

**Comment by ruiw0w** [comment]
I also encountered the same problem. I chose to export as - Advanced - PDF, and the resulting PDF files were not on the same page, and there would be pagination. One solution is to select the content you need or select all, choose export as - pdf - check only the selected content & export a single page, but the margins of the pdf file obtained in this way are too small, I usually specify the margins as 5. This problem has not occurred before. I don’t know if it is a bug in the new version.

**Comment by ruiw0w** [comment]
> > 我仍然面临这个问题。我尝试了“文件 -> 导出为 -> PDF”和“文件 -> 导出为 -> 高级 -> PDF”。他们都失败了。
> > 我还遇到这样的问题：生成的 PDF 会将我的大图表裁剪为多个页面（所有页面的边距都很大）。
> > 我在装有 Ubuntu 22.04 LTS、drawio v24.3.1 的台式机和装有 Windows 11、drawio v24.2.3 的笔记本电脑上进行了测试。有人知道如何解决这个问题吗？
> 
> 我现在有一个临时解决方案。
> 
> 首先按“Ctrl + A”选择所有元素。然后“文件 -> 导出为 -> PDF”。然后选择“仅选择”和“裁剪”。这保留了之前的“文件 -> 导出为 -> 高级 -> PDF”行为。

像你一样，按照“文件 -> 导出为 -> 高级 -> PDF”的方式导出，之前我并没有出现这种问题，所以这应该是软件的bug吗？

**Comment by ruiw0w** [comment]
我使用离线版本v24.2.5，按照“文件 -> 导出为 -> 高级 -> PDF”的方式导出，是没有问题的。

**Comment by alderg** [comment]
Fixed in v24.4.0 with the _Crop_ option checked:

<img width="413" alt="Screenshot 2024-05-11 at 08 34 00" src="https://github.com/jgraph/drawio/assets/921200/93955340-60e2-46a2-b479-7b04de2e1adc">

Use https://clear.diagrams.net/ to get the latest version.

**Comment by davidjgraph** [comment]
If you find issues with 24.4.0, please create a new issue.
