### ISSUE TITLE
How to insert the math formulars in Draw.io ?

### ISSUE THREAD

**Issue by deepmeng** [jgraph/drawio#437]

**Comment by deepmeng** [comment]
Solved

**Comment by wangguanan** [comment]
Hi, Can you take about how to solve the problem?

**Comment by wangguanan** [comment]
Hi, Can you talk about how to solve the problem?

**Comment by deepmeng** [comment]
https://desk.draw.io/support/solutions/articles/16000032875-how-to-use-mathematical-typesetting-

**Comment by wangguanan** [comment]
Thanks!
