### ISSUE TITLE
Most themes has been removed in self-hosted environment

### ISSUE THREAD

**Issue by Wertisdk** [jgraph/drawio#4384]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
After upgrading from 22.1.8 to 24.3.1 mos of the themes are no longer available in the themes menu, and do not apply when using the `ui` urlParam - like so: `ui=simple`.
However, when using the same urlParams on app.draw.io, this works fine. 

`https://[self-hosted-url]/?ui=simple&stealth=1&splash=0`
The default theme is applied and only the themes 'Automatic', 'Classic' and 'Minimal' are available.
This worked in v22.1.8

`https://app.diagrams.net/?ui=simple&stealth=1&splash=0`
The simple theme is applied and multiple themes are available

**To Reproduce**
1. Open a self-hosted version of drawio with the repo checked out to `tags/v24.1.3` and with the ui urlParam set to 'simple' (?ui=simple)
2. Observe that the simple theme is not applied
3. Open Extras > Themes 
4. Observe that only 'Automatic', 'Classic' and 'Minimal' are available

**Expected behavior**
You should be able to set the theme to any of the supported themes and themes should be available when self-hosting as well. 

If this is intended behaviour, it would be nice if this was stated clearly in: 
1. The github repo description
2. In the blogpost about configuring the editor (https://www.drawio.com/doc/faq/configure-diagram-editor)
3. In the changelog

**Screenshots**
Screenshot of available themes in self-hosted environment
![image](https://github.com/jgraph/drawio/assets/12416208/4a5c8959-9ff8-4ab0-b9a7-018fb43b60d4)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.1.3

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Browser Version: 124.0.6367.119

**Smartphone (please complete the following information):**
 N/A

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Comment by davidjgraph** [comment]
Thanks for the feedback, we'll keep that in mind for such future changes.
