### ISSUE TITLE
Kubernetes Shapes do not show any labels correctly - 20240507

### ISSUE THREAD

**Issue by csakaszamok** [jgraph/drawio#4386]
### Preflight Checklist

* [ x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

Kubernetes Shapes do not show any labels correctly
Similar issue: https://github.com/jgraph/drawio/issues/2759

**To Reproduce**
Create a new page
Click on Kubernetes
Drag any Kubernetes shape to the page
Double click on the shape and start typing
Be sad because you can't read your text. (It's hidden behind shape)

**Expected behavior**
The text should be clear to read, BELOW the shape, not on top.

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/5373500/abe96a70-17e5-439a-8b1a-834bd5fd462f)

**draw.io version (In the Help->About menu of the draw.io editor):**
Online drawio webapp, v24.3.0

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Browser Version: Version 124.0.6367.119 (Official Build) (64-bit)

**Additional context**
None

**Comment by davidjgraph** [comment]
It might be the perfect default, but changing this in the UI is pretty trivial.
