### ISSUE TITLE
Unable to download entire diagram in single page as PDF in v24.3.1 online or local app | Working on version v24.2.5

### ISSUE THREAD

**Issue by AdityaRidecell** [jgraph/drawio#4388]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
*[x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**

**To Reproduce**
1. Go to 'File > Export as > Advanced'
2. Click on 'Format' set to PDF
3. Border 30
4. Export
5. See the downloaded file, instead of one page PDF, it downloads in multi pages. 

**Expected behavior**
Entire drawing should be in single page PDF instead of multi page.

**draw.io version (In the Help->About menu of the draw.io editor):** v24.3.1

- draw.io version v24.3.1

**Desktop (please complete the following information):** Same as I explained above.
 - Browser: Chrome
 - Browser Version: Version 124.0.6367.119 (Official Build) (arm64)

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- Yes

**Comment by davidjgraph** [comment]
This is a known issue, we're removing the advance option in an upcoming release.

**Comment by AdityaRidecell** [comment]
but then, when we do export as PDF then it should download in single page instead of multi pages. Multi page diagram is not properly readable.

**Comment by azfreed** [comment]
Will the removal of the "advanced" option also remove the ability to export pdf. I can recreate the issue without going to advanced options using the "basic" pdf export option. I'd also like to work on a solution for this. Should I wait until the upcoming release to tackle it?
