### ISSUE TITLE
Project name wrong on integrations page

### ISSUE THREAD

**Issue by ferdnyc** [jgraph/drawio#4396]
Hi, I don't know if the source to the [integrations page](https://www.drawio.com/integrations) linked to from the Wiki here is public, or if there's a better place to report this. (I checked the only other likely-seeming jgraph repo, [jgraph/drawio-docs](https://github.com/jgraph/drawio-docs) but that was clearly wrong.)

Anyway — on the integrations page, ["3rd-party integrations" section](https://www.drawio.com/integrations#3rd-party-integrations): The first project listed should be "Bioicons" (which is a difficult enough name), but **instead it's spelled "Bioiocons"** (which caused my brain to trip and fall flat on its frontal lobe).

**Comment by atiehamidi** [comment]
Fixed it as my first contribution to open source community  :)

**Comment by ferdnyc** [comment]
Nice, thanks @atiehamidi — not sure how I missed that repo.
