### ISSUE TITLE
 Application (diagrams.net) is disabled

### ISSUE THREAD

**Issue by Tridy** [jgraph/drawio#4404]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Trying to authenticate with OneDrive (Company) from Teams or through https://app.diagrams.net/

**To Reproduce**
1. Go to https://app.diagrams.net/
2. Click on OneDrive > Authorize
3. Authenticate with Company email
4. See error: Message: AADSTS7000112: Application 'b5ff67d6-3155-4fca-965a-59a3655c4476'(diagrams.net) is disabled.

**Expected behavior**
Authenticated with OneDrive

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/7138873/3445b4bd-3398-409f-81f9-877178f63184)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.4.0

**Comment by davidjgraph** [comment]
It sounds like your admin has disabled the app, have you talked to them?
