### ISSUE TITLE
Cannot add text to shape on iPhone/iPad

### ISSUE THREAD

**Issue by derekoharrow** [jgraph/drawio#4411]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When using app.diagrams.net from either my iPad or iPhone I cannot enter text in the shapes. You should be able to double-tap on the shape and enter text, but all that happens is that the shape is selected or deselected.

**To Reproduce**
1. Go to app.diagrams.net from Safari on iPhone/iPad
2. Add shape
3. Double-tape on shape to enter text
4. Nothing happens - keyboard doesn't pop up, etc.

**Expected behavior**
As above, should be able to double-tap on a shape to enter text.

**Screenshots**
n/a

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version v24.4.4

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro / iPad Pro
 - OS: IOS 17.5
 - Browser Safari, Chrome and Edge

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Comment by davidjgraph** [comment]
Fix in 24.4.6.
