### ISSUE TITLE
google fonts, some work, some don't

### ISSUE THREAD

**Issue by Rizkiacry** [jgraph/drawio#4414]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
"barlow" and it's family can be used (ie barlow-light), but "shantell sans" can't

**Expected behavior**
"shantell sans" should works too

**Screenshots**
<img width="1680" alt="Screenshot 2024-05-18 at 1 39 24 PM" src="https://github.com/jgraph/drawio/assets/154677201/d4349250-2228-495a-94cd-2df681b812d8">

**draw.io version**
24.4.4
MacOS and Windows
Arc Browser and Chrome
Latest Chromium

**I tested the problem in incognito/private mode with all browser extensions switched off:**
-yes

**Comment by alderg** [comment]
Shantell Sans works for me. [Here](https://app.diagrams.net/#RjVNNb4MwDP01HFcVorb0uHal22HaJCZNO0aQkmgBo8QMul%2B%2F0JgCqirtEuznbz8TsH3ZHQ2v5SvkQgfRMu8C9hREURhuVu7TI2ePbOO1BwqjcnIagVT9CgKXhDYqF3bmiAAaVT0HM6gqkeEM48ZAO3c7gZ5XrXkhboA04%2FoW%2FVQ5So%2BuYjbiz0IVkirH0cYbSj740iBW8hzaCcQOAdsbAPRS2e2F7nc3rMXHJXes176MqPA%2FAWxjt9BiFCfH3Uvz9vXdvdsHyvLDdUPzfgiL1DCehyUYaKpc9ImWAdu1UqFIa5711tbR7jCJpXZa6MQTVJjwUume8VTyCn0jKa8smVNozCVaIjoeoxV7dI9rvX96B7soAAoteK3sIoPyYsjsxTU5%2BeROnKRfRbtpAX9H4dbpNKIwKLq7uwuvjLhLFlAKNK7CkgIiRiTSEcektuNFhAPPcnINa8I4HWFxzTwS5QTialDHm7jYJj8WO%2FwB#%7B%22pageId%22%3A%22a7DV5Q-H3MIrrqjlVKb6%22%7D) is an example.

<img width="200" alt="Screenshot 2024-05-21 at 11 35 42" src="https://github.com/jgraph/drawio/assets/921200/54dda928-7b79-4af4-aa77-d65b59ab982a">
