### ISSUE TITLE
Typos in README.md

### ISSUE THREAD

**Issue by LionNatsu** [jgraph/drawio#4416]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**

1. Introduced in commit `22.0.0 release` @ 8906f90ac0cc50a0c6da77c28cf9b2b2339277b1, Section "License", ~~*but the are some*~~ should be *but there are some*.
https://github.com/jgraph/drawio/blob/f8838968d878c7a2f0f12cfa857f1d84f9018d0b/README.md?plain=1#L10

2. Introduced in commit `23.1.8 release` @ c0537e9260544a38c77d3436812dbee506d70912, Section "License", ~~*dilgence*~~ should be *diligence*, which it was prior to the commit. Probably deleted a character accidentally.
https://github.com/jgraph/drawio/blob/f8838968d878c7a2f0f12cfa857f1d84f9018d0b/README.md?plain=1#L14

**To Reproduce**

1. Read the README.md.

**Expected behavior**

No typo.

**Screenshots**
(not applicable)

**draw.io version (In the Help->About menu of the draw.io editor):**

- Current dev branch version, v24.4.4 (f883896) as for now.

**Desktop (please complete the following information):**
(not applicable)

**Smartphone (please complete the following information):**
(not applicable)

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
(not applicable)

**Additional context**

By the way, a little "meta-issue". This issue template doesn't look right for such a minor typo, and its fields mostly do not apply.

I found the typo in passing (yes, I do read every README.md). I would quite like to kindly, technically report it and concisely, but the banner says "You must fill in this entire template If you delete part/all or miss parts out your issue will be closed." does scare me, so I could only keep every unrelated field there and keep repeating *not applicable*, I must apologize. I am not sure if this is the correct way to report such typos.

**Comment by davidjgraph** [comment]
Thanks for pointers.
