### ISSUE TITLE
Switching between tabs does not work when working with CKeditor

### ISSUE THREAD

**Issue by VProtcay** [jgraph/drawio#4417]
### Preflight Checklist

* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**

When you try to move from one chart tab to another in the text, the chart editing form opens.

https://github.com/jgraph/drawio/assets/93017500/616a40bf-04b7-4c51-bc23-6de9b07bc8a7

**To Reproduce**
1. Add a diagram with several tabs to the text using CKeditor
2. In the text, switch between chart tabs

**Expected behavior**
In the text it is possible to switch chart tabs.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version x.y.z

**Desktop (please complete the following information):**
 - Browser Version [e.g. 22]

**Smartphone (please complete the following information):**

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-

**Additional context**

**Comment by davidjgraph** [comment]
This isn't an issue isolated to draw.io, this is an integration issue with other software. You're welcome to start a discussion, but this isn't a bug in draw.io alone, so it's not a valid issue.
