### ISSUE TITLE
Can't edit embedded diagrams in Word

### ISSUE THREAD

**Issue by Filip-Labarque** [jgraph/drawio#4420]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
The Draw.IO edit button of a diagram embedded in MS Word is greyed out. Clicking on "Edit Selected" after selecting an embedded Draw.IO diagrams throws this error: "No diagrams found in the selection”.

**To Reproduce**
1.Install the draw.io add-in for Microsoft Word
2.Open a new document in Microsoft word. Click on Insert -> 'draw.io', pick a device file and click Insert.
3. Edit button remains greyed out.
4. Select the embedded diagram and click on "Edit Selected".

**Expected behavior**
The Draw.IO editor should open with the selected diagram.

**Screenshots**
![2024-05-15 08_35_55-Document1 - Word](https://github.com/jgraph/drawio/assets/95751753/bb15dda1-8874-418f-a270-450bb62edd78)
![2024-05-15 08_37_50-Document1 - Word](https://github.com/jgraph/drawio/assets/95751753/4f9cbeb5-b639-4c6e-b5b1-4792c195d185)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.4.0

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Chrome
 - Browser Version 124.0.6367.202

**Smartphone (please complete the following information):**

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-

**Additional context**

**Comment by davidjgraph** [comment]
Unfortunately, not being able to recreate the error, there isn't anything we can do here.
