### ISSUE TITLE
The diagram is not saved if more than three pages are added to it

### ISSUE THREAD

**Issue by Berestanadi** [jgraph/drawio#4421]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
We have integrated ckeditor in our application and it has the ability to create diagrams via draw.io.  And when creating a chart on three or four pages, the error "Not a chart file" appears. Then, after resaving, the editor closes but the diagram from the last page is saved in the document, all other pages are deleted

**To Reproduce**
1. add a diagram via the ckeditor panel'
2. in the draw.io editor that opens, add diagrams on three pages
3. Click save and exit
4. A modal window appears with an error in it, click OK
5. Click save and exit

**Expected behavior**
Diagrams on all pages are saved

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version v24.4.4

-

**Additional context**
ckeditor is integrated into our application and it is through it that we can open draw.io to create diagrams

**Comment by davidjgraph** [comment]
Bug reports need a stone-alone reproduction case. If you have integration issues with other software, that's your issue to fix.
