### ISSUE TITLE
Explore plugin overlays multiple connectors between neighbouring classes in UML diagram

### ISSUE THREAD

**Issue by Chris-ECE** [jgraph/drawio#4422]
Hello,

The explorer plugin can be used to make UML diagrams navigable, by showing only nearest-neighbour relations between classes. - However, when a pair of neighbouring classes have multiple connections/relations (i.e. arrows), the plugin renders these on top of each other, and it is not possible to clearly see the different relations.

To illustrate this issue, please see the example UML diagram below, and how it is rendered by the explorer plugin:
![image](https://github.com/jgraph/drawio/assets/136598758/4198492d-02bc-4f3f-b753-c54a5a41d367)

This is how the plugin renders it:
![image](https://github.com/jgraph/drawio/assets/136598758/503b80ab-c4b4-40c5-8169-df6251303ff8)

Please could some sort of minimum spacing be incorporated in the display of multiple arrows between neighbouring classes?

Thank you

**Comment by davidjgraph** [comment]
Fix in 24.4.6.

**Comment by Chris-ECE** [comment]
That's fantastic, and the curly arrows are actually quite attractive too. - I will raise a separate request about text/label placement, which I neglected to mention earlier. Thanks!
