### ISSUE TITLE
Simple Mode - Find/Replace missing in menus/tools

### ISSUE THREAD

**Issue by jaylapras** [jgraph/drawio#4423]
* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

In Classic mode, Edit > Find/Replace exists. 
In Simple mode, this is not in any menu/toolbar that I can find as there is no Edit menu item. 
The keyboard shortcut (ctrl+f) still works to bring up the dialog. 

<img width="1621" alt="image" src="https://github.com/jgraph/drawio/assets/60265913/cb415570-26cd-4133-ad57-9af44fe229b6">

**Describe the solution you'd like**
Not sure where it would logically sit in the Simple mode menu/toolbar structure. 

Perhaps in the right-click context menu when nothing is selected and clicking on a blank area of the diagram?

**Comment by jaylapras** [comment]
Uh... yeah, that. I never think to look there, as it doesn't feel like a menu/set of tools. 
Thanks!

**Comment by alderg** [comment]
All tool windows are in that menu.
