### ISSUE TITLE
[bug] Replay plugin requires you to hit "Record" button twice before it works

### ISSUE THREAD

**Issue by samyk** [jgraph/drawio#443]
When trying to use the Replay plugin, it requires going to Extras->Record *twice* before showing the record prompt.

**Comment by samyk** [comment]
My bad, I understand now that the first time begins recording, second time stops -- I was using it to "record" an animation so didn't notice. Would be nice to have an indication that it's recording, and perhaps have the name of the button change to "Stop Recording".

**Comment by alderg** [comment]
Good point. This will be fixed in the next release.
