### ISSUE TITLE
Connection points for groups don't appear to be working

### ISSUE THREAD

**Issue by mrtoikka** [jgraph/drawio#4435]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.
  * I found [Issue 2606](https://github.com/jgraph/drawio/issues/2606), but it was marked closed due to inactivity; and posting to it didn't seem to re-activate it, so I figure I'll create a 'new' issue. If I need to close this one and instead post to the original/old issue please let me know.

**To Reproduce**
Like the OP, I am able to group two items, and with the group selected, I can edit connection points. However, they don't appear to work. After setting them, all I can see when hovering over the group to draw connections are the original shape's connections points.

**Expected behavior**
I expect to see new connections points that I set for the group. (No expectation for whether points for the original shapes that are part of the group are shown or not).

**draw.io version**
- I am using 24.2.5

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser: Chrome
 - Browser Version: 124.0.6367.210 (Official Build) (64-bit)
   - Note: I am using the desktop version/executable of draw.io

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- Not applicable? As I'm using the desktop version/executable of draw.io?

**Additional context**
None at this time.

**Comment by alderg** [comment]
See https://github.com/jgraph/drawio/issues/2606
