### ISSUE TITLE
Version macro/element

### ISSUE THREAD

**Issue by JoSSte** [jgraph/drawio#4436]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Version determination of printed/exported diagrams is frustrating if you do not manually create a text field with the version. I can see that I am not the only one looking for such a feature: https://stackoverflow.com/questions/78493666/display-and-automatically-update-the-current-version-of-draw-io-diagramm-inside

**Describe the solution you'd like**
A macro like `%version%` or `{{version}}` in a text field which will change to the actual name and version of the diagram when saved/exported.

**Describe alternatives you've considered**
Alternatively a version element that can be added would be nice.

**Additional context**

**Comment by davidjgraph** [comment]
And if you save to device, how do you know what the versioning is?

And if you're collaborating on Google Drive and two users save different version numbers, which do you use?
