### ISSUE TITLE
Alternative SVG export

### ISSUE THREAD

**Issue by EltonCN** [jgraph/drawio#4446]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Hi! I usually use draw.io to prepare diagrams for presentations of the projects I carry out, however I recently noticed that the option to export "Convert labels to SVG" was removed (I've seen the issues explaining the reason related to maintaining a server for it ). I usually prepare presentations using [Canva](https://www.canva.com/), and for some reason it only supports SVG when exported using this option. I have already tested a combination of the other options present in the export dialog, and with all others it indicate that the file is not supported.

**Describe the solution you'd like**
> A clear and concise description of what you want to happen.

From what I understand, what the previous solution accomplished was:

- Export the diagram as PDF
- Send the PDF to the server
- Import the PDF into Inkscape
- Export to SVG in Inkscape
- Send back the generated SVG

Would it be possible to replicate this functionality in the desktop version of draw.io, performing the conversion locally? Considering that the user already has Inkscape installed and added to the path. I believe it would be something like exporting to PDF in a temporary file, calling draw.io, performing the conversion and deleting the temporary file, right?

**Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

I was able to manually perform the conversion, `inkscape --export-type="svg" <drawio_pdf_file.pdf>`, but it would be much better and faster to have an automatic option directly in draw.io.

**Additional context**
> Add any other context or screenshots about the feature request here.

**Comment by davidjgraph** [comment]
Not locally, no. It adds the risk of a security hole by allowing execution of another app. I'd suggest to automate or batch process.
