### ISSUE TITLE
Page breaks are misaligned on previewing multiple pages 

### ISSUE THREAD

**Issue by nobi-nobita** [jgraph/drawio#4447]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
When I try to preview multiple pages, page breaks are misaligned between edit screen and preview.

**To Reproduce**
1. Make a new file with A3/landscape
2. Place any shape at (0, 0) *upper left of the first page
3. Place another shape at (0, 23380) *upper left of the page no. 20
4. Press Ctrl + P to show print dialog
5. Click "Preview" button with default print configuration
6. See error; the second shape spans page no. 19 and no. 20

**Expected behavior**
The second shape is placed at the upper left of the page no. 20

**Screenshots**
![editing_screen](https://github.com/jgraph/drawio/assets/25452612/eb9a8020-2bb6-4752-a798-6d741424eccd)
![preview_screen](https://github.com/jgraph/drawio/assets/25452612/05f7c0c9-1963-4769-b9de-a4508d0c3cfe)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.4.13

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Browser Version: 125.0.6422.112

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**
The page number I specified above is not important. This behavior occurs with any numbers (e.g., 10, 20, 50, 100) of pages.

**Comment by davidjgraph** [comment]
24.7.4

**Comment by nobi-nobita** [comment]
> 24.7.4
I confirmed the expected behavior. thank you so much!
