### ISSUE TITLE
[Feature Request] Define Resolution for Editable PNG Files (.drawio.png)

### ISSUE THREAD

**Issue by sva-mk** [jgraph/drawio#4451]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Firstly, thank you for the fantastic work on Draw.io! It is an incredibly useful tool for creating diagrams and visual content.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to integrate diagrams into LaTeX documents or other professional documentation directly. The current options for the `.drawio.png` format do not allow me to specify the resolution (DPI), which results in outputs that may not meet the required quality standards.

**Describe the solution you'd like**
I would like to have the option to define the resolution (DPI) for `drawio.png` files, which can then be directly integrated into LaTeX documents or similar. Ideally, this feature would include:
- An option within the convert dialog box to specify the DPI value.
- A default DPI setting that can be configured in the application preferences, applying to all diagrams unless otherwise specified.

**Describe alternatives you've considered**
Currently, I have to adjust the resolution after exporting the diagrams, which is not efficient and may compromise the quality of the output. Another alternative could be  using the editable `.drawio.svg` files and then converting them with other tools, but this adds extra steps to the workflow and is less seamless.

**Additional context**
Having the ability to define the DPI would greatly enhance the usability of Draw.io for integrating high-resolution diagrams directly into LaTeX documents and other professional documentation. It would provide better control over the quality of diagrams, ensuring clarity and detail are maintained. 

Thank you for considering this feature request. Your work on Draw.io is greatly appreciated!

**Comment by davidjgraph** [comment]
Use the zoom and fix the size of the image on the target platform.

**Comment by sva-mk** [comment]
Thank you for your prompt reply.

I have tried using the zoom feature and resizing the image on the target platform as suggested, but have not been successful so far. The resolution does not seem to change significantly when using the zoom feature.

Could you please provide a brief guide on how to properly adjust the zoom and fix the size to achieve the desired resolution? Any specific steps or tips would be greatly appreciated.

Thanks again for your help!

**Comment by sva-mk** [comment]
Never mind, I tried using the zoom feature again and now it works. 

Thank you again for your help!
