### ISSUE TITLE
Error: "Not a Diagram File" when attempting to Publish a draw.io

### ISSUE THREAD

**Issue by izarni** [jgraph/drawio#4456]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
_I open my saved Diagram from local drive, but facing an error of "Not a Diagram File"_

**To Reproduce**
1. Go to 'File'
2. Click on 'Open From'
3. Click to 'Device'
4. Open the file.
5. See error of "Not a Diagram File"

**Expected behavior**
_The diagram file should be able to load._

**Screenshots**
- 
![image](https://github.com/jgraph/drawio/assets/171758418/0d10ed65-9fc0-4e2f-a145-99ac21b1c5cf)]
![Screenshot 2024-06-05 102128](https://github.com/jgraph/drawio/assets/171758418/d289504c-1cb4-441a-97c9-52b6732185b8)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version v24.4.0

**Desktop (please complete the following information):**
 - Browser: Edge
 - Browser Version: Version 125.0.2535.67 (Official build) (64-bit)

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- Yes

**Comment by davidjgraph** [comment]
Can you attach it here as a zip, or send to support@diagrams.net if the file is sensitive.

**Comment by davidjgraph** [comment]
I don't see the file attached in this issue.

**Comment by izarni** [comment]
Please check as attached.
1. The saved draw.io file as attached.
2. The screenshot of the error.

**Comment by davidjgraph** [comment]
There is no attachment on https://github.com/jgraph/drawio/issues/4456, without that, we cannot assist.

**Comment by izarni** [comment]
please retry again. thanks

**Comment by davidjgraph** [comment]
Use github directly.

**Comment by izarni** [comment]
[Screenshot 2024-06-05 102128.zip](https://github.com/user-attachments/files/15613247/Screenshot.2024-06-05.102128.zip)

**Comment by alderg** [comment]
Try opening the file with v24.4.13

**Comment by izarni** [comment]
I download the said version and it works as of now. Thank you for your help.
