### ISSUE TITLE
Can support live editor of mermaid

### ISSUE THREAD

**Issue by zhanjinhao** [jgraph/drawio#4457]
Some image is easy to descibe in mermaid.

but drawio do not support live editor of mermaid

i always write mermaid code in https://mermaid.live/. And copy to drawio.

i have found some other project support live editor of mermaid. for example: typora - https://github.com/typora

so can drawio support this feature.

thank you

**Comment by davidjgraph** [comment]
Mermaid is provided "as-is", it's not a core feature. We don't load the maintenance load of additional functionality.
