### ISSUE TITLE
Update IBM VPC Tab Icons

### ISSUE THREAD

**Issue by ggdaly** [jgraph/drawio#446]
Hello, can we please request an update to the IBM VPC icon tab see image below with attached file.  Thank you...this is a fairly important update any chance we can expedite?

![image](https://user-images.githubusercontent.com/19595321/58889417-7b258a00-86ae-11e9-993e-cdc54388db0e.png)
[VPCv2.0j.xml.zip](https://github.com/jgraph/drawio/files/3258440/VPCv2.0j.xml.zip)

**Comment by kutya** [comment]
Will be in next release.
