### ISSUE TITLE
Exporting math to PDF leaving huge blank space

### ISSUE THREAD

**Issue by Hi-Peng** [jgraph/drawio#4464]
Last time, math typesetting got error when export, but already fixed in latest release (thank you). But i got another problem, when i try to export it as PDF and enabling the corp (for latex import), i had a huge white space. Is there any way to fix it? Thank you
[Step1.pdf](https://github.com/jgraph/drawio-desktop/files/4513052/Step1.pdf)

**Comment by davidjgraph** [comment]
We recognise that this is affecting a number of users, but unfortunately we'll have to decline the issue.

We simply don't know the bounds of the math typesetting and we can't guess it. The text isn't cut off, so no information is lost. Some addition trimming of the PDF is required, but that is technically possible.
