### ISSUE TITLE
More problems with obscured labels with Explorer Plugin

### ISSUE THREAD

**Issue by Chris-ECE** [jgraph/drawio#4467]
Following the fix applied (in 24.4.10.) to issue #4424, there are further problems with the appearance of labels when using the Explorer Plugin.

While it's good that the labels have been brought to the front (both cardinalities and arrow labels), they now obscure each other. - The arrow labels tend to now be at one end of the arrow, which usually obscures some of the cardinalities, so I wonder if these should be nearer to the middle of the arrow to give a better chance of not overlapping with them? 

If it's feasible to enforce a minimum separation of labels/cardinalities, that would be great. - This has the potential to be such a powerful plugin.

Also, maybe cardinalities could be slightly offset so that they don't obscure the arrowhead (which identifies the type of relation).

Here is an example of how the same diagram appears since the fix in 24.4.10, and it's clear there are some issues:
![image](https://github.com/jgraph/drawio/assets/136598758/bfe5f94f-a95d-4c44-865f-1835663425a1)

Maybe there are some tweaks that could be made?

Many thanks!

**Comment by davidjgraph** [comment]
Thanks for the suggestion, but we have limited resources for a large number of issue. We don't have any further time to spend on the explore plugin.

**Comment by Chris-ECE** [comment]
I understand. - Would it be okay for me to re-raise this again in a few months' time?

Thanks
