### ISSUE TITLE
suggestion: make drawio a spring-boot and maven/gradle based project

### ISSUE THREAD

**Issue by chenkunyun** [jgraph/drawio#447]
The current java world is spring boot or maven/gradle based.

**Comment by davidjgraph** [comment]
Haha, good one. We laughed long over this one.

**Comment by chenkunyun** [comment]
@davidjgraph 

Is this some sort of joke that a non native English speaker won't get?

Maybe I didn't express my opinion well then.

What I'm suggesting is to :
1. make drawio sprint boot based, so the user can run it simply with "java -jar xxxx.jar"
2. use maven/gradle to manage the dependency. There's no need to put all the jars in WEB-INF/lib

**Comment by joshuaboniface** [comment]
I second this. It's frustrating to find all these self-hosted projects that require some custom Docker image or other convoluted nonsense to get set up. Let us run this with `java`.

**Comment by davidjgraph** [comment]
It's a static web app, you don't need the Java parts in 99.5% of cases. It's a ridiculous complication of something that's very simple and it'll be out of date in 6 months when the next set of buzzwords come out.
