### ISSUE TITLE
BPMN group shape doesn't respect the dark mode

### ISSUE THREAD

**Issue by lvmm** [jgraph/drawio#4471]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
BPMN group shape doesn't respect the dark mode and uses hardcoded black colour.

**Screenshots**
![BPMN5](https://github.com/jgraph/drawio-desktop/assets/11752339/f0e86c6c-cd14-419a-82db-8c08f04d12a7)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.5.1

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by davidjgraph** [comment]
Fix in 24.5.4.
