### ISSUE TITLE
check the version 

### ISSUE THREAD

**Issue by hammadali315** [jgraph/drawio#4476]
@startdfd
// External Entities
entity "Student" as E_Student
entity "Librarian" as E_Librarian

// Processes
process "1. User Registration" as P1
process "2. User Login" as P2
process "3. Manage Book Catalog" as P3
process "4. Search Book" as P4
process "5. View Book Details" as P5
process "6. Borrow Book" as P6
process "7. Return Book" as P7
process "8. View Borrowing History" as P8

// Data Stores
database "User Database" as DS_UserDB
database "Book Database" as DS_BookDB
database "BorrowTransaction Database" as DS_TransDB

// Data Flows
E_Student -> P1 : Register
P1 -> DS_UserDB : Save User Info

E_Student -> P2 : Login
P2 -> DS_UserDB : Verify Credentials

E_Librarian -> P3 : Manage Book Catalog
P3 -> DS_BookDB : Update Book Info

E_Student -> P4 : Search Book
P4 -> DS_BookDB : Retrieve Book Info
DS_BookDB -> E_Student : Display Search Results

E_Student -> P5 : View Book Details
P5 -> DS_BookDB : Get Book Details

E_Student -> P6 : Borrow Book
P6 -> DS_BookDB : Update Book Status
P6 -> DS_TransDB : Record Transaction

E_Student -> P7 : Return Book
P7 -> DS_BookDB : Update Book Status
P7 -> DS_TransDB : Update Transaction

E_Student -> P8 : View Borrowing History
P8 -> DS_TransDB : Retrieve Transaction History
DS_TransDB -> E_Student : Display History
@enddfd

This code does not runs on draw.io , it show error that check version.

**Comment by davidjgraph** [comment]
Use the template to submit a bug report.
