### ISSUE TITLE
Request for Skew/Shearing Image/Shape Options 🙏

### ISSUE THREAD

**Issue by UsmanMaqbool** [jgraph/drawio#4477]
* [* ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [* ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
 is an amazing tool for creating diagrams and graphics, but it's missing a crucial feature - the ability to skew or shear images and shapes. This feature is essential for creating complex transformations and perspectives in diagrams. 

**Describe the solution you'd like**
I kindly request the addition of skew/shear options for images and shapes. This could be achieved through:
- Adding skew/shear tools in the toolbar
- Implementing CSS-like transformations (e.g., transform: skewX(10deg))
- Providing a JavaScript API for applying custom transformations etc.

**Describe alternatives you've considered**
I've used photopea.com for applying such transformation -> export PNG -> import to draw.io

**Comment by davidjgraph** [comment]
Thanks for the suggestion, but these are features of a vector drawing tool, which draw.io is not.

**Comment by hochbit** [comment]
> Thanks for the suggestion, but these are features of a vector drawing tool, which draw.io is not.

I don’t agree and **strongly** suggest this to be reconsidered.

* draw.io already supports basic transformations (rotate, flip, scale), so this is not fundamentally outside its scope
* the requested behavior is just a transform (skew / projection), not full vector editing

Concrete issue:

* Let *M* be any icon from the library (see attached image)
* for an isometric diagram, the same icon is needed on:

  * top face
  * left face
  * right face
  * (optionally) front variation depending on style

Current workaround:

* maintain ~4 (or more!) separate versions per icon (if you only want the above mentioned, there are other angles)
* duplicate + manually adjust each variant
* higher maintenance
* cumbersome use of external tools for creation
* icon set gets overloaded

What this feature would enable:

* reuse a single icon (for example *M*)
* apply a perspective transform
* Have it fit the perspective of other existing icons, for example the homepage icon on the computer screen.


So this is less about “vector tool features” and more about reducing duplication with applying just a perspective transform.

<img width="858" height="545" alt="Image" src="https://github.com/user-attachments/assets/2f92e14a-fab5-4bda-9869-129536ffd024" />

I created a diagram with 10 of such blocks each with a different service logo, that is somewhat annoying.
Please reopen and implement this! 🙏
