### ISSUE TITLE
Failed to execute 'showSaveFilePicker' on 'Window': File picker already active.

### ISSUE THREAD

**Issue by jwergin** [jgraph/drawio#4486]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
When I try to open and existing diagram or when I try and create a new one I get this error inside Google Chrome. I switched to Safari and it just didn't acknowledge I had clicked a button.

**To Reproduce**
From the initial dialog select "device" and then select "from existing file"

**Expected behavior**
Up until last week it opened a dialog where I could select my file.

**Screenshots**

version 24.5.5

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser Chrome (version  126.0.6478.62) and Safari  (version 17.0 (19616.1.27.211.1))

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes on both browsers

**Additional context**
worked until a week or so ago.

**Comment by alderg** [comment]
This works for me. What version of iOS are you using?

**Comment by jwergin** [comment]
nevermind. ios was hung up updating... I guess for a while now. not an issue.
