### ISSUE TITLE
PDF exporting that actually looks good and is usable

### ISSUE THREAD

**Issue by MScoutsDCI** [jgraph/drawio#4488]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
PDF exporting has never really been a viable option for several reasons:
1. Dark mode still isn't supported
2. Some text and other elements become either very difficult or impossible to see in a PDF export (even though it's fine in light-mode in the diagram itself
3. Choosing the grid option has no effect

**Describe the solution you'd like**
Ideally I would love it if a PDF export simply looked exactly like the diagram does when I'm working on it.

**Describe alternatives you've considered**
I've tried exporting as various image formats and even the advanced options, but none of that results in an improved export.

**Additional context**
Here are 2 screenshots to clearly illustrate the issue:
Original diagram while in the app:

![original file](https://github.com/jgraph/drawio/assets/1620509/f5443e80-c09e-4d1d-b5c5-63e52e8c17e4)

PDF export (with the Grid option checked):

![pdf export](https://github.com/jgraph/drawio/assets/1620509/ab92a1df-67d1-4ed8-81ed-ae606c784be7)

Clearly, at least in my opinion, the PDF exported version is basically unusable.

**Comment by alderg** [comment]
Which version of draw.io are you using?

**Comment by MScoutsDCI** [comment]
My apologies, I was a version or two behind and now I"m running 24.5.3. This version seems to have resolved the issue where the grid doesn't show up in the export. However there's still one issue I"m seeing with that option. When I change the diagram to light mode and then export with the grid, it looks fine. If I export from dark mode however, the grid in the export is much more prominent in the foreground instead of being in the background:
![2024-06-19 11_30_10-Window](https://github.com/jgraph/drawio/assets/1620509/12ebbaf3-bd11-45fc-aaa8-6618d1856dc0)

As far as the inconsistent text visibility, I think I've traced that to an issue with choosing a style preset as opposed to manually recoloring an icon. I.e. if I choose one of the style presets, the icon's attached text does not properly flip between white and black when changing from dark to light (this affects the exports as well). On the other hand, when I manually choose new fill and line colors for an icon, the text acts as expected and changes to remain visible. Perhaps this should be open as a separate issue?

**Comment by davidjgraph** [comment]
Fix in 24.6.0.
