### ISSUE TITLE
add "Format->Diagram->Animation" Checked  Button to hide or show animation

### ISSUE THREAD

**Issue by DroidPusher** [jgraph/drawio#4491]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I use "Flow Animation" connection. This is a great feature but consumes large amount of CPU performance -> battery power. It leads to excessive heat and rapid discharge of my notebook.

**Describe the solution you'd like**
It would be great to be able to Hide or Show animation graphics when needed without changing actual property "Flow Animation".

**Describe alternatives you've considered**
Manualy turn off "Flow Animation" for all connection in the diagram. Which is VERY inconvenient.

**Additional context**
![image](https://github.com/jgraph/drawio/assets/25544075/d57fe598-75bc-4ebd-88f7-bbf8cd7eea92)

**Comment by davidjgraph** [comment]
24.6.0 adds config option:
```

{
  "enableAnimations": false
}
```

**Comment by DroidPusher** [comment]
thanks!

**Comment by DroidPusher** [comment]
Result:
![image](https://github.com/jgraph/drawio/assets/25544075/4efbfb83-926e-4344-8a0c-2f5b4cd7b1c7)

Still would be even better to have interactive button to switch between fast:
![image](https://github.com/jgraph/drawio/assets/25544075/c64303ac-2ee5-4e27-9311-dd667707c2a9)
