### ISSUE TITLE
mport vsdx from Microsoft Visio to draw.io desktop(web), but problem is it is not displayed, see attached.

### ISSUE THREAD

**Issue by stuarthill0** [jgraph/drawio#4494]
import vsdx from microsoft to [draw.io](http://draw.io/) desktop , but problem is it is not displayed, see attached.

Drawio app:
Mac iOS (24.5.1)
File: https://raw.githubusercontent.com/microsoft/CloudAdoptionFramework/master/ready/sap-landscape-multiple-systems-ref-architecture.vsdx

**Comment by davidjgraph** [comment]
Looks fine to me on a macos. What exactly do you see?

<img width="1111" alt="Capture d’écran 2024-06-21 à 13 04 34" src="https://github.com/jgraph/drawio/assets/1761087/61163bcf-cab8-47ef-bd5a-290bc84cadb5">

**Comment by stuarthill0** [comment]
￼

**Comment by stuarthill0** [comment]
I have Ventura 13.6.7 (22G720).

**Comment by m-mohamedin** [comment]
Did you check the pages? There are 4 pages and first two are almost empty
