### ISSUE TITLE
Preserve exported settings

### ISSUE THREAD

**Issue by luodeyu** [jgraph/drawio#4498]
First of all, I would like to thank the developer for bringing such a good software. My question is: everyone probably has some fixed export settings, such as selecting "selected content only" when exporting PDF, cropping, border width of 0, etc. However, these settings will disappear after closing the software, which will cause some troubles to users because they have to set them again every time.
![image](https://github.com/jgraph/drawio/assets/40289797/8c0c3bb5-acbe-46a6-9540-bbd502dcc160)

**Comment by yan12125** [comment]
Seems a similar issue as https://github.com/jgraph/drawio/issues/3375 and https://github.com/jgraph/drawio/issues/2729

**Comment by davidjgraph** [comment]
Duplicate #2729
