### ISSUE TITLE
export my diagram data as a URL, will it be saved on some server?

### ISSUE THREAD

**Issue by Laimic** [jgraph/drawio#4499]
If I export my diagram data as a URL, will it be saved on some server? Will my data be leaked?
If it is saved on the [diagrams.net](http://diagrams.net/) server, how can I delete it?

**Comment by Laimic** [comment]
> The diagram data is encoded in the URL itself and as such, cannot be deleted once it was shared.

Thank you very much for your response. So, I will export it as a URL. The graphics themselves won't be stored on any server, but once I share my URL, my content will be permanently leaked, is that correct?

**Comment by davidjgraph** [comment]
correct, think of the URL as being the same as a PNG file you have locally.

Also note that the data in the URL is not exposed to any web search engines, they cannot see it.
