### ISSUE TITLE
Draw.io Licensing Query - Scenarios Included

### ISSUE THREAD

**Issue by anilkm5** [jgraph/drawio#450]
Hi Team,

Based on the support ticket #13364, was advised to post the below query here.
Hence doing the same for appropriate responses. 

Could you kindly address the licensing queries for the below mentioned scenarios.

1. For the current project work, in the scenario of downloading the draw.io main branch code (from git hub) and using it by hosting it in our own code repository along with using custom code customization on top of that, would this usage be right to be accounted under Apache 2.0 licensing purview. 

2. Are there any components used within the draw.io code base, that have any separate licensing requirements which need to be adhered to while using draw.io code for our project.

Kindly share your opinion and looking forward to hearing from you.

Thanks,
Anil

**Comment by davidjgraph** [comment]
1. It's Apache 2.0 licensed, yes. If you want an anaylsis of whether you are following the license correctly for a particular usage, we cannot give legal advice, your best route is to consult a lawyer knowledgable in this area.

2. The due diligence of third-party OS components used in draw.io can by found at https://github.com/jgraph/security-privacy-legal/tree/master/OpenSource
