### ISSUE TITLE
[Bug] Highlight position calculation ERROR for basic mxShape

### ISSUE THREAD

**Issue by repo-ooo** [jgraph/drawio#4509]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The Highlight rect position is not currectly calculated for basic mxShape, which is doubled.

See https://app.diagrams.net/?p=f5&tags=%7B%7D&lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1#R%3Cmxfile%3E%3Cdiagram%20name%3D%22%E7%AC%AC%201%20%E9%A1%B5%22%20id%3D%22WQ1SrHj4c_pCWc8x_PhW%22%3EdZNNb4MwDIZ%2FDcdWfAjWHTsKnaauPVTTtFMVIIW0gURJGLS%2FfgkJX%2Bp6In5sJ%2FZrY3lh2W4ZoMUnySC2XDtrLW9jua5j%2B7b8KHLTxPcDDXKGMhM0giO6wz7T0BplkM8CBSFYIDqHKakqmIoZA4yRZh52Jnj%2BKgU5fADHFOBH%2Bo0yUWi6cl9G%2Fg5RXvQvO8Gr9pSgDzad8AJkpJkgL7K8kBEi9KlsQ4iVeL0uOi9%2B4h0KY7AS%2FyR8ccgOyUVp4toYJHIuXZBOw6i6ahskpJb56wQDiTpn%2F8R59xG19j2%2Be7TyT%2FvdD%2BKHhTOUPpTExa2Xi%2BquCyHUfNaqGje%2B5Go3ljkSRZ0sEZEoY6BBZIFRwqVlPme%2Fq%2F5NKkXVfWWrExlIr7F%2FVJQvE5SfED05gW3L0ALwCDA1Y2UhHjPSqeF01iY0Dsr3dWmw7vEXMgHbp1JOu9xCUkLBbjLEJHhmpGanA2M244I4wUqzYrocZvWB2cl8uHgcmzwYXXtzMsgejUvThU9%2BPS%2F6Aw%3D%3D%3C%2Fdiagram%3E%3C%2Fmxfile%3E#%7B%22pageId%22%3A%22WQ1SrHj4c_pCWc8x_PhW%22%7D

**To Reproduce**
1. Enable rackf5 plugin: https://app.diagrams.net/?p=f5
2. Add a rackf5 shape, e.g., the first one
3. Add link to the shape, e.g., about:blank
4. Export as URL, note that the plugin `p=f5` should be added to the generated url, e.g., https://app.diagrams.net/?p=f5&tags=.......
5. Hover the rackf5 shape to show the highlight box, which is not currectly drawn.

I believe the bug is caused by the duplicated counting of position,
https://github.com/jgraph/drawio/blob/61019d09622a65b48c17a6e159c2f17d23de4d95/src/main/webapp/mxgraph/src/util/mxSvgCanvas2D.js#L1342-L1352

called by
https://github.com/jgraph/drawio/blob/61019d09622a65b48c17a6e159c2f17d23de4d95/src/main/webapp/mxgraph/src/shape/mxShape.js#L953-L958

**Expected behavior**
The hightlight box should match the position of the shape.

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/169794098/a5a3cddb-a1ce-496e-a8c5-6e4669ea84a6)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.6.4

**Desktop (please complete the following information):**
 - OS: win11
 - Browser chrome
 - Browser Version 125.0.6422.113

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**
Maybe related to #4501.

**Comment by davidjgraph** [comment]
I feel quite faint, there are actually people who know how to submit a correctly formed bug report....

**Comment by davidjgraph** [comment]
24.7.5
