### ISSUE TITLE
drawio extension for Google Docs is not working well

### ISSUE THREAD

**Issue by SarelSchlesinger** [jgraph/drawio#4515]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
I installed the extension in Google Docs and tried to add a chart and every time I got an error message

**Screenshots**
https://www.loom.com/share/4e3aa69c1a3b48b088ea1750fd44ee5e?sid=990ab406-55a9-414c-ae9c-27e6d2a4c33c
I did a record of the bug

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.6.1

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser chrome
 - Browser Version 126.0.6478.127

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**

**Comment by davidjgraph** [comment]
That's a error with the Google Drive picker, it's not an error in our code. As i workaround I would suggest to already have the file uploaded to Google Drive prior to selecting in the addon.
