### ISSUE TITLE
Microsoft Azure Icons library update

### ISSUE THREAD

**Issue by FlorisWaternet** [jgraph/drawio#4518]
* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
The Azure icon library dates from dec 2022 and is outdated.
https://www.drawio.com/blog/azure-diagrams

**Describe the solution you'd like**
update the library from;
https://learn.microsoft.com/en-us/azure/architecture/icons/
While doing this, just as well take the other icon sets along:
Dynamics 365: https://learn.microsoft.com/en-us/dynamics365/get-started/icons
Powerplatform: https://learn.microsoft.com/en-us/power-platform/guidance/icons

**Describe alternatives you've considered**
Every user has to copy paste the icons themself. Less user friendly

**Comment by egrimate** [comment]
Azure update already implemented and the other two additional sets will be in the next release
