### ISSUE TITLE
File handler prefix

### ISSUE THREAD

**Issue by duydao** [jgraph/drawio#452]
Hi,

I'm working on a gitlab integration similar to the github mode, where we can save files using gitlab as storage. So far, I've managed to authenticate, open, load and store files on github, I'm working on "save as gitlab" at the moment.

I've noticed that draw.io uses Prefixes to differentiate the storage types, `H` for github, `G` for google drive etc.

What would be a good prefix for gitlab & bitbucket?

Best regards,

Duy

**Comment by davidjgraph** [comment]
You went with #GITLAB?

**Comment by duydao** [comment]
At that time i didn't realize that the prefix will be used as hash link. I can change, but you would have to decide what letter it should be. Please assign one for bitbucket as well while you're on it ;)

**Comment by alderg** [comment]
Please use A for GitLab and B for Bitbucket.
