### ISSUE TITLE
Request for Feature as a GIF Export

### ISSUE THREAD

**Issue by bugattie** [jgraph/drawio#4526]
* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the solution you'd like**
I wanted to Request a feature "Export as a GIF". It would help a lot to export Flow Animations as GIFs, as it will save us from going through a long process of making the flow animation available to show somewhere.

**Comment by davidjgraph** [comment]
Duplicate https://github.com/jgraph/drawio/issues/3739
