### ISSUE TITLE
Export png is not good 

### ISSUE THREAD

**Issue by VictorG1422** [jgraph/drawio#4531]
**Describe the bug**
not produce correct image what I drawn, its shows other details in export image

**To Reproduce**
1. Go to '...' files
2. Click on '....' export as PNG

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/109729215/84044c29-880d-44d0-9784-e1e99f125117)

- draw.io version 24.6.4

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser chrome
 - Version 24.6.4

**Comment by davidjgraph** [comment]
this bug report ain't brilliant either.
