### ISSUE TITLE
Ability to select only a certain type of element from a selected group of elements

### ISSUE THREAD

**Issue by gomarcus** [jgraph/drawio#4540]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When selecting elements at ones, the style panel only displays settings that are common for the range of selected types. But most times I simply want to edit one e.g. lines or rect, but selecting them one after a nother is due to the multitude of elements not feasible.

**Describe the solution you'd like**
Would be great, if it would be possible to select with mouse a group of elements (like it is currently supported) and then use a secondarily sub-selection for selecting e.g. all the selected lines or rectangles, so it is easily possible to style for example all lines but not the selected rect. A good place for such a sub-selection selector might by right over the style panel.

**Currently supported similar action**
- select a group of elements
- edit > select all node points
... this is a good option if you only want to differentiate between nodes and connections. The suggested implementation could be also implemented in this location, as edit > "select only" > "{element:type}" ... listing only the element types with at least one element selected.

**Where it would also be useful**
when adding CSS classes to elements becomes available, this would allow easy selection and application of classes to elements of specific element types.

**Comment by davidjgraph** [comment]
Thanks for your suggestion. Upon review, this is outside of the scope of functionality I want for the tool.
