### ISSUE TITLE
Error Loading File | Flow is deleted from first tab of Draw.io file 

### ISSUE THREAD

**Issue by LakshmanMuppuri** [jgraph/drawio#4541]
### Preflight Checklist

* [ Yes] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [Yes ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
I see an error "Error Loading File" and its not a "Diagram File" when we try to open the file. 

**To Reproduce**
Open the file attached and you will notice the error

**Expected behavior**
Open the file with diagram that I have created

**Screenshots**
![image](https://github.com/user-attachments/assets/68fb0d2f-ae42-48e8-b45f-41fb133eb104)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io **version 24.4.6**

**Desktop (please complete the following information):**
 - OS: **Windows**
 - Browser Version [e.g. 22]

**Smartphone (please complete the following information):** **Not Applicable**

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- Issue is noticed on desktop version however if I open the file i
[Inventory Splits Review 05-13-2024.zip](https://github.com/user-attachments/files/16239716/Inventory.Splits.Review.05-13-2024.zip)
n browser it show blank file for tab 1 where I had all the changes. 

**Additional context**

**Comment by davidjgraph** [comment]
How come you're using such a old draw.io version, is your browser not updating?

**Comment by LakshmanMuppuri** [comment]
I've had the version on my laptop for a while, but I've always been with using draw.io online. The problem persists even with the latest version.

**Comment by LakshmanMuppuri** [comment]
> How come you're using such a old draw.io version, is your browser not updating?


I've had the version on my laptop for a while, but I've always been with using draw.io online. The problem persists even with the latest version.
