### ISSUE TITLE
Keyboard navigation in diagram

### ISSUE THREAD

**Issue by olopost** [jgraph/drawio#4543]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

I create large diagram and when I need to navigate within it, I use the mouse sometime that's painfull when I manipulate some box.

**Describe the solution you'd like**
I think like in training simulator or video game a good feature can be to use WQSD key (or some mapping that I can configurate in config) W in US keyboard to navigate north, Q to navigate West, D to navigate East and S to navigater South

**Additional context**
I want to contribute in some coding if you help me to identify file and how to test my contribution.

Best regards.

**Comment by davidjgraph** [comment]
Thanks for the suggestion. However, that is outside of the scope of functionality that I want for the tool.
