### ISSUE TITLE
Issues encountered when using Mermaid in drawio

### ISSUE THREAD

**Issue by superman-wrdh** [jgraph/drawio#4544]
I am using drawio on the website https://app.diagrams.net/ to import flowcharts created with Mermaid. In this setup, each element is editable, such as dragging and deleting. However, when I use the latest code from https://github.com/jgraph/drawio to deploy it locally and import Mermaid flowcharts, the flowchart is treated as a whole, and its elements are not editable. Is this a change in the latest version, or has it been designed this way since a certain version?

on website https://app.diagrams.net/
![image](https://github.com/user-attachments/assets/155b2d27-799e-4219-bb95-25f87c7d9c25)

locally
![image](https://github.com/user-attachments/assets/cbd14f70-cde2-4817-b675-f70f40223c08)

**Comment by m-mohamedin** [comment]
Hi,
This feature is not part of the open-source code

**Comment by pcasalinho** [comment]
And how do we change that behavior on the "closed-source" code?Can't we edit the mermaid code in https://app.diagrams.net?

**Comment by surfmuggle** [comment]
@superman-wrdh i failed to [import a mermaid diagram](https://github.com/jgraph/drawio/discussions/5121). Could you help to describe the steps you took?
Thanks
