### ISSUE TITLE
How do to change the gridSteps of the grid?

### ISSUE THREAD

**Issue by cima-to-sa** [jgraph/drawio#4549]
I would like to change the structure (not the spacing of the main grid or sub-grid) of the grid from a default 4x4 sub-grid to e.g. 5x5 sub-grid.

There's a configuration parameter described (gridSteps: https://www.drawio.com/doc/faq/configure-diagram-editor) of which I think it's the right one. However, it does not change the the gridSteps as expected. It seems that this issue has already been discussed (https://github.com/jgraph/drawio/issues/1249) but not really sure if successful.

draw.io desktop, v24.6.4

Thanks for any help or tips. this is how the configuration looks like:
![drawio_configuration](https://github.com/user-attachments/assets/bd7c62be-317f-40e1-85f3-bf1f631982ac)

**Comment by alderg** [comment]
This works for me:
<img width="199" alt="Screenshot 2024-07-18 at 16 54 51" src="https://github.com/user-attachments/assets/af9f4d52-3232-418d-8502-7b1bbbec46e3">

<img width="194" alt="Screenshot 2024-07-18 at 16 54 56" src="https://github.com/user-attachments/assets/2d548d58-a80f-4430-a6ea-62b030c4378e">

[Try it.](https://app.diagrams.net/?grid=1&splash=0#_CONFIG_UzV3UjUySi/KTAkuSS0oBrJVjR2BpCmIZe4CAA==)

**Comment by kmsuzuki** [comment]
As @alderg indicated, this works. What's a bit confusing is if you specify this param in Configuration>Preferences, it does _not_ work. It works if you specify it at the Configuration level.
