### ISSUE TITLE
Issues Importing VSDX (Visio) with Dotted Lines

### ISSUE THREAD

**Issue by TheVakman** [jgraph/drawio#455]
When importing a Visio (.vsdx or .vdx) file that contains dotted lines, it imports very strangely and shades in areas that shouldn't be shaded. 

I've attached a sample document that causes the issue (added a .txt extension due to GitHub restrictions). I've also added sample screenshots of what it should look like versus the import.

@davidjgraph suggested I post the issue here. as per discussion here: https://groups.google.com/forum/#!topic/drawio/E2YgPnuw7u0

Here is the sample file to replicate the issue:
[SampleIssue.vsdx.txt](https://github.com/jgraph/drawio/files/3291886/SampleIssue.vsdx.txt)

![DottedLines](https://user-images.githubusercontent.com/18545156/59532163-f14b9d00-8eb5-11e9-83df-9797df4acf1d.JPG)
![DottedLines-drawio](https://user-images.githubusercontent.com/18545156/59532164-f14b9d00-8eb5-11e9-9a78-6cc32974f96e.JPG)

**Comment by ashrafteleb** [comment]
Fixed
