### ISSUE TITLE
Diagram text is being duplicated while editing

### ISSUE THREAD

**Issue by Genhis** [jgraph/drawio#456]
Diagram text is being duplicated while editing making it difficult to see what I am typing.

**Steps to reproduce:**
1. Create a new diagram
2. Add a shape, UML diagram or something else
3. Type something in the shape and click outside to let it save
4. While saving, immediately double-click the shape to edit it (and feel free to edit the text)
5. Wait a few seconds, you will see the original text behind the one you are editing
6. If you click outside the shape again, the new text is saved and the old duplicate disappears.

**Notes:**
- It can only be reproduced on the **first page** (not the first one created but the first page in current page order)
- Only **Dark theme** seems to be affected (the other three work fine)
- I use Google Chrome and save my diagrams in Google Drive

**GIF animation** (although it shows UML diagram, it can be reproduced with any shape)
![drawio_bug](https://user-images.githubusercontent.com/11155942/59554233-23392e00-8fa0-11e9-86d3-0f1ba6326ee9.gif)

**Comment by davidjgraph** [comment]
Could you create a blank diagram in Google Drive please then add ?sync=none to the URL and load that. If you then follow from step 2 after it loads, do you still experience the problem?

**Comment by Genhis** [comment]
Yeah, it's still there.
I created a blank diagram, added `?sync=none` and pressed Enter. After it loaded, I followed steps 2 - 6 and got the same issue.

Here is my URL:
![image](https://user-images.githubusercontent.com/11155942/59620106-53add300-912c-11e9-92d6-65dfd8d6eb2a.png)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by alderg** [comment]
Fixed in 10.8.0.
