### ISSUE TITLE
Bug introduced in 24.6.1: Font lists with fonts requiring quotes such as "Helvetica Neue" are not supported any more

### ISSUE THREAD

**Issue by rene-leanix** [jgraph/drawio#4560]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
The HTML escaping introduced [here](https://github.com/jgraph/drawio/commit/7449d2d7399feb0a9d3997814e3dffeadf1f5abf#diff-3acb7834a06a1685e9c25a9a816da40035d849026f8979f937a8bf9f0e0f6013R1953) for `fontName` leads to invalid font-family styles for font lists with some quoted elements.

**To Reproduce**
1. For a shape with a label, set the custom font to: `"Helvetica Neue", Helvetica`
2. The shape is rendered with the browser's fall-back, e.g. `serif`.

![image](https://github.com/user-attachments/assets/738c69c1-b998-4b5a-aa25-728b2e68668a)
![image](https://github.com/user-attachments/assets/c57956a0-3e9d-45a8-8299-d70527937cb2)

**Expected behavior**
font-family style is correct and specified font is rendered.

![image](https://github.com/user-attachments/assets/89ce78bc-261d-43ab-9bba-b465da938657)
![image](https://github.com/user-attachments/assets/6b7448d9-c286-439a-944f-0d9f77618be3)

**Screenshots**
See above.

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 24.7.1

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- Yes

**Comment by davidjgraph** [comment]
24.7.4
