### ISSUE TITLE
Prompt before transmitting diagram during PDF export

### ISSUE THREAD

**Issue by nathanielhourt** [jgraph/drawio#4562]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When exporting a PDF using the Export As->PDF menu, the diagram is transferred to a server outside of my network for processing. This is unexpected and in many environments this may be regarded as an unacceptable data leak.

**Describe the solution you'd like**
Before any transfer of potentially sensitive information outside of the user's or sysadmin's control, it would be ideal to prompt the user ensuring that they are aware of the potential transfer of information outside of their purview.

It would also be excellent if the admin could configure the DrawIO instance to disable all features that transfer content data outside of his/her network.

**Describe alternatives you've considered**
Alternatives don't readily spring to mind just now, but in general any warning about, and/or ability to opt out of, content data being transferred away would be suitable.

**Additional context**
I have none.

**Comment by davidjgraph** [comment]
See https://www.drawio.com/blog/data-governance-lockdown.
