### ISSUE TITLE
"This app is blocked" error

### ISSUE THREAD

**Issue by captcarl13** [jgraph/drawio#4589]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
When trying to install the [Draw.io Diagrams for Docs add-on](https://workspace.google.com/u/0/marketplace/app/drawio/224440279306), Google reports the app is blocked. This occurs in two different web browsers with two different accounts.

**To Reproduce**

1. From Google Docs, click **Extensions > Add Ons > Get Add Ons**
2. Search for draw.io
3. Click **Install**, then **Continue**
4. Select Google account to use with Draw.io Diagrams for Docs
5. Receive error **This app is blocked This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access**.

**Expected behavior**
Add-on should authorize successfully and appear in the **Add-ons** menu in Google Docs.

**Screenshots**
![image](https://github.com/user-attachments/assets/f799faf3-ff8d-4639-8d8e-6605fdb7e307)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.7.6

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 23H2
 - Browser: Microsoft Edge / Mozilla Firefox
 - Browser Version 127.0.2651.86 / 129.0

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**
As stated above, this error also occurs in Firefox using a completely different Google account. Other add-ons have been installed in Docs with no problem. Originally thought this was a permission setting at my org but when I tried with my personal Google account in a different web browser I have received the same error. All ad blockers were disabled when testing.

**Comment by davidjgraph** [comment]
Probably a repeat of https://github.com/jgraph/drawio/issues/4212. But, it's August, I'm on holiday, sorry :).

**Comment by kurti256** [comment]
I've been able to replicate this,

os windows 10 Version 22H2 2024-KB5042352
Browser Mozilla FireFox 
browser version 129.0.1

I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:

    yes


 please keep me posted

**Comment by akhilplw** [comment]
Hi, 
I am also facing the same issue for google slides.

**Comment by davidjgraph** [comment]
It doesn't look like there's anything we can do about this. Google have rejected the scopes and aren't allowing them back in.

**Comment by talkazaz** [comment]
Hi @davidjgraph ,
When trying to add a [draw.io]diagram into a slide within Google Slides via the designated [draw.io] addon for Google Slides, I'm being asked to "grant permissions" to the add-on. When clicking on "Ok", I'm requested to choose a Google account, I then click my email account (. After which the window says "This app is blocked").
I tried everything I could from Google support and they had no solution
Is this option not possible?
<img width="601" alt="image" src="https://github.com/user-attachments/assets/8ed8721c-5b1f-4d99-98c4-2acc5618c75c" />
I hope you answer me.

**Comment by talkazaz** [comment]
@davidjgraph

**Comment by ptorrsmith** [comment]
Just happened for me. Thought it may have something to do with free/personal Gmail users vs paid workspaces, but tried on both and got the same :-(

![Image](https://github.com/user-attachments/assets/683aeeb4-7c01-475a-81f6-f7cf67b05914)

![Image](https://github.com/user-attachments/assets/337a204c-93a5-43c9-a6af-ca4cd590caa8)

**Comment by davehouser1** [comment]
Still happening. Is there no solution for this?

**Comment by gchoules** [comment]
I got the same and on doing a bit of digging I found this, which hopefully offfers some insight into what Google have done and how apps need to change to abide by [their new rules](https://workspaceupdates.googleblog.com/)](https://workspaceupdates.googleblog.com/2023/09/winding-down-google-sync-and-less-secure-apps-support.html)

Their advice is to use Sign in with Google, described [here](https://support.google.com/accounts/answer/12849458?hl=en)

I hope this helps. I would really like to be able to use draw.io inside Google Docs.

Thanks.

**Comment by davidjgraph** [comment]
This is a scopes issue, not a signing in problem. Google allowed read-only drive for many years, then changed their decision. They just don't want to allow it any longer. There is no solution to fix the addon as it's currently architected.

We built a new addon last year, but when we enabled it, it took out one of their DB clusters, because we have so many users, so they disabled it and told us not to use it.

That's it, out of options.

**Comment by arobertn** [comment]
I'm sorry about the outcome but if it's insoluable I would request, as others have done, that the non-working (blocked) addon be removed from the marketplace and the [documentation page](https://www.drawio.com/blog/diagrams-google-docs) be removed, so people don't go down rabbit holes. @davidjgraph would you like me to open a new ticket for this?

**Comment by davidjgraph** [comment]
No, because that uninstalls it for everyone.

**Comment by onio-git** [comment]
At least, a warning should be put in the documentation that this is no longer working for new user. I made the error to remove the extension (that was working fine) and tried to reinstalling it and got it by the new security policy.
For example here:
https://www.drawio.com/integrations

**Comment by dstephan1** [comment]
I'll be poking around at Google to see if we can get this fixed.

**Comment by HEYRIX** [comment]
Any new progress?
