### ISSUE TITLE
Incorrect title for Fieldglass it is set as Fieldgrass

### ISSUE THREAD

**Issue by katansapdevelop** [jgraph/drawio#4596]
### Preflight Checklist

* [X ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Incorrect title for the SAP Fieldglass product, it is set as Fieldgrass for the "SAP" Shapes
![image](https://github.com/user-attachments/assets/1fbfa6ab-6f71-41a2-96a8-f8469c5fed4e)

For full details of the product name, see here https://www.sap.com/australia/products/acquired-brands/what-is-fieldglass.html

**To Reproduce**
1. Go to "SAP/Products" the label shows as Fieldgrass
![image](https://github.com/user-attachments/assets/8f2b6820-16bf-4685-a619-3b83b75f50ee)
2. When the component is added to a diagram you can see it is incorrectly labelled
![image](https://github.com/user-attachments/assets/7aeff68e-94b0-44d7-a416-10fa9cb70d88)

**Expected behavior**
The label should be "SAP Fieldglass"

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.7.5

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Browser Version : 128.0.2739.9 

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- No.  I can see the references to Fieldgrass in the source code of this repo

**Additional context**
I also created the same bug here on the official SAP repo. https://github.com/SAP/btp-solution-diagrams/issues/131 . They acknowledged it was an issue also and asked me to raise it here

**Comment by egrimate** [comment]
Will be in next release
