### ISSUE TITLE
Text entry not possible with touch/pen

### ISSUE THREAD

**Issue by DrZooDinghy** [jgraph/drawio#460]
I am unable to edit text on my surface tablet because drawio neither detects when i try to double tap the box nor does it recognize the double click interaction when I use the pen. Instead, the context menu opens as if a right-click was performed. 

Drawio was the first thing I tried with my new surface and new pen.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by DrZooDinghy** [comment]
Thank you!

**Comment by DigatalLion** [comment]
This issue is not fixed for a while. I need double touch a shape to change a text. But the first touch opens popup and second one clicks on <Delete>. And I delete a shape instead of changing a text. May be you can add new option in that popup as <Edit text>?

**Comment by davidjgraph** [comment]
We need full environment and reproduction steps in order to look.

**Comment by DigatalLion** [comment]
I use drawio app on my Windows tablet and online version of drawio via MS Edge (chromium) browser. I use my finger not a mouse.

**Comment by alderg** [comment]
If you are using the minimal UI (Theme, Minimal): We'll add an Edit option in the context menu under Edit Geometry in the next release.

**Comment by DigatalLion** [comment]
Yes, I use minimal UI.
Thank you!
