### ISSUE TITLE
Polar/radial grid

### ISSUE THREAD

**Issue by slyakh** [jgraph/drawio#4615]
* [✓] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [✓] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Although unusual, I wanted to make a circular ERD. Issues: 
• Some table shapes don't rotate, others rotate improperly (nested boxes stay aligned vertically). 
• Connectors either follow harsh angles, or have to be meticulously tweaked with goofy curves.

**Describe the solution you'd like**
Instead of messing with individual objects, what if entire grid could be polar. This would allow standard orthogonal shapes and connectors to be "warped" according to the new type of coordinates: shapes would simply be rotated based on their position around the center point, and for connectors, the horizontal lines would follow a circular path around the main center point, and vertical lines would become radial.

**Describe alternatives you've considered**
This is probably a tall order. So some alternatives would be: 
• allow shapes (like the Entity Relation ones) to be rotated, 
• allow shapes (like the General List one) to be properly rotated (where the list items stay within the main box),
• add an option for connector (regardless of the type) to be joined perpendicularly to a shape.

**Additional context**
![image](https://github.com/user-attachments/assets/f07b2d46-271b-422d-b5a6-fb7af5d03984)

Thank you.

**Comment by davidjgraph** [comment]
Thanks for the suggestion, but as you probably realised, there's no way we can implement this.
