### ISSUE TITLE
Diagaram-level sketch mode doesn't work

### ISSUE THREAD

**Issue by FarSeeing** [jgraph/drawio#4626]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
Checking/unchecking "Sketch" checkbox when no element selected doesn't change anything

**To Reproduce**
1. create a diagram
2. add some elements
3. check the "Sketch" checbox on the "Format" panel
4. Verify spinner gets shown & hidden
5. Nothing changes

**Expected behavior**
Sketch mode should be toggled on/off

**Screenshots**
![sketch](https://github.com/user-attachments/assets/47fe4580-baa1-4107-b85a-c59412533e42)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.7.7

**Desktop (please complete the following information):**
 - Browser Version [e.g. 22]

**Smartphone (please complete the following information):**

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-

**Additional context**

**Comment by davidjgraph** [comment]
It changes the default for new shapes, not old shapes. If you want to change old ones, select them and then sketch.

**Comment by davidjgraph** [comment]
Maybe so, but we can't change it now.
