### ISSUE TITLE
Add check for large element dementions

### ISSUE THREAD

**Issue by kirillgalushko** [jgraph/drawio#463]
I worked on the diagram about an hour and accidentally remove a dot in a width section of my box: from `709.9290780141844 pt` to `7109290780141844 pt`. Of course, the whole app just crashed, and all my work has been gone. Thank you for that. I really enjoyed it. Why there are no checks for this case? Just add a confirmation window.

**Comment by davidjgraph** [comment]
Happy to review a PR
