### ISSUE TITLE
Comments Mode: Toggle Show/Hide Comments, Add and Manage Comments on Page/Shape/Connection

### ISSUE THREAD

**Issue by datgausaigon** [jgraph/drawio#4633]
* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Hi,
You now have Comment feature (requires connection and sharing via Google Drive (Google Account))
But all Comments are currently only displayed in 1 Panel Comments (Popup):
- Add/Remove
- Reply
- Resolve
- Manage

![Screenshot 2024-09-02 at 16 44 03](https://github.com/user-attachments/assets/c817ce72-fd4d-4756-a39d-70c0b2b3a6af)

Can I suggest and request an additional feature for Comments? That is to refer to the Comments feature from Figma.
They have Comments Mode mechanism.
- Toggle Show/Hide Comments
- Add/Remove/Reply/Resolve/Manage Comments on everywhere

You can refer to this link and see the video below:

https://help.figma.com/hc/en-us/articles/360039825314-Guide-to-comments-in-Figma

![GIF_1](https://github.com/user-attachments/assets/a7c04ed5-d85a-4486-b5b2-85a699ba0a1e)

We can add Comments Mode feature
- Toggle Show/Hide Comments
- Add/Remove/Reply/Resolve/Manage Comments on Page/Shape/Connection/Object

This helps us increase the collaboration of drawio

Thanks 
🐻

**Comment by davidjgraph** [comment]
This is too vague. I don't follow exactly what's being requested.

**Comment by datgausaigon** [comment]
Hi @davidjgraph ,
Sorry for my unclear explanation of this request.
Here is what I mean:
Currently your comments feature comments are added and replied to in a Comments Panel Popup.
I am currently hoping to be able to Pin comments to any location on the page or on a Shape. And people can continue to exchange that Pin comment as a Thread.

![Screenshot 2024-09-02 at 16 58 09](https://github.com/user-attachments/assets/925400f8-6622-4582-b1b7-254ac5c1225d)

![Screenshot 2024-09-02 at 16 56 41](https://github.com/user-attachments/assets/e5a60d12-8250-43f3-aff0-c7966e668849)

![Screenshot 2024-09-02 at 16 56 51](https://github.com/user-attachments/assets/67885a27-1bc5-4cd9-990e-37a85b37d0e5)

![Screenshot 2024-09-02 at 16 57 10](https://github.com/user-attachments/assets/c7a968cb-c723-4f07-9f4b-86edce3102b9)

![Screenshot 2024-09-02 at 16 57 38](https://github.com/user-attachments/assets/bad2544b-090c-4317-91f5-ae4376baa09f)

**Comment by davidjgraph** [comment]
Yeah, we considered pinning comments in location, but it's just too much work to implement.

**Comment by datgausaigon** [comment]
Thank you for your consideration.
I hope this future feature will be developed when you have time.
Thanks
🐻
