### ISSUE TITLE
Could you make a shortcut for export as with a dialogue box to further show the file types

### ISSUE THREAD

**Issue by mcbhabhi** [jgraph/drawio#4640]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by davidjgraph** [comment]
Thanks for the request, but it's too much of an edge case and there are too few shortcuts left available.

**Comment by mcbhabhi** [comment]
i think its an important shortcut cos eventually people will export their drawings
