### ISSUE TITLE
Italian Translation Error

### ISSUE THREAD

**Issue by giovannigiannotta** [jgraph/drawio#4647]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
"Tutte le etichette" is not a correct Italian translation of "Autosave" word. The correct one is "Salvataggio automatico", or "Autosave" itself.

**To Reproduce**
1. Go to 'Extra/Language'
2. Click on 'Italiano'
3. Restart the application
4. See error: in the same menu when you select Italian language, at line "Autosave" you will find "Tutte le Etichette"

**Expected behavior**
In the Italian translation, it will be found the word "Salvataggio " or "Autosave", it where is "Autosave" word in English version.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version v24.7.8

**Desktop (please complete the following information):**
 - OS: Opensuse Linux
 - Browser --
 - Browser Version --

**Smartphone (please complete the following information):**
 - Device: --
 - OS: --
 - Browser --
 - Version --

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- not applicable

**Additional context**

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
