### ISSUE TITLE
"Edit Data" does not apply update to multiple selected shapes - only first selected

### ISSUE THREAD

**Issue by neeto33** [jgraph/drawio#4648]
### Preflight Checklist

* [X ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md) that this project adheres to.
* [ X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**

**To Reproduce**
1. Select multiple shapes
2. Go to "Edit"->"Edit Data..."
3. Enter Property Name e.g. "Impact", <CR>
4. Enter value e.g. "Modify" 
5. Click "Apply"
6. Select second shape, Property e.g.  "Impact" does not apply and is not present if you choose "Edit Data" on the shape

**Expected behavior**
1. That data property is added to and/or modified if existing to the entered value of each selected shape 

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.7.12

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft Edge
 - Browser Version: 

**Smartphone (please complete the following information):**

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**

**Comment by neeto33** [comment]
Seems like this a bit similar to #2184

**Comment by davidjgraph** [comment]
Duplicate #1184
