### ISSUE TITLE
Support for flipping rack unit number side

### ISSUE THREAD

**Issue by solidDoWant** [jgraph/drawio#4661]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When drawing rack diagrams for the front and back of racks, with connections between them, having unit numbers on the inside can sometimes make the diagram more difficult to read. However, it would still be nice to have this numbering.

**Describe the solution you'd like**
I would like an option to move server rack unit numbers (currently on the left side) to the right side.

**Describe alternatives you've considered**
Unfortunately vertically flipping the object doesn't fix this, because the numbers themselves also get flipped/mirrored.

**Additional context**
Example of the issue where a diagram is somewhat more difficult to read:
![image](https://github.com/user-attachments/assets/e1f3a46c-8d66-4281-8362-7d187b297325)

If the numbers on the rightmost rack object were on the right of the diagram, the arrow/connector would not overlap with them.

**Comment by egrimate** [comment]
Will be in next release
