### ISSUE TITLE
Sponsorship removed?

### ISSUE THREAD

**Issue by owhs** [jgraph/drawio#4679]
No template, because this isn't really a bug or a feature request. [Sorry!]

I have sponsored JGraph on gh for a while, while it's only a small contribution, over time it adds up, and it's one of the only projects I've wanted to support.

Is there is a specific reason for the departure in allowing sponsorships? I'd like to continue supporting financially.

I appreciate there's a commercial arm to this project, however as a free product available to the general public, I genuinely think that drawio  (diagrams... whatever lol) is **better** than paid alternatives.
I just hope for the continued success of the project and that it can remain viable as a free to use tool!

**Comment by davidjgraph** [comment]
Yeah, it's because the project is no longer technical open source, due to a line added into the license. We appreciate the wish to sponsor, but we needed to work on the assumption that a good number of the sponsorships were due to it being licensed under the Apache license.
