### ISSUE TITLE
Keep scope after deleting item inside a container

### ISSUE THREAD

**Issue by GaTechThomas** [jgraph/drawio#468]
I really appreciate draw.io. One difficulty that I regularly have with it is that I have items one or more containers deep. When I delete one of several items from inside a container and then use the mouse to try to grab an item that sat next to that deleted item, the mouse doesn't select the former sibling item, but instead the parent item. 

So at full speed in the app, it goes something like this:

1. Move several items around inside a container.
2. Realize that an item inside the container needs to be deleted, so delete it.
3. Use the mouse to grab and move another item inside the same container.
4. Realize that the entire container container just moved.
5. Undo the last action (and grumble a bit).
6. Click
7. Click
8. Click (and keep single-clicking until the nested item is selected).
9. Move the selected item.

Expected:

1. Same
2. Same
3. Same
(No more steps in this scenario.)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by Devaniti** [comment]
This is first google result for "draw io delete container and retain contents"
Please consider adding explanation on how to do that

**Comment by alderg** [comment]
Select the container, click ungroup, select the container again and click delete.
