### ISSUE TITLE
Zoom Issue: Header and Sidebar Menus Not Restoring in Chrome (macOS)

### ISSUE THREAD

**Issue by peco-tanaka** [jgraph/drawio#4686]
Preflight Checklist
 I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md) that this project adheres to.
 I have searched the issue tracker for a feature request that matches the one I want to file, without success.
Bug Report Title:
Zoom Issue: Header and Sidebar Menus Not Restoring in Chrome (macOS)

Describe the bug:
I am using macOS and accessing draw.io through the web version. Only the header and sidebar menu areas remain zoomed in, and I am unable to reset them to the original size. While zooming in and out using shortcut keys, mouse scroll, and zoom buttons works, I cannot reduce the zoom on these specific parts.

To Reproduce:

Open draw.io in Chrome on macOS.
Zoom in using shortcut keys, mouse scroll, or zoom buttons.
Attempt to zoom out.
Notice that only the header and sidebar menu areas remain zoomed in and cannot be reset.
Expected behavior:
The entire UI, including the header and sidebar, should zoom in and out consistently and allow a reset to the original size.

Screenshots:
(You could include a screenshot here showing the zoomed-in header and sidebar for better clarification.)

draw.io version:
Version X.Y.Z (you can find this in the Help -> About menu in the draw.io editor)

Desktop (please complete the following information):

OS: macOS
Browser: Chrome
Browser Version: Latest (or version number)
Smartphone (if applicable):

Device: N/A
OS: N/A
Browser: N/A
Version: N/A
I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:
Yes

Additional context:
I have tried clearing the cache, adjusting Chrome's zoom settings, and even reinstalling Chrome, but none of these steps resolved the issue. I also attempted using Edge, but the same problem occurred when zooming in, and I was unable to zoom out the header and sidebar areas.

Thank you in advance for your assistance.

This structure should allow for a detailed and clear bug report submission.
![スクリーンショット 2024-10-04 12 23 38](https://github.com/user-attachments/assets/d50c5acd-6d73-46dd-9498-ab6b27a10efd)
![スクリーンショット 2024-10-04 12 23 38](https://github.com/user-attachments/assets/77c618ca-9772-48ec-863c-e5cd3d96f7ce)

**Comment by davidjgraph** [comment]
And what's the browser zoom setting? Can you show a screenshot with the browser zoom setting visible?

**Comment by peco-tanaka** [comment]
Thank you for your response.
I checked the browser zoom settings, and it turns out they were incorrect (set to 250%).
I appreciate your help!
