### ISSUE TITLE
Please ensure JavaScript is enabled.

### ISSUE THREAD

**Issue by lpbaiser** [jgraph/drawio#469]
I'm trying to use draw.io on trello, but this message shows. What can I do?

![image](https://user-images.githubusercontent.com/14255595/60383256-f0ce0d00-9a44-11e9-9c18-87a50f6de391.png)

System: 
Mac OS 10.14
Trelo 2.10.14

**Comment by davidjgraph** [comment]
What steps did you follow exactly before you got to that screen?

**Comment by lpbaiser** [comment]
> What steps did you follow exactly before you got to that screen?

I installed the Power-Ups `draw.io`
Add new card on Trello > Power-Ups > draw.io > Create

![image](https://user-images.githubusercontent.com/14255595/60385238-837aa600-9a5d-11e9-83f9-951bc5cccc84.png)

**Comment by davidjgraph** [comment]
Works OK here, check a browser extension isn't breaking something.

**Comment by Neha-Ali-Khan** [comment]
![Capture](https://user-images.githubusercontent.com/119319654/204287671-11522eeb-2711-4562-b93a-77e589dc95c7.JPG)
Got this error plz help me how to resolve this, I opened this through chrome

**Comment by Josho-SAI** [comment]
I also frequently see this issue. 
Environment; Ubuntu 22.04.1 LTS running Gnome Desktop, Google Chrome (default) browser.
Browser Extensions; Adblock for Chrome, Adblock for You, Adblock for YouTube, Chrome Remote Desktop, Chrome Download Manager, GNOME Shell integration, Google Docs Offline, GSConnect

I can overcome this by doing a Shift-F5 however every time I revisit a drawing the "Please enable Javascript" issue appears. 

I will attempt to diagnose by selectively disabling the Extensions and attempting to open an existing drawing

**Comment by Josho-SAI** [comment]
After disabling ALL Google Chrome Extensions, the error still remains. It would appear this has nothing to do with a Chrome Browser extension.

**Comment by blackherohd** [comment]
I always have the same problem when I open file from google drive or access the home url. I saw some errors in the console.
After I have pressed Ctrl + Shift + R, there errors didn't appear.

![image](https://github.com/user-attachments/assets/522e2e60-c400-45b9-8912-12209c25b755)
