### ISSUE TITLE
Please improve how we can select objects

### ISSUE THREAD

**Issue by Shizu-ka** [jgraph/drawio#4692]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i need to select a big area just to choose some little objects.

**Describe the solution you'd like**
Please make area that i need to cover to select objects is as small as possible

**Additional context**
Look at this image. If i do this now, those objects won't be selected. Can you improve that and make even if my selected area is as small as this, those 2 objects will be selected (i can move around those 2 after that)
![image](https://github.com/user-attachments/assets/53e9861a-ead1-40ae-bd49-2bee0888cd75)

Because selecting all area of the objects like this is frustating when your diagram is complex and has many small objects.
![image](https://github.com/user-attachments/assets/a4032774-ad4a-4f7e-a27f-a79e493d2fc0)

Thank you so muchhhh!!

**Comment by alderg** [comment]
Try Alt+Select (Windows) or Option+Select (Mac)

**Comment by Shizu-ka** [comment]
> Try Alt+Select (Windows) or Option+Select (Mac)

thanks!
