### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by Maniues** [jgraph/drawio#4695]
I don't know how effective this draw.io license is when it comes to plugins. Is it really worth sacrificing the Free Software and Open Source title to prevent people from making plugins?

Personally, I'll have to stick with the old version, move to a community fork, or abandon draw.io.

A better effect can be achieved by using a trademark. Ban the Draw.io name, and there will be no such plugins, or no one will find them.

**Comment by davidjgraph** [comment]
You can't "ban the draw.io name". That's not how trademarks work.
