### ISSUE TITLE
"Words overlap in container while using PlantUML" (Draw.io uses a PlantUML server/docker with only one installed font?)

### ISSUE THREAD

**Issue by kirchsth** [jgraph/drawio#4699]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

If I add following PlantUML diagram in Draw.io then the characters overlaps (output is SVG).
If the diagram is displayed on the online PlantUML server then it is correct displayed (output is SVG too).

```plantuml
@startuml
header plantuml %version()

[=SPA\n=Admin SPA\nSPA\nAdmin SPA]
@enduml
```

draw.io output:

![image](https://github.com/user-attachments/assets/d2d3abef-d54c-4eb6-a385-07f42e40289a)

PlantUML online server output:

[![image](https://github.com/user-attachments/assets/c821ef66-4582-49e5-8064-5fba74f433a3)](https://www.[plantuml.com/plantuml/svg/SoWkIImgAStDuSf8JKn9BL8eo4dC0_4LLCjIYuepy_CqDBcuecs30nnZycmTKt8pynJ0R301vyToEQJcfG2r0G00](https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuSf8JKn9BL8eo4dC0_4LLCjIYuepy_CqDBcuecs30nnZycmTKt8pynJ0R301vyToEQJcfG2r0G00))

My assumption is that only one font is installed on the used PlantUML server/docker and therefore wrong distances,... are calculated.
Therefore I listed all available (PlantUML) fonts and create a png file (that it is independent of the e.g. fonts which are installed in the  browsers,...) and this looks for me that only one font is installed on the used PlantUML server/docker.

```plantuml
@startuml
listfonts <size:20>Admin SPA
@enduml
```

draw.io output:

![image](https://github.com/user-attachments/assets/8efcab63-c92d-4ca2-92b9-43da9d2503dd)

(details see below)

My original issues is documented in [C4-PlantUML](https://github.com/plantuml-stdlib/C4-PlantUML/issues/361) with a detailed analysis.
And I think it is also related to the  "off-topics" comments of https://github.com/jgraph/drawio/issues/4020.

**To Reproduce**

1. Go to 'https://app.diagrams.net'
2. Add a new PlantUML diagram via "Arrange->Insert->Advanced->PlantUML"
3. Enter following text
```plantuml
@startuml
header plantuml %version()

[=SPA\n=Admin SPA\nSPA\nAdmin SPA]
@enduml
```
4. Check that "PlantUML (SVG)" is selected and press "Insert"
5. And you see the image with the overlapping characters
![image](https://github.com/user-attachments/assets/04020c88-24d4-4f97-b2ce-9c36d54b1cf7)

**Expected behavior**
The PlantUML server/dockercalculates the correct distances (based on the installed fonts) that the SVG diagram can be drawn without any overlaps, 

**Screenshots**

see above and below

**draw.io version (In the Help->About menu of the draw.io editor):**

- https://app.diagrams.net/?src=about;  version 24.7.17

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge (but also Chrome has the same problem)
 - Browser Version: 129.0.2792.79

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**

The original issues is documented in [C4-PlantUML](https://github.com/plantuml-stdlib/C4-PlantUML/issues/361) with a detailed analysis. 

But I think the most important difference is that the PlantUML online server has more installed fonts and you see that ex. "SansSerif" and "Serif" use different fonts in the png output of the PlantUML online server (and in draw.io even the "Serif" font has no serifs):

```plantuml
@startuml
listfonts <size:20>Admin SPA
@enduml
```

PlantUML online server output:

(the image has a link to the PlantUML online server, that you can compare it online too)

[![image](https://github.com/user-attachments/assets/36ca2abf-8253-4fd4-b978-644c5ebf8cdc)](https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuSh9B2v9oyyhALQmASwiIhKoCh1pJCdDp5C83d3aSaZDIm4g0W00)

If you are using a docker image it could be the simplest to add more fonts based on following PlantUML instruction: [Additional fonts inside the PlantUML docker container](https://github.com/plantuml/plantuml-server/blob/master/examples/additional-fonts/README.md)

**Comment by davidjgraph** [comment]
We use PlantUML on AWS lambda, it provides for a massive reduction in attack-surface. A side effect of this is that only one font is available, yes.

But, this is meant as an as-is PlantUML implementation. If you want a fully featured, fully up to date implementation draw.io is the wrong tool.
