### ISSUE TITLE
C4 Model Diagram Shapes 

### ISSUE THREAD

**Issue by akahky** [jgraph/drawio#4704]
Hello All,

The current set of C4 shapes are missing some of the shapes in C4 model such as mobile container shape

C4 Mobile container should be added to the shapes of C4 shapes, and it will be great if you can add all the shapes of C4 model to draw.io 

I am using the container shape currently to replace the mobile shape yet it is not representative as the mobile shap

**Comment by davidjgraph** [comment]
Missing which? Please to them. This is very vague, please be precise is detailing what is wrong and how to fix it.

**Comment by akahky** [comment]
<img width="513" alt="Screenshot 2024-10-16 at 1 31 07 PM" src="https://github.com/user-attachments/assets/8f365da2-8e3b-41da-962f-257fc1c20c2d">
Please check the attached file, the browser container is there in the current C4 model shapes but the mobile container is not available

**Comment by davidjgraph** [comment]
So one shape is missing, not multiple as you wrote in your initial message?

**Comment by akahky** [comment]
Yes, that is what I faced so far.
