### ISSUE TITLE
Blurry emojis in PNG

### ISSUE THREAD

**Issue by fkohrt** [jgraph/drawio#4705]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**

Diagrams with emojis exported to PNG look blurred at high resolution.

**To Reproduce**

1. Create a new diagram with a text field containing `⚠️`.
2. Export it as PNG at a high resolution (e.g., 300%)
3. Obtain a blurred warning sign

**Expected behavior**

A crispy warning sign.

**Screenshots**

![Untitled Diagram drawio](https://github.com/user-attachments/assets/05575ee6-d435-4839-b2e4-806c9f5c6f0c)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.7.17

**Desktop (please complete the following information):**

 - OS: Fedora 40
 - Browser: Firefox
 - Browser Version: 130

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**

- yes

**Additional context**

Well, this is the issue that led me to the issue tracker and made me discover the [license change](https://github.com/jgraph/drawio/discussions/4623).

**Comment by davidjgraph** [comment]
That would be the expected behaviour for me, it's a raster image. If you search for "alert" in the shapes, there are vector alerts.

**Comment by fkohrt** [comment]
I see – I managed to work around it by exporting as SVG and screenshoting a zoomed version in the browser. So I thought this should be solvable in principle.

**Comment by davidjgraph** [comment]
Maybe so, but asking for icons to be vector to assure correctly scaled output is reasonable, so I'll close this one up.
