### ISSUE TITLE
Connection point on Edges

### ISSUE THREAD

**Issue by officemikedev** [jgraph/drawio#4709]
* [ X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md) that this project adheres to.
* [X ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I frequently have a need to connect a Text object to an edge in order to describe the edge.  For example, when depicting a Browser connected to an HTTP Server via an Edge that represents an HTTP Request, and I want to detail the HTTP Request attributes such as scheme, headers, body, protocol, by creating a Text object, the ask is to connect that Text description to the Edge itself, where the reader can intuitively understand it is describing the connection.  As it is, I have to connect the Text to the Browser object or the Server object, which loses the meaning that tyhe Text is describing the connection.

**Describe the solution you'd like**
When I have started a edge (a line) from one object and drag near to an existing Edge that is connecting two other box objects, that edge would adorn with connection endpoints the same way that other box objects do today, and I could connect the new edge to a connect point on the existing edge.  Then, when moving objects, these two edges would stay connected.

**Describe alternatives you've considered**
I put the Text near the Edge it is describing, and manually keep it near the edge when rearranging object.  Or I connect the Text to one of the the edge's connected box objects, and in the Text I further describe that the Text is deescribing the Edge and not the Box object.

**Additional context**

**Comment by davidjgraph** [comment]
We decided long again that connection points are only at the ends of edges, unfortunately, that's not going to change.

In the case of text shapes that are children of the edge, that is possible if you double click anyway along the edge. That creates a child text vertex that can be repositioned and will move with the edge.
