### ISSUE TITLE
Upgrade to Mermaid v11.1.0+ to Support Mermaid Architecture Diagrams in draw.io

### ISSUE THREAD

**Issue by no-identd** [jgraph/drawio#4712]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I wanna use https://mermaid.js.org/syntax/architecture.html in draw.io to describe & render complex IT architecture diagrams so I can shove them into consumers of draw.io diagrams (e. g. Confluence) 

**Describe alternatives you've considered**
Mermaid Block Diagrams don't cut it. At all.

**Additional context**
* https://www.mermaidchart.com/blog/posts/mermaid-supports-architecture-diagrams/
* https://github.com/mermaid-js/mermaid/issues/5367
  * https://github.com/mermaid-js/mermaid/pull/5452

**Comment by davidjgraph** [comment]
Mermaid support is fully as-is. We don't promise any particular version or that we'll ever update. For full mermaid support please use a tool specifically targetting mermaid.

**Comment by no-identd** [comment]
> Mermaid support is fully as-is.
…I already figured that beforehand.


>We don't promise any particular version or that we'll ever update.

Would seem oddly out of character if you did.

>For full mermaid support please use a tool specifically targetting mermaid.

Sure. ;) :)

👋🏼
