### ISSUE TITLE
Github Enterprise Support

### ISSUE THREAD

**Issue by sbueringer** [jgraph/drawio#473]
Hi,

what do you think about Github Enterprise support? Is it possible. What has to be changed compared to the github.com feature?

**Comment by davidjgraph** [comment]
Precisely what would that comprise? Wiki support? If it's diagrams stored in the repo, what would the UI look like? Does an API exist to support the concept?

**Comment by sbueringer** [comment]
I though mainly about storing diagrams in Github Enterprise the same way I can currently store it at github.com. The API itself is the same for Enterprise and .com.

**Comment by davidjgraph** [comment]
Implemented in 14.6.9
