### ISSUE TITLE
Is it possible for drawio to launch a team editing function?

### ISSUE THREAD

**Issue by TuuSiwei** [jgraph/drawio#4734]
Is it possible for drawio to launch a team editing function?

**Comment by davidjgraph** [comment]
what?

**Comment by TuuSiwei** [comment]
> what?

For example, if I create an image on my computer, is there any way for someone else to edit it directly, like a team?

**Comment by davidjgraph** [comment]
Yes, if you save it to a cloud service like google drive or onedrive. If you don't save it anywhere, that's not possible.

**Comment by TuuSiwei** [comment]
I know what to do. Thank you very much for your answer！
