### ISSUE TITLE
Unable to install Google Docs add-on.

### ISSUE THREAD

**Issue by k821msyk** [jgraph/drawio#4736]
*Please note that I am not an engineer and I am not a native English speaker.

**Problem :**
When I try to install the Google Docs add-on, I get the following white screen and cannot install it.
![image](https://github.com/user-attachments/assets/a6221210-5304-4de9-8150-06e2d51c0571)
*Display contents
“This application is blocked.”
This app tried to access private information in your Google Account. To keep your account safe, Google has blocked this access.

**Reproduction steps :**
1) Go to Google Workspace Marketplace (draw.io for Google Docs). 
2) Click "Install" in the upper right corner. 3.
3) Confirm the permissions required for installation, and click “Continue”. 
4) Sign in to your Google account (personal account).
5) An error message will be displayed.

**Expected Results :**
The installation should start without displaying an error message.

**draw.io version :**
- List update date [March 8, 2024].

**Desktop :**
- OS [Windows 10]
- Browser [Brave / Chrome]
- Browser Version [
Brave 1.72.93 Chromium: 131.0.6778.14 (Official Build) beta (64-bit)/
Chrome 130.0.6723.92 (Official Build) (64-bit)
]

**Comment by davidjgraph** [comment]
Duplicate #4589
