### ISSUE TITLE
Option to disable dark-mode filters on single objects (images)

### ISSUE THREAD

**Issue by ppabis** [jgraph/drawio#4737]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
In dark mode, imported images are also affected by the filter. I want to have all the shapes in improved contrast style but not images. They look absolutely broken when the filters are applied on them. There's nothing in the documentation that could help me. I tried many CSS snippets but nothing worked.

**Describe the solution you'd like**
A checkbox in properties "disable dark-mode CSS filter" on a single object.

**Describe alternatives you've considered**
A CSS snippet that will affect the image.

**Additional context**
Nothing to add. Try adding images to the diagram in dark mode and see how bad they usually look.

**Comment by davidjgraph** [comment]
Broken on what version, what platform, fill in the template

**Comment by ppabis** [comment]
@davidjgraph ah, sorry, just tested it on Firefox and it works there more reliable (although the filter is still applied it's not as bad). The issue is related to Safari (possibly unsupported `forced-color-adjust` but can't reproduce it on Firefox). I will open a new bug issue instead.
