### ISSUE TITLE
Can no longer change individual table cell alignment

### ISSUE THREAD

**Issue by waltsatan** [jgraph/drawio#474]
I have a table with multiple rows and columns.  I was previously able to select the text in a cell and set its alignment individually.  When I do this now, the entire table's alignment changes.  Perhaps this is a result of "Fixes inconsistent text editing alignment" in the 10.9.0 update?  Is this behavior as intended?  It was nice to have per-cell alignment options.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release. (As a workaround, hold shift when clicking the text align button.)
