### ISSUE TITLE
"AWS Application Composer" has been renamed to "AWS Infrastructure Composer"

### ISSUE THREAD

**Issue by typex1** [jgraph/drawio#4743]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
According to AWS News update in https://aws.amazon.com/about-aws/whats-new/2024/10/aws-application-composer-infrastructure-composer/ - the respective service has been renamed.

**To Reproduce**
1. Go to https://draw.io or the related desktop app
2. Click on search bar top left
3. Search for "application composer"

**Expected behavior**

The icon shows up, but the search needs to be "infrastructure composer", because that is now the new service name.

**Comment by egrimate** [comment]
Will be in next release
