### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by esclicosta** [jgraph/drawio#4745]
Hello,
How can I delete a link sent through the desktop export from Draw.io so that it is no longer accessible?

**Comment by davidjgraph** [comment]
don't send it to anyone else, everyone you already sent it to has seen the diagram.

**Comment by esclicosta** [comment]
> Quote reply
but I saved the link, and it is still accessible. Is there a time limit? I would like to remove it

**Comment by davidjgraph** [comment]
the data is in link, there's nothing server side.

**Comment by esclicosta** [comment]
> the data is in link, there's nothing server side.

isn't there a way to delete this link, or will it expire over time?

**Comment by davidjgraph** [comment]
delete it from where? the data is in the link, not on a server.

**Comment by davidjgraph** [comment]
to be able to expire, that would have to mean the data is stored on a server. It's not, so there's nothing to expire.
