### ISSUE TITLE
Background color rendering incorrect in Dark mode

### ISSUE THREAD

**Issue by jeffdaze** [jgraph/drawio#4746]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
When adding shapes to a diagram, background colours are not properly rendered within Dark mode; the colour yellow is entirely impossible to produce, and #FF0000 for red is rendered as a pink colour

**To Reproduce**
1. Add any shape
2. Click on the 'fill color' tool in the top bar or the fill option in the right panel
3. Enter a hex colour OR simply observe the colour swatch in the colour picker
4. Observe that yellow band is entirely absent, and colours are not properly rendered (compare by toggling between dark and light modes)

**Expected behavior**
Colours in dark mode should render as their true hex value represents eg #FF0000 should be red instead of pink, and yellow should be possible to use within dark mode

**Screenshots**
Dark version colour picker:
![Screenshot 2024-11-08 at 4 21 17 PM](https://github.com/user-attachments/assets/b34177b1-ace4-4e25-9c3f-353f94e711af)

Note the lack of yellow and generally muted, incorrect colour rendering.

Contrast with Light version colour picker which does render the colours properly:
![Screenshot 2024-11-08 at 4 21 46 PM](https://github.com/user-attachments/assets/c4086bc8-26de-4d60-baef-1006a9a4dd38)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.8.3

**Desktop (please complete the following information):**
 - OS: OSX Sonoma 14.6.1
 - Browser: Chrome
 - Browser Version: 130.0.6723.70 (Official Build) (x86_64) 

**Smartphone (please complete the following information):**

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
-no

**Additional context**
It's super weird; the actual SVG path data appears to be correct but setting fill to #FFFF00 actually renders #2E2E00 which seems like some universal calculation is being done against the colours to rotate them a bit (probably to make it conform to the dark theme?) the unfortunate consequence is that it means some colours are not possible to render (like yellow).

**Comment by davidjgraph** [comment]
This is all changing, please follow https://github.com/jgraph/drawio/discussions/4713

**Comment by jeffdaze** [comment]
Thank you for the update!
