### ISSUE TITLE
Export with broken image

### ISSUE THREAD

**Issue by vinhphat89** [jgraph/drawio#475]
Steps to reprodure:
1. Install Draw.io from Chrome.
2. Create an new Diagram.
3. Add Clipart/Computer to diagram.
4. Click Files -> Export as -> PNG (or JPEG)

![test_drawio](https://user-images.githubusercontent.com/7920995/60948019-34195d00-a31c-11e9-8939-ad10a91a54bb.png)

Environments:
- Ubuntu 16.04
- Chrome 73.0.3683.75 (Official Build) (64-bit)
- Draw IO v 10.9.2

**Comment by davidjgraph** [comment]
Could you clarify step 1 please, how do you "install draw.io from chrome"?

**Comment by vinhphat89** [comment]
I installed from this url: https://chrome.google.com/webstore/detail/drawio-diagrams/onlkggianjhjenigcpigpjehhpplldkc

**Comment by davidjgraph** [comment]
What does the diagram look like in the editor?

**Comment by vinhphat89** [comment]
I open it from dash and application name is 'draw.io Desktop'.

![test_drawio](https://user-images.githubusercontent.com/7920995/60959372-443c3700-a332-11e9-9972-a38076c8b252.png)

**Comment by davidjgraph** [comment]
This the desktop version, not the online version in Chrome? Install the latest version from https://github.com/jgraph/drawio-desktop/releases

**Comment by vegansk** [comment]
@davidjgraph , was it fixed in 10.9.8? Provided link contains latest version 10.9.5. 
![image](https://user-images.githubusercontent.com/2908508/61521258-04fc9d00-aa3a-11e9-9bdb-7248c023d5ba.png)

Installed deb version says that it is 10.9.7, not 10.9.5, but still fails.
![image](https://user-images.githubusercontent.com/2908508/61521285-134ab900-aa3a-11e9-820b-8cfa52b470cc.png)

Only online version from http://draw.io works. And it's 10.9.8
![image](https://user-images.githubusercontent.com/2908508/61521299-21003e80-aa3a-11e9-89d1-3495081a5190.png)

**Comment by vegansk** [comment]
Sure.

[test.xml.zip](https://github.com/jgraph/drawio/files/3410437/test.xml.zip)

Export result:
![test](https://user-images.githubusercontent.com/2908508/61525670-1302eb80-aa43-11e9-922d-3100377305dd.png)

**Comment by davidjgraph** [comment]
Needs testing in ubuntu 18.04

**Comment by diufanman** [comment]
Same thing happen in my Windows 10 for the draw.io desktop

OS: windows 10
draw.io desktop version: v11.2.1
chrome version: Version 76.0.3809.100 (Official Build) (64-bit)

Attached FYI
![exportBug](https://user-images.githubusercontent.com/12424674/63564809-256bca00-c599-11e9-9ec5-0a0787dc6bb0.jpg)
![exportBugEditor](https://user-images.githubusercontent.com/12424674/63564810-256bca00-c599-11e9-9c9a-aa89b7ab0206.png)

**Comment by davidjgraph** [comment]
There is no 11.2.1 version of the desktop build. Where did you get this from?

**Comment by diufanman** [comment]
@davidjgraph 
My draw.io desktop is from google chrome plugin: 

https://chrome.google.com/webstore/detail/drawio-desktop/pebppomjfocnoigkeepgbmcifnnlndla?hl=en-GB

Please see attached screen shot:
![draw io version](https://user-images.githubusercontent.com/12424674/63659258-16785800-c7e3-11e9-9c1c-1543aef04240.png)

**Comment by davidjgraph** [comment]
OK, the chrome package app version, we'll leave this open in case someone gets time to look.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by houssemFat** [comment]
Hello , any updates concerning this issue. I use the web app and some images are broken in the exported png (added via link).

![image](https://user-images.githubusercontent.com/5431172/89633107-99cf7400-d8a3-11ea-9b2e-fada6b3200a2.png)

**Comment by davidjgraph** [comment]
Are you certain this is exactly the same problem, not just the same result? That is, clipart images from within the app do not render?
