### ISSUE TITLE
Post vsd import label editing issues

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#476]
"I've got some shapes with embedded labels and I can't seem to figure out how to make changes to those labels. In ***** I can easily change both the text as well as the position of the text."

[APG Network Overview.vsd.txt](https://github.com/jgraph/drawio/files/3377670/APG.Network.Overview.vsd.txt)

**Comment by ashrafteleb** [comment]
Fixed in the next release. Label can be changed by double clicking on it. To move these labels, two single clicks on the label, then move
