### ISSUE TITLE
Select multiple objects via query

### ISSUE THREAD

**Issue by GaTechThomas** [jgraph/drawio#477]
Is it possible to select multiple shapes in a diagram via some sort of query mechanism?

It would be very helpful to be able to select many items that, say, have the same background color or have a particular property value.

If this isn't built in, what sort of starting point can you offer for me to create this functionality myself?

**Comment by davidjgraph** [comment]
Closest thing is tags, but that's show/hide, rather than selection.

**Comment by alderg** [comment]
The Show button does also select the cells.
