### ISSUE TITLE
Some external links don't behave as expected 

### ISSUE THREAD

**Issue by Farcasut** [jgraph/drawio#4789]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should report bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
If you add an external link to a diagram without the https:// prefix the link will redirect you on https://app.diagrams.net/www.google.com instead of the actual external site.

**To Reproduce**
1. Click on the + symbol on the top menu.
2. Select link
3. In the URL section paste: www.google.com
4. click on the added link

**Expected behavior**
Redirect to the external site.

**Screenshots**
![image](https://github.com/user-attachments/assets/d7ec62c6-c205-4835-86b2-9fefe02bd542)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 25.0.3

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Browser Version 133.0 (64-bit)

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Comment by davidjgraph** [comment]
https://kb.blackbaud.com/knowledgebase/Article/67574
