### ISSUE TITLE
Draw.io insert Google Doc in Document Store is Blocked

### ISSUE THREAD

**Issue by scrfix** [jgraph/drawio#4798]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should report bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
This app is blocked
This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.

**To Reproduce**
1. Go to 'Google Docs in your Google Doc.'
2. Open a new Google Doc.
3. Click on 'Extensions'
4. Then highlight 'Addons'
5. Then click Get Addons
6. Search for draw.io
7. Click on the draw.io addon for inserting diagrams into the Google Doc. It has 3.8 stars.
8. Click Install
9. Click Continue to authorize permissions.
10. Choose your Google Account.
11. Click Continue
12. See error

**Expected behavior**
Add-on will install

**Screenshots**
https://prnt.sc/nfA4py4DfIhG

**draw.io version (In the Help->About menu of the draw.io editor):**
Unable to install. No version.
- draw.io version n/a

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Chrome]
 - Browser Version [Version 131.0.6778.109]

**Smartphone (please complete the following information):**
 - Device: [Google Pixel]
 - OS: [15]
 - Browser [Chrome]
 - Version [13]

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
Yes

**Additional context**
This report is to try to get this information into someone's hands that can check into it and fix the issue.  I am not sure where to report it properly, but I took a hell of a lot of time to fill this out, please don't blow this off because it is not the correct place.  I am taking my time to report an issue to you. If this is the wrong place to report it, then report it to the correct place please. Thank you.

This reddit post has a fix for it in the comments: https://www.reddit.com/r/GoogleAppsScript/comments/u28bsl/this_app_is_blocked_this_app_tried_to_access/

**Comment by davidjgraph** [comment]
There is nothing to add from #4589 and still nothing we can do about it.
