### ISSUE TITLE
Losing properties when importing a visio vsdx file

### ISSUE THREAD

**Issue by ristllin** [jgraph/drawio#4800]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When Importing a visio vsdx file into drawio connector type is changed from curved to straight.

**To Reproduce**
1. Download the attached file and unzip
[test_flowchart.vsdx.zip](https://github.com/user-attachments/files/18201216/test_flowchart.vsdx.zip)
2. Go to draw.io
3. Click on File -> open from -> Device
4. Select the unzipped sample file attached to this bug report
5. See the lines are now straight

**Expected behavior**
The lines should remain curved as they are in the original visio file.

**Screenshots**
Expected:
![image](https://github.com/user-attachments/assets/1a3d8bca-26ee-40eb-89d0-0f88eddcaf6c)
Actual:
![image](https://github.com/user-attachments/assets/2ac1c3f3-f427-4af9-84b2-0faf3894fc6f)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 25.0.3 (latest as of this report)

**Desktop (please complete the following information):**
 - OS: tested on IOS and Linux
 - Browser: chrome
 - Browser Version 131.0.6778.140 (Official Build) (arm64) (latest as of this report)

**Smartphone (please complete the following information):**
 - Not Relevant

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**

**Comment by davidjgraph** [comment]
Duplicate #2104
