### ISSUE TITLE
Google blocked draw when i integrate it with google doc

### ISSUE THREAD

**Issue by wenzizone** [jgraph/drawio#4807]
This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.

![iShot_2024-12-25_09 35 03](https://github.com/user-attachments/assets/92b54d93-35fe-4d1a-b9ba-860cba1b0874)

how to resolve it

**Comment by davidjgraph** [comment]
There is nothing to add from https://github.com/jgraph/drawio/issues/4589 and still nothing we can do about it.

**Comment by superty** [comment]
I would suggest just deleting the app from the store so that users stop getting confused and you stop getting these duplicate issues :)

**Comment by davidjgraph** [comment]
It works for everyone that currently has it installed. If we delete the entry that uninstalls it for everyone.

**Comment by superty** [comment]
I see, I guess that makes sense then! Maybe you could still update the name/description in the store, if possible
