### ISSUE TITLE
Feature Request: add opacity slider in color chooser

### ISSUE THREAD

**Issue by JensErat** [jgraph/drawio#481]
Opacity is often very helpful in diagrams, especially when having larger labels on lines.

By adding two more hex digits to the RGB code, one can already setup opacity:

![image](https://user-images.githubusercontent.com/628441/61523101-f7342100-aa13-11e9-8f41-fbc51b4e7c1d.png)

And it actually works:

![image](https://user-images.githubusercontent.com/628441/61523045-dd92d980-aa13-11e9-9760-14be72e4eda2.png)

Also operations like saving/restoring the file, exporting diagrams, copying styles already work without any issues as far as my experiments went, but the opacity is cut off when opening the color picker again.

It would be great if the color picker UI gets support for opacity, for example an opacity slider next to the lightness slider. Some poor man's UI mockup:

![image](https://user-images.githubusercontent.com/628441/61524162-2481ce80-aa16-11e9-9e2b-e828971ceaa9.png)

**Comment by JensErat** [comment]
Looks to me like this was already implemented by now, issue can be closed? Thank you very much!

![image](https://user-images.githubusercontent.com/628441/64694760-b8ae6600-d49a-11e9-839c-4bd191852191.png)

**Comment by viacheslav-mik** [comment]
Hi, the workaround with manual adding 2 last digits doesn't work anymore.
The opacity settings changes the whole element's opacity, while it would be good to allow different opacity for stroke, fill and gradient colors.

**Comment by alderg** [comment]
> Hi, the workaround with manual adding 2 last digits doesn't work anymore. The opacity settings changes the whole element's opacity, while it would be good to allow different opacity for stroke, fill and gradient colors.

Fixed in 28.2.6

<img width="249" height="62" alt="Image" src="https://github.com/user-attachments/assets/770dd33e-e3c4-40bf-bc10-c6cd0468f51a" />
