### ISSUE TITLE
Line end spacing/offset not working when the lines destination is a connector point

### ISSUE THREAD

**Issue by hatalmasalma** [jgraph/drawio#4822]
EDIT: SEE MY COMMENT BELOW

### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should report bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
When setting the number input field of Line Spacing to any value, the line ending doesn't react at all.
I tried inputting positive and negative numbers, tried typing text and incrementing by the arrow buttons, tried creating the lines using different ways, changing line ending types.

**To Reproduce**
1. Place two rectangles
2. Make a line between them
3. Select the line
4. Change Line end Spacing values in the right side bar
5. Nothing happens

**Expected behavior**
The line end symbol should move somehow.
I expect it to move towards the line center when given positive value, and move away from it when given negative value (so it no longer contacts the line).

**Screenshots**
Nothing happens:
![Line end 50pt](https://github.com/user-attachments/assets/8d8ab860-0b4c-4098-aa31-150e7423c0e6)

Still nothing happens:
![Line end -50pt](https://github.com/user-attachments/assets/140df420-bec6-4af5-85c6-f48ed52109ff)

Expected:
![Line end expectationt](https://github.com/user-attachments/assets/06dfb7fe-7ed3-40f1-a779-6d7db6d305a3)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version v26.0.2 browser, v25.0.2 desktop

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox, Chromium
 - Browser Version Firefox 133.0-1, Chromium 131.0.6724

**Smartphone (please complete the following information):**

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**
The Line ending Size field works fine.

**Comment by hatalmasalma** [comment]
Nevermind, seems like it didn't do anything because I only tested pointing the lines to connector points.
The line end spacing works fine when the line is pointed to a object instead of its connector points.

I will test further and consider opening another issue/feature request for it to work when a line's destination is a connector point, but this report in its current form is invalid.

**Comment by malthe** [comment]
When is line spacing then supposed to work? I find that it doesn't work for connections, but also doesn't do anything for just random lines. It just has no effect no matter what 🙈 – !
