### ISSUE TITLE
Unable to save to GitLab if repository name contains a space

### ISSUE THREAD

**Issue by nfriend** [jgraph/drawio#484]
When saving drawings to [GitLab.com](https://gitlab.com/), the folder selection process fails with a `File not found` message when selecting a repository that contains a space in the name:

<img width="708" alt="Screen Shot 2019-07-22 at 12 38 02 PM" src="https://user-images.githubusercontent.com/1638631/61645713-9f005780-ac7d-11e9-8903-a5ba1faa76d4.png">

This screenshot was captured when selecting my repository named ["Draw.io Drawings"](https://gitlab.com/nfriend/draw.io-drawings).  I was able to successfully save a drawing in a repo named ["Draw.ioDrawings"](https://gitlab.com/nfriend/draw.iodrawings).

I _think_ this is happening because draw.io is making a request to the GitLab API using the project **name** instead of the project **path**.  For example, I can see a request being made to https://gitlab.com/api/v4/projects/nfriend%2FDraw.io%20Drawings/repository/tree?path=&ref=master, which fails with a 404.  If I instead make a request to https://gitlab.com/api/v4/projects/nfriend%2Fdraw.io-drawings/repository/tree?path=&ref=master, the request succeeds.

This is admittedly a little bit confusing as [the docs](https://docs.gitlab.com/ee/api/README.html#namespaced-path-encoding) use `NAMESPACE/PROJECT_NAME` as a placeholder.

Note that the API [also supports using the project ID to reference projects](https://docs.gitlab.com/ee/api/repositories.html#list-repository-tree), which might be a bit more straightforward and easier to work with.

**Comment by nfriend** [comment]
As a side note, I opened an MR to clarify the difference between project names and paths in the GitLab API docs here: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/31019.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
