### ISSUE TITLE
iOS - Open a file in draw.io from One Drive / Dropbox / Device - Errors

### ISSUE THREAD

**Issue by LearnedWords** [jgraph/drawio#486]
Device: 2018 iPad Pro, iOS 12.3.1, using draw.io in Safari. 
Also tested on 2016 iPad, iOS 12.3.0 & iPhone X 12.3.1.
Doesn’t matter whether popups are enabled or disabled in Safari preferences - the behavior is the same.
Cookies are not blocked. 
Minimal draw.io theme by default.

(Authentication with One Drive is successful)
1. Open an existing file results in an error “popup windows is disconnected”
2. Redirected to the One Drive app, which then displays an error. 
3. Redirected to One Drive in the browser. Select the file, click on Open and nothing happens. 

(Tested with and without closing the original error “popup window is disconnected”)

![IMG_0091](https://user-images.githubusercontent.com/26007669/61710074-fe7b6780-ad50-11e9-85db-f4c323e51d94.jpeg)

**Comment by LearnedWords** [comment]
Following the same procedure to open the file stored in DropBox (authentication also ok), results in Error 409. 
![IMG_4726](https://user-images.githubusercontent.com/26007669/61711125-9d08c800-ad53-11e9-9b02-f9ab9f053781.png)

**Comment by LearnedWords** [comment]
Open from device (iCloud) results in another error: “This web page was reloaded because a problem occurred”
![IMG_0095](https://user-images.githubusercontent.com/26007669/61711294-fd980500-ad53-11e9-9997-fa5320857a85.png)

**Comment by LearnedWords** [comment]
I can open draw.io diagrams from links in about.draw.io/blog posts and Google Drive on iOS without problems.

**Comment by davidjgraph** [comment]
Still an issue?

**Comment by t-j-n** [comment]
I have the issue that it reloads when trying to open a diagram from iCloud (option “Local Storage”) in Safari on an iPad Pro 12 with latest iOS. The same file loads fine when I copy it to Dropbox and open it from there. This worked in the past and I see the issue for two weeks, or so

**Comment by mmamedel** [comment]
The real problem is that iOS is triggering the apps installed. To solve you could:
* uninstall the app
* use Safari in private browsing mode
* lock Safari with Guided access 

The last one turned out to be my favorite because I can quickly turn it on and off without having to uninstall/install apps or login every time.
More details on how to do this you can find [here](https://www.howtogeek.com/682177/how-to-stop-safari-from-launching-apps-on-iphone-and-ipad/)
