### ISSUE TITLE
Getting error's while building

### ISSUE THREAD

**Issue by imidimi** [jgraph/drawio#487]
Hi,
I m getting the following errors while building the zip file provided for drawio. I have also tried different version's as well. I m using eclipse latest version to build it. Can you see the screenshot and help me resolve the issue.
![Screenshot (90)](https://user-images.githubusercontent.com/39778287/61772864-b588e900-ae0c-11e9-8491-f161e3314d53.png)

**Comment by davidjgraph** [comment]
Don't use the zip, just clone the repo and use that.
