### ISSUE TITLE
Objects slip after exporting them into svg format

### ISSUE THREAD

**Issue by asd4fgh** [jgraph/drawio#488]
I created a diagram in draw.io and exported it to svg format.
I attached both, the .drawio file and the .svg file. [Files.zip](https://github.com/jgraph/drawio/files/3425816/Files.zip)
Looking at the svg file, there are some objects, especially the small circles with the dots or the cross in their center, which have slipped out of place compared to the .drawio file, but just on another viewer. For example in Inkscape/Opera browser/Firefox browser and Internet Explorer. Reopening the .svg file in draw.io and the objects are in place again. As mentioned I used different browser, both to create in draw.io and to view the svg files.
I also tried to export into pdf format, but the pdf is not different to the svg, the same objects slip the same way compared to the svg.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by asd4fgh** [comment]
I just tried using Chrome to export the file. And it worked, being exported by Chrome the objects will not slip out of place no matter which viewer I use.
