### ISSUE TITLE
SVG export missing header

### ISSUE THREAD

**Issue by not-k** [jgraph/drawio#491]
When trying to use exported SVG's in an image tag, I get the little broken image icon in all of my browsers. I compared the SVG content between the draw.io export and some random SVG's from the internet which do work in my image tag, and noticed the draw.io image is missing this header as the first line of the file:

    <?xml version="1.0" encoding="UTF-8"?>

When I manually add this header, the draw.io SVG starts working in my img tags.

I believe this is a bug which can be fixed by draw.io prepending this header when exporting SVG. (Assuming it does not cause other regressions, but I imagine it's pretty benign as most other SVG's have it)

**Comment by alderg** [comment]
Can you share that image tag?

**Comment by not-k** [comment]
I believe the simplest img tag exhibits the issue <img src="my_image.svg"> when the server returns the svg file with some (incorrect) generic "text" mime-type (bitbucket does this for all files, such as image assets you want to embed in a readme). 

So arguably that mime type from bitbucket is the actual bug, but it seems that browsers will render any raster image still, and only reject the svg source, and it seems the xml header makes the issue go away, and is clean standard practice to put it on svg files anyway.

**Comment by alderg** [comment]
This will be fixed in the next release.
