### ISSUE TITLE
[Bug] - Importing a diagram reassigns layer IDs

### ISSUE THREAD

**Issue by LearnedWords** [jgraph/drawio#496]
Using the floor plan example from the blog, https://about.draw.io/interactive-diagrams-with-custom-links-and-actions/ and importing (drag&drop) into Confluence Server/Cloud, Jira Cloud and draw.io web all reassigned the layer IDs so that the interactive toggle links were broken (they referred to the old layer IDs).

**Comment by alderg** [comment]
This will be fixed in the next release.
