### ISSUE TITLE
Improve Visio export Quality

### ISSUE THREAD

**Issue by anb65** [jgraph/drawio#497]
I imported a simple Visio .vsd file, heavily modified it and tried to export it again, but the resulting .vsdx file cannot be open by the official MS Visio 2016 viewer (reported error "The Visio viewer did't succeed to complete the operation").
Moreover, if I try to re-import the .vsdx file in draw.io, I find it a little bit messed up: some objects disappear behind other ones, text alignment is often wrong, line spacing seems to be based on Helvetica 12 size even if the actual text is smaller (Helvetica 10), position of text in the boxes is not respected (always set to center), and some other minor issues.
I attach here my original draw.io file and the exported .vsdx file for your review; I tried both Mozilla Firefox Quantum rel. 68.0.1 (64 bit) and Microsoft Edge as browser to run draw.io, but the result has been the same.

[Example.zip](https://github.com/jgraph/drawio/files/3458906/Example.zip)

**Comment by Partizanin** [comment]
Also have a problem with exporting to vsdx, would be great if you fix it 😊

**Comment by davidjgraph** [comment]
Please avoid “me too” comments. They create noise in the thread without adding anything to the issue. Thumbs up on the first comment is the convention in github to indicate this.

**Comment by ashrafteleb** [comment]
The corrupted vsdx output is fixed. We are still working on improving the export quality
