### ISSUE TITLE
Language list unkown charactors

### ISSUE THREAD

**Issue by rickywu** [jgraph/drawio#498]
Runs well locally but  not work in docker,
I follow the step to build docker image:
```
cp etc/docker/Dockerfile .
docker build -t draw .
docker run -d -p 8888:8080 draw
```
![image](https://user-images.githubusercontent.com/442398/62350143-65a8d100-b534-11e9-9f9e-66aefbb3a9ed.png)

**Comment by rickywu** [comment]
I crated a pull request https://github.com/jgraph/drawio/pull/499

**Comment by davidjgraph** [comment]
Thanks, note that we recommend https://github.com/fjudith/docker-draw.io for draw.io in docker, it's actively maintained.

**Comment by rickywu** [comment]
@davidjgraph  This repo is base on release source, 
but sometimes someone want to change sources and build docker images for themself
