### ISSUE TITLE
Automatically connect new text box to previous text box

### ISSUE THREAD

**Issue by JesseAldridge** [jgraph/drawio#500]
Like I said in another ticket, I'm using draw.io to generate something like mind maps. I usually double click and start typing to add a text box. I repeat this many times, and then connect all the text boxes together with lines after a while. The process of adding the lines to connect all of the text boxes together actually consumes a surprisingly large amount of time due to the high volume of text boxes that I need to interconnect. 

The vast majority of the time I simply want to connect the most recently created text box to the one that I created immediately before. It would be very nice for my workflow if a line from the most recent text box to the previously created text box was automatically created. 

I can see this behavior being unexpected to users in some cases. But maybe the line between the two text boxes could only be created if the two text boxes were created within ten seconds of one another? If you are opposed to the idea of automatically creating lines, even a keyboard shortcut to automatically connect the most recently created text box to the previous one would be quite helpful.

Example of the sort of document I am creating:

![Screen Shot 2019-08-02 at 3 01 24 PM](https://user-images.githubusercontent.com/191903/62401072-75291980-b536-11e9-920a-7736821cb815.png)

**Comment by davidjgraph** [comment]
https://about.draw.io/organization-charts-and-mind-maps-in-draw-io/

**Comment by JesseAldridge** [comment]
Ok, yeah that's what I want. The little blue arrows that appear when you mouse over the text boxes do the job. Thanks. 

Not sure why I didn't think to try them. I think I tried them out when I first started using draw.io a long time ago, decided they weren't for me, and then quickly became blind to their existence.

**Comment by davidjgraph** [comment]
Could also use the mindmap container in the advanced section, give you the keyboard shortcuts mentioned.

**Comment by JesseAldridge** [comment]
Nah, I don't actually want mind-maps. Mind maps are tree structured but I want a graph.
