### ISSUE TITLE
Justificar un texto de un cuadro

### ISSUE THREAD

**Issue by luiscan** [jgraph/drawio#502]
Quiero justificar un texto que está dentro de un cuadro y no me sale opción. Solo derecha izquierda y centrado.

![descarga](https://user-images.githubusercontent.com/207978/62413700-8bd37d00-b5d7-11e9-9368-6817653023b0.png)

**Comment by davidjgraph** [comment]
What version of draw.io and what browser/version is this?

**Comment by luiscan** [comment]
Google chrome - Versión 75.0.3770.142 (Build oficial) (64 bits)
Drawio 11.1.1
