### ISSUE TITLE
The procedure written on your wiki did not work

### ISSUE THREAD

**Issue by omuomu** [jgraph/drawio#503]
#  The procedure written on your wiki did not work
## reproduction procedure
* Follow the wiki procedures
* Running locally in the browser
```
>python -m SimpleHTTPServer 8000
```
## Actual Results
```
>python -m SimpleHTTPServer 8000
\Python37\python.exe: No module named SimpleHTTPServer
```

## Expected Results
```
\war >python -m SimpleHTTPServer 8000
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
```
I can't find the directory /war
Instead, I found src/main/webapp
The following command worked.
```
> drawio\src\main\webapp>python -m http.server 8000
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
```

## My Environment
OS Windows 10 Home
version: 1803
OS build: 17134.885

### Python
```
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
```

**Comment by davidjgraph** [comment]
We didn't write this this, it was a community submission., which wasn't maintained. I'll detele.
