### ISSUE TITLE
Multiple imports from CSV with parent/child skews the output

### ISSUE THREAD

**Issue by GaTechThomas** [jgraph/drawio#504]
Repro:

Import the following draw.io CSV file, then import it again with new ID values (e.g., append a zero to each ID and parent ID value).

The result is that imports after the initial import cause the child items inside the container to all be skewed inside the container by the x,y value of the parent item.

```
## Shapes and their styles
# stylename: shapeType
# label: %name%
# ignore: id
# identity: id
# left: xposn
# top: yposn
# parent: rparent
# parentstyle: shape=rect;whiteSpace=wrap;html=1;horizontal=1;horizontalStack=0;resizeParent=1;fillColor=#F0F8FF;strokeColor=#666666;perimeter=rectanglePerimeter;container=1;recursiveResize=0;collapsible=0;
##*************
id,rparent,name,shapeType,xposn,yposn
a0,1,TopBox,rect,300,200
a1,a0,Name1,rect,50,80
a2,a0,Name2,rect,100,120
a3,a0,Name3,rect,150,80
```

**Comment by varunpalekar** [comment]
I am also facing some similar issue, using the following csv file:

```
## name,parent,egress,ingress,shape
# label: %type%<br>%name%
# style: %shapes%
# identity: name
# parent: parent-application
#
# parentstyle: %shapes%
#
# connect: {"from":"egress", "to":"name", "style":"curved=1;endArrow=blockThin;endFill=1;"}
# connect: {"from":"ingress", "to": "name", "invert": true, "style":"curved=1;"}
#
# namespace: csvimport-
# width: auto
# height: auto
# padding: -12
# ignore: shape,ingress,egress
# nodespacing: 40
# levelspacing: 100
# edgespacing: 40
# layout: verticaltree
## ---- CSV below this line. First line are column names. ----
name,parent-application,egress,ingress,type,shapes
k8s-multi-tenant,,"","",k8s,"fontSize=22;strokeColor=#326ce5;imageBorder=#326ce5;image=https://kubernetes.io/images/favicon.png;style=label;html=1;imageAspect=1;whiteSpace=wrap;fillOpacity=30;container=1;dashed=1;strokeWidth=6;"
istio-system,k8s-multi-tenant,"","",ns,"fontSize=17;strokeColor=#326ce5;imageBorder=#326ce5;style=label;html=1;imageAspect=1;whiteSpace=wrap;fillOpacity=30;container=1;dashed=1;strokeWidth=6;"
istio-prodgateway,istio-system,"","",deploy,"shape=image;fontSize=11;image=https://raw.githubusercontent.com/kubernetes/community/master/icons/svg/resources/labeled/deploy.svg;style=label;html=1;imageAspect=1;aspect=fixed;"
kube-system,k8s-multi-tenant,"","",ns,"fontSize=17;strokeColor=#326ce5;imageBorder=#326ce5;style=label;html=1;imageAspect=1;whiteSpace=wrap;fillOpacity=30;container=1;dashed=1;strokeWidth=6;"
```

**Comment by GaTechThomas** [comment]
@varunpalekar I don't know whether my code ever got pulled in. If you want to try it, it's at the following link. It's just 3 lines of code, so it's probably easiest to just manually repeat it on the newest code base.

https://github.com/jgraph/drawio/compare/master...GaTechThomas:master

**Comment by varunpalekar** [comment]
Thanks @GaTechThomas I will try this and let you know 👍

**Comment by GaTechThomas** [comment]
Any luck?

**Comment by chmduquesne** [comment]
Hi,

I found this issue while searching if there is a way to create a container shape in a csv import. I cannot find any reference to the "parent" configuration statements in the examples (found above)

```
# parent: parent-application
#
# parentstyle: %shapes%
```

I would be very interested in knowing how to use these statements, if they are supported (even if a bit buggy).

Is this something that one can experiment with?

Cheers,
Christophe-Marie

By the way: thanks for the csv import! I wrote a small python library to export a python networkx graph in drawio and I will opensource it soon 🙂

**Comment by GaTechThomas** [comment]
In case it helps... I see that the link in my comment earlier in this thread is not displaying any code changes. Here's a link that shows the change... at least it shows the diffs today. 🙂

https://github.com/GaTechThomas/drawio/commit/101a230dac410d2c039cbc27ab2979f8d94755ef?diff=unified

**Comment by chmduquesne** [comment]
@GaTechThomas this does help tremendously! It looks like this parent feature is in the master branch, so even if not documented, I can try it! Thank you for pointing me to the part of the code which reads the CSV, it helps to understand how it works exactly 🙂

**Comment by alderg** [comment]
See also https://groups.google.com/g/drawio/c/pDGf3gv5X8w/m/TiNg-oMZBQAJ

**Comment by davidjgraph** [comment]
This looks fixed. Any issues please reopen new ticket.
