### ISSUE TITLE
Export PNG with include a copy of my diagram in Chinese language failed.

### ISSUE THREAD

**Issue by purocean** [jgraph/drawio#506]
Reproduce:

1. Visit https://www.draw.io/
2. Switch Language to Simplified Chinese 简体中文
3. Draw a diagram with any content.
4. Export PNG. Check the "include a copy of my diagram" checkbox.
5. Click Export.

![image](https://user-images.githubusercontent.com/7115690/62450822-a0627180-b79f-11e9-82e9-045a2128595a.png)

**Comment by davidjgraph** [comment]
This bug report falls below the minimum standard needed to investigate. Please read https://stackoverflow.com/help/how-to-ask and improve the report, otherwise it will be closed.

**Comment by purocean** [comment]
I suggest use custom `Base64` tool Instead instead of `window.btoa`.

![image](https://user-images.githubusercontent.com/7115690/62451028-0e0e9d80-b7a0-11e9-8574-625a303a9e89.png)

**Comment by AdrianDuan** [comment]
Faced the same problem after I upgrade draw.io to the latest version.

**Comment by davidjgraph** [comment]
What browser are you using that doesn't have btoa?

**Comment by davidjgraph** [comment]
Thanks for the report, this should be fixed in 11.1.2. The desktop build will need another release.

**Comment by image72** [comment]
@davidjgraph just same problem repetition, in 
https://github.com/jgraph/drawio/blob/4785a219c80c7bec68aa54c236c590fca5558bd8/src/main/webapp/js/grapheditor/Format.js#L4568

because svg shape has unicode character id.
[properly process 
](https://stackoverflow.com/questions/23223718/failed-to-execute-btoa-on-window-the-string-to-be-encoded-contains-characte/26603875#26603875)

**Comment by image72** [comment]
convert that svg to mxlibrary file, and File > Open Library from > Device, pick mxlibrary file. 
then drag shape from shapes library, in Style panel click Fill .cls-1 color pick, will rise error
![wheel](https://github.com/jgraph/drawio/assets/243154/189538d6-ffac-4d1e-b188-5cbdc7170656)

[library.xml.zip](https://github.com/jgraph/drawio/files/12034634/library.xml.zip)

<img width="967" alt="image" src="https://github.com/jgraph/drawio/assets/243154/abdcb972-d0fe-4d02-a75f-b2053ffa0f51">

**Comment by image72** [comment]
but I think that problem resolved in 11-JUL-2023 version: 21.6.2

much Appreciate. ❤️

**Comment by image72** [comment]
> @image72 Could you please attach a test case so that we can verify our fix?

but I think that problem resolved in 11-JUL-2023 version: 21.6.2

much Appreciate. ❤️
