### ISSUE TITLE
Deleting object from group disables "To Front", creates phantom object

### ISSUE THREAD

**Issue by mrlnc** [jgraph/drawio#509]
Hi everybody!

Grouping objects sometimes renders the "To Front" or "To Back" functionality unusable. The object / group will just stay in its place.

Also, deleting objects from a group do not update the group's dimensions.

File with diagram included:
![grouping_bug-2](https://user-images.githubusercontent.com/1729953/62535475-ccd3c780-b84b-11e9-9d02-0d8588993f15.png)

# Steps to reproduce:
1) Add a big rectangle.
2) Add a small rectangle, place it in front of the big rectangle.
3) Group both objects.

```
########################
#   big rectangle.     #
#                      #
#  [ small rectangle ] #
#                      #
########################
```

4) Copy the Group. We will work with the Group copy now.
5) Click on the small rectangle a few times until only the small rectangle is selected.
6) Move the small rectangle a bit.
```
########################
#   big rectangle.     #
#                      #
#                 [ small rectangle ]
#                      #
########################
```
7) Click on the big rectangle like crazy, until not the whole group but only the outside rectangle is selected.
8) Delete the big rectangle.

# Expected Behavior

The big rectangle is gone, the small rectangle is the only object left in the group.

* Group is deleted, or
* Group dimensions are resized to the remaining objects
* The Group still behaves like a normal object.

# Actual Behaviour
## Group Size / Phantom Objects
The remaining part is the small rectangle, *and the group properties*. It looks like the following:
```
~~~~~~~~~~~~~~~~~~~~~~~~
~                      ~
~                  [ small rectangle ]
~                      ~
~~~~~~~~~~~~~~~~~~~~~~~~
```

The group size still remembers the big rectangle. It is possible to separate the "phantom" big rectangle and the small rectangle, so that an empty "group" object remains -- in total different locations than it's remaining member (the small rectangle).

## To Front / To Back
The resulting object cannot be put "To Front" or "To Back". The option is available but nothing happens when you click the button.
Note: You need to select the *group* with the phantom object, not explicitly the contained small rectangle.

**Comment by mrlnc** [comment]
<img width="596" alt="image" src="https://user-images.githubusercontent.com/1729953/83442200-167b4780-a448-11ea-8cfc-9868a87bab8a.png">

I can still reproduce this issue.

**Comment by davidjgraph** [comment]
@mararad could you check please?

**Comment by mararad** [comment]
I couldn't reproduce the part "Click on the big rectangle like crazy, until not the whole group but only the outside rectangle is selected." but phantom shape reproduced in 13.10.3 in Google Chrome

![fantom shape](https://user-images.githubusercontent.com/44292306/100341112-6d6b6f00-2fdc-11eb-99fc-84743591f1e5.JPG)

<mxGraphModel dx="1422" dy="762" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="850" pageHeight="1100" math="0" shadow="0">
  <root>
    <mxCell id="0" />
    <mxCell id="1" parent="0" />
    <mxCell id="3gBneRASPnXDAm0hd718-14" value="" style="group" vertex="1" connectable="0" parent="1">
      <mxGeometry x="200" y="300" width="260" height="170" as="geometry" />
    </mxCell>
    <mxCell id="3gBneRASPnXDAm0hd718-13" value="" style="rounded=0;whiteSpace=wrap;html=1;fillColor=#f8cecc;strokeColor=#b85450;" vertex="1" parent="3gBneRASPnXDAm0hd718-14">
      <mxGeometry x="170" y="-10" width="120" height="60" as="geometry" />
    </mxCell>
  </root>
</mxGraphModel>

**Comment by mararad** [comment]
![fantom shape](https://user-images.githubusercontent.com/44292306/100341331-b4596480-2fdc-11eb-9763-6a763605253f.JPG)

**Comment by alderg** [comment]
This is the expected behaviour. The group does not autosize, it has it's own size, is resizable and has no fill/stroke color assigned by default. ToFront/back on child objects of groups only affects the ordering within that group, ie relative to other child cells of the group.

**Comment by alderg** [comment]
PS: Use the autosize button to update the group bounds to include all child cells:
<img width="241" alt="Screenshot 2021-09-30 at 09 35 08" src="https://user-images.githubusercontent.com/921200/135408266-f08fd60f-49cc-470b-9b70-96b6bfc1e03d.png">
