### ISSUE TITLE
export as png error

### ISSUE THREAD

**Issue by shuzhongling** [jgraph/drawio#512]
it show a error messagebox when i export as png.  the message in the messagebox is: "Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range."  

there is some chinese characters in the graph, maybe this is the cause.

the version of draw.io  is v11.1.1

**Comment by davidjgraph** [comment]
There is a fix in 11.1.2.

**Comment by shuzhongling** [comment]
the drawio desktop software hasn't upgrade to 11.1.2, so this issue continue exists.

**Comment by davidjgraph** [comment]
ok, but this isn't the project for the desktop project, it's fixed in this project :)
