### ISSUE TITLE
PDF export breaks placeholders

### ISSUE THREAD

**Issue by arnoldligtvoet** [jgraph/drawio#514]
In the online version (11.1.2) I have created a plugin that uses a lot of placeholders. In the browser window these look and work fine and content is replaced. When I export the flow to PDF the export contains all placeholders (%placeholder%) and not the expected text. Exporting to PNG does show the expected text. 

This can also be seen using the p1.js plugin. Steps to reproduce:
- load new diagram with p1.js active (https://www.draw.io/?splash=0&p=p1)
- type '%filename%'
- text is replaced by 'Untitled Diagram'
- export to PDF 
- PDF shows single field '%filename%'
- export to PNG
- PNG shows 'Untitled Diagram'

**Comment by alderg** [comment]
Note: This needs a hook to collect global vars to send with pdf export request via extras URL parameter which we can then be injected via urlParams['vars'] to render. (This will not solve the problem for MS office and google docs with server-side PNG creation.)

**Comment by arnoldligtvoet** [comment]
Please note that I went the plugin route as I got errors trying to load via vars in url (header or cookie too large). I’m using about 70 placeholders with text content loaded from a google sheet.

**Comment by ashrafteleb** [comment]
Fixed, it will be available with next release

For plugins, you can add your variables to ui.editor.graph.globalUrlVars = JSON Object
