### ISSUE TITLE
Autosize - there is a difference when you change font size and text content 

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#519]
There is a difference when you change font size and text content (after autosize).
It seems a bit unstable. 

When font size is changed, some shape borders are missing (depend on font size,
![autosize](https://user-images.githubusercontent.com/44292306/62771197-f6376200-ba9c-11e9-8da1-1b5d64a0016f.gif)
 all border can be here, one can be missing or two can be missing).
When you change text content, it works well.

Chrome Version 74.0.3729.131 (Official Build) (64-bit) and Incognito 
draw.io online 11.1.4 and Win10

**Comment by davidjgraph** [comment]
Closing due to lack of interest from the core team.
