### ISSUE TITLE
Connections from children aren't created on CSV import

### ISSUE THREAD

**Issue by DeusExLibris** [jgraph/drawio#520]
When importing from CSV, if a connector is defined that starts from an item that is a child of another item, the connection isn't created.  The example below has a connector between two "fields" in a "table" but the behavior is the same if you try to connect from a child to any other item (you can see this by removing the parent reference from field_b in the example and moving field_b to the end)

# label: %entity_name%
# style: label;whiteSpace=wrap;rounded=1;fillColor=%fill%;overflow=hidden;align=left;spacingLeft=15;
# parentstyle: swimlane;childLayout=stackLayout;horizontal=1;rounded=1;horizontalStack=0;resizeParent=1;resizeParentMax=0;resizeLast=0;collapsible=1;
# identity: id
# parent: parent
# ignore: parent,downstream,fill,stroke
# connect: {"from": "downstream", "to": "id", "invert": false, "style": "curved=1;endArrow=blockThin;endFill=1;fontSize=11;strokeColor=black"}
# layout: horizontalflow
id,entity_name,entity_type,parent,downstream,fill,stroke
"315388520","table_a","TABLE","","","white","black"
"315388522","field_b","FIELD","315388520","","white","black"
"315388521","field_a","FIELD","315388520","315388522","white","black"

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
