### ISSUE TITLE
OneDrive storage type doesn't work on Android/Chrome

### ISSUE THREAD

**Issue by timblaktu** [jgraph/drawio#521]
I open draw.io in chrome on Android v9 phone (Note9). I select OneDrive storage and open existing. This opens a separate OneDrive browser window and I navigate to the library/folder/file I want to open from OneDrive and all it does is download the file onto my android device's downloads folder.

Why doesn't this behave like you'd expect, i.e. why doesn't this open the selected drawing in draw.io and enable auto saving directly to oneDrive?

I have confirmed that Google Drive storage type works fine in this same environment.

**Comment by ashrafteleb** [comment]
It will be fixed in the next release
