### ISSUE TITLE
Search not working for external libraries

### ISSUE THREAD

**Issue by flaimo** [jgraph/drawio#523]
Created from https://groups.google.com/d/msg/drawio/gi5aUH75p-o/1tMpS9tUCwAJ

Steps to reproduce:
1) Install fresh Confluence instance using the official Atlassian docker image with trial licence (6.15.4)
2) Install draw.io addon with trial licence (8.5.0)
3) Add UI config which loads external libraries (see google post for example, also works with https://raw.githubusercontent.com/jgraph/drawio-libs/master/libs/un-ocha-icons-bluebox.xml)
4) Create new diagram
5) Load library into sidebar
6) Expand library 
7) Search for a string that is part of a shape of that library (title) → NOK: No result found

![image](https://user-images.githubusercontent.com/416323/62827594-4c59f180-bbd2-11e9-9cb5-5ad4bcc748f2.png)

**Comment by alderg** [comment]
Thanks for the report, this will be fixed in the next release.

**Comment by flaimo** [comment]
It kind of works now, but this isn't really the intend, that I have to manually expand every library in the sidebar once, before I can search in them, right @alderg ? Because after starting draw.io (as an Confluence addon) this is the current behaviour.

**Comment by alderg** [comment]
Yes, this is currently the expected behaviour for custom libraries. Please open a feature request at https://trello.com/b/XQteVSKr/drawio-confluence-server

**Comment by flaimo** [comment]
I cannot add a request there, since I only have readonly access rights to the board.

**Comment by davidjgraph** [comment]
https://trello.com/c/9WDAt7Kw/247-allow-searching-of-custom-libraries-without-the-need-to-expand-them
