### ISSUE TITLE
even left/right align?

### ISSUE THREAD

**Issue by evanthebouncy** [jgraph/drawio#526]
There's left align, right align, and center align.

It'll be nice to have a feature of "even" align? I do not know the name but the words are even spaced out to have a clear boundary on both left AND right. It's in microsoft for sure. Anyways it'll be a cool feature to have

edit:
justified—text is aligned along the left margin, and letter- and word-spacing is adjusted so that the text falls flush with both margins, also known as fully justified or full justification; centered—text is aligned to neither the left nor right margin; there is an even gap on each side of each line.

^ that thing. can we have it?

**Comment by alderg** [comment]
This will be added in the next release for text blocks (ie via the Text format panel when editing the label).

**Comment by 14ttran** [comment]
I'd like to report that this feature is non-functional in the current release of drawio
