### ISSUE TITLE
Unable to export/save to a local file

### ISSUE THREAD

**Issue by madjoe** [jgraph/drawio#527]
I have drawio-desktop from AUR repo (Manjaro x64). Version of the app is [11.0.5](https://i.imgur.com/QLaskDv.png). There is an output from my _System Log Viewer_, whilst trying to "Export as..." > "PNG" into "~/Documents/Test" directory as "**Untitled Diagram.png**":

```
13. 08. 2019. 20:52	plasmashell	New URI "file:///home/joe/Documents/Test" "" ""
13. 08. 2019. 20:52	plasmashell	New URI "" "" ""
```

As a test content, I used an unchanged template from Maps... here's an XML output of my content: http://pasted.co/1a13e491

I restarted my system and tried again with the same outcome. I tried to save a project by "Save as..." > "**Untitled Diagram.drawio**" to the same location (accessible and writable by any other app) without any success. Writing a file seems impossible for Draw.io.

Any ideas what's happening here?

Thanks,
madjoe

**Comment by davidjgraph** [comment]
We didn’t publish that, you’d have to ask the author.
