### ISSUE TITLE
Elements not positioned at 0/0 when exporting to PDF

### ISSUE THREAD

**Issue by flaimo** [jgraph/drawio#529]
When positioning an element with left=0 and top=0 and exporting the diagram to pdf, there is still a 1pt padding to the element.

![Item-0_and_Menubar](https://user-images.githubusercontent.com/416323/63060554-e97a9a00-bef2-11e9-8a21-7aeb707ecb28.png)

[green_background.drawio.zip](https://github.com/jgraph/drawio/files/3503572/green_background.drawio.zip)
[Untitled Diagram(2).pdf](https://github.com/jgraph/drawio/files/3503573/Untitled.Diagram.2.pdf)

**Comment by mararad** [comment]
Hi,
tested in Chrome Version 83.0.4103.97, win 10 and diagrams.net online 13.2.1

Reproduced when a shape (rectangle) doesn't have a border line + under zoom.
When a shape has border line, all is ok under zoom also.

![ezgif com-optimize](https://user-images.githubusercontent.com/44292306/84369593-5d4f0700-abd7-11ea-9433-6f3b0517c7a2.gif)
