### ISSUE TITLE
Fix locked layer items from changing/attracting mouse state

### ISSUE THREAD

**Issue by russkel** [jgraph/drawio#53]
When I move an object to a locked layer (in this case a simple box to act as a boundary outline for other objects) hoving over the object will change mouse state to 'move', even though it's on a locked layer. I have to turn the layer off to prevent it from changing mouse state.

**Comment by mararad** [comment]
I tested this in draw.io online (Chrome Version 74.0.3729.131 (Official Build) (64-bit)
and desktop app and couldn't reproduce it.
