### ISSUE TITLE
Modify name in custom build 

### ISSUE THREAD

**Issue by VirtualEvan** [jgraph/drawio#530]
We have been using Drawio at CERN for some time now. But due to some specifications in our distribution systems, we will need to difference the name of our built applications from the upstream ones.

For what I have read in the license, this should be OK, but I would like to have a confirmation before proceed.
The name should be something like CERN_Drawio or Drawio_CERN.

Do you think this is an issue or goes against the license somehow?

**Comment by davidjgraph** [comment]
It doesn't conflict with the license. There's probably a convention somewhere for naming, I think it's usually in the version string, but up to you.

**Comment by VirtualEvan** [comment]
OK, I will check.
Thank you for your answer.
