### ISSUE TITLE
Export to PNG missing metadata

### ISSUE THREAD

**Issue by floongle** [jgraph/drawio#531]
Hi,

Whilst the PNG export works well, it is missing some useful metadata. In particular, it's missing the physical image size (the "pHYs" chunk). Having this chunk present means that desktop publishing systems (even MSWord) can set the "physical" size of the image correctly on the page. 

Without this "pHYs" chunk, the app that makes use of the PNG can only guess at the size.

This makes the creation of documents that have multiple diagrams in them (that require higher resolution output than the draw.io default) hard to manage in a way that looks consistent.

Here's a screenshot from TweakPNG showing an example of a PNG that has a "pHYs" chunk present, with correct data. Draw.io's exported PNGs are missing this chunk entirely.

![image](https://user-images.githubusercontent.com/44733236/63109214-92230b00-bf80-11e9-9074-25fc98bd310d.png)

I'm not an expert in these things (sorry!) but to set the "pHYs" value correctly, presumably there needs to be some calculation between the number of pixels (width and height) that the draw.io user sets in the export dialog box, and the "physical" size of the image.

In other words, the pixel width and pixel height can be customised by the draw.io user, but the physical size will _never_ change, no matter what pixel height and pixel width is set. The physical size remains dependant upon the bounds of the image that the user has drawn.

Another way of looking at it is:
* _The user_ defines the **physical size** of the image (by drawing the image to the size they want)
* _The user_ defines the **number of pixels** (pixel width and pixel height) they want the output PNG to have in the Export dialog box
* _Draw.io_ takes both of the above values and calculates the correct "pHYs" pixelsize

(Alternatively, the user defines the **physical size** and the **pixel size**, and Draw.io calculates the correct number of pixels to use in the exported PNG... this also results in a PNG with the correct metadata, but allows the user to set the DPI rather than pixelwidth/height)

**Comment by davidjgraph** [comment]
https://twitter.com/floongle/status/1162037679019712512

**Comment by floongle** [comment]
I'm sure you know this already, but it looks as if the magic should happen here

> src\main\webapp\js\diagramly\Editor.js 
>          Editor.prototype.writeGraphModelToPng

I tried to be a good citizen and fix it, but not being a JS wiz, nor much of a bit-fiddler, I stepped back from what would have been many nights of befuddlement!

That said, I'm very pleased to report that your build guide on the wiki was easy to follow for someone who hasn't dealt with this sort of thing in years!
Other than adding the exact ant commands (which admittedly are super-simple) I can't fault it.

**Comment by ashrafteleb** [comment]
You can now set the DPI of PNG exported images in advanced export dialog (File -> Export as -> Advanced...)

**Comment by floongle** [comment]
Hi,

Just tested it using the latest app version on Windows, v11.2.5.

The DPI dropdown is present, however unfortunately, the _pHYs_ chunk isn't present when creating a png (via File>Export>Advanced). - I checked this using TweakPNG.
![image](https://user-images.githubusercontent.com/44733236/64239255-d6f2ef80-cef7-11e9-9f86-d295c583b5b1.png)

Also, the UI doesn't work in an intuitive way. If you set the DPI to a different value, there's no reason for the Zoom level to change in sympathy. It's the pixel width and height that should change.

I've attached the 100 DPI and 300 DPI examples that I generated below, in case they are of help.
![3by3 300dpi](https://user-images.githubusercontent.com/44733236/64239531-541e6480-cef8-11e9-9ea5-7134a4d143ba.png)
![3by3 100dpi](https://user-images.githubusercontent.com/44733236/64239532-541e6480-cef8-11e9-9120-d4836a4cf64b.png)

Please could this be reopened?

**Comment by ashrafteleb** [comment]
Bug fixed, it will be available in the next release

Currently, you can try DPI on draw.io

The logic of changing Zoom level with DPI is the following:

DPI only tells how many pixels in an inch, so if we only set the DPI info in the PNG metadata, the resulting image dimensions will remains the same on the screen but changes when printed.

But since DPI is mainly for printing, then when an image DPI is increased from 96 DPI (default) to 300 DPI, the image is better scaled 300% to compensate.

Anyway, it is only a UI hint, you can change the zoom level to 100% manually after changing DPI

The following are two PNGs with different DPI that prints to the same area since we changed the Zoom level

100 DPI:
![100 DPI](https://user-images.githubusercontent.com/24944765/64355173-be093d80-cfce-11e9-9504-7433fbadb7fc.png)

300 DPI:
![300 DPI](https://user-images.githubusercontent.com/24944765/64355174-be093d80-cfce-11e9-9a19-4a5ee54d1841.png)

**Comment by borekb** [comment]
@ashrafteleb I'm not sure about how exactly the PNG metadata work but when I upload an image to GitHub, it can usually detect whether it's high-res or low-res and generate appropriate Markdown. Unfortunately, I'm not seeing this behavior with PNG exports from diagrams.net.

For example, I took a screenshot on macOS with a Redina display, and it encoded PPI into the image:

<img width="366" alt="Screen Shot 2021-07-01 at 18 37 49" src="https://user-images.githubusercontent.com/101152/124159488-8325a300-da9b-11eb-95a8-338fd596f008.png">

When I upload this screenshot to GitHub, it is smart enough to use `<img widht="HALF-THE-SIZE" ...>` instead of just `![alt](src)` and I get this nice rendering:

<img width="388" alt="Screen Shot 2021-07-01 at 18 25 21" src="https://user-images.githubusercontent.com/101152/124158852-b9165780-da9a-11eb-88ca-6840faf98d3a.png">

Markdown source for this:

```md
<img width="388" alt="Screen Shot 2021-07-01 at 18 25 21" src="https://user-images.githubusercontent.com/101152/124158852-b9165780-da9a-11eb-88ca-6840faf98d3a.png">
```

Without this trick, the rendering would be ugly:

![Screen Shot 2021-07-01 at 18 25 21](https://user-images.githubusercontent.com/101152/124158852-b9165780-da9a-11eb-88ca-6840faf98d3a.png)

When I try something similar with diagrams.net imports, I can see that some DPI metadata is in the image:

<img width="366" alt="Screen Shot 2021-07-01 at 18 41 26" src="https://user-images.githubusercontent.com/101152/124159945-02b37200-da9c-11eb-9086-5634b3ef75d5.png">
<img width="366" alt="Screen Shot 2021-07-01 at 18 41 48" src="https://user-images.githubusercontent.com/101152/124159952-047d3580-da9c-11eb-8660-8d2591f25202.png">

However, uploads to GitHub still look ugly:

![DPI test – 300 DPI](https://user-images.githubusercontent.com/101152/124158163-ddbdff80-da99-11eb-9d2e-177ffc63b2f4.png)

![DPI test – 100 DPI](https://user-images.githubusercontent.com/101152/124158316-0ba34400-da9a-11eb-816e-ffb7afd763f6.png)

The correct rendering of the first image should be this (I've manually converted it to the `<img width="THIRD-THE-SIZE">` syntax):

<img width="121" src="https://user-images.githubusercontent.com/101152/124158163-ddbdff80-da99-11eb-9d2e-177ffc63b2f4.png">

So something is probably wrong with the metadata.

BTW, this is how the **Export as... > Advanced** dialog looked like when I did the 300 DPI version:

<img width="395" alt="Screen Shot 2021-07-01 at 18 24 47" src="https://user-images.githubusercontent.com/101152/124160197-4f974880-da9c-11eb-9ce2-c7b10b5de6c2.png">

**Comment by borekb** [comment]
Another example:

I've tried creating a similar image in Excalidraw with https://github.com/excalidraw/excalidraw/pull/3530 applied (works in this preview version: https://excalidraw-git-fork-tomashubelbauer-master-excalidraw.vercel.app/. I've exported in "2x" resolution and uploaded to GitHub:

<img width="170" alt="excalidraw-dpi-test-2x" src="https://user-images.githubusercontent.com/101152/124161003-2cb96400-da9d-11eb-8e3e-aac38f15eb3e.png">

Similar test and a 200 DPI export from diagrams.net:

![DPI test – 200 DPI](https://user-images.githubusercontent.com/101152/124161061-3f339d80-da9d-11eb-8481-ac7f4c84d717.png)

Markdown source for both:

```md
<img width="170" alt="excalidraw-dpi-test-2x" src="https://user-images.githubusercontent.com/101152/124161003-2cb96400-da9d-11eb-8e3e-aac38f15eb3e.png">

--- vs. ---

![DPI test – 200 DPI](https://user-images.githubusercontent.com/101152/124161061-3f339d80-da9d-11eb-8481-ac7f4c84d717.png)
```

**Comment by borekb** [comment]
One last desperate attempt was to set DPI to 200 but reset Zoom back to 100:

https://user-images.githubusercontent.com/101152/124161638-f16b6500-da9d-11eb-924e-136833f73ef1.mov

Didn't help either (correct physical resolution but blurry, Markdown is still not `<img src="">`):

![DPI test (4)](https://user-images.githubusercontent.com/101152/124161420-ad786000-da9d-11eb-8b5c-d82b48e1dd9d.png)

**Comment by borekb** [comment]
There's also **File > Embed > Image...** where I can check "Retina". That indeed generates a markup that is "correct":

`<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQYAAAEGCAYAAACHNTs8AAAar0lEQVR4Xu2dCfQN5f/HH7+kRSVahSSppCJbSlK2TpJkSUSW7KSFY2lDKCpL2ZK0oM2aKKcsWcuxVCSnUMkuWVKUIv/znr+ZM3fu3PuZuXe+m8/7OcfBvZ95nufz+sy877POk8swkQAJkICHQC4SIQESIAEvAQoD7wkSIIE4AhQG3hQkQAIUBt4DJEACMgG2GGRGtCABdQQoDOpCTodJQCZAYZAZ0YIE1BGgMKgLOR0mAZkAhUFmRAsSUEcgjDAcV0eHDpPAyUcg0DMfyOgEGwrDyXeT0CN9BAI984GM3MJw/Dj1Qd+9RI9zOoFcuZxHPdAzH8iIwpDTbwvWXzsBCoP2O4D+k4APAQoDbwsSIIE4AhQG3hQkQAIUBt4DJEACMgG2GGRGtCABdQQoDOpCTodJQCZAYZAZ0YIE1BGgMKgLOR0mAZkAhUFmRAsSUEeAwqAu5HSYBGQCFAaZES1IQB0BCoO6kNNhEpAJUBhkRrQgAXUEKAzqQk6HSUAmQGGQGdGCBNQRoDCoCzkdJgGZAIVBZkQLElBHgMKgLuR0mARkAhQGmREtSEAdAQqDupDTYRKQCVAYZEa0IAF1BCgM6kJOh0lAJkBhkBnRggTUEaAwqAs5HSYBmQCFQWZECxJQR4DCoC7kdJgEZAIUBpkRLUhAHQEKg7qQ02ESkAlQGGRGtCABdQQoDOpCTodJQCZAYZAZ0YIE1BGgMKgLOR0mAZkAhUFmRAsSUEeAwqAu5HSYBGQCFAaZES1IQB0BCoO6kNNhEpAJUBhkRrQgAXUEKAzqQk6HSUAmQGGQGdGCBNQRoDCoCzkdJgGZAIVBZkQLElBHgMKgLuR0mARkAhQGmREtSEAdAQqDupDTYRKQCVAYZEa0IAF1BCgM6kJOh0lAJkBhkBnRggTUEaAwqAs5HSYBmQCFQWZECxJQR4DCoC7kdJgEZAIUBpkRLUhAHQEKg7qQ02ESkAlQGGRGtCABdQQoDOpCTodJQCZAYZAZ0YIE1BGgMKgLOR0mAZkAhUFmRAsSUEeAwqAu5HSYBGQCFAaZES1IQB0BCoO6kNNhEpAJUBhkRrQgAXUEKAzqQk6HSUAmQGGQGdGCBNQRoDCoCzkdJgGZAIVBZkQLElBHgMKgLuR0mARkAhQGmREtSEAdAQqDupDTYRKQCVAYZEa0IAF1BCgM6kJOh0lAJkBhkBnRggTUEaAwqAs5HSYBmQCFQWZECxJQR4DCoC7kdJgEZAIUBpkRLUhAHQEKQxaG/I8//jC7d+82//77rylUqJA555xzsrA2xmS3+mQpDOWFUxgy+QbYv3+/GTFihHn77bfNTz/9FFP62WefbcqVK2cef/xxU6dOHeMKTobVMrvVJ8McZcahCFAYQuFKz3j16tWmXr16Ztu2bWJGZcuWNbNnzzYFCxYUbVM1yG71SdUPXhc9AQpD9Ex9c/z111/NddddZ/B30HTbbbeZuXPnmty5cwe9JLBddqtP4IrTMFMIUBgyBbMxnTt3NqNHj3ZKK1y4sHnllVdMmTJlTNGiRa2xBnQvevfuHVOjV1991bRv3z7yWma3+kTuIDNMiwCFIS18wS4+dOiQOeussxzja665xmoJXHLJJXEZzJs3z9SsWdP5vHnz5mbChAnBCgpold3qE7DaNMtEAhSGTID92WefmTvuuMMp6dNPPzW1atVKWDK+g3AgXXnlleaHH36w/o0H2j0+ceqpp5rLL788YT4HDhwwe/bsMbDLkyePyZs3r8mXL5+Jqj7poNu1a5f5+uuvzVdffWW2bNliCSd8uf76602VKlV8s/79998NrkOCL2h1IW3fvt18/vnn1mDu//73P1O8eHFz++23m4svvjgmH/BDecuXLzdHjx61Bnrx57zzzkvHlZPyWgpDJoT1rbfeMq1atXJKwvRksnGDNm3amPHjx1v2mKk4ePCg9e+VK1eaihUrxtR46dKlpnLlynFeHDt2zFStWtUsW7bM+W7w4MGmR48eJqr6pIIOD2S/fv3MgAEDEl5eqVIl88ILL8QJxKBBg5yuFlpda9asMb169TJDhgzxzQtdtYcfftiABfweOnSor13btm0NumwQFab/J0BhyIQ7ATdkt27drJLwq/jjjz8mLbV06dJm7dq1lg1mJzB7YCc8CHjA7YQWxTfffGPOOOOMmDxffvll8+ijjzqfVahQwXzxxReWIEVZnzD4duzYYR544AGzcOHCQJfh1/2GG25wbN3CAL8hkpMmTUqa17Rp0wz+vPvuu0ntunTpYo35ZMYUcSDns9iIwpAJAfjvv/+spqutxGjaJ0pz5swxtWvXdr7GDYt1D3b6+++/rebv+vXrnc8wYPncc885/9+0aZMpUaJETBEbNmxwPouyPmHwubtI9nV33XWXwewLugnTp0+P8QsiilaBPT7jFgZ3uWhV3X333ZYdRAe+Jkro0l144YUG3TnvDNHixYsTdmPC+Hky2FIYskEUseLwu+++s25q76wE+t9FihSJqSX65mhJuBNaFfgMDz0etCVLljhfjx071rRr1y6wp2HrEyRj77gGxgfQ0nH3748cOWJat24d8+uOtRwQDyQ/YWjatKkZOXKkyZ8/v2Vz+PBha62IPUZj1w1s0LooWbKk9RE4YRYI5dmpZ8+eVhlM7Epk6T3QtWvXmNaAuzJ4cN5//33f8QPYoYXw5JNPOpdg0A5jEK+//ro1Ner+RZ41a1agJnI69UkGEn18PJh29wi2EAV0mbzJ29rB2IDddfIKA7oTEFTveM38+fNNjRo1YrL+/vvvzVVXXRVXHj6zWxgNGjQwU6dOzdJ7IrsUzhZDFkbCPcjorQbGBIYPH25uvvlm3xqia4LvIAZ2atGihfUraCc0sXHTe0fnE7mcTn2SYfS2cKRf5vr165sZM2ZYWYLDihUrrH97heHDDz8099xzT1zRmzdvNsWKFYvhggFXv4TWxcyZM62vMIiLwVwmthiy9B7AiDmawckSBs7woPglTGNeffXVCS/HDV+3bt3APqZbn0QF4SF3+yD15ffu3WswUImEcQP7IfcKA6ZusfnMm/bt2xfTRUHryttFs69p0qSJ1TLzilBgaCepIVsMWRjY48ePG/zBRibMz2OMASPj3sGznTt3JvzVHzVqlMEApTc99NBDVrciTIqiPn7lYTqxe/fuzlcYB/DOogSpp1cYEk37gmeBAgWcLN977z1z//33+xZBYfAnT2EIckdmos0///xjLYZyT+n17dvX9OnTx7cWGETDgJpXTLD2AV2JdFPY+viV16lTJzNmzBjnKwhQKsktDBiD2bp1q282XmFI1uqiMFAYUrkXs+QaNKPdTWSMymN03i/5zVDAbvLkyaZRo0aR1D9MffwKbNiwobWWAAlThdgXkkpyC0Oy9SBhhKFx48YWKyT3eEYq9TuZrmGLIYOjiWW4mBKzfyUxwJdsObRdnYsuusiZZ3cvi3ZX129Ng/09WgsYiffux8jI+iRCiW6Ee3WitPIzUT4Uhgy+WV3ZUxgymDUeAuxTsJM0Im/blSpVylns4139aNt4V0F6XUFLwztVmZH1SYTytddei9khilkD7ChNlLDQacqUKdbXsLPXFlAYMvhmpTBkHmCU5J4rDzIlhsE5bBKyk3f1Iz7HtJp7sxH63KtWrbKmMN1vhho3bpxBK8WdMqI+yYguWLDAVK9e3THBkuzHHnss4SW33HKLs8ejWbNmZuLEiZYthSHz7lu2GDKBtbsfi+Kw9qB8+fIJS8ar3YYNG+Z8/+abb5qWLVs6/8fKRGwicu+0tHdsegUDF2FvhnsXZtT1kRD++eefVpcG9UZCXbCk+7TTTou7dNGiRdbKTTthtSL2V1AYJMrRfk9hiJanb27YvOTeAYn+/0cffRTzAOBCPEDYVdi/f38nH9hiNSAG7ezUsWNHazegnbCwyb2AxyssaFlgW/Ipp5xiXRJ1fYIgxLLsDh06OKaYecGApLtltG7dOnPnnXfGCJ57qpYthiCko7GhMETDUczF+yuNCzB2gN2DeDs0HgA0ub0be7yr+7ybrCAc6Dqcf/75Th0wwIgl0u4uxUsvveTs8IRhVPURHT9hgLENLMZy1wliByFAC2Ljxo1xOyXtbdN2GRSGoLTTt6MwpM8wUA5o9mP5LrYSB014b8EzzzzjmGNFILoQbvFItHjH2yRHJt9++6259tprrfyiqE9QP2w7DDpiP0IQBvfdd5+1ItG9DZrCEJZ46vYUhtTZhb4Si4UGDhxonn322aTXVqtWzeB9CvZDbBtjwA77J+yUbH0DbLxLnJEvNhjZKd36hAZwYvcj3hOBQVG/hNYDljBjDYb3xSnuFZSJpnCRJ7Zwn3vuuU726LZhW7ZfevDBB53BzSADw6n4nBOvoTBkQdTwi499DviDtQZYvYj9AHgorrjiCut1bpn5wpCsqA/WYGBnJHZZopuB1+TDf3Q3kr2vIgvCpbJICoPKsNNpEkhOgMLAO4QESCCOAIWBNwUJkACFgfcACZCATIAtBpkRLUhAHQEKg7qQ02ESkAlQGGRGtCABdQQoDOpCTodJQCZAYZAZ0YIE1BGgMKgLOR0mAZkAhUFmRAsSUEeAwqAu5HSYBGQCFAaZES1IQB0BCoO6kNNhEpAJUBhkRrQgAXUEKAzqQk6HSUAmQGGQGdGCBNQRoDCoCzkdJgGZAIVBZkQLElBHgMKgLuR0mARkAhQGmREtSEAdAQqDupDTYRKQCVAYZEaRWBw9etQ6KGbPnj3O6+LdZx+ELeTIkSNm37591rFzOIXKewZDmPyizMtbLs7QmDdvnlgd+IGTqXDG5Y033mhwhF3+/PnF6/Dq+Vq1apljx46JtjA488wzTcmSJa2DhnFGJl5Xnyy1atXKOvsTCa+3dx8FGKjAHGpEYcjgwK1du9aMGjXK4MQo+1BXu0g8CKVLlzZPPPFE3DmWftXC9aNHjzY4Vt591Bts8SC1bdvW3HvvvYFEIsq8kiGsX7++mTFjRkqUcTBN3759Tb58+RJe/9dff1kPe6oJ53zitK9EZbhPBocw2CKRank55ToKQwZGasSIEaZr166BSsApUwMGDEh4k+NwlptuuilOXLyZQxhwOnayhynKvCTn0hEG5A3xXLhwofUr75fSFQbkiWP/cGye3+nbFAaTS4oxvg9kdCKj4/j7+HHrL3VpypQpBucvhkn4xUdrwJt+/vlnU6lSpbgDbxPljdbDJ5984ttyiDKvIL55hWHkyJFxp2zhqLz169eb1atX+55rCXFYtmyZdUqXN3mFAYf5tm/f3rdqaCXt2rXLYrNhw4YYm6eeeirmlHH7SwpDsGeewhDgacBx9jiF2p3wS965c2dTrlw563TrX375xTry3n2cPey//PJLSwTcqV69embmzJnORxUqVLC6H1WrVjUHDx60jrh/+umnY46PR5ejY8eOcbWNMq8AKIxXGHAcX7Lj9zBmgLMr0YVwJ5w9iTMoJWFo2bKl1WJKlvBj1bNnT/Piiy/GmO3evdtqobgThYHCEOQ+D2TzzjvvmGbNmjm2OOUaLQi/Mxlxc/bo0cOxxbHw+EWzE5q4EBM7oZ+7fPlyc8EFF8TUZcWKFdagnZ38Dn2NMq9AIIwJLQx2vhBCiJg7wUeIojt5WwxBhMG+vnHjxmby5MlOduiyQGwpDMYt3oEaA4GMToBV25Vw/yqj5YDma6IBMsxW4FfJHkyEPVoBdmrTpo0ZP3688/+VK1ea8uXL+z6X/fv3twbS7IQDYzG4mRF5ZbQwIP+hQ4eabt26OUX5ne6djjBghgGzDnYaM2aM6dChA4UBYwa5nEc90DMfyEi7MLibny1atBCnuHBzuqfBtm7dagoXLmxhLFKkiNNFwGf4LlHCDIhbCLz95ijzygxh2L9/vylQoEBMUevWrTOlSpVyPktHGDCNWrNmTScvdMcwvcoWA4Uh6P0dys7dhx40aJDVn02WMPaAMQE7ofVQrFgxs3nzZutvO2HmAr+iiRLm8jH3b0+LVq5c2SxdutQyjzKvMDDCjjF48+7evbsZMmSI8zG6ZA0bNoxEGDCF3LRpUyevN954I6YFgS84xsAxhjD3e9KHE4N+GGlHat26tbn11luT5o1fefzaI6ErceDAAWtGYerUqaZRo0bOtbNnzzZoTidLdevWNbNmzbJM3C2MKPMKAypdYZgzZ46pXbu2U+TgwYNjxmRSbTFgABIDwu5BXb+BXwoDhSHM/R6Zrbefi9V4mGVAQp+3U6dOTlnJxhdsI0zVuac87eniKPMK43y6wuDtHrVr186MHTs2rRYDxnCwZsQ9KwFB3rlzp8mbN2+MexQGCkOY+z0S248//tjUqVMnJq+5c+eaGjVqWJ8NHDjQYJzATps2bTLFixdPWnavXr0MflXthIcAN32UeYVxPl1h+O2332JmYKpVq2bmz5+fUBiwWAkzE35p7969Bus43DMRth2mOP2uozBQGMLc72nZYp0D5undfWdkiC6Ie6wBI/LuMQXc2N7BOG9FIAoQBzvhQbjsssus0f2o8grjfLrCgBaPex9I2bJlrYVQdopi5SOmiNH9wn4Nb6IwUBjC3O8p206fPt088sgjMYuRkBn6uxMnToxpykIo3AugsNkpT548ScseNmyYwfp/O9kzHFHmFcb5dIUB07nu9R/eKct0hQHijD0ZiTahURgoDGHu99C26CtDELCIxpuGDx9u7anwrgjE9Bn6wnbCoGSyPRCwe/75561VkXY6dOiQtYYiyrzCOJ+uMGANSMGCBZ0ipTEGrFzEOE2iZO+uxN6LMmXKWNPByRKFgcIQ5n4PbIvZiX79+lnLfL0JrQT8whctWtQ3P+zK7NKlS9yvf7LCIQoQBzvZg49R5hXY+TRWPtplLFmyJGZWB12wPn36OFVIdVYiqA8UBgpD0HslsB0GC7HsFkuR3QkbfdDfr169etK8vBux1qxZY3BtstS8eXMzadIky8Q9XRllXoEBRCAMEFX3volp06ZZy6ztRGEIE43gtlz5GJxVKMvt27cbDJTh5SzuhKlErG3wG+jyFrB48eKYtfsTJkwwePCTpYoVKxpMayK5pz6jzCsMiHS6EliwhVkG905IDNy6pxQpDGGiEdyWwhCcVWDLw4cPmypVqsS0FLD0dty4cQm7DX6Z79ixwxQqVMj5Cuv4sR4hUfLu6nSvuowyr8Ag0mwxeBdlYRv7Bx98EFM8hSFMNILbUhiCswpsiZkE95bnBg0aWDd0kFaCtxB0NxYsWGB9jIG1LVu2+L5QBN9L3YUo8woKI9UWA7phaHG533rlt/KTwhA0EuHsKAzheAWyxpuWsDUaCU1hNO1Tff0Yug/YiGUnvx2A+A4zFth2bTe7Mb4AEXHPdESZVyAQKbYYsL0aYrpt2zanmCjfxxC07rDj4CMHH8PcLwltsaAI70ywE2YVMKYQNGE+HQOM9gONB977UlT36kjki4VPeCGqe5ATU6CYHnWnKPMK6o+3xbBq1aq4NQNYq4CuDjZ6LVq0yPcdkXixzaWXXhpXLFsMQSMRzo4thnC8RGu/F4yIF3kM8PZntxjgIcfOSnfCar0SJUpYS3ztTVP292ilYAYjd+7ccUVHmVcQv9J95yOWc6MrlegdFBSGIFEIb0NhCM8s6RXel4ukkr1XGPA6tCZNmviu8ffmjy4EHiSIhl+KMq8gvqUjDJhVwVZo99Zzb5kUhiBRCG9DYQjPLOkV3k1MqWTvt8IRDzTeEdm7d++EWeIVcljI5J7JSCQOUeUl+ed9fVoye4gaXkmHrhReXiOt2UBeWCZ++umnO9kmeqGuVM9E3+OlMHhRLZLf6/JSzTe7X0dhyO4R8tQPo/QYnd+4caO1TRhLpPGLincVSoeneF2NMq8chpHVFQhQGHiLkAAJxBGgMPCmIAESoDDwHiABEpAJsMUgM6IFCagjQGFQF3I6TAIyAQqDzIgWJKCOAIVBXcjpMAnIBCgMMiNakIA6AhQGdSGnwyQgE6AwyIxoQQLqCFAY1IWcDpOATIDCIDOiBQmoI0BhUBdyOkwCMgEKg8yIFiSgjgCFQV3I6TAJyAQoDDIjWpCAOgIUBnUhp8MkIBOgMMiMaEEC6ghQGNSFnA6TgEyAwiAzogUJqCNAYVAXcjpMAjIBCoPMiBYkoI4AhUFdyOkwCcgEKAwyI1qQgDoCFAZ1IafDJCAToDDIjGhBAuoIUBjUhZwOk4BMgMIgM6IFCagjQGFQF3I6TAIyAQqDzIgWJKCOAIVBXcjpMAnIBCgMMiNakIA6AhQGdSGnwyQgE6AwyIxoQQLqCFAY1IWcDpOATIDCIDOiBQmoI0BhUBdyOkwCMgEKg8yIFiSgjgCFQV3I6TAJyAQoDDIjWpCAOgIUBnUhp8MkIBOgMMiMaEEC6ghQGNSFnA6TgEyAwiAzogUJqCNAYVAXcjpMAjIBCoPMiBYkoI4AhUFdyOkwCcgEKAwyI1qQgDoCFAZ1IafDJCAToDDIjGhBAuoIUBjUhZwOk4BMgMIgM6IFCagjQGFQF3I6TAIyAQqDzIgWJKCOAIVBXcjpMAnIBCgMMiNakIA6AhQGdSGnwyQgE6AwyIxoQQLqCFAY1IWcDpOATIDCIDOiBQmoI0BhUBdyOkwCMgEKg8yIFiSgjgCFQV3I6TAJyAQoDDIjWpCAOgIUBnUhp8MkIBOgMMiMaEEC6ghQGNSFnA6TgEyAwiAzogUJqCNAYVAXcjpMAjIBCoPMiBYkoI4AhUFdyOkwCcgEKAwyI1qQgDoCFAZ1IafDJCAToDDIjGhBAuoIUBjUhZwOk4BMgMIgM6IFCagjQGFQF3I6TAIyAQqDzIgWJKCOAIVBXcjpMAnIBCgMMiNakIA6AhQGdSGnwyQgE6AwyIxoQQLqCFAY1IWcDpOATIDCIDOiBQmoI0BhUBdyOkwCMgEKg8yIFiSgjgCFQV3I6TAJyAQyXBjkKtCCBEggGxPIFaRugYxOZHQ8SIa0IQESyNYEAj3zgYyytZusHAmQQOQEKAyRI2WGJJDzCVAYcn4M6QEJRE6AwhA5UmZIAjmfAIUh58eQHpBA5AQoDJEjZYYkkPMJUBhyfgzpAQlEToDCEDlSZkgCOZ8AhSHnx5AekEDkBCgMkSNlhiSQ8wn8H/nwCejiWGLUAAAAAElFTkSuQmCC" width="121" height="121" style="max-width:100%;" />`

But GitHub doesn't render it (and I don't want data encoded into `data:image/png;base64` anyway).

**Comment by ashrafteleb** [comment]
Unfortunately, it's a GitHub issue, they only add the width with 144 DPI. Export from draw.io with custom DPI of 144 and it will be recognized by GitHub similar to the following image
<img width="149" alt="Untitled Diagram (16)" src="https://user-images.githubusercontent.com/24944765/134520587-7e8bb9c6-a9c3-46bc-b87a-a95d413dc036.png">

**Comment by borekb** [comment]
@ashrafteleb Aha! That's a great tip, thanks!
