### ISSUE TITLE
unable to add svg icons - they are all broken

### ISSUE THREAD

**Issue by alexgman** [jgraph/drawio#538]
[Compute Service Color.zip](https://github.com/jgraph/drawio/files/3556364/Compute.Service.Color.zip)

I've attempted to add svg icons  by simply dragging a file from my desktop. (See attachment above):

![image](https://user-images.githubusercontent.com/4227695/63532993-816b1b80-c4d1-11e9-9c20-3a82e786175f.png)

I just get an empty image:

![image](https://user-images.githubusercontent.com/4227695/63533032-9a73cc80-c4d1-11e9-834c-b2b4f9be802e.png)

I've also attempted to create a new library:

![image](https://user-images.githubusercontent.com/4227695/63533089-b7a89b00-c4d1-11e9-9f02-7b904bb5bce2.png)

And unable to do that either:

![image](https://user-images.githubusercontent.com/4227695/63533153-da3ab400-c4d1-11e9-923c-481fe1136697.png)

I've also attempted to do this by providing URL of the svg:

![image](https://user-images.githubusercontent.com/4227695/63533228-f4749200-c4d1-11e9-8344-9eedf957f0f8.png)

And got this:

![image](https://user-images.githubusercontent.com/4227695/63533257-03f3db00-c4d2-11e9-8e38-844c194a8e83.png)

Yet, the svg is indeed publicly accessible:

![image](https://user-images.githubusercontent.com/4227695/63533288-15d57e00-c4d2-11e9-9ed9-c7d313b4e6ac.png)

**What am I doing wrong? How do we add svgs?**

**Comment by alderg** [comment]
What's the URL of the SVG file that you tried? This does not seem to work: https://tiffconverterstordev.blob.core.windows.net/public/Batch%20AI.svg

**Comment by alexgman** [comment]
I've attempted several times uploading svg's directly from my local
machine; and while the uploads showed succesfully completed, the images
were all showing as broken.

**Comment by davidjgraph** [comment]
Could you attach an example SVG that fails? What browser are you using?

**Comment by alexgman** [comment]
I've attached 2 samples.

I'm using chrome. Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by davidjgraph** [comment]
I meant attach the actual SVG files to this issue.

**Comment by alexgman** [comment]
> I meant attach the actual SVG files to this issue.

Sorry about that, I've just attached them zipped up. https://github.com/jgraph/drawio/files/3556364/Compute.Service.Color.zip

**Comment by alderg** [comment]
Replace xmlns:svg="http://www.w3.org/2000/svg" with xmlns="http://www.w3.org/2000/svg" in the SVG.
