### ISSUE TITLE
[Feature Request] Round images

### ISSUE THREAD

**Issue by flaimo** [jgraph/drawio#541]
I don't know if it is possible, but I would like to add an image as a background to a circle shape or a shape with rounded corners in a non-destructive way, just as I can with a rectangular shape. The image shouldn't bleed outside of the shape border.

![Screenshot 2019-08-30 at 12 05 50](https://user-images.githubusercontent.com/416323/64012756-8f96e880-cb1e-11e9-9e48-b4ce8f4c7c86.png)

**Comment by alderg** [comment]
For images with a data URI (ie those you drop into the diagram from your local file system), you can right click > Edit Image > Crop and tick "Circle".

**Comment by flaimo** [comment]
I know I can do that, but I need it to work non-destructive via URL. Also I cannot set a border color for images resaved with the crop to circle functionality.
