### ISSUE TITLE
Offline/Local usage in Chromium/Chrome is not possible.

### ISSUE THREAD

**Issue by RobertZenz** [jgraph/drawio#544]
Using draw.io offline/local with Chromium/Chrome is not possible, because it fails to load the local resources.

The basic idea is to have draw.io as some sort of app lingering around the local filesystem, which would make it possible to share it easily with others in the team without requiring an internet connection. For that I've downloaded the source tree and pointed Chrome/Chromium at it. First, Chromium/Chrome requires the parameter `--allow-file-access-from-file`, otherwise any request to local files will be denied. Second, draw.io fails to initialize because it *believes* that the resource files could not be loaded.

To be exact, there are [a few places inside App.js which are concerned with loading resources](https://github.com/jgraph/drawio/blob/92562fc3e957579157757fd7464515a6dff56b1d/src/main/webapp/js/diagramly/App.js#L4617), these are checking whether the return code was somewhere in the 200 range. However, Chromium/Chrome returns 0 for accessing local files, making draw.io believe that the resources have not loaded successfully, even though they did.

**Comment by alderg** [comment]
Have you tried app.draw.io and waited for the cache to be populated?

**Comment by RobertZenz** [comment]
No, it seems unrelated but might actually be a workaround. I've fixed it locally by amending `req.getStatus() == 0 ||` to the given line.

The real question would be "would you like to support such a usecase?", in which case someone would have to look at how Chrome/Chromium is behaving in that case and whether checking for a zero return code would be a viable solution.

**Comment by alderg** [comment]
https://app.draw.io uses the offline=0 URL parameter to disable all XHR. a more modern approach is our desktop app at https://get.draw.io

**Comment by RobertZenz** [comment]
Yes, I'm aware of these, and it's great that these exist. My use-case was slightly different, though, as stated.

**Comment by davidjgraph** [comment]
It's a very boundary usecase and not something that should go in the core project. However, if the issue is that of us checking for 2xx return codes, it wouldn't hurt to abstract the check out into a function that you can override. You're welcome to submit a PR along those lines.

**Comment by RobertZenz** [comment]
I could do that, might take some time, though.
