### ISSUE TITLE
Missing text after PNG export

### ISSUE THREAD

**Issue by agaget** [jgraph/drawio#546]
When we export to PNG the following scheme, it misses some text. We have Reproduced the bug in different computer.

[TypicalNeutronShape.txt](https://github.com/jgraph/drawio/files/3583665/TypicalNeutronShape.txt)
(it's an xml file renamed to txt, github can't handle xml... don't know why)
![TypicalNeutronShape-5](https://user-images.githubusercontent.com/25428659/64424412-4a882e80-d0a9-11e9-9f33-06f78efb7303.png)

On Windows 10 / firefox

File > Export As > PNG  > default option (try different ones, no difference)

**Comment by davidjgraph** [comment]
Exported following what process on what browser and what operating system?

**Comment by agaget** [comment]
I was just updating the issue to add this info, you have been to quick to answer :)

**Comment by ghart-IDM** [comment]
I am experiencing the same problem. Though for me it is specifically things that are mathematical typesetting. At the beginning of this month I got this image:
![snowSIRsimple](https://user-images.githubusercontent.com/49955673/69463726-46c38a00-0d31-11ea-87d1-d1ebed34a00b.png)
But now when I export I get this:
![snowSIRsimple](https://user-images.githubusercontent.com/49955673/69463740-517e1f00-0d31-11ea-8e8d-df5749fe1b7a.png)

Here is the XML exported at the time of the second image:

[snowSIRsimple.txt](https://github.com/jgraph/drawio/files/3881598/snowSIRsimple.txt)


File > Export As > PNG > default option (as well as other options and File > Export As > Advanced

I am using Firefox and Windows 10.

**Comment by alderg** [comment]
Fixed in 12.3.0. Thanks for the report!
