### ISSUE TITLE
Custom Google Drive App

### ISSUE THREAD

**Issue by pirhoo** [jgraph/drawio#550]
G'day,

First, thanks for this amazing tool. It's really neat and intuitive.

My organization has very high confidentiality needs (notably for source protection) so we would like to use Draw.io with our own Google app ID. It a quick & dirty solution but I tried to change values in the minfied code:

```bash
sed -i 's/this.appId="420247213240"/this.appId="{{ google_app_id }}"/g' js/app.min.js
sed -i 's/this.clientId="420247213240-hnbju1pt13seqrc1hhd5htpotk4g9q7u.apps.googleusercontent.com"/this.clientId="{{ google_client_id }}"/g' js/app.min.js
sed -i 's/DriveClient.prototype.newAppHostname="www.draw.io"/DriveClient.prototype.newAppHostname="{{ google_app_hostname }}"/g' js/app.min.js
```

So now, when I click on the "Google Drive" connect button, it's simply redirect me to the hostname I set in `ǹewAppHostname` (it was previously "www.draw.io"). Any idea how I can do that correctly?

Best,

Pierre

**Comment by pirhoo** [comment]
BTW, I'm happy to suggest this as a pull request if you think it's a good solution:

https://github.com/ICIJ/drawio/commit/aad484d34015c56fd9d9508aba9bcfa497c21ee2#diff-49fc01f0eabbb4555eda11422824daacR294-R308

**Comment by davidjgraph** [comment]
We're actually planning to create docker images with the various variables as environment variables. But pending that:

We'll add global vars to set the app and client ID. We had a PR to add a config.js file with global var overrides, I think that makes sense.

https://github.com/jgraph/drawio/blob/master/src/main/webapp/js/diagramly/DriveClient.js#L26

420... isn't actually the app you want to replace. 420 is the legacy app and when that mime is used, we do various things to translate the old format into the new and redirect the app, you don't want this.

I need to recreate the steps from scratch, if you can help me fill in https://gist.github.com/davidjgraph/9587fdcc44f5a9bc8cd4824d1ea68e3b I'll need to test a custom project to get you the exact process.

The Google UI has changed at the point I've gotten to:

<img width="488" alt="Screenshot 2019-09-10 at 11 53 55" src="https://user-images.githubusercontent.com/1761087/64608145-eecbe700-d3c1-11e9-8a73-b33c9be2be82.png">

Is it an OAuthClientID you picked?

**Comment by pirhoo** [comment]
A config file would be just perfect. Are you suggesting that I have to replace the appId `671128082532` instead?

I picked the OAuth client ID indeed. I didn't know what to choose as redirect URL on this screen:

![Capture d’écran de 2019-09-10 15-24-02](https://user-images.githubusercontent.com/471176/64617777-53496f00-d3df-11e9-87c4-cd2aaa445a44.png)

Thanks for your precious help!

**Comment by davidjgraph** [comment]
671, yes, but we need other changes, too. You don't need an authorized redirect.

What scopes did you enter for the OAuth constent screen? Was it held for manual approval or agreed straight-away?

**Comment by pirhoo** [comment]
I didn't change any of the default values:

![Capture d’écran de 2019-09-10 16-52-44](https://user-images.githubusercontent.com/471176/64625137-f4d6bd80-d3eb-11e9-99c8-e93ee06e1b86.png)

**Comment by davidjgraph** [comment]
You'll need auth/drive.file and auth/drive.install in the scopes, otherwise it won't work. Add those and see if it goes for manual review.

**Comment by pirhoo** [comment]
I got `auth/drive/file` but not `auth/drive.install`. Could it lives under another name?

Thanks!

**Comment by davidjgraph** [comment]
You might have to manually enter it:

https://www.googleapis.com/auth/drive.file
https://www.googleapis.com/auth/drive.install

**Comment by pirhoo** [comment]
I added the scopes:

![Capture d’écran de 2019-09-10 17-33-23](https://user-images.githubusercontent.com/471176/64628322-7715b080-d3f1-11e9-9501-23d960a09406.png)

Yet it's still redirecting me to the site homepage when clicking on the Google Drive logo. No manual approval appears.

**Comment by davidjgraph** [comment]
It won't work yet, this will not be a trivial process. Back to the OAuth Constent Screen, is "submit for verification" button active at the bottom of it? I'm not sure how you have this verified when the drive.file is present without a submission.

<img width="497" alt="Screenshot 2019-09-10 at 17 07 22" src="https://user-images.githubusercontent.com/1761087/64630663-7a0ea200-d3ed-11e9-85aa-896788dd6446.png">

What does the verification status at the top of the page show?

**Comment by davidjgraph** [comment]
Another question here is how are you adding security by creating another project ID? Is it that you think we have some kind of access to files stored with our app IDs? We cannot access them unless we could login as the actual user.

**Comment by pirhoo** [comment]
This button doesn't show since I'm not using one of the conditions (the application type is now "internal"):

> To protect you and your users, your consent screen and application may need to be verified by Google. Verification is required if your app is marked as Public and at least one of the following is true:
> 
>     Your app uses a sensitive and/or restricted scope
>     Your app displays an icon on its OAuth consent screen
>     Your app has a large number of authorized domains
>
>    You have made changes to a previously-verified OAuth consent screen

To answer your question, the documents we host on Google Drive are under a special protection due to the sensitivity of our work. This is mostly intended to protect our sources and therefore, press freedom. Unfortunately this extra-protection is not applied to documents shared with third parties (people or applications).

**Comment by davidjgraph** [comment]
ok, how did you define it as internal?

**Comment by pirhoo** [comment]
At the top of the " OAuth consent screen" page:

![Capture d’écran de 2019-09-10 18-19-15](https://user-images.githubusercontent.com/471176/64631550-a16a6c80-d3f7-11e9-9457-c30dcc82fe4f.png)

**Comment by davidjgraph** [comment]
OK, I didn't create the project using my GSuite account so I never got that option, good to know.

**Comment by davidjgraph** [comment]
You understand that drive.file means the draw.io application can only access Google Drive files created by the app (with that app ID), or files a user specifically opens from drive.google.com using draw.io? So, your concern is about sensitive data in the diagrams?

> To answer your question, the documents we host on Google Drive are under a special protection due to the sensitivity of our work. This is mostly intended to protect our sources and therefore, press freedom. Unfortunately this extra-protection is not applied to documents shared with third parties (people or applications).

**Comment by pirhoo** [comment]
Yes, I understand Draw.io won't be able to access our files except the one created with by the app. But if we do so those documents won't be protected as mentioned.

**Comment by davidjgraph** [comment]
Yes, I think the issue here is one of the logistics of actually getting a custom hosted version to access files with our project ID, rather than the use of the draw.io project ID increasing the possible attack surface. I don't think creating a custom project actually makes it more secure, it's just you'd need to add your domain to our project and neither of us want to do that :).

I just wanted to work through the exact security implications.

**Comment by davidjgraph** [comment]
Actually, it's not that bad. Replace:

```
	else if (this.ui.isDriveDomain())
	{
		this.appId = '98980727437';
		this.clientId = '98980727437-lr6plj68m1bgk3qhar12is01rumcohsb.apps.googleusercontent.com';
	}
	else
	{
		// Uses a different mime-type and realtime model than the drive domain
		// because realtime models for different app IDs are not compatible
		this.appId = '420247213240';
		this.clientId = '420247213240-hnbju1pt13seqrc1hhd5htpotk4g9q7u.apps.googleusercontent.com';
		this.mimeType = 'application/vnd.jgraph.mxfile.rtlegacy';
	}
```

with

```
	else
	{
		this.appId = 'YourAppId';
		this.clientId = 'YourClientId';
	}
```

And it works. Or override

```
App.prototype.isDriveDomain = function()
{
	return true;
//	return urlParams['drive'] != '0' &&
//		(window.location.hostname == 'test.draw.io' ||
//		window.location.hostname == 'cdn.draw.io' ||
//		window.location.hostname == 'www.draw.io' ||
//		window.location.hostname == 'drive.draw.io' ||
//		window.location.hostname == 'jgraph.github.io');
};

```

We'll add the config.js file for overrides, changing isDriveDomain is probably easier.

**Comment by pirhoo** [comment]
Fantastic, it worked! I used a custom Dockerfile to edit the minified file:

```dockerfile
FROM fjudith/draw.io:{{ draw_docker_version }}

# Update the configuration
RUN cd $CATALINA_HOME/webapps/draw && \
    sed -i 's/this.appId="671128082532"/this.appId="{{ google_app_id }}"/g' js/app.min.js && \
    sed -i 's/this.clientId="671128082532.apps.googleusercontent.com"/this.clientId="{{ google_client_id }}"/g' js/app.min.js && \
    sed -i 's/DriveClient.prototype.newAppHostname="www.draw.io"/DriveClient.prototype.newAppHostname="{{ google_app_hostname }}"/g' js/app.min.js && \
    sed -i 's/.prototype.isDriveDomain=function(){return/.prototype.isDriveDomain=function(){return true || /g' js/app.min.js
```

Thanks a million, I'll buy you a beer if I happen to be in Northampton ;)

**Comment by davidjgraph** [comment]
Oh please, let's find somewhere better than Northampton 8-).

**Comment by davidjgraph** [comment]
We've added pre and post config files to 11.2.9, https://github.com/jgraph/drawio/tree/master/src/main/webapp/js

You can set:

window.DRAWIO_GOOGLE_VIEWER_APP_ID and
window.DRAWIO_GOOGLE_VIEWER_CLIENT_ID

in the pre config and get the same result now.

**Comment by pirhoo** [comment]
Brilliant! Will test soon, thanks!
