### ISSUE TITLE
Text jumping at different zoom levels

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#555]
A user reported "I have noticed some odd behaviour whilst changing zoom levels, text boxes can change locations or disappear completely.  Please see the screenshots below showing the same page viewed at different zoom levels for an example."

I tested his file using draw.io desktop and online and text really changes positions when zoomed in/out. Chrome Version 74.0.3729.131 (Official Build) (64-bit) and Incognito.

Ticket 34760 has a reproduction video also.

[Draw.IO.bug.zip](https://github.com/jgraph/drawio/files/3604725/Draw.IO.bug.zip)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
