### ISSUE TITLE
License of included graphics.

### ISSUE THREAD

**Issue by RobertZenz** [jgraph/drawio#557]
I failed to find a dedicated license for the included graphics, so what is the license of the included graphics (f.e. the Office icon pack)?

**Comment by RobertZenz** [comment]
The reason I ask is as that is important to know for all created drawings. Because any drawing that uses these icons has to adhere to the license of them.

**Comment by davidjgraph** [comment]
We perform due diligence on the license to all shape sets that we use and derive from to check that adding them to a diagram is:

- Legally allowed for all cases
- Does not require attribution

**Comment by RobertZenz** [comment]
Might be worthwhile to mention that in the README or LICENSE file, knowing an exact source and license would be nice though. For example, that doesn't answer whether derivations for commercial usage would be allowed.
