### ISSUE TITLE
[question]  What is the purpose of the electron.js file in docker-drawio?

### ISSUE THREAD

**Issue by hoon111465** [jgraph/drawio#562]
I tryed git clone https://github.com/fjudith/docker-draw.io.git

There was a question while checking the source code.

In my opinion, I'm accessing index.html directly from Tomcat.

Then electron.js seems to run without it.

So where does the backend work? 

Doesn't it exist?

If I want to write backend code, do I have to create a new file?

**Comment by ashrafteleb** [comment]
draw.io is mostly client-side and the project is packaged as a war file that run in any servlet container (e.g., Tomcat)

electron.js is related to draw.io Desktop project
