### ISSUE TITLE
Allow to disable XML compression.

### ISSUE THREAD

**Issue by RobertZenz** [jgraph/drawio#563]
As I understood it, the saved XML files are partially compressed. It would be nice if we would be able to get (optional) non-compressed XML files, as that would make it nicer to store in source-control systems.

**Comment by alderg** [comment]
See https://twitter.com/drawio/status/1152165340891287552

**Comment by RobertZenz** [comment]
Wait...I need to save the file, edit it to add the `uncompressed` attribute, then reload it and then save it again to get it uncompressed?

**Comment by RobertZenz** [comment]
This has actually been solved with 11.3.0, as it introduced a global switch to disable the XML compression, which is good enough for me.

**Comment by cntsw** [comment]
> This has actually been solved with 11.3.0, as it introduced a global switch to disable the XML compression, which is good enough for me.

How to configure the `global switch`?

**Comment by RobertZenz** [comment]
Through the [global draw.io configuration (when self-hosted)](https://desk.draw.io/support/solutions/articles/16000058316-how-to-configure-draw-io-in-confluence-quip-and-embed-mode-). For the draw.io website you're out of luck, I guess.

**Comment by RobertZenz** [comment]
@cntsw see [#650](https://github.com/jgraph/drawio/issues/650#issuecomment-555548411).

**Comment by RobertZenz** [comment]
I'm a little bit confused why this got reopened, you fixed it.

**Comment by davidjgraph** [comment]
For per diagram setting in the UI

**Comment by RobertZenz** [comment]
Ah, I see. That would be nice, yes.

**Comment by alderg** [comment]
This will be added in the next release.

**Comment by davidjgraph** [comment]
compression will be off by default in next release.
