### ISSUE TITLE
"Open" only asks on new diagrams whether to use this window or not.

### ISSUE THREAD

**Issue by RobertZenz** [jgraph/drawio#568]
The "Open" menu action seems to have two modes of operation:

 1. If the current diagram is new, it asks whether it should open the file in this window or a new one.
 2. If the current diagram is not new (saved, loaded), it just opens the file in a new window.

I believe that it would be better to always ask whether this window should be reused, as one does not always want to open a new tab.

**Comment by alderg** [comment]
Thanks for your feedback. This will be changed in the next release.
