### ISSUE TITLE
Add kubernetes shapes

### ISSUE THREAD

**Issue by zopanix** [jgraph/drawio#569]
Hey,

The kubernetes community has a set of icons for different kubernetes resources. It would be nice to have them natively in draw.io

https://github.com/kubernetes/community/tree/master/icons

**Comment by CoolZeroNL** [comment]
I made a stencil that load the icons in the sidebar, u can use it as a plugin.

Plugin URL for Draw.IO: 
https://yacdn.org/serve/https://raw.githubusercontent.com/CoolZeroNL/draw-io-plugins/master/%23%20Draw-io-plugin-K8-Icons/draw-io-plugin-k8-icons-v1.js?maxAge=10

**Comment by kutya** [comment]
We did our own implementation and it will be in the next release.

**Comment by JamesBewley** [comment]
The kubernetes community icons set has a much richer set of icons, the option of having them labeled or unlabelled, and a slide deck to guide their usage.

Why did you decide to do your own implementation?

How can I import the kubernetes community icons?

**Comment by davidjgraph** [comment]
Where is the source to the other implementation?

What is the license for that set?

**Comment by JamesBewley** [comment]
As per the initial request.

https://github.com/kubernetes/community/tree/master/icons

Apache-2.0 or CC-BY-4.0

**Comment by davidjgraph** [comment]
And that is in the set originally referenced?
