### ISSUE TITLE
Cisco CVD icons

### ISSUE THREAD

**Issue by katrichnikitos** [jgraph/drawio#573]
Hello,

The currently used in draw.io Cisco shapes are outdated. It would be great to add new icons from Cisco Validated Design library. The icons are published in Power Point file(https://www.cisco.com/c/dam/en/us/td/docs/solutions/CVD/overview/Unmaintained-Desgin-Icons.zip), but i believe they are vector, so can be properly used.
Anyone have ideas how to do that?

**Comment by kutya** [comment]
We added these to the main project. They should be in the next release.

**Comment by katrichnikitos** [comment]
Many thanks!

**Comment by gigiogigo** [comment]
Hello, the online version I believe includes these icons as Cisco 19, however, the offline version of windows doesn't, is there anyway to fix this?

Thanks!

**Comment by davidjgraph** [comment]
Wait for the next desktop release.
