### ISSUE TITLE
Redis Icon and exporting to SVG

### ISSUE THREAD

**Issue by tzulberti** [jgraph/drawio#575]
When using the Redis Icon (`Cache_Redis_Product.svg`), and exporting the file into a SVG, it won't show the Redis Icon, instead it will show like a broken image

**Comment by tzulberti** [comment]
After testing some more, this also happens when exporting any icon on which the definition is an image. For example, with the firewall icon.

I attach a drawio file used an example to show this issue:

[issue_575.txt](https://github.com/jgraph/drawio/files/3672366/issue_575.txt)

When exporting to a PNG the image is Redis and firewall images are shown correctly but not when exporting the SVG. This is the PNG:

![issue_575](https://user-images.githubusercontent.com/614799/65899916-24456e00-e38b-11e9-968f-e854c0b09b0c.png)

This is the SVG (this is actually a screenshot of the PNG because GitHub doens't allow me to upload SVG files):

![image](https://user-images.githubusercontent.com/614799/65899983-4c34d180-e38b-11e9-9117-7c9dda5b40ae.png)

**Comment by davidjgraph** [comment]
I suspect the two images are referenced in the SVG by URL so it depends on which viewer you view the SVG with, a browser will probably work.

The fix here is to convert links to images to the images themselves when exporting to SVG.
