### ISSUE TITLE
[feature] New line style: "arc"?

### ISSUE THREAD

**Issue by ebousse** [jgraph/drawio#578]
A while ago when I was using [Dia](https://gitlab.gnome.org/GNOME/dia) to draw diagrams, I got used to creating "arc" lines that exactly follow the shape of a circle − there is in fact a dedicated tool for that in Dia.

Example:
![Capture d’écran de 2019-10-01 10-50-51](https://user-images.githubusercontent.com/5868014/65960820-9d10fc80-e455-11e9-9aeb-e80e44f75bb8.png)

In draw.io one can create a "curved" line, but it's very hard to put waypoints such that this line becomes constrained to exactly follow the shape of a circle.

Could an "arc" line style be considered for draw.io?

**Comment by Ezwen** [comment]
No hope for such a feature, even in the long term?

**Comment by ebousse** [comment]
No hope for such a feature, even in the long term?
