### ISSUE TITLE
Plugins - Append Custom Menu

### ISSUE THREAD

**Issue by CoolZeroNL** [jgraph/drawio#579]
I want to append my own menu. But when i do this it wont be added. If i use one of the default menu items, the menu is been appended.

Plugin 1: Add Menu item `tools` and 2 sub items (help & quit)

```js
Draw.loadPlugin(function(ui) {
	
	// Do no use in chromeless mode
	if (ui.editor.isChromelessView())
	{
		return;
	}
	
	// Adds menu
	mxResources.parse('myHelp=Help');
	mxResources.parse('myQuit=Quit');
	

    ui.actions.addAction('myHelp', function()
    {
    	window.open('https://github.com/jgraph/drawio/issues/579');
    });

    ui.actions.addAction('myQuit', function()
    {
    	// Hides UI
    	td.style.display = 'none';
    	
    	if (menu != null)
    	{
    		menu.style.display = 'none';
    	}
    });
    
	ui.menus.put('tools', new Menu(function(menu, parent)
	{
		ui.menus.addMenuItems(menu, ['-', 'myHelp', '-', 'myQuit']);
	}));

    if (ui.menubar != null)
    {
		var menu = ui.menubar.addMenu('Tools', ui.menus.get('tools').funct);
		menu.parentNode.insertBefore(menu, menu.previousSibling.previousSibling.previousSibling);
    }

});
```

Plugin 2; Need to append the menu that is created by Plugin 1
```js
Draw.loadPlugin(function(ui)
{

	// Adds resource for action
	mxResources.parse('myItem=My New Item...');

	// Adds action
	ui.actions.addAction('myItem', function()
	{
		alert('Hello World');
	});
	
	var menu = ui.menus.get('tools');
	console.log(menu);
	if (menu != null)
	{
		var oldFunct = menu.funct;
		
		menu.funct = function(menu, parent)
		{
			oldFunct.apply(this, arguments);
				ui.menus.addMenuItems(menu, ['-', 'myItem'], parent);
		};
	}
});
```

My own menu, but the item is not been append to my menu.

[![enter image description here][1]][1]

When i using a default menu item `extras` my item will be added to the `extras` menu.

[![enter image description here][2]][2]

When i look a the debug log, i see that the `extras` menu is triggering eventListeners, and my own menu issnt.

This is the log of `extras` menu

[![enter image description here][3]][3]

This is the log of `Tools` menu

[![enter image description here][4]][4]

How do i add or trigger a eventListeners to append my ow menu `Tools` ??

  [1]: https://i.stack.imgur.com/K1bcg.png

  [2]: https://i.stack.imgur.com/0ldCI.png

  [3]: https://i.stack.imgur.com/WxYIr.png

  [4]: https://i.stack.imgur.com/t4CFa.png

**Comment by alderg** [comment]
The loading order of the plugins is not ordered. Does the console.log(menu) output "null" in Plugin 2?

**Comment by CoolZeroNL** [comment]
@alderg I have noticed that also, the loading order of the plugin is the order that the puligins are been added to draw.io.

I have them is the right order, and menu != null in the second plugin.

![plugin-order](https://user-images.githubusercontent.com/26223744/68014988-4df6fb00-fc91-11e9-85b3-0774b659f0ae.png)

**Comment by mortenko** [comment]
any updates of issue I have almost the same problem
