### ISSUE TITLE
Publish link when drawing is in google shared drive returning some sort of authentication error

### ISSUE THREAD

**Issue by mikeditri** [jgraph/drawio#580]
When the diagram is in my drive I have no problem publishing the link however when it is on a share drive it looks like its getting stuck.

![image](https://user-images.githubusercontent.com/46933058/66050742-c4baa000-e4fb-11e9-8208-9e56eaff80df.png)
![image](https://user-images.githubusercontent.com/46933058/66050759-cab08100-e4fb-11e9-9c56-6488e53eaafe.png)
![image](https://user-images.githubusercontent.com/46933058/66050770-cf753500-e4fb-11e9-8a8f-b52ab8ce7608.png)

**Comment by mikeditri** [comment]
GET https://www.googleapis.com/drive/v2/files/13x0sewDVgF--G2yqxA3JLV1p6gahY3Z3/permissions 404

**Comment by alderg** [comment]
Fixed
