### ISSUE TITLE
Saving infinite loop when no internet connection

### ISSUE THREAD

**Issue by fusillijerry89** [jgraph/drawio#581]
If you attempt to save when having no internet connection, it gets stuck in an infinite loop that isn't solved when connecting to a working internet connection.

**Comment by davidjgraph** [comment]
What browser/version and where are you saving to, which storage?

**Comment by fusillijerry89** [comment]
Chrome 77. 

How do I tell which storage I am saving to? It must be default.

**Comment by davidjgraph** [comment]
It's whichever you selected in the opening splash screen, but default no storage is selected.

**Comment by fusillijerry89** [comment]
Using Google Drive.

This issue is happening more and more frequently, the bigger my file gets.

**Comment by davidjgraph** [comment]
I'd suggest to try the [desktop version](https://github.com/jgraph/drawio-desktop/releases) and autosave to a locally sync'ed version of your Google Drive.
