### ISSUE TITLE
[Feature Request] Paintbrush or Pen tool

### ISSUE THREAD

**Issue by JesseAldridge** [jgraph/drawio#582]
There are times when an idea is best expressed with a freeform paintbrush type tool. It would be great if I could create freeform vector lines with Draw.io. Maybe something along these lines: awwapp.com

**Comment by davidjgraph** [comment]
+ toolbar dropdown -> freehand

**Comment by JesseAldridge** [comment]
Oh, cool. Thanks.

**Comment by codebased** [comment]
> * toolbar dropdown -> freehand

I cannot find in mac standalone version.

**Comment by obeleh** [comment]
@codebased 

<img width="754" alt="image" src="https://user-images.githubusercontent.com/174411/157102913-679ea9a6-9eef-498c-a236-543e7eb6c2f1.png">

**Comment by obeleh** [comment]
@codebased 

<img width="754" alt="image" src="https://user-images.githubusercontent.com/174411/157103041-4cd067f1-ea04-488e-b06b-5e27835863ef.png">
