### ISSUE TITLE
Github Integration: Store draw.io files in github wiki repos not possible

### ISSUE THREAD

**Issue by fkfhain** [jgraph/drawio#586]
Right now I am able to store draw.io files in "normal" repositories on github.com but NOT in wiki-repos.

**How to reproduce:**
- Sign into your github account
- go to https://www.draw.io/
- Click "Show more" and click on "GitHub"
- Click "New Diagram"
- Create any type of a new diagram
- Acknowledge the "Authorization required" dialog 
- a "Select Folder" popup is displayed containing all repos of my github account

**Expected**
- also the wiki repos (ending with suffix .wiki) are shown
- If I click "Enter value .." I try to add something like "myOrg/myRepo.wiki" I expect that I can select the directory within my wiki repo

**Actual**
- the wiki repos do not show up in the "Select Folder"
- and even if I manually enter the wiki repo using "Enter value .."  I get an error message like below.

![Screenshot 2019-10-05 at 17 20 56](https://user-images.githubusercontent.com/2485896/66257046-b89d3f80-e794-11e9-88cb-a9d82217d60a.png)

**Comment by alderg** [comment]
This is a limitation of the GitHub JS API, please add a feature request with GitHub so that they add support for this in their API.

**Comment by fkfhain** [comment]
Thanks for the quick response. Can you explain in more detail, what kind of
limitation is that? Is there already an issue for that? Thanks.

**Comment by alderg** [comment]
It's actually not a JS API, but just the REST API v3. See https://developer.github.com/v3/. They do just not provide access to the wiki repositories via that API. I don't know if there is already an issue for that.

**Comment by BorntraegerMarc** [comment]
@fkfhain did you open a github feature request? Else I will do it :)

**Comment by alderg** [comment]
No we didn't. Please drop the link here so ppl can vote for it.

**Comment by BorntraegerMarc** [comment]
@alderg apparently we should be able to fetch wiki information. Source: https://stackoverflow.com/questions/27654854/is-it-possible-to-get-github-wiki-content-by-github-api

Could we add support for that? So at least if a user enters the wiki URL manually it could work.

> No we didn't. Please drop the link here so ppl can vote for it.

I sent a support request to github. Could you point me to the repository where I can create an issue? Then I will do it.

**Comment by alderg** [comment]
The GitHub REST API (https://developer.github.com/v3/) via api.github.com blocks access to those repos. Eg. https://www.draw.io/#Halderg%2Fsandbox.wiki%2Fmaster%2Fimages%2Fschema.png for https://github.com/alderg/sandbox/wiki returns 404 (not found).

**Comment by alderg** [comment]
As a workaround, clone the repo and use the desktop version to edit diagrams (see get.draw.io).

**Comment by BorntraegerMarc** [comment]
Got an reply from github :(

> Thanks for expressing interest in this, Marc. I'll pass this along to the team to consider, but I'm not aware of any plans to add such a feature, so it probably won't happen soon.If there's anything else you'd like to see improved -- let us know!

**Comment by alderg** [comment]
Thanks for the update. Try the workaround for now.
