### ISSUE TITLE
Problem witch sharepoint "Error fetching folder items"

### ISSUE THREAD

**Issue by matveevsereja** [jgraph/drawio#587]
Hi. I'm trying to use you extension https://appsource.microsoft.com/en-us/product/office/WA200000113?src=office&tab=Reviews
But when i try to open sharepoint folders i got error "Error fetching folder items"
Can you help please.

**Comment by alderg** [comment]
What operating system and version of Office (Mac/Windows/Online) are you using?

**Comment by matveevsereja** [comment]
> What operating system and version of Office (Mac/Windows/Online) are you using?

Windows 10 and office 365

**Comment by alderg** [comment]
Which browser/version are you using? If IE11 or MS Edge, can you check if it works with Chrome?

**Comment by matveevsereja** [comment]
> Which browser/version are you using? If IE11 or MS Edge, can you check if it works with Chrome?

I use Chrome

**Comment by alderg** [comment]
What type of Sharepoint account is it (Business/Education/Hosted etc)?

**Comment by matveevsereja** [comment]
> What type of Sharepoint account is it (Business/Education/Hosted etc)?

Business

**Comment by alderg** [comment]
Could you please go to https://www.draw.io/?mode=onedriv, click on "Sign Out" and try again?

**Comment by matveevsereja** [comment]
> Could you please go to https://www.draw.io/?mode=onedrive, click on "Sign Out" and try again?

I did it. Now i see error: The caller does not have permission to perform the action.

**Comment by davidjgraph** [comment]
You need to log in again.

**Comment by alderg** [comment]
After you click on "Sign out" you need to click "OK" in the Are you sure dialog ofc.
