### ISSUE TITLE
mxBpmnShape2.js isInverse undefined

### ISSUE THREAD

**Issue by algenty** [jgraph/drawio#588]
Hi draw.io team,

First : Great job for draw.io and mxgraph

When i try to integrate libs shapes in my project, i have an error in mxBpmnShape2.js for shapes BPNM
Line 298 : isInverse undefined.
For this to work, i need to declare var at line  213.
var isInverse = false;

Best regards
Arnaud

**Comment by davidjgraph** [comment]
I'm guessing you're using Typescript or similar that is compiling the JS for this to happen?

Why does it need to be added to 213? Isn't adding the var to 298 enough?

**Comment by algenty** [comment]
Hi david, you're right.
Line 213, it's for the beauty of the code where declarations are at beginning of the block
I use babel, the error is on the chrome console when user try to import BPNM chapes.

BR
Arnaud

**Comment by davidjgraph** [comment]
https://github.com/jgraph/drawio/commit/a1ff923e636425b7789632a3f82d4f460c8062a6#diff-8b7cd8a6ca38ab8b25445135aba7808b

But you will need the next release before the min.js files are built
