### ISSUE TITLE
Embed HTML not working in Google Shared drive (FKA Team Drive)

### ISSUE THREAD

**Issue by sze-wbrp** [jgraph/drawio#589]
For some reason, I can no longer do an HTML export (File > Embed > HTML...) of any drawings stored on a Google Shared drive. The "loading circle" (see attached screenshot) just goes on forever. Whenever I copy or move the same file to my own Google Drive (My Drive), it works just fine.

![Screenshot 2019-10-08 at 14 52 21](https://user-images.githubusercontent.com/28135362/66455905-6138f100-ea6c-11e9-8cf0-1531a41c4c06.png)

**Comment by alderg** [comment]
Fixed
