### ISSUE TITLE
Update to IBM icons and template

### ISSUE THREAD

**Issue by jaywarfield** [jgraph/drawio#591]
Please replace the IBM template named ibm_vpc_architecture.xml (under Cloud in draw.io) and the IBM icon set named VPC.xml (under Shapes/Networking/IBM in draw.io) with the files ibm_vpc_architecture.xml and VPC.xml in the attached ibmvpc4drawio.zip.  Thanks!

[ibmvpc4drawio.zip](https://github.com/jgraph/drawio/files/3713110/ibmvpc4drawio.zip)

**Comment by kutya** [comment]
Will be in next release.
