### ISSUE TITLE
Background Color missing on PDF Export with "Crop" Option selected

### ISSUE THREAD

**Issue by mapl** [jgraph/drawio#592]
### Environment
draw.io Online Edition v12.1.0 / draw.io Desktop 11.3.0

### Issue 

When exporting a drawing to a PDF File with the "Crop" option selected, the solid Background Color is  omitted in the rendered PDF File. 

However, when the "Crop" is not selected, the background Color is present as expected.

**Comment by alderg** [comment]
Thanks for the report, this will be fixed in the next release.
