### ISSUE TITLE
Bugs report: auto-cropping when exporting PDF

### ISSUE THREAD

**Issue by Kylin9511** [jgraph/drawio#595]
If there exist long formular at the very right of the graph (The formula is much shorter than the latex code of course), the  exported graph will has large blank at the right side.

This is because the cropping area detector fails to detect the correct range after redering. And changing the size of the text box doesn't work. Draw.io still detect the right border of the original latex text.

Bug fix should be easy, either you change the detection strategy, or enable the user to crop the image manually.

> System MacOS Mojave 10.14.6
> Draw.io version: 11.3.0.dmg

**Comment by davidjgraph** [comment]
Can you please include a diagram that demonstrates this problem?

**Comment by Kylin9511** [comment]
This is what I want:
![image](https://user-images.githubusercontent.com/25010679/66818114-6962c600-ef6f-11e9-95e3-c0d3037a06ba.png)

While this is want auto-cropping produce:
![image](https://user-images.githubusercontent.com/25010679/66818229-9911ce00-ef6f-11e9-86e9-05ad9a621439.png)

And I guess this is the reason:
![image](https://user-images.githubusercontent.com/25010679/66818282-ac249e00-ef6f-11e9-9b83-8a79525fae94.png)

**Comment by Kylin9511** [comment]
There are indeed many tools that can crop pdf easily. However, it is troublesome for Draw.io users. My recommendation is adding manual pdf cropping in the pdf export function.

**Comment by davidjgraph** [comment]
"Bug fix should be easy", OK, please submit the PR for the fix.

**Comment by Kylin9511** [comment]
This issue is merely a bug report for the author team to make Draw.io app better, instead of a technical discussion between programmers. I submitted this issue because your colleague asked me to after I send user report via email.

You may choose to add it to your TODO list or simply ignore it, since this problem can be skipped by using pdf cropping tools.

The complexity of fixing the cropping area detector is merely my guess, which is of course inaccurate. Sorry if you feel offended. @davidjgraph

**Comment by alderg** [comment]
Can you attach the XML for this diagram please?

**Comment by Kylin9511** [comment]
@alderg Thanks! It works when changing Text Overflow together with Arrange of latex formula.

**Comment by matthewelmer** [comment]
This workaround changes the positioning of the text. Is there any way we could get the manual cropping tool that @Kylin9511 suggested? I have no idea how difficult this would be and I'm a filthy freeloader, so feel free to hit me with a fat "**NO**" lol

**Comment by matthewelmer** [comment]
Oop, the workaround didn't work for me. Is there another workaround that might work?

**Comment by matthewelmer** [comment]
Is there any sort of debugging mode where I can see what's causing the failure to crop? I have attached the problem diagram.
![image](https://user-images.githubusercontent.com/26128847/167738386-f061b17f-a2e0-4400-8728-1c141db65ecb.png)
![image](https://user-images.githubusercontent.com/26128847/167738461-521821fa-2f97-4b1a-9889-9cf152c23c84.png)

**Comment by matthewelmer** [comment]
But when I remove all the LaTeX I am left with the following:
![image](https://user-images.githubusercontent.com/26128847/167738595-39b765b7-274c-453d-8924-970762558fed.png)

**Comment by matthewelmer** [comment]
Okay somehow it's the mathtext, and it causes problems whether I change overflow options or even deselect it when generating output:
![image](https://user-images.githubusercontent.com/26128847/167739378-9eb50e79-8ec6-4422-88a0-7b2bd41e281c.png)

**Comment by matthewelmer** [comment]
I ended up just cropping it with another program. Let me know if there's any progress on this!

**Comment by a123455392** [comment]
> Try using textOverflow=fill in the style for the math shape. ![math-clipping](https://user-images.githubusercontent.com/921200/66828727-10386980-ef52-11e9-9516-d6361349a1b4.png)

set ["Text Overflow" = "Block"] also work.

**Comment by IridiumXOR** [comment]
Why until some months ago it works and now is impossible to crop and export as a PDF a selected block without a large white  border?! This bug is very, very annoying...
