### ISSUE TITLE
Feature request: better auto size for subscript in latex formular

### ISSUE THREAD

**Issue by Kylin9511** [jgraph/drawio#596]
By simple trial you will find the latex formular support in draw.io still needs upgrade. If the size of front is getting too small, the text in the subscript will be almost the same size as the main text, making the formular ugly.

New feature shall auto resize the subscript if possible. Thx~

> System MacOS Mojave 10.14.6
> Draw.io version: 11.3.0.dmg

**Comment by davidjgraph** [comment]
That would be a feature that needs to be for MathJax, the [library](https://github.com/mathjax/MathJax) we use

**Comment by celynwalters** [comment]
While it does still seem to be down to MathJax, apparently it's expected behaviour.

I opened an [issue](https://github.com/mathjax/MathJax/issues/2356) over there, and the following fixes it in an isolated case:

```js
MathJax = {
  startup: {
  ready: function () {
    var math = MathJax._.core.MmlTree.MmlNodes.math.MmlMath;
    math.defaults.scriptminsize = '0px';
    MathJax.startup.defaultReady();
  }
  }
};
```

I don't know about for draw.io though, I don't know if there's anywhere I can inject it to try.

**Comment by zL1nX** [comment]
Hello, did you solve this issue? I have the same problem on version 16.5.1. The subscript size won't change with the main text.

**Comment by douseful** [comment]
> While it does still seem to be down to MathJax, apparently it's expected behaviour.虽然它似乎仍然取决于 MathJax，但显然这是预期的行为。
> 
> I opened an [issue](https://github.com/mathjax/MathJax/issues/2356) over there, and the following fixes it in an isolated case:我在那里提出了一个问题，以下在一个孤立的案例中修复了它：
> 
> ```js
> MathJax = {
>   startup: {
>   ready: function () {
>     var math = MathJax._.core.MmlTree.MmlNodes.math.MmlMath;
>     math.defaults.scriptminsize = '0px';
>     MathJax.startup.defaultReady();
>   }
>   }
> };
> ```
> 
> I don't know about for draw.io though, I don't know if there's anywhere I can inject it to try.

how to solve?

**Comment by gigberg** [comment]
Aha, just open chrome devtools in drawio webpage, the run below code in the console:
`
MathJax._.core.MmlTree.MmlNodes.math.MmlMath.defaults.scriptminsize = '0px';
MathJax.startup.defaultReady();
`
now you can try to use fontsize less than 8px to text, which will alse apply to  subscript and superscript

**Comment by Infin1te2021** [comment]
> Aha, just open chrome devtools in drawio webpage, the run below code in the console:
> 
> ```js
> MathJax._.core.MmlTree.MmlNodes.math.MmlMath.defaults.scriptminsize = '0px';
> MathJax.startup.defaultReady();
> ```
> 
> now you can try to use fontsize less than 8px to text, which will alse apply to subscript and superscript

It works fine when exporting it as an SVG file while I can't get it as a PDF directly. So, you may need a converter.
