### ISSUE TITLE
Can't save/load document to shared folder in OneDrive

### ISSUE THREAD

**Issue by hannojg** [jgraph/drawio#598]
Hello, 
we are trying to share draw.io file between multiple colleagues through our OneDrive cloud. Unfortunately, we are unable to select shared folders as a source for saving a draw.io file. 

<img width="987" alt="Screenshot 2019-10-12 at 16 11 57" src="https://user-images.githubusercontent.com/16821682/66702751-5a7bd980-ed0b-11e9-9b08-6b62c3b9d340.png">

The person trying to save has defnitly edit rights on this folder. With Google Drive this works seemlessly. 

Thank you in advance (and thx for the great tool! :))

**Comment by hannojg** [comment]
Double clicking to enter a folder is not the issue. 

Steps to reproduce:
1. Person A creates a folder on OneDrive 
2. Person A invites Person B to share this folder, and gives Person B edit rights 
3. Person B opens draw.io and selects OneDrive as storage 
4. Person B tries to save a .drawio file he/she created 
5. Person B tries to choose the shared folder as a destination folder 
6. Here arises the issue: person b can’t click the „save“ button to save the file to the shared folder (see image above)

**Comment by Jendker** [comment]
I believe it also affects the problem with loading the file from shared folder. One could change the issue title to reflect that.

**Comment by cstent** [comment]
This is still an issue. User that gain full access to shared folders, cannot select the file to edit it. This is an important bug, as it does not allow seamless collaboration.

**Comment by raf672** [comment]
> Double clicking to enter a folder is not the issue.
> 
> Steps to reproduce:
> 
> 1. Person A creates a folder on OneDrive
> 2. Person A invites Person B to share this folder, and gives Person B edit rights
> 3. Person B opens draw.io and selects OneDrive as storage
> 4. Person B tries to save a .drawio file he/she created
> 5. Person B tries to choose the shared folder as a destination folder
> 6. Here arises the issue: person b can’t click the „save“ button to save the file to the shared folder (see image above)

Hi! I have the same problem. Have you solved this problem?

**Comment by Jendker** [comment]
Write to Microsoft about this, they are responsible to find the solution as indicated in the first post.

**Comment by raf672** [comment]
> Write to Microsoft about this, they are responsible for this problem as indicated in the second post [#598 (comment)](https://github.com/jgraph/drawio/issues/598#issuecomment-541783140).

Thanks! I think this story is between Diagrams an Microsoft. Not Me and Microsoft.
The Diagrams is the MS Visio competitor.  So there is a possibility that Microsoft makes work with OneDrive for Diagrams difficult on purpose.

**Comment by davidjgraph** [comment]
Let's keep the thread factual please.
