### ISSUE TITLE
How to configure client_secret

### ISSUE THREAD

**Issue by ZanderZhao** [jgraph/drawio#600]
When I deploy the _web_ folder on my server without alter, then I save as github ,the web stop at
**This window will be closed automatically.**

I think the file in WEB-INF should be alter, but I want to know where can I get the **github_dev_client_secret** . Why doesn't need _github client ID_

![20191014103557](https://user-images.githubusercontent.com/40056837/66726950-c460c400-ee6e-11e9-84ce-8f94e857d9f2.png)

Thanks！

**Comment by davidjgraph** [comment]
https://auth0.com/docs/connections/social/github describes how to create an app and generate the client ID and secret to enter.
