### ISSUE TITLE
Feature Request: Unique URLs for each page

### ISSUE THREAD

**Issue by fusillijerry89** [jgraph/drawio#601]
Unique URLs for each page would allow more specific linking from another .drawio file.

i.e.

file2.drawio links to specific page within file1.drawio.

**Comment by briancousins** [comment]
A method to link to pages within a draw.io file would be very nice to have.

**Comment by alderg** [comment]
Right click the page tab and click Link.
![page-link](https://user-images.githubusercontent.com/921200/69728714-4823f680-1125-11ea-833d-44a7211e2eef.gif)
