### ISSUE TITLE
Text misalignment when exporting to PNG or SVG

### ISSUE THREAD

**Issue by cdsousa** [jgraph/drawio#603]
Hi all, I've tried to find some existing issues about this but I have found none, so here am I reporting it.

When exporting a drawing to SVG or PNG the text inside objects gets a different and wrong alignment when compared to the editor.

For example, using the "**Bulb**" example from https://github.com/jgraph/drawio-diagrams :

![1](https://user-images.githubusercontent.com/333519/66825444-30f8c300-ef42-11e9-9159-b38f10b46c0e.png)

I get this exported PNG:

![bulb](https://user-images.githubusercontent.com/333519/66825505-4837b080-ef42-11e9-988c-05cdc93a6498.png)

If I export to SVG and open in Chrome I get this:

![3](https://user-images.githubusercontent.com/333519/66825632-8c2ab580-ef42-11e9-8b50-3526c6c7b5dc.png)

PDF and HTML exports are OK!
I wonder if this has something to do with the way that Chrome (here in Linux) renders the SVGs and if the PNG export uses the browser itself.

**Comment by alderg** [comment]
What version of Chrome are you using? Can you attach the exported SVG file?

**Comment by cdsousa** [comment]
Google Chrome Version 77.0.3865.120 (Official Build) (64-bit) in Linux. But this issue has been happening for a long time.

SVG inside the attached ZIP file:
[bulb.zip](https://github.com/jgraph/drawio/files/3729554/bulb.zip)

**Comment by alderg** [comment]
I just tried with Ubuntu 16.04 and Ubuntu 18.04 with this version of Chrome and it works for me. Which Linux distribution and version are you using?

**Comment by cdsousa** [comment]
Ubuntu 18.04.3 with KDE (Kubuntu), with Chrome downloaded from the official page (https://www.google.com/chrome/).
I just confirmed, my coworkers have no issues in Chrome within XFCE and Gnome, Ubuntu 18.04.3.

Just to clarify, the PNG comes from a render of the SVG by the browser, right? So the issue here is in fact just a problem related to the render of the SVG by Chrome.

Can this be related just to missing fonts?

**Comment by alderg** [comment]
Correct. It can be related to missing fonts if you export on one machine and view on another.

**Comment by cdsousa** [comment]
Well, it's on the same machine.

And BTW, using Firefox is also stranger, see:

The editor in Firefox:
![Screenshot_20191015_162034](https://user-images.githubusercontent.com/333519/66845350-c9556e80-ef67-11e9-9e9e-8856d9817d1a.png)

The SVG generated in Firefox rendered in Firefox:
![Screenshot_20191015_162327](https://user-images.githubusercontent.com/333519/66845664-57315980-ef68-11e9-93b7-f307e9504525.png)

The SVG generated in Chrome rendered in Firefox:
![Screenshot_20191015_162550](https://user-images.githubusercontent.com/333519/66845725-792adc00-ef68-11e9-9c4c-688668c753fd.png)

The SVG generated in Firefox rendered in Chrome:
![Screenshot_20191015_162700](https://user-images.githubusercontent.com/333519/66845813-a4adc680-ef68-11e9-8c33-c83c99fefa52.png)

**Comment by alderg** [comment]
Did you have the browser console open when viewing the SVGs?

**Comment by cdsousa** [comment]
No, but just I've found the issue!

In the Chrome font settings, I had set "**Minimum font size**" to **14** (I usually do this since some years ago).
![Screenshot_20191015_163409](https://user-images.githubusercontent.com/333519/66846668-0b7faf80-ef6a-11e9-8953-e3fc56b4bbf7.png)

Setting it back to **0**, which is the default, fixed the issue in both PNG and SVG!
Thank you for this amazing software and all the support!
