### ISSUE TITLE
Certain symbols are barely visible in dark theme

### ISSUE THREAD

**Issue by AnElectricalEngineer** [jgraph/drawio#605]
Hi,

While using the dark theme, certain symbols (or part of them) are very difficult to see. For example, 
the curvy AC current symbol from the AC Source from Electrical/Sources almost disappears:

Dark Theme: 
![darktheme](https://user-images.githubusercontent.com/47844685/66859351-c7a1a000-ef93-11e9-966d-bf99265ba7b4.png)

Automatic Theme:
![automatictheme](https://user-images.githubusercontent.com/47844685/66859364-ce301780-ef93-11e9-8159-37f520ee9cd4.png)

This happened on version 12.0.1 on Windows 10.

**Comment by alderg** [comment]
Try removing the fill color.

**Comment by AnElectricalEngineer** [comment]
That worked, thanks.

**Comment by kutya** [comment]
Should be fixed in next release.
