### ISSUE TITLE
Saving method selection should not occur during startup

### ISSUE THREAD

**Issue by birgersp** [jgraph/drawio#609]
When I enter draw.io, the first thing I'm met with is this:

![Untitled](https://user-images.githubusercontent.com/5260237/67280407-5c912580-f4cd-11e9-83fa-b1e7aab342af.png)

But I want to get on with my drawing. Maybe I'll want to save it, but maybe not. IMO selecting where to save it is something I should deal with when I decide to save it, not before.

I suggest that this popup is removed from the application start.

**Comment by alderg** [comment]
Click "Decide later".

**Comment by davidjgraph** [comment]
Click in the background or "decide later". If we remove that we'll end up with 200 issues a week saying "I closed my browser before saving, please recover my file", which we can't.

You can add the ?splash=0 URL parameter to stop it showing.

**Comment by birgersp** [comment]
I didn't know that the start screen could be disabled. Thanks.
