### ISSUE TITLE
Error 500 - Creating PDF to jgraph/draw-image-export2

### ISSUE THREAD

**Issue by gil0109** [jgraph/drawio#617]
Using https://github.com/jgraph/draw-image-export2, I built the PDF Exporter.

I adjusted /usr/build/src/main/webapp/js/PreConfig.js to the new URL.

When draw.io initiates the export function, I get an Error with this in the export app logs:

[24/Oct/2019:02:01:52 +0000] "POST / HTTP/1.1" 500 - "https://<redacted>/ " "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36"

Have I missed changing something else?

**Comment by ashrafteleb** [comment]
It's hard to find out from a single log line. Please have a look at our Docker containers project here https://github.com/jgraph/docker-drawio/tree/master/image-export/standalone
