### ISSUE TITLE
outer group size is not protected with collapse and expand of child

### ISSUE THREAD

**Issue by bijwaard** [jgraph/drawio#618]
Dear draw.io developers,

Thanks for this great tool, it is really powerful.

The collapse/expand feature could be even better when outer group size can be protected, especially when complex structure diagrams have multiple nesting levels, like the following figure (e.g. similar to UML-2 composite structure diagram). 
![image](https://user-images.githubusercontent.com/6523124/67466210-f5977c00-f646-11e9-856d-f2ba0da0988f.png)

The issue is that the outer group resizes when the inner one expands, and doesn't go back to is original size when the inner one collapses again, see the following example.

1. create a group of groups like first figure below
2. collapse the inner group and then resize the outer group to contain it with ctrl-key, see second figure
3. expand the inner group with alt-key to protect size, and the outer group automatically resizes with the inner one, like in first figure
4. collapse the inner group and the outer group stays the same big size, see 3th figure

I tried fiddling with the outer container properties, but this does not seem to help:
- tried to turn on/off autosize of outer group, but it still resizes in step 3 and doesn't resize back in step 4
- tried to turn off resizable of outer group, but it still resizes in step 3 and outer group cannot be resized after step 4

I see a number of possible solutions/work-arounds:
- remember container size before auto-expanding in step 3 and re-apply it when child collapses
- use normal resize in step 2, but then the text doesn't scale with the figures, see 4th figure, at least for the UML types I used (Component, Required and Provided interfaces)
- add a property to keep group neatly around contained childs (i.e. before and after child collapse/expand)

Kind regards,
Dennis Bijwaard
![image](https://user-images.githubusercontent.com/6523124/67468462-d4388f00-f64a-11e9-93ed-606d420197ce.png)
![image](https://user-images.githubusercontent.com/6523124/67468509-e87c8c00-f64a-11e9-8916-7dc6b0ff8467.png)
![image](https://user-images.githubusercontent.com/6523124/67468581-0d70ff00-f64b-11e9-960e-2e751ccc0890.png)
![image](https://user-images.githubusercontent.com/6523124/67468724-4ad58c80-f64b-11e9-97c2-3fdd3ecf4bab.png)

**Comment by alderg** [comment]
This has been addressed with two new cell style properties, available in the next release:

**`contract`** — Set `contract=1` on a parent group (via Edit Style or the Properties panel in Format > Style) to make it automatically shrink to fit its children. When a child inside that group is collapsed, resized, moved, or deleted, the parent contracts to the bounding box of the remaining/resized children. This is the complement of the existing `expand` property which auto-grows the parent. The contraction recurses up through nested groups, so if you have multiple levels of nesting, each parent with `contract=1` will shrink accordingly.

**`groupPadding`** — Controls the padding in pixels between the children and the right/bottom edge of the group. Applies to both `expand` (auto-grow) and `contract` (auto-shrink). Default is 0. Set it on the parent group to maintain consistent spacing, e.g. `groupPadding=10` keeps 10px of space around the children.

Both properties are available in the Properties panel (Edit > Edit Style, or Format sidebar > Style > Properties).

**Example workflow from the original report:**
1. Create a group of groups, set `contract=1` on the outer group
2. Collapse the inner group — the outer group shrinks to fit
3. Expand the inner group — the outer group grows to fit (via existing `expand` behavior)
4. Collapse the inner group again — the outer group now correctly shrinks back

This will be included in the next release.

**Comment by davidjgraph** [comment]
Fix in 29.6.7
