### ISSUE TITLE
[WIP] Support for Box

### ISSUE THREAD

**Issue by timjacobi** [jgraph/drawio#62]
Hi,

I have started working on support for Box. Is this something you would be interested in?
https://www.box.com/

Here is the dev branch in my fork
https://github.com/timjacobi/draw.io/tree/box-support

**Comment by davidjgraph** [comment]
Sure, just shout if you have questions.

**Comment by timjacobi** [comment]
I'm sure I will at some point :) Thanks!

**Comment by timjacobi** [comment]
First question. Is there a way to develop the JavaScript files without having to rebuild with ant on every change?

**Comment by davidjgraph** [comment]
Use the dev=1 URL parameter. So, for example, I develop using https://test.draw.io/?test=1&dev=1&splash=0. Splash avoid the opening splash, test brings up the mxLog console in-editor. dev=1 bootstraps all of the source JS files for both draw.io and mxGraph. Note that you need to have mxGraph checked out as "mxgraph2" as a sibling folder to drawio. This makes for no build step when working on source.

**Comment by davidjgraph** [comment]
Obviously, I have test.draw.io mapped in my hosts and a fake cert for the domain. We enable this sub-domain on the cloud storage providers, so it behaves pretty much as production.

**Comment by alderg** [comment]
Yes, we use the dev=1 URL parameter, but you'll have to check out mxgraph2 (and use devhost.jgraph.com) or use mxClient.js and change Devel.js accordingly.

**Comment by timjacobi** [comment]
Thanks guys. I have the dev setup all working and am coding away. You can track the progress in the fork.

**Comment by joshuaquek** [comment]
Is this still available as a feature?
