### ISSUE TITLE
flowchart "Manual Input" shape is broken

### ISSUE THREAD

**Issue by Pwuts** [jgraph/drawio#623]
![image](https://user-images.githubusercontent.com/12185583/67572494-95800300-f736-11e9-8d91-8d8a9efbe6fa.png)
There are two things wrong with this shape:

* the text ends up outside the box
* the connectors are not on the perimeter (they seem to follow the perimeter of the "Card" shape)

This was on a newly created sheet, and the figure was inserted straight from the toolbar; I didn't alter its style or any of its settings.

**Comment by alderg** [comment]
The text position will be fixed in the next release.
