### ISSUE TITLE
Tooltips/Notes Visibility

### ISSUE THREAD

**Issue by Kager13** [jgraph/drawio#624]
The ability to add a "tooltip" or "note" to an object is useful, but the only way to know it's there is to hover over the object. Often the point of adding a note isn't just for "help" in using the object but to add some extra detail which you'd like to draw the viewer's attention to. If you have a lot of items on the diagram they are not going to hover over each one to find the "Easter Egg of Explanation". :)

It would be extremely helpful if you could add a visual indicator on the object to show it has additional information associated to it. To pile on - if you could toggle that indicator on/off I assume that would be good as well.

**Comment by alderg** [comment]
Try using the tooltips plugin via www.draw.io/?p=tips (you can make it permanent by clicking on Extras, Plugins, Add, then click Add for the prefilled text with the above URL, then click Apply to add the plugin to your editor).
