### ISSUE TITLE
Library import SVG files are not proportionally scaled

### ISSUE THREAD

**Issue by magnusolofstam** [jgraph/drawio#625]
When creating / adding an **image library** and **importing** multiple SVG files, the added images are squashed into a square-shaped image, and are not scaled proportionally. 

I created a video capture illustrating the issue. The yellow long bar with red circles gets squashed at first. But if instead dragging the same file onto the "library" area in the UI, the proportions are respected. 

https://youtu.be/3BaDbizIlxw

Also, here are the SVG-files, for reproduction
https://www.dropbox.com/sh/qx3kopgon7avdg2/AADEgEq6nZQKN0-6P2TsHxEXa?dl=0

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by magnusolofstam** [comment]
Awesone! It's working fine now - no SVG scaling proportion issues in 12.3.2
