### ISSUE TITLE
Google Drive: Error opening diagram

### ISSUE THREAD

**Issue by dayfuaim** [jgraph/drawio#626]
When I try to "Open existing diagram" from Google Drive (_being authorized_ just before), I get following window:
![Снимок экрана от 2019-10-29 12-16-32](https://user-images.githubusercontent.com/1274699/67753763-4bed2c00-fa46-11e9-8a36-0bdb4fa4136a.png)
(text: _"In order to select the item from the storage, please enter the system."_, button: "[Enter]")
Console is like that at this moment:
![Снимок экрана от 2019-10-29 12-16-21](https://user-images.githubusercontent.com/1274699/67753819-67583700-fa46-11e9-9590-f62258faba48.png)

Adblocker (uBlock Origin) is off at https://draw.io.

**Comment by alderg** [comment]
Does it work in an Incognito Window in the same browser?

**Comment by dayfuaim** [comment]
No, the same issue here.

Opera 65.0.3467.16 (beta).
Ubuntu 19.10

The same picture I see in other browsers: Firefox (stable & Nightly), Vivaldi (stable & Beta), and Brave (stable & Beta).

**Comment by dayfuaim** [comment]
Yes.

**Comment by alderg** [comment]
I'm afraid I'm not sure what's happening there. And what's even more confusing is that this dialog seems to be a Google+ dialog, but G+ is EOL since a long time...

**Comment by fusillijerry89** [comment]
Seems to be a few issues relating possibly to google drive
