### ISSUE TITLE
Wrong window to open/save drawio

### ISSUE THREAD

**Issue by tzulberti-jampp** [jgraph/drawio#627]
I updated drawio desktop to version v12.1.7 on Ubuntu 18.04.3, but the window to save, and open an existing diagram are inverted.

When I open DrawIO, and click `Open Existing Diagram`, the action of the button mentions `Save` instead of Open. 
![image](https://user-images.githubusercontent.com/18741829/67864048-c334c580-fb03-11e9-93b3-e3fc0bbe6758.png)

In a similar way, when I choose to export an existing diagram, the diagram mentions `Open`. For example, when exporting the diagram to a PNG, when saving the file I got the following action. 
![image](https://user-images.githubusercontent.com/18741829/67864197-068f3400-fb04-11e9-92f5-a2d897f9577a.png)

**Comment by tlchan** [comment]
Electron fixed it in https://github.com/electron/electron/pull/20861
