### ISSUE TITLE
Ubuntu message that drawio is ready

### ISSUE THREAD

**Issue by tzulberti-jampp** [jgraph/drawio#628]
When trying to export a diagram to a PNG, after chossing the PNG options (Trasnsparent background, Zoom, bandwidth, etc...), and before getting the option to save the image I got a message `drawio is ready ""`

![image](https://user-images.githubusercontent.com/18741829/67864514-78677d80-fb04-11e9-9c7f-3dfd95f1094b.png)

I am using Ubuntu 18.04 LTS, and drawio 12.1.7

**Comment by alderg** [comment]
This is a standard message in the window manager when a window is being displayed behind the current window (in this case the - wrongly labelled - save dialog for the image export).
