### ISSUE TITLE
export .xml broken in sandstorm 0.200

### ISSUE THREAD

**Issue by rawray7** [jgraph/drawio#63]
as soon as i upgraded to sandstorm 0.200, i lost the ability to export .xml. both view in new window and download fail. export to .pdf works

**Comment by ocdtrekkie** [comment]
I can definitely successfully export XML files with draw.io on Sandstorm Oasis, which is running 0.200. And I can't find anything in the changelog for 0.200 which would seem to affect this.

Are you on draw.io 5.6.0.3? If you go to the app store and try and install 5.6.0.3, does it ask if you if you want to upgrade your grains?

**Comment by rawray7** [comment]
I'm on v 5.6.0.3 .... hmmm. Running Firefox 51.0.1 (64-bit). Here's the (redacted) console:

Content Security Policy: The page’s settings blocked the loading of a resource at blob:https://XXXX.ABC.sandcats.io/YYYY (“frame-src https://*.ABC.sandcats.io”).

**Comment by ocdtrekkie** [comment]
Going to leave this in my inbox, will try and find some time to test some things, ask some questions of people, etc.

**Comment by ocdtrekkie** [comment]
It is possible this is related to https://github.com/sandstorm-io/sandstorm/issues/2602
