### ISSUE TITLE
Internal Page Links not preserved on xml export/import

### ISSUE THREAD

**Issue by fusillijerry89** [jgraph/drawio#630]
When exporting as xml, and then importing into a new file, links that point to internal pages appear as "Page Not Found."

**Comment by alderg** [comment]
This works for me. Can you attach a test case?

**Comment by ashrafteleb** [comment]
This happens with DnD and expected. Please use open or import to have internal page links correctly working

**Comment by alderg** [comment]
This will be fixed in the next release.
