### ISSUE TITLE
Support exporting multiple tab images at once

### ISSUE THREAD

**Issue by fidgetingbits** [jgraph/drawio#633]
I'm using the Linux desktop application. I regularly am exporting dozens of images from different tabs, and if I'm using minor variations of the same image and it turns out all of them have the same minor adjustment required, I have to manually update them all, after which I have to manually export all of the individual tabs with the exact same configuration. It would be nice if it was possible to select all tabs, or a series of tabs, and say you want to export them all using the same settings you specify for the first image being exported (like selection only, transparent, etc). A solution for #632 could help address this issue, in so far as the tab names could be used to automatically name the bulk exported images.

**Comment by alderg** [comment]
I you post this again we will block you.

**Comment by fidgetingbits** [comment]
These were all 3 separate issue, so I'm not sure why the others were deleted. Thanks.

**Comment by alderg** [comment]
Oops. It looked like spam (similar tickets created in short interval). Unfortunately there is no way to undelete issues. Sorry.

**Comment by alderg** [comment]
See #634 and #635
