### ISSUE TITLE
Importing Visio Stencils not working

### ISSUE THREAD

**Issue by kutya** [jgraph/drawio#637]
I have been trying to import the attached Vsio stencil file into draw.io(File-Import from Device) but a lot of them do not get imported correctly and get converted into a simple rectangle square shapes.
[Control Devices Stencils.zip](https://github.com/jgraph/drawio/files/3803397/Control.Devices.Stencils.zip)

**Comment by sidsabharwal** [comment]
Hi,

Requesting an update on this issue. We have been troubleshooting the importing of the Visio Stencils but are unable to get it to work properly.

Is there any other way by which we can get faster support?

**Comment by ashrafteleb** [comment]
Fixed, it will be available with the next release

**Comment by siddharthsharma** [comment]
Thanks for getting this issue fixed and releasing the changes. I reported this issue initially in the forum. We have been doing more testing and have found some more issues with respect to importing visio stencils. Please find the file and the issues identified below: 

**[VisioStencils.zip](https://github.com/jgraph/drawio/files/4875155/VisioStencils.zip)**
The shapes in the stencils are changing alignment, text changed alignment or spacing, line jumps disappeared, some shapes became inverted, line thicknesses changed, etc. 

If I need to report these details elsewhere or open another issue for the same please let me know.

Thanks for your help.
