### ISSUE TITLE
Self-hosted draw.war, getting 404 on image export

### ISSUE THREAD

**Issue by loganmarchione** [jgraph/drawio#639]
I self-host the draw.war file (v12.2.0) on Apache Tomcat 9. Recently, when trying to export a PNG of my diagram to my "Device", I get this error:

```
HTTP Status 404 – Not Found

Type Status Report

Message /draw/REPLACE_WITH_YOUR_IMAGE_SERVER

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

Apache Tomcat/9.0.27
```
Here is the URL it's calling:
`https://tomcat.internal.mydomainname.xyz/draw/REPLACE_WITH_YOUR_IMAGE_SERVER`

The only thing that's changed has been my version of the draw.war file. Not sure what version it started 404-ing.

**Comment by davidjgraph** [comment]
You need to replace the path with one that points to your image server, https://github.com/jgraph/draw-image-export2.

**Comment by loganmarchione** [comment]
Got it, thank you!
