### ISSUE TITLE
[Feature request] Select back element under current via alt + mouse click

### ISSUE THREAD

**Issue by MurzNN** [jgraph/drawio#64]
Very often we need to select element via mouse, that located in back of current element . At now via click we can select only front element. So we need to select it, lock (or send to back), and only after this - we can select other element under current.
In most of vector editors we can do this via alt+click on current element, or with other key combination.

Here is example how this works in Inkscape editor: http://graphicdesign.stackexchange.com/questions/13224/how-do-i-select-an-object-thats-below-another-object-in-inkscape

Please add this feature in draw.io - selecting next back element via alt+click or other way.

**Comment by carlfischerjba** [comment]
This appears to have been implemented.

**Comment by alderg** [comment]
Yes.
