### ISSUE TITLE
I self-host the draw.war file and want to self-host the export tool. Which Dockerfile should I use?

### ISSUE THREAD

**Issue by loganmarchione** [jgraph/drawio#640]
I'm the guy from #639. I self-host the war file and now want to self-host the [export tool](https://github.com/jgraph/draw-image-export2).

I see there are two repos containing Dockerfiles:
1. In [this repo](https://github.com/jgraph/drawio)
  ^^This seems to only contain a [Dockerfile](https://github.com/jgraph/drawio/blob/master/etc/docker/drawio-export/Dockerfile) that hosts **both** the war and the export server 
2. In a [separate repo](https://github.com/jgraph/docker-drawio)
  ^^This seems to contain multiple Dockerfiles
    a. A [Dockerfile](https://github.com/jgraph/docker-drawio/blob/master/debian/Dockerfile) (based on Debian) that hosts **both** the war and the export server 
    b. A different [Dockerfile](https://github.com/jgraph/docker-drawio/blob/master/image-export/bundled/Dockerfile) labeled as "bundled" that does the same thing as above
    c. Another [Dockerfile](https://github.com/jgraph/docker-drawio/blob/master/image-export/standalone/Dockerfile) labeled "standalone"

I believe 2c is the one I want, since I already have Draw.io running, but I'm wondering about the differences between 1, 2a, and 2b. Does that make sense? Is one repo more "official" than the other? I see the maintainers are different.

**Comment by davidjgraph** [comment]
They are both ours (jgraph).
