### ISSUE TITLE
Google Drive problems

### ISSUE THREAD

**Issue by FanyangMengDev** [jgraph/drawio#642]
Hi there,
I self-hosted the draw.io, but when I choose to save to the google drive, it will redirect to your website which is https://draw.io.
I have my own G Suite and already configure the API, could you please help me to make every time click on Google Drive it will authorized on my own website?
Thank you so much. And I am using the latest version.

**Comment by davidjgraph** [comment]
Please provide exact details of the environment and setup and exactly what operations you followed to be redirected to our website.

**Comment by FanyangMengDev** [comment]
OK, let me clarify the problem clearly.

First I need to say that this is a brilliant project and you are really excellent.

Now I will discript it in details:

1. When I self-hosted the latest version of draw.io and open the domain which bind with it, at first I will see "Save diagrams to:" , right?
![Save choice](https://user-images.githubusercontent.com/53750381/68378354-e9530900-0186-11ea-8c27-1a4c273de441.PNG)

So I click on google drive, cause I use it most. But when I click on it, it will redirect the url to your offcial website which is https://draw,io . Hence, I think that maybe I should create an API which allows me to use authorization on my own website without redirection.

I search the issues first, according to #550 , I use my G Suite account to create an API like this:
![OAuth 1](https://user-images.githubusercontent.com/53750381/68378781-ab0a1980-0187-11ea-8553-e48e0140051e.PNG)
![OAuth 2](https://user-images.githubusercontent.com/53750381/68378791-ad6c7380-0187-11ea-8f2c-95e927ab986f.PNG)

Then, I custom the file which is src/main/webapp/js/diagramly/DriveClient.js
https://github.com/jgraph/drawio/blob/05b910c689057509d7478b6a15e1e7c49d200d5a/src/main/webapp/js/diagramly/DriveClient.js#L33-L38
I custom this line and the next to my own client ID and enable the API

Then I clear the cache and refresh the web page. When I try to click on Google Drive, it still redirect to draw.io but not my own domain.

Could you please tell me how to fix it? That will be so much appreciated.

Thanks.

**Comment by davidjgraph** [comment]
Thanks for the details. I think you're hitting the same problem as https://github.com/jgraph/drawio/issues/550 had, you need an override of app.isDriveDomain to return true all the time.

Note that we added preConfig.js and postConfig.js so you can make arbitary JS changes without having to re-compile the code. You can put the appId and clientId in the preConfig and the override of isDriveDomain in the postConfig.

**Comment by davidjgraph** [comment]
If you are planning to have the interface in Chinese, btw, you can any improvements to https://docs.google.com/spreadsheets/d/1FoYdyEraEQuWofzbYCDPKN7EdKgS_2ZrsDrOA8scgwQ and that is automatically generated for each release.

**Comment by FanyangMengDev** [comment]
I think that is the point that I do not understand how to add and overide.
Here is what I do:
in app.js change it to this
![Screenshot_2019-11-08-01-24-29-333_com android chrome](https://user-images.githubusercontent.com/53750381/68412357-0c051200-01c7-11ea-8bf6-a6fd99d2a067.jpg)

preconfig file change to this 
![IMG_20191108_012927](https://user-images.githubusercontent.com/53750381/68412463-3951c000-01c7-11ea-8a05-e313449246cd.jpg)

postconfig file change to this
![Screenshot_2019-11-08-01-26-48-601_com android chrome](https://user-images.githubusercontent.com/53750381/68412491-48d10900-01c7-11ea-94d1-18a804249a07.jpg)

refresh and nothing changed.
Could you please help me check that where did I wrong?

**Comment by davidjgraph** [comment]
The syntax in postConfig is wrong and you don't need the override in App.js.

```
App.prototype.isDriveDomain = function()
{
	return true;
};
```

**Comment by FanyangMengDev** [comment]
Ah! Sorry that is a stupid mistake due to custom on phone.
After change it, it can autorized on my own domain, but Google give me an error message:

> The redirect URI in the request, https://draw.fanyangmeng.com/google, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/671128082532-jhphbq6d0e1gnsus9mn7vf8a6fjn10mp.apps.googleusercontent.com?project=671128082532

Could you please tell me why this happen? Thank you so much and you are so kind.

**Comment by FanyangMengDev** [comment]
I think the problem the string '/google' after my domain, but when I try to input in the Google API console, it tells me that it could not contain path or end with '/'.
So it will be so much appreciated that if you could help me tackle with this problem.
Thank you

**Comment by FanyangMengDev** [comment]
The redirect URI in the request, https://draw.fanyangmeng.com, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/671128082532-jhphbq6d0e1gnsus9mn7vf8a6fjn10mp.apps.googleusercontent.com?project=671128082532

after remove /google, it still wrong

**Comment by FanyangMengDev** [comment]
preconfig file should not have viewer id , all done.
thank you so much!

**Comment by FanyangMengDev** [comment]
![Screenshot_2019-11-08-02-40-46-782_com android chrome](https://user-images.githubusercontent.com/53750381/68417340-30fe8280-01d1-11ea-8bf9-ef78d23c3907.jpg)
it drives me crazy.
When I finally can login on my own domain, after I give permission to it , it redirect to this page.
I add a have permission redirect url which is my domain+google
I am crazy now.

**Comment by davidjgraph** [comment]
You need to serve https://github.com/jgraph/drawio/blob/master/src/main/java/com/mxgraph/online/GoogleAuthServlet.java on /google using a servlet engine, like Tomcat, for example. Have you tried the docker image, https://github.com/jgraph/docker-drawio ?

**Comment by FanyangMengDev** [comment]
Using docker, after I choose to give permission to draw.io, it display this
![Screenshot_2019-11-08-10-18-29-024_com android chrome](https://user-images.githubusercontent.com/53750381/68444466-dfc2b300-0211-11ea-813c-92dcd66a218c.jpg)
then I turn on ssh to look what happened
![Screenshot_2019-11-08-10-23-09-705_com server auditor ssh client](https://user-images.githubusercontent.com/53750381/68444485-ecdfa200-0211-11ea-963c-a5b7fbfad290.jpg)
Could you please tell me how to fix it?

**Comment by FanyangMengDev** [comment]
java.io.IOException: Server returned HTTP response code: 400 for URL: https://www.googleapis.com/oauth2/v4/token
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
        at com.mxgraph.online.AbsAuthServlet.doGet(Unknown Source)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1839)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
{
  "error": "invalid_request",
  "error_description": "Invalid parameter value for redirect_uri: Missing scheme: Replace_with_your_own_google_client_redirect_url"
}

**Comment by FanyangMengDev** [comment]
`08-Nov-2019 03:51:56.314 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
08-Nov-2019 03:51:56.331 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
08-Nov-2019 03:51:56.342 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["https-openssl-nio-8443"]
08-Nov-2019 03:51:56.361 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [6,338] milliseconds
08-Nov-2019 03:51:56.471 INFO [http-nio-8080-exec-2] org.apache.tomcat.util.http.parser.Cookie.logInvalidHeader A cookie header was received [userId":"wiz@fanyangmeng.com","key":"a9qWmPC08B/v64t5J1pVjA=="}; _ga=GA1.2.1311352958.1573042980; _gid=GA1.2.1829532929.1573042980; wizCookieToken=Q81x4agugYhL7bmulaC6jCD6RAIObCdue4zskbCKYgxsKbvlRkspuBq0Y2gtUByO] that contained an invalid cookie. That cookie will be ignored.
 Note: further occurrences of this error will be logged at DEBUG level.
08-Nov-2019 03:51:56.471 INFO [http-nio-8080-exec-1] org.apache.tomcat.util.http.parser.Cookie.logInvalidHeader A cookie header was received [userId":"wiz@fanyangmeng.com","key":"a9qWmPC08B/v64t5J1pVjA=="}; _ga=GA1.2.1311352958.1573042980; _gid=GA1.2.1829532929.1573042980; wizCookieToken=Q81x4agugYhL7bmulaC6jCD6RAIObCdue4zskbCKYgxsKbvlRkspuBq0Y2gtUByO] that contained an invalid cookie. That cookie will be ignored.
 Note: further occurrences of this error will be logged at DEBUG level.
`
I think maybe because another docker I installed have a bad influence with tomcat, could you please tell me how to custom the tomcat port in docker?

**Comment by FanyangMengDev** [comment]
I am really crazy now.
All docker files have been deleted.
I decide to use your already built files.
I have already install tomcat.
Would you please tell me what should I do to Tomcat?

If it takes your time so much, I would like to pay. Just this thing is really drives me crazy.

**Comment by ashrafteleb** [comment]
Docker moved to https://github.com/jgraph/docker-drawio

This Docker Compose in https://github.com/jgraph/docker-drawio/tree/master/self-contained will help you serve draw.io with Google Drive support. Follow the README
