### ISSUE TITLE
Complexity management of page tabs

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#647]
Allow scrolling through tabs when there are too many to fit on screen
Allow grouping of tabs

**Comment by HerrNyani** [comment]
Great request! I'd also like to request a bigger minimum width per tab so you can still read (a recognizable part of) the title, and that the scroll controls show earlier. It's ridiculous at the moment.

![image](https://user-images.githubusercontent.com/26082367/84354008-76988900-abc0-11ea-894e-82ab50ed488b.png)

![image](https://user-images.githubusercontent.com/26082367/84354190-bbbcbb00-abc0-11ea-9676-9187be9c371a.png)

**Comment by skysgh** [comment]
Agreed. 
Tabs, in general, when too many to fit, are problematic. Can't see what we are doing.
A shortstop solution that would allow some progress without a major redo would include
- Giving shortcuts to Move Tab Left, Move Tab Right, Rename Tab.  The code is already in place to do that.
Regarding being able to see the Tab title...dunno.

**Comment by MurzNN** [comment]
When we have many tabs, vertical list will be much better than horisontal, example is Firefox's [Tree Style Tab](https://addons.mozilla.org/en/firefox/addon/tree-style-tab/) extension.

**Comment by bugrasan** [comment]
i second the request above, when space is available (e.g. only 2 tabs):
> I'd also like to request a bigger minimum width per tab so you can still read (a recognizable part of) the title

**Comment by mararad** [comment]
Also will be good to have hierarchy structure of pages (or collapsible folders), like in wireframepro.mockflow.com

**Comment by dleach02** [comment]
It would also be useful if you could drag-n-drop a tab from one document to another. I created a document with too many tabs and wanted to break the document into multiple documents. Would be quicker if I could just drag-n-drop
