### ISSUE TITLE
Text font size change is strange

### ISSUE THREAD

**Issue by chkdmin** [jgraph/drawio#65]
Hello

I created text box and write multiple line text in one text box

![image](https://cloud.githubusercontent.com/assets/2172517/22538552/85187ae2-e956-11e6-86a2-cc0078da1e35.png)
select text all and change font size, Only one line is changed to the size I selected
other line changed 18px fixed like above image

this is bug??

Thank you

**Comment by alexis57** [comment]
Exactly the same problem, very annoying.

**Comment by alderg** [comment]
As a workaround, use Shift+Enter for creating new lines.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
