### ISSUE TITLE
Allow to pass client-side configurations via URL parameter.

### ISSUE THREAD

**Issue by RobertZenz** [jgraph/drawio#650]
draw.io [has a plethora  of configuration options](https://desk.draw.io/support/solutions/articles/16000058316-how-to-configure-draw-io-in-confluence-quip-and-embed-mode-) which is absolutely great, but these can only be set on self-hosted instances. A nice addition would be to be able to pass these configuration options as URL parameters, as that would allow individual clients to override the configuration of the server.

That doesn't make much sense when having a self-hosted instance, but when one is using the draw.io website it would grant them a lot more leeway of how to use it. For example the `compressXml` option is a great example of what you might want to be able to trigger even on a foreign instance. The passed configuration should override the hard-coded one, obviously. An example would be `https://www.draw.io?configuration={"compressXml": false}`.

As far as I can see all these options are also purely client-side, so there's no ill-effect on the server when being able to set them. Also this is already possible if one manages to swap out the configuration file which is being loaded on the client side or to inject their own code, but that's a pretty shitty hack at best.

**Comment by alderg** [comment]
We'll add client-side configuration via localStorage in the next release (.configuration key).

**Comment by RobertZenz** [comment]
Out of curiosity, how's that going to work for the end-user? As far as I know there is no direct and good way to edit the LocalStorage (besides some development tools), so will there be a configuration dialog?

**Comment by davidjgraph** [comment]
No, better it's done via the dev tools. If we add a UI dialog we'll get a ton of issues from non-techs who can't write the JSON, no thanks...

**Comment by RobertZenz** [comment]
That would mean that you can't bookmark/hand out links with a certain configuration, though.

**Comment by davidjgraph** [comment]
I don't really want to do that. Even if we take a PR, it won't be maintained and just cause as a bunch of issues every time we update the core and not the dialog (i.e. would have been quicker to just do ourselves, which I don't want to :) ). I'd suggest you create a plugin if you need that.

I'll leave it open in case one of the core team find it interesting, but I doubt they'll want the maintenance that it adds, either.

**Comment by RobertZenz** [comment]
I don't want that dialog anyway, I was just wondering how that would be useful to the end-user.

If you read the configuration extension/override from the URL one can pass around a link which contains the configuration, meaning that end-users don't have to worry about it besides having to click or bookmark a link. If the configuration is read from the local storage...well, I have no idea how to distribute that among users.

My main and original point was to have such an easy facility to share links to an existing instance with modified configuration.

**Comment by alderg** [comment]
We'll merge this with .drawio-config in the next release (.configuration key no longer used).

**Comment by alderg** [comment]
See https://twitter.com/drawio/status/1196806288048611328

**Comment by RobertZenz** [comment]
That's very nice, thank you.
