### ISSUE TITLE
Dropbox authenication does not succeed

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#651]
Authorize dialog is shown twice, then error dialog.

This happens straight away for new diagram.

For open existing diagram the picker shows the users' Dropbox correctly, so at least the picker has authenication, but then follows the same dialog pattern as new once a file is chosen.

**Comment by davidjgraph** [comment]
Seems to have been an outage at the time.

**Comment by SanjayVyas** [comment]
I have facing this problem with dropbox as well as google drive. Both ask for authorization but result in access denied. One drive seems to work

**Comment by davidjgraph** [comment]
Does it work incognito/private window? Ad blocker affecting it?
