### ISSUE TITLE
A question about the implementation of the underlying style

### ISSUE THREAD

**Issue by zhangml17** [jgraph/drawio#654]
For example:
"shadow=1" or "shadow=0" , how to add a specific shadow style ?   In the source code, I can not find the CSS code to implement it, could someone please tell me?

**Comment by ile** [comment]
Agreed. 

Could we use, say CSS `filter` rule to style shapes?

https://stackoverflow.com/questions/6088409/svg-drop-shadow-using-css3
https://developer.mozilla.org/en-US/docs/Web/CSS/filter#drop-shadow()_2

**Comment by ddidier** [comment]
See #1671
