### ISSUE TITLE
Less strict search matching

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#655]
"If I wanna search shapes I always have to enter the whole name:
WS-C2960X-24TS-l

WS-C2960* or something easier as JS-Regex would be great so that "normal" user also can use the search. "

**Comment by petervandivier** [comment]
Please re-open this issue. Icons with a plural name are not intuitively searchable if you forget or don't know in advance that the canonical name has a trailing "s". A lot of Azure icons in the default image pack (as of 20.7.4) have plural names. Some examples:

* endpoint analytics
* storage accounts
* data clusters
* azure workbooks
* language services
* bot services
* log analytics workspaces


|search|singular result|plural result|
|---|---|---|
| storage accounts | <img width="179" alt="Search Images:storage account (singular)" src="https://user-images.githubusercontent.com/10898767/234645236-645c488d-5b0c-4439-9630-98b1d0e79124.png"> | <img width="175" alt="Search Images:storage accounts (plural)" src="https://user-images.githubusercontent.com/10898767/234645356-a4a83c13-7970-4c8b-81e0-70406fe8080b.png"> |
| azure data clusters | <img width="173" alt="Search Images:azure data cluster (singular)" src="https://user-images.githubusercontent.com/10898767/234645522-ad2eb396-5bf2-4208-8921-caeb82096904.png"> | <img width="177" alt="Search Images:azure data clusters (plural)" src="https://user-images.githubusercontent.com/10898767/234645636-a0e1691e-8e45-426b-a531-09df43910a1c.png"> |

**Comment by davidjgraph** [comment]
we don't know how to implement this in JS.

**Comment by alderg** [comment]
This will be added in the next release (https://www.codedrome.com/the-soundex-algorithm-in-javascript/)

**Comment by davidjgraph** [comment]
Released in 21.2.4
