### ISSUE TITLE
Corrections to IBM icons and template

### ISSUE THREAD

**Issue by jaywarfield** [jgraph/drawio#659]
The VPC template (ibm_vpc_architecture.drawio/xml) included in the zip provided for #591 is correct but the published version has some differences: 1) some group tags in upper left corner of group boxes are not updated (IBM Cloud Tag and VPC Tag should be slightly redone tags for clarity, but the new Classic Tag is correct in the published VPC template), 2) arrow line from Floating IP to Internet is moved although is still accurate, 3) arrow line from Implicit Router to Classic box has an arrow that is cutoff so unable to see the arrow, 4) half of the text is blue and half is black (all text should be black for a consistent look), and 5) IBM Cloud box, VPC box, and all Subnet boxes do not have the Container property checked (all boxes should have the container property checked except for the security group box should not have the container property checked).  That #5 may be my fault as mentioned below (sorry about that) but I don't know why the 1 through 4 above.  I tried on both Firefox and Safari on Mac with some results as above.

The VPC library (VPC.xml) in #591 included in the zip provided for #591 is missing the container property on the IBM Cloud box, VPC box, and Subnet box, and the published version does not have the updated IBM Cloud Tag and VPC Tag that were redone a bit for clarity.

Perhaps the container property can get unchecked when updating the group box, so in the future before submitting changes I need to make sure the container property is set on all group boxes except the security group box should not have the container property set.

Therefore, to correct all of the above, in your next update please replace the IBM template named ibm_vpc_architecture.drawio (under Cloud in draw.io) and the IBM library named VPC (under Shapes/Networking/IBM in draw.io) with the files ibm_vpc_architecture.drawio and VPC.xml in the attached ibmvpc4drawio_corrections.zip.

[ibmvpc4drawio_corrections.zip](https://github.com/jgraph/drawio/files/3870814/ibmvpc4drawio_corrections.zip)

Thanks!

**Comment by davidjgraph** [comment]
Thanks for your recommendations. The stencils implemented are based on the raster images and often the raster images supplied are wrong, thus our implementation matches the errors in the rasters IBM send us.

For example:

![2019-12-18 09 38 45](https://user-images.githubusercontent.com/1761087/71074481-3f4da000-217a-11ea-94db-ff0a38a4a4a0.jpg)

We were provided the shape on the left and our developer had to adapt it to the drawio stencil on the right.

In terms of consistency, the first set provided had all blue text, then later black text was added to some shapes. Most vendors have design guidelines, IBM are notable that they don't.

The quality of the shapes in the attached .drawio file isn't good enough to work with. We need the vector originals. An example is:

![2019-12-18 09 38 05](https://user-images.githubusercontent.com/1761087/71074557-66a46d00-217a-11ea-8564-161692d4d9c7.jpg)

We just can't do anything with this, unfortunately.

I'll close this issue for now. If you wish to submit improvements as vector graphics, please open a new issue.

**Comment by jaywarfield** [comment]
Thanks David!  I was going to ask what else is needed and you answered my questions.  I'm working on a new rendition with more significant changes and will be sure to follow your comments then.
