### ISSUE TITLE
[Help] How to run drawio on local ?

### ISSUE THREAD

**Issue by srinivasdamam** [jgraph/drawio#663]
Would like to explore the project and contribute, but not sure how do I start it on my machine. Can someone help ?

**Comment by fuminori-ido-m** [comment]
> Would like to explore the project and contribute

Me either;-(  However, regarding to start on my machine, at least [starting by docker](https://github.com/fjudith/docker-draw.io) as README says is an easy 1st step.

**Comment by ashrafteleb** [comment]
Yes, docker is a good start

Also, in `etc/build` folder run `ant war` to build the project war file. Then, using any servlet container like Jetty or Tomcat, deploy the web app
