### ISSUE TITLE
How to customize server URL?

### ISSUE THREAD

**Issue by fuminori-ido-m** [jgraph/drawio#664]
According to [etc/docker/README.md](https://github.com/jgraph/drawio/tree/master/etc/docker), PreConfig.js looks a environment-dependent configuration file.  However, it is only for EXPORT_URL, PLANT_URL, and DRAW_MATH_URL.

As I asked [before](https://github.com/jgraph/drawio/issues/656), there are many hard-coded URL "www.draw.io" in source repository as the following "git grep" shows:

> $ git grep -l www.draw.io

Or, excludes some concatinated files like *.min.js, *.svg, templates/*.xml by:

> $ git grep www.draw.io $(git grep -l www.draw.io | grep -v -E '(.min.js|.svg|templates.*xml)')

...so that sometimes accessing to www.draw.io happens.

It looks possible to keep to use MY server rather than hard-coded "www.draw.io" because "dev" param in some source-code do the similar purpose.  What I'm proposing here is to isolate host information and development mode.

(Because of there are many hard-coded host info, as the first step for this, I will PR at least HTML viewer URL uses MY server rather than hard-coded "www.draw.io".)

**Comment by davidjgraph** [comment]
Thanks for the PR. We've added a base URL and viewer URL upstream, so the preconfig now looks like in next release:

window.EXPORT_URL = 'REPLACE_WITH_YOUR_IMAGE_SERVER';
window.PLANT_URL = 'REPLACE_WITH_YOUR_PLANTUML_SERVER';
window.DRAWIO_BASE_URL = null; // Replace with path to base of deployment, e.g. https://www.example.com/folder
window.DRAWIO_VIEWER_URL = null; // Replace your path to the viewer js, e.g. https://www.example.com/js/viewer.min.js
window.DRAW_MATH_URL = 'math';
window.DRAWIO_CONFIG = null; // Replace with your custom draw.io configurations. For more details, https://desk.draw.io/support/solutions/articles/16000058316
urlParams['sync'] = 'none' // Disabled realtime

That should mean you can correctly reference your own server.

**Comment by VVD** [comment]
> window.EXPORT_URL = 'REPLACE_WITH_YOUR_IMAGE_SERVER';
What does it mean?
How to configure and use it?
How to install self-hosted server instead https://convert.diagrams.net/node/export ?
How to configure it to save exported file in self-hosted NextCloud?
Can't find answers in documentation.

I'm using draw.war in tomcat9 with plugin for NextCloud 20.

**Comment by davidjgraph** [comment]
The image export server is this project https://github.com/jgraph/draw-image-export2

**Comment by VVD** [comment]
Thanks.

**Comment by GitHubFor122** [comment]
How to deploy https://viewer.diagrams.net? thanks

**Comment by GitHubFor122** [comment]
I built a Plant UML server,   config PLANT_URL ,   but no plantuml on arrange ==> insert ==> Advance.  May I have your help?
