### ISSUE TITLE
Cache server "rt.draw.io" is hard-coded.

### ISSUE THREAD

**Issue by fuminori-ido-m** [jgraph/drawio#665]
Dear,

When I ran [docker container](https://github.com/fjudith/docker-draw.io), I saw the following browser error in development console:

> Access to XMLHttpRequest at 'https://rt.draw.io/cache?alive' from origin 'https://localhost:8443' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains the invalid value 'https:/'.

Unfortunately, "rt.draw.io" HOST is hard-coded in [draw.io](https://github.com/jgraph/drawio) so that it cannot be customized at Dockerfile level.

When I changed source code src/main/webapp/js/diagramly/EditorUi.js

> EditorUi.cacheUrl = (urlParams['dev'] == '1') ? '/cache' : 'https://rt.draw.io/cache';

to

> EditorUi.cacheUrl = '/cache';

...then, it resulted in '404' error so that I am stuck.  I have two questions:

Q1) Can I ignore this error?
Q2) Are there any cache server to compose with my local draw.io in docker?

Thank you for your help!

**Comment by alderg** [comment]
Use urlParams['sync'] = 'none' in PreConfig.js to avoid the 404.

**Comment by ashrafteleb** [comment]
Also, have a look at the [self-contained docker-compose](https://github.com/jgraph/docker-drawio/tree/master/self-contained)

**Comment by davidjgraph** [comment]
This should be fixed in the latest release preconfig.js
