### ISSUE TITLE
[Feature request] TikZ export support

### ISSUE THREAD

**Issue by kevinhikaruevans** [jgraph/drawio#668]
I'm not quite sure if this is the right repo to make this request in, or if mxgraph would be better. Let me know if I should open this in mxgraph instead!

I'd like to use draw.io diagrams in LaTeX without having to convert them to png. If I could export the diagrams to TikZ, I would be able to include them and it would look quite beautiful. 

I wouldn't mind attempting the PR once I get some bearing on the organization of the repo. :)

**Comment by Atcold** [comment]
Was this merged somewhere?

**Comment by davidjgraph** [comment]
It's a duplicate of https://github.com/jgraph/drawio/issues/875
