### ISSUE TITLE
How to remove storage dialogue box when trying to run local . 

### ISSUE THREAD

**Issue by rajeevatos** [jgraph/drawio#669]
if i deploy code on my local tomcat and run url /index.html"offline=1 then first scrren it ask for storage dialgure with the option device and browser . i dont want to make this page first. i want my first page should be default viewer where i can draw images.

kindly help

**Comment by ashrafteleb** [comment]
You can try offline=1&local=1 which will directly ask for filename and select Device as a storage and you can also add url parameter splash=0 to hide the dialog completely
