### ISSUE TITLE
export to image on draw.io, math tyepesetting is wrong

### ISSUE THREAD

**Issue by cdancette** [jgraph/drawio#671]
Since today, the rendering of math typesetting in exported image is wrong: 

On draw.io : 

![image](https://user-images.githubusercontent.com/10550327/70051764-01754700-15d2-11ea-8b0c-e41f92f3c1ca.png)

On png export: 

![image](https://user-images.githubusercontent.com/10550327/70051777-0f2acc80-15d2-11ea-8566-20e4021dea2a.png)

**Comment by davidjgraph** [comment]
Can you attach the input diagram? What browser/version are you using?

**Comment by cdancette** [comment]
I tried online on firefox 70.0.1

I just tried with the desktop version (appimage, on linux):
- The issue is there on 12.3.2. (draw.io-x86_64-12.3.2.AppImage)
- The issue is not there on 12.2.2 (draw.io-x86_64-12.2.2.AppImage). 

With 12.2.2, I was able to export the diagram as a png and the rendering is correct.
I'm attaching you the diagram

**Comment by cdancette** [comment]
[poster-test.zip](https://github.com/jgraph/drawio/files/3916645/poster-test.zip)

**Comment by davidjgraph** [comment]
This should now be working online with 12.3.6 release.
