### ISSUE TITLE
Feature: Create presentation with Drawio

### ISSUE THREAD

**Issue by HeeroYui** [jgraph/drawio#674]
For this we need:

  - Permit to display the pages in fullscreen and go to next with space or left/right
  - Lock the size of the canva (can draw out but not display in fullscreen) to determine the display area, only one for al the show.
  - Create 3 generic background (1 big title / 1 for secondary title / 1 for normal page)
  - No annimation
  - Pdf extraction
 
Is this kind of feature possible ?

**Comment by RobertZenz** [comment]
Partially related is #60.

**Comment by davidjgraph** [comment]
Looks like duplicate of https://github.com/jgraph/drawio/issues/213, I would take the discussion there.
