### ISSUE TITLE
Regression bug: Exporting diagrams to PNG/JPEG with Mathematical Typesetting is broken

### ISSUE THREAD

**Issue by Vitaljok** [jgraph/drawio#675]
Hi!

On current draw.io release (v12.3.7) exporting diagrams to PNG/JPEG with Mathematical Typesetting option is not working any more.

For example, element with math formula `$$\frac{\sqrt{x^2 + y^2}}{cos(\phi)^2}$$`
is correctly shown in UI:
![image](https://user-images.githubusercontent.com/11552222/70324164-6b425a80-1837-11ea-84c7-72aac5375fbd.png)

But when exported to PNG/JPEG math symbols are displayed incorrectly.
![image](https://user-images.githubusercontent.com/11552222/70324286-bceae500-1837-11ea-95d3-12ebd3b78f76.png)

I assume that some fonts are missing, as LaTeX formulae is still processed, but not displayed correctly. 

Thanks!

* EDIT: Exporting not working specifically for PNG/JPEG options

**Comment by alderg** [comment]
Works for me in latest Chrome on macOS. What browser, operating system and versions have you tried? Does SVG export work?

**Comment by Vitaljok** [comment]
Initially I thought that it is back-end problem, but now I see that this feature works completely on front-end since recent draw.io update.

And for me the problem still persists on:
* latest Chrome (79.0.3945.79), Win10
* latest Chrome, Ubuntu 18.04

SVG export works fine on both systems (only minor shifts in text positions).

**Comment by alderg** [comment]
Confirmed for Chrome 79 on Windows and Ubuntu. (Firefox on Ubuntu works.)

**Comment by ashrafteleb** [comment]
Fixed
