### ISSUE TITLE
Cannot move, resize, rotate object on iPad Pro running iOS 13

### ISSUE THREAD

**Issue by dynsight** [jgraph/drawio#676]
On iOS 13 (13.2.3) I cannot move, resize, rotate an object via dragging.  The selected object will move on you a few pixels (8-10).  This makes the tool unusable.

I have tested this on an iPad Pro second generation, iPad Pro 3rd Generation (both 12.9"), and iPad mini (4th generation) all using iOS 13.

This is an issue with the following iOS browsers:

- Safari
- Edge
- Chrome
- Firefox

This has been going on for at least two months (Sept 24th is release date iPad OS).

**Comment by davidjgraph** [comment]
These all work correctly for me. How are you accessing draw.io?

**Comment by dynsight** [comment]
I am accessing it in an iPad Pro 12.9" , iOS 13.2.3.  I have the same problem on Safari, Chrome and Firefox.

I have the issue whether I am using my finger or Apple Pencil.

Charles John Borrelli, PMP, SMC
cborrelli@me.com
609.276.4469

**Comment by davidjgraph** [comment]
No, I mean you're accessing it via www.draw.io? What version does help->about show?

**Comment by dynsight** [comment]
The only way to access it on iPad is via the website, www.draw.io <http://www.draw.io/> com,

The about screen shows I am using v 12.3.8


Charles John Borrelli, PMP, SMC
cborrelli@me.com
609.276.4469

**Comment by dynsight** [comment]
If you want, I can post a video of the behavior I am experiencing.

Charles John Borrelli, PMP, SMC
cborrelli@me.com
609.276.4469

**Comment by davidjgraph** [comment]
Please, that would be useful. I can't repeat with a simple rectangle on latest iPadOS with 12.3.8

**Comment by dynsight** [comment]
https://1drv.ms/v/s!Ao3wfrN3wizrynIsJTtflGl4VtKX?e=mVcQmE <https://1drv.ms/v/s!Ao3wfrN3wizrynIsJTtflGl4VtKX?e=mVcQmE>

You can see that at some point I was able to resize ONCE and then it stopped.  I was hoping it was some sort of SNAP to setting, but I could not find that anywhere.

I did it this way instead of a screen capture because I wanted you to see the pencil and touch inputs.


Charles John Borrelli, PMP, SMC
cborrelli@me.com
609.276.4469

**Comment by dynsight** [comment]
One other (possibly related) issue..

On the iPad, I cannot drag multi-select (draw a window with the pencil or my finger).  When I place my finger or pencil anywhere on the grid and move, it PANS the entire drawing.


Charles John Borrelli, PMP, SMC
cborrelli@me.com
609.276.4469

**Comment by davidjgraph** [comment]
Thanks for the video. It sounds like we're just not detecting that's an iPad. We don't have a pro, but it works for me on a standard iPad, mini or iPhone. If you go to http://useragentstring.com/ in Safari on that iPad, what's your useragent string please?

**Comment by dynsight** [comment]
The link you sent didn’t work, but I got the info from another site:

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15

So I did request the mobile site from Safari and Firefox, but I had the same problem- I could not resize or move items only a few pixels at a time.  ) Version/13.0.3 Safari/605.1.15

Charles John Borrelli, PMP, SMC
Cborrelli@me.com
609.267.4469

**Comment by davidjgraph** [comment]
that's the user agent on your iPad, that the OS is Mac OS X? No wonder we don't recognise it, we'll have a think what we can do here, thanks for the detailed help.

**Comment by davidjgraph** [comment]
https://stackoverflow.com/questions/58019463/how-to-detect-device-name-in-safari-on-ios-13-while-it-doesnt-show-the-correct isn't a stable solution.

The only workaround, currently, would be to not request the desktop site.

**Comment by davidjgraph** [comment]
The iPad mini in Safari, what user agent does it report?

**Comment by dynsight** [comment]
I actually did that (see earlier email) and I still have the problem. I will try a couple of other options with Draw.io before I move on to another tool.

Charles John Borrelli, PMP, SMC
Cborrelli@me.com
609.267.4469

**Comment by davidjgraph** [comment]
I would switch tool, we can't work around a device with a purposefully misleading user agent.

**Comment by dynsight** [comment]
Mozilla/5.0 (iPad; CPU OS 13_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Mobile/15E148 Safari/604.1

That is iPad Mini... and it works very will

Charles John Borrelli, PMP, SMC
Cborrelli@me.com
609.267.4469

**Comment by dynsight** [comment]
I think you closed prematurely...

Mozilla/5.0 (iPad; CPU OS 13_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/78.0.3904.84 Mobile/15E148 Safari/604.1

That is the user agent for chrome on my iPad Pro, but that browser exhibits the same problem.  It may be a hardware issue with iPad Pro, but it is NOT an issue with the mobile vs. desktop site.  

I figured you would want to document it properly



Charles John Borrelli, PMP, SMC
Cborrelli@me.com
609.267.4469

**Comment by davidjgraph** [comment]
And you've documented the cases very well. It's more closed because, as it stands, the user agent is misleading and our capability check doesn't work. We can re-open and mark as help wanted, but we have limited resources, we don't want to disappear down a rabbit hole of apple's making.

**Comment by alderg** [comment]
iPad Mini with iOS 13.x works for me. @dynsight Does https://12-3-0-dot-drawdotio.appspot.com/ (draw.io v12.3.0) work on the iPad Pro and iPad Mini for you with iOS 13.x?

**Comment by ThomC** [comment]
I had the same issue and was able to fix it by changing safari settings to „Request Desktop Website -> All Websites“ from on to off. 

This changes the user agent string 

from:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Safari/605.1.15

to:
Mozilla/5.0 (iPad; CPU OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Mobile/15E148 Safari/604.1

**Comment by alderg** [comment]
Anyone with an iPad Pro: Do you see a green box at https://jsfiddle.net/31oq8tLu/?

**Comment by ThomC** [comment]
> Anyone with an iPad Pro: Do you see a green box at https://jsfiddle.net/31oq8tLu/?

Yes, in the lower right quarter.

**Comment by alderg** [comment]
We've deployed a (possible) fix in draw.io 12.4.4. Can someone check on an iPad Pro with "Request Desktop Website" turned on?

**Comment by ThomC** [comment]
> We've deployed a (possible) fix in draw.io 12.4.4. Can someone check on an iPad Pro with "Request Desktop Website" turned on?

Works for me with enabled desktop website request (v12.4.5).

**Comment by alderg** [comment]
Awesome, thanks for the reports!

**Comment by alderg** [comment]
Fixed in 12.4.6.
