### ISSUE TITLE
Create a specific size grid

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#677]
Generate NxM grid such as  3x3, 9x9 etc. A current user's solution is adding 9 squares for e.g. 3x3 grid as shown in the attachments below. https://webapps.stackexchange.com/questions/136935/how-to-draw-a-grid-size-n-x-m-in-draw-io

![separate squares](https://user-images.githubusercontent.com/44292306/70515669-025c2a80-1b36-11ea-8566-cb031e4e8a59.png)

![created grid](https://user-images.githubusercontent.com/44292306/70515732-16a02780-1b36-11ea-8385-a09ecd70b303.png)

**Comment by ttpro1995** [comment]
Upvoted, that is my question on stackexchange :3

**Comment by wayne1512** [comment]
Hey, any chance we can re-open this, it would be an incredibly useful feature.
