### ISSUE TITLE
Background images are not visible after import

### ISSUE THREAD

**Issue by oanalavinia** [jgraph/drawio#679]
**Steps to reproduce:**

1. Create a new diagram
2. Add some shapes, text
3. Select a background image
4. Click on File > Export as > XML > Uncheck 'Compressed' > Export
5. Create a new diagram
6. Click on File > Import from > Device
7. Select the new exported diagram > Import

**Expected results:**
The diagram appears just like in the source diagram (with the shapes, text and the background image).

**Actual results:**
The background image is missing.

**Environment:**
Fedora 28, Chromium Version 71.0.3578.98

**Comment by ashrafteleb** [comment]
Cannot reproduce on MacOS + Chrome
