### ISSUE TITLE
confusing UX with connector lines on layers other than the objects they connect

### ISSUE THREAD

**Issue by cabbey** [jgraph/drawio#68]
[sample document](https://www.draw.io/?chrome=0&lightbox=1&highlight=0000ff&edit=_blank&layers=1&title=Untitled%20Diagram#R7VdNj5swEP01HLsCDCE5BrJtL5UqpVK3RwccsGpwZJyv%2FfUdYpsvk2w2VbWX7mFlP8bj8XvPs14HJeXpi8C74hvPCHN8Nzs5aOX4fjAP4HcDnBWAQl8BuaCZgrwOWNNXokFXo3uakXoQKDlnku6GYMqriqRygGEh%2BHEYtuVsuOsO58QC1ilmNvqTZrJQ6Dx0O%2FwroXlhdvZc%2FWWD09%2B54PtK7%2Bf4aHv5UZ9LbHLp%2BLrAGT%2F2IPTsoERwLtWoPCWENdQa2tS6z1e%2B6roPmO31SX4UtMprU7YglbwnD7LyLHW98mw4OhZUkvUOp838CDZwUFzIksHMg6HOQIQkpxGpXRVee2RwEuElkeIMIXrBQpOkTdS649hJ4hkii54cM41h7YK8zdwdGQb61NMMBBYD8QcwgPwPpMC3KEjUdaO8Ake5E6e57arQSuj4MwZL44weYJg3w8RgkKcHW%2BSTKls2Nx1mKcN1TdMh%2B1CTOL%2FAxDWTX83kKWymJypfTByMuy9qG5JZ7aE7o6al5nuRksF1kVjkRPb8Y%2Bva0y2ckM1ggjAs6WFYxJSWeofvnEJ51y4OCkZuULXrRX3BRnm8YGS%2FxSiROrGV6OKs9tR3mW1hm80Q3Wme7sWBZK3Atw1wr5QfJZIXjciNHlQJjfvkONEVlYA9fO6F7ZqA%2BkbBs5GtkHu7rnDahp1JVAWPWmb2Rn%2Fy39ufoon%2BdE%2FXqYFg%2BVAziq53o%2BjOdjT7347%2BQTuaW1ZYWV6AP%2BtyKLMgNX3Fm0tAo7S%2BURAdxk64AgQzmleNS0A%2FIgBongcUHp5L%2FaGkWdasjxneEBa3z8mEMy4u%2B5oH5Y0Hhn4W60pa3w98E007Qif65D6582D%2Bd%2FKbEL7d1uSdisC0ewWr8O4%2FDfT8Bw%3D%3D).

You should see three layers.

Things: has A and B rectangles.
Connections 1: has two lines C and C2
Connections 2: has one line D

If you turn off the layer for either connection layer you will see the base things and the connections you specifically want to see. If you turn off both connections layers you will only see the base objects. If you turn off the base layer and connections 2, you ONLY see C2 (should see C). Similarly if you turn off things and connections 1.. nothing.

So in one view (things + connections 1) the arrow labeled D is clearly part of connections 2 (because it's gone). But if you invert the layers to view ONLY connections 2, it disappears.

Looking at arrows C and C2 you can see a better example of where I started in the real document I'm working on... a seemingly random subset of the things on the connections 1 layer are AWOL if that's the only layer that is visible... but they re-appear if you add other layers that they aren't on, as evidenced by them disappearing if you turn off the layer you think they should be on.

In boiling this down to a simple test case above, it's become obvious these awol lines are nominally connected to the objects they connect and are going away when either of the things they are attached to go away. The other lines that don't disappear aren't connected to these objects. It's a very confusing user experience.

**Comment by mararad** [comment]
The issue reproduced in draw.io online (Chrome Version 74.0.3729.131 (Official Build) (64-bit)

![layers](https://user-images.githubusercontent.com/44292306/60100170-7443e180-9759-11e9-8d24-99f6c59a56eb.gif)

**Comment by davidjgraph** [comment]
Still an issue?

**Comment by mararad** [comment]
Hi, 

the issue is still present in the 13.10.2 as shown in the video above (in Chrome Incognito Version 87.0.4280.66 (Official Build) (64-bit) and in FF

**Comment by axydraw** [comment]
I am not quite sure if my bug is the same as this one or different.
My detected bug is easy to explain:
- Layer 2 with a big rectangle is locked.
- On layer 1 (non locked) I like to draw just a line inside the visible rectangle from layer 2.
- I cannot draw the line as I want, because the line always tries to connect to layer 2 rectangle.
An inconvienient workaround is to hide layer 2 during editing layer 1.
How can I really disable the connection point "catching" on layer 2?

**Comment by axydraw** [comment]
I just detected, that this is also occuring on the same layer.
Drawing a line freely inside another object (e.g. rectangle) is not possible,
because the line tries always to connect to the object.
But both effects (on same or different layers can be avoided, when all related objects are locked (Ctrl+L)

**Comment by alderg** [comment]
Selecting the object and unticking "Connectable" should work:
<img width="350" alt="Screenshot 2021-08-03 at 14 06 49" src="https://user-images.githubusercontent.com/921200/128012767-cc0c5def-ce66-4ed8-b166-d1b89b6f1ea7.png">

**Comment by axydraw** [comment]
Thank you very much.  My PEBCAK!
Is there a use case where elements on locked layer need to be connected from other layers?
