### ISSUE TITLE
[Feature request] Support Bitbucket storage

### ISSUE THREAD

**Issue by aprasadh** [jgraph/drawio#685]
Like Github, Gitlab integration, please support bitbucket as storage medium.

**Comment by sashokbg** [comment]
Hello, I would like to reopen this issue with the hopes of bringing some attention to it and finding someone savvy enough to help us get this feature going.

Would implementing bitbucket storage support be similar to the one for gitlab ? https://github.com/jgraph/drawio/pull/458/commits/ae0c1f92a94325a92bf168d391ca1445d774328e 

Can someone from the core team produce a documentation for developers explaining how to integrate any generic storage provider with OAuth2 ?

**Comment by davidjgraph** [comment]
Closing due to lack of interest from core team.
