### ISSUE TITLE
[Feature request] Make tool windows like Layers or Outline dockable on the right bar

### ISSUE THREAD

**Issue by cypherbits** [jgraph/drawio#687]
Make tool windows like Layers or Outline dockable on the right bar so we can for example have the layers in a more handy way.

![imagen](https://user-images.githubusercontent.com/10424900/71017689-db31ca00-20ee-11ea-947f-2138c0964d10.png)

**Comment by coppolaop** [comment]
That would be very useful for me too.

**Comment by cypherbits** [comment]
This issue is still valid.

**Comment by davidjgraph** [comment]
Closing due to lack of interest from the core team.

**Comment by cypherbits** [comment]
Seriously? Can you close a feature request/proposal just because core team is not interested right now???

**Comment by coppolaop** [comment]
It's better to leave it open for more users to show interest, maybe that will change the mind of the development team. this also avoids the creation of duplicate issues. I didn't create this call myself because it already existed and I'm very interested in this feature.

**Comment by zaroth** [comment]
As somebody whose workflow would also be improved by having this feature, what are the biggest blockers to implementing this? Does the concept of dockable windows currently not exist in the current UI framework draw.io uses and would have to be implemented from scratch? Is this not aligning with the vision of the core team? What are the limitations?

**Comment by davidjgraph** [comment]
We don't have a UI framework, it would have to be implemented from scratch.

**Comment by davidjgraph** [comment]
Isn't the issue here that people just don't want windows at all? Just have everything docked and cannot be undocked.

**Comment by cypherbits** [comment]
We still want this. Maybe we need a UI stack to dock and undock tool windows.

**Comment by davidjgraph** [comment]
What is the ETA on this?

**Comment by terefang** [comment]
+1

**Comment by terefang** [comment]
maybe to post something constructive.

the right bar could be implemented as an accordion similar to the left bar.

so the "Tabs" of Diagram/Style/Text/Arrange (+Layers) become Accordions instead.

the good thing is that the code from the left bar could be reused.

**Comment by notyourfather** [comment]
This is rejected because: ....
Maybe explain to users who are used to this from pretty much all competing tools why your tool cannot support this or why users are stupid for expecting this.

Personally I have been dragging the layers window around for a few hours now as I try and edit a many layered document, being able to push it to the side and not have it obstruct controls, the document I am working on or well anything else would be a great help.

**Comment by terefang** [comment]
ping

is this finally declined ?

**Comment by terefang** [comment]
any updates when this feature will be available ?

**Comment by neut** [comment]
+1 vote for this feature in case anyone wants to pick it up at some point :)

**Comment by chadbeaudin** [comment]
I would also REALLY love to see this feature.

**Comment by terefang** [comment]
again cheers from me

**Comment by starikcetin** [comment]
This is an essential feature.

Also, what is this all about? Where is the abuse?
![image](https://github.com/jgraph/drawio/assets/21353964/f6462b9c-7634-42d6-bb10-d4720480ddbf)

**Comment by terefang** [comment]
i can only second that

**Comment by cedricseah** [comment]
Upvote: I don't care about making windows dockable, why not just embed it within the Diagram tab of the right panel? The floating dialogs (constrained to the draw.io window boundaries) just isn't very sensible. Even Gimp has implemented single window mode more than a decade ago, and it is the default behaviour today

**Comment by dibley1973** [comment]
Why was this closed? This is a really useful feature request.
