### ISSUE TITLE
[Feature Request] html link with preview, rich preview

### ISSUE THREAD

**Issue by TackerTacker** [jgraph/drawio#692]
Most modern web apps have the feature that they show a preview of a link pasted into the app, something like this

- [open graph protocol](https://ogp.me/)
- [ example ](https://codingislove.com/generate-link-preview-webapp/)
- [ example ](https://guteurls.de)

A feature like that would greatly improve Draw.io in my opinion and is especially useful for mind maps

**Comment by davidjgraph** [comment]
This isn't possible since we don't have control over the storage options and we don't store anything ourselves.
