### ISSUE TITLE
App installed through Flatpak does not show in the Open With list

### ISSUE THREAD

**Issue by Melvasul** [jgraph/drawio#695]
![Screenshot from 2019-12-26 22-13-37](https://user-images.githubusercontent.com/11297488/71490838-63217d80-282d-11ea-9906-3f0ee3c29204.png)

Hello there
Fedora 31 on a Thinkpad E485 (Ryzen APU powered) here, latest kernel
I've installed Draw.io using Flatpak, as from here: https://flathub.org/apps/details/com.jgraph.drawio.desktop
simply because it's the easiest and best way possible.

I really enjoyed its access to the folders and files in /home/ (something not always pre-available in many flatpak apps) but there's a problem:
When I go and try to select draw.io as the app to open the *draw.io files the app is simply not there :/

I've seen that all the other apps I've installed through flatpak are there though :|

Thanks in advance,
have a nice day :)

**Comment by davidjgraph** [comment]
We're not the authors of the Flatpak integration, probably better post this issue at https://github.com/flathub/com.jgraph.drawio.desktop/issues
