### ISSUE TITLE
Multicolor lines

### ISSUE THREAD

**Issue by Tremelune** [jgraph/drawio#697]
It would be great if a line stroke could have a primary and secondary color. Many wiring schematics use wires with a stripe, and this would allow for diagrams that closely match physical reality.

There are only so many colors of vinyl tape and heat shrink...

**Comment by Tremelune** [comment]
One means of implementation might be to just have two lines that share waypoints and style (for the most part) that are separated by 1 on the Z-axis. At widths of 1px, the front line is dotted, at 2px, the front line is 1px, at 5px the front line is still 1px and centered, at 6px the front line is 2px, etc etc...

**Comment by Tremelune** [comment]
Like super great. It would be great.

**Comment by Tremelune** [comment]
Was this closed because it was completed or because it's a duplicate issue or because I'm irritating?

**Comment by MontrealPaul** [comment]
> 
IMO, none of the above, [Tremelune](https://github.com/Tremelune), because I'm looking for this exact thing! Did you find it?

**Comment by jtsalas11** [comment]
I use two lines, bottom line is the base color of the wire in the schematic in 2 or 3 pt size, and a dashed line overlayed on top as the secondary color in 1pt font. Works pretty well and gives good indication of the base color (ex: red/with black stripe vs black with red stripe), but is a little tedious to draw each line twice and mess with thickness.

**Comment by bitboy85** [comment]
Using two lines on top is a workaround if you use straight lines. If you want curved ones its hard to match them.
so +1 for this feature request

**Comment by konradmoesch** [comment]
@davidjgraph could you please explain why this was first closed as "completed", then as "not planned" / "declined"? Thanks!

I am also looking for multi-colored lines, and was not able to find any feature allowing me edit a line's fill behaviour in such a way, so I think the issue still persists. But please correct me if I am wrong

**Comment by davidjgraph** [comment]
It is closed as not planned / declined because it's not planned and has been declined.

**Comment by 15frogs** [comment]
Multicolor lines are very much possible using the line type "wire".
If you select the line type "wire" in the dropdown menu shown below, the "fill" option becomes available, where you can select a second color. The line is striped automatically with both selected colors.

<img width="1308" height="640" alt="Image" src="https://github.com/user-attachments/assets/0bea2125-c223-48b5-a065-f99f8c1280d5" />
