### ISSUE TITLE
Custom Library from private Gitlab

### ISSUE THREAD

**Issue by schabert** [jgraph/drawio#700]
I'm trying to create a URL with parameters that uses preconfigured libraries and also a standard file.

Authorizing with the private Gitlab instance and opening a specific .drawio file worked fine.

`https://www.draw.io/?gitlab=https%3A%2F%2Fcode.companyname.com&mode=gitlab&gitlab-id=IDofGitlabInstance#Aorganization%2Fdraw.io%2Fmaster%2Ftemplate.drawio`

Unfortunately, I can't get the custom library integration into the URL.

I added the custom library via the UI and copied the path from the application store.

As described in the documentation
https://desk.draw.io/support/solutions/articles/16000042546-what-url-parameters-are-supported-

I then added this path to Draw.io using the clib parameter.
`https://www.draw.io/?gitlab=https%3A%2F%2Fcode.companyname.com&mode=gitlab&gitlab-id=IDofGitlabInstance&clib=Aorganization%2Fdraw.io%2Fmaster%2custom_librabry.xml#Aorganization%2Fdraw.io%2Fmaster%2Ftemplate.drawio`

Unfortunately I do not get an error message, nor is the library opened.

Does anyone have an idea or know why it does not work?

**Comment by davidjgraph** [comment]
Is the path to the clib is path that you can paste into another browser tab and it loads correctly?

**Comment by schabert** [comment]
Hi, David,
no the path is not loaded under CLIB I want to set the path to the "Gitlab" folder so
Arepository/project/custom-lib.xml

The library should only be available to people who have access to the gitlab repository (as it already works with the location hash)
