### ISSUE TITLE
[IBM VPC] Fixes problematic usability issue

### ISSUE THREAD

**Issue by jaywarfield** [jgraph/drawio#702]
Known issue has been the box tag (upper left corner of each box) can become separated and has to be repositioned during diagram creation. The attached zip will fix this issue in an acceptable manner and includes some additional style enhancements.  

Here is an example of the intended outcome (go to draw.io link at top) after applying the attached zip: https://github.com/ibm-cloud-architecture/ibm-cloud-stencils/blob/master/README.md

For usability and maintainability,
we are requesting to remove old vpc boxes from IBM / VPC and add new vpc boxes to a new IBM / Boxes

A. For new boxes in attachment:
1. Add contents of Boxes.xml to IBM / Boxes 
    Note that the tags in these boxes are already set up to point to img/lib/ibm/boxes
2. Add contents of boxes.zip to img/lib/ibm/boxes
  
B. For updated template in attachment:
1. Replace ibm_vpc_architecture template under draw.io Cloud with ibm_vpc_architecture.drawio in attachment.
    Note that the box tags in ibm_vpc_architecture.drawio in attachment are already set up to point to img/lib/ibm/boxes

C. Remove previous boxes in IBM / VPC:
1. Remove Cloud Universe box
2. Remove IBM Cloud box
3. Remove VPC box
4. Remove Region box
5. Remove Zone box
6. Remove Subnet box
7. Remove Security Group box
8. Remove Classic Infrastructure box
9. Remove Other Group box

D. Remove previous box tags in IBM / VPC:
1. Remove IBM Cloud tag
2. Remove VPC tag
3. Remove Region tag
4. Remove Zone tag
5. Remove Subnet tag
6. Remove Classic Infrastructure tag
7. Remove Enterprise tag
8. Remove Public tag

Let me know if there are any problems or questions.

Thanks!
Jay

[IBM_VPC_Boxes_Updates_Final7.zip](https://github.com/jgraph/drawio/files/4121043/IBM_VPC_Boxes_Updates_Final7.zip)

**Comment by jaywarfield** [comment]
Classic group was missing from original attachment IBM_VPC_V2Updates.zip so please use this IBM_VPC_V2Updates_UseThisZip.zip that includes Classic group.  Thanks! 

[IBM_VPC_V2Updates_UseThisZip.zip](https://github.com/jgraph/drawio/files/4041222/IBM_VPC_V2Updates_UseThisZip.zip)

**Comment by jaywarfield** [comment]
Just some final tweeking on the last zip attached named Final5 until you publish these changes.  I use multiple diagram tools and draw.io has become my favorite in part because of the fine tuning I can do.  I can see advantages of how other clouds are set up in draw.io, what are the advantages if we had resources to possibly look into how we are set up in draw.io in the future?

**Comment by kutya** [comment]
"Known issue has been the box tag (upper left corner of each box) can become separated" please, can you describe how can we reproduce this?

**Comment by kutya** [comment]
Also, is the image top left offset intentional in the file you sent us?
![image](https://user-images.githubusercontent.com/2485177/73269197-a9774d00-41dc-11ea-84d0-30c6c492fdb4.png)

**Comment by jaywarfield** [comment]
Hi Kutya, our previous implementation was containers with the box tag dragged onto the upper left corner of the boxes, when the box is first added to the palette the tag is in position in the box but as the box is resized and repositioned there is nothing to keep the tag in place, some of the boxes that had container=1 set became container=0 for some reason which may have contributed to the tag not staying in place also.  I was aware of the issue since the beginning and just getting around to fixing it with the attached zip.

**Comment by jaywarfield** [comment]
For the image offset, I did try to get the image all the way into the upper left corner with no white space, then I found some white space included around the edges of the image that we removed, so the included box images have no white space around the edges of the image, but the image is still offset.  In other words, I couldn't find a way to get the image all the way into the upper left corner so I decided it looks good with or without the offset.  One way to fix the image offset is with javascript which we may look at later.  If there is a simple way to get rid of the image offset that is fine too.  I set the text position to match the vertical offset of the image but the text would look fine if there was no image offset also.  Either way is fine with or without the image offset, but let me know if there is a way to get rid of the image offset.  Thanks.

**Comment by jaywarfield** [comment]
If there is a way to get rid of the image offset which requires additional changes perhaps we could leave the image offset and revisit at a later date and you can let me know how I can get rid of the image offset.  Thanks.

**Comment by jaywarfield** [comment]
Since the changes in this zip will help users now and since extra effort may be required to remove the image offset I would leave any changes beyond what is in this zip for a future time and you can help me understand how best to fix it later or I can continue reading the documentation.  The changes in this zip look good and we can continue building from there.   It is up to you.
 
Since I'm specifying "top left" in the styles, if the image offset is something that can be changed in draw.io I can open a separate issue for that if you want but I was assuming that draw.io has to leave room for the border width that can be increased and we don't need wider borders than what is already in this zip.  

Thanks!

**Comment by egrimate** [comment]
I've fixed the offset and cleaned up the stencils somewhat. Working on them currently. There were two stencils that needed redrawing.

**Comment by jaywarfield** [comment]
Awesome!  Thanks!

**Comment by jaywarfield** [comment]
I'm curious what was cleaned up and what two stencils needed redrawing or I can wait until published.  

I vary the width of borders slightly to highlight the relative importance of boxes, so I could see where fixing the image offset might be a bit different between boxes if a wider border overlaps the image or maybe that wasn't a problem.   

The text on the boxes with images will still probably be in a good position after fixing the image offset.  The text for ACL on the Subnet box will probably look a bit lower after fixing the image offset since the name of the ACL is intended to be on a second line under the name of the Subnet in the same textbox, so the entire Subnet text could potentially be raised a bit so the ACL doesn't look too low, but then again the ACL is probably still in a good position after fixing the image offset.  

Just trying to visualize what might have needed changing after fixing the image offset.  It will be great to have the image offset fixed as the image could potentially be confused as to what box it belonged to (the border above the image or the border of the nested box under the image).

Thanks!

**Comment by egrimate** [comment]
![image](https://user-images.githubusercontent.com/2485177/73430181-b65f8200-433d-11ea-92b9-9c1ac934d634.png)

IBM Cloud and VPC were redrawn:
![image](https://user-images.githubusercontent.com/2485177/73430248-ddb64f00-433d-11ea-94a9-3a162bafee1b.png)

As for the cleaning, unnecessary styles were removed. Also I wrote the group shapes (boxes) in JS, so functionality should be improved. You will be able to choose the box image from the properties menu:
![image](https://user-images.githubusercontent.com/2485177/73430399-443b6d00-433e-11ea-8e91-726ee41c1a77.png)
But you'll still need manually to change color. It's a technical limitation. Either you change box type and manually change color or the other solution would be to automatically change color on box type change, but then the color would be fixed, so you coulnd't change it manually. I think the first option gives you more freedom.

**Comment by egrimate** [comment]
I also changed the aspect as you used 25x25 in the shape, but the SVGs were 64x56.5 so they were stretched somewhat.

**Comment by jaywarfield** [comment]
Wow, awesome!  I was thinking the Subnet and ACL being on separate lines could potentially be changed to Subnet:ACL (a colon in between and on the same line) so the ACL won't get in the way of the nested box below it.  The intent is the user would replace Subnet with the cidr or name of the Subnet and the user would replace ACL with the name of the ACL, and let the user decide if they would prefer to put the ACL on a second line.

**Comment by jaywarfield** [comment]
I realized that the SVGs ended up not being quite square so thanks for changing the aspect!  The selection with a Box Type property will be great!  And manually changing the color is fine.  Thanks!

**Comment by egrimate** [comment]
The reworked boxes will be in the next release. Please, redraw the template using the new content when possible. I'll close this issue and please submit a new one for the template.

**Comment by jaywarfield** [comment]
Awesome, thanks!!!  I was planning to revisit the image offset later but this is so much better visually to have the image offset fixed now as well as to prevent the need to migrate later!!!

**Comment by jaywarfield** [comment]
Changes published this weekend look awesome!  I converted several secondary diagrams using Edit Style with cut-and-paste to get them quickly converted (realizing that the containers won't be set up properly since the objects were placed before some of the boxes were containers).  The Subnet:ACL worked out well.  This week I will convert the template published to draw.io from scratch so it will be created properly with all containers and will test out: 1. expansion problem (issue 723), 2. make sure objects stay in container (issue 724), and 3) revisit whether the 3 dashed groups should be a container.  These changes are really excellent!  Thanks!
