### ISSUE TITLE
[Feature Request] Diagonal Fill

### ISSUE THREAD

**Issue by volcbs** [jgraph/drawio#705]
As the title said, it'd be more helpful to draw something if you can fill the diagonal fill for your shape.

**Comment by davidjgraph** [comment]
Maybe rough.js can help.

**Comment by volcbs** [comment]
Wait, sorry for (very) late reply. I meant something more professional like [AutoCAD's diagonal fill.](https://allaboutcad.com/wp-content/uploads/2011/11/autocad_tips_easy_hatching-1.jpg)
