### ISSUE TITLE
SVG Export - exporting truncate text in tag <text>

### ISSUE THREAD

**Issue by pierrelapalu** [jgraph/drawio#706]
Hello,

I noticed that recently the SVG exports the truncated text to the tag <text>. 

For example, I have a box containing the following text: "test test". In the SVG file the <text> tag appears like this:

`<text x="60" y="34" fill="#000000" font-family="Helvetica" font-size="12px" text-anchor="middle">test...</text>`

Can we have this reversed? Or at least a new option on before exporting to avoid this? Because in my company we have a lot of Draw.io users, and they publish their flowcharts inside our intranet that runs on WordPress. We made a finder that connects the flowcharts to post contents that are really useful for our business. But they make the query based on the contents of this <text> tag, and the new flowcharts aren't able to be connect to other because the text is missing characters, we have an incomplete information to find. The <text> tag content is also an advantage to use because it is the plain text, clean of any formatting from draw.io or third-party applications.

**Comment by ashrafteleb** [comment]
Can you share the source draw.io diagram and the options used to export to SVG

**Comment by davidjgraph** [comment]
The full text is still in the file. The text is just a fall-back for SVG viewers that don't support foreign objects. If you look at the SVG you will see where the text now lives.

**Comment by CoolandHot** [comment]
Please open the exported SVG file with Chrome or Firefox, run the following codes in the console.

    let svg = document.querySelector("svg");
      svg.setAttribute(
        "xmlns:inkscape",
        "http://www.inkscape.org/namespaces/inkscape"
      );
      svg.setAttribute(
        "xmlns:sodipodi",
        "http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
      );
    
      document
        .querySelectorAll("foreignObject div div div")
        .forEach((foreignObject) => {
          let textHTML = foreignObject.innerHTML.replaceAll(
            ` xmlns="http://www.w3.org/1999/xhtml"`,
            ""
          );
          textHTML = textHTML.replaceAll(
            `<sub>`,
            `<tspan style = "font-size:65%;baseline-shift:sub">`
          );
          textHTML = textHTML.replaceAll(`</sub>`, `</tspan>`);
          textHTML = textHTML.replaceAll(
            `<sup>`,
            `<tspan style = "font-size:65%;baseline-shift:super">`
          );
          textHTML = textHTML.replaceAll(`</sup>`, `</tspan>`);
          textHTML = textHTML.replaceAll(
            `<b>`,
            `<tspan style = "font-weight:bold">`
          );
          textHTML = textHTML.replaceAll(`</b>`, `</tspan>`);
          let lines = textHTML.split("<br />");
          textHTML = "";
          lines.forEach((line) => {
            textHTML += `<tspan class="line">${line}</tspan>`;
          });
    
          let textNode = foreignObject.parentNode.parentNode.parentNode.nextSibling;
          textNode.innerHTML = textHTML;
          textNode.querySelectorAll(".line").forEach((line) => {
            line.removeAttribute("class");
            line.setAttribute("sodipodi:role", "line");
          });
        });
    console.log(document.querySelector("svg").outerHTML.replaceAll(`xmlns=""`, ""));
    alert("Please copy from the console.");


It should fix the <text> tag, and will display nicely in the inkscape as well.
