### ISSUE TITLE
[IBM VPC] Replace connectors

### ISSUE THREAD

**Issue by jaywarfield** [jgraph/drawio#707]
For usability and maintainability,
we are requesting to remove old connectors from IBM / VPC and add new connectors to a new IBM / Connectors

A. For new connectors in attachment:
1. Add contents of Connectors.xml to IBM / Connectors

B. Removed previous connectors in IBM / VPC:
1. Remove Bidirectional Connector
2. Remove Directional Connector
3. Remove Nondirectional Connector

Let me know if there are any problems or questions.

Thanks!
Jay

[IBM_VPC_Connectors_Updates_Final7.zip](https://github.com/jgraph/drawio/files/4121047/IBM_VPC_Connectors_Updates_Final7.zip)

**Comment by jaywarfield** [comment]
Just some final tweeks on the last zip attached named Final6 until you publish these changes. Thanks!

**Comment by egrimate** [comment]
Will be in next release

**Comment by jaywarfield** [comment]
Awesome, thanks!!!
