### ISSUE TITLE
package.json correct version?

### ISSUE THREAD

**Issue by Trexon25** [jgraph/drawio#710]
Hello I have a question about the package.json under `drawio/src/main/webapp/package.json`. Is this file up to date? Because the version is `11.3.0`. When I build the Draw.io Desktop app the Version in the control panel of Windows is not correct. When I change the version it shows the correct version in the control panel.

![drawio_control_panel](https://user-images.githubusercontent.com/35470572/72418842-ea527900-377b-11ea-8e47-713ca025fcfb.png)

![drawio_version](https://user-images.githubusercontent.com/35470572/72418849-ef172d00-377b-11ea-8b79-fcac9a95f097.png)

**Comment by davidjgraph** [comment]
Yeah, that's out of date. We build using the desktop wrapper project, We'll update this in the next release.
