### ISSUE TITLE
Add icons and support for Software & Systems Process Engineering Metamodel (SPEM)

### ISSUE THREAD

**Issue by ThomasOwens** [jgraph/drawio#716]
Specification: https://www.omg.org/spec/SPEM/About-SPEM/

**Comment by prateekrastogi** [comment]
If only we would had a Fairly Orchestrated Type Definitions import systems for multitude of such notation functions.

**Comment by ThomasOwens** [comment]
I'm interested in following up on this - I see it's been assigned and put into a project board. I'm curious if any work has started. If it hasn't or if there is something that I can help with, I'm interested in seeing what is required to create such stencils. I didn't see a guide or information anywhere - I'm not sure if I have the knowledge or skills to help out, but if I do, I'd be interested. I'm just not sure how this project works.

@egrimate - Since you self assigned this, can you provide any info? Thanks!

**Comment by ThomasOwens** [comment]
@davidjgraph @egrimate There hasn't been activity and stalebot has tagged this as wontfix. Are there any updates on this? Or information about how to contribute this myself?

**Comment by ThomasOwens** [comment]
This has been open for over a year. Are there plans to add these icons as a stencil set or to provide information on exactly what is needed for someone to submit a stencil set and have it accepted?

**Comment by davidjgraph** [comment]
No, there are no plans.

**Comment by bum2free** [comment]
draw.io is a great tool, What a pity if it is not supported~~
