### ISSUE TITLE
Large and off-center UI components on Firefox/Ubuntu

### ISSUE THREAD

**Issue by abacef** [jgraph/drawio#717]
I am using Draw.io on Ubuntu using Firefox, and I noticed some drop-down boxes and text boxes are a little larger then they should be, and they are off-center sometimes:
![crowded](https://user-images.githubusercontent.com/21362235/72687391-4f370780-3acb-11ea-9a55-e9c8ca192dc9.png)
The above is a snapshot of the right sidebar of an arrow when added to the canvas. No functionality is hindered or anything, it is just a little more cumbersome to use the sidebar. I was not sure if the development team was aware of this or not.

**Comment by alderg** [comment]
@abacef Should be fixed. Can you check?

**Comment by abacef** [comment]
Looks good. Thanks.
