### ISSUE TITLE
Can't find cell variable

### ISSUE THREAD

**Issue by rabpeter** [jgraph/drawio#718]
https://github.com/jgraph/drawio/blob/1087d46b8843a86569f6c8f56f6bf1ad2098ba8e/src/main/webapp/js/mxgraph/EditorUi.js#L550

**Comment by rabpeter** [comment]
@davidjgraph Why did you close this issue? The problem does not occur in the application, but there is no definition for var cell.

**Comment by davidjgraph** [comment]
We'll fix this upstream in the dev repo, thanks for the report.
