### ISSUE TITLE
Put embed documentation in github markdown

### ISSUE THREAD

**Issue by andersruneson** [jgraph/drawio#72]
I'm using [How-does-embed-mode-work](https://desk.draw.io/support/solutions/articles/16000042544-how-does-embed-mode-work-) and it's great documentation, but I'm a bit worried that changes is difficult to track, what new features are introduced in which version of draw etc.
One way to simplify would be to put this documentation in a markdown file on github instead.

**Comment by davidjgraph** [comment]
It'd certainly make sense. The advantage of desk.draw.io is it's full ticketing system, so people typing out questions get contextual suggestions from keywords. I've thought about putting it all into Github and using the Freshdesk API to populate desk from a cron job, but it's a lot of work. Possible, maybe could use that one as test case. You're best chance of it happening is a PR with an API call to Freshdesk showing how we can sync it up :).

**Comment by andersruneson** [comment]
I think I understand what desk.draw.io is useful for, I recently googled some issues I had with USING the draw.io editor and found related articles on desk.draw.io. 
But I would argue that one could separate documentation for developers and users. Developers does have another approach to finding the information they need compared to regular users.
