### ISSUE TITLE
Opening a diagram from OneDrive (on SharePoint) does not show list of shared libraries

### ISSUE THREAD

**Issue by Ignatnaumovich** [jgraph/drawio#720]
My diagrams are located in a shared libraries at OneDrive on SharePoint and until recent time I was able to see shared libraries to select a diagram:
![image](https://user-images.githubusercontent.com/42861768/72703217-1435e200-3b66-11ea-8d6a-78dfd7598654.png)

Starting from weekend (01/18/2020) until now (01/20/2020) I cannot see any shared libraries in attempt to open my diagrams.

It's a blocker for me.

![image](https://user-images.githubusercontent.com/42861768/72703327-5b23d780-3b66-11ea-8d65-babd15e78ea9.png)

**Comment by Ignatnaumovich** [comment]
It seems like this behavior depends on 'p=2' parameter in the Url for the 'Open from' dialog. When I copy the Url from it, navigate to it in separate browser tab - same behavior (no shared libraries).

When I delete the 'p=2' parameter, the shared libraries appear

**Comment by Ignatnaumovich** [comment]
I just wanted to mention that selection from a shared library worked 01/17/2020 and then stopped working on 01/18/2020.

I cannot use the draw.io anymore in our model of collaboration.

Maybe this will help making the Triage decision.

**Comment by ashrafteleb** [comment]
We have no control over the file picker URL. If you check this page
https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/?view=odsp-graph-online
You will see p=2 parameter in the screenshot

Also, I checked and I still can see shared folders. Notice it takes about 15 sec or more to show up
![Screen Shot 2020-01-20 at 9 50 52 AM](https://user-images.githubusercontent.com/24944765/72735944-cbccf300-3b6a-11ea-8116-8598d7f14235.png)

**Comment by davidjgraph** [comment]
The OneDrive picker is MS supplied, we don't have any control over it, as mentioned.

Why the picker populated the shared libraries section, unfortunately, we don't know. We don't do anything to indicate to OneDrive that specific files should be in there.

This has come up before, https://groups.google.com/forum/#!searchin/drawio/onedrive|sort:date/drawio/blwGcVieWho/sYVJVCGABAAJ and https://answers.microsoft.com/en-us/msoffice/forum/all/more-libraries-link-in-integrated-onedrive-apps/596ae357-05f3-4245-be8c-2742f49ea962 , I would suggest to contact MS support and ask them what changed.

**Comment by Ignatnaumovich** [comment]
Thank you for the support. Will reach out to the Microsoft.

**Comment by DamageLimiter** [comment]
It would be nice if you would keep this issue updated once you got an answer from microsoft. I am pretty sure that more people are affected by this change. And even though it's not a problem by JGraph, people will look for a solution here first.

**Comment by Ignatnaumovich** [comment]
Sure, will do.
As for now I am struggling with our internal corporate support to motivate them reaching out to the Microsoft support. This is a challenge because we use Office365 corporate subscription, it offers Visio Online so I am trying to explain why I do prefer to stay with the draw.io

**Comment by davidjgraph** [comment]
OK, I've finally worked out what a shared library is, it's a folder on a sharepoint, helpful naming.

One thing we can look into is whether we can patch the JS they deliver for the picker functionality, https://js.live.net/v7.2/OneDrive.js. They may be problems with 1) not delivering it on their domain and 2) it's huge and compressed (bit pointless being open source and not providing the source...).

The only workaround, for now, I can think of is to use the OneDrive sync client to sync to your local filesystem and then either use www.draw.io in device mode, or the desktop app, https://get.draw.io, to work directly on the synced version.

**Comment by davidjgraph** [comment]
OK, we seem to have a working workaround. You'll see that in 12.5.7

**Comment by Ignatnaumovich** [comment]
I have discovered that the functionality is restored without the workaround mentioned above.
Not sure I understand what happened. Could you please clarify was it change on the draw.io side?
![image](https://user-images.githubusercontent.com/42861768/73238503-4bca0d00-41aa-11ea-9bd9-9e8af4e0e7ca.png)

**Comment by DamageLimiter** [comment]
I also can confirm, that the functionality is back as expected without applying any workarounds. Thank you very much!

**Comment by gonzalovinas** [comment]
OMG! This week it returned. It does not show sharepoint shared libraries anymore (again)

**Comment by davidjgraph** [comment]
OK, but this is a Microsoft issue. Their picker seems to pick up our libraries and show them for some reason. We have no control over this display.

**Comment by zhaozhongming** [comment]
Yes, it is happening again.
