### ISSUE TITLE
Integrate multiple platforms using embed.ly

### ISSUE THREAD

**Issue by tillsanders** [jgraph/drawio#721]
[Embed.ly](https://embed.ly/) is a plattform that provides other companies with a simple way to support embedding third-party content from over 600 content providers. 

For example: Notion.so lets their users embed third-party content using embed.ly. If draw.io would partner with embed.ly, I would be able to embed draw.io diagrams into my other content at Notion.so (which is in fact the endeavour that brought me here).

I think this would be a nice and simple solution to spread adoption of draw.io quite easily.

P.S.: I'm in no way associated with either Embed.ly or Notion.so 🙂

**Comment by davidjgraph** [comment]
Where would the diagrams be stored that embed via this service?

**Comment by prateekrastogi** [comment]
Also, [oembed ](https://github.com/iamcal/oembed)spec is lacking mass adoption.

**Comment by tillsanders** [comment]
> Where would the diagrams be stored that embed via this service?

In Google Drive, the URL, et cetera. I guess otherwise this would not be possible without a dedicated storage solution. But that would be fine, wouldn't it?

**Comment by davidjgraph** [comment]
I'm just wondering whether this is an action item for us? Wouldn't it be for Google Drive to support it?

**Comment by tillsanders** [comment]
I am not entirely sure, but I think it is. Maybe, this link can help?

> - The embed needs to be novel, in that it provides some functionality to the end user. i.e play a video, scroll through a Behance portfolio or view a slideshow.
> - Your URLs and pages must be crawlable server side.
> - The embed must be responsive and, at minimum, work between 280 and 800 pixels.
> - The embed must work over HTTPS.
> - If the embed is a video or audio embed, it must support Player.js and pass all tests.
> - Your site needs to support oEmbed as way for Embedly to reliable match a URL to a piece of content. Please test with our oEmbed validator before submitting, this will ensure you pass the basic requirement tests.
> - If your embed is an IFrame, you must accept a "referrer" parameter as part of the source. This allows Embedly to pass along the actual page your embed is on.
> - We do not accept script tag embeds. These embeds do not work via client side API requests and most of our customers will not accept them. Please use an iframe embed instead.
> - If your embed is not responsive by height or have a predictable height, you may optionally implement height control. Note: this will only work on sites that use Embedly javascript integration.
> - After your site is added as an Embedly provider you will write a short announcement to your users that your content is available through Embedly.

https://embed.ly/providers/new

**Comment by davidjgraph** [comment]
OK, thanks for the clarification. If the issue is embedding within Notion, my personally preference would be to go direct. Adding a third-party dependency tends to turn sour when they disappear, change commercial terms, etc. I'll leave it open in case someone is interested in the task.

**Comment by amimas** [comment]
@davidjgraph - Instead of going through 3rd party, is it possible to look into implementing [oEmbed endpoints](https://oembed.com/)? That way, the diagrams can be embedded anywhere that supports oEmbed.
