### ISSUE TITLE
[Feature request] Make internal links work in PDF export

### ISSUE THREAD

**Issue by LiamDobbelaere** [jgraph/drawio#722]
Would be nice if the internal links set on shapes would also work in the exported pdf.

I know it is possible in PDF to link to certain pages within the pdf itself.

**Comment by davidjgraph** [comment]
It works correctly for me. Could you please detail the steps and environment that demonstrate it failing?

**Comment by TomDobbelaere** [comment]
It still doesn't work for me. I'm at 12.5.3 of the Windows draw.io desktop app.
I have enclosed the source file and resulting PDF export.

Steps to reproduce:
- Create a new diagram
- Place down a shape on page 1 (I picked the first one, rectangle)
- Create a second page
- Add a different shape on page 2 to indicate it's the second page
- Go back to page 1
- Right click on the shape and do "Add link", point it to the second page
- File -> Export as -> Pdf
- Leave default settings
- Save
- Observe how the shape is not clickable in the PDF


[diagram.zip](https://github.com/jgraph/drawio/files/4098794/diagram.zip)

**Comment by davidjgraph** [comment]
PDFs can't support internal links, only external links.

**Comment by TomDobbelaere** [comment]
Then my feature request still stands, I can adjust the title.

Hence why I said `I know it is possible in PDF to link to certain pages`.

Every Draw.io page is a separate page in a PDF, PDFs can perfectly link from one page in the PDF to another. So the feature request is for Draw.io PDF exports to take into account internal links and create them appropriately when exporting a PDF.

**Comment by wellbeingtool** [comment]
I see this is still in triage since Jan, so I think I should go with PPT for my current course till this feature is added.
Looking forward to using this feature with the super power that draw.io has in creating charts.

**Comment by BrandenKeck** [comment]
Hello.  This would be a great feature, but all issues related to this have been closed.  Is there a reason this is no longer on the low priority list?

**Comment by mhdadk** [comment]
For future readers, another possible way to make links work is to export the .drawio file as HTML instead of PDF. After pressing on a shape with an associated link, the associated page will open.

**Comment by cepstra** [comment]
> For future readers, another possible way to make links work is to export the .drawio file as HTML instead of PDF. After pressing on a shape with an associated link, the associated page will open.

It's true that exporting to HTML preserves the internal links, but I've noticed that Sharepoint does not properly display HTML files. So when working in Sharepoint, exporting to HTML isn't an option. 

Adding my vote to making internal links work when exporting to PDF.

**Comment by patrickheinigercsa** [comment]
It would be an amazing feature for wireframes.

Adding my vote to making internal links work when exporting to PDF.

**Comment by earenhart-perfutil** [comment]
Working with external clients and peers for review makes this feature absolutely a must.

Adding my vote to making internal links work when exporting to PDF.

**Comment by thethinker990** [comment]
+1

**Comment by romanraspopov** [comment]
Can somebody finally realize this "most wanted" feature? Almost 4 years have passed since the first request. PowerPoint can do these internal links between pages in PDF. MS Visio can do it either. But these tools are not convenient enough. Drawio is extremely useful and easy to use but still can`t do such an obvious thing as exporting to PDF with hyperlinks between pages. How come?

**Comment by alkcbs** [comment]
Looking for a Visio alternative, linking pages in a PDF export was the first thing I tested in draw.io and it doesn't work :( 

+1 to have this added, please

**Comment by alderg** [comment]
Try Print, Save as PDF instead of Export as, PDF.

**Comment by alkcbs** [comment]
> Try Print, Save as PDF instead of Export as, PDF.

Not an option on my end. I can print to Adobe, or print to Microsoft PDF. Neither results in functioning links. There is no 'save' option.

**Comment by davidjgraph** [comment]
Fix in 24.3.0

**Comment by cepstra** [comment]
Thank you so much for this fix! It makes a massive difference to my work. Appreciate your efforts.
