### ISSUE TITLE
[IBM VPC] Container expanding automatically

### ISSUE THREAD

**Issue by jaywarfield** [jgraph/drawio#723]
In the attached example, 
Example A shows only containers with the non-container Security Group sitting outside the containers.  
Example B shows after dragging the non-container Security Group on top of the containers.  draw.io automatically expanded the Zone 1 and Subnet 1 containers and placed behind the Zone 2 and Subnet 2 containers.

Whether the auto-expansion happens or not is random.  In a larger complete diagrams it seems to happen almost every time.  Example B of the attached example is a subset of a complete diagram and I tried overlaying the non-container Security Group several times before the containers auto-expanded. 

The question is whether this is working as designed (maybe containers and non-containers should not be mixed like this) or is this something that can be fixed in draw.io.  If this is working as designed we can get by without containers.

This does not happen if instead of using containers all boxes are non-containers but the boxes are grouped which is also similar to a container at that point with regard to retaining what is inside the boxes. 

Thanks!
Jay

[ContainerExpansionExample.drawio.zip](https://github.com/jgraph/drawio/files/4097814/ContainerExpansionExample.drawio.zip)

**Comment by egrimate** [comment]
Please let us know is this still an issue with the reworked shapes (boxes).

**Comment by jaywarfield** [comment]
Will do, the boxes have container=0 and I haven't had a problem with this auto expansion when container=0, this problem only happened previously when we had the boxes set to container=1 except for the 3 groups (Security, Resource, Instance Group) have container=0, so probably no problem with the reworked boxes either since container=0 on all boxes.  

The boxes are a good use case for container=1 not only for containing objects in the boxes but also programmatically to determine the hierarchy, so for example a program could find an object of a certain type, such as the Instance object, and then as a result of the container=1 being able to find that Instance 1 is in Subnet 1 and Subnet 1 has a cidr defined and then Subnet 1 is in Zone 1 which is in Region 1, etc.  I can do that programmatically on Visio with Visio containers.  I had't tried to do that programmatically yet on draw.io but was hoping it could be done programmatically on draw.io with container=1 set.

I ran across the auto expansion yesterday on our current diagrams with container=1 set and the expansion happened repeatedly.  

As this time we will plan to stick to container=0 on draw.io and only use container=1 on Visio and  write tools for Visio to extract the hierarchy example I mentioned above and maybe look at other ways of doing this in draw.io with container=0 set.

Thanks!

**Comment by jaywarfield** [comment]
Using the new boxes, the attached zip includes a non-overlayed diagram with 2 security groups below the diagram.  The security group on the right is the new box for security group which has the container property checked.  The security group on the left is the new box for security group but I unchecked the container property.

My test scenario is to drag one of the security groups onto the diagram without changing the size of the security group, look at whether one or more of the underlying containers expanded automatically, then click on the Undo to go back before the container expanded.

Scenario 1:
If I drag the container security group over the 2 bottom VSI icons in the 2 bottom subnet boxes in the diagram, one of the subnet boxes expands automatically to the right.  This seems to happen repeatedly.

Scenario 2:
If I drag the noncontainer security group over the 2 bottom VSI icons in the 2 bottom subnets, the subnet box expanded automatically to the right but this happened once and I couldn't get it to happen repeatedly.

Scenario 3:
If I drag either security group to cover 4 bottom corner of all 4 subnet containers, the subnet box on the top right expanded automatically downward.  

[ContainerExpansionExampleWithNewBoxes.drawio.zip](https://github.com/jgraph/drawio/files/4150751/ContainerExpansionExampleWithNewBoxes.drawio.zip)

**Comment by egrimate** [comment]
This is working as intended, but we could add an option to disable resizing in this case. Would this be suitable?

**Comment by jaywarfield** [comment]
In order to effectively make use of containers in this case I think an option to disable resizing would be great.  Would this be a general setting so the user can set it once and not have to set it again each time they start draw.io or would it be an option in the style for each box that is a container or something else.

Also, a VSI icon is primarily in a subnet and secondarily in a security group, so to prevent users from adding a VSI icon to a security group container since icons should be added to a subnet container, I think it would make sense for the 3 dashed-border groups (Instance Group, Resource Group, Security Group) to NOT be containers but everything else as containers makes sense if we can disable the resizing.  Let me know if I need to open a new issue for this.

One last problem I'm having is mentioned in issue 620 with the shading for 2 of our containers (Zone and Subnet) where the default white background sticks out, sometimes I can change it and sometimes I can't. Or if there is a general setting to make default background color for all text to be nothing.  I was going to open an issue for this when I found 620 and I didn't know if I could add a comment to 620 since I didn't open 620.  

Thanks!

**Comment by egrimate** [comment]
We implemented this as a property called "expand" for swimlanes. Default is expand=1 (old behavior), so let us know for which swimlanes should we use expand=0.

**Comment by jaywarfield** [comment]
IBM / Boxes used to contain a swimlane at top but that would push the box tag (square icon in upper left corner) to a smaller size on upper right corner, so the keyword swimlane was removed from all box styles.  That was right before your excellent work to integrate the box tag with box border via javascript, so I don't know if swimlane shoud be added back to all boxes in IBM / Boxes (I see swimlane keyword is used in the styles for draw.io-provided containers).  I have defined primary boxes vs secondary boxes in issue 748 (only mentioning 748 for description of the 2 different box types) but I think it makes sense to set expand=0 for all primary and secondary boxes in IBM / Boxes which means all boxes.  With our current boxes how would we set the expand=0 for all boxes, do we need to add swimlane to all box styles?   Thanks.

**Comment by egrimate** [comment]
Will be in next release.

**Comment by jaywarfield** [comment]
Great, looking forward to trying out the next release.  Thank you very much!

**Comment by jaywarfield** [comment]
These changes are work great with our boxes, thank you!!!
