### ISSUE TITLE
[IBM VPC] Copy/Paste style not copying everything

### ISSUE THREAD

**Issue by jaywarfield** [jgraph/drawio#725]
In the attached example,
select the first box which is blue, 
click on Copy Style,
select the second box which is green,
click on Paste Style.

The expected outcome is that the second box will turn blue and have the IBM tag in upper left corner.

The actual outcome is that the second box turns blue but does not have the IBM tag in upper left corner.

Therefore, the Copy Style doesn't include the image statements from the first blue box.

The workaround is to Edit Style on the first blue box, select all of the style including the image statements with the left mouse button, then the right mouse button to select Copy, then go to second green box and select Edit Style and delete the contents and right mouse button to select Paste.

Since the Edit Style shows the image statements should the image statements be included when selecting the Copy Style also.  The workaround is fine too, just checking to see if this is the expected behavior or if Copy Style should include everything that Edit Style shows which would include the image statements.

Thanks!
Jay

[copystyleexample.drawio.zip](https://github.com/jgraph/drawio/files/4099321/copystyleexample.drawio.zip)

**Comment by davidjgraph** [comment]
The image isn't part of the shape style, this is the expected behaviour for style copy and paste.

**Comment by jaywarfield** [comment]
Got it, just checking, thank you very much for confirming!
