### ISSUE TITLE
Exported PNG is upside down + some diagram elements are lost 

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#726]
When the diagram is exported to PNG (File > Export as > PNG and File > Export as > Advanced > PNG), it is all messy (upside down and doesn't have all diagram elements) although it was opened well in draw.io editor. 
Tried in Chrome and Incognito, as well in the desktop app. 

Diagram example in ticket 36888

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
