### ISSUE TITLE
Display a Jira Workflow Diagram in Confluence

### ISSUE THREAD

**Issue by fredclown** [jgraph/drawio#727]
It would be awesome to use Drawio to display a Jira workflow from a linked Jira instance on a Confluence page. This would make documenting Jira projects in Confluence much easier as diagrams of the workflows would be dynamically created and always up-to-date. As it stands right now it is a fully manual process that requires the person editing the Jira workflow to remember to update the Confluence documentation. Having dynamically generated up-to-date documentation is a huge win.

**Comment by davidjgraph** [comment]
Cloud or server?

**Comment by fredclown** [comment]
We use server.

**Comment by davidjgraph** [comment]
There's a feature request on the trello board, https://trello.com/c/241jZON3/154-import-workflow-diagrams-from-linked-jira-instance, you can vote for and follow the request there.
