### ISSUE TITLE
[IBM VPC] Additional icons

### ISSUE THREAD

**Issue by jaywarfield** [jgraph/drawio#729]
Please add the 2 svg files in the attachment to img/lib/ibm/vpc

And in IBM / VPC please add the 3 references to the svg files:
 
Power Instance
 which points to the new img/lib/ibm/vpc/PowerInstance.svg
 
Transit Gateway
 which points to the new img/lib/ibm/vpc/TransitGateway.svg 

Bare Metal Server 
which points to the existing img/lib/ibm/vpc/BareMetalServer.svg

Let me know if there are any problems or questions.

Thanks!
Jay

[IBM_VPC_Icons_Updates.zip](https://github.com/jgraph/drawio/files/4106538/IBM_VPC_Icons_Updates.zip)

**Comment by egrimate** [comment]
Will be in next release. Please note, I had to redraw these two icons too:
![image](https://user-images.githubusercontent.com/2485177/73521182-a57a4380-4405-11ea-8721-f078a129febf.png)

**Comment by jaywarfield** [comment]
Awesome, thanks!  I'm unable to see what had to be redrawn but I can wait until they are published to see.

**Comment by egrimate** [comment]
Can you see it on imgur?
https://imgur.com/a/yPHDdXg
SVG like those are not production quality, so we redraw them. If you avoid such when possible, it'll take us less time to implement your changes.

**Comment by jaywarfield** [comment]
Thanks for letting me know, I will definitely pass this along to our icon folks.
