### ISSUE TITLE
[Feature request] Cropping mask for crop images in draw.io editor

### ISSUE THREAD

**Issue by MurzNN** [jgraph/drawio#73]
Very often we need to hide some parts of image, for example create rounded image from square or hide some part of image without editing image in graphics editor and re-uploading, and unhide parts later. 

Other editors have "Clipping mask" functional for do this. 

Can we do something like this in draw.io editor?

**Comment by jschroeter** [comment]
I'm also missing the feature, especially just some simple cropping of inserted images.

**Comment by j2l** [comment]
Me too, +1

**Comment by davidjgraph** [comment]
Please do not +1, it makes a mess of comments. There's a thumbs up where you can vote. Only comment if you have information to add.

**Comment by amitguptagwl** [comment]
This could have been more easy wih cropping and polygon (or free hand draw) shape. ![screenshot from 2018-01-25 14-56-24](https://user-images.githubusercontent.com/7692328/35380671-fe82b058-01df-11e8-8b4d-30c36aa18aee.png)

**Comment by katopz** [comment]
Or maybe just provide `border-radius` properties?

**Comment by jufemaiz** [comment]
Low priority? Sad :(

**Comment by ChyraTomasz** [comment]
Please, min. add cropinng images by mouse not by entering cropping coords...

**Comment by davidjgraph** [comment]
https://twitter.com/drawio/status/1219675025835544576

**Comment by mararad** [comment]
https://trello.com/c/rzumXrlX/63-cropping-of-images-or-add-cropping-masks-for-groups-of-objects 

Cropping of images is very much needed. it would also be helpful to have cropping masks for groups of objects. This way it would be easy to make a mock-up of scrolled items that are only partially visible

**Comment by Karunamon** [comment]
Out of curiosity, what happened here? The feature was made live and then later retracted?

**Comment by ashrafteleb** [comment]
Hi @Karunamon,

The feature is not retracted, it is still available for images pasted into the editor (base64). It replaces the original image with the cropped one.

The issue is opened again since we want to implement a non-destructive cropping where the original image is not altered by cropping.

**Comment by davidjgraph** [comment]
Non-destructive image cropping in 16.2.6. If you have issues or suggestions please add as new discussion/issue.

**Comment by pcgeek86** [comment]
@davidjgraph Thank you for adding that feature!
