### ISSUE TITLE
Export to vsdx only exports active layer

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#738]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When exporting a diagram to vsdx, only the active layer is exported.

**To Reproduce**
1. Go to https://www.draw.io
2. Add a diagram with multiple layers
3. From the menu select File->Export As->VSDX
4. Load the vsdx in a native vsdx rendering tool, only the active layer is displayed.

**Expected behavior**
All layers of the draw.io diagram should be displayed in the native vsdx rendering tool.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 12.6.1

**Desktop (please complete the following information):**
 - OS: MacOS and Windows 10
 - Browsers: Chrome 79 and Firefox 72

**Comment by alderg** [comment]
Fixed in 12.6.2
