### ISSUE TITLE
[feature request] ERD Specialization Hierarchy

### ISSUE THREAD

**Issue by f0rmiga** [jgraph/drawio#74]
Since draw.io already has awesome tools for ERD, it would be great to have specialization hierarchy. 

Parts to be added:
- Disjoint/Overlapping constraint (d/o)
- Category symbol
- Partial/Complete constraint
- Subtype discriminator

An example:
[An image from the book Database Systems: Design, Implementation, & Management from Carlos Coronel and Steven Morris](http://www.myreadingroom.co.in/images/stories/docs/dbms/Specialization%20Hierarchy.JPG)

**Comment by meech-ward** [comment]
This was closed with an explanation. Has this feature been added, or is it not going to be added, or there a duplicate issue?

**Comment by f0rmiga** [comment]
@meech-ward I guess you meant `with no explanation`. 😅 
@davidjgraph What does reopening mean? Will you add it to the backlog? Will you leave it for the community to pick up? Shed some light on the thread, please.

**Comment by davidjgraph** [comment]
Happy to leave open, but we won't do it.

**Comment by a3s0h** [comment]
wait so there's no diagram to represent specialization ? 
then how do i  show it ??

**Comment by alderg** [comment]
How about this?[](https://app.diagrams.net/#R7Vxtc%2BI2EP41fMwNfgPysZDctdN0miZ30%2FajggXoTliuEIHk13dlSza2gNghYA5rhhmstbyWd5%2FVY2lldbzRfP2Fo3j2Bwsx7bjdcN3xbjqu67ieD39S8pJK%2Bm4%2FFUw5CVNRNxc8klesrtTSJQnxQslSkWCMChIXhWMWRXgsCjLEOVsVq00YDQuCGE1xoRlS8DhGFBvV%2FiahmKXSgX4KKf8Vk%2BlM39npXadn5khXVooXMxSy1YbIu%2B14I86YSI%2Fm6xGm0nhFu3zecTZrGMeRqHIB%2B47746uH27n3Z%2By83o%2F%2BGsfxldtTjRMv%2BolxCAZQxYhF8DccL%2FkzlmocKHC2jMKk1IUS42LGpixC9I6xWFX5joV4Ub5ES8FANBNzqs5OWCTUSQesMFwIxLVgAGUchcXSL9KPeWtA8plQqhoAT89f%2FpGFT4Eu%2Frt57mZdKL2okmk%2BZdEFW%2FIx3mMzx1M4RHyKxb6KaT1p0I07KO98wWyOoUFQgWOKBHkuIg4p4E6zerlv4UC5t4ardbOfEV2qW31FT%2BDmMgAAqLE8FMnZon88aTqINYFIhLly6JhRiuIFSaqnkhmh4R16YUuhFenScELWOHxIAzPF0%2BoOlC2UXxJ0qMbI04iSaQTHY%2FCTvOOQ4wW05Q4thKqxA1q9fU5%2Bxlzg9V6vqLP9QXqF6r8cVVzlnYEzUBE%2B2%2BwIgu6x%2FOgbftzvwgcZPMMZ4%2BRVOk4HzqZbk%2FKKzCmKoDtDYUk0ZKEOmwlE3ohRxjd6h4L7ZaWQs%2Firjg4piBmJRGKIYAg%2FMM1IhmsAbR1B2cnL8JPVuRixaCE4wEzqwODtFZYeH4qkl5FKKZ5o%2FVwZXh4%2FMSHYvDIg9sfK2zBRuPC61XDhHQ0WgQGL%2B993AgMsIAiiD0CZKJrS1I0Jg6LcjVt8vdX6mcXLrijHMgN7TmjSl89IGGKI6%2BFqRgR%2BjFHS5a7gJaJuRO8PkrcduOExr6bDlLLcirW1IQqdWoQEhBiw6sJAQdbOA4DRM4DxLSL%2FLfFvNw3DQ3ftad3hAkBAouldemWvhJ%2FgXPGz3t0BBB%2BKp0rqTgGoviWgSgTUPQB%2FtQmo1zgBDarD4jT9Cw6J1ndi9ulX9t7Fs8%2B1gQrZHbhdp2FwvEk%2BZwmX1pGNnj2xZHNOZHPdNNlk43hLNlmEWLLRIDDIpmlwnBHZ1IBL%2B8jGnCK1ZNM42Thu42xTY8r10tmmuvsunm3MGdeUbTzLNu%2BAS%2FvYpsI82pSzZVyaCe2att%2BV1cry4gpenc3U8zbrO7pRqu91NchXm8nvLeYLjtT1mu%2F5oWEkUEPiBa4P4nJ%2BosylwJvAnhmXpmUn49KqMVB7eO8Gn%2Fqm3b3k%2FqcjvbfRSUnSO8HLBPuRLY8opWRjzAk0KEkWP6Hxjyfo0e5zWcnm0qxsKaTiUbai44C3jRq214ivBnjnaGY3p1Ftmv7tkLly9CBPJ2R905EnztS75tznfi%2B2dThxyAvGoDJSziVTrxXbTH0hSOyAwjNfdmym%2FgPx07oRhlfhHc4S0IFvmLUJqPFMvVdjmvPCp7OyCLHs45mTnDZT%2F364tI9szOlQSzaNk03jmXrPXH7aWrIJKnvv4snGnPu2mfr3w6V9ZFNjsaklm1ORTfOZeq%2FGlOuls01191062%2FjmjKvN1L8fLq1jG98cAm9%2BJY3pE1vd5oKf5RNpp7P%2FE%2BnkueBYQoKMJWce8NW0ZpPTfzWtLr2X9Juj1yl%2F2KvLWkX6ROqqHFOmokFRkTsotSV9YkPRh4HTZDgLzprg9Bv7pH87poJ%2BrwjOQfd94Ax6RUWg%2BbTgtJsO5P6vswCo2KecwWIG3247cPTFDP7Pt%2B2Ab7cd2BYkdszl220Hjoqf9g3C7LYDR5%2Fyq09AjS9m8O22A0aEWPbx7bYDHwmX1pGNboYlm3Mim8YXMwR22wEjQizZBO4OsmkaHGdENjXg0j6ysdsOnCHZNL%2BYIbDbDhghYtkmsNsOfCRcLohtoJhvJ59Wzzfl927%2FBw%3D%3D)

**Comment by a3s0h** [comment]
> How about [this](https://app.diagrams.net/#R7Vxtc%2BI2EP41fMwNfgPysZDctdN0miZ30%2FajggXoTliuEIHk13dlSza2gNghYA5rhhmstbyWd5%2FVY2lldbzRfP2Fo3j2Bwsx7bjdcN3xbjqu67ieD39S8pJK%2Bm4%2FFUw5CVNRNxc8klesrtTSJQnxQslSkWCMChIXhWMWRXgsCjLEOVsVq00YDQuCGE1xoRlS8DhGFBvV%2FiahmKXSgX4KKf8Vk%2BlM39npXadn5khXVooXMxSy1YbIu%2B14I86YSI%2Fm6xGm0nhFu3zecTZrGMeRqHIB%2B47746uH27n3Z%2By83o%2F%2BGsfxldtTjRMv%2BolxCAZQxYhF8DccL%2FkzlmocKHC2jMKk1IUS42LGpixC9I6xWFX5joV4Ub5ES8FANBNzqs5OWCTUSQesMFwIxLVgAGUchcXSL9KPeWtA8plQqhoAT89f%2FpGFT4Eu%2Frt57mZdKL2okmk%2BZdEFW%2FIx3mMzx1M4RHyKxb6KaT1p0I07KO98wWyOoUFQgWOKBHkuIg4p4E6zerlv4UC5t4ardbOfEV2qW31FT%2BDmMgAAqLE8FMnZon88aTqINYFIhLly6JhRiuIFSaqnkhmh4R16YUuhFenScELWOHxIAzPF0%2BoOlC2UXxJ0qMbI04iSaQTHY%2FCTvOOQ4wW05Q4thKqxA1q9fU5%2Bxlzg9V6vqLP9QXqF6r8cVVzlnYEzUBE%2B2%2BwIgu6x%2FOgbftzvwgcZPMMZ4%2BRVOk4HzqZbk%2FKKzCmKoDtDYUk0ZKEOmwlE3ohRxjd6h4L7ZaWQs%2Firjg4piBmJRGKIYAg%2FMM1IhmsAbR1B2cnL8JPVuRixaCE4wEzqwODtFZYeH4qkl5FKKZ5o%2FVwZXh4%2FMSHYvDIg9sfK2zBRuPC61XDhHQ0WgQGL%2B993AgMsIAiiD0CZKJrS1I0Jg6LcjVt8vdX6mcXLrijHMgN7TmjSl89IGGKI6%2BFqRgR%2BjFHS5a7gJaJuRO8PkrcduOExr6bDlLLcirW1IQqdWoQEhBiw6sJAQdbOA4DRM4DxLSL%2FLfFvNw3DQ3ftad3hAkBAouldemWvhJ%2FgXPGz3t0BBB%2BKp0rqTgGoviWgSgTUPQB%2FtQmo1zgBDarD4jT9Cw6J1ndi9ulX9t7Fs8%2B1gQrZHbhdp2FwvEk%2BZwmX1pGNnj2xZHNOZHPdNNlk43hLNlmEWLLRIDDIpmlwnBHZ1IBL%2B8jGnCK1ZNM42Thu42xTY8r10tmmuvsunm3MGdeUbTzLNu%2BAS%2FvYpsI82pSzZVyaCe2att%2BV1cry4gpenc3U8zbrO7pRqu91NchXm8nvLeYLjtT1mu%2F5oWEkUEPiBa4P4nJ%2BosylwJvAnhmXpmUn49KqMVB7eO8Gn%2Fqm3b3k%2FqcjvbfRSUnSO8HLBPuRLY8opWRjzAk0KEkWP6Hxjyfo0e5zWcnm0qxsKaTiUbai44C3jRq214ivBnjnaGY3p1Ftmv7tkLly9CBPJ2R905EnztS75tznfi%2B2dThxyAvGoDJSziVTrxXbTH0hSOyAwjNfdmym%2FgPx07oRhlfhHc4S0IFvmLUJqPFMvVdjmvPCp7OyCLHs45mTnDZT%2F364tI9szOlQSzaNk03jmXrPXH7aWrIJKnvv4snGnPu2mfr3w6V9ZFNjsaklm1ORTfOZeq%2FGlOuls01191062%2FjmjKvN1L8fLq1jG98cAm9%2BJY3pE1vd5oKf5RNpp7P%2FE%2BnkueBYQoKMJWce8NW0ZpPTfzWtLr2X9Juj1yl%2F2KvLWkX6ROqqHFOmokFRkTsotSV9YkPRh4HTZDgLzprg9Bv7pH87poJ%2BrwjOQfd94Ax6RUWg%2BbTgtJsO5P6vswCo2KecwWIG3247cPTFDP7Pt%2B2Ab7cd2BYkdszl220Hjoqf9g3C7LYDR5%2Fyq09AjS9m8O22A0aEWPbx7bYDHwmX1pGNboYlm3Mim8YXMwR22wEjQizZBO4OsmkaHGdENjXg0j6ysdsOnCHZNL%2BYIbDbDhghYtkmsNsOfCRcLohtoJhvJ59Wzzfl927%2FBw%3D%3D)?

I think it doesn't matter how you represent but it must be readable.

**Comment by davidjgraph** [comment]
You're saying that's not readable?
