### ISSUE TITLE
export svg has a problem

### ISSUE THREAD

**Issue by Stars-One** [jgraph/drawio#744]
I use the option to exprot a svg file,but I found that the text of node is missing.
The svg file shows the text "not support by viewer"

**Screenshots**
![](https://img2018.cnblogs.com/blog/1210268/202002/1210268-20200202141842790-190047864.png)

**Comment by Stars-One** [comment]
the application version is draw.io-12.3.2-windows-no-installer

**Comment by davidjgraph** [comment]
https://desk.draw.io/support/solutions/articles/16000042487-why-does-the-text-of-svg-export-sometimes-not-display-correctly-in-ie-and-some-svg-editors-
