### ISSUE TITLE
Edge label missing on second page of PDF export

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#749]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Exporting the example diagram in this issue to PDF results in the edge label on page 2 not being visible on the resulting PDF.

**To Reproduce**
1. Click on [this link](https://www.draw.io/#R%3Cmxfile%3E%3Cdiagram%20id%3D%22VQjhcs3_58A44fEQAFcx%22%20name%3D%22Page-1%22%3E7Vxtc%2BooFP41fqwTIC%2F68Wrb3Tvbnd693b39uEMNGrZJcCJe2%2FvrFwxEExJN60sck7YzlRNA4DmHh3MC9NA4evstwfPgT%2BaTsAct%2F62HbnsQAg8C8U9K3pUEIJhKZgn1lWwjeKK%2FiBJaSrqkPlnkMnLGQk7neeGExTGZ8JwMJwlb5bNNWZj%2F1jmeEUPwNMGhKX2mPg%2BU1HXszYPfCZ0F%2BquBO0yfRFjnVl1ZBNhnqy0RuuuhccIYTz9Fb2MSyuHTA5OWu694mrUsITGvU%2BBu%2FOP73wF6fn8e2QPv7p%2B%2F8Nc%2FblQtP3G4VD2%2BxRy%2F4AVRjebveigCHoXiE%2BihUcKWsU9kvZZIZR2TiQmL6ER9DvELCUd48jpbFxizkCXiUcxiIovxhL1moyqGYzRlMb%2FHEQ2ltvwgiY9jrMRKM4DMhkM6i0ViIjpOkrQBc%2Fk0eptJNexTtvCWtB%2Bw5IHGUntGqpck4eStcvhABorQZ8IiwpN3kUUXsDWQSpdtjfRqSzGQk8qCLZ1wVDmsdHGW1b1BS3xQgH0APNiB91nwHNdrGDxkgPe45PMlN6BbBZSTpzmeyPRKjJEYktPCCQ6A8xhgQVSwNFBiaRrQs4BlG6gQX%2FCESqpB3AJl32jjhN9T2YQUNJlWozoQaRL76ilIU1vPauKStlc2cjcIok9smUzIjr4roxBtnBG%2BI9%2BwHNSEhJjTn%2Fl2HB0gx7Cmr3FnTNIkvKItlUx8Z7Ult8W2NKxpS6hJW%2FI6gPYCBJwmERrsRIglPGAzFuPwbiNtPWAH4rUu%2BiVJ8PtWhjmjMV9s1fxNCrZWMpZTmH2HdgH8tMqNKmRt%2B7x2DA0uBH3H0JjFikYhLtryGimVac16AQ39B%2FzOlnJwhSpMXnVqJJbo9JfIj3XhbU2BrqxN6InWrh5ExJK%2FuZJPskb1XQlZiLLftBKATPSAFzxj4TDE8wV9WbdQZokE8jQeMc5ZpDVWde0%2B%2F%2FXT9U8Zz25oH5yd9g%2Bn%2BKFdpHjXpHi7jOLhieYnHb3ZUsHvYkShBQw1FN3meRVMx7EwuNuapMdbrOJoPHsgU9kdeyP5rnooRWXrPSZGexquEQ6o75N4rQFcus6Z3ivLFk10RuJP9GdsCSNyRJPHIg02afEnsyd8zGLRdEzXoBGhsisi1faTq7qPLLEV7rAm7Drf8WE34W0tL2nL3r%2FU8xphJnswyE0aAzg4PTNl010XsfpwxMqzoWneZ41YAdRixwDUDYPYh3oGVUvJgdW3LAu4guA9aDteTjscG%2FSHyIIIIQA9zxvm609braosqMEx7LrN8bH6mgEP1IzDrNcMkYG%2BGYvp3IJrdQuc5t0Ct3MLTuEWVAWjLsYvaHNEEQxq0kOzIUXdzBw9wI4erpYePLdID07T9GAGLjt6OAY9DC6bHrINUl3Y6Cbb5LaPLQ71JT4XNULFbTRDWID%2FBFEj3Y0cNQ07arpaagLQuTRugmbksuOmI3BTlSZcDDe1OeYJ7ZpkhOwmXRfdzBw%2FmLh1%2FHAt%2FFB0XdyyzbznpQczuNrRwzHooWJiuRh62L2ZsV2ui1eTLUAzvgsozBqeew7fxSvhJnP7XsdN18JNwBoWyanp1y7QDO125HQMcqrYuXMx5GTGSNrju%2BgjRPvfyh%2B6M%2FiwU2DmTknQN%2B2y44dr4QensAoZWLBhekBmeLWjhyPQA7LKFeFS6EGfxG8nPdQObR26PfcwjNocfqyPUYWlnQmjsvCjuSGyo%2FBrofBi%2BPECKLwLP56Gwi88%2FIjafJYa1Y03NrvvGpVFAM0NkR09XAs9FPddXwA9dAHA09DDhQcA0e4AYKveTtl1N9ZV7ZY87dspt3DlkaPae9KXU7YZfHxc8pDG5N86M4NhSdKG6ASHX9SDSJjzWqfWvFFpzrfVqrZNE5V2qu7%2BU%2FX3sgv39ttvxXlqVf2N1ReTuZvDRfnjnz3Mp7Ow6XRBTnIUzzajeY8v%2F8mrEYuAtv4qJLfsAr%2FzXisGO7CqVlHOxYHV5licXfeQa9VL0fM4W3abDyLXx6jRV562GawyQQtDOl%2BQCo%2BhdOI7v6t4otsvgR4gvRSE5u5GVDLxoY9PfCK5uX84XYFs7nFGd%2F8D%3C%2Fdiagram%3E%3Cdiagram%20name%3D%22Page-2%22%20id%3D%22FqDU4ZqiGvi5B5aZwCEn%22%3E7VzbcuI4EP0aHkPZki%2FwOJBkdquyNVPJ7MzjlIIFaGMsyhZDkq9fCUu%2BySEiMeDETlIVdLGQ%2B3TrdLdkD%2BB09fg1RuvlPzTA4QBYweMAXg4AsH1g83%2Bi5knW2BCkNYuYBLIur7gjz1hWWrJ2QwKclDoySkNG1uXKGY0iPGOlOhTHdFvuNqdh%2BVvXaIG1irsZCvXaXyRgS3UblpU3%2FIXJYim%2FeuTKhns0e1jEdBPJ7xsAON%2F9pM0rpMaS%2FZMlCui2UAWvBnAaU8rST6vHKQ6FcJXYnn%2F8%2FPcWuOMfydXD8%2B0v72KSXF6kg10fckl2hzGOWLNDS6j%2FoHAjxXmJGLpHCZb3zJ6UnJdsFfJP9gBOdkLDYlyLlzK5iMKMrshMfg7RPQ4nmZSnNKQxb4pohMVlLKYPGWRcmpM5jdg1WpFQqOJPHAcoQrJaqp0tuqGQLCJemHFp4DidwFq0rh4XQseHhCb%2BhgyXNL4hkVDNiaEApaD%2F4Jjhx4J2SYF%2BxXSFWfzEu8jWsTICZTyWn5a3BU2Eblq3LCih0kEklX%2BRDZ0jyD9IEA8AFPaANgkosNwzA%2BpogH7bsPWGaXBul4ThuzWaifKWy42L6bgQ2%2B%2BA%2BFgA%2BqAMoFtjkKrLSfBzNaBwwPlLFqVcCzi9BgCK2TURU0hxFGUp6BEv4yiQrXZaKrQZQnUYMgndxDO8p58nXQIUL%2FDe8SQAQjp7gY5xiBj5U2b%2FxmHzNLP7O%2Bqt7iWr8ypGV7NontTo%2FI4bnTKmV63OaZXRjXrYDBdLr1W4jffiRmO2pAsaofAqr%2B1hzKOv5lDcXfoljtFTocOakoglhZG%2Fi4p88XadShAjEwC5RqQj5vqRTe3tKqNkVCBYe6j7SsmWrEJUtfsdfrLTjkqXJAxu0BPdCGlzBZk9qNKEBw3kmfdH6uKi%2FgBPjMa1R%2BncAEBsid%2FSlXdiRPldMU74td%2BVrthZ1Q1KWEbtYYjWCbnfzVB0WXFVINGEMkZXSo%2FlrV2Xv16mIGrIO%2Fcl7JP7EkfyGxxYcRwc3XFw6hwHcKSVzLY1tbzlUgaWrakmv0VWVstUthWBF7VLYcDdRRItbvBc3I6T19zKOxRVdY4l5ZKdhzvUlyQIcLTTCiYC%2FMwWpLXzKboT%2FseFN7W4Ybl8ylNetvMy%2FxPdYzalEZ86IjtsMVfjLRaq%2FHb30TLWAxVme2a4q37N4w56Civ1g4YUBket4LCxPyotJI7nnYDD%2BmRbo8k2OLL0ZeCkyTbb6XoEYpqucRqPQF5wTn1raFmW7XGb9oGj0nnKVfXHwzG0AITQBr7vj8vDp3chR6yoRhP23%2FXcnrm2wKa15X1mrmf37KHXBx%2FdDj7s80cffh99vD%2F68IwVoTXRR%2BcTn2NDImlZ4lPNu0QkeijZE8mnJpIsHsmIBJ6ZSICeXe2J5GAiGRsrQluIBOj4djqNBYAhrzQen7wpizWqnj6CVkUljpDFUjIqcZi%2Bo9dz2KfmML%2B6CXh%2BDtOzqz2HHcphmXF%2FIA7reg4WuKak5bYqGFLzLhEJ7ImkW0RSDYZg3Qnq0xKJnu3tieRgInGNFaE1RLL%2FFGj3gqGRIa%2FY7YiGvMpK4liniIZGNSSmp2d7EvvUJOaOqiR27q0hoGeaexI7mMRGxorQFhJTe5SdjYageqb41TMGoFXRkJp3iUh0Y%2B2J5HMTScWFcWpOuJ2UR9TD%2FT2PvINHoLketIZH9ERMx3jEOKvW%2BInm9wHX9XSoOXB2u4CrS4fqYPYOwKd2AFroAfTp0AY8gI%2BXDoVdfygemuY%2FW3ZaHdalJHUweyL51ERSPa3eAiLpU5INEMnHS0k6%2B1OSndtXU4nH1%2FfVxk3zypv21bJX8eQP0VV04gj7ao6eDv22YSGJ8G9gsFxo5iXshcxQ%2BEU2rLiN7xRtxzAv2vjly%2FpXJBRDDVGWoBlv9rZLOZFB8Y2Rdav7hTUEY%2FVMpdp0SktvfYBSdaHzeYKP8vyjUvwipvf%2FiXd8VgHt35IlWr3qpuK5303n6EcsewD3%2BWBO6xDsenbQMX0EGbQrret0%2Fdlxc%2BBAu4DT02c6kmFI1gl%2BITKpXTdPH6eekvhUukx5nJ5%2BJhTWLJvw8GWTF%2FM3cqeOTv7ec3j1Pw%3D%3D%3C%2Fdiagram%3E%3C%2Fmxfile%3E)
2. Select File->Export As-> PDF.
3. Ensure "all pages" is selected

**Expected behavior**
The edge label in page 2 should be present in the PDF export result.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 12.6.5

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.2
 - Browser Firefox
 - Version 72.0.2

**Comment by Nightheat** [comment]
Have a similar issue with added arrow text not showing on Page 2 of an exported PDF. If persistent, this would require checking every export for correct arrow labels.

**Comment by davidjgraph** [comment]
@Nightheat please just thumbs up the original, your post does not add any new information.

**Comment by Nightheat** [comment]
Oh ok sorry. Created a GitHub account just for his. I have no idea what I'm
doing.
