### ISSUE TITLE
Invalid Publish Link URL self-hosted

### ISSUE THREAD

**Issue by jbperrin88** [jgraph/drawio#750]
Hi there,

First of all , thank you for this amazing TOOLS ! 

I've set it up in docker container , with Gitlab self-hosted integration and it's working as expected 

I've downgrade to v 12.6.4 cause it mix GihubClient and GitlabClient  and send request to gitlab with authorization header TOKEN instead of Bearer (may need correction)

Now , i want to set everything to keep our information self hosted.

So in PreConfig , i've set :
urlParams['gapi'] = '0'; //google drive
urlParams['db'] = '0'; //dropbox
urlParams['od'] = '0'; //OneDrive
urlParams['gh'] = '0'; //github
//urlParams['gl'] = '0'; //gitlab (used it ^^)
urlParams['tr'] = '0'; //trello
urlParams['rt']='0'; / Real-time
urlParams['picker']='0'; /Picket from google
urlParams['base']='xxxxxxx';

when i launch the app , i still get rt.draw.io request and i also still have www.draw.io when i try to publish a link
![image](https://user-images.githubusercontent.com/11284940/73936919-25ac1780-48e4-11ea-8315-97ecfd224691.png)

Can you please help ?

**Comment by davidjgraph** [comment]
Add:

`window.REALTIME_URL = null;`
