### ISSUE TITLE
[feature] Option to set zoom level when using "auto-export" to PNG

### ISSUE THREAD

**Issue by ebousse** [jgraph/drawio#752]
**Is your feature request related to a problem? Please describe.**

I am using draw.io to make diagrams that I always export as PNG files.

To avoid storing both a `.drawio` file and a generated `.png` file, I really like using the feature "*Include a copy of my diagram*" when exporting to PNG, as it allows me to only store the PNG file since I can directly open it with draw.io − I can even delete the now useless `.drawio` file.

Unfortunately, when I open such a `.png` file with draw.io, make a change, and save the file, it does "auto-export" the PNG raster image inside the `.png` file, but always with a zoom level of 100%, which means a rather low definition PNG. Instead, in my case I would need a 200% or 300% zoom level.

Note that it is possible to decide the PNG zoom level when doing *File→Export as*, but this is a different workflow than directly opening a `.png` file and relying on the auto-export as described above.

**Describe the solution you'd like**

The diagram could store as metadata what is the preferred export zoom level, and this value could be used when the auto-export is triggered.

**Describe alternatives you've considered**

It could also be an application-level global option, but it would be less flexible I think.

**Comment by alderg** [comment]
You can now save the file as .png and set the default zoom and border via File, Properties.

**Comment by ebousse** [comment]
Thank you! Looking forward to try this feature!
