### ISSUE TITLE
[Feature request] Hatch fill

### ISSUE THREAD

**Issue by al-indigo** [jgraph/drawio#753]
I would like to have an ability to make shapes with hatch fill with different directions and line styles since I have color blindness and lots of diagrams look better with hatch fill instead of colors.

I have found the only example in mxgraph library and see that it's possible, but for some reason there is no options for it in your interface. The example is `mxgraph.lean_mapping.manufacturing_process_shared`.

Is it possible to make hatch fill for shapes?

**Comment by dannystaple** [comment]
This matters also for print material where colour may not be an option (ie large books).

**Comment by alderg** [comment]
If you check "Sketch" the Fill can be changed. Under Properties, set Jiggle to 0 and configure the Hachure Gap, Hachure Angle and Fill Weight:
![c51761c9456879b364d232de389e2d60](https://user-images.githubusercontent.com/921200/100191463-72eb8b00-2ef0-11eb-9057-01ea9accbadf.gif)

**Comment by ebousse** [comment]
Interesting. However using draw.io 13.7.9 the results have some problems:

![Capture d’écran de 2020-11-25 08-40-08](https://user-images.githubusercontent.com/5868014/100196996-fc538b00-2ef9-11eb-9be6-ee2afd224228.png)
![Capture d’écran de 2020-11-25 08-39-57](https://user-images.githubusercontent.com/5868014/100197001-fe1d4e80-2ef9-11eb-9680-e660eaa92c6f.png)
![Capture d’écran de 2020-11-25 08-39-49](https://user-images.githubusercontent.com/5868014/100197011-007fa880-2efa-11eb-9f26-10315733a841.png)
![Capture d’écran de 2020-11-25 08-39-42](https://user-images.githubusercontent.com/5868014/100197013-01b0d580-2efa-11eb-92c4-e6a1e20423cc.png)
![Capture d’écran de 2020-11-25 08-39-32](https://user-images.githubusercontent.com/5868014/100197016-02e20280-2efa-11eb-9e25-66532ec62ff4.png)
![Capture d’écran de 2020-11-25 08-39-23](https://user-images.githubusercontent.com/5868014/100197050-11c8b500-2efa-11eb-912a-a7f8c62e9bc2.png)

In almost all the cases, the fill goes out of the bounds of the figure. I suppose this is due to having _sketch=true_.

I think it would be interesting to have these fill options available even when _sketch=false_.

**Comment by al-indigo** [comment]
wow! looks great anyway, thanks

**Comment by al-indigo** [comment]
@alderg Yes, sketch=false mode would be even nicer than in sketch mode

**Comment by alderg** [comment]
Let's face it, it's a workaround, but the best solution we have for now.

**Comment by jamesssf** [comment]
Yes please do make this a feature. I have the need to fill shapes with black and white patterns without a "sketch" look.

**Comment by NexusDarkshade** [comment]
Hello, I'd also like to see this applied to more than just sketch style. I'd suggest going with the approach used by the Basic shape "Rectangle with Diagonal Fill" and its variants, which is the fillStyle tag.

**Comment by ashrafteleb** [comment]
![Screen Shot 2022-07-14 at 11 21 31 AM](https://user-images.githubusercontent.com/24944765/178949317-2e9bb59f-79dc-4e89-b0c6-32c6a710ebf0.png)

Feature added!

**Comment by jamesssf** [comment]
Awesome thanks!

**Comment by smoliji** [comment]
> Feature added!

How come I don't see the dropdown to select Hatch? It is visible for me only when I select Sketch. I am trying with common rectangle. 
![image](https://user-images.githubusercontent.com/6990251/196777982-0d2a4b90-676f-4da3-b83a-a4760874bacc.png)

**Comment by Leative** [comment]
As far as I can see, only the possibility to enable "hatch" has been added as a non-sketch feature. The style configurations concerning hatch (e.g., hachureGap=-1;), however, are not respected when "sketch=0" is set.

It would be great if the hatch could be configured regardless of sketch being enabled.

**Comment by m-mohamedin** [comment]
> As far as I can see, only the possibility to enable "hatch" has been added as a non-sketch feature. The style configurations concerning hatch (e.g., hachureGap), however, are not respected when "sketch=0" is set.
> 
> It would be great if the hatch could be configured regardless of sketch being enabled.

Please create a new issue for this feature request
Thanks

**Comment by taoohong** [comment]
Thank you for your excellent work! However, I'm wondering if there will be support for setting the display density of these hatches in the future?

**Comment by davidjgraph** [comment]
All the updates on the issue are in this thread.

**Comment by gigberg** [comment]
> ![Screen Shot 2022-07-14 at 11 21 31 AM](https://user-images.githubusercontent.com/24944765/178949317-2e9bb59f-79dc-4e89-b0c6-32c6a710ebf0.png)
> 
> Feature added!

thanks, but this hatching texture in non sketch mode, can not be adjusted to custom style. An interesting thing is that, the hatching changes its distribution automatically among different scale rate.

**Comment by kaddkaka** [comment]
> > ![Screen Shot 2022-07-14 at 11 21 31 AM](https://user-images.githubusercontent.com/24944765/178949317-2e9bb59f-79dc-4e89-b0c6-32c6a710ebf0.png)
> > Feature added!
> 
> In what version was this added?

Probably version [v20.1.4](https://github.com/jgraph/drawio/releases/tag/v20.1.4)

* Jul 21, 2022 `v20.1.4`
* Jul 12, 2022 `v20.1.1`

**Comment by 108anup** [comment]
Can we control the density of the hatch?

**Comment by iamkroot** [comment]
> Can we control the density of the hatch?

Just hit the same issue. Not super obvious, but it can be done by enabling "sketch" mode on the whole shape, and tweaking `Fill Weight` and `Hatchure Gap`. However, this also enables the "rough" style, which can be disabled by setting `Jiggle` to `0` (essentially creating a non-sketch shape.)

**Comment by acyuzuguler** [comment]
> Can we control the density of the hatch?

This is very much needed.
