### ISSUE TITLE
can't access files in ms sharepoint shared libraries when using the draw.io add-in for word

### ISSUE THREAD

**Issue by brathke** [jgraph/drawio#759]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
can't access files in ms sharepoint shared libraries when using the draw.io add-in for word - selected document folders are always shown as empty

**To Reproduce**
This happens using the draw.io add-in on both the macOS and web versions of MS Word.
1. launch MS Word, click Insert, and then click drawio add-in
2. when I do this I see the initial drawio screen
3. on the drawio screen, I select "Pick OneDrive File", which is successful
4. if I select Files, Recent, or Shared, I see the expected list of files - this seems to indicate successful OneDrive access
5. because I can see Sharepoint files when I select Shared, it seems that the add-in does have access to Sharepoint
6. If I select Sharepoint, I see a list of Sharepoint sites
7. If I select my team's site, I don't see any files

**Expected behavior**
When I select Sharepoint and my team site I expect to see files/folders

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**
Version
1.0.0.0
Updated
1/17/2020

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04, macOS 10.14.6
 - Browser chrome
 - Version 79.0.3945.130 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ashrafteleb** [comment]
I couldn't reproduce. Is this using the online version of Office or desktop?

**Comment by brathke** [comment]
both

**Comment by ashrafteleb** [comment]
I tried it online and it works. Can you check the browser console and send us the log if there are errors.
Thanks
<img width="333" alt="Screen Shot 2020-03-05 at 6 15 26 PM" src="https://user-images.githubusercontent.com/24944765/76034630-775cb780-5f0d-11ea-829c-ba3943c7b370.png">

**Comment by brathke** [comment]
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
MicrosoftAjax.js:5 OSF_Outil_getQueryStringParamValue: The parameter is not found.
OsfRuntimeWordWAC.js:18 Error while parsing the 'sandbox' attribute: 'ms-allow-popups' is an invalid sandbox flag.
j @ OsfRuntimeWordWAC.js:18
MicrosoftAjax.js:5 OSF_Outil_getQueryStringParamValue: The parameter is not found.
doc.aspx:1 Access to XMLHttpRequest at 'https://word-edit.officeapps.live.com/we/AppSettingsHandler.ashx?app=Word' from origin 'https://fender-my.sharepoint.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
doc.aspx:1 Access to XMLHttpRequest at 'https://word-edit.officeapps.live.com/we/AppSettingsHandler.ashx?app=Word' from origin 'https://fender-my.sharepoint.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
doc.aspx:1 Access to XMLHttpRequest at 'https://word-edit.officeapps.live.com/we/AppSettingsHandler.ashx?app=Word' from origin 'https://fender-my.sharepoint.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
word-edit.officeapps.live.com/we/AppSettingsHandler.ashx?app=Word:1 Failed to load resource: net::ERR_FAILED
word-edit.officeapps.live.com/we/AppSettingsHandler.ashx?app=Word:1 Failed to load resource: net::ERR_FAILED
word-edit.officeapps.live.com/we/AppSettingsHandler.ashx?app=Word:1 Failed to load resource: net::ERR_FAILED
MicrosoftAjax.js:5 onClickInsertOsfControl!
MicrosoftAjax.js:5 _isOsfControlInEmbeddingMode error. Exception details: {}
OsfRuntimeWordWAC.js:18 Unrecognized feature: 'focus-without-user-activation'.
_setSandboxAttribute @ OsfRuntimeWordWAC.js:18
2common.min.js:16 The icon "cancelglyph_16" was used but not registered. See http://aka.ms/fabric-icon-usage for more information.
r @ common.min.js:16
2graph.microsoft.com/v1.0/me/drive/root:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
DevTools failed to parse SourceMap: https://c1-word-edit-15.cdn.office.net/we/s/161270433700_App_Scripts/al.min.js.map
DevTools failed to parse SourceMap: https://c1-word-edit-15.cdn.office.net/we/s/161270433700_App_Scripts/common50.min.js.map
DevTools failed to parse SourceMap: https://c1-word-edit-15.cdn.office.net/we/s/161270433700_App_Scripts/canvasContextual.min.js.map
DevTools failed to parse SourceMap: https://c1-word-edit-15.cdn.office.net/we/s/161270433700_App_Scripts/uiFabricLazy.min.js.map
DevTools failed to parse SourceMap: https://c1-officeapps-15.cdn.office.net/we/s/161270433700_App_Scripts/Feedback/latest/officebrowserfeedback_floodgate.min.js.map
DevTools failed to parse SourceMap: https://c1-word-edit-15.cdn.office.net/we/s/161270433700_App_Scripts/wacBoot.min.js.map
DevTools failed to parse SourceMap: https://c1-word-edit-15.cdn.office.net/we/s/161270433700_App_Scripts/ir-ideas-ranker.min.js.map
DevTools failed to parse SourceMap: https://c1-word-edit-15.cdn.office.net/we/s/161270433700_App_Scripts/common.min.js.map
DevTools failed to parse SourceMap: https://c1-word-edit-15.cdn.office.net/we/s/161270433700_App_Scripts/canvasAtMentions.min.js.map
DevTools failed to parse SourceMap: https://c1-word-edit-15.cdn.office.net/we/s/161270433700_App_Scripts/appResourceLoader.min.js.map
DevTools failed to parse SourceMap: https://c1-word-edit-15.cdn.office.net/we/s/161270433700_App_Scripts/appChrome.min.js.map
DevTools failed to parse SourceMap: https://c1-word-edit-15.cdn.office.net/we/s/161270433700_App_Scripts/otelFull.min.js.map
DevTools failed to parse SourceMap: https://c1-word-edit-15.cdn.office.net/we/s/161270433700_App_Scripts/pdfjsWorker.min.js.map
DevTools failed to parse SourceMap: https://c1-word-edit-15.cdn.office.net/we/s/161270433700_App_Scripts/versionHistory.min.js.map
DevTools failed to parse SourceMap: https://c1-word-edit-15.cdn.office.net/we/s/161270433700_App_Scripts/wordVersionHistory.min.js.map
DevTools failed to parse SourceMap: https://c1-word-edit-15.cdn.office.net/we/s/161270433700_App_Scripts/uiSlice20.min.js.map

**Comment by ashrafteleb** [comment]
Unfortunately the logged errors are not related to draw.io.
Can you please check with others in your organization sharepoint account if they have the same issue

**Comment by brathke** [comment]
Yes, others have the same problem. I am unaware of anyone here that doesn’t have the problem. Our workaround is to share folders/doc with ourselves and then we can access in the Shared list

________________________________

**Comment by ashrafteleb** [comment]
OK, can you please open the console and network again and clear both before opening sharepoint. Then open sharepoint and double click one of the sites that is shown empty. Now, send us the console log and network log.

Mainly, we are interested in the results of these API calls:

- https://graph.microsoft.com/v1.0/sites?search=
- https://graph.microsoft.com/v1.0/sites/xyz.sharepoint.com,123/drive/root/children?select=id,name,description,parentReference,file,createdBy,lastModifiedBy,lastModifiedDateTime,size,folder,remoteItem,@microsoft.graph.downloadUrl

Thanks

**Comment by brathke** [comment]
ac.js:263 XHR finished loading: GET "https://graph.microsoft.com/v1.0/sites?search=".
AC.doAuthRequest
@
ac.js:263
fillFolderFiles
@
index.js:286
(anonymous)
@
index.js:356
ac.js:263 XHR finished loading: GET "https://graph.microsoft.com/v1.0/sites/fender.sharepoint.com,b35975cf-1b8e-…y,lastModifiedDateTime,size,folder,remoteItem,@microsoft.graph.downloadUrl".
AC.doAuthRequest
@
ac.js:263
fillFolderFiles
@
index.js:286
openFile
@
index.js:87
﻿
​

**Comment by ashrafteleb** [comment]
So, there was no errors in the console?
The two requests look like they worked (HTTP response 200). Can you share the results of these API calls?

**Comment by brathke** [comment]
sorry I thought I responded to this. No errors in the console, no files in the sharepoint list. How do I share the results of the API calls?

**Comment by ashrafteleb** [comment]
Open the browser console, select the Network tab, then from draw.io add-in, click the Sharepoint and then double click one of the sites. Back to the Network tab, find the requests (you can use filter box to quickly find them) and send us the Response as shown in this screenshot
<img width="1612" alt="Screen Shot 2020-03-21 at 9 38 06 AM" src="https://user-images.githubusercontent.com/24944765/77227582-b3238e00-6b57-11ea-8d97-fd25873f263c.png">

**Comment by brathke** [comment]
{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#sites('fender.sharepoint.com%2Cb35975cf-1b8e-4650-874a-6c99d658af08%2C911881ed-69ae-4bbe-8164-ed618ed66006')/drive/root/children","value":[{"@microsoft.graph.downloadUrl":"https://fender.sharepoint.com/sites/electronicsrd/_layouts/15/download.aspx?UniqueId=90b5b0b6-4ed3-4f25-9eff-a053837196c2&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvZmVuZGVyLnNoYXJlcG9pbnQuY29tQGNjOGQ4MzRmLTg1ZjktNDRjYy04OGU2LTNlNWI4YjM5MGRlYSIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE1ODQ4OTIzMTQiLCJleHAiOiIxNTg0ODk1OTE0IiwiZW5kcG9pbnR1cmwiOiJnQjNJRjNNN3kwdW1tYjZFRWgzZ1lOMFJNYkRucU5ydkxQdjBEQjdXaWVNPSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTM3IiwiaXNsb29wYmFjayI6IlRydWUiLCJjaWQiOiJZak5qWVRRMFlUSXRObUprTVMwME5tVXlMVGhoWlRZdE1qRXhZV1ppWldRNU5EUXgiLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiWWpNMU9UYzFZMll0TVdJNFpTMDBOalV3TFRnM05HRXRObU01T1dRMk5UaGhaakE0IiwiYXBwX2Rpc3BsYXluYW1lIjoiZHJhd2lvIiwiZ2l2ZW5fbmFtZSI6IkJlbiIsImZhbWlseV9uYW1lIjoiUmF0aGtlIiwic2lnbmluX3N0YXRlIjoiW1wia21zaVwiXSIsImFwcGlkIjoiNDVjMTA5MTEtMjAwZi00ZTI3LWE2NjYtOWU5ZmNhMTQ3Mzk1IiwidGlkIjoiY2M4ZDgzNGYtODVmOS00NGNjLTg4ZTYtM2U1YjhiMzkwZGVhIiwidXBuIjoiYnJhdGhrZUBmZW5kZXIuY29tIiwicHVpZCI6IjEwMDMwMDAwODkxNTYxNjQiLCJjYWNoZWtleSI6IjBoLmZ8bWVtYmVyc2hpcHwxMDAzMDAwMDg5MTU2MTY0QGxpdmUuY29tIiwic2NwIjoiYWxsZmlsZXMucmVhZCBhbGxmaWxlcy53cml0ZSBhbGxzaXRlcy5yZWFkIGFsbHByb2ZpbGVzLnJlYWQiLCJ0dCI6IjIiLCJ1c2VQZXJzaXN0ZW50Q29va2llIjpudWxsfQ.NWhtem5QRzFVY2JjNjNBTEM3OUJ2TjlrWEd6bFlQbEVWNlU2aHp4MGJkaz0&ApiVersion=2.0","id":"01H4C3RXNWWC2ZBU2OEVHZ575AKOBXDFWC","lastModifiedDateTime":"2020-03-05T20:06:11Z","name":"aaa.jpg","size":268641,"createdBy":{"application":{"id":"09abbdfd-ed23-44ee-a2d9-a627aa1c90f3","displayName":"ProjectWorkManagement"},"user":{"email":"brathke@fender.com","id":"2962b29b-2c84-4693-8524-e350cf1bf08f","displayName":"Ben Rathke"}},"lastModifiedBy":{"application":{"id":"09abbdfd-ed23-44ee-a2d9-a627aa1c90f3","displayName":"ProjectWorkManagement"},"user":{"email":"brathke@fender.com","id":"2962b29b-2c84-4693-8524-e350cf1bf08f","displayName":"Ben Rathke"}},"parentReference":{"driveId":"b!z3VZs44bUEaHSmyZ1livCO2BGJGuab5LgWTtYY7WYAbSpWCJ2769T4tHS8Im4HLd","driveType":"documentLibrary","id":"01H4C3RXN6Y2GOVW7725BZO354PWSELRRZ","path":"/drive/root:"},"file":{"mimeType":"image/jpeg","hashes":{"quickXorHash":"aYfiWD1s/VCAL/tVKJ/+22JV2GA="}}}]}

**Comment by ashrafteleb** [comment]
I'm confused, the response is correct and indicates that you have one file only (aaa.jpg) in this Sharepoint site. Is that correct or that site contains other files?

BTW, we filter non-supported files so **that site will be empty in draw.io UI**. We only show files that draw.io can open (.drawio, .xml, .html, .png, .svg, ...)

**Comment by brathke** [comment]
ok, I understand what the problem is now. You are only displaying the default Document library "Documents". Our sharepoint site is made up of a number of document libraries (which isn't an unusual practice). These other document libraries are at the same level as the "Documents" folder.
________________________________

**Comment by ashrafteleb** [comment]
Actually we show all sites, but within each site we filter the files content. Folders and Sites and not filtered

<img width="333" alt="Screen Shot 2020-03-23 at 1 06 47 PM" src="https://user-images.githubusercontent.com/24944765/77342829-2d464500-6d07-11ea-9deb-71d253c503cf.png">

**Comment by brathke** [comment]
I do see all sites. The problem is that once I select one of those sites, instead of seeing the list of Document Libraries, I see the contents of the Default Document Library.
________________________________

**Comment by ashrafteleb** [comment]
Sorry I don't understand. Can you send me a screenshot of what you see in draw.io UI vs what you see in Sharepoint/OneDrive?

**Comment by brathke** [comment]
In the pic below, "Documents" is what you are displaying (i.e. it is the one contains aaa.jpg).
![document-libraries](https://user-images.githubusercontent.com/6911903/77345925-9079ac80-6cf2-11ea-8b80-88258585018c.png)

**Comment by ashrafteleb** [comment]
Can you send us the response of the API when you open the "Electronics R&D" site please.

**Comment by ashrafteleb** [comment]
I understand what you mean now. I didn't know that a library can contain another one.

Thanks for your patience. We will try to fix it

**Comment by brathke** [comment]
Excellent. Thanks so much for your patience too! 🙂
________________________________

**Comment by ashrafteleb** [comment]
You are most welcome

Fixed. Will be available in the next release

**Comment by ashrafteleb** [comment]
It's deployed now. Does it work as expected now?

**Comment by brathke** [comment]
it works! Thanks!
________________________________

**Comment by ashrafteleb** [comment]
You are most welcome
