### ISSUE TITLE
Teams chat integration

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#761]

**Comment by GiantCrocodile** [comment]
What is this issue about: draw.io as a standalone app/bot for Microsoft Teams or as an app within Microsoft Team's channels? In channels you could embed it as a website already. That should work, right?

**Comment by andresmmujica** [comment]
can you elaborate on embed draw.io as a website within a Microsoft Team channel?

**Comment by GiantCrocodile** [comment]
Hi @andresmmujica! Check out this tutorial: https://docs.microsoft.com/en-us/microsoftteams/built-in-custom-tabs (You have to add a website tab)

**Comment by MikelisDz** [comment]
did embedding diagram as a website work for you? For me, it says that it lacks Javascript

**Comment by GiantCrocodile** [comment]
You are right @MikelisDz! It shows a javascript error:

```
Flowchart Maker and Online Diagram Software
diagrams.net (formerly draw.io) is free online diagram software. You can use it as a flowchart maker, network diagram software, to create UML online, as an ER diagram tool, to design database schema, to build BPMN online, as a circuit diagram maker, and more. draw.io can import .vsdx, Gliffy™ and Lucidchart™ files .

Page could not be loaded. Please try refreshing.
Please ensure JavaScript is enabled.
```

**Comment by MikelisDz** [comment]
@GiantCrocodile from the response on Microsoft Tech Community forums it seems that nothing with JavaScript will work in website tab.

**Comment by davidjgraph** [comment]
What's the link to the thread? Will the SVG of the diagram work?

**Comment by MikelisDz** [comment]
@davidjgraph there hasn't been any answers from devs, but others have reported the same problem. Couldn't find anything more within older posts there. 
https://techcommunity.microsoft.com/t5/microsoft-teams/webiste-tab-that-contains-javascript/m-p/1352710#M56257

**Comment by GiantCrocodile** [comment]
I think an update to Microsoft Teams did fix this:

![grafik](https://user-images.githubusercontent.com/6271057/81160923-07a98e00-8f8b-11ea-842e-8d26dff613e9.png)

This tab didn't work in the past (see previous comments) but works now.

**Comment by MikelisDz** [comment]
Seems you are right - only now I cannot login with my Ondrive, gets error "Automatic login interrupted. Please close and select OneDrive again.", but it works from Device. However seems that it is still very limited in usability, since every time I click away to another chat, team or anything it asks again to open the file. 
Not sure also how to make it usable Team-wide. If I place the .drawio file within Team Onedrive folder I hope every team member can open it and edit - not simultaneously of course. Co-working would be nice though.

**Comment by InternetMaster1** [comment]
This would be such an amazing feature to have! Just like LucidWorks, etc are built-in inside MIcrosoft Teams as an app, would be great to have a deeper integration of draw.io with Microsoft Teams.

**Comment by ashrafteleb** [comment]
Coming Soon!

**Comment by shibumi** [comment]
@ashrafteleb  do you have an update? How does this work in Teams?

**Comment by dieskim** [comment]
hi is there any news on this? is there a beta version or something we can try? Thanks

**Comment by davidjgraph** [comment]
No, we lack resources at the moment to finish publishing it.

**Comment by dieskim** [comment]
anything anyone can do to help or not really? is there a way you can make the app available for us to test and upload to our org via beta or something?

**Comment by davidjgraph** [comment]
If you could take a bunch of my internal support tickets :)

**Comment by Floriszz** [comment]
Sometimes a screenshot says more than a thousand words. Click a draw.io file in Teams Channel - Files and...
![image](https://user-images.githubusercontent.com/19168937/124784112-e86b0f80-df45-11eb-8d9d-93d99499884b.png)

**Comment by shibumi** [comment]
@Floriszz can two people work on the same file on real-time?

**Comment by dieskim** [comment]
@davidjgraph is integration ready now or not yet?

**Comment by Floriszz** [comment]
> @Floriszz can two people work on the same file on real-time?

Interesting! not tried. 
From a user perspective you just would like the draw.io file to be shown/opened in that window. Not a download button. Just as an image or Visio drawing.

**Comment by dgrospelier** [comment]
Is it planned to release an integration with MS Teams in order to co-author a draw.io file?

**Comment by dieskim** [comment]
> No, we lack resources at the moment to finish publishing it.

Any update on when we could expect Teams Integration?

**Comment by davidjgraph** [comment]
The current position is Microsoft see functionality failures on their side when testing the integration that we cannot repeat. If anyone knows a good contact within Microsoft...

**Comment by davidjgraph** [comment]
We've been rejected about 15 times now, still working on them.

**Comment by davidjgraph** [comment]
https://appsource.microsoft.com/en-GB/product/office/wa200003444

**Comment by Floriszz** [comment]
It seems to work for me(who added the plugin and link to the draw.io fille. But although my colleagues(Ms Team members of th the channel) can see the links in the tabs and can click on them, they will never get passed the authorization popup for Onedrive.(The draw.io files are not in my Onedrive, but in the MS Teams Site which is a SharePoint Site as well)
![image](https://user-images.githubusercontent.com/19168937/140765076-0b4c51ec-ae8a-45a1-83c6-2602341e6472.png)

**Comment by shibumi** [comment]
@Floriszz does it allow multi-user-support? Can multiple users draw  in it at the same time? Or is it just a "viewer" in Teams?

**Comment by Floriszz** [comment]
> @Floriszz does it allow multi-user-support? Can multiple users draw in it at the same time? Or is it just a "viewer" in Teams?

I tried both with the checkmark for 'editable' marked and unmarked. But for either situation same thing(screen). Everyone in the team has read/write access to the source where the draw.io files are stored in SharePoint.
![image](https://user-images.githubusercontent.com/19168937/140770316-8541b5bd-5744-41ab-bc12-3ff57f826192.png)

**Comment by shibumi** [comment]
@Floriszz ok, but the main question is: Can two or more people work simultaneously on the same diagram?

**Comment by ashrafteleb** [comment]
@Floriszz We need to debug this, can you check the browser console and send us any errors there (please try the bowser version of Teams for that). Also, it's better to open a new issue for that error

@shibumi Yes, the same collaborative editing of OneDrive in draw.io editor (near real-time)

**Comment by Floriszz** [comment]
> @Floriszz ok, but the main question is: Can two or more people work simultaneously on the same diagram?

I never tried. The intention of showing in Teams is just to be able to share a draw.io file that everyone can read. Just like with MS Visio files in Ms Teams.

**Comment by Wachert** [comment]
We got the same problem. I created a Tab with draw.io Files on Sharepoint, but other users can't see the tab. I then tried to share the draw io File on share point with that users, but they still can't see the tab in Teams. All other Tabs like Excel files etc. are working.

**Comment by davidjgraph** [comment]
Please open new issues for new issues, this thread is unreadable with all the different topics.

**Comment by davidjgraph** [comment]
Reopening, as we've killed the teams integration.
