### ISSUE TITLE
Download offline version?

### ISSUE THREAD

**Issue by martijintro** [jgraph/drawio#767]
Can't download it as described here: https://about.draw.io/use-draw-io-offline/

The link https://www.draw.io/app leads me to the online webapp, instead to a .zip (or similar) installer download: https://www.draw.io/index.html?offline=1

So where to download the offline version..??

Thx for feedback,
Jan

**Comment by davidjgraph** [comment]
Offline in this context mean Progressive Web Application (PWA). For the desktop build, use https://get.draw.io
