### ISSUE TITLE
Can't change text font size smaller than 17pt on Google Chrome / Linux when Chrome Setting is "Minimum Font Size: 17"

### ISSUE THREAD

**Issue by dnygren** [jgraph/drawio#768]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

I can't seem to use a font size smaller than 17pt. If I insert text, I can select the text and make it bigger than 17pt with either the right hand side menu, or top ribbon menu, but if I try and make the selected text smaller, it never goes below 17pt.

I'm using the latest Google Chrome Browser Version 80.0.3987.100 (Official Build) (64-bit) on Linux.

I just tried changing the font size on my drawio drawing to below 17pt on a Windows 10 PC running the Microsoft Edge browser. Everything worked fine there. I was able to change the font size to below 17 without any issues. So the problem isn't with my drawing.

**To Reproduce**
1. Using a Linux x86 PC, Google Drive, 
2. Click on "Create New Diagram"
3. Click on "Blank Diagram"
4. Click on "Create", "Use root folder"
4. Click on "Text" in left hand menu.
5. Select/Highlight "Text"
6. You can make the text selected larger than 17pt but not smaller using right hand side menu, or top ribbon menu, but if you try and make the selected text smaller, it never goes below 17pt.
 
**Expected behavior**
On a Windows PC, everything works as you would expect.

**Screenshots**

![drawio_17pt](https://user-images.githubusercontent.com/32287581/74754644-c8d72800-5226-11ea-9f7f-766495b9e50c.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]
v 12.7.1
© 2005-2020 JGraph Ltd.
All Rights Reserved.

**Desktop (please complete the following information):**
 - OS: Linux
$ uname -a
Linux my-pc 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux
 - Browser: Chrome
 - Version : Google Chrome Browser Version 80.0.3987.100 

**Smartphone (please complete the following information):**
N/A

**Additional context**
This problem has existed since I've been using draw.io (6-7 months). I always thought it was such a glaring bug that it would get fixed by someone else.

**Comment by ashrafteleb** [comment]
I couldn't reproduce on Ubuntu. Can you try another browser and let us know if the issue affect other browsers also?

**Comment by dnygren** [comment]
Thanks for the reply.

I tried with a different browser (Firefox 68.5.0esr (64-bit))  and observed the same behavior. So both Chrome and Firefox on my Debian Linux system are affected. 

On a Windows 10 PC running the Microsoft Edge browser, everything worked properly.

Here's the most recent uname -a output from the affected system:

$ uname -a
Linux my-pc 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux

**Comment by ashrafteleb** [comment]
We cannot reproduce on Debian with Gnome. Which graphical system you use?

**Comment by dnygren** [comment]
I'm using KDE Plasma. Is there some specific version string I should provide to you? If so, tell me how to generate it etc.

**Comment by ashrafteleb** [comment]
I couldn't reproduce using KDE Plasma also. I can only see an inconsistency in the UI where the drop-down menu is showing 11 while font-size is actually 6.
<img width="801" alt="Screen Shot 2020-03-17 at 7 51 22 PM" src="https://user-images.githubusercontent.com/24944765/76912017-c816cd80-6888-11ea-92ec-57695a2d2e25.png">

**Comment by dnygren** [comment]
Any suggestions on how we should proceed? What other information can I provide about my environment. Seems odd the windowing environment could make a difference on a browser based tool. I can send more screenshots etc. but the original example says it all. I'll think about it more tomorrow.

**Comment by ashrafteleb** [comment]
Yes, please

Can you also try changing the font size from right Format Panel (Text tab) [Shown in the above screenshot]. Does it work?

**Comment by dnygren** [comment]
I did some digging. The problem is that the web browsers on my Linux machine have this setting (Example for Chrome):

Chrome triple dots -> Settings -> Appearance -> Customize Fonts -> Minimum Font Size 17

So if I change this to a "17" lower number, I can make the font on a drawing respectively smaller. :-(

So you're thinking this is an operator error and you may want to close this bug. Before you do, let me say that I also use Lucidchart (https://www.lucidchart.com/) another very similar web based drawing tool, and it does not have this bug/feature. It sets the font of the text in the drawing to whatever the application selection pulldown is set to. The Lucidchart drawing font isn't overridden by the web browser font setting.

Sorry you spent so much time trying to reproduce my problem. Based on my use of Lucidchart and drawio's similarity to it, I didn't understand that the browser could possibly override a user's input.

**Comment by ashrafteleb** [comment]
No need to be sorry, it's new to me too. I'll mark the issue as a feature request so we can return to it later.

**Comment by miraculixx** [comment]
@davidjgraph I would like to vote for re-opening this issue, actually I think it is a bug since it removes intended functionality.

**Comment by davidjgraph** [comment]
Voting for issues is done by thumb up on the original post, this issue has no votes.

**Comment by davidjgraph** [comment]
I think this is the correct behaviour, it's just following the browser settings.

Lucidchart, the other example used, uses WebGL for rendering, last I checked. That's a layer above the browser provided text functionality, so I'd expect that it doesn't follow that browser setting.

If a user sets a high font size for accessibility, that should be the minimum size used. The font size can be set smaller in the diagram and other users will see the size as set.

**Comment by dnygren** [comment]
Is there any way to warn a user that the browser minimum font setting is overriding the font setting of the application?

**Comment by davidjgraph** [comment]
I'm don't think that we know the browser has overriden the setting.

**Comment by dnygren** [comment]
I was hoping there was some way for an application to detect that it can't override a browser font setting.
