### ISSUE TITLE
 [Feature Request] Trigger an image update in Confluence

### ISSUE THREAD

**Issue by epsFelixTran** [jgraph/drawio#769]
I'd like to have a feature to trigger an diagram update in Confluence. I am able to change the diagram programmatically, but I'm struggling with the update of the diagram as an image. Having a rest call would be great, but if the development teams finds another way, I wouldn't mind adjusting.

**Comment by davidjgraph** [comment]
Is this server or cloud?

**Comment by epsFelixTran** [comment]
Confluence Server

**Comment by davidjgraph** [comment]
That's tracked as a feature request at https://trello.com/c/F9O6ocCx/190-add-import-from-csv-directly-from-macro

**Comment by epsFelixTran** [comment]
Hi David
It seems like we have a small misunderstanding here. I don't want to import a csv into a draw.io diagram. We are able to change existing diagram from the deflated xml in the attachments. The attachments gets updated with our modifications, but we are currently not able to update the image on the View Mode in Confluence. Currently, we have to open the draw.io editor and save it again, which will finally trigger an image update. I'd like to have some kind of API to trigger said image update.

Best regards,
Felix
