### ISSUE TITLE
Can't "Export as" with custom font

### ISSUE THREAD

**Issue by jgreffe** [jgraph/drawio#772]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When using custom google font and trying to export, an error message is displayed

![image](https://user-images.githubusercontent.com/36693362/75015464-eefc0280-5488-11ea-8872-5e84e6ade14f.png)

**To Reproduce**
1. Add a custom google font, e.g. "Fira Sans"
2. Select a component using this font
3. Go to "File > Export as > JPEG..."
4. Check "Selection only"
5. Click "Export"
6. See error message: "Cannot read property 'https://fonts.googleapis.com/css?family=Fira+Sans' of undefined"

**Expected behavior**
Export should work with custom font.
Export works without custom font.
Export with custom font works with draw.io Desktop v12.6.5.

**Screenshots**
![image](https://user-images.githubusercontent.com/36693362/75015589-4306e700-5489-11ea-8a2a-5d17cdd5100e.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io web v12.7.2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: 80.0.3987.106 (64bit)

**Additional context**
N/A

**Comment by davidjgraph** [comment]
Fixed in 12.7.3. Thanks for report.
