### ISSUE TITLE
[Feature request] Skew text

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#773]
will be helpful for 3D diagrams
![3D](https://user-images.githubusercontent.com/44292306/75031297-40ff5100-54a6-11ea-9782-ae55e1e57212.png)

**Comment by robzach** [comment]
Also requesting this feature.

**Comment by rishikeshrmadan** [comment]
Since this was closed by the bot, should I open another issue? In any case, I too support this feature request of skewing, at least for text.

**Comment by davidjgraph** [comment]
We can open it, but it'll never be done, so kinda misleading.

**Comment by davidjgraph** [comment]
We're not going to implement this.
