### ISSUE TITLE
Additional shapes for the floorpan library

### ISSUE THREAD

**Issue by jaylapras** [jgraph/drawio#779]
Request - additional shapes in the Floorplan shape library for: 

* sliding doors
* accordion-style doors
* bifold doors
* bay windows
* swing (double action) doors

Similar to that those at: https://i.pinimg.com/originals/30/ce/35/30ce3516eb95d96570ca1c0b945bc55c.png and https://paintingvalley.com/drawings/sliding-door-plan-drawing-34.jpg

**Comment by egrimate** [comment]
Will be in next release
