### ISSUE TITLE
Shortcuts for navigation between pages

### ISSUE THREAD

**Issue by stealthcold** [jgraph/drawio#781]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
It would be nice to have shortcuts to navigate to the next/previous page and maybe to go to the first/last page too.

**Describe the solution you'd like**
Press something like ALT + Page Down/Up and then navigate to the next/previous page.

**Describe alternatives you've considered**
I searched the web but found no plugin with this functionality.

**Comment by davidjgraph** [comment]
https://www.draw.io/shortcuts.svg

cmd/ctrl + shift + page up or down.

**Comment by stealthcold** [comment]
Oh, my fault! 😐

I tried this combination before, but now I see that the pages I'm trying to navigate are so heavy that it takes too long to change between them.

Thanks for the cheatsheet!
