### ISSUE TITLE
can't open already existing diagrams

### ISSUE THREAD

**Issue by ddrs15** [jgraph/drawio#788]
if i try to open an already existing diagram it asks to log in to google, (pop up screen with google and red button to log in) if i hit login then it opens another screen shortly and then closes that again and nothing happens, if i hit login again it says:

Er is een fout opgetreden.(translation: an error has occurred.)

Details:

The feature you requested is currently unavailable. Please try again later.

and then i just can't do anything but close the 'pop up' screen and then im back where i started; the screen where i can choose to open a new diagram or an existing one, this is really annoying.
i can however go to my drive and just open a already existing diagram from drive by just opening one with draw.io. but i can't open existing diagrams from within draw.io.

i don't know if i just have some setting wrong or if this is a common issue but it would be nice if this problem could be resolved.

**Comment by ashrafteleb** [comment]
Can you try again in an incognito window. If it works, then you need to clear the browser cache

Otherwise, please share your console output

**Comment by ddrs15** [comment]
![2020 03 04-16 07_02](https://user-images.githubusercontent.com/47245725/75893039-8a4e8980-5e32-11ea-81af-1cde25c16de8.png)
![2020 03 04-16 08](https://user-images.githubusercontent.com/47245725/75893044-8b7fb680-5e32-11ea-9beb-636c9dfab56a.png)
![2020 03 04-16 08_01](https://user-images.githubusercontent.com/47245725/75893046-8b7fb680-5e32-11ea-8417-1894ef1064ba.png)
![2020 03 04-16 07](https://user-images.githubusercontent.com/47245725/75893047-8c184d00-5e32-11ea-9870-2a73a2a1a682.png)
![2020 03 04-16 07_01](https://user-images.githubusercontent.com/47245725/75893048-8c184d00-5e32-11ea-9afe-4beef2f6b387.png)

this is what i got, this is in incognito and it still doesn't work

**Comment by ddrs15** [comment]
i tried importing from drive in these pictures but opening from drive gives the same results

**Comment by ddrs15** [comment]
![2020 03 04-16 12](https://user-images.githubusercontent.com/47245725/75893384-02b54a80-5e33-11ea-91d7-b864a16446c8.png)
![2020 03 04-16 12_01](https://user-images.githubusercontent.com/47245725/75893391-0517a480-5e33-11ea-8df2-530a319ab797.png)
![2020 03 04-16 12_02](https://user-images.githubusercontent.com/47245725/75893398-0779fe80-5e33-11ea-9f67-d31c8980c839.png)
![2020 03 04-16 12_03](https://user-images.githubusercontent.com/47245725/75893403-0943c200-5e33-11ea-968d-bf7beef2d989.png)

opening from drive in the right order(i hope)

**Comment by ddrs15** [comment]
turning of adblocker doesn't change anything

**Comment by ashrafteleb** [comment]
There is something strange with your system. The login should show up in a popup window (no an iframe as the screenshots shows)
<img width="471" alt="Screen Shot 2020-03-04 at 10 33 02 AM" src="https://user-images.githubusercontent.com/24944765/75895368-8d7e5100-5e03-11ea-9457-55ee686c3926.png">

Can you try another browser?

**Comment by Achllle** [comment]
I'm getting the exact same issue. In Chrome, I removed cookies and site data and whitelisted app.diagrams.net and diagrams.net in third party. Did not help. I tried Brave Browser and I do get the popup, but then I get the second login page with red button as above and it takes me to same `The feature you requested is currently unavailable. Please try again later.` Same error with the chrome extension. On Mac and Ubuntu16.

**Comment by davidjgraph** [comment]
What chrome incognito or Firefox? What extensions do you have installed?

**Comment by Achllle** [comment]
Same story on Chrome or Brave Incognito. It shows the login popup and declares that the app already has access to my drive, but then when I click 'open diagram', I get the red button google login window again, which crashes after the second try.

**Comment by davidjgraph** [comment]
How are you opening it? From drive.google.com->open with->diagrams.net?

**Comment by Achllle** [comment]
No, when I do it that way, it works fine. When I navigate to diagrams.net first and click 'open existing diagram' it doesn't work.

**Comment by seanf** [comment]
I was getting the same problem (in Brave) until I enabled third-party cookies. Then it was fine.

**Comment by davidjgraph** [comment]
I think we've got too many different issues in one thread. I'd suggest to start a new thread on https://groups.google.com/g/drawio if you're still having issues.
