### ISSUE TITLE
How to import XML stencil containing <shapes> element?

### ISSUE THREAD

**Issue by slokhorst** [jgraph/drawio#789]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

This is more of a question than a bug.

I was looking for a "Pressure Reducing Valve" in the shapes, but unfortunately couldn't find it. I searched around online and came across [src/main/webapp/stencils/pid/valves.xml](https://github.com/jgraph/drawio/blob/master/src/main/webapp/stencils/pid/valves.xml) in this repository, which to my surprise contains `<shape aspect="variable" h="60" name="Pressure Reducing Valve" strokewidth="inherit" w="70">`. This would suggest it is available in the `Proc. Eng. / Valves` shape library.

So my question: is this shape actually available in draw.io, and did I just not look in the right place? Or can I import `valves.xml` in some way, so I can still use it?

**Comment by slokhorst** [comment]
As a workaround, I copied the relevant shape from `valves.xml`:
```xml
<shape aspect="variable" h="60" name="Pressure Reducing Valve" strokewidth="inherit" w="70">
    <connections/>
    <background>
        <path>
            <move x="0" y="20"/>
            <line x="20" y="30"/>
            <line x="0" y="40"/>
            <close/>
            <move x="70" y="0"/>
            <line x="70" y="60"/>
            <line x="20" y="30"/>
            <close/>
        </path>
    </background>
    <foreground>
        <fillstroke/>
        <fillcolor color="#000000"/>
        <ellipse h="4" w="4" x="18" y="28"/>
        <fillstroke/>
    </foreground>
</shape>
```

And imported it into Diagrams.net by following [Create custom shapes in diagrams.net using the text editor](https://desk.draw.io/support/solutions/articles/16000070744-create-custom-shapes-in-diagrams-net-using-the-text-editor):

_Arrange_ > _Insert_ > _Shape_ and then paste the snippet from above in the textbox. After you insert it you can save it in your Scratchpad to reuse it again later.

**Comment by egrimate** [comment]
Hi,

That valve shape is removed because of a newer valve library was added. But you can use it by dropping any shape on canvas and replacing its style with "shape=mxgraph.pid.valves.pressure_reducing_valve;". Let us know if this helps.
