### ISSUE TITLE
Lag observe when 

### ISSUE THREAD

**Issue by vishalsatam** [jgraph/drawio#790]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When a large number ( > 1000 components) are added on one page in a diagram, DrawIO slows down and performing any UI actions such as moving a component from one point to another, renaming, changing properties, dragging stencils to the drawing area, etc.

**To Reproduce**
1. Add a large number of components on one page in the diagram
2. Try to perform UI actions like moving a component from one point to another, renaming, changing properties, dragging stencils to the drawing area, etc.
3. You should observe that it takes more than a second in some cases for the action to complete rendering on the UI.

**Expected behavior**

**Screenshots**
N/A

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [12.7.9]

**Desktop (please complete the following information):**
 - OS: iOS and Windows
 - Browser Chrome and Firefox
 - Version Chrome - 79, Firefox - 68

**Smartphone (please complete the following information):**

**Additional context**
N/A

**Comment by davidjgraph** [comment]
I cannot repeat this. I put 1800 rectangles onto the canvas and all the operations mentioned took less than a second. Please provide exact reproduction steps ("a large number of components" is not exact).

**Comment by vishalsatam** [comment]
Attaching a diagram. Try dragging stencils into the drawing area. or try moving some components. You will start noticing a lag while moving components around. I'm not sure how much the response time should be for these movements but I can definitely see slowness while trying to perform actions in the UI.

[Untitled Diagram.drawio.zip](https://github.com/jgraph/drawio/files/4283005/Untitled.Diagram.drawio.zip)
