### ISSUE TITLE
[Bug] Misaligned text and failed cropping when exporting PDF

### ISSUE THREAD

**Issue by mhoff** [jgraph/drawio#80]
In this [drawing](https://github.com/jgraph/draw.io/files/824059/bug.xml.zip), there is a significant discrepancy between the view in the editor and the rendered PDF.

**Editor**

![On Website](https://cloud.githubusercontent.com/assets/9436725/23652365/ebb2575a-0328-11e7-8d55-44aff69648f7.png)

**PDF**

![PDF](https://cloud.githubusercontent.com/assets/9436725/23652441/490162fc-0329-11e7-979a-abf384129914.png)

1. The text is placed at the bottom
2. The cropping fails because of this (second PDF page)

I can compensate this error by aligning the text to the top or the bottom and then padding it to the center. This is what I did for the right node ("WebGL interface"). Otherwise the same would have happened here too.

This might be related to the unicode character "Ø" in "ØMQ". This text node does face the same issue and I could only place it at the right position by playing with the alignment. In the editor, this text node appears to extend way further to the south as it normally should.

Sidenote: I just started using draw.io; As someone coming from TikZ & Inkscape I really appreciate the high quality and the intuitive design of this project. Keep up the good work!

**Comment by davidjgraph** [comment]
Could you attach your test case?

**Comment by mhoff** [comment]
First sentence, there is the XML. Or do you need anything else?

**Comment by davidjgraph** [comment]
Sorry, missed that.

**Comment by mhoff** [comment]
In this [diagram](https://github.com/jgraph/draw.io/files/841139/bug.xml.zip) I experience apparently related issues.

**Editor:**
Top, "MUSIC" text object is way higher than the actual text.

![screenshot from 2017-03-14 12 43 41](https://cloud.githubusercontent.com/assets/9436725/23899058/ed8dc448-08b3-11e7-9950-c6fd3e7c7cc4.png)

Bottom, the Sigma (first blue box from the left) is misaligned (same as "ØMQ" in the original comment) and causes a second PDF page to be generated.

![screenshot from 2017-03-14 12 44 40](https://cloud.githubusercontent.com/assets/9436725/23899078/0346988c-08b4-11e7-9342-537bea591030.png)

**PDF:**

Top, unnecessary space in exported and automatically cropped (by draw.io) PDF.

![screenshot from 2017-03-14 12 45 36](https://cloud.githubusercontent.com/assets/9436725/23899121/31187f82-08b4-11e7-8a0f-ed90c85af87e.png)

Bottom, second PDF page.

![screenshot from 2017-03-14 12 45 49](https://cloud.githubusercontent.com/assets/9436725/23899127/3667e28e-08b4-11e7-9800-414bfbb6f8a3.png)

**Comment by alderg** [comment]
So the actual bug in this report is the second page in PDF export? (The Music shape can be resized manually, sigma isn't visible in the screenshot, cropping is a feature not a bug.)

**Comment by mhoff** [comment]
I think this issue addresses multiple consequences of one bug. To summarize, the attached diagrams and screenshots show the following faulty behaviour(s):

1. Centered text gets aligned to the bottom when exporting as PDF
2. Some text objects are significantly larger than the actual text contained
3. PDF export with cropping yields multiple pages

(1) and (2) seem to cause (3). The [first comment](https://github.com/jgraph/draw.io/issues/80#issue-212392810) demonstrates how (1) leads to a second PDF page. The [second comment](https://github.com/jgraph/draw.io/issues/80#issuecomment-286398460) shows how (2) leads to weird spacing at the top and a second page at the bottom.

>  So the actual bug in this report is the second page in PDF export?

It is one part of the bug, yes.

> The Music shape can be resized manually

I urge you to try out the attached test case. Yes, you can adapt the shape of the MUSIC shape, but even in the editor you can see that somehow the object is still bigger then the shape boundaries. The following screenshot shows the MUSIC shape. Unfortunately taking the screenshot has modified the mouse cursor, but in the editor you could actually _move the object_ by starting dragging _at this position_. So, even the editor shows this faulty behaviour. My first idea was that this is related to unicode characters, but now I think this has to do maybe with the font and especially with big font sizes.

![screenshot from 2017-03-14 15 22 32](https://cloud.githubusercontent.com/assets/9436725/23905116/53307e24-08ca-11e7-8b65-a368ffbdb05e.png)

> sigma isn't visible in the screenshot

Sorry for that, but the test case is attached.

> cropping is a feature not a bug

Did I say something against that? The cropping behaves in the wrong way.
