### ISSUE TITLE
Integration with OneDrive fails on App authorization

### ISSUE THREAD

**Issue by xdanos** [jgraph/drawio#801]
When trying to authorize https://diagrams.net application with OneDrive the following message appears after login:

` AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: <app-id-goes-here>`

Maybe there is some old https://draw.io back-link left in the integration code?

**Comment by mikelambrellis** [comment]
Came to report the same thing. Have tried this on multiple machines (Win & Mac), multiple browsers (Firefox, Safari, (new) Edge), and multiple networks. Have tried logging out of my Microsoft account, have tried blowing away cookies. Same error on the "Authorize" step when trying to use OneDrive the first time with app.diagrams.net.

**Comment by davidjgraph** [comment]
Fixed in 12.8.3
