### ISSUE TITLE
Issues with floor planner stencils

### ISSUE THREAD

**Issue by vic-t** [jgraph/drawio#802]
I noticed the following issues when working with draw.io and the floor planner stencils: 

- It's not possible to rotate a grouped object. 
- It's not possible to position objects such as walls or doors in any other angle than 90 degrees. 

Would be nice if this could be made possible. If not every angle can be supported, maybe just 45°.

**Comment by ashrafteleb** [comment]
More details please. We can rotate walls and doors when we tested
![Screen Shot 2020-03-10 at 10 38 43 AM](https://user-images.githubusercontent.com/24944765/76323641-586a7680-62bb-11ea-8fd4-710339e6dc6c.png)

**Comment by vic-t** [comment]
I can't seem to be able to reproduce this issue any longer.
