### ISSUE TITLE
Deselecting arrows and swim-lanes

### ISSUE THREAD

**Issue by abmyii** [jgraph/drawio#803]
I have a graph which contains items inside swim-lanes connected by arrows. Whilst selecting the items I sometimes accidentally click on arrows or inside the swim-lane itself. As there seems to be no way to deselect an arrow or the swim-lane, I have to re-select all the items again. Is there any solution for this?

**Comment by alderg** [comment]
Have you tried Shift+Click?

**Comment by alderg** [comment]
Thanks for the report, this will be fixed in the next release (use Shift+Click).

**Comment by abmyii** [comment]
> Thanks for the report, this will be fixed in the next release (use Shift+Click).

Great, thank you for this amazing software!
