### ISSUE TITLE
Google Docs addon source?

### ISSUE THREAD

**Issue by kjhughes** [jgraph/drawio#807]
Is the source for the Google Docs addon available?  If so, where it it?  (I see the [Google Sheets addon source](https://github.com/jgraph/drawio/tree/master/etc/sheetsaddon), but not the Google Docs addon source.)  If it is not currently available, could it be? 

Regardless, I would like to thank you for creating draw.io Diagrams and for making its source code available.  Amazing work!  Thank you.

**Comment by davidjgraph** [comment]
Better late than never, https://github.com/jgraph/drawio-google-docs.
