### ISSUE TITLE
Disable/set autosave when saving to device

### ISSUE THREAD

**Issue by spigelli** [jgraph/drawio#808]
When saving to the device I'm constantly waiting for the auto save to finish while frozen. It would be nice if I could just edit the time for auto save in settings

**Comment by ashrafteleb** [comment]
Is this related to desktop app?

What is your version and which OS/OS version

**Comment by chuck11001** [comment]
I'm having the same issue -- running the Windows 10 desktop version -- autosave seems to be triggering on every change to the document, and takes 5-10 each save.

**Comment by ashrafteleb** [comment]
We cannot reproduce. Autosave indeed is triggered with every change and takes few seconds BUT we still can use the app and we couldn't reproduce the freeze issue.

Please, explain the exact environment (OS version, architecture, app version, ...)

**Comment by mjs2020** [comment]
Same, running on macOS Catalina 10.15.5 with draw.io desktop app 13.3.1.
Working on a large diagram save takes ~3-4s and app is frozen in the meantime (e.g. can't move objects, edit text etc).
I' be happier with an option to set autosave frequency so I could do it every few mins.

**Comment by chuck11001** [comment]
@mjs2020 I ending up ditching the desktop app and using the browser based version.

**Comment by chuck11001** [comment]
@ashrafteleb I am running Microsoft Windows [Version 10.0.19041.329] and was using draw.io desktop app version 12.9.3

**Comment by mjs2020** [comment]
Actually there is an option to disable autosave in the right sidebar (the header will then show "Last saved X minutes ago"). This is good enough for me.

**Comment by ashrafteleb** [comment]
@chuck11001 @mjs2020 We have started using a separate thread for saving + async calls to filesystem (from v13.2.2), which was supposed to offload the ui thread.

Unfortunately, I couldn't reproduce and did that improvement based on guessing. If possible, can you share any file that causes this issue to you?

**Comment by chuck11001** [comment]
@ashrafteleb sorry I cannot due to work restrictions. It was a diagram with 10+ layers, 120+ shapes, 300+ links between the shapes, 100+ of the shapes were custom based on .svg import from Adobe Illustrator.

**Comment by mjs2020** [comment]
@ashrafteleb work file for me as well but I can remove some data and share privately with you to reproduce.

**Comment by ashrafteleb** [comment]
@mjs2020 Yes please, you can send to this email: mohamedin@draw.io
Thanks

**Comment by mjs2020** [comment]
I've installed v13.3.5 and no longer have had the issue so far. Thanks @ashrafteleb for looking into this.

**Comment by spigelli** [comment]
I was referring to the desktop app but have not experienced it lately. Will close for now.

**Comment by incognitojam** [comment]
I am experiencing this same issue using both the web version or desktop app. I chose to save my diagram to my device (e.g. `~/diagram.drawio`) and any time I make a change, the application freezes while it is (I assume) writing the file to disk. If I disable autosave the issue goes away.

I'm using Google Chrome 108.0.5359.124 on Ubuntu 20.04.
