### ISSUE TITLE
Migrate localStorage content from draw.io to diagrams.net

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#811]
Copy everything from draw.io domain in localStorage and indexdb (probably using hidden iFrame) to indexdb on diagrams.net one time and mark somewhere that’s happened so it’s not done again

**Comment by infinite-monkeys** [comment]
In the meantime, is there a manual process that can do this?

**Comment by ashrafteleb** [comment]
Done, will be available in the next release
