### ISSUE TITLE
Wrong copy/paste behavior using command/ctrl-v

### ISSUE THREAD

**Issue by ffbenedetti** [jgraph/drawio#813]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Different results using a combination of menu Edit->copy and Edit->paste vs Edit->copy and command-v

**To Reproduce**

draw a circle shape 
double click to edit shape text 
enter "demo1"
click outside the shape to exit from shape edit and deselect the shape

draw a circle shape 
double click to edit shape text 
enter "demo2"
click outside the shape to exit from shape edit and deselect the shape

select the shape "demo1"
click command-c

select the shape "demo2"
select menu Edit->Copy

select menu Edit->Paste
a new shape "demo2", correct

click command-v
a new shape "demo1" is created! wrong

**Expected behavior**
The last Edit->Paste and command-v must have the same effect of creating new shape "demo2"

**Screenshots**
N/A

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]
12.8.5

**Desktop (please complete the following information):**
 - OS: OSX Mojave
 - Browser Chrome and stand-alone App
 - Version 80.0.3987.132

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by ffbenedetti** [comment]
I have debugged a bit and it looks like the issue is in:
https://github.com/jgraph/drawio/blob/master/src/main/webapp/js/diagramly/EditorUi.js#L10176

invoked clicking command-v that is not invoking 
```
mxClipboard.paste(graph);
```
like it is doing:
https://github.com/jgraph/drawio/blob/master/src/main/webapp/js/mxgraph/Actions.js#L94

**Comment by DaPa** [comment]
This issue still exists in 12.9.13
