### ISSUE TITLE
Children are 0 width after collapsing and expanding nested pools

### ISSUE THREAD

**Issue by M-R-Epstein** [jgraph/drawio#814]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Collapsing and expanding nested pools causes their contents to temporarily lose their width. 

**To Reproduce**
1. Create a new diagram
2. Add a 'Horizontal Pool 1'
3. Add another 'Horizontal Pool 1' as a child of the first pool
4. Add a 'Textbox' as a child of the second pool
5. Collapse the second pool
6. Expand the second pool

**Expected behavior**
The children of the second pool should return to their pre-collapse width instead of remaining 0 width.

**Screenshots**
![image](https://user-images.githubusercontent.com/36113847/76904842-20dd6a80-6877-11ea-8584-3b4c5a0000c6.png)
![image](https://user-images.githubusercontent.com/36113847/76904906-3eaacf80-6877-11ea-976e-959a489dfcfe.png)

**draw.io version:**
 - draw.io version: 12.8.6

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
If you try to resize one of the 0-width elements after doing this it will snap back to its original size.

**Comment by mararad** [comment]
Tested in diagrams.net 13.10.2 in Chrome Incognito Version 87.0.4280.66 (Official Build) (64-bit) 
Not able to reproduce.
All is working well at my place.
