### ISSUE TITLE
Certificate

### ISSUE THREAD

**Issue by baldur1989** [jgraph/drawio#817]
Hello how do I do that if I have my own certificate and want to use it?

If I want to do it via a reverse proxy I have the problem that draw.io means that java is not activated.
And no Letsencrypt is not an option.

Thank you for help.

**Comment by davidjgraph** [comment]
How is this draw.io specific? This sounds like a generic IT question, maybe SuperUser?

**Comment by baldur1989** [comment]
No was a specific question about the container and not a general one.

In my case the key was not imported correctly. For which they also need once.
1) edit composer FIle
in the docker-composer.yml 
volumes:
- ./keystore/.keystore:/usr/local/tomcat/.keystore

docker cp drawio_drawio_1:/usr/local/tomcat/.keystore /your-path-from-composefile/keystore/.keystore

docker-compose down
docker-compose up -d

2) Create keystore
openssl pkcs12 -export -in mydomain.crt -inkey mydomain.key -out mydomain-store.p12 -name "mydomain-store

keytool -importkeystore -destkeystore /your-path-from-composefile/keystore/.keystore -deststorepass V3ry1nS3cur3P4ssw0rd -srckeystore mydomain-store.p12 -srcstoretype PKCS12 -srcstorepass mypass -alias mydomain-store

3) Restart again
docker-compose down
docker-compose up -d

Thank you and solved
