### ISSUE TITLE
Impossible to load a shared diagram saved in Onedrive 

### ISSUE THREAD

**Issue by cougil** [jgraph/drawio#818]
### Preflight Checklist
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Once a person already shared a diagram with another person using OneDrive, it is impossible to open it.

**To Reproduce**

1. When you receive the invite with the permission to access to the document, if you click on that link you will be able to download the file in Onedrive, instead of going to Draw.io and see the content, 

or

1. (once you have received the invitation to access the diagram) - Go to draw.io
2. File > Import from OneDrive >
3. It will be impossible to find the diagram, it won't appear within your files, neither you won't see the "shared" place there

**Expected behavior**
Either once you receive the notification email, the user should be able to see the diagram directly (visiting draw.io)

or

You should be able to see the elements that are shared with you, so you can select that diagram and opened it in draw.io

**Screenshots**
This is what appears when you are in OneDrive where you can see what people shared with you: 
![image](https://user-images.githubusercontent.com/2370634/77191566-6d28e480-6adb-11ea-87f6-0b88b49d3ff2.png)

Here you can see what the user can select when importing from OneDrive. There is no option for click in my "Shared" area and see what others have been shared with the user:
![image](https://user-images.githubusercontent.com/2370634/77191889-f2ac9480-6adb-11ea-984c-033901ec407a.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]
12.8.8

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by ashrafteleb** [comment]
Unfortunately, the OneDrive Picker API doesn't allow that (https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online#customize-capabilities)

**Comment by cougil** [comment]
So then, how a shared diagram in Draw.io works? It is possible to share one with another person or not?

**Comment by ashrafteleb** [comment]
I can only suggest some workaround like copying the file to another folder, use Sharepoint sites, or synchronize OneDrive to a folder and use our desktop application to edit the file.

You can also follow this issue https://github.com/OneDrive/onedrive-api-docs/issues/1180

**Comment by cougil** [comment]
Thx @ashrafteleb 
I don't know exactly how the OneDrive works. So, if the user copies the shared file into his/her owned folder, what will happen if the owner of the user updated the content of the diagram? It will be updated?
Best,

**Comment by ashrafteleb** [comment]
I've found a better workaround.

1. Let the owner of the file open it in draw.io (or app.diagrams.net) [File > Open from and Import from > OneDrive]
2. Copy the URL of diagrams.net editor and share that URL with another person (don't open it in OneDrive).  For example, https://app.diagrams.net/#Wcc42b5d927b7fbe1%2FCC42B5D927B7FBE1!134

**Comment by cougil** [comment]
I don't know if I'm wrong, but, with this approach, the file will be able to open it in WRITE mode ?

**Comment by ashrafteleb** [comment]
No, it depends on the permission given when the file is shared via OneDrive. So, make sure to share the file read-only within OneDrive. We cannot override those permissions.

**Comment by cougil** [comment]
So then I think this will work. Thanks a lot!
