### ISSUE TITLE
Can't import a Gliffy file twice from my device

### ISSUE THREAD

**Issue by raskiman** [jgraph/drawio#821]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

I'm trying to import a Gliffy diagram from my Device into an empty draw.io drawing.
This only works once. When I try to do this a second time, it doesn't work anymore. Nothing happens. No errors on the console either.
Or in the same diagram, or in a new/other diagram in the same Chrome browser. Same issue.
The only way I can make it work again is "Clear Site Data" using the Developer tools and reload the diagram again and do an "Authorize" again (the big blue button appears again).
Then I can import 1 diagram and we're back to square one.

**To Reproduce**
1. Go to 'Import in the menu', select 'Device..'
2. Select the gliffy file from your device
3. The file will import and a diagram is rendered and saved
4. Now do this again (in a new drawing, an existing one, ..)
5. When the file is selected from Device nothing happens anymore

**Expected behavior**
The file is each time uploaded and converted to a draw.io diagram

**draw.io version (In the Help->About menu of the draw.io editor):**

- I use draw.io using https://app.diagrams.net (so not in Confluence)

**Desktop**
 - Chrome Version 80.0.3987.149 (Official Build) (64-bit)
 - Firefox 72.0.2 (64-bits) (same issue)
 - Mac OS Catalina, 10.15.3

**Comment by ashrafteleb** [comment]
Can you try again. Is should be fixed

**Comment by raskiman** [comment]
It works now, but I had to perform a "Clear Site Data" once more (probably to reload the fixes?)

**Comment by raskiman** [comment]
Thx for the quick help!!
