### ISSUE TITLE
Math settings \hat{} is shifted when exporting any format

### ISSUE THREAD

**Issue by iteal** [jgraph/drawio#826]
* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

The \hat is not in the correct position when exporting.

1. Make a new diagram on draw.io online version using Google Chrome 
2. Enable Mathematical typesetting
3. Create a new text box, with value $$\hat{A}$$ See that the hat is above the A
4. Export to PDF for example, the hat is not in the same position (shifted left)

I tried "Keeping text boxes away from page borders and/or using textOverflow=fill/width for math elements (as shown in the image) might help." This doesn't change/

The preview and the export should be the same, the hat should not change position.

- draw.io version [e.g. 12.9.4]

**Comment by llvs** [comment]
As a workaround you may try to manually shift in math code using `$$\hat{\mkern-3mu A}$$` (-3mu is only a suggestion).
