### ISSUE TITLE
[Feature request] Allow user to preview templates before using it

### ISSUE THREAD

**Issue by Huy-Ngo** [jgraph/drawio#829]
* [ ✔ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ✔ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Before creating a new diagram, I would like to know how the template look like, so I can choose the right template. It's not always the problem, but sometimes I find many diagrams are similar, and I have to try each to know which one I need.

**Describe the solution you'd like**
I think a box on the side of the creating-from-template prompt would be nice. The diagram doesn't need to be real-size, but it should be large enough to be able to read the text on it.

![image](https://user-images.githubusercontent.com/19296926/77919760-ca851880-72c7-11ea-9ff0-afd5dc27d02f.png)

In addition, it'd be also nice to have some short description of each diagram.

**Describe alternatives you've considered**
Instead of creating it in a box, I think it's also okay to have a separate preview view, but I think it would take more time for user to check between templates.

**Comment by dainsmail** [comment]
Agreed, I am attempting to use Draw.io in a new position which involves AWS diagrams. In the online version, I can see that you have several AWS diagrams because of the tooltip with the filename, but I can't tell anything else about them. They look well done, but how would I know which one is best to start with for my diagram? Definitely need a preview.

**Comment by alderg** [comment]
Preview will be added in the next release.
