### ISSUE TITLE
Export drawio file to PNG on a server (without X11)

### ISSUE THREAD

**Issue by stderr-mila** [jgraph/drawio#830]
Hello,

First of, thank you for draw.io!

Is it possible to export a ".drawio" file to a "png" on a server (rather than on desktop) OS?
I am able to do the export from the CLI using `drawio-desktop` on a Ubuntu desktop but not on an Ubuntu server.
Is there a tool or method to do so?

**Comment by davidjgraph** [comment]
The PDF and image generation for IE 11 we use with the online version uses chrome in headless. That said, check that we have it set in headless mode, since we run it on a Mac farm, which isn't headless.

**Comment by stderr-mila** [comment]
Thank you for your answer.

I am not sure to get your answer right. What stack do you use to convert a ".drawio" file into ".png"?

Would you have any pointer with regards to files or bits of codes that I could look into in order to try an reproduce the feature? (the idea is to get the conversion done by Jenkins on, as said previously, a server without X11)

**Comment by Modelmat** [comment]
You can use `xvfb-run`.
https://github.com/jgraph/drawio-desktop/issues/146

**Comment by davidjgraph** [comment]
Sorry, forgot to link the project... https://github.com/jgraph/draw-image-export2
