### ISSUE TITLE
GitHub is hardcoded to diagrams.net client ID - how to configure?

### ISSUE THREAD

**Issue by ltning** [jgraph/drawio#835]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
There is no documented(?) way to override the GitHub client ID, and the ID seems to be hardcoded despite the developer guidelines being clear that this should never be included in a project.

**To Reproduce**
1. Install draw.war in a Tomcat installation
2. Attempt to open from GitHub
3. Ask to authorize
4. GitHub says it will redirect back to app.diagrams.net, not my site

**Expected behavior**
A documented way to change the (hardcoded) client IDs in the included .js files. Having manually modified them, this did not entirely work; redirecting back now works but I get authentication failed from drawio.

**Comment by ltning** [comment]
Any particular reason this is not considered worthy of attention?

**Comment by davidjgraph** [comment]
https://github.com/jgraph/drawio/wiki/Stale-bot-FAQ
