### ISSUE TITLE
Drawio desktop 12.9.3: cannot directly open existing .drawio file on hard drive

### ISSUE THREAD

**Issue by lwiart** [jgraph/drawio#840]
Hello,

Lately I updated my Draw.io desktop (Windows 10) to 12.9.3.
Since then, when I double click on a .drawio file, drawio will start up but won't open the file.
It will show the open existing diagram/create new diagram. I then have to click on "open existing", then pick the file I was trying to open previously.

It used to work with the previous Draw.io version.

Thanks for your help, and for the amazing Draw.io tool!!
Laurent

**Comment by davidjgraph** [comment]
If you update to 12.9.9 does it still happen?

**Comment by lwiart** [comment]
Hi David,
Thanks for your quick reply. You are right, with 12.9.9, it works!
Laurent
