### ISSUE TITLE
Add support for attachments from other services in Trello

### ISSUE THREAD

**Issue by ashrafteleb** [jgraph/drawio#844]
Currently, attachments from other services in Trello (e.g, Google Drive) appear in draw.io section but cannot be accessed.

**Comment by troywray** [comment]
When you click on the draw.io power up, you only get the chance to create a new drawio drawing. Couldn't you simply add the ability to specify the file here and then pass that to drawio so that it loads that file and from then on, it's the same workflow. Seems simple from outside anyway :)

**Comment by davidjgraph** [comment]
I'm in favour of switching to embedding as the only workflow. Direct editing via delete and create attachment is a hack and annoys more than it helps a lot of the time.

We'd have to allow existing diagrams to be edited somehow and need to think about how to treat uploading of files. Maybe open diagrams.net in a new tab in embed mode and let the user dictate the save point.
