### ISSUE TITLE
White text background missing on lines

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#845]
It used to be that when I double-clicked on a connecting line between two boxes, the text would have a white background and appear on top. Now it doesn't and it's really obnoxious. I noticed the 'background' is now off by default, it used to be on by default.

Attached is an example - on the left is what it used to look like when I double-clicked on a line, to the right is what it looks like now.

https://groups.google.com/forum/#!topic/drawio/n6WGiMkukdI

![Screenshot_1](https://user-images.githubusercontent.com/44292306/78880676-094c6880-7a56-11ea-8166-0e113796c9cf.png)

**Comment by alderg** [comment]
Fixed in next release.
