### ISSUE TITLE
Duplication of functions between editor and editorUI

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#846]
In branch remove_fn_dupl

These changes need to be applied once merged:

mxEditor: 690
 //This function is moved to Editor. Both are kept just in case
 Editor.prototype.createImageUrlConverter = EditorUi.prototype.createImageUrlConverter; 
 

mxImageExporter: 323

-  editorUi.exportToCanvas(mxUtils.bind(this, function(canvas)
+  editorUi.editor.exportToCanvas(mxUtils.bind(this, function(canvas)

**Comment by ashrafteleb** [comment]
Merged
