### ISSUE TITLE
Whether to consider supporting style customization

### ISSUE THREAD

**Issue by MrGaoGang** [jgraph/drawio#849]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

I often use draw.io to draw a flow chart, and the color configuration of the right style part is not suitable for me; so I need to manually modify the node color every time I draw the flow chart; so I think whether the right style part can support Collect and display commonly used colors, or change the color on the right side to your favorite color configuration。

**Comment by RobertZenz** [comment]
That's possible [as part of the server-side configuration (PreConfig.js)](https://desk.draw.io/support/solutions/articles/16000058316-how-to-configure-draw-io-).

**Comment by alderg** [comment]
You can change the configuration via Extras, Configuration. Here is a third-party app to create color schemes: https://drawio-config.herokuapp.com/ (via https://github.com/leifmarcus/drawio-config)

**Comment by MrGaoGang** [comment]
OK thanks @RobertZenz  and @alderg

**Comment by ga5tan** [comment]
@alderg sorry for kicking a dead issue, but how can I load configuration via JS ?
 I tried it like this:
`window.DRAWIO_CONFIG = JSON.parse(`{
  "customPresetColors": [
    "B5739D",
    "7EA6E0",
    "67AB9F",
    "FFD966",
    "EA6B66"
  ],
.
.
.`
in Preconfig.js, but no joy.
all I was able is to do was load custom styles like this:

`var node = mxUtils.load('styles.xml').getDocumentElement();

    if (node != null) {
        var dec = new mxCodec(node.ownerDocument);
        dec.decode(node, this.editorUi.editor.graph.getStylesheet());
    } else console.debug('Node is null');`

but that for some reason wont work in Chrome, when new tab opens with loaded file :(

**Comment by alderg** [comment]
Why JSON.parse?
