### ISSUE TITLE
[Feature Request] DOT export

### ISSUE THREAD

**Issue by aforsythe** [jgraph/drawio#85]
It'd be really nice to have an export optios to DOT to support workflows requiring that format.

**Comment by davidjgraph** [comment]
Please add/vote at https://draw.uservoice.com/forums/266072-feature-requests/filters/top

**Comment by mhgharieb** [comment]
it will be very nice if there is an export option for TikZ

**Comment by davidjgraph** [comment]
Removing TikZ to have one request per issue, TikZ added as https://github.com/jgraph/drawio/issues/668

**Comment by Atcold** [comment]
Why has this issued been closed? I don't see any merged PR associated to it.

**Comment by rgg-james** [comment]
@davidjgraph could you advise on what the state of this is? I see some associated labels have been added recently.

Is it essentially a "probably not going to happen" situation?

**Comment by davidjgraph** [comment]
https://github.com/jgraph/drawio/wiki/Stale-bot-FAQ

**Comment by davidjgraph** [comment]
Core team declined means nobody on the core team wants to implement and be responsible for maintenance of the feature.

Personally, I don't see how it would ever be possible to implement this in a generic diagramming tool, but if someone wants to prove me wrong, please be my guest.

**Comment by rgg-james** [comment]
Thanks @davidjgraph. The easiest way to implement it, at least in the short term, could be save it as SVG - which is already supported - and then call `svg2tikz`. https://github.com/kjellmf/svg2tikz

**Comment by davidjgraph** [comment]
tikz is a different issue, https://github.com/jgraph/drawio/issues/875, we split them and kept dot format here.

**Comment by rgg-james** [comment]
My bad

**Comment by davidjgraph** [comment]
Outside scope of project.
