### ISSUE TITLE
draw.io plug-in for Google Sheets / Docs / Sliedes should support Google Advanced Protection

### ISSUE THREAD

**Issue by silentwater** [jgraph/drawio#850]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

When trying to install the Chrome Plugin for Google Sheets / Docs / Sliedes, I get the error message , that the App does not support Googles Advanced Protection and therefore can't be installed.

**Describe the solution you'd like**

As a User I want that the plugins support Googles Advanced Protection for Google Accounts.

**Describe alternatives you've considered**

Turning off Googles Advanced Protection is not a viable option.

**Additional context**

See error message on attached screenshot.

<img width="495" alt="Capture" src="https://user-images.githubusercontent.com/6047599/79115922-70845880-7d87-11ea-9fb5-143e3937613c.PNG">

**Comment by davidjgraph** [comment]
Those addons need to be granted access to your Google Drive. That's not permitted for third-party apps when advanced protection is switced on. You need to export an image of the diagram and embed that into the Doc.
