### ISSUE TITLE
Question : How to disable / deactivate any of the online storage options

### ISSUE THREAD

**Issue by tasos-lgs** [jgraph/drawio#852]
I'm trying to deploy a local instance of draw.io. The objective currently is to disable the unneeded online storage options. Using the options described here , I added :

urlParams['db'] = '0'; //dropbox
urlParams['gh'] = '0'; //github
urlParams['gl'] = '0'; //gitlab
urlParams['tr'] = '0'; //trello
in the file PreConfig.js. That made however no difference to the options shown at the first time the site is visited. (Every storage option is still available to the user)

Are these config options enough / correct ?

Thanks in advance

**Comment by tobyqin** [comment]
try:
```
urlParams['local']='1'
```
Here is a local-feature-only of draw io built by me.
- <https://github.com/tobyqin/drawio-local>

**Comment by davidjgraph** [comment]
stealth=1 should do it.
