### ISSUE TITLE
Extra blank page in the end when export as pdf

### ISSUE THREAD

**Issue by IvanPletinskiy** [jgraph/drawio#854]
**Describe the bug**
Hi. I've exported my flowchart as pdf and got an extra black page in the end.

**To Reproduce**
1. Open my flowchart from google drive
https://drive.google.com/open?id=161UbwcnUC9wR5HLqdXtx3m_YW3HUPP6n
2. File -> Export As -> pdf
3. Choose all pages and uncheck include a copy of my diagramm
4. Save pdf to pc.
5. Open downloaded pdf.
Expected:
My flowchart in pdf.
Actual:
My flowchart + black page in the end.

**Expected behavior**
No ideas. Mb incorrect check of flowchart pages count.

 draw.io version [12.9.12]

**Comment by Ivanhanden** [comment]
Browser google chrome

**Comment by ashrafteleb** [comment]
The file includes two pages (second page is blank). So, the resulting pdf is correct since you selected "All pages"
