### ISSUE TITLE
[Request] Support for Feynman diagrams

### ISSUE THREAD

**Issue by jkellers** [jgraph/drawio#857]
Hello,

at first i want to say i really like draw.io and thanks for the creation of such a nice tool.
As a physicists i am always searching for a good and easy to use tool to create feynman diagrams, but so far i have found no solution that satisfies me.

So my request is to add support for the creation of feynman diagrams.
Examples of feynman diagrams can be found here [https://en.wikipedia.org/wiki/List_of_Feynman_diagrams](https://en.wikipedia.org/wiki/List_of_Feynman_diagrams)
So basicly what you need for feynman diagrams are line connections (that are already availabe) and wiggly and loop lines, that are missing. 
I already searched for these lines and i found in the Proc. Eng. / Fittings section the hose, that is almost perfect for the wiggly line, only the connection between the turns needs to be a little steeper. For the loop line i found in the Electrical / Inductors section the Inductor (Air Core), where just the straight ends needs to be removed and the loops must be wider. 

I hope i have described my problem and my solution clearly.

If would be really happy, if you implement feynman diagrams.

Have a good day!

**Comment by jerzydziewierz** [comment]
fixed link here [Wiki: List of Feynmann diagrams](https://en.wikipedia.org/wiki/List_of_Feynman_diagrams)

**Comment by kimbostroem** [comment]
I would appreciate such feature, too!!

**Comment by ritobt** [comment]
This would be enormously helpful. In Quantum computing theory we also use Feynman diagrams a lot!
