### ISSUE TITLE
Multi-page export to PDF does not resize larger diagrams to fit one page

### ISSUE THREAD

**Issue by jaylapras** [jgraph/drawio#858]
Single page export (using crop) works. 

By default, if technically possible, please make the multi-page export save each diagram page as a 'cropped' diagram to resize them to fit on their PDF page.

[business-plan-Business Model Canvas.pdf](https://github.com/jgraph/drawio/files/4494504/business-plan-Business.Model.Canvas.pdf)
[business-plan.pdf](https://github.com/jgraph/drawio/files/4494505/business-plan.pdf)

[Diagram link](https://app.diagrams.net?title=business-plan.drawio#R%3Cmxfile%3E%3Cdiagram%20id%3D%22Ut2qBbNyfKLfaLGg0lia%22%20name%3D%22Business%20Model%20Canvas%22%3E7R1bc9q4%2Btcw0%2FMAg80l4TGB0O7ZTdsJ3XbOU0fYAnRiW15JhtBfv58uNr5BuDnEaTLTArIt6dN3v0hudIb%2B00eGwsU9dbHXsNvuU6Mzati21R7Y8CFb1rrlutvXDXNGXHPTpmFCfuH4SdMaERfzzI2CUk%2BQMNvo0CDAjsi0IcboKnvbjHrZUUM0x4WGiYO8YusP4oqFgcK%2B2rR%2FwmS%2BiEe2%2BgN9xUfxzQYSvkAuXaWaOneNzpBRKvQ3%2F2mIPbl48bro58ZbriYTYzgQ%2Bzzwy3Yef36JrP9%2F%2Bfyn1xs%2FfBmMZ03TyxJ5kQHYTFas4xVgNApcLDtpNzq3qwUReBIiR15dAc6hbSF8D35Z8DUBUt7roSn2bpHzOFd9DKlHGVwKaIDlrYLRR1zaGK90B1pmxPPimxp2B19jdyY7n9FAGHLpx79T99nj3u3VENqRR%2BYBtHl4Bst0a%2BDFTOCnrQtpJegBusbUx4Kt4RbzQIzQdfbnakMett0zjYs0bfQG14YwDVHOk743eIMvBnUHoNEuQWPfk%2FC6ZJlBZ%2F%2BfSBKcWq4mV%2Bt3AzfY%2FfBpcxG%2Bzc2nF998fC%2FDiAuAk8END9hDgtCALyT%2Fmt4BYj1AdlBoVpPPtpY0TdnBj%2F5YIAmQWIcYPugM%2FmOpqUl5RUHq2G2MnEV8B40kCBto9hxrguc%2BUJbq7SmUMspuR1zJMdnEBZp6hMtRUOAqwUECAf8USQnZLhbYb3TGB0BH9KwDBcMCLSWUK5weTjL0%2Fj1%2BAp6W8hTr2UhmgEniOUMCu5mJqpXkIrtm04gTmIucjK80xMFDO5QLb52dwwGdHEUqz9O71T4H1%2BzuZRo33D0hP%2FRwmm2mJdAcyEqXBfIrZpwGyFMykRMgzgAUS02BGWGXOIYhUoDd1B6wCfZmzQlmS1JfGG4ikNoGOQaUExTQZWEZUt%2BPAiJInUFoOgwrhXsgCBexTtOGZ9ZE7TUKJupM%2FTUyJqplN%2FY2UaVxCoLEuzHNgkowOEBFgrm0itvJQpxkx1qdft6SvS6Ysl27xJLtxubt2Q3ZzlZDtow2TrNL%2F1R2zFfERADS%2BhkyLLUcTpmTZe%2FU%2Buz0Pk6byY8FTcwtbcXl1mtjfp0y2eIwj2oYHoWhR845jraJNRAPmMNgSgWYsZV1jJwIMcIkm9ntGaO%2B5qdzwrsHmVXU9SuQ%2BgmUccM9FWSp3S654pSlFjznItbe1v0SCuKTX0bnGWcPOzSg%2FrquMD1gN3IMQNqLJvwxAS4Cm5dJV1bUFsAb55%2BIcJIGUdIncSIPMe3rbgSJAhrBeiyrt80q1x7vdldldlf7SLNr0K7K7Oq%2BuNl1sy%2BbVKgRqxquGGgswtx2aWLxfFfLDqYVoyHVwoYr2QKyB4yTA%2BJcX1R%2FIwK8QqaRkVrDBQoC7PFDOtoasz2gjwe8xIECDKaDkX%2FQw2l87CM3qzR6yqaVLBQSeE4ZeTYutxtcQH2iSfd%2FZOphaaJOqLdUNuu%2BTwJCwdaCR8efsVhR9vjs2p4LWe9a5FxapFdIQ13cee%2FtzkKdX4mk3LhLp5KKfuWFBHz7vKJ7Ur3ofgVmfkGsf1uHCokmNVgks9q7o18Xay7lVF3n%2F0cgQCRhR0Qqy%2FJhyrT%2FFYJCVtlWkGFth4ZrJkWf%2Be0igf5TV4g%2FRT46NFr%2BaiY%2FJgEKHHIwvb0bDFUZDP3exQ2G%2FmsuWylX2pe2M5ZmVsq6UEFrF3tkqdS9KijRNRhObAQcVzbSyJRvJJ3d2Y3rdmMwkJox1O5HLoK%2BwF6ow%2BdqMhw8k4PsGwPlFDjU2yjgUHtHmyAbTzK46cHpbIZZanRTvJMyiEwtzjGr4mx6CTB2c0NzsLP4bK049veylMD4ZMgRsPAcxNibMpE%2B45WuWqrn9L9iJr38OleeaNZNkib1BCIWm8OPWAgjnpSQ%2Fi%2BdSmdOyltzy6iuMI4wl9ZLTWd%2Fq32H8UQgEdWX31mN67OGVBWNphKK9YTjQSdAaw%2FHjQPmFSdT4pH6Zm%2BHNFjigGClAcd%2Fc3RpcN4D5C%2Fn7w66ry7NevVyAfKi03NJ53WsKntWC1VRlXKbdA2oMonMohzimOUrx3ytQ4gfUiaQWr3Ya3vrAex7pHZX3CP2iEVdxfVn8LRx7aEw7CYrzesJwEiGkziZkfqCcB95gsBdrt6MkeS730PPl6l4urp%2Bdbr4%2BgV1cZyfvZwC%2FrYA0psvlBLW8czNpNKZ6t1mw%2B4xVlrlqtDrVG8ERM4JGw1XSR9J0ESaD4Hkq%2BN6NDBuIE9tYjx%2Bf6UuoAGQwfo4vhc9Q2PCyO2OTTybEYccGK4uLGAMYmYNzX7NVEwbyEPIPZpv3E5KppzjTSnOFoi%2FrRS%2F1YJLNysppmscxoZP5Eu9FEx5qH63S5o03W%2ByYgwRrrZ0bMBvoykQeSIGHOqHKFjnk1pbEk0ZtqjV%2BtmSCu6knqt3FP0oMpD5yIwbaLexXoqNPqBsjoI4x5CmhpIMcI3poCPp4GvEHCnn6grEcVSAPE%2BfIpAiA2WmhMlytHmIHfB5nDcqBboS%2ByNdKlDbeO5x2N8USKAtTG2oYUuwqFZL1FM6fyYUvBx59d0ifhyygXeX4PbLb9KGTjF4ytiVm0spExdF83sq4II73V9B7dvgNde%2BmWzsRDDQgxE7wVw4OXJhKsKSc38a5XF%2BaNIO%2FQIrqpBfG%2Bc4f%2Bi5jeNmMvJop4CTQ6vd0n1ntoed3vlRa35xkZ%2F1zv%2BQS7EuQWKGJGvvqBt2GzFAsaTaDx5GAU4iQarjhBNlHbs2Z0Nd8JHUhIZpk0be5qMn4kcq56aPv0mu4CdhKEryiFBEDTK3trXxsVW3WcKGPE8AdL7KACgbL16mzcEzQ7Vo2CdqjUqWsbbrsZP56wlJ3DBRx6BJPL7dytMxeVJ0OzRq7QNY8khvMpU0yzY7XCIhS1rgSm1J9TsAhqYaoxrcesJxp47yIJuqda5OkX070NDwUGjePZiqzoywrJIMqtUuO3a206nKhYnPaH6dPkxxD%2BvlnJi4%2FimzhSedk0xHJmGynjrrdAW0mtrOEqKDzjzNjOmarUFrNRaTZKeGOLDPknNgc70duANGd7iikeduugSTbLbZ0HTUFP1IOVbZU3zzFKE0TqB3UuN4OAp8ihTtM337rpTou4A7m4Czeq9RwhXPR%2F%2BmQhC3G2c0PvN%2BiIIl4mVCIkclsEgiSwoMgzBTNpCmhpASaeDB3b3bRm8ksQL%2BGzfYOxBJ3%2BSPUbObpYGdZ6ZXoLAGRWQmRUFpXF5Vhkq7RFnlMJNCSbykf0nG%2FJpk%2F0ZTKkBQb%2BfYNMttQUua712kj%2BIeFZm5q%2B8N5dz8p7l8vUKLUH7V8gl3Ws4CO49loiFB4jZBAD25sqokJ2OOlA%2FnKNTOn4cVF26nT9QvO0%2B%2FXxWplJ1CmiOVPGbk9ifeEgwtsdcCBcYV8Gkmz%2BEjWdDS9yA8S37ltBUjx5EFqOwwJbMvAZwlHm%2FlUG53CijvWCXh%2BMqkQ9kJaBeRDoUXYJTSx1Zi2i5cykQJAfuHtxYYMXFREWBdWb1WO%2FXXy5JHpygRuiXk0alMIjxztNHZglujdYB8U4RAnOyhXmVRrXMHDz7jORVEhUdlBHWK2ByRIBcZPveg%2FyNYmf%2F3KEBzrDboVzfYA3hXTUF83CxsM9hl2r8Ko82q2mjrtbutLOtZ9lW3aIaXqePKMqWxnq%2Bc%2BeKo62VY7y%2BiMj35XbznHsacNAjXZxjpjFLbxSEGx7VSvktVlnNzCsfLDPydepG%2FF5S%2FJct37N5eLF%2FmePcrY%2Flndkqe%2B5y3F2X0G86ximtm0wPnHuZvLl9tJ9m8ylEm0ZQ7jISmjm6MM8t5dhkJDKwk8%2FgB6Ft%2F%2Bwsjvt%2Fpp8dLZkcmyysd41Ya%2BSzBWJWLeOMqObQLoN9SElq5TWrlcrBTFomobJeaVbZNrRiK2OLzpaPNZV6kl3Nfk7DBkeGHvI%2FpcwfhluPRyG3Joxd%2FzpAjKCzLdgd2%2FxjFy7708foqV0F4VQxolqnI6qzisgLCfYNUAVelcxKrLVlZ9Piz36htsGonIfBQvxV2pmz7MwUr8icpltBC9yVpwS5LxG6hBeKrN97elkSzsug5R4xLDXYT46BdhhAzn9FCCHlG8Y1cCXvsuEFXRadmBEx21nLkyRFjKUPgQ0Wt4BMviddUP5oRx6wptzqyGVKHvfRBdI9VgVzTsq9boUxWZQls36RayUtoE%2FLaI5b%2BsmLKal93s0oMoC8KqusS4ryuijj3eMfwVq2VE2BoxTs69eGBt%2FxTFUcejJ0K3lF8MXwDwvt5982yBnFTCuf9q7gxk27rVYX1PdJtxxsuO62HMxo0NBIeCWD0%2BOXiZZF0Kvdpg5lDAweHgrfgicdTFZiOgldCMt3OIEMvtj0oEktJcD15q%2FrZSWWPdJtcw3Ar8Obl78YfaSTZwpP4yO4Uc1Lxy91fRqvvkZM6goWAusbq78L8IlU2V%2F9X5Q5sY6KsALf3ZasdxLuVruIkpqGpZlEud%2FsvSVJleax3kqoHSZ2faOAnozI2lFz7KJdTVzR17v4F%3C%2Fdiagram%3E%3Cdiagram%20id%3D%225AAhcrilLe33DnYhDtoa%22%20name%3D%22Customer%20Segments%22%3E5ZpfU%2BM2EMA%2FDY9oVtqVtHpMAhwzHXqdpnPtqy8xSeZCTI25QD9918QmMfJwF0hI6hpmEq8kO96f9p%2FkExzcPHzKk9vpVTZO5ycGxg8neHZijIZg5KOUPK4kTG4lmOSzcdVpLRjO%2FknrkZX0fjZO7xodiyybF7PbpnCULRbpqGjIkjzPls1u19m8edfbZJJGguEomcfSP2fjYlo9hfFr%2BWU6m0zrO2sXVi03Sd25epK7aTLOlhsiPD%2FBQZ5lxerbzcMgnZfKq%2FUy%2FXL2%2Beoz%2Fna1%2FLL4e%2FGLHV64x9PVxS62GfL8CHm6KN586d%2F%2FOv01fO%2Fd6bPL5NO3xf3w6tJXQ%2BB7Mr%2Bv9FU9a%2FFYK1CuIqzkpL%2Bczop0eJuMypalTBeR5VmRFLNsIZJTBBFcz%2BbzQTbP8qfReAHswYo8k3GzopxErux2V%2BTZt7TuuMgW5Q2mxc1czrR8rX5XmhfpwwuQP9CCfkYjczrNbtIif5Rx9VV0UExao2HnkLmaBo%2F1pHXKEgUqm3XwzKvm5XrmyBgFDJaN094yhsocppuTyDqF3gYKjOANcdUnqeby5PlnrXnJlwrZFvj0DvFptDG%2Bc7aOzPHgE3IqOOPk3zp0GOMjRseODZqgvYnw6WAVg6GSH8tJiOkZIGV8CB5ltnhBrfdEz7yX3gtY5sL2%2FeB4YCGAYlGkdmjRO0Bq0GKrNIoVGrAYdG2Jm6bmocW2CPaEA3eMQ5ter%2F%2Bzrm%2FTEO3H4BFXppxl7Zy1BsA4bOCR2yjnCdmQ4IOgMQIkJqYMAREE8aVI3rfwMvviRbuMXdQSuzy6QY%2BPx56MhB4kQs9BYpPh0OSlUSGQAa2FrISgFlxWEWiyMhQs%2BUAtuMAryfG0d0hBqNfp387p2YheL8In%2BitKfZfqX0z%2ByG5LUk9RKlsUw6of1Oer1FNTE0bZtJmPPB37hFQHnTomOYEmmgeUfMH54Gzs51rc3N6sxkV673dC79ZC0xysllxAwoU0iH%2FScGC9%2B0jvg07o3YnD8M6Kmw%2BSVdk6Ha5nP7qjmv0cUTjrBAXy%2BFqqhQaUZUbvpaMWWzkwhhBhOO8EBqSmE0Jq5lBxCvWhatdxud%2FrhhdCW9ZsjOwBpZgIzdRIIyky2gdvERkchANziOv2fjc42NrBP2c%2Fx%2BX%2FdVxz9zqiejL%2BtRCg6chIxOV2f9CNKEBsXyUhZZwz6DySFNAcr1F9LIe4jO7%2FLzAYPK4CQccVcb8jyWkwih1ykAgM5HQzRBgmKSDQOQC04EXrB%2BbQUiGfdcQiXtbIzqhggAOW214SvVvWYD9U9XGR3OuGCRiW%2Bow1GdLeaklBX9iAJKgsFTQGIkfEbftOHwqipU7uhgkgv1YolAvamzHhwBTiMjleI%2F3pJe6WBe7rN27OTvJkPEvX4Koem5jtIYwMFGwe9uXuICoSy5OOYmWaoMXIggqbR8sCuVT07FgyaE9yYB3Mdr85GNfq8ULte%2BCnb9zaPTzlJlX7Q6rUYrTICiTiicfVThvxufvCGJf6cbm53S7vtf3qR%2F95bgasKl%2BPIEQvbsjFSzKt2LwiCZae2aP81QnD7rHF6wRxIrLlbnCSfH2Drz02bNYqlDxGEhpJ3IUbHZe5xasKcd7yHq%2Fp0Y2SN%2BwJHx7jq7ERy3degMq1URf4OfBtFxqliwHthbAnLzlU2BqynK7fp3tq23grEc%2F%2FBQ%3D%3D%3C%2Fdiagram%3E%3Cdiagram%20id%3D%22oP0DXcLKlMJnkFUoio6r%22%20name%3D%22Revenue%20Streams%22%3E7Zvfk5o6FMf%2FGh%2B3QxLCj8dVt%2B10ptPt7N7exzu5kmKmaCxmV%2Bhf3yBBIbGCO2RltviihJCQ7%2BccOOeAEzRbZR9Ssll%2B5hFNJtCJsgmaTyAETgjlV9GSly2B65UNccoi1enY8MB%2B0epI1frEIrptdBScJ4Jtmo0Lvl7ThWi0kTTlu2a37zxpzrohMTUaHhYkMVv%2FZZFYqlVA%2F9j%2BkbJ4Wc0MvLDcsyJVZ7WS7ZJEfFdrQncTNEs5F%2BWvVTajSSFepUvyafkPRvlu%2Bm13z%2BnjF%2FZ1%2FfmmHOz9JYcclpDStXjx0P9P3SCc%2FXxGIPzybZP99%2BHjCqpDnGeSPCm91FpFXgm4WzJBHzZkUWzvpJFM0PQ7S5IZT3i674IAvL2dYtkepyRi8iSrfWu%2BprXmOUslYsbXchclW7mW6Vak%2FAfV%2Bi%2FFKpFboJiJH0eTM0HkulguaKrOm6aCZhroFpXAAZ20ecpXVKS5PK4apaKtzN1Dzjun9lH67I6mdDhiWTcjpBqJMt%2F4MNMRkfyhKF1ADIzEmsSQRsyvrjxtjLBGFlkiBkdiTWJY9zGvIzHg2PIqNDJqMvI1Rjjsysi3xchtZ0Qjee9Xm60alm5%2F0L6KDpBBo963nLKYpxe162o65yw%2BpQkR7Lk56ymJ1Rz3nMnzOeD0tGukp0Ha8qd0QdVB9SDi%2FDgw0MYRJI2pMMbZ8z4s%2B%2BUmgHtx0%2FdO4Dtvw031cAU7AwtXvF6I3QXYc%2BGbJIb8JjEXXxuZPzrZ%2BQgTu%2BG7sPYJOhLD2mG2As5g9LkWgLBjMGPNx8LRx87nBNjpGm%2FqoUx%2FmXY%2FxZE35Ec6JNTVj4AeJ%2FYHqUM9ZMwKLGcFYdAykOW0AJgllnuSEjksTfdnqVuE9Iu9f0nHZev4kUu3nd9g0y5UORsE1bYaomC%2BKVazXx%2BeTvD8T%2B5qyxfDUNPcNcOQ4ITtQGueaNZQMtBdeZKwuLj0LaQokhqaFpKxBUlu1Y4Vi6JiFAPEGWZXZqTH%2Br7XMR%2BzVz02iyiZecH8qyAZ9ePrQzLLHBn6uyHpkccAIPVT2XhDJeNAiwLAibI%2Bwo1iB6iuR01kzRJW9ai2f4RjpUNH6DdLFLgJFGgFjHDgfMdCSIuLBr146KFP%2FwTNOsljvqGy5YLIsqa3eRer3%2BewzXBdu4EFuswGiFcN3qFZ61BCXxAdDlJoAAemtFmwUEpfEOINU2lPU%2FrKQp8vCuQvUvvSooAl6TXlIb621mbunw8t97eFImigaH9fDJ0AA2AzsvJthUTQzP%2FzoeX%2FrwPq1AOG66Ixs%2F58aFn%2F66BB%2FtDQnMr1vUQoxRqEvJ9PvNpxs91reVvc3J1Ntr8XV%2Fvlr7j4njMiE4iV7CKYkGOoceV5lkOXvazZQQkbOZpdgPNBhiU70N8uMs0gACfsoHplon%2FuY4Gg7bVAt%2FPLtrYYjUl%2BCyMXdWQEgDVIZh6fuQO7t71yRVunZLOiLTePf1MpH7oe%2F%2ByD7n4D%3C%2Fdiagram%3E%3C%2Fmxfile%3E)

**Comment by ashrafteleb** [comment]
As a work around, you can change the page size to fit all contents before exportinng

**Comment by wucop** [comment]
Notices this as well, but it's only happening on the desktop version. Exporting it via browser works fine.
