### ISSUE TITLE
Icon, Object, Template Support for Value Stream Mapping (VSM) Exercises

### ISSUE THREAD

**Issue by eeik** [jgraph/drawio#859]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Draw.io native diagram type / template support for the Value Stream Mapping symbols, objects, link types, and numerical capture of process time / lead time process metrics.

**Describe alternatives you've considered**
PowerPoint templates

**Additional context examples**
- [9 Essential Value Stream Mapping Templates to Immediately Discover Flows in Your Processes](https://creately.com/blog/examples/value-stream-mapping-templates/)
- [Value Stream Map Examples and Templates (Lucidchart)](https://www.lucidchart.com/pages/templates/value-stream-map)
- [Value Stream Map Templates for Word, PPT And PDF](https://www.edrawsoft.com/value-stream-map-templates.html)
- [Value Stream Map PowerPoint Diagram](https://slidemodel.com/templates/value-stream-map-powerpoint-diagram/)

**Comment by AlexandreBonneau** [comment]
Could this issue be re-opened?
