### ISSUE TITLE
Templates in offline mode

### ISSUE THREAD

**Issue by NoralK** [jgraph/drawio#860]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I have in the PreConfig.js file 
```
urlParams['offline'] = '1';
```
The only other parameter I have in the config file is for Dark Mode and the default items.

When I go to **Create New Diagram** either from the initial start or File:arrow_right:New the template selection is not shown.  Is this the intended behavior?  I would expect to see the template selection.

When I remove the urlParams for offline it prompts as expected.

I am using this parameter to stop the auto-update and the popup for downloading the desktop version.  In any case, if there is another way to accomplish this without the offline parameter, please do let me know.

- draw.io version 12.9.14
- draw.io desktop version 12.9.13

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise LTSC 1809 RTM in Hyper-V with IIS for web version
 - Browser IE 11 v11.316.17763.0
 - Browser Chrome v81.0.4044.92 64-bit

**Comment by davidjgraph** [comment]
I can't repeat this using desktop 12.9.13. Could you record of video of what you see please?

**Comment by NoralK** [comment]
I will as it is still happening as of 13.0.2

**Comment by davidjgraph** [comment]
It's correct behaviour not to work with offline=1. The issue is not seeing them in the desktop build.

**Comment by NoralK** [comment]
Okay - I had the same PreConfig.js in the desktop build and it was not showing.

Why does it not show the template in offline, they are local?

**Comment by davidjgraph** [comment]
They are dynamically loaded as required.
