### ISSUE TITLE
frequency freeze.

### ISSUE THREAD

**Issue by doyee** [jgraph/drawio#862]
hi Guys,
    I found frequency freeze on 12.9.13 desktop version of Mac.
 I can't provide the problem file of draw.io, it has sensitive information.

can you try to reproduce this issue by follow way:
1. create 4 or more tabs in one draw.io
2. draw some shapes in each tab
3. insert some PNG files to one tab
4. save.

5. reopen this file.
6. minimize  draw.io destktop to background 
7. restore to front.   now, may be freeze, you can't do anything.

thanks.

**Comment by Hzzone** [comment]
same problem on mac.

**Comment by ashrafteleb** [comment]
I cannot reproduce, can you post a video please?
