### ISSUE TITLE
Easy way to add connection points on shapes

### ISSUE THREAD

**Issue by DangusTaargus** [jgraph/drawio#864]
I've discovered a method of adding connection points on the sides of squares by entering the coordinates in the 'edit styles' field (points=[[x,y]];), but it would be great if there were a quick and simple way to do this that didn't involve slowly entering them in this way - I've wanted to make objects with as many as 15 connection points and it's a bit cumbersome as is to enter them one at a time. A pull down menu or something where you can specify how many points each side of the shape should have, and then it'll divide their spacing out evenly as it does for the default 3 plus corners that are there now.

Is this possible? Am I missing an obvious menu somewhere? Thought I'd ask. Great software otherwise!

**Comment by markusdd** [comment]
I strongly wish to second this request.
The current method does work but is extremely cumbersome.
I do a lot of digital HW design block diagrams and when you have bus bridges etc. with a certain number of slaves connecting them evenly is a big pain at the moment.

**Comment by markusdd** [comment]
Hi again, for anyone who needs a quick workaround for this, I created a python script (3.6 or newer required) which you can use:

```py
#!/usr/bin/env python3
import sys

def point_calc(num_per_side, prints):
    s = f"points=[[1,0.0],[0,1.0],[0.0,0],[1.0,1]"  # corners
    if num_per_side:  # avoid div by zero
        a = 1 / (num_per_side + 1)
        s += ","
    else:
        s += "];"
    for i in range(num_per_side):
        s += f"[1,{a*(i+1):.3f}],[0,{a*(i+1):.3f}],[{a*(i+1):.3f},0],[{a*(i+1):.3f},1]"
        if i == num_per_side-1:
            s += "];"
        else:
            s += ","

    if prints:
        print(s)
    else:
        return s


if __name__ == '__main__':
    point_calc(int(sys.argv[1]), True)
```

it will always give you corner points and as many per side between the corners:

```sh
>> point_calc.py 7
points=[[1,0.0],[0,1.0],[0.0,0],[1.0,1],[1,0.125],[0,0.125],[0.125,0],[0.125,1],[1,0.250],[0,0.250],[0.250,0],[0.250,1],[1,0.375],[0,0.375],[0.375,0],[0.375,1],[1,0.500],[0,0.500],[0.500,0],[0.500,1],[1,0.625],[0,0.625],[0.625,0],[0.625,1],[1,0.750],[0,0.750],[0.750,0],[0.750,1],[1,0.875],[0,0.875],[0.875,0],[0.875,1]];
```

**Comment by donnib** [comment]
I could not believe this was so complicated to do. I really like draw.io but adding connection points which is so important only by editing style instead of single click using a shortcut is pretty complicated.

**Comment by davidjgraph** [comment]
If you press and hold alt while dragging the connector you can connect to any position within a shape.

**Comment by Dazeilad** [comment]
> If you press and hold alt while dragging the connector you can connect to any position within a shape.

Is this described in the documentation ?

**Comment by markusdd** [comment]
It is somewhere, but it does not allow for precise spacing.

I think having a quick and easy GUI option to add connection points is definetly needed.

**Comment by davidjgraph** [comment]
This is in 16.4.7. Right-clicking a shape to edit connection points:

<img width="536" alt="Screenshot 2022-01-25 at 18 03 44" src="https://user-images.githubusercontent.com/1761087/151033782-d1dd0f4c-9c27-45da-be4c-a7d9ca480db5.png">

You can select and move connection point(s) directly. You can add points distributed along an edge by selecting nothing, pick the number of points and which edge you want them on, then add.

You can rubber band select edge. Delete via keyboard or icon.

<img width="436" alt="Screenshot 2022-01-25 at 18 04 34" src="https://user-images.githubusercontent.com/1761087/151034141-1de457c8-a98f-47e3-830d-7861fa693eb8.png">

I'll close this issue now. If there are issues with the dialog please open as new issue(s).

**Comment by Bastesque** [comment]
Hey folks. Just saw the new feature…very nice. I saw that it's also possible to set new connection points inside the shape. This is very interesting, as this was only possible with the Alt key in the past. A follow up question: Are there plans to see the shape text in the editor window, so I can set the connection correctly? Also (when I use this option), the connector that reaches inside the shapes doesn't overlay the shape (see screenshots).
![Screenshot 2022-01-26 at 06 54 41](https://user-images.githubusercontent.com/68647048/151111130-9a64265f-e00b-46b3-9bbd-63d7fbb39fdd.png)
![Screenshot 2022-01-26 at 06 47 41](https://user-images.githubusercontent.com/68647048/151111132-94cab2e1-2afc-4346-8351-02df00d6012d.png)
![Screenshot 2022-01-26 at 06 44 16](https://user-images.githubusercontent.com/68647048/151111137-c28111a2-a86a-4b95-a51a-af047bbbc058.png)
![Screenshot 2022-01-26 at 06 43 54](https://user-images.githubusercontent.com/68647048/151111139-dd2b3d02-992e-41da-8e1c-297173422988.png)
.

**Comment by markusdd** [comment]
I think you should make this a new issue, but it's a very good point!

**Comment by alderg** [comment]
We'll add the label in the next release.

**Comment by davidjgraph** [comment]
https://www.diagrams.net/blog/edit-connection-points
