### ISSUE TITLE
Math Processing Error

### ISSUE THREAD

**Issue by federicodisante** [jgraph/drawio#865]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The [Latex Math formula](https://desk.draw.io/support/solutions/articles/16000032875-how-to-use-mathematical-typesetting-) stopped to work.

**To Reproduce**
1. Go to a new draw.io file
2. Enable Mathematical Typesetting (in Menu Extras)
2. Insert a test $$ a_b $$

**Expected behavior**
The production of a Latex formula

**Screenshots**
![image](https://user-images.githubusercontent.com/10895414/79910380-e68b5e00-841e-11ea-8058-a1f416902b98.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: 12.9.7

**Desktop (please complete the following information):**
 - OS: Linux Kubuntu
 - Browser Firefox 73 - 64bit

**Comment by davidjgraph** [comment]
If you force reload until you see 13.0.0, it should then work.

**Comment by federicodisante** [comment]
> If you force reload until you see 13.0.0, it should then work.

Thank you David!

If you mean reload the page, I just tried. The draw.io version stay at 12.9.7 and the error does not disappear!

But if I use a new Private Window in Firefox, the version upgrade to 13.0.0 and the error disappear!!! SOLVED!!!

Thank you again!
Federico

**Comment by davidjgraph** [comment]
Add offline=0 to the URL parameters, that should clear the serviceworker caching the older version.

**Comment by federicodisante** [comment]
> Add offline=0 to the URL parameters, that should clear the serviceworker caching the older version.

Hi David.

I tried to add the string **`?offline=0`** to the URL of my opened browser, but it doesn't helped.
With the string **`?offline=0`**, the render of the math formula was right, but the version is always  12.9.7.

Federico

**Comment by davidjgraph** [comment]
You need to load it once with offline=0 to clear the serviceworker, then load it again to get it fresh (maybe even with a browser cache clear in between).
