### ISSUE TITLE
Support EPC shapes

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#867]
Asked here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/drawio/AW4B9Z9QOEI/FrQN5G5-AwAJ

**Comment by AxelStieglbauer** [comment]
I've done a shapes library for EPCs. See attachement.
[EPK.zip](https://github.com/jgraph/drawio/files/8284128/EPK.zip)
I'd like to see them in Draw.io. How to achieve this? (The library works for me, but is it good enough to be integrated?)

**Comment by luizDR88** [comment]
Hello Axel,

Thank you for the EPC shapes! Do you know why I can't delete them once I put them on the model?
The shapes are dashed in red and don't have properties...

![EPC Shapes](https://user-images.githubusercontent.com/98462731/196389293-f8a997e0-bdcc-43b4-9321-f995d691b104.png)
