### ISSUE TITLE
Copy-pasting formatted text doens't work (anymore)

### ISSUE THREAD

**Issue by nicola-decao** [jgraph/drawio#870]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Copy-pasting formatted text from other sources (e.g., google doc or another object doesn't work).

**To Reproduce**
1. Create 2 text objects;
2. On one change the background to another color;
3. Copy-paste into that object any piece of text;
4. See error: the current background is reset to blank.

**Expected behavior**
The object should preserve current formatting.

**Video**
https://gyazo.com/8e12cb22a405f21c0845eb89287ceff1

**draw.io version 13.0.1**

**Desktop (please complete the following information):**
 - Browser: Mozilla Firefox

**Additional comments**
Also, copy-pasting formatted text from other sources (e.g, google doc) used to work and now when pasting the formatting is removed.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
