### ISSUE TITLE
Restore Draw.io files saved on the Google Chrome Browser

### ISSUE THREAD

**Issue by Jawadana** [jgraph/drawio#871]
Dears,

I have lost all my drawings saved on my browser since I disconnected from Google Chrome.
Is there any mean to restore those drawings?

Your help would be highly appreciated since I use those drawings in the professional environment.

Thank you in advance.

Jawad

**Comment by davidjgraph** [comment]
If you're being re-directed to app.diagrams.net and the browser stored diagrams are not migrating, you can use https://www.draw.io?redirect=0 to stop the redirect.

**Comment by Jawadana** [comment]
Hi davidjgraph - thank you for your swift contribution!

The issue is not linked to the redirection. 
I just restored my Google Chrome History but  I am unable to find back my draw.io files.

Any idea on how to tackle this?
thx

**Comment by davidjgraph** [comment]
Did you re-install the browser or clear cookies? Those will delete the diagrams stored in your browser.

**Comment by Jawadana** [comment]
Yes, I cleared the cookies indeed. Any way to restore?

**Comment by davidjgraph** [comment]
Unfortunately, no. I would either use the desktop draw.io and save to filesystem, or a cloud storage online.
