### ISSUE TITLE
math font change when export as PDF in 13.0.1

### ISSUE THREAD

**Issue by YanYangB** [jgraph/drawio#873]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Math font become bold when export as PDF in version 13.0.1.
When we type some math, it can be previewed successfully, like:
![preview](https://github.com/YanYangB/images/blob/master/drawio_bug/drawio-preview.png?raw=true)
when we export it as PDF in version 13.0.1, it becomes:
![version13](https://github.com/YanYangB/images/blob/master/drawio_bug/drawio-version13.png?raw=true)
The font of math becomes bold.
But when in version 12.9.13, it can be exported correctly:
![version12](https://github.com/YanYangB/images/blob/master/drawio_bug/drawio-version12.png?raw=true)
**draw.io version:**

- draw.io version: 13.0.1
- os: ubuntu 18.04

Both in browser and AppImage have the same result.

**Comment by alderg** [comment]
See https://github.com/jgraph/drawio/issues/451#issuecomment-617607817

**Comment by YanYangB** [comment]
@alderg Thanks for the reply. I have tried to change the zoom level, but it also looks bolder than normal. 
The issue disappeared when use drawio 12.9.13. So I think maybe some bug in the newest version.

**Comment by alderg** [comment]
What you are seeing is the new TeX font. This implements feature request 451.

**Comment by alderg** [comment]
We will add a new URL paramater to use the previous font in the next release, eg. https://app.diagrams.net/?math-font=STIX-Web

**Comment by YanYangB** [comment]
@alderg got it thanks.

**Comment by davidjgraph** [comment]
PDF export for other Math fonts isn't in, so use print to PDF until it is.

**Comment by YanYangB** [comment]
@davidjgraph Thank you. I'll try it later.
