### ISSUE TITLE
add swipe right/left diff display for better integration with version control

### ISSUE THREAD

**Issue by gvwilson** [jgraph/drawio#874]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

We use draw.io to create diagrams for books, lessons, and technical documentation. Several people may edit a diagram over its lifetime, either sequentially or concurrently, just as they may edit example code or explanatory text. We would like to be able to diff and merge edits to diagrams as easily as we can diff and merge edits to text.

**Describe the solution you'd like**

GitHub implemented SVG diffing in 2014 (see https://github.blog/2014-10-06-svg-viewing-diffing/). draw.io could provide a similar swipe right/swipe left display, but make one side (the current version) editable and the other (the old version or version being merged) non-editable.

**Describe alternatives you've considered**

1.  Open two diagrams side by side in draw.io and look back and forth between them: error-prone, and not practical unless you have a large monitor.
1.  Export to SVG + view diff: tedious, and requires multiple passes (because you always miss something).

**Additional context**

1.  https://discourse.opensourcedesign.net/t/existing-tools-attempts-for-diffing-svg/763 discusses some alternatives circa November 2018. The "onion skin" view is an interesting alternative to swipe left/swipe right.
2.  A shortcoming of the swipe approach is that it doesn't (easily) display changes to element properties: if, for example, an element has a hyperlink, and that hyperlink has changed, the change does not show in a left/right swipe. Showing differences in the object viewer isn't practical, since many objects may differ at the same time (imagine boxes stacked on top of each other, each with a changed hyperlink). However, we feel that changes to visual elements are more common and more important, and would be very happy with a partial solution.

**Comment by gvwilson** [comment]
Note: a multi-pane view of the sort used by many desktop text diff tools (left is version A, right is version B, center is the current state of the merge) is attractive, but:

1.  It would require much larger changes to draw.io's UI (multiple side-by-side drawings).
2.  It would need a way to draw attention to small differences (the swipe left/right does this for free because the eye is attracted to changes).
3.  It wouldn't help with the problem of properties changing but visuals remaining the same.

**Comment by alderg** [comment]
v13.10.4 now has a button to overlay the current revision in the revision history dialog:
![visual-compare](https://user-images.githubusercontent.com/921200/100441168-5002d780-30a6-11eb-94e2-7e0fae47e5e2.gif)
Shift+click on Restore now lets you edit and merge the diff for the selected revision:
![diff-sync](https://user-images.githubusercontent.com/921200/100441308-89d3de00-30a6-11eb-9044-48d20aea05c9.gif)

**Comment by gvwilson** [comment]
Thanks @alderg - is there a timeline for desktop release of V13.10.4? It looks like the latest available for download is V13.9.9. And does this feature work with Git history in the desktop version?

**Comment by davidjgraph** [comment]
The revision dialog isn't in the desktop version.

**Comment by gvwilson** [comment]
Thanks - could you please reopen this issue? We need an offline-capable solution.

**Comment by davidjgraph** [comment]
That would go in the desktop issues https://github.com/jgraph/drawio-desktop/issues
