### ISSUE TITLE
Export to Tikz

### ISSUE THREAD

**Issue by hughesjs** [jgraph/drawio#875]
The ability to export graphics to LaTex Tikz format would be invaluable.

https://www.overleaf.com/learn/latex/LaTeX_Graphics_using_TikZ:_A_Tutorial_for_Beginners_(Part_1)%E2%80%94Basic_Drawing

Inkscape has a similar feature for converting SVGs to Tiks, perhaps some of the algorithm could be reused.

https://tex.stackexchange.com/questions/370876/converting-an-svg-image-to-tikz-code

**Comment by Ra-Na** [comment]
A relatively painless method is to export as SVG, open with a program that supports TEX, and export. I found "Dia" to work OK, Inkscape and Xfig may work as well. Have a look here:
https://tex.stackexchange.com/questions/26972/what-gui-applications-are-there-to-assist-in-generating-graphics-for-tex/27062

**Comment by davidjgraph** [comment]
This is outside the scope of the project.
