### ISSUE TITLE
TLS certificate incorrect

### ISSUE THREAD

**Issue by webcatio** [jgraph/drawio#876]
I'm receiving this message from Cloudflare when I try to Authorize with Google Drive to open my documents:
Error 525 Ray ID: 5891a4254ab8d519 • 2020-04-24 17:45:59 UTC
SSL handshake failed

**Comment by davidjgraph** [comment]
Looking

**Comment by davidjgraph** [comment]
Workaround, load https://www.draw.io?tmp

**Comment by arcataroger** [comment]
> Workaround, load https://www.draw.io?tmp

Opens the app UI fine, but upon trying to load a file stored in GDrive, the same error happens.

FYI https://app.diagrams.net is not loading at all.

**Comment by davidjgraph** [comment]
Should be fixed. Might take a few minutes to propagate

**Comment by badsyntax** [comment]
Confirmed it's fixed for me.

**Comment by davidjgraph** [comment]
Switching to diagrams.net we used google managed certificates on Google Cloud and Cloudflare in front of it. If DNS points to Cloudflare the cert doesn't renew correctly if DNS doesn't point at it directly. Putting in external certs on GCP so it doesn't happen again.

Remember you store all your data, plus there's the free, open source desktop version, get.draw.io, so you always have your data and app to load/edit/save if there's a problem.

**Comment by webcatio** [comment]
Thank you David for your quick response and fix! It's working for me now.
