### ISSUE TITLE
Google Drive authorization: Cloudflare Error 525, SSL handshake failed

### ISSUE THREAD

**Issue by arcataroger** [jgraph/drawio#877]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The Google Drive integration, after it authenticates with Google and asks for permission, now results in a cloudflare SSL error:

It was working fine a couple hours ago. 

**To Reproduce**
1. In GDrive, open a diagrams.net document
2. In the "Authorization required" window, click Authorize and "Remember me".
3. Choose the right Google account
4. Confirm your choices (it might say you already gave draw.io access). Click Allow.
5. Cloudflare error happens

**Expected behavior**
1. It shouldn't need to ask for permission again
2. It should go to the document

**Screenshots**

![image](https://user-images.githubusercontent.com/11964962/80241827-e7dca680-8629-11ea-819c-13f3a5370ff2.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

Not sure, can't access.

**Desktop (please complete the following information):**
- OSX 10.15.4
- Chrome  81.0.4044.113

**Additional context**
Using GSuite

**Comment by davidjgraph** [comment]
https://github.com/jgraph/drawio/issues/876
