### ISSUE TITLE
GitHub Authorization incomplete

### ISSUE THREAD

**Issue by digiajay** [jgraph/drawio#880]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I authorize the github, the window doesn't closes automatically and comes back to draw.io "_This window will be closed automatically_." stays always.  Also, it looks like authorization is incomplete.  When I close this window manually and come back, the Authorize window persists.  When I close the Authorize dialog, it displays _Access Denied_.

**To Reproduce**
1. Go to 'https://www.draw.io/?mode=github'
2. Click on 'Create New Diagram'
3. Click Authorize.  A new window appears to get your GitHub authorization.
4. The same new window displays _This window will be closed automatically._
5. Close step.4 message window manually. 
6. See that Authorization window still persists to get authorization.
7. Close authorize dialog using 'x' mark
8. See, Access denied

**draw.io Version**
- draw.io version [13.0.1]

**Desktop:**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [80.0.3987.122 ]

**Comment by davidjgraph** [comment]
Repeatable, FF 75, MacOS 10.15.3.

"SecurityError: Permission denied to access property "onGitHubCallback" on cross-origin object"

**Comment by ashrafteleb** [comment]
Please use https://app.diagrams.net/?mode=github instead as a workaround until we fix it

**Comment by davidjgraph** [comment]
Redirect added

**Comment by akleiber** [comment]
> Redirect added

Should I be redirected if I open draw.io/?mode=github ?
I am not.

**Comment by davidjgraph** [comment]
If you're not redirected, just use https://app.diagrams.net/?mode=github

**Comment by lrockford** [comment]
This issue persists. Repeatable.
![image](https://user-images.githubusercontent.com/9937258/90679987-0eed6280-e22f-11ea-936b-3c3c27e02d84.png)

**Comment by lrockford** [comment]
This issue persists.
![image](https://user-images.githubusercontent.com/9937258/90680027-23315f80-e22f-11ea-91b7-10f3b97d45d8.png)

**Comment by davidjgraph** [comment]
This happens from https://app.diagrams.net/?mode=github ?
