### ISSUE TITLE
Show recent files when application has been just started

### ISSUE THREAD

**Issue by orangy** [jgraph/drawio#884]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When I start the application, it shows "new" or "open" choice, while often I want to open some recently edited file. It's present in File menu, but it is covered with that new/open screen. 

**Describe the solution you'd like**
Show recent files on the empty screen so I can open them with one click after I started application. 

**Describe alternatives you've considered**
Always open empty new file. The I can use File/Open Recent or File/Open menu to do what I want, or immediately start drawing.

**Comment by davidjgraph** [comment]
Workaround is to disable the splash screen and use file->open recent.
