### ISSUE TITLE
After the new update 13.0.1  double click open is not loading the diagram in the editor

### ISSUE THREAD

**Issue by ArunEdathadan** [jgraph/drawio#888]
After the new update 13.0.1  double click open is not loading the diagram in the editor

**Comment by Tx-monster** [comment]
Sometimes it works as aspected and sometimes it asks for creating a new diagram or open an existent one

**Comment by Tx-monster** [comment]
I am using offline version for windows 10, same problem here.
Sometimes it works as aspected and sometimes it asks for creating a new diagram or open an existent one.

Same happens on mac: #878

**Comment by davidjgraph** [comment]
Duplicate of https://github.com/jgraph/drawio-desktop/issues/272
