### ISSUE TITLE
Update ruler canvas on AnimationFrame (requires IE10+)

### ISSUE THREAD

**Issue by MJomaa** [jgraph/drawio#893]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

Not really. I guess every performance issue is related to this.

**Problem**

Currently the ruler updates with a debounce function or when the editor ui refreshes. If you have many shapes and/or a weak device the ruler redrawing will start lagging.
- A debounce function updates arbitrary, irregularly.
- Calling refresh many times can result into too many irregular updates, creating CPU spikes.

The redrawing/resizing should only happen

- on an event (it already does)
- on a new frame
- before the next Browser repaint

**Suggestion**
Using the Browser animation frame API we can update before a Browser repaint and really only when it is needed. No debounce required since we can cancel previous operations. 

```
animationId = -1

someListener = function() {
    cancelAnimationFrame(animationId);
    animationId = requestAnimationFrame(function() {
        // do ruler updates here
    });
};
```
API availabe for: https://caniuse.com/#search=animationframe

**Additional context**
I"ve tested this on an unoptimized project and it dramatically improved the ruler smoothness and performance. I haven't looked into other parts of drawio, but I guess that resizing the sidebar can use the same technique since it will require some expensive operations such as validating the background of the graph view. This is an improvement, but the underlying problem why such an optimization has any effect in the first place is because there can be too many nodes in the DOM tree. A WebGL renderer would be the biggest performance improvement.

**Comment by MJomaa** [comment]
**Also interesting**

1. The API _requestAnimationFrame()_ should be called for each animation-like function since they will be added internally to a callback list. Don't create a singleton where you combine-reduce all functions into one, it's counter productive.
 
2. The returned ID is unique to the particular request, not to the whole frame with all callbacks. If you need the whole frame you can pass _DOMHighResTimeStamp_ to it.

**Comment by ashrafteleb** [comment]
Added, should be in the next release
