### ISSUE TITLE
[Bug report] Find doesn't search for text in the middle

### ISSUE THREAD

**Issue by Huy-Ngo** [jgraph/drawio#895]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I search for text, only the beginning words of an element is searched. For examples, if I have an element with text "Foo bar" then search for "bar", it won't be found

**To Reproduce**
1. Create an element
2. Add "Foo bar" to the element
3. Press Ctrl+F and search for "bar"

**Expected behavior**
The texts in the middle should be searched.

**Screenshots**
![image](https://user-images.githubusercontent.com/19296926/80934192-35f36600-8df1-11ea-9029-eea4b9577c24.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 13.0.6]

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome
 - Version [e.g. 81.0.4044.129]

**Additional context**
Why is this important? I am drawing a very large diagram, and it is very troublesome if I can't mark some element with a marker then search for it later. Of course, I can put those at the beginning, but it becomes useless when there are more than one notes for one element.

**More**
For users who are meeting this same problem, you can use browser's search in the toolbar instead, whose shortcut is overwritten by this app. Browser's search tool also highlight the text better.

**Comment by SciFunk** [comment]
Another workaround: if you check the "regular expressions" box in the draw.io search, you can use .*bar.* to find any instance of bar.

**Comment by tigerinus** [comment]
> Another workaround: if you check the "regular expressions" box in the draw.io search, you can use `.*bar.*` to find any instance of bar.

I'm having the same trouble. Thanks for the workaround.

Hope 'Find' experience can be improved soon.

**Comment by JesseAldridge** [comment]
I don't think you don't actually need to use `.*bar.*`. You can just search for `bar`. As long as the regex box is checked it will work. This suggests that simply having the "Regular Expression" box be checked by default could be an easy fix for this issue. In fact you could hide the checkbox and make all searches be regex searches by default. Would mysteriously fail 1% of the time when people try to search for special characters though.
