### ISSUE TITLE
Load configuration and/or styling via JS

### ISSUE THREAD

**Issue by ga5tan** [jgraph/drawio#897]
How can I load configuration via JS ?

This FAQ item:
[https://desk.draw.io/support/solutions/articles/16000058316-how-to-configure-draw-io-](url)
describe, how to customize draw.io
But there is no mention on how to use window.DRAWIO_CONFIG from Preconfig.js
 I tried it like this:
`window.DRAWIO_CONFIG = `{
  "customPresetColors": [
    "B5739D",
    "7EA6E0",
    "67AB9F",
    "FFD966",
    "EA6B66"
  ],
.
.
.`
in Preconfig.js, but no joy.
all I was able is to do was load custom styles like this:

`var node = mxUtils.load('styles.xml').getDocumentElement();

    if (node != null) {
        var dec = new mxCodec(node.ownerDocument);
        dec.decode(node, this.editorUi.editor.graph.getStylesheet());
    } else console.debug('Node is null');`

but that for some reason wont work in Chrome, when loading file opens a new tab :(

**Comment by CvH** [comment]
Anyone a idea how this should work ? 
I know how I have to puzzle my config but have no idea how it should work.

I just added basic stuff and can confirm that it get loaded via Preconfig.js. But still doesn't work. Sadly there is zero docs about it.
The docs are only mentioning how it works if you have it integrated https://drawio-app.com/customizing-the-draw-io-interface-in-confluence-server/ .
edited `/var/www/drawio/js/PreConfig.js` and tried variations of
`window.DRAWIO_CONFIG = "{\"language\":\"de\"}";` 
`window.DRAWIO_CONFIG = '{"language":"de"}';`
...

**Comment by sag1** [comment]
I am also facing the problem. I don't know how to configure the value for this variable. As this issue is closed, I reported a new issue https://github.com/jgraph/drawio/issues/1825
