### ISSUE TITLE
Add support for FMC/TAM stencils

### ISSUE THREAD

**Issue by SvetlinZarev** [jgraph/drawio#899]
**Describe the solution you'd like**
I'd like drawio to support FMC and TAM stencils - at least [block diagrams](http://www.fmc-modeling.org/download/notation_reference/Reference_Sheet-Block_Diagram.pdf).

Most of the shapes are already available, so only a few new shapes (such as read/write access, request/response channel, etc) need to be implemented and then grouped together in their own tab in the "Shapes" window

**Additional context**
Resources:
* [Visio FMC stencils](http://www.fmc-modeling.org/fmc_stencils)
* [Vision TAM stencils](http://www.fmc-modeling.org/tam_stencils)
* Reference sheets: http://www.fmc-modeling.org/more2read

**Comment by davidjgraph** [comment]
Have you tried dropping the vss files into the editor?

**Comment by SvetlinZarev** [comment]
Yes, but it resulted in the message "Service unavailable or blocked".

**Comment by davidjgraph** [comment]
Where are you using draw.io, at app.diagrams.net?

**Comment by SvetlinZarev** [comment]
Latest desktop app on Mac OS

**Comment by davidjgraph** [comment]
Desktop doesn't support vss, use the online version. Please in future fill in the details in the template issue report, otherwise it takes time to ask them later in the thread.
