### ISSUE TITLE
Broken images in exports after release 12.9.6 (including)

### ISSUE THREAD

**Issue by samartzidis** [jgraph/drawio#901]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When using the self-hosted version of draw.io. The PNG **export** of a diagram that contains **external images** results in those images being displayed as a white box with an X in the exported file.

**To Reproduce**
* Download any version release 12.9.6 onwards and host the static JS app behind a web server.
* Create a new blank diagram.
* Go to: _Arrange_ -> _Insert_ -> _Image_ and paste that URL "https://cdn3.iconfinder.com/data/icons/brands-applications/512/PDF-128.png"
* Save the draw.io document on local filesystem.
* Go to: _File_ -> _Export As..._ -> _PNG_ and save the file on local filesystem.
* Open the locally saved PNG file. The inserted image will show as a white box with an X.

**Expected behavior**
I would expect the inserted image to show (correctly) as in the draw.io document before the export operation.

**Screenshots**
![Untitled Diagram](https://user-images.githubusercontent.com/3474783/81290952-d4d1c980-9060-11ea-8869-c5d11c424737.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

[12.9.6] onwards, when self-hosted.

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
A plain diff between the previous working release (12.9.5) and the reported one (12.9.6) shows that the "diagramly" component had been updated, which may have caused this behaviour.

**Comment by stanislavkozlovski** [comment]
👍 Same problem

**Comment by davidjgraph** [comment]
Please do not "me too" in thread. Use the thumbs up to up-vote the original post.

**Comment by davidjgraph** [comment]
That wouldn't be expected to work. Images hosted on third-party domains won't render on canvas when the image is generated client side, so they have to go via a proxy on the server to make them same domain.

Just the static JS alone cannot support this.

**Comment by samartzidis** [comment]
@davidjgraph, thanks for your answer. If this wouldn't be expected to work as you say, why does it work on earlier versions of draw.io and it is only broken only after the 12.9.6 release? We are using draw.io hosted in MediaWiki for several years now and we are impressed by its capabilities and user friendliness but this particular issue is blocking us from upgrading further than the 12.9.5 release.

**Comment by davidjgraph** [comment]
Could you look at the network traffic please for generating an client-side image containing cross images for both .5 and .6 and post the output please?

**Comment by finzzz** [comment]
> Could you look at the network traffic please for generating an client-side image containing cross-domain images for both .5 and .6 and post the output please?

I have tried .5 and .6 but still output the same. I also tried nginx redirection but has no luck.  
It fetches `SERVER/proxy?url=....jpg` instead of the actual image url when exporting. I'm pretty sure, it can be fixed.

**Comment by davidjgraph** [comment]
OK, I'll reopen. Please submit the fix.

**Comment by finzzz** [comment]
I'm not that good at JS, so not sure if I can fix it or not.

**Comment by davidjgraph** [comment]
"I'm pretty sure, it can be fixed." You don't know the code, don't know JS but you're pretty such it can be fixed?

**Comment by finzzz** [comment]
If you can fetch code from external sources why can't it be done?

**Comment by finzzz** [comment]
Why this issue is closed? Isn't this a basic function? Like @samartzidis said, if previous version works, why not the later version? If you don't have the ability to figure out the solution, you should at least warn people what's not working or remove static app functionality altogether.

**Comment by davidjgraph** [comment]
I stated the problem "Images hosted on third-party domains won't render on canvas when the image is generated client side, so they have to go via a proxy on the server to make them same domain.". Why part of this don't you understand?
