### ISSUE TITLE
When adding layer popup the rename dialog 

### ISSUE THREAD

**Issue by SanjayVyas** [jgraph/drawio#902]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Adding a new layer added a new layer as "Untitled Layer" which invariably makes us double click to rename.

When Adding a new layer, pop up the Layer rename dialog. If the user doesn't want to rename it, he/she can simply press enter.

**Comment by davidjgraph** [comment]
Fix in 24.5.5.
