### ISSUE TITLE
Option for dynamic embedded diagram in OneDrive

### ISSUE THREAD

**Issue by randoogle** [jgraph/drawio#903]
* [ x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I am wanting to use diagrams in our SharePoint documents. Currently I can get them to work by using the embed option using an iframe (html breaks a bunch of JavaScript BTW). This is pretty great, and it even gives us a link to update the diagram. However, any changes do not carry across to the embedded diagram (because it is embedded as static code).

**Describe the solution you'd like**
I'd love to have an embedded option for OneDrive that works similar to how Google drive embedded diagrams work, where the iframe simply includes the url to the file in OneDrive.

**Describe alternatives you've considered**
I've thought about creating a SharePoint webpart that can parse the drawio xml file and URL encode the diagram object to generate the same iframe code as comes from diagrams.net
But creating a webpart is a bit complicated, from what I can tell, and I don't know where to begin.

**Comment by agulabon11** [comment]
There should be a way to edit, or at least preview, a DrawIO file in OneDrive or Sharepoint online.
