### ISSUE TITLE
Add Moderation Relationship (link nodes to links)

### ISSUE THREAD

**Issue by hwongbaul** [jgraph/drawio#904]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'd like to request a feature that a node could be linked with a link, i.e. represent a **moderation** relationship within three nodes. 

**Describe the solution you'd like**
Links between nodes is not just a relationship, but a object that could be connected with other nodes or links.

**Describe alternatives you've considered**
[VUE ](https://github.com/VUE/VUE)(Visual Understanding Environment) provide such feature but no longer update.

**Additional context**
in VUE:
![link to relationship in VUE](https://user-images.githubusercontent.com/8535390/81383968-9103c080-9143-11ea-885e-126bd67d013d.png)
It's ok to drag nodes.
---
in Diagram.net:
![example in diagram.net](https://user-images.githubusercontent.com/8535390/81384221-ea6bef80-9143-11ea-8b0d-9aa6f5d6a63a.png)
![image](https://user-images.githubusercontent.com/8535390/81384433-3dde3d80-9144-11ea-8e0a-7119032cb85b.png)

**Comment by MJomaa** [comment]
Edge-to-Edge is afaik not supported. See the feature request here: 
https://trello.com/c/cq7QoWjS/313-edge-to-edge-connections

**Comment by hwongbaul** [comment]
> Edge-to-Edge is afaik not supported. See the feature request here:
> https://trello.com/c/cq7QoWjS/313-edge-to-edge-connections

 I'd checked it out, and thanks a lot for the information!😁 I believe this is a useful feature. Not sure if there is any maintained project supporting it.
