### ISSUE TITLE
Export diagram automatically on 'save' too.

### ISSUE THREAD

**Issue by aadrian** [jgraph/drawio#907]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
In almost all projects, when saving a diagram (to a VCS, or some other storage), the image (PNG/JPG) is also required to be saved near the file (with the same name, different extension), in order to be also directly embedded in documents, or just visualized with web UIs without having to open a "Viewer" like the diagram editing tool, or to be able to let other tools generate thumbnails out if them.

**Describe the solution you'd like**
To have an option: "Export diagram automatically on save".  This would also perform a silent export when the users is saving (or auto-saving) the diagram all the time.

**Describe alternatives you've considered**
The "alternative" is to do it manually - this is error prone, and the most diagrams/images in our repos are out of sync, since users forget all the time to do the required manual steps, or the export is bad since users always forget some of the export parameters (border, transparency, scale, etc).

**Comment by alderg** [comment]
What is the use case for this?

**Comment by aadrian** [comment]
> What is the use case for this?

@alderg "Make DrawIO smarter and more usable thus helping users save time and avoid errors" ?  

Any diagram in their native format, (`*.drawio` in this case) is not useful for other systems _(except the Diagram editor and for versioning/storage purposes)_ . 

To have the diagram  usable by other tools/systems, it needs to:
 - be exported first, after saving a change (PNG, SVG, whatever), 
 - also this export needs to be kept in sync with the original diagram file on any change by any user, with the same export parameters.

"Automatic export on save" would just do that.

**Comment by davidjgraph** [comment]
Why not just save in PNG/SVG with embedded XML?

**Comment by aadrian** [comment]
> Why not just save in PNG/SVG with embedded XML?

@davidjgraph because the exported files files might be edited/changed by other tools too (e.g. watermaking, other properties, anonymizer, i18n tools, etc), thus is not guaranteed for the metadata to remain "intact" _(having the "original" as `*.drawio` is very good)_.
