### ISSUE TITLE
Illegal constructor error on component duplicate/copypaste

### ISSUE THREAD

**Issue by thiagosoeiro** [jgraph/drawio#908]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Illegal constructor error popping up on screen when I try to duplicate/copypaste any component.

**To Reproduce**
1. Go to 'File > Open from > Device'
2. Select saved .drawio project from my hard drive
3. Try CTRL + C or right-click 'Duplicate'

**Expected behavior**
Should successfully clone selected objected.

**Screenshots**
<a href="https://ibb.co/wCstQ6M"><img src="https://i.ibb.co/wCstQ6M/Capturar.png" alt="Capturar" border="0"></a>

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.1.10

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 83.0.4103.44

**Comment by davidjgraph** [comment]
I cannot repeat this. This is using app.diagrams.net with no modifications?

**Comment by thiagosoeiro** [comment]
Yes. This is my project file: https://easyupload.io/q3hktv

This is console error:
<a href="https://ibb.co/fN0cMg1"><img src="https://i.ibb.co/fN0cMg1/Capturar.png" alt="Capturar" border="0"></a>

**Comment by davidjgraph** [comment]
If you open a blank diagram, drag a single shape in and duplicate it, does it happen?

**Comment by thiagosoeiro** [comment]
No, it does not.
I'm using C4 shapes, but new shapes added to the same project will work just fine. Only shapes already saved to this .drawio project will not work as expected.

**Comment by davidjgraph** [comment]
What is C4 shapes, a plugin? Uninstall it and try again.

**Comment by thiagosoeiro** [comment]
Same behaviour. Has anything changed so a .drawio file saved from january may experience breaking changes?

**Comment by davidjgraph** [comment]
No. Can you attach the file?

**Comment by thiagosoeiro** [comment]
Yeah. I already attached in the message 23 minutes ago. Can you see it?

**Comment by davidjgraph** [comment]
You're hitting https://github.com/tobiashochguertel/c4-draw.io/issues/11 (same issue as https://github.com/tobiashochguertel/c4-draw.io/issues/15). The plugin isn't written correctly, the steps to correct it are detailed in 11.

**Comment by builder7777** [comment]
> You're hitting [tobiashochguertel/c4-draw.io#11](https://github.com/tobiashochguertel/c4-draw.io/issues/11) (same issue as [tobiashochguertel/c4-draw.io#15](https://github.com/tobiashochguertel/c4-draw.io/issues/15)). The plugin isn't written correctly, the steps to correct it are detailed in 11.

I don't see steps to correct it in https://github.com/tobiashochguertel/c4-draw.io/issues/11

**Comment by davidjgraph** [comment]
"The problem seems to be related to the plugin attaching data to cells outside of the cell.value property. The recommended and supported custom data storage in cells is inside an XML node in cell.value"

**Comment by builder7777** [comment]
> "The problem seems to be related to the plugin attaching data to cells outside of the cell.value property. The recommended and supported custom data storage in cells is inside an XML node in cell.value"

These are not steps.
