### ISSUE TITLE
Multi-object operations

### ISSUE THREAD

**Issue by ebekker** [jgraph/drawio#909]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I was wondering if it's possible to perform certain operations when selecting more than one object, such as:
  * Union - combines 2 (or more) individual shapes into a single contiguous shape
  * Intersect - derives a single shape from 2 (or more) individual shapes but only where they intersect/overlap
  * Subtract - subtracts the intersection of a shape from another shape

These are just sample of some of the operations.

**Describe the solution you'd like**
Select 2 (or possibly more) shapes in a diagram and click an operation button.  For some operations like Subtract, the order of selection is important.  For example if you select shape 1, then shape 2 then click subtract, shape 2 would subtract from shape 1.

**Describe alternatives you've considered**
I was searching through the docs and other GH tickets and didn't see any of these features mentioned or previously requested.  The exist in other tools so it's possible to create them elsewhere then import them into draw.io.

**Additional context**
Illustrated samples:
![drawio-ops](https://user-images.githubusercontent.com/3308726/81627675-b5be9900-93cc-11ea-8b51-12d6a71e743a.png)

**Comment by ebekker** [comment]
I guess no interest in implementing this?

**Comment by ksiansf** [comment]
Too bad that would be a great way to create complex shapes.

**Comment by PatrickVHL** [comment]
Very good suggestion

**Comment by luciust** [comment]
Well I would love to see that, had to ditch draw.io because of that :(

**Comment by davidjgraph** [comment]
A new ticket with this issue has been opened at https://github.com/jgraph/drawio/issues/2898. We've all unsubscribed from it as we don't want to write it.
