### ISSUE TITLE
Error importing MS Visio diagram

### ISSUE THREAD

**Issue by mark-az** [jgraph/drawio#910]
I am trying to import a MS Visio diagram into draw.io but it hangs with the spinning icon running forever and the browser almost freezed.
In the javascript console lots of errors are reported concerning the 'path' attribute value, like the following:

app.min.js?__WB_REVISION__=69b9f7b905b30ccf4127a31e0d83bc3d:453 Error: <path> attribute d: Expected number, "…41.95 10 L 1841 1.57900127560107…"

I also tried to convert it in vsdx format (from original vsd format) prior trying to import but it doesn't help.
Importing the same file with LibreOffice works quite well, thought some lines are not perfectly connected to their shapes.
Attached full browser console log and the (zipped) affecting diagram

[www.draw.io-1589212939474.log](https://github.com/jgraph/drawio/files/4615516/www.draw.io-1589212939474.log)
[PR-41-05-01.zip](https://github.com/jgraph/drawio/files/4615537/PR-41-05-01.zip)

**Comment by mark-az** [comment]
Enviroment is:  Linux Opensuse Tumbleweed + Google Chrome 80.0.3987.149 (64 bit)
same behaviour on: Windows 10 + Google Chrome 80.0.3987.149 (64 bit)

**Comment by davidjgraph** [comment]
How was this created. We tried to open using Visio online and that failed as well.

**Comment by mark-az** [comment]
I don't know  Visio Online, but for sure that file has been created with MS Visio 2013
