### ISSUE TITLE
Shared diagrams are not opening in from the Diagrams App

### ISSUE THREAD

**Issue by dinukakavinda** [jgraph/drawio#912]
The Onedrive can't open shared Diagram files. When trying to open a shared draw.io file, it doesn't show up a shared category. Here the shared with me files tab is missing.

![image](https://user-images.githubusercontent.com/31726882/81822430-b718ce80-9550-11ea-9a87-51322f764040.png)

**Comment by davidjgraph** [comment]
The shared libraries section is nothing to do with diagrams.net, it's a section in the OneDrive picker that we have no control over.

Please follow the guidelines when posting. Searching for "onedrive shared libraries" in the google group reveals this previous thread on the subject, [https://groups.google.com/forum/#!searchin/drawio/onedrive$20shared$20libraries%7Csort:date](https://groups.google.com/forum/#!searchin/drawio/onedrive$20shared$20libraries%7Csort:date)
