### ISSUE TITLE
Working with shapes very slow on iPad pro

### ISSUE THREAD

**Issue by Cassiakai** [jgraph/drawio#914]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I’m trying to create block diagrams using diagrams.net on my iPad Pro. With any shape stencil ,or freehand shape, the manipulation is very slow and jittery.  For example if I try to move or resize a square in my document, the square will move a little then stop, move a little then stop. This means to move a shape from one side of the screen to the other will take several seconds.

I’ve turned of auto save thinking it was causing the slow down as well as turning off the grid.  This fault happens 90% of the time, and occasionally the action will be smooth.

The fault happens creating a document saved to OneDrive (work share space) or on my Google Drive or local iPad drive.

**To Reproduce**
1. Diagrams.net change to Device (or any drive)
2. New diagram
3. General shapes - square (any shape)
4. Select square with finger or Apple Pencil 
5. Shape outline highlighted blue move shape

**Expected behavior**
Shape should move smoothly.

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 13.1.1

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9
 - OS: 13.3.1
 - Browser Safari

**Comment by davidjgraph** [comment]
Update iPadOS to 13.4.x

**Comment by Cassiakai** [comment]
Thanks that worked. 😊
