### ISSUE TITLE
Feature Request for Embed Mode: include xml in load event

### ISSUE THREAD

**Issue by hediet** [jgraph/drawio#916]
If a document is loaded with the load action, it would very useful if the actually loaded xml document is included in the load event. This is particularly practical when loading a png or svg file.

This is the current behavior:
```
vscode -> drawio: { action: "load", xml: "<mxfile host="localhost" modified="2020-05-14T16:04:47.043Z" agent="5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.45.0 Chrome/78.0.3904.130 Electron/7.2.4 Safari/537.36" version="13.0.9" etag="hUiw05cRziyfAYYzymtF">
    <diagram id="Wvb0a2wADpB9Kn_nfm9h">
        ddHNEoIgEADgp+GuMFmdzfLSyUNnRjZhBl0GabSePh0kY6wLs3y7sPwQlrfjxXIjryhAE5qIkbAToTRLsmmc4elhF6CxSnhKV6jUCxZMFn0oAX1U6BC1UybGGrsOahcZtxaHuOyOOu5qeAMbqGqut3pTwkmvB7pfvQTVyNA5zY4+0/JQvNykl1zg8EWsICy3iM5H7ZiDnt8uvItfd/6T/RzMQud+LJiCde9pEn0QK94=
    </diagram>
</mxfile>", autosave: 1, actionId: "1" }
vscode <- drawio: { event: "load", pageVisible: true, translate: { x: 606, y: 468 }, bounds: { x: 606, y: 468, width: 0, height: 0 }, currentPage: 0, scale: 1, page: { x: 606, y: 468, width: 827, height: 1169 } }
```

As you can see, the input xml is not returned.

I know that I can request the current xml, but if the autosave feature is used, it would be much easier to keep the xml model synchronized if load also reports the current xml.
The autosave feature sends an event that contains the new xml whenever something changes.

**Comment by davidjgraph** [comment]
What problem case does this fix?

**Comment by hediet** [comment]
I have to admit, this would solve a rather special problem case.

In my Draw.io extension for VS Code, I maintain a [synchronized drawio xml document](https://github.com/hediet/vscode-drawio/blob/master/src/DrawioInstance.ts#L17).

For requesting an xml document, there is a [`getXml` method](https://github.com/hediet/vscode-drawio/blob/master/src/DrawioInstance.ts#L138).
This method has to account for the possibility of being accessed directly after loading a new drawio document, but before autosave has been fired.
In this case, I have to export the xml manually. However, in the meantime, autosave could have been triggered by user interaction, leading to possible race conditions.
It is unclear whether the requested export has priority over autosave, if the export has been issued before. It is very clear that an autosave cannot happen before the load request has been answered.

If load would return the loaded xml document, maintaining a synchronized xml document would be a bug free no-brainer. If autosave is understood as a way of synchronization and load accepts various input formats (*), it makes only sense that load triggers the initial synchronization.

(*) this is why I cannot/don't want just use the input file as the first version of the internal xml document: It might not even be xml.

If this is too complex to implement or if you do think this might lead to feature bloat, I can understand and live with that. However, I think it works well together with how autosave works.
