### ISSUE TITLE
Cannot open at all

### ISSUE THREAD

**Issue by Dr-Drosophila** [jgraph/drawio#917]

**Comment by davidjgraph** [comment]
Try another browser. Did you open from drive.google.com, selecting the file and open with? Or open from the dialog on the diagrams.net site?

**Comment by Dr-Drosophila** [comment]
I opened from Chrome now.
It works from Chrome.

I have been always going through drive.google.com <http://drive.google.com/>, selecting the file, and then selecting “Open with” (image).

It worked from Chrome, but not safari.
It used to work on the same safari version before.
Has something changed that does not allow me to work from Safari anymore?

CR

**Comment by davidjgraph** [comment]
Cookies might be corrupt, try clearing in Safari.

Check that third-party cookies are permitted, also.

**Comment by Dr-Drosophila** [comment]
… That was easy…

Deleted all cookies for diagrams.net <http://diagrams.net/> and draw.io <http://draw.io/>…
Works on Safari now…

Thank you David :D

Stay safe
CR
