### ISSUE TITLE
[Bug] Font Size Reset in online version

### ISSUE THREAD

**Issue by Zenahr** [jgraph/drawio#920]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Creating a text, changing the font size and then selecting all text inside the text element and writing new text resets the font size.

**Note:** this does not happen when using the desktop app (tested on Windows 10)

**To Reproduce**
1. create a new diagram
2. drag in a new text widget
3. select widget
4. change font size
5. select all text inside widget
6. type in new text

Result: font size jumps back to the default value.

**Expected behavior**
Keep the formatting settings when replacing all text inside a text widget of which I have already changed the formatting settings.

I am used to copy and paste components and just replace the text like so:
![image](https://user-images.githubusercontent.com/47085752/82122201-6b556780-9792-11ea-9aa9-649ddb362db5.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.1.2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox (Developer Edition)
 - Version: 77.0b6

**Comment by Vasiliy-Bondarenko** [comment]
Same issue for me. Very annoying. It happens in Firefox only. But i definitely prefer Firefox for drawio because it works faster when selecting objects with a mouse, while Chrome is lagging.

**Comment by Naroleptic** [comment]
Same here. Everything works well and very intuitively, but find no way of setting a default font other than Helvetica 12, wich new objects revert to when created. If i copy a object via the blue arrow text in object keeps format of original object.

This shoulr really work the way one expect - ie, either a "set as default" not only for objects but for fonts to (setting an object with formatted text in as default does NOT control formatting of text in new objects) and the choice of making the last choosen font default for next object?

Cheers!

**Comment by jonasViehweger** [comment]
This still occurs and is quite annoying.

**Comment by alderg** [comment]
This is a known Firefox contenteditable bug — when all text is selected and replaced by typing, Firefox strips the inline styles from the container element. The same steps work correctly in Chrome and Safari, as well as the desktop app (which uses Electron/Chromium).

Since the in-place text editor relies on the browser's native contenteditable implementation, there isn't a clean fix we can apply on our side. This would need to be addressed in Firefox's contenteditable handling.
