### ISSUE TITLE
Mermaid statediagram not rendered

### ISSUE THREAD

**Issue by nrnjnt** [jgraph/drawio#921]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Entering the mermaid syntax for a state diagram, for example as shown below, does nothing.
"
stateDiagram
    s1 --> s2
"

**To Reproduce**
1. Go to 'Arranged'->'Insert'->Advanced
2. Click on '.Mermaid..'
3. Enter the text shown above
4. No diagram generated.

**Expected behavior**
Simple state diagram as shown in https://mermaid-js.github.io/mermaid/#/stateDiagram.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [13.1.2]

**Desktop (please complete the following information):**
 - iOS
 - Browser (chrome)

**Additional context**
Same behavior if I first generate another type of diagram (figure is rendered) and then change the Mermaid text to state diagram (it disappears).

**Comment by ashrafteleb** [comment]
Fixed
