### ISSUE TITLE
PDF Export in Embed Mode

### ISSUE THREAD

**Issue by hediet** [jgraph/drawio#922]
Hello there ;)

I wonder how the PDF export in Draw.io works. It does not seem to work anymore when self hosting drawio. I guess that you use some server-side processing that clearly is not available when drawio is not served from https://draw.io.
How does Draw.io generate pdf files?

Thank you!

**Comment by davidjgraph** [comment]
Electron has PDF generation functionality, see https://github.com/jgraph/drawio/blob/master/src/main/webapp/js/diagramly/ElectronApp.js#L1404, I'm not sure what the permissions are in VS Code, but if you have the Base64 and can make this call, you could get the PDF.

**Comment by hediet** [comment]
First of all: Thank you so much for your sponsorship ;)

And thank for the link.
I think the more interesting part is here:
https://github.com/jgraph/drawio/blob/90ba75589c/src/main/webapp/electron.js#L1076

I cannot do that in my extension though, as it does not run inside electron.
I think this will end up in a solution that involves puppeteer.

Have you noticed major differences between the pdf generated by your hosted backend and by electron?

**Comment by davidjgraph** [comment]
Welcome, it is actually all of us on the project, btw, not just me 8-).

The puppeteer solution works pretty well, certainly better than the PhantomJS solution we used to have.

One issue we do have is font support. Both use the OS available fonts, so you'd need to run puppeteer on the same machine to have the same fonts. You're planning to run a local version that serves the plugin in VSCode?

**Comment by hediet** [comment]
> Welcome, it is actually all of us on the project, btw, not just me 8-).

Then thank you to all of you ;)

> You're planning to run a local version that serves the plugin in VSCode?

Kind of. I plan to make this a separate "SVG Exporter" extension that can export arbitrary svgs to pdf/png, completely independent of draw.io.
I don't want to bundle puppeteer in this "SVG Exporter" extension - it would be huge (like 700MB, since it would have to ship browser binaries for all three platforms).

My idea is to have a npm package (like `@hediet/svg-exporter`) that must be installed globally to use the "SVG Exporter" extension, so that npm takes care of installing puppeteer with the right browser binaries.
Alternatively, I would use puppeteer-core that uses chrome if it is already installed. 

This requires people to work with `*.drawio.svg` files though. If they don't want that, I can still improve that.
