### ISSUE TITLE
Embed Mode - Add Plugins from URL

### ISSUE THREAD

**Issue by hediet** [jgraph/drawio#923]
How do I add plugins from a specific url when using the embed mode?

The [docs](https://desk.draw.io/support/solutions/articles/16000058316) say that "plugins" is not available when using configure=1. Why?

**Comment by davidjgraph** [comment]
Just for simplicity. No questions over which one wins.

**Comment by hediet** [comment]
Which wins over what? As far as I can see, currently, the embed mode does not support plugins.

**Comment by davidjgraph** [comment]
Ah, custom pluigin, OK, no. If you're running your own version of the app, you could probably (TM) invoke the plugin load from the postConfig.js.
