### ISSUE TITLE
Plugin Development: How to set custom attributes to a cell

### ISSUE THREAD

**Issue by hediet** [jgraph/drawio#924]
How can I set a custom attribute for a cell that gets saved with the document?
`getAttribute`/`setAttribute` does not work the way I think.

I found [this](https://jgraph.github.io/mxgraph/docs/js-api/files/model/mxCell-js.html) documentation, but it does not really help. I don't understand how I can use an XML node as the value of the cell.

**Comment by hediet** [comment]
[I use this code](https://github.com/hediet/vscode-drawio/blob/text-range-linking/injected-scripts/linkSelectedNodeWithData.js#L44-L54) now in my prototype. I don't think this is the best way (or maybe it is?). How would you do it properly? Also, I want this feature to be composable - it should be non-invasive and work with other plugins.

**Comment by davidjgraph** [comment]
It is really a cell style? In mxGraph there's the concept of a [user object child node of a cell](https://jgraph.github.io/mxgraph/docs/manual.html#3.1.3.3), which is basically a custom data storage object that you can access via cell.value.

Check out:

https://jgraph.github.io/mxgraph/javascript/examples/userobject.html
https://github.com/jgraph/mxgraph/blob/master/javascript/examples/userobject.html

**Comment by hediet** [comment]
Thanks for the info and the example! But it seems, if multiple plugins use `cell.value`, there will be conflicts.

Also, I am not so sure what happens if a user edits a diagram with my plugin and my plugins overwrites some cell values with a custom xml element that wraps the original value and my custom data, and the user then edits this diagram without my plugin.
I guess all the wrapped values will disappear.

> It is really a cell style?
No, this is a hack :D 
But it seems to be pretty harmless to add unknown style properties while it seems to have big impact to overwrite the cell's value with my custom xml node.

**Comment by davidjgraph** [comment]
We suggest to make the user object an XML node. A well behaved plugin should create a node under that with a reasonably unique name and write/read there. If other plugins want to pretend they own the user object, well, they won't be very popular.

That said, you do raise the point that there's only one graph.convertValueToString, that does limit the amount of plugins you could have...

It's not world ending to use the style, since we manage changes to it for you. We do this for metadata on imports, it's certainly simpler.

**Comment by hediet** [comment]
Ah, I see that the default implementation of `graph.convertValueToString` actually checks if the value is an object and uses its `label` property if present.

I thought `label` was just an example property of how `convertValueToString` could be implemented.
With this default all my concerns are addressed!

**Comment by hediet** [comment]
For future reference:

This code block does not break anything:
```js
if (!mxUtils.isNode(value))
{
    var doc = mxUtils.createXmlDocument();
    var obj = doc.createElement('object');
    obj.setAttribute('label', value || '');
    value = obj;
}
```
Documents with nodes that have been transformed like this can be edited on draw.io without the need for plugins.

Providing a custom `convertValueToString` is not necessary.

**Comment by chengkehan** [comment]
@hediet Many many thanks.
