### ISSUE TITLE
Text duplication

### ISSUE THREAD

**Issue by nyqbgcd** [jgraph/drawio#925]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Often going into edit mode on a text box, a duplicate of the prior text will render.

**To Reproduce**
1. Go to a new document
2. Create a new text box
3. Start typing text
4. Deselect the box
5. Select the box again
6. Change the text slightly
7. You should notice the bug

**Screenshots**
[https://i.imgur.com/Ggu8nI6.gifv](https://i.imgur.com/Ggu8nI6.gifv)

**draw.io version (In the Help->About menu of the draw.io editor):** 13.1.2

It has been happening in Opera GX and Chrome for at least a year.

**Comment by davidjgraph** [comment]
Four of us tried and failed to recreate. What operating system?

**Comment by nyqbgcd** [comment]
I'm using Windows 10.
