### ISSUE TITLE
Can't update diagrams in Google Docs via "diagrams.net for Docs" add-on for Firefox

### ISSUE THREAD

**Issue by sphakka** [jgraph/drawio#926]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I can't update a diagram in Google Docs with "diagrams.net for Docs" for Firefox 68.8.0esr. "Update all" doesn't show any message, "Update selected" pops up a "Selection is empty" message. It looks like, once the diagram is added (one page was selected), the link to diagrams.net is lost, indeed selecting the diagram and trying "Edit selected" sends a "Could not open diagram for editing" error.

**To Reproduce**
1. Open a Google Docs document
2. Install "diagrams.net for Docs" add-on
3. Do "Add-ons" -> "diagrams.net for Docs" -> "Insert diagrams..."
4. Pick-up a diagram/page (in my case it's the last one)
5. See diagram inserted
6. Modify original diagram in diagrams.net (force save Ctrl+S)
7. Selected imported diagram in GDocs, do "Add-ons" -> "diagrams.net for Docs" -> "Update selected" 
8. A "Selection is empty" message pops up. The diagram is not updated

**Expected behavior**
Point 8. above: the diagram is updated.

**draw.io version (In the Help->About menu of the draw.io editor):**
13.1.3 (via Firefox)

**Desktop (please complete the following information):**
 - OS: GNU/Linux (Gentoo, kernel 5.4.38)
 - Browser: Firefox
 - Version 68.8.0esr

**Comment by axeltidemann** [comment]
I got a "Missing link" error message when trying to update the model the morning after I had made it. I had to delete and re-import the diagram. Chrome version 91.0.4472.164 (Official Build) (x86_64), OS X 11.4. draw.io version 14.9.1.
