### ISSUE TITLE
Treat double click on a color in the color selector as click + apply

### ISSUE THREAD

**Issue by Lorendn** [jgraph/drawio#928]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Treat double click on a color in the color selector as click + apply.

1. At the style side bar, click on fill or line color to open the color selector
2. Double click a color
3. The color selector should close and the double clicked color should be active without the need to click the apply button

**Describe alternatives you've considered**
Use the current method with click a color + click apply.

**Additional context**
None

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
