### ISSUE TITLE
Ability to select all layers, lock/unlock them, group them as folders

### ISSUE THREAD

**Issue by tvvignesh** [jgraph/drawio#930]
Hi. I have been using drawio for a long time for all my planning and its great. Recently I started using layers and while its great, I had some feedback.

1) It would be great to have a select all option for all layers so that I can do options like lock/unlock them all at once and unlock any specific layer and work with it.

2) It would be great to provide folder support for layers like what Photoshop and similar tools do to organize the layers into groups which definitely helps when working with multiple layers.

Thanks and great work with drawio btw.

**Comment by millsio** [comment]
Open this mutha back up!

**Comment by LukeDRussell** [comment]
I'd like to see this implemented.

**Comment by davidjgraph** [comment]
Voting for github issues is done by thumbs up'ing the original post.

**Comment by terefang** [comment]
+1

**Comment by Aeilstrup** [comment]
At least just add the possibility to select all layers content at once, I have almost 30 layer on one page that I need to just move up 11 pixels to match the location of another page. Thats cubersome work one layer at the time.

**Comment by davidjgraph** [comment]
Thanks for your suggestion, however, the implementation and maintenance effort vs benefit in this case doesn't work for us.
