### ISSUE TITLE
The List shape doesn't show connection points

### ISSUE THREAD

**Issue by hao-lee** [jgraph/drawio#932]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The List shape doesn't show connection points unless the cursor is hovering on the list name.

**To Reproduce**

Hover on the list item. The connection points disappear.

**Expected behavior**
The connection points should always be shown when I hover anywhere on the list shape.

**Screenshots**
Hover on the list name. Everything is OK.
![image](https://user-images.githubusercontent.com/8112645/82820489-dad6ff80-9ed4-11ea-992c-c041d8d93699.png)

Hover on the list item. The connection points disappear.
![image](https://user-images.githubusercontent.com/8112645/82820587-170a6000-9ed5-11ea-84d3-cd638eb6bb55.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.0.3

**Comment by mararad** [comment]
Reproduced in 13.10.3 in Chrome Version 87.0.4280.66 (Official Build) (64-bit). When a row is only hovered only, it shows only two row connection points. A workaround could be adding new conn points as described here: 
https://desk.draw.io/support/solutions/articles/16000042498-how-to-add-remove-connection-points-how-to-connect-anywhere-on-a-shape-

**Comment by hylkevds** [comment]
I think the problem here is that when trying to connect to a List, it shows the connection points for the list-items instead of for the list, unless one hoovers over the list title (since there are no list-items there).

Is there a way to disable this behaviour, and give the list a higher priority than the list-items?

**Comment by alderg** [comment]
Select the list items and uncheck Connectable:
![61e8e8fde1e4cb10b4bbfc9014b631e4](https://github.com/jgraph/drawio/assets/921200/dd1f0a14-878c-402c-8c2c-7b1d837bacf3)

**Comment by hylkevds** [comment]
Thanks, that works like a charm!
