### ISSUE TITLE
Icon labels alignment misplaced to right side. We are working in the embed mode. After saving the image and some other open the same diagram labels are shifting to the right

### ISSUE THREAD

**Issue by mjrgirish** [jgraph/drawio#933]
![drawiobug](https://user-images.githubusercontent.com/8536283/82829086-13280f00-9ed0-11ea-8f70-c808f2e4081f.PNG)
### Preflight Checklist

* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mararad** [comment]
Hi,

is it possible to attach a file, please and tell me where did you embed a diagram? 
You mentioned that when other users open this file, labels are shifted. What were the exact steps performed here?

Thanks,
