### ISSUE TITLE
Links created in svgs are not working in latest Chrome, Firefox and Safari

### ISSUE THREAD

**Issue by steinwelberg** [jgraph/drawio#935]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When exporting an image that contains a link, the link does not work in the latest Chrome, Firefox, Safari. Draw.io uses `xlink:href` to create links in svg images. This is a [deprecated feature](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href) of svg v2 and apparently modern browsers already removed support for this.

**To Reproduce**
1. Go to 'app.diagrams.net'
2. Create a new diagram
3. Add a link to a diagram
3. Export diagram to svg
4. Open svg image in latest Chrome/Safari/Firefox
5. Try to click on the link element

**Expected behavior**
The element with the link is clickable.

**Screenshots**
N/a

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 13.1.3]

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.4
 - Browser Chrome (81.0.4044.138), Safari (13.1 (15609.1.20.111.8)), Firefox (76.0.1)

**Comment by davidjgraph** [comment]
Works for me on FF 76. SVG 2 is not a published spec and is unlikely to ever be at the current rate. Anyone else repeat?

**Comment by steinwelberg** [comment]
Sorry, I was thrown off. They seem to be working if I open the image directly in Firefox, but not when they are included in a Mkdocs site using an HTML `<img src="">` tag. I'll close this issue and further investigate 😉.

**Comment by steinwelberg** [comment]
I already found out why it doesn't work. TIL if you embed an svg image using the `<img>` tag  there is no interaction possible. If you want interaction use the `<object>` tag.

**Comment by cinphon** [comment]
But the Links > Open in New Window (target="_blank") not working

**Comment by Starlight220** [comment]
I just ran into this, how can I embed a diagram while keeping link functionality? 
Replacing `img` with `object` doesn't display at all.

**Comment by kevinlrak** [comment]
@Starlight220 To fix that, ensure the `<a>` element in your SVG has the `target` attribute as described here:
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/target

In draw.io, you can experiment with values of that attribute if you go to `File`>`Export as`>`SVG`, then click the `Links` drop-down and select something other than `automatic`.

**Comment by mikclrk-21cs** [comment]
The links not working in an svg included via an <img... tag appears to be a security move on the part of the web browsers: https://www.sitepoint.com/add-svg-to-web-page/

The links work if you open the svg directly in the browser, but not if it's linked via an html img tag.
