### ISSUE TITLE
Add Pager icon

### ISSUE THREAD

**Issue by omides24** [jgraph/drawio#938]
----> [pager icon ](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.amazon.com%2FApollo-Programmable-Alpha-AL-924-AF-924%2Fdp%2FB00DMLHFZ2&psig=AOvVaw30oi_UhVi4r95Zh0ypvEQ0&ust=1590652520595000&source=images&cd=vfe&ved=0CA0QjhxqFwoTCJCQ_MvI0-kCFQAAAAAdAAAAABAD)

This icon need for VOIP

**Comment by alderg** [comment]
https://gyazo.com/23ff6bde6decda253bc89085e3263bc1
