### ISSUE TITLE
Label and Text are not in the good place.

### ISSUE THREAD

**Issue by algenty** [jgraph/drawio#940]
Hi teams,

First at all, i love your job and draw.io 
I'am working on grafana plugin and since version 13 of drawio, some labels are not in the good place for the same XML

Example
In 12 : 
![image](https://user-images.githubusercontent.com/47012725/83032371-07eef380-a036-11ea-909e-aac0156d0fe0.png)

In 13 : 
![image](https://user-images.githubusercontent.com/47012725/83031934-7d0df900-a035-11ea-8bfb-38d90bc0d7d4.png)

In 13, when Label is near the fronter of div, it moves

When i compare the generated svg, i found difference : 
Red version 13
Green version 12
![image](https://user-images.githubusercontent.com/47012725/83032595-54d2ca00-a036-11ea-8ab3-3f0fe4a0aae6.png)

If i replace the red section by the green section in chrome, it works, label is on the good place.
Others users are the same problem in embedded mode
https://github.com/algenty/grafana-flowcharting/issues/147

I don't know at this time how to resolve it, any idea ?

BR,
Cordialement,
Arnaud

PS : 
XML : 
7Vhtb9s4DP41+bjAkRM7+Zi0y3aHDlegG7p+Osi2YquVLVeWm2S//khZfovTImuD7oAtbQLrkUhJfEiJ9Mi9SHefFM2TLzJiYkScaDdyL0eETKaEjPDfifYV4i+mFRArHtlBLXDDfzALOhYtecSK3kAtpdA874OhzDIW6h5GlZLb/rCNFP1ZcxqzAXATUjFEb3mkkwqdE7/FPzMeJ/XME29R9aS0Hmx3UiQ0ktsO5H4cuRdKSl09pbsLJtB4tV2s3IisnxnQrE2xTJ8oQ7xqxBMVpd3ilz20BQ2QObNQva93D2vO8VEDueyHRCWrnCmeMs1UF79uwdU24Zrd5DREyS2MACzRqYDWBB43XIgLKaQyU7gb8wG80Eo+sE7P3MG/pqc2/wyR2pao0Cx9RcOHWMkyi47p3shMd3DHfACngscZYCEY0Kz9iSnNgf2l7dASVz+0szU9Dme7DmSN/olJsIZCw9remT8dzyohGwnEt1RsW7+a1AQmHZ/yLEatK8eN8h7V8GDZfoZ592eYN6ZkkTXxe1MqwbAbYZqo+20kn4G9Sc2B5W7uvC9105+iLpFpUBa/gDZkwB7hxDlK4wFHa/M5D0fugvQ4ajjrkuTOhyRNJudhaTFggkVwl9imVDqRscyo+NiiqzbMjL2aMVcSDx5j1Hum9d5alZZa9jkEe6n9d5Qfz+rmnVVnGpe7XmtvW6/mmO24/l6rhOe7dm5otbNho57sWXYLWaqQ1eehvd6pipnuOz4a8kUfUExQzZ/6l/YxPq3oteSwlMZ3vJnf952p11dRLdRKHdywB7pm0/5ZQSaLvq5qg8d0GQ9rdnWS03m/l9M1jnbX6XmL07nv42DN6VA7mE9e7WDEP3CwmXc+B/tWMPVPcI+pdH2/GJ2VIsGzh6qdaI0Z+BJVk/V9jNn/OOY6KYMxl0apwUx/J2uvpG25gH5c4MLh+zd9ojeh4jlOHHEK0mnKs9jMGihqWNAJxW6W0UAwlOSYt9HQMIMlRKWUZhGWBAmFZM5ooHkuIK3TXGaFWQv8BCjxWPLwQaDqUDGqWdROosoMfjPDuhnBM6N6b5L7e3Bh0IEFBlOtkNlOUeY5RJVRFhhJXZirLIukGlfmaOI3WN5+/Rw83n4Llndf57d7d+98IB1HsvF+JCnnqaldmpz1Ctm6lgXHbUJ/ILWW6Wm50/G8lxZ5VVNt+A7Pi5WZclmjTo3Ac98frCOEMD1ZUxFDCIId1pgL1Kx8UCzHtUokdh0IGaDT0ALzcLLmoWGq9qJ/BZxQ4F6w1LWiW1N5YCZ07Nx49ow5Rx44798Ti2GK4XnDDGP6qgQDmp1ofEN0brfbMc82otxFVNOKlUFI/mUGXK66MamhpkPfg+LORBuKB7RADIpy8JQqXjCaEog5gR0JbBstoiD1bELxsWTGjELSqDglAiZ/QqAOActcMM7hKPu17j/zyWERO3ePVELTIyHgnSkEhsWRf7w4unrxjUbCdjRGH+m9z7Bo8zaDvFxEOf+z1xnDeuscpM/9A9JPrX7nrz322pdiVcLSvloE0Fn+Bw==

Other Information : 
In viewer.min.js  : 

var mxClient = {
	VERSION: "4.0.6",

var mxClient = {
	VERSION: "4.1.2",

**Comment by alderg** [comment]
See #989
