### ISSUE TITLE
Add support for curved edges in Visio export

### ISSUE THREAD

**Issue by Yara-H** [jgraph/drawio#941]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Draw.io file not showing properly when exported to Visio.

**To Reproduce**
1. Go to file in drawio
2. Click on export as > VSDX (beta)
3. Open the exported file in Visio or Visioviewer
4. Diagram not showing properly.

**Expected behavior**
To be able to see the diagram on Visio the same way I see it on Draw.io.

**Screenshots**
![Manara VISIO](https://user-images.githubusercontent.com/66033130/83064276-338bd100-a06a-11ea-82b2-6b8038979f83.jpg)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version [11.1.4]  (downloaded from the Microsoft store)

**Desktop (please complete the following information):**
 - OS: Windows 10 pro (on Microsoft Surface Pro 4)
 - Browser Chrome 
 - Version [e.g. 83.0.4103.61]

**Additional context**
I tried opening the exported file on Visio professional 13. The version is inactivated and thought that this was the reason, so i downloaded the Visioviewer 16 and I am still facing the same issue. 
I can send the draw.io file via email if needed (because I don't have the right to post it publicly).

Many thanks!

**Comment by davidjgraph** [comment]
11.1.4 is pretty old (and I know we haven't updated it). Please try on app.diagrams.net.

**Comment by Yara-H** [comment]
Unfortunately, I just tried it and it did not work. I have downloaded the 13.0.3 version and tried exporting the file from it but again with the same results.

**Comment by Yara-H** [comment]
Hello again, I am sorry for the numerous messages. I tried removing all symbols from the map. The results are better, all the strange codes disappeared. 
![Exported to Visio Trial 2](https://user-images.githubusercontent.com/66033130/83088414-44553a80-a09c-11ea-83f9-367bef62632c.jpg)

However, the arrows which are supposed to be curved are still different (more like polylines without and not arcs). I am attaching part of the drawing to explain the difference.
![visio vs drawio](https://user-images.githubusercontent.com/66033130/83088501-8b433000-a09c-11ea-8fcd-7e93939849f5.jpg)
