### ISSUE TITLE
Mermaid Insert option not present using Minimal theme

### ISSUE THREAD

**Issue by mariolima** [jgraph/drawio#943]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The `Minimal` theme does not show the option to insert a `Mermaid` graph as is done in all the other Themes.

**To Reproduce**
1. Switch to Minimal Theme
2. Reload
3. Go to Insert > Advanced
4. No Mermaid option

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5732425/83268353-6abec700-a1bd-11ea-8fec-253870a7003b.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.1.7

**Desktop (please complete the following information):**
 - Browser Linux x86_64 Chrome/83.0.4103.61

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
