### ISSUE TITLE
Wikis are not secured?

### ISSUE THREAD

**Issue by SukantPal** [jgraph/drawio#944]
IDK why but I was able to create a wiki on your repo: https://github.com/jgraph/drawio/wiki/x

**Comment by SukantPal** [comment]
This might be security bug with GitHub.

**Comment by SukantPal** [comment]
https://github.com/jgraph/drawio/wiki/Getting-Support/Using+draw.io+with+Google+Drive - leads to a page for creating a wiki

**Comment by davidjgraph** [comment]
https://help.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis
