### ISSUE TITLE
Unable to create shape when snapping to a line in a locked layer.

### ISSUE THREAD

**Issue by torcher999** [jgraph/drawio#946]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Dragging in a new shape destroys the shape if snapped to a line on a locked layer.

**To Reproduce**
1. Unpack and open [line_grid.zip](https://github.com/jgraph/drawio/files/4707692/line_grid.zip)
2. Select Worklayer as active layer
3. Drag a shape onto the page
4. Have the shape snap into a line
5. Drop the dragged shape

**Expected behavior**
The dropped shape is created.

**Screenshots**
https://www.youtube.com/watch?v=dSzb0hRh904

**draw.io version:**
- 13.0.3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - 83.0.4103.61 64-bit

**Additional context**
This only works for new shapes. Repositioning existing shapes does not allow to snap to lines.
Using ALT when dragging disables all snapping.
[Associated feature request](https://github.com/jgraph/drawio/issues/945).

**Comment by mararad** [comment]
Reproduced in diagrams.net 13.10.2

A shape can be added to the editor when clicked in the sidebar or/and drag&dropped anywhere on canvas. The only problem is when it snaps to the grid line because it disappears.

**Comment by alderg** [comment]
Fixed in 14.8.6.
