### ISSUE TITLE
Docker image link in README.md points to older external repo

### ISSUE THREAD

**Issue by aaliddell** [jgraph/drawio#947]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
The link to 'the recommended Docker project' in README.md points to `fjudith/docker-draw.io`, but you appear to have a more up-to-date repo in your organisation that is forked from this one.

**To Reproduce**
N/A

**Expected behavior**
Update the link to point to `jgraph/docker-draw.io`

**Screenshots**
N/A

**Comment by davidjgraph** [comment]
Corrected, thanks for report.
