### ISSUE TITLE
Can't create or edit diagram from Office 365 app.

### ISSUE THREAD

**Issue by TakeshiMasukawa** [jgraph/drawio#951]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I tried to edit diagram from office 365 app but failed.
When I clicked "Edit" button, new window opened but it sayed "draw.io is now diagrams.net" then the window force closed.

**To Reproduce**
1. Open Office365 app
2. Click draw.io addon in "Insert" ribbon
3. Select a diagram file
4. Click "Edit" or "Create" button

**Expected behavior**
New window opens and we can edit diagram.

**Screenshots**
[![Image from Gyazo](https://i.gyazo.com/15314424c3a08b7cdbcfb79c0afe42f2.png)](https://gyazo.com/15314424c3a08b7cdbcfb79c0afe42f2)

**draw.io version (In the Help->About menu of the draw.io editor):**

- 13.1.12

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Microsoft Excel
 - Version 16.0.11929.20762

**Comment by w346159402** [comment]
office 365 word 
1、功能很不稳定，经常点击图标加载不上。
2、加载上后，只能看，不能进行编辑。

**Comment by davidjgraph** [comment]
Is this still valid?

**Comment by ashrafteleb** [comment]
Yes, the built-in browser in Desktop Office is very limited
