### ISSUE TITLE
May you please support openstack icons?

### ISSUE THREAD

**Issue by mostafaahamidmanon** [jgraph/drawio#952]
* [Y] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [Y] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

I need to have openstack icons as I found docker and vagrant icons.
Thanks

**Comment by davidjgraph** [comment]
Where are these sets and where are the licenses to the sets?

**Comment by jcosmao** [comment]
https://www.openstack.org/brand/openstack-logo/logo-download/
https://www.openstack.org/project-mascots/

> Logos are licensed under the Creative Commons CC-BY-ND, similar to other Foundation materials. That means you can use them freely, but can’t make derivative work, such as adding a for-profit company’s logo into your community project’s logo.
