### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by SavageAUS** [jgraph/drawio#954]
I work for a company that deals with defence  contracts and we would like to use your draw.io software. So i would like to know if we can use it in a company environment and in a Defense environment?

**Comment by davidjgraph** [comment]
draw.io is licensed under the Apache 2.0 license, https://github.com/jgraph/drawio/blob/master/LICENSE. The license explains the conditions under which the source code may be used. If you do not understand it, you need to find someone at your company that does.
