### ISSUE TITLE
Cannot copy/paste lucidchart diagram into draw.io empty diagram

### ISSUE THREAD

**Issue by gopz** [jgraph/drawio#955]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Cannot import lucidchart diagram into draw.io as following the steps described here:
https://desk.draw.io/support/solutions/articles/16000063693-how-to-import-lucidchart-diagrams-into-draw-io

**To Reproduce**
1. have a lucidchart diagram open
2. select all with ctr-a
3. copy with ctr-c
4. paste into a draw.io blank diagram with ctr-v

**Expected behavior**
lucidchart diagram will be imported into blank draw.io document

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**
in-browser, browser: chrome

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**
chrome 83

**Comment by alderg** [comment]
draw.io version not provided

**Comment by gopz** [comment]
@alderg i'm using in browser, chrome 83

**Comment by alderg** [comment]
Fixed in 13.1.13.
