### ISSUE TITLE
Mind Maps Subtree movement

### ISSUE THREAD

**Issue by arno-haas** [jgraph/drawio#957]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When creating Mind-Maps with the Advanced Features with using Tab/Enter/Shortcuts
the auto placing works very well and the whole mindmap groups everything automatically together (some times it might still overlap if the text is too long).
But as soon as I click on one window and wanting to move it manually it will freeze in place.

**Expected behavior**
Move the whole Mind Map diagram conveniently together as one 

**Screenshots**
[If applicable, add screenshots to help explain your problem.
](https://downloads.intercomcdn.com/i/o/213732827/d6c034caa0baa0ef45cc6944/ezgif.com-video-to-gif+%281%29.gif)
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/64929511/83546732-6d912300-a501-11ea-8b0f-67a8fb381ebf.gif)

**draw.io version (In the Help->About menu of the draw.io editor):**
- diagrams.net version 13.0.3

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by davidjgraph** [comment]
@mararad could you check please?

**Comment by mararad** [comment]
Reproduced in Chrome Incognito Version 87.0.4280.66 (Official Build) (64-bit) and FF 82.0.3 (64-bit)
diagrams.net 13.10.2
