### ISSUE TITLE
Don't proxy same-domain URLs

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#960]

**Comment by francoissey** [comment]
:thumbsup:

**Comment by francoissey** [comment]
I have a generic diagram which I want to use around 10 times. The only difference in this diagram is 5 names of components.
I wanted then to use placeholders and assigning their values via a url parameter as described in the documentation

https://desk.draw.io/support/solutions/articles/16000042546-supported-url-parameters

I cannot add a link to an existing drawio diagram and set  _vars={"nom":"test"_} is the URL.
I did make an example @ https://alliander.atlassian.net/wiki/spaces/AGILE/pages/1972961630/Test
