### ISSUE TITLE
Add Fonts awesome v4 or material.io icons

### ISSUE THREAD

**Issue by WHK102** [jgraph/drawio#961]
I suggest adding the free Fonts Awesome 4.7 icons: https://fontawesome.com/v4.7.0/icons/

I do not recommend using Fonts Awesome 6 for its restrictive licenses and because it is a commercial version.

For example, it would be possible to use intuitive and single-style icons, such as: https://fontawesome.com/v4.7.0/icon/print , because there are icons that are in one category of objects and others in another category with a totally different design. Fonts awesome would solve this problem.

I do not know if it is how to insert as a text source but it would be very useful if they were available as an icon vector. I know it is a long job having to vectorize each one but it would be very useful.

To avoid conflicts with some brands, you can omit the social icons.

**Comment by davidjgraph** [comment]
6? Do you mean 3?

**Comment by WHK102** [comment]
https://fontawesome.com/

> Now Brewing… Font Awesome 6!

The fonts awesome 5 and 6 is a paid version but 4 is free https://fontawesome.com/v4.7.0/

Fonts awesome was unfortunately acquired by a company and the free version of its fonts are restrictive and very few, however version 4 existed before being acquired and its free license was kept.

But you do not need to use the fonts directly, it is possible to use your own vectors using the same silhouettes as a base.

Additionally you can also use https://material.io/resources/icons/ which if it allows you to use them freely and you can download them in SVG format.

The main idea is to have a range of icons that maintain the same type of design and that are generic since you do not always need to make a google or amazon diagram, many times I need to make custom diagrams with navigation flows interactively and this type of icons are very necessary and are very scarce with the options that are available.

**Comment by WHK102** [comment]
Thaks.

**Comment by pklapperich** [comment]
I would also like to see this implemented. In my case, I'm mostly interested in font-awesome for imported Mermaid, but now that Mermaid can import to a diagram and not just a pre-rendered image, supporting font-awesome in imported mermaid might just be the same as supporting it everywhere.

At the very least, maybe font-awesome support in drawio could borrow the syntax from mermaid?

**Example:**

```
flowchart TD
    A[Christmas] -->|Get money| B(fa:fa-shopping-cart Go shopping)
    B --> C{Let me think}
    C -->|One| D[fa:fa-laptop Laptop]
    C -->|Two| E[fa:fa-mobile-phone iPhone]
    C -->|Three| F[fa:fa-car Car ]
```

Renders on [Mermaid.live](https://mermaid.live/) as:
![image](https://github.com/jgraph/drawio/assets/12666157/47d153a5-8468-4b6b-83d9-556fd7b3faf5)


But in drawio as:
![image](https://github.com/jgraph/drawio/assets/12666157/70223687-28e9-4f45-a1a2-c7dd301a4857)


It would be nice if the rendering in drawio included the icons and not the hint text.
