### ISSUE TITLE
Can't auth by google account.... after access right in google to drawio app

### ISSUE THREAD

**Issue by DarkNightHome** [jgraph/drawio#962]
### Preflight Checklist

* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
not auth in google account

**To Reproduce**
goto app.diagrams.net
choose open in google drive doc...
neet auth select google
enter google account and pass
give rights to app diagram.net....
see 401 error... not entered... 

**Expected behavior**
open chrome open google drive select open file in drawio and do auth and stuck

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop
 - OS: Windows 10
 - Browser Chrome
 - Version 

![Скриншот 05-06-2020 205335](https://user-images.githubusercontent.com/6933642/83907943-ecd75e80-a76e-11ea-8de0-2cba9a485851.png)

**Comment by xinatcg** [comment]
strange issue. I also get this issue on one of Google Account, but I try
1. another account, it works
2. incognito tab with this account, it works

I have tried to clean all Chrome data/ clean the cache storage of Google drive/ diagram.net, it should be totally clean on the chrome. but 401 still happen on the account.

**Comment by aisen0921** [comment]
Me too! But my error is a blank page.

**Comment by davidjgraph** [comment]
Clean cookies.

**Comment by xinatcg** [comment]
is it possible related to Google account type? the account which is not work is GSuite

**Comment by xinatcg** [comment]
> Clean cookies.

i have tried, actually, I clean everything I can clean on the Chrome

**Comment by xinatcg** [comment]
> Clean cookies.

![image](https://user-images.githubusercontent.com/55399567/84134847-19c29480-aa41-11ea-865e-d9963f14a381.png)


I think these cookies are what you mean if I am not wrong, I have tries lots of time

**Comment by davidjgraph** [comment]
No, it's the google domain cookies you need to clear, authenication is direct to google.

**Comment by xinatcg** [comment]
do you mean this?
![image](https://user-images.githubusercontent.com/55399567/84135808-50e57580-aa42-11ea-8f84-679ec9188c8a.png)

**Comment by xinatcg** [comment]
> No, it's the google domain cookies you need to clear, authenication is direct to google.

Or I need log out the google account from Chrome totally?

**Comment by xinatcg** [comment]
and I think the 401 error is the last step of Oauth right? `https://app.diagrams.net` use the token issued by Google to request the resource from google but Google refuses the request. 

I think the most possibility is some information is not match the register app on Google Cloud, is it possible based on the network flow to find out the exact reason?

![image](https://user-images.githubusercontent.com/55399567/84136136-c94c3680-aa42-11ea-89c6-9fc12c7e31d8.png)

**Comment by davidjgraph** [comment]
I don't know exactly which cookie is the problem, but if incognito works, clearing all cookies will fix the issue. If someone could work out exactly which cookie is causing the issue, that would be useful.

**Comment by xinatcg** [comment]
I think there should be some issue here. I create a new chrome user and log in my google. the first time I connect to google drive successfully. but after a period of time, I try to open a diagram from the drive and ask me to authorise again. then the same 401 error.

**Comment by davidjgraph** [comment]
That's with all browser extensions disabled?

**Comment by xinatcg** [comment]
oh no, do you mean some extension make this error?

**Comment by xinatcg** [comment]
![image](https://user-images.githubusercontent.com/55399567/84388216-19b2c800-abec-11ea-88ff-5c586eafafdd.png)

**Comment by davidjgraph** [comment]
The issue is originally about a complete failure of authenication, most likely caused by a cookie in a state that caused a problem. If you are seeing authenication timeout too quickly, that is likely another issue, please open another issue for it.

If it works incognito either an extension is causing the problem or a cookie. You need to clear cookies and switch off extensions one-by-one until the offending extension is found.

**Comment by rachelrlabare** [comment]
Hi - having the same issue. Cleared cookies, tried incognito and another browser and nothing has worked so far.

**Comment by xinatcg** [comment]
i use an extension session box to login make it works..

![image](https://user-images.githubusercontent.com/55399567/84433072-a6c64300-ac25-11ea-87a3-6c55add2e034.png)

**Comment by davidjgraph** [comment]
@rachelrlabare Could you open another issue please so we can look at your issue stand-alone, it's difficult with all the threads in this one.

**Comment by mtuzinskiy** [comment]
same issue here...

**Comment by davidjgraph** [comment]
If none of the solutions here fit, please open a new issue with details.

**Comment by Chazza011235** [comment]
I ran into the same problem as described by this ticket. After clicking the Authorize button and signing in, I got this generic error: ![ErrorAfterAuthorize_diagrams_net](https://user-images.githubusercontent.com/39905775/234930859-97ea6728-e982-4853-bd9e-891d51bdb5f6.PNG)
The user account I signed in with is managed by Google Workspace (formerly known as GSuite). After much trial and error, it turns out that the solution is to turn on setting "_Allow users to access Google Drive with the Drive SDK API_" to the "_Drive and Docs_" settings in Workspace. So you may need to speak nicely to your Workspace administrator.

**Comment by pkgainwell** [comment]
Today it worked for me when I turned off this extension verint.dpa.chrome.trigger 15.2.9.144
Not sure if that is the sole reason.
