### ISSUE TITLE
Using drawio in continious integration with docker 

### ISSUE THREAD

**Issue by robertselberg** [jgraph/drawio#963]
I was facing some problems when trying to configure gitlab-ci-runner to execute drawio from within a docker image where we generate documentation for our project. The problem was that drawio needed an X server and it had some other problems.

However, I solved it and this is how I did:

1. Download the latest drawio deb file. In this case it was draw.io-amd64-13.0.3.deb.

2. Write this to a file called: Dockerfile

    ADD draw.io-amd64-13.0.3.deb /
    RUN apt-get install -y xvfb
    RUN apt install -y /draw.io-amd64-13.0.3.deb && rm /draw.io-amd64-13.0.3.deb && rm /usr/bin/drawio
    ADD drawio /usr/bin/drawio

3. Write this to a file called: drawio

    #!/bin/bash

    if ! ps axu | grep -v grep | grep -q Xvfb; then
        Xvfb -screen 0 1024x768x16 &
        sleep 1
    fi

    DISPLAY=:0.0 /opt/draw.io/drawio $@ --no-sandbox

4. Build docker image and you're done.

Maybe you won't implement this in the drawio project, but putting it in the FAQ or something might help some people..

**Comment by nergiszaim** [comment]
I am getting this error ` /opt/draw.io/drawio: No such file or directory`
