### ISSUE TITLE
Cannot open local device files on iPad

### ISSUE THREAD

**Issue by my2iu** [jgraph/drawio#968]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Cannot open a local draw.io file when running in Mobile Safari on an iPad

**To Reproduce**
1. Start app
2. Click on 'Open Existing Diagram' to load a file from the local device
3. Choose a file from file picker
4. Page reloads itself and nothing is loaded

**Expected behavior**
Dialog box opens that asks you if you want to open in existing window or in a new window

**draw.io version (In the Help->About menu of the draw.io editor):**

- trunk branch on github as of today

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: iOS 13.5.1
 - Browser mobile safari

**Additional context**

In reference to #953 

https://github.com/jgraph/drawio/blob/b601c75cc98220e187e83f0797b01efadf06c6fe/src/main/webapp/js/diagramly/App.js#L3376-L3379

Reusing the file input like that and overwriting the input.type and input.value seems to be causing the page to crash in Mobile Safari. I imagine it's a bug in Mobile Safari, possibly a security bug.

I understand that you need to reset the input.type and input.value so that you can open the same file multiple times in other browsers, but to work around this Mobile Safari bug, you can just create a new file input each time:

```
// Resets input to force change event for same file
document.body.removeChild(input);
this.openFileInputElt = null;
```

I can confirm that this change fixes opening files on my iPad while also allowing the same file to be opened multiple times while still triggering a change event on normal Safari and Chrome.

**Comment by loganaaaflag** [comment]
We're having this same issue with regular file uploads using the `Arrange > Insert > Image > Open` on iOS 13.5 (iPad) as well.

**Comment by my2iu** [comment]
I’m able to open files in Safari using iOS 14, so I guess Apple must have fixed their bug and this workaround isn’t needed.
