### ISSUE TITLE
Export generates broken PNG

### ISSUE THREAD

**Issue by beachmachine** [jgraph/drawio#97]
When I export a drawing on draw.io as PNG, and select "Include a copy of my diagram", the mxGraphModel data is embedded in the PNG as zTXt chunk. Unfortunately the CRC checksum for this chunk is wrong, which prevents some image libraries from loading the image.

E.g. this happens when I try to load a draw.io via Python's image library:
```python
from PIL import Image
Image.open('draw-io-broken-image.png')
>>> IOError: cannot identify image file 'draw-io-broken-image.png'
```

You can also check via ImageMagick:
```bash
identify draw-io-broken-image.png
>>> draw-io-broken-image.png PNG 791x141 791x141+0+0 8-bit sRGB 5.15KB 0.000u 0:00.000
>>> identify: zTXt: CRC error `draw-io-broken-image.png' @ warning/png.c/MagickPNGWarningHandler/1656.
```

This is the image I used for testing:

![draw-io-broken-image](https://cloud.githubusercontent.com/assets/1974385/25169680/2a17b8ce-24e8-11e7-83b9-e5d18084767e.png)

**Comment by anx-ckreuzberger** [comment]
I had the same problem with draw.io images!

**Comment by alderg** [comment]
We've had a thorough at the function for the CRC in JS but didn't find a fix. The same code works in Java so we could use some help here, guys...

**Comment by alderg** [comment]
BTW: Quick workaround is to untick "Include a copy of my diagram".

**Comment by robertmoral** [comment]
Hi,
I have problem with label orientation after export graph into image. Do somebody know what is cause of problem pls?
I used mxCellRenderer.createBufferedImage with rotated vertexes. Label is displayed correctly but after export into image labels is not rotated.
I spent a lot of time but it seems like bug.

**Comment by ChristianKreuzberger** [comment]
Is this working yet, or why was this closed?

**Comment by davidjgraph** [comment]
I'm changing approach on handling issues. Basically, I want PRs rather than reports. Issues without a PR in A reasonable time will be closed.

**Comment by mig281** [comment]
@davidjgraph This is very disappointing:
1. Your users might not all be developers.
2. A year and a half later, the issue still exists and causes major issues for building documentation using draw.io-generated images.
3. It really sounds like what you're telling us is, "I'm not interested in fixing this. If you give me a fix, I'll merge it in." This seems diametrically opposed to the spirit of putting anything on GitHub.
:-1:

**Comment by davidjgraph** [comment]
We spent some time trying to fix this, we were unable.

@mig281 "I'm not interested in fixing this. If you give me a fix, I'll merge it in." is correct. What it sounds like you're telling me is I should work for free on whatever you deem important. Amazon is a big company, find a developer there to create a PR. To quote https://gist.github.com/richhickey/1563cddea1002958f96e7ba9519972d9:

"As a user of something open source you are not thereby entitled to anything at all. You are not entitled to contribute. You are not entitled to features. You are not entitled to the attention of others. You are not entitled to having value attached to your complaints. You are not entitled to this explanation."

However, I'm happy to reopen so it's understood that the issue is pending.

**Comment by davidjgraph** [comment]
@mig281 Additionally, this only applies when you insert the diagram into the PNG, in the private conversation we had you said you weren't doing this. So

1) Are you inserting the diagram data into the PNG?
2) If yes, don't. If the checksum is still wrong without the data, please provide a reproduction case.

**Comment by davidjgraph** [comment]
Re-tested, the CRC works correctly and has done since the PR mentioned was pulled. Most likely you're running a somewhat out of date version at Amazon @jpeddicord.

**Comment by jpeddicord** [comment]
Apologies for the noise. We're running 10.9.7 -- I'll see about getting that updated.

**Comment by davidjgraph** [comment]
That should be enough, you probably have a different problem, then.

**Comment by anx-ckreuzberger** [comment]
I just took a look at the draw.io Website and exported a picture as PNG (see attachment).

If I run
```bash
identify Untitled\ Diagram.png
```

I get this output:

```
Untitled Diagram.png PNG 1241x438 1241x438+0+0 8-bit sRGB 80.5KB 0.000u 0:00.009
identify-im6.q16: zTXt: incorrect header check `Untitled Diagram.png' @ warning/png.c/MagickPNGWarningHandler/1654.
```

This is different from the original `CRC error` posted by @beachmachine, so I guess the CRC Error has been fixed, but something might still be wrong with the headers.

(not complaining about this, just making sure it is documented)

![Untitled Diagram](https://user-images.githubusercontent.com/18396259/61768256-2d441d00-ade7-11e9-989a-08ea67a9d4d4.png)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by jinjamator** [comment]
FYI: this is not fixed, tested in 14.1.8 running on linux

**Comment by davidjgraph** [comment]
Please open a new issue for this. It might have been fixed and regressed, we do that via a new issue referencing this one just to keep things readable. Thanks.

**Comment by simonedlund** [comment]
Anyone who is interested in actually fixing this issue, please see the discussion in my CRC-fix PR:

https://github.com/jgraph/drawio/pull/394
