### ISSUE TITLE
Why aren't many shapes selected at once?

### ISSUE THREAD

**Issue by bd8036** [jgraph/drawio#970]
Hello

I'm using the Draw.io tool linked to Google Gsuite.
But I'm contacting you because there's a problem.

I'd like to drag several shapes with the mouse and choose one at a time.
When I drag some of the figures, they're all chosen.
But, When I drag many figures, they are not all chosen.
And when I try to move the shape, it doesn't move also.

When can this happen?
Please reply.

**Comment by ashrafteleb** [comment]
Can you explain with a video or screenshots?
