### ISSUE TITLE
Desktop drawio fails to start

### ISSUE THREAD

**Issue by medmedin2014** [jgraph/drawio#972]
I use the desktop version of draw.io but the app fails to start.
```
drawio-desktop: 13.0.3-2
Electron: v9.0.1
Operating System: Manjaro Linux 
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.70.0
Qt Version: 5.14.2
Kernel Version: 5.7.0-3-MANJARO
OS Type: 64-bit
```
![Screenshot_20200612_010429](https://user-images.githubusercontent.com/7027319/84450761-1ac61280-ac49-11ea-9a2b-55331db741e3.png)

**Comment by davidjgraph** [comment]
Could you check with 13.2.2 please?

**Comment by medmedin2014** [comment]
Today the new version 13.2.2 of drawio-desktop was pushed to Manjaro KDE stable branch and it seems to work without problems with the following config :

```
drawio-desktop: 13.2.2
Electron: v9.0.3
Operating System: Manjaro Linux 
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.70.0
Qt Version: 5.15.0
Kernel Version: 5.7.0-3-MANJARO
OS Type: 64-bit
```
