### ISSUE TITLE
Select-under is not working usefully

### ISSUE THREAD

**Issue by howff** [jgraph/drawio#976]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

The select-under feature (using the shift key while clicking) does not work.

**To Reproduce**

1. Create a rectangle
2. Put another rectangle on top
3. Put another rectangle on top
4. Very difficult to select the middle rectangle on a reasonably complex drawing and impossible to select the bottom rectangle at all 

**Expected behavior**
I would expect that selecting an object to be easy. Instead it is either difficult (requires precise timing of a 'double-click with shift') or impossible

**draw.io version (In the Help->About menu of the draw.io editor):**
13.2.2 and same on the diagram.net website

- draw.io version [e.g. 12.6.7]
13.2.2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chome
 - Version: 81

(I saw #64 which was closed, and it's true it's been partially implemented)

**Comment by alderg** [comment]
The modifier key for Select-under is Alt, not Shift. Where did you read that Shift should be used so we can correct that?

**Comment by howff** [comment]
I think you are bit premature closing this issue.  Firstly you haven't resolved the incorrect documentation. Secondly, you think I didn't already try Alt, Ctrl, Shift, and every combination thereof? It simply doesn't work, not in the browser and not in the app. Not for me anyway.

**Comment by alderg** [comment]
Where is the incorrect documentation please?
