### ISSUE TITLE
Cache / offline mode prevents files from being updated 

### ISSUE THREAD

**Issue by lamoquette** [jgraph/drawio#978]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I recently configured a gitlab integration and created an image with my settings so that I can export a diagram directly into a gitlab repo.

However, I noticed that when I pushed a new version of my image online, users don't always get the actual changes in their browser (probably because the application is cached). I also have this problem.

In private browsing, no problem.

I have however disabled offline mode and empty the caches, but only private browsing solves my problems.

Here's my PreConfig.js variables : 

`urlParams['mode'] = 'gitlab';
urlParams['browser'] = 1;
urlParams['ui'] = 'atlas';
urlParams['offline'] = 0;
urlParams['db'] = 0;
urlParams['od'] = 0;
urlParams['tr'] = 0;
urlParams['gh'] = 0;
urlParams['gapi'] = 0;
urlParams['gl'] = 1;
`

**draw.io version :**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**
 - OS: Mac Mojave
 - Browser : Chrome/Firefox

**Comment by alderg** [comment]
PWAs are updated when there are no more clients using the app. Check the list of Clients under Service Worker in the Application tab of the debugger.
