### ISSUE TITLE
Add column/row merging/splitting for tables

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#979]
Please do not comment "me too" or "+1", it just creates noise in the thread. If you wish to vote for this issue "thumbs up" this comment.

**Comment by mcmikecreations** [comment]
This would be great and very useful, right now tables feel half-finished without this feature,

**Comment by mcmikecreations** [comment]
Should this issue remain open?

**Comment by GerkinDev** [comment]
Hi,

#1650 suggests (just by the title) that there might be a non-GUI way to do so, but I can't find how. Any indications ?

**Comment by alderg** [comment]
No, there is currently no way to merge table cells.

**Comment by timblaktu** [comment]
I also would find this useful.

**Comment by cduerselenBX** [comment]
Also would love to have this feature!

**Comment by davidjgraph** [comment]
Please thumbs up the original post to vote for it. "Me too" comments are off-topic.

**Comment by ShamanthMurali** [comment]
Much needed feature... would love it too...

**Comment by lukaz914** [comment]
I would love to see this tool implemented too!

**Comment by davidjgraph** [comment]
Implemented in 16.2.2

Select multiple table cells (holding cmd on Mac or ctrl on Win) to form a rectangle and click merge in the arrange format panel.

Previously merged cells can be selected and unmerged in the same place.

In sketch mode:

https://user-images.githubusercontent.com/1761087/148213555-bb3a3ae9-3a86-431a-a7b6-1cefb13c731d.mp4

Any issues to new issue please.
