### ISSUE TITLE
Selecting multiple groups is impossible using shift click method.

### ISSUE THREAD

**Issue by NonLogicalDev** [jgraph/drawio#981]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Once the selection process started it is impossible to add groups to it by shift-clicking.

**To Reproduce**
1. Create a new diagram
2. Add Two shapes
3. Group them (Group A)
4. Select the Group A
5. Make a Copy (Group B)
6. Move a copy next to the first group
7. Select Group A by clicking on any element in the group
8. Attempt to select a second group by Shift-clicking an element Group B

**Expected behavior**
The Group B should get added to selection as a whole.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [13.2.4]

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [chrome/firefox]

**Additional Context**
So far it seems that the only way to select multiple groups would be to Mouse drag across all elements in all groups, then manually deselect all elements inside the groups leaving only the groups selected (Which proves difficult when you have 15 elements per group).

Alternatively, a fill or outline can be added to the group thus making it selectable on its own.

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.
