### ISSUE TITLE
Bash command glitch

### ISSUE THREAD

**Issue by fusillijerry89** [jgraph/drawio#982]
BASH: 'draw.io -x -f xml -o file.xml -x myfile.drawio'

Produces pdf output that looks like:

`%PDF-1.4
%����
1 0 obj
<</Creator (Mozilla/5.0 \(Macintosh; Intel Mac OS X 10_15_5\) AppleWebKit/537.36 \(KHTML, like Gecko\) draw.io/13.2.2 Chrome/83.0.4103.100 Electron/9.0.3 Safari/537.36)
/Producer (Skia/PDF m83)
/CreationDate (D:20200616140812+00'00')
/ModDate (D:20200616140812+00'00')>>
endobj
3 0 obj`

draw.io 13.2.2. MacOS 10.15.5

**Comment by davidjgraph** [comment]
Version? OS? Input file?

**Comment by fusillijerry89** [comment]
[test.drawio.zip](https://github.com/jgraph/drawio/files/4787096/test.drawio.zip)
