### ISSUE TITLE
Add different color support

### ISSUE THREAD

**Issue by edte** [jgraph/drawio#983]
Sometimes it is necessary to use different colors of tables and arrows. I have not found this function. Do you have any idea to implement this function?

**Comment by mararad** [comment]
Hi,

When you select e.g. arrow, there is a possibility to change its color in Format panel on the right > Style tab (as marked yellow in the attached image) Are you looking for this? If not, tell me diagrams.net version you are using (online, desktop etc.) and what exactly you would like to achieve
(you can send an example)

Thanks,

![arrow color](https://user-images.githubusercontent.com/44292306/85005487-26d63680-b159-11ea-9470-c1dc8425a8e6.PNG)

**Comment by edte** [comment]
Hello, sorry to disturb you, My English is poor, I use Google Translate, please forgive me

When there are too many arrows, it is difficult to distinguish, so I want to use different colors to distinguish them.
I am using online version 13.2.6
![](https://ae01.alicdn.com/kf/He87423d011224d25a5646da90cd352c4q.png)

I tried searching in the webpage, but I failed
![](https://ae02.alicdn.com/kf/Hab09ee6b3d1149a6a04a48f1e3815606j.png)

I didn't find the picture you posted, this interface
![](https://ae01.alicdn.com/kf/H3ef0dd1834864af4bbdeafcbc6c44ba9K.png)

When I use the chrome app, I found this interface.

This is a screenshot of the complete web page
![](https://ae02.alicdn.com/kf/H7276993bee674dcc8073781df9540b63I.png)

**Comment by edte** [comment]
Oh, I'm sorry, but I found its location, its location is not easy to find
![](https://img2020.cnblogs.com/blog/1823594/202006/1823594-20200621224237378-1254907653.png)
![](https://img2020.cnblogs.com/blog/1823594/202006/1823594-20200621224308241-817560668.png)
