### ISSUE TITLE
text element that scales with its container

### ISSUE THREAD

**Issue by masavini** [jgraph/drawio#984]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
the more a container element grows, the more i have to zoom out to see it all... until i find myself unable to read containers names. so i have to zoom in, increase the font size of the container label and start all over again...

**Describe the solution you'd like**
it would be nice to have a text element whose font size scales accordingly to its container size.

let's say you create a 200x200 container and you drop a 12pt label in it. if i grow the container to a 400x400 size, i'd like the label font size to be auto adjusted to 24pt.

in this way, big labels identify big containers (which often are the most important as well)...

**Describe alternatives you've considered**
another option could be having elements whose display size is fixed regardless of the zooming level, but i guess this could be harder to implement.

**Comment by mararad** [comment]
Hi, 

we already have a similar feature request here: https://trello.com/c/5S9cm4uZ/538-when-resizing-a-shape-resize-text-inside-a-shape so you can vote for it (I added your comment there) and track it

Regards,

**Comment by masavini** [comment]
thanks,
but trello says:

Card not found.
This card may be on a private board. If someone gave you this link,
they may need to invite you to one of their boards or teams.

regards,
matteo

**Comment by mararad** [comment]
No worries, your feature request will be kept here (not on Trello) so you can track the progress here.

Regards,

**Comment by davidjgraph** [comment]
Closing due to lack of interest from core team.

**Comment by pfleer** [comment]
I'm keen to see this feature implemented as it seems at odds with the rest of the objects which scale perfectly.
