### ISSUE TITLE
More table connector points (ports?)

### ISSUE THREAD

**Issue by thomasetter** [jgraph/drawio#987]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
When trying to use draw.io for visualizing data structures, I often would like to use tables to represent arrays/blocks of memory.
However I cannot add connectors in the way I would like:
![image](https://user-images.githubusercontent.com/422775/84763612-c619f300-afcc-11ea-8c26-79b1802ceb30.png)
I have marked the predefined connection points.

Only the center points of the left/right borders of the row are available in the current release.

**Describe the solution you'd like**
I think it would be more intuitive to have at least these points available:
![image](https://user-images.githubusercontent.com/422775/84763509-9bc83580-afcc-11ea-8dc9-faebe7f9954e.png)
This is essentially center-points and corners for each cell.
For corners, it might be necessary for a user friendly solution to expose the ability to switch the orientation of the incoming/outgoing connector in 90 or 45 degrees or even smaller steps.
This might be a useful addition for all connectors in general.

**Describe alternatives you've considered**
Using boxes for each cell works if there are no changes in geometry as then there are the 0%, 25%, 50%, 75%, 100% points for each side.
However for the corner points, I could not find a way to specify the arrow direction besides adding waypoints, which is a completely different intent and therefore does not get transformed well through any repositioning/resizing.

**Comment by davidjgraph** [comment]
Try pressing and holding alt (option) anywhere inside the shape to connect at the drop position.

**Comment by thomasetter** [comment]
> Try pressing and holding alt (option) anywhere inside the shape to connect at the drop position.

There are several problems with that, one of the most annoying (IMO) is that if I modify the table, e.g. by inserting or resizing a row/column, generally I have to change the connectors again.
