### ISSUE TITLE
Diagrams don't work in Confluence in Firefox

### ISSUE THREAD

**Issue by mchudinov** [jgraph/drawio#988]
Diagrams can not be load in Confluence in Atlassian cloud in Firefox.
I use the latest version of Firefox.
Instead of any diagram the message is shown "App is not responding. Wait or cancel?".

**Comment by davidjgraph** [comment]
Do you have an ad blocker blocking access to the domain the app is loaded on?

**Comment by mchudinov** [comment]
Exactly, it is so called "Privacy Badger" plugin that blocks draw.io diagrams. Thank you!
