### ISSUE TITLE
HTML label not in the good place in embed mode since v13

### ISSUE THREAD

**Issue by algenty** [jgraph/drawio#989]
Hi,

I already wrote  an issue about this at 
https://github.com/jgraph/drawio/issues/940

Without news, i had investigate and i found a solution.
In mxSvgCanvas2D.js function updateTextNodes 
i replaced :
'display: flex; **align-items**: unsafe ' +
By 
'display: flex; **align-self**: unsafe ' +

Before with align-items
![image](https://user-images.githubusercontent.com/47012725/85025492-c0acdc00-b177-11ea-871e-9737fd23657c.png)

After with align-self : 
![image](https://user-images.githubusercontent.com/47012725/85019842-bab2fd00-b16f-11ea-9f6f-32597ba78723.png)

BR,
Arnaud

**Comment by alderg** [comment]
Thanks for this. It seems to break one of our test cases. We need to understand why this breaks your output in #940 in the first place, maybe the container affects the output. Can you provide a standalone example that reproduces this problem?

**Comment by algenty** [comment]
I have create an example of bug on 
https://play.grafana.org/d/NpjdeVWGz/flowcharting-bug-draw-io-940?orgId=1
I think you know the used template.

PS : You can found other examples of flowcharting with drawio at
https://play.grafana.org/d/Unu5JcjWk/flowcharting-index?orgId=1 

Thx again for draw.io

**Comment by algenty** [comment]
To change align-items by align-self is not the solution, it generates others problems
![image](https://user-images.githubusercontent.com/47012725/85060156-0c29af00-b1a5-11ea-81c4-1642ccd8559f.png)

With mxgraph 4.0.0 align-items doesn't exist,

**Comment by alderg** [comment]
![Screenshot 2020-06-19 at 06 48 45](https://user-images.githubusercontent.com/921200/85097815-052c8c00-b1f9-11ea-9efb-cce4c0f13e81.png)
This CSS style seems to be causing the problem on the first DIV in the foreignObject.

**Comment by algenty** [comment]
You're right !
I can't modify this css because i'm not the owner but if i add 
-webkit-box-sizing : content-box 
on my parent div, it works !! Thx a lot

thx for your investigation
You are a chef !
