### ISSUE TITLE
Export to vsdx switched edge label orientation

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#990]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Exporting diagram to .vsdx causes orientation of edge labels to switch direction.

**To Reproduce**
1. Open [this example](https://app.diagrams.net/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1#R7Vtdc7I6F%2F01nTnnoh2%2BRLwUv63aqq3a3iFEiASCEFH89W%2BiUEFpn%2FrWep521A7CStiEsNfK3iG9ESvOuuFrntXFBkA3Amesb8TqjSDwiszRH4ZEMcJLMWL60IixPTCEGxCDSbUlNECQqUgwRgR6WVDHrgt0ksE038erbLUZRtmrepoJjoChrqFjdAwNYu1QRSju8SaAppVcmZdLuxJHSyrHdxJYmoFXKUis3YgVH2Oy23PWFYBY7yX9Ep8XamgZN2b7V3%2BnutIYVqrcuKY3u%2BX7CqqLzVLrls%2B3QdvtA5ekr3OSWeHIbFubo3BthMZZ7Is5zZYRtafOMDVLO5NE8ROSF0ucFNwGW%2F8p87y3TqCZ5kBEva9c0RCc%2BpDiOkbYp8iNIHLbD8UM6FP3gdilOCK0VEWAEODfBp6mQ9ekMLc1iqALbq34kZd5dncFCmNWjbDr8Ps20T2T%2FTbZIXUJw5pHNvNCbW0TY5rc09RPKiYI7a7djSawkLlnIQQ%2BgdRJywiatMVVBxoGK1O1GNBp7wN2F2FgrFtVivCsQyBCld3NUyvijGNfipu%2BZkB6Rrps%2B0mVVfcdVHWxz5xbpS7tsRYFBLg6RP%2BQUWdQDVpm9XGlNW27%2F7LsFN3Hkjrp6HwLruribCr2PWvtlLrNWqkkhyDgB0JjodyLS7PmWuWi3SnVYR0t7Lm9bpOK1LdGdjR6Usd8S5i3xHE00jXw1EWjicEpD%2F2C%2FNTCfKs71qTa2pkFRDPdsf04KY61jdeYo2GpJ4VCjcgCaPf0KrClpdyqPnTmcL7o15hW1aua3HilPawOZBMIJBx46hSISlt5aFJfrlstq76gvxt%2BbHXDUNYnBaVIwvbkGTxX%2F2V9QHxsg1TPSRz77npnR3jW9bEbPWGPArcpRMWEYOcA7IAZOYAGschsMaRNAVI13TZ9vHSN5OoudpkTbDHA%2BMWaYREHxY1YWZCAIbXHHtqKKvabb6X5%2BiHjqeOBRN3fRIzKP8AOIH5Eq8SlkhLrV6z8YqJnq72M8lyMWSkJTQYILVZu8830XkXoTiwkJ4iK9I4WpnmVsEW4AFueNyOhExRanZo16lE%2F7kD3fsNJZMOtvGhU5g1U47uB3404k0RwpQZo2JuMxj3XeIwg33mCtBfaHYVvmXSn1a7ZNdy%2Fp%2FpHfboxqKjPw1n5GTbt5xqyGvq9NPXU0cOrXYANr1cbjaANEO43X73gnntB486G75tUEdVmnXQjvVkzWy19OVdXqF9R7%2FX1Qipfvf0Db5cLGW%2BXEudKe7uY4%2B00YPgmdy%2F8rjH0eLB88p35AjqsQxcO8tlOuGSj6yKasfubLtijhisw9VjRjG2MgHW1Z2E7mId0dxGuVyzKNBEbl40lqzQMCMN8rK%2Fd5Y1Yf3%2BYPn3gpu5E0qPyoc7EPn0oMQdwrrpkmBmf8DNI%2BfloJmvrk2SWTiUzz90pYobOvHRXyBm9lDtRPKa0UvwmRsu%2Fi9GVhb8IGNPgEnir0GXPEgFGUFpDc5hn7LYUcb0pDD0SLiBjbehZ4KLBs3iBcMB9VTtVXDartcEjtxGHrWgOVtzweWAOqU21syzZ3Vc86VirXumBAmRpl5Hf89omP9xUm1J%2FTG%2Bc1u69mK9P9rwsPdur9rPZmNDHJKhydcJvOjMHR44xwXxxbRU2zqAt9yVBHVdmuoDbM6NM%2B1J9oT2slh9LlWnxoS02qVGh3eCbvcaG7iqSjZ6sx1FFpy2%2FBgQfBASFYkZBZEk%2BEpBiTjxQKHyTeBR%2Fl3jcm8ZFFUC%2Bps%2FX9PmC%2BiHKckY%2FinyOfsjH%2BiF%2BV%2FasnJA9K9fs%2BZo9n%2BTs2bmiQjEne86bK5K%2Fy9tLv2u0rNsWBus5S3gtulk6KDTAh6ntqYnsIeWviez5E1nlVF7t89NkFMlJYxUxN4uVvisQ5fPea%2F1gblUNhwCNzTvpG4Smcz83gYUAhZ7O5qhcm4WuOVVCgJfL1cxHiM1XuYa2uuwLIu6a5F6T3JP0RTh4x%2FPZJFcWv0tbjt93j0MjosYX8%2BNO%2BD9eTPPHb75%2FtHg96OYXROZNOtj8GDBMMIwLk1GbaD4ps1UYewy4RoLoSAsCqCcV48UfhV2l1NEH9EszjsshHHfEN%2B6YbtxHQ3eKWu8wMq2FWVoeiS1YQzJhhXeF%2BOglts32q%2Bv4vO1BlDp4BD6kTsxs7DCXsiVliB2%2BpMv2prZHUfro0Ngn1SHhVoCXvg4%2BqBiTmz5SE3xiXp75zYdi4wOkERhmF%2BTkSUd86iOGWya%2BzeZnz8CzWUDblaI%2B9UctStXwmIHgSIzemvQFffplC1vG8%2BUZ5EO6qsdp6pHSjr2S%2FBL1kD6pHspl1EPIRji3hxZOUZP8K0h89hLJwpm99OwsnleI8hbD%2FGAhalrROeIY%2FqpEVyU6UJg%2FKlHC3%2B%2BWotuzS4%2FIZ1ctyZxwAenJW5j0LiOFKyPzGPlOInHH8QWlKO63X2Bkho93BTH7%2BRsImhDvjwwt%2FhaCFsVLEPSXrTMqz88QGhSuOnRSZJDMaXw5MuD%2Ffh36bMpyIRkSshkLX1LOLUsyl13cdJCy%2FLH%2BZWQsb8XTe%2FQuXul9WpihpL%2B%2Fmt3yX8LuM844lIT%2FgI55C4h%2BcFTR984QVZSusvPfRBU%2Feb5B%2FmaheQsczh02HOrOF6cb6OH%2Bv6d31ff%2FhC7W%2Fgc%3D)
2. File->Export to->vsdx
3. Open the resulting vsdx back in app or .vsdx viewer.

**draw.io version (In the Help->About menu of the draw.io editor):**

- 13.2.6

**Desktop (please complete the following information):**
- FF 77 MacOS 10.5

**Comment by ashrafteleb** [comment]
Fixed
