### ISSUE TITLE
Issues with offline mode not loading

### ISSUE THREAD

**Issue by loganaaaflag** [jgraph/drawio#991]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Hi! I'm having problems getting the application to work offline. When offline, the app doesn't load for me at all.

**To Reproduce**
1. Load [app.diagrams.net](https://app.diagrams.net/index.html?offline=1) with the `offline=1` url param.
2. Disable your network connection
3. Refresh the page

**Expected behavior**
The app functions as normal, with some functionality removed.

**Screenshots**

Screenshot showing the service worker has been registered.
![image](https://user-images.githubusercontent.com/55156743/85060675-7d904000-b15a-11ea-9cc1-5093100be4a6.png)

Contents of the service worker
![image](https://user-images.githubusercontent.com/55156743/85060765-9dbfff00-b15a-11ea-8126-1938437ad670.png)

Screenshot of the network tab in chrome dev tools when reloading offline.
![image](https://user-images.githubusercontent.com/55156743/85062780-f0e78100-b15d-11ea-86f2-9462ae421973.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- diagrams.net 13.2.6

**Desktop (please complete the following information):**
Chrome@83.0.4103.106 (Official Build) (64-bit)
Firefox@78.0b8 (64-bit)
Windows 10 Pro v2004

**Smartphone (please complete the following information):**
N/A

**Additional context**
It also doesn't work removing the `offline=1` url param

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by loganaaaflag** [comment]
Thanks!
