### ISSUE TITLE
Add and share new libraries into draw.io

### ISSUE THREAD

**Issue by McCorner4** [jgraph/drawio#995]
Hi there
I am a newbie in Draw.io. I am trying to add and share a custom library. I have followed the procedure as stated in  https://github.com/jgraph/drawio-libs. However, I cannot find the raw URL path for the .XML file I already uploaded. 
I would appreciate any help

Thank you

**Comment by mararad** [comment]
So you uploaded a library to GitHub repository and you are not able to find raw URL path. If you click “Raw“ as shown in the example attachment below, what URL do you see in address bar, please? Does it start with “https://raw.githubusercontent.com/….“?

![raw link](https://user-images.githubusercontent.com/44292306/85267677-d707b000-b475-11ea-95c4-3f796fb036a7.PNG)
![raw](https://user-images.githubusercontent.com/44292306/85267680-d7a04680-b475-11ea-83d3-d3e28c6ca187.PNG)

**Comment by mararad** [comment]
Info: solved in ticket DID-347
