### ISSUE TITLE
Rows in the ER section are not selectable but available through "More Shapes"

### ISSUE THREAD

**Issue by flickojo** [jgraph/drawio#997]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**
1. Go to 'More Shapes'
2. Click on 'Entity Relation'
3. Notice the rows option.
4. Go to "Entity Relation" on side panel
5. Notice error.

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: NA
 - Version 13.2.4

**Smartphone (please complete the following information):**

**Additional context**
![Untitled](https://user-images.githubusercontent.com/59069703/85411297-26adb080-b536-11ea-80e2-855b24561bfb.png)
![Untitled (1)](https://user-images.githubusercontent.com/59069703/85411318-31684580-b536-11ea-9468-53140ae6d14f.png)

**Comment by flickojo** [comment]
![Untitled (1)](https://user-images.githubusercontent.com/59069703/85411048-dc2c3400-b535-11ea-9ac6-c0d79d24ec30.png)
![Untitled](https://user-images.githubusercontent.com/59069703/85411049-dc2c3400-b535-11ea-8ed8-fcc2abfc60c9.png)

**Comment by mararad** [comment]
Some shapes are missing (some of them are marked yellow) in "More shapes" and when added to sidebar (diagrams.net online 13.3.1 and desktop 13.2.4 and 13.3.1)
![some differences](https://user-images.githubusercontent.com/44292306/85528902-cb022680-b60c-11ea-8064-c3a73b1d57f7.PNG)
.4.

**Comment by egrimate** [comment]
Will be fixed in next release.
