### ISSUE TITLE
Dynamic action for sliders

### ISSUE THREAD

**Issue by plumcloth** [jgraph/drawio#998]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I would like to use a slider to represent a timeline, and have the diagram (layers) change depending on the position of the slider handle.

**Describe the solution you'd like**
I've seen and used [interactive diagrams with custom links and actions](https://drawio-app.com/interactive-diagrams-with-custom-links-and-actions/) and would like to be able to do similar for a slider based on the value of the slider handle. For example, if my slider represents the last 10 months, then when the slider handle is at 10, my custom action could show layer 1; then when the slider handle is moved to 20, my custom action could hide layer 1 and show layer 2; etc.

**Describe alternatives you've considered**
I could achieve similar using a series of buttons, where each button represents a month, and clicking on a button shows/hides the required layers.

**Additional context**
I like draw.io a lot, but a weakness, in my opinion, is the focus on static diagrams, and the small amount of features for creating dynamic content which is far more engaging for the user.

**Comment by edte** [comment]
agree

**Comment by plumcloth** [comment]
Hi @davidjgraph - can you help me understand why this is declined please ? Is it a dupe ? Wrong place to ask ? etc. ? Thanks.

**Comment by davidjgraph** [comment]
It's declined by the core team, meaning none of us wish to implement the functionality. It's left open as an issue in case any member of the community wishes to implement it.
