### ISSUE TITLE
Restore Comic style

### ISSUE THREAD

**Issue by nedmech** [jgraph/drawio#999]
* [X ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I went to open some of my pre-existing drawings thru the web app today, and they connectors now have a completely different look than when I first drew them. The new Rough style seems to have overridden the previous Comic style. The Rough style is not as visually appealing for my use case as the Comic style was, and some of the connectors now look like double-lines instead of single.

**Describe the solution you'd like**
Please implement Rough and Comic as separately selectable styles instead of overriding Comic with Rough.

**Describe alternatives you've considered**
My only recourse right now is to revert all my pre-existing drawings that used to use Comic to now use the basic standard undecorated style. That's a lot of work for some of my drawings that have a huge number of connections and elements using the Comic style.

**Additional context**
Example content
Original Comic style:
![Original Comic 2020-06-23 152040](https://user-images.githubusercontent.com/792497/85471451-545e1e00-b565-11ea-8567-371b4b20fc98.png)

New Rough style:
![Rough 2020-06-23 152106](https://user-images.githubusercontent.com/792497/85471457-5627e180-b565-11ea-9ceb-723f4d5ee966.png)

Edit:
I have found where a selection for Rough style can be set between Default and Legacy. The Legacy mode displays the Comic style I am expecting, but that is still not an acceptable solution. I would still have to go into the extended properties of EVERY connector in my drawing and change the Rough Style property from Default to Legacy. A more elegant solution is still to implement Rough and Comic as completely separate styles so pre-existing Comic-styled drawings don't completely change how they look just because the Rough style is now available.

**Comment by alderg** [comment]
Fixed in 13.3.2 and using a separate name for the new style.

**Comment by nedmech** [comment]
Thanks for the quick turnaround, @alderg ! I would've liked to have seen an easier way to get to the Comic style setting instead of it being buried in the extended properties fields, but this solution meets the need of not having to change any of my existing drawings in order to keep the same graphical look they were created with. I appreciate the support! Thanks again.
